### ISSUE TITLE
MQTT / Java 8 Issue

### ISSUE THREAD

**Issue by sijones** [bwssytems/ha-bridge#1001]
I have everything working but as soon as I configure the MQTT connection it seems to crash the bridge, the main thing that i see in the logs is:

WARNING: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
java[2703]: Sep 19, 2018 7:09:07 PM com.fasterxml.jackson.databind.ext.Java7Support <clinit>

Java version:
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

**Comment by bwssytems** [comment]
Will take a look.

**Comment by bwssytems** [comment]
I will update to version 1.2.0 of the library, but that may not help. If there are still issues, you may need to run ha-bridge with Java7 to support the mqtt library.
