### ISSUE TITLE
Another case of alexa no longer discovering ha-bridge devices..

### ISSUE THREAD

**Issue by whatsalinux** [bwssytems/ha-bridge#1002]
Part of me wonders if Alexa is going the route google did of requiring a meethue login, but there's enough weirdness in what I'm able to monitor and log that I might be missing something dumb.  So my setup - 

I've ru ha-bridge since the echodot came out, maybe two years now?  Part of that time I was building the jar and running it on ubuntu xenial, on port 8081, UDP port default 1900, response 50000 .  IP always static.  A few months ago I moved to using the docker image, on my NAS - worked just as well there.  Then last week I tried to add two new items to ha-bridge, and alexa just wouldn't discover them.  They were showing up in the habridge api xml just fine.  After turning on the habridge upnp and huemulator debug logs I could see my echo dots (have two) requesting the description xml/ lights list, but it never added anything.  

I tried removing one of the existing "devices" in the alexa app that was served by ha-bridge, wondering if I'd just misconfigured the new items i was trying to add, just to see if alexa would rediscover the "old" device.  It did not.  Having added and removed a number of devices to habridge over the years, I noticed my "ID" numbers in habridge were getting into the 50's, and wondered if I was hitting some kind of limit, so I hit the "renumber devices" button and rescanned.  Again it would not find my new, or the old removed device.  But I noticed that because of the change in numbering at ha-bridge, triggering a device in alexa now ran a different command in habridge, corresponding to what its old ID had been.  As another test I maneuvered the "new" habridge item into the ID position of an old item that was still mapped in alexa, and triggered it.  It ran fine, so I knew it wasn't a formatting issue in my new item.  

I'd experienced alexa refusing to find new items, mostly in the months after I got my dots - often I'd have to clean out the devices and start from scratch as others have noted.  Having seen it fail to re-add the one old skill I'd removed I was worried that clearing out alexa's memory might lead to losing all of the existing ones for good - and that's what happened.  I have an ecobee and a harmony hub, and it finds those fine after removing them.  

Other things I've tried, without success: 
* going down to a single item in habridge
* changing the hue firmware field in habridge to older hue bridge v1 firmwares.  And a v2 or two.  
* Adding the mac of a real V1 habridge in the mac emulation field (I don't have a real hue bridge yet)
* proxying habridge gui via apache as per guide, to port 80.  
* setting a local DNS alt name of philips-hue for the host running ha-bridge
* ensured IGMP was not enabled at pfsense router or the apple airports that provide wifi
* Tried older versions of habridge (including the 5.2.2 branch)
* tried changing gui, udp, and response ports
* tried using the "link" auth method in habridge when scanning. 
* tried going back from the docker image to a jar running on the ubuntu box (which is now bionic), and a raspberry pi

When scanning, I try each of triggering from the alexa app, the alexa website @ amazon, and vocally "discover devices". 

At some point soon after clearing out my alexa devices, I stopped seeing my echo dots interacting with the habridge via debug logs.  To make sure UPNP was actually working on my network, I enabled the UPNP server and listener in Kodi on the Ubuntu box.  As soon as I turn that on I see activity from kodi's IP in the habridge debug logs.  When I trigger alexa discovery, I'll quickly see more habridge debug log activity from the kodi box, passing along an M-search.  But I'm still not seeing any communication between the ha-bridge and the echodots directly, no matter where I run habridge, and no matter what combination of settings I use.  

Out of ideas, I went another route. 
Finding a cheap google home mini for sale, and noting the old ghome apk workaround on the wiki to add habridge, I ordered one, and installed the correct APK.  I guess that workaround is broken, because rather than pairing with the habridge, it takes me to the meethue webpage to login.  

The last thing I can think to try is to integrate an actual v1 hue bridge.  They're DIRT cheap now, under $10, so I'm waiting for that to show up to see if alexa finds it, and if I might be able to then sneak habridge in front of it (will I have any means to set the actual serial number of the hue bridge in habridge, or is that generated randomly and automatically?)

**Comment by sijones** [comment]
I found clearing all devices in Alexa and then a upnp delay of 250 worked perfect.

**Comment by whatsalinux** [comment]
Gave that a shot, sadly no change.  It found only the ecobee device.  
Does offer some hope if other people have habridge still working.

**Comment by whatsalinux** [comment]
Ok I got it - some multicast or UPNP  issue present between my wifi network and my ethernet network subnets that wasn't a problem historically, seems to be now.  I set up a raspi hosting a habridge jar on my wifi net, and alexa found habridge fine.  

glad to have it working again! thanks for the help!
