### ISSUE TITLE
Problem Running PowerShell Script

### ISSUE THREAD

**Issue by tracehae** [bwssytems/ha-bridge#1005]
I have read through all the other links and tried everything but still can not get my powershell scripts to run.

This is one of many things I tried.  When I execute it says  Request Executed: Success …..

 [{"item":"powershell.exe c:\powershellscripts\opengarage.ps1"}]

It runs at the command prompt perfectly.  Any ideas would be appreciated.

**Comment by bwssytems** [comment]
I'm not a powershell expert, but thinking of things to check. Do you need any privileges? (the ha-bridge process may not have them) Do you need a full path to the powershell.exe?

**Comment by tracehae** [comment]
Actually, I tried running the example in the on-line documentation for starting notepad.exe and it didn't work either.  I did the code below.  I also tried doing many other simple executions and nothing worked.  Is there something I'm missing?  I have tried both interfaces also unsuccessfully.

code from your on-line documentation for notepad.exe.
[{"item":"exec://notepad.exe","type":"cmdDevice"}]

**Comment by tracehae** [comment]
Any ideas on why the notepad example does not work?  Is there something I'm missing?

**Comment by bwssytems** [comment]
Most likely that you need to provide the full path to your executable. i.e. C:\Program Files\Windows\Notepad.exe for example (that may not be the correct path...)
