### ISSUE TITLE
Alexa detects sockets as lights

### ISSUE THREAD

**Issue by derekoharrow** [bwssytems/ha-bridge#1006]
First off, I love HA-Bridge - I use it to provide Alexa voice control of my Domoticz setup.

One small niggle - I have several domoticz sockets setup in HA Bridge, but Alexa detects these as lights and you can't change that from the Alexa app.

Is there any way for HA Bridge to identify these as sockets to Alexa at all, or is that a Hue constraint?

Thanks

**Comment by bwssytems** [comment]
Since ha-bridge is using the philips hue bridge emulation, it returns all items as lights.

**Comment by sOckhamSter** [comment]
Is there any way for an 'Alexa mode' option to be created within HA Bridge, one that breaks strict compatibility with emulating Philips Hue and passes on the device type to Alexa during discovery? This would make HA Bridge so much more useful as a bridge between Domoticz (or any other controller) and Alexa.

**Comment by derekoharrow** [comment]
And... Hue does now support far more than just lights - it supports switches, sensors, sockets, etc.

A normal Hue bridge will report these to Alexa as the correct type (e.g. Scenes), whereas HA-Bridge doesn't afaik.

**Comment by bwssytems** [comment]
I would have to research how the hue hub returns the new items within it's API.

**Comment by g1r1** [comment]
Any progress on this?

This is particularly a problem when all devices are considered lights and they are in smart groups. So if you say "Switch on Light" it switches all devices on put inside that smart group.

**Comment by bwssytems** [comment]
The ha-bridge has not implemented scenes or groups or rules or sensors as it is mainly to handle turning on items and that is through the lights api. This is defined in the hue API from Philips. if there are other advanced items that are being used such as the type field of the device and scenes. It is not available currently in the ha-bridge.

**Comment by bwssytems** [comment]
Included in community information https://github.com/bwssytems/ha-bridge/wiki/Informational-Items-Collected-from-the-Community#q-alexa-detects-sockets-as-lights
