### ISSUE TITLE
Alexa is no longer discovering any bridge devices.

### ISSUE THREAD

**Issue by jjlink** [bwssytems/ha-bridge#101]
All of a sudden Alexa is no longer discovering any bridge devices. Can you suggest how to figure out whats wrong? I can test the current bridge devices on the web interface and they work fine; its just Alexa that no longer sees them

**Comment by bwssytems** [comment]
What version of the bridge are you running?

**Comment by jjlink** [comment]
v2.0.3. It turned out it had the wrong UPNP IP Address. So the issues is resolved. Thanks
