### ISSUE TITLE
mapping Spark for Accept: [*/*]

### ISSUE THREAD

**Issue by eimarfandino** [bwssytems/ha-bridge#1010]
i have added the bulb via http, the on and off button are working on the ui but once opening the hue app and creating a room i get the following error:
```
The requested route [/api/51eac991c7e54de7971ce1229ac660a3/scenes/1/lightstates/1] has not been mapped in Spark for Accept: [*/*]
```

any ideas?

**Comment by bwssytems** [comment]
Interesting, will take a look at the api setup in ha-bridge.

**Comment by eimarfandino** [comment]
ok thanks @bwssytems

**Comment by fti7** [comment]
Same here. Room creation returns Error "cannot save"

**Comment by bwssytems** [comment]
So that method is not supported in the ha-bridge and was not intended to be. I do not emulate the full api, only what needs to be handled for alexa.

**Comment by eimarfandino** [comment]
does that mean we can ignore that error message @bwssytems ?

**Comment by bwssytems** [comment]
You can ignore it as is just an informational output message.

**Comment by eimarfandino** [comment]
@bwssytems i would like to ignore it but in the hue app i cant save the room due to this error

**Comment by bwssytems** [comment]
So as my previous response says, it is not implemented so the ha-bridge will not work with that hue app if you use rooms, groups or scenes.

**Comment by ozett** [comment]
i got the same error.
i am only using ha-bridge with alexa.
but i configured multi-room setup for alexa.
does this error mean that there are some functions not available,
or is the error still to ignore? as stated?

thanx

**Comment by bwssytems** [comment]
Rooms are not supported with ha-bridge

**Comment by bwssytems** [comment]
This has been added to the commnity information https://github.com/bwssytems/ha-bridge/wiki/Informational-Items-Collected-from-the-Community#q-mapping-spark-for-accept-
