### ISSUE TITLE
tuya smart devices?

### ISSUE THREAD

**Issue by SpoddyCoder** [bwssytems/ha-bridge#1011]
I've had good initial success wiring up the ha-bridge to run a wakeonlan command to turn on a pc :)

Now looking to get control over some cheapo Chinese smart plugs and bulbs we have around the house... they use the tuya smart app (or smart life). Couldn't find anything in the issue forum or the docs about these...

https://www.amazon.co.uk/gp/product/B07BS5B7QV/
https://www.amazon.co.uk/gp/product/B0796MX6DP/

There looks to be a well maintained gihub lib here to control these...

https://github.com/codetheweb/tuyapi

My intention was to get ha-bridge to run a custom script that then uses the tuyapi lib to interact with the smart devices. Best/only way to go atm? Or can these be natively controlled from within the ha-bridge?

Thanks.

**Comment by bwssytems** [comment]
Currently the ha-bridge does not support his api. Could integrate it in the future as it similar to some of the other APIs that are supported. If you are chomping at the bit to use it, I would suggest the python library https://github.com/clach04/python-tuya as this will be much more useful by using python scripts.
