### ISSUE TITLE
Cant set dim to 1

### ISSUE THREAD

**Issue by Blacksus90** [bwssytems/ha-bridge#1013]
Hey,
I have an issue with the dimming. I have multiple scripts on the rpi that is running my habridge. They are named HDMI1.sh, HDMI2.sh, HDMI3.sh...so the command I run in the dimmer is execute command/script/programm with /home/pi/IR/HDMI${intensity.percent}.sh. This works perfectly fine via the test dim button in ha bridge. Setting it to 1 runs HDMI1.sh. However, when trying it with alexa, 1 somehow defaults to 2, both via voice command and in the alexa app. 2, 3 and 4 work perfectly as intended and run the given script, only setting it to 1 doesnt work.

Am I doing anything wrong or is alexa just incapable of setting things to 1%?

**Comment by bwssytems** [comment]
Just to make sure on the rounding, I put in code to check if the raw is greater than 0 and less than 5 out of 254, that it should be 1%.
