### ISSUE TITLE
PUT http://host:port/api/devices/<id> did not work

### ISSUE THREAD

**Issue by sissiwup** [bwssytems/ha-bridge#1014]
Updating creates a new device:
When id is not valid, an error comes.
When the id exists anew device is created.

**Comment by BetoRn** [comment]
i've noticed this too, recently updated from versión 4 to 5 and a couple devices that I updated via the API stopped working

**Comment by sissiwup** [comment]
I had a look at the code. You can bypass by putting the id in the params for updates.
id: 1234,
name: ....

**Comment by bwssytems** [comment]
So, I assume you are not sending the "id" tag in the json structure which will cause your issue. Put in "id":"XX" and it will work.
