### ISSUE TITLE
V5.2.2 Release Candidate Testing

### ISSUE THREAD

**Issue by bwssytems** [bwssytems/ha-bridge#1017]
Release Candidate V3 out. Only updated the connection retry on the current XMPP harmony hub communication. No new api was put in for the harmony.

https://github.com/bwssytems/ha-bridge/releases/download/v5.2.2RC3

Please verify results and post here.

v5.2.2
Bug fixes found through issues
 
#923 HABridge sometimes executes both "on" and "dim" command enhancement question
#927 Added quotes around strings in json response for huemulator
#944 Binding to all IP addresses bug question
#945 Harmony activities not working after restarting hub enhancement question
#970 wrong IP address from habridge bug question
#980 UPnP listen by interface rather than address? Or listen on 0.0.0.0? bug question
#992 Domoticz discovery fails when using https without any credentials enhancement question
#1001 MQTT / Java 8 Issue question
#1013 Cant set dim to 1 enhancement question

**Comment by bwssytems** [comment]
@toms001 what release were you using previously?

**Comment by toms001** [comment]
5.2.1 / aptalca / docker-image

**Comment by bwssytems** [comment]
@toms001 assuming you are still using docker here. I will need to check how the new changes play with docker's IP handling.

**Comment by bwssytems** [comment]
@toms001 Confirmed, not a docker issue but a code issue. Thanks for testing, new RC2 soon.

**Comment by DrMichael** [comment]
I get a java.lang.Error:

Nov 15 15:24:41 raspi2 java[17147]: java.lang.Error: Unresolved compilation problem: |?Syntax error, insert ";" to complete Statement|
Nov 15 15:24:41 raspi2 java[17147]: #011at com.bwssystems.HABridge.hue.BrightnessDecode.replaceIntensityValue(BrightnessDecode.java:65)

**Comment by bwssytems** [comment]
Yep, built the ha-bridge with a bad class. new version coming.

**Comment by gohamstergo** [comment]
Thanks for the update!

This might be a good time to bring up a tiny thing that I didn't want to create a whole new ticket for. Would it be possible to have the 'bridge devices' page remember my preferred sorting? For example, when sorting by ID, name, etc. it would be great if it saved that. Currently, it seems to sort randomly on each page load.

**Comment by bwssytems** [comment]
@gohamstergo Well, currently with the angular control I use, that would be a ticket for an enhancement.

**Comment by gohamstergo** [comment]
okie doke, I can create a ticket

**Comment by scholzmichael** [comment]
Harmony communication does still not work after hub restart here with 5.2.2RC2. Allthough Alexa now confirms "ok" on a Harmony activity nothing happens, it works after a bridge reinit though.
Log shows:

WARN | Send heartbeat failed | net.whistlingfish.harmony.HarmonyClient
then
WARN | Issue in communcicating with Harmony Hub, retrying connect....
but without reinit of ha bridge communication will not pick up again

**Comment by bwssytems** [comment]
@scholzmichael Thanks for the testing... We are a step further as in the past the reinit would not fix it,

**Comment by bwssytems** [comment]
I will look into the harmony issue as I thought I had it internally reinit the plugin.

**Comment by BaBa483** [comment]
@scholzmichael 
would you please share your script to reinit three times a day?
i have the exact same issue and i'm very new to all this stuff :)

Thanks in advance and have a merry christmas to all :)

**Comment by aameradam** [comment]
Connection retry on XMPP still doesn't work - Alexa now says "OK" on harmony commands but nothing happens. Reinit fixes it.

2019-01-13 16:55:52,337 [qtp1521256589-3113] WARN  com.bwssystems.HABridge.plugins.harmony.HarmonyHandler - Issue in communcicating with Harmony Hub, retrying connect....
2019-01-13 17:07:07,362 [qtp1521256589-3124] WARN  com.bwssystems.HABridge.plugins.harmony.HarmonyHandler - Issue in communcicating with Harmony Hub, retrying connect....

**Comment by bwssytems** [comment]
RC4 is now available and should run in most Java Run-times due to the removal of JAXB and also updated Harmony Hub disconnect detection.

**Comment by scholzmichael** [comment]
Right now: positive feedback to Harmony issue, no fallout up to now (approx. 24h). Will monitor further...

**Comment by bwssytems** [comment]
This is now released!
