### ISSUE TITLE
AIY voice kit > HA bridge > harmony: control harmony activities by voice

### ISSUE THREAD

**Issue by Finch666** [bwssytems/ha-bridge#1018]
I've got the bridge running and absolutely love it. All harmony devices and activities are recognized., and I'm able to switch my milights with the harmony remote and control ESPeasy mega devices on the network. My AIY voice kit runs a python script that also gives me voice control of the milight strips and the ESP devices, but I've yet still not been able to get my voice script (python) to send (voice activated) commands to the bridge to start harmony activities/devices. What kind of command do I have to send from the voice kit to the bridge to control a harmony activity or device (like watching tv, etc)? Or is there a manual for dummies somewhere? (fairly new to python and bridge). PS: this is not really an issue with the brigde, but I could not find any place else to place this question.......

**Comment by bwssytems** [comment]
Also, thanks for the info ofr ESPEasy, I have been playing around with ESP32s and ESP8266s for another project I am working on for boat/yacht information gathering (battery, bilge pumps and so forth).

**Comment by Finch666** [comment]
https://www.letscontrolit.com/wiki/index.php/ESPEasyMega 
Easy to set up, easy to program, etc. Works like a charm and the bridge can send commands like this: http://xxx.xxx.xxx.xxx/control?cmd=event,T1

**Comment by bwssytems** [comment]
I have just been looking through the docs, very nicely done. I see they do have support for ESP32s that will greatly enhance the capability as the memory is 4MB and dual cores.

**Comment by Finch666** [comment]
Thanks for your kind help, but I'm really struggling with the command structure.
My bridge is at IP Address 192.168.192.200
The target item for the activity is ` {"name":"36165818","hub":"harmony"}`
The name of the harmony activity: "TV-kijken"
The python code in my voicekit:
`elif text == 'start watching':`
               `      assistant.stop_conversation()`
               `      tv_command = 'http://192.168.192.200/harmony/TV-kijken/false'`
               `      r = requests.post(tv_command)`
               `     aiy.audio.say('switching tv on')`
(short explanation: when I say "start watching" to my voicekit, it should start the activity and the voicekit should respond by saying "switching tv on")

I know I'm doing something terribly wrong in my python code, but can't figure out what...
Can you help me? (much obliged)

**Comment by audiofreak9** [comment]
@Finch666 
To turn a device ON in the HA-Bridge you need to do a PUT, a python example, replacing [[SOME_USER]](https://github.com/bwssytems/ha-bridge#create-user) with a HA-Bridge user, and [HA-BRIDGE_DEVICE_ID] with the HA-Bridge device ID you want to operate, would look something like this:

```
#!/usr/bin/python
import requests

url = "http://192.168.192.200/api/[SOME_USER]/lights/[HA-BRIDGE_DEVICE_ID]/state" 
payload = "{\"on\":true}"
r = requests.put(url, data=payload)
```

To turn a device OFF, change the payload variable's "true" with "false":

`payload = "{\"on\":false}"`

To DIM a device, change the payload variable, replacing [DIM_VALUE] with a number between 1 and 254, use the following:

`payload = "{\"on\":true,\"bri\":[DIM_VALUE]}`
