### ISSUE TITLE
pairing of synology docker version

### ISSUE THREAD

**Issue by Kat-CeDe** [bwssytems/ha-bridge#1019]
Hi,
I had ha-bridge running for about 2 years on QNAP native and it worked almost perfect but I want to switch to Synology. Because there is no package I installed linuxserver docker image. I used docker host IP and at the moment Synology host IP and ha-bridge itself is work as I can use the webinterface to control my devices.

I tried pairing Harmony, Alexa and Openhab with all combination of security settings and sometimes new entries in manages links appear BUT it never paired:-( I looked in the log and got a valid user entry, I used this user in Openhab and I had control but only for 15min or so.

I am really out of ideas as everything looks OK but it isn´t

btw. does anyone know an emulator similar to ha-bridge but which emulates a Roku? This would add usage to a Harmony.

Ralf

**Comment by bwssytems** [comment]
First I would check the wiki at https://github.com/aptalca/docker-ha-bridge for anything docker as I am not the expert on that. But I would also encourage you to turn on trace upnp on look at the log output as well.

**Comment by Kat-CeDe** [comment]
Hi,
I think I am big step further. **I gave HA-Bridge a MAC** and then openHab paired at once. There is also a step in the correct direction with Alexa because now I see communication but sadly still no pairing. Perhaps you can see the problem.
192.168.178.2:5065 is HA-Bridge and
192.168.178.22 is the second port of the NAS
192.168.178.47 is the Echo I used for device search.
192.168.178.73 is another Echo
192.168.178.46 is another Echo
192.168.178.52 is another Echo

Ralf
[echo.txt](https://github.com/bwssytems/ha-bridge/files/2596814/echo.txt)

**Comment by Kat-CeDe** [comment]
Hi,
I made a big step. MAC was the magic word. After I gave HA-Bridge a MAC Harmony and openHAB paired immediately. Perhaps it should be default.

Ralf

**Comment by Kat-CeDe** [comment]
Hi,
Alexa is a bitch:-( She will not pair regardless what I do. Can you take a look at the attached file? It is a log of a pairing attempt.
192.168.278.2 is the Synology. Port 5065 is the port of HA-Bridge.
192.168.278.22 is the 2nd connector of Synology but there is no cable plugged in.
172.17.0.1 is the IP of the docker host.

192.168.178.30 and .37 are 2 of my Harmonies successfully paired with HA-Bridge.
192.168.178.46 and .47 are 2 of my Echos trying to pair.

Ralf
[RB-HA-Bridge.txt](https://github.com/bwssytems/ha-bridge/files/2600792/RB-HA-Bridge.txt)

**Comment by MaxPainNL** [comment]
Install Docker in DSM and use this project: https://github.com/aptalca/docker-ha-bridge. (Use your Synology IP in the command and a custom port)

docker run -d --name="Home-Automation-Bridge" --net="host" -e SERVERIP="192.168.X.X" -e SERVERPORT="XXXX" -v /path/to/config/:/config:rw -v /etc/localtime:/etc/localtime:ro aptalca/home-automation-bridge

    Replace the SERVERIP variable (192.168.X.X) with your server's IP
    Replace the SERVERPORT variable (XXXX) with whichever port you choose for the web gui.
    Replace the "/path/to/config" with your choice of location
    If the -v /etc/localtime:/etc/localtime:ro mapping causes issues, you can try -e TZ="<timezone>" with the timezone in the format of "America/New_York" instead

I get all my stuff working with this way.

**Comment by maestroat** [comment]
MaxPainNL same do but alexa find no bridge devices  port: 81  test it with 8088, 9050, 82 and some others was i found on any sites
