### ISSUE TITLE
Test Color for fhem

### ISSUE THREAD

**Issue by stenny73** [bwssytems/ha-bridge#1020]
Use fhem

Devices (MiLight) are imported

Test Color does not send RGB values ​​but xy values. How can I send RGB values?

**Comment by bwssytems** [comment]
Read here https://github.com/bwssytems/ha-bridge#value-passing-controls

**Comment by stenny73** [comment]
Hello

ok.
under dim stands
{"url":"http://192.168.11.99:8084/fhem?cmd=set%20milight3_1%20","command":"RGB%20${color.rgbx}"}

i dont understand it.....
i wand an 6 digits hex sending
