### ISSUE TITLE
HA-Bridge and ioBroker

### ISSUE THREAD

**Issue by 150d** [bwssytems/ha-bridge#1023]
Hi,

I can't manage to connect ioBroker to HA-Bridge. The ioBroker plugin requests to press the Link button, which I do in HA-Bridge, but nothing more happens on either side until the 30 second timer runs out. Also, HA-Bridge is not automatically discovered by ioBroker (IP must be manually specified).

The problem may be caused by different network segments: HA-bridge runs on a Windows machine with several network interfaces, one of which is a logical one going to a VirtualBox VM running Linux, where ioBroker is installed. 

On the other hand, "Use UPNP Address Interface Only" in HA-Bridge is NOT checked. Shouldn't HA-Bridge listen for (and respond to) broadcasts on all interfaces then?

Regards

**Comment by bwssytems** [comment]
So, the different subnets will cause an issue as the habridge v5.2.1 will not respond corrcectly. The new version 5.2.2RC2 has updates to handle upnp replies to different subnets. Give it a shot

**Comment by 150d** [comment]
No, I'm afraid HA-Bridge v5.2.2RC2 did not behave differently.

But I'm not yet convinced that my setup is not at fault in the first place:

10.3.1.4 - HA-Bridge "UPNP IP Address"
10.4.1.4 - IP on the HA-Bridge-Server that is connected to the virtual interface that in turn is connected to the VM running ioBroker
10.4.1.101 - IP of the virtual machine ioBroker is running in
10.1.1.4 - HA-Bridge Webserver IP
"Use UPNP Address Interface Only" in HA-Bridge is NOT checked

1st problem:
HA-Bridge is not "discovered" when searching from ioBroker

2nd problem:
If i manually specify the device in ioBroker, I need to enter IP and port. Which port should be used here? Is this the "UPNP Response Port" from HA-Bridge's settings?

Regards

**Comment by bwssytems** [comment]
Turn on traceupnp which will give a lot of info on where the traffic is coming or not

**Comment by 150d** [comment]
I do not get anything meaningful out of the trace (as in: no messages.)

Once I saw this:

2018-11-22 15:19:01,500 [qtp9581803-48] INFO  com.bwssystems.HABridge.hue.HueMulator - Traceupnp: hue api user create requested for device type: test_ha_bridge#10.1.1.4 and username: 42d9f43a0b9d40b6a9fa32a983f319d7

I have no idea where this came from, and I couldn't reproduce it. The IP 10.1.1.4 is the HA-Bridge Webserver-IP.

Currently I'm looking onto the interface using Wireshark. I see some SSDP-Packages flowing by - when I press "discover" in ioBroker, it seems a M-SEARCH is sent:

Simple Service Discovery Protocol
    M-SEARCH * HTTP/1.1\r\n
    HOST: 239.255.255.250:1900\r\n
    MAN: ssdp:discover\r\n
    MX: 10\r\n
    ST: urn:schemas-upnp-org:device:Basic:1\r\n
    \r\n
    [Full request URI: http://239.255.255.250:1900*]
    [HTTP request 1/1]

There is no immidiate response, and HA-Bridge does not show any message in the log/trace.

Sometimes I see a SSDP NOTIFY packet:

Simple Service Discovery Protocol
    NOTIFY * HTTP/1.1\r\n
    HOST: 239.255.255.250:1900\r\n
    CACHE-CONTROL: max-age=100\r\n
    LOCATION: http://10.3.1.4:86/description.xml\r\n
    SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.19.0\r\n
    NTS: ssdp:alive\r\n
    hue-bridgeid: 38D547FFFE750A5F\r\n
    NT: uuid:2f402f80-da50-11e1-9b23-38d547750a5f\r\n
    USN: uuid:2f402f80-da50-11e1-9b23-38d547750a5f\r\n
    \r\n
    [Full request URI: http://239.255.255.250:1900*]

But the two seem to be in no correlation to each other. There are a number of other devices on the network that may be talking to each other (a number of Amazon Echos, OpenHAB with Hue Emulation), so I can't even be sure that the two parties I need (HA-bridge and ioBroker) have any kind of knowledge of each other. The HA-Bridge trace sure doesn't look like it to me.

**Comment by 150d** [comment]
I forgot to mention something:

On the same VM that is running ioBroker there is an instance of OpenHAB. This instance is running a Hue-Emulation (menaing: presents some datapoints as if they were Hue-Devices), which HA-Bridge successfully picks up and relays tehm to Amazon Echos on another network segment. The problem is just with ioBroker, not with OpenHAB - which would indicate that the network setup is basically ok.

**Comment by bwssytems** [comment]
The question is: Does the VM pass on upnp broadcast messages as they are multicast?

**Comment by 150d** [comment]
After having worked this problem for some time I now believe that it has nothing to do with HA-Bridge, but "the other end" misbehaving. I have now simplified my setup to eliminate OpenHAB (with its "Hue Emulation") from the network, and the result is HA-Bridge operating exactly as it is supposed to.

I'm therefore marking this issue as "closed". Thank you for your help, and an ongoing great big thanks for creating a superb program!

Regards
