### ISSUE TITLE
Get mapstype error- HA-bridge

### ISSUE THREAD

**Issue by sjpkt** [bwssytems/ha-bridge#1026]
When I log into a page, I got a message said " Get mapstype error: undefined with status: not found 404. and on fibaro's discovered device, alexa doesnt discover ha-bridge too. How to fix the problem?

**Comment by bwssytems** [comment]
Could you give some more info on how you cahevied this error? Browser type, OS type network config, ha-bridge config, etc.

**Comment by sjpkt** [comment]
It’s running on Chrome windows 10 connected to Wifi.

**Comment by bwssytems** [comment]
OK, what version for ha-bridge. Are your running the ha-bridge on your windows machine? You need to explain every detail on how this is setup for me to debug. The mapstype error is  not enough to go on.
