### ISSUE TITLE
Echo Plus ZigBee Hub

### ISSUE THREAD

**Issue by jpr105** [bwssytems/ha-bridge#1030]
Hello

First of all thank you for this fabulous software !!
I hope not bother you for nothing but I haven't found any answer to my question in your reposit.

I already have a home automation system based on Zwave protocol  (FIBARO HC2) and I just bought the « Echo Plus + Ampoule Philips Hue incluse (B07H334QWK) » kit because I read that it enclosed a ZigBee hub.

With this purchase I want to open my home automation system to ZigBee connected objects in addition to Zwave connected objects.

The question that arises is: is there a SIMPLE way to control these ZigBee devices through my Echo Plus using HA-Bridge? I am thinking of course APIs ... but locally (192.168.xxx.xxx) of course because it should work even if the internet connection is down.

Is it already exists in HA-Bridge (I should have "missed") and / or will you implement it?

Thank you so much for your great job.

Regards - Jean-Paul

**Comment by bwssytems** [comment]
I believe that hub is a Philips hue hub itself, is that what it says in the documentation?

**Comment by jpr105** [comment]
No, they are talking about an integrated ZigBee hub

Envoyé de mon iPhone

**Comment by jpr105** [comment]
Here is the link : [https://www.amazon.com/All-new-Echo-Plus-Bundle-Philips/dp/B07H1D6821/ref=sr_tr_3?ie=UTF8&qid=1544628221&sr=8-3&keywords=echo%2Bplus&th=1](https://www.amazon.com/All-new-Echo-Plus-Bundle-Philips/dp/B07H1D6821/ref=sr_tr_3?ie=UTF8&qid=1544628221&sr=8-3&keywords=echo%2Bplus&th=1)

> Wi-Fi connectivity | Dual-band Wi-Fi  supports 802.11 a/b/g/n/ac (2.4 and 5 GHz) networks. Does not support  connecting to ad-hoc (or peer-to-peer) Wi-Fi networks.
> -- | --
> ZigBee connectivity | Built-in ZigBee smart home hub supports ZigBee light bulbs, locks, sensors, plugs, and in-wall switches.
> Bluetooth connectivity | Advanced Audio  Distribution Profile (A2DP) support for audio streaming from your mobile  device to Echo or from Echo to your Bluetooth speaker. Audio/Video  Remote Control Profile (AVRCP) for voice control of connected mobile  devices. Hands-free voice control is not supported for Mac OS X devices.  Bluetooth speakers requiring PIN codes are not supported.

**Comment by bwssytems** [comment]
Ok, I see now. The ha-bridge will not be able to interface to that bulb since the hub is part of the echo and not accessible.

**Comment by jpr105** [comment]
I founded that [https://developer.amazon.com/fr/docs/smarthome/echo-plus-zigbee-support.html](https://developer.amazon.com/fr/docs/smarthome/echo-plus-zigbee-support.html) but it looks a bite complicated for me ...
What do you think, is it possible without HA-Bridge ?

**Comment by bwssytems** [comment]
You are probably better off just buying a hue hub and using that. Much easier.

**Comment by jpr105** [comment]
You are right but as I'm not in a hurry you can also vote for this idea : [https://alexa.uservoice.com/forums/906892-alexa-skills-developer-voice-and-vote/suggestions/36349165-locally-control-zigbee-devices-connected-to-my-ech](https://alexa.uservoice.com/forums/906892-alexa-skills-developer-voice-and-vote/suggestions/36349165-locally-control-zigbee-devices-connected-to-my-ech)

Thanks
Regards - Jean-Paul

**Comment by audiofreak9** [comment]
I voted, thanks for th link!

**Comment by jpr105** [comment]
Well done, thanks a lot 😉

**Comment by bwssytems** [comment]
This has been added to the Community information https://github.com/bwssytems/ha-bridge/wiki/Informational-Items-Collected-from-the-Community#q-is-there-a-simple-way-to-control-these-zigbee-devices-through-my-echo-plus-using-ha-bridge
