### ISSUE TITLE
Harmony helper newly broken? (connection refused)

### ISSUE THREAD

**Issue by wmichael3** [bwssytems/ha-bridge#1036]
HABridge can no longer communicate with either of my Harmony Hubs.  The IP addresses have not changed - they are fixed in DHCP and both servers respond to pings on those addresses and I verified those addresses using the Harmony Android app, (which is still working fine).  I also cannot connect to the hubs any longer from from Vera via the Vera Harmony plugin.  This happened sometime recently - it was working last week and has been working for years.  I am using HABridge 5.2.1 (just upgraded) and the Harmony Hub software version is 4.15.206.  I have restarted the hubs and HABridge to no avail.  HABridge continues to work with Vera scenes and devices.  Here is the error (basically it is 'connection refused' and it is the same with both of my hubs)  Is this just me or is it happening to everyone?

2018-12-17 13:32:43,936 [main] INFO  com.bwssystems.HABridge.plugins.harmony.Har
monyServer - setup initiated ....
2018-12-17 13:32:44,951 [main] ERROR com.bwssystems.HABridge.plugins.harmony.Har
monyHome - Cannot get harmony client (Family Room) setup, Exiting with message:
Failed communicating with Harmony Hub
java.lang.RuntimeException: Failed communicating with Harmony Hub
        at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:19
3)
        at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:11
8)
        at com.bwssystems.HABridge.plugins.harmony.HarmonyServer.execute(Harmony
Server.java:111)
        at com.bwssystems.HABridge.plugins.harmony.HarmonyServer.setup(HarmonySe
rver.java:68)
        at com.bwssystems.HABridge.plugins.harmony.HarmonyHome.createHome(Harmon
yHome.java:236)
        at com.bwssystems.HABridge.plugins.harmony.HarmonyHome.<init>(HarmonyHom
e.java:40)
        at com.bwssystems.HABridge.HomeManager.buildHomes(HomeManager.java:54)
        at com.bwssystems.HABridge.HABridge.main(HABridge.java:79)
Caused by: org.jivesoftware.smack.SmackException$ConnectionException: The follow
ing addresses failed: '192.168.1.136:5222' failed because: /192.168.1.136 except
ion: java.net.ConnectException: Connection refused: connect

**Comment by 111wolf111** [comment]
yea not just you,
I'm having the same problem, been working fine till now.
I also have firmware 4.15.206.
Could it be that logitech did something in the last firmware update?

**Comment by jpr105** [comment]
Same to me on my Raspberry `Cannot get harmony client (Harmony HomeGMJPR) setup, Exiting with message: Failed communicating with Harmony Hub`

**Comment by JsChiSurf** [comment]
See closed issue[1034](https://github.com/bwssytems/ha-bridge/issues/1034), which was pointed to [1017](https://github.com/bwssytems/ha-bridge/issues/1017), which points to [945](https://github.com/bwssytems/ha-bridge/issues/945), the second 2 of which appear to be unrelated and thus, likely the need to re-open [1034](https://github.com/bwssytems/ha-bridge/issues/1034), so as to prevent repeated posts.  

Logitech appears to have disabled the necessary port in their latest firmware update.

**Comment by jpr105** [comment]
[https://www.reddit.com/r/homeassistant/comments/a6u6ep/psa_harmony_hub_firmware_v415206_breaksremoves/](https://www.reddit.com/r/homeassistant/comments/a6u6ep/psa_harmony_hub_firmware_v415206_breaksremoves/)

**Comment by bwssytems** [comment]
Duplicate to #945 and that link has updates as well. Looks like logitech will bring back the API.

**Comment by cipher2k** [comment]
Logitech made a statement that this API change is intentional. They have closed port 5022 for good and I doubt that they will bring this back. But, there is still port 8088 open with Websockets which could be used instead.

**Comment by glsf91** [comment]
Logitech have just made an update on the item. See: https://community.logitech.com/s/question/0D55A00008D4bZ4SAJ/harmony-hub-firmware-update-fixes-vulnerabilities

Use should be possible again.

**Comment by freeblazin** [comment]
Has anyone had success with the method from the link that @glsf91 posted.  I downloaded the latest My Harmony application for windows, but am unable to bring up the "tool" with the hot-keys mentioned in the instructions.

**Comment by scholzmichael** [comment]
Just updated my Elite hub to 210, enabled Internet for the hub again and everything is up and running again. Nice to see that there seem to be a lot more customers using this as Logitech expected....

**Comment by jpr105** [comment]
+1

**Comment by audiofreak9** [comment]
@simondsmason follow this Logitech guide here: https://community.logitech.com/s/question/0D55A00008D4bZ4SAJ/harmony-hub-firmware-update-fixes-vulnerabilities

**Comment by simondsmason** [comment]
Thanks - it took me a while to realize that I had to plug the PC directly into the Harmony Hub, not the HA extender that I also have with it.  After that everything downloaded and updated and my bridge is back up and running.  Thanks.

**Comment by tynie** [comment]
I really have no idea what I'm doing wrong but I can't get the menu mentioned in the thread via the hotkeys called. I am in the login window of my current MyHarmony software and tried ALT+F9 and F9, but without success. Nothing happens. Does anyone else have a tip?

**Comment by NovaGL** [comment]
New firmware has XMPP support added back.
https://community.logitech.com/s/question/0D55A00008OsX3CSAV/update-to-accessing-harmony-hubs-local-api-via-xmpp

This issue should be closed.

**Comment by gohamstergo** [comment]
FYI: Mine showed "enabled" by default. Needed to cycle it disable/enable to get things going again.

**Comment by bwssytems** [comment]
This is now fixed in V5.2.2
