### ISSUE TITLE
Controlling Harmony Activities via new API

### ISSUE THREAD

**Issue by NovaGL** [bwssytems/ha-bridge#1039]
For all of you upset about loosing control over Harmony, it is easy to change activities using the new method (although the rest is a bit complicated)

To create an on off activity (assuming you know the activity ID's) you do the following.

Create a new device in HA-Bridge.

On Item
**Type** > HTTP Device.
**Target Item** > http://HUB_IP:8088
**HTTP VERB** > POST
**HTTP BODY**
`{"cmd": "harmony.activityengine?runactivity", "params":{"activityId":"ACTIVITY_ID"}}`

**HTTP HEADERS** 
`[{"name":"Accept","value":"utf-8"},{"name":"Origin","value":"http//:localhost.nebula.myharmony.com"}]`

**Content-Type** > application/json

Click Add 

And repeat for the Off Item but change activity ID to -1

**Comment by scholzmichael** [comment]
no need (at leasst right now) since controle is back with dev. FW 210 available. An official FW with option to gain local access was promised by Logitech for January

**Comment by audiofreak9** [comment]
@NovaGL 
Nice, thanks for this from someone who prefers to not use the XMPP method, so I don't have to rely on Harmony to keep this 'Developer' option alive.

**Comment by Dr-know** [comment]
treying to set up ha-bridge, where do i find the harmony activity ID ?

**Comment by NovaGL** [comment]
@Dr-know I created my own GitHub which goes through the API haven't added the section on Websocket yet. (However more information is listed below)
https://github.com/NovaGL/diy-harmonyhub

The way you get the Activity Id is similar but requires a few more steps.

Use the same information as above but change the body of the request to be the following.
Id can be a random number.

**REQUEST**
````json
{"id":0,"cmd":"setup.account?getProvisionInfo","timeout":90000}
`````

In the response you will see
````
"accountId": "[MyAccountID]"
````

Grab the [MyAccountID] value and use it for the next request.

**REQUEST**
````json
{"id":0,"cmd":"proxy.resource?get","params":{"uri":"harmony://Account/[MyRemoteID]/ActivityList"},"timeout":90000}
````

This will return you all the activities.
Because the list is so big you can use the following JSONata queryto only retrieve the information you need. Copy the response (from the above request) into the left side and the following query on the right side at this site: http://try.jsonata.org/

````jsonata
{
    "Activities": $spread(data.resource.Activities {
        Name: [
            $ ~> | $ | {}, "Name" |            
        ]
    }).{
        "Name": $keys()[0],
        "ActivityId":*."Id-"
    }
}
````

You will then get a structured JSON with only the information you need

````json
{
  "Activities": [
    {
      "Name": "Watch TV",
      "ActivityId": 0000
    }
]}
````

**Comment by Dr-know** [comment]
> 
> 
> @Dr-know I created my own GitHub which goes through the API haven't added the section on Websocket yet. (However more information is listed below)
> https://github.com/NovaGL/diy-harmonyhub
> 
> The way you get the Activity Id is similar but requires a few more steps.
> 
> Use the same information as above but change the body of the request to be the following.
> Id can be a random number.
> 
> **REQUEST**
> 
> ```json
> {"id":0,"cmd":"setup.account?getProvisionInfo","timeout":90000}
> ```
> 
> In the response you will see
> 
> ```
> "accountId": "[MyAccountID]"
> ```
> 
> Grab the [MyAccountID] value and use it for the next request.
> 
> **REQUEST**
> 
> ```json
> {"id":0,"cmd":"proxy.resource?get","params":{"uri":"harmony://Account/[MyRemoteID]/ActivityList"},"timeout":90000}
> ```
> 
> This will return you all the activities.
> Because the list is so big you can use the following JSONata queryto only retrieve the information you need. Copy the response (from the above request) into the left side and the following query on the right side at this site: http://try.jsonata.org/
> 
> ```
> {
>   "Devices": data.resource.Activities.({
>   "Name":$.Name,
>   "ActivityId": $."Id-",  
>   })
> }
> ```
> 
> You will then get a structured JSON with only the information you need
> 
> ```json
> {
>   "Activities": [
>     {
>       "Name": "Watch TV",
>       "ActivityId": 0000
>     }
> ]}
> ```

Thanks, for the reply, but every request i try i get 401 Wrong hubid back ...
so stuck at the ping action on your diy-harmony hub github .. 
ps , i am farley new at this api, thing .. i have installed postman to send the request ..

**Comment by NovaGL** [comment]
@Dr-know 
I'm a bit confused, do you have the right hub ip?

Harmony app> Select hub > Options > About > Versions > Hub IP Address.

Can you use this instead as Postman didn't work for me - https://chrome.google.com/webstore/detail/restlet-client-rest-api-t/aejoelaoggembcahagimdiliamlcdmfm?hl=en

In Restlet, make sure you are doing a POST request. Use the Hub address you got from the app with port of 8088

Headers, use the ones I mentioned above, body is request.

I might not be the right person to ask, as it might be too complicated the way I do it.

**Comment by Dr-know** [comment]
@NovaGL 
Hello,
I have got it ! with postman no suc6 , with the Chrome extention OK !!
Thank You verry mutch, no i can go on with testing !

Thanks!

**Comment by d3smo** [comment]
Is there also a http POST request available not for Harmony activities but for Harmony specific buttons inside a specific activity ?

**Comment by d3smo** [comment]
Thx for your concern but your explanation are a little bit confusing for me, here is what i have as action on my harmony button, could you explain your code or help me to understand what i have to do ?

https://i.imgur.com/SpLYkWE.png

**Comment by NovaGL** [comment]
I answered your question, you didn't ask how to press buttons in HA-Bridge. Since HA-Bridge doesn't do Websocket, you won't be able to do it.

If you want I can let you know how to do it in websocket? However doing it in HTTP post doesn't work well

**Comment by NovaGL** [comment]
I'm not sure how LUA works but maybe you can do it as curl command then that can be put in a linux script.

**Comment by d3smo** [comment]
I was able to do it in a linux script using a curl, but i don't know why maybe Logitech cahnge something i've got my button command action working again on HA Bridge

**Comment by NovaGL** [comment]
XMPP is enabled again so using WS might not be needed anymore
https://community.logitech.com/s/question/0D55A00008OsX3CSAV/update-to-accessing-harmony-hubs-local-api-via-xmpp
