### ISSUE TITLE
Razer Chroma with ha-bridge

### ISSUE THREAD

**Issue by MaxPainNL** [bwssytems/ha-bridge#1040]
I want to use Razer Chroma lightning with the ha-bridge. I don't have a Philips Hue bridge. I already use my ha-bridge with Domoticz to turn my lights on and off with a Amazon Echo. Is it possible to use my Razer devices aswell?

**Comment by bwssytems** [comment]
Without the hue hub, I would have to register with their developer program and see the api. This would be a low priority request due to that effort.
