### ISSUE TITLE
Json IR codes no longer working since upgrading to new version (from v3.1.0 to v5.2.1)

### ISSUE THREAD

**Issue by cjeri** [bwssytems/ha-bridge#1041]
Hi,

I used to run v3.1.0 and was able to get the IR codes working fine for my Global Cache Flex IR blaster, using the API and the IR libraries. 

Today, I upgraded to v5.2.1 and everything stopped working. I can still see the old codes in the "Legacy Fields" section, but they don't seem to be any good.

The setup that I used to have was:
On command: http://192.168.0.11/api/v1/irports/3/sendir
On content body (POST): application/json
{
  "frequency":”38000”,
  "irCode":"340,85,20,3663",
  "preamble": "340,169,20,20,20,20,20,64,20,20,20,20,20,20,20,20,20,20,20,64,20,64,20,20,20,64,20,64,20,64,20,64,20,64,20,64,20,20,20,20,20,64,20,20,20,20,20,20,20,20,20,20,20,64,20,64,20,20,20,64,20,64,20,64,20,64,20,1544",
  "repeat":”1”
}

I've tried adding what used to be the old content body as an additional line in the "On Items", but the log shows the following error:

Dec 27 22:09:10 raspberrypi java[7816]: 2018-12-27 22:09:10,633 [qtp6090057-8] WARN  com.bwssystems.HABridge.plugins.exec.CommandHome - Could not execute request: {
Dec 27 22:09:10 raspberrypi java[7816]:   "frequency":”38000”,
Dec 27 22:09:10 raspberrypi java[7816]:   "irCode":"340,85,20,3663",
Dec 27 22:09:10 raspberrypi java[7816]:   "preamble": "340,169,20,20,20,20,20,64,20,20,20,20,20,20,20,20,20,20,20,64,20,64,20,20,20,64,20,64,20,64,20,64,20,64,20,64,20,20,20,20,20,64,20,20,20,20,20,20,20,20,20,20,20,64,20,64,20,20,20,64,20,64,20,64,20,64,20,1544",
Dec 27 22:09:10 raspberrypi java[7816]:   "repeat":”1”
Dec 27 22:09:10 raspberrypi java[7816]: } with message: Cannot run program "{": error=2, No such file or directory
Dec 27 22:17:01 raspberrypi CRON[11708]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)

Any ideas what I could be doing wrong?

Many thanks!

**Comment by bwssytems** [comment]
It goes into the field "HTTP Body" in your on item. That field is to the right.

**Comment by cjeri** [comment]
Got it working! It turns out that my syntax for the IR code in the HTTP body was wrong (everything else was fine)! Duh! 

It should have been (and for those future users, note that the actual parameters will vary):

{
  "frequency": 38000,
  "irCode": "340,169,20,20,20,20,20,64,20,20,20,20,20,20,20,20,20,20,20,64,20,64,20,20,20,64,20,64,20,64,20,64,20,64,20,64,20,20,20,20,20,64,20,20,20,20,20,20,20,20,20,20,20,64,20,64,20,20,20,64,20,64,20,64,20,64,20,1544",
  "preamble": "340,85,20,3663",
  "repeat": 1
}
