### ISSUE TITLE
Homeassistant device list is blank

### ISSUE THREAD

**Issue by crzg** [bwssytems/ha-bridge#1042]
Hello

Thank you for putting this together it is solving a lot of my challenges with home automation!

I have this setup and working for mqtt (which in turn triggers events on Homeassistant) however I am unable to interact with Homeassistant via HA-Bridge directly. I have attached some screenshots to demonstrate - I am using duckdns and let's encrypt, so I have setup accordinly (e.g. use SSL) and it seems to connect (have tried dummy passwords which show errors in the log) - is it possible that it is not showing any devices because HA-Bridge is connecting using the legacy API password?

I have looked up a number of guides and GH issues - none seem to refer to this specific issue where I can connect, but not see entities.

If I am missing anything obvious with setup or information for troubleshooting please let me know! Alternative would be to continue going via mqtt but that seems like an unnecessary workaround.

![img_20181229_093032](https://user-images.githubusercontent.com/35422834/50536433-80edd100-0b4c-11e9-9b19-9afac3eaa6db.png)
![img_20181229_090450](https://user-images.githubusercontent.com/35422834/50536439-8ba86600-0b4c-11e9-80dc-1a57452a271b.png)
![img_20181229_090243](https://user-images.githubusercontent.com/35422834/50536444-9fec6300-0b4c-11e9-989a-b48fdd7a662c.png)

**Comment by bwssytems** [comment]
Interesting, I have not tested HA over the internet and it uses the password as I have not changed that method.

**Comment by Twit123** [comment]
Hi,

I had the same type of issue but only when I went to HA version 0.83.3 as there was a change to the legacy passwords in HA. I basically just followed this [https://github.com/home-assistant/home-assistant/pull/18922](url) and got it all working again. 

Although the legacy API password is still working at the moment, it will be removed at some point. Ha-bridge will need to use the new Long-Lived Access Tokens format.

Cheers

Simon

**Comment by Kalekulan** [comment]
@Twit123 The link seems to be dead. I have the same issue.

**Comment by crzg** [comment]
@Kalekulan the page is live, the hyperlink above does not. Try [this](https://github.com/home-assistant/home-assistant/pull/18922) or just copy the above link into your address bar

**Comment by amyth1884** [comment]
same here, need help to add esphome devices on ha bridge
