### ISSUE TITLE
Support of Philips HUE scenes?

### ISSUE THREAD

**Issue by Gaspode69** [bwssytems/ha-bridge#1050]
Hi,
I just tried to create "scenes" with the third party Android app "all 4 hue".
After setting up the settings for my scene, I get the message "Scene created", but this scene is nowhere listed. It seems, that the scene is not created at all.
Does HA-Bridge support these kind of scenes or is it an issue? Or am I doing something wrong.
Thanks

**Comment by audiofreak9** [comment]
Currently, HA-Bridge does not support creation of scenes.  However you can probably use Routines available in the Alexa app to do the same thing.

**Comment by Gaspode69** [comment]
Hi,
thanks for your answer.
I already use Routines in the Alexa App. Unfortunately, Routines cannot assigned to a room. So I hoped that I can use scenes for that purpose. Or is there another trick?

**Comment by audiofreak9** [comment]
Have you made any [Groups](https://www.amazon.com/gp/help/customer/display.html?nodeId=201749250) in the Alexa app?  You can then tell the assigned Echo in that Group simply, “Alexa, turn on [Group]”.

**Comment by Gaspode69** [comment]
Thanks again for the suggestion.
However, the plan is to use the same command in different rooms to switch different devices. In the way it already works by default with "Lights on", which turns on all lights assigned to the current room.

**Comment by gohamstergo** [comment]
Just create a device in ha-bridge with the same name as the scene. For example:
ha-bridge device "Bright in Living Room"
alexa cmd: alexa turn on bright in living room.

**Comment by Gaspode69** [comment]
And how does this help to use the same command in different rooms?
I'd like to say only "Turn on bright." without any room name behind it.
If I'm in the kitchen, I want that the according devices in the kitchen are turned on. If I'm in the living room, the decices in the living room, etc.

**Comment by gohamstergo** [comment]
i guess i didn't realize you could have separate but identical commands setup for different alexas in different rooms. i only have one, so i guess ill bow out of this discussion.

**Comment by audiofreak9** [comment]
With the Group option, "Alexa, turn on the lights" to the included Echo(s), is currently as close as you are going to get to your request, without making your own Alexa skill.  Or you can fork this repository, code to add the the Scenes using the Philips Hue API, the submit a merge request.
