### ISSUE TITLE
Fibaro Scene discovery not working

### ISSUE THREAD

**Issue by stevensingh** [bwssytems/ha-bridge#1051]
Hi I have a fibaro home center 2 running software 4.430 which is the latest firmware.
I have tried HA bridge version 5.2.1 and 5.2.2 running on a raspberry pi version 3
I also ran the ha hub as a docker container (latest build)

I ran api commands from the web browser and i can see that scene api discovery is working fine.

The Debug logging also shows the same from the ha hub please see below

----
getScenes response: <<<[{"id":1,"name":"All Lights On","type":"com.fibaro.blockScene","categories":["other"],"roomID":14,"iconID":2,"runConfig":"TRIGGER_AND_MANUAL","alexaProhibited":false,"autostart":false,"protectedByPIN":false,"killable":true,"killOtherInstances":false,"maxRunningInstances":2,"runningInstances":0,"instances":[],"runningManualInstances":0,"visible":true,"isLua":false,"properties":"","triggers":{"properties":[],"globals":[],"events":[{"deviceId":8,"eventName":"SceneActivationEvent","args":[]}],"weather":[]},"actions":{"devices":[9,14,19,24,29,34,39,50,54,58,62,66,72],"scenes":[],"groups":[]},"sortOrder":51},{"id":3,"name":"All Lights Off","type":"com.fibaro.blockScene","categories":["other"],"roomID":14,"iconID":2,"runConfig":"TRIGGER_AND_MANUAL","alexaProhibited":true,"autostart":false,"protectedByPIN":false,"killable":true,"killOtherInstances":false,"maxRunningInstances":2,"runningInstances":0,"instances":[],"runningManualInstances":0,"visible":true,"isLua":false,"properties":"","triggers":{"properties":[],"globals":[],"events":[{"deviceId":8,"eventName":"SceneActivationEvent","args":[]}],"weather":[]},"actions":{"devices":[],"scenes":[],"groups":[]},"sortOrder":52},{"id":4,"name":"Cinema On","type":"com.fibaro.blockScene","categories":["other"],"roomID":5,"iconID":5,"runConfig":"TRIGGER_AND_MANUAL","alexaProhibited":true,"autostart":false,"protectedByPIN":false,"killable":true,"killOtherInstances":false,"maxRunningInstances":2,"runningInstances":0,"instances":[],"runningManualInstances":0,"visible":true,"isLua":false,"properties":"","triggers":{"properties":[],"globals":[],"events":[{"deviceId":8,"eventName":"SceneActivationEvent","args":[]}],"weather":[]},"actions":{"devices":[],"scenes":[],"groups":[]},"sortOrder":53},{"id":5,"name":"Cinema Off","type":"com.fibaro.blockScene","categories":["other"],"roomID":5,"iconID":5,"runConfig":"TRIGGER_AND_MANUAL","alexaProhibited":true,"autostart":false,"protectedByPIN":false,"killable":true,"killOtherInstances":false,"maxRunningInstances":2,"runningInstances":0,"instances":[],"runningManualInstances":0,"visible":true,"isLua":false,"properties":"","triggers":{"properties":[],"globals":[],"events":[{"deviceId":8,"eventName":"SceneActivationEvent","args":[]}],"weather":[]},"actions":{"devices":[],"scenes":[],"groups":[]},"sortOrder":54},{"id":6,"name":"MasterBed Rails Clos","type":"com.fibaro.blockScene","categories":["other"],"roomID":8,"iconID":5,"runConfig":"TRIGGER_AND_MANUAL","alexaProhibited":false,"autostart":false,"protectedByPIN":false,"killable":true,"killOtherInstances":false,"maxRunningInstances":2,"runningInstances":0,"instances":[],"runningManualInstances":0,"visible":true,"isLua":false,"properties":"","triggers":{"properties":[],"globals":[],"events":[{"deviceId":13,"eventName":"SceneActivationEvent","args":[]}],"weather":[]},"actions":{"devices":[130,133],"scenes":[],"groups":[]},"sortOrder":61},{"id":7,"name":"MasterBed Rail Open","type":"com.fibaro.blockScene","categories":["other"],"roomID":8,"iconID":5,"runConfig":"TRIGGER_AND_MANUAL","alexaProhibited":false,"autostart":false,"protectedByPIN":false,"killable":true,"killOtherInstances":false,"maxRunningInstances":2,"runningInstances":0,"instances":[],"runningManualInstances":0,"visible":true,"isLua":false,"properties":"","triggers":{"properties":[],"globals":[],"events":[{"deviceId":8,"eventName":"SceneActivationEvent","args":[]}],"weather":[]},"actions":{"devices":[130,133],"scenes":[],"groups":[]},"sortOrder":62},{"id":8,"name":"MastBed Voils Close","type":"com.fibaro.blockScene","categories":["other"],"roomID":8,"iconID":5,"runConfig":"TRIGGER_AND_MANUAL","alexaProhibited":false,"autostart":false,"protectedByPIN":false,"killable":true,"killOtherInstances":false,"maxRunningInstances":2,"runningInstances":0,"instances":[],"runningManualInstances":0,"visible":true,"isLua":false,"properties":"","triggers":{"properties":[],"globals":[],"events":[{"deviceId":8,"eventName":"SceneActivationEvent","args":[]}],"weather":[]},"actions":{"devices":[130],"scenes":[],"groups":[]},"sortOrder":63},{"id":9,"name":"MastBed Voils Open","type":"com.fibaro.blockScene","categories":["other"],"roomID":8,"iconID":5,"runConfig":"TRIGGER_AND_MANUAL","alexaProhibited":false,"autostart":false,"protectedByPIN":false,"killable":true,"killOtherInstances":false,"maxRunningInstances":2,"runningInstances":0,"instances":[],"runningManualInstances":0,"visible":true,"isLua":false,"properties":"","triggers":{"properties":[],"globals":[],"events":[{"deviceId":8,"eventName":"SceneActivationEvent","args":[]}],"weather":[]},"actions":{"devices":[130],"scenes":[],"groups":[]},"sortOrder":64},{"id":10,"name":"MasBed Curtain Close","type":"com.fibaro.blockScene","categories":["other"],"roomID":8,"iconID":5,"runConfig":"TRIGGER_AND_MANUAL","alexaProhibited":false,"autostart":false,"protectedByPIN":false,"killable":true,"killOtherInstances":false,"maxRunningInstances":2,"runningInstances":0,"instances":[],"runningManualInstances":0,"visible":true,"isLua":false,"properties":"","triggers":{"properties":[],"globals":[],"events":[{"deviceId":8,"eventName":"SceneActivationEvent","args":[]}],"weather":[]},"actions":{"devices":[133],"scenes":[],"groups":[]},"sortOrder":65},{"id":11,"name":"MastBed Curtain Open","type":"com.fibaro.blockScene","categories":["other"],"roomID":8,"iconID":5,"runConfig":"TRIGGER_AND_MANUAL","alexaProhibited":false,"autostart":false,"protectedByPIN":false,"killable":true,"killOtherInstances":false,"maxRunningInstances":2,"runningInstances":0,"instances":[],"runningManualInstances":0,"visible":true,"isLua":false,"properties":"","triggers":{"properties":[],"globals":[],"events":[{"deviceId":8,"eventName":"SceneActivationEvent","args":[]}],"weather":[]},"actions":{"devices":[133],"scenes":[],"groups":[]},"sortOrder":66},{"id":12,"name":"Lounge Rails Close","type":"com.fibaro.blockScene","categories":["other"],"roomID":5,"iconID":5,"runConfig":"TRIGGER_AND_MANUAL","alexaProhibited":false,"autostart":false,"protectedByPIN":false,"killable":true,"killOtherInstances":false,"maxRunningInstances":2,"runningInstances":0,"instances":[],"runningManualInstances":0,"visible":true,"isLua":false,"properties":"","triggers":{"properties":[],"globals":[],"events":[{"deviceId":13,"eventName":"SceneActivationEvent","args":[]}],"weather":[]},"actions":{"devices":[124,127],"scenes":[],"groups":[]},"sortOrder":55},{"id":13,"name":"Lounge Rails Open","type":"com.fibaro.blockScene","categories":["other"],"roomID":5,"iconID":5,"runConfig":"MANUAL_ONLY","alexaProhibited":false,"autostart":false,"protectedByPIN":false,"killable":true,"killOtherInstances":false,"maxRunningInstances":2,"runningInstances":0,"instances":[],"runningManualInstances":0,"visible":true,"isLua":false,"properties":"","triggers":{"properties":[],"globals":[],"events":[{"deviceId":13,"eventName":"SceneActivationEvent","args":[]}],"weather":[]},"actions":{"devices":[124,127],"scenes":[],"groups":[]},"sortOrder":56},{"id":14,"name":"Lounge Voils Close","type":"com.fibaro.blockScene","categories":["other"],"roomID":5,"iconID":5,"runConfig":"TRIGGER_AND_MANUAL","alexaProhibited":false,"autostart":false,"protectedByPIN":false,"killable":true,"killOtherInstances":false,"maxRunningInstances":2,"runningInstances":0,"instances":[],"runningManualInstances":0,"visible":true,"isLua":false,"properties":"","triggers":{"properties":[],"globals":[],"events":[{"deviceId":13,"eventName":"SceneActivationEvent","args":[]}],"weather":[]},"actions":{"devices":[124],"scenes":[],"groups":[]},"sortOrder":57},{"id":15,"name":"Lounge Voils Open","type":"com.fibaro.blockScene","categories":["other"],"roomID":5,"iconID":5,"runConfig":"MANUAL_ONLY","alexaProhibited":false,"autostart":false,"protectedByPIN":false,"killable":true,"killOtherInstances":false,"maxRunningInstances":2,"runningInstances":0,"instances":[],"runningManualInstances":0,"visible":true,"isLua":false,"properties":"","triggers":{"properties":[],"globals":[],"events":[{"deviceId":13,"eventName":"SceneActivationEvent","args":[]}],"weather":[]},"actions":{"devices":[124],"scenes":[],"groups":[]},"sortOrder":58},{"id":16,"name":"Lounge Curtains Open","type":"com.fibaro.blockScene","categories":["other"],"roomID":5,"iconID":5,"runConfig":"MANUAL_ONLY","alexaProhibited":false,"autostart":false,"protectedByPIN":false,"killable":true,"killOtherInstances":false,"maxRunningInstances":2,"runningInstances":0,"instances":[],"runningManualInstances":0,"visible":true,"isLua":false,"properties":"","triggers":{"properties":[],"globals":[],"events":[{"deviceId":13,"eventName":"SceneActivationEvent","args":[]}],"weather":[]},"actions":{"devices":[127],"scenes":[],"groups":[]},"sortOrder":59},{"id":17,"name":"Lounge Curtain Close","type":"com.fibaro.blockScene","categories":["other"],"roomID":5,"iconID":5,"runConfig":"MANUAL_ONLY","alexaProhibited":false,"autostart":false,"protectedByPIN":false,"killable":true,"killOtherInstances":false,"maxRunningInstances":2,"runningInstances":0,"instances":[],"runningManualInstances":0,"visible":true,"isLua":false,"properties":"","triggers":{"properties":[],"globals":[],"events":[{"deviceId":13,"eventName":"SceneActivationEvent","args":[]}],"weather":[]},"actions":{"devices":[127],"scenes":[],"groups":[]},"sortOrder":60}] >>> 

----

However directly beneith i see 

 getScenes Found: 0 scenes

The ha hub manages to get all the devices listed and i can add these but not the scenes.

Also Amazon Alexa is not able to see any devices after a device discovery

**Comment by bwssytems** [comment]
Will take a look

**Comment by stevensingh** [comment]
Hi is there any update on this ? would it be possible to revert back to using the old Vera API instead ?

**Comment by stevensingh** [comment]
I rebuilt the pi using full version of rats Ian with GUI. Did an update and a upgrade added a static IP address, started and enabled there ha-bridge service. Now have all devices and scenes. Alexa also sees these upon running discovery
