### ISSUE TITLE
Google home assistant

### ISSUE THREAD

**Issue by digitallivinglk** [bwssytems/ha-bridge#1052]
How to connect google home mini to Ha bridge on raspberry pi ? ... i am connect to alexa this a no problem, discover all devices.  I can't connect to google home mini......please tell me

**Comment by bwssytems** [comment]
Please Read https://github.com/bwssytems/ha-bridge/wiki/HA-Bridge-FAQs#q-why-doesnt-google-home-find-my-ha-bridge-and-goes-to-the-meethuecom-website

This will not work due to Google....
