### ISSUE TITLE
Harmony Hub commands will repeat

### ISSUE THREAD

**Issue by Nachtfalke49** [bwssytems/ha-bridge#1053]
Hello,

After the update from 5.2.1 to 5.2.2RC3 Harmony Hub commands are no longer executed properly. The Harmony Hub button 22 will run as 2 then 22 and then 2. The Target Item in Ha-Bridge is [{"device": "49687309", "button": "2"}, {"device": "49687309", "button": "2"}]
With 5.2.1 the Target Item works.

Regards,

Andi

**Comment by bwssytems** [comment]
Will take a look

**Comment by bwssytems** [comment]
So, that is probably an old syntax. I would delete that item and use the Harmony Device Tab to build a button to send 2 and then use the count parameter to send it twice.

**Comment by Nachtfalke49** [comment]
Upgrading to version v5.2.2RC4 was the solution. Now it works again.
