### ISSUE TITLE
How to Pair with Harmony Hub?

### ISSUE THREAD

**Issue by ratoaq2** [bwssytems/ha-bridge#1058]
I searched in the issues and wasn't able to make it work with any solution.

I have the latest ha-bridge running from a docker version using the `--net=host` and the correct ip as a system property.
When I add the Philips Hue in Harmony Hub it tells me to press the center button in the bridge.
In ha-bridge doesn't show anything.

What's the process to pair?

**Comment by bwssytems** [comment]
You need to set use link button on ha-bridge which provides the capability. After that and a restart, there will be a link button on the home page of the ha-bridge

**Comment by ratoaq2** [comment]
I press the link button and nothing happens.
Was supposed to show any entry in the table below?

**Comment by ratoaq2** [comment]
I tried using docker in a synology NAS, using docker in a raspberry pi and using docker in my laptop. I can't add the Phillips Hue in Harmony Hub because it doesn't detect the center button press.

Running in synology
```
docker run --name bridge -d --net=host -v /volume1/public/habridge/data/:/bridge/data -v /etc/localtime:/etc/localtime:ro -e PORT="-Dserver.port=8084" -e KEY="-Dsecurity.key=asecret" -e IP="-Dserver.ip=192.168.0.10" -e "-Dupnp.config.address=192.168.0.10" -e GARDEN="-Dexec.garden=/bridge/" bios/docker-alexa-ha-bridge
```

Running in a PI 3
```
docker run --name ha-bridge --rm --init --detach --net=host --volume=/home/pi/ha-bridge/data:/ha-bridge/data --volume=/etc/localtime:/etc/localtime:ro --volume=/etc/timezone:/etc/timezone:ro habridge/ha-bridge-raspberrypi3 -Dserver.port=8080 -Dsecurity.key=asecret
```


Running in my laptop
```
docker run --name bridge -d --net=host -v /home/user/habridge/data:/bridge/data -v /etc/localtime:/etc/localtime:ro -e PORT="-Dserver.port=8080" -e KEY="-Dsecurity.key=asecret" -e IP="-Dserver.ip=192.168.0.116" -e "-Dupnp.config.address=192.168.0.116" -e GARDEN="-Dexec.garden=/bridge/" bios/docker-alexa-ha-bridge

**Comment by bwssytems** [comment]
Ahh, you will need to make sure your docker proxy address is available to send and receive udp
