### ISSUE TITLE
Domoticz Groups use incorrect api

### ISSUE THREAD

**Issue by gorstj** [bwssytems/ha-bridge#1062]
Using Ha-Bridge to control a Domoticz GROUP using the 'Domoticz Tab' to create the device.

It uses the command:
http://IP:8080/json.htm?type=command&param=switchlight&idx=15&switchcmd=On

It should use:
http://IP:8080/json.htm?type=command&param=switchscene&idx=15&switchcmd=On

note 'switchscene' rather than 'switchlight'.

(n.b. Domoticz 'scenes' are correctly constructed using the 'swicthscene' api command)

**Comment by bwssytems** [comment]
Will look t the code when decoding the devices and apply this. Thanks

**Comment by bwssytems** [comment]
So, what is the type in the Domoticz tab that it shows before you create the device?

**Comment by bwssytems** [comment]
Never mind, I see the type is 'Group' that is returned
