### ISSUE TITLE
Is support for Logitech Pop gone

### ISSUE THREAD

**Issue by bashers222** [bwssytems/ha-bridge#1064]
I can see the Logitech Pop support was added after #623 , but i'm darned if i can get it going now
I've taken the latest version as of today- 5.2.2.RC3
I can control the device, a HEOS speaker from ha-bridge, but triggering the faked HUE light from the logitech app and it fails to fire the command.
It seems to be calling the scene; 
```
HueMulator PUT called on api/* with request <<</api/0da712600639421e830d71bd686d6018/groups/0/action>>>, and body <<<{"scene":"L0cGOEjjJPIRE0rd"}>>>
but not returning a 404 so that the scene fails and the light is called individually
```

`21:09:12 centos01 java: 2019-02-26 21:09:12,230 [qtp1726125653-44] DEBUG com.bwssystems.HABridge.hue.HueMulator - HueMulator PUT called on api/* with request <<</api/0da712600639421e830d71bd686d6018/groups/0/action>>>, and body <<<{"scene":"L0cGOEjjJPIRE0rd"}>>>
Feb 26 21:09:12 centos01 java: 2019-02-26 21:09:12,230 [qtp1726125653-44] DEBUG com.bwssystems.HABridge.hue.HueMulator - PUT action to group  0 from 192.168.2.55 user 0da712600639421e830d71bd686d6018 with body {"scene":"L0cGOEjjJPIRE0rd"}
Feb 26 21:09:12 centos01 java: 2019-02-26 21:09:12,230 [qtp1726125653-44] DEBUG com.bwssystems.HABridge.hue.HueMulator - hue lights list requested: 0da712600639421e830d71bd686d6018 from 192.168.2.55
Feb 26 21:09:12 centos01 java: 2019-02-26 21:09:12,230 [qtp1726125653-44] DEBUG com.bwssystems.HABridge.hue.HueMulator - Processing light1: false true false
Feb 26 21:09:12 centos01 java: 2019-02-26 21:09:12,230 [qtp1726125653-44] DEBUG com.bwssystems.HABridge.hue.HueMulator - Processing light2: false true false
Feb 26 21:09:12 centos01 java: 2019-02-26 21:09:12,230 [qtp1726125653-44] DEBUG com.bwssystems.HABridge.hue.HueMulator - Processing light3: false true false
Feb 26 21:09:12 centos01 java: 2019-02-26 21:09:12,230 [qtp1726125653-44] DEBUG com.bwssystems.HABridge.hue.HueMulator - Processing light4: false true false
Feb 26 21:09:12 centos01 java: 2019-02-26 21:09:12,230 [qtp1726125653-44] DEBUG com.bwssystems.HABridge.hue.HueMulator - Processing light5: false true false`

**Comment by bwssytems** [comment]
Yes, it looks like when Pull request #712 was committed.

**Comment by bashers222** [comment]
Looking at #712, do i need to create a defaul room or scene?
Is that with the Phillips Hue App?

**Comment by bwssytems** [comment]
You could do that, but its a manual entry in the groups file. You would have to follow the instructions that FloFloer provided

**Comment by xrusher** [comment]
Hello,
also trying to get this working but somehow I'm lost...
I tried to edit the group.db to get a default room but I can't find exact informations about that procedure in the thread from FloFloer. I can see all my Lights in the Pop app but can't switch them (same with bashers222 in this threat here).
Maybe someone here is using the Logitech Pop switches with ha-bridge and can help.

**Comment by bashers222** [comment]
i found an earlier thread highlighting where things were changed re room setups
rolling back to version 4.5.6 fixed it .
theres no features i required in the new versions

**Comment by xrusher** [comment]
Thanks for this Info. Too bad it's not working within the actual version. I had many problems with lags and dimming issues within my Harmony setup with the versions before and now everything is running really smooth so I dont want to go back only for this. 
Actually I use the Harmony activities as a workaround to switch lights and press keys wit the POPs. But for this I have to create an own activity for every light/key/group I want to use and also can't toggle or switch more than one of these activity with a keypress... so using the Pop-Switch again  directly with ha bridge in the actual version would be really helpful. 
Maybe this can be implemented somehow again?
