### ISSUE TITLE
probable non issue data/group data missing

### ISSUE THREAD

**Issue by npaisnel** [bwssytems/ha-bridge#1065]

**Comment by npaisnel** [comment]
Query really as everything seems to be working with 5.2.2RC3

Thought maybe group.db might be created after reboot of device, but no.

Error reading the file: data/group.db - Does not exist or is not readable. continuing...

under the startup log I am seeing the above Warning.
5.22RC3 just installed

other files within 
/home/pi/habridge/data are:
`pi@x10:~/habridge $ cd data
pi@x10:~/habridge/data $ ls
device.db                         habridge.config
device.db-2018-10-01-18-58-56.bk  habridge.config-2019-03-04-10-20-47.cfgbk
pi@x10:~/habridge/data $ pwd
/home/pi/habridge/data
pi@x10:~/habridge/data $ 
`
all X-10 devices seem to work dim/bright of all lights works as expected so far. 
No Echo Gen 3 devices, all gen 2

Only items I have on my system are X-10 devices.

Is this missing group.db file going to cause any issues?

**Comment by audiofreak9** [comment]
Non issue, you would create the group.db manually, originally introduced here: https://github.com/bwssytems/ha-bridge/issues/713
