### ISSUE TITLE
Question: switches / dimmer for tuya bulbs via home assistant

### ISSUE THREAD

**Issue by Alfiegerner** [bwssytems/ha-bridge#1066]
Hi, noob here, apologies if this obvious.

I have this set up to control my tuya bulbs from harmony remote via home assistant.

Next step is to add wall switches: can I use Phillips dimmer or other hue compatible switches with habridge? If not any recommendations on how to implement? I have attached gang switch plate with 1 of the switches being a three way hallway switch.

TIA!

**Comment by audiofreak9** [comment]
The HA-Bridge does not control Philips devices, it discovers as a Philips HUE Bridge to control other systems such as a Vera, Harmony Hub, HAL, LIFX, HomeAssistant, HomeWizard, Domoticz, OpenHAB, FHEM, Nest, MiLight bulbs, mqtt devices or any other system that has an http/https/tcp/udp/command interface.  You would need a hub (Philips HUE Hub for example) that can control your Philips dimmer, of which you would be able to interface with HA-Bridge.

**Comment by Alfiegerner** [comment]
Thanks @audiofreak, just what I needed to know.
