### ISSUE TITLE
memory leak ? 

### ISSUE THREAD

**Issue by MattL0** [bwssytems/ha-bridge#1069]
New to ha bridge. 

Does ha-bridge have a memory leak?

After 1 hour it went from 0.5% to 1.3% of 15.7 gb.  ( 0.2 gb). I reproduced this 3 times now. I'll check again tomorow after a longer period.

I saw somewhere that the log is kept in memory... is there a way to turn off the log?
Or maybe this is just a leak.
My system is ubuntu server x64 and i'm running ha bridge 5.2.2rc3

thanks

**Comment by bwssytems** [comment]
200MB is not bad, mine runs at 340MB on a raspberry pi.

**Comment by MattL0** [comment]
Ok it is about this I think . It is now 1.4% since i posted.

So it seems stable at 220mb. Maybe it will go a little higher as I add more device (curently have 6).

Btw thanks for this program . It is awesome !

**Comment by MattL0** [comment]
Will just let this go one more day. Before marking it resolved , if you do not mind ? Thanks

**Comment by MattL0** [comment]
Seems to be stable at 1.4%
