### ISSUE TITLE
No devices detected!

### ISSUE THREAD

**Issue by LukeTheDukester** [bwssytems/ha-bridge#1070]
Hi everyone!

I'm running ha-bridge on a raspberry pi just to control some lights. Worked perfectly for ages but recently I added a couple of new echo dots and upgraded to the latest release of ha-bridge.  All seemed ok but suddenly (a few months back) Alexa lost all the devices and now fails to detect them again.  I've tried everything I can think of. I've done all the things suggested to do in the FAQs and suggestions I've found in previous support posts but nothing seems to work.

Attached is the log after turning on trace upnp.  Would be grateful for any help or suggestions.

Thanks,
Luke.

[log.txt](https://github.com/bwssytems/ha-bridge/files/2960462/log.txt)

**Comment by bwssytems** [comment]
What are the addresses of the echos? Are you using the link button when Discovery is occurring?

**Comment by LukeTheDukester** [comment]
Hi,

IP Addresses of the Echos are:
192.168.0.113
192.168.0.16
192.168.0.115
192.168.0.110
192.168.0.82

Yeah - using the 'Link' button but that has never made a difference to discovery.

Thanks.

**Comment by bwssytems** [comment]
So, Only 2 devices have even communicated with the ha-bridge, 192.168.0.85 and 192.168.0.117 as far as this log shows. You might want to do a request on the echo to discover new devices and then post the log again.

**Comment by LukeTheDukester** [comment]
Hi - thanks for helping but after hours of trying to sort it I went back to version 3.1.0 and it found all my devices again first time.  I'll stick with that for now until a newer version at which point I'll try that.

Thank you and thanks for a great piece of software!
