### ISSUE TITLE
Error reading db-files

### ISSUE THREAD

**Issue by Stephan811D** [bwssytems/ha-bridge#1071]
Hi,
when my ha-bridge starts i get those errors:
![image](https://user-images.githubusercontent.com/37579239/54869837-9155c680-4d9e-11e9-90a4-5fa49899a8f7.png)

i don't know whats wrong .. the files are in the right folder ... i already changed the rights to 777 for the device.db .. no affects.

ha-bridge folder looks like this: 

![image](https://user-images.githubusercontent.com/37579239/54869879-f4dff400-4d9e-11e9-9f44-f05775d1a575.png)

web-inteface config looks like this:

![image](https://user-images.githubusercontent.com/37579239/54869888-0aedb480-4d9f-11e9-9f6b-82a33117cc42.png)

thanks in advance

Stephan

**Comment by bwssytems** [comment]
So, your device.db file is not specified on the startup path.This puts it in the default path of /root as this is started from a service. Add your device.db path to the startup.
