### ISSUE TITLE
Bacnet IP write property

### ISSUE THREAD

**Issue by sjpkt** [bwssytems/ha-bridge#1072]
There is an object instance for setpoint temperature but it does not seem I can set a new temperature via node red. Once I check the property of that object instance, there is no priority array and its priority is 16. In the manual, it says to make it writable the object need to be set it "out of service." I try to set it out of service using bacnet write in node-red, error occured "BacnetAbort -Reason 6.
How to make object instance writable?

**Comment by bwssytems** [comment]
I believe you may be on the wrong project. ha-bridge is not a node application, it is pure java.
