### ISSUE TITLE
Basic authentication with 8266 milight hub alternative

### ISSUE THREAD

**Issue by dougdalton** [bwssytems/ha-bridge#1073]
connecting to the 8266 milight hub alternative

I have habridge 5.2.2 rc 3 set to : 

Type: HTTP Device
Target Item: http://admin:password@192.168.2.4/gateways/0x5685/rgbw/1
HTTP Verb: PUT
HTTP Headers: [{"status":"off"}]
Content type:  application/json

I am gettting the error: 
2019-04-14 12:15:53,782 [qtp1030734556-12] ERROR spark.http.matching.GeneralError - 
java.lang.IllegalArgumentException: Header name may not be null

Perhaps I have the settings wrong

**Comment by bwssytems** [comment]
That's interesting as that is the ha-bridge internal webserver displaying that message. Could you turn on debugging for the HueMulator class and post the log.

**Comment by dougdalton** [comment]
com.bwssystems.HABridge.hue.HueMulator
--
04-20-2019 02:17:39.047 | DEBUG | Decode Json for url items: [{"item":"http://admin:password@192.168.2.100/gateways/0x5685/rgbw/1","type":"httpDevice","httpVerb":"PUT","httpHeaders":"[{\"status\": \"off\"}]","contentType":"application/json"}] | com.bwssystems.HABridge.hue.HueMulator
04-20-2019 02:17:39.048 | DEBUG | Calling Home device handler for type : httpDevice | com.bwssystems.HABridge.hue.HueMulator
04-20-2019 02:17:39.048 | DEBUG | executing HUE api request to Http PUT: http://admin:password@192.168.2.100/gateways/0x5685/rgbw/1 | com.bwssystems.HABridge.plugins.http.HTTPHome
04-20-2019 02:17:39.048 | DEBUG | doHttpRequest with url <<<http://admin:password@192.168.2.100/gateways/0x5685/rgbw/1>>>, verb: PUT, contentType: application/json, body <<<null>>> | com.bwssystems.HABridge.plugins.http.HTTPHandler
04-20-2019 02:17:39.048 | DEBUG | header index 0 name: <<<null>>>, value: <<<null>>> | com.bwssystems.HABridge.plugins.http.HTTPHandler
04-20-2019 02:17:39.048 | DEBUG | Making outbound call in doHttpRequest: <<<PUT http://admin:password@192.168.2.100/gateways/0x5685/rgbw/1 HTTP/1.1>>> | com.bwssystems.HABridge.plugins.http.HTTPHandler
04-20-2019 02:17:39.048 | ERROR |   | spark.http.matching.GeneralError

**Comment by dougdalton** [comment]
I had the request in the headers not the correct body section

**Comment by bwssytems** [comment]
So all good now? The General Error you see is that something is calling the ha-bridge with a URL it does not know.

**Comment by dougdalton** [comment]
yes sorry it is all working now
