### ISSUE TITLE
DreamScreen implementation possible?

### ISSUE THREAD

**Issue by scholzmichael** [bwssytems/ha-bridge#1075]
Would it be possible to integrate DreamScreen (4k) DIY in HA-Bridge?

https://www.dreamscreentv.com/

**Comment by audiofreak9** [comment]
Looking their site over, I don't see an API.  Do you know of one?  They do state, 
> "We are already working on integration with other devices, such as Amazon Alexa, Google Home, etc. We are working on getting into contact with Logitech as cooperation from them is needed for integration with their device."

**Comment by scholzmichael** [comment]
API can be found on their Forum (subscription needed). [http://dreamscreen.boards.net/thread/293/dreamscreen-wifi-udp-protocol](url) I could also send it if you let me know which way is preferred...

**Comment by audiofreak9** [comment]
Follow DreamScreen’s UDP protocol to create UDP devices in the HA-Bridge.

**Comment by scholzmichael** [comment]
Will do that anyway, but a native implementation would have been nice..

**Comment by bwssytems** [comment]
If the API does not support getting info of scenes or other information, it is not prevalent to build a helper tab. This would be similar to milight.

**Comment by scholzmichael** [comment]
As far as I understand it does as I read in the "Device Discovery and State" section of the attached PDF. Well I'm not a native (English) Speaker so I may misunderstand it...

**Comment by bwssytems** [comment]
So looking at this again, you should be able to build your own udp messages using the udp protocol in ha-bridge with the hex conversion available.

**Comment by scholzmichael** [comment]
I did implement it using the following python script which was already available on github: [https://github.com/genesisfactor/DreamScreenCommander](url)
It works fin, thank's.

**Comment by boldiebold** [comment]
> I did implement it using the following python script which was already available on github: [https://github.com/genesisfactor/DreamScreenCommander](url)
> It works fin, thank's.

Hi Michel,, as a newbie could you be so kind and share some screenshots or infos how you made the integration with dreamscreen happen. Thanx

**Comment by scholzmichael** [comment]
@boldiebold 
you can see that I included it in a Harmony action, in my case called "Fernsehen" which starts TV, AVR and satellite receiver, then start dreamscreen, after that sidekick left, and finally sidekick right.
What I did is copy the DreamScreenComander.py 3 times(once for dreamscreen, and once for each sidekick as they have of course different IP addresses) to my pi at /opt/dreamscreen and then just call the script in line 2,3, and 4, thats basically all. All you need to do after copying the script is to adjust the IP address within the script to your dreamscreen IP address.
