### ISSUE TITLE
Not able to install ha-bridge in hassio 0.91.4

### ISSUE THREAD

**Issue by pradeepmilly** [bwssytems/ha-bridge#1079]
I am not able to install ha- bridge  add-on in hassio 0.91.4 , did a full wipe out & re installed the hassio even then it's not getting installed, any help here would be appreciated, thanks in advance

**Comment by bwssytems** [comment]
If this is part of the Hass.io install, please post in their forum. We did not build that add on install.

**Comment by bwssytems** [comment]
I'm assuming you have posted this issue on the hass.io forums.
