### ISSUE TITLE
Passing a variable

### ISSUE THREAD

**Issue by dougdalton** [bwssytems/ha-bridge#1080]
with Milight, it it possible to allow an alexa call to pass a variable through ha bridge, for example to set the mode to 1 - 8 for the "disco mode"  rather than having to make a specific call for each?

**Comment by bwssytems** [comment]
You could use the dim capabilities as percent. So you would tell the milight "Alexa, set milight to 2" and using the {{intensity.percent}} variable would give you that.

**Comment by dougdalton** [comment]
perfect, great idea
