### ISSUE TITLE
intermittent tcp problem

### ISSUE THREAD

**Issue by odinlake** [bwssytems/ha-bridge#1083]
I used "tcp://server:port/myCommand" to forward commands to my custom tcp server. This works fine for a while and then stops working for a while. When it does not work, it seems ha-bridge opens and closes the tcp connection without sending any data. To check that the problem was not on my end, I also opened a tcp port using "nc" on a different linux device but found the same problem. I then thought I might have misunderstood something about ha-bridge, so I configured it additionally to make an http GET request (right after the tcp command) and I found that, when the problem happens with tcp, the http request still looks fine. So I think ha-bridge has a problem with tcp. 

As I would like to use it with a microcontroller, simple tcp would be preferable to http.

I'm running ha-bridge on a raspberry pi 3b+ with the latest rasbian os.

**Comment by bwssytems** [comment]
So, how long does it work for before it stops?

**Comment by odinlake** [comment]
It's pretty irregular, it may or may not work to start with. When I tried again recently it mostly did not work but then occasionally worked once or twice in a row.

**Comment by odinlake** [comment]
I should add that the behavior is the same whether I issue the command through Alexa or use the test buttons in the ui. When using the buttons, I see a green "ok" message and there is nothing strange in the log, irrespective of whether the tcp communication worked or not.

**Comment by bwssytems** [comment]
So far, I cannot replicate this in my test environment. So What version of the ha-bridge are you using?

**Comment by odinlake** [comment]
Thanks for trying. I cloned the repo, built with mvn, and installed as described in the readme.

**Comment by bwssytems** [comment]
Try the RC4 jar in the releases and see how that helps
