### ISSUE TITLE
Quit Putty stops Habridge

### ISSUE THREAD

**Issue by Marianke** [bwssytems/ha-bridge#1087]
I updated habridge to 5.2.2. and after closing putty after update habridge stops . I'll tried several times... whenever I quit Putty habridge stops

**Comment by bwssytems** [comment]
You'll need to setup a system startup for ha-bridge so it runs in the background under the system and not a terminal. https://github.com/bwssytems/ha-bridge#manual-installation-of-ha-bridge-and-setup-of-systemd-service

**Comment by Marianke** [comment]
thx.... I already got the file but had an - too much in the directorys name...
