### ISSUE TITLE
Synology Docker HA-Bridge 5.2.2 - discovery Alexa

### ISSUE THREAD

**Issue by maestroat** [bwssytems/ha-bridge#1088]
Hi, since 4 days i work but not function :(
i have install docker, than ha bridge, 
upnp ip: 192.168.1.2
Web Port: 81.
its online and i can work on webinterface, and its sends commands to device. 
my problem is that alexa nothing found from ha brdige :(
i have read many, change ports and so on, but nothing work so now i need pls help.
what you need from me  for help.

**Comment by maestroat** [comment]
one think was i have found, my synology has the correct time, but in log from ha-bridge always 2h back

**Comment by bwssytems** [comment]
With docker you will need to expose the interfaces to the host machine as the UPNP is multicast. This has been answered on the docker site here https://github.com/aptalca/docker-ha-bridge

**Comment by maestroat** [comment]
I know this site but its doesnt help me, or i dont understand it correct.
