### ISSUE TITLE
http-device über Logitech Harmony einschalten funktioniert nicht

### ISSUE THREAD

**Issue by darkman242** [bwssytems/ha-bridge#1089]
Hallo,
ich habe auf die HA-Bridge 5.2.2 aktualisiert (von 5.2.1). Ich habe 2 Sonoff-Geräte (mit Tasmota 6.5.0) als http-Devices eingerichtet. Diese kann ich sauber über die HA-Bridge-Webseite ein- und ausschalten. Die HA-Bridge habe ich mit einem Logitech-Hub gekoppelt um die Geräte über die Tasten der Fernbedienung schalten zu können.
Allerdings kann ich mit der HA-Bridge 5.2.2 über die Logitech Fernbedienung / Smartphone-App die Lampen/Schalter nur ausschalten - einschalten funktioniert nicht. Über die HA-Bridge-Webseite kann ich sie einschalten. Mit der Version 5.2.1 der HA-Bridge funktioniert das Ein- und Ausschalten fehlerfrei.

**Comment by bwssytems** [comment]
Use this flag "On when Dim is present (Always uses on with a dim request otherwise it will ignore a given on was well. This is overidden by onFirstDim.)" in the edit device area as the remote sends DIM requests for on presses.

**Comment by darkman242** [comment]
Funktioniert, Danke

**Comment by bwssytems** [comment]
Herzlich Willkommen, Danke, dass du die ha-Brücke benutzt.
