### ISSUE TITLE
Ability to Edit Existing Vera Devices?

### ISSUE THREAD

**Issue by seanford** [bwssytems/ha-bridge#109]
ENHANCEMENT REQUEST:

Any chance you can add the ability to edit existing Vera Devices and scenes?  It would be easier to troubleshoot a device by editing it, rather than deleting and re-creating it.

**Comment by bwssytems** [comment]
In the configuration tab next to your created device, hit the Edit/Copy button.....

**Comment by seanford** [comment]
Ah yes, I was on the Vera tab.  Thanks.
