### ISSUE TITLE
habridge trigger url ?

### ISSUE THREAD

**Issue by GevaudanBeast** [bwssytems/ha-bridge#1090]
Hello, thanks for ha-bridge. Work nice.
I want to know if it’s possible to trigger with url an device in ha-bridge ?
Example : http://habridge/api/mydevice=on
Thanks you ?

**Comment by bwssytems** [comment]
That answer would be here: https://github.com/bwssytems/ha-bridge#hue-rest-api-usage

**Comment by GevaudanBeast** [comment]
Thanks, but, i test ./api/devices/14, it's ok.
But i don't understand how i can trigger the device 14 with url, i have try :
./api/device/14/state/on but response is 404...

**Comment by bwssytems** [comment]
Please read the link I posted as the ha-bridge emulates the HUE API for the device control

**Comment by GevaudanBeast** [comment]
I try, but not work.
Can you give me an example ?
Please

Cordialement,

Aurélien Faucon

**Comment by GevaudanBeast** [comment]
Good evening,
I will try to explain my request better.
Here is my goal: trigger by a url a bash script on the raspberry that hosts ha-bridge (camera snapshot).
the script works, and I would like to trigger it when my home server receives a support on the doorbell (no problem to fill an url and send it to the choice post / get or put).
I can not create a device that will execute my script and I do not disturb the url that I should use to launch it ...
my English is very weak and I can not find, thanks for your help.

**Comment by bwssytems** [comment]
This is the link to the http device state change request: https://github.com/bwssytems/ha-bridge#set-light-state

If you do not have link turned on in the security section the <username> can be anything and then the <id> is the number of the device you are trying to trigger. This is an HTTP PUT with a body as described in the link.

You can use curl to do this.

**Comment by GevaudanBeast** [comment]
So, if I understand correctly, I can not do it from the address bar of the browser.
So I will try as directed directly from my domotic server.
To run the script, I create a custom device and on the "on" function I put the local script address /home/xxx/script.sh?
Thank you

**Comment by bwssytems** [comment]
No, you will not be able to do this from the address bar on a browser as you need to send a PUT. Browsers only send a GET. You need to use curl or another command line http requester to get the PUT method.

**Comment by GevaudanBeast** [comment]
I thought I could do a PUT from then my domotic server, but the choices that are offered to me are: GET, POST or UDP is it okay? If, no, can I simply upload a file that will execute my script as in php?

**Comment by bwssytems** [comment]
Please read the documentation and I have said here that it is a PUT.

**Comment by tuicemen** [comment]
@GevaudanBeast  the Demotic forum should be able to supply some additional helpful info.
bwssystems has provided the  PUT info needed.

**Comment by bwssytems** [comment]
Any update?

**Comment by GevaudanBeast** [comment]
No solution for me, I have try with another lighthttpd service and that work.
