### ISSUE TITLE
Alexa Issue : ID conflict between HA  Bridge an Hue Bridge

### ISSUE THREAD

**Issue by StephaneM60** [bwssytems/ha-bridge#1093]
Hi,

I'm running the latest HA-Bridge 5.2.2 and since yesterday I'm experiencing something I can't explain : when using Alexa to turn on / off some devices handled by HA Bridge : some work fine, and some doesn't work any more.

All my devices were working properly for month now , so I don't know what is going on.

So if I'm using the HA Bridge Web Interface, devices are working properly (all devices are Domoticz devices) but when I use Alexa (either a physical device like a Dot, or the Alexa App) then some devices work and some don't.

I can't find any pattern that would explain why some works and other doesn't.

What debug info should I enabled to pinpoint the point of failure (I already looked in the logs but can't see any errors, neither I can spot a difference when using a working or non working device)

Does anybody have encountered an issue like this ?

**Comment by bwssytems** [comment]
I would do a discover devices again on the alexa

**Comment by StephaneM60** [comment]
I have done it : I removed one of the device that wasn't working, performed the discovery, Alexa found the deleted device just right. Trying to power on / off = nothing. And I can't see a difference in the logs between a working and non working device...

**Comment by StephaneM60** [comment]
So after a few attempts for recovering everything, this is what I have discovered : there is something very wrong with Alexa when using both HA Bridge and a real Hue Bridge at the same time and this is a new thing, as nothing has changed in my configuration (except automatic updates for Alexa and the Hue Bridge).

I removed all HA Bridge devices from Alexa, and detected them all again => same behavior those that work continue to work, those that doesn't continue to not working. I removed them all again, and unplugged all Echo devices except one Dot V2 and unplugged the Hue Bridge, all devices came back and they are all working as they should.

BUT : now some of my Hue devices stopped working in Alexa and even worse, when turning on a real hue device in Alexa, it doesn't turn on, instead it's a HA Bridge device that turns on...

So I removed the affected Hue Devices, stopped HA Bridge, detected devices again, Alexa found the removed one, and now I'm back to some HA Bridge devices not working again...

From what I understand : Alexa is sending request to turn on/off devices to the wrong bridge and it's the discovery process that mess everything up (and it doesn't matter if I turn off HA Bridge / Hue Bridge when detecting devices)

Any ideas ? Should I change IDs in HA Bridge (thouhg I can't seem to  be able to change the Hue ID)  ?

**Comment by StephaneM60** [comment]
Indeed it has something to do with IDs : I have exactly  20 hue lightn devices (and remote and sensors). The  HA Bridge devices that doesn't work do have IDs (second column on the Bridge Devices web page in HA Bridge) less than 20... those with IDs greater than 20 are working....

Moreover If ask to Alexa to turn on the HA Bridge device with ID 17, it does turn on a Hue device that is on row 17 in the Hue Devices page in HA Bridge...

**Comment by SelmaUrban** [comment]
Amazon has changed something there.

I had the same problem last night.
Alexa, turn on the Lights -> truns on the TV (same ID)
(Problem exists with and without hue and harmony skill activated)

My Workaround was to maually edit the device.db.
I change all IDs from 1,2,3,... to 100,101,102,...

After a new discover devices everything works fine.

So if this should be a feature and not a bug from Amazon,
a option to chose the start ID no. can be the trick.

**Comment by StephaneM60** [comment]
Yup I  changed the ID manually as well to recover.

Though @SelmaUrban I don't understand what you mean with  "problem exists with and without hue and harmony" ? For me : when I unplugged my hue bridge, removed all HA Bridge devices, started discovery : HA Bridges were working fine, as soon as the hue was plugged back, problem appeared again (and was aggravated by a new discovery)

I agreed a **custom seed number** for the IDs for renumbering could be handy, or maybe there is a smarter way to do it : **HA Bridge is able to connect to the Hue Bridge and can ensure IDs are not in conflict with Hue**...

**Comment by SelmaUrban** [comment]
@StephaneM60 only for information that the problem exists with and without activated alexa smart home skill for those two.

"What about people with 2 or more hue bridge" is the big question away from ha bridge.

**Comment by TRIROG** [comment]
Same issue here. Will try to change IDs

**Comment by bwssytems** [comment]
I will have the numbering start higher than 100

**Comment by bwssytems** [comment]
So , the new version will have an ID seed you can control in the bridge settings screen and it will renumber from that value.

**Comment by SelmaUrban** [comment]
Fantastic!
