### ISSUE TITLE
issue with 5.2.2 and Harmony

### ISSUE THREAD

**Issue by rmohsenn** [bwssytems/ha-bridge#1094]
I just updated to the latest version , it working well with Alexa and from the browser , but Harmony assigned buttons doesn't work anymore , I went back to 5.2.1 and it's working fine

**Comment by Ano10** [comment]
I have the same issue.

With ha-bridge 5.2.1
Everything work as expected with web browser, Alexa, Harmony remote and Harmony smartphone application.

With ha-bridge 5.2.2
Everything work as expected with web browser and Alexa.
Switch on device doesn't work with Harmony remote or Harmony smartphone application.
Switch off device work with Harmony remote or Harmony smartphone application.

What surprise me most is I can't switch on but I can switch off.

**Comment by bwssytems** [comment]
Please turn on debug for the HueMulator class in the Logs tab and post results after retyring

**Comment by Kniri** [comment]
You can fix this by setting the "On with First Dim" configuration switch to true. It seems that the Harmony Remote sends a DIM command instead of sending a ON command.

**Comment by Ano10** [comment]
You are right "On with First Dim" solve my issues. It now works as expected.
Thank you !

**Comment by bwssytems** [comment]
Working on the on and dim type commands in the next release.
