### ISSUE TITLE
issue with 5.2.2 and fhem

### ISSUE THREAD

**Issue by ammawel** [bwssytems/ha-bridge#1095]
Up to version 5.2.2-RC4 automatically created fhem devices work fine.
After updating to the latest version 5.2.2 I get the following error messages:

`Request Error, Please look in your habridge log: error {"type":"6","address":"/lights/1","description":"Error on calling url to change device state","method_name":"/lights/1state"}`

The device-target-item is 
`{"url":"http://127.0.0.1:8088/fhem?cmd=set%20ta_Test%20","command":"on"}`
and the log says
`Cannot parse command to FHEM <<<"{\"url\":\"http://127.0.0.1:8088/fhem?cmd=set%20ta_Test%20\",\"command\":\"on\"}">>>
com.bwssystems.HABridge.plugins.fhem.FHEMHome`

Went back to RC4 and all ist working fine again.

**Comment by marcelfischer** [comment]
Having the same problem when changing the command for a device

**Comment by marcelfischer** [comment]
Could someone provide a jar file for 5.2.2 RC4?

**Comment by bwssytems** [comment]
will take a look

**Comment by bwssytems** [comment]
So, it looks as the url in the error above has beginning quotations and ending quotations. The builder does not put those in. 

Are these custom built commands?

**Comment by ammawel** [comment]
No, they are fhem-devices and the bridge-devices were created by ha-bridge from the fhem plugin.
When exchanging the jar file for V5.2.2-RC4 the commands of the bridge-devices created in this way work.

The definition of the target items, e.g. {"url": "http://127.0.0.1:8088/fhem?cmd=set%20ta_Test%20", "command": "on"} is done with V5.2.2 as before, there is no difference.
The error must be in the evaluation.

The screenshot shows the bridge-device created by the fhem-plugin, definition as usual, works up to RC4 including

![bridge-device created from fhem-plugin](https://user-images.githubusercontent.com/51128844/58657524-ba568280-831e-11e9-8af2-587aa2f23939.png)

**Comment by bwssytems** [comment]
I am putting in checks for json object versus string to help.
