### ISSUE TITLE
List item as switch Instead of dimmer. 

### ISSUE THREAD

**Issue by justintime1976** [bwssytems/ha-bridge#1096]
I am running HA bridge on a Pi with Domoticz.

Now i have set up a second PI with Openhab to get Google Home integration.

All switches in OpenHab will come in as dimmers because the unique name is hue:0100:********

My problem is when I change the switch in openhab to rollers shutter openhab wil regonize it as a dimmer rollershutter so you can set at certain percentage. Which I don't have. 
It will only close and open with set of percetage and not with buttons. 

I could set up as a switch in OH but than GH only accept curtains on/off instead open/close.

So please let us choose in HA bridge the type of switch sent to OH.

**Comment by bwssytems** [comment]
I would have to check to see if there is a hue device that would be identified as a switch as most all hue products would support dimming. OpenHAB is defaulting the device to a dimmer as that is what it thinks it should do with a Hue Device. You maybe better off asking OpenHAB team to be able to change the type and customize.

**Comment by bwssytems** [comment]
I will close this as there is nothing that we can do for the openhab interface as limited by the Hue API.
