### ISSUE TITLE
Home Assistant has new authentication methods and Legacy API Passwords will be removed

### ISSUE THREAD

**Issue by Cardy165** [bwssytems/ha-bridge#1098]
Hi I have just been linking my habridge to Home Assistant but I had to add an API key to home assistant. 

It appears from documentation located on this page [https://www.home-assistant.io/docs/authentication/providers/](url) that the current API method of authentication is going to be removed.

From the above page: "LEGACY API PASSWORD:  Warning: This is a legacy feature for backwards compatibility and will be dropped in a future release. You should move to one of the other auth providers."

I looked for another issue relating to this but couldn't see one. I am guessing at the point Home Assistant removes the Legacy API support habridge will no longer be useable with Home Assistant.

**Comment by bwssytems** [comment]
Just need to add the bearer token login for the new authentication.

**Comment by bwssytems** [comment]
There will be a switch to select legacy login with the password and the default will be the bearer token.

**Comment by Twit123** [comment]
Hi,

Just a heads up for anyone trying the new long lived token. I first had to go in and tick the legacy password box and save. HA Bridge then connected as it always has. I then pasted in my long lived token and unticked the box to get the new way to work.

Just going straight in and pasting the token in caused errors and it would not connect.

Thanks for the great work.

Simon

**Comment by bwssytems** [comment]
Interesting, I had no issues when I setup HomeAssistant to use the token only. But if it works, it works!
