### ISSUE TITLE
Disable the web interface for user, but not the whole web service?

### ISSUE THREAD

**Issue by martijintro** [bwssytems/ha-bridge#1099]
Is that possible, so nobody can visit the habridge GUI page on http://w.x.y.z/#!/ ?

Thank you for your feedbacks.

**Comment by bwssytems** [comment]
It could be done but there is not a way to configure that currently.

**Comment by martijintro** [comment]
ok thx - theoretically, because the source code is open! ;-)

**Comment by bwssytems** [comment]
Yes it is, but if you use the key as described here https://github.com/bwssytems/ha-bridge#-dsecuritykeyyour-key-to-encrypt-security-data, it will be secure for internal home use. I would never suggest that any system you have on your home network be exposed to the internet and that includes any commercial products.

**Comment by martijintro** [comment]
thank you for your informations!! :-)
