### ISSUE TITLE
Echo discovers more devices than configured?

### ISSUE THREAD

**Issue by VPsych** [bwssytems/ha-bridge#110]
I'm having an odd issue where Echo's discovery finds previously configured items that have since been deleted from the HA-Bridge. Running device discovery will return 42 smart home devices yet only 29 devices are currently configured on the HA-Bridge. I recognize some of the older devices since they were previously configured but have been since deleted. The bridge has also been restarted. 

Deleting all the Smart Home devices from the Alexa or Echo's web interface doesn't seem to matter. It'll re-discover them when a re-discovery is done.

**Comment by audiofreak9** [comment]
Sounds to me like a second instance of the bridge is running.  Enter: `$ ps -ef | grep java` to see what all is running.

**Comment by VPsych** [comment]
```
root@DiskStation:~# ps -ef | grep java
root     21965 21923  0 13:53 pts/2    00:00:00 grep --color=auto java

```

**Comment by bwssytems** [comment]
a question, did you do a forget all devices first on the echo?

**Comment by VPsych** [comment]
Yes. I've tried using the Alexa app , verbally, and via the website. After forgetting no devices are listed. I then rediscover (via the app., verbally, or website). It discovers 42 devices. It seems that it's discovering previously configure but deleted devices but also all my Hue lights despite not pressing the link button or configuring all the Hue lights on the bridge.

**Comment by bwssytems** [comment]
Ahh, people have had issues when doing a discover and the real hue is connected. Disconnect your real hue bridge and do a forget and re-discover.

**Comment by VPsych** [comment]
That worked! Down to 29 devices. =)

**Comment by audiofreak9** [comment]
Well, not a second instance, but a real instance of a real HUE, glad you got it to work.
