### ISSUE TITLE
HA bridge port 80 and google home not working

### ISSUE THREAD

**Issue by GravityRZ** [bwssytems/ha-bridge#1101]
spend a lot of time trying to get things to work.

port 80 is default forwarded to 5000 on synology so i was trying to solve this problem.

i could not gret goofle home/assistant to recognize the habridge because it kept on sending be to the hue landing page.

now it turns out that this is caused by the latest google home version.

is there any way to get ha bridge to work with google home/assistant or is this functionality killed forever?

ISSUE: Google Home now seems to not support local connection to Philips Hue Hubs and requires that it connect to meethue.com. Since the ha-bridge only emulates the local API, and is not associated with Philips, this method will not work. If you have an older Google Home application, this may still work. YMMV.

**Comment by bwssytems** [comment]
Google home is dead for ha-bridge. Other systems may have support such as OpenHAB which built a cloud connector.

**Comment by GravityRZ** [comment]
thanks. did not know that
