### ISSUE TITLE
Parameter "upnpstrict" in configuration file?

### ISSUE THREAD

**Issue by jmar83** [bwssytems/ha-bridge#1102]
I saw that parameter in the habridge.config file, but there are not many informations about it:

https://www.google.com/search?ei=IqkCXd_8CZCvmwXz2J2ACw&q=site%3Agithub.com+%22upnpstrict%22+%22ha-bridge%22&oq=site%3Agithub.com+%22upnpstrict%22+%22ha-bridge%22&gs_l=psy-ab.3...1774.4612..4775...0.0..0.111.1040.11j1......0....1..gws-wiz.0MuuhpoZyXU

...and i saw no related configuration option in the HA-Bridge Web GUI. Maybe that parameter is from an earlier version and is obsolete?

Thank you for your feedbacks.

With kind regards,
Jan

**Comment by bwssytems** [comment]
It was from an earlier version and it became the standard. In V5.3.0 it will be deprecated.

**Comment by jmar83** [comment]
Thx. So "true" is the standard? Is there a documentation about it? And there is really no GUI option for it, right?

**Comment by bwssytems** [comment]
Nope, and it was there for testing purposes a while ago when we switched to a tighter upnp selection method. In V5.3.0 we added the ability to be a little more flexible and there is now an option to use an older upnp search method.

**Comment by bwssytems** [comment]
Inserted into the Community information https://github.com/bwssytems/ha-bridge/wiki/Informational-Items-Collected-from-the-Community#q-parameter-upnpstrict-in-configuration-file
