### ISSUE TITLE
Have single scroll bar for Bridge Devices page.

### ISSUE THREAD

**Issue by gohamstergo** [bwssytems/ha-bridge#1103]
Would it be possible to remove the inner frame and just have the devices show on the top layer? (not sure of the proper terminology here). That way there would only be one scroll bar to make your way down the page. Not sure what's possible, just throwing it out there.

Thanks as always for such an awesome program.

edit: i saw in another ticket that you're using a scrollable table from another author. I'm curious if there is an option in the table to simply expand to max size automatically. That could remove the scroll bar of the table perhaps...

**Comment by bwssytems** [comment]
I had this way thinking it would be easier to get to the backup items. But it probably makes more sense to have one scroll bar. The logs tab works that way too. I'll deprecate that.

**Comment by gohamstergo** [comment]
looks great in RC3!

**Comment by audiofreak9** [comment]
I second that, much better UI experience on mobile devices as well.

**Comment by bwssytems** [comment]
Awesome, glad you like it!

**Comment by gohamstergo** [comment]
since all is well, i'll close. :)

**Comment by bwssytems** [comment]
I'll keep this open until the merge

**Comment by bwssytems** [comment]
I also added for the final version a floating back to top button that will appear after you start scrolling
