### ISSUE TITLE
Add HTTPS to ha-bridge

### ISSUE THREAD

**Issue by bwssytems** [bwssytems/ha-bridge#1109]
Have the ability to use https for the api and web pages.

**Comment by audiofreak9** [comment]
The HTTPS info, including the Use HTTPS checkbox in the Security Settings on HA-Bridge don't remain set after re-initialization or restart?

**Comment by danwooller** [comment]
@audiofreak9 this is the problem I have, assumed it was me not understanding how it's supposed to work. Interestingly, the bridge goes offline if you just check the box but don't enter the other details.

**Comment by audiofreak9** [comment]
@danwooller 
> Interestingly, the bridge goes offline if you just check the box but don't enter the other details.

I am not seeing that behavior, just never able to run bridge in HTTPS.

**Comment by bwssytems** [comment]
If you check the box, you should have setup a keystore with a password as per the instructions. If you don't, it gets stuck with an invalid https setup.
