### ISSUE TITLE
Unable to load JDK7: no Java7 support added

### ISSUE THREAD

**Issue by jluc2808** [bwssytems/ha-bridge#1112]
running 5.3.0RC10 as docker on synology DSM 6.2.2

i have installed java7 and added to the docker environment $PATH java7, but i get a warning 

Jul 16, 2019 7:52:58 AM com.fasterxml.jackson.databind.ext.Java7Support <clinit>
WARNING: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added

does this mean i forget something ?

**Comment by bwssytems** [comment]
Interesting, the ha-bridge release is compile with Java8, but it looks like the Synology java does not have the support for that package.

**Comment by jluc2808** [comment]
previously i have added java8 package within my synology and i got this warning, so i reinstall java7 and set the java7 to $PATH before the java8 environment

**Comment by bwssytems** [comment]
Is this all working for you?
