### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by martijintro** [bwssytems/ha-bridge#1114]
What is that?
-> Current RC12 Version

```
Jul 25 15:19:05 xaxada-0800270f2789 java[1881]: Exception in thread "main" java.lang.NullPointerException
Jul 25 15:19:05 xaxada-0800270f2789 java[1881]:         at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:170)
Jul 25 15:19:05 xaxada-0800270f2789 java[1881]:         at com.bwssystems.HABridge.HABridge.main(HABridge.java:58)
```

**Comment by bwssytems** [comment]
not sure. Please post this in the RC testing thread please.

**Comment by martijintro** [comment]
it seems habridge has truncated the habridge.config file to 0 bytes.

anyway, will go back to previous version

**Comment by bwssytems** [comment]
You can go back only if you backed it up.

**Comment by bwssytems** [comment]
Also, what steps did you take before this happened so it can be reproduced.

**Comment by martijintro** [comment]
Will go back to default config i mean.

The thing i've some is startign it a few times, and i can't imagine that there is anther process that truncated the file.

**Comment by martijintro** [comment]
same problem with previous RC8 version.

somewhere i have that line to update the ip in a perl script:

```
`jq '.upnpconfigaddress = "$ip"' /opt/habridge/data/habridge.config | sponge /opt/habridge/data/habridge.config`;
```

Maybe the ha-bridge process updates the habridge.config file from time to time, and there is a confilct between ha-bridge and the shell command line i use in perl script with "jq" and "sponge"...?

**Comment by martijintro** [comment]
the perl script will also be applied from time to time, and not just once. because of that, maybe there is a confict between the two things, which results in a 0 byte habridge.config?

**Comment by bwssytems** [comment]
That would be the conflict. Updating another processes file may result in unknown behavior.

**Comment by bwssytems** [comment]
I am closing this as you should not run that script when the ha-bridge is running.

**Comment by martijintro** [comment]
So it's impossible to use another method to change the config file than the web gui?

Do i need some paramters for habridge jar in that case - only one way?

**Comment by martijintro** [comment]
Maybe a workaround, example in perl:

```
        my $filesize = (stat("/opt/habridge/data/habridge.config"))[7];

        if($filesize > 0)
        {
                `jq '.upnpconfigaddress = "$ip"' /opt/habridge/data/habridge.config | sponge /opt/habridge/data/habridge.config`;
        }
```

**Comment by bwssytems** [comment]
That will help, but still not guaranteed. You could call the settings api with Curl and a script. You would need to send one request to get the settings, modify it in the script and send the settings back. It is in Json.

The call to get the settings is ```http://<ip:port>/system/settings``` and to set it is to call a PUT method on ```http://<ip:port>/system/settings``` with the json payload of the settings you retrieved by the GET.
