### ISSUE TITLE
Alexa to HA-Bridge to Harmony to Control X-10

### ISSUE THREAD

**Issue by npaisnel** [bwssytems/ha-bridge#1119]
I am not quite sure what harmony Hub itself, the actual hardware can do yet in relation to HA-Bridge and X-10 devices and Alexa, and spending £160 UK pounds or more to find it is not what I need is not an option.

So simple question..not asking for a How TO or a walk through or anything (yet ..) but just a simple yes or No ..it can or cannot be done.

Current system is 
All X-10 home devices
Latest HA-bridge as of 12th August 2019, running on Raspberry Pi 3B+
Two Echo Dots.

I can currently control all me devices via voice commands using Alexa..

My old Universal 'All in One 'including X-10  type remote control died the other day.

Yes if I get a Harmony hub and remote it will control my TV/DVD/Sky etc..but will I be able to link it all in via the harmony Hub page on the HA-bridge GUI?

Thanks

**Comment by bwssytems** [comment]
So, what software system do you use to control the X10 devices currently?

**Comment by npaisnel** [comment]
HA-bridge, is all I have

Control of X-10 stuff is either via the HA-bridge / Alexa or via standard X-10 remote control units.  Trouble is the same as every one ..multiple hardware remote controls. TV/Amplifier/DVD Sky X-10 etc.

Until a few days ago had a UR81SLR 'all in one' remote control that did all the devices and X-10 stuff.  Since that is dead, I want to replace it with somethings else.  Harmony Hyb device will only drive X-10 via an IR to RF convertor..which are no longer in production...

So I see HA -Bridge has harmony page...want to know if the Harmony page on the HA-bridge interface can drive th eX-10 CM11 controller...Works with Alexa..
Alexa-Ha-Bridge-Raspberry Pi-CM11- to powerline commands

**Comment by npaisnel** [comment]
Just lying in bed and a thought came to me about your question of what other software ... 

The commands I use to drive the X-10 devices are ‘HEYU’ commands...
I was thinking HEYU was part of HA-Bridge... but no I guess not

Would I be setting up a Heyu command in Harmony Hub Page in the same way the Alexa/ Philips Hue Page issues Heyu commands to the X-10 CM11

**Comment by bwssytems** [comment]
Ahhh, now that makes sense.

So, you just need the harmony hub to connect to the ha-bridge as it was a Philips Hub. Many people do this regularly. The lights should show up int the Harmony Hub config software (not the ha-bridge) and it will be able to control the lights as the Alexa does to the ha-bridge.

**Comment by npaisnel** [comment]
I don’t actually have a Philips Hue Hub, I thought it was HA-bridge that is pretending to be the Hue Hub.

Guess the only way now is to spend the money and try it.

Thanks

**Comment by bwssytems** [comment]
That is correct. The ha-bridge pretends to be a philips hue hub. That is how the magic works :)
