### ISSUE TITLE
No lamps paired with your hue bridge

### ISSUE THREAD

**Issue by McPostal** [bwssytems/ha-bridge#112]
I hope I'm just ignorantly missing a step.  I'm running HA-bridge 2.0.5 since today but started this yesterday with 2.0.4. I've created four devices from the Vera devices tab and they work when tested in the browser. Harmony hub sees and adds the HA-bridge as a hue hub but when I click on the hue hub in the Harmony app, it says "No lamps paired with your hue bridge."

**Comment by bwssytems** [comment]
I need to take a look at this as I haven't' paired the hub to the ha-bridge in a while.

**Comment by McPostal** [comment]
On the third day the devices showed up.

**Comment by bwssytems** [comment]
I do not have a good answer for that. I was trying to get into my Harmony App on my phone and it won't let me login. I can login on the web and my hue registration works with the ha-bridge, but the app doesn't let me go into setup. working on that.

**Comment by McPostal** [comment]
I didn't use a hue account. I skipped it in the harmony app.

**Comment by bwssytems** [comment]
Sorry I meant the harmony registration....

**Comment by bwssytems** [comment]
Closing as this is now working
