### ISSUE TITLE
Devices will not be found: HA-Bridge 5.3.0 / Alexa Echo Dot Gen. 2

### ISSUE THREAD

**Issue by martijintro** [bwssytems/ha-bridge#1123]
Device names for example (you can find them in the log):

- "einfahren"
- "garage"
- "brunnen"
- "schliessen"
- etc...

The virtual philips hue devices will be read from the devices.db (json) file, but the Alexa home automation device search process will not find them. Echo device was also restarted. (power off/on)

Log (Level "debug" and UPnP trace option on) are here: https://justpaste.it/3i5th

(BTW: How can i attach a file here??)

Thank you for your feedbacks.

Best regards,
Jan

**Comment by tobit6795** [comment]
same here with gen1 echo dot (german location)

**Comment by hokie21** [comment]
I have the same situation here with Gen 2 echo dot and version 5.1.0.  Running the trace option and wireshark and I don't see any communication between the Echo and the HA-Bridge. It used to be that Alexa worked with HA-Bridge without having the Phillips Hue skill installed. Has this changed? When attempting discovery, Alexa asks me if the skill is installed for my smart home device.

I restored my working Raspberry PI configuration from backup and I still have "family room lights is not responding." I think something has changed on the Alexa end. This RPI disk image has always worked in the past and nothing else has changed that I am aware of.

**Comment by martijintro** [comment]
How does it work with the current 5.3.0 version? Same problem?

**Comment by evilmumi** [comment]
have the same problem. do you run it on port 80?

**Comment by mzielinskim** [comment]
I also have the problem. I used 5.2.1 and eerything workend. Then Alex said "not repsonding". after that i deleted all devices from alexa and tried to serach again. i also uodated to 5.3.0 and searched in every way. search for hue bridge v1, search for all devices. with and without "link button" in HAbridge. I even deleted unused devices and renumbered them - nothing helps. in the log i see that Alex talks via upnp to habridge but still "no devices found".
I even totally reset the echo dot 1.gen but nothing helps.
i use habridge with http devices.

**Comment by bwssytems** [comment]
I will need the traceupnp log for a discovery with ip addresses of the alexa and other devices looking to find the ha-brige to help you debug

**Comment by timberhisarmswide** [comment]
I too have this problem. Alexa stopped communicating with my devices a couple of days ago. The commands work from the HA Bridge but no communication between Echo and the bridge. Alexa does not see any of my devices when I perform a discovery.

**Comment by hokie21** [comment]
Here is my log: [https://justpaste.it/3uq4m]
192.168.0.51 is HA-bridge
192.168.0.88 is a Windows 7 PC that for some unknown reason seems to be talking to HA-bridge for UPNP discovery
192.168.0.63 is Alexa (who doesn't seem to show up in this log). 
This log was started before I told Alexa to "discover devices" and was stopped after she said she couldn't find anything.

**Comment by mzielinskim** [comment]
This is my log: https://justpaste.it/3sfus
192.168.1.55 is the echo dot v1

**Comment by martijintro** [comment]
The problem seems to be the following:

There are MANY different hardware revisions of the echo devices - it depends where you bougth them.

And that different hardware revisions have different firmware. For example, hw revision 1 is the newest firmware 1.01, for hw revision 2, the newest firmware is 1.03, for hw revision c, the newest firmware is 1.03 (these are just examples!!)

And amazon seems to be unable to ensure that ALL that firmware version have the same behavior. (at least from outside)

So the echo devices are 100% black boxes, and they are completely uncontrollable on their behavior.

P.S.: You can force the upgrade to most current firmware, but you will see, if you have many different devices (hw revision), the most current firmware will not be same.

Alexa is NOT a serious (so not eligibe for serious, business-critial applications), it's just a gimmick - nothing else..

**Comment by mcwieger** [comment]
Have the same issue, HA-Bridge 5.3.0 on Synology DS414.

**Comment by bwssytems** [comment]
@hokie21 Your Alexa did not even send out a upnp search message at all. Do you have the philips hue alexa skill installed?

**Comment by bwssytems** [comment]
@mzielinskim You will need to run on port 80 for the ha-bridge.

**Comment by martijintro** [comment]
@bwssytems:

Don't understand - web server port has nothing to do with smart home device search?

Alexa Gen3 devices need http port 80 to switch, AFTER the devices was correctly found with udp/upnp.

Dot 2 devices work on our systems with ha-bridge port 81 - no problems.

**Comment by bwssytems** [comment]
It won't hurt if he tries it. As the software versions that are out there, an update that he is running may require port 80. His alexa is sending the search and the ha-bridge is responding, but his alexa is not requesting the lights list from the ha-bridge as that is the final piece of the handshake.

**Comment by bwssytems** [comment]
Oh, and to answer your question, the webserver port has everything to do with the search as it is also the port that the API runs on as well.

**Comment by mzielinskim** [comment]
Thanks - with Port 80 it works now. Although it worked with port 8080 until some days ago...

**Comment by hokie21** [comment]
I had not had the Phillips Hue skill installed with my Alexa previously and it worked just fine. I attempted to install the skill recently. The Phillips Hue installer failed with "There are no bridges on your network."

**Comment by bwssytems** [comment]
@hokie21 Ok, do not install the alexa skill for the hue as it is not needed ant it can cause problems with the ha-bridge.

How are you running the ha-bridge? machine type, os type, docker?

**Comment by hokie21** [comment]
I'm running it directly on a Raspberry Pi model 1. The command line reports Debian 9.3 with a 4.9.80+ Kernel version. Processor is an ARMv61.

**Comment by bwssytems** [comment]
@hokie21 Check your router to see if it is filtering upnp messages as your log shows that it did not receive any messages at all from echo 192.168.0.63.

**Comment by hokie21** [comment]
The UPNP messages are from the Alexa to the Habridge server, right? These devices are on the same subnet so the router wouldn't come into play, right? I've attached a Wireshark pcap file showing all Alexa communication during a "discover devices."
[alexa discover.zip](https://github.com/bwssytems/ha-bridge/files/3585856/alexa.discover.zip)

**Comment by wilme2** [comment]
"Thanks - with Port 80 it works now. Although it worked with port 8080 until some days ago..."
"Have the same issue, HA-Bridge 5.3.0 on Synology DS414."
So port 8080 is no longer supported?  This is a problem for us running the bridge on a Synology where port 80 is the Synology web GUI...

**Comment by dinkybluebug** [comment]
Mine was always on port 80 anyway - but I think this is by default. Any ideas as to why this might have stopped working?  Any chance that web interface is running on port 80, but alexa thinks its on a different one?

**Comment by wilme2** [comment]
So I got on with Amazon CS, and they had me switch profiles on one of my Echo Dots and discovery works again.  I even set my port back to 8080 and it works.  Frustrating neither the Android or Windows apps can discover correctly - but once I did a discovery on a Dot in my own profile, it works.  I am back to adding devices...

**Comment by dinkybluebug** [comment]
Wilme2 that doesn’t work for me. I switched accounts - did ‘Alexa discover my devices’ and no new devices. Very frustrating.

**Comment by dinkybluebug** [comment]
@wilme2 thats worked for me now too - thanks

**Comment by evilmumi** [comment]
> So I got on with Amazon CS, and they had me switch profiles on one of my Echo Dots and discovery works again. I even set my port back to 8080 and it works. Frustrating neither the Android or Windows apps can discover correctly - but once I did a discovery on a Dot in my own profile, it works. I am back to adding devices...

can you please list all steps needed - what do you mean with switch profiles?

**Comment by wilme2** [comment]
> can you please list all steps needed - what do you mean with switch profiles?

In my case both my wife and I have Amazon profiles on the same Echos & Dots.  So I realized one of my problems was the fact that I needed the Dot was was using to discover to be in my profile while adding devices. "Alexa whose profile is this?" and "Alexa switch profiles."

**Comment by hokie21** [comment]
I switched profiles. Neither profile was able to discover my devices. The error messages were different between the profiles. One told me to add the smart home skill. The other told me to push the button on the Phillips hue bridge. @bwssytems any other suggestions and did my network capture help?

**Comment by vco1** [comment]
Still no luck here. I deleted my ha-bridge conf file, deleted and re-added all devices in ha-bridge. Did a re-initialization of my Echo Dot. But the Alexa app can't find any devices. I don't have any profiles activated for my Alexa's.
Ha-bridge is running on port 80. Can't see anything special in the log file.
Help or suggestions are appreciated.

**Comment by InvertedMinor** [comment]
I am on 5.3.0 on RPI no docker port 80 , Echo Dot gen2. 17 devices have always been discoverable but new switches are no longer discovered by Echo. The devices can be switched on/of from HA-bridge. Any suggestions?

**Comment by bwssytems** [comment]
@InvertedMinor Do a forget all devices in the Alexa app. Renumber all your devices in the ha-bridge. Then do an Alexa discover again.

**Comment by InvertedMinor** [comment]
👍 Yep that did the trick, thnx!

**Comment by heffneil** [comment]
I am running a pre-existing installation.  A friend of mine had the port 80 problem.  I helped him with it but he continued to have weirdness happen.  He forgot all devices and renumbered and can not find devices.  I added a test device in my setup and did a search and too can not find it.  Latest bridge version running port 80.  On my side most things I try work without incident.  Very strange.

**Comment by audiofreak9** [comment]
@heffneil 
I remember reading other's reporting that "Forget All" does not work, BUT forgetting each device individually does work.  Try that?

**Comment by heffneil** [comment]
He is telling me that all the devices are gone?

I looked up higher in my logs and it queries and gets all the devices from the bridge.  I searched in the response and it 100% shows my new device in that response but the amazon device is saying no new devices found so something is awry 100%

**Comment by audiofreak9** [comment]
"Use Link Button" not checked under security?
Also try deleting the IP(s) of the Amazon devices from the Bridge Devices page -> Manage Links button.  Then do another discovery to see if any Amazon devices create a user entry in the list.

**Comment by audiofreak9** [comment]
Or delete all users from that list if the IPs are not listed

**Comment by heffneil** [comment]
Ok I cleared user entries and added the link button.  Reinitialized and then pushed the Link button and did a device search.  No new devices found.

**Comment by audiofreak9** [comment]
Uncheck the link button then.  
Have you tried discovery from other devices or the web interface?
Does the HA Bridge log show any IPs of the Echo(s) doing a discovery?

**Comment by audiofreak9** [comment]
Also, what is the setting for the "UPNP IP Address" input on the Bridge Control page?

**Comment by heffneil** [comment]
my upnp address is 0.0.0.0

I didn't have the link button enabled until you recommended.

I haven't tried another device.  How do you do the web interface?  I would like to try a device on the same class c vs where my dhcp is numbering things but the friend is all the same class c.  Can you test with a new test device and find it to see if it works for you?  I am curious.

**Comment by audiofreak9** [comment]
I have not had any issue, but always been on port 80, but I do have the upnp address set to my RPi's IP.

Alexa Web interface: [alexa.amazon.com](https://alexa.amazon.com/spa/index.html#appliances) bottom of page "Discover" button.

**Comment by guiguih76** [comment]
I Have the same problem (ha-bridge 5.3.0 on RPi and echo dot gen 2 fr).
ha-bridge was on port 82 and it worked before. I tried on port 8080 and it don't work for me.
On port 80 it work. So now it seems to work only on port 80.

**Comment by heffneil** [comment]
I am working on port 80.  But I can not get it to add new devices.  I guess the question I am asking can anyone currently find new devices with their amazon device on the bridge?

**Comment by CedGexx** [comment]
(ha-bridge 5.3.0 on RPi Stretch and echo dot gen 1 us)

@heffneil I can't. I tried to "Forget all" and it will empty the list of devices but will almost 100% of the time find my previous devices but not new devices. But when I did a "Forget" for a specific device, then it was gone for ever... Also, what I have added in another post is that my devices are using their old ID when Alexa summons them and since I have renumbered my devices, I now need to manually edit my "./habridge/data/devices.db" to replace all the new IDs by the old ones...

**Comment by heffneil** [comment]
Thats very strange.  The strangeness multiplies!  I read somewhere the response string recently changed - don't know why or how but it did.  Maybe this is part of our problem.  Im confused -we gotta all figure this out.  My buddy lost all his devices and can't operate anything afterwards.

**Comment by heffneil** [comment]
Thats very strange.  The strangeness multiplies!  I read somewhere the response string recently changed - don't know why or how but it did.  Maybe this is part of our problem.  Im confused -we gotta all figure this out.  My buddy lost all his devices and can't operate anything afterwards.

**Comment by audiofreak9** [comment]
I’ve always been on port 80, and I can still add and discover devices.  I always keep the bridge up to date.  I have a large mix of echo devices, discovery works from any device.  However, I have not checked the software version on each Echo.  I also have over 40 devices in the bridge.

This is surely a result of Amazon making updates to their devices.

**Comment by heffneil** [comment]
I wonder if some brave soul was willing to delete everything and start over if it would work.  Things work solidly for me on and off but learning new devices doesn't happen.  I did move ports but I still can't see how that would make a big difference.  I am using an Echo Show 1 latest software and tried from my computer.  Are there any Firewall ports that needs opening up for the bridge?  I didn't recall that originally but it has been a while?

**Comment by bwssytems** [comment]
@heffneil So, your upnp address cannot be 0.0.0.0 as it needs to be a specific address. That address is a global bind address. Please set it to an address that matches your network and the interface device. i.e.: 192.168.1.3 or what matches your network addressing.

**Comment by bikeymouse** [comment]
I am running HA-Bridge in Docker and it seems dat HA-Bridge overrides the IP-address setting! I am getting this warning:
_The upnp config address, 192.168.1.120, does not match any known IP's on this host. Using default address: 172.19.0.2_

The 172.19.0.2 address is however the internal docker address and not the host-address (I have forwarded traffic on port 80 to the internal network).

As a consequente it is not working anymore. Please help...
