### ISSUE TITLE
habridge.config won't save changes

### ISSUE THREAD

**Issue by mcwieger** [bwssytems/ha-bridge#1124]
Whenever I make updates to habridge.config (either from the GUI or in the file itself), any changes are lost after a Bridge Reinitialize.

'Configuration Path and File' is set to '/volume1/web/ha_bridge/data/habridge.config'. Changing it to 'data/habridge.config' also is not saved.

Whenever I reinitialize, a new version of the file is created, so something is written (not a permission issue, it seems), but it reverts to the original state before saving.
 I tried to 777 both directory and file: no success.

Any ideas?

**Comment by bwssytems** [comment]
@mcwieger How do you start the ha-bridge and where do you expect the config file to be? If you are starting the ha-bridge from the system, it will run as root and all relative paths work from the root directory.

**Comment by mcwieger** [comment]
It starts with
`/volume1/@appstore/Java8/j2sdk-image/bin/java -jar -Dserver.port=8085 /volume1/web/ha_bridge/ha-bridge-5.3.0.jar`

The config file is actually in that location and being used (and on reinitialize it shows a file update on that date and time). Initially I could save changes (I added a Domoticz server), but not anymore.

Some more background (see issue #659): for device.db to work, I have to include the full path. Apparently, the habridge.config does NOT allow full path anymore. So I think I may have broken it, by changing the habridge.config setting to a full path, which makes that it doesn't update anymore...

**Comment by mcwieger** [comment]
Yep, that's it. So in my environment (Synology, not in Docker), the habridge.config needs the relative path (data/habridge.config) and the device.db needs the absolute path (/volume1/.../data/device.db).

**Comment by JamieClaye** [comment]
I've recently been having this problem as well.  It doesn't matter if I change the settings on the Raspberry Pi or via a remote windows station. 

At the same time I've been running into the Echo complaining "I had trouble communicating with provider, check the network connections and power supply" - this message only comes when I try to control a light that the HA bridge won't let me change. 

If I make edits on the Raspberry Pi, those will remain until I reboot the device.

**Comment by JamieClaye** [comment]
I should add that the systems had been working for more than a year without issue.  Something changed behind the scenes as I've not directly done any updates or edits.
