### ISSUE TITLE
Can't get XY ColorData into URL

### ISSUE THREAD

**Issue by sub0ne** [bwssytems/ha-bridge#1126]
As far as I see HTTPHome uses ColorDecode.replaceColorData() to replace the URL placeholder for the color data. From the logs I can see that XY color data is present and transformed to hsl, rgb or whatever by the ColorDecoder. There seems to be no way to get the XY color data into the URL which is used by Philips Hue Bulbs. CIE is alway converted into RGB and from there in something else.

**Comment by bwssytems** [comment]
There is no color variable to put in xy currently. But if you use the Philips Hue Passthru, it will send the original color package on to the hue without modification.
