### ISSUE TITLE
Can't get separate hue, saturation and brightness

### ISSUE THREAD

**Issue by sub0ne** [bwssytems/ha-bridge#1127]
Hue, saturation and brightness are comma separated. It's not possible to split those in the URL if those need to be set separatly.

**Comment by bwssytems** [comment]
Sure, this could be done like it is for RGB

**Comment by Cypher87** [comment]
With RC1 I'm not able to do this yet. Or am I wrong?

**Comment by bwssytems** [comment]
Let me check, might not have gotten to it yet
