### ISSUE TITLE
Set log level with command line?

### ISSUE THREAD

**Issue by martijintro** [bwssytems/ha-bridge#1129]
So i know, the log level is not persistent... but the **_"Trace UPNP Calls"_** and **_"Trace State Changes"_** are.

Is it possible to set the log level via command line like that:

 /usr/bin/java -jar -Dconfig.file=/opt/habridge/data/habridge.config /opt/habridge/ha-bridge.jar -[LOG_LEVEL_PARAMETER]

I need that for debugging.

Thank you for your feedbacks.

Best regards,
Jan

**Comment by bwssytems** [comment]
Not currently

**Comment by martijintro** [comment]
Thank you for your feedback.
Can i set with with a http request, e.g. via CURL or something like that? I think that should be (theoretically) possible?

**Comment by bwssytems** [comment]
Yep, you should be able to do that. Look at the code: 

https://github.com/bwssytems/ha-bridge/blob/master/src/main/resources/public/scripts/app.js

look for the method "this.updateLogLevels"

**Comment by tegger2000** [comment]
old issue, but maybe other still use it, i use this 

curl 'http://X.X.X.X:80/system/logmgmt/update' \
-X 'PUT' \
-H 'Accept: application/json, text/plain, */*' \
-H 'Content-Type: application/json;charset=UTF-8' \
--data-raw '[{"loggerName":"ROOT","logLevel":"INFO_INT","newLogLevel":"WARN_INT"}]'
