### ISSUE TITLE
Changing color temperatur is not working correctly

### ISSUE THREAD

**Issue by sub0ne** [bwssytems/ha-bridge#1131]
Again tested with Alexa: the changing of color temperatur seems to be incorrect on Philips Hue blubs. The method replaceColorData() is called with ColorMode CT and converted via convertCTtoRGB() to RGB values. This seems not to work correct as comparing bulbs paired with a real hue show complete different colors. 

I found the following values were set:
Color change with CT: 383. Resulting RGB Values: 255 163 80    --> CT on hue 331
Color change with CT: 350. Resulting RGB Values: 255 172 100   --> CT on hue 322
Color change with CT: 284. Resulting RGB Values: 255 193 142   --> CT on hue 301
Color change with CT: 234. Resulting RGB Values: 255 212 178   --> CT on hue 283
Color change with CT: 199. Resulting RGB Values: 255 229 207   --> CT on hue 269

Maybe even the conversion from RGB to Hue, Sat, Bri fails as the CT value gets transformed to RGB and from RGB back to Hue, Sat, Bri in my case (I use the color.hsl variable in my item url).

What the algorithm does is exactly what Tanner Helland says. But something seems to be wrong:

CT request Hue (mired): 383
in RGB: 255 163 80
in HSL: 28 100 66
in HSB: 28 69 100
setting CT on Huebulb directly: 383: hue 45.46; sat 154; (bri 254)

HSL and HSB seems to be mixed also in the code

**Comment by bwssytems** [comment]
Will be writing a test case for this and will validate the calculation
