### ISSUE TITLE
build current ha-bridge master branch with eclipse java 2019-09?

### ISSUE THREAD

**Issue by jmar83** [bwssytems/ha-bridge#1136]
I've done that steps

- Installing eclise 2019-09 for JEE
- Open CMD on my eclipse workspace folder
- git clone https://github.com/bwssytems/ha-bridge.git
- Starting eclipse
- Import ha-bridge Eclipse project from its workspace directory
- Then i saw that i need to "update" on Maven context menu, to resolve dependencies
- Then i selected the run as maven build with "build" and "build..."
- Then i saw i need to enter a "goal"
- Then i saw that different goals, i was thinking "deploy" is the right one for me...
- Then i seems to build the .jar, which is right for me
- After all that, i get that error: "[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project ha-bridge: Deployment failed: repository element was not specified in the POM inside distributionManagement element or in -DaltDeploymentRepository=id::layout::url parameter -> [Help 1]"

How to build it with eclipse? Do i need a jdk12 instead of jdk11 what is installed on my pc? I think ha-bridge is java 8 compatible, even java 7. (??)

Thank you for your feedbacks.

Regards,
Jan

**Comment by bwssytems** [comment]
The maven command for the ha-bridge is install as mentioned here: https://github.com/bwssytems/ha-bridge#build
