### ISSUE TITLE
Device ID creation fails

### ISSUE THREAD

**Issue by sub0ne** [bwssytems/ha-bridge#1139]
Let's say you have created three devices with the IDs 100, 101 and 102. After restarting ha-bridge the DeviceRepository loads the device list and sets the assigns the highest ID to the variable 'nextID'. Now you add a new device in ha-bridge and the device 102 will be overwritten during save since nextID is first used and then incremented. 

_loadResository():
```
for (int i = 0; i < list.length; i++) {
	if (list[i].getColorUrl() == null || list[i].getColorUrl().isEmpty())
		list[i].setDeviceState(DeviceState.createDeviceState(false));
	else
		list[i].setDeviceState(DeviceState.createDeviceState(true));
	put(list[i].getId(), list[i]);
	if (Integer.decode(list[i].getId()) > nextId) {
		nextId = Integer.decode(list[i].getId());
	}
}
```

and in save():
```
descriptors[i].setId(String.valueOf(nextId));
nextId++;
```

**Solution proposal:**

_loadResository():
```
for (int i = 0; i < list.length; i++) {
	if (list[i].getColorUrl() == null || list[i].getColorUrl().isEmpty())
		list[i].setDeviceState(DeviceState.createDeviceState(false));
	else
		list[i].setDeviceState(DeviceState.createDeviceState(true));
	put(list[i].getId(), list[i]);
	if (Integer.decode(list[i].getId()) >= nextId) {
		nextId = Integer.decode(list[i].getId()) + 1;
	}
}
```

gonna fix this in my branch https://github.com/sub0ne/ha-bridge

**Comment by bwssytems** [comment]
Hmmm, thought I fixed that before as it was an issue prior. Will take a look

**Comment by bwssytems** [comment]
Well, it needs to be updated to do something.... But, I need to make sure it works with a sparse array. The changes I made were to be able to account for gaps in the IDs. Guess it was not enough.

**Comment by bwssytems** [comment]
The solution is:

for (int i = 0; i < list.length; i++) {
	if (list[i].getColorUrl() == null || list[i].getColorUrl().isEmpty())
		list[i].setDeviceState(DeviceState.createDeviceState(false));
	else
		list[i].setDeviceState(DeviceState.createDeviceState(true));
	put(list[i].getId(), list[i]);
	if (Integer.decode(list[i].getId()) >= nextId) {
		nextId = Integer.decode(list[i].getId()) ;
	}
}

nextId = nextId + 1;

Have to wait until all devices are loaded to get the highest value.

**Comment by SvenXP** [comment]
Hi, not sure if it belongs here but seems related:

If i want to add a new device via "edit/copy" and then "add bridge device" it overwrites my existing device with id=100. so i can not add any new devices cause it just overwrites the last one.

Also i have no idea why i have id 100 cause i do not have that many devices and the one before is 41.

**Comment by bwssytems** [comment]
This is a bug that has not been released yet....

**Comment by bwssytems** [comment]
Fixed in RC3
