### ISSUE TITLE
HTTPS setting not sticking

### ISSUE THREAD

**Issue by bluesubaru03** [bwssytems/ha-bridge#1140]
Trying to get HA-bridge to use HTTPS. Using Smarthings and bridging HA-bridge to control my X10 devices. Was working with Smartthings on port 8080 until a recent update to smartthings makes ST try to use HTTPS when a HUE reports V2. I added a cert file according to the instructions but when I reinitialize the system after setting HTTPS to true the setting returns to false. Is there a log I can look at to see why it is disabling? Running on Pi. (linux newbie)
The only changes I am making to enable HTTPS is setting to true, path to keyfile, and password. Is there something else I need to change? I assume the HA-bridge should be accessible on 443 if I am successful?

**Comment by audiofreak9** [comment]
I have the exact same issue.  I have not been able to get the use HTTPS setting to stick either.

**Comment by bwssytems** [comment]
You need to look at your log to see if there were any errors using the cert. It there is, the bridge defaults back to HTTP so as not to lock you out.

**Comment by bluesubaru03** [comment]
I'm not seeing anything in the logs related to security or HTTPS. I see an entry the security settings were updated but nothing further on HTTPS. Is there specific logging entries I need to enable or set to debug to see it? I'm running 35.3.0

**Comment by audiofreak9** [comment]
> Looks like none of the settings from the "Bridge Control" page stick for me after clicking save.

Created this same problem for myself when I changed the "Configuration Path and File" input setting on the Bridge Control page, but didn't update the systemctl service file to match the update.

**Comment by bwssytems** [comment]
Yes, make sure your paths are correct based on the relative path of the user starting the process. If it is the system, you need to set the path on the command line as it will not find root or your directories.

**Comment by bluesubaru03** [comment]
Adding the config file path to the startup command in the service file allowed me to be able to save settings. I am now able to save the set HTTPS true setting and it sticks. What is strange is that the certificate path and password settings were saving just not the HTTPS true settings. Another thing to note is enabling HTTPS does not change the port to 443, that needed to be set separately.
