### ISSUE TITLE
Command line appears not to execute.

### ISSUE THREAD

**Issue by st2000** [bwssytems/ha-bridge#1144]
Attempting to upgrade from older install of raspbien, habridge and heyu.  With new raspbein, new habridge and new heyu - able to execute heyu on command line with expected results.   But, unable to use habridge to execute heyu commend.  Verified habridge attempts to execute heyu command by inspection of habridge log:

Tracestate: Decode Json for url items: [{"item":"/usr/local/bin/heyu on l5","type":"cmdDevice"}]

(Using habridge web interface to generate above log entry. )

Expected results: X10 module turning on / off.  This was accomplished using heyu on command line.

Unexpected results: X10 module did not turn on / off.  An attempt was make using the habridge web interface which generated the log entry but did not turn on / off the X10 module.

**Comment by audiofreak9** [comment]
When you re-installed heyu, which choice did you choose at this step?
`I did not find a Heyu configuration file.
Where would you like the sample Heyu configuration file installed?
1. In directory /home/pi/.heyu/
2. In subdirectory .heyu/ under a different user home directory
3. In directory /etc/heyu (for system-wide access)
4. No thanks, I'll take care of it myself
Choice [1, 2, 3, 4] ? `

I recommend you choose 3 so it is system-wide accessible.  Then you only need “heyu on I5”.

**Comment by st2000** [comment]
When I installed heyu I followed the INSTALL directions found in the zip package.  This installed heyu in /usr/local/bin for system wide access.  Regardless, I entered the entire path to heyu in habridge.

I recall downloading the ha-bridge-5.3.0.jar file and re-writing the /etc/systemd/system script to start it instead.  I saw some anomalies in the existing devices (the habridge web page had changed) do I deleted all entries, verified the habridge data file was empty and added back on test device.  Which I have yet to turn on / off.  Could it be that manually installing habridge may be the problem?

**Comment by audiofreak9** [comment]
Try one more change to your command, “/usr/local/bin/heyu -c /usr/local/bin/.heyu/x10config” modifying the config path to meet your installation.  This tells heyu where the config file is relative to the command path.

**Comment by audiofreak9** [comment]
Forgot to add the “ on I5” to the end of the quotes.

**Comment by st2000** [comment]
That fixed it!  Adding the path to the x10config file works!

How odd is that?  The heyu man page spells out exactly where the several possible x10config file locations are.  Some are local to the user (understandable if not found when heyu is executed from applications which start up at boot time).  But others should be universal to all users.  And, currently, both my local and universal x10config files are identical.

Thanks!

**Comment by audiofreak9** [comment]
Glad that fixed it, I came across this config path gem nearly 7 years ago while trying to execute heyu commands from a PHP page.  Heyu needs to access the config file on every execution.  Calling the heyu script from the HA-Bridge run at startup by root is causing a path issue.  Getting it to work by adding the config path to the command line confirmed my suspicion, your install of heyu is not accessible to root startup items.
