### ISSUE TITLE
Cannot add Harmony hub

### ISSUE THREAD

**Issue by Hawkser22** [bwssytems/ha-bridge#1147]
I have just installed HA-Bridge for the first time.  I added a real Hue bridge and added my lights, which worked flawlessly.  I am trying to add a Logitech Harmony Hub, but I do not understand how to add it.  I have added the Harmony Hub under Bridge Control by giving it a name and adding the IP address.  When HA-Bridge initializes, I just keep getting the error ...

"Cannot get harmony client (HarmonyHub1) setup, Exiting with message: Failed communicating with Harmony Hub"

I have seen other posts about entering the username and password for the Logitech account, but I cannot find anywhere in HA-Bridge to add that information.  Under Bridge Control, there are only three fields for Harmony; Name, IP, and Webhook.  There are no username or password fields.

Can someone please provide some instructions for how to add a Logitech Harmony hub and pull in the activities into HA-Bridge?

TIA

**Comment by bwssytems** [comment]
PLease read this to enable the harmony hub for the ha-bridge to communicate

https://www-theverge-com.cdn.ampproject.org/v/s/www.theverge.com/platform/amp/2018/12/21/18152037/logitech-will-restore-third-party-harmony-home-automation?amp_js_v=0.1#referrer=https%3A%2F%2Fwww.google.com&amp_tf=From%20%251%24s&ampshare=https%3A%2F%2Fwww.theverge.com%2F2018%2F12%2F21%2F18152037%2Flogitech-will-restore-third-party-harmony-home-automation

**Comment by Hawkser22** [comment]
This is fantastic.  Thank you for the response.  That article led me down a
rabbit hole that ultimately led to a solution.  Exactly what I needed.  I
enabled XMPP through the Logitech app, sync'd the hub, restarted the
HA-Bridge, and all of the Logitech devices and activities appear perfectly
now.  Thanks again.

Now that the immediate problem is solved, let's switch (if I may) to a more
academic discussion.  Do you know anything about the differences between
XMPP and webhooks?  I'm wondering if there is a better (read = more secure)
way to control the Harmony Hub with HA-bridge than using XMPP (given that
there are known vulnerabilities with XMPP)?  Is it possible to disable XMPP
again and control the hub some other way?  Such as webhooks?

Just wondering.

TIA

**Comment by bwssytems** [comment]
There is the new interface I could code to, but since this is usually used on a local network I'm ok with it for now.

Logitech changed it as some people open their home networks up to be vulnerable.....

**Comment by npaisnel** [comment]
Hawkser 
When you added the Hub on the bridge Control page .
Is the name just your friendly name or a specific ?

what goes in the Webhook ?


Will follow that link too, but those two for now will be great to get me started

**Comment by npaisnel** [comment]
Well

Thanks for the link about the XMMP   added that in My harmony 

added the ip address of the harmony hub.

but not populating with harmony devices

Failing to Communicate with harmony.   have tried multiple reboots  and Sync's



```
04-15-2021 09:41:11.230 | INFO | HA Bridge startup sequence... | com.bwssystems.HABridge.HABridge
-- | -- | -- | --
04-15-2021 09:41:11.587 | INFO | HA Bridge (v5.4.0) initializing.... | com.bwssystems.HABridge.HABridge
04-15-2021 09:41:11.593 | INFO | reading from config file: /home/pi/habridge/data/habridge.config | com.bwssystems.HABridge.BridgeSettings
04-15-2021 09:41:13.739 | INFO | StaticResourceHandler configured with folder = /public | spark.staticfiles.StaticFilesConfiguration
04-15-2021 09:41:13.999 | INFO | System control service started.... | com.bwssystems.HABridge.SystemControl
04-15-2021 09:41:14.132 | INFO | Initializing UDP response Socket... | com.bwssystems.HABridge.util.UDPDatagramSender
04-15-2021 09:41:14.151 | INFO | UDP response Socket initialized to: 50000 | com.bwssystems.HABridge.util.UDPDatagramSender
04-15-2021 09:41:14.160 | INFO | HTTP Home created. | com.bwssystems.HABridge.plugins.http.HTTPHome
04-15-2021 09:41:14.172 | INFO | Harmony Home created. | com.bwssystems.HABridge.plugins.harmony.HarmonyHome
04-15-2021 09:41:14.480 | INFO | == Spark has ignited ... | spark.embeddedserver.jetty.EmbeddedJettyServer
04-15-2021 09:41:14.481 | INFO | >> Listening on 0.0.0.0:80 | spark.embeddedserver.jetty.EmbeddedJettyServer
04-15-2021 09:41:15.958 | INFO | setup initiated .... | com.bwssystems.HABridge.plugins.harmony.HarmonyServer
04-15-2021 09:41:18.120 | INFO | setup initiated .... | com.bwssystems.HABridge.plugins.harmony.HarmonyServer
04-15-2021 09:41:20.134 | INFO | setup initiated .... | com.bwssystems.HABridge.plugins.harmony.HarmonyServer
04-15-2021 09:41:22.148 | INFO | setup initiated .... | com.bwssystems.HABridge.plugins.harmony.HarmonyServer
04-15-2021 09:41:24.162 | INFO | setup initiated .... | com.bwssystems.HABridge.plugins.harmony.HarmonyServer
04-15-2021 09:41:24.176 | ERROR | Cannot get harmony client (Harmony Hub) setup, Exiting with message: Failed communicating with Harmony Hub | com.bwssystems.HABridge.plugins.harmony.HarmonyHome
```

**Comment by npaisnel** [comment]
OK, well I am posting this for the benefit of any one else misguided to have bought one of these Harmony Remote and is determined to get it to work
I have been trying to get this to work for years, and did know about the XMPP firmware downgrade.

What noe of the instructions see to tell you is that if you do ANY settings changes to the remote config and do a Syn...the bloody hub updates its firmware again , and then nothing works again.

So after changing anything on the Harmony, api must go back to the MyHarmony app, Alt-Fn  F9 on a Mac and scroll down again and down grade each time! What  PITA
