### ISSUE TITLE
How To Pair with Harmony Hub

### ISSUE THREAD

**Issue by hendryman** [bwssytems/ha-bridge#1149]
I searched in the issues and wasn't able to make it work with any solution. Issue #1058 was similar to mine, but I don't run Docker, so the solution did not apply to me.

I have the ha-bridge 5.3.0 running on a raspberry pi on port 80.
When I add the Philips Hue in the Harmony Hub app on my mac, it tells me to press the center button in the bridge. I then press the link button in ha-bridge, but Harmony Hub never discovers my ha bridge and finally times outl

How can i get the pairing done?

**Comment by bwssytems** [comment]
Please turn on upnp trace from the control page and post the log after you do a discovery with the harmony hub.

**Comment by hendryman** [comment]
Deleting the db did the job.
