### ISSUE TITLE
Home Assistant gets null exception during initialization

### ISSUE THREAD

**Issue by tjedmunds** [bwssytems/ha-bridge#1150]
I am using the most recent version of hassio (Home Assistant). After entering IP, port and a long lived access token (not a legacy password) for authentication ha-bridge fails to initialize the hass information. Further digging in the logs finds the following:

Nov 05 19:30:17 smarthouse.lan java[31933]: 2019-11-05 19:30:17,156 [main] ERROR com.bwssystems.HABridge.plugins.hass.HassHome - Cannot get hass (smarthouse) setup, Exiting with message: null
Nov 05 19:30:17 smarthouse.lan java[31933]: java.lang.NullPointerException: null
Nov 05 19:30:17 smarthouse.lan java[31933]:         at com.bwssystems.HABridge.plugins.hass.HomeAssistant.isLegacyAuth(HomeAssistant.java:111)
Nov 05 19:30:17 smarthouse.lan java[31933]:         at com.bwssystems.HABridge.plugins.hass.HomeAssistant.<init>(HomeAssistant.java:31)
Nov 05 19:30:17 smarthouse.lan java[31933]:         at com.bwssystems.HABridge.plugins.hass.HassHome.createHome(HassHome.java:53)
Nov 05 19:30:17 smarthouse.lan java[31933]:         at com.bwssystems.HABridge.plugins.hass.HassHome.<init>(HassHome.java:34)
Nov 05 19:30:17 smarthouse.lan java[31933]:         at com.bwssystems.HABridge.HomeManager.buildHomes(HomeManager.java:82)
Nov 05 19:30:17 smarthouse.lan java[31933]:         at com.bwssystems.HABridge.HABridge.main(HABridge.java:92)

**Comment by bwssytems** [comment]
Will need to take a look at that

**Comment by tjedmunds** [comment]
A workaround for this issue is to click the Legacy Password checkbox even though it isn't a legacy connection. Click Save. You will get a 500 error. Uncheck the checkbox and click Save again. Then it connects. Go figure.

**Comment by ceefin** [comment]
Can verify, had to go through this process myself after a recent upgrade to 0.102. Was previously using 0.96.x and the upgrade forced me to ditch the legacy password.

sidenote: thank you BWS!!!!

**Comment by JesusArmy** [comment]
> A workaround for this issue is to click the Legacy Password checkbox even though it isn't a legacy connection. Click Save. You will get a 500 error. Uncheck the checkbox and click Save again. Then it connects. Go figure.

I confirm that this workaround did also the trick for me. Thanks tjedmunds and thanks a lot bwssystems for this wonderful lightweight piece of software!

**Comment by aristosv** [comment]
I can confirm that this issue still exists, and the workaround also works.

I am using Debian buster and I followed this installation method

https://github.com/bwssytems/ha-bridge#manual-installation-of-ha-bridge-and-setup-of-systemd-service

**Comment by sanderlv** [comment]
I have a major down again... It worked and then I had no devices in habridge anymore. So I restarted, redid, retried... nothing... even not the trick from above. Sorry: SUCKS.

**Comment by bwssytems** [comment]
This is an issue in tha apache http response entity deflater. This will be in 5.4.0
