### ISSUE TITLE
Habridge not compatible with java11, while java8 is no longer installable

### ISSUE THREAD

**Issue by QuangKhuongIoT** [bwssytems/ha-bridge#1159]
today i install habridge v5.2.1 on my pi, buster with default java11 installed. i got error server error 500, i found that the Habridge only compatible with java8, which no longer available on server.
what's should i do to make habridge run clearly on my new OS.
![habridge](https://user-images.githubusercontent.com/21331190/70202561-a61b9400-174c-11ea-9526-9329c761b96e.jpg)

**Comment by bwssytems** [comment]
I figured this day would come. Will need to have two versions for download. Java8 version is compatible for people that use Raspberry Pi, Synology and other smaller systems with linux. Windows I assume would go this route.

**Comment by bwssytems** [comment]
I have added a Java 11 executable to the v5.3.0 release:

https://github.com/bwssytems/ha-bridge/releases/download/v5.3.0/ha-bridge-5.3.0-java11.jar

**Comment by QuangKhuongIoT** [comment]
Glad to hear this from you, i will check if it worked! Thanks!

> I have added a Java 11 executable to the v5.3.0 release:
> 
> https://github.com/bwssytems/ha-bridge/releases/download/v5.3.0/ha-bridge-5.3.0-java11.jar

**Comment by Cybertom** [comment]
The latest version of raspbian buster distro only has java 11 and java 8 is no longer supported. i tried the java 11 executable, i can add things but when i try to restore my backup i get error 500

**Comment by bwssytems** [comment]
@Cybertom See the link above that has the link to the java11 executable....

**Comment by Cybertom** [comment]
that's the one i use, everything works fine only restore doesn't work. I have now filled in everything manually again
