### ISSUE TITLE
Support for Harmony Sequence

### ISSUE THREAD

**Issue by CashAMatic** [bwssytems/ha-bridge#116]
Not knowing anything about the Harmony API... so this may be a limitation on the Harmony side of things.

Is it possible to support what Harmony calls a "sequence"?

They are essentially macros you can build to perform a number of button presses in sequence with optional delays. They are sort of a pain to build, you need a remote to make one, but then they are given a name and can be assigned to remote buttons or to app gestures (when using the IOS/Android app).
It would be awesome to be able to trigger a sequence via voice command.

**Comment by audiofreak9** [comment]
You can build your own custom sequence in the ha-bridge on the Harmony Devices tab.  You will need to find the Harmony device ID and commands for the devices you want in your sequence.  In the ha-bridge, sequenced commands are comma separated.   For example, the following raises my stereo volume twice and changes the DVR up one channel: 

`[{"device":"32829111","button":"VolumeUp"},{"device":"32829111","button":"VolumeUp"},{"device":"32829115","button":"ChannelUp"}]`

1. Open two browser tabs of your ha-bridge on the Harmony Devices tab.  (One to build your actual sequence button and one to copy the individual commands from.)
2. On the first tab, give your new sequence a name and add the first command in the sequence.  The On and Off URLs will have: `[{"device":"ID","button":"COMMAND"}]`
3. In the other browser window, find the commands you want to sequence by choosing them one by one from the device dropdowns and copying them to your sequence in the first tab (don't copy the brackets, just the braces.  Remember to comma separate the braces.  Your On and Off URLs will end up like this:`[{"device":"ID","button":"COMMAND"},{"device":"ID","button":"COMMAND"},{"device":"ID","button":"COMMAND"},{"device":"ID","button":"COMMAND"}]` as many as you need for your sequence.

Remember you can use `{"name":"-1"}` in the Off URL alone to turn off all the devices turned on by the Harmony if you desire.

My example is not something you would actually build, but it gives you the idea.

**Comment by bwssytems** [comment]
The Helper screen for devices does this for you. Just select the button you want for on and off then hit build button, then select another button and hit build button. Easy as pie!

**Comment by audiofreak9** [comment]
When I try to generate a new Harmony Device with multiple commands it overwrites the first one each additional Build a Button press.

**Comment by bwssytems** [comment]
Crap, It is broke.... bug
