### ISSUE TITLE
X10 Commander and HA Bridge Communication Error

### ISSUE THREAD

**Issue by pbmeisel** [bwssytems/ha-bridge#1166]
Hello all,

I am fairly new to application work and trying to set up HA Bridge with X10 Commander to control my radio signal outlets ultimately through Alexis.

I am running into issues getting HA Bridge to interface with X10 Commander. 

I am using the following PUT commands to send my signals:
http://192.168.1.85:8086/?x10command=DEVICE~sendrf~%22P1%20ON%22%27
http://192.168.1.85:8086/?x10command=DEVICE~sendrf~%22P1%20OFF%22%27

When I post these commands in browser, they appear to properly detect the X10 controller and exist validly. However, in HA Bridge, they register the following error:

12-23-2019 17:13:19.151 | WARN | Could not execute request: http://192.168.1.85:8086/?x10command=DEVICE~sendrf~%22P1%20ON%22%27 with message: Cannot run program "http://192.168.1.85:8086/?x10command=DEVICE~sendrf~%22P1%20ON%22%27": CreateProcess error=2, The system cannot find the file specified | com.bwssystems.HABridge.plugins.exec.CommandHome

-- | -- | -- | --
12-23-2019 17:13:19.152 | WARN | On/Off Request failed with: [{"error":{"type": 6, "address": "/lights/100","description": "Error on calling out to device", "parameter": "/lights/100/state"}}

I am using a Firecracker CM17A on Com3 to interface with the units. I saw some posts online indicating this module may require different commands to function properly with HA Bridge. However, I have been unable to find a means to test commands out from X10 Commander to determine that. The X10 client on my phone does control my devices properly. 

Is anyone able to offer any input on next steps I can take to confirm this interfacing to get my X10 Commander and HA Bridge integrating properly?

**Comment by bwssytems** [comment]
It looks like you set your device type in the on/dim/off area of the device setup as "execute command/script/program" instead of "HTTP device"

**Comment by pbmeisel** [comment]
That took care of it.  Everything seems to be working now.  Thanks a lot!
