### ISSUE TITLE
Device Discovery

### ISSUE THREAD

**Issue by Pukkahq** [bwssytems/ha-bridge#1167]
I have removed all of the devices from HA Bridge, ran a scan and Alexa it still finds the devices. I removed the devices from Alexa and left it a few days but they were still found. finally i shut down the HA Bridge raspberrypi left it a few days and ran another scan it still finds the devices. 
Any pointers?

**Comment by mamama1** [comment]
doesn't seem to have anything to do with ha-bridge...

**Comment by bwssytems** [comment]
Check to see if you have an ha-bridge still running

**Comment by Pukkahq** [comment]
The Raspberry pi is currently switched off. my next test is to turn all of the alexa devices except 1.

**Comment by leyton01** [comment]
Same issue with me. We just moved house and I have only plugged in is the hue hub and a few echos on a network with a new modem/router. After 'forget all' on the Alexa website and re-running discovery I have all the old ha-bridge devices still listed.  Definitely no ha-bridge running (the pi is still back at the old house). 

Are these devices stored into the hub somehow (like routines)?

**Comment by leyton01** [comment]
Seems to be an Alexa issue where it does not forget devices. 
This

**Comment by bwssytems** [comment]
Closing referencing #1143
