### ISSUE TITLE
MQTT Client support? 

### ISSUE THREAD

**Issue by farhanito** [bwssytems/ha-bridge#117]
Any plans on adding MQTT Client like Paho?https://github.com/eclipse/paho.mqtt.java

Or, should we just use {"item":"exec://mosquitto_pub.exe"} 

Thanks

**Comment by bwssytems** [comment]
It would be interesting, I'll take a look and see what it takes. Using  the client for now will work though.

**Comment by scargill** [comment]
Anyone have a screenshot of a typical device firing stuff to MQTT - I understand Mosquitto etc - but I can't find an example of exactly what you need to put in the edit/copy a device page - to use MQTT.

**Comment by bwssytems** [comment]
Here is a screen shot on how you would use mosquitto_pub.exe

![image](https://cloud.githubusercontent.com/assets/13528314/20182448/710f5d0c-a727-11e6-8de0-8724089f98ac.png)

**Comment by bwssytems** [comment]
I will include the mqtt client into the ha-bridge as it looks straight forward. The config will be broker and client id, then messages would be "topic" and "content"

**Comment by farhanito** [comment]
Hi, 

@scargill 
Here's mine on a Rasp Pi
http://i.imgur.com/ugM6iWn.jpg

@bwssytems 
Excellent, thanks. So excited.

**Comment by scargill** [comment]
Don't forget username and password for MQTT - many of us use that for a bit of extra security...

**Comment by scargill** [comment]
Thanks for that - I have MQTT working - just got it back on port 80 after displacing Apache by 1 port.. now to try Google Now..

**Comment by bwssytems** [comment]
Anybody want to give it a whirl? Test version, but does not have user/password yet.

Grab it here: http://bwssystems.com/files/ha-bridge-3.2.2d.jar

**Comment by farhanito** [comment]
@bwssytems 

sorry, currently trying the test version. any example how to create device that uses mqtt?

thanks

**Comment by bwssytems** [comment]
Some other home automation platforms use MQTT for their bus. Rspbian Jessie already runs a MQTT broker, so I just test by connecting to that and running the mosquitto_sub on the other end.

**Comment by farhanito** [comment]
I mean, what to input in the on and off URLs?

**Comment by bwssytems** [comment]
Gotcha, go into the bridge control tab and enter a ClientId and an ipaddress and port for an MQTT broker. Save it. Then you will see the MQTT tab that has the builder for MQTT messages. Put in a topic and message content and generate the device.

**Comment by scargill** [comment]
Not by default it doesnt

**Comment by bwssytems** [comment]
Ahh, good to know. The install for mosquitto must start that up then....
