### ISSUE TITLE
Please add option: If bright request present with on, only send dim

### ISSUE THREAD

**Issue by sbormann** [bwssytems/ha-bridge#1171]
As discussed here: https://github.com/bwssytems/ha-bridge/issues/923#issuecomment-556392598

Please add option to only send dim, even if bright request is made with on
(because in some circumstances alexa asks for both, on and dim, so a light bulb goes first to 100% (on-request) and then to the requested dim-level).

Thanks and best regards!

**Comment by SelmaUrban** [comment]
@bwssytems 
if it is not too much effort, it would be cool to find this function in v5.3.1 Final

**Comment by St4tikk** [comment]
Will this one make it into an RC in the near future?  It's the only thing preventing me from switching over to Ha-Bridge for local control vs the flaky alexa skill implementation of my hub software.  Thanks for this software I've been running it since the beginning for certain devices and it's incredible how far it has come!

**Comment by bwssytems** [comment]
I'll look into the current RC for this

**Comment by bwssytems** [comment]
So, I believe I have the setup for this: use "On when Dim is present" set to false and "On with First Dim" set to false in the next RC4 release.

**Comment by St4tikk** [comment]
Thanks!  Can't wait to try it out when RC4 releases!  👍

**Comment by bwssytems** [comment]
The implementation will actually be another switch called "Dim only when on present". It didn't work the way I described above.

**Comment by bwssytems** [comment]
RC4 is released and this is now in that release

**Comment by MattL0** [comment]
ha bridge is still sending an on command when a dim command is called. I tried the flags with no luck

**Comment by MattL0** [comment]
The only way tom make the dim action not send an on value is to set the payload of the on action to ''on'' . if this is set to anything else it does not work. 

When the payload is set to ''on''  in the on action of ha bridge.... ha bridge is send a 100 instead of On

**Comment by MattL0** [comment]
adfter some testing.... it seems like the on and dim command needs to be a number, and if there is nothing in the on command when setting the light to on , the dim will be sent

**Comment by MattL0** [comment]
And when all on/off dim are used. 

The off command will send a 0, the dim command will send a on command 2 times and a dim value number  , and the on command will send a ( in this case 122, and a 100 value)
![1](https://user-images.githubusercontent.com/27497561/103960034-4ea1e180-511f-11eb-8301-a54ec509b34b.PNG)

**Comment by MattL0** [comment]
of value received 
![2](https://user-images.githubusercontent.com/27497561/103960108-72fdbe00-511f-11eb-9716-d260d0d2aef7.PNG)

**Comment by MattL0** [comment]
dim commands received 
![3](https://user-images.githubusercontent.com/27497561/103960149-83159d80-511f-11eb-8d16-798e758780db.PNG)

**Comment by MattL0** [comment]
on commands received : 
![4](https://user-images.githubusercontent.com/27497561/103960190-94f74080-511f-11eb-85b1-ccaec062deee.PNG)

**Comment by MattL0** [comment]
this is with the device flag Dim only when On present (If dim is present and the on request is present, the on request will not be sent. This is overriden by the above settings.) set to true. 

1st pic is a dim command . Second pic is a on command
![1](https://user-images.githubusercontent.com/27497561/103960585-7ba2c400-5120-11eb-9319-0cc556f6a804.PNG)
![2](https://user-images.githubusercontent.com/27497561/103960586-7ba2c400-5120-11eb-9c07-e9cd399df33d.PNG)
