### ISSUE TITLE
Harmony hub problems

### ISSUE THREAD

**Issue by cherowley** [bwssytems/ha-bridge#1177]
Hi!

Anyone got any ideas why my harmony hub stops working with habridge after a week or so? Restarting habridge gets it working again.

Error log:

01-22-2020 05:48:48.741 | WARN | Send heartbeat failed | net.whistlingfish.harmony.HarmonyClient
-- | -- | -- | --
01-22-2020 05:49:18.744 | WARN | Send heartbeat failed | net.whistlingfish.harmony.HarmonyClient
01-22-2020 17:06:10.480 | WARN | Issue in communcicating with Harmony Hub, retrying connect.... | com.bwssystems.HABridge.plugins.harmony.HarmonyHandler
01-22-2020 17:06:11.278 | INFO | Resetting harmony hub due to communication errror: Hub | com.bwssystems.HABridge.plugins.harmony.HarmonyHome
01-22-2020 17:06:11.307 | INFO | setup initiated .... | com.bwssystems.HABridge.plugins.harmony.HarmonyServer
01-22-2020 17:06:15.488 | WARN | Should not get here, no harmony hub available | com.bwssystems.HABridge.plugins.harmony.HarmonyHome
01-22-2020 17:06:15.490 | WARN | On/Off Request failed with: [{"error":{"type": 6, "address": "/lights/136","description": "Should not get here, no harmony hub available", "parameter": "/lights/136/state"}}] | com.bwssystems.HABridge.hue.HueMulator
01-22-2020 17:06:15.846 | WARN | Should not get here, no harmony hub available | com.bwssystems.HABridge.plugins.harmony.HarmonyHome

Looks like it loses connection to the hub, tries to reset but after resetting it really confuses itself!

I've been running 5.3 for months and months without prior problems..

Cheers!

**Comment by cherowley** [comment]
No ideas anyone?

**Comment by bwssytems** [comment]
Could you turn on debug for this class in the log tab please: com.bwssystems.HABridge.plugins.harmony

Then post the log after this issue occurs. Thanks

**Comment by edd--** [comment]
I'm having the exact same problem, did you get any further debugging or even solving this ?

**Comment by edd--** [comment]
could be a harmony hub issue though, since when I open the harmony app, I'm able to control the lights again. So it stops working using the remote, but when you open the app it works again, also with the remote.

**Comment by bwssytems** [comment]
Is this still an issue?

**Comment by cherowley** [comment]
Hiya,

Not had the problem in a few days now ypu mention it....
________________________________
