### ISSUE TITLE
Device Types

### ISSUE THREAD

**Issue by 1liminal1** [bwssytems/ha-bridge#1178]
Hey guys, 

Hue has things like plugs ect now. But HA bridge still only displays things as lights. Can this be updated?

I have Yamaha amps being used though HA Bridge that don't work well in Alexa Groups because they appear as lights. Would be great if they could be plugs. 

Is this something that would ever be implemented?

**Comment by 1liminal1** [comment]
Ok; so is this confirmed to never going to change?

https://github.com/bwssytems/ha-bridge/issues/1006

**Comment by bwssytems** [comment]
Not currently

**Comment by 1liminal1** [comment]
Ok cool, thanks for letting me know
