### ISSUE TITLE
HA-Bridge Version 5.4 Release?

### ISSUE THREAD

**Issue by martijintro** [bwssytems/ha-bridge#1179]
Hi there!

Does somebody known (more or less..) when the next HA-Bridge version 5.4 will be released?

Thank you for your feedbacks.

Best regards,
Jan

**Comment by bwssytems** [comment]
When I look at a few more issues. If you need something that may already be fixed , you can build the dev branch 5.3.x

**Comment by martijintro** [comment]
thx!!
