### ISSUE TITLE
Alexa reports device malfunctioning even though the device actually functions as expected.

### ISSUE THREAD

**Issue by shawn-lindberg** [bwssytems/ha-bridge#1182]
I apologize if this issue has been reported, I looked through the issues and it seems different from all of the other ones. Quite a while ago (sometime last year), I started having an issue where Alexa would report "<blank> appears to be malfunctioning", for _some_ devices even though the device had correctly responded. I was a bit lazy to deal with it, because the devices were working okay. This seems to occur regardless of whether I have recently issued a command or not, and tends to happen for the same devices each time. Any idea why this occurs and whether it can be worked around/fixed?

**Comment by tuicemen** [comment]
This issue happens with many smart devices even if not using HA-Bridge.
I usualy get this after a power outage for the first device I attempt to control. If I reply to Alexas comment that the device was unresponcive with yes it did she replied with 'Oh Ok' and I know longer get those messages untill next power blip.
Others have reported removing a hub or other skills and forgetting to unlink all devices to that hub/skill. Also if you removed a device then re added it in Alexa some times the remove dosen't  doesn't actually take so Alexa still sees the original which is not the correct one.

**Comment by shawn-lindberg** [comment]
> This issue happens with many smart devices even if not using HA-Bridge.
> I usualy get this after a power outage for the first device I attempt to control. If I reply to Alexas comment that the device was unresponcive with yes it did she replied with 'Oh Ok' and I know longer get those messages untill next power blip.
> Others have reported removing a hub or other skills and forgetting to unlink all devices to that hub/skill. Also if you removed a device then re added it in Alexa some times the remove dosen't doesn't actually take so Alexa still sees the original which is not the correct one.

Thank you for your reply, tuicemen. I did notice some duplicates a couple weeks ago, but I deleted them all right away and all of the devices are actually functioning correctly. If I tell the device to turn on or off, it will do so, every time. Alexa does not report that they are unresponsive, she says that they are malfunctioning. Specifically, she says "Sorry, <device name> appears to be malfunctioning". As you can imagine, this is really annoying. That's why I would like to try to find a solution. :)

**Comment by MasterRay2** [comment]
I notice this behavior when controlling my FHEM devices. They all work properly but Alexa has a different opinion about that ;-) That wouldn't really bother me but HA Bridge obviously retries each command several times in this case!? And that is really bad if you send toggle commands :-(

**Comment by bwssytems** [comment]
In some cases, if the command on the ha-bridge takes too long to execute before it replies to the echo, the echo times out on the call and reports the error. the ha-bridge then does complete the call but the reply is too late of course.

**Comment by shawn-lindberg** [comment]
> I notice this behavior when controlling my FHEM devices. They all work properly but Alexa has a different opinion about that ;-) That wouldn't really bother me but HA Bridge obviously retries each command several times in this case!? And that is really bad if you send toggle commands :-(

Oh, I don't have any toggle commands, so I guess I didn't notice that behavior. That does sound unfortunate.



> In some cases, if the command on the ha-bridge takes too long to execute before it replies to the echo, the echo times out on the call and reports the error. the ha-bridge then does complete the call but the reply is too late of course.

That possibility did occur to me, but the commands are very lightweight and I noticed that the effect of executing the command is instantaneous, and the reply that it is malfunctioning happens a few moments afterwards. Very puzzling indeed. Is there any way I can provide more information to help track down the issue?

**Comment by MasterRay2** [comment]
Thanks. I use script execution now. That works fine for me.

**Comment by bwssytems** [comment]
@shawn-lindberg You could turn on debug for the HueMulator class and then do your command and then post the log output.

**Comment by shawn-lindberg** [comment]
@bwssytems Okay, I was able to get the log output. It is below. I'm not sure if this really gives a clue to the problem because I don't know how to interpret it. I can tell you that 192.168.1.11 is the local IP address of my Echo Dot, which for some reason is on the my 5 GHz Wi-Fi. The Raspberry Pi running the ha-bridge is on my 2.4 GHz, but I wouldn't think that would matter.

`
03-11-2020 09:51:28.653 | DEBUG | HueMulator GET called on api/* with request  <<</api/devices/backup/available>>>, and body  <<<>>> | com.bwssystems.HABridge.hue.HueMulator
-- | -- | -- | --
03-11-2020 09:51:28.658 | DEBUG | HueMulator GET called on api/* with request <<</api/devices>>>, and body <<<>>> | com.bwssystems.HABridge.hue.HueMulator
03-11-2020 09:52:02.910 | DEBUG | HueMulator PUT called on api/* with request  <<</api/475c3e1d65514e239f3ab9801ed89085/lights/101/state>>>,  and body <<<{"on":true}>>> | com.bwssystems.HABridge.hue.HueMulator
03-11-2020 09:52:02.912 | DEBUG | hue state change requested: 475c3e1d65514e239f3ab9801ed89085 from 192.168.1.11 body: {"on":true} | com.bwssystems.HABridge.hue.HueMulator
03-11-2020 09:52:02.913 | DEBUG | Calling on-off as requested. | com.bwssystems.HABridge.hue.HueMulator
03-11-2020 09:52:02.914 | DEBUG | Decode Json for url items: [{"item":"sandman --command=back_raise","type":"cmdDevice"}] | com.bwssystems.HABridge.hue.HueMulator
03-11-2020 09:52:02.916 | DEBUG | Calling Home device handler for type : cmdDevice | com.bwssystems.HABridge.hue.HueMulator
03-11-2020 09:52:02.930 | DEBUG | HueMulator GET called on api/* with request  <<</api/475c3e1d65514e239f3ab9801ed89085/lights/101>>>,  and body <<<>>> | com.bwssystems.HABridge.hue.HueMulator
03-11-2020 09:52:02.933 | DEBUG | hue light requested: 101 for user: 475c3e1d65514e239f3ab9801ed89085 from 192.168.1.11 | com.bwssystems.HABridge.hue.HueMulator
03-11-2020 09:52:02.934 | DEBUG | found device named: sandman back | com.bwssystems.HABridge.hue.HueMulator
03-11-2020 09:52:04.112 | DEBUG | HueMulator GET called on api/* with request  <<</api/475c3e1d65514e239f3ab9801ed89085/lights/101>>>,  and body <<<>>> | com.bwssystems.HABridge.hue.HueMulator
03-11-2020 09:52:04.114 | DEBUG | hue light requested: 101 for user: 475c3e1d65514e239f3ab9801ed89085 from 192.168.1.11 | com.bwssystems.HABridge.hue.HueMulator
03-11-2020 09:52:04.115 | DEBUG | found device named: sandman back | com.bwssystems.HABridge.hue.HueMulator
03-11-2020 09:52:05.135 | DEBUG | HueMulator GET called on api/* with request  <<</api/475c3e1d65514e239f3ab9801ed89085/lights/101>>>,  and body <<<>>> | com.bwssystems.HABridge.hue.HueMulator
03-11-2020 09:52:05.137 | DEBUG | hue light requested: 101 for user: 475c3e1d65514e239f3ab9801ed89085 from 192.168.1.11 | com.bwssystems.HABridge.hue.HueMulator
03-11-2020 09:52:05.138 | DEBUG | found device named: sandman back | com.bwssystems.HABridge.hue.HueMulator
`

**Comment by audiofreak9** [comment]
It actually may matter what band your Echo is on, read [this Amazon Echo article](https://www.amazon.com/gp/help/customer/display.html?nodeId=201751350)

**Comment by shawn-lindberg** [comment]
> It actually may matter what band your Echo is on, read [this Amazon Echo article](https://www.amazon.com/gp/help/customer/display.html?nodeId=201751350)

@audiofreak9 Thank you for the suggestion. I moved the Echo Dot onto the 2.4 GHz band (they have different SSIDs), I didn't really want it on the 5 GHz, anyway. Unfortunately, it doesn't seem to have helped the erroneous malfunction messages.

**Comment by shawn-lindberg** [comment]
I haven't gotten any responses to my log post, but I have noticed something interesting. Alexa only reports a malfunction when I turn the devices on. When I turn them off she always says okay. Perhaps that's a hint?

**Comment by shawn-lindberg** [comment]
Okay, I believe I finally figured this out. I had set the devices to have no state (the No State checkbox was checked). When I unchecked that and updated the device, Alexa started reporting okay instead of that there was a malfunction when I asked her to turn on the devices. I will do a little bit more testing and then report back.

**Comment by shawn-lindberg** [comment]
Yes, that seems to fix the problem. One wonders what this option is for, but whatever.
