### ISSUE TITLE
Echo Show 5 no longer "sees" devices, but older Echos do.

### ISSUE THREAD

**Issue by napcs** [bwssytems/ha-bridge#1186]
It seems something's up with Amazon again.

I have older Echos and Sonos devices and they are able to control things. But the Echo Show 5 in my living room says it can't find any of the the lights anymore. Deleted everything, rediscovered devices (which wasn't easy, btw, as people report in issue #1184 and #1185) and they all show up in the Alexa app, but they have errors on each of them - "Device does not support requested value."  Pressing the button in the Alexa app does turn the light on and off, but it then errors.

It appears the newer echos expect some different responses that HA-bridge isn't sending back. I have seen issues on here where it may have to do with dimming, but I can't for the life of me figure out what to actually put in, as the lights I have don't support dimming.

Anyone have any ideas?

**Comment by bwssytems** [comment]
Yes, the errors are a bug that is fixed in the dev branch, but not yet released. As far as the echo show 5, I assume it may be an amazon thing for that device.

**Comment by napcs** [comment]
I forked this repo, rebased master with the dev branch, and rebuilt the JAR locally. Problems are resolved.

**Comment by heikoh81** [comment]
Where can I find that forked repo?
Although I don't have a Show 5, I'd like to give it a try as local discoery has stopped working in my setup, too.

Stay healthy!

**Comment by napcs** [comment]
@heikoh81 I literally just cloned this repo to my local machine, checked out the dev branch, did a `git rebase master`, installed maven, and built the jar with `mvn install`.

**Comment by heikoh81** [comment]
I'm using github just as a user, not developer...
I managed to clone master-branch to my raspi test system to /root/ha-bridge/master,
and dev-branch to /root/h-bridge/dev.
I fail at the command git rebase master.
How does it have to look like?

**Comment by heikoh81** [comment]
Have to give up on this approach, getting to many errors during install of java, maven, etc.
I will have to wait until new prcompiled .jar-file with fix for not discovering HA-Bridge devices is provided by BW Systems.

**Comment by bwssytems** [comment]
I may do an intermediate release on what is already fixed.

**Comment by heikoh81** [comment]
That would be great.
