### ISSUE TITLE
Alexa App "Device Doesnt Support Requested Value"

### ISSUE THREAD

**Issue by cylon147** [bwssytems/ha-bridge#1187]
I think HA-bridge Sending the wrong reply to Alexa app when you open Devices in the Alexa app.

The Correct Reply should be 
`'{"state":{"on":false,"bri":1,"alert":"none","reachable":true},"type":"Dimmable light","name":"Light","modelid":"LWB007","manufacturername":"Philips","uniqueid":"00:17:88:5E:D3:100-100","swversion":"66012040"}'`

Please correct me if I m wrong. Thanks

**Comment by bwssytems** [comment]
This is the same as #1044 and it is already tagged as a bug.
