### ISSUE TITLE
Device Limit?

### ISSUE THREAD

**Issue by osenbruggen** [bwssytems/ha-bridge#119]
Hi, Is there a device limit? Up to 51 devices everything works perfect. If I add 52. my Echo doesn't find anything any more?

**Comment by bwssytems** [comment]
Unfortunately, a known limitation of the Echo. Has been reported for Smarththings with the echo as well. It is a limit per device hub the Echo sees.

Start another HA bridge using different web server and upnp response ports pointing to a different directory and you can add more.

**Comment by osenbruggen** [comment]
Hmmm OK.. Good to know. I did E-mail Amazon Support about this as well.

**Comment by bwssytems** [comment]
Known limit of the Echo, closing.
