### ISSUE TITLE
Harmony hub wants bridge button pressed

### ISSUE THREAD

**Issue by FourFoot** [bwssytems/ha-bridge#1193]
I'm trying to add hue (ha bridge) to my harmony elite remote, however harmony wants me to press the button on the bridge, which of course I don't have.

I've tried enabling the link button in ha-bridge, but clicking it doesn't make any difference when adding it to harmony. Also tried the other suggestions of scanning for a Hunter Douglas hub, then searching for hue, but it still wants the button pressed.

Any advice?

![Screenshot_20200328-210228](https://user-images.githubusercontent.com/4620432/77833828-1c973400-7138-11ea-8533-b739ab9d264d.jpg)

**Comment by audiofreak9** [comment]
Patience, it takes a few moments.  With the link button setting disabled, HA-Bridge broadcasts as if the HUE button was pressed.

**Comment by FourFoot** [comment]
How long does it need leaving for? I've tried various times, longest being about 40 minutes - still sat on that above screen when I came back to it

**Comment by audiofreak9** [comment]
Well, certainly 40 minutes is too long.  Mine usually too 20-30 seconds to detect.  Just tried it now and it discovered in about 20 seconds.  I did see the press the button graphic, but then it detected.

**Comment by Loafdude** [comment]
I am also experiencing this issue.
Tried in a docker container with --host and also naively in Ubuntu 10.04 LTS
I tried with manual link button and automatic link.
My harmony app sits asking the button to be pressed forever.

diyHUE also failed for me in the same way recently. 
Perhaps the harmony app has changed. It may require and change and sync to your hub to experience the issue.

I have a real harmony hub here that pairs correctly. (I power it off during pairing with habridge)

**Comment by audiofreak9** [comment]
What port are your bridges set to?  Harmony I believe, is hard coded to only discover devices on default ports 80 & 50000.

**Comment by Loafdude** [comment]
I'm definitely got the web port on 80 and upnp on 50000

**Comment by FourFoot** [comment]
Same here, 80 and 50000

**Comment by audiofreak9** [comment]
**Some more thoughts to get my setup consistent with your setup:**
- What is your "Emulate Hue Hub Version"?  Mine is 1935144020.
- What is your "Button Press/Call Item Loop Sleep Interval (ms)" setting?  Mine is 100?
- What is the UPNP delay set to for your setups?  I landed on 650 for consistent discovery.
- What ID numbers do your devices have?  Original HA-Bridge single digit start or triple digit 100 start?
- Have you tried setting "UPNP Original (simple version)" to TRUE and trying Harmony to discover HA-Bridge?

**Comment by FourFoot** [comment]
Hub version: 999999999
Button press: 100ms
UPNP delay: 650
Device IDs are >100
UPNP original: false

I'll give your settings/suggestions a shot and see what happens

**Comment by audiofreak9** [comment]
I also have both my "UPNP IP Address" and "Web Server IP Address" IP filled out the my RPi's IP.

**Comment by FourFoot** [comment]
Setting changes made no difference :-(
I also have the IP address specified in the UPNP and web server fields (as this server has multiple IP addresses)

**Comment by audiofreak9** [comment]
That's crazy, we have identical settings, short of devices, mine discovers with ease.  I assume your Harmony Hub's firmware is up to date?

One other thing occurred to me, do you have a real Philips HUE bridge?  If so turn it off while you are attempting discovery.

Also, when I go to the Bridge Devices tab and click Manage Links, I see my Harmony Hub listed as "Harmony Hub#192.168.1.151".  See if any entry matches your Harmony Hub's IP in this list.

**Comment by FourFoot** [comment]
Out of interest, I've tried removing all devices apart from one, still didn't work.
My harmony hub is on the latest firmware, has xmpp enabled (if that makes a difference) and isn't listed in the links list.

I don't have a real hue bridge.

**Comment by Loafdude** [comment]
> **Some more thoughts to get my setup consistent with your setup:**
> 
> * What is your "Emulate Hue Hub Version"?  Mine is 1935144020.
Changed mine, made no difference

> * What is your "Button Press/Call Item Loop Sleep Interval (ms)" setting?  Mine is 100?
Mine is set to 100ms. I have enabled manual link

> * What is the UPNP delay set to for your setups?  I landed on 650 for consistent discovery.
I believe you are refering to "UPNP Send Delay" which defaults to 650.

> * What ID numbers do your devices have?  Original HA-Bridge single digit start or triple digit 100 start?
I have a stock install with 1 device. ID is 100

> * Have you tried setting "UPNP Original (simple version)" to TRUE and trying Harmony to discover HA-Bridge?
Same behavior. Hub is detected but is waiting for authentication with the link button forever.
Logs show
`2020-03-29 20:18:43,955 [qtp867925190-72] INFO  com.bwssystems.HABridge.SystemControl - Link button pressed....
`2020-03-29 20:19:13,956 [Timer-4] INFO  com.bwssystems.HABridge.LinkButtonPressed - Link button time ended....

**Comment by FourFoot** [comment]
I've just set the log level on "root" to debug, attempted the pair process but nothing with my harmony hub IP shows in the log... This is making me think there's maybe something else on the network which the hub is getting a response from and thinking it's a hue hub.

I'll try putting the harmony hub and ha-bridge on its own vlan tomorrow to make sure it's not something else responding.

**Comment by Loafdude** [comment]
Kill the ha-bridge daemon and see if Harmony finds a hub instead of vlan

**Comment by FourFoot** [comment]
Good idea... Just done that and the harmony is still finding a hub... Now to try and find what it is!

**Comment by Loafdude** [comment]
My harmony is finding something as well but the official Hue app does not... odd

**Comment by Loafdude** [comment]
Got it working
Had to unplug and replug the harmony hub.
It seems to store the old hub or something?

**Comment by FourFoot** [comment]
I think my hub must be knackered... It's now on a network on its own with no other devices... Been powered off/restarted, and it's still finding a hue hub and waiting for the button to be pressed!
