### ISSUE TITLE
Add Nest support

### ISSUE THREAD

**Issue by hmspain** [bwssytems/ha-bridge#12]
My request is for the ha-bridge to support the Nest thermostat.  Everyone is waiting for the Nest skill to come out... it's almost the end of 2015 :-). Beat them to the punch like you did with Harmony support.

The Nest API requires a username (your Email address) and a password into the nest.com web site.

Here is where everything appears to be documented; https://developer.nest.com/

**Comment by bwssytems** [comment]
So, the interesting thing is... if you have a harmony hub, you can control the nest. With the bridge, it would go through the harmony activity. I know, not everyone has an harmony hub.

**Comment by hmspain** [comment]
Hmmmm.  Using the Harmony smart hub (got two) to control my Nest?  Wha?

**Comment by bwssytems** [comment]
Yep.... read it here ....
 
https://support.myharmony.com/en-us/harmony-experience-with-nest-thermostat
 
--------- Original Message --------- Subject: Re: [ha-bridge] hmspain@gmail.com (#12)

**Comment by hmspain** [comment]
Thank you!!!  If my HA gets any more complex, I think my head will explode
haha

**Comment by bwssytems** [comment]
Well, I will till keep this on the lit. There are some things we can do directly with the bridge that the harmony would have an activity for instead. We can set the thermostat to 50, in essence.
 
 
--------- Original Message --------- Subject: Re: [ha-bridge] hmspain@gmail.com (#12)

**Comment by hmspain** [comment]
I tried doing this with multiple scenes in Vera and then calling the
specific temperature scene via the Echo -> habridge -> Vera.  It didn't
work well :-).

**Comment by hmspain** [comment]
It is working, but painful.  You are limited to activities, and the best I could do was tell Alexa to cool or warm to a specific point.

Perhaps it would be useful to define what command we wanted to work and see if the bridge could make it happen...

Alexa, set nest to 75?


Harrison Spain
hmspain@gmail.com

**Comment by audiofreak9** [comment]
Could you leverage the {intensity.percent} to set the desired temperature?

**Comment by hmspain** [comment]
I'm not sure "Alexa set Nest to 50%" means much in this context :-).  Good thought though.


Harrison Spain
hmspain@gmail.com

**Comment by audiofreak9** [comment]
Yeah, that's what I thought since it's an activity.  I don't have a Vera, I use my bridge to control my X10 devices (showing my age) through a PHP interface I wrote on my RPi.

**Comment by hmspain** [comment]
LOL I have a box of X10 no longer used.  Now it's Z-Wave.  HA is still in it's infancy.  Fun to struggle with and see the evolution.

I live in a mobile home so every light switch, every socket, every light, fan, humidifier, water sensor, motion sensor, camera... Well everything is automated and now voice controlled thanks to your bridge.


Harrison Spain
hmspain@gmail.com

**Comment by audiofreak9** [comment]
You sure are right that it is fun to struggle with and see the evolution of the ha-bridge.  When I bought my Echo I was searching for a solution to connect it to my X10.  I came across the MiCasaVerde Forum this past June, and began with ARM's version and evolved to Crush's, I love that I can connect my smart home devices, even though they are X10 to my Echo!

**Comment by hmspain** [comment]
The habridge can control anything that is "IP" accessible, but therein lies the rub.  Most don't have the time or inclination to figure out the syntax.  Your bridge provides a cool UI that allows even a novice to point a command phrase to a Vera scene or device.

Adding Nest to that IF would be a welcome addition.

I added an ezOutlet to power my Vera.  As we all know, at times the Vera needs a power reboot LOL.  With the ezOutlet I can cycle the power from work or vacation.  Since the ezOutlet has an IP interface, I can also reboot my Vera using your bridge!

Alexa, turn off Vera

Very cool.


Harrison Spain
hmspain@gmail.com

**Comment by bwssytems** [comment]
I use mostly X10 and some Zwave. Changing over slowly. I got a a vera due to the fact I bought a zwave door lock. Integration for Vera with 10 CM11 and CM15  are so easy and I hate not using what I have.

On ANother note, I will put NEST integration up next after the UDP impl is done. It will be similar to the way the harmony control works for authentication and having multiple units.

**Comment by hmspain** [comment]
Wonderful news! I look forward to trying out the new functionality.
