### ISSUE TITLE
sleep button null pointer exception issue in 2.0.7

### ISSUE THREAD

**Issue by eatonsn4** [bwssytems/ha-bridge#120]
C:\homeseerapi>java -jar -Dorg.slf4j.simpleLogger.defaultLogLevel=DEBUG ha-bridge-2.0.7.jar
2016-05-28 10:17:00,463 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v2.0.7) starting....
2016-05-28 10:17:00,473 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
Exception in thread "main" java.lang.NullPointerException
        at com.bwssystems.HABridge.BridgeSettings._loadConfig(BridgeSettings.java:175)
        at com.bwssystems.HABridge.BridgeSettings._loadConfig(BridgeSettings.java:169)
        at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:55)
        at com.bwssystems.HABridge.HABridge.main(HABridge.java:52)

Config file:

{
	"name" : "Light",
	"deviceType" : "switch",
	"onUrl" : "http://192.168.5.xx:80/JSON?request=controldevicebylabel&ref=5&label=On",
	"offUrl" : "http://192.168.5.xx:80/JSON?request=controldevicebylabel&ref=5&label=Off"
}
{
	"name" : "Garage Light",
	"deviceType" : "switch",
	"onUrl" : "http://192.168.5.xx:80/JSON?request=controldevicebylabel&ref=61&label=On",
	"offUrl" : "http://192.168.5.xx:80/JSON?request=controldevicebylabel&ref=61&label=Off"
}
{
	"name" : "Switch Binary",
	"deviceType" : "switch",
	"onUrl" : "http://192.168.5.xx:80/JSON?request=controldevicebylabel&ref=66&label=On",
	"offUrl" : "http://192.168.5.xx:80/JSON?request=controldevicebylabel&ref=66&label=Off"
}
{
	"name" : "Alarm",
	"deviceType" : "switch",
	"onUrl" : "http://192.168.5.xx:80/JSON?request=controldevicebylabel&ref=73&label=On",
	"offUrl" : "http://192.168.5.xx:80/JSON?request=controldevicebylabel&ref=73&label=Off"
}

**Comment by bwssytems** [comment]
So, if this is your config file, it is all the data from a device.db file and the bridge is choking in it. Rename this to your device.db file and start the bridge.

**Comment by eatonsn4** [comment]
I realized that after and have it working.  I did modify your load config code to ignore null exception pointers.  I can send you the code to save you some time.  If every expected option is not properly specified in that config file it will still error on an unhandled null exception.  Another issue I had was it wasn't viewing correctly in the original IE with windows 7.  No devices or buttons would show up to add devices.  Once I viewed it in Firefox then I realized what was happening.  It also works fine on an up to date IE on windows 7 as well.  I didn't look at the versions, but I am sure they are different since the original one is dedicated for homeseer.  Great work on the code and let me know if you need any help.  I like where you are headed.

**Comment by bwssytems** [comment]
Will implement a better handling of the config file in a future release. Thanks for tracking that down.
