### ISSUE TITLE
mochad / ha-bridge echo 2 not dimming to percentage

### ISSUE THREAD

**Issue by pittgo** [bwssytems/ha-bridge#1203]
I created a file named stovedim with my path echo "pl a3 dim ${intensity.math(((X*-31)/255)+31)}" | nc -w1 localhost 1099   make it executable them call it from the script callout dim in ha-bridge   it doesn't work on my original  X10  lamp modules or light switch controllers

Does anyone have experience getting Alexa to dim to varying levels ?

Thanks

**Comment by bwssytems** [comment]
Does the script work from the command line?

**Comment by pittgo** [comment]
how would i substitute  the variable with a value?

**Comment by pittgo** [comment]
here is the log 

04-13-2020 14:38:05.550	DEBUG	HueMulator PUT called on api/* with request <<</api/d67e77dd6e364165b0a7417ebb643eed/lights/107/state>>>, and body <<<{"on":true,"bri":128}>>>	com.bwssystems.HABridge.hue.HueMulator
04-13-2020 14:38:05.552	DEBUG	matchedPart: :userid = d67e77dd6e364165b0a7417ebb643eed	spark.Request
04-13-2020 14:38:05.553	DEBUG	matchedPart: :id = 107	spark.Request
04-13-2020 14:38:05.554	DEBUG	hue state change requested: d67e77dd6e364165b0a7417ebb643eed from 192.168.0.16 body: {"on":true,"bri":128}	com.bwssystems.HABridge.hue.HueMulator
04-13-2020 14:38:05.556	DEBUG	validateWhitelistUser: found a user <d67e77dd6e364165b0a7417ebb643eed>	com.bwssystems.HABridge.BridgeSecurity
04-13-2020 14:38:05.557	DEBUG	Calling on-off as requested.	com.bwssystems.HABridge.hue.HueMulator
04-13-2020 14:38:05.557	DEBUG	Decode Json for url items: [{"item":"/home/pittgo/Downloads/mochad-0.1.16/Stovelighton","type":"cmdDevice"}]	com.bwssystems.HABridge.hue.HueMulator
04-13-2020 14:38:05.559	DEBUG	Calling Home device handler for type : cmdDevice	com.bwssystems.HABridge.hue.HueMulator
04-13-2020 14:38:05.561	DEBUG	Exec Request called with url: /home/pittgo/Downloads/mochad-0.1.16/Stovelighton and exec Garden: not given	com.bwssystems.HABridge.plugins.exec.CommandHome
04-13-2020 14:38:05.562	DEBUG	Request <</home/pittgo/Downloads/mochad-0.1.16/Stovelighton>>, not done: false	com.bwssystems.HABridge.hue.DeviceDataDecode
04-13-2020 14:38:05.563	DEBUG	Executing request: /home/pittgo/Downloads/mochad-0.1.16/Stovelighton	com.bwssystems.HABridge.plugins.exec.CommandHome
04-13-2020 14:38:05.569	DEBUG	Process running: true	com.bwssystems.HABridge.plugins.exec.CommandHome
04-13-2020 14:38:05.570	DEBUG	Calling dim as requested.	com.bwssystems.HABridge.hue.HueMulator
04-13-2020 14:38:05.671	DEBUG	Decode Json for url items: [{"item":"/home/pittgo/Downloads/mochad-0.1.16/Stovelightdim"}]	com.bwssystems.HABridge.hue.HueMulator
04-13-2020 14:38:05.671	DEBUG	Calling Home device handler for type : cmdDevice	com.bwssystems.HABridge.hue.HueMulator
04-13-2020 14:38:05.671	DEBUG	Exec Request called with url: /home/pittgo/Downloads/mochad-0.1.16/Stovelightdim and exec Garden: not given	com.bwssystems.HABridge.plugins.exec.CommandHome
04-13-2020 14:38:05.671	DEBUG	Request <</home/pittgo/Downloads/mochad-0.1.16/Stovelightdim>>, not done: false	com.bwssystems.HABridge.hue.DeviceDataDecode
04-13-2020 14:38:05.671	DEBUG	Executing request: /home/pittgo/Downloads/mochad-0.1.16/Stovelightdim	com.bwssystems.HABridge.plugins.exec.CommandHome
04-13-2020 14:38:05.674	DEBUG	Process running: true	com.bwssystems.HABridge.plugins.exec.CommandHome
04-13-2020 14:38:05.699	DEBUG	HueMulator GET called on api/* with request <<</api/d67e77dd6e364165b0a7417ebb643eed/lights/107>>>, and body <<<>>>	com.bwssystems.HABridge.hue.HueMulator
04-13-2020 14:38:05.702	DEBUG	matchedPart: :userid = d67e77dd6e364165b0a7417ebb643eed	spark.Request
04-13-2020 14:38:05.705	DEBUG	matchedPart: :id = 107	spark.Request
04-13-2020 14:38:05.706	DEBUG	hue light requested: 107 for user: d67e77dd6e364165b0a7417ebb643eed from 192.168.0.16	com.bwssystems.HABridge.hue.HueMulator
04-13-2020 14:38:05.706	DEBUG	validateWhitelistUser: found a user <d67e77dd6e364165b0a7417ebb643eed>	com.bwssystems.HABridge.BridgeSecurity
04-13-2020 14:38:05.707	DEBUG	found device named: Stove Light	com.bwssystems.HABridge.hue.HueMulator

**Comment by bwssytems** [comment]
This line:
04-13-2020 14:38:05.550 DEBUG HueMulator PUT called on api/* with request <<</api/d67e77dd6e364165b0a7417ebb643eed/lights/107/state>>>, and body <<<{"on":true,"bri":128}>>> com.bwssystems.HABridge.hue.HueMulator

Is the one to look for when testing. It says the bri value is 128 which is 50%

**Comment by pittgo** [comment]
yes after the test callout  for 50 % the intensity.math should have taken that value and applied it as the X  ...driving an output of ((((128*-31)/255)+31)    or 15.4   this value should have dimmed the module to ~50%  I dont see where the value of 128 has been converted and sent at the 15.4 value?

**Comment by bwssytems** [comment]
So you will need to turn debug on the tcp device plugin to see what it calculated.

**Comment by pittgo** [comment]
The DEBUG for com.bwssystems.HABridge.plugins.tcp renders nothing in the llog  nor does the com.bwssystems.HABridge.hue.BrightnessDecode . I was hoping to see the math results in the latter.

**Comment by pittgo** [comment]
I solved this by executing the dim through a shell vs the raw echo "pl a3 dim ${intensity.math(((X*-31)/255)+31)}" | nc -w1 localhost 1099 

I creates an executable script  called x10cmd   with echo "$@" | nc localhost 1099

then i call the dim command in the bridge with /x10cmd dim ${intensity.math(((X*-21)/255)+21)}
