### ISSUE TITLE
alexa not dimming lights

### ISSUE THREAD

**Issue by InfamousTony** [bwssytems/ha-bridge#1206]
It started about 2-3 days ago and alexa keeps saying "Device doesn't support requested value". When i try to ask her to set the lights to a % she either just beeps like she understands it or sometimes says "sorry i don't know that". When i try to tell her, this is what comes through in the logs:
Apr 23 22:45:57 raspberrypi dhcpcd[565]: eth0: offered 192.168.xx.x from 192.168.xxx.x
Apr 23 22:45:57 raspberrypi dhcpcd[565]: eth0: NAK: wrong server-ID from 192.168.xx.x
Apr 23 22:45:57 raspberrypi dhcpcd[565]: eth0: message: wrong server-ID

Please help.

Weird thing: if i use the app on my iphone to say these commands, they work with no issues.

**Comment by bwssytems** [comment]
those log messages are from dhcp and not the ha-bridge. post the ha-bridge log with traceupnp and tracestate turned on.
