### ISSUE TITLE
Only "turn on" and "turn off" works...rest do not work.

### ISSUE THREAD

**Issue by smarty125** [bwssytems/ha-bridge#121]
I recently tried to add a custom device (driveway gate), where the "on" URL would OPEN the "driveway gate", and the "off" URL would CLOSE the "driveway gate".

After discovering the new device, Alexa will only "turn on" or "turn off" the device.  Using the phrase "open" or "close" would not work.  I did try renaming the device to just "gate"; there was no change.  I also tried all the other "on" phrases in the README.md.  The only one that worke, was "turn on".

Could it be that the "open" and close" phrases (as well as the others) no longer work with this emulator (ver. 2.0.7)?  I hope I screwed something up, but if not, the README.md should be updated.

**Comment by bwssytems** [comment]
Some others have noticed this a well. It seems Amazon is now reserving words for other systems and those are not compatible with the Philips Hue, which this bridge emulates. Sorry that there is not much that can be done since all the phrases are interpreted by Amazon and not the bridge.

**Comment by bwssytems** [comment]
Closing, Amazon controls the utterances and their actions.
