### ISSUE TITLE
[Enahnacement] Have link button timeout be configurable

### ISSUE THREAD

**Issue by tjedmunds** [bwssytems/ha-bridge#1210]
I am running RC1 now for a few weeks and no real issues. Great solution! Discovery also works once I opened ports 50000 and 1900 for UPNP in my firewall.

I just wondered why the Link button only works for 30 seconds when Alexa requires a full 45 seconds to run discovery. I changed ha-bridge to 60 seconds thinking it would make it easier to Link and it would be great if this was built-in or even configurable. Wouldn't it be better to run Link for the entire time of discovery to avoid timing issues?

I was also running the java11 version before this RC so I compiled from source since I didn't see a java11 build this time around. Perhaps that isn't necessary anymore?

**Comment by bwssytems** [comment]
I agree, we can have the timeout as a variable in the control page and increase the default.
