### ISSUE TITLE
How to dim in steps from 1-6 

### ISSUE THREAD

**Issue by schnippendullerich** [bwssytems/ha-bridge#1220]
Hi,

it seems like a ceiling fan with speed steps 1-6 with summer and winter mode, timer function and light is hard to control in one device as there is only on, off, dim and color available.

So far I can turn it on the fan with speed level one (or different depending on the called command) by a shell sript. The light control is managed in another device called "Ceiling Fan Light".

I would love to make it more flexible by passing a number as parameter e.g "/home/pi/fanspeed.sh [1-6]".
Is it possible to realize this with dim? Would it be done with the intense.math function? If yes, I honestly don't get how to use it. Apart from that I am unsure if ha-bridge variables can be used to pass paramters to scripts.

I the end it should work like this expample:
"Alexa, turn on ceiling fan speed level 3" 

Thank you for your help.

Kay

**Comment by CatmanV2** [comment]
I could be totally wrong, but isn't this totally analagous to what happens with a thermostat?

What's the script you run currently?

C

**Comment by schnippendullerich** [comment]
Not sure. But possibly as you need to pass specific values like "22" for 22°C. The script is a simple bash script:
`#!/bin/bash
case $1 in
	0|1|2|3|4|5|6) /usr/local/bin/pilight-send -p raw -c "$(< /home/pi/ceiling-fan/commands/level$1.raw)";;
	*) echo "Value for speed level not provided or wrong. Valid values are 0 (stop), 1, 2, 3, 4, 5 or 6 (maximum speed). Setting speed level 1 (default)."
           /usr/local/bin/pilight-send -p raw -c "$(< /home/pi/ceiling-fan/commands/level1.raw)";;
esac`
In HA-Bridge it looks like this currently:
DimUrl: [{"item":"/home/pi/ceiling-fan/scripts/fanspeed.sh ${intensity.math(X)}","type":"cmdDevice"}]
But simply using X is not working as expected. When I say "Alexa, Ceiling Fan 3" the fan changes to speed level one only if it was higher before. So I guess the value which the script gets is wrong. Maybe the command line in HA Bridge is wrong as I might still not completely understand how HA-Bridge works.

**Comment by CatmanV2** [comment]
OK I *think* we are talking at cross purposes, but I am NOT a coder. More a practical sort of guy

> So far I can turn it on the fan with speed level one (or different depending on the called command) by a shell sript.

Can you share that script. That *works*? The one above seems to be your attempt at passing your variable?

The Dim ULR looks like it's calling fanspeed.sh? Is this the one you're using?

C

**Comment by schnippendullerich** [comment]
> > So far I can turn it on the fan with speed level one (or different depending on the called command) by a shell sript.
> 
> Can you share that script. That _works_? The one above seems to be your attempt at passing your variable?
It's the one I posted above.
> The Dim ULR looks like it's calling fanspeed.sh? Is this the one you're using?
Correct.

**Comment by CatmanV2** [comment]
Ahh right

Can you share

/usr/local/bin/pilight-send

C

**Comment by schnippendullerich** [comment]
The program [pilight-send](https://manual.pilight.org/programs/send.html) is just part of Pilight. I am using this to send the signbal to the fan. It only works with 433MHz radio signals. There is a 433MHz sender module connected to the raspberry pi where everything is running on.

**Comment by CatmanV2** [comment]
OK with you. The options for pilight appear badly thought out. I count -c used 3 times so maybe expressly state --code?

OK if this was me, I'd start by trying to make it work manually as it were.

Have you established the value of /home/pi/ceiling-fan/commands/level$1.raw ?

I'm probably not being much help :(

C

**Comment by audiofreak9** [comment]
I use HEYU to control my X10 modules, they only accept dim level values of 0-22, so I use: 
`${intensity.math(((X*-22)/255)+22)}`
however, HEYU accepts 0 as no dim, 22 as full dim - probably opposite your needs.  So I think this may work for your 1-6 dim level:
`${intensity.math((X*6)/255)}`
What the above does is multiply the given dim X value from HA-Bridge by 6, then divide it by 255 - the max value, to get the fraction of 6 of the given HA-Bridge dim value.  The math() will provide a whole number.
Hope this helps?

**Comment by audiofreak9** [comment]
NOTE: With `${intensity.math((X*6)/255)}`, you can naturally ask for values of 0 to 100% with the Alexa, rather than 1 through 6.

**Comment by schnippendullerich** [comment]
Right and that works great. Thank you very much!
So I guess that means Alexa can only work with values in percent.

**Comment by audiofreak9** [comment]
You can say, "Alexa, set {device] to 30" without needing to say "percent" at the end of the phrase, but it's just not natural to say it that way.

**Comment by schnippendullerich** [comment]
Allright, thanks a lot.
