### ISSUE TITLE
Dealing with stateless dimmable lamps with step brightness

### ISSUE THREAD

**Issue by fzmemon** [bwssytems/ha-bridge#1222]
I have some no-name lamps which offer a REST API for turning them on, turning them off, incrementing brightness and decrementing brightness in steps of 10%. Unfortunately I cannot query these lamps for their current state.

I would very much like to control the brightness of these lamps via Alexa over habridge. However for that, I don't only need the target brightness but also the current brightness value from habridge. If I had both values, I could calculate how many steps I should increment or decrement the lamps to reach the target brightness. So the question is, is it possible to access the current brightness of these lamps?

**Comment by audiofreak9** [comment]
@fzmemon Look at the "[Get light attributes and state](https://github.com/bwssytems/ha-bridge#get-light-attributes-and-state)" section of the README, most importantly the State object.

**Comment by fzmemon** [comment]
@audiofreak9 Thanks for quick response. I thought of that already. However when I try to get the state in a script which is called via habridge, it is already updated to the target brightness.

If I turn on the "No State" option, I do get the current brightness in the script and can calculate the target brightness and set it afterwards via /updatebridgestate. This does seem to work. However, turning on the "No State" breaks alexa responses somehow. The response become something like "sorry <deviceName> didn't respond". Although everything works.

**Comment by audiofreak9** [comment]
@fzmemon I have a few devices configured with "No State" set TRUE, since both the On and Off do the same thing with these devices (ie. one will update my HA-Bridge device states for my X10 and MQTT equipment).  I do not have a failed to respond issue operating them with Alexa, since my script that the device is tied to reports HTTP success back to HA-Bridge.  

So this brings a few thoughts to my mind.  I wonder if HA-Bridge is reporting an HTTP success response to the Echo with the device State Change?  So when you set "No State" TRUE with your device(s), which do not respond this may be the problem?  What does your ON Items and OFF Items look like - (anonymize them as needed)?  

What I'm getting at is Alexa requires an HTTP success response: HTTP 200, 201, 202, etc. to not report the "sorry {deviceName} didn't respond".  You might need to write a script that fires your no-name lamps REST API, then use that script in HA-Bridge, and your script can provide the HTTP success response the Echo is looking for.

**Comment by fzmemon** [comment]
I think I need to provide more details so here it comes. Here is one of my configured lights:
`On Item: http://localhost:8021/on?ip=192.168.1.140&zone=3&deviceId=100
Off Item: http://localhost:8021/off?ip=192.168.1.140&zone=3&deviceId=100
Dim Item: http://localhost:8021/dim?ip=192.168.1.140&zone=3&deviceId=100&intensity=${intensity.percent}`

On and off work like a charm. But Dim is leading to "Sorry deviceName appears to be malfunctioning". Here is the JS method which is invoked by the dim item above:
`
var callback = function () { response.writeHead(200, {'Content-Type': 'text/html'});response.end();}
adjustBrightness(query.ip, query.zone, query.deviceId, query.intensity, callback);

function adjustBrightness(ipAddress, zone, deviceId, intensity,callback) {
    var light = new Milight.MilightController({
        ip: ipAddress,
        type: 'v6'
    });
 
    getCurrentState(deviceId, function (state) {
         if(state.on == true) {
             console.log("Setting target brigtness to: " + intensity);
             var promiseArray = [];
             if (intensity == 100) {
                 promiseArray.push(light.sendCommands(commands.white.maxBright(zone)));
             } else {
                 var deltaBri = intensity - Math.ceil((state.bri * 100) / 254);
                 console.log("Delta brightness: " + deltaBri);
                 if (deltaBri < 0) {
                     for (var i=0; i < (deltaBri * -1) / 10; i++) {
                         promiseArray.push(light.sendCommands(commands.white.brightDown(zone))); 
                         promiseArray.push(light.pause(500));
                     }
                 } else {
                     for (var i=0; i < deltaBri / 10; i++) {
                         promiseArray.push(light.sendCommands(commands.white.brightUp(zone)));
                         promiseArray.push(light.pause(500));
                     }
                 }
             }
             updateState("bri", Math.ceil((intensity * 254) / 100),deviceId,callback);
             console.log("Executing " + promiseArray.length/2 + " adjust brightness commands");
             Promise.all(promiseArray).then(function() {
                 light.close().then(function () {
                     console.log("Adjust brightness commands executed.");
                   }).catch(function(error) {
                     console.log(error);
                 });
             }).catch(function(error) {
                 console.log(error);
             });
         } else {
             console.log("Light is off. Cannot set brightness");
         }	
     });
 }`

The function updateState() is invokes the /bridgeupdatestate for updating the brightness since "No State" is enabled. See if you can find an issue in the script.

**Comment by audiofreak9** [comment]
Thanks for the details, much easier to troubleshoot.

Just quickly looking through the script, if intensity is < 100 then it loops deltaBri until it matches the intensity requested with a `pause(500)` at each iteration of the loop.  The promiseArray must resolve this loop, then respond with the HTTP 200.  Not knowing how MiLights dim, they may require one '10' dim step at a time with the delay?  However, the Echo is expecting the HTTP 200 response within a set time limit.  Your script may be outside that set response time limit?  I see what you're doing, if it fails then it doesn't respond with HTTP 200 and doesn't update the /bridgeupdatestate.

Maybe you should send HTTP 200 first no matter on/off/dim, this would really just relay to the Echo that the HA-Bridge successfully sent the command to your script.  Your script from there update the /bridgeupdatestate, if successful.  Your script logs errors for troubleshooting, so the Echo need not know if your script was successful, only that the HA-Bridge successfully sent the command to a script that didn't error when received.  

I hope that makes sense?

**Comment by fzmemon** [comment]
You understood the script correctly :) and thanks for the input. I just updated the code and now I am responding with 200 as soon as I receive the dim request. However the issue persists still. So the probably the issue is on the ha-bridge side which would also match with the observation that dim works fine if "No State" is false even if I send a response after actually processing the `promiseArray`.

The script responds pretty fast, and Alexa's response "Sorry deviceName appears to be malfunctioning" is also instantaneous. Don't think it is a timing issue. Any other ideas?

Only if I could pass current and targer brightness to the script from ha-bridge. I wouldn't have to set "No State" to true.

**Comment by fzmemon** [comment]
I did some tests and found out an interesting thing, i.e. there are only certain percentage values which are causing Alexa to respond that the device is malfunctioning. For example, setting device to 30% gets me a successful response but setting it to 80% always causes the error. So it clicked to me that I might have a conversion discrepancy which looks like this 

1. Alexa tells ha-bridge set light to 80%
2. ha-bridge invokes the script to set the light to 80%
3. Script coverts 80% to a value between 1 and 254 and set that value to at ha-bridge
4. ha-bridge converts the value again and reports to alexa as a percentage.

Double conversion in 3 and 4 are probably causing precision error so for 80% which Alexa told ha-bridge to set, ha-bridge is probably reporting that I set 81% or 79%. This cause Alexa to say, that's not the value I asked for. Dang! error....

Any ideas how to avoid this conversion discrepancy?

**Comment by fzmemon** [comment]
Just found out that I could pass-through the intensity as 'intensity.byte' from ha-bridge. Now I am getting the value as byte, converting it to percentage for internal use and then setting the same value back to ha-brige. All issues resolved.
Thank you @audiofreak9 for the discussion. Sometime one just needs to discuss the issues to find the bug!
Closing the issue.
