### ISSUE TITLE
No change to setup (running on Rpi) but service refuses to load now

### ISSUE THREAD

**Issue by dazed24** [bwssytems/ha-bridge#1223]
Appreciate the work done on this and have been using this since version sub 1.0

I have the service running on a headless Rpi, which all of a sudden refuses to load. Reboots of the Rpi don't work, and I've tried wiping the config file with a fresh one, but same error.

Log file shows:

Jul 15 19:07:10 raspberrypi systemd[1]: Started HA Bridge.
Jul 15 19:07:12 raspberrypi java[913]: 2020-07-15 19:07:12,826 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge startup sequence...
Jul 15 19:07:13 raspberrypi java[913]: 2020-07-15 19:07:13,389 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v5.3.0) initializing....
Jul 15 19:07:13 raspberrypi java[913]: 2020-07-15 19:07:13,398 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: /home/pi/ha-bridge/data/habridge.config
Jul 15 19:07:13 raspberrypi java[913]: Exception in thread "main" java.lang.NullPointerException
Jul 15 19:07:13 raspberrypi java[913]: #011at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:170)
Jul 15 19:07:13 raspberrypi java[913]: #011at com.bwssystems.HABridge.HABridge.main(HABridge.java:58)
Jul 15 19:07:13 raspberrypi systemd[1]: ha-bridge.service: Main process exited, code=exited, status=1/FAILURE
Jul 15 19:07:13 raspberrypi systemd[1]: ha-bridge.service: Failed with result 'exit-code'.

Unfortunately I can't get it to run so can't change any settings via the web UI

Should I just wipe the Pi and start a fresh Raspbian install?

**Comment by ma11w00d** [comment]
I have exactly the same issue.  Did you manage to resolve.

**Comment by bwssytems** [comment]
Which version of the ha-bridge is being run as it is not in the log?

**Comment by ma11w00d** [comment]
I am runnung 1.10.5 (nodemcuv2).  I resolved the issue soon after posting.  I copied ha-bridge.config to ha-bridge.config.old and then the service started.  I must have then restored from a backup.
