### ISSUE TITLE
where is the "releases" section?

### ISSUE THREAD

**Issue by martijintro** [bwssytems/ha-bridge#1224]
Hello

I can't see that anymore... (?)

Did you hide it or github has changed its gui?

Thank you for your feedback! :-)

Best regards,
Jan

**Comment by audiofreak9** [comment]
Github changed the GUI, it's labeled "Releases" in the right sidebar under "About".

**Comment by martijintro** [comment]
Thanks, but i can't find any about link / text when i search with Ctrl-F, just the "About" word in your text and the about link on bottom:

![about](https://user-images.githubusercontent.com/42765391/88151820-74840a00-cc03-11ea-9f3f-06c7169ddfc2.png)

**Comment by audiofreak9** [comment]
![bwssytems-ha-bridge-Home-automation-bridge-that-emulates-a-Philips-Hue-light-system-and-can-control-other-systems-such-as-a-Vera-Harmony-Hub-Nest-MiLight-bulbs-or-any-other-system-that-has-an-http-https-tcp-udp-interface-This-is-a-compact-i](https://user-images.githubusercontent.com/6260089/88231567-77eab600-cc42-11ea-9f10-da96d56647e3.png)

**Comment by jmar83** [comment]
Thank you very much, now i saw it!

(This is my personal account..)

Best regards,
Jan
