### ISSUE TITLE
Feature request: ${intensity.previous} value passing control

### ISSUE THREAD

**Issue by peskdale** [bwssytems/ha-bridge#1227]
I have a couple of uses in my setup where I don't need to know a new brightness value on a dim command, but rather the difference relative to the old one.

e.g . I'm using the dim functionality to exec a script to increase/decrease of the volume of a device. I don't care what the actual brightness value of the 'light bulb' is - I just want to know if an increase or decrease has been requested.

Currently, I'm making this work by storing the previous intensity value in a text file that I can look up next time the dim command is executed. But that number already exists in ha-bridge, and [is even used](https://github.com/bwssytems/ha-bridge/blob/master/src/main/java/com/bwssystems/HABridge/hue/BrightnessDecode.java#L25) in calculating the new value.

It would be great to have an additional command that could accommodate workflows like mine, which returns the previous intensity, allowing it to be used in directly by other scripts.

**Comment by audiofreak9** [comment]
@peskdale Could you leverage the [GET light attributes and state](https://github.com/bwssytems/ha-bridge#get-light-attributes-and-state) prior to executing your command command?

**Comment by peskdale** [comment]
@audiofreak9 Thanks for the suggestion. I have just tried implementing that request at the start of my script.

However, it seems that the new brightness value is already present in the response.

**Comment by bwssytems** [comment]
This will be in the next release

**Comment by bwssytems** [comment]
The components available will be

${intensity.previous_percent}
${intensity.previous_decimal_percent}
${intensity.previous_byte}
