### ISSUE TITLE
SSH shutdown command to W10 & GroovyArcade (Linux)

### ISSUE THREAD

**Issue by solderchicken** [bwssytems/ha-bridge#1229]
Hi BWS

Sorry for this message, but I am cannot figure out how to shutdown my W10 PC and GroovyArcade (Linux) PCs with HA-Bridge using SSH.

I have SSH working for both Linux & W10, public keys are copied and I can login to both over SSH without a password.

I can shutdown the Linux PC using

ssh root@<IP.ADDRESS> sudo shutdown now &> /dev/null &

and the W10 PC using

ssh <username>@<IP.ADDRESS> shutdown -f 0

or 

ssh <username>@<IP.ADDRESS> shutdown -s -t 00

I have tried entering these commands in ha-bridge as written above, but they have no effect on the PCs.

The W10 PC displays that an SSH command has been recieved, but the command does not shut it down.

I have also tried executing a local script on the raspberry PI using ha-bridge, but that does not work either. 
If I run the script in terminal, it does work though!

Apologies if I have not given the correct, or enough,  information, hope someone can help.

Many thanks

SDCHick

![Screen Shot 2020-09-02 at 23 18 31](https://user-images.githubusercontent.com/60044004/92043226-92e93380-ed73-11ea-8b14-830f7eb7345f.png)
![Screen Shot 2020-09-02 at 23 20 42](https://user-images.githubusercontent.com/60044004/92043230-941a6080-ed73-11ea-8381-18dcd517d3cb.png)
![Screen Shot 2020-09-02 at 23 21 03](https://user-images.githubusercontent.com/60044004/92043232-94b2f700-ed73-11ea-9b34-495344e4c44f.png)

**Comment by bwssytems** [comment]
You will need to preface those commands with a shell execute environment such as sh or bash for linux or cmd.exe or the powershell command for windows.

**Comment by solderchicken** [comment]
Thank you BWS.

I actually got it to work with the commands above, it was that I hadn't added the keys for ha-bridge root user to target machine.

Works a charm now! Thank you for this software!

PS - I'm using Bitvise SSH Server free edition. Works really well for this task and highly configurable.
