### ISSUE TITLE
Adding arguments to bash script

### ISSUE THREAD

**Issue by feriniguez** [bwssytems/ha-bridge#1235]
Hello, I would like to know if there is possible to add arguments when execute a bash script.

I'm able to execute scripts from the Execute Command/Script/Program with no issues when there are no arguments. Like this:

/home/username/Scripts/./Activity1.sh

I have one script that controls almost all of my stuff but I just need to add the proper argument. I would like to run some like this:

/home/username/Scripts/./Master.sh TVON
This works great from my terminal.
In HA-bridge I get a success message when I push the Test ON button but the script is executed without the argument added to the line.

I haven't found any information in the documentation nor googling. 
Any ideas?

Thanks!
V5.3.0

**Comment by audiofreak9** [comment]
Hey @feriniguez,

Yes, I use a bash script to control blinds with arguments, my ON / DIM / OFF items in HA-Bridge are the following:

- ON: `/home/pi/habridge/blinds.py True`
- DIM: `/home/pi/habridge/blinds.py True ${intensity.percent}`
- OFF: `/home/pi/habridge/blinds.py False`

**Comment by feriniguez** [comment]
Ok, it is good to know that the feature is there... however I can not get it working.

I have tried adding | sh | bash | exec:// | at the beginning of the line but no success... 

The script have (just for testing) 777 permissions.

**Comment by feriniguez** [comment]
Ok I found the solution...

My script used the paths to files in the form:
~/directory/to/file.txt
It worked without issues directly from the terminal or ssh'ing to the host and running the script.
It didn't work from ha-bridge.

I did some testing and noticed that the script wasn't getting the info from the files. So I changed the paths to:
/home/username/directory/to/file.txt
and worked!

I don't really know why just from ha-bridge you need the absolute path but I'm happy I found the solution.

Closing.
