### ISSUE TITLE
Is only for ON/OFF ?

### ISSUE THREAD

**Issue by Bobsilvio** [bwssytems/ha-bridge#1236]
does ha-bridge only serve to make an ON / OFF?
i am trying to emulate a tv, so i should also give commands like, volume up / down, change channels (trami internal api) http: // xxxxx / api? vol = up

**Comment by lollett** [comment]
Hi Bob,  This has been answered in the FAQ: https://github.com/bwssytems/ha-bridge/wiki/HA-Bridge-FAQs#commands
It's is simply a limitation of the real Philips Hue Bridge API which was really designed for light bulbs.

A workaround might be to use the SET / DIM / BRIGHT commands: 
https://github.com/bwssytems/ha-bridge#ask-alexa
https://github.com/bwssytems/ha-bridge#google-assistant

Example:
"Alexa, SET TV VOLUME to 10" 
"Alexa, SET TV CHANNEL to 10" 
"Alexa, DIM TV [VOLUME/CHANNEL]"
"Alexa, DIM TV [VOLUME/CHANNEL] to 10"

**Comment by bwssytems** [comment]
Is this still an issue?
