### ISSUE TITLE
Understanding RGB color conversion

### ISSUE THREAD

**Issue by JsChiSurf** [bwssytems/ha-bridge#1237]
So, I just started playing around with the ${color.r},${color.g},${color.b} color replacement variables.  The whole process by which a color name is converted to an RGB value is black box to me (I assume Hue has some built in mappings?).

Regardless, I can use the "test color" button in ha-bridge, set a custom RGB value, and if I set it to 'red', for example, I see the expected query string parameter sent to my server, defined as "&color=${color.r},${color.g},${color.b}" sent as : "&color=255,0,0".

However, when I use a verbal command to the echo, such as: "Set the couch light to color red", what gets passed to my server is: "&color=255,253,255" (which as we know is not red / is almost full white).

No matter what is the "standard" colors I request, they are all relayed as some similar form of the RGB values above, such as:

=255,253,255
=255,255,253

And so on.  I'm probably doing something wrong and/or am not 100% clear on the commands to use, etc.  Looking for some insight.  Thanks.  Running on v5.3.0.

**Comment by bwssytems** [comment]
Could you turn on trace state changes and post your log

**Comment by bwssytems** [comment]
I have fixed the color conversions in RC4, please try that.

**Comment by JsChiSurf** [comment]
Thanks, I will test out.

On a related note, when setting up a "custom" device, is there a trick to make the echo think/know the device is color capable, so as to use the ability to pass r,g,b values?  I've tried setting the 'device type' drop-down to a variety of devices, but after discovery, when attempting to issue a voice command to set a particular color, Alexa responsds with "...device doesn't support that".

I'm assuming that device capability is determined during the discovery process?  If so, and there is not currently a way, could an option exist to set the 'device type' as a 'color capable light'?  There is probably already a way and I'm simply overlooking it as well.

Thanks.

**Comment by bwssytems** [comment]
When in the device editor, put in instructions in the color area as that handles the control whether the device is color or not
