### ISSUE TITLE
Commands all work properly using test on HA-BRIDGE, but confused when initiated thu Alexa

### ISSUE THREAD

**Issue by dcuste** [bwssytems/ha-bridge#1240]
I'm running v5.3.0 and has worked well for over a year. I added devices and now have 13 but alexa wouldn't find them. I deleted all devices in Alexa and I also renumbered them in HA-BRIDGE. Alex discovered only 10 devices and now even though ever device tests correctly in the HA-BRIDGE, Alexa doesn't control the correct device. e.g. I order the livingroom lights on and Alexa will turn on the hall lights. Is their a limited number of devices that Alexa will discover from the HA-BRIDGE? Is the renumbering what screwed up Alexa and what is the fix?

**Comment by amyth1884** [comment]
I too am facing this issue, about a week ago new devices were getting recognized, but now no new device is getting recognized, seems like Amazon has made some changes. Any help would be really great

**Comment by audiofreak9** [comment]
Many have reported [the process detailed in this post](https://github.com/bwssytems/ha-bridge/issues/1185#issuecomment-625803726) works given this problem.

**Comment by amyth1884** [comment]
Tried this method as well, still no luck 

> What I did to discover devices again:
> 
> * Remove all devices + Rooms in the Alexa-App
> * Renumber all devices in the web interface
> * Restart the raspberry pi
> * Turn off alexa and wait a few seconds and turn it on again
> * Search for devices

**Comment by dcuste** [comment]
I also tried all the steps below and even went as far as reinstalling the HA-BRIDGE and rebuilding the data base. Alexa did discover the devices but the controls are still confused.   


Tried this method as well, still no luck


What I did to discover devices again:
   
   - Remove all devices + Rooms in the Alexa-App
   - Renumber all devices in the web interface
   - Restart the raspberry pi
   - Turn off alexa and wait a few seconds and turn it on again
   - Search for devices

**Comment by dcuste** [comment]
I logged some debug items and have attached as a docx file. It seems this has events of some sort almost continually. At 10-26-2020 07:17:22.127 I asked Alexa to turn on living room lights. That command should have found living room (number 110) at the top of the list and send and on and fon command to J6. Instead it found chandelier (number 107) and sent on and fon commands to J4. The chandelier light did come on.  
[habridge debug file.docx](https://github.com/bwssytems/ha-bridge/files/5439385/habridge.debug.file.docx)

**Comment by sanderlv** [comment]
WOW! I also stumbled upon this topic because I have the issue... worked for YEARS, now not anymore.
I deleted all devices in the alexa.amazon.com portal and discovered them again. It finds them but I cannot voice control them anymore... I can however control the devices via the habridge interface.
running 5.3.0

**Comment by amyth1884** [comment]
I am going through the same hair pulling experience, my setup is not able to discover at all any device, is there a way to reset, not sure if region matters I changed my region to India recently

**Comment by sanderlv** [comment]
Edit 6:
I "jsut" pressed in the morning disocver devices and they are found!
**BUT They are all double!?? - BUT They are all double!??**

Pressing discover devices again makes them triple... WTH is wrong!?

**Comment by dcuste** [comment]
My work around is to delete all the HA-BRIDGE devices from Alexa, do a hard reset, have Alexa do a new discovery, and then test each Alexa device and change the names of the ones that are labeled wrong. It is a very tedious process, but everything appears to be working now. 
I'm not going to test if I do another discovery if it will double up. I'm going to try and never change anything again. But, I would hink it would be pretty easy to use the app and delete the duplicates. Much easier than what I had to do.
Dave 
 

    On Monday, October 26, 2020, 11:48:50 PM PDT, sanderlv <notifications@github.com> wrote:  
 
 


Edit 6:
I "jsut" pressed in the morning disocver devices and they are found!
BUT They are all double!?? - BUT They are all double!??

Pressing discover devices again makes them triple... WTH is wrong!?

**Comment by sanderlv** [comment]
I don't know what happened overnights... but I can discover my devices again?/ Was some sort of Amazon hickup? Can it be that "discovery" is some sort of rate-limited by them?

**Comment by amyth1884** [comment]
Still not working for me

**Comment by dcuste** [comment]
I'm able to discover 13 devices. For some reason, I can't get it to discover more and I'm not willing to remove the ones I have because I to manually rename them. I did do an alexa app update. But it still won't discover more devices. 
I'm thinking of creating a second Alexa account and see if it works better.


 
 
  On Wed, Oct 28, 2020 at 3:13 AM, amyth1884<notifications@github.com> wrote:   


Still not working for me

**Comment by amyth1884** [comment]
I reset all my echo devices and used the option to  delete all alexa devices from my Amazon account and finally I was able to discover and use devices like before. I noticed on first boot post reset it discovered devices which I had added few days back and those were not discovered, seems like they were stuck in queue somewhere, not sure though but complete reset helped in my case.

**Comment by luciano968** [comment]
Is this working properly after the complete reset?

> I reset all my echo devices and used the option to delete all alexa devices from my Amazon account and finally I was able to discover and use devices like before. I noticed on first boot post reset it discovered devices which I had added few days back and those were not discovered, seems like they were stuck in queue somewhere, not sure though but complete reset helped in my case.

**Comment by amyth1884** [comment]
After readd haven't tried fideling much l, but yea devices are working fine

**Comment by amyth1884** [comment]
After deleting devices from [here](https://www.amazon.in/hz/mycd/myx#/home/alexaPrivacy/deviceHistory) https://www.amazon.in/hz/mycd/myx#/home/alexaPrivacy/deviceHistory, I was able to discover devices but with delays, patience needed, as highlighted somewhere in the thread it takes some time to clear cached devices, to be on safe side I did a 20 sec reboot for the Echo Plus.
