### ISSUE TITLE
Is there a method for determining "Initiator IP" from logs?

### ISSUE THREAD

**Issue by mattgyver83** [bwssytems/ha-bridge#125]
This is sort of a feature request/question, been doing a bit of research and I still think what I am trying to do is best targeted by getting info from HA-Bridge directly.  If you feel this is totally off topic for the project I won't be ashamed if you just close this out because this can be perceived as one of those "you dug that hole" scenarios.  Hopefully I explain this well and if nothing else maybe it gives you some ideas for future use cases of the bridge as well.  Sorry for the below wall of text.

I have a script that controls some firetv's via adb, of which I own 2.  I also have a script that parses the ha-bridge log, ill get to that in a second. Using OpenHAB+HA-Bridge I have a variety of devices setup and working and I have created a few of them which I will call "ambiguous" devices.  The intent of these devices are so you can go into a room and say "Turn on Screen Mirroring" and the ha-bridge sniffer script can tell you what device "Initiated" this request and then do a lookup on a sqlite table I have that contains a matrix so it can return its closest "neighbor" to that initiator's IP, IE: turn turn on Screen Mirroring on the Upstairs TV when talking to Echo upstairs, or on the Basement TV when talking to the FireTV Stick downstairs.  The sniffer is basically designed to hook into things to just report the Initiators IP and nothing else and really is just a shim because I could not find a to get this info from HA-bridge or OpenHAB itself and so to be clear these scripts are actually configured in OpenHAB's item definition and not via HA-bridge as to ease configuraiton.  The above is just an example, my use cases for this type of dynamic control go further than this with the bridge-sniffer script+sqlite lookup but in the end I need to be able to know what device asked the bridge to do anything in the first place.

So, to achieve where I currently am what I did was basically modify logback.xml to look like this.  I think this could be a useful feature in the UI in the future as well even if its not exposed inside of the UI (im just using logrotate to manage the log sizing but it looks like there is also a RollingFileAppender);

        <appender name="FILE" class="ch.qos.logback.core.FileAppender">
                <file>/var/log/ha-bridge/ha-bridge.log</file>
                <append>true</append>
                <encoder>
                        <pattern>%d [%thread] %-5level %logger - %msg%n</pattern>
                </encoder>
        </appender>

        <root level="info">
                <appender-ref ref="STDOUT" />
                <appender-ref ref="CYCLIC" />
                <appender-ref ref="FILE" />
        </root>

My adb script now has the option to receive its destination IP via my sniffer script instead of manually.  My sniffer script does a JSON query to ha-bridge and gets the ID for the bridge device name called then just greps that log file backwards to return the IP.  It then runs a sqlite query on a proximity_map table I made defining "neighbors", the neighbor is what is reported so it can be fed to other scripts/processes.  My best attempt to capture the initiator's IP inside of the logfile was the following line when logging is configured for DEBUG;

2016-06-04 16:46:23,871 [qtp32610876-21] DEBUG com.bwssystems.HABridge.hue.HueMulator - hue light requested: 88301378 for user: hm3JnxYjJAKVDx8OkGQZwk1UKTwslVGKn0or5N29 from 192.168.1.211

For some reason all of my Alexa enabled devices all report that they come from that specific IP which is actually the LAN IP of my Echo, my other Alexa devices carry different IPs however in this log its always reporting .211.  It made me wonder is this normal?  Is there someting in ha-bridge I am overlooking that can provide me with who requested this?  My only requirement is that whatever I achieve I do not want to be at a networking/router level so I can down the road unwind some of the requirements I already have and flex it to other use cases.  If you have any insight into this or maybe have a better way to approach this id be elated despite though I have come really far but want to thank you again for all your work on this project its been really helpful and works wonderfully.

**Comment by bwssytems** [comment]
Very cool idea and very much in the vein of intelligent HA. My first thought is, could you do this with multiple HA bridges that are used for different zones and then one for your global commands. The HA Bridge can talk to other HA bridges with the Hue devices enabled for another bridge. The idea is that you only let certain echo's or fire tv's discover certain HA Bridges.

**Comment by mattgyver83** [comment]
Thanks for the suggestion I will have to play around with that concept.  In a perfect world just knowing where that traffic is requested from tells me what I need to know and does not require any additional bridges though I can see how that could be beneficial in the future too, I really wish I understood why that log always shows that same IP but it may be me not completely understanding the multi-casting aspect of the Echo requests.  I may be overthinking your reply but are you saying that there is a method for me to get one bridge to communicate to another somehow like for example have one bridge process craft a URL to make another perform an action?  If there is I would definitely be interested in learning more about that process as it may open up some ideas as well.

**Comment by bwssytems** [comment]
Not sure I understand what you are saying about the same IP? Is that the IP of the echo?

For the last question, the bridges can talk to each other by utilizing the Hue passthru feature. Start up 2 separate bridges on different web ports and upnp response ports, then in the first bridge, put the ip and port of the second one into the Hue config in the bridge control page. You will now be able to create devices that pass thru to the second bridge from the first one and you could name them differently,

**Comment by mattgyver83** [comment]
Ohhhh okay that explains the passthru - I had seen it in the docs but since I wasn't actively attempting to use it I didn't pay a lot of attention to it so thanks for explaining.    I did some more digging last night and it looks like maybe my issue actually stems from my darn router.  It seems that after telling my FireTV's to "discover devices" they find no devices to discover unlike my Echo which finds all 14.  Looking at that network traffic when I tell a FireTV to turn on a device (which works) I see the request go out to amazon then come back and go tell the Echo to perform the action at the bridge which is wierd as crap.  Basically it is looking like the Echo is the only thing using the bridge and the FireTV's just work by default because of some Amazon Alexa/multicasting juju.  In about less than a month I'll have a dot arrive so at least by then I will know for sure if its just the FireTV's that have this issue.

In the interim I'll have to do some troubleshooting and see what could be causing it - seems there could be some UPNP features I may need to mess with etc.  The good news is this could explain why I don't see the initiating IP in the log, if this is actually the case then all of my script logic is right and yet again I have dd-wrt to blame and once I fix my router my scripts will work as expected.

Thanks for the tips, hopefully I get the damn thing to work!  Btw if you just so happen to put in the ability to log to a file or a "custom" api attribute we can set for things like this that would be awesome, at least in my case it makes my entire script go away as I can just poll everything from the bridge :)

Thanks again

**Comment by bwssytems** [comment]
I have heard that the Fire TV ca use your Echo, so that may be the way of things. Also, you can turn on trace upnp in the bridge control tab and see if you get a request from the Fire TV to check.

I'll look at what would make sense to put in the bridge.

**Comment by mattgyver83** [comment]
Yeah looking at the the network traffic its looking pretty apparent that this is the case and that the FireTV's just report to the Echo.  I actually found a comment from one reader of aftvnews who reported that they were informed by Amazon customer support that the smart home functionality will only work with cloud based services unless you own an Echo in which case it will use that to reach third party, specifically HUE - http://goo.gl/DR6Da0.  Network traffic seems to show that when you use Alexa and ask her to control SmartHome devices the request goes out to Alexa and then comes directly back to the echo, nothing goes directly back to the TV and as well when asking to discover devices she instantly states no devices were found.  I'll close this out, you have been more than helpful and hopefully one day this info somehow helps someone else as well.
