### ISSUE TITLE
HABridge hue ColorDecode 0 0 0

### ISSUE THREAD

**Issue by Nikelele** [bwssytems/ha-bridge#1253]
Hey,

i have my habridge set up on a raspberry pi connected to some LED Strips.
Scrips to start, stop and dim the LED's via Hyperion works just fine.

My Issue is when trying to set a color with ${color.rgbx} for a script, it always changes to black (off).
I had a look into the logs and something with the color decode seems to be wrong.

Tracestate: Calling color as requested. With Color Data mode: XY, data: [0.6982, 0.2995]
Color change with XY: 0.6982 0.2995 Resulting RGB Values: 0 0 0
Request <</home/pi/hyperion_color.sh 000000>>, not done: true

I doesn't matter which color i choose, it always comes to RGB Values 0 0 0.

I am using the Version 5.3.1RC2.

Maybe you can help me with this.
Keep up the great work!

Cheers

**Comment by bwssytems** [comment]
Still need work on the color translations

**Comment by Nikelele** [comment]
Hey, 

I was just wondering because it worked perfectly till last week where i reinstalled the system.

But thanks for your answer.
I'll be patient.

**Comment by bwssytems** [comment]
Were you using the RC2 last week as well?

**Comment by Nikelele** [comment]
yes i was

**Comment by bwssytems** [comment]
interesting. as not understanding what would change if the habridge version didn't change

**Comment by bwssytems** [comment]
Colors are fixed in RC4
