### ISSUE TITLE
Support for other device types, such as speaker?

### ISSUE THREAD

**Issue by taddat** [bwssytems/ha-bridge#1255]
Does ha-bridge support changing the device type of the emulated device, such as to a "speaker" device?  I ask because I understand that Alexa/Echo supports room awareness for the following devices: lights, AC, TV, temperature sensor and speaker.

I already have devices setup for each room named "bedroom music," "kitchen music," etc which make http calls to turn on and off the music in my whole home audio system in the appropriate rooms.  While I would prefer a way to filter based on the Alexa/Echo unit making the request to achieve more flexible room awareness, I understand that IP filtering still isn't working due to the round-robin approach that Amazon takes to processing voice requests.  Nonetheless, being able to say "turn on the speaker" or "turn off the speaker" or "set the speaker to volume XX" in a given room would be a step in the right direction.  Does ha-bridge support the speaker type?  If not, is there a plan to support it in the future?

**Comment by audiofreak9** [comment]
The HA-Bridge emulates the Phillips Hue Bridge API, this API does not include "speaker" so there is no way to add the various types.
