### ISSUE TITLE
Echo Dot/Alexa not finding any HA Bridge devices

### ISSUE THREAD

**Issue by jenssladek** [bwssytems/ha-bridge#1257]
Hello,

I've tried everything I could think of, but my HABridge devices are not recognized by Alexa.

What did I try:
Search via:
- Echo Dot Gen 3
- Amazon Alexa Webpage
- Android Alexa App

Server setup:
- always running on port 80
- running on a Windows 10
- running on a Raspberry Pi

Network Setup:
- original Hue Bridge existing
- tried with Hue Bridge switched of
- tried with all Hue devices deleted from Alexa

Other information:
- tried several HA Bridge version on several machines
- created 2 devices in HA Bridge 
- switched off the Echo Dot
- always tried the search at least 2 times
- played with UPNP send delay 250 or 1000

Logfile looks like this (.51 is the Echo Dot Gen 3 - .24 is the Raspberry Pi running HA Bridge):
`11-21-2020 12:23:22.765 	INFO 	Traceupnp: SSDP M-SEARCH packet from 192.168.178.91:50000 	com.bwssystems.HABridge.upnp.UpnpListener
11-21-2020 12:23:23.419 	INFO 	Traceupnp: send upnp discovery template 1 with response address: 192.168.178.24:80 to address: /192.168.178.91:50000 	com.bwssystems.HABridge.upnp.UpnpListener
11-21-2020 12:23:23.438 	INFO 	Traceupnp: request of description.xml from: 192.168.178.91:80 filled in with address: 192.168.178.24:80 	com.bwssystems.HABridge.upnp.UpnpSettingsResource
11-21-2020 12:23:23.454 	INFO 	Traceupnp: hue lights list requested by user: 2b17f520a367402a86ce964dd2f3eba0 from address: 192.168.178.91 	com.bwssystems.HABridge.hue.HueMulator
11-21-2020 12:23:23.545 	INFO 	Traceupnp: hue lights list requested by user: 2b17f520a367402a86ce964dd2f3eba0 from address: 192.168.178.91 	com.bwssystems.HABridge.hue.HueMulator
11-21-2020 12:23:24.071 	INFO 	Traceupnp: send upnp discovery template 2 with response address: 192.168.178.24:80 to address: /192.168.178.91:50000 	com.bwssystems.HABridge.upnp.UpnpListener
11-21-2020 12:23:24.723 	INFO 	Traceupnp: send upnp discovery template 3 with response address: 192.168.178.24:80 to address: /192.168.178.91:50000 	com.bwssystems.HABridge.upnp.UpnpListener
11-21-2020 12:23:24.725 	INFO 	Traceupnp: SSDP M-SEARCH packet from 192.168.178.91:50000 	com.bwssystems.HABridge.upnp.UpnpListener`

I guess I've already tried all the hints I've found in the internet - except using maybe an older Echo Dot generation.
Shouldn't we find any reply to the lights list request in the log?
Any other ideas what to try?
I really appreciate your help.
Thank you,
Jens

**Comment by sanderlv** [comment]
Did you look at:
https://github.com/bwssytems/ha-bridge/issues/1243

**Comment by jenssladek** [comment]
> Did you look at:
> #1243

Thanks for the hint. I will try the updated version this evening.

**Comment by jenssladek** [comment]
Great. It works like a charm now with 5.3.1 RC 2. New devices are detected at first try now.
Thank you, sanderlv, for the hint and most of all thank you, bwssystem, for this great piece of software.
I will close this issue now.
