### ISSUE TITLE
Start Harmony command from Ha-Bridge's api

### ISSUE THREAD

**Issue by osenbruggen** [bwssytems/ha-bridge#126]
I have seen in the documentation it is possible to get Harmony activities and Devices from the API. But is it also possible to start them? I'm running a linux machine with HA software and would like to be able to give HA-Brige over the api API commands to start Harmony activities or commands from that machine with curl. Is this possible?

**Comment by bwssytems** [comment]
Very much so. Go to http://www.developers.meethue.com/ and register to see the api that the bridge emulates. You can call most of the light and config portions of the api.

**Comment by osenbruggen** [comment]
Hi no I don't think you understand. I would like to use ha-bridge like your restfulHarmony.

**Comment by bwssytems** [comment]
ok, hint here. The HA-bridge has a rest api to do this, it's just the hue api....

PUT http://192.168.1.1:8080/api/username/lights/numberofdeviceforactivity/state with the body {"on":true}

The curl would be:
curl  -H 'Content-Type: application/json' -X PUT -d {\"on\":true,\"bri\":51} http://192.168.14.59/api/username/lights/164824388/state

where 1648224388 is the id for the device of the harmony activity in the bridge

**Comment by osenbruggen** [comment]
Ah so I need to generate a device or button first? I was hoping not to because of the 50 device limitation.

**Comment by bwssytems** [comment]
Yep, I was trying not to bloat the habridge with more code that you could get by running the restful-harmony app separately.

**Comment by osenbruggen** [comment]
OK I understand. Maybe I should run that one next to it then. Thanks for clearing this up :)

**Comment by bwssytems** [comment]
Yep, that would be preferred.

Thanks, closing this issue.
