### ISSUE TITLE
5.3.1RC3 original-ha-bridge-5.3.1RC3.jar only 900KB

### ISSUE THREAD

**Issue by BattloXX** [bwssytems/ha-bridge#1261]
Hi, the original-ha-bridge-5.3.1RC3.jar has only 900kb, when i download, it doent start up, RC2 had 10,2 MB is this a "Bug"?

**Comment by bwssytems** [comment]
Sorry, uploaded the wrong jar.

**Comment by bwssytems** [comment]
Fixed
