### ISSUE TITLE
No release since v5.3.0 2019

### ISSUE THREAD

**Issue by Jean-Mercier** [bwssytems/ha-bridge#1264]
Hello Thanks for all the work 

i see there is no release since v5.3.0 in 2019 
https://github.com/bwssytems/ha-bridge/releases/tag/v5.3.0
there is only release candidate

Could we hope a release with all the recent fix ? or something block this ?

I use docker for ha bridge https://github.com/linuxserver/docker-habridge/releases
but they don't build release candidate

Thanks

**Comment by bwssytems** [comment]
It will be coming soon as RC5 is the final testing candidate before regular release.

**Comment by bwssytems** [comment]
The new release is available as 5.4.0
