### ISSUE TITLE
ha-bridge with Google Home

### ISSUE THREAD

**Issue by Wox1** [bwssytems/ha-bridge#1265]
Hi there,

I read that Google Home has stopped working locally.
I ran Pi-hole and made a DNS entry in the host file. So that "auth.meethue.com" and account.meethue.com" is redirected to a local address. Unfortunately that doesn't work. Can anyone help me here whether this could even work?

Can anyone explain to me what the entry is for: "HomeAssistant Names and IP Addresses"

Thank you very much

**Comment by bwssytems** [comment]
Google Home will not work as commented in the readme and the FAQ. 

for home assistant review this: https://github.com/bwssytems/ha-bridge#home-assistant-names-and-ip-addresses
