### ISSUE TITLE
Synchronization of colors back to Ha-Bridge

### ISSUE THREAD

**Issue by dbochicchio** [bwssytems/ha-bridge#1269]
I developed a plug-in for Vera to synchronize status back to HA-Bridge
https://github.com/dbochicchio/Vera-HABridge

It's working well, even if it's new, but I'm wondering if it's possible to synchronize colors as well.

Thanks.

**Comment by bwssytems** [comment]
You can send color updates as well since the ha-bridge emulates the hue interface. You can send hue/sat or XY messages to the ha-bridge in the status update call.
