### ISSUE TITLE
door look discovered with wrong serviceId

### ISSUE THREAD

**Issue by wolfpackt99** [bwssytems/ha-bridge#127]
After manually poking around i was able to get the bridge to actually do the lock.

NEW:
data_request?id=action&output_format=xml&DeviceNum=56&serviceId=urn:micasaverde-com:serviceId:DoorLock1&action=SetTarget&newTargetValue=1

OLD:
data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:SwitchPower1&action=SetTarget&newTargetValue=1&DeviceNum=56

**Comment by rafale77** [comment]
Hmm didn't even notice this. I made a similar fix to another bridge on github, The Homekit one. Suggest you push your fix?

**Comment by bwssytems** [comment]
The ha bridge helper does not interrogate the type of device. IT is set to just build a switch http call.

**Comment by wolfpackt99** [comment]
This was VERA by they way.  I have been digging in the code. seems based on documentation on vera that the serviceId is important to the the call. The request for devices should have the serviceId in there.

http://wiki.micasaverde.com/index.php/Luup_Variables

**Comment by bwssytems** [comment]
That is correct, the Helper in the bridge for Vera is static and only has switch power service id. As I mentioned, the bridge does not look up the service id for the vera device and use it. Since there is a way to edit, you can change it as you did.

**Comment by bwssytems** [comment]
Closing as the bridge does not interrogate type for vera devices.
