### ISSUE TITLE
Link Button?

### ISSUE THREAD

**Issue by steviehs** [bwssytems/ha-bridge#1272]
I tried adding a new device today (have HA bridge running since years) and nothing was recognized. Still I see a lot of UPNP requests in the logs while updating devices (started from Alexa Web UI). Now, how to proceed? Updated to 5.4.0, no changes... There are 5 3.Gen Echos and 2 2.Gen Dots here... 
What I have not found: How do I activate a "Link" Button? I have not seen such option, though the Devices Tab shows me a "Manage Links" Button. I am rather frightened to delete all devices inside Alexa or renumber them in HA Bridge, as we are so used to control everything via voice ::-)

**Comment by audiofreak9** [comment]
@steviehs HA-Bridge by default is always in the state of "link button pressed.  So there is no need to actually press a button to make the devices discoverable.  To turn on the requirement to press the link button go to the Bridge Control page, and click the orange "Update Security Settings" button.  A popup menu will appear, you can toggle the "Use Link Button" option from False to True by checking the checkbox and clicking "Update".  A "Link" button will appear on the "Bridge Devices" page when the Use Link Button is checked True.  I never use the link button option.

Do one thing for me, go to the "Bridge Control" page and click the Test button to open your device JSON.  Find your new device and look for it's "uniqueid" and post the actual ID, it should be something along the lines of this: "00:11:22:33:44:55:66:6E".  I want to see if your device has a dash with two digits after or not.  The Alexa discovery recently changed and will not work with IDs that have the appended dash and two digits.  Let me know...

**Comment by steviehs** [comment]
>  Find your new device and look for it's "uniqueid" and post the actual ID, it should be something along the lines of this: "00:11:22:33:44:55:66:6E". I want to see if your device has a dash with two digits after or not.

In fact all my devices have unique ids in this format, e.g. 00:17:88:5E:D3:6E-00.
Is there something I can do to change this? My first idea would be to edit the backup :-)

**Comment by steviehs** [comment]
Uh, you were right, I just stopped habridge, edited the ID I wanted to detect from 00:17:88:5E:D3:6E-00 to 00:17:88:5E:D3:6E:00 and voilá! 
Now, I could perhaps try to find the point in the code, where the uniq ids are generated and change this to the above form, but may be it had a reason, so I should better leave this to the more enlightened people here?
Thanks a lot @audiofreak9 !

**Comment by Jean-Mercier** [comment]
Same for me #1270  id with - at the end how you change it ? 

Thanks

**Comment by steviehs** [comment]
Quite easy: make a backup first :-) stop habridge, edit device.db with a text editor and change the - in the uniqueid value to a : 
Then start habridge and discover...

**Comment by audiofreak9** [comment]
Linking to [thread #1243](https://github.com/bwssytems/ha-bridge/issues/1243#issuecomment-722917680) so users can get the whole uniqueid history.

Also @steviehs and @Jean-Mercier  to future proof your existing devices you may want to do the following [from this post](https://github.com/bwssytems/ha-bridge/issues/1243#issuecomment-723436638) to update all uniqueids for every device, in short it makes a copy of your device.db file, then removes all "dash,digit,digit" combinations.

```
# systemctl stop ha-bridge.service
# cp device.db device.copy
# sed -i 's/-[0-9][0-9]"/"/g' device.db
# systemctl start ha-bridge.service
```

**Comment by audiofreak9** [comment]
FYI...https://github.com/bwssytems/ha-bridge/issues/1270#issuecomment-749247749

**Comment by audiofreak9** [comment]
So I just found out on another thread https://github.com/bwssytems/ha-bridge/issues/1270#issuecomment-749815765 that changing the ID SEED number and renumbering your devices also fixes device discovery.  Very interesting, leads me to think the cache of id and uniqueid are tied together in device discovery and the return of deleted devices during discovery.

**Comment by npaisnel** [comment]
and yet today after two days of trying to get discovery working again ...and losing all devices, recovering from backup, deleting data directory habridge.config etc...I also tried the trick of editing the ID to remove the - and replace with :

It worked for some the first time I did it ..second time..creating new devices....it did not work...

**Comment by obzerving** [comment]
> Linking to [thread #1243](https://github.com/bwssytems/ha-bridge/issues/1243#issuecomment-722917680) so users can get the whole uniqueid history.
> 
> Also @steviehs and @Jean-Mercier to future proof your existing devices you may want to do the following [from this post](https://github.com/bwssytems/ha-bridge/issues/1243#issuecomment-723436638) to update all uniqueids for every device, in short it makes a copy of your device.db file, then removes all "dash,digit,digit" combinations.
> 
> ```
> # systemctl stop ha-bridge.service
> # cp device.db device.copy
> # sed -i 's/-[0-9][0-9]"/"/g' device.db
> # systemctl start ha-bridge.service
> ```

I followed this instruction except that I just replaced the dash with a colon and didn't remove the last octet. Discovery worked (thanks, audiofreak9), but I want to be clear that this resulted in an 8 octet uniqueid. I was expecting to see 9 octets per my configuration settings. I should also note that I also changed the seed and did a renumber, but neither of those actions worked prior to editing the device.db file.
