### ISSUE TITLE
Echo Discovery Issues

### ISSUE THREAD

**Issue by nihebe** [bwssytems/ha-bridge#1273]
Hi,

I'm unable to discover habridge with my Echos ("no devices found"). I updated and configured habridge freshly and it was never discovered before. I use link button method, but I also tried it with deactivated link button method. For discovery I unplugged another original Philips Hue Bridge in my network.
To start discovery I tried using the iOS App ("Hue V1 Bridge") and https://alexa.amazon.de/spa/index.html#appliances on a computer.

I uploaded a debug [syslog.txt](https://github.com/bwssytems/ha-bridge/files/5740018/syslog.txt) with trace upnp from the Rasperrby Pi running ha-bridge. I also use homebridge on the Pi with ports 8581 and 51148. The syslog was recorded while searching for new devices with the computer.
IPs of devices:
- habridge v5.4.0-java11 on a Raspberry Pi: 10.1.1.10
- Computer executing discovery on Alexa Website: 10.1.1.20
- iPhone running Alexa App: 10.1.1.184
- Amazon Echos (multiple models / generations): 10.1.1.80, 10.1.1.90, 10.1.1.122, 10.1.1.223, 10.1.1.231

Thanks a lot for having a look and Merry Christmas!

**Comment by audiofreak9** [comment]
Please see this thread https://github.com/bwssytems/ha-bridge/issues/1272 . Short of it is reseed the IDs or update the uniqueids.  Closing this issue as it is duplicate.
