### ISSUE TITLE
Alexa finding nothing except Alexa devices

### ISSUE THREAD

**Issue by gbCambridge** [bwssytems/ha-bridge#1279]
Somehow, out of the blue, with nothing changed, Alexa can no longer find any devices via ha-bridge. This was with 5.3.0. I upgraded to 5.4.0 and got exactly the same result.
In looking at the trace I found just one clue. It was this:

Jan 13 16:22:13 DomoHab java[549]: 2021-01-13 16:22:13,489 [qtp23762093-34] INFO  spark.http.matching.MatcherFilter - The requested route [/api//lights/237/state] has not been mapped in Spark for Accept: [application/json, text/plain, */*]

Can anyone convert this to English so that I can do something about it...or even better, give me an idea of the problem.

Thanks for the help

George

**Comment by bwssytems** [comment]
That message is an INFO message and not an ERROR. It just means the bridge got a request that it cannot parse.

**Comment by gbCambridge** [comment]
Oh...so just info. Well, since then, out of the blue, Alexa started to find my devices. The first problem, it generally, but not always, found two of each device, and the second problem is that none of them work..so again Alexa is not operative. I have deleted, reloaded, and tried most combinations...wasted a lot of time and still nothing works. All the devices can be operated via ha_bridge, directly from the screen, but the Alexa gateway seems to be failing. Anyone with a guaranteed fix for this problem??
Thanks to all who try.

**Comment by bwssytems** [comment]
You should use the thread #1277 as this has been discussed very much there. I'm closing this as a duplicate to that thread.
