### ISSUE TITLE
I need help to restore a friends home automation system. 

### ISSUE THREAD

**Issue by e-m-m-a** [bwssytems/ha-bridge#1284]
Hello,
My friend setup a whole, complex, home automation system with Intelliremote interfacing with Ha-Bridge. He died recently and after a power outage, the ha-bridge is not working - so lights don't work, heating doesn't come on on demand, stereo doesn't work - you used to be able to say alexa turn the lights on and it worked and now it doesnt plus there was a web based remote interface tat won't load. 

Can you help me. I am a mac/ linux girl and haven't used HA bridge before.  Ha-bridge is running on a headless HP microserver running something windows server ish. I think he VNC's into this but I don't know how and there is no obvious VNC software on his laptop. 

What I think happens is ha-bridge interfaces with inteliremote https://melloware.com/intelliremote/ and controls wifi lights. 

He said this"I tend to favour Tasmota flashed Sonoff which connect by wifi, but don't need a hub...  I run a Hue emulator on my server so I can address just about anything via Alexa, if I want to."

The logs are showing an error on ha-bridge restart :

Error calling out to HA gateway - see pics.

Your help would be very much appreciated as his wife is non techie and very fed up. it looks like this error but its just appeared after a reboot

https://github.com/bwssytems/ha-bridge/issues/782

![IMG-4975](https://user-images.githubusercontent.com/16956316/105896234-742f5600-600e-11eb-874c-b78415dcc3fe.JPG)
![IMG-4973](https://user-images.githubusercontent.com/16956316/105896250-77c2dd00-600e-11eb-8813-09a95d046139.JPG)

**Comment by audiofreak9** [comment]
My first thought is since the power outage the various device IP addresses have changed.  So the device running inteliremote with previous IP 192.168.157.132 has changed, this is probably why the inteliremote interface and inteliremote HA-Bridge items no longer work.  Can you access the router to search for the inteliremote device's IP, or find that IP on the device itself?

**Comment by e-m-m-a** [comment]
Thanks but both are running on the same HP Microserver and the IP of HP-Bridge has not changed (and I imagine its a fixed IP anyway)

**Comment by e-m-m-a** [comment]
Its seems to have fixed its self, with a manual restart of the server, which didn't work with a simple server reboot. Thanks,
