### ISSUE TITLE
5.4.0 did not find new devices and find old devices double

### ISSUE THREAD

**Issue by thorstensd** [bwssytems/ha-bridge#1286]
Hello,

5.4.0 did not find new devices - so I renumberd them and restarted the service and delete all the devices.
That was a mistake, because it still dont find new devices, but i find now all devices doube and none of them are working.

I did shutdown my pi and tested a rediscovery - alexa still shows all devices double. Normaly it should find nothing, because the pi was offline, there must be a cache or something.

Any suggestions how to fix this?

Best regards, Thorsten

**Comment by tvonderhaar** [comment]
I'm having the same problem. I have had mine setup for years. I fixed the port 80 problem with a proxy awhile back. I wanted to added a new device and Alexa could not find it. I upgraded to 5.4.0, deleted all me devices(big mistake), and asked for a check of new devices. No matter how I do it from an echo or from the Alexa app,  it  can't find any of my 59 devices. It can find the thermostat, my two ROKUS and one of my harmony hubs(even thought both seem to work.) I tried shutting down Apache2 and moving the HA-Bridge to port 80. No joy. Although I found for some reason Firefox won't bring up the bridge page when moved to port 80(thank God google chrome did work.) I turned on debug logging on the UPNP and UPNP listen and saw traffic between my echo's and the bridge. I never say my device names in the traffic but they weren't found by Alexa. I use the bridge every day! Please can anyone help.

**Comment by tvonderhaar** [comment]
Update!!! I found that changing the number seed of the devices on the bridge control tab to a number bigger than my last previous number, saving the bridge settings, renumbering the devices on bridge devices page with the renumber button at top of that page, deleting all devices with the Alexa app, and then performing a discovery from the Alexa app will then allow all my devices(even new ones) to be found. Be careful once a device number is used it can't be reused. Don't renumber with the same seed after Alex finds devices using the that seed  or you have to increase the seed above the last used device number and restart the procedure above all over.  I don't know how high the seed can be set and have this work around still work. I discovered this by wondering why there was a renumber button and googling its use. Some bug in original numbering scheme requires renumbering. This was purely emperically discovered, others with a better understanding of the API might better explain this behavior.
       Tom

**Comment by dbase25** [comment]
@tvonderhaar 
Thanks for the Info. With update my number from 100 to 200 under 
Bridge control -> ID Seed (start number...) -> 100 change to 200
alexa found all my devices again

And it works again

**Comment by thorstensd** [comment]
Hi, 
I did renumber already, with 200, before my first post.
But same here, since today everything is runing like it should. I think Amazon changed something.

Best regards 

Thorsten
