### ISSUE TITLE
Sonoff-Tasmota/Harmony

### ISSUE THREAD

**Issue by asselt** [bwssytems/ha-bridge#1287]
Guten Abend,

ich versuche verzweifelt seit Tagen meine Sonoff Steckdosen (geflasht mit Tasmota) in über eine erfolgreich angelegte HA-Bridge (bewusst ohne Echo/Alexa) anzulegen, um Sie anschließend über die Harmony einbinden/schalten zu können. Aber es will einfach nicht klappen, gefühlt habe ich schon alles probiert. Nur halt nicht das Richtige! Über den Browser funktioniert http://192.168.178.171/cm?&cmnd=Power1 on einwandfrei!
Egal was ich bei der Bridge im Device unter -> Http Verb und -> Content Type eingebe, ich bekomme beim TEST ON/OFF immer die Fehlermeldung:
Error on calling url to change device state: http://192.168.178.171/cm?&cmnd=Power1 on
On/Off Request failed with: [{"error":{"type":"6","address":"/lights/2","description":"Error on calling url to change device state","method_name":"/lights/2/state"}}]

Es würde mich sehr freuen wenn mir jemand helfen könnte. Danke, im Voraus.
![Bridge_Geär](https://user-images.githubusercontent.com/53236978/107994167-60a75780-6fdc-11eb-9819-5a176b5e0bd1.jpg)
![Bridge_Start](https://user-images.githubusercontent.com/53236978/107994172-63a24800-6fdc-11eb-824e-fcd9cc6a50e3.jpg)
![Sonoff_Einstellung](https://user-images.githubusercontent.com/53236978/107994179-67ce6580-6fdc-11eb-8a10-29a4a3b745ff.jpg)

**Comment by bwssytems** [comment]
So the first thing I see is there are spaces in the URL. URLs have to specifically type the space as %20. You also have content type to application/json but you are not sending any json payload. I would not set that parameter.

**Comment by asselt** [comment]
The problem is solved. It was the spaces. **Thank you for your help**. 
I have changed the content type to text/html. It works great!
