### ISSUE TITLE
Hue passthroiugh devices always sets color to purple

### ISSUE THREAD

**Issue by JJBottjen** [bwssytems/ha-bridge#129]
I am using HA Bridge to go between Harmony remote and Hue bridge (and Vera). Hue devices are added as pass through, and turn on/off as expected when tested...

Except... It always changes the bulb color to purple. No matter what color the bulbs are set to before testing on/off they go to purple.

Something I'm doing wrong? Or a limitation of the system?

**Comment by bwssytems** [comment]
It may be an issue OR the start state of 0 for the hue value is purple and you need to prime it by calling the api and setting it.

**Comment by bwssytems** [comment]
So this is interesting as the code just regurgitates the request body to the pass through device without changing it. Have you tried anything again with this?

**Comment by bwssytems** [comment]
Is this still an issue?

**Comment by authomation** [comment]
just installed a harmony hub.
harmony hub  ==> ha-bridge ==> hue hub
I am noticing the same behavior: turning on any bulb from harmony will launch it in full purple.
however turning it on from the ha-bridge web-gui retains its previous color it had before turn off.
starting a bulb from the harmony remote if it has been paired with the hue bridge (and not ha-bridge) the purple effect is not happening.


```
bulb color has been set to yellow in hue app and bulb turned off
bulb status: off
action: 'on' from ha-bridge web interface
log: 2016-08-20 10:14:16,957 [qtp2137569308-18] DEBUG com.bwssystems.HABridge.hue.HueMulator - hue state change requested: test from 0:0:0:0:0:0:0:1 body: {"on":true}
bulb status: yellow
action: 'off' from ha-bridge web interface
log: 2016-08-20 10:15:15,990 [qtp2137569308-14] DEBUG com.bwssystems.HABridge.hue.HueMulator - hue state change requested: test from 0:0:0:0:0:0:0:1 body: {"on":false}
bulb status: off
action: 'on' from harmony remote
2016-08-20 10:15:55,956 [qtp2137569308-13] DEBUG com.bwssystems.HABridge.hue.HueMulator - hue state change requested: 1e36caddcf3f48b69ea9d41786564e93 from 172.16.1.15 body: {"xy":[0,0],"on":true,"bri":0}
bulb status: yellow for a split second, then purple
```

I notice another thing on my harmony remote:
If I turn on a bulb the harmony remote knows the status of the bulb  and displays it as "on"
after a few seconds the harmony remote however displays the bulb as "off", even though it is still on. This behavior as well only happens when the harmony is connected to ha-bridge vs being connected straight to the hue-bridge.
I suspect that something might be broken with the harmony remote querying the status of the bulbs and that might also be the issue with the color?

**Comment by bwssytems** [comment]
Could you turn on DEBUG for com.bwssystems.HABridge.hue.HueMulator component. Changing this and then selecting the Update Log Levels button applies the new log settings. Please pos your log after running your scenario. Thanks

**Comment by marcfon** [comment]
I have the same setup (harmony hub > ha bridge > hue hub) and can confirm that I have the same issue as the hue lights turn on purple.

**Comment by marcfon** [comment]
@bwssytems here are the logs that indicate that there is a difference between how the HA Bridge web interface turns on the Hue lights and how the Harmony Hub mobile app does it. The big difference is that the web interface sends an `{"on":true}` while the mobile app sends `{"xy":[0,0],"on":true,"bri":246}` when pressing the On button. I guess everything would work as supposed if the mobile app also would just send the `{"on":true}` command...

**HA Bridge web interface**
```
2016-09-08 14:27:57,518 [qtp7100535-98] DEBUG com.bwssystems.HABridge.hue.HueMulator - hue state change requested: test from 192.168.1.9 body: {"on":true}
2016-09-08 14:27:57,523 [qtp7100535-98] DEBUG com.bwssystems.HABridge.hue.HueMulator - Making outbound call in doHttpRequest: PUT http://192.168.1.5/api/si2-XPiy3Q5X0SBNaLmZaAozNu1Vk0ynbS32WeZq/lights/3/state HTTP/1.1
2016-09-08 14:27:57,581 [qtp7100535-98] DEBUG com.bwssystems.HABridge.hue.HueMulator - PUT execute on URL responded: 200
```

**Harmony Hub android app**
```
2016-09-08 14:28:25,300 [qtp7100535-93] DEBUG com.bwssystems.HABridge.hue.HueMulator - hue state change requested: 57344036db8d4b6ba6243c2d6aad03ff from 192.168.1.9 body: {"xy":[0,0],"on":true,"bri":246}
2016-09-08 14:28:25,304 [qtp7100535-93] DEBUG com.bwssystems.HABridge.hue.HueMulator - Making outbound call in doHttpRequest: PUT http://192.168.1.5/api/si2-XPiy3Q5X0SBNaLmZaAozNu1Vk0ynbS32WeZq/lights/3/state HTTP/1.1
2016-09-08 14:28:25,358 [qtp7100535-93] DEBUG com.bwssystems.HABridge.hue.HueMulator - PUT execute on URL responded: 200
```

**Comment by bwssytems** [comment]
A question here then, Do you set the type for the hue lights to be the hue passthrough? That type is supposed to pass anything it receives straight to the hue hub.

**Comment by bwssytems** [comment]
Also, is this happening in version 3.1.0? There were some updates to try and help this.

**Comment by marcfon** [comment]
The type is set to passthrough and im on 3.1.0. But my guess is that the harmony app is adding the x,y parameter to the request and that screws things up. The x,y parameter is probably correct for the lux bulbs but not for the color lamps.

**Comment by marcfon** [comment]
When the hue lamps are added to the harmony app that are passed through ha bridge it somehow thinks every lamp is a lux on/off lamp. If it would recognize the lamp type correctly I think we wouldn't have this issue.

**Comment by marcfon** [comment]
When the hue lamps are added to the harmony app that are passed through ha bridge it somehow thinks every lamp is a lux on/off lamp. If it would recognize the lamp type correctly I think we wouldn't have this issue.

**Comment by mysteryan** [comment]
I actually run multiple instances (lux, ct and rgb) because I encountered similar issues of it responding only as lux lamps too.  It's a pretty easy fix.  Just edit DeviceResponse.java (ha-bridge/src/main/java/com/bwssystems/HABridge/api/hue/DeviceResponse.java).  At the bottom, just change the values for setType and setModelid.  I.e. If you want color bulbs, just change it to "LCT004" and and "Extended Color Light", for white tunable bulbs, it would be "LTW004" and "Color Temperature Light".

Perhaps a future enhancement could make this configured dynamicly on a per device basis rather than the whole bridge.

**Comment by marcfon** [comment]
Great catch @mysteryan! Making this user configurable via the webinterface would already help. But of course it would be even better if HA bridge would automatically detect what kind of hue light it is and return the correct one. I guess it should be able to get this info from the philips hue bridge fairly easily.

**Comment by bwssytems** [comment]
That is something I'll have to put in.

**Comment by bwssytems** [comment]
I have an updated jar to try: http://bwssystems.com/files/ha-bridge-3.1.0l.jar

**Comment by marcfon** [comment]
I can confirm that this is fixed. The lights turn on to the last set color. Also they are displayed as color lamps in the harmony app. However I also have a LUX lamp which should only have the brightness control interface but it too shows up as a color lamp in the harmony app. This is not a show stopper but could be something to look into.

**Comment by marcfon** [comment]
I've just updated to 4.1.0 and the behaviour as described before seems to be back. The lamps always turn on to a dim blue color instead of the color that was previously set. Also the lamps don't show up in the harmony app as color lamps but as on/of lamps.

**Comment by bwssytems** [comment]
Yep, I Broke this

**Comment by marcfon** [comment]
I can confirm that the lights turn on to the latest set color (v 4.1.2). Thanks!

The lights still show up as on/off lights in the Harmony mobile app. This is not a dealbreaker for me but it would be nice if the color lamps actually show up as color lamps.
