### ISSUE TITLE
Can't access UI in web browser

### ISSUE THREAD

**Issue by Tr4inman** [bwssytems/ha-bridge#1290]
I'm not sure if I did something wrong or what. I installed everything without issue, and then started/enabled the habridge. However, when I put my Pi 3's IP into Chrome it gave me an error that said Connection Refused.

**Comment by bwssytems** [comment]
Look at your log to see if the bridge started properly.

**Comment by Tr4inman** [comment]
Oh, thank you! I used sudo systemctl status habridge.service. It turns out my file was named habridge when it needed to be named ha-bridge, or something along those lines. Thanks for the help!
