### ISSUE TITLE
Unable to discover homeassistant's device？

### ISSUE THREAD

**Issue by hasspi88** [bwssytems/ha-bridge#1292]
![image](https://user-images.githubusercontent.com/77336160/110809809-333e8880-82c0-11eb-893d-0e6432ce7c57.png)
![image](https://user-images.githubusercontent.com/77336160/110809864-3cc7f080-82c0-11eb-8e30-3a8c49786291.png)
Unable to find homeassistant devices, only 4 devices are displayed

**Comment by bwssytems** [comment]
How did you configure homeassistant in the bridge control tab?

**Comment by hasspi88** [comment]
![image](https://user-images.githubusercontent.com/77336160/111071227-1e583400-8510-11eb-9549-eea912e51fd6.png)

**Comment by hasspi88** [comment]
![image](https://user-images.githubusercontent.com/77336160/111071265-48a9f180-8510-11eb-9d5f-dae310a5073c.png)

**Comment by hasspi88** [comment]
![image](https://user-images.githubusercontent.com/77336160/111095397-5004e580-8578-11eb-9402-1e4eb0243ab1.png)

**Comment by hasspi88** [comment]
> 您如何在网桥控制标签中配置homeassistant？

**Comment by hasspi88** [comment]
> 您如何在网桥控制标签中配置homeassistant？
I add homeassistant configuration by token or password. It can't display the device, only has a number 4

**Comment by hasspi88** [comment]
![image](https://user-images.githubusercontent.com/77336160/111173040-4c597900-85e1-11eb-9dce-a1a9fdbafef9.png)

**Comment by hasspi88** [comment]
![image](https://user-images.githubusercontent.com/77336160/111173307-8296f880-85e1-11eb-8152-5fbff9b0ae4f.png)
