### ISSUE TITLE
how to write "pretty print" JSON for the HA-Bridge .db files (device.db, group.db)

### ISSUE THREAD

**Issue by jayjupdhig** [bwssytems/ha-bridge#1299]
Because that is much more easy to debug...

Thank you for your feedbacks!! :-)

With kind regards,
Jan

**Comment by bwssytems** [comment]
http://jsonprettyprint.net/

**Comment by jayjupdhig** [comment]
Is that possible or not? Thanks in advance for your feedback.

If there are any questions, so please don't heisitate to ask me.

**Comment by bwssytems** [comment]
Just cut and paste it into the json pretty print on the web page listed above. There are tools you can download as well. There is no real need for the ha-bridge to provide that in itself.

**Comment by jayjupdhig** [comment]
Thank you very much for your feedback.

I meant the the habridge will create pretty-printed files... much more easy to debug.

Or can i create a "hook" that executes a shellscript with uses ´jq´ and ´sponge´ (e.g.) for format the habridge JSON config files?

**Comment by jayjupdhig** [comment]
https://github.com/bwssytems/ha-bridge/issues/1300

**Comment by jayjupdhig** [comment]
Is that not possible??

**Comment by jayjupdhig** [comment]
anyway...
