### ISSUE TITLE
Error connection refused in logs

### ISSUE THREAD

**Issue by ckhyatt** [bwssytems/ha-bridge#13]
First--thanks for the great work on this app! 

I have posted this issue on the thread in Vera but I am a new user so I am waiting for a moderator to approve my post. Apologies for the cross post.
 
I am seeing the same issues as xeinth--Error Calling out to HA Gateway, connection refused (to my VE)--multiple times. It then eventually connects. The UI correctly detects all Devices and Scenes and displays them. It is displaying Devices and Scenes in the UI even as the log shows repeated instances of Connection Refused. Devices generate URLs and test properly. I enabled UPNP on both my routers. 

Scenes do not generate URLs. If I manually add a scene (http://vera:3480/data_request?id=action&serviceId=urn:micasaverde-com:serviceId:HomeAutomationGateway1&action=RunScene&SceneNum=<scene#>) I either get a a popup with a 404 error or a popup with command ran successfully but the scene doesn't fire. 

The scenes run fine in Vera Ui 7. I have done everything I can think of including deleting all devices and adding them again. At present I have (11) zwave switches/outlets that test successfully and work through Echo. 

I am running this on an rpi 2, with Raspbian Jessie. I am running the most recent Vera firmware--1.7.1598 that was released last week. 

Thanks!

**Comment by bwssytems** [comment]
So, there is a bug in url generation that needs to be fixed. It will be coming soon.
 
Thanks
 
The Support Team
 
--------- Original Message --------- Subject: [ha-bridge] Error connection refused in logs (#13)

**Comment by ckhyatt** [comment]
Excellent--thanks! What about the Error Calling out to HA Gateway, connection refused?

**Comment by bwssytems** [comment]
What is your command line? The call is a direct calm to the vera you specify on the command line.
Thanks
On Dec 1, 2015 9:32 AM, ckhyatt <notifications@github.com> wrote:Excellent--thanks! What about the Error Calling out to HA Gateway, connection refused?

**Comment by ckhyatt** [comment]
This is the command line in the .sh:

ps -ef | grep "ha-bridge" | awk '{print $2}' | xargs kill
java -jar -Dupnp.device.db=/usr/local/habridge/devices.db
 /usr/local/habridge/ha-bridge-1.1.0.jar 2>&1 | tee /usr/local/habridge/habridge.log &

This is in the crontab:

@reboot java -jar java -jar -Dupnp.device.db=/usr/local/habridge/devices.db
 /usr/local/habridge/ha-bridge-1.1.0.jar 2>&1 | tee /usr/local/habridge/habridge.log &

Thanks!

**Comment by bwssytems** [comment]
Ahh yes, you need to supply the vera IP address. Add this -Dvera.address=<vera IP address> and you will be in business.
Please read the readme at HTTPS://github.com/bwssytems/ha-bridge as it will explain all the command line items and why you may need them.
The support team
On Dec 1, 2015 9:53 AM, ckhyatt <notifications@github.com> wrote:This is the command line in the .sh:

ps -ef | grep "ha-bridge" | awk '{print $2}' | xargs kill
java -jar -Dupnp.device.db=/usr/local/habridge/devices.db
 /usr/local/habridge/ha-bridge-1.1.0.jar 2>&1 | tee /usr/local/habridge/habridge.log &

This is in the crontab:

@reboot java -jar java -jar -Dupnp.device.db=/usr/local/habridge/devices.db
 /usr/local/habridge/ha-bridge-1.1.0.jar 2>&1 | tee /usr/local/habridge/habridge.log &

Thanks!

**Comment by ckhyatt** [comment]
I originally had the IP and it made no difference. The readme indicates the IP is not necessary as it uses the default IP of the host. Is the readme incorrect? To be clear, the bridge is running and I can control 11 devices through Echo.

Thanks!

**Comment by bwssytems** [comment]
That is the upnp.config.address. If you want the vera helpers, you will need to add it.
On Dec 1, 2015 10:21 AM, ckhyatt <notifications@github.com> wrote:I originally had the IP and it made no difference. The readme indicates the IP is not necessary as it uses the default IP of the host. Is the readme incorrect? To be clear, the bridge is running and I can control 11 devices through Echo.

Thanks!

**Comment by ckhyatt** [comment]
My apologies, I copied this incorrectly from my configuration doc. Here is how it is configured:

ps ­ef | grep "ha­bridge" | awk '{print $2}' | xargs kill
java ­jar ­Dvera.address=192.168.1.135 ­Dupnp.device.db=/usr/local/habridge/devices.db /usr/local/habridge/ha­bridge­1.1.0.jar 2>&1 | tee /usr/local/habridge/habridge.log &

**Comment by bwssytems** [comment]
Ahh, looking through my notes, and updates for the next release, I have changed how the bridge connects to the vera. I have run into that before as well.
 
Comming soon.
 
Thanks
 
--------- Original Message --------- Subject: Re: [ha-bridge] Error connection refused in logs (#13)

**Comment by ckhyatt** [comment]
Thanks! I just wanted to be sure I hadn't made a mistake.

Thanks again for all your work on this app. It is an excellent solution.

Regards,

Craig

**Comment by ckhyatt** [comment]
I confirmed my device IDs and Scene IDs are duplicates. I suspect this is the reason it doesn't work when I manually copy the scene URL into the UI. Looks like both issues will be fixed in the next release. 

Thanks again for all your hard work on this app.

Craig
