### ISSUE TITLE
timeout issue of multi command call

### ISSUE THREAD

**Issue by cykew** [bwssytems/ha-bridge#130]
When setup multi command call, amazon echo will wait for all commands executed before reply "OK". However most of the time it timeout before commands executed, therefore amazon echo will reply something like "I don't know what went wrong...." but actually commands is executed successful. 

How about use asynchronous execution for multi command call so that amazon echo can immediately get reply and answer "OK"?

**Comment by bwssytems** [comment]
Yep, I have that too. You can lower the "Button Press/Call Item Loop Sleep Interval (ms)" setting to 0 and that will loop immediately. That helps as well. I won't do the parallel run as the idea is to allow sequences in order such as button 6, button 0, button 5 to turn to that channel with the Harmony and it requires the sequence.

**Comment by cykew** [comment]
Ok. I will try zero interval but I believe if there is many commands in the loop, echo will still time out eventually. What I suggest is asynchronous execution. So far I am using php asynchronous execution, I found it still execute in sequence correctly, just that asynchronous execution it won't wait for reply before execute next command.

**Comment by bwssytems** [comment]
I'll consider adding it as an option

**Comment by cykew** [comment]
thank. Waiting for your good news

**Comment by bwssytems** [comment]
So, reviewing asynch capabilities to execute an external program in Java, it is not built in. I believe the solution is to put all of your commands into a script and then execute that script through the exec feature.
