### ISSUE TITLE
How to create a shutdown hook for HA-Bridge

### ISSUE THREAD

**Issue by jayjupdhig** [bwssytems/ha-bridge#1300]
Problem: I want to edit the .db files (device.db, group.db) also with my PHP web app... but after initializing a HA-Bridge restart via `http://x.x.x.x/system/control/reinit`, the file attributes of that .db files (device.db, group.db) are reverted a again with rights they are NOT writeable for the "wwwdata" user - the security context which apache2 services uses...

After init `http://x.x.x.x/system/control/reinit`, that 2 files are like that, if something was changed. (if group has other rights and nothing was changed, the permissions are sill the same as before):

![](https://i.ibb.co/9NgLTFC/1111.jpg)

**Comment by jayjupdhig** [comment]
It should be 0775 instead of 0644 and root is eligible as an user - with that settings, the apache2 service is able to edit them with php. But not with 0644.

So: How to solve that issue? Thanks.

If there are any questions, so please don't hesitate to ask me. Thx.


With kind regards,
Jan

**Comment by jayjupdhig** [comment]
Is that possible or not? Thanks in advance for your feedback.

If there are any questions, so please don't heisitate to ask me.

**Comment by jayjupdhig** [comment]
https://github.com/bwssytems/ha-bridge/issues/1299

**Comment by jayjupdhig** [comment]
Is that not possible??

**Comment by bwssytems** [comment]
The best thing is to start the habridge with another user (which will allow you to edit) which you can do straight from the service file or other script you use to start it. Google will be your friend on this issue.

**Comment by jayjupdhig** [comment]
ok will look about it...
