### ISSUE TITLE
Unable to send address bytes 

### ISSUE THREAD

**Issue by npaisnel** [bwssytems/ha-bridge#1302]
No idea where in the scheme of things this fits, but trying here first

Last night, went to Bed and Alexa ‘Everything Off ‘. Worked perfectly 

This morning... no response to my commands 

so i try via ‘Terminus’ app on the phone to get the Cmd line on my Pi that’s running HA Bridge/ Heyu

type in ‘heyu On A1’ or any command and just eventually get an ‘Unable to send address bytes’ response.

‘Heyu Monitor’   just sits there and shows no ‘traffic’ when the normal X-10 controller or TIP10RF device sends signals .

Nothing changed in the system, it was all exactly the same as it has been for many years.

I had a thought of what it could be, but thought I’d get confirmation here, I won’t plant seeds by saying what I thought.... anyone else seen this ?

**Comment by bwssytems** [comment]
I think this issue was accidentally posted here instead of the heyu git issues?

**Comment by npaisnel** [comment]
Actually not accidental 

I guessed there would be others here using heyu and since there is never much response over on the heyu group I hoped some one might have seen it on here.

**Comment by bwssytems** [comment]
Still, this is for habridge items. If there are no answers in a few days, I will close this as it is already posted in the heyu issues.

**Comment by npaisnel** [comment]
Yep, no problem 
No answers on there either
With the constant Alexa discovery issues, and now the CM11 hardware failure and inability to buy a new one, might be time for me to scrap the entire HA-Bridge / X-10 / heyu system and move in to the modern age with newer devices !   Keeping all this vintage kit running with hacks like heyu/ HA-Bridge is getting harder all the time !

**Comment by bwssytems** [comment]
FYI. I switched to OpenHAB to control the CM11 and also if you can get a CM15, mochad works great as well.

**Comment by npaisnel** [comment]
Think the issue is the CM11 has died, 
Can’t see any other reason for it to suddenly stop working.

I do have a CM15 but know that will not work in place of the CM11


Could you elaborate on how you set up the CM15 to drive the X-10 devices with Alexa... am using an RPi 3 B+

**Comment by bwssytems** [comment]
google "mochad" as that is the CM15 controller for linux

**Comment by npaisnel** [comment]
Thanks

found one article but it is a bit beyond my understanding .  I did the original build by following a tutorial ...Do this type that ..et ..

not yet found one for mochad
Looks like the Cm11 I need is actually a CM12U ..that seems to be the british one.

**Comment by npaisnel** [comment]
looks like it could well be a filesystem corruption issue on the Rasp Pi SD card.
just done a clown of the card and the problem persists. 
Yet writing an old img of the sd card from a while ago...it works correctly.

**Comment by npaisnel** [comment]
solved.

2gb SD card was full ..so tempted field that get written as commands are sent ..had no space to be written
Clone and expand FS  to 16GB card and all working again
