### ISSUE TITLE
Don't Discover Switch

### ISSUE THREAD

**Issue by lacojim** [bwssytems/ha-bridge#1308]
Is there a way to set up a device or devices that will intentionally not get discovered by Alexa? It would be nice to NOT have everything automatically discovered. Maybe there is a way already? Please, if there is not already, add this feature. Otherwise, how may I do it?

**Comment by bwssytems** [comment]
Yep, set the inactive flag to true for each device you do not want discovered.

**Comment by lacojim** [comment]
Perfect! Thank you.
