### ISSUE TITLE
Devices Disappear

### ISSUE THREAD

**Issue by lotusgary** [bwssytems/ha-bridge#1310]
Whenever I add new devices they disappear when I restart ha-bridge. They also are not being discovered by Alexa, but that could well be that they are not stored in the DB properly.

I've updated to the latest (4.5.1) release but no difference.

If I add the devices and then backup the DB - they are not there when I restore it.

Is there a way I can do a readable export of the DB to check it?

**Comment by npaisnel** [comment]
go to the habridge data folder and find the device.db file.

it is jsut a long text string.

take it in to something like Word or a text editor .

maybe just copy it and change the .db extension to txt and see if it will open automatically in Wordpad/ or pages/Word etc..

**Comment by bwssytems** [comment]
Look at your log if it is taking an error on saving the db as it is  most likely the path to the db file is not writable

**Comment by lotusgary** [comment]
Thank you. I can see the device.db file has not been updated since November, however the habridge.conf file has been updated today (in the same directory). No errors that I can see in the log

**Comment by npaisnel** [comment]
> Thank you. I can see the device.db file has not been updated since November, however the habridge.conf file has been updated today (in the same directory). No errors that I can see in the log

Have you found a third place where data is saved?
You can delete those two files, devices.db and habridge.config and habridge re creates them.  but it carries data over form the previous config..there must be another place where data is stored..

**Comment by lotusgary** [comment]
ah ok. It looks like there is a c:\data directory which it is using. I will amend my startup to cd to the correct directory first

**Comment by lotusgary** [comment]
that seems to have fixed it. Now I can't get any of my devices discovered by Alexa, but I think that is the same problem everyone has
