### ISSUE TITLE
Logic in commands sent

### ISSUE THREAD

**Issue by wookienow** [bwssytems/ha-bridge#132]
Hi,
You mention. Multiple Command Sending on your web page. (see below) the image shows logic.

Is there a way to build logic in what is sent.
i.e. For Dim commands
count = intensity.math
while (count>0)
{
{"device":"26936994","button":"VolumeUp"}
count= count -1
}

"Multiple command sending....
New! Any type of custom command can be built within one bridge device. Such as executing multiple UDP calls in once command or TCP calls or HTTP calls or a mixture of the three. Execution calls can be bundled together too."

**Comment by bwssytems** [comment]
Currently, there is no logic within those commands except for the value and
math items. I'm not planning on building a logic compiler yet. For now, you
could execute 3 or 4 volume up or down commands to give you that
functionality.

The support team

**Comment by wookienow** [comment]
As an alternative
Can I use a HTTP GET in the DIM and use the other harmony posts in the ON/OFF?

Thanks Brad.

**Comment by bwssytems** [comment]
Currently this isn't sup, but have been supported currently since the device type is for all commands.

**Comment by wookienow** [comment]
Thanks, Is there any logic in the Custom devices I could use?

**Comment by bwssytems** [comment]
So what I am referring to is utilizing a manually added device to string along calls to other devices that you have created. You can call the bridge itself with the example above as a device that the echo calls. i.e.

Create a Harmony Button Device - "ButtonA" = on/off
Create a Vera light Device - "LightB" = on/dim/off
Create a Harmony Activity - "TV" = on/off

Create a manually added device - "CustomC" - [{"item":"http://bridge_ipa_and_port/api/userxxx/lights/ButtonA/state"},{"item":"http://bridge_ipa_and_port/api/userxxx/lights/LightB/state"},{"item":"http://bridge_ipa_and_port/api/userxxx/lights/TV/state"}] using the multi command constructs with the content body {"on":true}

There is no interpretive logic within the statements.

**Comment by cjeri** [comment]
Been trying to use the above to work, but have failed miserably.

My steps:
1) Created a couple devices with Global Cache IR codes running on JSON. e.g. "ButtonA", "LightsB" - using the same names above for simplicity sake
2) Added a manual command called "TEST", and included the following under the "On URL":
{"item":"http://bridge_ipa_and_port/api/userxxx/lights/ButtonA/state"},{"item":"http://bridge_ipa_and_port/api/userxxx/lights/LightB/state"}]
3) Included the following HTTP VERB "PUT", Content Type: application/json:
{"on":true}
4) Saved the command and tested: no result

I know the individual buttons (i.e. ButtonA, LightB) are fine, as they do trigger an IR command. However, I may be doing something wrong with the multiple command structure. Any help / changes I need to make? What should I replace the "userxxx" with? 

Thanks,
CJ

**Comment by bwssytems** [comment]
Why not put the details of what ButtonA and LightsB are in a command and not do a self call? The self call will need a body element to work as that is what is missing.

**Comment by cjeri** [comment]
That was my first thought initially. Turns out that Global Cache iTach Flex API can only handle one IR code command at a time via JSON (went through their support team). Managed to get the self call working, although not ideal as I have taken up "space" for some other devices I may want to include in the future before I hit the 40 limit.

**Comment by bwssytems** [comment]
Sure you can, it is the same construct.

[{"item":"tcp://lots o stuff"},{"item":"tcp://lots more stuff"}]

and so on.

Each item call is separate.

**Comment by bwssytems** [comment]
So, I am going to add some simple parameters to the item command. I will add "count" and "delay" as those seem to be useful from all the requests I have seen.

**Comment by bwssytems** [comment]
The count and delay parameters will work on "item" types and "ButtonPress" types.
