### ISSUE TITLE
Linking HABridge in Harmong

### ISSUE THREAD

**Issue by rutj87** [bwssytems/ha-bridge#1327]
Hi Team,
Hoping someone can help!
I have previously had my Harmony Hub and HABridge working together however have changed my setup to Unraid and have deployed a new instance of HABridge.
Since this I can’t get Harmony to discover the emulated Phillips Hue. 
The standard container had the default port set to 8080. I have tried this set to 80 and still having no luck with Harmony discovering.
Any help or suggestion would be greatly appreciated.
Thanks

**Comment by Romain125** [comment]
Hi, 
May be related...or not I don't know...but I'm having trouble linking my HABridge on Raspberry with my Harmony.

Detection goes well on Harmony side but it prompts to push the physical button on the bridge.
As far as I read through the previous issues, the HABridge is always configured to be "Button pressed".

I tried with the "Link" button, didn't work.
The fun fact it that it works well on windows with the same version.
