### ISSUE TITLE
Cannot discover bridge

### ISSUE THREAD

**Issue by wwboynton** [bwssytems/ha-bridge#134]
Hello!

I've created an arbitrary device in my bridge, and am now attempting to discover the bridge with my Echo. However, it simply repeats that it cannot find any new devices on the network. The bridge is being hosted on an Ubuntu-based headless server within the same network. I've opened the firewall on the server entirely but I still cannot discover it from the echo. I can access the Web GUI on port 8080 without issue.

Thank you in advance for your assistance. Let me know if I can do anything additional to inform you.

**Comment by bwssytems** [comment]
Turn on trace upnp in the bridge config page and then post the log so we can see if it is finding it.

**Comment by wwboynton** [comment]
It turns out this was an issue with networking being run inside a docker container, which I stupidly neglected to mention. It works as intended when the jar is executed at the system level. 

You can close this and I'll determine if it's worth opening another issue regarding docker. My guess is there's a workaround on the docker side to enable generic UPnP discovery and you don't need to make any changes.

Thanks!
