### ISSUE TITLE
Update Docker image to 5.4.1.jar

### ISSUE THREAD

**Issue by BuxtonCalvin** [bwssytems/ha-bridge#1343]
Could you please update the docker image.  I'm having trouble finding devices and it's probably related to the 9 octet issue that was solved in the latest release.

**Comment by bwssytems** [comment]
Please post this to the docker support for the ha-bridge at https://github.com/aptalca/docker-ha-bridge

**Comment by BuxtonCalvin** [comment]
> Please post this to the docker support for the ha-bridge at https://github.com/aptalca/docker-ha-bridge

The container is remade automatically when you update the master branch of ha-bridge.  I think you have to merge your development devbranch5.4.1 into the master to trigger a new container getting made as that dev branch is one commit ahead of the master.

**Comment by bwssytems** [comment]
I'll get to that soon, otherwise it can be done manually.

**Comment by Rogero54** [comment]
Hello,
Do you have an ETA on when you can get to this?
Thanks

**Comment by bwssytems** [comment]
The release for 5.4.1 is published, it should work one
