### ISSUE TITLE
Q: How do I use color settings?

### ISSUE THREAD

**Issue by steviehs** [bwssytems/ha-bridge#1346]
Maybe it's because it's Monday, but I do not really understand for what I should use the color stuff in ha-bridge, if Alexa does not understand it (which is, what I understand from all documentation, that Alexa understand from direct hue detection only ON/OFF/DIM)?

So before I start fiddeling around with all that color settings: how do I use that then?

**Comment by bwssytems** [comment]
Have you filled in any color command in the device editor?

**Comment by steviehs** [comment]
No, although I could, but what could I then do with it? I use ha-bridge exclusively for voice control via Alexa...

**Comment by bwssytems** [comment]
I believe that has been fixed in Alexa. You can always test it by adding the color command and saying Alexa, set light to blue

**Comment by steviehs** [comment]
great! it just works! I was using the wiki here for understanding the concept and it is stating different, I will change it. Thanks for your great work!

**Comment by bwssytems** [comment]
Not sure on what Alexa completely supports, but the ha-bridge only offers the commands for lights with on/off/dim/color/temperature
