### ISSUE TITLE
Alexa Dot Gen. 2 suddenly has problems with HA-Bridge v5.4.1 RC1 - at least one smart home device does not work anymore

### ISSUE THREAD

**Issue by jayjupdhig** [bwssytems/ha-bridge#1351]
Hi there

**Today, we had a problem with our Alexa Dot Gen. 2 device and HA-Bridge v5.4.1 RC1:**

We realized that one (maybe more than one, but we didn't tested them all until now) device called "sued" ("south" in German, but without the umlaut ´ü´) was not working anymore.

Then, we looked that the device

a.) exists in HA-Bridge device list (http://192.168.178.5/#!/)

AND

b.) exists in the Amazon Alexa Web GUI (https://alexa.amazon.de/)

-> Then we saw that it exists on both places.

We had different situations:

1.) We said "echo, sued schalten" (switch "sued"), then the Alexa device made that "beep" tone. (Usually, it's a confimations that the process was successful) - but in the HA-Bridge console log there was NO new entry/line for that switch command

AND

2.) We said "echo, sued schalten" (switch "sued"), then the Alexa device told us that it can't find a device with that name

(And it suddenly seems to have a lil bit more problems to understand device names correctly in general...)

THEN, we added a new device called "süden" in the HA-Bridge and told "Alexa, seach for some new devices"... but there was no new device found. After that, wo also tried to do a device scan via https://alexa.amazon.de/ - same problem, no new device found, still 40 pcs...

After that, i deleted the Alexa "device cache" called [at least in german] "Smart Home Device History" - same result, not new devices foudn after smart home device search, still 40 pcs...

Maybe somebody saw a similar behavior on his/her system..?

Thank you very much for your feedbacks.

-> Maybe the Amazon Alexa Cloud infrastructure servers have a problem OR they changed something with their API again - so HA-Bridge v5.4.1 RC1 is not working 100% anymore OR both... but i don't really no what the problem is. 

Thank you very very much for your feedbacks.

With kind regards, Jan

**Comment by jayjupdhig** [comment]
Maybe similar to:

- https://github.com/bwssytems/ha-bridge/issues/1342
- https://github.com/bwssytems/ha-bridge/issues/1350

Hmmm...?

**Comment by jayjupdhig** [comment]
Nobody knows where the problem is...?

**Comment by jayjupdhig** [comment]
???

**Comment by steviehs** [comment]
Maybe to most extensive thread how to "reread" everything with Alexa and which Amazon Crap is caching what and how to delete it is:
#1216

**Comment by jayjupdhig** [comment]
With another Echo Device (Gen. 3 Dot at this time) and a complete fresh installation of our smarthome solution, the device scan process (on Alexa Web GUI) will not find any devices. (Excluding itself, so i see that Echo Gen. 3 Device in the smart home device list...)

**Comment by jayjupdhig** [comment]
???

**Comment by jayjupdhig** [comment]
Hello!?

**Comment by flynnsbit** [comment]
Turn on the octet 9 setting and renumber your devices.

https://github.com/bwssytems/ha-bridge/issues/1342#issuecomment-987554619

**Comment by jayjupdhig** [comment]
It's already turned on; after renumbering, all is fu**ed up completely... not just that one device was not found anymore... the existing devices all don't react anymore and when i start a smarthome device search, NOTHING will be found anymore...

why!?

**Comment by jayjupdhig** [comment]
Nobody knows what that issue is...?

**Comment by jayjupdhig** [comment]
Hello?!?

**Comment by jayjupdhig** [comment]
Problem still persists...

**Comment by jayjupdhig** [comment]
Problem solved by not using HA-Bridge anymore... :-)
