### ISSUE TITLE
Virtual Doorbell?

### ISSUE THREAD

**Issue by Supertas** [bwssytems/ha-bridge#1355]
Hi,
thx for the great project.
It is possible to create a local doorbell or to trigger for an alexa routine when the ha-bridge lamp is switched on/off?
I found only external solutions like the alexa skills like

url routine trigger
or
voice monkey

This skills are working very good with ha-bridge to trigger the routines

But i am searching for a complete locale solution, because is the homepage of the skills offline, then my switch is not working anymore.

**Comment by steviehs** [comment]
https://github.com/adn77/alexa-remote-control 

maybe that is, what you are looking for?

**Comment by Supertas** [comment]
Hi,

yes with this it works fine. Thx.

We can close this topic.
