### ISSUE TITLE
Habridge is detected but not added

### ISSUE THREAD

**Issue by TheUntouchable** [bwssytems/ha-bridge#1359]
Hi guys,

I just wanted to finally control my homematic devices with alexa (I have a hue bridge and 4 echo dot latest gen and a raspmatic docker container).

I am running the habridge in a docker container (container from linuxserver) with a macvlan in the same VLAN as the hue bridge and echos are running.

When I start the detection in the alexa app, you can see in the logs of the habridge, that the echos are talking to the bridge, but it doesn get added:

<html><body>

02-22-2022 08:59:48.507 | INFO | Traceupnp: hue api user create requested: {"devicetype": "Echo"} from address: 192.168.20.15 | com.bwssystems.HABridge.hue.HueMulator
-- | -- | -- | --
02-22-2022 08:59:48.508 | INFO | Traceupnp: hue api user create requested for device type: Echo#192.168.20.15 and username: ee72293aeaaa49a58eeb8a51f900496f | com.bwssystems.HABridge.hue.HueMulator
02-22-2022 08:59:48.517 | INFO | Traceupnp: hue lights list requested by user: ee72293aeaaa49a58eeb8a51f900496f from address: 192.168.20.15 | com.bwssystems.HABridge.hue.HueMulator
02-22-2022 08:59:50.300 | INFO | Traceupnp: hue api user create requested: {"devicetype": "Echo"} from address: 192.168.20.12 | com.bwssystems.HABridge.hue.HueMulator
02-22-2022 08:59:50.300 | INFO | Traceupnp: hue api user create requested for device type: Echo#192.168.20.12 and username: 0772cf6525814e81a5ac0bc3c3f26a23 | com.bwssystems.HABridge.hue.HueMulator
02-22-2022 08:59:50.311 | INFO | Traceupnp: hue lights list requested by user: 0772cf6525814e81a5ac0bc3c3f26a23 from address: 192.168.20.12 | com.bwssystems.HABridge.hue.HueMulator

</body>
</html>

I can even see all my echos under Links:

![grafik](https://user-images.githubusercontent.com/2162540/155092344-6a5b036b-3501-4a65-91a0-9bc6b1833b75.png)

There are allready 3 devices I created:

![grafik](https://user-images.githubusercontent.com/2162540/155091056-0ee9d56c-f66b-443b-b07e-a02370aaa053.png)

So what I am currently doing wrong? :(

**Comment by TheUntouchable** [comment]
I just installed it directly on a Raspberry 2 and I have the completely same behaviour. The dots and the habridge can talk with each other but the bridge is not added.

**Comment by TheUntouchable** [comment]
No one..?

**Comment by flynnsbit** [comment]
Turn on the octet 9 setting and renumber your devices.

https://github.com/bwssytems/ha-bridge/issues/1342#issuecomment-987554619

**Comment by TheUntouchable** [comment]
Okay, that was a quick on. Working now! Thanks a lot :)
@bwssystems Perhaps that should be added to the Trouble-Shooting page ;)
