### ISSUE TITLE
When you have device names that start with the same word, ha-bridge always selects the first device for dim commands

### ISSUE THREAD

**Issue by brandoncorry** [bwssytems/ha-bridge#136]
I have two devices "television" and "television sound". When I ask Alexa to "set my television sound to XX%", HA-Bridge always says it finds the device "television" and runs the command for that device instead of the "television sound" device. If I ask Alexa to turn on/off the "television sound" device, it works as expected - so this may be limited to the dim command logic.

**Comment by bwssytems** [comment]
Unfortunately, this is the processing in Amazon for the echo. There is no control over this from the bridge. The best thing is to pick a single keyword for these as to be different.

**Comment by brandoncorry** [comment]
I was afraid of that. Thanks for confirming. I'll file some feedback with Amazon for the time being. I've actually taken advantage of the feature you added to have on/off and dimURLs. I have combined them so that the on/off is for power, and the 'dim commands' are for setting the volume... so your awesome work to the rescue again. :)

**Comment by bwssytems** [comment]
Your solution seems more intuitive any way by using the dim for sound.

**Comment by kaznad** [comment]
Hi, brandoncorry could you share how to used the dim commands to set the volume? I would like to do this with my harmony hub as well. Thanks a lot.

**Comment by brandoncorry** [comment]
I have a Yamaha AVR receiver that enables control of the volume so I simply took the dim command with and used the available math functions within HABridge to map it (roughly) to the right value to pass to the Yamaha AVR API (I currently pass it through my openHAB setup as well so I can maintain state and react to volume changes, etc):

http://<serverIP>:<serverPort>/CMD?YamahaVolume=${intensity.math(1-(X/255)*-96)}
