### ISSUE TITLE
suddenly nothing works anymore ... spark.http.matching.MatcherFilter / spark.http.matching.GeneralError

### ISSUE THREAD

**Issue by veitk** [bwssytems/ha-bridge#1360]
Hi, 

i love ha-bridge! but suddenly it stopped working (just been away 5 days, maybe it got bored?)

The log looks like this:

02-25-2022 17:28:13.453 | INFO | The requested route [/api//lights/114/state] has not been mapped in Spark for Accept: [application/json, text/plain, */*] | spark.http.matching.MatcherFilter

if i push any buttons an error is added:

02-25-2022 17:28:18.213 | ERROR |   | spark.http.matching.GeneralError
02-25-2022 17:31:18.063 | ERROR |   | spark.http.matching.GeneralError
02-25-2022 17:33:06.491 | ERROR |   | spark.http.matching.GeneralError

do you have any hints how i can get it back up and running?

5.4.0 by the way.

**Comment by bwssytems** [comment]
Please install the latest release 5.4.1.

**Comment by veitalmaphil** [comment]
i updated and installed all raspberry updates (on raspian 10 - buster). 
did the deamon reload and even restarted.
every time i switch a device there is a new entry with the spark error in the log :(

**Comment by bwssytems** [comment]
Please click on the manage links button in the Bridge Devices tab and take a screen shot and post that. Somehow, it looks as if the userid in the rest api call is not being filled in. I assume you were doing the switch from the HA-Bridge web page.

**Comment by veitalmaphil** [comment]
![Bildschirmfoto 2022-03-13 um 15 17 24](https://user-images.githubusercontent.com/83720999/158064014-3a8b1f36-9b1e-4fb2-b1ea-13314861b49a.png)

this one?

**Comment by bwssytems** [comment]
Delete all the ones that say auto or test but not the Echos on this and then restart your habridge system and let me know if it works from the web page a gain.

**Comment by veitk** [comment]
removed links, press save (whitelist updated) after restart its the same. most of the links are back again. tried multiple times :(

**Comment by bwssytems** [comment]
Have you tried to clear your browser cache or try a different browser? It seems some of the javascript is not executing properly.

**Comment by veitk** [comment]
i did now. deleted links again, restarted ha-bridge.service, used a different browser.

**Comment by veitalmaphil** [comment]
03-16-2022 21:21:50.433 | INFO | == Spark has ignited ... | spark.embeddedserver.jetty.EmbeddedJettyServer
-- | -- | -- | --
03-16-2022 21:21:50.436 | INFO | >> Listening on 0.0.0.0:80 | spark.embeddedserver.jetty.EmbeddedJettyServer
03-16-2022 21:21:50.475 | INFO | Hue emulator service started.... | com.bwssystems.HABridge.hue.HueMulator
03-16-2022 21:21:50.705 | INFO | Description xml service started.... | com.bwssystems.HABridge.upnp.UpnpSettingsResource
03-16-2022 21:21:50.726 | INFO | UPNP Discovery Listener starting.... | com.bwssystems.HABridge.upnp.UpnpListener
03-16-2022 21:21:50.729 | INFO | Create and run mDNS service. | com.bwssystems.HABridge.upnp.UpnpListener
03-16-2022 21:21:50.854 | INFO | UPNP Discovery Listener running and ready.... | com.bwssystems.HABridge.upnp.UpnpListener
03-16-2022 21:22:44.537 | ERROR |   | spark.http.matching.GeneralError
03-16-2022 21:23:36.902 | ERROR |   | spark.http.matching.GeneralError

03-17-2022 18:31:47.436 | WARN | Could not find device: 115 for hue state change request: 57e6e4dbc0f0482bab5d118da9b48dbf from 192.168.0.38 body: {"on":false} | com.bwssystems.HABridge.hue.HueMulator


^^interesting if i try to switch something through alexa he can't find the device id .... and spark listening on 0.0.0.0:80? sounds weired. 

well i guess i will delete everything and set it up again

**Comment by bwssytems** [comment]
I would check if you have another bridge running that did not get shutdown.

**Comment by veitalmaphil** [comment]
i checked running services - there was only one entry. 

but i noticed that my config file was empty and set it up again, restartet the daemon and tried to switch a domoticz device from alexa:


pi@raspberrypi:/etc/systemd/system $ sudo nano ha-briddge.service
pi@raspberrypi:/etc/systemd/system $ sudo systemctl daemon-reload
pi@raspberrypi:/etc/systemd/system $ sudo systemctl start ha-bridge.service
pi@raspberrypi:/etc/systemd/system $ sudo systemctl enable ha-bridge.service
pi@raspberrypi:/etc/systemd/system $ tail -f /var/log/syslog
Mar 21 15:58:24 raspberrypi systemd[1]: Starting deCONZ: ZigBee gateway -- Initialisation...
Mar 21 15:58:24 raspberrypi systemd[1]: deconz-init.service: Succeeded.
Mar 21 15:58:24 raspberrypi deCONZ[1196]: qt.qpa.screen: QXcbConnection: Could not connect to display
Mar 21 15:58:24 raspberrypi deCONZ[1196]: Could not connect to any X display.
Mar 21 15:58:24 raspberrypi systemd[1]: Started deCONZ: ZigBee gateway -- Initialisation.
Mar 21 15:58:24 raspberrypi systemd[1]: deconz.service: Main process exited, code=exited, status=1/FAILURE
Mar 21 15:58:24 raspberrypi systemd[1]: deconz.service: Failed with result 'exit-code'.
Mar 21 15:58:24 raspberrypi systemd[1]: Starting deCONZ: ZigBee gateway -- Initialisation...
Mar 21 15:58:24 raspberrypi systemd[1]: deconz-init.service: Succeeded.
Mar 21 15:58:24 raspberrypi systemd[1]: Started deCONZ: ZigBee gateway -- Initialisation.
Mar 21 15:58:43 raspberrypi java[839]: 2022-03-21 15:58:43,241 [qtp5039649-18] ERROR spark.http.matching.GeneralError -
Mar 21 15:58:43 raspberrypi java[839]: **java.lang.NullPointerException: null**   <<<<<<---- ############
Mar 21 15:58:43 raspberrypi java[839]: #011**at com.bwssystems.HABridge.plugins.domoticz.DomoticzHome.findHandlerByAddress(DomoticzHome.java:178)**
Mar 21 15:58:43 raspberrypi java[839]: #011at com.bwssystems.HABridge.plugins.domoticz.DomoticzHome.deviceHandler(DomoticzHome.java:101)
Mar 21 15:58:43 raspberrypi java[839]: #011at com.bwssystems.HABridge.hue.HueMulator.callUrl(HueMulator.java:1692)
Mar 21 15:58:43 raspberrypi java[839]: #011at com.bwssystems.HABridge.hue.HueMulator.changeState(HueMulator.java:1301)
Mar 21 15:58:43 raspberrypi java[839]: #011at com.bwssystems.HABridge.hue.HueMulator.lambda$setupServer$39(HueMulator.java:456)
Mar 21 15:58:43 raspberrypi java[839]: #011at spark.RouteImpl$1.handle(RouteImpl.java:72)
Mar 21 15:58:43 raspberrypi java[839]: #011at spark.http.matching.Routes.execute(Routes.java:61)
Mar 21 15:58:43 raspberrypi java[839]: #011at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
Mar 21 15:58:43 raspberrypi java[839]: #011at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
Mar 21 15:58:43 raspberrypi java[839]: #011at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
Mar 21 15:58:43 raspberrypi java[839]: #011at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
Mar 21 15:58:43 raspberrypi java[839]: #011at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
Mar 21 15:58:43 raspberrypi java[839]: #011at org.eclipse.jetty.server.Server.handle(Server.java:530)
Mar 21 15:58:43 raspberrypi java[839]: #011at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
Mar 21 15:58:43 raspberrypi java[839]: #011at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
Mar 21 15:58:43 raspberrypi java[839]: #011at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
Mar 21 15:58:43 raspberrypi java[839]: #011at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
Mar 21 15:58:43 raspberrypi java[839]: #011at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
Mar 21 15:58:43 raspberrypi java[839]: #011at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
Mar 21 15:58:43 raspberrypi java[839]: #011at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
Mar 21 15:58:43 raspberrypi java[839]: #011at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
Mar 21 15:58:43 raspberrypi java[839]: #011at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
Mar 21 15:58:43 raspberrypi java[839]: #011at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
Mar 21 15:58:43 raspberrypi java[839]: #011at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
Mar 21 15:58:43 raspberrypi java[839]: #011at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by bwssytems** [comment]
Well, looks like the setup for Domoticz is not working. you would need to turn on debugging for 	com.bwssystems.HABridge.plugins.domoticz

**Comment by veitk** [comment]
so i finally looked into this problem and solved it. the domoticz plugin logs didn't show anything at all.
problem were:
1. my domoticz plugin setting in ha-bridge disappeared somehow
2. domoticz setup for user without password was also wrong, it did work probably because domo didn't care before

thx for your help - finally everything runs again
