### ISSUE TITLE
Unable to remove hue bridge proxy

### ISSUE THREAD

**Issue by kaznad** [bwssytems/ha-bridge#137]
Hi,

I tried adding a original Hue Bridge to the HABridge. Now I want to remove it, but am not able to remove it. When I click on the cross, it goes away, but I cannot click on the save button. Is there a way to manually remove the Hue Bridge?

Thanks.

**Comment by bwssytems** [comment]
Yep, that is something that needs attention. The workaround is to change another value, such as the port and then set it back.

**Comment by kaznad** [comment]
Thank you. I had removed the data folder and re-setup the bridge.

**Comment by bwssytems** [comment]
This is being solved in code as well. Re-opening for close on code commit.
