### ISSUE TITLE
Discovery doesn't work if you add too many devices

### ISSUE THREAD

**Issue by signal15** [bwssytems/ha-bridge#138]
I think I found the cause.  See here:
http://forum.micasaverde.com/index.php/topic,38327.msg286826.html#msg286826

This doesn't explain why the Echo seems to arbitrarily request the /groups/0 URL, but if that was implemented in ha-bridge and returned nothing, it would probably solve it.

**Comment by bwssytems** [comment]
Cool! great work! In the latest version I am working on I have been adding the extra calls that return empty constructs.

**Comment by bwssytems** [comment]
try this version to see if that works http://www.bwssystems.com/files/ha-bridge-2.0.7-hal-h.jar

**Comment by signal15** [comment]
I won't be able to test until Thursday evening as I'm traveling with a full
work schedule. If I have time before that, I will try to VPN in.

**Comment by signal15** [comment]
Just tested.  It doesn't work.  Here's the HTTP stream.  The ha-bridge is
returning an error.  I'm guessing because you implemented /groups, but not
something like /groups/0.

GET /api/h632JhAtwDezSwGk3VKEeFn4snXZUjro9OoEvdur/groups/0 HTTP/1.1

Host: 10.129.1.4:8080

Accept: */*


HTTP/1.1 200 OK

Date: Fri, 15 Jul 2016 04:35:17 GMT

Content-Type: text/html;charset=utf-8

Transfer-Encoding: chunked

Server: Jetty(9.3.z-SNAPSHOT)


7F

[{"error":{"type":"3", "address":
"/api/h632JhAtwDezSwGk3VKEeFn4snXZUjro9OoEvdur/groups/0","description":
"Object not found"}}]

0


GET /api/h632JhAtwDezSwGk3VKEeFn4snXZUjro9OoEvdur/groups/0 HTTP/1.1

Host: 10.129.1.4:8080

Accept: */*


HTTP/1.1 200 OK

Date: Fri, 15 Jul 2016 04:35:17 GMT

Content-Type: text/html;charset=utf-8

Transfer-Encoding: chunked

Server: Jetty(9.3.z-SNAPSHOT)


7F

[{"error":{"type":"3", "address":
"/api/h632JhAtwDezSwGk3VKEeFn4snXZUjro9OoEvdur/groups/0","description":
"Object not found"}}]

0


POST /api HTTP/1.1

Host: 10.129.1.4:8080

Accept: */*

Content-Length: 22

Content-Type: application/x-www-form-urlencoded


{"devicetype": "Echo"}HTTP/1.1 200 OK

Date: Fri, 15 Jul 2016 04:35:17 GMT

Content-Type: application/json; charset=utf-8

Transfer-Encoding: chunked

Server: Jetty(9.3.z-SNAPSHOT)


3D

[{"success":{"username":"3e975079139a417b933fc0835581ea4f"}}]

0


GET /api/3e975079139a417b933fc0835581ea4f/groups/0 HTTP/1.1

Host: 10.129.1.4:8080

Accept: */*


HTTP/1.1 200 OK

Date: Fri, 15 Jul 2016 04:35:17 GMT

Content-Type: text/html;charset=utf-8

Transfer-Encoding: chunked

Server: Jetty(9.3.z-SNAPSHOT)


77

[{"error":{"type":"3", "address":
"/api/3e975079139a417b933fc0835581ea4f/groups/0","description": "Object not
found"}}]

0


POST /api HTTP/1.1

Host: 10.129.1.4:8080

Accept: */*

Content-Length: 22

Content-Type: application/x-www-form-urlencoded


{"devicetype": "Echo"}HTTP/1.1 200 OK

Date: Fri, 15 Jul 2016 04:35:17 GMT

Content-Type: application/json; charset=utf-8

Transfer-Encoding: chunked

Server: Jetty(9.3.z-SNAPSHOT)


3D

[{"success":{"username":"52d290a812474b5a817fd8c4c36265ce"}}]

0


GET /api/52d290a812474b5a817fd8c4c36265ce/groups/0 HTTP/1.1

Host: 10.129.1.4:8080

Accept: */*


HTTP/1.1 200 OK

Date: Fri, 15 Jul 2016 04:35:18 GMT

Content-Type: text/html;charset=utf-8

Transfer-Encoding: chunked

Server: Jetty(9.3.z-SNAPSHOT)


77

[{"error":{"type":"3", "address":
"/api/52d290a812474b5a817fd8c4c36265ce/groups/0","description": "Object not
found"}}]

0




On Tue, Jul 12, 2016 at 8:32 AM, BWS Systems <notifications@github.com>
wrote:

> try this version to see if that works
> http://www.bwssystems.com/files/ha-bridge-2.0.7-hal-h.jar
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bwssytems/ha-bridge/issues/138#issuecomment-232047941>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMlDm7oHqfxNjoQaGxeLe925JgahuwICks5qU5dbgaJpZM4JJ3DW>
> .
>



-- 
--
jay austad  |  612.423.1433  |  austad@signal15.com

**Comment by bwssytems** [comment]
Yep, that is what is coded to do

**Comment by bwssytems** [comment]
Alrighty, try this one to see if that works http://www.bwssystems.com/files/ha-bridge-2.0.7-hal-k.jar

**Comment by signal15** [comment]
It appears to work fine now.  However, the Echo says "Discovery is complete, I found 2 devices".  The 2 it's referring to are my thermostats.  But, it actually found all of my devices (62 total).  I've attached the HTTP stream.

[successful-discovery.pdf](https://github.com/bwssytems/ha-bridge/files/366759/successful-discovery.pdf)

**Comment by bwssytems** [comment]
That is awesome! I had not even thought that this function would be used. Many persons will now be very happy!

**Comment by audiofreak9** [comment]
Great work @bwssytems, and a big thanks to @signal15 for taking the time to test.
