### ISSUE TITLE
Device not found.

### ISSUE THREAD

**Issue by AHA430** [bwssytems/ha-bridge#1406]
Hi, 
I've been using Ha-Bridge for a very long time and since reinstalling my VM my devices are no longer visibly by my Echo. 
I'm using version 5.4.1 and nothing has changed on my installation. 
Does Ha-Bridge work for you?

**Comment by fzmemon** [comment]
I am facing the same issue. I can even see the M-SEARCH Pakets coming in from the Echo device and a UPNP response going out from habridge but  still Alexa is not able to find the lamps
