### ISSUE TITLE
Alexa to report sensor status 

### ISSUE THREAD

**Issue by Mahindergola** [bwssytems/ha-bridge#143]
Is there anyway Alexa can report back VERA sensor status..

example : 
Alexa - What is my Thermostat temperature ?
Alexa - Check my Front Door status ?

**Comment by bwssytems** [comment]
No and Yes. The ha-bridge cannot do this as it just emulates a Philips HUE bridge. You can do this if you write your own Alexa Skill using their architecture through AWS Lambda.

**Comment by bwssytems** [comment]
Closing as this has been answered.
