### ISSUE TITLE
If .jar is ran in DOS window, bridge no longer works...

### ISSUE THREAD

**Issue by smarty125** [bwssytems/ha-bridge#144]
Overview: Win 7 32, Java Version 8.101 (latest)
 
I start the bridge by running a ".bat" (contents below):
cd\
cd ha-bridge
java -jar ha-bridge-3.0.0.jar

This leaves a command prompt screen open on my desktop (I minimize the window).

For whatever reason, Alexa can no longer discover my 29 devices when the bridge is started in this manner.

If I start the bridge by just opening/double clicking the .jar file, everything including discovery then works just fine (and I also have no command window open on the desktop).

For home security purposes, my automation system runs or closes the bridge based upon my home alarm system status.  It does this via sarching for the command window handle that the .jar was executed with.  If I execute the .jar OUTSIDE of a .bat file, I am not sure how I could accurately stop/start the bridge (how could I identify and control the correct java process)?

**Comment by bwssytems** [comment]
Just a thought. You may need to run the .bat file as admin. I am not a windows person per se, but some ports could be restricted as a security measure when running .bat files.

**Comment by dale3h** [comment]
You may also want to check out my [launcher batch script](https://github.com/dale3h/amazon-echo-bridge-launcher), as it will allow you to launch silently.

Note: It did work for me on Windows 7 x64 without elevated privileges.

**Comment by smarty125** [comment]
I am running the .bat file as an admin already...so that is not it.
..............
More info that I have determined....

Something seems to have changed on my system (I cleared the java cache...so that is not it), because when I revert back to bridge version 2.0.7, things still "mis-behave" as they do for bridge version 3.0.0.

Again... the only way I can get the bridge (either version now) to perform and respond is to double click directly on the .jar file (<=in this manner, I can trigger and also discover all my bridge defined devices...works perfectly as expected)

When I run either version of the  .jar file via the .bat file above, I DO see the bridge via web browser on port  8080 as expected (and all the bridge defined devices), but Alexa can not seem to trigger (or discover) them.

**Comment by bwssytems** [comment]
I am at a loss for this. This is a windows issue and not a ha-bridge issue.

**Comment by smarty125** [comment]
The info in this link seems to explain what I am seeing "spot on".
http://stackoverflow.com/questions/17603961/double-click-vs-java-jar-myjar-jar

I will place the executable .jar file into different java sub-directories and try to see if this makes any difference.  Something is "relative" path dependent when using java on Win 7.

**Comment by smarty125** [comment]
Well, I now have it working...here is what I found (again, I am using Win 7 32 bit):

I have to launch the .jar file via a .bat file that looks like this:

cd\
cd ha-bridge
javaw.exe -jar ha-bridge-3.0.0.jar

Note 1 - before executing the .jar, I MUST get into the directory where the .jar file is located (paths seem relative to the launching location). 

Note 2 -I MUST use "javaw.exe", as "java.exe" DOES NOT work ( with "java", I do see the bridge via web browser on port 8080 as expected, but no devices...the path to the config and .db seem screwed up.  When I use "javaw.exe", all works as expected.

Note 3 - my .jar file is located in C:\HA-Bridge.  My config and .db files are in C:\HA-Bridge\data (as normal).

**Comment by bwssytems** [comment]
So, are you good?

**Comment by smarty125** [comment]
Yep - all is working, but if we don't know what changed...I do wonder how long it will keep working...
