### ISSUE TITLE
http post "device xxx is not responding...."

### ISSUE THREAD

**Issue by TooUnCool** [bwssytems/ha-bridge#147]
Hi,

Firstly, very many thanks for this software, it is a great piece of work and incredibly useful. 

I have seen this question asked but haven't seen a clear reason why the above error occurs after successful command execution. My commands, sent to a Crestron processor to control lighting and audio in a room, work perfectly, but Alexa then informs me that the device that just worked perfectly, isn't responding. Is there something I need to program to send back to the Bridge, or am I simply being an idiot and missing something obvious. 

I am running my bridge on a MacMini. Any advice anyone is able to share would be very much appreciated...

Marc

**Comment by bwssytems** [comment]
Yes, I have that too when I use the multi command feature. It seems the echo expects the responses to be immediate and if it takes too long > 150ms it complains it didn't work when it actually did.

**Comment by TooUnCool** [comment]
Nothing that can be done? Whilst after using HA-Bridge I wouldn't go anywhere near IFTTT Maker again, the few times I tried said hack, it didn't have this problem. I can get feedback to the Echo from the Crestron processor fairly easily if it helps?

**Comment by audiofreak9** [comment]
@bwssytems, just a thought...could you create a ha-bridge device that only calls a second ha-bridge device that does all the multi command work?  So when you ask Alexa to control the first device it would respond without delay, since it is only calling the second device.

**Comment by bwssytems** [comment]
The refactor I would have to do is thread off the call when received and reply success immediately, even if it didn't succeed in the end.

**Comment by TooUnCool** [comment]
No negative response on failure sounds better to me than a negative response on success, so this has my vote, but clearly there are a lot more users than just me.....

**Comment by bwssytems** [comment]
So again, the responses the ha-bridge is sending are successes, it is in the timing of when the echo receives them that it says it is not responding, 

Could you post the commands for the devices.

**Comment by TooUnCool** [comment]
It's a super-simple POST of plain text "pause" or "play" to a TCP server running on the Crestron controller. I parse the incoming http command to find the text and fire commands on there based on a match....totally inelegant but works well.

I changed to using TCP from the HA-Bridge and it works fine, "Success" response.

**Comment by bwssytems** [comment]
Ahh, multiple hops through other programs. Glad it is resolved.

**Comment by avalokitasvara** [comment]
I *have* to delay my command for 30 seconds (it’s controlling a roomba under the kitchen, so it has to wait for its “garage” to open before it fires - long story).
Is there some way to return success to Alexa immediately, regardless of the *actual* success?

**Comment by avalokitasvara** [comment]
Ok so I worked around it by creating a script called triggerdelay.sh that opens lxterminal -e and runs the command including the delay. This enables me to call this script and have it finish the reply to alexa before the actual command is executed :)

**Comment by bwssytems** [comment]
@avalokitasvara Yep, that is the only way to have alexa not complain. Also, if you do not care if Alexa complains, you can just leave it as the command does execute properly.
