### ISSUE TITLE
HDMI CEC

### ISSUE THREAD

**Issue by winebob** [bwssytems/ha-bridge#15]
Enhancement request:
HDMI CEC support.  I have this working now to change channels on Dirtectv receivers (using SHEF) but would love to be able to turn on/off using the cec-utils library.  Thanks for your great work.

**Comment by bwssytems** [comment]
This looks interesting to implement, but currently there is a way to bridge to a CEC Web interface. Setup this system, https://robbiet480.github.io/cec-web/#introduction, and then call it's rest API with the ha-bridge.

**Comment by winebob** [comment]
That'll work.  Thanks

**Comment by bwssytems** [comment]
I also found a Java based version: https://github.com/DDRBoxman/WebCEC

**Comment by bwssytems** [comment]
I will look into how to incorporate the Java based version, but it requires Java JNI interfaces. Packaging for different platforms will be interesting.....

**Comment by bwssytems** [comment]
After some review, building this with JNI for different platforms will not be very user friendly and a huge workload to support. Trying to stay in the java world so it works everywhere.
