### ISSUE TITLE
Setting television (sound) percentages on 3.0

### ISSUE THREAD

**Issue by Noirad** [bwssytems/ha-bridge#152]
Lately I've been having trouble with version 3.0 allowing Alexa to consistently, and properly  preform the "Turn receiver volume to xx%, or on" 

I've tried the code "`[{"device":"36348370","button":"VolumeDown"}]` in the "Dim" and "Power On" fields, but I Alexa keeps returning errors. I've tried using the a few of the scripts offered in '"

but I'm not sure how `http://ip address:port/data_request?id=action&output_format=json&DeviceNum="XX"&serviceId=urn:upnp-org:serviceId:RenderingControl1&action=SetVolume&DesiredVolume=${intensity.math(X/5)}` translates in to the code that I enter [here ](https://drive.google.com/open?id=0B76FmSgsTcs2UW5QWDJJSGpjd2s) that matches this `([{"device":"36348370","button":"VolumeDown"}])`.

Please any advice would be greatly appreciated, I just want to be able to say "Alexa, turn Receiver Volume to XX%" 

Thank you so much!

**Comment by audiofreak9** [comment]
I too have a configured device that includes "volume", and I have experienced the same thing.  I think the Echo is be beginning to reserve words that would correspond to control of a Harmony Hub (work on direct control of the Harmony Hub by the Echo as was recently announced).  So I've changed my to "sound" instead.

**Comment by Noirad** [comment]
@audiofreak9 Have you been abel to get a proper string working at all? if so what does your string resemble?

**Comment by audiofreak9** [comment]
I am using a Harmony Hub, so my command raises the volume by 2 each time through a "Harmony Button" Map Type in the ha-bridge.

**Comment by Noirad** [comment]
@audiofreak9 what does your button mapping look like, this [https://drive.google.com/open?id=0B76FmSgsTcs2cTdMa1BPOTVKa1U](url) is an example of what I've been using.

I'm trying to get closer to this [https://drive.google.com/open?id=0B76FmSgsTcs2c19SQW1fT1BYenc](url) but I'm a little confused on what it should look like.

Have you been having trouble when asking Alexa to raise Tv sound or Tv volume and it defaulting to increasing or decreasing the volume of the Echo it's self? Thanks for any help!

**Comment by audiofreak9** [comment]
My Harmony Button, created using the Harmony Devices page.  This button raises or lowers my theater volume by 2.

**Name:** sound
**Target:** Harmony Hub
**Device Type:** Button
**Map Type:** Harmony Button
**On URL:** [{"device":"32829111","button":"VolumeUp"},{"device":"32829111","button":"VolumeUp"}]
**Dim URL:** (NOT CONFIGURED)
**Off URL:** [{"device":"32829111","button":"VolumeDown"},{"device":"32829111","button":"VolumeDown"}]

I originally named this device "volume", and yes I began to have trouble with the Echo raising or decreasing its own volume level.  I can make my "sound" device work by saying, "Alexa, turn on/off sound."  If you really want to use the dim, try saying, "Alexa, set the volume light to (desired number)."  I know it's weird to include "light", but it will work.  Remember the Echo thinks it's communicating with a Philips Hue Hub, which mainly controls lighting.

**Comment by bwssytems** [comment]
Is this still an issue?
