### ISSUE TITLE
Send JSON message over TCP?

### ISSUE THREAD

**Issue by farhanito** [bwssytems/ha-bridge#153]
Is it possible to send TCP messages in JSON format?
For example:

tcp://192.168.31.102:55443/{"id":1,"method":"toggle","params":[]}

Thanks

**Comment by bwssytems** [comment]
Sure, that will work just fine. See examples in the readme here https://github.com/bwssytems/ha-bridge#multiple-call-construct

**Comment by bwssytems** [comment]
Did you get this to work?

**Comment by farhanito** [comment]
Hi,

Yes it does work. Apparently i need to escape character like this..

tcp://192.168.31.101:55443/{\"id\":1,\"method\":\"toggle\",\"params\":[]}\r\n

Thanks

**Comment by bwssytems** [comment]
That is correct. Closing
