### ISSUE TITLE
Pi3 systemd not starting

### ISSUE THREAD

**Issue by dv8ed** [bwssytems/ha-bridge#155]
Anyone know why my systemd file won't start? 
The .sh file starts and creates .db file fine just systemd I get error below. 
===
[Unit]
Description=HA Bridge
Wants=network.target
After=network.target

[Service]
Type=simple
User=root
ExecStart=/usr/bin/java -jar -Dconfig.file=/home/pi/habridge/data/habridge.config /home/pi/habridge/ha-bridge-3.0.0.jar

[Install]
WantedBy=multi-user.target
===

ha-bridge.service - HA Bridge
   Loaded: loaded (/etc/systemd/system/ha-bridge.service; enabled)
   Active: failed (Result: exit-code) since Tue 2016-08-23 19:06:57 PDT; 3s ago
  Process: 25149 ExecStart=/usr/bin/java -jar -Dconfig.file=/home/pi/habridge/data/habridge.config /home/pi/habridge/ha-bridge-3.0.0.jar (code=exited, status=1/FAILURE)
 Main PID: 25149 (code=exited, status=1/FAILURE)

Aug 23 19:06:56 raspberrypi systemd[1]: Started HA Bridge.
Aug 23 19:06:57 raspberrypi java[25149]: 2016-08-23 19:06:57,439 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v3.0.0) starting....
Aug 23 19:06:57 raspberrypi java[25149]: 2016-08-23 19:06:57,462 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: /home/pi/habridge/data/habridge.config
Aug 23 19:06:57 raspberrypi java[25149]: 2016-08-23 19:06:57,478 [main] WARN  com.bwssystems.HABridge.BridgeSettings - Error reading the file: /home/pi/habridge/data/habridge.config - Does not exist or is not readable. continuing...
Aug 23 19:06:57 raspberrypi java[25149]: Exception in thread "main" java.lang.NullPointerException
Aug 23 19:06:57 raspberrypi java[25149]: at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:108)
Aug 23 19:06:57 raspberrypi java[25149]: at com.bwssystems.HABridge.HABridge.main(HABridge.java:54)
Aug 23 19:06:57 raspberrypi systemd[1]: ha-bridge.service: main process exited, code=exited, status=1/FAILURE
Aug 23 19:06:57 raspberrypi systemd[1]: Unit ha-bridge.service entered failed state.

**Comment by bwssytems** [comment]
Well that is not supposed to happen. Labeled as a bug. In the meantime, create that files as an empty file before you start.

**Comment by dv8ed** [comment]
correct if config file is there systemd/service starts but even though there is a /data/device.db it doesn't read from it log says not there or not readable. I tried adding/deleting buttons it doesn't do anything to .db file in /data folder. seems like it's writing to virtual environment somewhere? systemd/service method is writing to .db file somewhere just not in /data folder. I want to use a backup .db file but it doesn't read. habridge.sh reads config file and /data/device.db file okay.

**Comment by bwssytems** [comment]
When you start from systemd it is a root process. So it uses the /root directory. Once you can change and save your config in the gui, it should be pointing to where you want it.

**Comment by dv8ed** [comment]
so that's where it's been writing I switched over to root went to data folder every backup .db was there. it writes config to pi and root but .db only to root. not sure if it's something I'm doing wrong or if it's a bug. at least i know where .db file is at now. thanks for all your help really great software!
