### ISSUE TITLE
3.0.0 not storing extended values (2.0.7 does)

### ISSUE THREAD

**Issue by mysteryan** [bwssytems/ha-bridge#157]
On 2.0.7 (with modified DeviceResponse), extended bulb properties get stored such as ct values.  On 3.0.0, even when these values are changed, they still always return 0.  

_I.e if I curl PUT {"bri":100,"ct":200} to the device, the device response would still be {"state":{"on":true,"bri":100,"hue":0,"sat":0,"effect":"none","ct":0,"alert":"none","reachable":true}

On 2.0.7, it would properly reflect changes and return: {"state":{"on":true,"bri":100,"hue":0,"sat":0,"effect":"none","ct":200,"alert":"none","reachable":true}_

Even though these values aren't officially utilized, they are useful for bridging bulbs of different protocols into one instance.  I.e, when device changes state, I use a script that executes and pulls the values from the device response and incorporates it into a request to a foreign API.  I use a secondary instance of HA-Bridge to bridge Osram Lightify color temperature bulbs, but I'm sure it can be implemented to bridge with other protocols like LIFX, Wemo, TCP, Z-Wave or BLE type bulbs.  I can imagine it can be used to add an extra dimension of control to one device too.  Like a TV with state and bri mapped to power and volume and having ct or sat values translated to channel or input selection on one device. 

Without the values of extended properties saving, you can only bridge state and bri properties over.

**Comment by bwssytems** [comment]
Yes, I updated the way the state handling and interrogation were done from the two releases. Originally I treated the states received as states that were valid, that is not always the case. So the logic was changed just to set the on/off and bri values as those were what the bridge could do, except if it bridges to another hue system. Then it is an issue.
