### ISSUE TITLE
Device with only dimming command not responding?

### ISSUE THREAD

**Issue by farhanito** [bwssytems/ha-bridge#16]
Currently running v1.1.0

When i set a device with only dimming command, 
e.g  onURL = http://host:port/CMD?TV_VOLUME=${intensity.percent}
Alexa will say "Sorry, the device XXX is not responding, please check its network connection and power supply."
But it works if combined with switch command.
e.g onURL = http://host:port/CMD?TV=On&TV_Volume=${intensity.percent}

Is this normal?

**Comment by rafale77** [comment]
Just a guess as I am also working on emulating the Lux to a sonos volume. On a light when you say turn on a device, it sets the intensity percent to 100%. Your host (not sure what it is you are trying to control) is probably not going to like it. It is much more practical to have an on function separate from the volume...

**Comment by audiofreak9** [comment]
Does the volume change even though you get the, "Sorry, the device XXX is not responding, please check its network connection and power supply."?  If your volume is changing, then an HTTP 200 OK reply is not being received by the Echo.  The Echo requires an HTTP 200 OK response in reply to the command it gives, otherwise it'll give the "Sorry, the device..." statement.

**Comment by farhanito** [comment]
The device i want to control is an XBMC, bind to OpenHab.
Volume changing works fine using OpenHab UI. 
Weird thing is, sending GET request to ha-bridge using web browser, http://ha-bridge:port/CMD?TV_Volume=60, works as well... But not through Alexa.
With that response from alexa, the volume doesn't change.

I'll recheck my setup..

**Comment by farhanito** [comment]
Well, scratch that. I'm an idiot. 

I didn't put "http://" in front of OnURL, that's why

**Comment by audiofreak9** [comment]
At least you solved it!

**Comment by bwssytems** [comment]
issue resolved....
