### ISSUE TITLE
Harmony Hub Sleeps?

### ISSUE THREAD

**Issue by stas1000** [bwssytems/ha-bridge#162]
My bridge works well with my vera and harmony hub but if i leave it over night and ask alexa to turn on the tv the next day, she will give me the ok response but nothing will happen..... my vera activities continue to work but i have to re-initialize the bridge or mess with the harmony to get it to work again with the harmony.

has anybody had this issue or know any reason/work around for this?

Cheers

**Comment by bwssytems** [comment]
I have not seen this happen. Could you let us know what versions of the harmony hub software and which model? Thanks

**Comment by stas1000** [comment]
the hub software is 4.11.6 and it is on a harmony ultimate hub. Although it doesn't seem to be happening as much anymore

**Comment by bwssytems** [comment]
So I have not seen or heard anything on the web about the hub sleeping. Could you have an issue with your network connections?

**Comment by stas1000** [comment]
No it is not a network issue. I think i am narrowing it down though, when it does not work i am am teller her "turn on tv" ill get an 'ok' back with nothing happen. When this happens I have been telling alexa to 'turn off tv' instead of turn on and then I will be able to turn on again.



________________________________

**Comment by bwssytems** [comment]
Ahh, it is priming the state. The ha bridge does not know the state when it first comes up. Best to handle this as you just found.

**Comment by stas1000** [comment]
ohh no worries. Thanks at least i know this is normal now. Is it because of the time between using the bridge or because maybe the tv was turned off by the tv timer instead of the harmony remote last?


________________________________

**Comment by bwssytems** [comment]
So, you have something that is turning the tv off besides the hub itself? a timer? If that is the case, the harmony hub thinks the tv is still on and needs to reset it's state off. Nothing to do with the bridge.

**Comment by stas1000** [comment]
Yes sometimes i set the tv timer to turn off the tv. I know have another issue with the hub though where the last 2 days the hub stays on but is losing its ip address. so the bridge wont won't. This is an issue with the hub though obviously


________________________________

**Comment by bwssytems** [comment]
Thanks, it looks like this issue is solved for the bridge.

If your hub is reconnecting to the network all the time, then you have a wireless issue. Also, you should be able to set the ip address to the same on given to the hub every time. That will help also.
