### ISSUE TITLE
Total Connect interface

### ISSUE THREAD

**Issue by dougdalton** [bwssytems/ha-bridge#163]
Is it possible to convert this to an Ha-bridge interface? The one think I am not sure how to capture is the session variable:

https://raw.githubusercontent.com/bdwilson/SmartThings-TotalConnect-Device/master/SmartThings-TotalConnect-Device.groovy

**Comment by bwssytems** [comment]
Would need to investigate

**Comment by bwssytems** [comment]
Interesting. Simple API and I am seeing a lot of rest interfaces done this way. I'll add a generic impl to capture the token and then it will be able to be used within a custom call by keyword variable.

**Comment by bwssytems** [comment]
So, are you still interested in this to be added? With the concerns about security, this would leave your alarm system open to disabling it view the ha-bridge if it was hacked into.
