### ISSUE TITLE
Is it possible to disable UPNP?

### ISSUE THREAD

**Issue by attzonko** [bwssytems/ha-bridge#164]
Hi, is it possible to use this bridge if UPNP is disabled on the local network? I grepped through the source but did not find the "--upnp.disable" configuration option. 

Thanks

**Comment by bwssytems** [comment]
Sure, the ha-bridge will work. If your router filters out upnp messages, just discovery won't work.

**Comment by tcicatelli** [comment]
So, if the "Test On" and "Test Off" are working for all devices, and the bridge can control the HAC, how can you load devices into the Echo without UPNP?  I put the Echo and the Bridge on the same LAN segment, but devices are not discoverable.  Shouldn't they be able to see each other without the router if they're plugged into the same switch?

**Comment by bwssytems** [comment]
So, what is disabled for upnp? Most routers have a disable upnp that are for whether the router itself will respond to upnp messages for configuration purposes. Did you specifically turn of multicast being allowed on your network?

**Comment by bwssytems** [comment]
Is this still an issue?

**Comment by tcicatelli** [comment]
I'm not sure what was going on. All of a sudden, the Alexa learned everything without me even initiating a discovery. Thanks for following up.






On Tue, Sep 20, 2016 at 9:46 AM -0400, "BWS Systems" <notifications@github.com> wrote:












Is this still an issue?

**Comment by bwssytems** [comment]
Great!
