### ISSUE TITLE
question: Content Body for DIM?

### ISSUE THREAD

**Issue by jswim788** [bwssytems/ha-bridge#166]
Newbie question: why isn't there a content body for "dim"?  I need to use POST, and I need to send a different body for each case: on, dim, and off.  But it seems that dim and on share the content body?  Is that due to a limitation as to how the Hue bridge behaves?  Any workarounds?  Or maybe I misunderstand something.

Also, there's a button to test the DIM, but I didn't see a way to set the intensity value for it.  Is there a way?  If not, what value is it trying to send for intensity (percentage)?

thanks!

**Comment by bwssytems** [comment]
Unfortunately, that is a leftover that I did not change. Currently when the dim url is used the ha-bridge checks the state to see if ti was last on or off and then uses those content bodies accordingly. I'll need to update this to have a dim body.
