### ISSUE TITLE
Clicking on tabs in UI results in error

### ISSUE THREAD

**Issue by ckhyatt** [bwssytems/ha-bridge#17]
Clicking on any tab in UI (Configuration, Vera Devices, etc.) results in: Get Harmony Activities Error: undefined. I do not have a Harmony Hub nor do I have one defined in the command line.

Thanks!

**Comment by ckhyatt** [comment]
Sorry, correction--any tab except Configuration. All other tabs including Manual Add.

**Comment by ckhyatt** [comment]
I don't know if this is related but Scenes still don't generate a URL. I was able to add them manually and have Scenes function so that's good :).

Thanks!

**Comment by ckhyatt** [comment]
Here's an interesting new development. I just rebooted the rpi and the Harmony tabs are now missing. Is is not supposed to display the tabs unless you have a Harmon Hub configured in the command line?

**Comment by ckhyatt** [comment]
Even stranger. Now the UI is generating URLs properly. The only thing I did was clear the browser cache in Chromium on the rpi.

**Comment by ckhyatt** [comment]
Scenes generate properly through the UI and work through Echo--Awesome! The only question I have is about the Harmony Hub tabs. Are those supposed to be suppressed if you don't have a Harmony Hub configured in the command line? I only ask because I am getting a Harmon Hub for Christmas :)

Thanks again for this terrific app!

**Comment by audiofreak9** [comment]
Yes, the tabs will be suppressed if you do not declare a Harmony IP.  From the README, "...Supply -Dharmony.address=X.Y.Z.A on the command line to provide it. If a Harmony Hub is not used, do not set it..."  I have also found that if you declare "-Dharmony.address=1.1.1.1" that the Harmony Tabs will be suppressed.

**Comment by bwssytems** [comment]
please clear your cache on your browser as the javascript and pages are cached and the new load is very different. thanks

**Comment by ckhyatt** [comment]
I did that yesterday and everything appears to be working great. Thanks again!

**Comment by bwssytems** [comment]
issue resolved through browser cache clear
