### ISSUE TITLE
Instructions are still incorrect?

### ISSUE THREAD

**Issue by tinker3433** [bwssytems/ha-bridge#171]
RE #167 
I believe the instructions are still incorrect...

pi@raspberrypi:~/habridge $ wget https://github.com/bwssytems/ha-bridge/releases/download/v2.0.6/ha-bridge-3.1.0.jar

should be:
pi@raspberrypi:~/habridge $ wget https://github.com/bwssytems/ha-bridge/releases/download/v3.1.0/ha-bridge-3.1.0.jar

Also it was changed on the Master branch but not the Post3.1Fixes branch

Thanks

**Comment by bwssytems** [comment]
done, the new branch will get it soon after a merge.

Thanks
