### ISSUE TITLE
Amazon Echo cannot detect custom devices

### ISSUE THREAD

**Issue by javenlim** [bwssytems/ha-bridge#175]
I have Fibaro HC2 and successfully create HA Bridge with some devices.  Using HA bridge, I can turn on/off devices but I got stuck at Echo Discovering devices.  Echo simply cannot see the devices that I had added.  HC2 is running on cable and Echo is running on wireless.  HC2 can see alot of uPNP traffic in my home network but do not see anything coming from Echo.

1) When Echo discover devices, does it use uPNP protocol?
2) Does the discovery comes from Echo inside LAN or from Internet AWS cloud or something?  I have Sophos firewall at my gateway and had disabled everything from my Notebook including firewall and AV.
3) How can I get Echo see the devices I manually added?

I had been stuck in this for weeks.  Hopefully can have some expert here to advise.  Thank you.

Regards,
Javen

**Comment by javenlim** [comment]
Windows and Mac version not working well for me.  Issue resolved after switching to Linux HA Bridge

**Comment by psurma** [comment]
I'm in the same position, Echo doesn't discover any of my devices listed in "Bridge Devices".  I can manually click on the buttons to control them from ha-bridge.

What did you do to fix? (I am already on Linux)

**Comment by bwssytems** [comment]
@Pete Please post your ip address of your bridge and then your configuration of what you are using for the upnp ip address. Also, post your ha-bridge version. Thanks
