### ISSUE TITLE
Other types of 

### ISSUE THREAD

**Issue by exdirectory** [bwssytems/ha-bridge#178]
Have the ha-bridge working perfectly, also hooked up my own java servlet and getting them called via the bridge, all cool and very fast. Was a little underwhelmed by Echo until i found this project.

Am i right in thinking turn on/off and dim are the only device functions currently available without going via a skill (and the cloud)?

I have my nest hooked up but only after adding this skill, so echo is able to work with extra temperature words via the cloud, i.e. "set lounge to 20 degrees". Lounge being the device.

So is this project now limited by on/off/dim or are there other

**Comment by bwssytems** [comment]
This ha-bridge emulates a Hue hub. Since the only thing the Alexa can control on the Hue is on/off/dim that is all that is available. There are some sayings with Alex that make it a bit natural such as dimming "Alexa, set device to 40" and you can infer that any way you wish. But in the end, the skill will be more specific to it's device.

**Comment by exdirectory** [comment]
Sure, understood. My question is more general, and therefore still relevant as to say what other devices could be emulated that have a documented (or reverse engineered) protocol that might be interesting to add to the project to increase the vocabulary. i.e. not just emulate a hue.

I agree, sayings like "set <device> to <x>" works, but that requires some human training to remember the correct phrases, and not to use words like volume!

**Comment by bwssytems** [comment]
For local devices, there are no others. The Echo only has this capability for the Hue. All others are integrated applications within the Alexa cloud (i.e. Smarththings/Nest) and call their cloud systems directly or that a Skill need to be created and then managed, but that is all AWS cloud with Lambda.

**Comment by exdirectory** [comment]
So you may be aware that in the UK we don't have IFTTT enabled yet. Hence my original disappointment!

But using the ha-bridge is better anyway given i feared the lag of IFTTT which is often reported.

Have you tried your own skill with Lambda/AWS and able to compare performance to your bridge?

**Comment by bwssytems** [comment]
The issue with the skills is they require running in AWS Lambda. Each person would need to have their own account. You wouldn't want some Jo Shmo like me seeing all your data....

**Comment by exdirectory** [comment]
Let's close this one as question was answered, only hue currently supports actions without going via the cloud, and therefore limited to the hue vocab.
