### ISSUE TITLE
Echo could not discover my device from my ha-bridge(docker synology)

### ISSUE THREAD

**Issue by johnjohn444** [bwssytems/ha-bridge#179]
I have been suck for few days. At first, when i run this in my desktop win7, it's prefect. Then, I try to do it on my Synology 412+ DSM 6.0.2 in the container of docker. No luck at all. I am able to access the HA Bridge page though port 8080 of my Synology Ip. And i test everything is working, however Echo couldn't see my devices. Following is my log:

10-04-2016 18:17:31.226 INFO    HA Bridge (v3.1.0) starting.... com.bwssystems.HABridge.HABridge
10-04-2016 18:17:31.277 INFO    reading from config file: data/habridge.config  com.bwssystems.HABridge.BridgeSettings
10-04-2016 18:17:31.475 INFO    HA Bridge (v3.1.0) initializing.... com.bwssystems.HABridge.HABridge
10-04-2016 18:17:31.522 INFO    System control service started....  com.bwssystems.HABridge.SystemControl
10-04-2016 18:17:32.199 INFO    == Spark has ignited ...    spark.webserver.JettySparkServer
10-04-2016 18:17:32.205 INFO    >> Listening on 0.0.0.0:8080    spark.webserver.JettySparkServer
10-04-2016 18:17:32.904 INFO    setup initiated ....    com.bwssystems.harmony.HarmonyServer
10-04-2016 18:17:39.326 INFO    activity changed: [21412108] Play Music com.bwssystems.harmony.HarmonyServer
10-04-2016 18:17:39.402 INFO    HABridge device management service started....  com.bwssystems.HABridge.devicemanagmeent.DeviceResource
10-04-2016 18:17:39.826 INFO    Hue emulator service started....    com.bwssystems.HABridge.hue.HueMulator
10-04-2016 18:17:39.871 INFO    Hue description service started.... com.bwssystems.HABridge.upnp.UpnpSettingsResource
10-04-2016 18:17:39.885 INFO    UPNP Discovery Listener starting....    com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:17:39.898 INFO    Traceupnp: eth0 ... has addr /fe80:0:0:0:42:acff:fe11:2%eth0    com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:17:39.904 INFO    Traceupnp: eth0 ... has addr /fe80:0:0:0:0:242:ac11:2%eth0  com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:17:39.905 INFO    Traceupnp: eth0 ... has addr /172.17.0.2    com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:17:39.906 INFO    Traceupnp: Adding eth0 to our interface set com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:17:39.907 INFO    Traceupnp: lo ... has addr /0:0:0:0:0:0:0:1%lo  com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:17:39.908 INFO    Traceupnp: lo ... has addr /127.0.0.1   com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:17:39.908 INFO    Traceupnp: Adding lo to our interface set   com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:17:39.909 INFO    UPNP Discovery Listener running and ready....   com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:18:01.177 INFO    Traceupnp: isSSDPDiscovery found message to be an M-SEARCH message. com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:18:01.178 INFO    Traceupnp: isSSDPDiscovery found message to be valid under strict rules - strict: true  com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:18:01.179 INFO    Traceupnp: SSDP packet from 172.17.0.1:35215, body: M-SEARCH \* HTTP/1.1
 Host: 239.255.255.250:1900
 Man: "ssdp:discover"
 ST: ssdp:all
 MX: 5

```
com.bwssystems.HABridge.upnp.UpnpListener
```

10-04-2016 18:18:01.181 INFO    Traceupnp: sendUpnpResponse discovery template with address: 192.168.1.117 and port: 8080   com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:18:29.792 INFO    UPNP Discovery Listener - ended, restart found  com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:18:29.792 INFO    HA Bridge (v3.1.0) reinitialization requessted....  com.bwssystems.HABridge.HABridge
10-04-2016 18:18:29.793 INFO    >>> Spark shutting down ... spark.webserver.JettySparkServer
10-04-2016 18:18:29.811 INFO    done    spark.webserver.JettySparkServer
10-04-2016 18:18:29.814 INFO    reading from config file: data/habridge.config  com.bwssystems.HABridge.BridgeSettings
10-04-2016 18:18:29.823 INFO    HA Bridge (v3.1.0) initializing.... com.bwssystems.HABridge.HABridge
10-04-2016 18:18:29.825 INFO    System control service started....  com.bwssystems.HABridge.SystemControl
10-04-2016 18:18:29.829 INFO    == Spark has ignited ...    spark.webserver.JettySparkServer
10-04-2016 18:18:29.830 INFO    >> Listening on 0.0.0.0:8080    spark.webserver.JettySparkServer
10-04-2016 18:18:29.839 INFO    setup initiated ....    com.bwssystems.harmony.HarmonyServer
10-04-2016 18:18:33.405 INFO    activity changed: [21412108] Play Music com.bwssystems.harmony.HarmonyServer
10-04-2016 18:18:33.412 INFO    HABridge device management service started....  com.bwssystems.HABridge.devicemanagmeent.DeviceResource
10-04-2016 18:18:33.441 INFO    Hue emulator service started....    com.bwssystems.HABridge.hue.HueMulator
10-04-2016 18:18:33.445 INFO    Hue description service started.... com.bwssystems.HABridge.upnp.UpnpSettingsResource
10-04-2016 18:18:33.446 INFO    UPNP Discovery Listener starting....    com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:18:33.450 INFO    Traceupnp: eth0 ... has addr /fe80:0:0:0:42:acff:fe11:2%eth0    com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:18:33.453 INFO    Traceupnp: eth0 ... has addr /fe80:0:0:0:0:242:ac11:2%eth0  com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:18:33.453 INFO    Traceupnp: eth0 ... has addr /172.17.0.2    com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:18:33.454 INFO    Traceupnp: Adding eth0 to our interface set com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:18:33.455 INFO    Traceupnp: lo ... has addr /0:0:0:0:0:0:0:1%lo  com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:18:33.457 INFO    Traceupnp: lo ... has addr /127.0.0.1   com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:18:33.458 INFO    Traceupnp: Adding lo to our interface set   com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:18:33.458 INFO    UPNP Discovery Listener running and ready....   com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:18:35.082 INFO    Traceupnp: upnp device settings requested: from 172.17.0.1:8080 com.bwssystems.HABridge.upnp.UpnpSettingsResource
10-04-2016 18:18:35.084 INFO    Traceupnp: upnp device settings template filled with address: 192.168.1.117 and port: 8080  com.bwssystems.HABridge.upnp.UpnpSettingsResource
10-04-2016 18:19:01.177 INFO    Traceupnp: isSSDPDiscovery found message to be an M-SEARCH message. com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:19:01.178 INFO    Traceupnp: isSSDPDiscovery found message to be valid under strict rules - strict: true  com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:19:01.178 INFO    Traceupnp: SSDP packet from 172.17.0.1:35215, body: M-SEARCH \* HTTP/1.1
 Host: 239.255.255.250:1900
 Man: "ssdp:discover"
 ST: ssdp:all
 MX: 5

```
com.bwssystems.HABridge.upnp.UpnpListener
```

10-04-2016 18:19:01.179 INFO    Traceupnp: sendUpnpResponse discovery template with address: 192.168.1.117 and port: 8080   com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:19:31.176 INFO    Traceupnp: isSSDPDiscovery found message to be an M-SEARCH message. com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:19:31.177 INFO    Traceupnp: isSSDPDiscovery found message to be valid under strict rules - strict: true  com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:19:31.177 INFO    Traceupnp: SSDP packet from 172.17.0.1:35215, body: M-SEARCH \* HTTP/1.1
 Host: 239.255.255.250:1900
 Man: "ssdp:discover"
 ST: ssdp:all
 MX: 5

```
com.bwssystems.HABridge.upnp.UpnpListener
```

10-04-2016 18:19:31.178 INFO    Traceupnp: sendUpnpResponse discovery template with address: 192.168.1.117 and port: 8080   com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:20:01.177 INFO    Traceupnp: isSSDPDiscovery found message to be an M-SEARCH message. com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:20:01.178 INFO    Traceupnp: isSSDPDiscovery found message to be valid under strict rules - strict: true  com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:20:01.178 INFO    Traceupnp: SSDP packet from 172.17.0.1:35215, body: M-SEARCH \* HTTP/1.1
 Host: 239.255.255.250:1900
 Man: "ssdp:discover"
 ST: ssdp:all
 MX: 5

```
com.bwssystems.HABridge.upnp.UpnpListener
```

10-04-2016 18:20:01.179 INFO    Traceupnp: sendUpnpResponse discovery template with address: 192.168.1.117 and port: 8080   com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:20:31.176 INFO    Traceupnp: isSSDPDiscovery found message to be an M-SEARCH message. com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:20:31.177 INFO    Traceupnp: isSSDPDiscovery found message to be valid under strict rules - strict: true  com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:20:31.177 INFO    Traceupnp: SSDP packet from 172.17.0.1:35215, body: M-SEARCH \* HTTP/1.1
 Host: 239.255.255.250:1900
 Man: "ssdp:discover"
 ST: ssdp:all
 MX: 5

```
com.bwssystems.HABridge.upnp.UpnpListener
```

10-04-2016 18:20:31.178 INFO    Traceupnp: sendUpnpResponse discovery template with address: 192.168.1.117 and port: 8080   com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:21:01.176 INFO    Traceupnp: isSSDPDiscovery found message to be an M-SEARCH message. com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:21:01.177 INFO    Traceupnp: isSSDPDiscovery found message to be valid under strict rules - strict: true  com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:21:01.177 INFO    Traceupnp: SSDP packet from 172.17.0.1:35215, body: M-SEARCH \* HTTP/1.1
 Host: 239.255.255.250:1900
 Man: "ssdp:discover"
 ST: ssdp:all
 MX: 5

```
com.bwssystems.HABridge.upnp.UpnpListener
```

10-04-2016 18:21:01.178 INFO    Traceupnp: sendUpnpResponse discovery template with address: 192.168.1.117 and port: 8080   com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:21:31.175 INFO    Traceupnp: isSSDPDiscovery found message to be an M-SEARCH message. com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:21:31.175 INFO    Traceupnp: isSSDPDiscovery found message to be valid under strict rules - strict: true  com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:21:31.176 INFO    Traceupnp: SSDP packet from 172.17.0.1:35215, body: M-SEARCH \* HTTP/1.1
 Host: 239.255.255.250:1900
 Man: "ssdp:discover"
 ST: ssdp:all
 MX: 5

```
com.bwssystems.HABridge.upnp.UpnpListener
```

10-04-2016 18:21:31.177 INFO    Traceupnp: sendUpnpResponse discovery template with address: 192.168.1.117 and port: 8080   com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:22:01.176 INFO    Traceupnp: isSSDPDiscovery found message to be an M-SEARCH message. com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:22:01.177 INFO    Traceupnp: isSSDPDiscovery found message to be valid under strict rules - strict: true  com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:22:01.177 INFO    Traceupnp: SSDP packet from 172.17.0.1:35215, body: M-SEARCH \* HTTP/1.1
 Host: 239.255.255.250:1900
 Man: "ssdp:discover"
 ST: ssdp:all
 MX: 5

```
com.bwssystems.HABridge.upnp.UpnpListener
```

10-04-2016 18:22:01.178 INFO    Traceupnp: sendUpnpResponse discovery template with address: 192.168.1.117 and port: 8080   com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:22:31.177 INFO    Traceupnp: isSSDPDiscovery found message to be an M-SEARCH message. com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:22:31.178 INFO    Traceupnp: isSSDPDiscovery found message to be valid under strict rules - strict: true  com.bwssystems.HABridge.upnp.UpnpListener
10-04-2016 18:22:31.178 INFO    Traceupnp: SSDP packet from 172.17.0.1:35215, body: M-SEARCH \* HTTP/1.1
 Host: 239.255.255.250:1900
 Man: "ssdp:discover"
 ST: ssdp:all
 MX: 5

```
com.bwssystems.HABridge.upnp.UpnpListener
```

10-04-2016 18:22:31.179 INFO    Traceupnp: sendUpnpResponse discovery template with address: 192.168.1.117 and port: 8080   com.bwssystems.HABridge.upnp.UpnpListener
Logging Configuration 

Please advice. Thank you.

John

**Comment by bwssytems** [comment]
You need to set the upnp ip addr to the host of the synology. I looks like is using a different address.

**Comment by johnjohn444** [comment]
I think I did (from the HA Bridge page 192.168.1.117 is in the field of UPNP IP Adress) and I also allow the 50000 port in my synology. Did i miss something? Thank you.

**Comment by johnjohn444** [comment]
I also found "java-jar-Dupnp.config.address=192.168.1.117" in the process page of my docker.

**Comment by bwssytems** [comment]
And your Synology ip address is 172.17.0.2  from the log above. The docker has a example ip in it and you will need to change to match your synology host ip addr.

**Comment by johnjohn444** [comment]
Is it possible that the upnp config file could not be access by Echo? How can i change the path of the file so that i could make it in a share folder in my NAS?

**Comment by bwssytems** [comment]
Have you taken a look at these instructions? https://github.com/bwssytems/docker-ha-bridge/blob/master/README.md

**Comment by johnjohn444** [comment]
I don't know how to change 172.17.0.2 from my docker bridge network. Is there any other way to change the unpn ip? Can i do it in the environment at the startup of the container?

**Comment by bwssytems** [comment]
Where did you get your docker config for the ha-bridge? That site I listed above is the one that most people use. I am not the docker person and it is maintained at he site listed above.

**Comment by johnjohn444** [comment]
I get it from here https://hub.docker.com/r/aptalca/home-automation-bridge/

**Comment by bwssytems** [comment]
Then that readme at that site has the info to update the IP. you'll need to google docker configurations to help you.

**Comment by bwssytems** [comment]
Did this get solved?

**Comment by rodders99** [comment]
I had an identical problem, ha-bridge was running fine on a Raspberry Pi, it worked first time without any modification, I had UDP devices configured and working in under an hour. 

I then moved ha-bridge to a synology NAS DS215j version: DSM 6.0.2-8451 Update 2 (if that helps) last update to the OS was 5/10/2016 (uk date) and Alexa wouldn't find it. On the Pi I didn't need to set the UPnP address it worked without having to modify it.

However when I moved to the Synology NAS Alexa couldn't find any devices. I then found another comment describing a similar problem and solution, to set the UPnP address to the correct address of the synology NAS, that hadn't been picked up correctly unlike running on the PI and it worked immediately.

**Comment by bwssytems** [comment]
closing due to non issue with ha-bridge

**Comment by rdownesy** [comment]
@rodders99 can you let me know how you installed this on a DS215J (which doesn't support docker)? I'm trying to work out how to do this! thanks

**Comment by rodders99** [comment]
Installed Java, downloaded the zip from git, unzipped the zip and ran it using the command line as instructed on the github page. Didn't need docker. You'll need to install JAVA.
