### ISSUE TITLE
Json style

### ISSUE THREAD

**Issue by robertw** [bwssytems/ha-bridge#18]
could you provide a example as to the layout using real info as i can not seem to get it t working correct for multiple  harmony hubs 

What am i doing wrong here many thanks

{devices:[{name:Theater,ip:192.168.1.246},{name:Family Room,ip:192.168.1.210]}}

**Comment by audiofreak9** [comment]
Looks like you have the last bracket and brace swapped.

-Dharmony.address={devices:[{name:Theater,ip:192.168.1.246},{name:Family Room,ip:192.168.1.210}]}

**Comment by robertw** [comment]
Many thanks but i believe there is a bug or I am not doing this right if I
change the hub to family and drop room all is fine it does not seem to
parse the name if there is a space....

Many thanks

On Mon, Dec 14, 2015 at 2:26 PM, audiofreak9 <notifications@github.com>
wrote:

> Looks like you have the last bracket and brace swapped.
>
> -Dharmony.address={devices:[{name:Theater,ip:192.168.1.246},{name:Family
> Room,ip:192.168.1.210}]}
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bwssytems/ha-bridge/issues/18#issuecomment-164533638>.
>



-- 
Regards

Robert

**Comment by bwssytems** [comment]
You will need to surround this with quotes as the space is being interpreted on the command line....

-Dharmony.address="{devices:[{name:Theater,ip:192.168.1.246},{name:Family Room,ip:192.168.1.210}]}"

**Comment by randellhodges** [comment]
Do you also need to quote the values, for a valid json object as a string?

-Dharmony.address="{devices:[{name:'Theater',ip:'192.168.1.246'},{name:'Family
Room',ip:'192.168.1.210'}]}"

**Comment by bwssytems** [comment]
nope, that happens automagically inside the program.

**Comment by audiofreak9** [comment]
A lot happens 'automagically' inside the program and we thank you for ALL of it!!!

**Comment by robertw** [comment]
Works great many thanks have a great  holiday .......
