### ISSUE TITLE
Harmony dim

### ISSUE THREAD

**Issue by exdirectory** [bwssytems/ha-bridge#180]
Have added some harmony hub functions, works perfect again - well done for getting this all hooked up and working out of the box.

For newbies, you have to configure the harmony hub on the bridge control page, then hit save, then you get two new tabs appear - i was struggling until this point to see how harmony activities could be configured. Once those pages arrive all your devices and activities can be selected - very easy.

My question is, there is no dim action on the harmony helpers, i assume this is because no one has worked out this part of the harmony hub protocol that you can hook in to, or you expecting a relevant activity to be created on the harmony to increase/decrease the light level.

e.g. if i say turn down my lounge lights, would you expect to have to call an activity on the harmony hub to do that? [assume my lights can be controlled only via IR via the hub, which they are].

Or am i missing a trick here?

**Comment by bwssytems** [comment]
Your assumption is correct. The ha-bridge only can call activities or buttons that are already configured. Those are the only items exposed on the harmony api.

**Comment by bwssytems** [comment]
closing this as it is a question that is answered.
