### ISSUE TITLE
Asking Alexa to increase / decrease

### ISSUE THREAD

**Issue by cherowley** [bwssytems/ha-bridge#182]
Hi!

Is there anyway to get home bridge to work with these commands after a "on" command?

The problem as I see it is that homebridge needs to be told the level of the device just turned on as it may have changed since the last "set" command homebridge issued?

Maybe add some additional boxes for the on / off URLs  to query (in my case) domoticz and get the current value?

This is all so I can control my home made Wi-Fi thermostat by asking Alexa to increase by 1 rather than asking her to set to a specific Temperature 😀

**Comment by audiofreak9** [comment]
Is your thermostat a homebrew creation or by a thermostat company?  
How are you controlling it?  API, RPi, Alexa skill?
Based on what's available to you, can you get the current setting when your control occurs?

**Comment by cherowley** [comment]
Hi!

I made it myself using a sonoff (based on esp8266) and wrote a new espeasy plugin to control the relay based on time and DHT22 readings..

As such I wrote it to accept the usual domoticz/espeasy http json commands..

**Comment by audiofreak9** [comment]
The ha-bridge does have update state ability.  It may be a silly loop, but you could have the ha-bridge first send a command to domoticz that fires both an update ha-bridge command, that also fires another command back to the ha-bridge that fires your current domoticz command to change the thermostat.  If that all makes sense?
It requires an http PUT, see here https://github.com/bwssytems/ha-bridge/blob/master/README.md#update-bridge-internal-light-state

**Comment by cherowley** [comment]
Hi AF,

That command looks like what I need :)

Just got to figure out how to actually use it lol ...

http://192.168.2.100:8080/api/user/lights/20/bridgeupdatestate=%7B%22on%22:true,%22bri%22:25%7D

**Comment by bwssytems** [comment]
@cherowley A couple of things to help you. To set the values for the call it is an HTTP PUT with the address http://<bridge ip and port>/api/<your user>/lights/<your light id>/bridgeupdatestate with a json body of '{"on":true,"bri":<your value between 0 and 254>}', the 254 is the high value and think of that as the 100 value when working with other things, just divide by 254.

Also, if you want to send multiple commands within one 'On' URL, use the multi-command feature: https://github.com/bwssytems/ha-bridge/blob/master/README.md#multiple-call-construct

**Comment by cherowley** [comment]
Hmm, Ok So I tried this in my browser but no good :(

http://192.168.2.100:8080/api/lights/bridgeupdatestate.htm?{"on":false,"bri":20}

Response in chrome was:

HTTP ERROR: 404

Problem accessing /api/ights/bridgeupdatestate.htm. Reason:

    Not Found

**Comment by bwssytems** [comment]
You cannot use a browser as all it does is HTTP GET when getting to a site. You will need a tool that does HTTP PUT and also you need to follwo the construct of Rest API: ```http://<ha-bridge ip and port>/api/<your username>/lights/<your light id>/bridgeupdatestate```

**Comment by cherowley** [comment]
Just a quick update, I'm still looking into this but haven't had time recently so please keep open :)

**Comment by bwssytems** [comment]
Any info on this?

**Comment by cherowley** [comment]
Not as yet, still trying to figure out the exact command!

Using the chrome rest console

http://192.168.2.100:8080/api/che/lights/20/ - this is the target request URI
{"on":false,"bri":100} - this is the request body raw payload

But this is the response:

<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 404 </title>
</head>
<body>
<h2>HTTP ERROR: 404</h2>
<p>Problem accessing /api/che/lights/20/. Reason:
<pre>    Not Found</pre></p>
<hr /><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.3.z-SNAPSHOT</a><hr/>
</body>
</html>

**Comment by bwssytems** [comment]
You need to call POST http://192.168.2.100:8080/api/che/lights/20/**state**

**Comment by cherowley** [comment]
That works many thanks :)

Can you confirm how the "remembering" of brightness level works in HA bridge please?

Does it internally remember the last brightness set between on/offs?

So If I say 

Alexa set light to 20 percent
alexa turn light off
alexa turn light on
alexa increase light by 3

will the light be on at level 23 ?

**Comment by bwssytems** [comment]
Yes, the ha-bridge remembers the state between calls. I believe Alexa uses just dim and bright for the commands and the ha-bridge will act accordingly.

**Comment by cherowley** [comment]
Ah this doesn't quite work.

Asking Alexa to increase light only works after you have first asked Alexa to set light to level.

So if you

Alexa turn on light
Alexa increase light

Doesn't work but

Alexa turn on light
Alexa increase light
Alexa decrease light

Will increase it - seems to be one command behind or something?

**Comment by bwssytems** [comment]
Unfortunately, the bridge does not know the state of the device until it is primed. There is a command to prime it, but you still have to know when to do it and what to set it to.

**Comment by cherowley** [comment]
Ah but if  the bridge is storing the level then it is primed?

Store the last used level then it will work?

Once a set command has been done once then all further commands should work until the bridge is restarted and the variable holding the last level is initiated?

**Comment by bwssytems** [comment]
When the bridge first starts, all devices are off and have 0 setting for brightness.

Turning a device "on" sets it state to on and the brightness at full (even if the device being activated has some previous memory of a level that is not full)

So, priming involves setting the device to a specific setting that you can work from... So, the on command should set the device to on and at it's fullest value. Then subsequent commands will work.

**Comment by cherowley** [comment]
That all makes sense but doesn't seem to quite work for me, after turning on the first increase or decrease command does nothing.

The system will have already been primed by previous set, increase and decrease commands before the off command.

I will try putting the dim URL into the on URL..

**Comment by cherowley** [comment]
OK that works as you said :)

Could the design be changed so that the on command goes to the last level instead of 100? It would be WAY more useful not to have lights blasting at 100% when turning on but coming back on at the last level 😀

**Comment by bwssytems** [comment]
Something to look at. Just need to know when it is first called to prime it.

**Comment by cherowley** [comment]
Would be great as I can then use it to control the heating, at present every time I ask it to turn on the heating would go into the tropics lol 😂

**Comment by audiofreak9** [comment]
Since I use the ha-bridge to control my X10 equipment.  My CM11A controller only tracks on/off and if was dimmed, but not dim level.  Being able to use or have access to last on bright level would be great.

**Comment by bwssytems** [comment]
I looked at the code again, and the only time it sets the bri  value to 254 automatically, is when on is called and the value is 0; This should be working properly in the current versions.
