### ISSUE TITLE
404 systemctl?

### ISSUE THREAD

**Issue by Deojuvente** [bwssytems/ha-bridge#186]
Hello, 

just reinstalled and...
i don't see the device.db in the data/device.db and only get 404 errors :(
the habridge.config is working and is in there. i think this has to do whit the new linux (systemctl) i read on here  but i don't know how to solve it.. is someone willing to make a walk trow on this for a Raspberry pi plz? i use the ha bright sins V1.5.1 and i am missing it..!! or am i wrong here?
thnx

Add new Device Error: undefined with status: Not Found - 404

noting more in the log as this:
Component
10-15-2016 22:15:25.974 	INFO 	HA Bridge (v3.1.0) starting.... 	com.bwssystems.HABridge.HABridge
10-15-2016 22:15:26.534 	INFO 	reading from config file: data/habridge.config 	com.bwssystems.HABridge.BridgeSettings
10-15-2016 22:15:27.323 	INFO 	HA Bridge (v3.1.0) initializing.... 	com.bwssystems.HABridge.HABridge
10-15-2016 22:15:27.483 	INFO 	System control service started.... 	com.bwssystems.HABridge.SystemControl
10-15-2016 22:15:29.767 	INFO 	== Spark has ignited ... 	spark.webserver.JettySparkServer
10-15-2016 22:15:29.791 	INFO 	>> Listening on 0.0.0.0:8080 	spark.webserver.JettySparkServer
10-15-2016 22:15:31.296 	INFO 	setup initiated .... 	com.bwssystems.harmony.HarmonyServer
10-15-2016 22:15:37.983 	INFO 	activity changed: [19974595] watch television 	com.bwssystems.harmony.HarmonyServer
10-15-2016 22:15:44.942 	INFO 	Starting Nest login... 	com.bwssystems.nest.controller.NestSession
10-15-2016 22:15:47.045 	INFO 	Completed Nest login... 	com.bwssystems.nest.controller.NestSession
Logging Configuration

**Comment by Deojuvente** [comment]
after reinstall:
10-17-2016 19:52:51.366 	INFO 	HA Bridge (v3.1.0) starting.... 	com.bwssystems.HABridge.HABridge
10-17-2016 19:52:51.572 	INFO 	reading from config file: /home/pi/habridge/data/habridge.config 	com.bwssystems.HABridge.BridgeSettings
10-17-2016 19:52:52.606 	INFO 	HA Bridge (v3.1.0) initializing.... 	com.bwssystems.HABridge.HABridge
10-17-2016 19:52:52.798 	INFO 	System control service started.... 	com.bwssystems.HABridge.SystemControl
10-17-2016 19:52:54.958 	INFO 	== Spark has ignited ... 	spark.webserver.JettySparkServer
10-17-2016 19:52:54.981 	INFO 	>> Listening on 0.0.0.0:8080 	spark.webserver.JettySparkServer
10-17-2016 19:52:56.438 	INFO 	setup initiated .... 	com.bwssystems.harmony.HarmonyServer
10-17-2016 19:53:03.145 	INFO 	activity changed: [19974595] watch television 	com.bwssystems.harmony.HarmonyServer
10-17-2016 19:53:03.183 	WARN 	Error reading the file: data/device.db - Does not exist or is not readable. continuing... 	com.bwssystems.HABridge.dao.DeviceRepository
10-17-2016 19:53:03.806 	INFO 	HABridge device management service started.... 	com.bwssystems.HABridge.devicemanagmeent.DeviceResource
10-17-2016 19:53:03.945 	INFO 	Hue emulator service started.... 	com.bwssystems.HABridge.hue.HueMulator
10-17-2016 19:53:03.998 	INFO 	Hue description service started.... 	com.bwssystems.HABridge.upnp.UpnpSettingsResource
10-17-2016 19:53:04.015 	INFO 	UPNP Discovery Listener starting.... 	com.bwssystems.HABridge.upnp.UpnpListener
10-17-2016 19:53:04.049 	INFO 	UPNP Discovery Listener running and ready.... 	com.bwssystems.HABridge.upnp.UpnpListener
10-17-2016 19:54:15.261 	WARN 	Issue getting directory listing for backups in directory: data 	com.bwssystems.util.BackupHandler
10-17-2016 19:54:18.087 	WARN 	Issue getting directory listing for backups in directory: data 	com.bwssystems.util.BackupHandler
10-17-2016 19:54:21.682 	WARN 	Issue getting directory listing for backups in directory: data 	com.bwssystems.util.BackupHandler
10-17-2016 19:54:42.097 	WARN 	Issue getting directory listing for backups in directory: data 	com.bwssystems.util.BackupHandler

**Comment by bwssytems** [comment]
So, the location of the directory for data is not writable. You will need to set that location differently in the config tab and save it first.

**Comment by Deojuvente** [comment]
i dunn this step by step:
 
mkdir habridge
 cd habridge
 wget https://github.com/bwssytems/ha-bridge/releases/download/v3.1.0/ha-bridge-3.1.0.jar

Rename the .jar in /home/pi/habridge/ This will allow you to insert future versions by renaming them ha-bridge.jar and overwriting the existing ha-bridge.jar without having to redo the systemctl file.

 mv ha-bridge-3.1.0.jar  ha-bridge.jar

Edit the shell script for starting:

 nano starthabridge.sh

Then cut and past this, modify any locations that are not correct

 cd /home/pi/habridge
 rm /home/pi/habridge/habridge-log.txt
 nohup java -jar /home/pi/habridge/ha-bridge.jar > /home/pi/habridge/habridge-log.txt 2>&1 &
 chmod 777 /home/pi/habridge/habridge-log.txt

Exit and save the file with ctrl-X and follow the prompts and then execute on the command line:

 chmod u+x starthabridge.sh

Then execute the script:

 ./starthabridge.sh

You should now be running the bridge. Check for errors:

 tail -f habridge-log.txt

Create a systemctl unit file (habridge.service) so the habridge will autostart:

Create a unit file in the /etc/systemd/system/ directory and make sure it has the correct file permissions. Execute as root:

 sudo su
 touch /etc/systemd/system/habridge.service
 chmod 664 /etc/systemd/system/habridge.service

Open the file for editing:

 cd /etc/systemd/system/
 nano habridge.service

Add the following content to the file:

 [Unit]
 Description=HA Bridge
 Wants=network.target
 After=network.target

 [Service]
 Type=simple
 ExecStart=/usr/bin/java -jar -Dconfig.file=/home/pi/habridge/data/habridge.config /home/pi/habridge/ha-bridge.jar

 [Install]
 WantedBy=multi-user.target

Save the file (ctl-o), confirm the file to save as, and exit (ctl-x)

Execute the following commands to reload the configuration and start the custom service:

 systemctl daemon-reload
 systemctl start habridge.service
 systemctl enable habridge

To check the status:

 systemctl status habridge

**Comment by Deojuvente** [comment]
● habridge.service - HA Bridge
Loaded: loaded (/etc/systemd/system/habridge.service; enabled)
Active: failed (Result: exit-code) since ma 2016-10-17 19:23:23 CEST; 10s ago
Main PID: 1144 (code=exited, status=100)

**Comment by Deojuvente** [comment]
Hello BWS

its writable

root@FibaroPI:/home/pi/habridge/data# dir
device.db                         habridge.config
device.db-2016-10-17-19-47-35.bk  habridge.config-2016-10-17-19-50-45.cfgbk
root@FibaroPI:/home/pi/habridge/data#

10-17-2016 20:24:25.995 	WARN 	Error reading the file: data/device.db - Does not exist or is not readable. continuing... 	com.bwssystems.HABridge.dao.DeviceRepository

**Comment by bwssytems** [comment]
IN the Bridge Control tab, if the location says data/device.db, then it is wrong. You need to have the full path to /home/pi/habridge/data/device.db as when the system starts the habridge, the home dir is root not /home/pi.

**Comment by Deojuvente** [comment]
still not working http://prntscr.com/cvj879

**Comment by Deojuvente** [comment]
is it possible it has something to do whit the raspberry pi pixel software
https://www.raspberrypi.org/blog/introducing-pixel/
this i have installed on the PI?

**Comment by bwssytems** [comment]
It's not the PIXEL OS it is not finding or being able to access anything in the device.db. Can you do an ls -l on the /home/pi/habridge/data directory please.

**Comment by Deojuvente** [comment]
http://prntscr.com/cvk2i5

**Comment by Deojuvente** [comment]
sorry
http://prntscr.com/cvk34d

**Comment by bwssytems** [comment]
In the data directory: cd data; ls -l

**Comment by Deojuvente** [comment]
http://prntscr.com/cvk34d sorry

**Comment by bwssytems** [comment]
In the data directory: cat devices.db

**Comment by Deojuvente** [comment]
http://prntscr.com/cvk6gg file or dir dos not exist

**Comment by bwssytems** [comment]
Sorry, it is device.db

**Comment by Deojuvente** [comment]
http://prntscr.com/cvk90a blocked my pasw :)

**Comment by bwssytems** [comment]
Ahh, that is an habridge.config file data. Shutdown your habridge and delete the device.db file. It will be better after that.

**Comment by Deojuvente** [comment]
looks like its working now
but still have a error
10-17-2016 23:01:14.190 	WARN 	Error reading the file: /home/pi/habridge/data/device.db - Does not exist or is not readable. continuing... 	com.bwssystems.HABridge.dao.DeviceRepository

**Comment by bwssytems** [comment]
That would be correct as you just deleted the file. Now go add some devices....

**Comment by Deojuvente** [comment]
looks nice thank you for your help :) are you planning to make a easy update button :D i worth love that hehe

**Comment by bwssytems** [comment]
Due to the multiple platforms, probably not on the update function. Closing this issue.

**Comment by Deojuvente** [comment]
plz re open
after reboot i lost all my devises and back to 404
http://prntscr.com/cvyni7

**Comment by bwssytems** [comment]
Your command line to start the bridge is not pointing at the habridge.config that you saved before. Look at your setup for where your files are stored.

**Comment by kleuschner** [comment]
Hi,

I'm also gettting this 404 error. I deleted the device.db and now I have a new file with an existing device, but getting the error and no device is displayed in the webinterface.

` cat habridge.config
{"upnpconfigaddress":"192.168.178.101","serverport":88,"upnpresponseport":50088,"upnpdevicedb":"/home/pi/habridge/data/device.db","harmonyaddress":{"devices":[{"name":"Harmony Hub","ip":"192.168.178.58"}]},"buttonsleep":100,"upnpstrict":true,"traceupnp":false,"nestuser":"kaeze","nestpwd":"doener123","veraconfigured":false,"harmonyconfigured":true,"nestconfigured":true,"farenheit":true,"configfile":"/home/pi/habridge/data/habridge.config","numberoflogmessages":512,"hueconfigured":false,"halconfigured":false,"whitelist":{"gld6NRZND6eB1YVgCmpZkiH8pOVn9zP0BGWj7SSY":{"lastUseDate":"2017-02-16T09:23:16","createDate":"2017-02-16T09:23:16","name":"auto insert user"},"test":{"lastUseDate":"2017-02-16T14:40:42","createDate":"2017-02-16T14:40:42","name":"auto insert user"}},"settingsChanged":true,"myechourl":"alexa.amazon.de/spa/index.html#cards","webaddress":"0.0.0.0","mqttconfigured":false,"hassconfigured":false,"hubversion":"01036659","domoticzconfigured":false}`

` cat device.db
[{"id":"1","uniqueid":"00:17:88:5E:D3:01-01","name":"Schalte Fernseher","mapType":"httpDevice","offUrl":"[{\"item\":\"http://192.168.178.48/web/remotecontrol?command\u003d116\",\"type\":\"httpDevice\",\"httpVerb\":\"GET\"}]","onUrl":"[{\"item\":\"http://192.168.178.48/web/remotecontrol?command\u003d116\",\"type\":\"httpDevice\",\"httpVerb\":\"GET\",\"httpBody\":\"\"}]","inactive":false,"noState":false}]`

**Comment by bwssytems** [comment]
You need to post how you are starting the bridge and the details of that.
