### ISSUE TITLE
Cant discover bridge

### ISSUE THREAD

**Issue by scoobyd00** [bwssytems/ha-bridge#187]
Hi,
Ive got this setup on my Raspberry PI to control lights in my domoticz setup.
I can access the webpage and setup the various devices and the tests work and control my lights.

Im going to be using this with a Amazon dot when it arrives later this week but wanted to test to make sure the bridge is working ok. 

Im trying to find the bridge using the Philips HUE android app but it doesnt find anything when I do a search.
I see that in the terminal window of the raspberry pi that its seeing the incoming packet but the app isnt discovering any bridge.
If I have my PC turned on I then see in the terminal window of the PI that its sent and got a response from my ip address of my PC so it looks like its sending packets out but for some reason the app isnt finding the bridge.

Ive tried changing the port from 8080 to 80 but this hasnt helped?.

Any ideas?, i just want to make sure the bridge is working correctly before i get the amazon dot.

Thankyou.

**Comment by scoobyd00** [comment]
Just tried ver 1 of the official hue app and it finds the bridge fine.

Looks like its an issue with ver 2 latest of the app as this doesnt find the bridge

**Comment by bwssytems** [comment]
The net version will have better handling of upnp and will be find-able by more apps.

**Comment by scoobyd00** [comment]
Excellent, thanks for the quick reply. I look forward to the next version.

**Comment by scoobyd00** [comment]
The new update has fixed this issue, working perfectly.. Thanks for the excellent software
