### ISSUE TITLE
New feature: Domoticz scan

### ISSUE THREAD

**Issue by cherowley** [bwssytems/ha-bridge#188]
This isn't an issue but was advised to put this request here :)

Can we add a section to the bridge control to enter a domoticz server details.
The HA bridge would then scan the domoticz server for compatible devices and add them - in a similar fashion as it does for the Harmony Hub and Home Assistant types :)

Cheers!

**Comment by sacheenganatra** [comment]
+1 this would be great if it was possible,

**Comment by oktane83** [comment]
Does this feature  exists with Home Assistant? Did I miss something?

**Comment by bristolbaz** [comment]
+1 for me too on this - this would cut down my current process of Alexa --> Smartthings --> Domoticz
