### ISSUE TITLE
Device IDs are are ambiguous with multiple Veras

### ISSUE THREAD

**Issue by hharte** [bwssytems/ha-bridge#19]
If you have multiple Vera controllers, devices on different controllers may have the same IDs.  In this case, devices with duplicate IDs on different Veras will show that the device is already configured.  It would be great if the device ID and some other key (maybe Vera MAC address) was used to disambiguate, so ha-bridge could be used with multiple Vera controllers.

**Comment by bwssytems** [comment]
Something that I thought may come about  since people have asked for the multiple harmony support. THis will be in the enhancement queue.
