### ISSUE TITLE
Can not create backup

### ISSUE THREAD

**Issue by jmaybes** [bwssytems/ha-bridge#190]
Hello and thanks so much for this awesome project. I am having only one, what seems to be probably a simple issue, I can not create a device backup, I receive the following messages, any help is much appreciated:

ERROR	Could not backup to file: back.bk message: data\device.db	com.bwssystems.util.BackupHandler

WARN	Issue getting directory listing for backups in directory: data	com.bwssystems.util.BackupHandler

**Comment by bwssytems** [comment]
Looks like there is a permission issue in the directory that is trying to be used, Look at your configuration of where your data directory is in relation to the user that is running the ha-bridge.

**Comment by jmaybes** [comment]
Sorry, im a bit of a newbie running anything with a localhost, by config file is located:

http://localhost/#/data/habridge.config

Should there be a relative path on my machine and could you help me to get there? I haven't changed any configs as per default setting when running the bridge. Thanks so much for the help.

**Comment by bwssytems** [comment]
What is the path that shows in the bridge control tab for the "Configuration Path and File	" and "Device DB Path and File"? These control the paths to the directories for the files. If they show somewhere that is not accessible, that is why. Also, how do you start the bridge?

**Comment by jmaybes** [comment]
Configuration Path and File:  data/habridge.config

Device DB Path and File: data/device.db

I started the bridge by running a command prompt where the jar file was placed, in: C:\Program Files\Java\jdk1.8.0_40\bin

Im guessing this is my problem, now when I read the log, it seems it has never been able to create any files. Confusing how I have managed to created 26 devices so far? any advice how I can correct this, without losing anything? Thanks again so much for your time.

**Comment by bwssytems** [comment]
You can create devices but there are errors in your log saying they couldn't be saved.

To save these, open a text editor, notepad is fine and do the following:

1) got to http://<your ip and port>/api/devices
2) cut and paste the all of the ouput in your browser window to the notepad
3) save the file as device.db in a directory you ca access: i.e.: Documents/habridge/data
4) run your bridge and point the config file with -Dconfig.file=c:\Users\<your user>\Documents\habridge\data\habridge.config
5) when you get to the web ui, hit dave in the bridge control page to actually create the config file and then change your path for the device.db file and you will be ready to go.

**Comment by jmaybes** [comment]
Spot on, worked a treat, thx very much!!

**Comment by bwssytems** [comment]
Awesome.
