### ISSUE TITLE
use ${intensity.percent} inside a call to ${intensity.math}

### ISSUE THREAD

**Issue by Malarcy** [bwssytems/ha-bridge#191]
I would like to use the intensity percentage as part of a calculation - I have a requirement to turn a 1-100 % into a level of 1 - 32 for a dim command URL

What I have is 

http://192.168.0.215:8990/json.htm?type=command&param=switchlight&idx=72&switchcmd=Set%20Level&level=${intensity.math((${intensity.percent}/100)*32)}

What I hope/extpect is a url sent as (for 50%) 
http://192.168.0.215:8990/json.htm?type=command&param=switchlight&idx=72&switchcmd=Set%20Level&level=16

What I get (in the logs) is
Error on calling url to change device state: http://192.168.0.215:8990/json.htm?type=command&param=switchlight&idx=72&switchcmd=Set%20Level&level=${intensity.math((50/100)*32)}

It seems the intensity.math substitution is not performed in this case.

**Comment by audiofreak9** [comment]
You need to use 

`${intensity.math((X/255)*32)}`

intensity.math is the calc, based on a 0 to 255 range

**Comment by Malarcy** [comment]
Doh!

OK - got it, desired result achieved simply - cold light of day is always good for math.

Thanks.
