### ISSUE TITLE
Orvibo S20 Wifi Switch

### ISSUE THREAD

**Issue by nasherg** [bwssytems/ha-bridge#192]
Has anyone been able to connect a WIWO (Orvibo S20) wifi switch?

based on the following link I have created the UDP commands in ha-bridge but the on/off commands are not working.
https://stikonas.eu/wordpress/2015/02/24/reverse-engineering-orvibo-s20-socket/

My best guess is that I need a sleep/pause between the subsription UDP command and then the on/off command.     Is this possible via the json construct ?

Any help would be appreciated.

example command that I have used

[{"item":"udp://192.168.0.7:10000/6864001e636cxxxxxxxxxxxx202020202020xxxxxxxxxxxx202020202020"},
{"item":"udp://192.168.0.7:10000/686400176463xxxxxxxxxxxx2020202020200100000000"}]

Thanks

**Comment by bwssytems** [comment]
By default, the sleep time between commands is 100ms. To change this, go to the Bridge Control tab and change "Button Press/Call Item Loop Sleep Interval (ms)" to a setting in ms that you desire.

**Comment by bwssytems** [comment]
Any update on this?

**Comment by merlin051** [comment]
I'm using the orvibo switches. But I'm using a Python script and custom execution in the bridge to end commands over. 

Look here:

https://github.com/cherezov/orvibo/blob/master/README.md
