### ISSUE TITLE
Is it possible to execute a batch- or a powershell script?

### ISSUE THREAD

**Issue by JoeTN** [bwssytems/ha-bridge#197]
There's probably no issue about this, I just can't get it to work... First of all, thank you so much for your fantastic bridge, nice work.

I am currently running the ha-server 3.1.0 on Windows 10 from an elevated commandprompt. I am trying to use the device type "Execute script/program" with the following "On url" which works: `[{"item":"C:\\Home_Automation_Software\\Harmony_Control\\Scripts\\Commands\\putty.exe"}]`

if I then try to change putty for a batch script called tv.bat like this  `[{"item":"C:\\Home_Automation_Software\\Harmony_Control\\Scripts\\Commands\\tv.bat"}]` I get the following response when testing the "On url" `Request Exceuted: success {"/lights/983837034/state/on":true}` Even though the batch file isn't actually launched at the computer, like Putty was.

If I try to change to a Powershell script like this `[{"item":"C:\\Home_Automation_Software\\Harmony_Control\\Scripts\\Commands\\test.ps1"}]` I get the following response `Request Error, Pleae look in your habridge log: error {"type":6,"address":"/lights/983837034","description":"Error on calling out to device","parameter":"/lights/983837034state"}` and it says in the log that `Could not execute request: C:\Home_Automation_Software\Harmony_Control\Scripts\Commands\test.ps1` Even though it is in the same folder as putty.exe and tv.bat.

Am I doing something wrong, or does it just not support launching other filetypes than *.exe?

I hope it is okay to post this, since I am unsure whether I am just stupid or there is an actual bug.

Best regards
JoeTN

**Comment by bwssytems** [comment]
Interesting... I haven't tested this extensively on windows to see if the Java execution environment needs more settings.. Will look into it more.

**Comment by JoeTN** [comment]
Aah okay. If you need help in testing changes etc. just let me know.

**Comment by bwssytems** [comment]
Found it for bat files 

from stackoverflow.com/questions/.../how-do-i-run-a-batch-file-from-my-java-application
"To run batch files using java if that's you're talking about... ProcessBuilder is the Java 5/6 way to run external processes. The executable used to run batch scripts is cmd.exe which uses the /c flag to specify the name of the batch file to run: Runtime.getRuntime().exec(new String[]{"cmd.exe", "/c", "build.bat"});"

**Comment by bwssytems** [comment]
It is the same for powershell as well.

You could try adding cmd.exe in front of the .bat file in your config and then put powershell.exe in front of your .ps file in the config.

**Comment by bwssytems** [comment]
So, the way the it is called in java, you would need to put cmd.exe in front of the bat file and powershell.exe in front of the .ps file in your exec description.

**Comment by JoeTN** [comment]
I can confirm it works that way with Powershell scripts. Just for others to know, my on/off now looks like this: [{"item":"powershell.exe C:\\Home_Automation_Software\\Harmony_Control\\Scripts\\Commands\\living_room_lights_on.ps1"}]

**Comment by bwssytems** [comment]
Glad that works! closing
