### ISSUE TITLE
Avoid 127.0.0.1 as the auto-detected address for upnp

### ISSUE THREAD

**Issue by jeffdoering** [bwssytems/ha-bridge#20]
While the upnp.config.address setting can be used to force a particular callback address for upnp; it would be nice if single address systems did not have to specify it explicitly. In particular; localhost (127.0.0.1) is almost never useful for upnp callbacks so it would be ideal to skip that during auto-detection. upnp.config.address could still be used explicitly to select 127.0.0.1 in exceptional cases where that is desired.

**Comment by bwssytems** [comment]
Sounds like a good validation to add. I assume you have had this happen? And if so, which OS's did it occur.

Thanks

**Comment by alexrudloff** [comment]
I've had it happen on my raspberry pi. Drove me crazy for a bit ;) 

pi@raspberrypi ~ $ uname -a
Linux raspberrypi 4.1.13+ #826 PREEMPT Fri Nov 13 20:13:22 GMT 2015 armv6l GNU/Linux

**Comment by jeffdoering** [comment]
Occurred for me in a FreeBSD Jail (freenas 9.3). ifconfig is also returning the loopback interface (lo0) first. The virtual nic "epair4b"  with the real IP address comes up second.
