### ISSUE TITLE
[feature request] add option to localise the url for "My Echo"

### ISSUE THREAD

**Issue by digiltd** [bwssytems/ha-bridge#202]
As the Echo is starting to become available in more countries, it would be helpful if the My Echo link at the top of the page pointed to the appropriate url.
- US = alexa.amazon.com  
- UK = alexa.amazon.co.uk  
- DE = alexa.amazon.de  

Not critical, but hopefuly you can squeeze it in at some point :)

Thanks

**Comment by bwssytems** [comment]
Just need to figure out a way to detect country.

**Comment by audiofreak9** [comment]
Without either determining the set localization of the machine or being able to determine the IP from an ISP, maybe just have a Bridge Control Page localization setting?

**Comment by digiltd** [comment]
Yeah, I actually forked the project with the intention to put something in the front end that would do it the fancy way. But after looking into it (for way too long that I should have) it seemed a lot of hard work, with some privacy issues that would need to be authorised by the user. Why punish ourselves when a field in the settings would achieve the same results :)

You could even future proof it by scraping the dropdown and simply have a text field for the user to paste in their relevant url.

**Comment by bwssytems** [comment]
I'll probably put in a setting in the config page
