### ISSUE TITLE
NEWBIE, Need help

### ISSUE THREAD

**Issue by ab1976** [bwssytems/ha-bridge#203]
Hello All,

I installed Alexa on my RPI3 and this all works fine, she is responding to my questions, but she is unable to discover my devices!

I installed habridge and added upnp.config.address
nohup java -jar -Djava.net.preferIPv4Stack=true /root/habridge/ha-bridge-3.2.0.j
ar upnp.address.config=192.168.1.96 > /root/habridge/habridge-log.txt 2>&1 &

In my windows environment I can see the upnp device, but alexa is unable to find it.

I created a test device within habridge but still no go, what is I do wrong, please help, thanks in advance

**Comment by bwssytems** [comment]
Use this command line: 

nohup java -jar -Djava.net.preferIPv4Stack=true /root/habridge/ha-bridge-3.2.0.j
ar  > /root/habridge/habridge-log.txt 2>&1 &

Then go into the web interface and set your upnp ip address to 192.168.1.96

**Comment by ab1976** [comment]
Tried this but again Alexa can not find any devices

T: upnp:rootdevice
MAN: "ssdp:discover"
User-Agent: UPnP/1.0 DLNADOC/1.50 Kodi
Connection: close
Host: 239.255.255.250:1900


2016-11-01 18:09:08,943 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - Traceupnp: sendUpnpResponse discovery responseTemplate1 is <<<HTTP/1.1 200 OK
HOST: 239.255.255.250:1900
CACHE-CONTROL: max-age=100
EXT:
LOCATION: http://192.168.1.96:80/description.xml
SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
hue-bridgeid: B827EBFFFEE7475B
ST: upnp:rootdevice
USN: uuid:2f402f80-da50-11e1-9b23-b827ebe7475b::upnp:rootdevice

>>>
2016-11-01 18:09:08,945 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - Traceupnp: sendUpnpResponse discovery responseTemplate2 is <<<HTTP/1.1 200 OK
HOST: 239.255.255.250:1900
CACHE-CONTROL: max-age=100
EXT:
LOCATION: http://192.168.1.96:80/description.xml
SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
hue-bridgeid: B827EBFFFEE7475B
ST: uuid:2f402f80-da50-11e1-9b23-b827ebe7475b
USN: uuid:2f402f80-da50-11e1-9b23-b827ebe7475b

>>>
2016-11-01 18:09:08,947 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - Traceupnp: sendUpnpResponse discovery responseTemplate3 is <<<HTTP/1.1 200 OK
HOST: 239.255.255.250:1900
CACHE-CONTROL: max-age=100
EXT:
LOCATION: http://192.168.1.96:80/description.xml
SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
hue-bridgeid: B827EBFFFEE7475B
ST: urn:schemas-upnp-org:device:basic:1
USN: uuid:2f402f80-da50-11e1-9b23-b827ebe7475b

>>>
2016-11-01 18:09:09,463 [qtp20483818-15] INFO  com.bwssystems.HABridge.upnp.UpnpSettingsResource - Traceupnp: upnp device settings requested:  from 192.168.1.24:80
2016-11-01 18:09:09,467 [qtp20483818-15] INFO  com.bwssystems.HABridge.upnp.UpnpSettingsResource - Traceupnp: upnp device settings template filled with address: 192.168.1.96 and port: 80

**Comment by bwssytems** [comment]
What is the ip of the Amazon Echo?

**Comment by ab1976** [comment]
It's running on the same Rpi, so it's also 192. 168.1.96




Mvg,
Alwin Bongers
Verzonden vanaf mijn Samsung Galaxy-smartphone.<div>
</div><div>
</div><div>-------- Oorspronkelijk bericht --------</div><div>Van: BWS Systems <notifications@github.com> </div><div>Datum: 01-11-16  19:26  (GMT+01:00) </div><div>Aan: bwssytems/ha-bridge <ha-bridge@noreply.github.com> </div><div>Cc: ab1976 <alwinbongers@hotmail.com>, Author <author@noreply.github.com> </div><div>Onderwerp: Re: [bwssytems/ha-bridge] NEWBIE, Need help (#203) </div><div>
</div>
What is the ip of the Amazon Echo?

**Comment by bwssytems** [comment]
Are you running the software alexa? If so, that does not discover deivces, you need a hardware echo or echo dot.

**Comment by ab1976** [comment]
It's software alexa
Thanks for your quick answers




Mvg,
Alwin Bongers
Verzonden vanaf mijn Samsung Galaxy-smartphone.<div>
</div><div>
</div><div>-------- Oorspronkelijk bericht --------</div><div>Van: BWS Systems <notifications@github.com> </div><div>Datum: 01-11-16  19:54  (GMT+01:00) </div><div>Aan: bwssytems/ha-bridge <ha-bridge@noreply.github.com> </div><div>Cc: ab1976 <alwinbongers@hotmail.com>, Author <author@noreply.github.com> </div><div>Onderwerp: Re: [bwssytems/ha-bridge] NEWBIE, Need help (#203) </div><div>
</div>
Are you running the software alexa? If so, that does not discover deivces, you need a hardware echo or echo dot.

**Comment by bwssytems** [comment]
Yep, that does not work for home automation control. Sorry.
