### ISSUE TITLE
ha-bridge does not work reliably with multiple Amazon Echo's

### ISSUE THREAD

**Issue by ov3rmind** [bwssytems/ha-bridge#205]
ha-bridge is not working reliably with multiple Amazon Echo's or Dots. Worked 100% reliably with a single Amazon Echo.  Having multiple "Alexas"results in roughly 50% of commands being delayed anywhere by 5-15 seconds, 20% of commands failing to process entirely, and 30% going through OK.  I originally had only one amazon echo and added 5 echo dots -- started having bad results immediately.  Reduced it to 2 echo dots only and the results were still the same.  If only one Alexa is on the network, results are instant and perfect.  All commands test instantly via ha-bridge interface "test on"/"test off" buttons and also via Vera controller. 
Examples of inconsistent results:
Scenario 1: "Alexa, turn off kitchen lights"  10 second delay, Alexa responds "The device or group name Kitchen Lights is not responding at the moment", then after 5 seconds the lights turn off.  
Scenario 2:  "Alexa, turn off kitchen lights"  15 second delay, then Alexa responds "Something went wrong"'
Scenario 3:  "Alexa, turn on kitchen lights"   20 second delay, then lights turn on and Alexa says "OK"
Scenario 4:  "Alexa, turn on kitchen lights"  1 second delay, lights turn on, Alexa says "OK" 

What kind of logging can I help generate?

**Comment by lonebaggie** [comment]
Running with an Echo and a one Dot. No issues. HA-Bridge  running on Raspberry PI model 1 working with Lightwaverf switches and Harmony Hub

**Comment by ov3rmind** [comment]
In an act of desperation, I ditched auto-issued DNS servers from Verizon FIOS on my main router and switched over to ones recommended by opendns: https://support.opendns.com/hc/en-us/articles/228008607

So far devices have been responding instantly, and I've had 1 echo, 1 dot gen 1, and 5 dots gen 2 online with no issues.  Could be a coincidence, or could be bad DNS servers from verizon not mapping correctly to the amazon cloud.  Will report back after more testing.

**Comment by ov3rmind** [comment]
The above was a coincidence.  I added 6 echo dots back online and severe delays are back.. New to the mix is Alexa now saying "I'm not quite sure how to help you with that", then the lights turn on after 15 seconds.  The only reason I think it has something to do with ha-bridge only is because alexa responds to other home automation commands instantly, such as TP link wifi lamp controllers and all harmony activities.  Is there any logging that can help here?

**Comment by bwssytems** [comment]
This is interesting as it seems that there is an issue routing. Does everything on your network go through the FIOS home router? Or do you have your own?

**Comment by ov3rmind** [comment]
Yes, FIOS router is the main and only active router in my network.  I have a managed (netgear prosafe 48port) switch on top of it and a (ubiquiti unifi ac AC pro ) WIFI AP on top of that... All with DHCP and routing turned off.

**Comment by bwssytems** [comment]
Do use ACLs on your netgear switch?

**Comment by ov3rmind** [comment]
Nope.  I don't have any ACLs configured.  It's on a default setting.

**Comment by ov3rmind** [comment]
Now this is really strange.  Looking at the logs, sometimes requests seem to originate from the wrong IP.  

First, if I ask the echo dot closest to me (with IP ending in .27) to turn off "Island Light" I see something that looks like is coming from the correct IP address: 
```

11-02-2016 21:12:24.235 	DEBUG 	hue light requested: 8 for user: UxidyZH8A7ySLbZg2GuKxPafd1wNVkHbvsblQ3GR from 192.168.1.27 	com.bwssystems.HABridge.hue.HueMulator
11-02-2016 21:12:24.235 	DEBUG 	found device named: Island Light 	com.bwssystems.HABridge.hue.HueMulator
11-02-2016 21:18:09.685 	DEBUG 	hue state change requested: UxidyZH8A7ySLbZg2GuKxPafd1wNVkHbvsblQ3GR from 192.168.1.27 body: {"on": false} 	com.bwssystems.HABridge.hue.HueMulator
11-02-2016 21:18:09.691 	DEBUG 	executing HUE api request for network call: http://192.168.1.195:3480/data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:SwitchPower1&action=SetTarget&newTargetValue=0&DeviceNum=97 	com.bwssystems.HABridge.hue.HueMulator
11-02-2016 21:18:09.694 	DEBUG 	executing HUE api request to Http GET: http://192.168.1.195:3480/data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:SwitchPower1&action=SetTarget&newTargetValue=0&DeviceNum=97 	com.bwssystems.HABridge.hue.HueMulator
11-02-2016 21:18:09.696 	DEBUG 	Making outbound call in doHttpRequest: GET http://192.168.1.195:3480/data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:SwitchPower1&action=SetTarget&newTargetValue=0&DeviceNum=97 HTTP/1.1 	com.bwssystems.HABridge.hue.HueMulator
11-02-2016 21:18:09.710 	DEBUG 	GET execute on URL responded: 200 	com.bwssystems.HABridge.hue.HueMulator
11-02-2016 21:18:09.801 	DEBUG 	hue light requested: 8 for user: UxidyZH8A7ySLbZg2GuKxPafd1wNVkHbvsblQ3GR from 192.168.1.27 	com.bwssystems.HABridge.hue.HueMulator
11-02-2016 21:18:09.802 	DEBUG 	found device named: Island Light 	com.bwssystems.HABridge.hue.HueMulator

```

Then I ask the same Echo dot to "Turn on Kitchen Lights" (yes my "on" command is a scene -- I was testing because scenes seemed to work much more reliably)

Look at the origin IP -- its .212 -- an Echo that's in a nearby room, even though its not the echo dot that listens to my command or responds "OK" at the end. 
```

11-02-2016 21:18:19.913 	DEBUG 	hue state change requested: UxidyZH8A7ySLbZg2GuKxPafd1wNVkHbvsblQ3GR from 192.168.1.212 body: {"on": true} 	com.bwssystems.HABridge.hue.HueMulator
11-02-2016 21:18:19.917 	DEBUG 	executing HUE api request for network call: http://192.168.1.195:3480/data_request?id=action&output_format=json&serviceId=urn:micasaverde-com:serviceId:HomeAutomationGateway1&action=RunScene&SceneNum=24 	com.bwssystems.HABridge.hue.HueMulator
11-02-2016 21:18:19.918 	DEBUG 	executing HUE api request to Http GET: http://192.168.1.195:3480/data_request?id=action&output_format=json&serviceId=urn:micasaverde-com:serviceId:HomeAutomationGateway1&action=RunScene&SceneNum=24 	com.bwssystems.HABridge.hue.HueMulator
11-02-2016 21:18:19.919 	DEBUG 	Making outbound call in doHttpRequest: GET http://192.168.1.195:3480/data_request?id=action&output_format=json&serviceId=urn:micasaverde-com:serviceId:HomeAutomationGateway1&action=RunScene&SceneNum=24 HTTP/1.1 	com.bwssystems.HABridge.hue.HueMulator
11-02-2016 21:18:19.931 	DEBUG 	GET execute on URL responded: 200 	com.bwssystems.HABridge.hue.HueMulator
11-02-2016 21:18:20.041 	DEBUG 	hue light requested: 3 for user: UxidyZH8A7ySLbZg2GuKxPafd1wNVkHbvsblQ3GR from 192.168.1.212 	com.bwssystems.HABridge.hue.HueMulator
11-02-2016 21:18:20.042 	DEBUG 	found device named: Kitchen Lights 	com.bwssystems.HABridge.hue.HueMulator


```

I ask the same Echo Dot to turn it off, again it turns off but request originates from a different IP.  Somehow it still works and she says "OK". 
```

11-02-2016 21:18:47.099 	DEBUG 	hue state change requested: UxidyZH8A7ySLbZg2GuKxPafd1wNVkHbvsblQ3GR from 192.168.1.212 body: {"on": false} 	com.bwssystems.HABridge.hue.HueMulator
11-02-2016 21:18:47.103 	DEBUG 	executing HUE api request for network call: http://192.168.1.195:3480/data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:SwitchPower1&action=SetTarget&newTargetValue=0&DeviceNum=87 	com.bwssystems.HABridge.hue.HueMulator
11-02-2016 21:18:47.111 	DEBUG 	executing HUE api request to Http GET: http://192.168.1.195:3480/data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:SwitchPower1&action=SetTarget&newTargetValue=0&DeviceNum=87 	com.bwssystems.HABridge.hue.HueMulator
11-02-2016 21:18:47.112 	DEBUG 	Making outbound call in doHttpRequest: GET http://192.168.1.195:3480/data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:SwitchPower1&action=SetTarget&newTargetValue=0&DeviceNum=87 HTTP/1.1 	com.bwssystems.HABridge.hue.HueMulator
11-02-2016 21:18:47.123 	DEBUG 	GET execute on URL responded: 200 	com.bwssystems.HABridge.hue.HueMulator
11-02-2016 21:18:47.229 	DEBUG 	hue light requested: 3 for user: UxidyZH8A7ySLbZg2GuKxPafd1wNVkHbvsblQ3GR from 192.168.1.212 	com.bwssystems.HABridge.hue.HueMulator
11-02-2016 21:18:47.229 	DEBUG 	found device named: Kitchen Lights
```

Could this have anything to do with the inconsistent behavior and spotty delays I'm experiencing ? Can this be caused by bad routing, bad Alexa protocols, or something in ha-bridge?

**Comment by bwssytems** [comment]
So, do you fix your ip's to your devices or do you let dhcp give out ip's. That could be an issue.

**Comment by ov3rmind** [comment]
I made them static.

**Comment by bwssytems** [comment]
Hmmm, hive minds with the echo?

**Comment by tracstarr** [comment]
I have 3 2nd gen dots. I've always had 3 connected and have experienced both instant response (with lights turned on or off) and delayed responses of 5-10 seconds without Alexa responding with "ok". The response is maybe 50% of the time. I've not looked at any logs, but I can help provide any information from my setup if it's possibly useful.

**Comment by bwssytems** [comment]
So, a couple of things here, is there any other application on the server that is running the ha-bridge? If the calling system from the ha-bridge is slow, so will it's response to the echo and you will get the took to long to respond from the echo.

**Comment by ov3rmind** [comment]
Not in my case.  In fact, I had this running on a Pi B+ and upgraded to a dedicated Pi 3 -- running ha-bridge only.  When I test on/off commands via ha-bridge interface, they are always 100% instant.

**Comment by bwssytems** [comment]
That is a good thing. Ruling out the ha-bridge and now onto network and multiple echo issues. With what you are saying, it is looking like the multiple echos are finding each other using them to proxy the others. This will be difficult to solve as it is an amazon implementation.

**Comment by ov3rmind** [comment]
Agree.  The strange part is that devices like Harmony and TP Link wifi smart plugs work with multiple echos instantly.  It's some combination of amazon implementation and how it deals with the hue protocol it seems.

**Comment by bwssytems** [comment]
Closing as this is not an ha-bridge issue.

**Comment by dsohgithub** [comment]
@ov3rmind - did you ever come up with a solution to this issue on the echo end? I am having a similar issue on my setup.

**Comment by ov3rmind** [comment]
@dsohgithub - I contacted amazon echo dev team about this issue who said they'd look into it.  They never got back to me but about a week later the issues went away on their own.  I have no idea if Amazon fixed something or if the problem was elsewhere.  All I can say is that I have 7 Alexa devices right now working with ha-bridge flawlessly.

**Comment by dsohgithub** [comment]
@ov3rmind - I had a similar experience with the problem just going away. I suppose it was something on their app/server send that they fixed. Mine is working correctly now as well (with 7 Dots and a Fire).

**Comment by Jinsterrrr** [comment]
You guys are lucky. I have 4 dots and 2 originals. Exactly the same issue as you described - Echo often responds with "ok" but doesn't actually turn on my Milight. This happens 60% of the time. Whereas pushing the "on" button in the web interface triggers Milight instantly and 100% of the time.
