### ISSUE TITLE
Vera adding not working

### ISSUE THREAD

**Issue by jheizer** [bwssytems/ha-bridge#208]
Attempting to add vera running UI7 to a new deploy of 3.2.0 after saving no vera tabs were added across the top of the page.  Nothing in the log seemed to indicate an error had occurred.  Downgraded to 3.1.0 and on first start the vera was located.

**Comment by bwssytems** [comment]
That is interesting as the vera tabs are controlled by having a vera address in the configuration in the bridge control tab.

**Comment by bwssytems** [comment]
There is no difference between 3.2.1 and 3.1.0 on how the ha-bridge talks to the vera. Have you tried it again?

**Comment by jheizer** [comment]
I was setting it up for a no tech friend over a shared screen so I don't have access to it anymore.  I had just happen to have played with it locally before hand at which point I noticed I had an older version than they had and decided to give that a try and it worked.
