### ISSUE TITLE
Multi / Batch URL generation and Add to Configuration

### ISSUE THREAD

**Issue by Ltek** [bwssytems/ha-bridge#21]
Vera Suggestion... Multi / Batch URL generation and Add to Configuration : Check Box style method for automatically generating URLs, naming them (using the same name that is in Vera) and add selected into the Configuration.

**Comment by bwssytems** [comment]
I have had this request before. It is not straight forward with the selections and makes the gui very distracting. I'll think about it. It also has some issues for the user as they have to see if the names will clash and then if you want dimming control, you have to back and edit it by hand,

**Comment by Ltek** [comment]
I understand your points... I suggest making all the options available to set on the batch. Thus, if someone wants to batch add 10 dimmers, they can check the box for each device, select the dim option they want (yes all 10 would be the same) and click 'set' ... this is how I've seen most GUIs do batch. The naming would just be set as it is named in Vera, they would not have a choice... but it is unlikely users would change many names - most of us would want to have them be the same as in the Vera GUI for consistency... and it is easier to remember what is what that way too. It is unlikely people would have two devices in Echo named "Kitchen Lights" :)

**Comment by bwssytems** [comment]
Will try for this in a future release.
