### ISSUE TITLE
Delay between button commands

### ISSUE THREAD

**Issue by lemked** [bwssytems/ha-bridge#211]
Hi there,

first of all, thanks for this great piece of software. It works like a charm on my raspberry pie 2 so far. One thing that I'm missing currently is the ability to declare a delay between Harmony button commands that are sent by the bridge. I know that activities should normally be used to accomplish such things, but for a specific case I'd like to use buttons instead.

I was thinking on something like this:
`[{"device":"22910352","button":"7"},{"device":"-1","delay":"5000"},{"device":"22910352","button":"InputHdmi4"},{"device":"-1","delay":"2000"},{"device":"22910352","button":"Select"}]`

**Comment by bwssytems** [comment]
It is an overall setting in the bridge control tab currently "Button Press/Call Item Loop Sleep Interval (ms)" it is set to 100ms by default.

**Comment by lemked** [comment]
Great, thanks!
