### ISSUE TITLE
ha-bridge exits/crashes with UPNP Discovery Listener error after random amount of time 

### ISSUE THREAD

**Issue by nickmig** [bwssytems/ha-bridge#212]
Octopi/Raspian on RPI3 started on boot via systemctl or just launched separately. This also had the same issue with the previous version. This may work for days at a time and then the ha-bridge goes offline. Here are the errors I'm getting in the systemctl status. I'm launching ha-bridge via a different port 8081 if that makes any difference. Any suggestions? Thank you!!

Nov 01 20:00:36 octopi java[694]: at java.net.DatagramSocket.send(DatagramSocket.java:693)
Nov 01 20:00:36 octopi java[694]: at com.bwssystems.util.UDPDatagramSender.sendUDPResponse(UDPDatagramSender.java:70)
Nov 01 20:00:36 octopi java[694]: at com.bwssystems.HABridge.upnp.UpnpListener.sendUpnpResponse(UpnpListener.java:215)
Nov 01 20:00:36 octopi java[694]: at com.bwssystems.HABridge.upnp.UpnpListener.startListening(UpnpListener.java:127)
Nov 01 20:00:36 octopi java[694]: at com.bwssystems.HABridge.HABridge.main(HABridge.java:94)
Nov 01 20:00:37 octopi java[694]: 2016-11-01 20:00:37,954 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener - ended, error found
Nov 01 20:00:38 octopi java[694]: 2016-11-01 20:00:38,026 [main] INFO  spark.webserver.JettySparkServer - >>> Spark shutting down ...
Nov 01 20:00:38 octopi java[694]: 2016-11-01 20:00:38.039:INFO:oejs.ServerConnector:main: Stopped ServerConnector@1c04a3e{HTTP/1.1,[http/1.1]}{0.0.0.0:8081}
Nov 01 20:00:38 octopi java[694]: 2016-11-01 20:00:38,043 [main] INFO  spark.webserver.JettySparkServer - done
Nov 01 20:00:38 octopi java[694]: 2016-11-01 20:00:38,046 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v3.2.0) exiting....

**Comment by bwssytems** [comment]
I would like to see the rest of the exception error message, but I am assuming you had a upnp response error that it marked as a serious error. The latest version, v3.2.1, now just warns on these errors.

**Comment by nickmig** [comment]
Hrrm - That's all I could grab using systemctl status habridge -L. Can you point me to log data for that and I will try and pull?

Thanks!

**Comment by bwssytems** [comment]
The log messages are in/var/log/syslog and you can grep that for the "bwssystems" and you should get all the messages. Also, with v3.2.1 I believe you will not have this issue.
