### ISSUE TITLE
SyntaxError: Unexpected token in JSON at position 2941 

### ISSUE THREAD

**Issue by heffneil** [bwssytems/ha-bridge#213]
When clicking update log using Chrome Version 54.0.2840.71 (64-bit) I get this JSON error.  I previously attempted to enabled Trace on the com.bwssystems.HABridge.HABridge log but the best I could get it to save was Info.  Pressing the Update Log button replicates this warning.

**Comment by bwssytems** [comment]
I cannot replicate this. Where does this error present itself? On the broswer window? as a popup?

**Comment by heffneil** [comment]
Thanks,

Neil H.

**Comment by bwssytems** [comment]
Still wondering where the error was presented, as a browser error or a log error?

**Comment by heffneil** [comment]
I gave you screen shot in the browser.  DId you not get it?

Thanks,

Neil H.

**Comment by bwssytems** [comment]
Replying to the github messages probably drops any attachments. You'll have to upload it on the github issue page.

**Comment by bwssytems** [comment]
Is your bridge working? Are you relieving this error still?

**Comment by heffneil** [comment]
Seems ok?

Thanks,

Neil H.
