### ISSUE TITLE
Echo Dot not discovering HA bridge on Windows 10 PC

### ISSUE THREAD

**Issue by TJLY** [bwssytems/ha-bridge#215]
HI, sorry for another tedious problem with Alexa (on a new Echo Dot) not being able to discover any devices.

I have a Window 10 PC running the 3.2.1 version of the bridge using this command:

`java -jar -Dserver.port=81 -Djava.net.preferIPv4Stack=true ha-bridge-3.2.1.jar`

Once it's running I can use the UI which works fine. But Alexa does not discover anything after I add a first device.  (I had the same problem with similar [code from Armzilla](https://github.com/armzilla/amazon-echo-ha-bridge)).

I have tried restarting the Echo Dot and turning off the Windows firewall but no joy.

Any ideas anyone?

Thanks - Tim

**Comment by bwssytems** [comment]
In the UI, make sure that the upnp ip address is set to the host windows 10 ip address. Also, you can turn on trace upnp to see if your echo requests info from the bridge. You will need the ip of your echo to determine this from the logs.

**Comment by TJLY** [comment]
Thanks for coming back to me so soon.  I have a home network that has a couple of switches and three wifi access points.  To get it working I had to connect the PC running HA Bridge directly to the main router and the Echo Dot to it as well (by wifi).  The Echo then found the HA Bridge no problem.  After adding and discovering all my devices I went back to the previous setup and it all still works.

**Comment by bwssytems** [comment]
Glad it works.
