### ISSUE TITLE
Unable to link HA-Bridge to Openhab

### ISSUE THREAD

**Issue by Chanete** [bwssytems/ha-bridge#217]
Hi, I've set up an HA-Bridge to control a couple things with Alexa and it works perfect!! 

Now I want to have a mobile app to control the same things. 

I've tried to discover HA-Bridge with the HUE official app but it doesn't show up. There no way to "press the HUE button"  

Next thing I've tried is to link HA-Bridge to Openhab and I end up in the same situation. This is the error  in OPenhab log which relates to the same thing "Press the button"

[binding.hue.handler.HueBridgeHandler] - Failed creating new user on Hue bridge
java.io.IOException: Server returned HTTP response code: 401 for URL: http://192.168.1.246/api/

How can I "Press the button" on HA-Bridge

Thx

**Comment by bwssytems** [comment]
That is interesting as the ha-bridge is n a mode "button presses" always. There maybe a first time priming issue here, when you get that message, have Openhab rediscover the bridge again.

**Comment by audiofreak9** [comment]
I'm assuming the answer is yes but, make sure your bridge using port 80 rather that something else.

**Comment by Chanete** [comment]
Rediscovering with openhab didn't solve it. 

I'm not running ha-bridge on port 80 because I'm running a webserver in the same machine, so I've create a new ethernet (eth0:0) with a different IP. I've configured apache to bind only in one of the IP's, but I'm unable to configure ha-bridge to bind only in one IP, it always bind to 0.0.0.0:80 which, in my case, fails because apache is using port 80 in one of the interfaces.

How can I change ha-bridge to bind only to one IP??

thx

**Comment by audiofreak9** [comment]
Add 
`-Dserver.port=8080` 
(or whatever port you choose) to the startup command.

**Comment by audiofreak9** [comment]
I too am running an Apache webserver on my RPi and bound it to a different port (8080), because most other applications expect port 80 when connecting to a Hue Bridge.

**Comment by Chanete** [comment]
thx for your prompt answer, but that changes the port, but not the IP to which ha-bridge bind the service. 

I want to keep my web server in port 80, so users don't have to write the port, thats way I've setup a new interface (eth0:0) but I need to know how to tell HA-bridge to bind to that new interface instead of binding to all interfaces as it does now

WHen I start ha-bridge it says: 
[Thread-0] INFO  spark.webserver.JettySparkServer - >> Listening on **0.0.0.0:8080**

I need it to say 
[Thread-0] INFO  spark.webserver.JettySparkServer - >> Listening on **192.168.1.245;80**

using -Dserver.port only changes the port part of the binding.

**Comment by bwssytems** [comment]
Got it, I'll need to put the web server specific address setting.
