### ISSUE TITLE
Unable to link HA Bridge to Logitech Hub 

### ISSUE THREAD

**Issue by memojo** [bwssytems/ha-bridge#218]
Hi!

Ich have read a lot posts saying that i just have to try again and again. I did this for days now - but it is not pissible to link them. It says that i have to push the link button. I tried restarting everything but it did not help. Linking with Domoticz works (even with empty username)! It seems linke this is the same problem linke the poste below saying that its not possitble to link with Openhab? I also played around with the setting "linkbutton" but it did not help either...

Thank you for your efforts. HA bridge has a great userinterface!

Version: 3.2.1 & 1.3.7 tested
![img_8352](https://cloud.githubusercontent.com/assets/20846958/20017136/966121ee-a2c2-11e6-8c09-d97aec49d478.PNG)

**Comment by bwssytems** [comment]
So, the ha-bridge is in a mode that the button is always pressed, you may need to do the discovery twice from your system you are trying to link to.

**Comment by memojo** [comment]
Thank you for your immediate feedback. I tried it several times but it remained like that. Now it magically works. For those experiencing the same problem here is what i changed since it did not work: in the logitech harmony app i chose to discover "Hunter Douglas Powerview HUB". The I tried to discover the Philips hue Hub again. It seems to be problem with the logitech software!

**Comment by klein0r** [comment]
@memojo It's totally strange! I've encountered the same problem and tried the pairing a 100 times! After discovering (non existent) "Hunter Douglas" devices, the next try to pair hue worked like charm. Thanks a lot for this workaround hint :) 👍

**Comment by ngodfriedt** [comment]
Unfortunately this workaround doesn't work for me. I always get the pair hue screen.

**Comment by bwssytems** [comment]
@ngodfriedt What version of the ha-bridge are you using?

**Comment by ngodfriedt** [comment]
@bwssytems I'm on version 5.1.0. I'm running it on port 3000, can this have to do with it?

**Comment by bwssytems** [comment]
It maybe setup with docker. Look at issues in the ha-bridge docker github site.

**Comment by ngodfriedt** [comment]
For prosperity: I managed to resolve my issue by running the docker in privilige mode.

**Comment by bwssytems** [comment]
It must have failed startup using port 80 then.

**Comment by schaaff** [comment]
Same here. I couldn't pair with the HA-bridge until I intermittently looked for "Hunter Douglas" devices, back to search for a Hue Hub and et voila! Thanks for the comments here!
