### ISSUE TITLE
ERRORS in log: spark.webserver.MatcherFilter

### ISSUE THREAD

**Issue by paulhemels** [bwssytems/ha-bridge#219]
What does this error mean: spark.webserver.MatcherFilter
There are 3 of them in a minute :(

**Comment by bwssytems** [comment]
Could you post the log please, need some context as those are statements from the internal web server.

**Comment by paulhemels** [comment]
Is this OK?

11-04-2016 18:00:05.379	ERROR		spark.webserver.MatcherFilter
11-04-2016 18:00:06.561	ERROR		spark.webserver.MatcherFilter
11-04-2016 18:00:07.729	ERROR		spark.webserver.MatcherFilter
11-04-2016 18:00:27.579	INFO	UPNP Discovery Listener - ended, restart found	com.bwssystems.HABridge.upnp.UpnpListener
11-04-2016 18:00:27.580	INFO	HA Bridge (v3.2.0) reinitialization requessted....	com.bwssystems.HABridge.HABridge
11-04-2016 18:00:27.592	INFO	>>> Spark shutting down ...	spark.webserver.JettySparkServer
11-04-2016 18:00:27.604	INFO	done	spark.webserver.JettySparkServer
11-04-2016 18:00:27.606	INFO	reading from config file: /usr/local/habridge/data/habridge.config	com.bwssystems.HABridge.BridgeSettings
11-04-2016 18:00:27.614	INFO	HA Bridge (v3.2.0) initializing....	com.bwssystems.HABridge.HABridge
11-04-2016 18:00:27.617	INFO	System control service started....	com.bwssystems.HABridge.SystemControl
11-04-2016 18:00:27.620	INFO	== Spark has ignited ...	spark.webserver.JettySparkServer
11-04-2016 18:00:27.621	INFO	>> Listening on 0.0.0.0:80	spark.webserver.JettySparkServer
11-04-2016 18:00:27.635	INFO	setup initiated ....	com.bwssystems.harmony.HarmonyServer
11-04-2016 18:00:29.972	INFO	activity changed: [-1] PowerOff	com.bwssystems.harmony.HarmonyServer
11-04-2016 18:00:29.978	INFO	HABridge device management service started....	com.bwssystems.HABridge.devicemanagmeent.DeviceResource
11-04-2016 18:00:29.980	INFO	Hue description service started....	com.bwssystems.HABridge.upnp.UpnpSettingsResource
11-04-2016 18:00:29.981	INFO	Initializing UDP response Seocket...	com.bwssystems.util.UDPDatagramSender
11-04-2016 18:00:29.981	INFO	UDP response Seocket initialized to: 50000	com.bwssystems.util.UDPDatagramSender
11-04-2016 18:00:30.013	INFO	Hue emulator service started....	com.bwssystems.HABridge.hue.HueMulator
11-04-2016 18:00:30.015	INFO	UPNP Discovery Listener starting....	com.bwssystems.HABridge.upnp.UpnpListener
11-04-2016 18:00:30.017	INFO	UPNP Discovery Listener running and ready....	com.bwssystems.HABridge.upnp.UpnpListener
11-04-2016 18:02:14.401	ERROR		spark.webserver.MatcherFilter
11-04-2016 18:02:15.571	ERROR		spark.webserver.MatcherFilter
11-04-2016 18:02:16.738	ERROR		spark.webserver.MatcherFilter
11-04-2016 18:03:18.083	ERROR		spark.webserver.MatcherFilter

**Comment by bwssytems** [comment]
It just means that something is calling your bridge with a request it doesn't understand. Hopefully nothing is trying to hack it.

**Comment by paulhemels** [comment]
I will change the web server port, maybe that helps :)
Do you know why, my Harmony Hub only see 3 devices, there are 10 devices in the HA-Bridge!

**Comment by paulhemels** [comment]
Change the webserver port doesn't help :(

**Comment by bwssytems** [comment]
The most helpful logger would be setting DEBUG for com.bwssystems.HABridge.hue.HueMulator component. Changing this and then selecting the Update Log Levels button applies the new log settings.

**Comment by paulhemels** [comment]
Here it is:

11-04-2016 19:01:29.714	ERROR		spark.webserver.MatcherFilter
11-04-2016 19:01:30.929	ERROR		spark.webserver.MatcherFilter
11-04-2016 19:06:52.267	WARN	Send heartbeat failed	net.whistlingfish.harmony.HarmonyClient
11-04-2016 19:07:22.271	WARN	Send heartbeat failed	net.whistlingfish.harmony.HarmonyClient
11-04-2016 19:07:52.274	WARN	Send heartbeat failed	net.whistlingfish.harmony.HarmonyClient
11-04-2016 19:08:12.745	DEBUG	isSSDPDiscovery Found message to be an M-SEARCH message.	com.bwssystems.HABridge.upnp.UpnpListener
11-04-2016 19:08:12.746	DEBUG	isSSDPDiscovery Got SSDP packet from 192.168.0.147:60804, body: M-SEARCH * HTTP/1.1
 HOST: 239.255.255.250:1900
 MAN: "ssdp:discover"
 MX: 1
 ST: urn:dial-multiscreen-org:service:dial:1
 USER-AGENT: Google Chrome/54.0.2840.71 Windows
 
	com.bwssystems.HABridge.upnp.UpnpListener
11-04-2016 19:08:13.746	DEBUG	isSSDPDiscovery Found message to be an M-SEARCH message.	com.bwssystems.HABridge.upnp.UpnpListener
11-04-2016 19:08:13.747	DEBUG	isSSDPDiscovery Got SSDP packet from 192.168.0.147:60804, body: M-SEARCH * HTTP/1.1
 HOST: 239.255.255.250:1900
 MAN: "ssdp:discover"
 MX: 1
 ST: urn:dial-multiscreen-org:service:dial:1
 USER-AGENT: Google Chrome/54.0.2840.71 Windows
 
	com.bwssystems.HABridge.upnp.UpnpListener
11-04-2016 19:08:14.746	DEBUG	isSSDPDiscovery Found message to be an M-SEARCH message.	com.bwssystems.HABridge.upnp.UpnpListener
11-04-2016 19:08:14.747	DEBUG	isSSDPDiscovery Got SSDP packet from 192.168.0.147:60804, body: M-SEARCH * HTTP/1.1
 HOST: 239.255.255.250:1900
 MAN: "ssdp:discover"
 MX: 1
 ST: urn:dial-multiscreen-org:service:dial:1
 USER-AGENT: Google Chrome/54.0.2840.71 Windows
 
	com.bwssystems.HABridge.upnp.UpnpListener
11-04-2016 19:08:15.752	DEBUG	isSSDPDiscovery Found message to be an M-SEARCH message.	com.bwssystems.HABridge.upnp.UpnpListener
11-04-2016 19:08:15.752	DEBUG	isSSDPDiscovery Got SSDP packet from 192.168.0.147:60804, body: M-SEARCH * HTTP/1.1
 HOST: 239.255.255.250:1900
 MAN: "ssdp:discover"
 MX: 1
 ST: urn:dial-multiscreen-org:service:dial:1
 USER-AGENT: Google Chrome/54.0.2840.71 Windows
 
	com.bwssystems.HABridge.upnp.UpnpListener
11-04-2016 19:08:16.881	DEBUG	isSSDPDiscovery Found message to be an M-SEARCH message.	com.bwssystems.HABridge.upnp.UpnpListener
11-04-2016 19:08:16.882	DEBUG	isSSDPDiscovery Got SSDP packet from 192.168.0.155:2048, body: M-SEARCH * HTTP/1.1
 HOST: 239.255.255.250:1900
 MAN: "ssdp:discover"
 MX: 5
 ST: upnp:rootdevice
 
	com.bwssystems.HABridge.upnp.UpnpListener
11-04-2016 19:08:16.882	DEBUG	isSSDPDiscovery found message to be valid under strict rules - strict: true	com.bwssystems.HABridge.upnp.UpnpListener
11-04-2016 19:08:16.884	DEBUG	sendUpnpResponse discovery responseTemplate1 is <<<HTTP/1.1 200 OK
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 EXT:
 LOCATION: http://192.168.0.151:8090/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 hue-bridgeid: B827EBFFFEEE1C4B
 ST: upnp:rootdevice
 USN: uuid:2f402f80-da50-11e1-9b23-b827ebee1c4b::upnp:rootdevice
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener
11-04-2016 19:08:16.884	DEBUG	Sending response string: <<<HTTP/1.1 200 OK
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 EXT:
 LOCATION: http://192.168.0.151:8090/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 hue-bridgeid: B827EBFFFEEE1C4B
 ST: upnp:rootdevice
 USN: uuid:2f402f80-da50-11e1-9b23-b827ebee1c4b::upnp:rootdevice
 
 >>>	com.bwssystems.util.UDPDatagramSender
11-04-2016 19:08:16.885	DEBUG	sendUpnpResponse discovery responseTemplate2 is <<<HTTP/1.1 200 OK
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 EXT:
 LOCATION: http://192.168.0.151:8090/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 hue-bridgeid: B827EBFFFEEE1C4B
 ST: uuid:2f402f80-da50-11e1-9b23-b827ebee1c4b
 USN: uuid:2f402f80-da50-11e1-9b23-b827ebee1c4b
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener
11-04-2016 19:08:16.889	DEBUG	Sending response string: <<<HTTP/1.1 200 OK
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 EXT:
 LOCATION: http://192.168.0.151:8090/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 hue-bridgeid: B827EBFFFEEE1C4B
 ST: uuid:2f402f80-da50-11e1-9b23-b827ebee1c4b
 USN: uuid:2f402f80-da50-11e1-9b23-b827ebee1c4b
 
 >>>	com.bwssystems.util.UDPDatagramSender
11-04-2016 19:08:16.890	DEBUG	sendUpnpResponse discovery responseTemplate3 is <<<HTTP/1.1 200 OK
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 EXT:
 LOCATION: http://192.168.0.151:8090/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 hue-bridgeid: B827EBFFFEEE1C4B
 ST: urn:schemas-upnp-org:device:basic:1
 USN: uuid:2f402f80-da50-11e1-9b23-b827ebee1c4b
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener
11-04-2016 19:08:16.890	DEBUG	Sending response string: <<<HTTP/1.1 200 OK
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 EXT:
 LOCATION: http://192.168.0.151:8090/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 hue-bridgeid: B827EBFFFEEE1C4B
 ST: urn:schemas-upnp-org:device:basic:1
 USN: uuid:2f402f80-da50-11e1-9b23-b827ebee1c4b
 
 >>>	com.bwssystems.util.UDPDatagramSender
11-04-2016 19:08:16.963	DEBUG	httpMethod:get, uri: /description.xml	spark.webserver.MatcherFilter
11-04-2016 19:08:16.964	DEBUG	get params	spark.Request
11-04-2016 19:08:16.964	DEBUG	get splat	spark.Request
11-04-2016 19:08:16.965	DEBUG	upnp device settings requested: from 192.168.0.155:8090	com.bwssystems.HABridge.upnp.UpnpSettingsResource
11-04-2016 19:08:16.967	DEBUG	Traceupnp: upnp device settings template filled with address: 192.168.0.151 and port: 8090	com.bwssystems.HABridge.upnp.UpnpSettingsResource
11-04-2016 19:08:19.361	DEBUG	httpMethod:get, uri: /system/logmsgs	spark.webserver.MatcherFilter
11-04-2016 19:08:19.362	DEBUG	get params	spark.Request
11-04-2016 19:08:19.363	DEBUG	get splat	spark.Request
11-04-2016 19:08:19.363	DEBUG	Get logmsgs.	com.bwssystems.HABridge.SystemControl

**Comment by bwssytems** [comment]
Everything there looks good. Is it working for you?

**Comment by paulhemels** [comment]
At the moment my Harmony Hub doesn't see the devices that are in the HA bridge, this morning he saw 3 of the 10.
When I use the buttons on the device in the HA bridge it works well.

**Comment by bwssytems** [comment]
What is your intent? For the harmony to control the ha-bridge OR For an Echo to control the Harmony Hub through the ha-bridge.

**Comment by paulhemels** [comment]
My intentie is to control the HA-bridge with the harmony.
Then the HA-bridge sent a Jhon command to HomeSeer.

Op vrijdag 4 november 2016 heeft BWS Systems <notifications@github.com> het
volgende geschreven:

**Comment by bwssytems** [comment]
So, let's do a couple of things. !) Remove the config for the harmony hub in the ha-bridge config - this is not needed. 2) Change your port for the ha-bridge to be 80.

**Comment by paulhemels** [comment]
I have doen the 2 steps, when i try to get new hue device from the
HA-bridge, i get the mesage unable to get new devices.
I wil try again tomorow.

Op vrijdag 4 november 2016 heeft BWS Systems <notifications@github.com> het
volgende geschreven:

**Comment by paulhemels** [comment]
I have reinstalled de HA-bridge, the error are gone.
When i want to connect the HA-bridge to the harmony hub, the harmony does
"see" the HA-bridge, but it ask to push the button on the HA-bridge!
But there is no button to push on my RPI, what is the next step?

Op vrijdag 4 november 2016 heeft Paul Hemels <paulhemels@gmail.com> het
volgende geschreven:

**Comment by paulhemels** [comment]
The HA-bridge is now connected to the Harmony Hub, the only problem is that now there is 1 device from the HA-bridge visible on the Harmony, the others not :(
Reconnect the HA-Bridge doesn't help, do you have a idea or is it a Harmony isseu.

**Comment by paulhemels** [comment]
It is a problem with the Harmony HUB, I installed the philips hue App and that does see all the devices on the HA-bridge :)
And can control them.
