### ISSUE TITLE
GUI option for Shutdown & Restart HA-Bridge

### ISSUE THREAD

**Issue by Ltek** [bwssytems/ha-bridge#22]
I have HA-Bridge running on my Synology NAS, and it has been working well - thank you!

During my trial & error testing it was a PITA to shutdown and restart the app... would be great if there was an option to do it in the GUI.

**Comment by bwssytems** [comment]
I'll take a look into this. Should be able to do it with a generated script.

**Comment by bwssytems** [comment]
Since this is a multi platform system, it will be very messy to support this request... sorry.
