### ISSUE TITLE
Fresh Raspbian install, RPi3 bridge won't run, errors (Submitted for someone on my website)

### ISSUE THREAD

**Issue by audiofreak9** [bwssytems/ha-bridge#220]
@bwssytems - Corey here trying to help someone on my website who is having problem getting the bridge to start.  Fresh Raspbian install, RPi3 (and RPi2) bridge won't run, errors below:

He keeps getting the following error after running: `Java -jar /home/pi/echobridge/ha-bridge-3.2.1.jar`

- Response Port is in use, starting loop to find open port for 20 tries – configured port is: 50000
- ERROR spark.webserver.JettySparkServer – ignite failed
- java.net.SocketException: Permission denied

Thanks!
—

> 2016-11-03 09:03:28,009 [main] INFO com.bwssystems.HABridge.HABridge – HA Bridge (v3.2.1) starting….
> 2016-11-03 09:03:28,079 [main] INFO com.bwssystems.HABridge.BridgeSettings – reading from system properties
> 2016-11-03 09:03:28,105 [main] INFO com.bwssystems.HABridge.BridgeSettings – Adding 192.168.1.162 as our default u pnp config address.
> 2016-11-03 09:03:28,106 [main] INFO com.bwssystems.HABridge.HABridge – HA Bridge initializing….
> 2016-11-03 09:03:28,175 [main] INFO com.bwssystems.HABridge.SystemControl – System control service started….
> 2016-11-03 09:03:28.736:INFO::Thread-0: Logging initialized @2534ms
> 2016-11-03 09:03:28,925 [main] WARN com.bwssystems.HABridge.dao.DeviceRepository – Error reading the file: data/de vice.db – Does not exist or is not readable. continuing…
> 2016-11-03 09:03:28,926 [main] INFO com.bwssystems.HABridge.devicemanagmeent.DeviceResource – HABridge device mana gement service started….
> 2016-11-03 09:03:29,000 [main] INFO com.bwssystems.HABridge.upnp.UpnpSettingsResource – Hue description service st arted….
> 2016-11-03 09:03:29,014 [main] INFO com.bwssystems.util.UDPDatagramSender – Initializing UDP response Seocket…
> 2016-11-03 09:03:29,028 [main] WARN com.bwssystems.util.UDPDatagramSender – UDP Response Port is in use, starting loop to find open port for 20 tries – configured port is: 50000
> 2016-11-03 09:03:29,029 [main] INFO com.bwssystems.util.UDPDatagramSender – UDP response Seocket initialized to: 5 0001
> 2016-11-03 09:03:29,199 [Thread-0] INFO spark.webserver.JettySparkServer – == Spark has ignited …
> 2016-11-03 09:03:29,209 [Thread-0] INFO spark.webserver.JettySparkServer – >> Listening on 0.0.0.0:80
> 2016-11-03 09:03:29.226:INFO:oejs.Server:Thread-0: jetty-9.3.z-SNAPSHOT
> 2016-11-03 09:03:29,463 [Thread-0] ERROR spark.webserver.JettySparkServer – ignite failed
> java.net.SocketException: Permission denied
> at sun.nio.ch.Net.bind0(Native Method)
> at sun.nio.ch.Net.bind(Net.java:433)
> at sun.nio.ch.Net.bind(Net.java:425)
> at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
> at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
> at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:326)
> at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
> at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:244)
> at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
> at org.eclipse.jetty.server.Server.doStart(Server.java:384)
> at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
> at spark.webserver.JettySparkServer.ignite(JettySparkServer.java:131)
> at spark.SparkInstance.lambda$init$0(SparkInstance.java:341)
> at java.lang.Thread.run(Thread.java:745)

**Comment by audiofreak9** [comment]
User was using Raspbian LITE and/or Raspbian installed by NOOBS LITE.  Need full Raspbian to run ha-bridge.  Also finding that port 80 is requiring sudo, flushing this out now...so closing Issue.

**Comment by iantrich** [comment]
Lite just has less pre-installed. Did you ever determine what was needed to overcome the errors beyond installing a new image of Raspbian?

**Comment by st2000** [comment]
BUMP.
I just installed jessie (just checked by cat /etc/os-release) and have this same exact problem.  No where in this file does it say "lite".  So I am stumped.  Especially since I just went through Corey's how-to just last month.  (I trashed my SDCard and had to start over).  Aside from possible pilot error, the only thing I didn't do was start with Corey's old how-to then proceed to his new how-to.  Maybe there is something missing by skipping over doing Corey's old how-to.

**Comment by bwssytems** [comment]
Sometimes it is best to go with the standard Raspbian instructions and go from there.

**Comment by st2000** [comment]
Yes, I understand what you are saying.  I am fairly sure that this (https://www.raspberrypi.org/downloads/raspbian/) is what I downloaded and installed.  The raspberry pi version of Jessie.  "Raspbian Jessie with PIXEL".

**Comment by bwssytems** [comment]
are you running the bridge with sudo or giving port 80 access to the pi user?

**Comment by st2000** [comment]
Linux.  I used "dd".  So I assume the SDCard was erased in the process.  The SDCard is 16GBytes.

**Comment by audiofreak9** [comment]
No, I believe dd does not erase the sd card when writing the image.  You can erase an sd card with dd using the following: `sudo dd if=/dev/zero of=/dev/disk2 bs=8192`, being **SUPER** sure you have the correct disk in the "of=" part, I used disk2 as this was my disk's name.  You can also use the fdisk or cfdisk command to erase the card.   Once erased, the card will be unmounted and you can dd the image on thereafter.

**Comment by st2000** [comment]
BTW, there's a difference in the startbridge.sh script.  Corey has:
 nohup java -jar -Djava.net.preferIPv4Stack=true /home/pi/habridge/ha-bridge.jar > /home/pi/habridge/habridge-log.txt 2>&1 &
...and here it's:
nohup java -jar -Dconfig.file=/home/pi/habridge/data/habridge.config /home/pi/habridge/ha-bridge-3.5.1.jar > /home/pi/habridge/habridge-log.txt 2>&1 &
...I'm not sure if this is a small update or something important.
(Thanks for the help guys.)

**Comment by st2000** [comment]
Ok, @Corey, I'll start over.  Check the MD5's this time too.
-thanks.

**Comment by audiofreak9** [comment]
`-Djava.net.preferIPv4Stack=true` is actually now not required, as it is default.

I name my jar file simply "ha-bridge.jar" so I don't have to edit the startbridge.sh script.  I simply download the latest, rename it, and reboot.

So essentially the two are the same, I'll remove the `-Djava.net.preferIPv4Stack=true` from my tutorial now.

**Comment by st2000** [comment]
Ok, it worked.  The SHA1 check good on the original raspbean file so I used it again.  Maybe dd doesn't wipe a SDCard clean.  But I am going to side with me pushing the install.  I think I executed a config  or make early before the apt-get upgrade was finished.
