### ISSUE TITLE
Home assistant add devices..

### ISSUE THREAD

**Issue by oktane83** [bwssytems/ha-bridge#221]
I see vera and harmony can detect all the devices on those platforms.. is this feature supported for home assitant? Would be nice to not have to manually add 30 switches..

Cheers!

**Comment by bwssytems** [comment]
Will look into this

**Comment by bwssytems** [comment]
So, I will add the get for all "states" i.e. devices and have helpers for either, light (has dim) or Switch which is on and off.

**Comment by xbmcnut** [comment]
That would be awesome. I'm currently controlling a couple of Home Assistant scenes with API calls but if ha-bridge could 'see' everything natively, that's a killer feature. Can't wait to test that out.

**Comment by GrubbyDungles** [comment]
Check this script out for HASS import.
https://community.home-assistant.io/t/why-cant-emulated-hue-work-with-onhub-or-google-home/5794/40?
It would be great to be able to pull everything in at once and then enable / disable / edit the parts you want to use.

**Comment by Yungling** [comment]
Hi GrubbyDungles,

I am very new to the programing/automation world. Now I have managed the set up the HA-bridge but have difficulty adding devices to it (from Home Assistant). I saw the script you paste but have no idea how to execute it. Would you please help me out here. Really appreciate!!

**Comment by GrubbyDungles** [comment]
@Yungling Sorry - I just linked to that script because I thought it was relevant. If you want to use it the best thing to do would be to follow the link and ask the guy who wrote it.

Otherwise, there is a general guide with examples for home assistant here. 
https://community.home-assistant.io/t/general-ha-bridge-guide-hue-bridge-for-alexa-or-google-home/6758

Once you add a few lights in you will get the gist, if you have any problems post in that thread and someone will help.

**Comment by bwssytems** [comment]
You can check out the beta version posted in #344 for HomeAssistant connection

**Comment by Yungling** [comment]
Thanks to @GrubbyDungles  @bwssytems 
However i still cannot manually add any devices from Home assistant to HA bridge (i managed to add Harmony though. Works great!)
I pasted my web request i used to turn the lights on by using IFTTT...Not sure if this helps....

https://XXXXXXX.duckdns.org/api/services/light/turn_on?api_password=XXXXXX

**Comment by GrubbyDungles** [comment]
@Yungling https:// will be your problem, something to do with letsencrypt, java and the location of certificates. The problem was solved, check this link to the solution.
https://community.home-assistant.io/t/why-cant-emulated-hue-work-with-onhub-or-google-home/5794/35?

**Comment by Yungling** [comment]
@GrubbyDungles i tried right away and it worked! Now i can turn on/off my light thru HA bridge, which is a lot faster vs. thru IFTTT. Thank you very much for helping!
