### ISSUE TITLE
Bridge not found

### ISSUE THREAD

**Issue by Joe-houghton** [bwssytems/ha-bridge#223]
Hi,

So I am trying to use Domoticz with HA-bridge in the hope of using the [AlexaPi ](https://github.com/alexa-pi/AlexaPi) project also on the Pi.

I wasn't finding the HA-bridge when scanning with Alexa, so i decided to wipe the Pi and start from scratch.

I used the Domoticz pi sd card image, and have ran all the updates.
Installed Java 1.8
Downloaded the HA-bridge-v3.2.1.jar followed the Readme.md instructions to get it running. The only difference is that i have to use "sudo ./starthabridge.sh".
I have setup a single device that is of type custom and the On/Off URLS. Testing this works fine, my light turns on.

Before I installed AlexaPi, I read somewhere that you can try with the Phillips Hue App to try and find the bridge. It cannot find the bridge.

I have attached my log and also the Bridge backup file. Any suggestions on what to try next?

Many Thanks,

Joe

[habridge-log.txt](https://github.com/bwssytems/ha-bridge/files/573531/habridge-log.txt)
[testing.bk.txt](https://github.com/bwssytems/ha-bridge/files/573532/testing.bk.txt)

**Comment by Joe-houghton** [comment]
Update -- In the Phillips hue app i found a way to manually add the HA-Bridge and it can see my bridge device. Great! however, Alexa does not have this manual add option. So i'm still stuck.

Joe

**Comment by cykew** [comment]
i tried below with latest ha bridge 3.2.1 running on port 80

1. Ha Bridge found by Amazon Echo and able to control the devices (No issue)

2. Ha Bridge found by Philips Hue latest app however fail to add the devices in due to it required the philips hue hub (ha bridge) found must support Apple Home Kit.

3. Ha Bridge found by Philips Hue gen 1 app and able to add and control the devices. Same, not able to control via Siri because it detect ha bridge is not a philips hue hub that support Apple Home Kit.

4. I would like to add Ha Bridge (Philips Hue Bridge) in Imperihome app but failed. Not able to found/detect the bridge. Anyone know how to check and why?

**Comment by bwssytems** [comment]
@cykew Could you add a specific issue for the imperihome request. Then close this issue.

Thanks

**Comment by cykew** [comment]
@bwssytems This issue not open by me, i think i cannot close right? I will open another issue for imperihome. Thank

**Comment by bwssytems** [comment]
@Joe-houghton Have you checked the upnp ip address in the bridge control tab that it matches your system ip?

**Comment by Joe-houghton** [comment]
@bwssystems thanks for your reply. 
I have set the ip address to 192.168.0.25 which is the ip address of my pi running HA-bridge.

**Comment by bwssytems** [comment]
So, in your original log, I don't see a request from any other device for upnp in your trace. Is there something to have Domoticz look for a hue bridge?

**Comment by bwssytems** [comment]
I'm, sorry, I just read again your post. The software Alexa does not search for any home automation devices locally, that is disabled in that software. Only the hardware echo's do that.

**Comment by Joe-houghton** [comment]
Ah! That would make sense. 
Is there anyway to do a port forward or something on a router to loop back?

**Comment by bwssytems** [comment]
Again, The software Alexa does not have the ability to find any Hue bridge at all, the software is not included in soft Alexa.

**Comment by Joe-houghton** [comment]
Ah,  I understand you now. Completely misunderstood before.
