### ISSUE TITLE
Duplicate calls made to URL, first one un-authenticated

### ISSUE THREAD

**Issue by sumnerboy12** [bwssytems/ha-bridge#224]
I am using this awesome tool for integrating my Echo with openHAB and it works great, so firstly thanks very much! 

Recently I added `fail2ban` to my setup to try and beef up security but was finding my `ha-bridge` VM was getting banned. Checking the openHAB Jetty request logs I was seeing two requests every time I executed a command via the `ha-bridge`, and the first one always fails with a `401` error - i.e. forbidden.

```
192.168.1.21 -  -  [06/Nov/2016:22:45:38 +1300] "POST /rest/items/GF_Kitchen_CoffeeMachine HTTP/1.1" 401 1406
192.168.1.21 -  -  [06/Nov/2016:22:45:38 +1300] "POST /rest/items/GF_Kitchen_CoffeeMachine HTTP/1.1" 201 0
```

Just wondering if this is a known issue? Does the bridge make some sort of initial attempt to connect? The URL for the device in `ha-bridge` is `http://<username>:<password>@openhab:8080/rest/items/GF_Kitchen_CoffeeMachine` using POST etc. 

FYI: Any commands sent from the openHAB mobile app (which uses the REST API) come thru fine, as a single request.

**Comment by sumnerboy12** [comment]
After thinking about this a bit more, am I right in saying it is not `ha-bridge` that makes the calls to the openHAB REST API, it is Alexa itself. All `ha-bridge` does is provide the on/off URLs during discovery.

So is it possible Alexa is doing something with my URLs (maybe stripping the authentication details) and making the request in this form first, before sending the full URL?

**Comment by sumnerboy12** [comment]
And any idea why the failure request have 1406 bytes, but the succesfull request is empty? Trying to figure out what might be causing this...

**Comment by bwssytems** [comment]
It is the Alexa that calls the ha-bridge like it is a philips hue bridge, the ha-bridge in turn then calls the URL you provide. Do you have multi exec statements in your URL?

**Comment by sumnerboy12** [comment]
Here is a screen grab of an item as setup in `ha-bridge` - so the request is actually made by `ha-bridge`. I wonder if there are duplicate item definitions floating around (from earlier configs) that are being used? I checked the device db and there is only one reference to `GF_Kitchen_CoffeeMachine` in there. Anywhere else I should be checking?

![image](https://cloud.githubusercontent.com/assets/5060842/20072287/a98df11c-a58c-11e6-854f-463f43a45741.png)

**Comment by bwssytems** [comment]
I'll need you to turn on logging to what is happening:

"To set logging at a lower level, select the Show All Loggers checkbox and then you can set the explicit level on each of the processes components. The most helpful logger would be setting DEBUG for com.bwssystems.HABridge.hue.HueMulator component. Changing this and then selecting the Update Log Levels button applies the new log settings."

Post the log when you have the double call. Thanks

**Comment by sumnerboy12** [comment]
Hope this helps; 

```
11-08-2016 09:19:59.944	DEBUG	hue state change requested: test from 192.168.10.25 body: {"on":true}	com.bwssystems.HABridge.hue.HueMulator
11-08-2016 09:19:59.944	DEBUG	executing HUE api request for network call: http://user:password@openhab.home:8080/rest/items/GF_Kitchen_CoffeeMachine	com.bwssystems.HABridge.hue.HueMulator
11-08-2016 09:19:59.944	DEBUG	executing HUE api request to Http POST: http://user:password@openhab.home:8080/rest/items/GF_Kitchen_CoffeeMachine	com.bwssystems.HABridge.hue.HueMulator
11-08-2016 09:19:59.944	DEBUG	Making outbound call in doHttpRequest: POST http://user:password@openhab.home:8080/rest/items/GF_Kitchen_CoffeeMachine HTTP/1.1	com.bwssystems.HABridge.hue.HueMulator
11-08-2016 09:19:59.953	DEBUG	POST execute on URL responded: 201	com.bwssystems.HABridge.hue.HueMulator
11-08-2016 09:20:02.232	DEBUG	hue state change requested: test from 192.168.10.25 body: {"on":false}	com.bwssystems.HABridge.hue.HueMulator
11-08-2016 09:20:02.233	DEBUG	executing HUE api request for network call: http://user:password@openhab.home:8080/rest/items/GF_Kitchen_CoffeeMachine	com.bwssystems.HABridge.hue.HueMulator
11-08-2016 09:20:02.233	DEBUG	executing HUE api request to Http POST: http://user:password@openhab.home:8080/rest/items/GF_Kitchen_CoffeeMachine	com.bwssystems.HABridge.hue.HueMulator
11-08-2016 09:20:02.233	DEBUG	Making outbound call in doHttpRequest: POST http://user:password@openhab.home:8080/rest/items/GF_Kitchen_CoffeeMachine HTTP/1.1	com.bwssystems.HABridge.hue.HueMulator
11-08-2016 09:20:02.237	DEBUG	POST execute on URL responded: 201	com.bwssystems.HABridge.hue.HueMulator
```

**Comment by bwssytems** [comment]
So it only shows 2 calls exterenally that are 3 seconds apart and they are successful.

**Comment by sumnerboy12** [comment]
Yes, but in my openHAB logs I am seeing; 

```
192.168.1.21 -  -  [08/Nov/2016:09:19:59 +1300] "POST /rest/items/GF_Kitchen_CoffeeMachine HTTP/1.1" 401 1406
192.168.1.21 -  -  [08/Nov/2016:09:19:59 +1300] "POST /rest/items/GF_Kitchen_CoffeeMachine HTTP/1.1" 201 0
192.168.1.21 -  -  [08/Nov/2016:09:20:02 +1300] "POST /rest/items/GF_Kitchen_CoffeeMachine HTTP/1.1" 401 1406
192.168.1.21 -  -  [08/Nov/2016:09:20:02 +1300] "POST /rest/items/GF_Kitchen_CoffeeMachine HTTP/1.1" 201 0
```

**Comment by bwssytems** [comment]
Well, I have no idea why the OpenHAB has that. The ha-bridge only called out twice as the log indicates.

**Comment by sumnerboy12** [comment]
Hmm - the openHAB app uses the REST API as well but I am not seeing these duplicate calls with that. Thanks, I think you have confirmed what I was wanting to know - that `ha-bridge` doesn't make two calls for whatever reason. Must be something else.

**Comment by sumnerboy12** [comment]
Hi - I figured out what was going on so thought I would report back in case someone else comes across the same thing. It was due to the way I sending my authentication, i.e. in the URL itself. 

Changing my ha-bridge config to authenticate using HTTP headers, e.g.;
```
[{"name":"Authorization", "value":"Basic <base64encoded-user:password>"}]
```
Has solved the issue.

**Comment by bwssytems** [comment]
Great!
