### ISSUE TITLE
${intensity.percent} inside Content Body Dim?

### ISSUE THREAD

**Issue by farhanito** [bwssytems/ha-bridge#225]
I tried a setup like this, and it doesn't work..

Dim URL:
http://192.168.31.157/sony/audio

HTTP Verb : POST
Content-Type : application/json

Content Body Dim:
{"id":3,"method":"setAudioVolume","version":"1.0","params":[{"target":"speaker","volume":"${intensity.percent}"}]}

Is this possible? 

Thanks

**Comment by bwssytems** [comment]
What version are you running. An error with dim was fixed in v3.2.1

**Comment by farhanito** [comment]
Ah, yes, sorry. It does work with the echo.
The "Test Dim" button doesn't.

**Comment by bwssytems** [comment]
I'll take a look at that for the test button.

**Comment by bwssytems** [comment]
It' a bug.
