### ISSUE TITLE
Path discrepancy in the how to

### ISSUE THREAD

**Issue by koncertedseanleach** [bwssytems/ha-bridge#226]
On the main project page, in the how-to/setup section, there is a section that describes how to setup a systemctl service on a Raspberry Pi. In this line:

ExecStart=/usr/bin/java -jar -Dconfig.file=/home/pi/amazon-echo/data/habridge.config /home/pi/amazon-echo/ha-bridge-3.2.2.jar

...it shows a path that is different from the one suggested in the lower part of the how-to:

/home/pi/habridge/ha-bridge-3.2.2.jar

etc.

Seems like everything should be consistent. A new user who isn't experienced with the command line may have trouble figuring this out.

**Comment by bwssytems** [comment]
Thanks for the suggestion, will update.
