### ISSUE TITLE
systemctl method for automating ha-bridge does not work in older Raspbian distributions

### ISSUE THREAD

**Issue by koncertedseanleach** [bwssytems/ha-bridge#227]
After getting ha-bridge running on my Pi, I wanted to make sure it launched at startup on it's own.

I followed the section about setting up a systemctl service, but the "systemctl" command doesn't work under older Raspbian distributions, on older Raspberry Pi devices.

It may be worth suggesting that folks with an older Pi/Raspbian setup schedule a cron job to run the starthabridge.sh script they created during the initial setup.

**Comment by bwssytems** [comment]
It does say next gen linux systems with systemctl and there is an alternate for when systems do not have it. I totally understand for newbies that may have an issue and can post there problem. This is github, newbies will be awash with questions.

**Comment by koncertedseanleach** [comment]
Understood. Just wanted mention it.

**Comment by bwssytems** [comment]
Thanks
