### ISSUE TITLE
Imperihome app not able to find HA Bridge

### ISSUE THREAD

**Issue by cykew** [bwssytems/ha-bridge#228]
i tried below with latest ha bridge 3.2.1 running on port 80:

I would like to add Ha Bridge (Philips Hue Bridge) in Imperihome app but failed. Not able to found/detect the bridge. Anyone know how to check and why? Thank

**Comment by bwssytems** [comment]
So, I tried the imperihome app and try to add a philips hue. It does not send out any multicast messages. It may be using the web based discovery from philips, which the ha-bridge cannot do. I would contact the imperihome creators to see how they connect to a philips hue.

**Comment by cykew** [comment]
Thank. Wait for  your good news.

**Comment by bwssytems** [comment]
There is no good news from me, this is an imperihome issue. If you would like to contact the developer of imperihome to find out more that would be great. Thanks, closing.
