### ISSUE TITLE
Trigger Harmony Activity by URL ?

### ISSUE THREAD

**Issue by dmb0058** [bwssytems/ha-bridge#229]
Just a question really ... is it possible to trigger a Harmony activity that's defined on the bridge ? Or to set the state of a Harmony device (e.g. PUT http://localhost:8080/api/devices/32285975
{ "on": true, "bri": 254 }) ?

**Comment by bwssytems** [comment]
Yes you can the format of the PUT statement is  http://ip_address:port/api/{userId}/lights/{lightId}/state with the body you identify in your post.

**Comment by dmb0058** [comment]
Hi,

What value should I use for the lightId ? I tried three values that I found
for the particular Harmony activity by using the API, but they all returned
404.

Cheers,

David

**Comment by bwssytems** [comment]
Did you create a device in the ha-bridge for the harmony activity? That is what that call triggers. If you want to call the harmony hub directly, you'll need to review the code for the harmony connector in the bridge. It is not pretty.

**Comment by dmb0058** [comment]
Yes I did. I'll try again with anything that might conceivably be an id field in the output from the URL that lists activities...

**Comment by bwssytems** [comment]
It is the id for the created ha-bridge device not the activity id from the harmony. It is the one in the bridge devices screen.

**Comment by dmb0058** [comment]
Tried a PUT to http://localhost:8080/api/lights/15/state of { "on": true, "bri": 254 } where 15 is the value in the ID column of the bridge devices screen corresponding to this activity (Name: "TV", Type: "activity", Target: "Harmony Hub") but I get 404 (Not found).

**Comment by bwssytems** [comment]
you need a user id like "test" in between the /api and the /lights as the format indicates. The Id can be anything.

**Comment by dmb0058** [comment]
Hmm, better. With http://localhost:8080/api/test/lights/4/state I don't get
the 404 but the device doesn't switch off either. The "Test on"/"Test off"
buttons on the HA bridge web page for ID 4 work fine.

**Comment by bwssytems** [comment]
body {"on":true} turns device on, body {"on":false} turns device off. These are the Hue API calls that the bridge understands.

**Comment by bwssytems** [comment]
And you have to do an HTTP PUT, you cannot just put this into a browser as you need a REST tool to send the request.

**Comment by dmb0058** [comment]
Yes, this is what I did, using python (urllib2).

Is there a debug mode I can set to see what the http server is
doing/getting ?

**Comment by bwssytems** [comment]
Yes, read this in the readme https://github.com/bwssytems/ha-bridge#the-logs-tab

**Comment by dmb0058** [comment]
It works - if I take out the "bri" parameter for the off command. So {"on":true
}/{"on":false} is fine, {"on":true, "bri":254} works but
{"on":false,"bri":254} does not.

**Comment by bwssytems** [comment]
usually there are no other parameters when turning off. So that would be correct.

**Comment by merlin2105** [comment]
hello,
i want to trigger a harmony button , this is not work for me
http://192.168.1.21:81/api/test/lights/1/state/on=true
when i send192.168.1.21:81/api/test/lights/1  
i get this 
{"state":{"on":false,"bri":0,"hue":0,"sat":0,"effect":"none","ct":0,"alert":"none","reachable":true},"type":"Dimmable light","name":"wohnzimmer","modelid":"LWB004","manufacturername":"Philips","uniqueid":"00:17:88:5E:D3:01-01","swversion":"66012040"}

How can i send the stat on or off

**Comment by bwssytems** [comment]
@merlin2105 please review the readme for the hue api state change commands.

**Comment by merlin2105** [comment]
Hello, i dont understand this, i am not an developer, i am a user ! 
i don't understand where i can send this 
{
	"on": true,
	"bri": 200
}

with the Url line! i google hours to find a solution. can i send the state with the url ?

is this wrong?
http://192.168.1.21:81/api/test/lights/1/state/on=true
can you correct the line to trigger the On or Off button! 

i need this for the HomeKit Plugin 

{
            "accessory": "BlindsHTTP",
            "name": "Alle",
            "up_url": "https://maker.ifttt.com/trigger/Rollo_alle_auf/with/key/xxxxxxxxxxxxxxx",
            "down_url": "https://maker.ifttt.com/trigger/Rollo_alle_zu/with/key/xxxxxxxxxxxxx",
            "http_method": "PUT"
        }

i need your help :-)

.. i will not trigger this over IFTTT , it is very slow!

thanks

**Comment by audiofreak9** [comment]
You can't do a PUT from a browser using the "URL line"!

You need to reference this section of the [READ ME](https://github.com/bwssytems/ha-bridge#set-light-state)!

You can also review any of the [results from a Google search for the RESTful API using put](https://www.google.com/search?q=REST+put)!

**Comment by merlin2105** [comment]
can i send it with PHP script like this?
<?php

set rollo = http://192.168.1.21:81/api/test/lights/1/state
curl -X PUT -d "{"on":true}" %rollo% >>NUL
?>
 But it does not work either

**Comment by merlin2105** [comment]
hi, 
i find a PHP script for Philips HUE,

 <?php

$arrData['on'] = false;
#$arrData['sat'] = 254;
#$arrData['bri'] = 0;

$data = json_encode($arrData);
echo $data;

$url = "http://192.168.1.21:81/api/test/lights/1/state";

$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_PORT, 81);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PUT");

$response = curl_exec($ch);
echo $response; 

?>
The result when i call the script  = {"on":false} 

Can really help anyone here..    :-(
