### ISSUE TITLE
UP down or a number

### ISSUE THREAD

**Issue by scargill** [bwssytems/ha-bridge#230]
When you set say a lamp up - and say "up" or "down" - or feed in a percentage - all of that is great - but what if you only wanted to go up one point/degree/percent?  is there a way to differentiate between the up/down command and putting a value in - right now all that seems to go out is the value.

**Comment by bwssytems** [comment]
Unfortunately, there is not. This is all controlled by the Echo and amazon alexa. The ha-bridge only receives the command from the echo or home's interpretation.

**Comment by scargill** [comment]
Thanks for the feedback - saves me wasting time looking for answers that are not there :-)
