### ISSUE TITLE
Google Home displaying duplicate devices

### ISSUE THREAD

**Issue by dannieboiz** [bwssytems/ha-bridge#232]
on HA Bridge it's only showing 1 device but on the app, I'm showing 2-4 of the same devices.

**Comment by bwssytems** [comment]
do you have multiple instances of the bridge running?

**Comment by dannieboiz** [comment]
yup, only 1 java instance running and 1 bridge

**Comment by bwssytems** [comment]
Don't know why then. I don't have a google home to test.

**Comment by audiofreak9** [comment]
Does the Google Home have a forget all devices option?

**Comment by robertw** [comment]
unlink and relink

**Comment by dannieboiz** [comment]
That's what I've been doing link and unlink fixes it then later it comes back. I just did it again lets see how it goes.

**Comment by jimboca** [comment]
I see the same issue, and experienced this with the hue-upnp emulator as well.  To fix it with the there I changed the code to ignore the same device requesting POST /api within a few seconds then it returns a 404 on the second request for the same client.  I'd really like to use your code for hue emulation with google home since it has really cool features for controlling my harmony hubs as well!

**Comment by bwssytems** [comment]
@jimboca That seems odd as that call is to get a username after link button is pressed. The ha-bridge is in link button pressed mode all the time. Could you turn traceupnp on in the ha-bridge and post the log when getting the Google Home setup. Thanks

**Comment by jimboca** [comment]
@bwssytems Yes, the Google Home seems to ask for the username a couple times, and accepts both of them and asks for all the lights on each. 

But, of course now that I turned on traceupnp it is not happening.  Let me know if there is something else I can try.  I will email you the log.

BTW, I am writing Python code that works with the UDI ISY994zw to interface your ha-bridge with this controller.

**Comment by bwssytems** [comment]
@jimboca Interesting, wouldn't you have to start from scratch and clear out all the devices and the ha-bridge on the Google Home to replicate?

By chance, would you be interested in writing your UDI interface in Java so that it can be pulled into the bridge?

**Comment by jimboca** [comment]
@bwssytems I did clear all in Google Home. Didn't think I needed to clear ha-bridge. 

I'd love to have the ISY part integrated in ha-bridge, but I don't know Java. I've talked to guy who wrote the Android Agave app for the ISY and he is interested, but wasn't sure when he would have time.

**Comment by bwssytems** [comment]
There was a guy that wrote a configurator system to work with the ha-bridge
that proxied all the calls to the ISY. Have you looked into that? I believe
this is the link
http://forum.universal-devices.com/topic/14525-amazon-echo-and-isy/page-35

**Comment by jimboca** [comment]
Yes, that code writes a config which you can copy to use in ha-bridge.  My code grabs the spoken directly from the ISY and passes them to ha-bridge thru the rest interface, and keeps a connection with the ISY alive to pass updates to ha-bridge so the light status (on/off/bri) are updated as they happen.

**Comment by asomnath** [comment]
Any update on this issue. I am seeing duplicate devices on google home.
I have just one ha-brigde running on port 80 to which both Amazon Alexa and Google Home are connected.

**Comment by bwssytems** [comment]
As mentioned above, with Google Home you have to unlink and relink for the duplicates to go away. Not an ha-bridge issue.

**Comment by asomnath** [comment]
Thanks a lot for the reply. I just check Google Home now and there is just one set of devices. 
Somehow the duplicates went away .. i will wait and watch. 
I had seen similar discussion on Google Home forums where they were using the physical hub , so i knew it was not a ha-bridge problem ,just wanted to check if someone here had found some creative solution

Thanks
