### ISSUE TITLE
Not an issue - I was able to add HA-Bridge as a Phillips Hue device to Harmony App

### ISSUE THREAD

**Issue by dannieboiz** [bwssytems/ha-bridge#233]
I didn't even know that it was possible. This is pretty awesome.

**Comment by audiofreak9** [comment]
And you can put those lights into harmony activities.

**Comment by dannieboiz** [comment]
I was thinking just that. What's nice is I can control lights and AV with a single source.

**Comment by audiofreak9** [comment]
BINGO!

**Comment by audiofreak9** [comment]
BTW, the ha-bridge is discoverable by _just about_ anything that can discover a real HUE Bridge.
