### ISSUE TITLE
Unable to activate activities through HUB from GH

### ISSUE THREAD

**Issue by dannieboiz** [bwssytems/ha-bridge#234]
Are there any additional steps that I need to be aware of when adding the Harmony Hub?

I'm unable to control activities through GH. I can use GH to turn off the system

The test on feature does work on all activities within HA Bridge. 

GH say there's an error and cannot control my device.

**Comment by bwssytems** [comment]
Debug is your friend. Read this and turn on the debug and take a look at what is happening... Teaching you to fish here.... https://github.com/bwssytems/ha-bridge#the-logs-tab

**Comment by dannieboiz** [comment]
thanks, the debugging helped me isolate the issue to the stupid Harmony Hub. I think the hub go on standby or something after awhile and can only be triggered by the actual remote. Once I start the activity for the first time then I can start triggering different activities. ugh!
