### ISSUE TITLE
Dim URL quoted text getting garbled?

### ISSUE THREAD

**Issue by iotarho** [bwssytems/ha-bridge#235]
Using Chrome and attempting to control my milights according to the post here:
http://codecorner.galanter.net/2016/05/12/full-control-of-your-limitless-ledmilight-bulbs-from-amazon-echo/

The "On URL" and "Off URL" entries work great, however when I attempt to run two udp sequences to dim the lights, like this:
[{“item”:”udp://192.168.1.27:8899/0x450055″},{“item”:”udp://192.168.1.27:8899/0x4E${intensity.math((X*27)/255)}55″}]

then doing "Update Device", the quoted text is getting garbled:
[{â€œitemâ€�:â€�udp://192.168.1.27:8899/0x450055â€³},{â€œitemâ€�:â€�udp://192.168.1.27:8899/0x4E${intensity.math((X*27)/255)}55â€³}]

Not quite sure what I'm doing wrong?

**Comment by bwssytems** [comment]
The character set at the website that you cut and pasted from is nonstandard and it pastes that info into the text box. just type it in as you see it and it will fix it.

**Comment by bwssytems** [comment]
Did you get this fixed?

**Comment by iotarho** [comment]
I did, thanks for the fast response, it's copy/paste weirdness that was circumvented by your suggestion.
