### ISSUE TITLE
No german "umlaute" in device name

### ISSUE THREAD

**Issue by thto666** [bwssytems/ha-bridge#238]
HA-Bridge web GUI seems to save device name as UTF8 string in the data/device.db file.
The device.db file is ANSI encoded, which results in names like "Radio KÃ¼che"

After manually editing the name in device.db file everything works as expected.

Kind regards,
Thomas

**Comment by henmedia** [comment]
Me too ... also if I use blanks in the URL to call, the call fails, I have to replace them by %20

![screenshot_01](https://cloud.githubusercontent.com/assets/24408115/21748419/38013ca6-d585-11e6-851c-144f7fb578f5.png)

Stefan

**Comment by audiofreak9** [comment]
I found that for spaces, using the plus symbol + rather than %20 worked more consistently for me with the backend encoding.

**Comment by bwssytems** [comment]
You should be able to encode with the following:

German special characters

Description	Character	Code
Capital A with umlaut	Ä 	&#196;
Capital E with acute	É 	&#201;
Capital O with umlaut	Ö 	&#214;
Capital U with umlaut	Ü 	&#220;
SZ ligature	ß 	&#223;
Description	Character	Code
Small a with umlaut	ä 	&#228;
Small e with acute	é	&#233;
Small o with umlaut	ö 	&#246;
Small u with umlaut	ü 	&#252;

**Comment by henmedia** [comment]
But that shouldn't be the final solution :)

**Comment by bwssytems** [comment]
So in testing this on the current version, it saves and keeps the umlaut in my testing.

**Comment by henmedia** [comment]
Sorry, but still the same problem with umlaut characters.

If I enter

![screenshot_04](https://cloud.githubusercontent.com/assets/24408115/24139735/a0431d5e-0e1d-11e7-99ca-ef5cc6bfb5a2.png)

I get

![screenshot_05](https://cloud.githubusercontent.com/assets/24408115/24139771/bde3e8a2-0e1d-11e7-8acc-3adfa56cd0d2.png)

![screenshot_06](https://cloud.githubusercontent.com/assets/24408115/24139815/e63cccec-0e1d-11e7-8ecc-91c251353605.png)

![screenshot_01](https://cloud.githubusercontent.com/assets/24408115/24139854/07573d68-0e1e-11e7-8630-a9fc5580b1f9.png)

**Comment by bwssytems** [comment]
So, I need to ask how your system is setup to enter the characters (os, keyboard, language) as I will need to test it. There  must be a conversion from unicode that is happening in the ui to the server that is not being handled (of course!) as there are 2 bytes showing up when you save and not one.

**Comment by henmedia** [comment]
Windows 7 German, Chrome and Firefox in their latest versions (FF 52.0.1, Chrome 56.x)
