### ISSUE TITLE
mutliple custom executions

### ISSUE THREAD

**Issue by merlin051** [bwssytems/ha-bridge#239]
Hi,

I'm using custom executions to call a python script to control my Orvibo S20 sockets.

My request looks like this:
//ON
[{"item":"exec://C:\\python27\\python C:\\ha-bridge-master\\s20control.py poweron 192.168.0.8 AC:CF:23:8D:2A:10"}, {"item":"exec://C:\\python27\\python C:\\ha-bridge-master\\s20control.py poweron 192.168.0.9 AC:CF:23:93:33:DC"}]

//OFF
[{"item":"exec://C:\\python27\\python C:\\ha-bridge-master\\s20control.py poweroff 192.168.0.8 AC:CF:23:8D:2A:10"}, {"item":"exec://C:\\python27\\python C:\\ha-bridge-master\\s20control.py poweroff 192.168.0.9 AC:CF:23:93:33:DC"}]

After a lengthy Idle period (60mins+) when toggling the block, its only processing the first command in the list.

So, 'Alexa, Lights On' only turns on 192.168.0.8, if i repeat myself 'Alexa, Lights On' 192.168.0.9 will also turn on.

If i then immediately call 'Alexa, Lights Off' they both turn off, however if its left with both lights on for a longer period (60 mins) I have the same problem with the Off command, only the first light is triggered.

Now after they've all been on/off immediately calling On/Off works fine and both items in list are processed as expected.

It appears that after a longer duration, the second command is dropped?

At first I thought this was do do with the time between calls, but this makes no difference.

I've attached the python script I'm using for other peoples reference.

source: https://github.com/glenpp/OrviboS20
[s20control.py.txt](https://github.com/bwssytems/ha-bridge/files/587319/s20control.py.txt)

Any suggestions?

**Comment by bwssytems** [comment]
What version of the ha-bridge are you running?

**Comment by merlin051** [comment]
3.2.2 running in windows environment

**Comment by bwssytems** [comment]
Let's turn on some debugging to see how the calls are working, read this: https://github.com/bwssytems/ha-bridge#the-logs-tab and turn on the Huemulator debug.

**Comment by bwssytems** [comment]
Any update?

**Comment by merlin051** [comment]
Apologies, my server has had some hdd issues.

I will get some debugging done when i can and post the logs.

**Comment by merlin051** [comment]
this is the logs from an event which only fired the first command.

all looks good:


11-30-2016 06:26:51.043	DEBUG	hue state change requested: JKA0H0DIvi2SyZ77gCVzWVeygXS5aiOldhVnL2M0 from 192.168.0.21 body: {"on": true}	com.bwssystems.HABridge.hue.HueMulator
11-30-2016 06:26:51.046	DEBUG	Exec Request called with url: [{"item":"exec://C:\\python27\\python C:\\ha-bridge-master\\s20control.py poweron 192.168.0.8 AC:CF:23:8D:2A:10"}, {"item":"exec://C:\\python27\\python C:\\ha-bridge-master\\s20control.py poweron 192.168.0.9 AC:CF:23:93:33:DC"}]	com.bwssystems.HABridge.hue.HueMulator
11-30-2016 06:26:51.047	DEBUG	Executing request: C:\python27\python C:\ha-bridge-master\s20control.py poweron 192.168.0.8 AC:CF:23:8D:2A:10	com.bwssystems.HABridge.hue.HueMulator
11-30-2016 06:26:51.082	DEBUG	Process running: true	com.bwssystems.HABridge.hue.HueMulator
11-30-2016 06:26:51.633	DEBUG	Executing request: C:\python27\python C:\ha-bridge-master\s20control.py poweron 192.168.0.9 AC:CF:23:93:33:DC	com.bwssystems.HABridge.hue.HueMulator
11-30-2016 06:26:51.635	DEBUG	Process running: true	com.bwssystems.HABridge.hue.HueMulator
11-30-2016 06:26:51.747	DEBUG	hue light requested: 1056028236 for user: JKA0H0DIvi2SyZ77gCVzWVeygXS5aiOldhVnL2M0 from 192.168.0.21	com.bwssystems.HABridge.hue.HueMulator
11-30-2016 06:26:51.748	DEBUG	found device named: Lights	com.bwssystems.HABridge.hue.HueMulator

**Comment by merlin051** [comment]
forgot to add, this is also running on 3.5.1 latest release.

I start the Jar using this bat file in windows:

@echo off
java -Xms32m -Xmx128m -jar C:\ha-bridge-master\ha-bridge-3.5.1.jar --upnp.config.address=192.168.0.1 --server.port=8080

**Comment by bwssytems** [comment]
interesting as it shows it did fire the second one in the log. Will investigate.

**Comment by RodrigoMusalem** [comment]
I am planning on running the ha-bridge on a Raspberry Pi. Would it possible to control the GPIO pins using custom executions? Any suggestions?

**Comment by audiofreak9** [comment]
Python GPIO.

**Comment by RodrigoMusalem** [comment]
Yes, thank you. I guess my question is where exactly in the HA-Bridge do I make the call to the python scripts I have to control the GPIO pins in the PI

**Comment by audiofreak9** [comment]
Command execution

https://github.com/bwssytems/ha-bridge/blob/master/README.md#script-or-command-execution

**Comment by merlin051** [comment]
i call a python script in my examples above, granted thats from windows enviroment, but shouldnt be too different for you in linux.

just swap my command+arguments  for your script.py

**Comment by RodrigoMusalem** [comment]
Thank you both. I will try that.

**Comment by bwssytems** [comment]
Closing until reoccurrence
