### ISSUE TITLE
Is HA  Bridge mainly for lighting controls? Can device category be customized?

### ISSUE THREAD

**Issue by dannieboiz** [bwssytems/ha-bridge#240]
I tried to add the Ecobee3 and Schlage locks and it comes up to be a switch. 

I also have dry contact switches acting as my garage and gate opener, when I say turn on all lights it opens my garage and my gate as well. Can device category be customized?

**Comment by bwssytems** [comment]
Everything is handled like a switch in essence as the ha-bridge emulates a Philips Hue Bridge. So you can control anything you want with what you put in the URLs, but is in the context of ON, OFF and DIM to the ha-bridge.

**Comment by bwssytems** [comment]
Did I answer your question?
