### ISSUE TITLE
possible issue with ip addresses

### ISSUE THREAD

**Issue by scargill** [bwssytems/ha-bridge#241]
UPNP and WEBSERVER address...  just for your attention, can't replicate this right now.. so I have this all setup controlling things - excellent incidentally.  Yesterday due to my own incompetence I blew the fuses. When the power came back up, everything was fine as it usually is - but HA-Bridge was not working. I noted in webserver address 0.0.0.0 and in UPNP a 169 address which I think is the default IP address that means bust.   I set them both back to the address of the Raspberry Pi running this and all was well.. but if this can happen - well, people do have power cuts.  Just wonder if this has anything to do with how you store stuff.

Pete.

**Comment by bwssytems** [comment]
So, it seems like you did not hit save after updating the address? Just a dumb question.

**Comment by bwssytems** [comment]
Tested this again and can't reproduce. Also, you are testing a dev version.

**Comment by bwssytems** [comment]
Have you seen this again?
