### ISSUE TITLE
add multiple functions per device

### ISSUE THREAD

**Issue by glacket** [bwssytems/ha-bridge#242]
Is it possible to add more functions per device? for example on my harmony hub, i would like to play pause stop turn on, turn off my tv. currently i can only turn on and off. If i want to setup pause or play, Etc. i need to create an additional device and call it a different name. I've tried grouping these together in the amazon alexa app, but it doesnt work correctly.

**Comment by bwssytems** [comment]
That is correct. Setting up different devices with different names. The Echo only sends on,off and dim to the bridge.

**Comment by bwssytems** [comment]
This is not a bridge issue
