### ISSUE TITLE
Clarify what "software Alexa" means in the README 

### ISSUE THREAD

**Issue by digiltd** [bwssytems/ha-bridge#245]
Hi, maybe it is just me, but I have only just understood what the following message is referring to.

> ATTENTION: This does not work with the software Alexa. That version does not have any capability for Hue Bridge discovery!

Thinking it was about the Alexa iOS/Android app I didn't pay much attention to it as it was working fine with my "software Alexa" :)

Can I suggest changing it to something like:

> ATTENTION: This requires a physical Amazon Echo, Dot or Tap and does not work with prototype devices built using the Alexa Voice Service e.g. [Amazon's Alexa AVS Sample App](https://github.com/alexa/alexa-avs-sample-app) and [Sam Machin's AlexaPi](https://github.com/sammachin/AlexaPi). The AVS version does not have any capability for Hue Bridge discovery!

**Comment by fauna5** [comment]
+1! Was very confusing.

**Comment by Dizlem** [comment]
To clarify the above does it work with the Amazon Alexa iOS app without a physical Echo (purchase pending)?  I have been unable to get the official Alexa app to see my HA Bridge yet other Hue apps have been able to find it.

Not sure if its an issue with UpNP or multicast packets on my network so would be good to get clarification either way.

**Comment by bwssytems** [comment]
Thanks for the re-wording. I just wanted to put in a quick note and appreciate the help.

As far as the software Alexa, they took out the upnp multicast discovery. It does not send out any multicast packets, period.
