### ISSUE TITLE
Help with this error message.

### ISSUE THREAD

**Issue by synack23** [bwssytems/ha-bridge#25]
synack23:~ owner$ java -jar  -Dupnp.config.address=192.168.0.13 -Dharmony.address=192.168.0.7 -Dserver.port=8081 -Dharmony.user=XXX@XXX.XXX -Dharmony.pwd=XXX /Users/owner/Desktop/ha-bridge-1.2.3.jar  
[main] INFO com.bwssystems.HABridge.HABridge - HA Bridge (v1.2.3) starting setup....
[main] INFO com.bwssystems.harmony.HarmonyServer - setup initiated ....
[main] INFO com.bwssystems.harmony.HarmonyServer - activity changed: [15689828] Watch Roku
[main] WARN com.bwssystems.HABridge.dao.DeviceRepository - Error reading the file: data/device.db - Does not exist or is not readable. continuing...
[main] INFO com.bwssystems.HABridge.devicemanagmeent.DeviceResource - HABridge device management service started.... 
[main] INFO com.bwssystems.HABridge.hue.HueMulator - Hue emulator service started....
[main] INFO com.bwssystems.HABridge.upnp.UpnpSettingsResource - Hue description service started....
2016-01-05 09:44:04.015:INFO::Thread-5: Logging initialized @3016ms
[Thread-5] INFO spark.webserver.JettySparkServer - == Spark has ignited ...
[Thread-5] INFO spark.webserver.JettySparkServer - >> Listening on 0.0.0.0:8081
2016-01-05 09:44:04.061:INFO:oejs.Server:Thread-5: jetty-9.3.z-SNAPSHOT
2016-01-05 09:44:04.092:INFO:oejs.ServerConnector:Thread-5: Started ServerConnector@970bf99{HTTP/1.1,[http/1.1]}{0.0.0.0:8081}
2016-01-05 09:44:04.092:INFO:oejs.Server:Thread-5: Started @3093ms
[main] INFO com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener starting....
[main] ERROR com.bwssystems.HABridge.upnp.UpnpListener - UpnpListener encountered an error opening sockets. Shutting down
java.net.BindException: Address already in use
	at java.net.PlainDatagramSocketImpl.bind0(Native Method)
	at java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:94)
	at java.net.DatagramSocket.bind(DatagramSocket.java:392)
	at java.net.DatagramSocket.<init>(DatagramSocket.java:242)
	at java.net.DatagramSocket.<init>(DatagramSocket.java:299)
	at java.net.DatagramSocket.<init>(DatagramSocket.java:271)
	at com.bwssystems.HABridge.upnp.UpnpListener.startListening(UpnpListener.java:42)
	at com.bwssystems.HABridge.HABridge.main(HABridge.java:106)
[main] INFO com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener Stopped

As far as I understand I use the address 192.168.0.13 (my computers address for the HA Bridge) and 192.168.0.7 (the Harmony Hubs address).

**Comment by bwssytems** [comment]
You have another program or an instance of the bridge already running. The port 50000 is already used by the other program and you cannot start this one. Look around on how to kill processes and stop it and retry.

**Comment by bwssytems** [comment]
Did this get resolved?

**Comment by bwssytems** [comment]
Closing this issue. Assuming it's resolved.

**Comment by akshayhuria** [comment]
Hi.

I'm facing the same error. I'm using echo, raspberry and an HC2(fibaro).

The point is that using the same equipment I'm trying to compare 2 different bridges, with one .jar from armzilla stored on one microSD and another one being from this site stored on a different microSD.

I ran the first one and the config panel was working perfectly, then i came across this .jar and tried setting up the bridge with a different SD, however encountered the error mentioned above. Both the codes being the same

I'm a bit new to this and need some help. TIA!

**Comment by akshayhuria** [comment]
The code after running shows - UPNP up and running, hence I'm not sure that if there is an error or not.

I was trying - http://localhost:8080/configuration.html and gave me a 404 - version 2.0.3.

however it was the panel for the 1st .jar(armzilla), however I read it just now that the config page is for our .jar's is- http://localhost:8080

can this be the reason?

**Comment by bwssytems** [comment]
You need to make sure that the ports are different for each of the bridges for the server port and the upnp response port. Read both instructions and adjust accordingly.
