### ISSUE TITLE
Mqtt returns a error message

### ISSUE THREAD

**Issue by micropet** [bwssytems/ha-bridge#251]
Hello,

a great idea to integrate mqtt, thank you.
If I enter the ip and the port of my mqtt broker and restart the bridge I get the following error:

Nov 19 10:01:35 d125 java[27331]: 2016-11-19 10:01:35.463:INFO:oejs.Server:Thread-15: Started @38383ms
Nov 19 10:01:36 d125 java[27331]: 2016-11-19 10:01:36,686 [main] INFO  com.bwssystems.harmony.HarmonyServer - activity changed: [-1] PowerOff
Nov 19 10:01:36 d125 java[27331]: 2016-11-19 10:01:36,690 [main] INFO  com.bwssystems.mqtt.MQTTHandler - Setting up handler for name: habridge
Nov 19 10:01:36 d125 java[27331]: Exception in thread "main" java.lang.NoClassDefFoundError: org.eclipse.paho.client.mqttv3.logging.JSR47Logger
Nov 19 10:01:36 d125 java[27331]: at org.eclipse.paho.client.mqttv3.logging.LoggerFactory.<clinit>(LoggerFactory.java:52)
Nov 19 10:01:36 d125 java[27331]: at org.eclipse.paho.client.mqttv3.MqttAsyncClient.<clinit>(MqttAsyncClient.java:87)
Nov 19 10:01:36 d125 java[27331]: at org.eclipse.paho.client.mqttv3.MqttClient.<init>(MqttClient.java:226)
Nov 19 10:01:36 d125 java[27331]: at com.bwssystems.mqtt.MQTTHandler.<init>(MQTTHandler.java:27)
Nov 19 10:01:36 d125 java[27331]: at com.bwssystems.mqtt.MQTTHome.<init>(MQTTHome.java:30)
Nov 19 10:01:36 d125 java[27331]: at com.bwssystems.HABridge.HABridge.main(HABridge.java:78)

**Comment by bwssytems** [comment]
Confirmed, looks like when I build in Maven, I have removed the logger class.

**Comment by micropet** [comment]
Ah great, thanks for the looking.

**Comment by bwssytems** [comment]
Found it, hate maven builds when you want to slim down the Jar by not including referenced items...except when the are down through discovery....

**Comment by micropet** [comment]
Now it works. Thank you.

Greetings Peter
