### ISSUE TITLE
Home Assistant - set media player volume via dim

### ISSUE THREAD

**Issue by GrubbyDungles** [bwssytems/ha-bridge#253]
Does anyone know how to set volume on a Home Assistant media player using dim?

I can manually specify a volume in the body part of the command as below (.6) and it works, but can't work out how to make it variable.

**Dim URL**
`http://localhost:8123/api/services/media_player/volume_set`

**Content Body Dim**
`{"volume_level":".6", "entity_id":"media_player.kitchen_avr"}`

After a bit of reading I think this should work but it doesn't seem to change - I can see the device react but it just sets the device volume to either 100% or 0% if Raw Input is below 35

**Content Body Dim**
`{"volume_level":"${intensity.math(X/255)}", "entity_id":"media_player.kitchen_avr"}`

Volume level once set directly in home assistant reports as a number between 0 and 1
`volume_level: 0.54`

**Comment by bwssytems** [comment]
So, Assuming that volume is between 0.0 and 1.0. you will need to use ${intensity.percent} and put a period before it to get anything below 1. It is kinda of a hack, but currently math does not do decimal values.

**Comment by GrubbyDungles** [comment]
Fantastic - this works perfectly.

Thank you for the help.
