### ISSUE TITLE
Different commands depending activities

### ISSUE THREAD

**Issue by d3smo** [bwssytems/ha-bridge#259]
I want to use a same command "Pause" for example but the http order sent will be different depending the activity launched, putting in pause the music for exemple if music is the current activity or pause the movie if movie is the running activity. Is there a way to do that actually, i search but didn't find, or could you think to add it in future releases.

**Comment by bwssytems** [comment]
First, I don't think "Pause" will work with the echo to control the philips hue api as it is a lighting interface. To test this, you would have to have a bridge device called "Pause" and I'm sure that would be a reserved word for the echo. Try it to control a light on or off, if it works maybe we can do something.

**Comment by audiofreak9** [comment]
I can attest that "pause" is a reserved Alexa word.  You may be able to say, "Alexa, turn on the pause light" with the word light specifically in you phrase.  If you find a device name that works, a hack might be to add all Harmony controlled device pause commands in one ha-bridge Harmony button.  This way the command works no matter which playback device is on.

**Comment by d3smo** [comment]
Right i did not figure out that Echo could have reserved words such as Pause. To be honest i'm anticipating a little bit my configuration, i still not have my echo, i hope receiving it this week. But i totally understand the limitation. So about my specific question, to be more precise what i need is to send a pause command to the same machine my Home Cinema Computer, one command will be to send pause command to Foobar for pausing the music and Sending pause to Kodi when activity is Kodi. But understanding the limitation you've mentioned, the solution could be to create to device called "Pause music" and "Pause movie" and call them telling "Alexa Turn On Pause music" or "Alexa Turn On Pause movie". I've got to try these when i'll have my Echo. Thanks for your replies, i close the topic.
