### ISSUE TITLE
Multiple commands

### ISSUE THREAD

**Issue by vitycent** [bwssytems/ha-bridge#26]
Sorry for the noob question.  Is there any way to run multiple commands with a single voice activation?  I'm mainly looking at the harmony hub.  I want to send multiple volume up commands or change a change by saying turn on ESPN and the hub would send out the channel numbers.  I know I can create activities to just change to the specific but that just clusters up my remote screen.

**Comment by bwssytems** [comment]
Activities are the way it currently can be done. I haven't yet gotten to the point where others have asked for this as they are using the Activity method or use the harmony control through the vera and use scenes.

**Comment by audiofreak9** [comment]
I would like this option, especially to send multiple volume up/down with one 'button' in the ha-bridge.  I was going to pursue this, couldn't we just add multiple commands to the option ourselves, kinda like clicking the Harmony Remote's volume up multiple times.

**Comment by bwssytems** [comment]
Will need to look into this as the builder doesn't have a way to stack yet. It's easy to put into a description to execute though as a manual edit.

**Comment by audiofreak9** [comment]
If I can manually edit to send multiples of the same command to the Harmony Hub, then I'd be good to go!  Excuse my lack of knowledge interacting with the Harmony, how would that look given I already have a Harmony Button on the bridge defined with 'On' as {"device":"32829111","button":"VolumeUp"}?  I'd like to send 2 or 3 'VolumeUp' commands successively.

**Comment by vitycent** [comment]
This would be very exciting if we had this feature!  Thanks for all your hard work.  The bridge is working wonderfully otherwise with my echo and harmony hubs.

**Comment by rafale77** [comment]
Interesting requests. The bridge would have to send multiple commands with a delay between each. I currently have volume setup but one button push at a time by calling "turn on" and "turn off" the "TV volume" on the Harmony. It isn't very practical. With the Sonos, using the an http-sonos bridge and this bridge I am able to use the volume as a dimmer (ie. "set the sonos to 50"). The Harmony only handles one command at a time unless an activity is set. I have set activities to change channels on my cable box ("turn on NBC" for example) and linking the activities to the bridge but the harmony goes through the entire setup of all the devices input so it is quite slow (have to set inputs for the TV and the receiver). It is not able to recognized that it already on the correct inputs from the previous activity called like it does for the power status.

**Comment by lynchhj1** [comment]
I'd would also like the option.  I tried to do it manually but neither one executed.

{"activity":[
{"device":"33325887","button":"VolumeUp"},
{"device":"33325887","button":"VolumeUp"}
]}

**Comment by bwssytems** [comment]
This development is done and in testing. It works like a charm and there is a builder capability. The syntax is not the same as you show though.

**Comment by audiofreak9** [comment]
I'll beta test if needed.

**Comment by drussmiller** [comment]
Is there a way to set a delay between command, like delay 1 sec? the TV isn't responding quick enough and command are getting skipped.
