### ISSUE TITLE
Additional Commands not working. Lock and Unlock aren't recognized as valid commands like the Read-Me says it is

### ISSUE THREAD

**Issue by SpartanTech** [bwssytems/ha-bridge#262]
Is there something I have to do enable the lock or unlock command? I saw on the ha-bridge Read-Me that lock and unlock are supported, but even though I can use 'turn on the front door' or 'turn off the front door', it won't let me do 'lock the front door'. I'm using Alexa.

Is there something else I have to have configured?

**Comment by bwssytems** [comment]
Unfortunately, that list changes as Amazon updates their software for the Echo and reserves those words for other devices. You will have to stay with on and off.

**Comment by bwssytems** [comment]
Does this answer your question?

**Comment by SpartanTech** [comment]
yes, it does unfortunately. hopefully a solution comes later on because it really sucks to regress features :/
