### ISSUE TITLE
Harmony Setup

### ISSUE THREAD

**Issue by mmontier** [bwssytems/ha-bridge#263]
Setup harmony IP address, email, and password.  Don't see any activities.  What is the process to debug?  I see this error message in the logs:  Cannot get harmony client (Harmony) setup, Exiting with message: Failed to parse response from Logitech auth service

**Comment by digiltd** [comment]
Are you using the latest version 3.5.1?

This was an issue (see #246) but was quickly patched

**Comment by bwssytems** [comment]
Upgrade to V3.5.1

**Comment by mmontier** [comment]
I downloaded and installed on Saturday. 


Thanks for getting back to me so quickly. I'll check when I'm home tonight. Thanks

**Comment by mmontier** [comment]
I checked and I downloaded 3.5.1.  However, oddly, when I am on the webinterface and click on "About" Ha-Bridge it says 3.2.2

**Comment by bwssytems** [comment]
You either have the previous version running or the startup script was not changed to call the new version.

**Comment by mmontier** [comment]
Yea, it appears that somehow I pulled 3.2.  3.5.1 seems to have the harmony activities.  Thanks!
