### ISSUE TITLE
Any info about how multiple commands can be used?

### ISSUE THREAD

**Issue by digiltd** [bwssytems/ha-bridge#265]
I have successfully tested how to use the "count" and "delay"

` [{"device":"31028313","button":"3","delay":100,"count":10}]`

It would be very handy to be able to use `${intensity.percent}` as the count value so we can  dynamically alter the count. Is it possible?

`[{"device":"31028313","button":"3","delay":100,"count":${intensity.percent}}]`

I have tried but not sure if it my syntax or if it is simply not possible.

**Comment by bwssytems** [comment]
I'll have to add that into the button calls. I am reworking how the structure is used across all device types, so this can be done.

**Comment by Manideepydder** [comment]
![screenshot 72](https://cloud.githubusercontent.com/assets/22833621/20556476/506f0334-b18d-11e6-8e35-41ed7fa5c313.png)
 Hello ..I had tried HABRIDGE 3.1.0 it was working well but when i was doing the same with ha-bridge-3.5.1 its giving the error which i had attached. Is HAbridge 3.5.1 supported by RPI with Rasbian???

**Comment by Juppers** [comment]
I'd like to see ${intensity.byte} be available as well.

**Comment by bwssytems** [comment]
@Juppers  It will be all replacement types and math included.
