### ISSUE TITLE
Do HA BRIDGE 3.5.1 works with RPI

### ISSUE THREAD

**Issue by Manideepydder** [bwssytems/ha-bridge#267]
Hello ..I had tried HABRIDGE 3.1.0 it was working well but when i was doing the same with ha-bridge-3.5.1 its giving the error which i had attached. ![screenshot 72](https://cloud.githubusercontent.com/assets/22833621/20556801/be735974-b18e-11e6-9615-121b5787d9c5.png) Is HAbridge 3.5.1 supported by RPI with Rasbian???
![image](https://cloud.githubusercontent.com/assets/22833621/20558571/af0d315a-b196-11e6-8045-c66c50a50672.png)

**Comment by digiltd** [comment]
Works fine for me. Make sure the port you are trying to use is free.

`sudo lsof -i -n -P | grep TCP`

will list your port use

if in doubt, reboot

**Comment by princefisher** [comment]
Hi there,
I had the same problem just last night. Have you tried running habridge with sudo? 
That fixed it for me.
Regards

**Comment by Manideepydder** [comment]
It shows "Invalid or corrupt Jarfile" when i tried to run the bridge with "java -jar ha-bridge-3.5.1.jar".
Do you have any idea ??

**Comment by bwssytems** [comment]
Download it again, transmission issues.

**Comment by Manideepydder** [comment]
Tried but i didn't worked.
