### ISSUE TITLE
User authentication...

### ISSUE THREAD

**Issue by emigrating** [bwssytems/ha-bridge#270]
I know there are ways around this already, but I'm moving virtual machines around and want to lighten the load a little so...

Is there a way to actually authenticate users directly? As in, I currently use HA-Bridge with my existing Amazon Echoes and Dots, but I also use it via IFTTT using the maker channel to have lights turn on when my Ring doorbells or stick-up cams sense motion, change the hue somewhat depending on temperature and so on.

The way I currently do this is by using an intermediate host, which takes a json input (if the sender is authenticated) and calls the correct /api/username/lights/nnnnnnnnnn/state URL.

It works, but like I said, I'd like to lessen the load so it'd be great to be able to call this directly from IFTTT (or similar services). The way I envision this is to run the open API as is (for Echo/LAN use) but have it available on a separate port where you'd have to authenticate (just using a randomly generated ID would work). That way I could simply forward the locked down port and I could use the maker channel to send commands directly rather than going thru the intermediary.

Am I making sense? Any plans to implement anything like this?

**Comment by bwssytems** [comment]
So, this is the HUE api and it uses the username key. But this implementation to make it easier for most, it takes in whatever username is passed as on a real hue hub, you have to actually push the button. I would have to see what it would be to have the as a setting.

**Comment by bwssytems** [comment]
So, I am going put this in has the whole UI security. There will now be a button to register a device just like a real hue and the UI will be locked if this is used by password. There will also, be the option to lock the REST API by password as well.
