### ISSUE TITLE
Dynamic Timestamp in HTML 'Body'

### ISSUE THREAD

**Issue by bellissimo** [bwssytems/ha-bridge#271]
I was hoping to call an Alexa Skill (which is running locally on my server but can also be called externally from an AWS Lambda) which takes an HTTP POST request. However the service requires a timestamp in the JSON body to help validate the request. So it would be good if we could have a dynamic insertion for a standard ISO 8601 timestamp:

    e.g. {yyyy-MM-ddTHH:mm:ssXXX}

This would be ideal in the Body and may also be useful for the URL.

**Comment by bwssytems** [comment]
I'll put this on the list.

**Comment by bwssytems** [comment]
Using the format options in the Java Date Formatter with the replacement tag of ${time.format(xxxx)} and xxxx is a format string from this https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html

Your example above works and would look like this  ${time.format(yyyy-MM-ddTHH:mm:ssXXX)}
