### ISSUE TITLE
hue passthrough requires link button press on reboot

### ISSUE THREAD

**Issue by npgauth** [bwssytems/ha-bridge#273]
Hello,
I love this project--extremely useful!

One problem I cannot seem to solve is that rebooting / restarting ha-bridge requires that we re-press the link button on our hue bridge in order to enable passthrough control of the hue lights. Upon pressing the link button, all is well again, but this is not optimal if the power ever goes out or just for general reboots.

Here are the two errors that popup on the server:
  1. Popup seen on the website states: "Request Error, Pleae look in your habridge log: error {"type":101,"address":"","description":"link button not pressed"}"
  2. Logs record "registerWithHue needs link button pressed on HUE bridge: living room primary".

Any idea how to get a more "permanent" registration saved in the config file or db so that the link button doesn't need to be pressed every time the software restarts?

Thanks and keep up the good work!
Nick

**Comment by bwssytems** [comment]
I should put a note out there, if you do a save in the bridge control tab after you have all controllers attached to the ha-bridge, it will save all the usernames it has accumulated. The press the button issue wont occur again for the ha-bridge.

**Comment by npgauth** [comment]
I still can't seem to get it to stick. Here is the procedure I followed:

1. Start with a fresh startup (i.e., no data folder)
2. In the web user interface add IP address and name ("myhue") in the "Bridge Control" form.
3. Click "Save". Bridge reinitializes and "Hue Devices" tab appears.
4. Press the physical link button on my Hue bridge.
5. Click on the "Hue Devices" tab--all Hue lights appear in the list. As I understand from the hue api, this means the handshake between ha-bridge and the hue bridge worked, and ha-bridge should now have a username.
6. Click on the "Bridge Control" tab and click "Save".

When re-entering the "Hue Devices" tab, the lights no longer appear in the list and the "Logs" show the error "registerWithHue needs link button pressed on HUE bridge: myhue". Adding a light (i.e., add bridge device) before performing the save does not help.

Am I performing the steps in the correct order? Are you sure the hue bridge-provided username is being set and reused from the database?
Thanks! Nick

**Comment by bwssytems** [comment]
Ahh, did not realize you were using the passthrough. That's interesting as the real bridge should be OK as i use the same ID to it Everytime as the user it needs. Will take a look.

**Comment by nawaidrana** [comment]
I have same issue, I have to press button on hue bridge everytime I need to reboot my raspberry pi.

**Comment by volcan96** [comment]
Just dropped in to say same here. Similar setup as OP. On reboot I have to press relink on the hue.

**Comment by ph4x0** [comment]
And the same here after restart. :)

**Comment by bwssytems** [comment]
Well, on restart there is no saved userid for that Hue. I will look into a way to save that for each hue. It will still have to be once.

**Comment by bwssytems** [comment]
Looks like there is a way and will take a one more step after you get the bridge linked to the hue hub, you will have to go to the bridge control tab ant hit save when it is done.
