### ISSUE TITLE
Controlling insteon lights/dimmer

### ISSUE THREAD

**Issue by nawaidrana** [bwssytems/ha-bridge#274]
I'm currently using ha bridge to turn on insteon dimmers, I have an old insteon hub, so I am using http commands to turn on and off, which works find, but dimming doesnt seem to work.

I used insteon.js previously with homebridge (via siri) and dimming worked perfect with that  application, but I am trying to us ha-bridge for google home now, so it will be great if we can somehow get dimming to work for this application as well.

**Comment by nawaidrana** [comment]
BTW, here is the site through which you can generate http commands. Look at how dimming changes the 2 digit XX after 0F11

http://www.smarthome.com.au/smarthome-blog/insteon-hub-http-commands/

This site below also contains the brightness table which tells 2 digit dimmer code:

http://www.insteon.com/support-knowledgebase/2015/4/9/control-your-insteon-hub-from-your-android-wear-device-using-tasker

**Comment by bwssytems** [comment]
If you take a look at the README, there are the commands for passing the Echo's dimming values by using ${intensity.percent} OR ${intensity.byte} OR ${intensity.math(X/2)}. Look through that and may give you direction

**Comment by bwssytems** [comment]
Is this answered?
