### ISSUE TITLE
Save Settings Error: undefined with status: Server Error - 500

### ISSUE THREAD

**Issue by x0x0Atreyux0x0** [bwssytems/ha-bridge#277]
I have tried rebooting / port 80 port 30 / relading / changing my config file to sudo etc. 

i still end up with the error Save Settings Error: undefined with status: Server Error - 500 evertime i try to save a change to the hub. 

Not to mention that Alexa is not connecting to the Bridge. 

Please assist.

**Comment by bwssytems** [comment]
So, you need to set your paths for the config file to somewhere where it has access. This has been answered before. Search the closed issues.

**Comment by bwssytems** [comment]
Is this corrected?

**Comment by x0x0Atreyux0x0** [comment]
I have not tried at this time

**Comment by x0x0Atreyux0x0** [comment]
I moved out of root and chroot = 777 this still  does not work. Error the same.

**Comment by bwssytems** [comment]
Take a look at this guide....

https://timleland.com/wireless-power-outlets/
