### ISSUE TITLE
Cant use Open, close or shut

### ISSUE THREAD

**Issue by narcosi** [bwssytems/ha-bridge#280]
I have the bridge connected to my HC2 - its amazing

but i have to say turn on to open my garage door and turn off to close it

it doesnt seem to like the alternative words you described such as on, off or shut

do i need to enable these? or add them?

thanks

J

**Comment by bwssytems** [comment]
Sorry, these are reserved words by amazon. We have no control over this. I need to update the documentation.

**Comment by narcosi** [comment]
That makes sense - though it's weird that they expect home automation to work without words like open and close.

Do you have a list or understanding of what phrases do and don't trigger the home automation devices and what we can use to come up with sensible phrases

**Comment by bwssytems** [comment]
I will be changing the doc to be just on, off, set, and dim, brighten. As for the device name, you will have to experiment.
