### ISSUE TITLE
HABridge stops running after awhile

### ISSUE THREAD

**Issue by djentor** [bwssytems/ha-bridge#281]
Have it all setup and working on raspberry pi, but after about an hour it stops working. If i run the command to start the .jar again it starts working again for another hour or so.

Am I missing something to keep it running, in the habridge config, or perhaps some configuration on the pi?

**Comment by djentor** [comment]
Also noticed that when I run the command to start it appears to hang or not complete or something. See screenshot. 
![screen shot 2016-11-27 at 7 35 04 pm](https://cloud.githubusercontent.com/assets/24214359/20653262/bf578b10-b4d8-11e6-9a55-8a9a073f41d2.png)

**Comment by Pseudomizer** [comment]
I had the same issue. I upgraded Rasperian to latest updates and distribution upgrades. That didn't make it go away completely, but from before hanging 4 or 5 times a day, it only happens every 2 days now. 
I noticed a massive delay sometimes from command said and execution and most of the times Alexa did say that the device is not responding, while it just did. Seems to go beyond certain timeout values.

**Comment by bwssytems** [comment]
Why not set this up int he systemctl startup so this can be managed. Look at the README.

**Comment by djentor** [comment]
@bwssytems I would, but I didn't exactly understand how to do that. Is there a step by step available somewhere for setting up systemctl?

**Comment by audiofreak9** [comment]
You can follow the instructions on my website: http://coreyswrite.com/tips-tricks/amazon-echo-x10-home-control-updated/#reboot

**Comment by bwssytems** [comment]
Is this answered?

**Comment by djentor** [comment]
@audiofreak9 Followed your steps but got following results:

root@raspberrypi:/etc/systemd/system# systemctl status habridge.service -l
● habridge.service - HA Bridge
   Loaded: loaded (/etc/systemd/system/habridge.service; enabled)
   Active: failed (Result: exit-code) since Fri 2016-12-02 05:45:47 UTC; 37s ago
 Main PID: 3737 (code=exited, status=1/FAILURE)

Dec 02 05:45:47 raspberrypi systemd[1]: Started HA Bridge.
Dec 02 05:45:47 raspberrypi java[3737]: Error: Unable to access jarfile Djava.net.preferIPv4Stack=true
Dec 02 05:45:47 raspberrypi systemd[1]: habridge.service: main process exited, code=exited, status=1/FAILURE
Dec 02 05:45:47 raspberrypi systemd[1]: Unit habridge.service entered failed state.

**Comment by djentor** [comment]
Even though I get the error above when checking the service it appears to be working anyway. At least it has stayed running over night which it usually doesnt.

**Comment by bwssytems** [comment]
If it's running, it is not running in the service as the error showed it failed as you don't have a "dash" in front of the "D" and it thinks the parameter is the jar file.
