### ISSUE TITLE
Confused by Harmony

### ISSUE THREAD

**Issue by narcosi** [bwssytems/ha-bridge#282]
I am sure i am being dumb

I entered what i think is my harmony IP address (which i cant seem to verify anywhere other than doing IP scan for port 5222 (any better ideas?)

when i call this on my Bridge: http://192.168.20.154/api/devices/harmony/show

i get [] back

i see nothing on the harmony pages on the bridge

help

**Comment by digiltd** [comment]
Your Harmony IP can be seen using the Harmony app: Menu > About > Versions

**Comment by narcosi** [comment]
Thanks, found it - i did have it correct then from the scan.

what should i see when i add it to the bridge? - it doesnt show any devices etc

**Comment by digiltd** [comment]
After you add the Harmony Hub in the Bridge Control tab (and saved it) do you then see the two tabs for Harmony Devices and Harmony Activities?

**Comment by narcosi** [comment]
yes

**Comment by digiltd** [comment]
And when you click on them you see nothing?

Can you confirm your HA Bridge Version number (found in the "About" dropdown at the top of the page)

**Comment by narcosi** [comment]
![image](https://cloud.githubusercontent.com/assets/24214357/20667010/08f4db16-b55f-11e6-849c-d12115961e95.png)

yep nothing

3.5.1

**Comment by digiltd** [comment]
I expect you already have rebooted the machine running HA Bridge?

What version Harmony Hub are you running (found in the same place as the Harmony IP)? I am running 4.12.36

**Comment by narcosi** [comment]
same version

So i rebooted everything and deleted it all and added it again and now it works - who knows :)

thanks for your help
