### ISSUE TITLE
Removing one Harmony scene killed everything

### ISSUE THREAD

**Issue by xbmcnut** [bwssytems/ha-bridge#284]
I had a Harmony scene under 3.2.2 called 'Everything' which activated the turn off all devices (-1) on the Harmony remote. This worked flawlessly on Echo, but caused a problem on Google Home as it decided that 'Everything' was all 17 light bulbs, one of which was my Vera garage door controller scene so saying "Turn off Everything" cycled the garage, not amusing my wife at 11:45pm.

Last night I simply removed the ha-bridge entity called 'Everything' and that's when everything died. I now can get the following errors when poking around the interface:
```
Cannot get devices from habridge: undefined with status: Not Found - 404
Get Backups Error: undefined with status: Not Found - 404
Get Vera Devices Error: undefined with status: Not Found - 404
Get Vera Scenes Error: undefined with status: Not Found - 404
```
I've pretty much cleaned everything out, rebuilt the service, tried 3.5.1, went back to 3.2.2 and those errors are persistent. Is there some cache somewhere that is preventing ha-bridge from working. Can you advise how I debug those errors and how I clean everything out and start again?

**Comment by bwssytems** [comment]
How did you remove that entity?

**Comment by xbmcnut** [comment]
From the actions menu. Test On, Test Dim, Test Off, Edit/Copy, Delete. I chose Delete. For the life of me I cannot get it working now. 404 errors everywhere. Deleted all folders and started again with 3.5.1, still no go.

**Comment by bwssytems** [comment]
Well that is very odd. You need to go through your setup and also check that there is not another instance running now.

**Comment by xbmcnut** [comment]
Yes, it is odd but I stumped now. How do I tell if there is more than one instance running?

**Comment by xbmcnut** [comment]
pi@raspberrypi:~/habridge $ sudo systemctl status habridge.service -l
● habridge.service - HA Bridge
   Loaded: loaded (/home/pi/habridge/habridge.service; enabled)
   Active: active (running) since Tue 2016-11-29 10:16:28 NZDT; 2min 1s ago
 Main PID: 1878 (java)
   CGroup: /system.slice/habridge.service
           └─1878 /usr/bin/java -jar -Dconfig.file=/home/pi/habridge/data/habridge.config /home/pi/habridge/ha-bridge-3.5.1.jar

Nov 29 10:16:34 raspberrypi java[1878]: Exception in thread "main" java.lang.NullPointerException
Nov 29 10:16:34 raspberrypi java[1878]: at com.bwssystems.HABridge.dao.DeviceRepository._loadRepository(DeviceRepository.java:63)
Nov 29 10:16:34 raspberrypi java[1878]: at com.bwssystems.HABridge.dao.DeviceRepository.<init>(DeviceRepository.java:49)
Nov 29 10:16:34 raspberrypi java[1878]: at com.bwssystems.HABridge.devicemanagmeent.DeviceResource.<init>(DeviceResource.java:50)
Nov 29 10:16:34 raspberrypi java[1878]: at com.bwssystems.HABridge.HABridge.main(HABridge.java:80)
Nov 29 10:16:34 raspberrypi java[1878]: 2016-11-29 10:16:34,850 [Thread-0] INFO  spark.webserver.JettySparkServer - == Spark has ignited ...
Nov 29 10:16:34 raspberrypi java[1878]: 2016-11-29 10:16:34,862 [Thread-0] INFO  spark.webserver.JettySparkServer - >> Listening on 0.0.0.0:80
Nov 29 10:16:34 raspberrypi java[1878]: 2016-11-29 10:16:34.881:INFO:oejs.Server:Thread-0: jetty-9.3.z-SNAPSHOT
Nov 29 10:16:35 raspberrypi java[1878]: 2016-11-29 10:16:35.375:INFO:oejs.ServerConnector:Thread-0: Started ServerConnector@5787d9{HTTP/1.1,[h    ttp/1.1]}{0.0.0.0:80}
Nov 29 10:16:35 raspberrypi java[1878]: 2016-11-29 10:16:35.383:INFO:oejs.Server:Thread-0: Started @6664ms

**Comment by bwssytems** [comment]
You need to start here /home/pi/habridge/data/, and see what is in this directory. Also, you should do a sudo systemctl stop habridge.service.

**Comment by xbmcnut** [comment]
habridge.config is the only thing in /data. When I do a bridge test, I get "_Problem accessing /api/devices. Reason: Not Found_". habridge can no longer 'see' my Harmony or Vera and chucks up "Get Harmony Activities Error: undefined with status: Not Found - 404"

**Comment by xbmcnut** [comment]
From the logs, I have this
```
11-29-2016 10:42:34.475 	INFO 	setup initiated .... 	com.bwssystems.harmony.HarmonyServer
11-29-2016 10:44:17.471 	INFO 	activity changed: [-1] PowerOff 	com.bwssystems.harmony.HarmonyServer
```
Oddly, the last line is the activity I deleted. Where could that be coming from?

**Comment by xbmcnut** [comment]
Is there some detailed logs I can send you?

**Comment by bwssytems** [comment]
No, that is not a deleted activity, the ha-bridge just shows the current activity on the hub. The logs are in /var/logs/syslog. The errors you received before from the UI show that you either have a new IP on the ha-bridge or it was not running.

**Comment by xbmcnut** [comment]
But I can connect to the webpage and add Vera and Harmony devices. Does that not mean it's running? The Pi has a static IP and that has not changed. I might try an install on another Pi and see what happens.

**Comment by xbmcnut** [comment]
Looks like something funky has happened to my Pi? My MQTT broker which is part of the Home Assistant VENV install is not working either so maybe something else is going on? HA is working fine though.

**Comment by bwssytems** [comment]
Dumb question... Do you have static IPs for your devices on your network? Always a culprit.

**Comment by xbmcnut** [comment]
Yep, all IoT devices on my network have DHCP reservations.

**Comment by bwssytems** [comment]
Without poking around your network, you'll need to do some digging, sorry.

**Comment by xbmcnut** [comment]
Yes, something strange has happened which may have just coincided with the deletion of the Harmony scene. It will take me longer to debug than to rebuild the entire system so here we go...

**Comment by audiofreak9** [comment]
I'd try apt update and upgrade before entire redo...

**Comment by xbmcnut** [comment]
Used the HASSBian image for a clean install on a new Pi and everything working again. Something obviously wrong with my TCP stack on my live system? To hard to debug for this noob. Update and upgrade did not fix my problem. Going to rebuild my live system now.

**Comment by xbmcnut** [comment]
Thanks for the prompt feedback.
