### ISSUE TITLE
ifttt not supported?

### ISSUE THREAD

**Issue by tuspam** [bwssytems/ha-bridge#285]
When I add Hue to IFTTT then receive "This Action will turn on your hue lights.  Which lights? * Loading..."

It's because impossible link bridge to https://www.meethue.com/en-us/user/linkbridge

**Comment by audiofreak9** [comment]
The ha-bridge emulates a Phillips HUE Bridge on your local network.  Linking a Phillips HUE account with IFTTT does not link your ha-bridge to IFTTT.  A Phillips HUE account does not connect to the ha-bridge.

**Comment by bwssytems** [comment]
As audiofreak9  mentioned, this bridge is not connected to meethue.com since this is not made by Philips. Closing.
