### ISSUE TITLE
Cannot Connect Via Android App forced port?

### ISSUE THREAD

**Issue by TechBiscuit** [bwssytems/ha-bridge#286]
Hi, I downloaded this in the unraid community apps section and left all the defaults except changing the server IP, the docker is started and I can access the GUI page however I have tried using multiple apps to connect to the bridge with no luck.

The most success I have had is with Hue4All which can see the bridge but when I click connect I receive the following error,

Not Connected:  Selected Philips Hue Bridge with Ip address xxx.xxx.x.xxx is not responding.Try again to connect or search or continue in offline mode.

I know im on the right path as changing settings or stopping the docker makes the Hue4All app not detect any bridge at all so the fact I can see it is good.

I have read about port 80 for apps to access the bridge but I have noticed in the GUI the following settings:

Web Server Port	
3080
UPNP Response Port	
50000

Also when I try to change the 3080 port to 80 or 8080 and click save it reverts back to 3080 is this normal or ok?

I have found in the config folder the following files:
ha-bridge-3.5.1.jar  /// unsure how to edit.
ha-bridge.log
and a data folder with habridge.config

If anyone has any ideas how to solve this issue be great, the end goal is to have the hue bridge see my Hue White Ambient light bulb (plugged into a B22 socket fitting) and have Alexa talk to the bridge to then send on and off to the bulb.

**Comment by Pseudomizer** [comment]
Change the port in your startup script when you call the jar file. See options for launching HA bridge in the documentation. Hope this helps.

**Comment by audiofreak9** [comment]
Most apps that connect to real a HUE Bridge have port 80 hard coded, once I used port 80 I was able to use most apps.

**Comment by TechBiscuit** [comment]
So it is def a port 80 redirect issue then, right so I need to edit the Jar file under config folder in unraid in order to point to port 80 direct yes?, how would I go about that? Im not used to editing Jar files at all. 

Also in the data folder with habridge.config it does say port 8080 but in the web gui still says 3080

**Comment by aptalca** [comment]
You should have mentioned that you are using the docker container.

Don't change the port in the web ui. Change the container settings in the unraid gui and change the environment variable `SERVERPORT` to 80.

**Comment by aptalca** [comment]
Umm, actually, it's more complicated since you're on unraid. See, unraid gui runs on port 80, so the container won't start with that setting unless you somehow move the unraid gui to a different port (I believe it is possible but I have no idea how)

**Comment by TechBiscuit** [comment]
Ah ok I thought it needed to be changed in the web UI, Ill give your suggestions a go.

**Comment by TechBiscuit** [comment]
Hey again, yea seems you were right I changed the port for Unraid temp to 81 and restarted and also added 

Container port that seemed to be missing
WebUI:	
8080

Now when  navigate to IP:80 i can see the GUI and also the device pops up in the Hue4All app it now recognized the bridge, however it now asks that I press the button on the bridge in order to authorize the app access, how would I do this as there is no physical button and I do not see an option for it in the web GUI , many thanks so far.

**Comment by audiofreak9** [comment]
The ha-bridge is coded such that it emulates the button being pressed constantly.  Is there an ok or proceed option on the app?

**Comment by TechBiscuit** [comment]
Ah great, no there wasn't a button but when i read this I tapped the back button and it threw me into the app so it bypass the press a physical button, Now I can access the features, hopefully I can now add my bulb back into my B22 socket and sync my lights up, I wont be able to test this until later but yea you have all helped me out and Ive learned a few little tricks so thanks to everyone so far, fingers crossed the rest is easy sailing.

**Comment by TechBiscuit** [comment]
Hey again so new update, Ive plugged in my pug into a lamp right next to the router as Ive read setup distance can affect discovery of lights. However I have managed to get into the hue app and connect to the bridge it now says you are connected to Hue Bridge and says there's an update available but it wont let me do anything other than press update.

This starts the orange update progress bar but 2 seconds in it rolls back and says "ouch the update failed to install please try again" I have used other apps to search for the light and tried adding the serial number but no joy any thoughts?, I feel so close!

I have tried restarting the container and unraid prior to doing this 

Key 1:	
xxx.xxx.x.xxx
Container Variable: SERVERIP
Key 2:	
80
Container Variable: SERVERPORT
WebUI:	
80
Container Port:

**Comment by audiofreak9** [comment]
The _NEW_ HUE app doesn't work with the ha-bridge, it requires the ability to store room information on the real HUE Bridge, which the ha-bridge does not replicate.  Also, the coded software version the ha-bridge is emulating needs updated so the _NEW_ HUE app gets past the "Update software" prompts.

BUT you can download the _OLD_ HUE app, it works perfectly.

**Comment by TechBiscuit** [comment]
Ok I have stopped using that app and am now using the old one, I can find the bridge ok and it says its fine, I still cant find light when auto searching ot manual searching via the serial number. 

Ive checked make sure that the bridge is being seen on port 80 but the app just cant find it for some reason, is there anything I need change in the web ui my current settings are >

Setting	Value
Configuration Path and File	
data/habridge.config
Device DB Path and File	
data/device.db
UPNP IP Address	
xxx.xxx.x.x.xx
Web Server IP Address	
xxx.xxx.x.x.xx (same as IP)
Web Server Port	
80
UPNP Response Port	
50000


My unraid docker has these settings:


Network Type:	
Privileged:	OFF
Key 1:	
xxx.xxx.x.xxx
 Edit Remove
Container Variable: SERVERIP
Key 2:	
80
 Edit Remove
Container Variable: SERVERPORT
Host Port:	
80
 Edit Remove
Container Port:

 Hide advanced settings ...
AppData Config Path:	
/mnt/user/appdata/Home-Automation-Bridge
 
Container Path: /config


The only other thing if these settings are correct would be a faulty bulb maybe, Ive ordered a color changing one now which should be here tomorrow so I can see if that's the problem, im gonna try a few more times today with this one though, see if three's any little setting not right, if anyone has any more suggestions meantime.

**Comment by TechBiscuit** [comment]
Seems my order shipped a day early, so Ive just tested a color bulb but still the same result, I have also tried removing the docker image and starting over but app still cant find bulbs.

**Comment by bwssytems** [comment]
Ok, dumb question... Are you trying to use the bridge to control a real hue bulb without a real hue bridge?

**Comment by TechBiscuit** [comment]
Yea, so does that mean I need another piece of hardware for this to work? I thought this would bridge my bulbs as it were and sync up to harmony hub, is that not the case or have I goofed a little.

**Comment by bwssytems** [comment]
Unfortunately, this is not a controller for actual hue bulbs. It is an API emulator to allow it to look like a Real Philips Hue Bridge to be able to call out to different systems. You will need to buy a Real Philips Hue Bridge to control your lights. Closing

**Comment by TechBiscuit** [comment]
Ah ok so this will then allow me to connect to my harmony hub and the hue hub and bulbs no problem, I missed that one, thanks Ill grab one of those and then we should be good to go.
