### ISSUE TITLE
All devices are "Lux Light" for google home and echo

### ISSUE THREAD

**Issue by tuspam** [bwssytems/ha-bridge#287]
I got problems with controling devices via google home and amazon echo. All devices are "Lux Light" but i got connected to ha bridge difrent types for example blinds and when I say turn off all lights my blinds go down to. It's any way to change in ha bridge device type?

**Comment by bwssytems** [comment]
Unfortunately, for compatibility reasons, it needs to return back a Hue Light type, and Lux is selected as there is only on, off and dim available.

**Comment by tuspam** [comment]
Only on, off and dim available it's not a problem for me, problem it's with only one type ""Lux Light". I got a lot devices not a light type and it's hard to voice control them. Thanks any way. Very good job.

**Comment by bwssytems** [comment]
Yep, just stuck with what the HUE api gives to make this compatible. Closing.
