### ISSUE TITLE
Alexa was not able to discover devices on the Hu bridge (Raspberry Pi-3)

### ISSUE THREAD

**Issue by AnantaCreation** [bwssytems/ha-bridge#289]
Hi,
I have brought Amazon Echo Dot and successfully integrated with Fibaro HC-2 using Raspberry Pi-3.

Similar thing I want to execute at my client office. But the Amazon Echo Dot was unable to find the Smart devices via Raspberry Pi-3. I have tested Raspberry Pi at my experience center an it was working fine.

I am unable to identify the issue at My client side. Is there any one can help me to sort out this issue?

The situation at my client place. They are using Firewall for security purpose. So is there any issue related to Firewall?

**Comment by bwssytems** [comment]
You will need to provide me more information on your configuration of the Echo, ha-bridge setup on the pi3, network and such. Also, turn on trace upnp and look at your logs to see if you are seeing any upnp traffic from your Echo.

**Comment by bwssytems** [comment]
any update?
