### ISSUE TITLE
Is there a way to seperate Vera switches?

### ISSUE THREAD

**Issue by dannieboiz** [bwssytems/ha-bridge#290]
When I add my garage and gate opener GH thinks it's a light switch so when I say turn on all lights it open the gate and garage as well. Is there anyway we can seperate them?

**Comment by bwssytems** [comment]
That is a google home command and it turns on everything it knows. I am assuming the GH considers all "Philips HUE" devices as lights as it seems to be. Suggestion: Don't do that.

**Comment by dannieboiz** [comment]
thanks that's what I figured so i deleted the devices. kind of suck that I can tell it to open and close my doors and gate
