### ISSUE TITLE
milight v3 / limitless v6 hubs..

### ISSUE THREAD

**Issue by duecedriver** [bwssytems/ha-bridge#291]
does this support the latest hubs mentioned in the title.. thanks

home assistant does not seem to work with them using lights: limitlessled.. I think they toped out at limitless v5 hubs

**Comment by bwssytems** [comment]
The ah-bridge does not have specific support for any milight or limitless bulbs. What it is able to do is send the raw udp commands that are needed to the bulbs themselves. If there is a REST AIP to the hub, you can write your calls to that if you wish.

**Comment by duecedriver** [comment]
interesting.. thanks for the tip... so in essence .. running this is basically a bridge emulator... 

do you know if this works like a plug in for home assistant software or homebridge which alows siri integration?

Thanks.. any info would be a help.. just getting into this so I am still a bit new...

**Comment by bwssytems** [comment]
This allows you to bridge other software or appliances that can talk to a Philips Hue and instead call other systems. Amazon Echos and Google Homes can talk to a philips hue and so this can run instead and call those other systems such as home assistant. Homebridge does not work with this as it expects the hue hub to be registered with meethue.com which this does not. It only implements the local discovery.

**Comment by duecedriver** [comment]
ah... thanks for the info..

**Comment by timbiotic** [comment]
Can it send UDP and then react based on the response? Because the new version basically hands out a session response that you need to include in your next command to turn off/on the lights.  See here https://github.com/mwittig/node-milight-promise/issues/7
