### ISSUE TITLE
Exeption for All lights ON/OFF

### ISSUE THREAD

**Issue by parostberg** [bwssytems/ha-bridge#293]
Is there any way to exclude a scene for the the expression "Turn all lights ON/OFF"?
I have a scene in my Vera that I don't want to run while giving this command.

**Comment by bwssytems** [comment]
The ha-bridge does not get expressions. The Echo and Google Home turn all lights on and off directly. So I cannot tell what called it.

**Comment by parostberg** [comment]
Is it possible to disable the "Turn on all lights" function?

**Comment by bwssytems** [comment]
This will be on the Amazon Echo or the Google Home. I do not see any setting on the Amazon Echo.
