### ISSUE TITLE
Ha-Bridge not listing devices

### ISSUE THREAD

**Issue by Chanete** [bwssytems/ha-bridge#295]
I'm integrating HA-Bridge with openhab but openhab fails to discover the devices defined in HA-Bridge.

To discover devices openhab uses this url: http://bridgeip/api/xxxx-user_id_registered...9cab98a0/ and it gets a "404 Page not found". 

If you try the same URL on a real HUE (with the proper IP and user) you get a very long json answer like this: 
{"lights":{"1":{"state":{"on":false,"bri":254,"alert":"none","reachable":true},"type":"Dimmable light","name":"Desk","modelid":"LWB006","manufacturername":"Philips","uniqueid":"00:17:88:01:10:5c:26:d1-0b","swversion":"5.38.2.19136"},"2":{"state":{"on":false,"bri":254,"alert":"none","reachable":true},"type":"Dimmable light","name":"living room","modelid":"LWB006","manufacturername":"Philips","uniqueid":"00:17:88:01:02:08:38:2e-0b","swversion":"5.38.2.19136"},"4":{"state":{"on":false,"bri":254,"alert":"none","reachable":true},"type":"Dimmable light","name":"dining room","modelid":"LWB006","manufacturername":"Philips","uniqueid":"00:17:88:01:02:08:20:22-0b","swversion":"5.38.2.19136"}},"groups":{"1":{"name":"Salón","lights":["2"],"type":"Room","state":{"all_on":false,"any_on":false},"class":"Living room","action":{"on":false,"bri":254,"alert":"none"}},"2":{"name":"Comedor","lights":["4"],"type":"Room","state":{"all_on":false,"any_on":false},"class":"Living room","action":{"on":false,"bri":254,"alert":"none"}},"3":{"name":"Despacho","lights":["1"],"type":"Room","state":{"all_on":false,"any_on":false},"class":"Office","action":{"on":false,"bri":254,"alert":"none"}}},"config":{"name":"Philips hue  Bri","zigbeechannel":25,"bridgeid":"001788FFFE27AC6A","mac":"00:17:88:27:ac:6a","dhcp":true,"ipaddress":"192.168.1.79","netmask":"255.255.255.0","gateway":"192.168.1.1","proxyaddress":"none","proxyport":0,"UTC":"2016-12-04T20:16:09","localtime":"2016-12-04T21:16:09","timezone":"Europe/Madrid","modelid":"BSB002","swversion":"01036562","apiversion":"1.15.0","swupdate":{"updatestate":0,"checkforupdate":false,"devicetypes":{"bridge":false,"lights":[],"sensors":[]},"url":"","text":"","notify":true},"linkbutton":false,"portalservices":true,"portalconnection":"connected","portalstate":{"signedon":true,"incoming":true,"outgoing":true,"communication":"disconnected"},"factorynew":false,"replacesbridgeid":null,"backup":{"status":"idle","errorcode":0},"whitelist":{"18xxxxxxxxxxxxx23a25097824074515":{"last use date":"2016-08-16T10:15:34","create date":"2016-07-13T14:49:25","name":"Hue 2#HUAWEI EVA-L09"},"7nxxxxxxxx4UrXYY-iuzuAnRu1phqAuTUZUm7dnE":{"last use date":"2016-11-10T20:53:18","create date":"2016-08-19T11:54:49","name":"Hue 2#HUAWEI EVA-L09"},"xxxxxxxxxxxKz5douC4YPRU2myrrF0JXTHB24Z":{"last use date":"2016-11-10T22:38:18","create date":"2016-09-14T19:42:48","name":"EclipseSmartHome"},"exxxxxxxxxxxxxxxOvJ2gmzBW2PAl7oiHO-xvnD6h":{"last use date":"2016-10-09T20:04:45","create date":"2016-10-09T19:52:54","name":"Echo"},"6fnuUVFBYT4dtWUxxxxxxxxxxxxxxxxxxM6U3":{"last use date":"2016-10-09T20:04:45","create date":"2016-10-09T19:52:55","name":"Echo"},"ZkCxxxxxxxxxxw6l6TSx84xcKSHflJjEyjAK-TQ":{"last use date":"2016-12-04T18:37:11","create date":"2016-10-09T19:52:55","name":"Echo"},version":1,"data":"akjir_r02_d06"},"picture":"","lastupdated":"2016-10-17T19:38:38","version":2}},"rules":{},"sensors":{"1":{"state":{"daylight":null,"lastupdated":"none"},"config":{"on":true,"configured":false,"sunriseoffset":30,"sunsetoffset":-30},"name":"Daylight","type":"Daylight","modelid":"PHDL00","manufacturername":"Philips","swversion":"1.0"}},"resourcelinks":{}}

**Comment by bwssytems** [comment]
Any update? Otherwise need log files...

**Comment by Chanete** [comment]
No, I haven't been able to solve it. 

Attached you'll find the Bridge log file. I've placed the log_level to debug.

Just to add some more  information, the log error in OpenHab is this: 
18:20:43.370 [ERROR] [binding.hue.handler.HueBridgeHandler] - Bridge cannot search for new lights.
java.io.FileNotFoundException: http://192.168.1.246/api/3a202335f9f446adac6df5209cab98a0/

There is very looong a java traceback after that that I'm removing. 

Thx.! 

[Bridgelog.txt](https://github.com/bwssytems/ha-bridge/files/646674/Bridgelog.txt)

**Comment by bwssytems** [comment]
Looks as if openhab is using a call that is not implemented in the ha-bridge. I will review the hue api again but this looks solvable if a real hue hub is doing it.

**Comment by bwssytems** [comment]
Wow! totally missed that call in the hue api doc. This may fix some other systems like smartthings.

**Comment by bwssytems** [comment]
Oops, the call is available, but the spark webserver is not finding it..... maybe it is the slash at the end....

**Comment by bwssytems** [comment]
Found it, as the slash needs to be explicit in spark, the same issue was found with the Harmony Hub when registering for a user with a POST.

**Comment by Chanete** [comment]
Great!!, Thank you! I'll test it as soon as you release 4.0.0

**Comment by Chanete** [comment]
Hi, Happy New Year!!  

When are you planning to release V4.0.0 so I can test that this is fixed? 

Is there any build that I can use?

Thx 
Alejandro

**Comment by bwssytems** [comment]
This issue contains the beta #344

**Comment by Chanete** [comment]
I've just tested and it works perfect. Now Openhab can interact with HA Bridge perfectly. 

I have already have to test if the real HUE app works with the bridge, I'll let you know as soon as I can test it. 

Thank you!!
