### ISSUE TITLE
support Xiaomi Yeelight plugin mechanism ?

### ISSUE THREAD

**Issue by mp3llll** [bwssytems/ha-bridge#296]
There is a way to work with plugin mechanism?

i want to use Yeelight

Thansk!

**Comment by bwssytems** [comment]
Yes there is a way. I will put it on the enhancement list, but it will be a bit as other enhancements are prioritized first.

**Comment by bwssytems** [comment]
With the implementation of OpenHAB, Which has Xiaomi connectivity, I will suggest that is the path to implement this.

See https://www.openhab.org
