### ISSUE TITLE
Vera - Fibaro FGRM222 blind control module not working

### ISSUE THREAD

**Issue by cw-kid** [bwssytems/ha-bridge#298]
Hello

I have a Fibaro FGRM222 blind control module connected to my curtains. 

In the HA-Bridge in the list of Vera devices in the Category column, it does state that this Fibaro FGRM222 device is "Window covering". 

I pressed the Generate Bridge device button and added it to the Bridge. However the curtains do not open or close. Below are the codes generated by the HA-Bridge;

On:

http://192.168.1.100:3480/data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:SwitchPower1&action=SetTarget&newTargetValue=1&DeviceNum=75

Off:

http://192.168.1.100:3480/data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:SwitchPower1&action=SetTarget&newTargetValue=0&DeviceNum=75

If I run these I can hear the Fibaro blind control module click. But the curtains do not actually open or close. So I think the code is not quite right ? 

I have also raised a support ticket with Vera to see what they say. I am using a Vera Edge UI7 with beta firmware 1.7.2348.

Thanks

**Comment by cw-kid** [comment]
Actually I think this is a bug in Vera.

If I make sure the curtains are open first. 

If I then run this command:

http://192.168.1.100:3480/data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:SwitchPower1&action=SetTarget&newTargetValue=0&DeviceNum=75

They close OK.

However once the curtains have closed if I run this command to open them:

http://192.168.1.100:3480/data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:SwitchPower1&action=SetTarget&newTargetValue=1&DeviceNum=75

Nothing happens I do not hear the relay click and the curtains do no open. 

I also tried this command instead:

http://192.168.0.12:3480/data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:SwitchPower1&action=SetTarget&newLoadLevelTarget=100&DeviceNum=75

When using that command I do hear the relay click, but still the curtains do not open. 

I have also had problems in the past with the Fibaro blind control module and native Vera scenes, for example in the advanced editor of a scene you can set your action to be "togglestate" this does not work either and behaves in a similar way to what I am seeing with HA-Bridge.  Where it will close the curtains but not toggle them properly and does not open the curtains. 

I did report it as a bug to Vera but they never fixed it.

**Comment by bwssytems** [comment]
This may not be a vera bug. The ha-bridge is simplistic in it's url generation for vera. It only has switches and scenes. There may be a better url luup request for your blinds by it's type. Take a look here to see if there is a better one http://wiki.micasaverde.com/index.php/Main_Page. Also, read the micasaverde forums, http://forum.micasaverde.com/index.php/topic,31920.0.html, for the ha-bridge as someone may already have it.

**Comment by cw-kid** [comment]
OK thanks will do. I will also wait and see what Vera support says about the correct URLs. 

But I know for 100% that there are some bugs in Vera for this Fibaro blind control module specifically their "togglestate" command does not work properly. I was using it to assign a single button on to an Aeon Minimote remote control to open and close the curtains it use to work in Vera UI5 but they broke it in UI7 and never fixed it.

**Comment by bwssytems** [comment]
Yes, understand. If you could always take a look at the luup code for the fibaro and debug it for them... lol

**Comment by cw-kid** [comment]
These command URLs work! 

Open:

http://192.168.1.100:3480/data_request?id=action&output_format=json&DeviceNum=75&serviceId=urn:upnp-org:serviceId:Dimming1&action=SetLoadLevelTarget&newLoadlevelTarget=100

Close:

http://192.168.1.100:3480/data_request?id=action&output_format=json&DeviceNum=75&serviceId=urn:upnp-org:serviceId:Dimming1&action=SetLoadLevelTarget&newLoadlevelTarget=0

Although I am not sure about "dimming" yet to say open the curtains to 50%. 

I have updated the HA-Bridge device with these different commands. 

With Alexa if I say "Turn On Curtains" they open and "Turn Off Curtains" they close.

However it would be much better if I could just say "Open Curtains" or "Close Curtains" ??

Thanks

**Comment by cw-kid** [comment]
"Dimming" works, your HA-Bridge automatically populated the Dim URL field with this code:

http://192.168.1.100:3480/data_request?id=action&output_format=json&DeviceNum=75&serviceId=urn:upnp-org:serviceId:Dimming1&action=SetLoadLevelTarget&newLoadlevelTarget=${intensity.percent}

If I say Alexa "Dim Curtains 50 percent" the curtains go to 50% opened.

Again would be better to say Alexa "Open curtains 50%"

Thanks

**Comment by bwssytems** [comment]
Glad its working!
