### ISSUE TITLE
Nuimo app discovers Ha-Bridge but can't control lights

### ISSUE THREAD

**Issue by spedja** [bwssytems/ha-bridge#299]
Nuimo is an android app that controls Philips Hue lights with physical Nuimo controller. (more info on senic.com)
Nuimo app can discover Ha-Bridge and all "lights" added there, and within app there is a Test button and chosen light can be turned On/Off. (just for a test purpose)
At that moment (pressing test button) Ha-bridge throws Exception:
[log.txt](https://github.com/bwssytems/ha-bridge/files/637503/log.txt)

--192.168.0.35:80 HA-bridge server ip
--192.168.0.28 Nuimo app on android

at line 2016-12-07 18:44:56,683 Nuimo app tries to create a new user and fails, even though light can be turned On/Off (with a test button).

After you choose light that you wanna control with Nuimo controller, Nuimo app fails to control (turning the light On/Off)
[log 2.txt](https://github.com/bwssytems/ha-bridge/files/637525/log.2.txt)

pay attention on line 2016-12-07 18:55:04,052 config requested: <no_user> from 192.168.0.28

**Comment by bwssytems** [comment]
There seems to be no issues in the log, That line with <no_user> is a valid request. Also there were create user requests already:
2016-12-07 18:54:57,091 [qtp22965473-24] INFO  com.bwssystems.HABridge.hue.HueMulator - Traceupnp: hue api/* user create requested:  from 192.168.0.28
Which creates the id ti send back to the client.

You can turn on debug for the HueMulator class to look at calls for state change.

**Comment by spedja** [comment]
Hi BWSSystem,

thanks for replay. After enabling debug for the HueMulator i am getting following output:
[log3.txt](https://github.com/bwssytems/ha-bridge/files/640231/log3.txt)

Its really strange, like Nuimo app tries to create new user every time after i press command On/Off on Nuimo controler, right?

output from http://192.168.0.35/api/user:
[users.txt](https://github.com/bwssytems/ha-bridge/files/640234/users.txt)

BTW, Nuimo app works ok with real PhilipsHue bridge, where you can On/Off Light, dim, change color, etc.

Thanks!

**Comment by bwssytems** [comment]
It is very weird as it does ask for the complete state of the system every minute. What is weird is that even though it is creating new users, it uses a different user for all the calls. It keeps asking for a light ID of "new" as well which would be incorrect in the vernacular of the hue api as they are all numbers. Have you tried turning off your real hue bridge and try it without that running?

**Comment by spedja** [comment]
Ok, did that, PhilipsHue Bridge off and its still the same. Seems that they have problem in their app, but then, why its working with original hue bridge (confused)?

2016-12-08 20:07:14,875  moment when App tries to reach Ha-bridge and retrieve lights
2016-12-08 20:08:31,597 test button is pressed

![screenshot_2016-12-08-21-17-08](https://cloud.githubusercontent.com/assets/17951934/21026295/42019338-bd8c-11e6-926f-70034d49cbba.png)

[log5.txt](https://github.com/bwssytems/ha-bridge/files/640502/log5.txt)

**Comment by audiofreak9** [comment]
@bwssytems HUE firmware is now at 01036562.  Last time we spoke it was 01035934.  This _might_ be the reason the app is not picking up the ha-bridge.

Maybe make the emulated firmware version that the bridge reports a setting on the ha-bridge?

**Comment by bwssytems** [comment]
@audiofreak9 That may be the best course of action as that seems to be one of the issues with these apps.

**Comment by spedja** [comment]
How i can change firmware version in Ha-bridge and test it out?

**Comment by bwssytems** [comment]
3 files contain the SW version, HueConfig.java, HuePublicConfig.Java and UpnpSettingsResource.java. I'll put in a setting to control this in the next release. But if you would like to test it, that would be great.

**Comment by spedja** [comment]
Yes, i will test it today. Will let you know about outcome. Thanks!

**Comment by spedja** [comment]
I updated SW version to 01036659 (current version on my Philips HUE hub), but behaviour is the same :(

![screen shot 2016-12-21 at 06 59 21](https://cloud.githubusercontent.com/assets/17951934/21379105/9d0ca63c-c74b-11e6-8889-2c0faf119c8a.png)

Any other ideas?
Thanks!
