### ISSUE TITLE
Support for setting intensity level of Dimmable Switch devices

### ISSUE THREAD

**Issue by signal15** [bwssytems/ha-bridge#3]
Add the option to use the Dimming function for the onURL for Dimmable switches so one can set the intensity level.

Looks like you *can* do this with SwitchPower1, but it appears that not all devices support doing that.  Will likely have to use Dimming1.

**Comment by bwssytems** [comment]
I'm trying to figure out if this is solved with the dimming variables or not. I do not see anything else to set in the vera other than SetLoadLevelTarget which is a percentage.
