### ISSUE TITLE
Can't connect to Hue hub

### ISSUE THREAD

**Issue by booles04** [bwssytems/ha-bridge#300]
I'm trying to connect ha-bridge to a physical hue hub. added a name and ip address in the bridge settings, saved, "hue devices" tab appears but no devices populate. Log shows:

12-08-2016 06:17:59.365	WARN	registerWithHue needs link button pressed on HUE bridge: huehub	com.bwssystems.hue.HueUtil
12-08-2016 06:17:59.372	WARN	Register to Hue for huehub returned error: [{"error":{"type":101,"address":"","description":"link button not pressed"}}]	com.bwssystems.hue.HueInfo
12-08-2016 06:17:59.383	WARN	Cannot get lights for Hue with name: huehub	com.bwssystems.hue.HueHome

I've tried pressing physical link button before and after adding hue ip address. Also tried deleting data directory in habridge on my pi. I've read through all the issues and don't see what I'm missing.

**Comment by bwssytems** [comment]
It's a bit tricky.

Start up the ha-bridge, add the ip, save, hit the link button on your hue, then go to the tab for the hue. These steps should work. When it first starts it will fail as the message above shows and it needs to try a second time. By hitting the tab, it makes the bridge talk to the hue again.

**Comment by booles04** [comment]
I appreciate your quick response. I tried the above steps and still get the same log messages. For what its worth, I can control the hue hub with HTTP calls in the api debug tool in the browser.

**Comment by bwssytems** [comment]
Ahh, the error will always happen on startup as the ha-bridge does not save the registration user info from start to start. Once it has gone through it while it is up, it will work fine.

**Comment by booles04** [comment]
Well my hue devices that are paired with the hue hub are not populating in the list of devices on the hue tab in ha-bridge. Do I have to add them manually? What registration user info are you talking about? I've never seen anywhere to input user info, only the ip address of the hub.

**Comment by bwssytems** [comment]
No, you do not need to add the devices manually as that will not work properly. The path that the ha-bridge takes, is it calls the hue hub with a dummy user first, if it gets an error for "please press the link button" you should press that before you try another command. I believe you have thirty seconds to try again. So, in that time, you would need to hit the hue link button, then go to the ha-bridge ui and hit the bridge control tab then go back and hit the hue device tab as that will make the bridge try again and then it can register with the hue hub as the link button is pressed.

**Comment by booles04** [comment]
Thank you for your detailed response. I got it working. It looks like the timeout on pressing the link button and the hue tab was much shorter, at least in my experience, closer to 10 seconds or so.
