### ISSUE TITLE
Newbie Question - SSL Support

### ISSUE THREAD

**Issue by jasondharper** [bwssytems/ha-bridge#301]
Hello - I apologize in advance if this is an elementary question.  But I want to serve the web interface over https (443).  I have SSL certificates, etc. but don't see anywhere to configure SSL other than changing the Web Server port to 443?

Thank you!

**Comment by aptalca** [comment]
You should use a reverse proxy

**Comment by jasondharper** [comment]
Perfect - I can take it from there.  Thank you!
