### ISSUE TITLE
Using Curl to control the ha-bridge

### ISSUE THREAD

**Issue by 101jallen** [bwssytems/ha-bridge#302]
Must be a brain block I have. What would the syntax for using curl to control the bridge to turn on/off a specific light? Below is what I am trying in all sorts of iterations to no avail.
curl -X PUT -H "Content-Type: application/json" -d '{"lights":"11":"state":"on":"true"}' "http://10.255.254.81:88/api/test" which results in a 404 error but I can browse to the url and get the device list.
Thank you for a fantastic piece of software.

**Comment by audiofreak9** [comment]
ON full bright would be:

`curl -X PUT -H 'Content-Type: application/json' -d '{"on":"true","bri","255"}' http://10.255.254.81:88/api/username/lights/{DEVICEID}/state`

replace {DEVICEID} for your device ID

OFF would be: 

`curl -X PUT -H 'Content-Type: application/json' -d '{"on":"false"}' http://10.255.254.81:88/api/username/lights/{DEVICEID}/state`

replace {DEVICEID} for your device ID

DIM would be: 

`curl -X PUT -H 'Content-Type: application/json' -d '{"on":"true","bri","255"}' http://10.255.254.81:88/api/username/lights/{DEVICEID}/state`

replace {BRIGHTNESS} with your desired brightness 1 to 255, and replace {DEVICEID} for your device ID.

**Comment by audiofreak9** [comment]
Fixed the "DIM" part...

**Comment by bwssytems** [comment]
@101jallen Did this answer your question?

**Comment by 101jallen** [comment]
@bwssytems,
I was just testing this out. Perfect! Hooked this in with ifttt.com for some custom strings of events. For example;  "alexa, trigger lets reload" turns on the reloading room lights, individual press lights and magic packet wakes a computer up and opens a browser window on a Windows 10 PC to the reloading data and starts playing some music. "alexa trigger reload off" closes it all down and plays a reminder to turn off some other things yet to have automation (the heater which I will not automate for fire concerns).

Perfect thanks you!
Jerry

**Comment by bwssytems** [comment]
Glad it's being useful! Have fun!
