### ISSUE TITLE
MQTT Dim URL can't use variable substitutions?

### ISSUE THREAD

**Issue by spants** [bwssytems/ha-bridge#303]
My setup:
I am using 3.5.1 in a Docker environment on unRaid.
I have 4 echos, lots of Hues and other lights with custom firmware all tied together with MQTT.

I have found that ON and off work:
[{"clientId":"habridge","topic":"House/Lights/strip1/white1","message":"100"}]
[{"clientId":"habridge","topic":"House/Lights/strip1/white1","message":"0"}]

But the Dim does not work:
[{"clientId":"habridge","topic":"House/Lights/strip1/white1","message":"${intensity.percent}"}]

Sends ${intensity.percent} to the topic. If I remove the quotation marks, I get an error = SyntaxError: Unexpected Token...

I guess it may be getting confused with all of the curly brackets....

**Comment by bwssytems** [comment]
I knew I forgot to do something..... will be implementing that in the next release

**Comment by elgerg** [comment]
Glad i checked here before getting really confused....

FYI in case it drives where/how you can implement i was hoping i could use something like:

[{"clientId":"habridge","topic":"HomeEasy","message":"{\"emitter\":50420536,\"sendingStation\":\"Lounge2\",\"receiver\":0,\"transmitValue\":\"Off\",\"level\":${intensity.math((X/100)*15)},\"rngID\":\"rnglounge\"}"}]

When all is working...

Thanks!
