### ISSUE TITLE
Hyperion Lights Control ?

### ISSUE THREAD

**Issue by Wolfieeewolf** [bwssytems/ha-bridge#304]
Any idea how to get this to work with Hyperion (https://hyperion-project.org/)

**Comment by bwssytems** [comment]
You will have to write scripts that can be called by the bridge, or be enterprising and write your own http server for the hyperion library. Good luck!

**Comment by pattyland** [comment]
Simple script as a first test:

`ssh pi@hyper "hyperion-remote --effect 'Knight rider'"`

saved as an sh file and mapped to the "on" event of a device from ha-bridge. Works great!
