### ISSUE TITLE
Vera / Google Home - Lights vs Appliances

### ISSUE THREAD

**Issue by JustinLutsky** [bwssytems/ha-bridge#307]
Hello! So far working wonderfully well to integrate voice control of my VeraPlus with Google Home. One particular scenario, I wonder if anyone has a suggestion for:

Room: Den
-Floor Lamp
-Table Lamp
-Can Lights
-Fan

If I tell Google Home to "Turn on Den" or "Set the Den to 50%", the fan turns on as well.

Tried creating new Rooms as follows:

Room: Den
-Floor Lamp
-Table Lamp
-Can Lights

Room: Fans
-Den Fan
-Living Room Fan
-Bedroom Fan

Same result. Anytime "Den", or the corresponding room name is used in the voice command, it groups the appliance (fan) in with the other lights. Any trick or suggestion to separate appliances like fans from all the lights, and still maintain individual voice control of the appliances?

**Comment by bwssytems** [comment]
Unfortunately, as stated before, Google Home is using the interpretation of a room in it's deciphering of what is said to control. There is nothing in the ha-bridge that can tell what is happening at that end.

**Comment by cogneato** [comment]
Maybe make a custom room in the Google Home app (at the bottom of the pre-made list) and call it "ceiling" (or anything else). Assign all the fan devices to the "ceiling"? Then you could "set ceiling to 50%" to do all fans. Or you could split them up by being more specific.
