### ISSUE TITLE
Linking two bridge devices together?

### ISSUE THREAD

**Issue by AdrianKielbowicz** [bwssytems/ha-bridge#309]
This might be a silly question (or I am not thinking hard enough!) but how do I link two bridge devices together so Alexa can effectively do two things at the same time? I'm thinking here about the following scenario which I have already setup but need to issue two voice commands to accomplish:

1) Alexa turn on my gaming machine which does simple WOL and powers on my desktop,
2) Alexa turn on my TV which talks to my Harmony Hub to trigger an activity to turn my TV on.

How do I simply say "Alexa turn on my gaming machine" and that triggers two actions to a) wol my gaming PC and b) turn on my TV?

What am I missing here to get this done?

cheers,
Adrian

**Comment by bwssytems** [comment]
The next version allows multi commands across different types. You will just create the two actions in the given device.... But! There is a hack that works now as multi commands work for http!

Device Name: Gaming Machine
On URL: [{"item":"http://<ip of your ha bridge or localhost>:<port>/api/anyusername/lights/<id of the first item you want to turn on from your bridge devices>/state"},{"item":"http://<ip of your ha bridge or localhost>:<port>/api/anyusername/lights/<id of the second item you want to turn on from your bridge devices>/state"}]

HTTP Verb: PUT

On Body: {"on":true}

This will do the same thing for now.

**Comment by rafale77** [comment]
Not sure why you would not just create a group in the Alexa app where you would put both bridge devices.

**Comment by AdrianKielbowicz** [comment]
I knew there was something that I was blatantly overlooking! Thanks @rafale77 for opening my eyes!

@bwssytems, thank you for your reply as well. HA-Bridge is such an awesome piece of work. Keep it up!
