### ISSUE TITLE
Run as a service on Synology

### ISSUE THREAD

**Issue by mcwieger** [bwssytems/ha-bridge#310]
I'm trying to get this working on my Synology DS414. I'm using this release, which works fine when starting from the command line in Putty, all perfect:

java -jar -Dserver.port=8085 ha-bridge-3.5.1.jar

However, as soon as I close the SSH session, the app is also going down. How can I start HA-Bridge as a service on Synology, so it keeps running?  Using Docker is not an option as it is not supported by this Synology type (only the + versions).

**Comment by bwssytems** [comment]
https://github.com/bwssytems/ha-bridge/issues/179

https://github.com/bwssytems/ha-bridge/issues/146

https://github.com/bwssytems/ha-bridge/issues/145

**Comment by mcwieger** [comment]
I've gone through those, but they all refer to using Docker. Only a limited set of Synology devices support Docker. Is there a way (in general) to run as a service on Linux, preferably without 3rd party tools?

**Comment by bwssytems** [comment]
There is, but I would look to the Synology forums. The examples here on Github are for debian mostly on standard hardware.

**Comment by christophfe** [comment]
Hi, you could try to run it with
nohup java -jar -Dserver.port=8085 ha-bridge-3.5.1.jar
on Synology

**Comment by mcwieger** [comment]
That's it. Thanks a lot!

nohup java -jar -Dserver.port=8085 /volume1/@appstore/HA_bridge/ha-bridge-3.5.1.jar
