### ISSUE TITLE
Can't find any devices..

### ISSUE THREAD

**Issue by johnnydisco** [bwssytems/ha-bridge#311]
OK so I am new to this so apologies if I have missed something simple.  

- I have an Alexa and a single solitary Philips Hue lightbulb, no bridge.
- I have installed Ubuntu 16.04 updated and installed default-jre and jdk.  
- I have created a directory called data
- I have run java -jar ha-bridge-3.5.1.jar and no errors
- I can access the webserver on my laptop and it loads HQ bridge

What's next?  Should devices magically appear or am I missing some hardware, software or configuration?

Thanks

**Comment by bwssytems** [comment]
This does not replace a Philips hue hub as it is designed to control other devices via the Hue API. It is not related to Philps in anyway. You will need to buy a Philps Hue Hub to control your light bulb.

**Comment by audiofreak9** [comment]
@bwssytems, this has come up a few times now, I wonder if adding another bold disclaimer to the README is in order?  Something like:

**NOTE: This software does not control Philips Hue devices directly. A physical Philips Hue Bridge is required for that, by which the ha-bridge can then proxy all of your real Hue bridges behind this bridge.**

**Comment by bwssytems** [comment]
Yep, will add that too.
