### ISSUE TITLE
Starting via script shows devices.  Starting via sysctl shows none

### ISSUE THREAD

**Issue by Lorccan** [bwssytems/ha-bridge#315]
I am pretty sure this is a configuration problem, but just in case:

If I start via starthabridge.sh, all my devices show up in the Bridge Devices tab.  However, if I start via sysctl (successful launch with no errors in status), no devices show up.

I have been over the configurations, and it looks as though the same settings are in both places.

**Comment by elgerg** [comment]
You should probably paste the contents of each file in.

When i had the same issue it was due to the instructions i had followed had myhabridge.config instead of habridge.config...

The next issue i had was DHCP related. I had set mine up on one IP, rebooted and gone... As soon as i went back to the original IP (now static so it wont happen again) boom the devices were back.

Check your logs tab for something like looking for config, failed....

Hope that helps

**Comment by Lorccan** [comment]
Thanks.  I don't think it's either of those as I have a fixed IP and I am not restarting the computer in between the different start methods.

I will review the files and post back as there are some slight differences.

**Comment by Lorccan** [comment]
I have tried a few alternatives and still have the same problem: no devices when started via sysctl.

This is /etc/systemd/system/habridge.service:

`[Unit]
Description=HA Bridge
Wants=network.target
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/java -jar -Dserver.port=4080 /home/pi/habridge/ha-bridge.jar

[Install]
wantedBy=multi-user.target`

(the line in ExecStart is exactly the same as the one in starthabridge.sh)

Looking at the log when started from sysctl, I see this:

`ERROR com.bwssystems.HABridge.dao.DeviceRepository - Error file is not writable: data/device.db`

and
`... Error file is not writable: data/habridge.config`

(and this is so even if I do a sudo chmod 777 on both of them)

I suspect that the sysctl version is using relative paths and so looking for files in different places, but I have googled around and can't determine where it's expecting them.)

**Comment by Lorccan** [comment]
OK I fixed it:

I noticed a directory /data that contained habridge.config, so I deleted this and added symlinks to  habridge.config and device.db in /home/pi/habridge/data.
