### ISSUE TITLE
Trigger activity via simple http command?

### ISSUE THREAD

**Issue by cherowley** [bwssytems/ha-bridge#317]
Is there a way to use ha-bridge to start a harmony activity using a simple http command?

I wish to trigger the all off from my home controller software (Domoticz) whose native harmony support is unstable..

Thanks!

**Comment by bwssytems** [comment]
Yes you can!

Since the ha-bridge emulates the Hue API you can call it like this as long as Domoticz can do an HTTP PUT request

PUT http://<ip of ha-bridge>:<port of ha-bridge>/api/ausername/lights/<ID of your device in the ha-bridge>/state

HTTP BODY: {"on":true}

**Comment by cherowley** [comment]
Fantastic, thanks!
