### ISSUE TITLE
Feature Request: Support Aliases for Devices

### ISSUE THREAD

**Issue by sgruby** [bwssytems/ha-bridge#32]
While I know that I can create more than 1 device with the same URL, it would be convenient to have aliases such that I can call a device more than 1 name, i.e. kitchen lights, kitchen can lights, overhead lights, etc.

**Comment by bwssytems** [comment]
Just create the device again with the same url info. I do that all the time. Each entry is unique by Id, not the content. Generate your URL for the vera device and change the name and add it.

**Comment by sgruby** [comment]
Thanks; I understand that, but was looking for an easier way.

**Comment by bwssytems** [comment]
It is the easy way. :)

**Comment by bwssytems** [comment]
Well after doing some work on my bridge system for devices, I see what you mean. Especially of the item is now in the already in use list.This request is back on the table.

**Comment by sgruby** [comment]
Thanks, this should make it much easier to give devices multiple names. My family sometimes uses the wrong device name, and I think this would help.

**Comment by cr4zyg047** [comment]
Agree with sgruby - it'd be great to either have list one can populate alternative names into (or make the name a comma separated value) - and it will maintain multiple object ID's on the outward facing API to the Echo. I will say that the Echo is VERY flexible when it comes to using slightly different names for existing lights. My "living room" object can be triggered with "living room off" -- "turn the living room lights off" - etc. It doesn't have to be literal.

**Comment by audiofreak9** [comment]
Maybe a "Copy" button next to the "Edit" button in the Current Devices page, that copies the settings of any device (minus the name) to the manual add page so the user just has to fill in a name and click the Add Device button?

**Comment by bwssytems** [comment]
@audiofreak9 That is the way! Thanks!

**Comment by bwssytems** [comment]
I am just going to tweak this a bit and have the button "edit" be "Edit/copy" and then add a new device in the edit page.

**Comment by audiofreak9** [comment]
Even better!

**Comment by gregsheremeta** [comment]
Copy is better than nothing, but when you update the original (add a new kitchen lamp perhaps), you now have to go update all the copies too.

A true alias feature would be nicer.

**Comment by FloFoer** [comment]
You could do the following, might be better than copying in that perspective: 
- Create a alias device
- In the alias device, instead of copying the url from the original, simply do a http request to localhost to the original device. Like a passthrough of the command to the original device.   

That way you would only have to change one device.
