### ISSUE TITLE
MQTT Client doesnt automatically reconnect to broker

### ISSUE THREAD

**Issue by elgerg** [bwssytems/ha-bridge#320]
Hi,

I seem to have an issue where the bridge gets disconnected from my MQTT broker. There is no current reconnect and as such the bridge must be re-initialized to allow functionality to resume.

Any chance you could either reconnect on a disconnect or try to reconnect when a command is sent?

Thanks in advance

**Comment by bwssytems** [comment]
Yep, this is a good idea.

**Comment by bwssytems** [comment]
Found the options, will add.
