### ISSUE TITLE
Error "Could not send data for network request"

### ISSUE THREAD

**Issue by xxxmaxxx** [bwssytems/ha-bridge#321]
Hello,
i got an issue, if i push the test botton i will get an error.

Change device state, Could not send data for network request: http://xxx.xxx.xxx.xx:8083/ZAutomation/api/v1/devices/ZWayVDev_zway_9-0-37/command/on with Message: HTTP request may not be null

I did just setup the off and on URL. Did I miss something?
Can someone help me?

regards Max

**Comment by bwssytems** [comment]
Turn on debug for the Huemulator class as directed in the readme. Post your log errors.

**Comment by xxxmaxxx** [comment]
Hello,
i hope this is what you ask for!?

[habridge-log.txt](https://github.com/bwssytems/ha-bridge/files/671201/habridge-log.txt)

**Comment by xxxmaxxx** [comment]
I thought the debugging was on but it isn't. Can you please explain exactly what i have to type in to activate?

**Comment by bwssytems** [comment]
So, did you change the address in the HTTP request to your target or did you X it out for posting? I.e. http://xxx.xxx.xxx.xxx:8083....

https://github.com/bwssytems/ha-bridge/blob/master/README.md#the-logs-tab

**Comment by xxxmaxxx** [comment]
Yes, i just changed it.
Here is a new log.
[habridge-log.txt](https://github.com/bwssytems/ha-bridge/files/671585/habridge-log.txt)

**Comment by xxxmaxxx** [comment]
This might be helpful find the issue.
With curl it works even without login or password.

`pi@raspberrypi:~ $ curl -v  http://192.168.222.10:8083/ZAutomation/api/v1/devices/ZWayVDev_zway_9-0-37/command/off
* Hostname was NOT found in DNS cache
*   Trying 192.168.222.10...
* Connected to 192.168.222.10 (192.168.222.10) port 8083 (#0)
> GET /ZAutomation/api/v1/devices/ZWayVDev_zway_9-0-37/command/off HTTP/1.1
> User-Agent: curl/7.38.0
> Host: 192.168.222.10:8083
> Accept: */*
>
< HTTP/1.1 200 OK
* Server Mongoose/6.4 is not blacklisted
< Server: Mongoose/6.4
< Content-Type: application/json; charset=utf-8
< X-API-VERSION: 2.0.1
< Date: Sat, 24 Dec 2016 08:08:58 GMT
< Access-Control-Expose-Headers: Accept-Ranges, Content-Encoding, Content-Length, Content-Range, Content-Type, ETag, X-API-VERSION, Date, Cache-Control, If-None-Match, Content-Language, Accept-Language, ZWAYSession
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
< Access-Control-Allow-Headers: Authorization
< Connection: close
< Content-Length: 56
<
* Closing connection 0
{"data":null,"code":200,"message":"200 OK","error":null}`

**Comment by xxxmaxxx** [comment]
I did figured it out!
I found a manual that helps me.
Me settings were wrong.

ZWay API (German):
[https://www.siio.de/connected-home/zway-amazon-echo-alexa/]

Thanks
