### ISSUE TITLE
Cannot get harmony client

### ISSUE THREAD

**Issue by jimboca** [bwssytems/ha-bridge#325]
On startup this failed:
12-23-2016 11:33:57.420	ERROR	Cannot get harmony client (Master) setup, Exiting with message: Failed communicating with Harmony Hub	com.bwssystems.harmony.HarmonyHome

But this hub has been working, so must be some intermittent communication issue?  Could it retry occasionally?

**Comment by bwssytems** [comment]
Did it work when you restarted or reinitialized?

**Comment by jimboca** [comment]
Yes, reinitialized fixed it.

**Comment by bwssytems** [comment]
I'll look at a re-init if it cannot get the first time. The Harmony client code does do that after it is init'd the first time.

**Comment by jimboca** [comment]
Great, thanks.

**Comment by bwssytems** [comment]
I put in a try for 3 times with a sleep of 2 seconds.

**Comment by jimboca** [comment]
Nice, thanks!
