### ISSUE TITLE
Avoid JSON-Parse error in on/dim/offURL by parsing before saving

### ISSUE THREAD

**Issue by luke-ff** [bwssytems/ha-bridge#326]
it would be great if typed in JSON (i.e. multiple http-requests in on/offURL fields) would be parsed before saving. I've had some issues with non-visible characters (\u001d \u001b), which were found only when manually editing the database file using vi.

**Comment by bwssytems** [comment]
I'm thinking about expanding the hex encoding that is available for tcp and udp commands. That would fix this.

**Comment by bwssytems** [comment]
So now that I think about this, this happens more from cut and paste requests instead of actually typing in the UI, correct?
