### ISSUE TITLE
Tracking Harmony activity state

### ISSUE THREAD

**Issue by jasondharper** [bwssytems/ha-bridge#330]
Hello! 

I've got the bridge and harmony control up and running with no issue - everything works great.  What I can't seem to figure out is if there is a way to track activity state independent if triggering it within the ha-bridge.  For example, if I turn a harmony activity on/off via the bridge or an API call to the bridge, the device state correctly shows on or off.

But, if I turn on a harmony activity using the harmony remote, is there a way for the bridge to update it's state respectively?   My use case is that I'm developing a UI that will show "Now Playing" type activity and, if I have someone trigger the activity via my UI or Alexa, no problem.  But if the activity is triggered outside of the bridge, there's no way for me to know that activity state is on?

Hope that makes sense and thanks!

**Comment by bwssytems** [comment]
That makes sense. I did not connect the state call to anything in the ha-bridge.

**Comment by jasondharper** [comment]
Cool. Will your harmony API project allow me to get whether an activity is on or off?  I looked at the readme but didn't see a method to get activity state?

**Comment by bwssytems** [comment]
There is:

https://github.com/bwssytems/ha-bridge#show-harmony-current-activity

**Comment by jasondharper** [comment]
Interesting.  So I tried that but when I call that method, I get the same output as if I had called the /api/devices/harmony/activities method.  It just lists every activity on the hub even if nothing is on....?  Am I missing something?  Thank you!

**Comment by audiofreak9** [comment]
I too get the same as above.  

@bwssytems, I am not fully familiar with the Harmony Hub API, does it respond with JSON?  The reason I ask is I <a href="https://github.com/audiofreak9/ha-bridge-X10-device-state-update">just wrote a python script</a> that I run with cron that updates the ha-bridge device state for my X10 devices (still gotta finish the instructions) but I can add Harmony Activity state update to it too.

**Comment by audiofreak9** [comment]
@bwssytems, just installed <a href="https://github.com/bwssytems/restful-harmony">your restful-harmony</a> and it does give the current Harmony activity properly with GET http://host:8081/harmony/show/activity

**Comment by bwssytems** [comment]
Geez, you guys are falling down on debugging my code... that has been a bug since I created it....lol

**Comment by jasondharper** [comment]
Lol. Awesome - thanks!  What's your timing on 4.0?  Not a big deal - I'll stand up some instances of the restful harmony API for not but just curious. Thanks for such an awesome project!

**Comment by bwssytems** [comment]
Almost finished. Just finished the refactoring write now. Just checking the bugs to be in and then testing and then it will be out. This week.

**Comment by audiofreak9** [comment]
@jasondharper, Once this bug is _squashed_, LOL! I'll update my script to query the ha-bridge "/api/devices/harmony/show" and update the ha-bridge.  I'll post when done.

**Comment by jasondharper** [comment]
Nice!  Thank you!!

**Comment by Matt8119** [comment]
Will this also allow me to control individual items with my Google home and not just scenes? I'm also looking to voice automate my soundbar that's connected to my harmony hub.

**Comment by bwssytems** [comment]
This works for Google Home as well
