### ISSUE TITLE
Changing colors of hue bulbs not working

### ISSUE THREAD

**Issue by jryanishere** [bwssytems/ha-bridge#331]
Looking over the Hue API, it should be as simple as sending "hue:65535" right after "on:true".

After adding hue:65535 (with various different formatting) to the "Content Body On" as Put, application/json, it isn't being passed along. I have confirmed this with Wireshark, the packet content ends with {"on":true}

Is there a way to currently do this?

In the future, a input box for the color number would make this super easy for people to set.

**Comment by bwssytems** [comment]
Is this on a hue passthru device in the ha-bridge? As that is the only one that will pass on the values. Also the format of the json is {"on":true,"hue":65535} , the quotation marks are required.

**Comment by jryanishere** [comment]
Yes. It is a hue passthrough device. I want a specific color set every time it is turned on.

It always sends {"on":true}, how to I get it to append "hue":65535 ?

If I add it to the on URL, it doesn't work. When I add it to the content body on, it also doesn't work.

**Comment by bwssytems** [comment]
I see now what you are trying to do. You want to append something to the hue passthru device. That is not what this does. This is made to pass the exact state change call that was given to the ha-bridge and send it to the hue device. To do what you want, you could create a device that calls the hue api directly with what you want. The only caveat is figuring out a valid user for your hub.

**Comment by bwssytems** [comment]
Did this answer your question?

**Comment by jryanishere** [comment]
Yes. Thanks.
