### ISSUE TITLE
OK

### ISSUE THREAD

**Issue by mushieslushie** [bwssytems/ha-bridge#333]
Is there a way to make Alexa stop saying 'OK' after every command?  It's pretty annoying.

Doing a search I read that people with an actual Philips Hue device no longer get the OK response but just a sound.  Does this have to do with the bridge or is this just the normal response to this type of request?

Is there a way to make her stop?

**Comment by bwssytems** [comment]
It's in the settings of your echo. Not the ha-bridge.
