### ISSUE TITLE
Multiple Echo Profiles

### ISSUE THREAD

**Issue by pattont** [bwssytems/ha-bridge#334]
My wife and I have our own profiles (separate Amazon accounts) signed into our Echo. Yesterday I setup HA Bridge and added 16 devices successfully from my Vera Plus (UI7). Today I installed a few more Z-Wave devices in to my home, added them to Vera, found and added them to HA bridge and added them to my profile in Alexa successfully for a total of 27 devices. I then switched accounts to my wife's account so she has access as well and asked Alexa to discover devices and it doesn't find any additional items (still at 16 devices). I have restarted the HA bridge and I feel like I have tried everything I know to try. I cannot get the new devices to add to my wife's profile even though the original ones added to both profiles successfully.

I only technically added 2 new devices (simple ones -- light and dimmer light), but I selected some additional ones I didn't add the first time I set it up. All of which are working fine in my profile, but I can't get the additional ones to add to her profile.

Any ideas???

**Comment by emiliosic** [comment]
Sounds like an issue with Echo. The Hue emulation doesn't know about Amazon profiles. Try forgetting the devices from the alexa app / web site (alexa.amazon.com) and re-discover.
you can see debug activity from the log tab, setting the logger to debug. It will log the activity when the Echo is discovering devices.

**Comment by pattont** [comment]
Couple more quick things:

1. I am not running on port 80, I am running this on ubuntu with the firewall disabled. Obviously, echo can connect since it finds the devices on my profile

2. I noticed in the config file there was a "whitelist" followed by what looks like a device ID. Does anyone know if that is a device ID or perhaps it's device+user id. What I'm thinking is the Hue is bound to my profile now and my wife's can no longer see it. I had the first set of devices working on both, but I can't seem to get them now.

**Comment by pattont** [comment]
Ok... ok... fixed it.. I went downstairs to the actual Alexa and asked her to discover devices and she was able to find them. Weird that you can't do it from the app considering its doing the same thing, but whatever.. Fixed
