### ISSUE TITLE
Is there anyway to customize the voice trigger?

### ISSUE THREAD

**Issue by masterchop** [bwssytems/ha-bridge#335]
In order to use this integration which works very well, thanks for this :)
You always need to say a state ON/OFF on your voice commands, is there any way to just sent a word, like   alexa i am leaving and run a script to shutdown the house.

**Comment by digiltd** [comment]
Nope.

For stuff like that I like to use "mode" in the device name i.e. "empty house mode" "bedtime mode" "night mode"

Allowing you to say "turn bedtime mode on" or "turn off empty house mode". Which sounds a bit more natural :)

**Comment by masterchop** [comment]
Sounds like a good solution to me :+1: 
Thanks for this, it made everything so simple.

**Comment by audiofreak9** [comment]
The Harmony Hub now has an Alexa Skill and the channels work exactly the same way with the skill.  You have to say, "Alexa, turn on Fox".  To get full control you will need to make your own custom Alexa Skill.  The ON and OFF or DIM terms are part of the Philips HUE bridge protocol, which the ha-bridge emulates.

**Comment by masterchop** [comment]
Thank you for clarification, I provide next course of action :)
I will keep working with this solution until i manage to build my own. Thank you
