### ISSUE TITLE
Fibaro support

### ISSUE THREAD

**Issue by snoopy86** [bwssytems/ha-bridge#336]
Could you add support for fibaro?

**Comment by fergie** [comment]
👍
Looks like a lot of the work has already been done by Domotics, although would be nice if they'd publish it and contribute it back to the community:
http://www.domotics.sg/how-to-integrate-vera-and-fibaro-harmony-and-nest-to-amazon-echo/

**Comment by Matt8119** [comment]
This is "automation asia's" version of this ha-bridge.  They edited it a bit, but the same file.

**Comment by Matt8119** [comment]
If anyone is interested, DM me and I'll send it to you..

**Comment by snoopy86** [comment]
@Matt8119 Please share if you have, so maybe we can make pull request and merge it together.

**Comment by Matt8119** [comment]
[AUTO Asia ha bridge Ghome.zip](https://github.com/bwssytems/ha-bridge/files/696001/AUTO.Asia.ha.bridge.Ghome.zip)

**Comment by bwssytems** [comment]
So, I am not going to put this into 4.1.0 but the next version. Need to work on this independently with someone who has a fibaro and can test the alpha versions for me.

**Comment by marcfon** [comment]
I can test fibaro stuff. Let me know what you need.

**Comment by bwssytems** [comment]
@marcfon When I start implementing it, I will only be able to unit test the calls. You'll need to run the release and see if it actually works against a real fibaro

**Comment by sege** [comment]
I could to some testing as well. Just let me know when there's something to test!

**Comment by CelticWebSolutions** [comment]
I've just received a Fibaro HC2, I've used your bridge with my Vera for some time, I still have the Vera but I'm switching quietly over the the Fibaro so I am more than happy to help testing if you need anything. 

Thanks!
Huw

**Comment by CelticWebSolutions** [comment]
Looking back at the last message before me being in the middle of Feb, has any progress already been made on the Fibaro integration?

**Comment by bwssytems** [comment]
unfortunately, no... slow as a turtle on this

**Comment by CelticWebSolutions** [comment]
Not much I can say there then lol

**Comment by Matt8119** [comment]
looking for pointers on how to setup virtual devices on Fibaro.  does anyone have any examples they can share?

**Comment by leyton01** [comment]
Also willing to help test a possible plug in on a Fibaro

**Comment by leyton01** [comment]
Is fibaro integration on the roadmap or is it not a priority at this stage?

**Comment by bwssytems** [comment]
It is on the map somewhere.... looking into the next features

**Comment by bwssytems** [comment]
Fibaro Support will be in 5.0.0

**Comment by CelticWebSolutions** [comment]
Excellent news!

**Comment by leyton01** [comment]
Great news - looking forward to the new version
