### ISSUE TITLE
Multiple devices same name different requester IPs

### ISSUE THREAD

**Issue by elgerg** [bwssytems/ha-bridge#337]
I am trying to set up 2 TVs in 2 rooms with 2 echo devices.

I thought ok, so set up one for each room using the same name but restricted by IP. That doesnt work as i assume you are using name as a non-duplicate key?

How would you go about being able to use the same name for on/off commands (TV, Main Light etc) in multiple rooms?

If you could make the requester IP/MAC available in the same way as the $intensity stuff that could work for me.

Thanks for the advice in advance

**Comment by bwssytems** [comment]
Version 4.0.0 will have the correct way to add requester IP to the device url itself. The way it is handled in 3.5.1 does not work as the echo's talk to each other about what devices are available. In essence it will do what you are asking and there will be a special format for the device by adding a "filterIPs" field.

**Comment by elgerg** [comment]
Ah that makes sense. As I've set my other 2 devices up I've not had to discover devices to get "new" listings.

Thanks again for the great work, it's much appreciated!

Regards
