### ISSUE TITLE
Beta Test 4beta1 V4.0.0 available

### ISSUE THREAD

**Issue by bwssytems** [bwssytems/ha-bridge#338]
Please test:

 http://bwssystems.com/files/ha-bridge-4beta1.jar

All items in the issues labeled for milestone V4.0.0 are in this release, click her eto see: https://github.com/bwssytems/ha-bridge/milestone/28

Urls now are created with specifiic information per call. All devices have the multi command construct:
```
[{item:<something>,type:<atype>....},{item:<another item>,type:<aType>}]
```
Here are the fields that can be put into the call item:
String or JsonElement item;
Integer count;
Integer delay;
String type;
String filterIPs;
String httpVerb;
String httpBody;
String httpHeaders;
String contentType;

For the type field, it should be one of these (it is the first value in the array:
```
public class DeviceMapTypes {

	public final static String[] CUSTOM_DEVICE = { "custom", "Custom", "none"};
	public final static String[] VERA_DEVICE = { "veraDevice", "Vera Device", "vera"};
	public final static String[] VERA_SCENE = { "veraScene", "Vera Scene", "vera"};
	public final static String[] HARMONY_ACTIVITY = { "harmonyActivity", "Harmony Activity", "harmony"};
	public final static String[] HARMONY_BUTTON = { "harmonyButton", "Harmony Button", "harmony"};
	public final static String[] NEST_HOMEAWAY = { "nestHomeAway", "Nest Home Status", "nest"};
	public final static String[] NEST_THERMO_SET = { "nestThermoSet", "Nest Thermostat", "nest"};
	public final static String[] HUE_DEVICE = { "hueDevice", "Hue Device", "hue"};
	public final static String[] HAL_DEVICE = { "halDevice", "HAL Device", "hal"};
	public final static String[] HAL_BUTTON = { "halButton", "HAL Button", "hal"};
	public final static String[] HAL_HOME = { "halHome", "HAL Home Status", "hal"};
	public final static String[] HAL_THERMO_SET = { "halThermoSet", "HAL Thermostat", "hal"};
	public final static String[] MQTT_MESSAGE = { "mqttMessage", "MQTT Message", "mqtt"};
	public final static String[] EXEC_DEVICE_COMPAT = { "exec", "Execute Script/Program", "command"};
	public final static String[] CMD_DEVICE = { "cmdDevice", "Execute Command/Script/Program", "command"};
	public final static String[] HASS_DEVICE = { "hassDevice", "HomeAssistant Device", "hass"};
	public final static String[] TCP_DEVICE = { "tcpDevice", "TCP Device", "none"};
	public final static String[] TCP_DEVICE_COMPAT = { "TCP", "TCP Device", "none"};
	public final static String[] UDP_DEVICE = { "udpDevice", "UDP Device", "none"};
	public final static String[] UDP_DEVICE_COMPAT = { "UDP", "UDP Device", "none"};
	public final static String[] HTTP_DEVICE = { "httpDevice", "HTTP Device", "none"};
}
```

**Comment by jasondharper** [comment]
You rock.  So I've just loaded this up and am really interested in drilling in on the filtering by IP functionality.  Can't seem to find anything in the beta UI to filter?  Can you just help me to understand how I filter (ie., device ABC should only respond to echo 1, device XYZ should only respond to echo 2, etc.)?  Once I can figure out how to implement, I'll test straight away!

**Comment by bwssytems** [comment]
You will have to create a device with the generator, then add "filterIPs" in JSON notation as in the example above. It's a comma separated list. The new UI editor is still being worked on.

**Comment by jasondharper** [comment]
So just to make sure I've got this...if I were creating a device that makes an HTTP call and it should only respond to an Echo at 10.1.1.1, ON/OFF url would look something like this?

On URL:  {"item":"http://api.call.here", "httpVerb":"POST", "httpBody":"value1=1&value2=2","filterIPs":"10.1.1.1"}

??

**Comment by jasondharper** [comment]
Can also confirm that #330 has been resolved.

**Comment by jlekhter** [comment]
Just trying to understand - if I have 5 echos, do I create 5 devices named "lights" and each one with a different filterIP.  If that's the case, then what does the Echo discover? Do you de-dupe the devices.

**Comment by audiofreak9** [comment]
My existing heyu EXEC scripts are no longer working, example:
ON = "heyu on M8"
DIM = "heyu obdim M8 ${intensity.math(((X*-22)/255)+22)}"
OFF = "heyu off M8"
Error = Could not execute request: "heyu on M8", etc...

So when I edit any EXEC and click update, it creates a new nameless device and does not update the existing device.

What is the new "type" construct for Execute Script/Program?  Exec?

**Comment by audiofreak9** [comment]
When I edit existing harmony buttons and click update the commands are doubled.

Existing ON command:
{"device":"32829113","button":"PowerOn"}
becomes:
[{"item":{"device":"32829113","button":"PowerOn"},"type":"null"},{"item":{"device":"32829113","button":"PowerOn"},"type":"null"}]

**Comment by glyxkecks** [comment]
It seems to work and https://github.com/bwssytems/ha-bridge/issues/261 seems to be fixed partitially.
Partitially because intensity is send as 1 Byte for 127 and below, while it is send as 2 Bytes for 128 and above.

**Comment by bwssytems** [comment]
@jasondharper Your url is close

On URL: [{"item":"http://api.call.here", "httpVerb":"POST", "httpBody":"value1=1&value2=2","type":"httpDevice","filterIPs":"10.1.1.1"}]

**Comment by bwssytems** [comment]
@jlekhter There would be one device named "lights" and all echos find it. If you want only certain echos to cal it then you put in the filter up for those echos in the ON/DIM/OFF commands.

**Comment by jasondharper** [comment]
@bwssytems  Ah, got it.  And so if I wanted to create multiple items for lights, I just repeat the item with different filter info?  Example:

Turn on Lights in Bedroom 1 (http://api.call.here/1) - Restricted to Echo 1 (10.1.1.1)
Turn on Lights in Bedroom 2 (http://api.call.here/2) - Restricted to Echo 2 (10.2.2.2)
Turn on Lights in Bedroom 3 (http://api.call.here/3) - Restricted to Echo 3 (10.3.3.3)

Device:  "Lights"
On URL: [{"item":"http://api.call.here/1", "httpVerb":"POST", "httpBody":"value1=1&value2=2","type":"httpDevice","filterIPs":"10.1.1.1"},{"item":"http://api.call.here/2", "httpVerb":"POST", "httpBody":"value1=1&value2=2","type":"httpDevice","filterIPs":"10.2.2.2"},{"item":"http://api.call.here/3", "httpVerb":"POST", "httpBody":"value1=1&value2=2","type":"httpDevice","filterIPs":"10.3.3.3"}]

Do I have that right?  Makes sense to me just wanted to verify.

**Comment by bwssytems** [comment]
@audiofreak9 Yep, need to fix the device edit. Also, your heyu ON commands what is the deviceMapType in the deviceDb for this device. I may be having a selection issue on the type for backwards compatibility.

**Comment by audiofreak9** [comment]
For each of my heyu devices, the deviceMapType is null.

**Comment by bwssytems** [comment]
@jasondharper You are correct in your URL handling for filtering.

**Comment by bwssytems** [comment]
@audiofreak9 and your deviceType should be "exec" for those correct?

**Comment by audiofreak9** [comment]
@bwssytems Correct, deviceType is "exec" and deviceMapType is not even set in the JSON.

**Comment by bwssytems** [comment]
@audiofreak9 try the new beta....

New beta is out

Closing as this is now continued under #344
