### ISSUE TITLE
Alexa discovery

### ISSUE THREAD

**Issue by casskrygier** [bwssytems/ha-bridge#339]
Hi

I have the bridge running and seems to be available in the network as the hue app so discovery seems to be on the bridge side.  I'm running 3.2.

I'm not sure of what logs I should be attaching so switched on a few.  Would really appreciate some guidance on how to get this working:

12-29-2016 22:31:13.248	INFO	Traceupnp: sendUpnpResponse discovery responseTemplate1 is <<<HTTP/1.1 200 OK
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 EXT:
 LOCATION: http://192.168.1.99:8085/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 hue-bridgeid: 000088FFFE00BBEE
 ST: upnp:rootdevice
 USN: uuid:2f402f80-da50-11e1-9b23-00008800bbee::upnp:rootdevice
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener
12-29-2016 22:31:13.248	INFO	Traceupnp: sendUpnpResponse discovery responseTemplate2 is <<<HTTP/1.1 200 OK
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 EXT:
 LOCATION: http://192.168.1.99:8085/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 hue-bridgeid: 000088FFFE00BBEE
 ST: uuid:2f402f80-da50-11e1-9b23-00008800bbee
 USN: uuid:2f402f80-da50-11e1-9b23-00008800bbee
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener
12-29-2016 22:31:13.255	INFO	Traceupnp: sendUpnpResponse discovery responseTemplate3 is <<<HTTP/1.1 200 OK
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 EXT:
 LOCATION: http://192.168.1.99:8085/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 hue-bridgeid: 000088FFFE00BBEE
 ST: urn:schemas-upnp-org:device:basic:1
 USN: uuid:2f402f80-da50-11e1-9b23-00008800bbee
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener
12-29-2016 22:31:13.255	INFO	Traceupnp: isSSDPDiscovery found message to be an M-SEARCH message.	com.bwssystems.HABridge.upnp.UpnpListener
12-29-2016 22:31:13.255	INFO	Traceupnp: isSSDPDiscovery found message to be valid under strict rules - strict: true	com.bwssystems.HABridge.upnp.UpnpListener
12-29-2016 22:31:13.255	INFO	Traceupnp: SSDP packet from 192.168.1.103:56264, body: M-SEARCH * HTTP/1.1
 Host: 239.255.255.250:1900
 Man: "ssdp:discover"
 ST: ssdp:all
 MX: 5
 
	com.bwssystems.HABridge.upnp.UpnpListener
12-29-2016 22:31:13.422	INFO	Traceupnp: sendUpnpResponse discovery responseTemplate1 is <<<HTTP/1.1 200 OK
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 EXT:
 LOCATION: http://192.168.1.99:8085/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 hue-bridgeid: 000088FFFE00BBEE
 ST: upnp:rootdevice
 USN: uuid:2f402f80-da50-11e1-9b23-00008800bbee::upnp:rootdevice
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener
12-29-2016 22:31:13.424	INFO	Traceupnp: sendUpnpResponse discovery responseTemplate2 is <<<HTTP/1.1 200 OK
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 EXT:
 LOCATION: http://192.168.1.99:8085/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 hue-bridgeid: 000088FFFE00BBEE
 ST: uuid:2f402f80-da50-11e1-9b23-00008800bbee
 USN: uuid:2f402f80-da50-11e1-9b23-00008800bbee
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener
12-29-2016 22:31:13.427	INFO	Traceupnp: sendUpnpResponse discovery responseTemplate3 is <<<HTTP/1.1 200 OK
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 EXT:
 LOCATION: http://192.168.1.99:8085/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 hue-bridgeid: 000088FFFE00BBEE
 ST: urn:schemas-upnp-org:device:basic:1
 USN: uuid:2f402f80-da50-11e1-9b23-00008800bbee
 
 >>>

**Comment by bwssytems** [comment]
For one, download the latest version and use that. and Two, search the issues that are closed in this list, most all questions have been answered.

**Comment by bwssytems** [comment]
Any update on this?

**Comment by casskrygier** [comment]
I haven't had an opportunity to troubleshoot today but I'll be back on it shortly and will try and search for some of the prior issues to see if there is anything I've missed....

**Comment by casskrygier** [comment]
All resolved.  I had changed my IP address but I had changed it to the IP address of my rm tasker bridge rather than the ip address the ha bridge was working on #idiot!  Anyway, gotta say this is a cracking little solution and will help to get around the current 16 device limit on the RM Tasker app (or at least I hope it will!).
