### ISSUE TITLE
Allow aliases for items

### ISSUE THREAD

**Issue by mavenius** [bwssytems/ha-bridge#342]
It would be nice to be able to have multiple names for the same item. E.g. I would like to be able to say "set the heat to 70" or "set the furnace to 70" and not have to configure two otherwise identical items.

If they each show up separately in Alexa, that's fine (and expected.)

**Comment by bwssytems** [comment]
Just makes it easier to do the copy than add so much code for alias handling.

**Comment by mavenius** [comment]
Fair enough; I am still getting things configured, so changes are happening
frequently. I wasn't sure how much headache exploding out items would be.

Thank you,

Mark Avenius

**Comment by bwssytems** [comment]
As always, test the base first then do the copy.... Have Fun!
