### ISSUE TITLE
Is a query possible?

### ISSUE THREAD

**Issue by jswim788** [bwssytems/ha-bridge#343]
Does the Amazon Echo/Alexa allow querying of a value?  The control works great, but I am wondering if there is a way using the HA Bridge to get Alexa to respond with a value.  For example, tell me the temperature or the current dimming value?

**Comment by bwssytems** [comment]
Nope. Not to the bridge or a philips hue hub which this emulates.

**Comment by bwired-nl** [comment]
Not sure if i understand your answer....
i had the same question, so its not possible the send via http respond or simular a value back to alexa which alexa will speak?  With the Siri bridge this is possible
thanks!

btw: just working with your bridge and thanks for all the good work :-)
regards Pieter

**Comment by bwssytems** [comment]
Amazon did not put that feature in for their connection to the Hue API. This is something I cannot change as it is not in the ha-bridge.

**Comment by bwired-nl** [comment]
This is not related to the Hue?
Your bridge gives me a request to my server and I can respond with a value.
Or is everything based on hue api? :-)

**Comment by bwssytems** [comment]
Everything from the Amazon Echo to the ha-bridge is based on the Hue API. The API has calls that give state back and the echo actually asks for them, but the echo does not have the code to handle your request.
