### ISSUE TITLE
Add editable Philips HUE version to config

### ISSUE THREAD

**Issue by audiofreak9** [bwssytems/ha-bridge#345]
I would like to request that the ha-bridge config file have the ability to manually update the reported Philips HUE version.  This will let users update the version for apps that report an update of the bridge is needed before the app will work again.

**Comment by bwssytems** [comment]
@audiofreak9 You did not look in the bridge control tab at the bottom now did you....

**Comment by audiofreak9** [comment]
I now feel so ashamed!  LOL!

**Comment by pr3sidentspence** [comment]
Did this go away, or is it only in the beta? I can't find it.

**Comment by bwssytems** [comment]
It is in the beta, and another issue has this for the next release.

**Comment by pr3sidentspence** [comment]
I'm trying this out, but the hue app says it needs an update. Does anyone know what the current hue hub version is? Or better yet, teach me how to find out myself.

**Comment by pr3sidentspence** [comment]
Ah, nevermind: http://hue.ip.add.ress/api/config

**Comment by audiofreak9** [comment]
Just follow this thread on Philips website: http://www2.meethue.com/en-us/release-notes/bridge/ they post release notes for each version update.
