### ISSUE TITLE
http changing state but not actually turning on the light. 

### ISSUE THREAD

**Issue by rodders99** [bwssytems/ha-bridge#346]
Pretty sure this is me being dumb : 

curl -X PUT -H "Content-Type: application/json" -d '{"deviceState": {"on": "true"}}' "192.168.0.4:9876/api/devices/200014"

Should turn the fan on. 

I get a response : 

id":"4000061","uniqueid":"00:17:88:5E:D3:3D093D-3D093D","deviceState": "on":true,"bri":0,"hue":0,"sat":0,"ct":0,"reachable":false}}

But the fan isn't on.

Am I being dumb ? And if so, can anyone point me the right direction to control ha-bridge from http if I'm on completely the wrong track. 

This is the final step in running a macro that lasts five minutes and doesn't time out Alexa with an error, or cause Alexa to fire the macro off multiple times, almost there !

Thanks

**Comment by bwssytems** [comment]
The call is like this: 192.168.0.4:9876/api/dummyusername/devices/200014/state

**Comment by audiofreak9** [comment]
@rodders99 
Did you get this resolved with the addition of the "/state" to the URL?
