### ISSUE TITLE
Status sync into ha-bridge via MQTT

### ISSUE THREAD

**Issue by linuxkidd** [bwssytems/ha-bridge#348]
I've come across a situation where Google Home will ack a voice command, but not issue the command if it detects the status is already that which was requested.

**Example:**

- "Main" light turned on via other method ( wall switch for example )
- "Hey Google, Turn off Main" -> "You got it, turning off Main"
- packet capture shows:
-- status query showing that 'on': 'false' for the "Main" device
-- No action packet sent

If I ask Google Home to toggle to the current state FIRST, then to the desired state, the command succeeds as the state will toggle with the first command (but no actual action is taken since the light is already in that state), then the second command will be sent by Google Home.  I've not noticed this issue w/ Amazon Echo devices so I presume they simply ignore the current state all together and blindly send the requested command.

**Request:**
- Provide a means of maintaining state via MQTT subscription. ( other means are welcome, but my current solution already has the state in MQTT, so this would be simple to integrate for my situation. )

If there already exists a means of injecting state into the ha-bridge system, please do let me know.

Thanks!

**Comment by jimboca** [comment]
There is a REST command https://github.com/bwssytems/ha-bridge/blob/master/README.md#update-bridge-internal-light-state

**Comment by bwssytems** [comment]
Yes, there is a way to inject state into the ha-bridge system. I created another call like the hue api state call but named it bridge update state. Call it like so: PUT http://ip_address_of_ha-bridge:port//api/username/lights/<light_id_in_ha-bridge>/bridgeupdatestate with bodge: {"on":<true or false>,"bri":a number}

You can call curl in a multi command to do this.

**Comment by linuxkidd** [comment]
Ah yes... thanks.. not sure how I missed this.  I still think it would be useful for an MQTT means of state synchronization.  Thanks!

**Comment by linuxkidd** [comment]
Ok, one other question.  How resilient is this process to heavy use.  I ask for I'm using ha-bridge as a means of controlling CAN-bus enabled lighting.  When 'on', the light sends a status on the bus once per second.  There are upwards of 40 lights, so if all were on, there's be 40 requests per second to this status update mechanism.  Would this be expected to cause any performance issues?  (I'm running this on a Pi3).

**Comment by bwssytems** [comment]
So, each call gets threaded off. it will be the bandwidth of the PI3 that will be the limiting factor. Try it!

**Comment by tyjtyj** [comment]
i dont have google home now but i do concern about future. 
Echo seems to work pretty fine for now
My device does not have a way to maintain status state, any work around ?

**Comment by bwssytems** [comment]
https://github.com/bwssytems/ha-bridge#update-bridge-internal-light-state

**Comment by bwssytems** [comment]
Is this resolved?

**Comment by linuxkidd** [comment]
Hello @bwssytems, I'd prefer to leave this open as a request for status update via MQTT subscription as in my case, this would be much preferred over generating additional http traffic into the habridge.

Thanks!

**Comment by chrisfraser05** [comment]
I'm struggling with this myself

I'd like to get Vera to update the status to HA Bridge and I've tried all sorts of itterations of the url

I'm just testing it from the browser at the moment, getting the response " Not Found" for everything I try.

would this be correct syntax?

http://192.168.1.10:80/api/username/lights/14/bridgeupdatestate{"on"}

Thanks

**Comment by bwssytems** [comment]
@chrisfraser05 You cannot use a browser to do this. Please read this https://github.com/bwssytems/ha-bridge#update-bridge-internal-light-state

**Comment by Matt8119** [comment]
Is it still possible, with the latest changes to inject state into the ha-bridge system. Using another call like the hue api state call but named it bridge update state. As stated in the post mentioned above.  for example, calling it: PUT http://ip_address_of_ha-bridge:port//api/userame/lights/<light_id_in_ha-bridge>/bridgeupdatestate with bodge: {"on":,"bri":a number}

By call curl in a multi command to do this.

**Comment by audiofreak9** [comment]
I think this is what you are asking for: https://github.com/bwssytems/ha-bridge#update-bridge-internal-light-state
