### ISSUE TITLE
Example of how to run ha-bridge along side a web server on port 80 for Google Home compatibility

### ISSUE THREAD

**Issue by linuxkidd** [bwssytems/ha-bridge#349]
In my situation, I wanted to keep a web interface running on port 80, but also allow Google Home to operate the ha-bridge enabled devices.  I accomplished this via a simple proxy configuration. These examples assume you are running ha-bridge http on port 8080.

**Example lighttpd config:**
```
server.modules   += ( "mod_proxy" )
proxy.server = ( 
	"/api" =>
        (
                ( "host" => "127.0.0.1",
                  "port" => "8080"
                )
        )
)
```

**Example apache config:**
```
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so

ProxyTimeout 1800

ProxyPass        /api  http://127.0.0.1:8080/api
ProxyPassReverse /api  http://127.0.0.1:8080/api
```

**Example nginx config:**
```
location /api/ {
    proxy_pass http://127.0.0.1:8080/api;
}
```

NOTE: I've personally tested and am running the lighttpd config noted above.  The others are adaptations based on other experiences which _should_ work, but have not been personally tested by me in this exact use case.

**Comment by bwssytems** [comment]
Thanks, that is good info!

**Comment by linuxkidd** [comment]
Sure thing.  It appears that Google Home ignores the port and always uses port 80.  So it's no problem that ha-bridge says to use port 8080.

**Comment by bwssytems** [comment]
There are a few other hue applications that default to 80 as well. People just don't read the api's or are lazy and do not implement the upnp handling process.

**Comment by joekmd** [comment]
@linuxkidd - your info was very helpful in solving my problem with having Apache and ha-bridge Google Home using port 80 on my server.  I am now able to have Apache serving web pages on port 80 and forward Google Home requests to ha-bridge on port 8080.

There were no changes made to ha-bridge config (ha-bridge is configured for port 8080).  I am not an Apache expert, but below is what worked for me in configuring a reverse proxy with Apache on Ubuntu linux:

a2enmod proxy
a2enmod proxy_http
a2enmod headers

Added the following lines to my apche config file “000-default”

<VirtualHost *:80>
	ProxyPass         /api  http://localhost:8080/api nocanon
	ProxyPassReverse  /api  http://localhost:8080/api
	ProxyRequests     Off
	AllowEncodedSlashes NoDecode

	# Local reverse proxy authorization override
	# Most unix distribution deny proxy by default (ie /etc/apache2/mods-enabled/proxy.conf in Ubuntu)
	<Proxy http://localhost:8080/api*>
		  Order deny,allow
		  Allow from all
	</Proxy>

….. (the rest of the VirtualHost config section) …..
</VirtualHost>

service apache2 restart

**Comment by paulheideman** [comment]
Thank you!

**Comment by bwssytems** [comment]
@linuxkidd Thanks for this. I updated the readme to reflect his post.

**Comment by epitsi** [comment]
Two notes trying to make this work with Google Home and nginx:

First, I was not able to make the pairing work, no matter what I tried, until I just "hijacked" my whole webserver for ha-bridge:

location / {
    proxy_pass http://127.0.0.1:8080;
}

After that, I was able to switch to

location /api/ {
    proxy_pass http://127.0.0.1:8080/api/;
}

as suggested by the tutorial, and everything works perfectly. Not the "/" at the end of the proxy_pass line that I used, which is *required* in nginx for things to work as intended. Please consider updating the readme.

Thanks to everyone for your help!

**Comment by linuxkidd** [comment]
Hello @epitsi .. I have switched my config from lighttpd to nginx and have had complete discovery/ normal operation with only the following:

```
	location /api {
		proxy_pass http://127.0.0.1:8080/api;
	}
```

I think my initial comment above having mixed / usage ( the location has a trailing /, but the proxy_pass does not ) may be the source of the issue you experienced.

**Comment by mbnn** [comment]
So on my Synology I have installed the Docker for HA Bridge (running on port 8123). However, I created a Reverseproxy for hostname habridge (port 80) to 127.0.0.1 (port 8123). This seems to work, when i enter http://habridge on any device in my LAN it pings the diskstation and I can access the web/api of  habridge.

However, both Alexa or Google Home dont find any devices, any idea what this could be? or is there something im missing? I dont have to change anything in the web interface for this to work right?

**Comment by mbnn** [comment]
Anyone?

**Comment by linuxkidd** [comment]
@mbnn You also need to map UDP ports 1900 and 50000.

**Comment by mbnn** [comment]
From where to where? :)

**Comment by linuxkidd** [comment]
From the physical machine's IP ( the Synology IP ) to the Docker container

**Comment by mbnn** [comment]
Well, first of all i cant get the /api to work in NGINX on the Synology for some strange reason :(
Next to that I think it would be a whole lot easier if there was a way to let the docker have its own IP for HA Bridge on the Synology. There just isnt any documentation on how to do that.

**Comment by linuxkidd** [comment]
To be more specific:
- There are 3 paths of data flow for the ha-bridge:
 + TCP Port 8080 (default) for the web interface and API calls
 + UDP Port 1900 (default) for uPNP listening
 + UDP Port 50000 (default) for uPNP response
-- All of these must be accessible on the network for anything to map the ha-bridge.
This report is specifically on how to run a normal web server on port 80, while forwarding the /api path to ha-bridge.

It's also important to note that from what I've found, @bwssytems is not the maintainer of the docker container.  Thus, while this community can help figure things out, it may be worthwhile to ping the docker maintainer for specifics on how his container works.

For my personal use of nginx with habridge, here's my full config:

`server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	server_name _;

	access_log off;
	error_log stderr crit;

	location /api {
		proxy_pass http://127.0.0.1:8080/api;
	}

}
`

**Comment by mbnn** [comment]
Yes, ive put that in a /sites-enabled/habridge.conf indeed and restarted NGINX. However when I then browse to the NASIP/api/devices i simply go to the NASIP:5000 (default synology stuff).

It is not possible to edit the nginx.conf because it gets overwritten with every restart on Synology.

**Comment by linuxkidd** [comment]
Sorry @mbnn ... looks like you'll need to seek help from a synology support forum.

**Comment by audiofreak9** [comment]
I have a Synology, but do not run the bridge on it, however, I'm pretty sure you'll need to specify different UDP uPNP listening and UDP uPNP response ports for the ha-bridge other than the defaults, since the Synology uses those ports already.

Also as was already suggested, try posting this over at [https://github.com/aptalca/docker-ha-bridge ](https://github.com/aptalca/docker-ha-bridge )for Docker related help.

**Comment by qnstie** [comment]
I struggled with forcing my Synology to forward :80/api to the Docker container with ha-bridge and the final working solution is:

Create (as a superuser, so e.g. `sudo vi FILENAME`) a file called `/etc/nginx/conf.d/www.habridge-google-home.conf`
with the contents:
```
location ^~ /api {
    proxy_pass http://127.0.0.1:8080/api;
}
```

The **`^~`** is crucial, without it `nginx` would always drop error 404.

I chose this solution as the simplest - Synology does not overwrite anything in `/etc/nginx/conf.d/` and the files `/etc/nginx/conf.d/www.*.conf` are inserted into the `nginx.conf` in the section of the server configuration related to port 80 (actually  - also to 443 (HTTPS), but this does not hurt).

Hope that helps someone :)

**Comment by mbnn** [comment]
Very cool @qnstie but which docker image did you use on your Synology? Since the aptalca one seems deprecated!?

**Comment by qnstie** [comment]
@mbnn I used aptalca, through the Synology Docker Registry UI (I did not have to use ssh for that). It is almost a year old, but works for me so far (although I already see shortcomings, like its inability to expose different types of devices - all is pushed to Alexa or Google Home as bulbs... now imagine a "Switch all lights" command applied to your door lock or blinders...).

Well - adding to Google home was straightforward in my case, the app did not demand any Hue login (I think the login page appeared for a moment, but disappeared instantly) - the devices registered in ha-bridge just appeared on the screen.
I do NOT own any real Hue devices nor Hue bridge, maybe you do. I guess this may cause such effects.

**Comment by sheriffdude** [comment]
Hi guys I no its not the same thing exactly but I am running the bridge .but it starts on 8081 port on windows 10 using a batch file to start ha bridge .but was using this with easy bulbs to turn off and on lights but can't get echo dot to find ha bridge .so was trying to start it on port 80 .but it will not start and if I change it in settings to 80 and save it just defaults back to 8081 so anyone got a clue how to fix this cheers

**Comment by mcwieger** [comment]
> **Example apache config:**
> 
> ```
> LoadModule proxy_module modules/mod_proxy.so
> LoadModule proxy_http_module modules/mod_proxy_http.so
> 
> ProxyTimeout 1800
> 
> ProxyPass        /api  http://127.0.0.1:8080/api
> ProxyPassReverse /api  http://127.0.0.1:8080/api
> ```

In which file (and where is it located) should I put this?

**Comment by sheriffdude** [comment]
Sorry but I don't have the answer I was using this ages ago to use with easy bulbs with Alexa not google .but gave up as I had to have laptop on all the time for it to work or out it on a android box .but ended up just putting wifi plugs on then sorry I could no help you

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bwssytems** [comment]
Please look at this link as well

https://github.com/bwssytems/ha-bridge#run-ha-bridge-alongside-web-server-already-on-port-80

**Comment by sheriffdude** [comment]
Yes but like i was saying it has to be turned on all the time i mean i got it all to work but i mean you could stick it on a small computer like like a raspberry but still would need to be on all the time

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bwssytems** [comment]
Yep, that is how these systems work.

**Comment by mcwieger** [comment]
> Please look at this link as well
> 
> https://github.com/bwssytems/ha-bridge#run-ha-bridge-alongside-web-server-already-on-port-80

It refers to a file called "000-default", which does not exist on my system (Apache on Synology).

I do see a file called 'httpd24.conf', which also loads a number of modules. Can I add it to that? Or should I add something to a file called 'proxy-html.conf', which also seems like a nice place for it, judging by its name.

(I'm clearly not an Apache expert)

**Comment by wesmannmsu** [comment]
Is this the reason why I can not get HA-Bridge to Pair with Harmony. I have HA-Bridge running on unraid in LinuxServerop Docker. 

I have the Bridge Setup, I have a Vera working in it (have a button, can turn on and off lights with it) and in my Harmony App, when I press, "Add device, Hue Bridge" it says, press the Link Button to pair. And I press the "link" button on the Control page, and it responds with "Pair in 30 seconds"" or something like that. 

but they never pair. is it because its looking on port 80 instead of the default for the docker 8080?

**Comment by bwssytems** [comment]
@wesmannmsu You may want to look at your routing for the Docker impl. I believe Harmony does not have an issue with port 8080, only the Alexa Echo does.

**Comment by 1nsomnia** [comment]
other solution. Bind 2 ip addresses to network and then bind ha-bridge to 1 and apache to the other
interfaces:
iface eth1 inet static
  address 192.168.1.1/24
iface eth1 inet static
  address 192.168.1.2/24

apache: ports.conf
Listen 192.168.70.11:80

ha-bridge:
ExecStart=/usr/bin/java -jar -Dserver.ip=192.168.1.2 -Dconfig.file=/opt/habridge/data/habridge.config /opt/habridge/ha-bridge-5.3.0.jar

**Comment by wesmannmsu** [comment]
Thanks for the tip, I will try that. going to have to locate a NIC card though,
