### ISSUE TITLE
Harmony Activities not showing up

### ISSUE THREAD

**Issue by dannieboiz** [bwssytems/ha-bridge#351]
I had to make some modifications to my system. Now under Harmony Activities and Device, nothing is showing up on there. How can I troubleshoot this issue?

**Comment by bwssytems** [comment]
Check your error logs, I think we have gone through debugging with you before....

**Comment by audiofreak9** [comment]
@dannieboiz 
Is this still a problem for you?

**Comment by dannieboiz** [comment]
I updated the app and it got resolved

**Comment by audiofreak9** [comment]
Good to hear, closing...resolved.
