### ISSUE TITLE
intensity.math to calculate an inverted percentage

### ISSUE THREAD

**Issue by peterosburg** [bwssytems/ha-bridge#352]
Hi,

I couldn't find something that helps me, that's why I am asking. I'd like to use intensity.math to calculate an inverted percentage.
Say, when I get 60% it shall calculate `100-60=40`. So I tried this statement `${intensity.math(100-${intensity.percent}}`
As this doesn't do the trick, I was looking in the documentation and saw something with "X" so I tried `100-X`, which wasn't bringing a good result, either.
So I wonder what "X" is and I also would love to get some hint on how to find a solution for the inverted percentage calculation.

Many thanks in advance.

**Comment by audiofreak9** [comment]
Try ${intensity.math((X-100)*-1)}. I think the X needs to come first.

**Comment by bwssytems** [comment]
Remember, in math the value that is past is 0-255. So you need to calculate from there.

**Comment by audiofreak9** [comment]
Oops, your right, try ${intensity.math(((X/255)-100)*-1)}

**Comment by bwssytems** [comment]
Why multiply by -1? I think he is trying to get the remainder and not the negative value.

 ${intensity.math(100-(X/255))}

**Comment by audiofreak9** [comment]
Sure, I've just not had success unless the X was first in the formula.

**Comment by audiofreak9** [comment]
So I have to get the negative result, then multiply by -1 to get positive returned.

**Comment by peterosburg** [comment]
Ok, so you say You is representing the value received from the command? 
When I looked at the code while my above mentioned code didn't work, I could see that the log told me, that in the brackets of math the formula was correctly set with 100-60 
Back then I used 
$integrity.math(100-{$integrity.percent}) it just was not evaluated.

**Comment by peterosburg** [comment]
Sorry, typo: You = X

**Comment by bwssytems** [comment]
@peterosburg Unfortunately, you cannot use 2 different types of replacements, it is one or the other. But the examples we gave with just intensity.math will do the same thing,

@audiofreak9 The X should not matter where it is in the formula, will check.

**Comment by bwssytems** [comment]
@peterosburg Sorry, yes 'X' is used in the code to insert the value received.

**Comment by audiofreak9** [comment]
@bwssytems, yeah I use ${intensity.math(((X*-22)/255)+22)} because I could not get something like ${intensity.math(22*(X/255))} to work for my X10.

**Comment by peterosburg** [comment]
Unfortunately the suggestions don't work. My roller blinds still go to the percentage position, not the calculated value. Can I somewhere debug or see the value that has been calculated by intensity.math?

**Comment by audiofreak9** [comment]
To see the value that is being calculated go to the Logs page, then open the Logging Configuration, then be sure the "Show All Loggers" checkbox is checked.

Find the "com.bwssystems.HABridge.hue.BrightnessDecode"  component, and set it's log level to "DEBUG", then click the "Update Log Levels" button.  

Try testing your device again from the Bridge Devices page by clicking the associated "Test Dim" button, use the slider to desired level and click "Set". 

Go back to the Log page and read the messages for "com.bwssystems.HABridge.hue.BrightnessDecode", it will read "Math eval is: (YOUR INPUT FOMULA), Where X is: {NUMBER VALUE}.  Do the math and see what the result comes out as.

**Comment by audiofreak9** [comment]
@peterosburg 
I have to backtrack my previous comment a bit, the "com.bwssystems.HABridge.hue.BrightnessDecode" log component does not current exist in current release, only in the 4.0.0 beta releases.  I apologize for any confusion.

**Comment by bwssytems** [comment]
Is this resolved?
