### ISSUE TITLE
Restore settings backups from another Pi?

### ISSUE THREAD

**Issue by jonohunt** [bwssytems/ha-bridge#353]
I've setup and been running HA Bridge without any problems, but have been having other problems (installing lots of things I don't really need).

So I setup a clean install of Jessie on a spare SD Card, installed HA Bridge again, etc. 

I wanted to copy the Device DB and Settings backups from the old SD Card to ~/habridge/data/ on the new SD Card then restore from the backups in HA Bridge to get things up and running, without having to manually set things up from scratch again.

It wouldn't let me copy them from the old SD Card as it said I didn't have permission. So I sudo copied them to another location, then changed the owner of the files to pi.

I stopped HA Bridge running, copied them to ~/habridge/data/ on the new SD Card, restarted the Pi, but didn't see the backups to restore from in HA Bridge. 

So I tried changing the owner back to root, rebooted again but still don't see the backups to restore from. 

I'm new to the Pi (and HA Bridge) so I'm guessing I'm doing something stupid.

How can I transfer the settings from one Pi and restore them on another one? Or is there a way to load and restore settings config files from any location, like you can with Domoticz?

**Comment by bwssytems** [comment]
There should be no issues for what you are trying to do. The config and db files are portable as long as you don't have the web server address set to a specific ip otherwise you will need to hand edit the habridge.config file.

**Comment by jonohunt** [comment]
Thanks.

So in theory I should be able to make copies of the habridge.config and device.db files, change ownership to pi (is this necessary, or should I just sudo copy and replace with the original permissions), and replace those on the new install of hb on the new SD Card, and that should work?

**Comment by bwssytems** [comment]
You are correct. The owners of the files will be set when you copy them in and if they are in the home/pi directory should be owned by pi.

**Comment by jonohunt** [comment]
Thanks for confirming that.

So I stopped HA Bridge on the new Pi, copied the files from the old Pi over to the new Pi, and it changed the owner from root:root to root:pi, not sure if that matters (is that as expected?). I replaced the habridge.config and device.db files, then rebooted the Pi.

It then showed the items I'd added under Bridge Control on the old Pi (Harmony, Nest and Hue). But it didn't show any devices I'd added manually (manual switches that run scripts, Harmony Activities etc.)

I then tried changing the owner to pi:pi (just in case it worked), and rebooted but that didn't do anything.


I then copied the backup files (.bk and .cfgb) from the old Pi to the new Pi, then rebooted. But it didn't show the backups at the bottom of the page that I could restore.

With what I've described should the backups I've copied over from the old Pi appear at the bottom of the pages on the new Pi?

**Comment by audiofreak9** [comment]
@jonohunt 
Are you still having problems with this issue?

**Comment by jonohunt** [comment]
Yes, I haven't been able to restore the settings on the new Pi from the old one (as described above).

**Comment by bwssytems** [comment]
How are you starting your bridge? What directories are you copying from and to? What is the start up command look like? This is just a config issue. Also, it in Linux, users determine directories and also where the ha-bridge is started. i.e. you try it on the command line and it uses one set of directories, starting it through the system startups use a different set of directories.

**Comment by jonohunt** [comment]
HA Bridge auto starts on boot with starthabridge.sh
(I tried the newer systemctl method, but all my Bridge Devices disappeared from the web ui, so I ended up going back to the old/original method.)

```
cd /home/pi/habridge
rm /home/pi/habridge/habridge-log.txt
nohup java -jar -Dconfig.file=/home/pi/habridge/data/habridge.config /home/pi/habridge/ha-bridge-3.5.1.jar > /home/pi/habridge/habridge-log.txt 2>&1 &
chmod 777 /home/pi/habridge/habridge-log.txt
```


I then did:

`sudo nano /etc/rc.local`


And added the lines between "fi" and "end"

`sudo /home/pi/habridge/starthabridge.sh`




To copy the files to a USB disk I did:

```
sudo cp ~/habridge/data/habridge.config  /mnt/usbdisk
sudo cp ~/habridge/data/device.db  /mnt/usbdisk
```



Then to copy them to the newer install:

```
sudo cp /mnt/usbdisk/habridge.config ~/habridge/data/

sudo cp /mnt/usbdisk/device.db ~/habridge/data/
```

**Comment by bwssytems** [comment]
when you copied the files back, did you change the owner of the files. They maybe based on the original system.

cd /home/pi/habridge
sudo chown pi:pi *

**Comment by jonohunt** [comment]
OK, I've changed permissions of habridge.config and device.db from root:root to pi:pi, copied them over the the new install, rebooted and it's successfully copied over the settings from the old install.

Thanks a lot for the help!

**Comment by Xavier38330** [comment]
Hi

I had to reinstall my RPI Raspbian and I when I reinstalled HA-BRIDGE, I copied the files in data directory.
The ha-bridge version was the same as before (v5.2.1) but the new installation never displayed my old configuration  with all my devices I created...
I checked the permissions, they are already pi:pi.

What am I missing to restore my device backup files ?

**Comment by bwssytems** [comment]
Do you have the same relative path to your data directory when you start the new ha-bridge instance?

**Comment by Xavier38330** [comment]
I successfully restored by configuring the config and moving back to my original habridge directory instead of ha-bridge.
