### ISSUE TITLE
Can't save rooms in hue app.

### ISSUE THREAD

**Issue by pr3sidentspence** [bwssytems/ha-bridge#354]
After putting in the latest version of the hue hub swversion (01036659) I was able to connect the hue app to ha-bridge 4beta2.7. After that, the hue app insists on making a room. 

![image](https://cloud.githubusercontent.com/assets/711433/21745764/58e5bb50-d4f8-11e6-848c-625a02401fed.png)

I can not save the room. I've tried all lights selected, just one, and none. I've tried removing spaces from my room name.

![image](https://cloud.githubusercontent.com/assets/711433/21745767/6b15cacc-d4f8-11e6-9c29-042587856b14.png)

The "Cancel" option simply takes you back to the create room screen, with no way to get out of it.

**Comment by audiofreak9** [comment]
This is the Version 2 HUE app and the ha-bridge, not being a real Philips HUE the ha-bridge does not allow for saving rooms, etc.  The original HUE app Version 1 will work with the ha-bridge.

**Comment by pr3sidentspence** [comment]
Ah. Does the hue gen 1 app allow for multiple bridges? It doesn't seem to let me do two. I guess that is why there's the pass through, but trying to add it does not seem to do anything. At least in 4beta2.7. I'll try it back in the release version.

**Comment by pr3sidentspence** [comment]
After going back to the release version and seeing up pass through, I've been spending a lot of time trying to find  an app that works with ha-bridge and will allow me to change a room or group of lights all at once. None of them seem to work.  Is there no way to group lights when using ha-bridge? Apologies if this is a dumb question. 

I'm trying to find one app that can allow me to control both my real hue lights and my ha-bridge emulated x10 devices. As audiofreak9 said, the gen 1 app allows this, but it doesn't seem to allow me to group lights.

**Comment by mysteryan** [comment]
I agree that grouping would be a useful feature.  It would make it easier to seamlessly consolidate different ecosystems of devices in a unified one under ha-bridge.  I've tried browsing through the source to see if I can at least add a static group definition.  I've since gave up on that effort due to lack of comprehension.

**Comment by pr3sidentspence** [comment]
I'm experimenting right now with manual adds using multiple commands and
the hue API to achieve this. So far it's not working, but it seems like it
should.

**Comment by audiofreak9** [comment]
The Alexa app lets you group lights for voice control, unless you are after an app to interact with by touch?

**Comment by audiofreak9** [comment]
I also <a href="http://coreyswrite.com/tips-tricks/phone-tablet-desktop-php-ha-bridge-control/">wrote a PHP driven control page</a> that allows you to control all devices configured on the ha-bridge.  You can run it from the same device the ha-bridge is on.

**Comment by pr3sidentspence** [comment]
Yes, the echo dot is in the living room, but we need a phone (iPhone) app for when we're in the bedroom. If I had the money, I could just get another dot, but the problem is with little kids, we don't want to wake them up issuing commands. I'll check out your control page, thanks.

**Comment by audiofreak9** [comment]
My PHP control page can be saved to the home screen from safari, and it will look and act like an app rather than just a webpage.

**Comment by pr3sidentspence** [comment]
It wasn't obvious from your screenshot, does your control page allow grouping?

**Comment by audiofreak9** [comment]
Not as coded currently, but it sure could.  I'll add rooms and grouping to the code asap!

**Comment by pr3sidentspence** [comment]
As I said earlier, I was playing with the multiple command constructs to make a "light" that was actually a room (or group). I was able to turn off my entrance (two hue bulbs in one ceiling fixture) by turning on or off one light in the old Hue, or other Hue apps that work with ha-bridge. So this is a solution.

Unfortunately, the release version doesn't (seem to?) like multiple commands, and I have had a lot of problems with the beta doing manual adds, so I don't think I can use this yet. But as the beta improves this should work fine.

**Comment by pr3sidentspence** [comment]
Oh, I found a better solution. Using the gen2 hue app, when you make rooms
they are created on the Hue hub. You can access them directly with the api.
So, for me, a habridge light with a put like:

http://<HUEipAddress>/api/<username>/groups/1/action  with body {"on":true,
"bri": 128} would turn on my master bedroom (ceiling and two lamps), and
set them to half brightness.

Now, I can easily have both x10 and hue lights, with groups, in gen1 apps.

**Comment by audiofreak9** [comment]
Glad you found a usable solution.  I'm still going to add rooms to my control page for those who don't have a real Philips Hue bridge.

**Comment by bwssytems** [comment]
Great! Closing as solved
