### ISSUE TITLE
Running Scenes

### ISSUE THREAD

**Issue by pattont** [bwssytems/ha-bridge#357]
I have a number of scenes like:

- All Kitchen Lights On, All Kitchen Lights Off
- All Downstairs Lights Off
- Good Night ((This turns off all the lights))

Is there no good way to tell Alexa, "Turn All Downstairs Lights Off"? Instead I have to say, Alexa, "Turn On All Downstairs Lights Off". I realize by "Turning On" I am running the scene. Is there no other keyword to use to run a scene? I realize this is not truely a HA Bridge issue as I can in-fact run the scene, I'm just hoping this targeted audience can assist since any Alexa forum probably has no clue what Vera even is or HA Bridge.

Thanks in advance!

**Comment by rafale77** [comment]
I would rename the scene "device" on the HABridge "Downstairs Lights". Create one scene to turn them on, Another (the one you already have) to turn them off and put them in the corresponding on and off commands for the "device" in the bridge. 
No good solution for Good Night. I just use the word "mode". So I call, "turn night mode on"

**Comment by pattont** [comment]
Oh you mean create them in the HA Bridge, but only have one "scene" from Vera. Just modify the command sent by the HA Bridge. 

Interesting...

**Comment by audiofreak9** [comment]
@pattont 
Have you resolved this issue?

**Comment by pattont** [comment]
yes!

**Comment by audiofreak9** [comment]
Great, closing as resolved.
