### ISSUE TITLE
Device state updates...

### ISSUE THREAD

**Issue by emigrating** [bwssytems/ha-bridge#358]
So, I have a bunch of devices running on ESP8266 - i.e. directly connected to my Wi-Fi network. Due to the location of some of these devices I will sometimes have to issue the same command twice for them to fire.

For example, one of the bedside lamps in the master bedroom, for whatever reason just doesn't hold a good network connection and I'll have to say "Alexa brighten the left bedside lamp to 10" (or press the button on my phone) several times before going to bed so I don't fall over in complete darkness and wake my wife up.

Now, these ESP8266 modules are running my own custom firmware so I figured a way around having to issue the commands several times would be for the device itself to update the state information in ha-bridge. This would also help in cases where you switch the device from outside of ha-bridge.

Seeing as there's already "state" information held by ha-bridge, I'd like the option for this to not change just by ha-bridge running the on/dim/off command, but rather wait for ack from the device in question. That way, if I run "back entrance : on" the command could repeat every second or so (for a predetermined length of time or N tries) until the device acknowledges the request by a http or udp call back.

In addition, I currently have each of my devices listen for an AYT message over UDP - basically, if I broadcacst "AYT!" to the network each device will ping back with name, MAC, IP and so on. It could be interesting to have ha-bridge automatically send such a message once every so often and update the "reachable" flag based on the [lack of] response. That way, if someone has physically switched off the device Alexa won't just say Ok, but rather reply that there's a problem reaching the device.

Any chance you could look into adding something like this?

**Comment by bwssytems** [comment]
Would really need to take a look on how to implement that. Others rely on the current operation of the state tracking. If you can send an http command out of your firmware, you could update the bridges state for a device as there is a special api call for that.

**Comment by emigrating** [comment]
Are you talking about _PUT http://host:port/api/<username>/lights/<id>/state_ or is there a different method I'm not aware of?

The issue with the above is that it, as far as I can tell, changes as soon as the command is issued - which means I can't use it to track if the bulb actually received the command or not.

The same is true for _PUT http://host:port/api/<username>/lights/<id>/bridgeupdatestate_. While that would update state fine, it seems the variable is the same that changes automatically?

A simple 0/1 toggle on the device should suffice here. If AutomaticStateHandling = 1 (default) things work as they do today, if = 0, do not update state when a command is issued from ha-bridge.

**Comment by bwssytems** [comment]
@emigrating That would be an enhancement for a future release.

**Comment by bwssytems** [comment]
For legacy compatibility, I'll add a flag to disable state handling

**Comment by emigrating** [comment]
Awesome. Thanks!
