### ISSUE TITLE
(NOOB question) how do update to current version on my raspberry Pi?

### ISSUE THREAD

**Issue by Matt8119** [bwssytems/ha-bridge#359]
I have the current version of the Ha-bidge installed on my raspberry Pi and i haven't found any tutorials or directions on how push the next update once its released to my Pi, without losing my current settings.  Any help would be greatly appreciated

**Comment by bwssytems** [comment]
Download the new jar where you have the current jar, then update any calls to use the new jar name.

**Comment by Matt8119** [comment]
the first part seems pretty straight forward.  now you mentioned "updating any calls to use the new jar name."  im not too clear on how you you would update any calls that will correspond with the new jar file name.

**Comment by bwssytems** [comment]
That means how you start the ha-bridge, you can't use the old jar name, use the new jar name.

**Comment by tinker3433** [comment]
Or name your jar something generic like ha-bridge.jar and then just rename each new version as you download it to that and then overwrite the old version with it. No messing around with updating calls etc.

**Comment by audiofreak9** [comment]
@Matt8119 Has this issue been resolved for you?

We now have a FAQs page for the ha-bridge.  I included the entire step by step process to accomplish this.  Find this particular FAQ here: https://github.com/bwssytems/ha-bridge/wiki/HA-Bridge-FAQs#update

**Comment by Matt8119** [comment]
Yes, you did. I appreciate this very much! Thanks!
