### ISSUE TITLE
PUT Method for Fibaro Integration

### ISSUE THREAD

**Issue by intellimation** [bwssytems/ha-bridge#360]
I am using the PUT method for changing the value of a variable. It keeps throwing back and error Error on calling url to change device state: url...

I am using json/application format to make the call, but it always errors out. I am not sure how this needs to be used

**Comment by bwssytems** [comment]
Would need to see the error output. Turning on debug would also help.

**Comment by bwssytems** [comment]
Is this resolved?

**Comment by intellimation** [comment]
No this is not resolved yet... I will send you the requested inputs..

**Comment by bwssytems** [comment]
Is this resolved?
