### ISSUE TITLE
Echo not passing percentage correctly 

### ISSUE THREAD

**Issue by Djbower1** [bwssytems/ha-bridge#362]
I think this is a amazon issue as it has only started happening today. Im hoping someone using the bridge and echo can confirm its an issue. 

 My echo is hearing the percent as per cent. So when I say "Turn Lounge lights on to 75 percent" it does not work. If I say Turn Lounge lights on to 75" everything works fine.

Ta

Dan

**Comment by CPM-luvr** [comment]
I noticed this several days ago but I just checked it and it works fine now. I simply say "Dining room light 50%".

bwssystems has my unending gratitude for creating this service. It enabled me to get rid of the Wink and keep the controls local. It also enabled me to integrate my Vera3 with the harmony Hub I bought recently. Thank you!

**Comment by Djbower1** [comment]
I tried
"echo lounge light 50%"
Echo heard "echo lounge light fifty per cent" (according to history log)
and responded
"Please try again, with the device name and setting."

**Comment by audiofreak9** [comment]
@Djbower1 
Have you done the Echo voice training yet?  It helped my family greatly when i came to interpreting what we say to the Echo.  http://alexa.amazon.com/spa/index.html#settings/voicetraining

**Comment by Djbower1** [comment]
There is currently no voice training available on the uk version of the echo :(

**Comment by audiofreak9** [comment]
Bummer, sorry to learn that!  It really helped me and my family.  I would send Amazon feedback stating that the UK model needs this option.  Hopefully the UK version allows you to submit feedback?
http://alexa.amazon.com/spa/index.html#feedback

**Comment by Djbower1** [comment]
I have sent them several just today as I am very annoyed its stopped working. I have 2 echo and 3 dots in my house all doing the same thing.

**Comment by paulnd** [comment]
My UK Echo now also responds with "Please try again, with the device name and setting" when I try to dim my lights...

**Comment by Djbower1** [comment]
Glad someone else is having the same issue. Mine will now 1 in 20 times work when saying percentage. It has to be an amazon issue as I have made no changes to my setup. 

I got this back from amazon.

"This is Paul from the Echo support team and I'm sorry to hear about the issue you are having with Alexa with having to rephrase the way you adjust your heating.
I'll share your feedback with our Alexa development team. I know they'll want to hear about your experience.
Your feedback helps us improve your experience with Alexa.
We look forward to seeing you again soon."

I dont know why they refereed to heating when it lights :) But as you can tell from the reply it didn't help me in anyway.

**Comment by Djbower1** [comment]
@paulnd FYI mine issue is exactly the same!

**Comment by Matt8119** [comment]
Dim Command thats working for me is this on the Google home. should be the same for Alexa

http://xxxxxxx:xxxxxxx@192.168.0.xx/api/callAction?deviceID=47&name=setValue&arg1=${intensity.percent}

Can even just say "ALEXA LED STRIP 50%"

**Comment by Djbower1** [comment]
@Matt8119  Thanks for you comment. I understand the syntax and i am using similar with my setup. The problem has started happening for no reason after working for the past 3 months. 

Are you from the UK?

**Comment by bwssytems** [comment]
Is this resolved?

**Comment by Djbower1** [comment]
Hello, I have been meaning to post an update but keep forgetting. It seems like everything is working again at the moment. I guess it was an Amazon issue. Fingers crossed the problem is resolved.
