### ISSUE TITLE
Vera thermostats with Google Home

### ISSUE THREAD

**Issue by neurolizer** [bwssytems/ha-bridge#363]
Is there a way to configure my Vera thermostats in HABridge so that Google Home responds that it is setting a temperature instead of "setting the **brightness** to # **percent**"?

**Comment by bwssytems** [comment]
Yes, there is. look on this forum as it has been posted there I believe.

http://forum.micasaverde.com/index.php/topic,31920.0.html

**Comment by neurolizer** [comment]
Hmm, I've read every post in that thread since November, as well as every post on the MiCasa forum with google, temp, or thermostat in it. I wonder if maybe I didn't present my question clearly. My Vera devices (including thermostats) are being controlled wonderfully by both Alexa and Google Home via the HABridge (thank you so much for that!). My question is simply a nitpick with how GH responds to my thermostat commands. Since GH sees the thermostat as a light in the Hue Hub, it responds that it is setting _brightness_ instead of temperature. The command still adjusts my thermostat correctly though. This isn't an issue with Alexa since she just responds with OK. How can I get GH to see the Hue device as a thermostat instead of a light?

**Comment by audiofreak9** [comment]
@neurolizer Since the ha-bridge emulates a real Philips Hue bridge, the Echo treats it like a real Philips Hue bridge.  The interaction between the Echo and the ha-bridge will only consist of the available Echo / Hue interactions.  This being On, Off & Dim commands with "OK" as the confirmation.  

If you want this type of interaction, then you can create your own Alexa Skill and program your own responses as well.  It's really not too daunting to be honest, just [a bit of reading](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/getting-started-guide).

**Comment by bwssytems** [comment]
@neurolizer Clarification... You can control your vera thermostat by using the constructs of on, off and dim in the ha-bridge, You will need to find the http luup call for that type of device into the vera to set this. This is in essence how the nest thermostats are handled.

**Comment by audiofreak9** [comment]
I did not know that...learn something new every day!

**Comment by Matt8119** [comment]
The Dim Command im using on google home, that should be the same for Alexa

http://xxxxxxx:xxxxxxx@192.168.0.xx/api/callAction?deviceID=47&name=setValue&arg1=${intensity.percent}

Works a treat with the HA-Bridge

You can just say "Hey Google, LED STRIP 50%"

**Comment by bwssytems** [comment]
Unfortunately, that is not what Vera expects. The Vera helpers I have do switches and scenes. There is another type that is used for thermostats with Vera.

**Comment by neurolizer** [comment]
I feel like I am missing something very obvious or my question is still not being understood correctly. I am not asking how to control my thermostats. Basically what I want to know is how can I make the light bulb icons I have circled in red below be thermostat icons instead?
![image](https://cloud.githubusercontent.com/assets/11532663/21959077/88a7d450-da79-11e6-8cce-d99e6f1466fa.png)
My first guess would be to just set the bridge device type setting to Thermo, but that doesn't seem to have any effect.
![image](https://cloud.githubusercontent.com/assets/11532663/21959106/5fd74898-da7a-11e6-994c-3bc56c7b2ba4.png)
I don't have a Nest, but I would expect if you connect a Nest to ha-bridge, Google Home will interpret it as a thermostat and thus the icon will be a thermostat instead of a light bulb, right? Is this not possible with Vera thermostats on ha-bridge? Am I doing something wrong? Maybe there is a bug in that the ha-bridge Device Type setting is not functioning properly for Vera devices?

FYI, these are some of the http luup commands to control a Vera thermostat with ha-bridge:
```
http://veraip:3480/data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:TemperatureSetpoint1&action=SetCurrentSetpoint&NewCurrentSetpoint=${intensity.percent}&DeviceNum=#
http://veraip:3480/data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:TemperatureSetpoint1_Cool&action=SetCurrentSetpoint&NewCurrentSetpoint=${intensity.percent}&DeviceNum=#
http://veraip:3480/data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:TemperatureSetpoint1_Heat&action=SetCurrentSetpoint&NewCurrentSetpoint=${intensity.percent}&DeviceNum=#
```

**Comment by rafale77** [comment]
Audiofreak is correct. You are missing one key point which is that this bridge is a philips hue emulator: it turns devices like the vera and harmony or nest and makes them look like a hue bridge to echo and google home. What you are asking is to change the hue bridge into a thermostat withing google home which is not within the scope of this bridge.

**Comment by neurolizer** [comment]
Thank you everyone for your patience with me. I understand that ha-bridge is a Philips Hue Hub emulator. My confusion was that I thought the Hue Hub was able to control Nest thermostats due to some article titles I had seen about connecting the two together. Coming from a Vera background, I just assumed that the Hue Hub would control the thermostat, but I finally went back to watch some YouTube videos about connecting Nest with Hue and it seems that the connection only allows Nest to control the Hue lights and not the Hue Hub to control Nest.
