### ISSUE TITLE
Question: Running multiple commands when called from Alexa

### ISSUE THREAD

**Issue by ragunathd** [bwssytems/ha-bridge#367]
When I say, Turn on Entertainment to my alexa, I want the following set of actions to triggered.

1. Run a script (that sends x10 commands to turn on power to my entertainment system"
2. Invoke Harmony activity to trigger "Entertainment activity"

I have 1 and 2 individually working from Alexa->HABridge.  I want to combine them.  I understand that HAbridge supports to call multiple commands ( sequence of scripts  or sequence of Harmony activity), I'm not sure how to mix them.

Could you please someone help or point me in right direction?

Thanks
Ragu
Btw, HABridge rocks. RPi+HABridge+Alexa is really works well.

**Comment by audiofreak9** [comment]
[Multiple Call Construct](https://github.com/bwssytems/ha-bridge#multiple-call-construct)

**Comment by ragunathd** [comment]
Thanks you for the response.  I'm aware of the multi-call-construct. May be, i don't know how to use that for my need.  I guess I don';t know the http url for my Harmony bridge triggers.  Has anyone combined harmony triggers and running shell commands?

**Comment by bwssytems** [comment]
Yeah, this is not straightforward as you need to combine different types into one call. The example for you is:

[{"item":"exec://<your script call here>","type":"execDevice"},{"item":"{"name":"<activity id from harmony"}","type":"harmonyActivity"}]

The "activity id from harmony" is the id you see in the harmony tab. You can create the activity in the tab and copy it into this construct as shown.

**Comment by bwssytems** [comment]
Is this resolved?
