### ISSUE TITLE
Any idea?

### ISSUE THREAD

**Issue by rebirth24** [bwssytems/ha-bridge#37]
Why I keep getting this popup error while navigating through the menus?

"Get Vera Devices Error: undefined"

**Comment by bwssytems** [comment]
Do you have any vera's configured?

**Comment by rebirth24** [comment]
Nothing under Vera Devices or Vera Scenes.  All insteon devices configured under "Configuration"

**Comment by bwssytems** [comment]
So, do you have the parameter -Dvera.address=<something> on your command line? If you do, that is what is causing this as the bridge is trying to talk to that ip as a Vera and it fails. As it sounds like you do not have a Vera.

**Comment by rebirth24** [comment]
Silly me! Thanks for the support!

**Comment by bwssytems** [comment]
You are welcome. Anytime.
