### ISSUE TITLE
Enchantment: run on Onhub 

### ISSUE THREAD

**Issue by pr3sidentspence** [bwssytems/ha-bridge#370]
So, I learned today that my Google onhub which I bought based on the (as yet unfulfilled) promise that they would enable the USB, Bluetooth, ZigBee and wave antennas, is basically a scrabbles Chromebook and is rootable. 

While expensive when I bought mine (thanks again, Google), they can be found pretty cheap now. I'm wondering if ha-bridge was put on it, if it could actually control hue lights and many other ZigBee devices without needing a hub. 

I suspect it would be no easy task. But it would be cool.

**Comment by bwssytems** [comment]
So, your request is a bit grand to what the ha-bridge is. The ha-bridge is basically a protocol converter. Take API A request and turn it into API X request. This is actually building the Home Automation Endpoint. Maybe you could request this from Home Assistant, as that system is setup to do what you want.

**Comment by pr3sidentspence** [comment]
Just a bit.  Does home assistant actually have the hardware like the onhub does? I'll look into it. I know this was kind of silly.

**Comment by bwssytems** [comment]
It actually is not silly. If the onhub has all those hardware features, it's just software to make it work, which is what Home Assistant is....

**Comment by pr3sidentspence** [comment]
Oh, I was confused with Google Assistant. I'll check it out.
