### ISSUE TITLE
Enhancement: Work with gen2 app

### ISSUE THREAD

**Issue by pr3sidentspence** [bwssytems/ha-bridge#372]
I'm not sure this is a possibility, but it would be enormously helpful if ha-bridge could work with the gen2 hue app, because:

1) The hue gen2 app is nicer than the gen1
2) It has better room support
3) It's widget on iOS works (not sure why gen1's doesn't)
4) Apple's Homekit discovers what hue lights you have by being told it from the hue gen2 app. So allowing gen2 app also allows Homekit/Siri control.

**Comment by bwssytems** [comment]
I would have to think about this. The current intent of the ha-bridge is not to be the perfect end point for true hue apps. This would be down on the list for consideration.

**Comment by pr3sidentspence** [comment]
A workaround for this would be to create a default room so that the gen2 app will not try to force you to make one. I *think* that if ha-bridge reported that it had a room configured, then (with the version properly set) the gen2 app would work. At least, this is where it stops working now.

**Comment by bwssytems** [comment]
I'll add the create group call as a dummy.
