### ISSUE TITLE
Question: Why Nest support?

### ISSUE THREAD

**Issue by pr3sidentspence** [bwssytems/ha-bridge#377]
I suspect that the issues isn't the best place to ask this, but I don't know where else to ask.

What does Nest integration in ha-bridge do for someone that they wouldn't be able to do without it?

**Comment by audiofreak9** [comment]
You gotta remember not every one who has an Echo and uses the ha-bridge lives in a country that has all the Alexa skills available.

**Comment by bwssytems** [comment]
Also, Originally there was no skill for Nest in the Amazon library and that skill does not go as far as the nest integration on the bridge.
