### ISSUE TITLE
Switching light with pilight and ha-bridge url do not work in ha-brdige

### ISSUE THREAD

**Issue by domiboss81** [bwssytems/ha-bridge#382]
Hello, firstly sorry for my terrible englisch, i have the following problem.
i want to use pilight, the url command for this is: 

http://192.168.1.x:xxxx/send?{%22action%22%3A%22control%22%2C%22code%22%3A{%22device%22%3A%22Switch1%22%2C%22state%22%3A%22onf%22}}

but when i set ist as On URL, than i get a error.

"Request Error, Pleae look in your habridge log.error ("type" 6,"address"."/lights/1","description"Error on calling url to change device.....)

when i try it in a web Browser from Windows 7 or from my Cell phone in the same network, than i can switch my light.

i have try the ip 127.0.0.1 too, with the same result.

**Comment by pr3sidentspence** [comment]
I think curly braces "{}" are interpreted by ha-bridge. You might need to
escape them with a backslash "\".

**Comment by pr3sidentspence** [comment]
Or URL encode them:


The { symbol should be replaced with %7B and } with %7D.

**Comment by domiboss81** [comment]
Thank you for your help

i have try both tips, but i get the same error

**Comment by bwssytems** [comment]
@domiboss81 Unfortunately they did a terrible job on handling commands as the should use rest. There example shows to encode everything including the '?' like so:
```
send%3F%7B%0A%09%22action%22%3A%20%22control%22%2C%0A%09%22code%22%3A%20%7B%0A%09%09%22device%22%3A%20%22mainlight%22%2C%0A%09%09%22state%22%3A%20%22on%22%2C%0A%09%09%22values%22%3A%20%7B%0A%09%09%09%22dimlevel%22%3A%20%2210%22%0A%09%09%7D%0A%09%7D%0A%7D
```

**Comment by bwssytems** [comment]
Link to this info here:

https://manual.pilight.org/en/api

**Comment by domiboss81** [comment]
@bwssytems Thank you for your help

When i understand it right, i have to change my config.json.
my conifg.json didnt have the programm line
"values": {7  "dimlevel": 10]

My config.json looks like this

{
	"devices": {
		"Switch1": {
			"protocol": [ "intertechno_old" ],
			"id": [{
				"id": 0,
				"unit": 4
			}],
			"state": "off"
		},
		"Switch2": {
			"protocol": [ "intertechno_old" ],
			"id": [{
				"id": 1,
				"unit": 4
			}],
			"state": "on"
		},


I'm sorry for this stupid questions, I'm still new in this area and my english is not the best.

**Comment by domiboss81** [comment]
oh sorry i have seen that the site is in german too.
i try to understand the api. Thank you very much for youre help.

**Comment by timherrm** [comment]
This is working for me in habridge 4.0.0. 
Needed a few hours to figure this out.

Device Type (Informational)

- Type:
- HTTP Device
- Target Item: http://10.0.2.12/send?%7B%22action%22:%22control%22,%22code%22:%7B%22device%22:%22schrank%22,%22state%22:%22on%22%7D%7D

Change "schrank" to you device name from config.json and state to on/off, and the IP Adress to your pilight address.
Don't choose any HTTP Verb or Content Types
Press Add for On and Off Items, Press Update Bridge Device.

![screenshot](https://cloud.githubusercontent.com/assets/23706249/22380695/9c2b0f7a-e4be-11e6-89e4-2e03a84f4667.png)

PS Jetzt wo ich alles in Englisch geschrieben habe lese ich in der letzten Zeile, dass ich wohl hätte Deutsch schreiben können.

**Comment by domiboss81** [comment]
@timherrm Hallo, entschuldige das ich jetzt erst antworten kann. 

Ich Danke Dir. Es funktioniert einwandfrei. Tausend Dank. Dann brauch ich das ganze jetzt nicht weiter über Scripte zu machen.
