### ISSUE TITLE
Whitelist IP addresses

### ISSUE THREAD

**Issue by pr3sidentspence** [bwssytems/ha-bridge#383]
Is there a way to restrict the entire (spark?) web server to specific IP addresses?

I don't mean just access to lights, but the webpage itself, and api calls. I want to be able to allow specific static IPs on the internet to reach it, but have everyone else talk to the hand.

**Comment by bwssytems** [comment]
yes, that is the web server address in the bridge control tab.

**Comment by bwssytems** [comment]
But if you mean access to the bridge itself, you'll need to control it on the router

**Comment by pr3sidentspence** [comment]
Stupid onhub. Grr. Guess which feature is lacking.

**Comment by bwssytems** [comment]
Get a different router....

**Comment by pr3sidentspence** [comment]
I would, but it's coverage is pretty amazing. But... I might switch it into
bridge mode and start using my ISP router to do the complex stuff.

**Comment by bwssytems** [comment]
So, OnHub does not have an advanced page to handle external routes of from/to. Most cheapo routers even have this capability.

**Comment by pr3sidentspence** [comment]
OnHub is marketed as a plug it in and forget it router. I knew this going in, I bought it because of (a) The promised (but unrealized) smart home integration, (b) the amazing coverage (it is amazing), and (c) my suspicion (incorrect) that it would become what ended up being Google Home.

I knew it didn't have advanced features, but said to myself, when was the last time you used advanced features, and after admitting it had been years, took the plunge. Then promptly needed advanced features.

That being said, Google is adding features all the time. I don't think it even had port forwarding when I bought it.

**Comment by bwssytems** [comment]
go ahead and close this issue then.
