### ISSUE TITLE
Home Assistant doesn't detect ha-bridge

### ISSUE THREAD

**Issue by pr3sidentspence** [bwssytems/ha-bridge#385]
I'm trying out Home Assistant and it does not detect ha-bridge. I've tried unplugging my real Hue hub, during the process, as well as reinitializing ha-bridge during HA's attempts to find it; with no luck.

HA probably has some manual ip entry, but I haven't found it yet.

**Comment by jbardi** [comment]
Is your habridge running on port 80? In 2 seperate homes I have automated, more than half of the devices and services would not find the habridge unless it was running it on port 80. Now I just set them all up on port 80 by default.

**Comment by Matt8119** [comment]
@jbardi this habridge runs on port 80

**Comment by Matt8119** [comment]
@pr3sidentspence here's a guess blog that got home assistant running with the ha bridge.  Check it out http://fearoffish.com/home-automation/home-assistant-and-ha-bridge/

**Comment by pr3sidentspence** [comment]
Yes, port 80.

**Comment by pr3sidentspence** [comment]
Yeah, I found that blog post, too. However he was going the other way,
discovering hass devices in ha-bridge.

**Comment by bwssytems** [comment]
I have this working. I had to re install Home Assistant with the latest version.

**Comment by pr3sidentspence** [comment]
Hmm.. I just installed Home Assistant yesterday, using pip3. Did you get it some other way?

**Comment by bwssytems** [comment]
Sorry, I was wrong on that...I added a vera...

**Comment by bwssytems** [comment]
so, is this anjust for fun exercise or a need....

**Comment by pr3sidentspence** [comment]
Was a need. But I've switched to using hass + fauxmo to control my old legacy x10 stuff and am no longer using ha-bridge.

**Comment by zombiehunter1** [comment]
Will this actually work? I have some mqtt devices setup on ha-bridge  I want hass to discover ha-bridge  so I can use the devices, else I'll have to duplicate mqtt calls in hass

hass is currently giving me error messages
