### ISSUE TITLE
Limitless LED not working in v4.0.1

### ISSUE THREAD

**Issue by dmsims** [bwssytems/ha-bridge#388]
Worked fine in v3.5.1 (and still works)

Not working in v4.0.1

from log:

01-24-2017 13:36:51.390 	INFO 	Hue description service started.... 	com.bwssystems.HABridge.upnp.UpnpSettingsResource
01-24-2017 13:36:51.393 	INFO 	Hue emulator service started.... 	com.bwssystems.HABridge.hue.HueMulator
01-24-2017 13:36:51.433 	INFO 	UPNP Discovery Listener starting.... 	com.bwssystems.HABridge.upnp.UpnpListener
01-24-2017 13:36:51.454 	INFO 	UPNP Discovery Listener running and ready.... 	com.bwssystems.HABridge.upnp.UpnpListener
01-24-2017 13:38:29.670 	WARN 	Error calling out to HA gateway: IOException in log 	com.bwssystems.HABridge.plugins.http.HTTPHandler
01-24-2017 13:38:29.671 	WARN 	Error on calling url to change device state: udp://192.168.1.81:8899/0x350055 	com.bwssystems.HABridge.plugins.http.HTTPHome
01-24-2017 13:38:32.472 	WARN 	Error calling out to HA gateway: IOException in log 	com.bwssystems.HABridge.plugins.http.HTTPHandler
01-24-2017 13:38:32.473 	WARN 	Error on calling url to change device state: udp://192.168.1.81:8899/0x350055 	com.bwssystems.HABridge.plugins.http.HTTPHome

**Comment by bwssytems** [comment]
Post your config for this device please. Something is not working for previous configs

**Comment by dmsims** [comment]
I hope this is what you need
![bridgedevice](https://cloud.githubusercontent.com/assets/4712953/22253620/35039388-e24a-11e6-96ea-9d6818388b1c.png)

**Comment by bwssytems** [comment]
Change your Device Type to UDP. The new bridge resolves 'Custom' device type to HTTP.

**Comment by dmsims** [comment]
Setting type to UDP worked - thank you
