### ISSUE TITLE
TypeError: Cannot set property 'name' of undefined

### ISSUE THREAD

**Issue by audiofreak9** [bwssytems/ha-bridge#39]
Javascript error anytime I click the "Clear Device" button: **TypeError: Cannot set property 'name' of undefined**  Caused by the $scope.clearDevice = function () in the aps.js file line 511, seems "olddevice" is not defined.

**Comment by bwssytems** [comment]
Yep, Thanks. I ought to vet my variables.... supposed to be olddevicename with no dot.
