### ISSUE TITLE
Pairing Google Home to ha-bridge v4.0.2

### ISSUE THREAD

**Issue by adit262** [bwssytems/ha-bridge#391]
I updated to the new 4.0.2 version but cannot get Google Home to pair with ha-bridge. The following error is thrown in the ha-bridge log:

> Jan 24 08:04:40 raspberrypi java[10299]: 2017-01-24 08:04:40,376 [qtp18328106-31] ERROR spark.webserver.MatcherFilter -
> Jan 24 08:04:40 raspberrypi java[10299]: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $
> Jan 24 08:04:40 raspberrypi java[10299]: at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
> Jan 24 08:04:40 raspberrypi java[10299]: at com.google.gson.Gson.fromJson(Gson.java:879)
> Jan 24 08:04:40 raspberrypi java[10299]: at com.google.gson.Gson.fromJson(Gson.java:844)
> Jan 24 08:04:40 raspberrypi java[10299]: at com.google.gson.Gson.fromJson(Gson.java:793)
> Jan 24 08:04:40 raspberrypi java[10299]: at com.google.gson.Gson.fromJson(Gson.java:765)
> Jan 24 08:04:40 raspberrypi java[10299]: at com.bwssystems.HABridge.hue.HueMulator.lightsListHandler(HueMulator.java:528)
> Jan 24 08:04:40 raspberrypi java[10299]: at com.bwssystems.HABridge.hue.HueMulator.lambda$7(HueMulator.java:132)
> Jan 24 08:04:40 raspberrypi java[10299]: at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
> Jan 24 08:04:40 raspberrypi java[10299]: at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162)
> Jan 24 08:04:40 raspberrypi java[10299]: at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61)
> Jan 24 08:04:40 raspberrypi java[10299]: at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
> Jan 24 08:04:40 raspberrypi java[10299]: at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
> Jan 24 08:04:40 raspberrypi java[10299]: at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
> Jan 24 08:04:40 raspberrypi java[10299]: at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
> Jan 24 08:04:40 raspberrypi java[10299]: at org.eclipse.jetty.server.Server.handle(Server.java:517)
> Jan 24 08:04:40 raspberrypi java[10299]: at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
> Jan 24 08:04:40 raspberrypi java[10299]: at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
> Jan 24 08:04:40 raspberrypi java[10299]: at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
> Jan 24 08:04:40 raspberrypi java[10299]: at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
> Jan 24 08:04:40 raspberrypi java[10299]: at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
> Jan 24 08:04:40 raspberrypi java[10299]: at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
> Jan 24 08:04:40 raspberrypi java[10299]: at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
> Jan 24 08:04:40 raspberrypi java[10299]: at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
> Jan 24 08:04:40 raspberrypi java[10299]: at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
> Jan 24 08:04:40 raspberrypi java[10299]: at java.lang.Thread.run(Thread.java:745)
> Jan 24 08:04:40 raspberrypi java[10299]: Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $
> Jan 24 08:04:40 raspberrypi java[10299]: at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:388)
> Jan 24 08:04:40 raspberrypi java[10299]: at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:209)
> Jan 24 08:04:40 raspberrypi java[10299]: ... 24 common frames omitted

Any ideas what could be going on?

**Comment by bwssytems** [comment]
you'll need to post your devices config as something is not right with them.

**Comment by adit262** [comment]
I have a bunch of Philips Hue lights, along with some RF-controlled outlets. I can control the lights using the ha-bridge website but cannot get Google Home to pair correctly with ha-bridge. 

Here is the output from ip/api/devices: (I removed some of the mac addresses/codes).

[{"id":"11","uniqueid":"00:XX:XX:XX:XX:XX-0B","name":"Plant Lamp","deviceType":"exec","targetDevice":"Encapsulated","offUrl":"[{\"item\":\"/var/www/html/rfoutlet/codesend 1234567 -l 185\"}]","dimUrl":"","onUrl":"[{\"item\":\"/var/www/html/rfoutlet/codesend 1234568 -l 185\"}]","deviceState":{"on":false,"bri":0,"hue":0,"sat":0,"effect":"none","ct":0,"alert":"none","reachable":true}},{"id":"12","uniqueid":"00:XX:XX:XX:XX:XX-0C","name":"TV Lamp","mapId":"00:XX:XX:XX:XX:XX:XX:XX-0b","mapType":"hueDevice","deviceType":"passthru","targetDevice":"LR Hue","offUrl":"[{\"item\":\"{\\\"ipAddress\\\":\\\"10.0.0.2\\\",\\\"deviceId\\\":\\\"1\\\",\\\"hueName\\\":\\\"LR Hue\\\"}\",\"type\":\"hueDevice\"}]","dimUrl":"[{\"item\":\"{\\\"ipAddress\\\":\\\"10.0.0.2\\\",\\\"deviceId\\\":\\\"1\\\",\\\"hueName\\\":\\\"LR Hue\\\"}\",\"type\":\"hueDevice\"}]","onUrl":"[{\"item\":\"{\\\"ipAddress\\\":\\\"10.0.0.2\\\",\\\"deviceId\\\":\\\"1\\\",\\\"hueName\\\":\\\"LR Hue\\\"}\",\"type\":\"hueDevice\"}]"}]

**Comment by sognen** [comment]
Hi,
I just wanted to confirm that I am seeing the same error message in my log. The output from /api/devices looks fine. However the output from /api/discovery.xml gives me: <html><body><h2>500 Internal Error</h2></body></html>. This may be the reason why we are having issues with pairing it with GH.

If I remove all bulbs the output from /api/discovery.xml is valid json with config, whitelist etc.  

Cato

**Comment by bwssytems** [comment]
Verified. Will be fixing
