### ISSUE TITLE
LIFX support

### ISSUE THREAD

**Issue by leyton01** [bwssytems/ha-bridge#396]
From my reading I could control LIFX bulbs using UDP under the manual add button.  Is this correct and if so would you consider adding a 'friendly' way for packets to be constructed (ie a GUI with selections that create a packet). 

LAN API here:
https://github.com/LIFX/lifx-protocol-docs/blob/master/README.md
Or
https://lan.developer.lifx.com

Building a packet:
https://lan.developer.lifx.com/docs/building-a-lifx-packet

Discussion here:
https://community.lifx.com/t/building-a-lifx-packet/59/
Including example code:
https://community.lifx.com/t/building-a-lifx-packet/59/7

This would allow LIFX bulbs to be controlled with many more applications (ie Hue compatible) and would also make them faster and more reliable as the current supported control in most applications is through the cloud, which is flaky at best.

**Comment by bwssytems** [comment]
This impl will be a fun one. The YeeLight is also a discover/ip based system, so this will set the architecture.

**Comment by bwssytems** [comment]
Ordered a Lifx bulb today and found a java lifx library. Shouldn't be too hard.

**Comment by leyton01** [comment]
Great - there are 2 ways to access the bulbs, via the cloud or local
network.  The cloud API was the original and has most development but lacks
some of the reliability of the LAN API.

Cheers
Leyton

**Comment by bwssytems** [comment]
The Android App can't even connect on my network... I understand now there needs to be a better way

**Comment by ahielg** [comment]
Hello,
Can you add support for color changing in LIFX?

**Comment by bwssytems** [comment]
Eventually, that is request #327

**Comment by huongminh** [comment]
Hello,

I don't see any Lifx bulbs on the tab LIFX Devices. How can I see them? the LIFX support checkbox is checked TRUE and I clicked SAVE. After that the LIFX Devices tab appears but nothing in there. I have no issue seeing Domoticz and Hue devices.

**Comment by bwssytems** [comment]
Turn on debug for 	com.bwssystems.HABridge.plugins.lifx in the Logs tab (click show all loggers to find)

**Comment by huongminh** [comment]
I did it and read in the log:

![image](https://cloud.githubusercontent.com/assets/19623472/23832754/178b7be2-076e-11e7-8025-3f7b5abc6360.png)

![image](https://cloud.githubusercontent.com/assets/19623472/23832758/40ec7f4a-076e-11e7-823c-ef9e36d102e6.png)

**Comment by huongminh** [comment]
For the IO exception, I found it is because of my homebridge for Apple homekit is running with LiFx plugin. I stopped homebridge, reinitiated Habridge and found my Lifx device under the LIFX Device Tab. I build some LIFX devices, however it did not run stably. Press the tests buttons and it was hit and miss all the time

**Comment by huongminh** [comment]
this is the log when the test button would not work
![image](https://cloud.githubusercontent.com/assets/19623472/23833214/1f0ab714-0775-11e7-94b3-7c2f1cc6f689.png)
And in the LIFX device, my LIFX bulbs kept appearing and disappearing. In the log it read LIFX devices added and removed...

**Comment by bwssytems** [comment]
Unfortunately, The LIFX protocol is not stable from what I have seen as well.

**Comment by huongminh** [comment]
![image](https://cloud.githubusercontent.com/assets/19623472/23833257/981b951a-0775-11e7-9d83-51c4e4c5d926.png)

It seems the LIFX homebridge plugin and Habridge plugin use the same LAN API and communicate with LIFX via port 56700. However, I've run the LIFX homebridge plugin for 10 months and it was very stable.
