### ISSUE TITLE
Can't run old multiple commands anymore

### ISSUE THREAD

**Issue by jonohunt** [bwssytems/ha-bridge#399]
I’ve upgraded to 4.2 (previously 3.5.1) and I can’t get my old commands to work, turning on/off 2 LightwaveRF lights at the same time.

It’s very possible I’m doing something wrong due to the new changes, but whatever I try doesn’t work. (I've tried adding them as individual entries, combined entries in the regular fields, and combined entries in the bottom legacy fields without any luck)

These are the commands I use to use after creating a manual button and setting the type as UDP:

On
```
[{"item":"udp://10.0.1.180:9760/001,!R2D1F1","delay":1000},
{"item":"udp://10.0.1.180:9760/001,!R2D2F1"}]
```

Dim
```
[{"item":"udp://10.0.1.180:9760/100,!R2D1FdP${intensity.math(X/8)}","delay":1000},
{"item":"udp://10.0.1.180:9760/100,!R2D2FdP${intensity.math(X/8)}"}]
```

Off
```
[{"item":"udp://10.0.1.180:9760/001,!R2D1F0","delay":1000},
{"item":"udp://10.0.1.180:9760/001,!R2D2F0"}]

```

Any help would be appreciated.

**Comment by bwssytems** [comment]
I am going to guess, that the Device Type is not UDP for this item. Updating the line items to be the udpDevice in the new editor will fix this, i believe.

**Comment by jonohunt** [comment]
I've already done that (if I understand correctly)

Here's screenshots of what I've tried

http://d.pr/i/lzcd

http://d.pr/i/y2TT

http://d.pr/i/GQW8

http://d.pr/i/FDR

(I've tried setting 'Device Type (Informational)' as UDP as well)

**Comment by bwssytems** [comment]
So, are you getting errors in your log? I need to see the log from the process output.

**Comment by bwssytems** [comment]
@jonohunt http://d.pr/i/lzcd is the correct syntax, suggest to move the delay to the first item as that is what controls the delay after the call.

**Comment by jonohunt** [comment]
Thanks, I've moved the delay to the first items. When I press the button it shows this in the logs:

Could not decode Json for url items: 40 for hue state change request: test from 10.0.1.11 body: {"on":true} url items: [{"item":"udp://10.0.1.180:9760/001,!R2D1F1","type":"udpDevice","delay":"1000"},{"item":"udp://10.0.1.180:9760/001,!R2D2F1","delay":"","type":"udpDevice"}]

**Comment by bwssytems** [comment]
Interesting, I've cut and pasted your udp request on my system on Windows and it is working.

**Comment by jonohunt** [comment]
Strange.

If I use the commands separately for each light they work fine, just not combined anymore.

**Comment by bwssytems** [comment]
I get it to work under 4.0.2, Turn on Debug for the UDP plugin

Here is my configuration for your device
![udptestmulticommand](https://cloud.githubusercontent.com/assets/13528314/22309332/701c234c-e310-11e6-8788-f13ac3e264a2.png)

**Comment by bwssytems** [comment]
Try the new 4.0.3 version, that has some fixes

**Comment by jonohunt** [comment]
That's it, it seems to be working OK now! Thanks for the help! (again)
