### ISSUE TITLE
Enhancement: pretend to be hue lights 

### ISSUE THREAD

**Issue by pr3sidentspence** [bwssytems/ha-bridge#400]
This might/would need some sort of ZigBee adapter, and reverse engineering the comms. But it would allow anything compatible hue hub or app to control those fake lights, which would then be x10, nests, etc. 

This might be another project, but I thought I'd share the idea.

**Comment by bwssytems** [comment]
Not in my plans, even for another project. Philips did a good job, go buy one, it's easier.

**Comment by pr3sidentspence** [comment]
I have :)

But this would allow for not only Echo control, but also control from gen2 apps, and secure remote access through myhue (or whatever they call it), as well as fix problems where ha-bridge isn't detected. I think though, that you are right, it doesn't belong in this project.

If anyone would like to brainstorm the requirements of this with me, please let me know. My username at hot mail.

**Comment by pr3sidentspence** [comment]
FYI, It occurred to me that this would be better done with tp-link or wemo devices, as they use wifi instead of Zigbee. It turns out this has already been done with fauxmo (https://github.com/makermusings/fauxmo).

**Comment by bwssytems** [comment]
So, I do appreciate your input. But please know that there are so many other home automation tools that do the things your asking. Please google for those first as I am not trying to build the state handling endpoint.

**Comment by pr3sidentspence** [comment]
Roger that.

**Comment by pr3sidentspence** [comment]
As I, and others, have run into the boundaries of the scope of this project recently. Perhaps you might consider adding a, "What this is / What this is not" in your documentation.
