### ISSUE TITLE
Dim Values 0.0 to 1.0

### ISSUE THREAD

**Issue by beandi** [bwssytems/ha-bridge#401]
Adding a Homematic dimmable actor through the xml-API does work for on and off but not for dim-values: It seems like the statechange-url needs a value between 0.000 and 1.000, but the "intensity"-functions only generates values between 0 and 255.
Where can this behaviour be altered?

**Comment by bwssytems** [comment]
This would be an enhancement to the intensity calculation. Currently it receives a value of 1-254 as that is what the Hue api expects. Most systems deal with integer as well when they are called from the ha-bridge. Looks like Homematic wants decimal to three places.

**Comment by beandi** [comment]
made a workaround with a shell script, which calculates a decimal value from intensity.percent. It still would be nice, if the function is implemented natively.
Nevertheless, really great piece of work - thanks a lot!

**Comment by bwssytems** [comment]
It would have to be selective per item... Something to think about

**Comment by plenet** [comment]
had the same issue. my workaround this at the end of the dim url:
State(0.${intensity.math(X/25.5)});

**Comment by beandi** [comment]
Tried the workaround with the "0." in front, but was used to saying "100%" - then it doesnt work.
What do you mean "selective per item"?
My script gets 2 variables passed, intensity and device_id, so it will work for all homematic dimmers. Will post it tomorrow, if anyone is interested.

**Comment by bwssytems** [comment]
This will be a new value, ${intenstiy.decimal_percent}
