### ISSUE TITLE
[feature request] Web Users/Login

### ISSUE THREAD

**Issue by insanerwayner** [bwssytems/ha-bridge#402]
Would be nice if you could setup a login with password for getting into the WebUI to keep unwanted users out of the config. Possibly maybe even different users down the line with different permissions.

**Comment by tuicemen** [comment]
Add me to the list of users wishing this.
A regular user and admin user would be all I would require.
Regular user only has access to the devices screen with the edit/copy & delete buttons hidden

**Comment by bwssytems** [comment]
So, I am going put this in has the whole UI security. There will now be a button to register a device just like a real hue and the UI will be locked if this is used by password. There will also, be the option to lock the REST API by password as well.

**Comment by tuicemen** [comment]
Yes!!!
Thanks, I can't wait!
