### ISSUE TITLE
Reset a devices intencity level

### ISSUE THREAD

**Issue by Weingummi** [bwssytems/ha-bridge#403]
I use Ha-bridge anderen Alexa to control my TV via a selfmade RPi IR remote. With DIM I can say turn up TV and the volume goes up by e.g. three ticks. However, Alexa remembers the intencity level of the device and will not increase the volume if it is at maximum, or decrease at minimum. Is there a way to tell Alexa that the intencity is e.g. at 50% after each command, in order to only use relativ intencity?

**Comment by bwssytems** [comment]
This is an extension that was made on the ha bridge to do this: https://github.com/bwssytems/ha-bridge#update-bridge-internal-light-state

**Comment by Weingummi** [comment]
Yes, that seems like it should do the trick. Yet, I have difficulties getting it to work...

On DIM I want to run my script and then reset the brightness to 127, but the call

```
curl -H "Content-Type: application/json" -X PUT -d "{ "on": true , "bri": 127 }" http://192.168.2.106:8081/api/devices/lights/1/bridgeupdatestate
```

doesn't change either. In fact, the "bri" does also not work for a simple /lights/1/state PUT, only ON/OFF works here. The log states:

com.bwssystems.HABridge.hue.HueMulator - Update state requested: devices from 192.168.2.106 body: { on: true , bri: 127 }

Any idea what's wrong/missing here?

**Comment by bwssytems** [comment]
What version are you running? And I'll take a look.

**Comment by Weingummi** [comment]
Version 4.0.2, and just updated to 4.0.3, still the same.

**Comment by bwssytems** [comment]
Ok, you can do this call to see what the value is after the bridgeupdatestate to verify

GET http://192.168.2.106:8081/api/dummyuser/lights/1 and look at the bri value

**Comment by Weingummi** [comment]
Yes, I did that, it does not change. "Bri" does also not change if I use state instead of bridgeupdatestate. Maybe thats part of the problem. However, On/off works with state.

**Comment by bwssytems** [comment]
There are no errors returned on your call? I tested this and it is working fine with your body as the payload.

**Comment by bwssytems** [comment]
Could you post the return of the curl call, it will have a messsage

**Comment by Weingummi** [comment]
I only get [] for the above PUT call, no success message or something

**Comment by bwssytems** [comment]
So that is a problem.

**Comment by bwssytems** [comment]
put single quotes around the body, the double quotes end up matching in the command line

**Comment by Weingummi** [comment]
Well, that solved something, how foolish.. Now I receive success Messages for both and the values are updated correctly. Nevertheless, the Main Problem remains.

When I use bridgeupdatestate in the DIMurl the new brightness is still taken from the Input  e.g. Test value, and not the one from my put call. Hence, the brightness is not 'reset'.

**Comment by bwssytems** [comment]
Change the order, If you want a specific value to start from, set it first then do the next call.

**Comment by Weingummi** [comment]
Of course, the thing is, that bridgeupdatesate does not seem to work for the requesting device itself, since my entered default brightness is never set.

If I just add one task to the dim section of device 1:
- Type: Http Device
- Target item: http://192.168.2.106:8081/api/devices/lights/1/bridgeupdatestate
- Http Verb: PUT
- Http Body: {"on": true,"bri": 127}
- Content Type: application/json

After calling the DIM, the brightness level is not 127 but the input value. On the other hand, there is no problem in using bridgeupdatestate to change the brightness for a different device (e.g. 4 instead of 1). Seems to me like I cannot call bridgeupdatestate for the requesting device..?

**Comment by bwssytems** [comment]
I believe this implementation will let you control what you want #358

**Comment by bwssytems** [comment]
So, have you tried v4.1.0 and use the setting to not track state for a device and then use the update state command to set it?

**Comment by Weingummi** [comment]
That works perfect! I just tell Ha_bridge to not update the device and preset the brightness to 127. Then, all I have to do is forward the intensity. Accordingly, the relative change is simply (intensity.byte - 127). Thanks for this great solution!
