### ISSUE TITLE
Extended color light support

### ISSUE THREAD

**Issue by sognen** [bwssytems/ha-bridge#404]
Hi,
With the latest 4.0.3 I am able to pair Hue with Google Home. Very much appreciated.

I can now turn lights of and on individually or as a group. However, I am unable to change the color. When looking at /api/discovery.xml all bulbs are  reported as being of type "Dimmable light" when they really are of type "Extended color light". I suspect that GH refuse to pass on the color because it has been told that is a dimmable white bulb.

I am not sure if this is an enhancement request or a bug. In any case, it would be fantastic if we could get it working.  Please let me know if I can be of any assistance. Under you can find a snippet from my discovery.xml showing a bulb as dimmable, and another example I found somewhere on internet showing an Extended Color Light bulb.
 
Snippet of my /api/discovery.xml
{
	"3": {
		"state": {
			"on": false,
			"bri": 0,
			"hue": 0,
			"sat": 0,
			"effect": "none",
			"ct": 0,
			"alert": "none",
			"reachable": true
		},
		**"type": "Dimmable light",**
		"name": "Fado",
		"modelid": "LWB004",
		"manufacturername": "Philips",
		"uniqueid": "00:17:88:5E:D3:03-03",
		"swversion": "66012040"
	}

Example: Extended Color Light (i found on some website)
{
	"20": {
		"state": {
			"on": false,
			"bri": 25,
			"hue": 14988,
			"sat": 141,
			"effect": "none",
			"xy": [0.4575, 0.4101],
			"ct": 365,
			"alert": "none",
			"colormode": "xy",
			"reachable": true
		},
		**"type": "Extended color light",**
		"name": "Living Room A",
		"modelid": "LCT001",
		"manufacturername": "Philips",
		"uniqueid": "00:17:88:01:00:b6:b0:25-0b",
		"swversion": "5.23.1.13452"
	}

**Comment by sognen** [comment]
Hi,
Correct. I'm using openHab and would like to use Google Home to control ha-bridge devices which would include the real hue hub and other devices configured in openHab.
Now, I know that I could connect the hue hub with the GH, but since it only allows one hue hub I would miss out on other devices, such as TVs and other devices that could be turned OFF or ON. 

Is this doable?

**Comment by sognen** [comment]
Hi, 
I just did a quick test and updated DeviceResponse.java with setType to "Extended color light" and setSwversion to "65003148" (I'm not sure if the last one really matters though), and I can now change the color both as group and individually.  I guess ideally we would like the ha-bridge to passthrough whatever bulb information it gets from the hue hub.

Cato

**Comment by bwssytems** [comment]
I am looking at how to do this with the new multi construct call. as the ha-bridge can only return one state per device, even though it may be acting on multiple devices on the other end. I'll put in a return if there is only one item in the device and it is a Hue bulb on the other end.

**Comment by sognen** [comment]
Hi,
Thank you, and kudos for putting this excellent piece of software together.

Cato

**Comment by bwssytems** [comment]
I updated this in V4.1.1. Tale a look to see if that helps.

**Comment by sognen** [comment]
Thank you. It works perfectly.  I am now able to change color individually and as group.
