### ISSUE TITLE
Fibaro RGBW controller support?

### ISSUE THREAD

**Issue by booles04** [bwssytems/ha-bridge#405]
I have the Fibaro RGBW controller connected to about 40 feet of RGBW leds. I have it working with my vera 3 flawlessly. I also have a hue hub controlling various leds around my house. I have google home, and ha-bridge running on an rpi. Voice control through home controls the hue colors perfectly. What I would like to do is have the Fibaro RGBW sync with the state of the hue bulbs. I just need pointed in the right direction here. 

Is there a way for ha-bridge to GET the state of the hue bulbs and POST to the Fibaro? Or would I need to run a java service on my pi that parses the JSON data from GET commands to the hue hub, and converts them into hex (or whatever the Fibaro RGBW controller uses, haven't made it that far yet)? 

Is there any plan to have ha-bridge support color changing bulbs in the future? Is there a simpler solution I'm not thinking of?

**Comment by bwssytems** [comment]
Sorry I haven't gotten to this, but yes this can work. Just get the state of your hue bulb through the ha-bridge GET /api/user/lights/<id> and the state is returned and then send the converted url to your Fibaro controller

**Comment by bwssytems** [comment]
Raw color support is already a requested feature

**Comment by bwssytems** [comment]
referencing #327
