### ISSUE TITLE
Dimming with Home Assistant

### ISSUE THREAD

**Issue by cogneato** [bwssytems/ha-bridge#406]
I am having a hard time getting lights to dim from devices pulled in from the Home Assistant Helper and it feels a lot like https://github.com/bwssytems/ha-bridge/issues/194 but that was closed months ago so I assume I am doing something wrong.

I select "percentage" before adding the home assistant light and then add it. Testing for on and off works fine but dimming only appears to succeed. The light does nothing. Am I missing details to add?

**Comment by bwssytems** [comment]
Well, this would be new to the Helper and not the original issue. Please post the item text from the device config.

**Comment by cogneato** [comment]
**Dim Items**
Type: HomeAssistant Device
Target Items:{"entityId":"light.kitchen_table","hassName":"HomeAssistant","state":"on","bri":"${intensity.percent}"}

Everything else in Dim Items is blank.

And from Home Assistant log after attempting a dim test I get:
17-01-27 19:35:26 homeassistant.core: Invalid service data for light.turn_on: extra keys not allowed @ data['attributes']. Got {'brightness': 6}
extra keys not allowed @ data['state']. Got 'on'

**Comment by bwssytems** [comment]
Remove the state:on and see what that does

**Comment by cogneato** [comment]
No change.

**Comment by noodlemctwoodle** [comment]
Getting the same issue on Home Assistant when dimming any bulb using 4.1.0. 

17-01-28 15:15:01 homeassistant.core: Invalid service data for light.turn_on: extra keys not allowed @ data['attributes']. Got {'brightness': 16}

**Comment by bwssytems** [comment]
Confirmed. working on this

**Comment by SMOCULETZ** [comment]
This works for me (Fibaro Dimmer 2) and Home Assistant:
DIM
{"entityId":"light.fibaro_system_fgd212_dimmer_2_level_3_0","hassName":"homeassistant","state":"on","bri":"${intensity.byte}"}
