### ISSUE TITLE
Echo warning of "device may be turned off" after completing action successfully

### ISSUE THREAD

**Issue by chrisfraser05** [bwssytems/ha-bridge#407]
I just wanted to say thanks for this awesome piece of software first of all.

Since upgrading to 4.0.2 and trying out the multiple activities option Alexa tells me the activity failed and may not be plugged in.
This is after it completed.

The activities are a harmony scene, followed by two Vera devices turning off with delays.

The log shows the harmony scene command as info but nothing else.

It all works fine. But after the last light goes up Alexa warns me incorrectly every time.

This is only happening with multiple command not single devices.

Cheers

**Comment by bwssytems** [comment]
i believe this our favorite alexa issue where  the command takes too long.

**Comment by bwssytems** [comment]
Did I answer your question?
