### ISSUE TITLE
Can a Wink hub control ha-bridge?

### ISSUE THREAD

**Issue by lairdknox** [bwssytems/ha-bridge#408]
Ha-bridge is working wonderfully with Alexa.

My understanding is that ha-bridge looks like a Hue hub to Alexa. If that is the case can a Wink hub also control ha-bridge?

Everything works well when initiated from Alexa but I would also like to initiate actions from Wink. I'm looking to control Milight lamps from a button press in addition to using Alexa.

Thanks,

Jeff

**Comment by bwssytems** [comment]
if the wink hub can find a hue hub it should work

**Comment by lairdknox** [comment]
So the Wink hub would connect to the Hue hub which would connect to the ha-bridge using the Hue proxy?

I had ha-bridge and hue hub setup in a proxy once while trying to first get everything working. Since the Alexa -> Milight integration is working I hadn't revisited that.

**Comment by bwssytems** [comment]
https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=wink+hub+and+philips+hue

**Comment by bwssytems** [comment]
Is this resolved?

**Comment by lairdknox** [comment]
Unfortunately no. I know how to link the Wink to the Hue hub so a Google search of how to do that wasn't useful. My question was should ha-bridge behave the same and directly link to Wink or does it have to proxy with/through the Hue hub? 

I have tried various combinations and haven't been able to get it to work. The Hue app connects to ha-bridge so I'm guessing that Wink should also connect directly.

On a side note it would be nice if there were a button on the Hue tab that simulates the link button press on the hub. Clicking in and out of the tab to fire the action is not intuitive.

**Comment by bwssytems** [comment]
There ha-bridge acts as the link button is always pressed, there is no need to do anything else. It may take 2 tries in a row with the wink so that the ha-bridge syncs with the wink.

**Comment by lairdknox** [comment]
So what happens when you first open the Hue tab? I see some traffic in the command window. Or is that just coincidence?

Should I disconnect the real Hue hub when trying to establish the connection to ha-bridge? I've tried it both ways.

**Comment by bwssytems** [comment]
Yes, you should disconnect the real philips hue hub when you do this.

**Comment by KeithLaepple** [comment]
Lairdknowx, did you ever find a way to connect Wink to HA-Bridge? I've been attempting it myself and having trouble. Philips' Hue app on the same Android phone does see HA-Bridge, but the Wink app appears to be attempting to connect indirectly via meethue.com.
