### ISSUE TITLE
Retry Register to Hue for Philips Hue bridge returned error: [{"error":{"type":1,"address":"/","description":"unauthorized user"}}]

### ISSUE THREAD

**Issue by micropet** [bwssytems/ha-bridge#410]
Hello,

With the HA Bridge (v4.0.3) I suddenly get the following error:

01-27-2017 17:11:04.042	WARN	Retry Register to Hue for Philips Hue bridge returned error: [{"error":{"type":1,"address":"/","description":"unauthorized user"}}]	
01-27-2017 17:11:04.043	WARN	Max Retry reached to get Hue data from Philips Hue bridge	
01-27-2017 17:11:04.044	WARN	Cannot get lights for Hue with name: Philips Hue bridge

With the older versions, there was never a problem with the HUE lamps.

Greetings Peter

**Comment by bwssytems** [comment]
When you started the new version, did you push the link button on your bridge?

**Comment by micropet** [comment]
Hello,

 

yes, i do it a few times.

 

Peter

 

 

Von: BWS Systems [mailto:notifications@github.com] 
Gesendet: Freitag, 27. Januar 2017 17:22
An: bwssytems/ha-bridge <ha-bridge@noreply.github.com>
Cc: micropet <w33@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [bwssytems/ha-bridge] Retry Register to Hue for Philips Hue bridge returned error: [{"error":{"type":1,"address":"/","description":"unauthorized user"}}] (#410)

 

When you started the new version, did you push the link button on your bridge?

**Comment by bwssytems** [comment]
Hmmm, will look into that. The new version will now save the login to your real hue bridge from start to start so as only to do this once.

**Comment by micropet** [comment]
I have also  Firmware version: 01036659.

**Comment by bwssytems** [comment]
turn on debug for com.bwssystems.HABridge.plugins.hue and post output of this test

**Comment by micropet** [comment]
With com.bwssystems.HABridge.plugins.hue debug on I see no more.

01-27-2017 22:28:20.520	INFO	HA Bridge (v4.0.3) starting....	com.bwssystems.HABridge.HABridge
01-27-2017 22:28:20.534	INFO	reading from config file: /opt/ha-bridge/habridge.config	com.bwssystems.HABridge.BridgeSettings
01-27-2017 22:28:20.625	INFO	HA Bridge initializing....	com.bwssystems.HABridge.HABridge
01-27-2017 22:28:20.647	INFO	System control service started....	com.bwssystems.HABridge.SystemControl
01-27-2017 22:28:20.747	INFO	Initializing UDP response Socket...	com.bwssystems.HABridge.util.UDPDatagramSender
01-27-2017 22:28:20.763	INFO	UDP response Seocket initialized to: 50000	com.bwssystems.HABridge.util.UDPDatagramSender
01-27-2017 22:28:20.765	INFO	Harmony Home created.	com.bwssystems.HABridge.plugins.harmony.HarmonyHome
01-27-2017 22:28:20.894	INFO	== Spark has ignited ...	spark.webserver.JettySparkServer
01-27-2017 22:28:20.907	INFO	>> Listening on 0.0.0.0:8802	spark.webserver.JettySparkServer
01-27-2017 22:28:21.077	INFO	setup initiated ....	com.bwssystems.HABridge.plugins.harmony.HarmonyServer
01-27-2017 22:28:23.395	INFO	activity changed: [-1] PowerOff	com.bwssystems.HABridge.plugins.harmony.HarmonyServer
01-27-2017 22:28:23.403	INFO	Nest Home created. No Nest configured.	com.bwssystems.HABridge.plugins.NestBridge.NestHome
01-27-2017 22:28:23.404	INFO	Hue passthru Home created.	com.bwssystems.HABridge.plugins.hue.HueHome
01-27-2017 22:28:23.907	INFO	HAL Home created. No HAL devices configured.	com.bwssystems.HABridge.plugins.hal.HalHome
01-27-2017 22:28:23.908	INFO	MQTT Home created.	com.bwssystems.HABridge.plugins.mqtt.MQTTHome
01-27-2017 22:28:23.909	INFO	Setting up handler for name: habridge	com.bwssystems.HABridge.plugins.mqtt.MQTTHandler
01-27-2017 22:28:23.938	INFO	HomeAssistant Home created. No HomeAssistants configured.	com.bwssystems.HABridge.plugins.hass.HassHome
01-27-2017 22:28:23.939	INFO	Command Home for system program execution created.	com.bwssystems.HABridge.plugins.exec.CommandHome
01-27-2017 22:28:23.946	INFO	Http Home created.	com.bwssystems.HABridge.plugins.http.HTTPHome
01-27-2017 22:28:23.958	INFO	TCP Home created.	com.bwssystems.HABridge.plugins.tcp.TCPHome
01-27-2017 22:28:23.959	INFO	UDP Home created.	com.bwssystems.HABridge.plugins.udp.UDPHome
01-27-2017 22:28:23.960	INFO	Vera Home created. No Veras configured.	com.bwssystems.HABridge.plugins.vera.VeraHome
01-27-2017 22:28:23.978	INFO	HABridge device management service started....	com.bwssystems.HABridge.devicemanagmeent.DeviceResource
01-27-2017 22:28:24.002	INFO	Hue description service started....	com.bwssystems.HABridge.upnp.UpnpSettingsResource
01-27-2017 22:28:24.009	INFO	Hue emulator service started....	com.bwssystems.HABridge.hue.HueMulator
01-27-2017 22:28:24.031	INFO	UPNP Discovery Listener starting....	com.bwssystems.HABridge.upnp.UpnpListener
01-27-2017 22:28:24.033	INFO	UPNP Discovery Listener running and ready....	com.bwssystems.HABridge.upnp.UpnpListener
01-27-2017 22:29:02.820	WARN	registerWithHue needs link button pressed on HUE bridge: Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:29:02.826	WARN	Could not register with hue: Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:29:02.900	WARN	registerWithHue needs link button pressed on HUE bridge: Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:29:02.900	WARN	Retry Register to Hue for Philips Hue bridge returned error: [{"error":{"type":1,"address":"/","description":"unauthorized user"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:29:03.974	WARN	registerWithHue needs link button pressed on HUE bridge: Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:29:03.975	WARN	Retry Register to Hue for Philips Hue bridge returned error: [{"error":{"type":1,"address":"/","description":"unauthorized user"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:29:05.048	WARN	registerWithHue needs link button pressed on HUE bridge: Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:29:05.049	WARN	Retry Register to Hue for Philips Hue bridge returned error: [{"error":{"type":1,"address":"/","description":"unauthorized user"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:29:06.126	WARN	registerWithHue needs link button pressed on HUE bridge: Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:29:06.127	WARN	Retry Register to Hue for Philips Hue bridge returned error: [{"error":{"type":1,"address":"/","description":"unauthorized user"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:29:06.133	WARN	Max Retry reached to get Hue data from Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:29:06.134	WARN	Cannot get lights for Hue with name: Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueHome

**Comment by micropet** [comment]
with V4.1.0 i get:

01-27-2017 22:47:24.786	INFO	HA Bridge (v4.1.0) starting....	com.bwssystems.HABridge.HABridge
01-27-2017 22:47:24.799	INFO	reading from config file: /opt/ha-bridge/habridge.config	com.bwssystems.HABridge.BridgeSettings
01-27-2017 22:47:24.890	INFO	HA Bridge initializing....	com.bwssystems.HABridge.HABridge
01-27-2017 22:47:24.914	INFO	System control service started....	com.bwssystems.HABridge.SystemControl
01-27-2017 22:47:25.016	INFO	Initializing UDP response Socket...	com.bwssystems.HABridge.util.UDPDatagramSender
01-27-2017 22:47:25.026	INFO	UDP response Seocket initialized to: 50000	com.bwssystems.HABridge.util.UDPDatagramSender
01-27-2017 22:47:25.032	INFO	Harmony Home created.	com.bwssystems.HABridge.plugins.harmony.HarmonyHome
01-27-2017 22:47:25.166	INFO	== Spark has ignited ...	spark.webserver.JettySparkServer
01-27-2017 22:47:25.167	INFO	>> Listening on 0.0.0.0:8802	spark.webserver.JettySparkServer
01-27-2017 22:47:25.338	INFO	setup initiated ....	com.bwssystems.HABridge.plugins.harmony.HarmonyServer
01-27-2017 22:47:27.683	INFO	activity changed: [-1] PowerOff	com.bwssystems.HABridge.plugins.harmony.HarmonyServer
01-27-2017 22:47:27.690	INFO	Nest Home created. No Nest configured.	com.bwssystems.HABridge.plugins.NestBridge.NestHome
01-27-2017 22:47:27.692	INFO	Hue passthru Home created.	com.bwssystems.HABridge.plugins.hue.HueHome
01-27-2017 22:47:28.176	INFO	HAL Home created. No HAL devices configured.	com.bwssystems.HABridge.plugins.hal.HalHome
01-27-2017 22:47:28.178	INFO	MQTT Home created.	com.bwssystems.HABridge.plugins.mqtt.MQTTHome
01-27-2017 22:47:28.182	INFO	Setting up handler for name: habridge	com.bwssystems.HABridge.plugins.mqtt.MQTTHandler
01-27-2017 22:47:28.231	INFO	HomeAssistant Home created. No HomeAssistants configured.	com.bwssystems.HABridge.plugins.hass.HassHome
01-27-2017 22:47:28.232	INFO	Command Home for system program execution created.	com.bwssystems.HABridge.plugins.exec.CommandHome
01-27-2017 22:47:28.241	INFO	Http Home created.	com.bwssystems.HABridge.plugins.http.HTTPHome
01-27-2017 22:47:28.242	INFO	TCP Home created.	com.bwssystems.HABridge.plugins.tcp.TCPHome
01-27-2017 22:47:28.242	INFO	UDP Home created.	com.bwssystems.HABridge.plugins.udp.UDPHome
01-27-2017 22:47:28.243	INFO	Vera Home created. No Veras configured.	com.bwssystems.HABridge.plugins.vera.VeraHome
01-27-2017 22:47:28.244	INFO	Domoticz Home created. No Domoticz devices configured.	com.bwssystems.HABridge.plugins.domoticz.DomoticzHome
01-27-2017 22:47:28.270	INFO	HABridge device management service started....	com.bwssystems.HABridge.devicemanagmeent.DeviceResource
01-27-2017 22:47:28.294	INFO	Hue description service started....	com.bwssystems.HABridge.upnp.UpnpSettingsResource
01-27-2017 22:47:28.303	INFO	Hue emulator service started....	com.bwssystems.HABridge.hue.HueMulator
01-27-2017 22:47:28.332	INFO	UPNP Discovery Listener starting....	com.bwssystems.HABridge.upnp.UpnpListener
01-27-2017 22:47:28.333	INFO	UPNP Discovery Listener running and ready....	com.bwssystems.HABridge.upnp.UpnpListener
01-27-2017 22:47:59.440	WARN	registerWithHue needs link button pressed on HUE bridge: Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:47:59.442	WARN	Could not register with hue: Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:47:59.515	WARN	registerWithHue needs link button pressed on HUE bridge: Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:47:59.522	WARN	Retry Register to Hue for Philips Hue bridge returned error: [{"error":{"type":1,"address":"/","description":"unauthorized user"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:48:00.596	WARN	registerWithHue needs link button pressed on HUE bridge: Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:48:00.599	WARN	Retry Register to Hue for Philips Hue bridge returned error: [{"error":{"type":1,"address":"/","description":"unauthorized user"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:48:01.671	WARN	registerWithHue needs link button pressed on HUE bridge: Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:48:01.672	WARN	Retry Register to Hue for Philips Hue bridge returned error: [{"error":{"type":1,"address":"/","description":"unauthorized user"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:48:03.010	WARN	registerWithHue needs link button pressed on HUE bridge: Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:48:03.011	WARN	Retry Register to Hue for Philips Hue bridge returned error: [{"error":{"type":1,"address":"/","description":"unauthorized user"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:48:03.012	WARN	Max Retry reached to get Hue data from Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:48:03.012	WARN	Cannot get lights for Hue with name: Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueHome
01-27-2017 22:53:09.306	DEBUG	consolidating devices for hues	com.bwssystems.HABridge.plugins.hue.HueHome
01-27-2017 22:53:09.307	DEBUG	Get hue info to hue Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:09.327	DEBUG	registerWithHue - POST execute on Philips Hue bridgeURL responded: 200	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:09.328	DEBUG	registerWithHue response data: [{"error":{"type":101,"address":"","description":"link button not pressed"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:09.329	WARN	registerWithHue needs link button pressed on HUE bridge: Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:09.330	WARN	Could not register with hue: Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:09.431	DEBUG	GET HueApiResponse - data: [{"error":{"type":1,"address":"/","description":"unauthorized user"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:09.449	DEBUG	registerWithHue - POST execute on Philips Hue bridgeURL responded: 200	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:09.450	DEBUG	registerWithHue response data: [{"error":{"type":101,"address":"","description":"link button not pressed"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:09.451	WARN	registerWithHue needs link button pressed on HUE bridge: Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:09.451	WARN	Retry Register to Hue for Philips Hue bridge returned error: [{"error":{"type":1,"address":"/","description":"unauthorized user"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:10.504	DEBUG	GET HueApiResponse - data: [{"error":{"type":1,"address":"/","description":"unauthorized user"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:10.523	DEBUG	registerWithHue - POST execute on Philips Hue bridgeURL responded: 200	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:10.524	DEBUG	registerWithHue response data: [{"error":{"type":101,"address":"","description":"link button not pressed"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:10.525	WARN	registerWithHue needs link button pressed on HUE bridge: Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:10.529	WARN	Retry Register to Hue for Philips Hue bridge returned error: [{"error":{"type":1,"address":"/","description":"unauthorized user"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:11.587	DEBUG	GET HueApiResponse - data: [{"error":{"type":1,"address":"/","description":"unauthorized user"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:11.606	DEBUG	registerWithHue - POST execute on Philips Hue bridgeURL responded: 200	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:11.608	DEBUG	registerWithHue response data: [{"error":{"type":101,"address":"","description":"link button not pressed"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:11.609	WARN	registerWithHue needs link button pressed on HUE bridge: Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:11.610	WARN	Retry Register to Hue for Philips Hue bridge returned error: [{"error":{"type":1,"address":"/","description":"unauthorized user"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:12.665	DEBUG	GET HueApiResponse - data: [{"error":{"type":1,"address":"/","description":"unauthorized user"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:12.683	DEBUG	registerWithHue - POST execute on Philips Hue bridgeURL responded: 200	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:12.683	DEBUG	registerWithHue response data: [{"error":{"type":101,"address":"","description":"link button not pressed"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:12.684	WARN	registerWithHue needs link button pressed on HUE bridge: Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:12.684	WARN	Retry Register to Hue for Philips Hue bridge returned error: [{"error":{"type":1,"address":"/","description":"unauthorized user"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:12.684	WARN	Max Retry reached to get Hue data from Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:12.684	WARN	Cannot get lights for Hue with name: Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueHome
01-27-2017 22:53:12.689	DEBUG	consolidating devices for hues	com.bwssystems.HABridge.plugins.hue.HueHome
01-27-2017 22:53:12.689	DEBUG	Get hue info to hue Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:12.701	DEBUG	registerWithHue - POST execute on Philips Hue bridgeURL responded: 200	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:12.702	DEBUG	registerWithHue response data: [{"error":{"type":101,"address":"","description":"link button not pressed"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:12.702	WARN	registerWithHue needs link button pressed on HUE bridge: Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:12.703	WARN	Could not register with hue: Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:12.765	DEBUG	GET HueApiResponse - data: [{"error":{"type":1,"address":"/","description":"unauthorized user"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:12.784	DEBUG	registerWithHue - POST execute on Philips Hue bridgeURL responded: 200	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:12.785	DEBUG	registerWithHue response data: [{"error":{"type":101,"address":"","description":"link button not pressed"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:12.785	WARN	registerWithHue needs link button pressed on HUE bridge: Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:12.785	WARN	Retry Register to Hue for Philips Hue bridge returned error: [{"error":{"type":1,"address":"/","description":"unauthorized user"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:13.839	DEBUG	GET HueApiResponse - data: [{"error":{"type":1,"address":"/","description":"unauthorized user"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:13.858	DEBUG	registerWithHue - POST execute on Philips Hue bridgeURL responded: 200	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:13.860	DEBUG	registerWithHue response data: [{"error":{"type":101,"address":"","description":"link button not pressed"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:13.861	WARN	registerWithHue needs link button pressed on HUE bridge: Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:13.861	WARN	Retry Register to Hue for Philips Hue bridge returned error: [{"error":{"type":1,"address":"/","description":"unauthorized user"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:14.915	DEBUG	GET HueApiResponse - data: [{"error":{"type":1,"address":"/","description":"unauthorized user"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:14.933	DEBUG	registerWithHue - POST execute on Philips Hue bridgeURL responded: 200	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:14.934	DEBUG	registerWithHue response data: [{"error":{"type":101,"address":"","description":"link button not pressed"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:14.935	WARN	registerWithHue needs link button pressed on HUE bridge: Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:14.935	WARN	Retry Register to Hue for Philips Hue bridge returned error: [{"error":{"type":1,"address":"/","description":"unauthorized user"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:15.990	DEBUG	GET HueApiResponse - data: [{"error":{"type":1,"address":"/","description":"unauthorized user"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:16.010	DEBUG	registerWithHue - POST execute on Philips Hue bridgeURL responded: 200	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:16.012	DEBUG	registerWithHue response data: [{"error":{"type":101,"address":"","description":"link button not pressed"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:16.012	WARN	registerWithHue needs link button pressed on HUE bridge: Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:16.012	WARN	Retry Register to Hue for Philips Hue bridge returned error: [{"error":{"type":1,"address":"/","description":"unauthorized user"}}]	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:16.012	WARN	Max Retry reached to get Hue data from Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueInfo
01-27-2017 22:53:16.012	WARN	Cannot get lights for Hue with name: Philips Hue bridge	com.bwssystems.HABridge.plugins.hue.HueHome

**Comment by bwssytems** [comment]
I didn't change anything in 4.1.0 for this, the way the log file shows, is that it gets the return that the hue link button is not pressed on you hue hub. But then it gets an authorization error when trying to get a user name, very strange. 

Have you tried this scenario:
1) start up your ha-bridge, DO NOT go to the hue devices tab
2) press the link button on your Philips Hue Hub
3) go to your ha-bridge web page and click the Hue Devices Tab

Let me know if that errors too

**Comment by micropet** [comment]
It works.

I do not understand that. 
I had already started several times the ha_bridge and also pressed the HUE Connect button.

Maybe I pressed the button too late or too early.

**Comment by bwssytems** [comment]
They may have changed the timeout, it was 30 seconds from the time you pushed the button.

Closing as resolved.

**Comment by micropet** [comment]
OK. Good that it works again.
Many Thanks!
