### ISSUE TITLE
Need to know the latest Hue Bridge sw version

### ISSUE THREAD

**Issue by bwssytems** [bwssytems/ha-bridge#411]
If you have a real hue hub, I need to know the latest sw version if possible?

Thanks :)

**Comment by volcan96** [comment]
I checked https://www.meethue.com/en-us/user/bridge for my bridge and this is the version there:
Firmware version: 01036659

**Comment by audiofreak9** [comment]
@bwssytems I always refer to: http://www2.meethue.com/en-us/release-notes/bridge/

Should I add this URL to FAQs?

**Comment by bwssytems** [comment]
That would be great! I was testing the hue gen 2 app and ran into the version issue and didn't have the latest

**Comment by audiofreak9** [comment]
Go figure...I added that previously.

https://github.com/bwssytems/ha-bridge/wiki/HA-Bridge-FAQs#HUEReleaseVersion

**Comment by bwssytems** [comment]
And I didn't go read the FAQ first....lol I'm a noob
