### ISSUE TITLE
execute program/script adds/edits broken

### ISSUE THREAD

**Issue by tuicemen** [bwssytems/ha-bridge#412]
With the new build I find I can no longer manual add or edit a program script.
The new layout has me a bit confused if I click on a device to edit which was a program/script the old on/off/dim urls don't display anywhere to allow editing them.

**Comment by audiofreak9** [comment]
In On, Dim & Off Item rows find the "Target Item" column, your program scripts should be in those inputs (which are expandable by dragging the bottom right of the input).

**Comment by tuicemen** [comment]
Ok that lets me view the device settings but I can't add a similar device entering similar info. The info never gets saved. if i test i get an error.
if I click edit then on /off/dim entries are blank

**Comment by tuicemen** [comment]
I just tried entering a new device as a program/script I get no error creating it, but opening the data.db file I see the on/off/dim commands aren't saved.
this is what is saved `{"id":"15","uniqueid":"00:17:88:5E:D3:0F-0F","name":"tester","deviceType":"exec","targetDevice":"Encapsulated"}`
If it try to edit I get the same results.

**Comment by bwssytems** [comment]
When you are in the editor, you have to hit the add icon to the right of the on/dim/off item to make it stick add I is a list of items for each of these functions now.

**Comment by tuicemen** [comment]
Ok thanks that did it!  the read me needs to be updated with this new info
Great work!
