### ISSUE TITLE
Xiaomi Yeelight support - TCP requests to use \n \r

### ISSUE THREAD

**Issue by mihaifireball** [bwssytems/ha-bridge#415]
I have a Yeelight bulb, which was working fine with ha-bridge v3.5.1, but with the latest versions (4.1.0) I cant make it work.
For example, in the v3.5.1, power on command was:

`tcp://10.100.1.60:55443/{\"id\":1,\"method\":\"set_power\",\"params\":[\"on\"]}\r\n`

Which will be the syntax for  ha-bridge v4.1.0?

Thank you!

**Comment by bwssytems** [comment]
Yep, #296, asked for this as well

**Comment by mihaifireball** [comment]
So, as I understand, it is not working anymore in the latest version?

**Comment by bwssytems** [comment]
Is there an error message that occurs in the log?

**Comment by mihaifireball** [comment]
No, there is no error in the log, and the webpage confirms that the command was successfully executed (green popup).

**Comment by bwssytems** [comment]
That entry is pretty bad. Did you cut and paste from somewhere?

**Comment by mihaifireball** [comment]
Yes, from a notepad file, but I did the same thing with the previous version of ha-bridge and there was no problem.

**Comment by bwssytems** [comment]
Well let's create a new device by typing it in manually. It seems there are too many escapes

**Comment by bwssytems** [comment]
To create your device, type the tcp://10.100.1.60:55443/{"id":1,"method":"set_power","params":["off"]} and see if that has less escape '\' characters in it

**Comment by mihaifireball** [comment]
I made it work finally, but only by editing the device.db file. Here it is what i found:
the working entry in the  device.db file is:
`"offUrl":"[{\"item\":\"tcp://10.100.1.60:55443/{\\\"id\\\":1,\\\"method\\\":\\\"set_power\\\",\\\"params\\\":[\\\"off\\\"]}\\r\\n\",\"type\":\"tcpDevice\"}]"

So, if i use the web interface i had to add this entry: 
`tcp://10.100.1.60:55443/{"id":1,"method":"set_power","params":["off"]}\r\n`
but the problem is that **\r\n** is translated in  **\\\\r\\\\n\**, instead of **\\r\\n\** in the device.db file.

**Comment by bwssytems** [comment]
@mihaifireball I don't think you need the \r\n at all in the call since this is pure tcp

**Comment by mihaifireball** [comment]
If i remove it, it doesn't give me any error, but the light bulb is not reacting.

**Comment by mihaifireball** [comment]
This issue is not fixed, right? because i still have to delete manually 2 backslashes before \r and two before \n on 4.1.4 release.

**Comment by bwssytems** [comment]
No updates to this yet

**Comment by hphde** [comment]
I created some [shell-scripts](https://github.com/hphde/yeelight-shell-scripts) to play with the Yeelight and use them as wrappers inside HA-Bridge

**Comment by bwssytems** [comment]
@mihaifireball The next version of ha-bridge will support \r \n and others
