### ISSUE TITLE
4.1 no dimming for new Vera devices

### ISSUE THREAD

**Issue by devenbj** [bwssytems/ha-bridge#417]
Since upgrading to 4.1, I can no longer dim new devices. Existing devices still dim correctly, though the edit screen does not show the configuration.

**Comment by bwssytems** [comment]
Will look into that.

**Comment by jbardi** [comment]
I know bwssystems is looking into it, but as far as not being able to see the configuration for the dimming on your existing devices, you need to scroll down to the bottom of the editor and click on "Legacy Fields"

These are fields from ha-bridge before he updated the editor, so all of your old data should be in there.

**Comment by devenbj** [comment]
That's what I thought, but they were empty as well.

**Comment by bwssytems** [comment]
So, I have to ask, when you created the new vera device, did you select the dimming type? Otherwise, I would like you to post your item call for dim from the editor.
Thanks

**Comment by devenbj** [comment]
Good catch. It worked if I select the dim option prior to adding the device. I could not see a way to enable dimming if I had not selected the dimming setting prior to adding the device.

It would be nice if there was a way to configure in the edit screen.

**Comment by papa-legba** [comment]
I'm having this issue adding devices through the home assistant devices helper tab on 4.1.0. On and off work fine from the HA bridge panel but dim seems to have no effect. I have tried building the items using the dim control setting to pass-thru, percentage, none and custom math and none seem to carry over to home assistant.

From the home assistant web UI the items dim. I also have hue bulbs connected through the hue devices helper tab and HA bridge passes the dim percentage to them correctly.

**Comment by bwssytems** [comment]
@devenbj The edit screen is all manual at that point as it is not connected to the helpers at that point. It is used to tweak the calls by hand. So, of you read the README it tells you about how to use different types of value replacement in the item call manually. This tool is very low level based.

@papa-legba Could you open up a new issue with this request as this one is about Vera. Thanks

**Comment by bwssytems** [comment]
@papa-legba Nevermind on that request, it is already logged as #406
