### ISSUE TITLE
documentation issue

### ISSUE THREAD

**Issue by timmarti** [bwssytems/ha-bridge#42]
There is a typo in the section documenting the usage of the -Dupnp.device.db parameter: there is an extra "s" which references "-Dupnp.device**s**.db" instead of "-Dupnp.device.db"

Current:
If you would like a different filename or directory, specify -Dupnp.devices.db=<directory>/<filename> or <filename> if it is the same directory

Change To:
If you would like a different filename or directory, specify -Dupnp.device.db=<directory>/<filename> or <filename> if it is the same directory

**Comment by audiofreak9** [comment]
Wow, great catch, kudos!

**Comment by bwssytems** [comment]
Just saw that the other day...thanks for the update!
