### ISSUE TITLE
Dimming a Sonos speaker volume

### ISSUE THREAD

**Issue by thienedits** [bwssytems/ha-bridge#421]
I am using https://github.com/jishi/node-sonos-http-api which has an api to change the volume of a sonos speaker. 

Set Volume:
http://localhost:5005/livingroom/volume/15 (will set volume for room Living Room to 15%)

However, using http://localhost:5005/livingroom/volume/${intensity.percent} always sets the volume all the way down. Guess I am not understanding how ${intensity.percent} works. Isn't this a number between 0-100?

**Comment by bwssytems** [comment]
It is a number between 1 and 100. Turn on debug for the httpHandler

**Comment by thienedits** [comment]
Here's the log:

01-29-2017 23:09:01.713 DEBUG Making outbound call in doHttpRequest: GET http://10.0.95.21:5005/LivingRoom%20Sonos/volume/$%7Bintensity.percent%7D HTTP/1.1 com.bwssystems.HABridge.plugins.http.HTTPHandler 

01-29-2017 23:09:01.766 DEBUG GET execute on URL responded: 200 com.bwssystems.HABridge.plugins.http.HTTPHandler

**Comment by thienedits** [comment]
Ah i just figured it out its the URL percent encoding that was screwing it up it needs to be ${intensity.percent} and not $%7Bintensity.percent%7D
