### ISSUE TITLE
Naming & Notes Enhancement Suggestions

### ISSUE THREAD

**Issue by smarty125** [bwssytems/ha-bridge#423]
I am a happy user since version 2.0.4.  The bridge has become an integral part of my total home automation “package”.  A big THANK YOU!
I have two suggestions for possible enhancements…
1)	Please consider having an optional “comments” field that is visible when doing an “edit/copy” (it doesn’t need to visible on the “Bridge Devices” page.  This field would have no action or significance other than a place to keep your device programming notes.  With a number of my devices, I need a place to keep notes as to why I programmed something the way I did.  This is especially needed when multiple commands or delays are issued for one device call.

2)	On the front “Bridge Devices” page, consider having another “Name” type field for each device.  This second name type field would be used to properly group common things.  For example, I have 4 devices set up to control my 2 overhead garage doors. 
The devices are “small garage door”/”west garage door” …..and….. “large garage door”/”east garage door” <=these are the spoken device invocations.  I need all of them because the wife can’t remember my naming invocation strategy.  …in the suggested secondary naming field, I would put in names like “garage_door_1/2/3/4” so that they would sort next to each other.  This could also be useful for colored LED lights (the invocation names won’t group them together), but a secondary non-invocation name could.

**Comment by bwssytems** [comment]
Not a bad idea. I'll put it in the queue
