### ISSUE TITLE
Alexa no longer responds to voice commands

### ISSUE THREAD

**Issue by micropet** [bwssytems/ha-bridge#424]
Since the V4.1 (or earlier), Alexa does not respond to the voice commands. 
She reports "The appliance with the name living room lamp does not respond".
The lamps can be switched on and off via "Test On / OFF".

Under Bridge Devices - Edit it looks very confusing. I found the old version much clearer. The input fields are also not completely readable.

Under Alexa "devices search"  all my devices are displayed

![ha-bridge_editdevice](https://cloud.githubusercontent.com/assets/2838584/22454824/f8d83244-e788-11e6-8b5e-7bbc9852188f.jpg)

**Comment by tuicemen** [comment]
Try rebooting your Alexa device.( unplug and re-plug in)
Also try reinitializing the bridge
I agree the Add/edit screen is confusing but that happens when a program evolves with extra options

**Comment by bwssytems** [comment]
After you have done what tuicmen has recomended, in the Alexa control page, do a "forget all devices" and then do a discovery again.

**Comment by micropet** [comment]
Rebooting Alexa does not help.  "forget all devices" does the Trick.
Thank you. 

Can you make the input fields completely readable again?

**Comment by bwssytems** [comment]
Great! To read the fields, use your mouse to grab that little corner in the lower right to drag and expand it.... Just not enough room on the on smaller monitors... Suggestion is 24" monitor :)
