### ISSUE TITLE
On and off commands get reversed for harmony activities

### ISSUE THREAD

**Issue by glacket** [bwssytems/ha-bridge#425]
If i say "turn on tv" which then triggers the harmony activity to turn on my receiver and tv, but then turn both of via the remote, next time i want to activate the activity, i have to say "turn off tv" because from ha-bridge point of view, it never received the off command. is there a way to fix that so no matter how i turn off the devices in the activity, i can always turn on the devices by saying "turn on". hopefully that makes sense. basically if i dont turn on and off the activity via voice command, then it gets scrambled.

**Comment by bwssytems** [comment]
I will need to see your configuration for the harmony activities. If you used the builder, this should not happen as they are explicit to the hub and the remote should be working with the hub. I assume your remote and hub are paired.

**Comment by glacket** [comment]
Hi, i have a harmony 900 remote which is not compatible with the hub, so it cannot be paired. I selected the harmony activity and generated a bridge device from it, thats it.

**Comment by bwssytems** [comment]
That is why it does not work for you, the harmony hub has no idea of the state when you use the remote. Cannot help here.

**Comment by glacket** [comment]
So, everyone who is using this successfully has a remote synced to the hub? i didnt know that was a requirement. Im pretty sure there only 1 or 2 remotes that actually sync with it.

**Comment by bwssytems** [comment]
Yep, I bought my hub then bought the compatible remote. It does make life easier as you only have to do the configuration once instead of per device such as you are.

**Comment by glacket** [comment]
i will have to research this further then. I guess it makes sense as i had the same issue with the logitech skill. The biggest turn off for me and the waf is the delay in changing channels or do anything with the remote because its wireless to the hub. If the remote can use ir direct to tv and still wirelessly pair with the hub i would consider switching to it.

**Comment by bwssytems** [comment]
Actually, the delay with the remote is not much at all, it has WAF as mine uses both the Alexa and the remote and she is happy :) Also, closing as this is not an ha-bridge issue
