### ISSUE TITLE
server setting not saving e.g domoticz

### ISSUE THREAD

**Issue by phate1** [bwssytems/ha-bridge#427]
Adding a domoticz or one of the other servers to the setting appears to work it shows the entry above with the red delete button but navigate away from the screen and back again and is gone. checking the config file that's generated nothing appears other than domoticz enabled:false

HA Bridge Ver 4.1.1
Raspberry pi3 - running OSMC
Linux osmc 4.4.27-7-osmc #1 SMP PREEMPT Tue Jan 24 03:38:31 UTC 2017 armv7l GNU/Linux
java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) Client VM (build 25.121-b13, mixed mode)
javac -version
javac 1.8.0_121

**Comment by bwssytems** [comment]
Ok, simple question, did you hit the Save button in the top left of the screen?
