### ISSUE TITLE
harmony hub device power toggle button vs separate on off buttons

### ISSUE THREAD

**Issue by glacket** [bwssytems/ha-bridge#429]
I wasnt able to ask this question before my previous question was closed. If i set my devices to powertoggle(using the same button to turn device on and off), add them to an activity and activate the activity, regardless if i say "turn on" or "turn off" activity, the Harmony hub should act as a dumb device and issue the ir command. is this not correct? based on this theory, i should be able to turn the devices in the activity on or off by saying "turn on" or "turn off" because both commands are using the power toggle button.

**Comment by bwssytems** [comment]
This is where you use the Harmony Devices Tab and select the power buttons you want executed. In essence, this will build your own "Activity" with buttons.

**Comment by glacket** [comment]
I understand the build buttons part, but that is for a single device, correct? I setup my receiver and tv power on and off buttons as "power toggle" under harmony devices tab. to turn them on and off, the would have to be different. If i just create individual devices, i cant say "turn on tv" and have both my receiver and tv power on. i thought this could only be done through devices or a device group on alexa.

**Comment by bwssytems** [comment]
Thats the power of the interface for building buttons, you can string them along.

1) Select on button and off button for a device
2) Select Build
3) select the Harmony Devices tab again
4) select on button and off button for another device
5) select build
6) Repeat as needed
7) When you have all of your devices  that you want commands for
8) Change the name to what you want Alexa to act against
9) Add Bridge Device

**Comment by glacket** [comment]
if i could build a device where i could add multiple device buttons for a single on or off url then i could see how that would work. but i tried that and i couldnt get it to work.

**Comment by glacket** [comment]
i got it now. I originally tried stringing them together manually without the right syntaxwhich most likely cause it not to work. I will try this tonight. Thanks!

**Comment by leyton01** [comment]
I did this with mute on my cable TV box and media PC. I stringed together the mutes for both and set them to be on and off activities. This way can say "mute on" or "mute off" and it achieves muting of whatever I am watching. Muting is similar to power toggle and it doesn't matter what state it is in (ie you can turn "on" or "off" as many times in a row you like)

**Comment by bwssytems** [comment]
Great!

**Comment by glacket** [comment]
I didnt have time to test this yesterday, however i am still curious as to why an activity using power toggle would not work in the same manor? for it not to work, it would have to be tracking on and off commands which to me, doesnt add any benefit.

**Comment by glacket** [comment]
that worked a treat! thanks for the help!

**Comment by Matt8119** [comment]
I'm curious as to what your udp string looks like,  to make that dual purpose command work.
