### ISSUE TITLE
Percent slider for testing ${intensity.percent} from Configuration page

### ISSUE THREAD

**Issue by audiofreak9** [bwssytems/ha-bridge#43]
Requesting the addition of a percentage slider for testing the ${intensity.percent} portion of the On URL from the Configuration page of the ha-bridge.  It can work in conjunction with the 'Test ON' button, and have a 100% default.

**Comment by bwssytems** [comment]
Cool idea, especially now that more items have those included,

**Comment by audiofreak9** [comment]
The Harmony activities and buttons would obviously not need the slider.  Not a Vera user myself, but I'm sure there are scenes and activities for the Vera that would not require the slider as well.

I'm also leaning towards requesting an "Operation" page as a PC/tablet/phone web interface, this would give the bridge a second role, behind just configuration and connection.  An all-in-one control interface.

**Comment by bwssytems** [comment]
I'm not sure I want to get into building a control page yet for this as then I get the bridge into the HA GUI arena. I'll put in the test selector for intensity though.
