### ISSUE TITLE
hex value needed for dimming

### ISSUE THREAD

**Issue by Neuroplant** [bwssytems/ha-bridge#430]
Hello,

I need values 0,08,18..f8 for dimming (jb media light manager pro)
the whole line would be for 100% (mention the "db2=.."-part)
`http://[local-ip]:81/control?cmd=dim&dl=8&id=1&db0=5&db1=0&db2=f8&db3=6&db4=1&db5=0&db6=0&db7=0`
tried with
`http://[local-ip]:81/control?cmd=dim&dl=8&id=1&db0=5&db1=0&db2=0x${intensity.math(X/16)}8&db3=6&db4=1&db5=0&db6=0&db7=0`
as to your answer in (https://github.com/bwssytems/ha-bridge/issues/124#issuecomment-227345385#)
Unfortunately the result is
`http://[local-ip]:81/control?cmd=dim&dl=8&id=1&db0=5&db1=0&db2=0x168&db3=6&db4=1&db5=0&db6=0&db7=0
`
what am I doing wrong?

Thanks
Neuroplant

**Comment by bwssytems** [comment]
That hex conversion is not implemented into the http call at this time. It is only in tcp and udp calls.

**Comment by Neuroplant** [comment]
Hello,
thanks for the Information, I thought I was going crasy not finding the Problem.
Is it planned to implement this as well for http?
This would open dimming for JB media Light Manager connected wireless devices.
Neuroplant

**Comment by bwssytems** [comment]
I'll put this on the enhancement list
