### ISSUE TITLE
Google Home and Hue lights don't seem to be in sync

### ISSUE THREAD

**Issue by thienedits** [bwssytems/ha-bridge#431]
Voice commands are working, however, if I go in the Philips Hue app and turn on/off the light, then ask Google Home "is the .... light on", she will respond with the wrong answer. When I paired the official Hue bridge to Google Home it seems to be working correctly.

**Comment by bwssytems** [comment]
My assumption is that the Google Home does not ask for state from the ha-bridge first and only returns what it knows as the last state.

**Comment by thienedits** [comment]
Do you know if the home device is getting the state from the official philips hue bridge. When i pair with that bridge and turn on/off lights in the philips hue android app, the home device seems to know the updated state.

**Comment by bwssytems** [comment]
Yep, if you want it to be consistent, you will have to bridge the real hue hub through the ha-bridge using the hue pass thru capability

**Comment by thienedits** [comment]
Are you referring to entering the hue ip address in ha-bridge's bridge control section? I have done this and the hue devices are set up as passthru devices.

**Comment by bwssytems** [comment]
So, then the Google Home does not query the ha-bridge for state before calling. It looks like a google Home behavior
