### ISSUE TITLE
Where is the data and config stored?

### ISSUE THREAD

**Issue by dapug** [bwssytems/ha-bridge#432]
The readme file says Devices DB is in "**data/devices.db**". And in fact, config is in "**data/habridge.config**".  But, uh, I'm not seeing anything at all in the data folder - totally empty.  How is habridge even running?

**Comment by bwssytems** [comment]
The bridge has default parameters on startup. You have to add one device for the device.db file to be written and you have to save the config in the bridge control tab to write the config file.

**Comment by dapug** [comment]
Ah, yes indeed, saving a bridge config change for the first time creates data/habridge.config.  However, I have over 10 devices, and created a Device DB backup, but dont see any of this in the habridge or habridge/data folder.

**Comment by bwssytems** [comment]
The next question is, how are you starting your system? Those are relative paths to the process owner....

**Comment by dapug** [comment]
here is my habridge.service file, which resides in /home/pi/habridge
```
[Unit]
Description=HA Bridge
Wants=network.target
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/java -jar -Dconfig.file=/home/pi/habridge/data/habridge.config /home/pi/habridge/ha-bridge-4.1.2.jar

[Install]
WantedBy=multi-user.target
```

**Comment by bwssytems** [comment]
Well, that is because the relative data/device.db is in the root folder and your config is in /home/pi/habridge/data dir. That's what relative data paths mean. in your config you should set it to /home/pi/habridge/data/device.db.....

**Comment by dapug** [comment]
ah, I see now. Device db is in /data. I totally glossed over the field for setting the location using the bridge control tab. I was focused on the config setup via script. Thanks!
