### ISSUE TITLE
Fibaro question.

### ISSUE THREAD

**Issue by daneasa** [bwssytems/ha-bridge#433]
Hello I'm at the beginner level . I have Fibaro system and i need some help with the new version 4.1.2 of Habridge.
In Habridge 3.0.0 it was easy to add the device but now i don't understand how this works :D.

Turn On in 3.0.0 - http://admin:admin@192.168.1.130/api/callAction?deviceID=152&name=turnOn
Intensity in 3.0.0 - http://admin:admin@192.168.1.130/api/callAction?deviceID=152&name=setValue&arg1=${intensity.percent}

Can you help me ? 

Sorry for a request like this .

Thank you.

![screen shot 2017-02-03 at 16 39 05](https://cloud.githubusercontent.com/assets/25531432/22595925/18309694-ea32-11e6-8261-acd017c9a3e6.png)

**Comment by bwssytems** [comment]
Type should be "HTTP Device", the "Target Item" should be your http URL call and the body should be blank as that is used for POST and PUT methods

**Comment by daneasa** [comment]
Is working perfectly .
So for Fibaro i will complete just the :Type and the Target Item .

Thank you very much .

**Comment by bwssytems** [comment]
Yep, enjoy.
