### ISSUE TITLE
Dimming Issue using intensity math

### ISSUE THREAD

**Issue by lonebaggie** [bwssytems/ha-bridge#434]
Im using LIghtwaverf dimmers that use UDP calls to dim. Dim levels are 1 to 32  so I am using ${intensity.math(X/8)} to take values down to the right range.

the UDP Command is 100,!R1D1FdP followed by the number 1 to 32

When testing on full dim I get the following, a dim level of 20 what am I doing wrong ?

02-04-2017 10:09:37.033	DEBUG	executing HUE api request to UDP: udp://192.168.1.253:9760/100,!R1D1FdP${intensity.math(X/8)}	com.bwssystems.HABridge.plugins.udp.UDPHome
02-04-2017 10:09:37.034	DEBUG	Math eval is: X/8, Where X is: 255	com.bwssystems.HABridge.hue.BrightnessDecode
02-04-2017 10:09:37.038	DEBUG	Sending response string: <<<100,!R1D1FdP20>>>

**Comment by lonebaggie** [comment]
Just an update I am  using latest version 4.1.2 

If I change the values I get very strange results. A  value of 227 from the test Dim give me a result of 1C  


02-04-2017 10:48:47.192	DEBUG	Decode Json for url items: [{"item":"udp://192.168.1.253:9760/100,!R1D1FdP${intensity.math((X/8))}","type":"udpDevice"}]	com.bwssystems.HABridge.hue.HueMulator
02-04-2017 10:48:47.193	DEBUG	executing HUE api request to UDP: udp://192.168.1.253:9760/100,!R1D1FdP${intensity.math((X/8))}	com.bwssystems.HABridge.plugins.udp.UDPHome
02-04-2017 10:48:47.194	DEBUG	Math eval is: (X/8), Where X is: 227	com.bwssystems.HABridge.hue.BrightnessDecode
02-04-2017 10:48:47.198	DEBUG	Sending response string: <<<100,!R1D1FdP1C>>>

**Comment by bwssytems** [comment]
So, I looked at the code and I change it to hex representation by default, that is a bug.
