### ISSUE TITLE
database issue after update

### ISSUE THREAD

**Issue by charlez79** [bwssytems/ha-bridge#436]
After updating from ha-bridge-3.5.1 to ha-bridge-4.1.2 non of the created devices work.
all fields are empty

error {"type":"6","address":"/lights/3","description":"Error on calling url to change device state","method_name":"/lights/3state"}

**Comment by tuicemen** [comment]
Did you try a bridge reinitialize,refresh and Reboot?

**Comment by bwssytems** [comment]
This just means that it cannot understand what type of device you have. The format changed and in the editor you can expand the fields, such as "target item" which holds your previous call. Set the device type with in that row and update it and it should be fine.

**Comment by charlez79** [comment]
This indeed solved by defining the type of device.

**Comment by bwssytems** [comment]
I don't understand what you cannot alter? You can change any setting as long as you click update bridge device.

**Comment by charlez79** [comment]
This is a screenshot of a device after updating to version 4.1.3.
As you can see, old layout, fields empty and unable to change.

![image](https://cloud.githubusercontent.com/assets/25553678/22649624/114c3c60-ec7c-11e6-8ec4-50cf8c97b941.png)

**Comment by bwssytems** [comment]
Alright, I'll need to see your device.db. You are having a JSON decode issue on your devices.

**Comment by charlez79** [comment]
[device.zip](https://github.com/bwssytems/ha-bridge/files/754901/device.zip)

**Comment by bwssytems** [comment]
so, the new version tries to decode the old URLs into the new item JSON format. Since the "New Line" character is in that string, it becomes an invalid JSON. Until I can figure out how to deal with those characters, you'll need to manually edit your device.db when those characters are present.

**Comment by charlez79** [comment]
removed the \n characters in the db and problem solved.

thx!

**Comment by bwssytems** [comment]
So the \n characters are not needed?

**Comment by charlez79** [comment]
I've changed my setup on the other side so then can be removed.

**Comment by bwssytems** [comment]
Great, closing
