### ISSUE TITLE
 Get http://localhost/api/habridge/version error

### ISSUE THREAD

**Issue by tuicemen** [bwssytems/ha-bridge#437]
With the latest version (4.1.2) I attempted a GET to retrieve the bridge version number in an application which failed.
 I then attempted with Chrome's Postman and get a 404 error,(Problem accessing /api/habridge/version. Reason:    Not Found)
Has this GET option been altered or removed?

**Comment by bwssytems** [comment]
It is not in that location anymore, try http://localhost/system/habridge/version

**Comment by bwssytems** [comment]
Documentation fixed

**Comment by tuicemen** [comment]
No Problem, I figured the get had been changed some how as everything else I've tried using get/put/post works.
