### ISSUE TITLE
Additional web calls?

### ISSUE THREAD

**Issue by tuicemen** [bwssytems/ha-bridge#441]
Can we call a Bridge stop with a web call?
What about a reinitialization, refresh or is that done with a GET http://host:port/api/devices?

**Comment by bwssytems** [comment]
Yes, you can...

They are:

PUT http://ipaddress/system/control/reinit
PUT http://ipaddress/system/control/stop

Just remember if you call stop, you will have to restart on the system itself

**Comment by tuicemen** [comment]
great thanks
