### ISSUE TITLE
Using a get command 

### ISSUE THREAD

**Issue by michaelhinchey** [bwssytems/ha-bridge#442]
Is it possible or has anyone tried to get a response from alexa using the zwave honeywell thermostat.
I would love to be able to ask her the temperate of the house and also what temp the thermastat is set to.
As of now I can only change the temperture up and down and change the setting status mode.  Any help would be great.  THX

**Comment by bwssytems** [comment]
The api from the amazon echo for the hue api (which the ha-bridge implements) does not support this.

Sorry

**Comment by michaelhinchey** [comment]
Bummer
