### ISSUE TITLE
Can't for the life of me get a simple POST to work... 

### ISSUE THREAD

**Issue by sticilface** [bwssytems/ha-bridge#443]
Can someone point me in the right direction...  

here is the curl command that works....
```
curl -d "switch=off" http://192.168.1.219/data.esp
```

<img width="1445" alt="screen shot 2017-02-05 at 20 36 09" src="https://cloud.githubusercontent.com/assets/10061736/22629689/cad361e4-ebe2-11e6-8028-35435506b72e.png">

This is what I have, i've tried many permutations and just can't get it to work. 

any help appreciated.

**Comment by bwssytems** [comment]
Your curl request is not a POST, the default is GET in your command line example. Curl uses -X POST as the parameter to post. Change your ha-bridge to GET Verb.

**Comment by sticilface** [comment]
I've tried that and it doesn't work either!

**Comment by sticilface** [comment]
Are you certain that it is not a POST request.  from man curl

```
-d, --data <data>

(HTTP) Sends the specified data in a POST request to the HTTP server, in the same way that a browser does when a user has filled in an HTML form and presses the submit button. This will cause curl to pass the data to the server using the content-type application/x-www-form-urlencoded. Compare to -F, --form.
```

**Comment by bwssytems** [comment]
So set POST it is, how about setting content-type application/x-www-form-urlencoded

**Comment by sticilface** [comment]
bingo...

thanks :)

**Comment by bwssytems** [comment]
So, solved? you can close if you are good with it
