### ISSUE TITLE
Homeassistant Setup with SSL and Domain

### ISSUE THREAD

**Issue by quadflight** [bwssytems/ha-bridge#445]
Trying to setup HASS but using SSL (letsencrypt) and domain. Tried various combinations and will not populate the HASS devices. 

error received
`Cannot get devices for HomeAssistant with name: hass, skipping this Hass.`
`com.bwssystems.HABridge.plugins.hass.HassHome`

HASS and HABRIDGE running on the same device. Vera and Harmony works great.

Any help pointing in the right direction will be much appreciated.

**Comment by quadflight** [comment]
Solution
Name: yourname
IP: somedomain.com
Port: 443
Password: your_password
Use SSL: true

**Comment by bwssytems** [comment]
Yep!
