### ISSUE TITLE
Fibaro connection issue?

### ISSUE THREAD

**Issue by kendoone** [bwssytems/ha-bridge#446]
I am trying to get the Ha Bridge running with my Fibaro HC2 for days now.
Mostly to controll my fibaro roller shutters.
I am not very experienced with Linux so i am not exactly sure where my problem could be.

Static IP for the Pi, yes.
Static IP for the HC2, yes.
I installed the Ha Bridge ( Version 4.1.2 ) under Jessie pixel.
Configured it to run at system start.
Everything works fine
I added my Devices to the Bridge as

Device Type : Custom
Http Device
On Url: http://myusername@gmail.com:mypw@192.168.178.26/api/callAction?deviceID=42&name=turnOn
Off Url: http://myusername@gmail.com:mypw@192.168.178.26/api/callAction?deviceID=42&name=turnOff

Under Http Verb and Content Type i tried every possible combination ( leaving both blank, get + jason, Verb blank content html and many more. Like i said every possible combination. )
Tried to exchange the @ in the email adress for %40 ( like somebody in the fibaro forum suggested ) What resulted in not even giving out the error message.

The Bridge itself works.
Alexa finds the bridge device.
The Url works if i enter it in the Browser.

But if i press the test buttons in the bridge interface or tell alexa to turn off the device i always get this : 
Error on calling url to change device state: http://myusername@gmail.com:mypw@192.168.178.26/api/callAction?deviceID=42&name=turnOff

The Debug says:

02-06-2017 15:01:39.951	INFO	HA Bridge initializing....	com.bwssystems.HABridge.HABridge
02-06-2017 15:01:39.955	INFO	System control service started....	com.bwssystems.HABridge.SystemControl
02-06-2017 15:01:39.958	INFO	Initializing UDP response Socket...	com.bwssystems.HABridge.util.UDPDatagramSender
02-06-2017 15:01:39.959	INFO	UDP response Seocket initialized to: 50000	com.bwssystems.HABridge.util.UDPDatagramSender
02-06-2017 15:01:39.959	INFO	== Spark has ignited ...	spark.webserver.JettySparkServer
02-06-2017 15:01:39.959	INFO	Harmony Home created. No Harmony devices configured.	com.bwssystems.HABridge.plugins.harmony.HarmonyHome
02-06-2017 15:01:39.960	INFO	>> Listening on 0.0.0.0:80	spark.webserver.JettySparkServer
02-06-2017 15:01:39.960	INFO	Nest Home created. No Nest configured.	com.bwssystems.HABridge.plugins.NestBridge.NestHome
02-06-2017 15:01:39.960	INFO	Hue passthru Home created. No Hue passtrhu systems configured.	com.bwssystems.HABridge.plugins.hue.HueHome
02-06-2017 15:01:39.960	INFO	HAL Home created. No HAL devices configured.	com.bwssystems.HABridge.plugins.hal.HalHome
02-06-2017 15:01:39.960	INFO	MQTT Home created. No MQTT Clients configured.	com.bwssystems.HABridge.plugins.mqtt.MQTTHome
02-06-2017 15:01:39.961	INFO	HomeAssistant Home created. No HomeAssistants configured.	com.bwssystems.HABridge.plugins.hass.HassHome
02-06-2017 15:01:39.961	INFO	Command Home for system program execution created.	com.bwssystems.HABridge.plugins.exec.CommandHome
02-06-2017 15:01:39.983	INFO	Http Home created.	com.bwssystems.HABridge.plugins.http.HTTPHome
02-06-2017 15:01:39.984	INFO	TCP Home created.	com.bwssystems.HABridge.plugins.tcp.TCPHome
02-06-2017 15:01:39.984	INFO	UDP Home created.	com.bwssystems.HABridge.plugins.udp.UDPHome
02-06-2017 15:01:39.984	INFO	Vera Home created. No Veras configured.	com.bwssystems.HABridge.plugins.vera.VeraHome
02-06-2017 15:01:39.984	INFO	Domoticz Home created. No Domoticz devices configured.	com.bwssystems.HABridge.plugins.domoticz.DomoticzHome
02-06-2017 15:01:39.988	INFO	HABridge device management service started....	com.bwssystems.HABridge.devicemanagmeent.DeviceResource
02-06-2017 15:01:39.993	INFO	Hue description service started....	com.bwssystems.HABridge.upnp.UpnpSettingsResource
02-06-2017 15:01:39.994	INFO	Hue emulator service started....	com.bwssystems.HABridge.hue.HueMulator
02-06-2017 15:01:39.999	INFO	UPNP Discovery Listener starting....	com.bwssystems.HABridge.upnp.UpnpListener
02-06-2017 15:01:40.001	INFO	Traceupnp: wlan0 ... has addr /fe80:0:0:0:8c85:b7e:ee44:6d78%wlan0	com.bwssystems.HABridge.upnp.UpnpListener
02-06-2017 15:01:40.002	INFO	Traceupnp: eth0 ... has addr /fe80:0:0:0:6ed4:a8af:e19a:5546%eth0	com.bwssystems.HABridge.upnp.UpnpListener
02-06-2017 15:01:40.002	INFO	Traceupnp: eth0 ... has addr /192.168.178.41	com.bwssystems.HABridge.upnp.UpnpListener
02-06-2017 15:01:40.003	INFO	Traceupnp: Adding eth0 to our interface set	com.bwssystems.HABridge.upnp.UpnpListener
02-06-2017 15:01:40.003	INFO	Traceupnp: lo ... has addr /0:0:0:0:0:0:0:1%lo	com.bwssystems.HABridge.upnp.UpnpListener
02-06-2017 15:01:40.004	INFO	Traceupnp: lo ... has addr /127.0.0.1	com.bwssystems.HABridge.upnp.UpnpListener
02-06-2017 15:01:40.004	INFO	Traceupnp: Adding lo to our interface set	com.bwssystems.HABridge.upnp.UpnpListener
02-06-2017 15:01:40.004	INFO	UPNP Discovery Listener running and ready....	com.bwssystems.HABridge.upnp.UpnpListener
02-06-2017 15:01:40.106	INFO	Traceupnp: upnp device settings requested: from 192.168.178.41:80	com.bwssystems.HABridge.upnp.UpnpSettingsResource
02-06-2017 15:01:40.108	INFO	Traceupnp: upnp device settings template filled with address: 192.168.178.41 and port: 80	com.bwssystems.HABridge.upnp.UpnpSettingsResource
02-06-2017 15:01:48.796	WARN	Error on calling url to change device state: http://myusername@gmail.com:mypw@192.168.178.26/api/callAction?deviceID=42&name=turnOff	com.bwssystems.HABridge.plugins.http.HTTPHome

I have absolutely no idea what i am missing out.
Perhaps someone here can help me out.

**Comment by bwssytems** [comment]
The format is this http://username:pwd@ipaddress//api/devices/deviceID/action/actionName

**Comment by kendoone** [comment]
It worked like a charm!
Thanks a lot for your help!

I just wanted to add that i had to use the format

http://username%40gmail.com:pwd@ipaddress//api/devices/deviceID/action/actionName

Cause Fibaro Id requires a login with email adress instead of username in the newest firmware the @ in the email adress is exchanged with %40.
Otherwise it didn't work.
Just wanted to add that for other users with the same problem.

Can u perhaps tell me the right format for the dim command too?

**Comment by Matt8119** [comment]
im also stumped with what the new dim commands are for the Fibaro home center...

**Comment by duztmonkey** [comment]
Hi, i just got Habridge up and running using 4.1.4.jar on a HC2 4.110.

im trying to add a device, but i seam unable to get the  "Http" correct.

Can i somehow test that the "login" part of it all is working, so that i know that it is excepting my username/password and username?

Im trying to add my fiboar dimmer 2 witch has device # 13. How should the URL look?

http://eric.besterman%40gmail.com:password@192.168.2.199//api/devices/13/action/turnOff

This is what i have tried, only changing the last word from off to on for the turn on part. But i get error every time.

**Comment by bwssytems** [comment]
@duztmonkey Are you using the POST http verb?

**Comment by duztmonkey** [comment]
@bwssytems Thanks for the quick reply!

I was not using the POST verb, but i changed it to post but still getting the same error. 

the "habridge-log.txt" logs the following error:

"2017-02-23 19:42:13,213 [qtp5508233-11] WARN  com.bwssystems.HABridge.plugins.http.HTTPHome - Error on calling url to change device state: http://xxxx.xxxxxxx%40gmail.com:Password@192.168.2.199//api/devices/13/action/turnOn"

The only things i have entered into the device in Habridge Gui is the "Type=Http Device". My HTTP link witch you can see in the error log above. And now i also tried to change the Verb to POST (this was empty before). 

I dont know if it is the "API" (if that what it is called?) is wrong? 

I have entered the following in the "on" part of the Gui:
"http://xxxx.xxxxxxx%40gmail.com:Password@192.168.2.199//api/devices/13/action/turnOn"
Im not sure if this is right for the Fibaro HC2 now when they have changed it to email log in?

Thanks again for your help!

PS. i'm testing this through the "test buttons" if that can cause any problems?

**Comment by kveselko** [comment]
@bwssytems Can you please provide new command formats for DIMMING, RGB(W), ROLLER SHUTTER... and for FIBARO system. Many thanks!

**Comment by Matt8119** [comment]
Hers fibaro commands:

Turn	On	a	Device:	
http://USER%40EMAIL.COM:PASSWORD	@IPADDRESS/api/callAction?deviceID=ID&name=turnOn	 Turn	Off	a	Device:	
http://USER%40EMAIL.COM:PASSWORD	@IPADDRESS/api/callAction?deviceID=ID&name=turnOff	 Dim	a	Device:	
http://USER%40EMAIL.COM:PASSWORD	@IPADDRESS/api/callAction?deviceID=ID&name=setValue&arg1=${intensity.percent}	 Start	a	Scene:	
http://	USER%40EMAIL.COM:PASSWORD	@IPADDRESS	/api/sceneControl?id=ID&action=start	 The	Fibaro	RGBW	allows	us	to	set	the	colours	of	all	4	values	with	this	API:	 http://USER%40EMAIL.COM:PASSWORD@IPADDRESS	 /api/callAction?deviceID=241&name=setColor&arg1=100&arg2=200&arg3=50&arg4=0

**Comment by bwssytems** [comment]
@Matt8119 Thanks, as I would have to google this to find it. 
@kveselko Since I have not worked on a Fibaro yet, it would help if you could google for the answers

**Comment by Matt8119** [comment]
@kveselko  this guy's just did a YouTube video with  version 4.1.4 on setting this up a raspberry pi from scratch and connecting with a fibaro hc2 
https://youtu.be/kwYGsxhQCvc

**Comment by kveselko** [comment]
this does not work with my configuration as the new format is http://username%40gmail.com:pwd@ipaddress//api/devices/deviceID/action/actionName . If a use this format all is well but I don't have and can't find DIMMER and other commands :(

**Comment by Matt8119** [comment]
@kveselko  try these.

Turn On	aDevice:	
http://USER%40EMAIL.COM:PASSWORD@IPADDRESS/api/callAction?deviceID=ID&name=turnOn	 Turn	Off	a	Device:	
http://USER%40EMAIL.COM:PASSWORD@IPADDRESS/api/callAction?deviceID=ID&name=turnOff	 Dim	a	Device:	
http://USER%40EMAIL.COM:PASSWORD@IPADDRESS/api/callAction?deviceID=ID&name=setValue&arg1=${intensity.percent}	 
Start a Scene:	
http://USER%40EMAIL.COM:PASSWORD@IPADDRESS/api/sceneControl?id=ID&action=start	 
The	Fibaro RGBW allows us to set the colours of	all 4 values with this API:	 http://USER%40EMAIL.COM:PASSWORD@IPADDRESS/api/callAction?deviceID=241&name=setColor&arg1=100&arg2=200&arg3=50&arg4=0

**Comment by kveselko** [comment]
This format **works**: 
http://username%40mail.com:pwd@ipaddress//api/devices/deviceID/action/actionName

This format **does not work**:
http://username%40mail.com:pwd@ipaddress/api/callAction?deviceID=ID&name=turnOn

**Comment by duztmonkey** [comment]
@kveselko 

How would my adress look using your first example that actually works?

http://username%40mail.com:pwd@ipaddress//api/devices/deviceID/action/actionName

If i want to turn ON my "Diningroom Light" with ID 13?
My login details could be name.lastname@gmail.com and password is "Password/87".

Thanks for all the help!

**Comment by kveselko** [comment]
http://name.lastname%40gmail.com:87@000.000.000.000//api/devices/13/action/turnOn

if this is FIBARO, device type is "HTTP Device" and HTTP Verb is "POST"

for off, just change the actionName at the end to "turnOff"

**Comment by bwssytems** [comment]
This does work, so losing

**Comment by ElementProHD** [comment]
I need help making a Virtual device work I have this in the LUA:

local http = Net.FHttp("w******@hotmail.com:F*******3!@192.168.1.7", 80);
local response = http:GET("/api/callAction?deviceID=61&name=turnOn");

local http = Net.FHttp("w******@hotmail.com:F*******3@192.168.1.7", 80);
local response = http:POST("/api/callAction?deviceID=61&name=turnOn");

I have tried these two and all I want to do is turn on device 61 which works if I type this link in internet explorer:

http://w******@hotmail.com:F*******3@192.168.1.7/api/callAction?deviceID=61&name=turnOn


I just want it so if I click one of the buttons in fibaro it turns on the device thanks.
