### ISSUE TITLE
newline

### ISSUE THREAD

**Issue by mbreunich** [bwssytems/ha-bridge#448]
Hi there,

in version 4.1.4 the newline character for items does not work anymore.

e.g.
cmd item: tcp://localhost:7072/set ZWave_SWITCH_BINARY_7 on\n

will be replaced with:
old version: tcp://localhost:7072/set ZWave_SWITCH_BINARY_7 on\\n
new version tcp://localhost:7072/set ZWave_SWITCH_BINARY_7 on\\\\n

I could manually fix this by editing the device.db to old version.

Best regards,
Michael

**Comment by bwssytems** [comment]
Yes, the new JSON constructs do not like new line chars in them

**Comment by bwssytems** [comment]
Fixed in 4.2.1
