### ISSUE TITLE
Get current activity Harmony Hub

### ISSUE THREAD

**Issue by Echotrouble** [bwssytems/ha-bridge#449]
Hello,

Is it possible to get the current activity from the Harmony hub? Or can I check if one of my devices is one through the Harmony hub REST api?

**Comment by bwssytems** [comment]
https://github.com/bwssytems/ha-bridge#show-harmony-current-activity

**Comment by Echotrouble** [comment]
Yeah, sorry I was still on 3.5.1 and it was just showing the same as http://192.168.123.60/api/devices/harmony/activities , I fixed it by upgrading to 4.1.4 !

**Comment by bwssytems** [comment]
Yes, that was broke in 3.5.1, as you see it is fixed.
