### ISSUE TITLE
Unable to edit on ipad 

### ISSUE THREAD

**Issue by Luftloch80** [bwssytems/ha-bridge#450]
It is impossible to work with habridge on ipad with new version 

![img_0008](https://cloud.githubusercontent.com/assets/20800008/22706583/24200d40-ed70-11e6-94f2-dce26adf69c9.PNG)

**Comment by bwssytems** [comment]
Don't use safari, download chrome for iOS....

**Comment by Luftloch80** [comment]
On My iPad Pro same behaviuor with chrome

**Comment by bwssytems** [comment]
You are not able to grab the lower right corners of the edit boxes to expand on an iPad? Don't know if I'll get around to changing anything to work on tablets for the editor. Using your laptop or desktop would be better for now.

**Comment by Andyjd86** [comment]
using Edge on windows 10 has a similar problem

**Comment by emiliosic** [comment]
I think Chrome on iOS still uses webkit. It's a shame it only works on Chrome

**Comment by bwssytems** [comment]
This will be fixed in 5.0.0
