### ISSUE TITLE
Can I mix protocols on a single Device

### ISSUE THREAD

**Issue by lonebaggie** [bwssytems/ha-bridge#451]
I have a single dimmer LightwaveRF which I control with UDP commands  works fine.

I have an additional 3 devices Bright,Relaxed and Dark which set dimming levels for the same dimmer. It easier to say "Alexa turn on Bright"  than "Alexa Turn on Living room light to 100".

I would like to keep the four devices in sync so when I turn on bright can I use a UDP command to turn on the dimmer and  a REST API Update bridge internal light state for the other devices, so when I turn off bright  the light goes out and four devices are logically off in the emulated Hue

Do multiple command have to be in the same protocol ?
 
Im  struggling with the format for the API calls, so I just need to know if its my stupidity.

**Comment by bwssytems** [comment]
Yes they can be different, that was the whole idea.  V4 had the constructs to make that tester for editing.

**Comment by bwssytems** [comment]
Did this answer your question?

**Comment by lonebaggie** [comment]
Glad it my stupidity 
Struggling to format the Http call back to the HA-Bridge.
Thanks  for replying so quickly

**Comment by bwssytems** [comment]
review the Hue Api here https://github.com/bwssytems/ha-bridge#hue-rest-api-usage

**Comment by bwssytems** [comment]
Has this answered your question?
