### ISSUE TITLE
habridge and weaved?

### ISSUE THREAD

**Issue by jswim788** [bwssytems/ha-bridge#453]
Has anyone tried to use the habridge with weaved/remot3.it?  The weaved installer doesn't seem to see anything listening on port 80, but the habridge does work locally.  I did notice this from netstat -lptn.  I'm not up to speed on tcpip v6, but maybe there is some issue here?  Or I have something configured incorrectly on the RPI?

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      522/sshd
tcp6       0      0 :::80                   :::*                    LISTEN      6411/java
tcp6       0      0 :::22                   :::*                    LISTEN      522/sshd

sshd seems to be on both tcp and tcp6, but the habridge is only on tcp6.

**Comment by bwssytems** [comment]
That should not be the case as I force the ha-bridge to be IPV4 only and IPV6 needs to have a setting passed to enable it. I would look at the config for your PI as you can disable IPV6 from starting as it is on by default.

**Comment by jswim788** [comment]
To me it looks like just the opposite - IPV6 is enabled but IPV4 is not in the ha-bridge.  The Raspberry Pi seems to be enabled for both as can be seen in the support for sshd on both.  I'm using the 4.1.4 pre-built version.  I'll look for anything interesting in the logs.  Any ideas?  Thanks.

**Comment by bwssytems** [comment]
https://www.raspberrypi.org/forums/viewtopic.php?f=36&t=138899

**Comment by jswim788** [comment]
This is a non-issue, I think.  Despite weaved not seeing this, it works anyway.  I was confused because my work location doesn't let some traffic through the firewall, and this is one it blocked.  Once I tried remote access to the ha-bridge from a non-work location via weaved, it worked fine.  Moral of the story: only work on the ha-bridge at home...
