### ISSUE TITLE
issue using REST api

### ISSUE THREAD

**Issue by cipher2k** [bwssytems/ha-bridge#455]
I have an issue using the REST api to add/modify a harmony activity.

This JSON works fine:

`{"id":"23","deviceType":"activity","name":"Fire","targetDevice":"Schlafzimmer","mapType":"harmonyActivity","mapId":24338000,"onUrl":"[{\"item\":\"{\\\"name\\\":\\\"24338000\\\",\\\"hub\\\":\\\"Schlafzimmer\\\"}\",\"type\":\"harmonyActivity\"}]","offUrl":"[{\"item\":\"{\\\"name\\\":\\\"-1\\\",\\\"hub\\\":\\\"Schlafzimmer\\\"}\",\"type\":\"harmonyActivity\"}]"}`

But this JSON does not:

`{ "name" : "Fire", "id" : "23", "deviceType" : "activity", "targetDevice" : "Schlafzimmer", "mapType" : "harmonyActivity", "mapId" : 24338000, "onUrl" : "[{ \"item\" : \"{ \\\"name\\\" : \\\"24338000\\\", \\\"hub\\\" : \\\"Schlafzimmer\\\" }\", \"type\" : \"harmonyActivity\" }]", "offUrl" : "[{ \"item\" : \"{ \\\"name\\\" : \\\"-1\\\", \\\"hub\\\" : \\\"Schlafzimmer\\\" }\", \"type\" : \"harmonyActivity\" }]" }`

The second JSON does not respond with an error, but when I look into HA Bridge then I see that in On Items the type is not set to Harmony Activity and in Target Items I see the following JSON:
`[{"item":"{ \"name\" : \"24338000\", \"hub\" : \"Schlafzimmer\" }","type":"harmonyActivity"}]`

Do you have an explanation for this behavior? Both JSONs are equal to me, except slightly different order and the spaces.

**Comment by bwssytems** [comment]
Was either of those created with the helper?

**Comment by cipher2k** [comment]
the first one was initially created with the helper and then i used it as a template.

the second one was created programmatically with a JSON parser.

**Comment by cipher2k** [comment]
any idea what is wrong with the second query? are you able to reproduce the behavior?

**Comment by bwssytems** [comment]
When looking at those, it looks like it should work. I'll try and test your second generated one.

**Comment by bwssytems** [comment]
Wow, I do not have an explanation for this as I get the same results. Will review some more.

**Comment by cipher2k** [comment]
so you are able to reproduce it?

**Comment by bwssytems** [comment]
Yep, I can reproduce it.

**Comment by sege** [comment]
I'm having trouble with REST looking like this:
{ "args": [ 2 ] }

Adding with helper but I only get errors when I'm trying to use it. 

Looks like this in config:
"onUrl": "[{\"item\":\"http://<user>:<password>@<IP>:80/api/devices/691/action/pressButton\",\"type\":\"httpDevice\",\"httpVerb\":\"POST\",\"httpBody\":\"{ \\\"args\\\": [ 2 ] }\",\"contentType\":\"application/json\"}]",

Any ideas?

**Comment by bwssytems** [comment]
@sege I will assume it is not liking the array value [2]. I'll take a look at the handling of the httpBody in the request.

**Comment by sege** [comment]
@bwssytems can I help you in some way? Supply logs or something, just let me know!

**Comment by cipher2k** [comment]
issue is still open in 4.2.0 . just tried it.

**Comment by bwssytems** [comment]
yes, i have not solved this yet

**Comment by bwssytems** [comment]
@sege I do not see that issue, in my test it is working.

**Comment by bwssytems** [comment]
I have added a parse check on the api. This is duplicated to #326

**Comment by cipher2k** [comment]
sorry, but it is still not working as expected.
when i put this json:
`{ "name" : "TV", "id" : "22", "deviceType" : "activity", "targetDevice" : "Schlafzimmer", "mapType" : "harmonyActivity", "mapId" : 24337959, "onUrl" : "[{ \"item\" : \"{ \\\"name\\\" : \\\"24337959
\\\", \\\"hub\\\" : \\\"Schlafzimmer\\\" }\", \"type\" : \"harmonyActivity\" }]", "offUrl" : "[{ \"item\" : \"{ \\\"name\\\" : \\\"-1\\\", \\\"hub\\\" : \\\"Schlafzimmer\\\" }\", \"type\" : \"harmonyActivity\" }]" }`

I get this response from HA Bridge:
`{"id":"22","u
niqueid":"00:17:88:5E:D3:16-16","name":"TV","mapId":"24337959","mapType":"harmonyActivity","deviceType":"activity","targetDevice":"Schlafzimmer","offUrl":"[{ \"item\" : \"{ \\\"name\\\" : \\\"-1\\\", \\\"hub\\\" : \\\"Schlafzimmer\\\" }\
", \"type\" : \"harmonyActivity\" }]","onUrl":"[{ \"item\" : \"{ \\\"name\\\" : \\\"24337959\\\", \\\"hub\\\" : \\\"Schlafzimmer\\\" }\", \"type\" : \"harmonyActivity\" }]","inactive":false,"noState":false}`

and when I look into HA Bridge UI, I see the following:
[http://enlightme.info/hab.png](url)

**Comment by cipher2k** [comment]
more interestingly, when I put:
`{ "name" : "TV", "id" : "22", "deviceType" : "activity", "targetDevice" : "Schlafzimmer", "mapType" : "harmonyActivity", "mapId" : 24337959, "onUrl" : [{ "item" : { "name" : "24337959", "hub" : "Sc
hlafzimmer" }, "type" : "harmonyActivity" }], "offUrl" : [{ "item" : { "name" : "-1", "hub" : "Schlafzimmer" }, "type" : "harmonyActivity" }] }`

I get the following:
`<html><body><h2>500 Internal Error</h2></body></html>`

**Comment by cipher2k** [comment]
ok, got it solved by sending HA Bridge a compressed JSON. But, this is a problem with the JSON parser you are using.

With the following JSON:
`{"name":"TV","id":"22","deviceType":"activity","targetDevice":"Schlafzimmer","mapType":"harmonyActivity","mapId":24337959,"onUrl":"[{\"item\":\"{\\\"name\\\":\\\"24337959\\\",\\\"hub\\\":\\\"Schlaf
zimmer\\\"}\",\"type\":\"harmonyActivity\"}]","offUrl":"[{\"item\":\"{\\\"name\\\":\\\"-1\\\",\\\"hub\\\":\\\"Schlafzimmer\\\"}\",\"type\":\"harmonyActivity\"}]"}`

...it works as excpected.

**Comment by bwssytems** [comment]
Ahh, you figured it out as I just wnet through it as well
```
{ "name" : "TV", "id" : "22", "deviceType" : "activity", "targetDevice" : "Schlafzimmer", "mapType" : "harmonyActivity", "mapId" : "24337959", "onUrl" : "[{ \"item\" : \"{ \\\"name\\\" : \\\"24337959 \\\", \\\"hub\\\" : \\\"Schlafzimmer\\\" }\", \"type\" : \"harmonyActivity\" }]", "offUrl" : "[{ \"item\" : \"{ \\\"name\\\" : \\\"-1\\\", \\\"hub\\\" : \\\"Schlafzimmer\\\" }\", \"type\" : \"harmonyActivity\" }]" }
```

**Comment by bwssytems** [comment]
This is not an issue with the JSON parser, it is because the field "onUrl", "offUrl" and "dimUrl" are strings and then they encapsulate JSON in the new versions, but the old versions did not. It is a backwards compatibility thing.

**Comment by cipher2k** [comment]
This is clear to me, but it is clearly an issue with whitespace (non-compressed) vs. no whitespaces (compressed) version...

**Comment by bwssytems** [comment]
Whitespace doesn't matter as the example I just posted works fine. It was all about the escaping the quotation marks that was the issue.

**Comment by cipher2k** [comment]
But why does this NOT work properly:
`{ "name" : "TV", "id" : "22", "deviceType" : "activity", "targetDevice" : "Schlafzimmer", "mapType" : "harmonyActivity", "mapId" : 24337959, "onUrl" : "[{ \"item\" : \"{ \\\"name\\\" : \\\"24337959 \\\", \\\"hub\\\" : \\\"Schlafzimmer\\\" }\", \"type\" : \"harmonyActivity\" }]", "offUrl" : "[{ \"item\" : \"{ \\\"name\\\" : \\\"-1\\\", \\\"hub\\\" : \\\"Schlafzimmer\\\" }\", \"type\" : \"harmonyActivity\" }]" }`

And this DOES:
`{"name":"TV","id":"22","deviceType":"activity","targetDevice":"Schlafzimmer","mapType":"harmonyActivity","mapId":24337959,"onUrl":"[{\"item\":\"{\\\"name\\\":\\\"24337959\\\",\\\"hub\\\":\\\"Schlafzimmer\\\"}\",\"type\":\"harmonyActivity\"}]","offUrl":"[{\"item\":\"{\\\"name\\\":\\\"-1\\\",\\\"hub\\\":\\\"Schlafzimmer\\\"}\",\"type\":\"harmonyActivity\"}]"}`

In both cases the quotation marks are escaped correctly. The only difference is the whitespaces.

**Comment by bwssytems** [comment]
compare this string to yours with the whitespace:
'{ "name" : "TV", "id" : "22", "deviceType" : "activity", "targetDevice" : "Schlafzimmer", "mapType" : "harmonyActivity", "mapId" : "24337959", "onUrl" : "[{ \"item\" : \"{ \\\"name\\\" : \\\"24337959 \\\", \\\"hub\\\" : \\\"Schlafzimmer\\\" }\", \"type\" : \"harmonyActivity\" }]", "offUrl" : "[{ \"item\" : \"{ \\\"name\\\" : \\\"-1\\\", \\\"hub\\\" : \\\"Schlafzimmer\\\" }\", \"type\" : \"harmonyActivity\" }]" }'

**Comment by cipher2k** [comment]
only difference here is that you have mapId value in quotation marks and in my request it is an integer:
`"mapId" : "24337959"`   vs. `"mapId" : 24337959`

**Comment by bwssytems** [comment]
It is a String in the code.

**Comment by cipher2k** [comment]
ok, good to know. will change this accordingly in my code. :)
