### ISSUE TITLE
Can't get bridge to talk to Netcat to send commands via mochad

### ISSUE THREAD

**Issue by instructor1361** [bwssytems/ha-bridge#458]
Probably not a bridge issue as much as a user issue but I'm trying to get the bridge to send netcat commands via mochad. NC from the terminal works fine as does a remote nc session. Would like examples of the proper command syntax to configure in the bridge GUI. Have used the bridge successfully with windows and Mint 18 via a firecracker module but can't figure out the proper command structure to get it to communicate via Netcat to a CM19A X10 module.

Searched the forums to no avail, any assistance appreciated.

**Comment by bwssytems** [comment]
The target item should be tcp://pl a1 on and the type should be TCP Device.

**Comment by instructor1361** [comment]
Thanks for the response but still no go. Command generates no errors but still no comm to Netcat. If this helps my platform configuration is all on same PC:
Mint 18
Mochad 0.1.17
HA-Bridge 4.1.3 (Tried in older 3.5.1 as well)
Settings in Bridge
Name=Testlight
Inactive and No state.. blank
Target= default
Device Type = TCP
Map Type = Blank
MAC Addr for HUe = per system
Map ID = per system 1111
On Items Settings 
Type = TCP Device
Target Item = tcp://192.168.1.240:1099/rf a1 on
Remaining On items left at default

Request executed success shown when using test button

**Comment by bwssytems** [comment]
I have tested this again and it is working.

**Comment by instructor1** [comment]
Not sure what the issue is but it doesn't work for me. Anyway, got tired of tweaking on it to no avail so I installed Domoticz and let it be the mediator. Works great and your Domoticz configuration tool works flawlessly and saves a lot of typing too! Thanks for the follow-up and the great application. BTW I'm using my Echo Dot to voice manage the lighting through the bridge and that works great too.

**Comment by bwssytems** [comment]
Yes, tested some more and now it is inconsistent. Will look some more.

**Comment by instructor1361** [comment]
?Thank You


Mark J. Puig

<http://www.cvtc.edu/>
<http://www.cvtc.edu/>
________________________________

**Comment by bwssytems** [comment]
I have an enhancement that may help in the next release

**Comment by instructor1361** [comment]
Thank you,

I just ordered a Raspberry Pi to try this in. I'll give it a go with 4.2.1.

**Comment by bwssytems** [comment]
Well, I have to do some other fixing, it seems mochad needs a \n, \r or \0 for it complete the line read. Unless you send a hex string, i encode those as characters and not to the actual byte value.

**Comment by instructor1361** [comment]
Received the Pi3 yesterday, installed Mochad and Ha-Bridge 4.2.1, used TCP device command as  tcp://192.168.1.240:1099/rf a1 on. No error indicted from the Bridge but no comm with Mochad either. Using Netcat command rf a1 remotely to, and locally on the Pi work fine. Any suggestion on how else o test comms between the bridge and mochad?

**Comment by bwssytems** [comment]
You need to put a \n after that command

**Comment by instructor1361** [comment]
Will give that a try tomorrow. Thank You

**Comment by instructor1361** [comment]
Couldn’t wait but adding the \n did the trick. What is its function? I saw some mention of the \n in the last fix but missed what it does. Thanks for the prompt response and fix.

**Comment by bwssytems** [comment]
Mochad expects that a CR LF or null to be passed at the end of the string. When using netcat, when you hit the return key it sends the CR or \n character.

**Comment by instructor1361** [comment]
?Makes sense, thank you for the explanation. The fix in 4.2.1 will allow me to take Domoticz out of the mix although the two products have been working well together. I haven't tried 4.2.1 with the Echo yet but I'm optimistic it will be as seamless as the previous releases.


Next task, is X10 dimming possible using the Dim command in place of the on/off options? I have both power-line and RF options available.


Thanks again, great product!


Mark J. Puig

<http://www.cvtc.edu/>
<http://www.cvtc.edu/>
________________________________

**Comment by audiofreak9** [comment]
I wrote a tutorial for X10 that gives X10 dimming examples here: http://coreyswrite.com/electronics/home-automation/amazon-echo-x10-home-control-updated/

**Comment by Matt8119** [comment]
@audiofreak9 in this write up, is the process involving the ha-bridge still the same as you described?

**Comment by instructor1** [comment]
Thanks Corey, not using Heyu, sending X10 commands directly from the HA-Bridge via TCP to Netcat to execute in Mochad. Mochad is talking to the X10 transceiver via a USB port. Until the latest update (4.2.1) I couldn't get the bridge to talk to Netcat so I had installed Domoticz as a go between to send the commands from the bridge to Mochad. This worked great but the fix now allows me to send directly from the bridge to Mochad via Netcat using TCP device type. (e.g. tcp://192.168.x.x:1099/rf a1 on)

**Comment by audiofreak9** [comment]
@Matt8119 yes, just use the updated ha-bridge v4.2.1, otherwise my tutorial for X10 control is up to date.

@instructor1 nice, I'm planning on playing with some TCP myself, so yeah my tutorial uses `obdim`  "On, Full Bright, Dim %", which is a HEYU command, but this works nicely with the ha-bridge's state memory.  You can just use MOCHAD's dim, nearly the same.  Power-line is `pl <H><U> dim <Dims>` and RF is `rf <H><U> dim`.

**Comment by audiofreak9** [comment]
@Matt8119 BTW, I've even bricked an RPi in the past and followed my own tutorial building a new ha-bridge, just to be sure my steps still work.

**Comment by audiofreak9** [comment]
@instructor1 Just a thought if the ha-bridge and the USB X10 transceiver are on the same RPi, then you can call the MOCHAD directly on the ha-bridge with the exec type, essentially replacing HEYU with MOCHAD in my tutorial.

**Comment by instructor1361** [comment]
That may be the case but I wasn’t able to get that to work when I first starting playing with this project. Domoticz worked fine to communicate to Mochad but I couldn’t get exec type to work so I left Domoticz in and then used the Ha-Bridge to configure the Domoticz devices once I had the X10 switches setup in Domoticz. Used advise from Bwssystems to configure the TCP connection via Netcat which also didn’t work until the 4.2.1 update as seen of the github thread.

It may have been a configuration issue (user error) early on but I couldn’t seem to find out how to properly apply the settings to make bridge send the commands directly to mochad. And I did spend a lot of time searching for them without luck. In fact you and I had a dialogue back in the early stages when I was switching from the X10 firecracker to a CM19a and Mochad and I was trying to make it work. The TCP solution looks like it’s working OK for me now but I’d still be interested in how to configure the bridge to send exec type commands if you have some doc on that.

**Comment by audiofreak9** [comment]
I'm gonna have to get my test RPi B+ out, install MOCHAD and test it out.  However, using the EXEC type is very straight forward - even in the newest GUI.

**Comment by instructor1361** [comment]
I'll be interested to know how that goes. I just got my first RPi 3 on Friday but haven't had much time to play with it beyond a simple test of 4.2.1 and mochad on it. I'll try some exec commands today.


My current operational configuration is running on an old HP Netbook under Linux 16.4. Works fine but I wanted something smaller that I can physically pair with an X10 CM15a or just the CM19a.


?
<http://www.cvtc.edu/>
<http://www.cvtc.edu/>
________________________________

**Comment by enishoca** [comment]
I got this working on 4.5.6 with the following settings
Set the Map Type to TCP Device
Set the command type to TCP Device
set the Item field to "tcp://127.0.0.1:1099/rf a1 on \n" without quotes

**Comment by instructor1** [comment]
Thanks Enis. I didn’t know this question was still out there. I’ve had it working for quite a while now. I was missing the \n in the TCP command to netcad. Are you using any dim commands to X10 via the bridge?

**Comment by enishoca** [comment]
sorry for the late reply - sort of, not really.  the only way I could get that to work was create another switch and replace the on and off commands with dimmer up and down command.
________________________________
