### ISSUE TITLE
Question - How to configure dimmer with URL

### ISSUE THREAD

**Issue by ps915** [bwssytems/ha-bridge#459]
Whats the correct URL for controlling a Homematic Dimmer via FHEM HTTP Device?

If i manually surf this url, it works:
`http://127.0.0.1:8083/fhem?cmd.dimmer.esstisch=set+dimmer.esstisch+50`

if i use this in HA Bridge
`http://127.0.0.1:8083/fhem?cmd.dimmer.esstisch=set+dimmer.esstisch+{$intensity.percent}`

i get this error

> Request Error, Pleae look in your habridge log: error {"type":"6","address":"/lights/1","description":"Error on calling url to change device state","method_name":"/lights/1state"}

**Comment by pattyland** [comment]
You have to write $ before the brackets, it's `${intensity.percent}`

**Comment by ps915** [comment]
Ok, that's embarrassing! Thank you! :-P
