### ISSUE TITLE
Harmony remote not seeing ha-bridge 'Hue' devices properly

### ISSUE THREAD

**Issue by gorstj** [bwssytems/ha-bridge#460]
I have my echo working perfectly with my Ha-Bridge setup.

However I am having trouble getting the Harmony remote/app to see my 'Hue' devices.

They can only see 2 of my 7 devices and when I switch these on and off the names are incorrect (e.g. lounge actually controls dining room!)

Does anyone else have Harmony set up and working? Did you encounter these issues?

(this has been an issue in both 3.5 and the latest 4)

**Comment by Neuroplant** [comment]
Hello,
you have to renumber the devices, because it seems you have cloned your devices from two masters and they have all the same Hue-ID.

I wonder if I can use this to hide Actions from Harmony...
Greeting
Neuroplant

**Comment by Wobbi** [comment]
@Neuroplant Thanks for this hint. I am not really well acquainted with habridge at the moment, but it seems renumbering the devices, reinitializing the bridge and then repairing the hub with the hue device solves the problem.
