### ISSUE TITLE
Execute commands with parameters containing whitespaces

### ISSUE THREAD

**Issue by pattyland** [bwssytems/ha-bridge#462]
Hi there!

I have a configured a device that executes commands when triggered. "on" and "off" have different parameters. The parameter for the "on" trigger contains a whitespace, and does not work. Executing the command in bash does work though...

Andy idea? parameters without whitespaced are working!

Greets, Sören

**Comment by audiofreak9** [comment]
I found the plus sign + works well in place of the space.

**Comment by audiofreak9** [comment]
@pattyland Have you found a working solution to this issue?

**Comment by pattyland** [comment]
Hm, it does not seem to work for me. I'm using `effect="${1/+/ }"` to convert the plus sign in my bash script now, but this is an ugly solution
