### ISSUE TITLE
Sending URL to arduino

### ISSUE THREAD

**Issue by GeorgesVDR** [bwssytems/ha-bridge#463]
I just recently bought an Amazon Echo from the German Amazon Store and started to implement into my home automation system build with an Arduino Mega. It has been doing a great job so far and managed to integrate it with home bridge. Now i'm trying to get everything working with Ha-bridge! Managed to get everything up and running but now i'm manually adding devices and get back some errors :s.

So in my home automation a webserver is waiting on simple command for example:
To turn the kitchen light on or off: http://192.168.0.221/$5
No state is generated its just a simple relay thats opening and closing on the otherside.

![capture](https://cloud.githubusercontent.com/assets/25721809/22863346/b8a070d2-f13e-11e6-801a-3e0ad2772a96.PNG)

Although I managed to get this far I'm still a noob trying to figure things out with watching youtube and reading forum's.

Error's are below. Am I configuring my request wrong? Because I can test within HA brigde and everything works fine (although I get a red box like the pictures below) but when asking Alexa my lights turn on but I get an error respons and my light turn back off :s.

![capture 2](https://cloud.githubusercontent.com/assets/25721809/22862187/75cf90e4-f12a-11e6-954b-521d8653afbd.PNG)
![capture3](https://cloud.githubusercontent.com/assets/25721809/22862188/776abdc0-f12a-11e6-83ce-99dd43a56887.PNG)

![capture4](https://cloud.githubusercontent.com/assets/25721809/22863388/63c43dcc-f13f-11e6-8451-4e46241f9f07.PNG)

Thanks again for some guidance !

**Comment by GeorgesVDR** [comment]
Just to be clear I'm using the "HTTP Device" not the "Domoticz device" like mentioned it the printscreen.

**Comment by bwssytems** [comment]
Have you tested this outside of the bridge to see if the http calls are working go your arduino?

**Comment by GeorgesVDR** [comment]
Yes, I can confirm they're working through a test via a webbrowser.

**Comment by bwssytems** [comment]
What is the return from the arduino api? It seems there is no return and that is the issue.

**Comment by GeorgesVDR** [comment]
Yes, indeed. It just processes the command but doesn't respond. So what response is HA-bridge waiting for so I could alter the code of my arduino script. Or is there an option to alter HA-bridge to not look for a respons.

**Comment by bwssytems** [comment]
It needs an HTTP 200 Ok based in the http protocol.

**Comment by jbardi** [comment]
Your arduino script needs to return an http response before closing the client connetion. Somthing like this I belive:

// send a standard http response header
client.println("HTTP/1.1 200 OK");
client.println("Content-Type: text/html");
client.println("Connection: close");
break;

**Comment by GeorgesVDR** [comment]
Adjusted the arduino code like jbardi mention and everything works like a charme :)
