### ISSUE TITLE
Cannot discover on Pixel Google assistant

### ISSUE THREAD

**Issue by sandervanpelt** [bwssytems/ha-bridge#464]
Followed the normal discovery process.
Running version 4.1.4  of habridge
Android 7.1.2 beta
Please let me know what logging you need to troubleshoot

**Comment by audiofreak9** [comment]
Do you have a physical Google Home device?  

I think just like the Amazon Alexa app, you may not be able to discover the ha-brigde without a physical device.

**Comment by audiofreak9** [comment]
FYI: https://github.com/bwssytems/ha-bridge/wiki/HA-Bridge-FAQs#device

**Comment by sandervanpelt** [comment]
True, no physical Google Home device. 
Now that Google Assistant on Pixel supports Home Control I was hoping for this to work.

**Comment by Matt8119** [comment]
a physical google home searches on port 80.  "creating the web address"

**Comment by audiofreak9** [comment]
Yeah, this project currently requires a physical device.

**Comment by nldroid** [comment]
Did you try the assistant with a 'real' Hue bridge?

**Comment by Matt8119** [comment]
You must have a physical Google home to discover the bridge

**Comment by audiofreak9** [comment]
I feel this thread is sufficiently answered...closing.
