### ISSUE TITLE
Available syntaxes besides ${intensity.percent} ?

### ISSUE THREAD

**Issue by Chrunchy** [bwssytems/ha-bridge#467]
What syntax'es are available to use, besides ${intensity.percent} ?
Are there any syntax available for 'Target' or 'Map ID'?

I'm asking since i use ha-bridge to run different shellscripts, and it would be convenient to parse in values typed into 'Map ID' or 'target' for the script it's running. ${intensity.percent works perfectly for this, i just need to know if others are available.

Example of my script:
Script target '/home/sunny/backlight.sh ${intensity.percent} uniquID'

Instead of typing in the unique ID for every item in the targetcode, i would like to type in the unique ID in to either Target or Map ID and parse it like i do with intensity.percent syntax, so the code would be:

'/home/sunny/backlight.sh ${intensity.percent} ${Map.ID}'

**Comment by bwssytems** [comment]
That is not available, but could be an enhancement

**Comment by Chrunchy** [comment]
Ok, thanks for answering so quickly.
I would love to see it possible in a future update.
 
Are there any suggestion list/wishlist for enhancements i can add it to?

**Comment by bwssytems** [comment]
this is the place, just enter an issue for each thing you would like. But please review other enhancements as to not duplicate.

**Comment by cipher2k** [comment]
Could you add the possibility to get the ID of the device that got fired like with ${intensity.percent} for example ${device.id} ?
