### ISSUE TITLE
HA Bridge says Access Denied in Nano on terminal 

### ISSUE THREAD

**Issue by Piers101** [bwssytems/ha-bridge#469]
So recently I bought the amazon echo dot and the Milights I bought these then realised I needed Ha-Bridge so I followed these instruction and after pasting this into nano on terminal and pressed ctrl x then y and then enter I got an error message saying access denied. Anyone know hot  fix this issue im new to coding so like I hv no idea. 

Btw im on mac using jar 4.4.1 and latest ha bridge version.

[Unit]
Description=HA Bridge
Wants=network.target
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/java -jar -Dconfig.file=/home/pi/habridge/data/habridge.config /home/pi/habridge/ha-bridge-3.5.1.jar

[Install]
WantedBy=multi-user.target

**Comment by bwssytems** [comment]
So, if you are writing that into /etc/systemd/system then you need to be root to write to that directory. Use sudo nano to help you with that. Please also google how to use root on linux systems as well. that will help you to know when you need sudo and when you don't.

**Comment by Piers101** [comment]
oh ok thanks
