### ISSUE TITLE
http://[your-ip-address]:80 This link leads my macbook to say unauthorized connection

### ISSUE THREAD

**Issue by Piers101** [bwssytems/ha-bridge#470]
<img width="402" alt="screen shot 2017-02-14 at 10 48 39 pm" src="https://cloud.githubusercontent.com/assets/25770921/22933895/f7867600-f307-11e6-9051-88da452e9cf5.png">

How do I fix this issue?

**Comment by bwssytems** [comment]
So, did your ha-bridge actually start? Please check your logs.

**Comment by Piers101** [comment]
How do I check this (I am new to coding).

**Comment by audiofreak9** [comment]
If you start the ha-bridge with systemctl then enter the following on the command line.
`$ sudo systemctl status habridge.service -l`
It will even give you "LOCATION" information which equates to "http://[your-ip-address]:80"

**Comment by Piers101** [comment]
When I enter this line it asks for my password then I get 
sudo: systemctl: command not found

**Comment by audiofreak9** [comment]
Do you know your root password?
Are you using a Raspberry Pi or other device?
What operating system are you using and variant?

Try: `$ sudo su` then `$ systemctl status habridge.service -l`

**Comment by Piers101** [comment]
I believe I know my root password?
My operating device is mbp running osx sierra.

**Comment by audiofreak9** [comment]
How are you starting the ha-bridge?  Command line, bash script, rc.local, systemctl, etc...

**Comment by audiofreak9** [comment]
BTW, just to be clear the "your-ip-address" means the IP Address of the device the ha-bridge is running on given to it by your router, not your public IP.

**Comment by Piers101** [comment]
I'm trying to start it using a command line and I was using public ip that might be the problem. So should I use the IP address provided by my router?

**Comment by bwssytems** [comment]
So, please search for Mac startup in the closed issues. Also there is a lot you can get through google. Mac OSX requires you to start the bridge with sudo as it wont let you connect to port 80 otherwise. There are some other minor caveats as well.  I do not believe that OSX uses the systemctl construct.

**Comment by Piers101** [comment]
So I need to start bridge using sudo in terminal.

**Comment by Piers101** [comment]
Can some one please post a set of clear instructions on how to make it work on mac OS X 

Thank you

**Comment by bwssytems** [comment]
@Piers101 Are you running OSX server?
