### ISSUE TITLE
myechourl lost colon in URL

### ISSUE THREAD

**Issue by hphde** [bwssytems/ha-bridge#473]
The myechourl should test and/or strip or contain `http://` because currently entering this ends up as `http//alexa.amazon...`

**Comment by bwssytems** [comment]
So, do not put http:// and only the URI into the myechourl field. Like this ```echo.amazon.com/#cards```

**Comment by hphde** [comment]
For me it was obviuos but I guess others may come across this.

Personally I would allow anything and just prepend `http://` in case the urn scheme is missing
