### ISSUE TITLE
ubuntu install guide 

### ISSUE THREAD

**Issue by 1liminal1** [bwssytems/ha-bridge#474]
Hi guys, 

Im looking for an Ubuntu install guide?

Thanks

**Comment by Matt8119** [comment]
Google.com

**Comment by Matt8119** [comment]
YouTube.com

**Comment by 1liminal1** [comment]
HAHA, 

Ive been looking? It all seems to be for the pi

I did find this, 

http://xbmcnut.blogspot.com.au/2016/10/installing-ha-bridge-on-your-raspberry.html

But it didnt work (used the ubuntu user of course, but didnt change anything else)

Feb 17 18:11:36 HA-BRIDGE systemd[1]: Started HA Bridge.
Feb 17 18:11:36 HA-BRIDGE systemd[1]: habridge.service: Main process exited, code=exited, status=203/EXEC
Feb 17 18:11:36 HA-BRIDGE systemd[1]: habridge.service: Unit entered failed state.
Feb 17 18:11:36 HA-BRIDGE systemd[1]: habridge.service: Failed with result 'exit-code'.
lines 1-10/10 (END)

**Comment by 1liminal1** [comment]
shane@HA-BRIDGE:~$ cd /etc/systemd/system
shane@HA-BRIDGE:/etc/systemd/system$ sudo nano habridge.service
shane@HA-BRIDGE:/etc/systemd/system$ cd
shane@HA-BRIDGE:~$ sudo systemctl daemon-reload
shane@HA-BRIDGE:~$ sudo systemctl start habridge.service
shane@HA-BRIDGE:~$ tail -f /var/log/syslog
Feb 17 19:01:16 HA-BRIDGE systemd[1]: snapd.refresh.timer: Adding 36min 12.044499s random time.
Feb 17 19:01:16 HA-BRIDGE systemd[1]: snapd.refresh.timer: Adding 3h 3min 23.922120s random time.
Feb 17 19:01:29 HA-BRIDGE systemd[1]: Reloading.
Feb 17 19:01:29 HA-BRIDGE systemd[1]: snapd.refresh.timer: Adding 3h 27min 53.982282s random time.
Feb 17 19:01:29 HA-BRIDGE systemd[1]: snapd.refresh.timer: Adding 1h 28min 4.957515s random time.
Feb 17 19:01:37 HA-BRIDGE systemd[1]: Started HA Bridge.
Feb 17 19:01:37 HA-BRIDGE java[1729]: Error: Unable to access jarfile /home/pi/habridge/ha-bridge-4.1.4.jar
Feb 17 19:01:37 HA-BRIDGE systemd[1]: habridge.service: Main process exited, code=exited, status=1/FAILURE
Feb 17 19:01:37 HA-BRIDGE systemd[1]: habridge.service: Unit entered failed state.
Feb 17 19:01:37 HA-BRIDGE systemd[1]: habridge.service: Failed with result 'exit-code'.

**Comment by 1liminal1** [comment]
So I guess this, 

Feb 17 19:01:37 HA-BRIDGE java[1729]: Error: Unable to access jarfile /home/pi/habridge/ha-bridge-4.1.4.jar

But I dont know enough about linux to fix that?

**Comment by 1liminal1** [comment]
Feb 17 19:01:37 HA-BRIDGE java[1729]: Error: Unable to access jarfile /home/pi/habridge/ha-bridge-4.1.4.jar

so I fixed the location, but still getting the same error, strange

**Comment by 1liminal1** [comment]
Right got it, its there twice :)
