### ISSUE TITLE
Logitech Harmony Target

### ISSUE THREAD

**Issue by Frenchgrey11** [bwssytems/ha-bridge#475]
Hi,
I must say that UI looks much cleaner and nicer.
What would be really handy for new users is good guide (video? ) what can be put in to the fields.
I was using V 3.5.1 and I decided to install new one, but get in to trouble with logitech harmony.
Some of the devices stopped to work, but after recreating they are OK now
I have about 30 devices , 2 Harmony bridges.
In V3.5.1 with no problem I could successfully set the TARGET IP's to each Logitech bridge hiding unneeded devices.
How hard I'm trying to make it works, both of my remote see all my devices.
All command work with no problem on all devices
I'm using this metod to target as shown below
![image](https://cloud.githubusercontent.com/assets/25729286/23056127/0a6fa91a-f4ea-11e6-8033-db4bb34cd78b.png)

I'm sure I've been doing something wrong. Could you please guide me how to make it .
Thanks

**Comment by smanig** [comment]
Hello,
just click here:

![image](https://cloud.githubusercontent.com/assets/25879700/23103315/b9df161c-f6b9-11e6-860e-c570a5f0a2be.png)

and build a item or button. So it works...

Or not?

you had set up your Harmony there?
![image](https://cloud.githubusercontent.com/assets/25879700/23103322/e0155ee0-f6b9-11e6-8d66-a7cf716fc5c3.png)

**Comment by Frenchgrey11** [comment]
Thanks,
This is not what I'm struggling with. I already tried that. What I'm trying to achieve is masking (making invisible) for some harmony remotes as it was possible in version 3.5.1
to explain in detail: I have 2 remotes call: bedroom and livingroom. From list of 30+ devices I want to make visible for bedroom remote only 2 devices and for livingroom I have 4. 
Other devices should be invisible for both remotes

**Comment by bwssytems** [comment]
@Frenchgrey11 How were you accomplishing this with v3.5.1?

**Comment by Frenchgrey11** [comment]
putting target with ip of desired remote, same as in snippet, but it doesn't work in this version
![image](https://cloud.githubusercontent.com/assets/25729286/23107649/0c32cbe2-f701-11e6-94eb-bd5ea4770761.png)

**Comment by bwssytems** [comment]
Ahh, you were using the feature I changed in 4.1.4 from 3.5.1. That Ip is now the ip filter list in the detailed on/dim/off areas

**Comment by Frenchgrey11** [comment]
New filtering field is fantastic handy improvement, but unfortunately it's doesn't behave as before. Already I tested this option and only difference on Harmony is that filtered commands are not accessible on filtered device, but still all devices are visible to both harmony's. Would be really sweet to have old capability to mask/hide device. I finding this handy as I could neatly filter my Logitec as well as Alexa where now I have bunch of  unneeded names which she from time to time messing up

**Comment by bwssytems** [comment]
Closed to enhancement #526
