### ISSUE TITLE
Any chance to include support for LimitlessLED v6?

### ISSUE THREAD

**Issue by thofra** [bwssytems/ha-bridge#477]
While everything is working fine with sending UDP commands to the old Limitless LED API v5, v6 expects session management. See http://www.limitlessled.com/dev/
So there is no possibility any longer to just send UDP commands. It  would be so great if you could implement basic support for Limitless LEDs.

**Comment by bwssytems** [comment]
Will have to put it in as a future enhancement.

**Comment by Bergasha** [comment]
Any updates on this at all? Would love to have the new controllers work with HA bridge.

**Comment by bwssytems** [comment]
Soon, as this is higher up on the priority list as being older.

**Comment by FloFoer** [comment]
I'm new to limitless/milight and used v5 up until now. What is better with v6? Is there a reason to switch, can it something nice that v5 can't?

**Comment by thofra** [comment]
This is not the right place to talk about the benefits. But shortly, as far I understand the situation... I am not happy about v6 because before it was a very simple communication, now it is complex and session-based. But v6 is required whenever you will receive one of the new Wifi boxes which only will support v6 (it is most of the time even difficult to find this out before - it is all about the firmware running on it). v6 seems to be also required in case you want to use the new RGB-CCT bulbs. I really like them because you can also choose the color temperature of white - so you will not need to choose CW or WW, it is both in one and even everything in between. And you can mix white with shades of colors. A lot of new options. But I am sure, this all would have been possible also with previous versions of the API.

**Comment by thofra** [comment]
@bwssytems 
Maybe you'll want to look into this:
http://codecorner.galanter.net/2017/02/24/full-control-of-your-limitless-ledmilight-v6-bulbs-from-amazon-echo/
The communication is very slow - most of the time it takes 5-10 seconds until the bulbs will react once Alexa told you "Ok". This seems to be related to the session handling. But maybe there are also ways to speed it up. I assume the Android app is using the same interface and is much faster.

**Comment by Bergasha** [comment]
Is this still something you will implement into HA bridge?

**Comment by mfaalk** [comment]
I've set up the bulbs in openhab and controling them by http rest commands from ha bridge.
That way I can turn on(100%), set brightness to some % or turn off(0%) brightness.

**Comment by bwssytems** [comment]
Thanks, will take a look

**Comment by mfaalk** [comment]
Actually my ha bridge just stopped working a few days ago :/
Before I could use an older version, 1.20.9, to set it up as philips hue but doesn't work any more.
My home restarted itself, probably some update that broke it.

**Comment by francescofact** [comment]
So now is going to work this software with Milight hub v6?

**Comment by Rossbro2** [comment]
@bwssytems 
Any updates on supporting the Milight v6 API?

**Comment by bwssytems** [comment]
With the implementation of OpenHAB, Which has MiLight/Limitless connectivity, I will suggest that is the path to implement this.

See https://www.openhab.org
