### ISSUE TITLE
HA Bridge Devices not found by Amazon Echo

### ISSUE THREAD

**Issue by cutzenfriend** [bwssytems/ha-bridge#479]
Hi,

I have everything set up correctly an can use the Webinterface of HA Bridge (Port 80) to control all my devices. My Problem is that my Echo does not find or see those devices.

I do have an original Hue Bridge in my Network is this somehow a problem?

**Comment by smanig** [comment]
Hello,
the "Test" work correctly?
![image](https://cloud.githubusercontent.com/assets/25879700/23102426/56a2cf04-f6a9-11e6-8e07-06087c53c60d.png)

**Comment by cutzenfriend** [comment]
Yes this works without any issues.

**Comment by bwssytems** [comment]
@cutzenfriend You will need to power off your real hue bridge to get the ha-bridge discovered.

**Comment by bwssytems** [comment]
Is this resolved
