### ISSUE TITLE
Minor: ':' recorded as 'NaN' when creating bridge device from Vera scene

### ISSUE THREAD

**Issue by ceefin** [bwssytems/ha-bridge#48]
This has happened a couple times - I try to create a device (from the scene list) tied to executing one scene for on, and another for off. The 'off' scene url ends up having "NaN" instead of ':' between the host name and port for the vera. On-link works fine. When I try to turn off the device, it fails due to this issue.

**Comment by bwssytems** [comment]
I see that myself... will fix in the next release.

**Comment by bwssytems** [comment]
Just replace the NaN with a colon in the edit page and it will work for now.

**Comment by ceefin** [comment]
Thank you!
