### ISSUE TITLE
is it possible to control the devices HA-bridge with a http request?

### ISSUE THREAD

**Issue by smanig** [bwssytems/ha-bridge#480]
Hello,
is it possible to control the devices HA-bridge with a http request?
If is possible, my home automatic (loxone) can control the harmony via ha-bridge. It would be nice ;)

e.g.:    http://192.168.178.xx:xx/api/TV/on

Simon

![image](https://cloud.githubusercontent.com/assets/25879700/23102124/9741496a-f6a3-11e6-9b5d-0b27309eaab5.png)

**Comment by bwssytems** [comment]
Yes, it is in the README here: https://github.com/bwssytems/ha-bridge#hue-rest-api-usage

**Comment by smanig** [comment]
Hello,
thank you. 
Maybe i dont understand:

http//192.168.178.102:81/api/lights/5/state?on=true&bri=200 
doesn´t work.
![image](https://cloud.githubusercontent.com/assets/25879700/23187591/b50c2a20-f88b-11e6-8500-65d8e0317366.png)
Whats is wrong?
![image](https://cloud.githubusercontent.com/assets/25879700/23187703/24a62d86-f88c-11e6-9133-621e21989d35.png)
Thank you very much
Simon

**Comment by bwssytems** [comment]
These are PUT and POST requests that are sent to the server. Browsers only send GET requests. You will need to read up on REST API's as a generic concept.

**Comment by bwssytems** [comment]
Did you figure this out?

**Comment by dinkybluebug** [comment]
I cant get this to work.... I added a webhook in IFTTT that can create webhooks using PUT/POST/GET

my url of http://username.ddns.net:port/api/devices  shows the state of all my devices - so I know my ddns is forwarding my request to the right port.

In the webhook in IFTTT Ive set it up to PUT - { "lights": { "13": { "state": { "on": true, } } } }

I keep getting an error 404 message.

any ideas why?

**Comment by luciust** [comment]
Hey bwssytems, it seems that the question was on how to use GET method to turn on/off/dim things.
Your API is fine as it is but some of us are not only used to Domoticz way of using the JSON API, but more importantly - to use the GET method straing from i.e. smartwatch.

Garmin smartwatches are good example - the can do a GET HTTP but no more. I.E.: https://apps.garmin.com/da-DK/apps/ac9a81ab-a52d-41b3-8c14-940a9de37544;jsessionid=76799D266EE60E770D7A36E96E73B8B5

Would you consider adding the GET as a way to turn on/off things? Would be great!

**Comment by bwssytems** [comment]
Well, the API is emulating the HUE API protocol. I was not thinking about using GET on top of the PUT or POST requests.

**Comment by luciust** [comment]
Sure! I would be kind of silly and against the actual proper way of API, right? But imagine somebody who is just here to use the API in any way possible - his problem is that some other APIs only work with GET. And Domoticz JSON API might be the first API they ever encouted - so it's natural way for them.

And then - oh boy - comes the smartwatches - the aformentioned Garmin apps - they can do GET only (two apps are currently there).

So few folks, me included - would just shout YES if your API would be able to do exactly what Domoticz HSON API gives us - ability to turn on/off with just a GET.
