### ISSUE TITLE
Domoticz Integration fails with Website Protection 

### ISSUE THREAD

**Issue by lonebaggie** [bwssytems/ha-bridge#483]
Domoticz  integration fails if I use username and password on Domoticz

Running  Version: 3.6752 Domoticz
Running 4.1.4 HA Bridge
If I remove username password from both HA-Bridge and Domoticz all works fine

**Comment by bwssytems** [comment]
I will test again. Thanks

**Comment by bwssytems** [comment]
Confirmed, will fix in next release.
