### ISSUE TITLE
Poll for Status changes

### ISSUE THREAD

**Issue by NovaGL** [bwssytems/ha-bridge#484]
Got this working on my Harmony hub which is great, I had one question though.

When I do dimming it doesn't know the state so just does it at 100% I was controlling speakers so obviously this isn't the best.

How do I pass the current status, eg

I have http://localhost/volume
which returns {"volume":16,"mute":false}

That way if the status is changed externally HA-Bridge will know.

**Comment by bwssytems** [comment]
Here ya go: https://github.com/bwssytems/ha-bridge#update-bridge-internal-light-state

**Comment by NovaGL** [comment]
Is that status polling it seems more like a one time update. I want it to poll

**Comment by bwssytems** [comment]
Well, that is a very different question than you wrote. will need to review more.

**Comment by NovaGL** [comment]
Thanks, that's why I changed the title to better reflect the question

**Comment by tuicemen** [comment]
I think you might  need to use what bwssystems first pointed to for when the device status is changed outside the bridge then this to poll the bridge https://github.com/bwssytems/ha-bridge#get-light-attributes-and-state

**Comment by audiofreak9** [comment]
@NovaGL I wrote a python script to poll my X10 device states and update the ha-bridge.  It's not exactly what you would need, since it's for X10 devices, but it may inspire you.  I run it on a 15 minute cron.  It's available [here](https://github.com/audiofreak9/ha-bridge-X10-device-state-update).

**Comment by tuicemen** [comment]
I do a simular routine for X10 devices watching their on/off and dim status.
Based on the dim status I know to send a bri or dim command

**Comment by bwssytems** [comment]
I am going to leave this to external entities to call the ha-bridge update status.

**Comment by NovaGL** [comment]
How would I do that with Harmony. The remote never knows the correct level. If Ha Bridge could poll it would make things much easier

**Comment by bwssytems** [comment]
There is no command for the Harmony Hub api to get the device levels.

**Comment by NovaGL** [comment]
No way to implement it? So a harmony hub never knows the dim level of a normal hue light?

**Comment by bwssytems** [comment]
It may internally, but the API has no way to get so I cannot get that info.
