### ISSUE TITLE
Searching syntax for mqtt dimming

### ISSUE THREAD

**Issue by micropet** [bwssytems/ha-bridge#485]
I use the following syntax to turn on an item via mqtt:
[{"clientId":"habridge","topic":"/test","message":"100"}]

Can you tell me the syntax for the dimming?

**Comment by bwssytems** [comment]
Here ya go: https://github.com/bwssytems/ha-bridge#value-passing-controls

**Comment by micropet** [comment]
Thank you. I do not understand it, unfortunately.
Can you supplement my set for dimming?

[{"ClientId": "habridge", "topic": "/ test", "message": "100"}]

**Comment by bwssytems** [comment]
So, replace the number you want to control with ${intensity,percent} That is what the documentation tries to explain. So in your case it is "100" should be "${intensity.percent}"

**Comment by micropet** [comment]
Wau, that's easy, thank you.

You should show some examples on your site. This helps people like me and we do not need stupid questions.

**Comment by bwssytems** [comment]
There are examples.... If I put every permutation of an example then it would be specific....
