### ISSUE TITLE
disregard...

### ISSUE THREAD

**Issue by Corremans** [bwssytems/ha-bridge#486]
ups ...... disregard.....

**Comment by Matt8119** [comment]
This must be installed on a Linux to run properly. Like in a synology server, Raspberry Pi, or virtual machine running Linux

**Comment by Matt8119** [comment]
You need to properly read the readme file.

**Comment by Corremans** [comment]
@ Matt8119.

should be working on a windows 10 machine as well.
Auto correct changed localhost 80 to localhost 8080  ......  that was the problem.

thanks, 
Cor

**Comment by audiofreak9** [comment]
Just to be clear, this will run on any machine the can run java 8 JDK  including Windows.

Closing as solved.
