### ISSUE TITLE
Bulk Add not working?

### ISSUE THREAD

**Issue by seanford** [bwssytems/ha-bridge#488]
I seem to remember in an early version being able to use the Bulk Add feature and the checkboxes to simply add several Vera devices at once.

In 4.1.4, when I do this, it seems like the dvices I check are combined into one, with the MapID being a composite of the two devices I added.  eg. 102-345

Is this the new desired behavior?  I've recently switched from the Docker version that self-upgraded to a Raspberry Pi and am starting my configuration from scratch and that seems to be my only issue.  Very time-consuming to add devices one by one with the interface refreshing each time.

**Comment by bwssytems** [comment]
I will take a look at that. I re-factored the bulk add code to be the same for all bulk add operations. May have missed something.

Also, you should have been able to take the device.db and habridge.conf from your docker install and use it in your own setup.

**Comment by seanford** [comment]
Thanks. and I know, but there were so many changes since I last configured I kind of wanted to re-learn what it can do.

Also, any plans for an auto-updating option?  Thought that was one of the best features of the Docker version. (Or should I put this in another thread so it can be marked as an enhancement request?)

**Comment by bwssytems** [comment]
The docker item is handled by another developer altogether on another github page.
