### ISSUE TITLE
Only show Philips Hue lights in Alexa that I've added in HA Bridge?

### ISSUE THREAD

**Issue by jonohunt** [bwssytems/ha-bridge#490]
I'm using HA Bridge to control my Philips Hue lights (among other devices) via Alexa. I don't have the 'proper' Philips Hue Alexa skill enabled, as I only want to control devices I've manually added though HA Bridge.

But it still shows **ALL** of my Hue lights in the Alexa app. Could the Echo be automatically discovering all of my Hue lights, even though I don't have the Philips Hue skill enabled (therefore not a problem with HA Bridge), or could it be that HA Bridge is making all of my Philips Hue lights available to Alexa, not just those that I've manually added to HA Bridge?

**Comment by bwssytems** [comment]
The echo is finding all of your hue bulbs as well as the bridge when you do a discover. Unplug your real hue hub when you do a discover. There is no communication to know this is the case.

**Comment by jonohunt** [comment]
Ah, thanks a lot for the info!

And good to know there's no problem with HA Bridge 👍🏼
