### ISSUE TITLE
Cannot Configure HA-Bridge to Talk to Kodi

### ISSUE THREAD

**Issue by hernandito** [bwssytems/ha-bridge#494]
Hello, 

I want to configure a device that basically sends a request to my **Kodi** machine. In this example, if I enter the URL below into any web browser, in my Kodi machine, it launches an Artwork Downloader (add-on) search:

`http://myusername:mypassword@192.168.0.103:88/jsonrpc?request={%20%22jsonrpc%22:%20%222.0%22,%20%22id%22:%200,%20%22method%22:%20%22Addons.ExecuteAddon%22,%22params%22:%20{%22addonid%22:%20%22script.artwork.downloader%22,%20%22params%22:%20{%22mediatype%22:%20%22movie%22}}}`

For the life of me, I cannot figure out how to configure HA-Bridge. Please see screencap below:

![5e610d1621727ec61a647de2268bf274d6e2fdbd](https://cloud.githubusercontent.com/assets/787317/23301903/3ff2e384-fa5a-11e6-8647-d072ba1e6cde.png)

After adding this, I was able to detect the device name in my Alexa app - but obviously it did not work.

I tried following the guide here:

[HA-Bridge Kodi](https://github.com/bwssytems/ha-bridge/issues/193)

But I still cannot get it to work even with the code for the "Volume" in the guide. I have tried entering the URL in various places of the HA-Briddge UI and either; I get an OK and nothing happens; or I get the error: 

> Request Error, Pleae look in your habridge log: error {"type":"3","address":"/lights/4","description":"Could not find url.","method_name":"/lights/4

Can some kind soul please point me in the right direction?? 

On a similar note, I want to be able to also send a command that executes a php and/or sh script on my server. my server has an internal ip of **192.168.1.200** (HA-Bridge runs in a Docker on this server), I would want to execute a command like:

` php /config/www/script.php`

and/or

`sh /home/script.sh`

Unfortunately I could not find anything that provided examples that worked. Any help would go a long way in creating about a dozen commands I can control with Alexa.

Any advice is greatly appreciated.

Thanks,

H.

**Comment by bwssytems** [comment]
So, remove the %20 items as those are not needed within the json. Then change the %22 to " in the editor.

**Comment by hernandito** [comment]
Thank you for replying. My url that I paste in the UI looks now like:

`http://unsername:password@192.168.0.133:80/jsonrpc?request={"jsonrpc":"2.0","id":0,"method":"Addons.ExecuteAddon","params":{"addonid":"script.artwork.downloader","params":{"mediatype":"movie"}}}`

![image](https://cloud.githubusercontent.com/assets/787317/23318004/bbc5c4ce-fa9e-11e6-8d1e-265acbe89546.png)

When I Test the On switch, I get the green notification with the message:

> Request Executed: success [{"success":{"/lights/2/state/on":true}}]

But nothing happens on my Kodi machine. Are the other setting correct per my screen capture above?

Again many thanks for your help. I know I am close.

H.

**Comment by hernandito** [comment]
I figured it out. Per the link tutorial above, the ONLY part to copy from the json part of the string, which is the long part between the curly brackets { } is what needs to be copied into the json encode/decode web link.

I hope this helps others. It only took me 2 weeks to finally figure it out by finally carefully reading the directions.

Thanks for this awesome software!!

Cherrs,

H.
