### ISSUE TITLE
Using Escape Character

### ISSUE THREAD

**Issue by craiglt** [bwssytems/ha-bridge#495]
I have created bridge device with the type of TCP device and a target item of:
 tcp://192.168.0.4:2500/task 36 \n

The call does not work.  The entry in the device.db file looks like this:
"onUrl":"[{\"item\":\"tcp://192.168.0.4:2500/task 36 \\\\n\",\"type\":\"tcpDevice\"}]"

If I manually edit the device.db file to look like this:
"onUrl":"[{\"item\":\"tcp://192.168.0.4:2500/task 36 \\n\",\"type\":\"tcpDevice\"}]"
then the call works.

Am I making a mistake when I first create the bridge device?

**Comment by bwssytems** [comment]
I need to rework encoding

**Comment by craiglt** [comment]
Thanks, but it looks like my original posting does not appear exactly as I entered it.

In the devices.db file, the call that does not work ends with:
task 36 backslash backslash backslash backslash n backslash

The call that does work ends with:
task 36 backslash backslash n backslash

**Comment by bwssytems** [comment]
This has been added to the next release
