### ISSUE TITLE
Multiple Harmony Support

### ISSUE THREAD

**Issue by rafale77** [bwssytems/ha-bridge#5]
Request the addition of up to 5 Harmony Hub support on the bridge.

**Comment by bwssytems** [comment]
a question, when you have more than one harmony hub, is it a different login?

**Comment by rafale77** [comment]
No it isn't. One same Harmony account can have multiple hubs.

**Comment by bwssytems** [comment]
Great! That will make it easier so as to supply only multiple hub ip's and not any other login info.
