### ISSUE TITLE
POST/PUT Support - format question

### ISSUE THREAD

**Issue by willplaice** [bwssytems/ha-bridge#50]
Hi there - I guess i am unable to follow the example -so this isn't an issue, just a question, of you would be so kind ?

I'm trying to pass the following to my AV Amp....

I've pasted what i think should go where and i just get "error on calling url..." as the error ?

an example of the format:  http://www.openremote.org/display/forums/Yamaha+RX-A+ip+control.+(Solved)

from wireshark 
http://192.168.1.119:80/YamahaRemoteControl/ctrl

and
HTML Form URL Encoded: application/x-www-form-urlencoded
"PUT"><Main_Zone><Volume><Lvl><Val>Down</Val><Exp></Exp><Unit></Unit></Lvl></Volume></Main_Zone></YAMAHA_AV>

[yamaha_post.pcapng.zip](https://github.com/bwssytems/ha-bridge/files/138662/yamaha_post.pcapng.zip)

**Comment by bwssytems** [comment]
So, You are almost there, I think....

So use the custom method as you said with the URL you need.

Then you have to select 'PUT' as the verb

The URL encoding should be ok.

Put the XML data in the examples in the body of on or off depending on what you need.

Hope that gives some direction.

**Comment by willplaice** [comment]
Hi

Im getting some sort of preamble in the command ?  best way I can explain is - capture from ha-bridge on left, and from the call via the web app on the left (which works) -

any ideas? 


![traces](https://cloud.githubusercontent.com/assets/17142986/13203465/c569bdc0-d8b0-11e5-9ea6-0017cf1494a6.png)

**Comment by bwssytems** [comment]
Ahh, I see now. It is a "POST" command, even thought PUT is in the body...misleading.

So it is a POST command for the http verb and the on or off body is everything after the the quotes in the Form item capture..... "Form item:" "<YAMAHA_AV cmd" " = " ""PUT"><Main_Zone>......

**Comment by willplaice** [comment]
ok so the following in the body ?

"<YAMAHA_AV cmd" = ""PUT"><Main_Zone><Volume><Lvl><Val>Down</Val><Exp></Exp><Unit></Unit></Lvl></Volume></Main_Zone></YAMAHA_AV>”


?

I’ve grabbed 1.4.0 and here’s the comparison now:


note I still have additional characters being sent in the actual message…

<img width="1920" alt="pastedgraphic-1" src="https://cloud.githubusercontent.com/assets/17142986/13203974/a12025fc-d8bb-11e5-8a68-d978451c825a.png">

**Comment by bwssytems** [comment]
You actually need to include a "Form item:" in the beginning as well just like the first one you showed. The wireshark output puts the field name there and then puts the text it received in quotes and that contained "Form item:".

**Comment by willplaice** [comment]
ok..



here’s the device config - and referring to the screen capture, can you see the extra characters in the left hand side, before the “POST”   i’m guessing this is my problem ?



"name":"avDown","deviceType":"custom","targetDevice":"Encapsulated","offUrl":"","onUrl":"http://192.168.1.119:80/YamahaRemoteControl/ctrl","httpVerb":"POST","contentType":"application/x-www-form-urlencoded","contentBody":"\"Form item:\" \"PUT\"\u003e\u003cMain_Zone\u003e\u003cVolume\u003e\u003cLvl\u003e\u003cVal\u003eDown\u003c/Val\u003e\u003cExp\u003e\u003c/Exp\u003e\u003cUnit\u003e\u003c/Unit\u003e\u003c/Lvl\u003e\u003c/Volume\u003e\u003c/Main_Zone\u003e\u003c/YAMAHA_AV\u003e"},{"id":"1584565507”,

**Comment by bwssytems** [comment]
I'm not sure what you see as this looks good to me?

**Comment by willplaice** [comment]
see attached - it's sending the whole string in the key field and nothing in value ?


![missing value](https://cloud.githubusercontent.com/assets/17142986/13205052/46878548-d8d6-11e5-9e61-621503e6342b.png)

**Comment by bwssytems** [comment]
I was reading the remote app info and I am now very confused. Are these strings actually sent to the Yamaha Receiver or are they the config for the remote app?

**Comment by willplaice** [comment]
ok, and again many thanks for looking at this..


(please look at the last screen capture)

I have a wireshark trace of a working http post message that i want to copy into ha-bridge (the one on the right is the working one)

on the left is the output from ha-bridge with the device config below, as you can see there is a difference.


the working xml has values for key and vlaue

what i am sending via ha-bridge has all the detail in the key field and a blank value field.

i am guessing i’ve not put a coma or quote in the right place.




i hope that’s a clear explanation of the problem I’m having.

**Comment by bwssytems** [comment]
Ok, the confusing thing is the decoding from wireshark. Look at the hex dump below and that is the key: I copy and pasted, please check.

"name":"avDown","deviceType":"custom","targetDevice":"Encapsulated","offUrl":"","onUrl":"http://192.168.1.119:80/YamahaRemoteControl/ctrl","httpVerb":"POST","contentType":"application/x-www-form-urlencoded","contentBody":"<YAMAHA_AV cmd=\"PUT\"><Main_Zone><Volume><Lvl><Val>Down<Val><Exp></Exp><Unit></Unit></Lvl></Volume></Main_Zone></YAMAHA_AV>"}

**Comment by bwssytems** [comment]
Ok the markdown languag screwed that up... Just follow the text in the dump.

**Comment by bwssytems** [comment]
Aha, used the markdown language to fix the text above.

**Comment by willplaice** [comment]
ok so i now see that when i paste strings into the content body on field, i get the extra characters added that i'm seeing being sent.... I'll edit the device.db file and see if i can get what i want to to send there.

**Comment by dale3h** [comment]
I was able to get this working from the HA Bridge web UI alone. When I compared the data I captured to the data from this topic, I noticed that there was a / missing in the closing tag for Val.

Just to confirm, "Form item:" is not required in the "Content Body On"

Here is the body that worked for me: `<YAMAHA_AV cmd="PUT"><Main_Zone><Volume><Lvl><Val>Down</Val><Exp></Exp><Unit></Unit></Lvl></Volume></Main_Zone></YAMAHA_AV>`

Here is the config from device.db: `{"id":"1554843008","name":"avDown","deviceType":"custom","targetDevice":"Encapsulated","onUrl":"http://192.168.1.100:80/YamahaRemoteControl/ctrl","httpVerb":"POST","contentType":"application/x-www-form-urlencoded","contentBody":"\u003cYAMAHA_AV cmd\u003d\"PUT\"\u003e\u003cMain_Zone\u003e\u003cVolume\u003e\u003cLvl\u003e\u003cVal\u003eDown\u003c/Val\u003e\u003cExp\u003e\u003c/Exp\u003e\u003cUnit\u003e\u003c/Unit\u003e\u003c/Lvl\u003e\u003c/Volume\u003e\u003c/Main_Zone\u003e\u003c/YAMAHA_AV\u003e"}`

**Comment by bwssytems** [comment]
Is this working now?

**Comment by willplaice** [comment]
Hi.  Yep.  Seems pasting into the web gui causes formatting issues at least for me.  So I'm having to edit the db file.  But it works !   Thanks for the development and the support !

**Comment by dale3h** [comment]
Just to prevent any confusion for future users that come across this post: when pasting into the **web UI**, make sure that you're using < and >. In the **config file** is where you'll want to use \u003c and \u003e.
