### ISSUE TITLE
Dim command not firing for Harmony activity

### ISSUE THREAD

**Issue by cipher2k** [bwssytems/ha-bridge#500]
I have the following harmony command configured:

![img](https://cloud.githubusercontent.com/assets/20582892/23333946/1e3c05d6-fb95-11e6-851e-1530f568ec1a.png)

But the dim command does not fire when I tell Alexa to dim this device to X. Could this be made possible somehow?

What I basically would like to do with the dim command is to set a sleeptimer to X minutes. Since the harmony API does not support it, I have written a workaround that calls the PowerOff command after X minutes.

And BTW: thanks for this very usefull piece of software! Sorry for bothering you with issues/questions here. ;)

**Comment by bwssytems** [comment]
You need to set the dim command to be of type HTTP Device, it is trying to default to Harmony based on the overall type.

**Comment by cipher2k** [comment]
Cool, it works! Thanks!
