### ISSUE TITLE
Echo Dot Does Not Discover Any Devices

### ISSUE THREAD

**Issue by dtan98** [bwssytems/ha-bridge#502]
Hello,

I have the same problem as Tiramisos mentioned in issue #489. I have the HA Bridge up and running on a Rasp Pi and test shows it is working properly with switching on and off. But Echo Dot is not able to discover any devices.

The HA Bridge log with UPNP trace switched on and upon restart is as follow:

02-25-2017 23:50:44.259	INFO	HA Bridge (v4.2.0) starting....	com.bwssystems.HABridge.HABridge
02-25-2017 23:50:44.306	INFO	reading from config file: /home/pi/habridge/data/habridge.config	com.bwssystems.HABridge.BridgeSettings
02-25-2017 23:50:45.226	WARN	The upnp config address, 172.17.0.1, does not match any known IP's on this host.	com.bwssystems.HABridge.BridgeSettings
02-25-2017 23:50:45.229	INFO	HA Bridge initializing....	com.bwssystems.HABridge.HABridge
02-25-2017 23:50:45.434	INFO	System control service started....	com.bwssystems.HABridge.SystemControl
02-25-2017 23:50:46.291	INFO	Initializing UDP response Socket...	com.bwssystems.HABridge.util.UDPDatagramSender
02-25-2017 23:50:46.463	INFO	UDP response Seocket initialized to: 50000	com.bwssystems.HABridge.util.UDPDatagramSender
02-25-2017 23:50:46.536	INFO	Harmony Home created. No Harmony devices configured.	com.bwssystems.HABridge.plugins.harmony.HarmonyHome
02-25-2017 23:50:46.577	INFO	Nest Home created. No Nest configured.	com.bwssystems.HABridge.plugins.NestBridge.NestHome
02-25-2017 23:50:46.585	INFO	Hue passthru Home created. No Hue passtrhu systems configured.	com.bwssystems.HABridge.plugins.hue.HueHome
02-25-2017 23:50:46.588	INFO	HAL Home created. No HAL devices configured.	com.bwssystems.HABridge.plugins.hal.HalHome
02-25-2017 23:50:46.604	INFO	MQTT Home created. No MQTT Clients configured.	com.bwssystems.HABridge.plugins.mqtt.MQTTHome
02-25-2017 23:50:46.610	INFO	HomeAssistant Home created. No HomeAssistants configured.	com.bwssystems.HABridge.plugins.hass.HassHome
02-25-2017 23:50:46.615	INFO	Command Home for system program execution created.	com.bwssystems.HABridge.plugins.exec.CommandHome
02-25-2017 23:50:47.636	INFO	== Spark has ignited ...	spark.webserver.JettySparkServer
02-25-2017 23:50:47.662	INFO	>> Listening on 0.0.0.0:80	spark.webserver.JettySparkServer
02-25-2017 23:50:48.791	INFO	Http Home created.	com.bwssystems.HABridge.plugins.http.HTTPHome
02-25-2017 23:50:48.794	INFO	TCP Home created.	com.bwssystems.HABridge.plugins.tcp.TCPHome
02-25-2017 23:50:48.796	INFO	UDP Home created.	com.bwssystems.HABridge.plugins.udp.UDPHome
02-25-2017 23:50:48.800	INFO	Vera Home created. No Veras configured.	com.bwssystems.HABridge.plugins.vera.VeraHome
02-25-2017 23:50:48.803	INFO	Domoticz Home created. No Domoticz devices configured.	com.bwssystems.HABridge.plugins.domoticz.DomoticzHome
02-25-2017 23:50:48.809	INFO	LifxDevice Home created. No LifxDevices configured.	com.bwssystems.HABridge.plugins.lifx.LifxHome
02-25-2017 23:50:48.888	INFO	HABridge device management service started....	com.bwssystems.HABridge.devicemanagmeent.DeviceResource
02-25-2017 23:50:48.934	INFO	Hue description service started....	com.bwssystems.HABridge.upnp.UpnpSettingsResource
02-25-2017 23:50:48.951	INFO	Hue emulator service started....	com.bwssystems.HABridge.hue.HueMulator
02-25-2017 23:50:49.012	INFO	UPNP Discovery Listener starting....	com.bwssystems.HABridge.upnp.UpnpListener
02-25-2017 23:50:49.015	INFO	Traceupnp: eth0 ... has addr /fe80:0:0:0:f673:6aa8:8615:36a%eth0	com.bwssystems.HABridge.upnp.UpnpListener
02-25-2017 23:50:49.018	INFO	Traceupnp: wlan0 ... has addr /fe80:0:0:0:2fc6:6c8e:c3c0:f610%wlan0	com.bwssystems.HABridge.upnp.UpnpListener
02-25-2017 23:50:49.019	INFO	Traceupnp: wlan0 ... has addr /192.168.1.19	com.bwssystems.HABridge.upnp.UpnpListener
02-25-2017 23:50:49.020	INFO	Traceupnp: Adding wlan0 to our interface set	com.bwssystems.HABridge.upnp.UpnpListener
02-25-2017 23:50:49.021	INFO	Traceupnp: lo ... has addr /0:0:0:0:0:0:0:1%lo	com.bwssystems.HABridge.upnp.UpnpListener
02-25-2017 23:50:49.022	INFO	Traceupnp: lo ... has addr /127.0.0.1	com.bwssystems.HABridge.upnp.UpnpListener
02-25-2017 23:50:49.022	INFO	Traceupnp: Adding lo to our interface set	com.bwssystems.HABridge.upnp.UpnpListener
02-25-2017 23:50:49.022	INFO	UPNP Discovery Listener running and ready....	com.bwssystems.HABridge.upnp.UpnpListener
02-25-2017 23:51:26.654	INFO	Traceupnp: sendUpnpNotify notifyTemplate is <<<NOTIFY * HTTP/1.1
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 LOCATION: http://172.17.0.1:80/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 NTS: ssdp:alive
 hue-bridgeid: 000088FFFE00BBEE
 NT: uuid:2f402f80-da50-11e1-9b23-00008800bbee
 USN: uuid:2f402f80-da50-11e1-9b23-00008800bbee
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener
02-25-2017 23:51:26.839	INFO	Traceupnp: isSSDPDiscovery found message to be an M-SEARCH message.	com.bwssystems.HABridge.upnp.UpnpListener
02-25-2017 23:51:26.840	INFO	Traceupnp: isSSDPDiscovery found message to be valid under strict rules - strict: true	com.bwssystems.HABridge.upnp.UpnpListener
02-25-2017 23:51:26.841	INFO	Traceupnp: SSDP packet from 192.168.1.21:50000, body: M-SEARCH * HTTP/1.1
 HOST: 239.255.255.250:1900
 MAN: "ssdp:discover"
 MX: 15
 ST: urn:schemas-upnp-org:device:basic:1
 
	com.bwssystems.HABridge.upnp.UpnpListener
02-25-2017 23:51:26.843	INFO	Traceupnp: sendUpnpResponse discovery responseTemplate1 is <<<HTTP/1.1 200 OK
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 EXT:
 LOCATION: http://172.17.0.1:80/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 hue-bridgeid: 000088FFFE00BBEE
 ST: upnp:rootdevice
 USN: uuid:2f402f80-da50-11e1-9b23-00008800bbee::upnp:rootdevice
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener
02-25-2017 23:51:26.845	INFO	Traceupnp: sendUpnpResponse discovery responseTemplate2 is <<<HTTP/1.1 200 OK
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 EXT:
 LOCATION: http://172.17.0.1:80/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 hue-bridgeid: 000088FFFE00BBEE
 ST: uuid:2f402f80-da50-11e1-9b23-00008800bbee
 USN: uuid:2f402f80-da50-11e1-9b23-00008800bbee
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener
02-25-2017 23:51:26.847	INFO	Traceupnp: sendUpnpResponse discovery responseTemplate3 is <<<HTTP/1.1 200 OK
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 EXT:
 LOCATION: http://172.17.0.1:80/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 hue-bridgeid: 000088FFFE00BBEE
 ST: urn:schemas-upnp-org:device:basic:1
 USN: uuid:2f402f80-da50-11e1-9b23-00008800bbee
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener
02-25-2017 23:51:26.943	INFO	Traceupnp: isSSDPDiscovery found message to be an M-SEARCH message.	com.bwssystems.HABridge.upnp.UpnpListener
02-25-2017 23:51:26.944	INFO	Traceupnp: isSSDPDiscovery found message to be valid under strict rules - strict: true	com.bwssystems.HABridge.upnp.UpnpListener
02-25-2017 23:51:26.944	INFO	Traceupnp: SSDP packet from 192.168.1.21:50000, body: M-SEARCH * HTTP/1.1
 HOST: 239.255.255.250:1900
 MAN: "ssdp:discover"
 MX: 15
 ST: urn:schemas-upnp-org:device:basic:1
 
	com.bwssystems.HABridge.upnp.UpnpListener
02-25-2017 23:51:26.945	INFO	Traceupnp: sendUpnpResponse discovery responseTemplate1 is <<<HTTP/1.1 200 OK
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 EXT:
 LOCATION: http://172.17.0.1:80/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 hue-bridgeid: 000088FFFE00BBEE
 ST: upnp:rootdevice
 USN: uuid:2f402f80-da50-11e1-9b23-00008800bbee::upnp:rootdevice
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener
02-25-2017 23:51:26.946	INFO	Traceupnp: sendUpnpResponse discovery responseTemplate2 is <<<HTTP/1.1 200 OK
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 EXT:
 LOCATION: http://172.17.0.1:80/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 hue-bridgeid: 000088FFFE00BBEE
 ST: uuid:2f402f80-da50-11e1-9b23-00008800bbee
 USN: uuid:2f402f80-da50-11e1-9b23-00008800bbee
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener
02-25-2017 23:51:26.947	INFO	Traceupnp: sendUpnpResponse discovery responseTemplate3 is <<<HTTP/1.1 200 OK
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 EXT:
 LOCATION: http://172.17.0.1:80/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 hue-bridgeid: 000088FFFE00BBEE
 ST: urn:schemas-upnp-org:device:basic:1
 USN: uuid:2f402f80-da50-11e1-9b23-00008800bbee
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener
02-25-2017 23:51:46.970	INFO	Traceupnp: sendUpnpNotify notifyTemplate is <<<NOTIFY * HTTP/1.1
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 LOCATION: http://172.17.0.1:80/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 NTS: ssdp:alive
 hue-bridgeid: 000088FFFE00BBEE
 NT: uuid:2f402f80-da50-11e1-9b23-00008800bbee
 USN: uuid:2f402f80-da50-11e1-9b23-00008800bbee
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener
02-25-2017 23:51:46.973	INFO	Traceupnp: sendUpnpNotify notifyTemplate is <<<NOTIFY * HTTP/1.1
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 LOCATION: http://172.17.0.1:80/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 NTS: ssdp:alive
 hue-bridgeid: 000088FFFE00BBEE
 NT: uuid:2f402f80-da50-11e1-9b23-00008800bbee
 USN: uuid:2f402f80-da50-11e1-9b23-00008800bbee
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener

**Comment by bwssytems** [comment]
so, are you just posting because it failed or that you read your log and have tried to fix it and there is something else.....

**Comment by dtan98** [comment]
Sorry, did not realize the log file is a mile long until I have posted it. Anyhow, I managed to resolve the problem. UPNP was not enabled in my router.
