### ISSUE TITLE
Cant Execute Shell Script

### ISSUE THREAD

**Issue by GenerationX2k6** [bwssytems/ha-bridge#505]
Sorry for my English. Im From Germany and i try my best that you understand me :D 

In want to control my Wireless 433 MHZ Socket with WiringPi. When i use the Sh Command on My Raspberry it works without issues. in HABridge 2.5.1 i put in "HTML On" the path to the script and it works.
in the Other Versions it wont work and i dont know why. Everything i Get is a Warning when i try to test the "Device"
![unbenannt](https://cloud.githubusercontent.com/assets/26059407/23358210/5abf40c0-fce1-11e6-9b97-577b31eef1aa.png)
![unbenannt2](https://cloud.githubusercontent.com/assets/26059407/23358376/0572bcc2-fce2-11e6-9d65-0ad3df2d65ac.png)

Everything is on Execute Script/Program

Thanks for Help!

**Comment by bwssytems** [comment]
Interesting as this is very straight forward call to your script. Could you post the log file output as there is more information in there,

**Comment by GenerationX2k6** [comment]
can you tell me were the log is?

**Comment by GenerationX2k6** [comment]
so i downgrade to version 3.5.1 and all works perfectly.. i dont know why it happens in all Versions with Item On and Item Off..
All Versions With URL on, DIM On, URL Off works perfectly and i can add my sh scripts like /home/pi/ so on.

**Comment by bwssytems** [comment]
@GenerationX2k6 I will need you to tun on debug for com.bwssystems.HABridge.plugins.exec and post your output. Thanks

**Comment by bwssytems** [comment]
So, somehow, your script is trying to be executed as an HTTP command. Please post your device.db

**Comment by GenerationX2k6** [comment]
Which one? In data/ Or /home/pi/habridge/data?

**Comment by bwssytems** [comment]
Where ever your startup says the device.db is located. Look at each file to see which one is more complete and that will tell you.

**Comment by GenerationX2k6** [comment]
OK thanks, i will post it when im at home and i hope you can help me

**Comment by GenerationX2k6** [comment]
So, i found the Real device.db.
Its in data/device.db

`[{"id":"1","uniqueid":"00:17:88:5E:D3:01-01","name":"Regal","mapType":"cmdDevice","deviceType":"exec","targetDevice":"Encapsulated","offUrl":"/home/pi/steckdosen/Regalaus.sh","onUrl":"/home/pi/steckdosen/Regalan.sh"},{"id":"2","uniqueid":"00:17:88:5E:D3:02-02","name":"Receiver","deviceType":"exec","targetDevice":"Encapsulated","offUrl":"/home/pi/receiver/receiveraus.sh","onUrl":"/home/pi/receiver/receiveran.sh"},{"id":"3","uniqueid":"00:17:88:5E:D3:03-03","name":"Receiver Lautlos","deviceType":"exec","targetDevice":"Encapsulated","offUrl":"/home/pi/receiver/receivermute.sh","onUrl":"/home/pi/receiver/receivermute.sh"},{"id":"4","uniqueid":"00:17:88:5E:D3:04-04","name":"Fernseher Schlafzimmer","deviceType":"exec","targetDevice":"Encapsulated","offUrl":"home/pi/steckdosen/FernseherSchlafzimmeraus.sh","onUrl":"home/pi/steckdosen/FernseherSchlafzimmeran.sh"},{"id":"5","uniqueid":"00:17:88:5E:D3:05-05","name":"Fernseher Wohnzimmer","deviceType":"exec","targetDevice":"Encapsulated","offUrl":"/home/pi/steckdosen/FernseherWohnzimmeraus.sh","onUrl":"/home/pi/steckdosen/FernseherWohnzimmeran.sh"},{"id":"6","uniqueid":"00:17:88:5E:D3:06-06","name":"Receiver Standby","deviceType":"exec","targetDevice":"Encapsulated","onUrl":"/home/pi/receiver/receiverstandby.sh"},{"id":"7","uniqueid":"00:17:88:5E:D3:07-07","name":"Test Device","deviceType":"exec","targetDevice":"Encapsulated"}]`

**Comment by bwssytems** [comment]
In 4.2.1 you need to make sure you hit the green add button on the right of the item before saving.

**Comment by bwssytems** [comment]
Also, make sure you select Execute/Sehll/Command for the type

**Comment by GenerationX2k6** [comment]
oh man... ok this was my fault... i thought i would be saved if I press on "Add Bridge Device"... Now it Works!! :D Thanks for all!

**Comment by Elmente85** [comment]
@noovib Hi, hast du deine Skripte mittlerweile zum Laufen bekommen? Ich hab dasselbe Problem. Auch mit Libreelec, docker und ha-bridge. Über Putty(SSH) kann ich die Skripte korrekt ausführen, aber über ha-bridge funktioniert kein Skript. Es wird lediglich der grüne hinweis "request executed" angezeigt, aber nichts weiter passiert :-(. Ärgerlich, da ich vor einem halben Jahr bereits alles am Laufen hatte und auch die Skripte wunderbar funktioniert haben, leider ist mir nun die SD-Karte abgeraucht, und beim Erneuten einrichten mache ich scheinbar irgendwas falsch :-(. Danke
