### ISSUE TITLE
HA-Bridge 4.2.0 - NullPointer on DomoticzHome

### ISSUE THREAD

**Issue by kaaspad** [bwssytems/ha-bridge#507]
Hi I just installed this on RPi that has domoticz beta 3.6800 on it. HA-Bridge starts up correctly, but if I try to do anything on the bridge settings pages (which then calls a re-initialize) I get the following in the log:

`2017-02-27 21:19:24,074 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener - ended, restart found
2017-02-27 21:19:24,075 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.2.0) reinitialization requessted....
Exception in thread "main" java.lang.NullPointerException
	at com.bwssystems.HABridge.plugins.domoticz.DomoticzHome.closeHome(DomoticzHome.java:164)
	at com.bwssystems.HABridge.HomeManager.closeHomes(HomeManager.java:107)
	at com.bwssystems.HABridge.HABridge.main(HABridge.java:88)`

any ideas?

when I try the identical on 4.14 it works fine.

**Comment by bwssytems** [comment]
Need to check if it is valid before closing.

**Comment by bwssytems** [comment]
Until this gets fixed, you'll have to restart the bridge from the system.

**Comment by kaaspad** [comment]
what do you mean by "restart the bridge from the system"? currently regardless if I add a domoticz server I still get the memory release issue - the moment the bridge initializes that error appears. Should I just downgrade to 4.1.4 for now?

**Comment by bwssytems** [comment]
So, once you have a domoticz address in the system, when you start the system again from the command line or startup configuration, it will not do that again. IT is a bug when there is no domoticz configured or for the first time that a domoticz is being configured.

**Comment by bwssytems** [comment]
If you want a beta that has this fixed: http://bwssystems.com/files/ha-bridge-4.2.0a.jar
