### ISSUE TITLE
Echo does not find any devices

### ISSUE THREAD

**Issue by doucit** [bwssytems/ha-bridge#509]
Hello bwssystems, hello guys....

Installed ha-bridge on raspbian on a PI and added a test device which executes custom scripts. This is working perfectly. Just my Echo does not find any devices...
I did research and found a lot to try... nothing worked for me and iam about to cry, seriously.

My Modem/Router does not support UPNP so i connected my old router behind, which supports UPNP.

(sorry for the tons of " - ", only spaces will be ignored :/ )
Modem/Router 1(no UPNP)
--------- |------------- |
--------- |-------- Other stuff
---Router 2(UPNP)
---|---------|
---|---------|
Pi (lan)-----|   
---------Echo (wlan of Router 2)

DHCP enabled
PI IP-Address: 192.168.0.100
Echo IP-Address: 192.168.0.101

After startup, the first problem i see is this:
WARN   The upnp config address, 192.168.0.100, does not match any known IP's on this host.	com.bwssystems.HABridge.BridgeSettings

Thank you!

**Comment by bwssytems** [comment]
so, the warning message is telling you that your ip is now different. have you set the address for the pi to be static? dhcp assigned a new address to the pi

**Comment by doucit** [comment]
wow that was a fast replay - thanks.

the ip for the pi is not static but it is the current ip. i checked the ips after every reboot in the routers gui - no changes there. 

btw: is it normal that i see this warning only once after a reboot even if a save/reinitialize?

**Comment by bwssytems** [comment]
So there is no issue with dhcp release and request, it is best to set it to static. THen you won't have to change your upnp config address all the time in the UI. 

When you do have it set to the machine's IP and you are not seeing the bridge, turn on trace upnp in the Bridge Control tab and look at the log to see if your echo is getting to the bridge.

**Comment by doucit** [comment]
pi: 192.168.0.100
echo: 192.168.0.101
'UPNP IP Address' in bidge control: 192.168.0.100
Router: Current UPnP Status - Enabled

i guess here is the echo searching?
03-01-2017 15:57:54.950	INFO	Traceupnp: SSDP packet from 192.168.0.101:50000, body: M-SEARCH * HTTP/1.1
 HOST: 239.255.255.250:1900
 MAN: "ssdp:discover"
 MX: 15
 ST: urn:schemas-upnp-org:device:basic:1
 
	com.bwssystems.HABridge.upnp.UpnpListener

fulll log:

03-01-2017 05:21:58.274	INFO	HA Bridge (v4.2.0) starting....	com.bwssystems.HABridge.HABridge
03-01-2017 05:21:58.344	INFO	reading from config file: /home/pi/habridge/data/habridge.config	com.bwssystems.HABridge.BridgeSettings
03-01-2017 05:21:59.485	WARN	The upnp config address, 192.168.0.100, does not match any known IP's on this host.	com.bwssystems.HABridge.BridgeSettings
03-01-2017 05:21:59.489	INFO	HA Bridge initializing....	com.bwssystems.HABridge.HABridge
03-01-2017 05:21:59.888	INFO	System control service started....	com.bwssystems.HABridge.SystemControl
03-01-2017 05:22:01.219	INFO	Initializing UDP response Socket...	com.bwssystems.HABridge.util.UDPDatagramSender
03-01-2017 05:22:01.428	INFO	UDP response Seocket initialized to: 50000	com.bwssystems.HABridge.util.UDPDatagramSender
03-01-2017 05:22:01.496	INFO	Harmony Home created. No Harmony devices configured.	com.bwssystems.HABridge.plugins.harmony.HarmonyHome
03-01-2017 05:22:01.580	INFO	Nest Home created. No Nest configured.	com.bwssystems.HABridge.plugins.NestBridge.NestHome
03-01-2017 05:22:01.595	INFO	Hue passthru Home created. No Hue passtrhu systems configured.	com.bwssystems.HABridge.plugins.hue.HueHome
03-01-2017 05:22:01.631	INFO	HAL Home created. No HAL devices configured.	com.bwssystems.HABridge.plugins.hal.HalHome
03-01-2017 05:22:01.640	INFO	MQTT Home created. No MQTT Clients configured.	com.bwssystems.HABridge.plugins.mqtt.MQTTHome
03-01-2017 05:22:01.645	INFO	HomeAssistant Home created. No HomeAssistants configured.	com.bwssystems.HABridge.plugins.hass.HassHome
03-01-2017 05:22:01.650	INFO	Command Home for system program execution created.	com.bwssystems.HABridge.plugins.exec.CommandHome
03-01-2017 05:22:04.004	INFO	== Spark has ignited ...	spark.webserver.JettySparkServer
03-01-2017 05:22:04.040	INFO	>> Listening on :80	spark.webserver.JettySparkServer
03-01-2017 05:22:06.556	INFO	Http Home created.	com.bwssystems.HABridge.plugins.http.HTTPHome
03-01-2017 05:22:06.562	INFO	TCP Home created.	com.bwssystems.HABridge.plugins.tcp.TCPHome
03-01-2017 05:22:06.568	INFO	UDP Home created.	com.bwssystems.HABridge.plugins.udp.UDPHome
03-01-2017 05:22:06.573	INFO	Vera Home created. No Veras configured.	com.bwssystems.HABridge.plugins.vera.VeraHome
03-01-2017 05:22:06.580	INFO	Domoticz Home created. No Domoticz devices configured.	com.bwssystems.HABridge.plugins.domoticz.DomoticzHome
03-01-2017 05:22:06.594	INFO	LifxDevice Home created. No LifxDevices configured.	com.bwssystems.HABridge.plugins.lifx.LifxHome
03-01-2017 05:22:06.791	INFO	HABridge device management service started....	com.bwssystems.HABridge.devicemanagmeent.DeviceResource
03-01-2017 05:22:06.897	INFO	Hue description service started....	com.bwssystems.HABridge.upnp.UpnpSettingsResource
03-01-2017 05:22:06.935	INFO	Hue emulator service started....	com.bwssystems.HABridge.hue.HueMulator
03-01-2017 05:22:07.096	INFO	UPNP Discovery Listener starting....	com.bwssystems.HABridge.upnp.UpnpListener
03-01-2017 05:22:07.101	INFO	Traceupnp: eth0 ... has addr /fe80:0:0:0:8b8e:d03:fca2:cb55%eth0	com.bwssystems.HABridge.upnp.UpnpListener
03-01-2017 05:22:07.102	INFO	Traceupnp: eth0 ... has addr /192.168.0.100	com.bwssystems.HABridge.upnp.UpnpListener
03-01-2017 05:22:07.105	INFO	Traceupnp: Adding eth0 to our interface set	com.bwssystems.HABridge.upnp.UpnpListener
03-01-2017 05:22:07.105	INFO	Traceupnp: lo ... has addr /0:0:0:0:0:0:0:1%lo	com.bwssystems.HABridge.upnp.UpnpListener
03-01-2017 05:22:07.106	INFO	Traceupnp: lo ... has addr /127.0.0.1	com.bwssystems.HABridge.upnp.UpnpListener
03-01-2017 05:22:07.107	INFO	Traceupnp: Adding lo to our interface set	com.bwssystems.HABridge.upnp.UpnpListener
03-01-2017 05:22:07.108	INFO	UPNP Discovery Listener running and ready....	com.bwssystems.HABridge.upnp.UpnpListener
03-01-2017 15:55:51.881	INFO	Traceupnp: sendUpnpNotify notifyTemplate is <<<NOTIFY * HTTP/1.1
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 LOCATION: http://192.168.0.100:80/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 NTS: ssdp:alive
 hue-bridgeid: B827EBFFFEBFF418
 NT: uuid:2f402f80-da50-11e1-9b23-b827ebbff418
 USN: uuid:2f402f80-da50-11e1-9b23-b827ebbff418
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener
03-01-2017 15:56:12.858	INFO	Traceupnp: sendUpnpNotify notifyTemplate is <<<NOTIFY * HTTP/1.1
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 LOCATION: http://192.168.0.100:80/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 NTS: ssdp:alive
 hue-bridgeid: B827EBFFFEBFF418
 NT: uuid:2f402f80-da50-11e1-9b23-b827ebbff418
 USN: uuid:2f402f80-da50-11e1-9b23-b827ebbff418
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener
03-01-2017 15:56:52.126	INFO	Traceupnp: sendUpnpNotify notifyTemplate is <<<NOTIFY * HTTP/1.1
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 LOCATION: http://192.168.0.100:80/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 NTS: ssdp:alive
 hue-bridgeid: B827EBFFFEBFF418
 NT: uuid:2f402f80-da50-11e1-9b23-b827ebbff418
 USN: uuid:2f402f80-da50-11e1-9b23-b827ebbff418
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener
03-01-2017 15:56:52.128	INFO	Traceupnp: sendUpnpNotify notifyTemplate is <<<NOTIFY * HTTP/1.1
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 LOCATION: http://192.168.0.100:80/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 NTS: ssdp:alive
 hue-bridgeid: B827EBFFFEBFF418
 NT: uuid:2f402f80-da50-11e1-9b23-b827ebbff418
 USN: uuid:2f402f80-da50-11e1-9b23-b827ebbff418
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener
03-01-2017 15:57:13.145	INFO	Traceupnp: sendUpnpNotify notifyTemplate is <<<NOTIFY * HTTP/1.1
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 LOCATION: http://192.168.0.100:80/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 NTS: ssdp:alive
 hue-bridgeid: B827EBFFFEBFF418
 NT: uuid:2f402f80-da50-11e1-9b23-b827ebbff418
 USN: uuid:2f402f80-da50-11e1-9b23-b827ebbff418
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener
03-01-2017 15:57:34.145	INFO	Traceupnp: sendUpnpNotify notifyTemplate is <<<NOTIFY * HTTP/1.1
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 LOCATION: http://192.168.0.100:80/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 NTS: ssdp:alive
 hue-bridgeid: B827EBFFFEBFF418
 NT: uuid:2f402f80-da50-11e1-9b23-b827ebbff418
 USN: uuid:2f402f80-da50-11e1-9b23-b827ebbff418
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener
03-01-2017 15:57:54.740	INFO	Traceupnp: sendUpnpNotify notifyTemplate is <<<NOTIFY * HTTP/1.1
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 LOCATION: http://192.168.0.100:80/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 NTS: ssdp:alive
 hue-bridgeid: B827EBFFFEBFF418
 NT: uuid:2f402f80-da50-11e1-9b23-b827ebbff418
 USN: uuid:2f402f80-da50-11e1-9b23-b827ebbff418
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener
03-01-2017 15:57:54.949	INFO	Traceupnp: isSSDPDiscovery found message to be an M-SEARCH message.	com.bwssystems.HABridge.upnp.UpnpListener
03-01-2017 15:57:54.950	INFO	Traceupnp: isSSDPDiscovery found message to be valid under strict rules - strict: true	com.bwssystems.HABridge.upnp.UpnpListener
03-01-2017 15:57:54.950	INFO	Traceupnp: SSDP packet from 192.168.0.101:50000, body: M-SEARCH * HTTP/1.1
 HOST: 239.255.255.250:1900
 MAN: "ssdp:discover"
 MX: 15
 ST: urn:schemas-upnp-org:device:basic:1
 
	com.bwssystems.HABridge.upnp.UpnpListener
03-01-2017 15:57:54.951	INFO	Traceupnp: sendUpnpResponse discovery responseTemplate1 is <<<HTTP/1.1 200 OK
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 EXT:
 LOCATION: http://192.168.0.100:80/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 hue-bridgeid: B827EBFFFEBFF418
 ST: upnp:rootdevice
 USN: uuid:2f402f80-da50-11e1-9b23-b827ebbff418::upnp:rootdevice
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener
03-01-2017 15:57:54.954	INFO	Traceupnp: sendUpnpResponse discovery responseTemplate2 is <<<HTTP/1.1 200 OK
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 EXT:
 LOCATION: http://192.168.0.100:80/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 hue-bridgeid: B827EBFFFEBFF418
 ST: uuid:2f402f80-da50-11e1-9b23-b827ebbff418
 USN: uuid:2f402f80-da50-11e1-9b23-b827ebbff418
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener
03-01-2017 15:57:54.956	INFO	Traceupnp: sendUpnpResponse discovery responseTemplate3 is <<<HTTP/1.1 200 OK
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 EXT:
 LOCATION: http://192.168.0.100:80/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 hue-bridgeid: B827EBFFFEBFF418
 ST: urn:schemas-upnp-org:device:basic:1
 USN: uuid:2f402f80-da50-11e1-9b23-b827ebbff418
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener
03-01-2017 15:57:55.042	INFO	Traceupnp: isSSDPDiscovery found message to be an M-SEARCH message.	com.bwssystems.HABridge.upnp.UpnpListener
03-01-2017 15:57:55.042	INFO	Traceupnp: isSSDPDiscovery found message to be valid under strict rules - strict: true	com.bwssystems.HABridge.upnp.UpnpListener
03-01-2017 15:57:55.043	INFO	Traceupnp: SSDP packet from 192.168.0.101:50000, body: M-SEARCH * HTTP/1.1
 HOST: 239.255.255.250:1900
 MAN: "ssdp:discover"
 MX: 15
 ST: urn:schemas-upnp-org:device:basic:1
 
	com.bwssystems.HABridge.upnp.UpnpListener
03-01-2017 15:57:55.044	INFO	Traceupnp: sendUpnpResponse discovery responseTemplate1 is <<<HTTP/1.1 200 OK
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 EXT:
 LOCATION: http://192.168.0.100:80/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 hue-bridgeid: B827EBFFFEBFF418
 ST: upnp:rootdevice
 USN: uuid:2f402f80-da50-11e1-9b23-b827ebbff418::upnp:rootdevice
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener
03-01-2017 15:57:55.046	INFO	Traceupnp: sendUpnpResponse discovery responseTemplate2 is <<<HTTP/1.1 200 OK
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 EXT:
 LOCATION: http://192.168.0.100:80/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 hue-bridgeid: B827EBFFFEBFF418
 ST: uuid:2f402f80-da50-11e1-9b23-b827ebbff418
 USN: uuid:2f402f80-da50-11e1-9b23-b827ebbff418
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener
03-01-2017 15:57:55.048	INFO	Traceupnp: sendUpnpResponse discovery responseTemplate3 is <<<HTTP/1.1 200 OK
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 EXT:
 LOCATION: http://192.168.0.100:80/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 hue-bridgeid: B827EBFFFEBFF418
 ST: urn:schemas-upnp-org:device:basic:1
 USN: uuid:2f402f80-da50-11e1-9b23-b827ebbff418
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener
03-01-2017 15:58:16.146	INFO	Traceupnp: sendUpnpNotify notifyTemplate is <<<NOTIFY * HTTP/1.1
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 LOCATION: http://192.168.0.100:80/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 NTS: ssdp:alive
 hue-bridgeid: B827EBFFFEBFF418
 NT: uuid:2f402f80-da50-11e1-9b23-b827ebbff418
 USN: uuid:2f402f80-da50-11e1-9b23-b827ebbff418
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener

**Comment by bwssytems** [comment]
03-01-2017 05:21:59.485	WARN	The upnp config address, 192.168.0.100, does not match any known IP's on this host.	com.bwssystems.HABridge.BridgeSettings

This is still your issue.... Now I see that you have a typo... remove the comma after the IP address

**Comment by doucit** [comment]
Bridge Control -> UPNP IP ADDRESS: 192.168.0.100

There is no comma. :(

**Comment by bwssytems** [comment]
Sorry, I do see the comma in the code as a delimeter.

So, the only other thought is that the field for the address is not truly the correct characters. If you cu and pasted the text that could have brought unseen formatting. Delete out the text and hand type it back in. As long as you get that warning message, the system will not send back the correct address from a upnp response.

**Comment by doucit** [comment]
Sadly, i already typed it without copy & paste.. again and again. Is there somewhere a config file to check whats written in there?

**Comment by bwssytems** [comment]
Yes, in the data directory there is an habridge.conf file that contains this info

**Comment by doucit** [comment]
{"upnpconfigaddress":"192.168.0.100","serverport":80,"upnpresponseport":50000,"upnpdevicedb":"data/device.db","buttonsleep":100,"upnpstrict":true,"traceupnp":true ... "

the correct string :/

**Comment by bwssytems** [comment]
I am baffled....

**Comment by doucit** [comment]
so am i. but thank you anyway :)

**Comment by bwssytems** [comment]
So, last question... Are you starting the ha-bridge from a rc script or using the systemctl startup or from the command line?

**Comment by doucit** [comment]
With the systemctl and start service on boot

**Comment by bwssytems** [comment]
So you have the unit file with this text at the top? Especially the network target
```
[Unit]
Description=HA Bridge
Wants=network.target
After=network.target
```

**Comment by doucit** [comment]
Yea, got this from your install instructions.

BTW: Installed ha-bridge on a windows machine in the same network and echo found it

/etc/systemd/system/habridge.service

[Unit]
Description=HA Bridge
Wants=network.target
After=network.target

[Service]
Type=simple

ExecStart=/usr/bin/java -jar -Dconfig.file=/home/pi/habridge/data/habridge.config /home/pi/habridge/ha-bridge-4.2.0.jar

[Install]
WantedBy=multi-user.target

**Comment by bwssytems** [comment]
So, we have seen some issues on the rapsberry pi installs where it just is not working with the network. We  have suggested re-install a fresh raspbian image and that has resolved it.

**Comment by doucit** [comment]
It was a fresh raspbian-jessie but i will try a new one. Will reply then :)

**Comment by audiofreak9** [comment]
Do make sure it's the full RASPBIAN JESSIE WITH PIXEL, not the LITE version.

**Comment by doucit** [comment]
Thanks, got the full version and used update/upgrade after first boot.

**Comment by doucit** [comment]
So, finally... it is working !
The problem was xrdp, i think. After a fresh install, it worked. Installing xrdp after made it not finding devices anymore.
After multiple removes/installs of vncserver/xrdp, both is working well for now.

**Comment by bwssytems** [comment]
Great!
