### ISSUE TITLE
Log file

### ISSUE THREAD

**Issue by hmspain** [bwssytems/ha-bridge#51]
This is such an excellent implementation, I hesitate to ask but... adding a log file to the habridge process would be a welcome enhancement! :-)

No need to gimmick the java start command line to try and capture the output (like I do), just specify the log file location/name in your new Bridge control, and the log file gets created.  Click on a button to review older logs.  A new log file would be created each time the process starts keeping a limited number.

If the process dies for any reason, the previous log file can be reviewed either from shell or the web page.

**Comment by bwssytems** [comment]
I will look into this. The logging subsystem needs to be updated.
