### ISSUE TITLE
Proxy two Hue bridges

### ISSUE THREAD

**Issue by wpeterw** [bwssytems/ha-bridge#511]
I want to proxy two Hue bridges thru HA-bridge and control the light with HomeAssistant.

Is it correct that I need to run HA-bridge on port 80?

I can change the port from 8082 to 80 but after a restart it's on 8082 again. The .Config in /data says port 80. HomeAssistant cannot connect to HA-bridge emulated Hue bridge. What am I doing wrong?

**Comment by bwssytems** [comment]
So, you can do this, but it looks like you are having relative path location issues.happens based on where you start the bridge and then the 'data' directory is relative to that. The best thing to do is to start the bridge with a fixed path to the habridge.conf and make sure you update that path in the UI and save it after the first start of the system.

**Comment by wpeterw** [comment]
Thanks for the quick reply. I have a full path specified to both the config and the data db:
Ps: How do I emulate the "Press the button on the bridge"?

![capture](https://cloud.githubusercontent.com/assets/9653787/23481260/1a3dd6d8-fecb-11e6-94e9-b82e4fa839b1.PNG)

**Comment by bwssytems** [comment]
It is always in press the button mode. Do your discovery twice in a row

**Comment by wpeterw** [comment]
Just to be sure: the Web Server Port (see pic above) needs to be 80 for the Hue App to see the emulated (proxied) bridges ?

**Comment by bwssytems** [comment]
for the hue app, that is corect
