### ISSUE TITLE
Dim handling in V4

### ISSUE THREAD

**Issue by tuicemen** [bwssytems/ha-bridge#512]
Using windows 10 so that may be part of the issue.
1: bridge will not stop
Clicking stop bridge displays message that it is stopped and must be restarted from server but if i just refresh the page the bridge is still running.

2: if a dim command is sent and then a off command is sent the bri level stays at what ever the dim was and doesn't get set to Zero as it did in 3.5.1, seems it has been like that since then
if the bri level is at 254 it does get set to zero.

3: the bri level (#2) wouldn't be a issue if the PUT **htp://host:port/api/<username>/lights/<id>/bridgeupdatestate** would allow a
{
    "on": false,
    "bri": 0
}
it only will do the "on": false

**Comment by tuicemen** [comment]
if I do a PUT htp://host:port/api//lights//bridgeupdatestate
{
"on": false,
"bri": 254
}
followed by a put htp://host:port/api//lights//bridgeupdatestate
{
"on": false,
}
the device does truly go to off 0
so with  this work around  #s 2 & 3  can be remedy but it is a lot of extra code.

A follow up to #1:
 I can't shut down the bridge via code either using PUT http://host:port/system/control/stop
versions prior this worked.

**Comment by bwssytems** [comment]
So, this was implemented on request to have a preset dim level status available. Some systems turn on the light to the previous dim level unless it was fully on. Calling bridgeupdatestate should have the same effect as it calls the same routines to calculate on/off/dim

I'll look into the shutdown

**Comment by tuicemen** [comment]
I'll post a suggestion for the Presets, as I do like that feature it just messes with some bulbs.

I reverted to 4.1.4 just to confirm the shut down works with that version on my system so my system hasn't changed.

**Comment by bwssytems** [comment]
Yeah, the shutdown is due to the domoticz close handler as it fails and hangs the program

The status handling setting can be turned off overall in the bridge control tab, but not per bulb at this point

**Comment by tuicemen** [comment]
> The status handling setting can be turned off overall in the bridge control tab, but not per bulb at this point
Can you point to that I can't find it?

**Comment by bwssytems** [comment]
Sorry I was wrong. It is per device and it is called "No State (Do not update state for device)"

**Comment by tuicemen** [comment]
Ok I seen that, I assumed that was for ON/Off and Dim 
I still wish to know the on/off state in all cases

**Comment by bwssytems** [comment]
So, I'll put in a switch for the device to have off set bri to 0.
