### ISSUE TITLE
OpenHAB integration

### ISSUE THREAD

**Issue by m4rcu5** [bwssytems/ha-bridge#516]
Hi,

I see that for Vera and recently Home Assistant there is a way to poll devices and very easily create bridge items in ha-bridge.
Are you planning on doing the same for OpenHAB? This would be a cool feature.

**Comment by bwssytems** [comment]
Future enhancement

**Comment by aerickson** [comment]
Until this feature is done...

People seem to have this working with the Hue Emulation plugin in OpenHab.

https://github.com/bwssytems/ha-bridge/issues/295

It doesn't seem to be possible to edit tags in OH2 yet (required for the Hue Emulation plugin to export the item/thing).

**Comment by TRIROG** [comment]
How about just integrating support for OpenHAB REST API?

**Comment by digiltd** [comment]
You can easily do this now by creating a custom device.

Here is how I added a socket dimmer controlled in OpenHAB to ha-bridge so I can say "set the bedside lights to 40%" "turn the bedside lights on/off"

![image](https://user-images.githubusercontent.com/5680968/32419936-a103fe36-c27a-11e7-87c6-5240a8fb5158.png)

**Comment by bwssytems** [comment]
This will be interesting as OpenHAB 2.2.0 will have hue emulation.

**Comment by bwssytems** [comment]
Please go test RC version in #863

**Comment by bwssytems** [comment]
New Jar is out in thread #863

**Comment by zdzichu** [comment]
Can you provide few paragraph with instructions how one is supposed to use this OpenHAB functionality?
Right now I'm configuring my devices with type HTTP and urls like http://openhab.ip/CMD?sSWITCHNAME=ON etc. I don't see how defining OpenHAB instance in ha-bridge configuration changes that.
Thanks
