### ISSUE TITLE
Basic Manual add question, convert URL get to bridge object

### ISSUE THREAD

**Issue by papa-legba** [bwssytems/ha-bridge#518]
So I have a Broad link Rm 3 mini IR blaster that I am controling through the RM tasker plugin running on my Nvidia Shield TV. Using the RM tasker plugin I am now running an HTTP bridge on the shield that can receive commands and execute them on the IR blaster.  

Through the API I have determined that if I enter as an example http://10.0.1.15:9876/execute?macroId=123 in a webrowser it successfully executes the command on Shield TV.

my question

How do I create a manual device for the bridge that will send a get or post command to a url.  

here is my URL that works in my web browser
http://10.0.1.15:9876/execute?macroId=xxxxxxxxx-bef9-xxxxxxx-bca4-883baab6195f

Which fields do I need to fill in. I have tried several approaches but I'm not well versed in JSON or the basics of the API from the Readme.

**Comment by bwssytems** [comment]
Just use the UI and put that into your on/dim/off target item as an HTTP device

**Comment by papa-legba** [comment]
Awesome!  Works like a charm!!!
