### ISSUE TITLE
Dim feature not working with Home Assistant

### ISSUE THREAD

**Issue by wjbeckett** [bwssytems/ha-bridge#519]
I'm trying to get dimming to work with HomeAssistant but the brightness value isn't being passed through.

When using the dimming test button, the logs on HomeAssistant is showing the brightness being set at 1.0 regardless of what the slider's value is on HA-Bridge.

I have tried with the raw and percentage values.

Is there further configuration needed when adding the light from the HomeAssistant tab? From what I can see the Dim items command is the same as the On items command. Is this correct?

**Comment by bwssytems** [comment]
what bridge  version are you running?

**Comment by bwssytems** [comment]
Any issues still?

**Comment by wjbeckett** [comment]
Sorry,
Yep. Still not dimming the lights.

Bridge version. 4.2

**Comment by bwssytems** [comment]
Ahh, when you create the device, you need to select the dim control at the top of the page to be one of the selections.

**Comment by bwssytems** [comment]
Did that answer your question?

**Comment by wjbeckett** [comment]
Thank you very much! It works now.
