### ISSUE TITLE
MQTT 

### ISSUE THREAD

**Issue by merlin051** [bwssytems/ha-bridge#521]
I have MQTT up and running using the python-broadlink script.

At the moment I'm using mosquitto_pub.exe to send messages and everything is working ok. However when I activate(enter IP:port ) the MQTT broker in HA-Bridge my python script can no longer connect to the service on port 1883. 

Is this a single thread operation or is something broken?

**Comment by bwssytems** [comment]
Only one program can connect to the port on the same system.Either use the mqtt_pub or the HA-Bridge MQTT but not both.
