### ISSUE TITLE
Send raw data to an IP address, including spaces

### ISSUE THREAD

**Issue by domier** [bwssytems/ha-bridge#523]
I'm working on configuring ha-bridge to work with the IP control interface of a sharp aquos TV.  The IP control system isn't that well documented, but I have managed to get it to work over PuTTY as described in the below link:

http://forum.universal-devices.com/topic/12512-ip-control-of-sharp-tv/

In summary, I need to send 8 characters of raw data, that often end with spaces.  An example of what I need to send is "POWR1   ", but without the quotes.  Note the 3 spaces at the end that make it 8 characters.

What I'm struggling to get ha-bridge to send this for two reasons:
1) I have to pick and HTTP verb, which throws a bunch of information into the request.  From what I can tell I need to send 8 characters and 8 characters only
2) if I end my "Http Body" with a space it gets dropped when I save the device

Is there a way to accomplish this with ha-bridge as is, or would this be a feature request?

**Comment by bwssytems** [comment]
Well, that interface is not an HTTP interface. You need to use the TCP Device in the ah bridge.

the target item format is tcp://<ip_address>:<port>/<payload> to guarantee that you get your spaces I would use the ehx encoding of "POWR1   " which is 0x504f575231202020

so your target item will look like tcp://192.168.1.1:10002/0x504f575231202020

**Comment by domier** [comment]
Thanks for the quick reply!

I realize it's near impossible to troubleshoot this here, but the above isn't working.  Seeing as I have to send RSPW2___ and then POWR1___ I have the below test config set up for the ON command.  Anything look glaringly wrong?

Also, in the interest of being thorough I went back into PuTTY and tried sending the hex codes to the TV, but it responded with the error code. Looking at page 64 of the linked manual it seems to need to be in ACSII, and the commands detailed within certainly work in ASCII, but not in hex.  This brings me back to wanting to send ASCII through ha-bridge that ends in spaces, but having no way to input it.  Any other ideas?

Note: I tried the hex codes with and without the 0x at the beginning, with and without the 0DH return char code mentioned in the manual

**Manual:**
http://files.sharpusa.com/Downloads/ForHome/HomeEntertainment/LCDTVs/Manuals/mon_man_LC70LE847U_LC60LE847U_LC70LE745U_LC60LE745U_LC80LE844U.pdf

**Current Test Config:**
Type: TCP Device
Target Item: tcp://192.168.1.4:10002/0x5253505732202020
Delay: 200
Count: <Blank>
Filter IPs: <Blank>
Http Verb: ---Please Select---
Http Body: <Blank>
Http Headers: <Blank>
Content Type: ---Please Select---

Type: TCP Device
Target Item: tcp://192.168.1.4:10002/0x504F575231202020
Delay: 200
Count: <Blank>
Filter IPs: <Blank>
Http Verb: ---Please Select---
Http Body: <Blank>
Http Headers: <Blank>
Content Type: ---Please Select---

Note: I tried text/plain,*, and x-www-form-urlencoded as well, but no luck.

**Comment by bwssytems** [comment]
Ahh, sorry, I see that a CR LF needs to be sent as well  from the top link's instructions

The hex codes you see are interpreted into binary when sent. That binary stream looks like the ASCII chars that need to be sent. This is because the UI does not handle spaces very well at the end of a string. But, since we need to sent a CRLF at the end of the line, this will be much easier... So, her eya go...

The item in the on field

TCP Device
tcp://192.168.1.4:10002/RSPW2   \r\n

TCP Device
tcp://192.168.1.4:10002/POWR1   \r\n

**Comment by bwssytems** [comment]
Crap, that won't work that way until the next release.... You'll have to use the hex interpretation

Also, 0x is the key that tells the habridge to convert the hex string characters into a binary bytes that are represented by the codes.

I use this site to convert the text http://codebeautify.org/string-hex-converter but it does have issues iwth converting a return key to CR LF, that is what the 0d0a is on the end of the hex representation

RSPW2 \r\n
tcp://192.168.1.4:10002/0x5253505732202020d0a

POWR1 \r\n
tcp://192.168.1.4:10002/0x504f5752312020200d0a

**Comment by domier** [comment]
I don't believe it, it works!!  Thank you so much, I don't think I would have ever figure that out on my own.

Exciting to hear that you're adding support for the other formatting in the new version, I saw the issue about the hex conversion being pushed to 4.2.1 and wasn't sure if it was related or not...  I'll upgrade when 4.2.1 comes out and see if I can get it to work there as well, would certainly make this a lot easier to manage.

closing the issue :D
