### ISSUE TITLE
ha bridge not paired with my Google assistance"OK GOOGLE "home control of updated google assitance Application on android cell phone 

### ISSUE THREAD

**Issue by vngic** [bwssytems/ha-bridge#524]
Hello , 
 A Warm hello from India
Thank you very much for HA bridge , Its very usefull for me and for any one .

I'm writing here something because of that , as people always want more and more .

I have Google home which is easily connect with  ha-bridge , and now i'm able to use its TCP Device to control my home automation system.
 
Here Comes More ,

My Android Phone also  have OK Google Feature (Attaching screenshot-
![screenshot_20170308-125943](https://cloud.githubusercontent.com/assets/18141289/23694612/d78ac216-0400-11e7-87ad-a7621153cdc1.jpg) )  with Home control , tab on home control , add the philips hue device  but its asking 
![screenshot_20170308-131304](https://cloud.githubusercontent.com/assets/18141289/23694701/4dcb40fe-0401-11e7-83e5-30f6ac0b8f8c.jpg)
me for login as both i.e. my cell phone and ha-bridge are on same network (Which is not happening with Google home App i.e. ha-bridge directly get connected with Google home and populated all the device )

Please help to add habrodge to my google assitance  

What should need to be done please let me know

 Eagerly waiting for your reply  ...

My Email-Id - Avaneesh.lnm@gmail.com
Skype Id-avaneesh.pathak

Please , Help me on that ...

**Comment by Matt8119** [comment]
@vngic the help section is to answer questions, not tutorials.  you need to watch this video to understand how to install it and get it started.  https://www.youtube.com/watch?v=93PE8avLq5M

**Comment by Matt8119** [comment]
https://github.com/bwssytems/ha-bridge#google-assistant

**Comment by bwssytems** [comment]
@vngic Unfortunately, the phone version of the Google Assistant can not connect to local network devices. Only the Google Home appliance can do that.

**Comment by vngic** [comment]
Hey ..
Is there anyway to connect phone version to connect with google home..??

**Comment by Matt8119** [comment]
A: The ha-bridge requires a physical Amazon Echo, Dot, Tap or Google Home device and does not work with prototype devices built using the Alexa Voice Service e.g. Amazon’s Alexa AVS Sample App and Sam Machin’s AlexaPi. The AVS version does not have any capability for Hue Bridge discovery!

**Comment by vngic** [comment]
sorry for my previous comment , i just need to ask about is there any way to connect phone version of google assitance with habridge  .

any way ...?

**Comment by vngic** [comment]
Or should i add harbridge to my account which is created on hue website .. i think on that way i can connect habridge to home assistance

**Comment by vngic** [comment]
Please suggest me something , some code changes some extra device anything ..

**Comment by vngic** [comment]
I'm sure if there is option for home control in phone version ,there is way to connect with it .

**Comment by Matt8119** [comment]
you can build your own.  all the ha-bridges need a physical device

**Comment by merlin051** [comment]
HA-Bridge is local lan.

As far as I'm aware the Google stuff goes out to the cloud?

**Comment by vngic** [comment]
hey Owner ..
Any suggestions...

**Comment by vngic** [comment]
@Matt8119  I love to build my own , but need your help .. can you help me out?

**Comment by Matt8119** [comment]
you can use autovoice with tasker.

**Comment by Matt8119** [comment]
https://ifttt.com

**Comment by vngic** [comment]
Great ..you have something on that?

I mean where i can start with ..

**Comment by Matt8119** [comment]
'google search" is your friend.

**Comment by vngic** [comment]
hahaha...
You are also my friend ..

**Comment by bwssytems** [comment]
@vgnic You will need to do your homework, this is a contribute what you know project and we can help along the way if you have understanding. If you do not want to take the time to investigate and to understand yourself, it would be difficult to spend days with you. We do this in our spare time.

**Comment by vngic** [comment]
Yeah ..Understood ..I'll do my homework ..For sure ..if I stuck somewhere , i need your help guys..

**Comment by bwssytems** [comment]
Closign for now
