### ISSUE TITLE
Vera devices offline

### ISSUE THREAD

**Issue by unifiedesystems** [bwssytems/ha-bridge#53]
Hi,
I just installed this on a fresh Windows 7 VM, per a upnp conflict on another machine. Echo did discover all the devices after removing Hue devices from SmartThings. They then worked when I tested Alexa. However, after a short period, the Vera devices show as offline in Echo, even after a stop/start or reinitialization of the HA Bridge. The devices test fine in the bridge. They also work in Echo with an Offline status. When I add new Bridge Devices and attempt to find them in Echo, the new devices are not discovered. How do I resolve both the offline and new device discovery issue?

**Comment by bwssytems** [comment]
The echo is a bit eccentric at times. One of the things to try is forget all devices. Reboot your echo (unplug, wait, plug in) and then re-discover devices. The echo seems to cache some information. Also, if you have a real hue bridge, the echo gets a bit confused. Try this out and let me know.

**Comment by unifiedesystems** [comment]
Seems I have to remove all and re-discover a lot, on the Echo. This has nothing to do with your app either, but this is how I get the new devices discovered, I did notice that it confuses the Hue bulbs when they are also linked with SmartThings (double devices). Like it checks the name, rather than a unique identifier. 
Since this sort of hacks the Hue, is there a way to get the Vera devices to appear as Hue devices (like I have a second Hue), so that they can easily be used in IFTTT recipes (no MAKER or Tasker,etc.), since Vera appears to be the only provider without a channel or noticeable interest in any partnerships with any company dealing with current technology? 
Are you brewing anything to easily "migrate" Vera devices over to SmartThings? Then I can finally add the green thing to my box of antique electronics....

**Comment by bwssytems** [comment]
The habridge only emulates a local HUE bridge. It does not register with the hue cloud for the other control items.

Smartthings already has native echo control so there is no need to bridge it. It seems that will be the route that most people will take, Vera will probably not survive in the end.

**Comment by unifiedesystems** [comment]
I was trying to bridge Vera to SmartThings or migrate my devices from Vera to ST. Right now the Hue, Echo, TCP, Vera and ST are a cluster-f. No, Vera won't survive. It's been stale for years. Putting pretty wrapping on old technology, calling it a new model, to get sales. But SmartThings needs to come up with WiFi/remote pairing and a Windows web interface. Those are the only reasons users still bother with Vera. 1980 End User Requirements, more so than device types it can control.

**Comment by emiliosic** [comment]
I somewhat agree with you but in the end I just migrated to a Vera Plus, which adds support for Wave plus, Zigbee and BT Smart. The software can be a lot friendlier; but it's been stable for me. So fad had no issues with ha-bridge/echo and Harmony.
What sold me are the plugins, and the fact that with little knowledge (in Lua) and a fair amount of plugins, it works, and it doesn't rely on cloud services.
You lost mw with the requirements. Vera can be controlled from a web page from any device I tried from; and although their own mobile apps are basic; there's a healthy amount of third party mobile apps. The whole API is fairly open and you can even SSH as root to it.
Vera seems to be thin on development resources but they're chugging along. I think they made strides in stability in the past year or so.

**Comment by bwssytems** [comment]
It is interesting that the home automation area kind of lacks that vision of how to put it all together to be useful. But, in the end for the big companies, it's about how much they can sell, not that it really is a fully fleshed out product. That's why we do these things...lol

**Comment by unifiedesystems** [comment]
Ha. The 1980's requirements are a web site and WiFi. Vera is easy to use and setup. Web interfaces have been the norm for a very long time. Cloud or local. So has wifi. For SmartThings to take that away but provide more integrations than Vera would ever offer...wasnt vera smart. Lol. And the fix is easy, but still not implemented after years of complaints...
They are both half-assed and why I have both. 
True, we wouldnt have jobs if any company had it all together.

**Comment by bwssytems** [comment]
So, is this question answered?

**Comment by unifiedesystems** [comment]
Yes, sir. I've discovered Tasker and commanding everything else thru AutoVoice.
