### ISSUE TITLE
Dim parameters for Vera Z-wave

### ISSUE THREAD

**Issue by xbmcnut** [bwssytems/ha-bridge#530]
Loving ha-bridge but after adding two z-wave dimmers to my Vera network, I'm a bit stumped how to get them to dim with Google Home. GH says she's dimming, but nothing happens.

By default, ha-bridge adding the following to the _target_ box for _dim items_ which I'm assuming is not correct? I've read through the guide but it's a bit over my head. 

`http://10.0.1.91:3480/data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:SwitchPower1&action=SetTarget&newTargetValue=1&DeviceNum=27`

Any assistance would be greatly appreciated. BTW, running 4.2.0

**Comment by xbmcnut** [comment]
OK. I'm a dumb arse. Had not selected the _dim control type_ before adding the device. Dim works now however the percentages are well off. If I select _percentage_ as the dim type. Dim by 10% (from full) goes to about half way, dim another 10% light goes out. Can that be tweaked somewhere?

**Comment by xbmcnut** [comment]
OK, re-added device with pass-thru now after scouring through closed issues. It works quite well now but it seems the relationship between the percentage on the vera and the actual brightness are off and that's not related to ha-bridge. Dimming the lights on the AEON V2 dimmer to 16% using Imperihome results in no light so I'll have to see if there is a tweak for that somewhere.

**Comment by bwssytems** [comment]
dim by intensity.percent is the correct way, pass thru sends the raw value from the hue api which is from 1-255

**Comment by bwssytems** [comment]
Also, the constructs for dimming with Alexa are "Alexa, set thing to 70" or "Alexa dim thing". I don't think it's construct deals with "Alexa, dim thing by 10 percent".

**Comment by xbmcnut** [comment]
Thank you. Have changed it back to percent and while any value under 30% is pretty much useless, it is now working fine. Thanks for your help.
N.B In Google Home, dim is achieved with "Set <light name> to 50%" or Dim/Brighten <light name> by 50%"

**Comment by bwssytems** [comment]
Just remember that the bridge has to have a value to give to Google Home or Alexa so that they can find the current value to dim form. Such as the light is not on and you ask it to dim by 50% may have inconsistent results.
