### ISSUE TITLE
Hostnames not working in target

### ISSUE THREAD

**Issue by wacind** [bwssytems/ha-bridge#532]
If I use a hostname instead of IP address in 'target item'  i get an exception "WARN  com.bwssystems.HABridge.plugins.http.HTTPHome - Error on calling url to change device state: "

For example if my target item for turning something on is 'http://192.168.1.2:5000/?TV_ON' it will work
but if it is 'http://HTPC:5000/?TV_ON' it will not work.

using the hostname instead of IP works from all other devices on the network and it also works using the armzilla ha-bridge. I was wondering if i had to do something to get host name working.

Thanks

**Comment by bwssytems** [comment]
That would need to be an enhancement

**Comment by wacind** [comment]
hmm strange. I thought it use to work for me and then at some point stopped working. maybe when i recently moved. Oh well not a big deal. thanks for replying so quickly

**Comment by bwssytems** [comment]
Now I look at the code and that should work as I am just using the apache http client and using the URI formatter.

**Comment by bwssytems** [comment]
Have you investigated this any further? It seems to be working for me.

**Comment by audiofreak9** [comment]
Tested myself for shits and giggles and hostname works for me too.

**Comment by bwssytems** [comment]
Not an ha-bridge issue
