### ISSUE TITLE
Dimming control in Version 4.1.3---  Edit I updatd to 4.2.1

### ISSUE THREAD

**Issue by michaelhinchey** [bwssytems/ha-bridge#538]
Ok I have been using Ha Bridge since version 3.0.  Picked it up really easy however I didnt have to do crazy stuff with this.  I have always updated the Bridge, sometimes I forget how to do it.  It really is simple if the correct steps are followed.  I had to completely reinstall windows 7 64bit and all of my programs and services which is now completed.  I reinstalled NSSM and Alexa is able to control my lights again.   YEAh!
What I am having difficulty with is how to use the new setup for dimming in 4.1.3.  It was really simple in the last versions but I cant seem to figure out all the drop downs.  Can someone point me in the right direction.  Thank you

IM using Vera Plus and Harmony Elite

**Comment by bwssytems** [comment]
well, that is previous version. upgrade and read the readme and faqs

**Comment by michaelhinchey** [comment]
4.1.3 is the previous version?  I downloaded the latest version.

**Comment by michaelhinchey** [comment]
I still cannot dim an item that I was able to dim earlier.  It looks like the dim command line is the same for on/off.  http://192.168.1.XX:XXXX/data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:SwitchPower1&action=SetTarget&newTargetValue=1&DeviceNum=7
I understand this has to be different but how do I make it so?

**Comment by bwssytems** [comment]
When you create a device, you need to select the dim control dropdown to percent first.

**Comment by michaelhinchey** [comment]
I didn't see that anywhere on the menus?

**Comment by michaelhinchey** [comment]
I seen where it says vera switch , I seen a bunch of other device types even pass thru.  But nothing that reads percentage.

**Comment by michaelhinchey** [comment]
I can manually input this into the dim area correct?

http://192.168.1.xx:xxxx/data_request?id=action&output_format=json&DeviceNum=9&serviceId=urn:upnp-org:serviceId:Dimming1&action=SetLoadLevelTarget&newLoadlevelTarget=${intensity.percent}

**Comment by bwssytems** [comment]
So you dont use the vera helper tab to build devices then. and yes you can type it in as you show

**Comment by michaelhinchey** [comment]
I'm unsure what the Vera helper tab is?  OR what you mean by that.  Sorry  Screen shot?

**Comment by bwssytems** [comment]
Please look into the Bridge control tab, here is the readme for Vera https://github.com/bwssytems/ha-bridge#vera-names-and-ip-addresses

**Comment by michaelhinchey** [comment]
Thanks.  Ive skimmed it briefly and I didn't see exactly where to add the percent or pass thru info before creating the device.  I do remember this needed to be don't with a drop down at the top of the device making.  But that was before the advancements of where this bridge is today.  I will look again tomorrow.  Thanks again

**Comment by bwssytems** [comment]
Well, I hate to say it, but you need to read the info, even if it is tedious. That is why it is there. I am teaching you to fish, instead of getting you the fish......

**Comment by michaelhinchey** [comment]
Totally understand.  It really is a lot to digest and I know that is not your issue.  You have done everything you could do.  I was just missing where the drop down was for dimming devices.  I still cannot find it.

**Comment by bwssytems** [comment]
You really need to configure your vera into the bridge control tab... Then you can see the helper tabs with the drop down. It is not in the manual edit screen.....

**Comment by michaelhinchey** [comment]
So build the device first
Then look for the helper tabs?  
Will this work even with devices that have been already introduced into the system thru earlier versions of the bridge ?

**Comment by bwssytems** [comment]
No, open teh "Tab called "Bridge Control" and add your vera name and ip at the line "Vera Names and IP Addresses"

**Comment by michaelhinchey** [comment]
I already have done that.  I've been using this since version 3.0.0.  I'm just looking for where the drop down is for percentage , pass thru etx so I can dim lights.  
I have successfully added a light and used it via Alexa.  I just can't find where the dim drop down is.

**Comment by bwssytems** [comment]
![vera](https://cloud.githubusercontent.com/assets/13528314/23863108/de13c594-07dc-11e7-8d89-a2a671afec50.jpg)

**Comment by bwssytems** [comment]
Did this answer your question?

**Comment by michaelhinchey** [comment]
Yes.  I will check that out soon.  I can't believe I missed that.  Thank you.   I am a very visual person and you are very helpful. Thx for the bridge.
