### ISSUE TITLE
Would I still need a Hue bridge (hub)?

### ISSUE THREAD

**Issue by pageb018** [bwssytems/ha-bridge#539]
I am trying to understand ha-bridge a little better, but remain confused. If I am running this on my network, could it take the place of the Hue hub and allow me to control hue bulbs via my Echo Dot and/or Apple Home Kit?

Sorry if this is a dumb question, but I am a little lost.

**Comment by michaelhinchey** [comment]
Yes.

**Comment by bwssytems** [comment]
this bridge does not control hue bulbs directly. See the readme
