### ISSUE TITLE
Must Harmony end activity always be PowerOff (-1)

### ISSUE THREAD

**Issue by johndietrich** [bwssytems/ha-bridge#54]
Is there any way to allow granular control of which activity I want to end, versus the -1 that powers off everything? For example, I might have one activity started which is watching TV and another one that turns on a lamp. If I want to turn the lamp off, that -1 also turns off the TV.

The Harmony app is able to end activities independently.... does the API not allow the same?

P.S. Great product....makes my Echo a complete home control device!

**Comment by bwssytems** [comment]
You can copy the activity for lamp off into the off area. There is no specific reason that you cannot configure it that way. By default, it assumes you turn your system on and then you turn your system off. It does not know that you have a lamp off activity and that should be switched, but you can do that by cut and paste in the on/off url areas yourself.

**Comment by johndietrich** [comment]
Thanks for the quick response! I guess that's where I'm struggling....so in the Harmony app I've created an activity the turns a Lifx bulb on. Ending that activity in the Harmony app turns the bulb off, so clearly the app has some discrete way of turning that activity off without powering everything off.

But in the Bridge, when I create the actions from that activity, I don't know what to manually put in the "off" area because I don't know the syntax for triggering an activity to end. Clearly it's got to reference the activity ID, but I don't know what else. Any clues?

Thanks so much for the help!

**Comment by bwssytems** [comment]
Interesting... all the activities are listed from the hub through the call to the interface. There are not 2 activities for the LIFX bulb on your system?

**Comment by johndietrich** [comment]
Well, no -- for example, I have an activity called "Watch TV" that turns on my AV receiver, television, and DVR. That appears in the Bridge as one activity, and I can create a device from it that I can turn on and off. Same with the Lifx bulb -- I have an activity called "Living Room Lamp" and that appears in the list of Harmony Activities as one activity as well. Turning it on works great, but turning it off uses the "-1" which I guess powers off everything. (That's not a problem when turning off the TV activity, because I actually *do* want all the AV equipment to go off in that case.) So, is there a way to create an OFF URL that uses the activity ID rather than "-1"?

Or is the suggestion to create (in the Harmony app) an activity that ONLY turns the bulb on, and a separate activity that ONLY turns it off? (Rather than using the "end" sequence of the ON activity to turn the bulb off.)

**Comment by bwssytems** [comment]
I need to do some more research on the harmony rest interface to see what I can call.

**Comment by bwssytems** [comment]
I need a little help from you. If you could run the restful-harmony app on this site and give me the output of http://<yourserver>:8081/harmony/list/activities that would be a big help in seeing how the details of your activities are set up. Unfortunately, the ha-bridge hides this info.

**Comment by johndietrich** [comment]
Here you go!

-----------------------[{"label":"TV","suggestedDisplay":"Default","id":18751108,"activityTypeDisplayName":"Default","controlGroup":[{"name":"NumericBasic","function":[{"name":"NumberEnter","label":"Number Enter","action":"{\"command\":\"NumberEnter\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"},{"name":"Number0","label":"0","action":"{\"command\":\"0\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"},{"name":"Number1","label":"1","action":"{\"command\":\"1\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"},{"name":"Number2","label":"2","action":"{\"command\":\"2\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"},{"name":"Number3","label":"3","action":"{\"command\":\"3\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"},{"name":"Number4","label":"4","action":"{\"command\":\"4\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"},{"name":"Number5","label":"5","action":"{\"command\":\"5\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"},{"name":"Number6","label":"6","action":"{\"command\":\"6\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"},{"name":"Number7","label":"7","action":"{\"command\":\"7\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"},{"name":"Number8","label":"8","action":"{\"command\":\"8\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"},{"name":"Number9","label":"9","action":"{\"command\":\"9\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"}]},{"name":"Volume","function":[{"name":"Mute","label":"Mute","action":"{\"command\":\"Mute\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"},{"name":"VolumeDown","label":"Volume Down","action":"{\"command\":\"VolumeDown\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"},{"name":"VolumeUp","label":"Volume Up","action":"{\"command\":\"VolumeUp\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"}]},{"name":"Channel","function":[{"name":"PrevChannel","label":"Prev Channel","action":"{\"command\":\"ChannelPrev\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"},{"name":"ChannelDown","label":"Channel Down","action":"{\"command\":\"ChannelDown\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"},{"name":"ChannelUp","label":"Channel Up","action":"{\"command\":\"ChannelUp\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"}]},{"name":"NavigationBasic","function":[{"name":"DirectionDown","label":"Direction Down","action":"{\"command\":\"DirectionDown\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"},{"name":"DirectionLeft","label":"Direction Left","action":"{\"command\":\"DirectionLeft\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"},{"name":"DirectionRight","label":"Direction Right","action":"{\"command\":\"DirectionRight\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"},{"name":"DirectionUp","label":"Direction Up","action":"{\"command\":\"DirectionUp\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"},{"name":"Select","label":"Select","action":"{\"command\":\"Select\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"}]},{"name":"TransportBasic","function":[{"name":"Stop","label":"Stop","action":"{\"command\":\"Stop\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"},{"name":"Play","label":"Play","action":"{\"command\":\"Play\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"},{"name":"Rewind","label":"Rewind","action":"{\"command\":\"Rewind\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"},{"name":"Pause","label":"Pause","action":"{\"command\":\"Pause\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"},{"name":"FastForward","label":"Fast Forward","action":"{\"command\":\"FastForward\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"}]},{"name":"TransportRecording","function":[{"name":"Record","label":"Record","action":"{\"command\":\"Record\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"}]},{"name":"TransportExtended","function":[{"name":"SkipBackward","label":"Skip Backward","action":"{\"command\":\"Replay\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"},{"name":"SkipForward","label":"Skip Forward","action":"{\"command\":\"Advance\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"}]},{"name":"NavigationDVD","function":[{"name":"Menu","label":"Menu","action":"{\"command\":\"Menu\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"},{"name":"Back","label":"Back","action":"{\"command\":\"Back\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"}]},{"name":"NavigationDSTB","function":[{"name":"C","label":"C","action":"{\"command\":\"C\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"},{"name":"B","label":"B","action":"{\"command\":\"B\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"},{"name":"A","label":"A","action":"{\"command\":\"A\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"}]},{"name":"TiVo","function":[{"name":"RecordedTV","label":"Recorded TV","action":"{\"command\":\"RecordedTV\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"}]},{"name":"NavigationExtended","function":[{"name":"Guide","label":"Guide","action":"{\"command\":\"Guide\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"},{"name":"Info","label":"Info","action":"{\"command\":\"Info\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"},{"name":"Exit","label":"Exit","action":"{\"command\":\"Exit\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"},{"name":"PageDown","label":"Page Down","action":"{\"command\":\"PageDown\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"},{"name":"PageUp","label":"Page Up","action":"{\"command\":\"PageUp\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"},{"name":"Clear","label":"Backspace","action":"{\"command\":\"Clear\",\"type\":\"IRCommand\",\"deviceId\":\"33967732\"}"}]},{"name":"DisplayMode","function":[{"name":"Aspect","label":"Aspect","action":"{\"command\":\"Aspect\",\"type\":\"IRCommand\",\"deviceId\":\"33967730\"}"}]}],"activityOrder":0,"tuningDefault":true,"fixit":{"33967728":{"id":"33967728","alwaysOn":false,"relativePower":false},"33967730":{"id":"33967730","power":"ON","input":"HDMI 1","alwaysOn":false,"relativePower":false},"33967729":{"id":"33967729","alwaysOn":false,"relativePower":false},"33967731":{"id":"33967731","power":"ON","input":"CBL/SAT","alwaysOn":false,"relativePower":false},"33967732":{"id":"33967732","power":"ON","alwaysOn":false,"relativePower":false}},"type":"VirtualTelevisionN","icon":"userdata: 0x4454e0","baseImageUri":"https://rcbu-test-ssl-amr.s3.amazonaws.com/"},{"label":"Bedtime","suggestedDisplay":"Default","id":18754324,"activityTypeDisplayName":"Default","controlGroup":[],"activityOrder":3,"tuningDefault":false,"fixit":{"33967728":{"id":"33967728","alwaysOn":false,"relativePower":false},"33967730":{"id":"33967730","power":"OFF","alwaysOn":false,"relativePower":false},"33967729":{"id":"33967729","alwaysOn":false,"relativePower":false},"33967731":{"id":"33967731","power":"OFF","alwaysOn":false,"relativePower":false},"33967732":{"id":"33967732","power":"OFF","alwaysOn":false,"relativePower":false}},"type":"VirtualGeneric","icon":"userdata: 0x4454e0","baseImageUri":"https://rcbu-test-ssl-amr.s3.amazonaws.com/"},{"label":"Downstairs Lamp","suggestedDisplay":"Default","id":18833497,"activityTypeDisplayName":"Default","controlGroup":[],"activityOrder":1,"tuningDefault":false,"fixit":{"33967728":{"id":"33967728","alwaysOn":false,"relativePower":false},"33967730":{"id":"33967730","power":"OFF","alwaysOn":false,"relativePower":false},"33967729":{"id":"33967729","alwaysOn":false,"relativePower":false},"33967731":{"id":"33967731","power":"OFF","alwaysOn":false,"relativePower":false},"33967732":{"id":"33967732","power":"OFF","alwaysOn":false,"relativePower":false}},"type":"VirtualGeneric","icon":"userdata: 0x4454e0","baseImageUri":"https://rcbu-test-ssl-amr.s3.amazonaws.com/"},{"label":"Chromecast","suggestedDisplay":"Default","id":18751389,"activityTypeDisplayName":"Default","controlGroup":[{"name":"Volume","function":[{"name":"Mute","label":"Mute","action":"{\"command\":\"Mute\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"},{"name":"VolumeDown","label":"Volume Down","action":"{\"command\":\"VolumeDown\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"},{"name":"VolumeUp","label":"Volume Up","action":"{\"command\":\"VolumeUp\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"}]},{"name":"DisplayMode","function":[{"name":"Aspect","label":"Aspect","action":"{\"command\":\"Aspect\",\"type\":\"IRCommand\",\"deviceId\":\"33967730\"}"}]}],"activityOrder":4,"tuningDefault":false,"fixit":{"33967728":{"id":"33967728","alwaysOn":false,"relativePower":false},"33967730":{"id":"33967730","power":"ON","input":"HDMI 1","alwaysOn":false,"relativePower":false},"33967729":{"id":"33967729","alwaysOn":false,"relativePower":false},"33967731":{"id":"33967731","power":"ON","input":"Game","alwaysOn":false,"relativePower":false},"33967732":{"id":"33967732","power":"OFF","alwaysOn":false,"relativePower":false}},"type":"VirtualDvd","icon":"userdata: 0x4454e0","baseImageUri":"https://rcbu-test-ssl-amr.s3.amazonaws.com/"},{"label":"Music on Stereo","suggestedDisplay":"Default","id":18774883,"activityTypeDisplayName":"Default","controlGroup":[{"name":"NumericBasic","function":[{"name":"Number0","label":"0","action":"{\"command\":\"0\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"},{"name":"Number1","label":"1","action":"{\"command\":\"1\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"},{"name":"Number2","label":"2","action":"{\"command\":\"2\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"},{"name":"Number3","label":"3","action":"{\"command\":\"3\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"},{"name":"Number4","label":"4","action":"{\"command\":\"4\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"},{"name":"Number5","label":"5","action":"{\"command\":\"5\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"},{"name":"Number6","label":"6","action":"{\"command\":\"6\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"},{"name":"Number7","label":"7","action":"{\"command\":\"7\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"},{"name":"Number8","label":"8","action":"{\"command\":\"8\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"},{"name":"Number9","label":"9","action":"{\"command\":\"9\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"}]},{"name":"Volume","function":[{"name":"Mute","label":"Mute","action":"{\"command\":\"Mute\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"},{"name":"VolumeDown","label":"Volume Down","action":"{\"command\":\"VolumeDown\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"},{"name":"VolumeUp","label":"Volume Up","action":"{\"command\":\"VolumeUp\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"}]},{"name":"NavigationBasic","function":[{"name":"DirectionDown","label":"Direction Down","action":"{\"command\":\"DirectionDown\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"},{"name":"DirectionLeft","label":"Direction Left","action":"{\"command\":\"DirectionLeft\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"},{"name":"DirectionRight","label":"Direction Right","action":"{\"command\":\"DirectionRight\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"},{"name":"DirectionUp","label":"Direction Up","action":"{\"command\":\"DirectionUp\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"},{"name":"Select","label":"Select","action":"{\"command\":\"Select\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"}]},{"name":"TransportBasic","function":[{"name":"Stop","label":"Stop","action":"{\"command\":\"UsbStop\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"},{"name":"Play","label":"Play","action":"{\"command\":\"UsbPlay\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"},{"name":"Rewind","label":"Rewind","action":"{\"command\":\"UsbRewind\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"},{"name":"Pause","label":"Pause","action":"{\"command\":\"UsbPause\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"},{"name":"FastForward","label":"Fast Forward","action":"{\"command\":\"UsbFastForward\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"}]},{"name":"TransportExtended","function":[{"name":"SkipBackward","label":"Skip Backward","action":"{\"command\":\"UsbSkipBack\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"},{"name":"SkipForward","label":"Skip Forward","action":"{\"command\":\"UsbSkipForward\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"}]},{"name":"NavigationDVD","function":[{"name":"Return","label":"Return","action":"{\"command\":\"Return\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"}]},{"name":"GameType3","function":[{"name":"Home","label":"Home","action":"{\"command\":\"Home\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"}]},{"name":"RadioTuner","function":[{"name":"FM","label":"FM","action":"{\"command\":\"FM\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"},{"name":"AM","label":"AM","action":"{\"command\":\"AM\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"},{"name":"PrevPreset","label":"Prev Preset","action":"{\"command\":\"PresetPrev\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"},{"name":"ScanDown","label":"Scan Down","action":"{\"command\":\"TuneDown\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"},{"name":"ScanUp","label":"Scan Up","action":"{\"command\":\"TuneUp\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"},{"name":"NextPreset","label":"Next Preset","action":"{\"command\":\"PresetNext\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"},{"name":"DirectTune","label":"Direct Tune","action":"{\"command\":\"DirectTune\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"}]},{"name":"Setup","function":[{"name":"Sleep","label":"Sleep","action":"{\"command\":\"Sleep\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"}]}],"activityOrder":2,"tuningDefault":false,"fixit":{"33967728":{"id":"33967728","alwaysOn":false,"relativePower":false},"33967730":{"id":"33967730","power":"OFF","alwaysOn":false,"relativePower":false},"33967729":{"id":"33967729","alwaysOn":false,"relativePower":false},"33967731":{"id":"33967731","power":"ON","input":"Internet Radio","alwaysOn":false,"relativePower":false},"33967732":{"id":"33967732","power":"OFF","alwaysOn":false,"relativePower":false}},"type":"VirtualCdMulti","icon":"userdata: 0x4454e0","baseImageUri":"https://rcbu-test-ssl-amr.s3.amazonaws.com/"},{"label":"PowerOff","suggestedDisplay":"Default","id":-1,"activityTypeDisplayName":"Default","controlGroup":[],"tuningDefault":false,"fixit":{"33967728":{"id":"33967728","alwaysOn":false,"relativePower":false},"33967730":{"id":"33967730","power":"OFF","alwaysOn":false,"relativePower":false},"33967729":{"id":"33967729","alwaysOn":false,"relativePower":false},"33967731":{"id":"33967731","power":"OFF","alwaysOn":false,"relativePower":false},"33967732":{"id":"33967732","power":"OFF","alwaysOn":false,"relativePower":false}},"type":"PowerOff","icon":"Default"},{"label":"Fire TV","suggestedDisplay":"WatchFireTV","id":18751326,"activityTypeDisplayName":"Default","controlGroup":[{"name":"Volume","function":[{"name":"Mute","label":"Mute","action":"{\"command\":\"Mute\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"},{"name":"VolumeDown","label":"Volume Down","action":"{\"command\":\"VolumeDown\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"},{"name":"VolumeUp","label":"Volume Up","action":"{\"command\":\"VolumeUp\",\"type\":\"IRCommand\",\"deviceId\":\"33967731\"}"}]},{"name":"NavigationBasic","function":[{"name":"DirectionDown","label":"Direction Down","action":"{\"command\":\"DirectionDown\",\"type\":\"IRCommand\",\"deviceId\":\"33967729\"}"},{"name":"DirectionLeft","label":"Direction Left","action":"{\"command\":\"DirectionLeft\",\"type\":\"IRCommand\",\"deviceId\":\"33967729\"}"},{"name":"DirectionRight","label":"Direction Right","action":"{\"command\":\"DirectionRight\",\"type\":\"IRCommand\",\"deviceId\":\"33967729\"}"},{"name":"DirectionUp","label":"Direction Up","action":"{\"command\":\"DirectionUp\",\"type\":\"IRCommand\",\"deviceId\":\"33967729\"}"},{"name":"Select","label":"Select","action":"{\"command\":\"OK\",\"type\":\"IRCommand\",\"deviceId\":\"33967729\"}"}]},{"name":"TransportBasic","function":[{"name":"Stop","label":"Stop","action":"{\"command\":\"Stop\",\"type\":\"IRCommand\",\"deviceId\":\"33967729\"}"},{"name":"Play","label":"Play","action":"{\"command\":\"Play\",\"type\":\"IRCommand\",\"deviceId\":\"33967729\"}"},{"name":"Rewind","label":"Rewind","action":"{\"command\":\"Rewind\",\"type\":\"IRCommand\",\"deviceId\":\"33967729\"}"},{"name":"Pause","label":"Pause","action":"{\"command\":\"Pause\",\"type\":\"IRCommand\",\"deviceId\":\"33967729\"}"},{"name":"FastForward","label":"Fast Forward","action":"{\"command\":\"FastForward\",\"type\":\"IRCommand\",\"deviceId\":\"33967729\"}"}]},{"name":"TransportExtended","function":[{"name":"SkipBackward","label":"Skip Backward","action":"{\"command\":\"SkipBackward\",\"type\":\"IRCommand\",\"deviceId\":\"33967729\"}"},{"name":"SkipForward","label":"Skip Forward","action":"{\"command\":\"SkipForward\",\"type\":\"IRCommand\",\"deviceId\":\"33967729\"}"}]},{"name":"NavigationDVD","function":[{"name":"Menu","label":"Menu","action":"{\"command\":\"Menu\",\"type\":\"IRCommand\",\"deviceId\":\"33967729\"}"},{"name":"Back","label":"Back","action":"{\"command\":\"Back\",\"type\":\"IRCommand\",\"deviceId\":\"33967729\"}"}]},{"name":"NavigationDSTB","function":[{"name":"Search","label":"Search","action":"{\"command\":\"Search\",\"type\":\"IRCommand\",\"deviceId\":\"33967729\"}"}]},{"name":"GameType3","function":[{"name":"SmartMenu","label":"Home","action":"{\"command\":\"Home\",\"type\":\"IRCommand\",\"deviceId\":\"33967729\"}"}]},{"name":"NavigationExtended","function":[{"name":"Exit","label":"Exit","action":"{\"command\":\"Exit\",\"type\":\"IRCommand\",\"deviceId\":\"33967729\"}"},{"name":"Exit","label":"Esc","action":"{\"command\":\"Exit\",\"type\":\"IRCommand\",\"deviceId\":\"33967729\"}"}]},{"name":"DisplayMode","function":[{"name":"Aspect","label":"Aspect","action":"{\"command\":\"Aspect\",\"type\":\"IRCommand\",\"deviceId\":\"33967730\"}"}]}],"activityOrder":5,"tuningDefault":false,"fixit":{"33967728":{"id":"33967728","alwaysOn":false,"relativePower":false},"33967730":{"id":"33967730","power":"ON","input":"HDMI 1","alwaysOn":false,"relativePower":false},"33967729":{"id":"33967729","alwaysOn":false,"relativePower":false},"33967731":{"id":"33967731","power":"ON","input":"TV/CD","alwaysOn":false,"relativePower":false},"33967732":{"id":"33967732","power":"OFF","alwaysOn":false,"relativePower":false}},"type":"VirtualGeneric","icon":"userdata: 0x4454e0","baseImageUri":"https://rcbu-test-ssl-amr.s3.amazonaws.com/"}]

--------------------------

**Comment by bwssytems** [comment]
Interesting, so Bedtime and Downstairs I assume are the lighting activities. They have different layout with something called activity order. I'll need to look into the harmony api a bit more.

Thanks for the info!

**Comment by johndietrich** [comment]
Sorry, that's just be being stupid. :-(  The Harmony activity is called Downstairs Lamp. (The Lifx bulb is named Living Room Lamp in the Lifx app, so I just got confused.)  I called the Harmony activity something different because Alexa couldn't distinguish between "Turn the Living Room Lamp off" (Harmony activity) and "Tell LIFX to turn the Living Room Lamp off" (Alexa using LIFX skill to turn the lamp off).


Which gets to why I'm using the Harmony hub to control the bulb in the first place -- since Alexa doesn't supprt LIFX directly (as with WeMo) but only through a skill, you have to say "Alexa, tell LIFX to turn ____ on/off."


What does it say about our world when I'm going through all this trouble just to avoid saying three extra words? :-)


________________________________

**Comment by bwssytems** [comment]
Ok, I have a hunch. I think the activity is a toggle. Put the ON URL text into the OFF URL text and try that.

**Comment by johndietrich** [comment]
I was really optimistic that you were on to something there, because it makes a ton of sense -- but I tried it and no, it's not a toggle. Triggering the OFF URL after the activity has started seems to do nothing -- the Hub already knows the activity is "active" so it doesn't restart it, either. (I can tell because the "TV" activity does a lot of things like change the receiver HDMI input and tunes to a specific cable channel on the DVR, so I'd see that IR activity happening.)


Based on all the (limited) documentation I've been able to find, I'm inclined to think that maybe it's just not possible to power off a specific activity. The older versions of the Harmony API that I've seen people write code around seem to have the idea that only one activity can be running at a time, so the generic "-1" power off is all you need. But yet somehow the Harmony app manages to have multiple activities running at one time and lets you power them off independently of one another, so I don't know how it does that -- but maybe that level of control isn't exposed in the API.


________________________________

**Comment by bwssytems** [comment]
I am at a loss right now for this. I'll configure a light and create an activity for it and do some tests.

**Comment by bwssytems** [comment]
I just had an epiphany on some of the call structure to the harmony ip that I will need to validate. The call structure for the url is "vnd.logitech.harmony/vnd.logitech.harmony.engine?startactivity", so I need to see of there is an "?endactivity" type.

**Comment by bwssytems** [comment]
@johndietrich - is it possible to run a wireshark dump when you execute your light commands from the remote. I need to be able to see the calls

**Comment by johndietrich** [comment]
Sure I should be able to do that. Am in Vegas this week for work but will be able to do it next week.

**Comment by bwssytems** [comment]
@johndietrich - Make sure you use the app on your phone to do it and not the remote.

Thanks!

**Comment by jayrox** [comment]
Any update on this? I was enjoying reading this conversation in understanding how this all works for my current build.

**Comment by bwssytems** [comment]
I still need some debug logs from John's setup. If you could do the same, it would be great

**Comment by bwssytems** [comment]
Looking for any updates on this issue? I would need log files or is this not important?

**Comment by johndietrich** [comment]
Hi....sorry, yes, you can close it. Shortly after I opened the issue, Echo got native support for Lifx bulbs, so I no longer needed to use the Harmony as a workaround. So at this point it would be intellectually interesting to figure out, but not necessary. :-) Thanks!
