### ISSUE TITLE
Where do install the nssm before installing it?

### ISSUE THREAD

**Issue by michaelhinchey** [bwssytems/ha-bridge#541]
Do I download and install this file in the java folder before I install it through CMD?

**Comment by sirmax1** [comment]
You do not need to install nssm, just put it in your root drive and make your scripts for it run the java app.

**Comment by michaelhinchey** [comment]
I should have said where do I place the file not install.  Poor choice of words.  Thank you for the reply .

**Comment by sirmax1** [comment]
You can place it anywhere on your local drive, i made a folder called scripts and keep it in there with my scripts for nssm.

**Comment by michaelhinchey** [comment]
Thank you
