### ISSUE TITLE
Has the add device method changed with 4.2.1

### ISSUE THREAD

**Issue by tuicemen** [bwssytems/ha-bridge#542]
I updated from 4.1.4 to 4.2.1 (Had issues with 4.2.0 not closing)
Now when I attempt to add a device using the post method I get errors
Even the examples in the help file throw errors now
Is there now a new required field I'm missing?
If I add a device from the bridge itself it works.

**Comment by bwssytems** [comment]
Make sure you check your escapes for the quotes. Too many and it is not correct or too little. The best way to get an examples is to turn on debug for the com.bwssystems.HABridge.devicemanagmeent and 	com.bwssystems.HABridge.dao.DeviceRepository and look at the outputs.

**Comment by tuicemen** [comment]
My method of adding a device has not changed, something has changed in the bridge.
Even Postman for chrome throws a error when using it with 4.2.1
If I revert to 4.1.4 the exact same script works.
Sample:
post http://localhost/api/devices
Body {"name":"DeviceName","deviceType":"exec","offUrl":"c:/alex10/alex10.exe SENDPLC_A6_Off","dimUrl":"c:/alex10/alex10.exe SENDPLC_A6_Dim ${intensity.percent}","onUrl":"c:/alex10/alex10.exe SENDPLC_A6_On","inactive":false,"noState":false}

**Comment by tuicemen** [comment]
Debug tells me  that the issue is with the OnURL But I don't understand  why same exact same put works with older bridge versions.
what am I missing?
03-13-2017 08:34:23.193	DEBUG	Create a Device(s) - request body: {"name":"DeviceName","deviceType":"exec","offUrl":"c:/alex10/alex10.exe SENDPLC_A6_Off","dimUrl":"c:/alex10/alex10.exe SENDPLC_A6_Dim ${intensity.percent}","onUrl":"c:/alex10/alex10.exe SENDPLC_A6_On","inactive":false,"noState":false}	com.bwssystems.HABridge.devicemanagmeent.DeviceResource
03-13-2017 08:34:23.195	DEBUG	Bad on URL JSON in create device(s) for name: DeviceName with on URL: c:/alex10/alex10.exe SENDPLC_A6_On	com.bwssystems.HABridge.devicemanagmeent.DeviceResource
03-13-2017 08:34:24.728	DEBUG	Sending notify packet for upnp.	com.bwssystems.HABridge.upnp.UpnpListener
03-13-2017 08:34:24.729	INFO	Traceupnp: sendUpnpNotify notifyTemplate is <<<NOTIFY * HTTP/1.1
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 LOCATION: http://localhost:80/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 NTS: ssdp:alive
 hue-bridgeid: 000088FFFE00BBEE
 NT: uuid:2f402f80-da50-11e1-9b23-00008800bbee
 USN: uuid:2f402f80-da50-11e1-9b23-00008800bbee
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener
03-13-2017 08:34:26.534	DEBUG	isSSDPDiscovery Found message to be an M-SEARCH message.	com.bwssystems.HABridge.upnp.UpnpListener
03-13-2017 08:34:26.534	DEBUG	isSSDPDiscovery Got SSDP packet from 192.168.0.100:56531, body: M-SEARCH * HTTP/1.1
 HOST: 239.255.255.250:1900
 MAN: "ssdp:discover"
 MX: 1
 ST: urn:dial-multiscreen-org:service:dial:1
 USER-AGENT: Google Chrome/56.0.2924.87 Windows
 
	com.bwssystems.HABridge.upnp.UpnpListener
03-13-2017 08:34:27.534	DEBUG	isSSDPDiscovery Found message to be an M-SEARCH message.	com.bwssystems.HABridge.upnp.UpnpListener
03-13-2017 08:34:27.534	DEBUG	isSSDPDiscovery Got SSDP packet from 192.168.0.100:56531, body: M-SEARCH * HTTP/1.1
 HOST: 239.255.255.250:1900
 MAN: "ssdp:discover"
 MX: 1
 ST: urn:dial-multiscreen-org:service:dial:1
 USER-AGENT: Google Chrome/56.0.2924.87 Windows
 
	com.bwssystems.HABridge.upnp.UpnpListener
03-13-2017 08:34:28.534	DEBUG	isSSDPDiscovery Found message to be an M-SEARCH message.	com.bwssystems.HABridge.upnp.UpnpListener
03-13-2017 08:34:28.535	DEBUG	isSSDPDiscovery Got SSDP packet from 192.168.0.100:56531, body: M-SEARCH * HTTP/1.1
 HOST: 239.255.255.250:1900
 MAN: "ssdp:discover"
 MX: 1
 ST: urn:dial-multiscreen-org:service:dial:1
 USER-AGENT: Google Chrome/56.0.2924.87 Windows
 
	com.bwssystems.HABridge.upnp.UpnpListener
03-13-2017 08:34:29.536	DEBUG	isSSDPDiscovery Found message to be an M-SEARCH message.	com.bwssystems.HABridge.upnp.UpnpListener
03-13-2017 08:34:29.536	DEBUG	isSSDPDiscovery Got SSDP packet from 192.168.0.100:56531, body: M-SEARCH * HTTP/1.1
 HOST: 239.255.255.250:1900
 MAN: "ssdp:discover"
 MX: 1
 ST: urn:dial-multiscreen-org:service:dial:1
 USER-AGENT: Google Chrome/56.0.2924.87 Windows
 
	com.bwssystems.HABridge.upnp.UpnpListener
03-13-2017 08:34:36.857	DEBUG	httpMethod:get, uri: /system/logmsgs	spark.webserver.MatcherFilter
03-13-2017 08:34:36.857	DEBUG	get params	spark.Request
03-13-2017 08:34:36.857	DEBUG	get splat	spark.Request
03-13-2017 08:34:36.857	DEBUG	Get logmsgs.	com.bwssystems.HABridge.SystemControl

**Comment by bwssytems** [comment]
To see the difference, add a device using the UI and it will log what it looks like. Use that as your template.

**Comment by tuicemen** [comment]
OK so the add device method has changed!
**Previously this Worked:**`{"name":"Bridge Test","deviceType":"exec","offUrl":"C:/Alex10/Alex10.exe SENDPLC_B15_Off","dimUrl":"C:/Alex10/Alex10.exe SENDPLC_B15_Dim ${intensity.percent}","onUrl":""C:/Alex10/Alex10.exe SENDPLC_B15_On","inactive":false,"noState":false}
`

**Now it is required to be sent like this:**`{"name":"Bridge Test","deviceType":"exec","offUrl":"[{\"item\":\"C:/Alex10/Alex10.exe SENDPLC_B15_Off\"}]","dimUrl":"[{\"item\":\"C:/Alex10/Alex10.exe SENDPLC_B15_Dim ${intensity.percent}\"}]","onUrl":"[{\"item\":\"C:/Alex10/Alex10.exe SENDPLC_B15_On\"}]","inactive":false,"noState":false}`

Is the reason for this the multi call add or something else?

**Comment by bwssytems** [comment]
Ahh, yes the UI automatically does that now. THere is a check for the constructs on the add device. Silly me, I assume too much

**Comment by tuicemen** [comment]
So this is to be the new method for adding?
Or will a new bridge update revert back to the old method?
Just wish to know if I should be recoding my application.

**Comment by bwssytems** [comment]
It is a permanent enhancement, this will stay.

**Comment by tuicemen** [comment]
Ok Thanks.
