### ISSUE TITLE
Google Home not working and Philips Hue app is working

### ISSUE THREAD

**Issue by harolds** [bwssytems/ha-bridge#544]
For some reason the discovery of the virtual Hue lamps (from my Domoticz server) is not working from the Google Home settings app. I keep getting back the Philips Hue login screen. I have read all issues and info I could find about this but that did not help until now.

My phone (with both the Philips Hue app and Google Home app) and the Google Home are connected to the same Wifi router (FRITZ!Box Fon WLAN 7360).

I do see a discovery broadcast in the logs that could have been from the Google Home. See the attached file.
Any help would be great!

[ha-bridge-log.txt](https://github.com/bwssytems/ha-bridge/files/838205/ha-bridge-log.txt)

**Comment by bwssytems** [comment]
Comment posted in another issue #237 Yesterday by huongminh:

"BTW, after the latest release of Google Home App Mar. 2nd, Google Home cannot discover Habridge anymore but would lead to the Hue account log in screen and one would have to control Hue Bulb via the cloud which is very slow. To overcome this, I had to install an older version of Google Home app on a Android Device and do the link. That did the trick for me so far."

**Comment by huongminh** [comment]
Yes. And here is the link for a working version of google home apk (I tried the 1.20.9) http://www.apkmirror.com/apk/google-inc/google-home/

**Comment by harolds** [comment]
I wanted to try your work around but first my Samsung S3 is too old to be used as Google Home setup device. The latest version that working on my S3 is 1.19.29 but that version does not seem to have Philips Hue setup support :-(. But after reinstalling multiple times not 1.20.9 does work (go wonder...)

But I can't find how to setup the link in the setup app. Just does not seem to be there...

I hope it can be fixed in the ha-bridge application. Maybe its some timing issue. The fact remains that the official Hue app is working with ha-bridge and Domoticz and the Google Home iPhone app is not.

**Comment by bwssytems** [comment]
The ha-bridge application is not the issue. Please search on google home in the closed issues.

**Comment by harolds** [comment]
Thanks for the info. I did not yet know that there was an closed issue list :-).
Well looked through it but did not find out why its not working. I will reread everything soon.

**Comment by bwssytems** [comment]
There was something special you had to do in the app i remember seeing for the philips hue.

**Comment by bwssytems** [comment]
https://github.com/bwssytems/ha-bridge/issues/216

**Comment by huongminh** [comment]
I think 1.19.29 should work as well as 1.20.9. Make sure both google home and the android device are in the same WIFI network. Google home app google home device are logged by the same account and you can see the Home Control option in the setting menu. I tried it on my android tv box and got tricky when could not find the Home Control option in the setting menu even my Android box was connected in the same subnet as the google home device, but via ethernet port. When I was going to give up I tried to connect via WIFI instead and voila... it came the Home Control option in the menu, under home assisstant.

**Comment by durzo** [comment]
1.20.9 nor 1.19.29  works for me, I have turned off my amazon echo and still Home app just opens the hue website when i click on Hue. I can confirm I have habridge on a dedicated local IP on port 80 with strict upnp fully working.

One thing I'm not sure of but I don't actually own a Google Home device, im just trying to set it up via the Google Assistant (pixel). I say "turn on my lights" and it prompts me to open the Home Controll settings app - Do i actually need a Google Home Hub for this to work through habridge?

**Comment by durzo** [comment]
Answering my own question.. it seems you need to have a Google Home Hub for this to work ala #464

**Comment by bwssytems** [comment]
Ahh, we thought you had one and were running into the new issue of the app going to the meethue.com instead of a local search. Closing

**Comment by harolds** [comment]
Well for me the isssue is not closed. I can not get it connected even when reading all the closed issues. Thats a pitty (for me and possible others with this same issue). I think I will test the other Philips Hue bridge to check if that has the same issue.

**Comment by bwssytems** [comment]
Sorry @harolds that is correct for you. But this is still not an ha-bridge issue

**Comment by harolds** [comment]
Yep it might not be an ha-bridge issue because testing with the amazon-echo-ha-bridge application has the same result (so none). I switched to a different wifi accesspoint (for my Google Home, ha-bridge system and Google Home app on iPhone) and still get the Philips Hue login screen. Tested ha-bridge on wifi only and with the correct IP setting in ha-bridge, and even with '0.0.0.0' as IP address. Makes no difference.

So my conclusion for now it that its not possible anymore to use the Google Home with a virtual Hue bridge. Must be the home app or the device itself that fails to communicate.

**Comment by wimbuh** [comment]
Having the same problem with the new Google Home app version 1.21 . But I have an Iphone. So the android apk link does not work for me.  Does anybody have a link to an older version of the app on IOS. Have done some tutorials on how to downgrade apps on IOS without succes. ( Did not have a backup of the app on itunes. Maybe somebody has an .ipa file of the older version). 

Or maybe another workaround how to get the google home connected to my HA bridge again would be highly appreciated.

**Comment by bwssytems** [comment]
there is no other workaround as they changed the app to go to the hue cloud.

**Comment by wimbuh** [comment]
Unfortunate. Then I have to get hold of an previous version of the "google home" ios app. I will post here if I get hold of one.

**Comment by Ram0909** [comment]
So basically, now it isn't possible to use HA bridge with Google Home?

**Comment by huongminh** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } You can still use an old version of the google home app to link with habridge. 


Sent from Yahoo Mail for iPhone


On Sunday, April 2, 2017, 4:09 PM, Ram0909 <notifications@github.com> wrote:


So basically, now it isn't possible to use HA bridge with Google Home?

**Comment by rwoolf** [comment]
I have tried using every old apk version but when I select Philip hue it always takes me to hue-adapter.appspot.com. Has google made it so that even old apks will no longer work?

I can find no way for GH to directly look for my ha-bridge

**Comment by dony71** [comment]
It seems google try to kill emulated home bridge
This is not a good sign

**Comment by ashug987** [comment]
Any idea how to get it working? My system was working fine until yesterday and then stopped working today (May 6th, 2017). I have tried installing the older version as well without any luck

**Comment by Matt8119** [comment]
i was reading on the home assistant forums site to see if anyone has had any luck with a work around for this issue.  a user stated that: "dit2: just got off the phone with google support... they confirmed this was a change made." it mentions that it was a request made by HUE on how the HUE is discovered with the google home app...   

https://community.home-assistant.io/t/google-home-hue-setup-change/13159

**Comment by harolds** [comment]
I got it fixed! See https://github.com/bwssytems/ha-bridge/issues/626
