### ISSUE TITLE
wrong device triggered from alexa command

### ISSUE THREAD

**Issue by tuicemen** [bwssytems/ha-bridge#545]
I asked Alexa to turn on a device which had a bridge ID # of 3 & row#11.
instead the bridge turned on the device which was listed in row  #3 & Bridge ID of 13
Thinking it was just a fluke I tried again with the same result .
I'll try again tomorrow as today is the 13th.
Bug, just strange or what?

**Comment by bwssytems** [comment]
that is not enough info.  turn debug on and post log

**Comment by tuicemen** [comment]
Duh!!!  why didn't I think of that????
I probably wouldn't even of notice the issue except the TV was on and the command to turn on the light changed the TV input.
I tried again this morning a couple of times and am unable to repeat the issue so it appears there is something else in the mix. I'll a tempt a few more time threw the day but it is looking like it was just a fluke.

**Comment by audiofreak9** [comment]
@tuicemen were you able to try this again?

**Comment by tuicemen** [comment]
I have attempted to recreate this a few times today without success so it is looking more and more like a freak incident.
If I can't recreate by days end I'll close  this.

**Comment by tuicemen** [comment]
Ok I managed to semmi duplicate this though not with the same devices Alexa clearly heard me correctly say turn on bedroom light Id#3 but turned on id#7 (checked her history) log shows Bridge get #7 
`03-14-2017 19:19:19.048	DEBUG	Sending notify packet for upnp.	com.bwssystems.HABridge.upnp.UpnpListener
03-14-2017 19:19:19.049	INFO	Traceupnp: sendUpnpNotify notifyTemplate is <<<NOTIFY * HTTP/1.1
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 LOCATION: http://192.168.0.100:80/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 NTS: ssdp:alive
 hue-bridgeid: D43D7EFFFE2C0978
 NT: uuid:2f402f80-da50-11e1-9b23-d43d7e2c0978
 USN: uuid:2f402f80-da50-11e1-9b23-d43d7e2c0978
 
 >>>	com.bwssystems.HABridge.upnp.UpnpListener
03-14-2017 19:19:19.426	DEBUG	httpMethod:get, uri: /	spark.webserver.MatcherFilter
03-14-2017 19:19:21.428	DEBUG	httpMethod:get, uri: /	spark.webserver.MatcherFilter
03-14-2017 19:19:23.428	DEBUG	httpMethod:get, uri: /	spark.webserver.MatcherFilter
03-14-2017 19:19:23.430	DEBUG	httpMethod:put, uri: /api/pH2S1zhJ0t7lzN4ZfftrLqxC18vCYhU4597L0zPa/lights/7/state	spark.webserver.MatcherFilter
03-14-2017 19:19:23.430	DEBUG	get params	spark.Request
03-14-2017 19:19:23.430	DEBUG	matchedPart: :userid = pH2S1zhJ0t7lzN4ZfftrLqxC18vCYhU4597L0zPa	spark.Request
03-14-2017 19:19:23.430	DEBUG	matchedPart: :id = 7	spark.Request
03-14-2017 19:19:23.430	DEBUG	get splat	spark.Request
03-14-2017 19:19:23.430	DEBUG	hue state change requested: pH2S1zhJ0t7lzN4ZfftrLqxC18vCYhU4597L0zPa from 192.168.0.106 body: {"on": true}	com.bwssystems.HABridge.hue.HueMulator
03-14-2017 19:19:23.431	DEBUG	Decode Json for url items: [{"item":"scripts/PorchLightOn.bat"}]	com.bwssystems.HABridge.hue.HueMulator
03-14-2017 19:19:23.431	DEBUG	Exec Request called with url: scripts/PorchLightOn.bat	com.bwssystems.HABridge.plugins.exec.CommandHome
03-14-2017 19:19:23.431	DEBUG	Executing request: scripts/PorchLightOn.bat	com.bwssystems.HABridge.plugins.exec.CommandHome
03-14-2017 19:19:23.446	DEBUG	Process running: true	com.bwssystems.HABridge.plugins.exec.CommandHome
03-14-2017 19:19:23.517	DEBUG	httpMethod:get, uri: /api/pH2S1zhJ0t7lzN4ZfftrLqxC18vCYhU4597L0zPa/lights/7	spark.webserver.MatcherFilter
03-14-2017 19:19:23.518	DEBUG	get params	spark.Request
03-14-2017 19:19:23.518	DEBUG	matchedPart: :userid = pH2S1zhJ0t7lzN4ZfftrLqxC18vCYhU4597L0zPa	spark.Request
03-14-2017 19:19:23.518	DEBUG	matchedPart: :id = 7	spark.Request
03-14-2017 19:19:23.518	DEBUG	get splat	spark.Request
03-14-2017 19:19:23.518	DEBUG	hue light requested: 7 for user: pH2S1zhJ0t7lzN4ZfftrLqxC18vCYhU4597L0zPa from 192.168.0.106	com.bwssystems.HABridge.hue.HueMulator
03-14-2017 19:19:23.518	DEBUG	found device named: Porch Light	com.bwssystems.HABridge.hue.HueMulator
03-14-2017 19:19:27.646	DEBUG	httpMethod:get, uri: /	spark.webserver.MatcherFilter
03-14-2017 19:19:29.426	DEBUG	httpMethod:get, uri: /	spark.webserver.MatcherFilter
03-14-2017 19:19:31.426	DEBUG	httpMethod:get, uri: /	spark.webserver.MatcherFilter
03-14-2017 19:19:33.427	DEBUG	httpMethod:get, uri: /	spark.webserver.MatcherFilter
03-14-2017 19:19:35.427	DEBUG	httpMethod:get, uri: /	spark.webserver.MatcherFilter
03-14-2017 19:19:37.429	DEBUG	httpMethod:get, uri: /	spark.webserver.MatcherFilter
03-14-2017 19:19:39.051	DEBUG	Sending notify packet for upnp.	com.bwssystems.HABridge.upnp.UpnpListener
03-14-2017 19:19:39.051	INFO	Traceupnp: sendUpnpNotify notifyTemplate is <<<NOTIFY * HTTP/1.1
 HOST: 239.255.255.250:1900
 CACHE-CONTROL: max-age=100
 LOCATION: http://192.168.0.100:80/description.xml
 SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0
 NTS: ssdp:alive
 hue-bridgeid: D43D7EFFFE2C0978
 NT: uuid:2f402f80-da50-11e1-9b23-d43d7e2c0978
 USN: uuid:2f402f80-da50-11e1-9b23-d43d7e2c0978
 
 >>>`
I was looking more for a miss match like what I saw last night so there may have been others I missed as  there were times Alexa said ok and a different light came on so I just suspected I wasn't heard right.
this time I checked her history.

**Comment by tuicemen** [comment]
I've renumbered the devices with the bridge several times and it is always id #3 that doesn't fire correctly
I'm hoping for a better log capture.
Maybe my DB file is corrupt I'll have a look at it.

**Comment by bwssytems** [comment]
Alright, So, if you renumber devices, you will need to have Alexa forget devices and re discover. This also occurs if you delete a device and the add a new one, you need to tell alexa to forget devices and re-discover.

**Comment by tuicemen** [comment]
I don't believe that is true for renumbering , I do know it is true for removing. If you wait long enough after adding, Alexa will discover a newly added device.
You would think if a renumber required Alexa to rediscover then all devices would not respond correctly which isn't the case.
I'll do a rediscover and see what happens.
if I still get weird triggering  then I'm going to remove all devices from the bridge then re-add, re-discover and see what happens.

**Comment by bwssytems** [comment]
Alexa uses the ID it already has. If is finds the ID, it doesn't update the name.

**Comment by tuicemen** [comment]
Ok, I've been a little more diligent with having Alexa rediscover devices each time I change anything in the Bridge, even updating versions, and so far no false triggers so I'll close this!
