### ISSUE TITLE
Getting "No route to Host error" in log

### ISSUE THREAD

**Issue by lemrock** [bwssytems/ha-bridge#546]
The HA Bridge has been working perfectly for months now but last night and still today I get
"Get Vera Scenes/(Devices) Error: A Vera is not available and failed to get scenes. Check your Vera IP addresses. with status: Service Unavailable - 503".  I checked the Vera 3 IP address and it's still static and correct.  I can't list any devices or scenes in the HA Bridge.  It's running on a raspberry pi and it still looks good. What could have happened?

**Comment by audiofreak9** [comment]
You didn't mention this, have you tried rebooting your RPi?

**Comment by lemrock** [comment]
I rebooted the RPi and still the issue persists. In the HA Bridge I can see the configured devices but the list of unconfigured devices and scenes is empty when I each tab. The errors in the log look like this:
03-14-2017 04:20:59.817 	INFO 	UPNP Discovery Listener starting.... 	com.bwssystems.HABridge.upnp.UpnpListener
03-14-2017 04:20:59.822 	INFO 	UPNP Discovery Listener running and ready.... 	com.bwssystems.HABridge.upnp.UpnpListener
03-14-2017 04:29:15.408 	WARN 	Error calling out to HA gateway: IOException in log 	com.bwssystems.HABridge.plugins.http.HTTPHandler
03-14-2017 04:29:15.408 	WARN 	Error calling out to HA gateway: IOException in log 	com.bwssystems.HABridge.plugins.http.HTTPHandler
03-14-2017 04:29:30.393 	WARN 	Error calling out to HA gateway: IOException in log 	com.bwssystems.HABridge.plugins.http.HTTPHandler
03-14-2017 04:29:30.393 	WARN 	Error calling out to HA gateway: IOException in log 	com.bwssystems.HABridge.plugins.http.HTTPHandler
03-14-2017 04:29:48.393 	WARN 	Error calling out to HA gateway: IOException in log 	com.bwssystems.HABridge.plugins.http.HTTPHandler
03-14-2017 04:29:48.395 	WARN 	Error calling out to HA gateway: IOException in log 	com.bwssystems.HABridge.plugins.http.HTTPHandler
03-14-2017 04:29:51.393 	WARN 	Error calling out to HA gateway: IOException in log 	com.bwssystems.HABridge.plugins.http.HTTPHandler
03-14-2017 04:29:51.403 	WARN 	Error calling out to HA gateway: IOException in log 	com.bwssystems.HABridge.plugins.http.HTTPHandler
03-14-2017 05:43:52.271 	WARN 	Send heartbeat failed 	net.whistlingfish.harmony.HarmonyClient
03-14-2017 05:44:22.278 	WARN 	Send heartbeat failed 	net.whistlingfish.harmony.HarmonyClient
03-14-2017 05:44:52.282 	WARN 	Send heartbeat failed 	net.whistlingfish.harmony.HarmonyClient
03-14-2017 05:45:52.270 	WARN 	Send heartbeat failed 	net.whistlingfish.harmony.HarmonyClient
03-14-2017 05:46:22.278 	WARN 	Send heartbeat failed

**Comment by bwssytems** [comment]
Your Pi is not getting a route to your devices. Use curl to tests your http commands from your Pi on the command line.
