### ISSUE TITLE
Dokumentation delay and count

### ISSUE THREAD

**Issue by RobertHerter** [bwssytems/ha-bridge#547]
Hello,

i didn't find a Dokumentation for the 2 Parameters. What i try to do is the following:
1 have 2 Hue Lights and the power of these Lights is controlled via mqtt (knx).

So to dim the light if the power is off, i have to send the power-On first and than after a delay the hue on/dim command.

**Comment by bwssytems** [comment]
Read the FAQ: https://github.com/bwssytems/ha-bridge/wiki/HA-Bridge-FAQs#entries

**Comment by bwssytems** [comment]
Delay is the time in milliseconds to wait until the execution of the next item in the multi commands.

Count is how many times to repeat the current command item and the delay time is used tin between the executions.

**Comment by bwssytems** [comment]
I updated the wiki FAQ with this info

**Comment by avalokitasvara** [comment]
Something is not clear to me from this thread or the FAQ: if I only have one line, with one command, and enter a delay, does it happen before or after the command?

In other words, to have a delay before the (only) command, do I need to create an "empty" on item with just the delay, and then another on item with the command?

Thanks for ha-bridge by the way, awesome software! :)

**Comment by bwssytems** [comment]
The delay is after the command.

**Comment by avalokitasvara** [comment]
Dankeschön :)
