### ISSUE TITLE
Removing Delay or Repeat in Edit-Device results in bad Config

### ISSUE THREAD

**Issue by RobertHerter** [bwssytems/ha-bridge#548]
Removing Delay and/or Repeat in a Device-Config results in a Bad Config.

`Could not decode Json for url items: 14 for hue state change request: test from 192.168.0.83 body: {"on":true,"bri":18} url items: [{"item":"{\"clientId\":\"HABRIDGE\",\"topic\":\"knx/0/Licht/Licht_schalten/Wohnzimmer_Wandleuchten_schalten/set\",\"message\":\"${intensity.math(X>0)}\"}","type":"mqttMessage","delay":"500","count":""},{"item":"{\"ipAddress\":\"192.168.71.24\",\"deviceId\":\"12\",\"hueName\":\"Herter\"}","type":"hueDevice","delay":"","count":""},{"item":"{\"ipAddress\":\"192.168.71.24\",\"deviceId\":\"13\",\"hueName\":\"Herter\"}","type":"hueDevice","delay":"","count":""}]`

**Comment by bwssytems** [comment]
Well why do you have delay or count that are empty strings any way. They are Integers if you look at the documentation. Also, in JSON, If you don't want to provide those params, do not put them in your JSON.

**Comment by RobertHerter** [comment]
Because removing them in the WEB-UI creates the empty one, that's what i reported. I know that i could remove them with an editor.

**Comment by bwssytems** [comment]
Gotcha, thought you were using the api directly to add devices. will take a look. Thanks

**Comment by Twit123** [comment]
Hi,
Just wanted to point out that I had the same issue. IE Add delay in UI, save it then remove it again and you get the above error.

I just put a "0" in the delay field and it works fine again.

Simon

**Comment by bwssytems** [comment]
Yes, observed as well. Sorry for the rough questions.
