### ISSUE TITLE
Add Possibility to change order of Multicommand

### ISSUE THREAD

**Issue by RobertHerter** [bwssytems/ha-bridge#549]
Please add the ability to change the order of Multicommands in Web-UI

**Comment by bwssytems** [comment]
Dude, cut and paste.

**Comment by RobertHerter** [comment]
I think most of the Users use the WEB-UI to edit devices not an Editor. And changing the order of 20-30 Multidevices via Copy-Add-Delete on all 3 Commands is ok, but for normal user frustrating.

**Comment by bwssytems** [comment]
That is a very rare use case to me. If most people entered multi commands and then determined all there items were out of order, then it will be still a burden to go and hit edit for all those and then change the order on the 3 items.

**Comment by bwssytems** [comment]
I will consider this a feature if others think it is useful. But currently the use case does not make sense.

If interested, give a thumbs up to Robert's comment.

**Comment by michaelhinchey** [comment]
Maybe I can be more of assistance of I new what the multicommand was for? Is it for saying one command name and multiple devices will do that command ?

**Comment by bwssytems** [comment]
This can be solved by copy and paste
