### ISSUE TITLE
How to use Ha Bridge with Harmony Hub for beginner questions

### ISSUE THREAD

**Issue by hln98** [bwssytems/ha-bridge#55]
Hello,

I am currently looking at using some home automation with Amazon Echo, using your Amazon Echo and Harmony Hub solutions. 

Ultimately, I want to use Echo to issue verbal commands so that it will direct my Harmony hub to say, Turn on TV or Turn on Movies or many of my Harmony hub activities.  

I am having trouble understanding your solutions.  I read the examples you have but failed to connect the two together.

What I have so far:

1.  I have a raspberry pi 2 up and running
2.  Installed the Ha Bridge jar and ran it and saw the configuration where I can add my devices
3.  Downloaded the Restful Harmony Hub jar and ran the jar.  When I did  "GET http://host:8081/harmony/list/activities”, I saw my harmony hub activities and all.  Great.

Questions:

a. Now, how do I do a Post, to get my Harmony activities into my Amazon Echo? 

b. Do I copy the results from the “GET” earlier on step 3 above, into a json file and then post it to the running HA Bridge? 

c. or do I post it to the Harmony Hub bridge?

When you said in your Ha Bridge direction:

"POST http://host:8080/api/devices"
Does this mean “devices” is a file that has the text I get from “GET” command issued in the Harmony Hub.  This Post will copy that into Ha Bridge?  Please please help.  

Pardon as I am new to Linux world.  Though, I was able to install “HomeBridge” and can use Siri to control my Nest, but I would like some help on questions above.  Please don’t be shy to assume that I know nothing and be very very specific.  Thanks in advance.

Thank you.

**Comment by bwssytems** [comment]
So the first thing is you do not have to run restful-harmony. That is a standalone program that does not interface with the echo.
 
The ha-bridge has all you need. Use the latest version, 1.4.0, and it has a bridge control page to setup the address and login for your harmony.
 
Then you will be able to add devices.

**Comment by hln98** [comment]
Ok I saw the bridge control page and entered my Harmony hub name, IP address, user name and password. Clicked on save. Now how do I start adding devices?

How about some detail write up please.  Be very specific please please.  Thanks.

**Comment by audiofreak9** [comment]
I'd suggest reading the README, config URL is detailed here: https://github.com/bwssytems/ha-bridge#ha-bridge-device-configuration.  Short answer is http://<ip address>:<port>

**Comment by npaisnel** [comment]
Did you ever get this working with Harmony Hub
I now have ha bridge Jar 5.4.0 and Bridge Control page show 
Name - IP - Webhook

earlier in this question there was mention of Harmony user name AND password

in the Bridge Control page to add a Harmony hub there is a Name entry...

But what is ‘Name’ what is it expecting? The name of the hub? Your log-in user name ? A friendly user name ?


Same as the Webhook entry ... what is that ? What goes in there ?
