### ISSUE TITLE
No go on Synology

### ISSUE THREAD

**Issue by yaggayoyo** [bwssytems/ha-bridge#550]
I have installed this on my synology via Docker and following the instructions but I cant seem to get the IP or page to login to portal. What am i doing wrong? The logs show no IP or Port despite my configure stating one.

**Comment by audiofreak9** [comment]
Typically (most of the time) the Synology will already be using the ports set as defaults on the ha-bridge, so make sure you are setting the bridge to run on unused ports.  Neither BWS Systems nor I use Docker so I would post this over to https://github.com/bwssytems/docker-ha-bridge.
