### ISSUE TITLE
Ability to have two bridges running at same time?

### ISSUE THREAD

**Issue by michaelhinchey** [bwssytems/ha-bridge#552]
s it possible to have two bridges running simultaneously?   
    I have two computers and occasionally I need to turn them off but not simultaneously,  I would still like to have access 100% of the time aND not have to wait for next reboot

**Comment by tuicemen** [comment]
it is possible to run two Bridges at the same time. What you can't do is have them configured with the same devices with the same names.
Well you can but it confuses Alexa. A way around this would be to have the devices named slightly different maybe with A/B or 1/2 though Alexa has difficulty with numbers sometimes.  Amazon suggests avoiding them.

**Comment by audiofreak9** [comment]
If you run the ha-bridge with systemctl you could keep one on "hot stand by".  Just stop the bridge on one with the `$ sudo systemctl stop habridge` command.  When you want to swap computers just run `$ sudo systemctl stop habridge` on the one coming out of service, and `$ sudo systemctl start habridge` on the other going into service.

**Comment by michaelhinchey** [comment]
@audiofreak9
  Thank you for the reply, however I was hoping for a seemless integration.  While this is a great option and there probaby is a way to code all of the above you have stated and maybe even automate the codes it is a bit out of my league.  
   @tuicemen this is something that I can already do with Alexa and Vera.  Vera is just starting to come out of beta with a decent working firmware that would allow me to run both.   I don't want to completely ditch the bridge because I think it has way more control over how vera and alexa work.  Although I do have the vera/alexa skill working much better with the thermostat that I have.  I do understand that alexa gets confused with two of the same name or numbers in the name and this has been a crutch of Alexa.  For now I'll live.  Lol. Thank you both for the replies

**Comment by michaelhinchey** [comment]
Also @audiofreak is that code for Windows or rasp pi?  I should have been more clear and stated both are windows.  I haven't made the jump yet but really would love to soon since it is a much lower cost to run that instead of a windows htpc.

**Comment by audiofreak9** [comment]
@michaelhinchey The systemctl command is for RPi (Linux) not Windows.  The ~$25 investment in an RPi will be well worth the 4watts it takes to run it vs. the typical 25watts of a PC (or more), plus you can just set it and forget it, no need to swap between Windows machines.  If you are invested in using the ha-bridge then the RPi is a no brainer purchase.

**Comment by tuicemen** [comment]
@michaelhinchey 
I had two Windows PCs with the bridge configured the same on both PCs as long as only one is running the bridge you'll have no issues Alexa will see the bridge that is on line and report all the devices on it as on line. The devices on the bridge which is not running will be reported as off line.
So as long as you remember to only have one bridge running at a time you should have no problems.

**Comment by michaelhinchey** [comment]
@tuicemen Understood.  However, I rarely turn both my pc s off.  I've been looking for ways to do so but really haven't found any and still have the bridge running.  Sometimes my gf will be on pc in bedroom and I'll be in the living room so that is not an option.   It is in a perfect world though. Thx for the option and reply.

**Comment by michaelhinchey** [comment]
I did buy a rpi 3 about a yr ago but it sat because I has some issues with work I needed to get done and then didn't have time to work on it.  So I returned it.  I did buy a rpi zero at the time because it was .99 cents.  Still sitting.lol. 
    Maybe I will invest in the pi.  Is the original one ok and still will work?  I've never used the software for this and I guess it's command based.  Any help there would be great. Thx

**Comment by audiofreak9** [comment]
I'd suggest an RPi B+ or newer.  Just follow the README for setup on the RPi.  Otherwise are you good to go on this issue.

**Comment by michaelhinchey** [comment]
Yes thank you. Sorry I didn't reply back.   I'm sure I will need more help whenever I goto build the bridge since this will be the first time I am working outside of windows.
