### ISSUE TITLE
Pull Status from http api

### ISSUE THREAD

**Issue by yaggayoyo** [bwssytems/ha-bridge#554]
Using the GUI, how do you setup a polling interval for http api. I am using this for AirFoil implementation and if i turn off the speakers from AirFoil App or is disconnects from Wifi this is not reflected in Smartthings connected to HA Bridge.

**Comment by bwssytems** [comment]
The ha-bridge does not poll for device state updates from it's target. It just remembers what the last state that it was called with.  To poll, you could like at some comments in #484

**Comment by yaggayoyo** [comment]
Truthfully, this is above my head. Where is the gui so I put the  the PUT url?

**Comment by bwssytems** [comment]
There isn't one, you need to write a script to update the ha-bridge from your called source using http commands for REST API's.

**Comment by audiofreak9** [comment]
There is an [AirFoil API](https://github.com/jnewland/airfoil-api) someone put on github that you could leverage to poll your AirFoil device states to update the ha-bridge.

**Comment by bwssytems** [comment]
Not any interest in this.
