### ISSUE TITLE
Importing database from original amazon-echo-ha-bridge?

### ISSUE THREAD

**Issue by 2MuchTech** [bwssytems/ha-bridge#56]
This is a question... not a bug report:

I was happily entering all of my devices into the configurator in the original HUE emulator that this project is forked from, and it was working well until Echo stopped being able to import devices (I don't know if I reached some limit on the number of devices, but it can no longer find any devices, even though I can see the log entry showing it's initiating the request).  While I was hunting for a solution I came across this much fuller-featured version of the app, but I'm wondering if there's a simple way to preserve all of the work I did entering the device info into the original app.  I've got roughly 50 devices and am not eager to have to re-enter them all manually.  I captured the data I entered via the api/devices page, so I do have a text file with all of my devices listed.  I'm interfacing with openHAB, so I'm using the manual add tab to get my devices into this emulator. Thanks.

**Comment by bwssytems** [comment]
So, it is very easy. The capture you did from the api/devices call is the base format of the device.db file. Save that data to a file without any extra returns at the ens and put that file in a direcory and point the bridve ar for the device db. Th bridge will load it.

**Comment by 2MuchTech** [comment]
Well, it wasn't quite as simple as a copy and paste, but I did finally get it to import the old database.  I had to remove ,**"httpVerb":null,"contentType":null,"contentBody":null** from each record before the new ha-bridge would recognize the file as valid.

HOWEVER, I'm still running into problems with Alexa telling me it hasn't found any connected devices.  Through some trial and error, it appears Echo cannot deal with more than 47 devices in the HUE bridge emulator.  If I stick to 47 it imports fine into Echo, but if there are >47 devices in the emulator, Echo fails to import any of them.  Has anyone else run into this?  I tried changing my 48th device to a different one just in case that was the problem, but it didn't make a difference.

**Comment by 2MuchTech** [comment]
Apparently I'm not the first to run into a limit, but for some reason the limit I'm hitting is higher than what others reported.  See: https://github.com/armzilla/amazon-echo-ha-bridge/issues/12 for some additional info on this.  It's not clear to me that the limit is in Echo... it could be something in the bridge emulator.

Is there a way to disable to UPNP listener in your version of the ha-bridge?  It appears I will need to run two instances of the bridge to get around the limitation in Echo, and I'm guessing only one instance at a time should be listening for Echo to query the database?  According to jlippold at the above URL, you don't want to leave it listening all the time anyway because Echo will end up refreshing the list without your permission.

**Comment by bwssytems** [comment]
It is a limitation with the echo as it has occurred with smartthings and wink. It seems it is based on the connection to a specific hub instance. 

The Multiple bridge solution works great and many use this method to get past the limitiation. You just have to change 2 settings, the upnp response port and the web port for each bridge you run. UPNP is already shareable on a given device.

**Comment by dale3h** [comment]
This seems like a great feature to have built-in: automatically enumerate the devices across different UPnP ports.

How difficult do you think this would this be to support?

**Comment by audiofreak9** [comment]
I can confirm it is a limit of the Echo, when IoT connections were first available on the Echo it had a 12 (or so) device limit, that Amazon was well aware of, and 'fixed' with code. Going by others who have hit the discovery limit you are pretty fortunate, many others have found the limit in the high 20's.  I too use the bridge with mostly short custom URLs to interface with my X10 equipment (along with a Harmony Hub configuration) and have not yet hit a limit with 43 configured devices.  Most who have reported discovery limits are using Vera device configurations which include more config data, Crush (@bwssystems) and I have discussed what we think is behind this seemingly random limit.  He is way more familiar with the discovery process, and has stated that the Echo only uses the device IDs for discovery so the config of the devices does not come into play, but I can't help but wonder why those with setups like ours have higher limits than those with Vera configured devices.

**Comment by 2MuchTech** [comment]
Since I'm going to have to run 2 instances of the ha-bridge anyway, I guess I should split the devices evenly between the two so I have less risk of some future problem that spontaneously lowers the (apparently high) limit I've found through testing.  It would be nice if Alexa would actually tell you that you've exceeded the limit instead of acting like she didn't even find the bridge.

What about the issue of turning off UPNP after the initial setup?  Is this not something that I should be worried about, or is there already built-in support for this in ha-bridge?  I didn't see it on the Bridge Control page.  Is the command line option for this still embedded in ha-bridge like it was the the project ha-bridge was forked from?

**Comment by 2MuchTech** [comment]
One more question... I noticed that the device IDs from the original emulator are significantly longer than the device IDs in this version of ha-bridge.  Since I'm going to have to manually manipulate the database to split it in two, I can easily edit the device IDs as well.  Is there any reason to have long numbers or can I safely use something simple like 1,2,3,4,... ?  Put differently, do the IDs have to be unique only within the list of ha-bridge entries, or do they need to be unique in the entire universe of devices that Echo knows about?

**Comment by dale3h** [comment]
As for turning off UPnP after the initial setup, what if we mimic the way that the Hue bridge does this? Alexa instructs you to press the button on the Hue bridge to enable discovery of the devices.

Would it be better to have a button on the web UI that allows the software to broadcast the devices for 60-90 seconds, or whatever amount of time that the Hue bridge does? Maybe something configurable to enable/disable manual broadcasting, and to set the time limit might be helpful.

**Comment by 2MuchTech** [comment]
Yet another question... When I built my initial database using the original bridge emulator, it assigned a deviceType of "switch" to each device.  I noticed that ha-bridge assigns a "custom" deviceType if I build the record on the Manual Add page.  How/where is this deviceType used?  I'm sending all of my bridge output to openHAB, and so far it seems to turn my lights on and off with either deviceType, but I'm wondering if there's a reason I should have them set one way vs the other.  FWIW, most of my physical devices are Dimmers, with a few Switches mixed in.

**Comment by bwssytems** [comment]
So, the first question you had was, why not enumerate the devices over the ports if given. Unfortunately, I use a framework, sparkjava, to implement the rest api's. It only allows me to have one configured web port per process. To emulate multiple bridges, it needs to be a different URL as the echo recognizes this as I tried. So that is out.

There is no need to turn off UPNP in any process. They all reply as individual devices that the echo sees.

As far as the ID's, You could assign any number you want. The random generator I use starts around 9 digits so you could go less than that.

The deviceType is a carry over from the original bridge and I use other methods to detect what to do.

**Comment by bwssytems** [comment]
Is this all set now?

**Comment by 2MuchTech** [comment]
I have split my devices into two groups and I set up two instances of the emulator.  Echo is able to discover all of my devices now, and things seem to work pretty well, but I noticed that the iPad Alexa app shows many of my devices as "Offline".  I have tried "forgetting" all devices via the iPad app and re-discovering them. After some period of time (less than an hour I believe), all of the devices from one or the other instance of ha-bridge will grey out and display "Offline" (all devices from the other instance of ha-bridge continue to show as online).  I can still use these Offline devices from Echo, and after using a device it will revert back to an Online status in the Alexa app for a while, but after some additional period of time it goes back to Offline again.  Only the device(s) I actually use will revert to Online... the rest in that group still show Offline.  It doesn't seem to affect my ability to control devices, but I find it a little disconcerting that Echo seems to think all of the devices in one of my ha-bridge groups is Offline.

I don't know if this is related, but I have also noticed that sometimes the "discovery" process will only pick up one of the two bridge's devices.  I eventually got all devices from both instances to be discovered, but I don't remember if I had to stop the ha-bridge process and restart it to get discovery to work.  I've had this happen several times as I was experimenting, so it's not a one-off problem.

So I think things are running well even if I have a strange Offline status problem.  I really appreciate the effort you put into creating this streamlined app.  Right now I'm running it on my OS X machine, but I plan to migrate to a Raspberry Pi at some point, so the lightweight app will be a big plus there.

**Comment by 2MuchTech** [comment]
I forgot to mention one other thing... Since I had to edit the database to get it to import, I started by separating each device onto its own line in the text file.  I did this to make it easier to read the file and perform the edits.  I fully expected I would have to put it all back on one line to get it to import into ha-bridge, but I was pleasantly surprised to find that ha-bridge is able to read the file with the line breaks in it.  If you use the GUI in ha-bridge to make any database changes, it gets written back out as a single line, but for those users who might find it easier to maintain their list of devices using a text editor, this is something they might like to know about.

**Comment by bwssytems** [comment]
Glad it is all working for you. The Offline/Online status is something others have seen as well, but they still work. Also, the discovery process without all devices I have encountered. These things are all in the echo as far as I can tell.

Thanks for the tip on the  db files. That will be something we add to the help we are creating.

Closing as this is resolved.
