### ISSUE TITLE
Setting up a scenes or activities on the ha bridge with two harmony hubs

### ISSUE THREAD

**Issue by michaelhinchey** [bwssytems/ha-bridge#561]
I have set up successfully numerous  devices and have seperate activities on two separate harmony hubs.  What I want to do is have Alexa through a command word we will call "Switch", turn off one activity and start another on a different hub.  Basically it is turning off a tv activity on one hub and then starting another activity (Turning on tv activity in the bedroom).   I'm unsure if the distance between the hubs is two far to just add the devices so what I am trying to do is prevent me from having to put the devices in this activity :"Switch" all on the same hub.  
   I'm sure it is easier than I am thinking it is but if you have suggestions please feel free.
I am running hub 3.5.1 right now but I will soon upgrade to 4.3.1 soon.  THX

**Comment by bwssytems** [comment]
Is this an issue....
