### ISSUE TITLE
Anyone Using HA-Bridge to control Forked-Daapd?

### ISSUE THREAD

**Issue by 1liminal1** [bwssytems/ha-bridge#562]
Im looking to control airplay devices, turn them off/ on and dim volume?

Thanks!

**Comment by 1liminal1** [comment]
No one is doing this?

**Comment by 1liminal1** [comment]
So really no one is using an MPD server with HA-Bridge?

**Comment by bwssytems** [comment]
Looked at this a bit, if you can manage multiple calls you could use the forked-daapd json api with http calls. I did not find the api spec for the json calls.

**Comment by bwssytems** [comment]
Doesn't seem to be much interest in this and also, no documentation on the api. You could write scripts and execute them.

**Comment by 1liminal1** [comment]
Yeah looks that way sadly, I've actually moved on to using echo dots with old Logitech speakers as my end points and then creating an everywhere music group in the Alexa app. 

Not as synced as using ShairPort Sync unfortunately. But not too bad.
