### ISSUE TITLE
In-UI update option

### ISSUE THREAD

**Issue by domier** [bwssytems/ha-bridge#563]
I realize that ha-bridge is already quite easy to update by replacing the .jar file on the host machine, but is there a plan to allow ha-bridge to update itself via the web interface?  

Alternatively, any suggestions on how to dl the most recent version from terminal?  I tried wget and curl but got 404 errors.  Perhaps I have a simple usage error:

wget https://github.com/bwssytems/ha-bridge/releases/download/v4.3.1/ha-bridge-4.3.1.jar

Would like to run the pi completely headless, but this is the last sticking point.

**Comment by audiofreak9** [comment]
You can go headless by SSHing into the RPi.

**Comment by domier** [comment]
Yes, I've gotten that far, all I'm struggling with at the moment is downloading the .jar files from github using terminal

**Comment by domier** [comment]
Edit: just tried again..... I must have repeatedly made a typo in the wget, it works fine today.  Closing.
