### ISSUE TITLE
issue tcp command

### ISSUE THREAD

**Issue by charlez79** [bwssytems/ha-bridge#564]
hi, 
After updating from 4.2.0 to 4.3.1 tcp commands are only executed the 3th time.
The server who picks up the traffic is only receiving data the 3th time.
I guess homebridge is not sending any data first 2 times.

kind regards

**Comment by bwssytems** [comment]
So, it seems if the server end closes the socket after the first send, the ha-bridge does not pick that up. Need to test socket before call.

**Comment by bwssytems** [comment]
I think I will put a param field on tcp commands to tell the ha-bridge if you want to re-use connections (ala persistent)
