### ISSUE TITLE
Sorry for the Noob question, but why wouldn't the Hue App (iOS) discover the habridge?

### ISSUE THREAD

**Issue by hmspain** [bwssytems/ha-bridge#566]
Due to the number of Hue devices, I had to go to two hubs.  The Hue app (on my iPad) sees both hubs nicely.  It's a pain to switch between then everytime I want to see/control the lights on hub2, but I digress.

When adding the second hub, I asked the Hue app to "discover" any new hubs.  After pressing the button, the 2nd hub shows up, and I'm in business.

Is there any way to "press the button" on the habridge such that the Hue app will see the "bridge"?

**Comment by audiofreak9** [comment]
The ha-bridge is coded such that the button is always "pressed".  The Hue app does require your ha-bridge to be running on port 80 for discovery.

**Comment by hmspain** [comment]
Got it; I'm running habridge on my NAS for speed and convenience.  Now that you you press my nose into it, I *am* running on an alternate port since port 80 is used by the NAS (duh).

Time to break out the RPi I was using in the past!

Thank you!!!

**Comment by audiofreak9** [comment]
Ok, great.  Closing...
