### ISSUE TITLE
Calling multiple HTTP addresses from HABridge

### ISSUE THREAD

**Issue by pixelflowxyz** [bwssytems/ha-bridge#568]
Hi there,

While trying to set up my HABridge to be able to start a certain chain of events (that call multiple [SonosAPI](https://github.com/jishi/node-sonos-http-api) links (set up on the same Raspberry Pi as HABridge)), I came across a problem - I don't think I can.

Can you advise me on how to do this, and if you can't, it would be a feature I would love to see implemented.

I'm running HABridge 3.5.1 on a Raspberry Pi 3 Model B.

Thanks,
Dan.

**Comment by bwssytems** [comment]
That is the multiple call construct feature https://github.com/bwssytems/ha-bridge#multiple-call-construct

It's best if you upgrade to v4.3.1

**Comment by pixelflowxyz** [comment]
Thanks - will upgrade later
