### ISSUE TITLE
BridgeSettings.configWriter needs synchonized

### ISSUE THREAD

**Issue by srchacker** [bwssytems/ha-bridge#571]
It looks like that somewhat, multiple threads can get into configWriter at the same time, which gets the move to config.old confused.  I keep seeing that the move to config.old failing on the screen every once in a while, so decided to track it down a little.  Not sure if this is the correct fix though.

**Comment by bwssytems** [comment]
Most likely. Now that a save can happen on a hue api call and they are all on separate threads.
