### ISSUE TITLE
Multiple Call Construct Difficulty

### ISSUE THREAD

**Issue by wisouder** [bwssytems/ha-bridge#573]
Running: HA Bridge Version 4.3.1 ON Linux rpi-02 4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017 armv7l GNU/Linux

In summary, I'm using perl to read data from vera units and based on parameters passed to perl and how I've configured the devices in the various vera units, I generate the JSON that I thought was necessary to enter into a new device in ha-bridge.  This greatly cuts down on the time it takes me to generate the various groups I want to have created to do various tasks.

In a previous version of ha bridge it was working great however since the new version (greater than 4.0?) I am either using the multiple call construct incorrectly or something else appears incorrectly configured on my part or even a potential bug.

When I create the device in ha-bridge and save and run, i receive the following error:
Request Error, Pleae look in your habridge log: error {"type":"6","address":"/lights/1","description":"Error on calling url to change device state","method_name":"/lights/1state"}

In reviewing the log as instructed, I see the following:
2017-03-29 08:53:39,968 [qtp9110572-11] WARN  com.bwssystems.HABridge.plugins.http.HTTPHome - HTTP Call to be presented as http(s)://<ip_address>(:<port>)/payload, format of request unknown: [{"item":"http://XXX.XXX.XXX.XXX:XXXX/data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:SwitchPower1&action=SetTarget&newTargetValue=1&DeviceNum=102","type":"httpDevice"},{"item":"http://XXX.XXX.XXX.XXX:XXXX/data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:SwitchPower1&action=SetTarget&newTargetValue=1&DeviceNum=99","type":"httpDevice"}]

I created the device above by conducting the following steps:
1. go to [Add/Edit] tab
2. enter name "Outside Lights"
3. set Device Type "Group"
4. set Map type "HTTP Device"
5. in On Items:
 - set Type "HTTP Device"
 - set Target
[{"item":"http://XXX.XXX.XXX.XXX:XXXX/data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:SwitchPower1&action=SetTarget&newTargetValue=1&DeviceNum=102","type":"httpDevice"},{"item":"http://XXX.XXX.XXX.XXX:XXXX/data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:SwitchPower1&action=SetTarget&newTargetValue=1&DeviceNum=99","type":"httpDevice"}]
6. choose add
7. choose [Add Bridge Device]

I apologize if this is simply my misunderstanding of how the new version works.  Do you see that the process or data is incorrect or can I provide additional information to determine a potential problem in the code?

**Comment by bwssytems** [comment]
Do not set Target to that, you are duplicating the construct of what the GUI is doing for you. Target should just be the http call itself all the other attributes are on the gui line.

**Comment by wisouder** [comment]
Thank you for the quick response!

To follow-up and verify I'm understanding your response.

Through the GUI, i can no longer enter into a box the JSON for multiple actions, i have to use the GUI to do it?

As noted, it seemed to work in previously releases where I could build the JSON for a device of [n] actual http calls, but now it seems the GUI must be used to create those groups instead of my program building them and I paste it into a single box?

My apologies for the follow-up but and I'm sure there may not have been many people (if any) doing what I'm doing... so if this ability was lost, i would ask for a short cut way to add it back or in a different way :)
