### ISSUE TITLE
${device.name} not working

### ISSUE THREAD

**Issue by wookienow** [bwssytems/ha-bridge#575]
I am trying to use
${device.name}
in a http payload and it is just passing the text 
${device.name} 
doing the same works for intensity

json below for item.

What am I doing wrong?

{"id":"11","uniqueid":"00:17:88:5E:D3:0B-0B","name":"test","onUrl":"[{\"item\":\"http://homeserver/rest/items/EchoCommand\",\"httpVerb\":\"POST\",\"httpBody\":\"${device.name}\",\"contentType\":\"text/plain\"}

**Comment by bwssytems** [comment]
What version are you running?

**Comment by wookienow** [comment]
4.2.1

**Comment by bwssytems** [comment]
The release that added that feature, if you read the notes was 4.3.1. You will need to upgrade.

**Comment by wookienow** [comment]
OK. Thanks
Easy done.
