### ISSUE TITLE
504 Gateway Timeouts

### ISSUE THREAD

**Issue by brandoncorry** [bwssytems/ha-bridge#579]
If HA-Bridge is not used for some time, the first attempts to use it seem to always fail with a 504 timeout. I thought it was Home Assistant that may have been the idle problem, but this morning I was able to narrow the issue down a bit.

I used fiddler to call Home Assistant directly and it worked without any issues. I then went into HA-Bridge UI, and clicked 'turn'on' for a light, and it throws the 504 error. It does do the retry that was added in 4.2.1 from issue #501, and fails. When I click turn-on a second time in the UI, it will work, but only if a long enough time hasn't passed.

I am currently running HA-Bridge on an RPi3 Model B if that helps with debugging.

![image](https://cloud.githubusercontent.com/assets/17894275/24588107/fcd8af4a-1776-11e7-8f3f-fb9ec445f59e.png)

**Comment by bwssytems** [comment]
man, it looks like i lost something kn a merge as i was adding the capabililty to use persistent ip connections or not

**Comment by bwssytems** [comment]
Sorry, was thinking about TCP devices. So, I am not sure as the http call issue is coming from the Home Assistant end.

**Comment by bwssytems** [comment]
Is this still occurring?

**Comment by brandoncorry** [comment]
Not as often as before; however, I just upgraded to 4.5.5 today, so i'll monitor it for a couple days and let you know.

**Comment by brandoncorry** [comment]
Seeing a different error - but still have to execute my commands twice. If I try doing it through HomeAssistant dashboard first, it works, so HA is up and running, but first voice command fails. New error pasted below:

![image](https://user-images.githubusercontent.com/17894275/27065175-91aef270-4fb0-11e7-99aa-d4a28133449a.png)

**Comment by bwssytems** [comment]
This is believed to be a protocol exception error. #671 has debugged this

**Comment by bwssytems** [comment]
closing as this as it is mostly related to #671
