### ISSUE TITLE
Can you give me one example to load into for Harmony Hub

### ISSUE THREAD

**Issue by hln98** [bwssytems/ha-bridge#58]
Please help.  I ran your jar and added my Harmony Hub user name and pw with the "Bridge Control".  Now I clicked on Manual Add tab, how do I add one of my existing activities, say "What TV".  What do I put in for the "On URL" and "OFF URL"?

Do I use "PUT" and what do I type in. Content Body On etc..?  

How about a writeup that beginners can follow?  And please never be brief.  
Please be very specific and give examples.  

Thanks

**Comment by audiofreak9** [comment]
You say you added your harmony username and password, did you also enter your Harmony Hub's Name and IP address?  

Do you not have "Harmony Activities" and "Harmony Devices" tabs next to the "Manual Add" in the config?

**Comment by hln98** [comment]
Yes I entered name and IP address for harmony hub. And no I don't have Harmony Activities and Harmony Devices next to Manual Add

**Comment by audiofreak9** [comment]
Using the IP and configured port of the system you are running the jar on enter the following and let me know if you have any devices listed.

http://host:port/api/devices/harmony/devices

**Comment by bwssytems** [comment]
Is this working now?
