### ISSUE TITLE
The upnp config address, 192.168.1.83, does not match any known IP's on this host

### ISSUE THREAD

**Issue by vitorantunes1980** [bwssytems/ha-bridge#580]
04-02-2017 16:56:36.383	INFO	HA Bridge (v4.3.1) starting....	com.bwssystems.HABridge.HABridge
04-02-2017 16:56:36.434	INFO	reading from config file: /home/pi/habridge/data/habridge.config	com.bwssystems.HABridge.BridgeSettings
04-02-2017 16:56:37.360	WARN	The upnp config address, 192.168.1.83, does not match any known IP's on this host.	com.bwssystems.HABridge.BridgeSettings
04-02-2017 16:56:37.586	INFO	HA Bridge initializing....	com.bwssystems.HABridge.HABridge
04-02-2017 16:56:37.843	INFO	System control service started....	com.bwssystems.HABridge.SystemControl

**Comment by bwssytems** [comment]
you are setting an upnp ip that is not configured for the host anymore . do you use dhcp?

**Comment by vitorantunes1980** [comment]
Sorry :( I do not understand much !!!
Tell me what I have to do to solve this. I really want to have Alexa to work.
thank you

**Comment by vitorantunes1980** [comment]
Help me to solve this problem, I do not know what to do, I try to put the ip in the "Bridge server" equal to the "UPNP IP Address" and I can not :(
Please I need help


<img width="1280" alt="captura de ecra 2017-04-02 as 23 59 37" src="https://cloud.githubusercontent.com/assets/26839465/24591746/74088110-1800-11e7-9d33-106f3527ea73.png">

**Comment by bwssytems** [comment]
Just put in 0.0.0.0 there and it will try to pick your up address

**Comment by vitorantunes1980** [comment]
Sorry, I tried to sim and did not. I do not quite understand what you want me to do, you can explain better. Please

<img width="1280" alt="captura de ecra 2017-04-03 as 00 10 06" src="https://cloud.githubusercontent.com/assets/26839465/24591820/3e555eba-1802-11e7-8c3d-4ec92ffc11bd.png">

**Comment by bwssytems** [comment]
Use ip address 0.0.0.0 in those fields, it tells the system to determine the ip itself

**Comment by vitorantunes1980** [comment]
I did it this way and it's not
 
<img width="1280" alt="captura de ecra 2017-04-03 as 00 18 45" src="https://cloud.githubusercontent.com/assets/26839465/24591855/5c730108-1803-11e7-8c59-9e672dbec96d.png">

I did save
<img width="1280" alt="captura de ecra 2017-04-03 as 00 19 00" src="https://cloud.githubusercontent.com/assets/26839465/24591856/5c784c12-1803-11e7-8f2b-bfd4b527b948.png">

and it stays the same again.
<img width="1280" alt="captura de ecra 2017-04-03 as 00 17 34" src="https://cloud.githubusercontent.com/assets/26839465/24591854/5c70e29c-1803-11e7-8591-631406936017.png">

**Comment by vitorantunes1980** [comment]
what is your opinion

<img width="1280" alt="captura de ecra 2017-04-03 as 00 34 00" src="https://cloud.githubusercontent.com/assets/26839465/24591960/59d49da6-1805-11e7-8c6d-81802dada9cc.png">

**Comment by bwssytems** [comment]
There is no error shown in the last screen shot. If you are still getting that error, you need to set your machine that runs the ha-bridge to a static ip address and then use that ip in those fields.

**Comment by Deojuvente** [comment]
same thing here: The upnp config address, 192.168.178.48, does not match any known IP's on this host.
i have a stattic ip adres, if i go to my PI and hostname -I i see 192.168.178.48. i delete the habridge data file (.config) but no luck there. 

i cant add the harmony or nest but the lights (HTTP) are working good :)

**Comment by vitorantunes1980** [comment]
Deojuvente
sorry for my english.
You also can not get Alexa to work?
I've been looking for and I think the error is the ipv6 format.
I'm trying to disable ipv6 for raspberry to work with ipv4.
I'm sad :( I can not get Alexa to do things.

**Comment by Deojuvente** [comment]
Alexa is working good lights go on and off when i ask
the only thing thets not working is the nest and harmony i cant save the password and settings there

**Comment by bwssytems** [comment]
There are no passwords for the harmony anymore.

**Comment by Deojuvente** [comment]
i know nest loggin and pas is not saveing
for the harmony its the ip settings not saveing

**Comment by bwssytems** [comment]
Then you need to look at your log for errors as the system probably cannot save the settings....

**Comment by Deojuvente** [comment]
04-04-2017 20:48:40.033 	INFO 	HA Bridge (v4.3.1) starting.... 	com.bwssystems.HABridge.HABridge
04-04-2017 20:48:40.276 	INFO 	reading from config file: data/habridge.config 	com.bwssystems.HABridge.BridgeSettings
04-04-2017 20:48:41.185 	WARN 	The upnp config address, 192.168.178.48, does not match any known IP's on this host. 	com.bwssystems.HABridge.BridgeSettings
04-04-2017 20:48:41.428 	INFO 	HA Bridge initializing.... 	com.bwssystems.HABridge.HABridge
04-04-2017 20:48:41.735 	INFO 	System control service started.... 	com.bwssystems.HABridge.SystemControl
04-04-2017 20:48:43.179 	INFO 	Initializing UDP response Socket... 	com.bwssystems.HABridge.util.UDPDatagramSender
04-04-2017 20:48:43.263 	INFO 	UDP response Seocket initialized to: 50000 	com.bwssystems.HABridge.util.UDPDatagramSender
04-04-2017 20:48:43.324 	INFO 	Harmony Home created. No Harmony devices configured. 	com.bwssystems.HABridge.plugins.harmony.HarmonyHome
04-04-2017 20:48:43.410 	INFO 	Nest Home created. No Nest configured. 	com.bwssystems.HABridge.plugins.NestBridge.NestHome
04-04-2017 20:48:43.422 	INFO 	Hue passthru Home created. No Hue passtrhu systems configured. 	com.bwssystems.HABridge.plugins.hue.HueHome
04-04-2017 20:48:43.437 	INFO 	HAL Home created. No HAL devices configured. 	com.bwssystems.HABridge.plugins.hal.HalHome
04-04-2017 20:48:43.445 	INFO 	MQTT Home created. No MQTT Clients configured. 	com.bwssystems.HABridge.plugins.mqtt.MQTTHome
04-04-2017 20:48:43.452 	INFO 	HomeAssistant Home created. No HomeAssistants configured. 	com.bwssystems.HABridge.plugins.hass.HassHome
04-04-2017 20:48:43.470 	INFO 	Command Home for system program execution created. 	com.bwssystems.HABridge.plugins.exec.CommandHome
04-04-2017 20:48:45.317 	INFO 	== Spark has ignited ... 	spark.webserver.JettySparkServer
04-04-2017 20:48:45.356 	INFO 	>> Listening on 0.0.0.0:80 	spark.webserver.JettySparkServer
04-04-2017 20:48:47.420 	INFO 	Http Home created. 	com.bwssystems.HABridge.plugins.http.HTTPHome
04-04-2017 20:48:47.426 	INFO 	TCP Home created. 	com.bwssystems.HABridge.plugins.tcp.TCPHome
04-04-2017 20:48:47.431 	INFO 	UDP Home created. 	com.bwssystems.HABridge.plugins.udp.UDPHome
04-04-2017 20:48:47.435 	INFO 	Vera Home created. No Veras configured. 	com.bwssystems.HABridge.plugins.vera.VeraHome
04-04-2017 20:48:47.442 	INFO 	Domoticz Home created. No Domoticz devices configured. 	com.bwssystems.HABridge.plugins.domoticz.DomoticzHome
04-04-2017 20:48:47.447 	INFO 	Somfy Home created. No Somfys configured. 	com.bwssystems.HABridge.plugins.somfy.SomfyHome
04-04-2017 20:48:47.457 	INFO 	LifxDevice Home created. No LifxDevices configured. 	com.bwssystems.HABridge.plugins.lifx.LifxHome
04-04-2017 20:48:47.599 	INFO 	HABridge device management service started.... 	com.bwssystems.HABridge.devicemanagmeent.DeviceResource
04-04-2017 20:48:47.680 	INFO 	Hue description service started.... 	com.bwssystems.HABridge.upnp.UpnpSettingsResource
04-04-2017 20:48:47.708 	INFO 	Hue emulator service started.... 	com.bwssystems.HABridge.hue.HueMulator
04-04-2017 20:48:47.805 	INFO 	UPNP Discovery Listener starting.... 	com.bwssystems.HABridge.upnp.UpnpListener
04-04-2017 20:48:47.810 	INFO 	UPNP Discovery Listener running and ready.... 	com.bwssystems.HABridge.upnp.UpnpListener
04-04-2017 22:22:28.532 	ERROR 		spark.webserver.MatcherFilter
04-05-2017 09:57:30.300 	ERROR 	Error writing the file: data/habridge.config message: data/habridge.config 	com.bwssystems.HABridge.BridgeSettings

**Comment by Deojuvente** [comment]
oke i have given the habridge.config 777
now i lost all devices and the IP is not known
04-05-2017 21:28:17.177 	INFO 	HA Bridge (v4.3.1) starting.... 	com.bwssystems.HABridge.HABridge
04-05-2017 21:28:17.468 	INFO 	reading from config file: data/habridge.config 	com.bwssystems.HABridge.BridgeSettings
04-05-2017 21:28:18.318 	WARN 	The upnp config address, 192.168.178.48, does not match any known IP's on this host. 	com.bwssystems.HABridge.BridgeSettings
04-05-2017 21:28:18.627 	INFO 	HA Bridge initializing.... 	com.bwssystems.HABridge.HABridge
04-05-2017 21:28:19.031 	INFO 	System control service started.... 	com.bwssystems.HABridge.SystemControl
04-05-2017 21:28:20.379 	INFO 	Initializing UDP response Socket... 	com.bwssystems.HABridge.util.UDPDatagramSender
04-05-2017 21:28:20.422 	INFO 	UDP response Seocket initialized to: 50001 	com.bwssystems.HABridge.util.UDPDatagramSender
04-05-2017 21:28:20.522 	INFO 	Harmony Home created. 	com.bwssystems.HABridge.plugins.harmony.HarmonyHome
04-05-2017 21:28:22.582 	INFO 	== Spark has ignited ... 	spark.webserver.JettySparkServer
04-05-2017 21:28:22.648 	INFO 	>> Listening on 0.0.0.0:80 	spark.webserver.JettySparkServer
04-05-2017 21:28:26.233 	INFO 	setup initiated .... 	com.bwssystems.HABridge.plugins.harmony.HarmonyServer
04-05-2017 21:28:39.423 	INFO 	activity changed: [-1] PowerOff 	com.bwssystems.HABridge.plugins.harmony.HarmonyServer
04-05-2017 21:28:39.438 	INFO 	Nest Home created. 	com.bwssystems.HABridge.plugins.NestBridge.NestHome
04-05-2017 21:28:39.482 	INFO 	Starting Nest login... 	com.bwssystems.nest.controller.NestSession
04-05-2017 21:28:41.735 	INFO 	Completed Nest login... 	com.bwssystems.nest.controller.NestSession

**Comment by bwssytems** [comment]
That is because if you start with the system it uses /root if you start with pi user it is in /home/pi. you'll need to copy files from one to the other

**Comment by vitorantunes1980** [comment]
: (I've done everything and I can not make Alexa work
Can someone give me the email to help me?
thank you


04-05-2017 22:15:10.463	INFO	HA Bridge (v4.3.1) starting....	com.bwssystems.HABridge.HABridge
04-05-2017 22:15:10.509	INFO	reading from config file: /home/pi/habridge/data/habridge.config	com.bwssystems.HABridge.BridgeSettings
04-05-2017 22:15:11.286	WARN	The upnp config address, 192.168.1.83, does not match any known IP's on this host.	com.bwssystems.HABridge.BridgeSettings
04-05-2017 22:15:11.404	INFO	HA Bridge initializing....	com.bwssystems.HABridge.HABridge
04-05-2017 22:15:11.525	INFO	System control service started....	com.bwssystems.HABridge.SystemControl
04-05-2017 22:15:13.565	INFO	Initializing UDP response Socket...	com.bwssystems.HABridge.util.UDPDatagramSender
04-05-2017 22:15:13.695	INFO	UDP response Seocket initialized to: 50000	com.bwssystems.HABridge.util.UDPDatagramSender
04-05-2017 22:15:13.748	INFO	Harmony Home created. No Harmony devices configured.	com.bwssystems.HABridge.plugins.harmony.HarmonyHome
04-05-2017 22:15:13.829	INFO	Nest Home created. No Nest configured.	com.bwssystems.HABridge.plugins.NestBridge.NestHome
04-05-2017 22:15:13.888	INFO	Hue passthru Home created. No Hue passtrhu systems configured.	com.bwssystems.HABridge.plugins.hue.HueHome
04-05-2017 22:15:13.894	INFO	HAL Home created. No HAL devices configured.	com.bwssystems.HABridge.plugins.hal.HalHome
04-05-2017 22:15:13.899	INFO	MQTT Home created. No MQTT Clients configured.	com.bwssystems.HABridge.plugins.mqtt.MQTTHome
04-05-2017 22:15:13.903	INFO	HomeAssistant Home created. No HomeAssistants configured.	com.bwssystems.HABridge.plugins.hass.HassHome
04-05-2017 22:15:13.908	INFO	Command Home for system program execution created.	com.bwssystems.HABridge.plugins.exec.CommandHome
04-05-2017 22:15:15.338	INFO	== Spark has ignited ...	spark.webserver.JettySparkServer
04-05-2017 22:15:15.358	INFO	>> Listening on 0.0.0.0:80	spark.webserver.JettySparkServer
04-05-2017 22:15:17.229	INFO	Http Home created.	com.bwssystems.HABridge.plugins.http.HTTPHome
04-05-2017 22:15:17.235	INFO	TCP Home created.	com.bwssystems.HABridge.plugins.tcp.TCPHome
04-05-2017 22:15:17.239	INFO	UDP Home created.	com.bwssystems.HABridge.plugins.udp.UDPHome
04-05-2017 22:15:17.243	INFO	Vera Home created. No Veras configured.	com.bwssystems.HABridge.plugins.vera.VeraHome
04-05-2017 22:15:17.247	INFO	Domoticz Home created. No Domoticz devices configured.	com.bwssystems.HABridge.plugins.domoticz.DomoticzHome
04-05-2017 22:15:17.251	INFO	Somfy Home created. No Somfys configured.	com.bwssystems.HABridge.plugins.somfy.SomfyHome
04-05-2017 22:15:17.260	INFO	LifxDevice Home created. No LifxDevices configured.	com.bwssystems.HABridge.plugins.lifx.LifxHome
04-05-2017 22:15:17.389	INFO	HABridge device management service started....	com.bwssystems.HABridge.devicemanagmeent.DeviceResource
04-05-2017 22:15:17.476	INFO	Hue description service started....	com.bwssystems.HABridge.upnp.UpnpSettingsResource
04-05-2017 22:15:17.498	INFO	Hue emulator service started....	com.bwssystems.HABridge.hue.HueMulator
04-05-2017 22:15:17.621	INFO	UPNP Discovery Listener starting....	com.bwssystems.HABridge.upnp.UpnpListener
04-05-2017 22:15:17.625	INFO	UPNP Discovery Listener running and ready....	com.bwssystems.HABridge.upnp.UpnpListener

**Comment by bwssytems** [comment]
@vitorantunes1980 All the info has been given here. If you do not understand, it would be time to ask your friends that have some technology background to help you. This is free software and it is on a developer site, so it comes with the idea you have some idea what the technology does.

**Comment by vitorantunes1980** [comment]
OK, sorry.

**Comment by devenbj** [comment]
I had a similar issue. I found that my system was starting ha bridge prior to the nic getting an IP. I changed my habridge.service to Type=idle. This added enough of a start-up delay to allow my nic to start before ha bridge. Problem solved for me.

**Comment by Deojuvente** [comment]
i know what it is.. if you just setup a new habridge and you add Nest loggin and pas and added the harmony, you cant add devives its not makeing the device.db file.
