### ISSUE TITLE
Philips Hue and other iPhone apps not autodetecting HA-Bridge

### ISSUE THREAD

**Issue by zounder1** [bwssytems/ha-bridge#581]
Hi,
The Philips Hue iPhone app does not automatically detect the HA-Bridge install that I have setup.  If enter the IP address manually it connects fine.

My setup:
Raspberry Pi running Jessie Lite
Fully updated install.
Basic install, nothing else installed.
Running HA-Bridge using the recommended sysctrl method.
HA-Bridge is running fine when using the web interface.
The RPI is getting is getting a static IP address assigned by DHCP.

Is there anything else I need to do on the Raspberry PI and/or HA-Bridge so it is discoverable by the iPhone app automatically?  (Like Apple's bonjour protocol?)

The IP address is great but greatly decreases the usability for the rest of the family.  (I would rather not need to handle every device that they will use.)

Thanks in advance.

**Comment by bwssytems** [comment]
That's because those apps use the hue cloud first to connect. This is not a Philips Hue device, so it is not connected in their cloud and won't be as this is not a Philips product.
