### ISSUE TITLE
habridge 4.5.0rc1 Release Candidate

### ISSUE THREAD

**Issue by bwssytems** [bwssytems/ha-bridge#582]
See this for notes and jar download

https://github.com/bwssytems/ha-bridge/releases/tag/v4.5.0rc1

Please test... :)

**Comment by bwssytems** [comment]
So, now I see a default hardocded test user for the testing and that kinda breaks the use link button security. Will add get testuser button to do that and remove the hard code. So, to test you will have to hit the link button, then hit the get test user button.....

**Comment by tuicemen** [comment]
I never noticed the link button but do now I'm confused as to what this is suppose to do!
I see  message link your device in 30 seconds. Is this to detect and register a hue device?
Is there a command line to enable the walled execGarden?

**Comment by tuicemen** [comment]
Would it be possible to hide the add edit tab using a command line call?
Maybe still allow a PUT with the add/edit tab hidden?
This would prevent users from having to rewrite all their device calls for a walled garden.
As it is now anyone that was to gain unauthorized access could create a custom device to call a suspicious URL infecting ones system.
Or they could edit devices so they no longer worked.

**Comment by bwssytems** [comment]
Well that is what the username password is for.

**Comment by tuicemen** [comment]
So the execGarden idea has been abandoned then.
Still would be nice for an admin level access and user/operator level access.
Users/operators not able to change settings just activate devices.
Great work on the bridge, it just keeps getting better!

**Comment by tuicemen** [comment]
Is there anything special you'd liked tested?
I haven't been able to find any issues as yet however I only use exec calls and custom URL calls.

Currently it is possible to log on with id currently in use so having ability to add additional users added isn't required unless user restrictions are planned for a future add.

**Comment by bwssytems** [comment]
The execGarden has not been abandoned. You will need to give a -Dexec.garden=Path on the command line to use it. It is useful if you want to secure your system further and it has been requested as an enhancement by several users. I put it on my system and it works great.

I am updating the code to dynamically retrieve a user to test with as that was the last security hole.

**Comment by tuicemen** [comment]
Do you need to use the command line on each startup?
If not is there away to disable if one doesn't wish to use it?

**Comment by bwssytems** [comment]
If you don't put the -Dexec.garden on the command line, it won't use it and works as before

**Comment by tuicemen** [comment]
Cool, I'll play a bit more with it

**Comment by tuicemen** [comment]
I'm missing something and maybe because I'm testing in windows.
Starting the bridge with command` ha-bridge.jar -Dexec.garden=C:\Users\tuicemen\ha\Scripts`
has no affect on devices still configured the old way. Old devices still work but new devices  configure without the path in the call don't work

**Comment by bwssytems** [comment]
-D has to go before the ha-bridge....jar file

**Comment by tuicemen** [comment]
So command line  would be `-D ha-bridge.jar exec.garden=C:\Users\tuicemen\ha\Scripts` ?

**Comment by akurz42** [comment]
java -jar -Dexec.garden=C:\Users\tuicemen\ha\Scripts ha-bridge.jar

Cheers,
Alex

**Comment by tuicemen** [comment]
thanks Alex

**Comment by tuicemen** [comment]
Ok bridge running with execgarden enabled.
I can turn on off a device but then after that the bridge locks up and I get  small yellow box with:
 [object Object]   and can't access the log to see if anything is being reported.
![image](https://cloud.githubusercontent.com/assets/25393840/24718558/6aa54530-1a04-11e7-830e-0a560014233c.png)

**Comment by bwssytems** [comment]
That usually means that the ha-bridge died...

**Comment by tuicemen** [comment]
this is repeatable using the garden and always after second command after restarting.
I guess the execGarden currently isn't compatible with Windows 10  :(

**Comment by bwssytems** [comment]
what is the command line error?

**Comment by tuicemen** [comment]
Restarted Windows ran CMD as admin
on starting there is one line  reporting a warning about security:
`2017-04-05 14:47:08,838 [main] WARN com.bwssystems.HABridgeSecurity - Could not get security data, using default security (none): null`
As soon as I test a device the cmd closes and the bridge dies

**Comment by bwssytems** [comment]
That error is bogus, as you found something I need to fix. So does it run and then throw an error when you do something?

**Comment by tuicemen** [comment]
interesting. if I close the CMD before login in the bridge dies 
seems the issue is the exegarden and scripts I have there which are Batch files. if I click on a device not configured with a call to the garden the CMD remains open and displays an error.
everything seems to work untill I attempt to activate a device that makes a call to the garden
when I click on a device whos call is to the garden the call works but then the bridge dies.
I can only make one call now it use to let me make two calls but maybe I was doing them fast enought before everything died.

**Comment by tuicemen** [comment]
Ok I may have stumbled on a cure.
if I login then click on reinitialize bridge then re-login devices configured to use the garden work and the bridge doesn't die (unless I close the cmd)

**Comment by bwssytems** [comment]
Updated dynamic test user

https://github.com/bwssytems/ha-bridge/releases/download/v4.5.0rc2/ha-bridge-4.5.0rc2.jar

Next to do is put the whitelist into the security data so no one can see it. this will convert the old list if it is available

**Comment by tuicemen** [comment]
Using the execGarden I find device activation too slow for my liking.
Besides it seems over kill if your using a user authorization for bridge access.

I believe I seen a brief toast message about dynamic tester when first starting the new version and haven't seen it since. 
Everything seems to be working fine for me with my setup!

**Comment by bwssytems** [comment]
execGarden should not be any slower than not as all it does is append the path to the command given. Nothing else.

**Comment by tuicemen** [comment]
A direct program (exe) call is faster then a script maybe not noticeable to most users as it is just seconds and these can't be used if the garden is enabled.
A script not using the garden is also faster but just milliseconds nothing worth worrying about. (at least I don't)
Reentering (editing) my few exe/script device calls and having to create new scripts for exe calls is more then I wish to do, those with a larger setup may dread it even more.

Don't get me wrong the execGarden is a nice add for those security paranoid users or new users.
There are just a few things about it that I personally don't like, but don't change it you did a good job on it.

I'd just be more apt to use user access levels so only 1 user had device add/editing/delete privileges.
Maybe first user added had add/edit/delete ability all others added were just operators

**Comment by bwssytems** [comment]
When running on a linux system, you can link the executable into your directory, so there is no difference. Windows works a bit different.

**Comment by tuicemen** [comment]
I'm using Windows.
It is possible to place a shortcut in the execGarden then the device call would be `ProgramName.lnk argument` I'll experiment to see the speed of execution.
I dislike having to redo(edit) all calls to use this and don't like the CMD open. (just one more way to kill the bridge)
This may grow on me yet the more I experiment!

**Comment by tuicemen** [comment]
OK that didn't work from the bridge! :( funny how some things work  but not from the bridge!

**Comment by bwssytems** [comment]
Ok, closing as RC3 hoepfully will be the last if no issues found
