### ISSUE TITLE
habridge.config wiped on power fail

### ISSUE THREAD

**Issue by Rand0mJ0e** [bwssytems/ha-bridge#584]
The habridge.config file gets truncated to 0 bytes on a power failure.  Seems to happen every time with recent releases.
The OS is Ubuntu 16.04.2 LTS.  ha-bridge version is 4.3.1 running on openjdk 1.8.0_121. 
No changes were made to the config prior to the power failure.  It appears that the habridge.config file is being updated continuously.  The modified timestamp on the file is updated approximately every 10 seconds while ha-bridge is running.

**Comment by bwssytems** [comment]
What OS?

**Comment by bwssytems** [comment]
And it should not happen as any change is saved immeidately.

**Comment by Rand0mJ0e** [comment]
Output of inotifywait -m --timefmt "%H:%M:%S" --format "%T: %f %e" .
17:33:10: habridge.config MOVED_FROM
17:33:10: habridge.config.old MOVED_TO
17:33:10: habridge.config CREATE
17:33:10: habridge.config OPEN
17:33:10: habridge.config MODIFY
17:33:10: habridge.config CLOSE_WRITE,CLOSE
17:33:10: habridge.config ATTRIB
17:33:10: habridge.config.old DELETE
17:33:10: habridge.config OPEN
17:33:10: habridge.config ACCESS
17:33:10: habridge.config CLOSE_NOWRITE,CLOSE
17:33:20: habridge.config MOVED_FROM
17:33:20: habridge.config.old MOVED_TO
17:33:20: habridge.config CREATE
17:33:20: habridge.config OPEN
17:33:20: habridge.config MODIFY
17:33:20: habridge.config CLOSE_WRITE,CLOSE
17:33:20: habridge.config ATTRIB
17:33:20: habridge.config.old DELETE
17:33:20: habridge.config OPEN
17:33:20: habridge.config ACCESS
17:33:20: habridge.config CLOSE_NOWRITE,CLOSE
... every 10 seconds

**Comment by bwssytems** [comment]
Are you running Domoticz?

**Comment by Rand0mJ0e** [comment]
No, not running Dominicz.

**Comment by bwssytems** [comment]
So, something is calling your system every 10 seconds. The harmony hub does that and so does domoticz. The new version will also fix some issues with writing the config file as well. Otherwise, there is no cure for writing a file and a power interruuption occurrs.

**Comment by Rand0mJ0e** [comment]
Yes, I am using a Harmony Hub, and have been since I started using ha-bridge.  I've worked around the zeroed config file in my startup script.  Thanks for looking into this issue.

**Comment by bwssytems** [comment]
Just a question on your Harmony Hub... Do you have the Harmony Hub controlling the ha-bridge as well?

**Comment by Rand0mJ0e** [comment]
No, I use ha-bridge as an Amazon Echo bridge to control home automation and entertainment devices, but none of those devices is the bridge itself.  I hope I understood your question question correctly.
