### ISSUE TITLE
Service Crashing 4.5.0

### ISSUE THREAD

**Issue by insanerwayner** [bwssytems/ha-bridge#588]
Service starts then fails after moving from 4.3.1

> pi@ha-bridge:~ $ sudo systemctl status habridge.service  -l
> ● habridge.service - HA Bridge
>    Loaded: loaded (/etc/systemd/system/habridge.service; enabled)
>    Active: failed (Result: exit-code) since Fri 2017-04-07 19:21:24 UTC; 1min 3s ago
>   Process: 655 ExecStart=/usr/bin/java -jar -Dconfig.file=/home/pi/habridge/data/habridge.config /home/pi/habridge/ha-bridge-4.5.0.jar (code=exited, status=1/FAILURE)
>  Main PID: 655 (code=exited, status=1/FAILURE)
> 
> Apr 07 19:21:16 ha-bridge systemd[1]: Started HA Bridge.
> Apr 07 19:21:23 ha-bridge java[655]: 2017-04-07 19:21:22,826 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.5.0) starting....
> Apr 07 19:21:23 ha-bridge java[655]: 2017-04-07 19:21:23,312 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: /home/pi/habridge/data/habridge.config
> Apr 07 19:21:24 ha-bridge java[655]: Exception in thread "main" java.lang.NullPointerException
> Apr 07 19:21:24 ha-bridge java[655]: at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:150)
> Apr 07 19:21:24 ha-bridge java[655]: at com.bwssystems.HABridge.HABridge.main(HABridge.java:51)
> Apr 07 19:21:24 ha-bridge systemd[1]: habridge.service: main process exited, code=exited, status=1/FAILURE
> Apr 07 19:21:24 ha-bridge systemd[1]: Unit habridge.service entered failed state.
>

**Comment by bwssytems** [comment]
Will need to look at your habridge.config as there is something it does not like now

**Comment by insanerwayner** [comment]
Cool, maybe I can just clear the config and rebuild it. But I'll submit it in a bit we know what's going on.

Sent from my iPhone

On Apr 7, 2017, at 10:50 PM, BWS Systems <notifications@github.com<mailto:notifications@github.com>> wrote:


Will need to look at your habridge.config as there is something it does not like now

**Comment by insanerwayner** [comment]
So my config file was blank after the upgrade. I moved the file so it would build a new config file. It worked. I restored from a backup file inside the interfaced and that was also successful.
