### ISSUE TITLE
How would I use the ha-bridge to set receiver volume to x%

### ISSUE THREAD

**Issue by fbrea** [bwssytems/ha-bridge#59]
I'm using a Marantz Receiver with the Denon Receiver plugin in Veralite. Can you help me with the command string
 Im using this string:
http://veraip/data_request?id=action&output_format=json&DeviceNum=58&serviceId=urn:upnp-org:serviceId:RenderingControl1&action=SetVolumeDBTarget&newVolumeDBTarget=${intensity.percent}
TIA.

**Comment by bwssytems** [comment]
I wouldn't know off hand, it may be using the dim command for a device, try it, it won't hurt anything...
On Mar 5, 2016 1:14 AM, fbrea <notifications@github.com> wrote:I'm using a Marantz Receiver with the Denon Receiver plugin in Veralite. Can you help me with the command string

TIA.

**Comment by fbrea** [comment]
Hi i just got it to work on my Receiver Denon/Marantz using the Denon Receiver Control Plugin for Vera. and this url string:

http://ip address:port/data_request?id=action&output_format=json&DeviceNum="XX"&serviceId=urn:upnp-org:serviceId:RenderingControl1&action=SetVolume&DesiredVolume=${intensity.math(X/5)}

**Comment by bwssytems** [comment]
Great the hear it is working...closing this question
