### ISSUE TITLE
[Feature] Select Interface - UPnP Listening on all interfaces/IP addresses

### ISSUE THREAD

**Issue by sgruby** [bwssytems/ha-bridge#591]
It appears that even with

`  "upnpconfigaddress": "10.0.1.100", `

set in the config, the bridge is listening on all interfaces:

`mediacenter-internal:~ mediacenter$ netstat -an | grep 1900
udp46      0      0  *.1900                 *.*                               `

I only want it to listen on one of the interfaces (it's a Mac Pro) as I have some devices on a different VLAN trying to discover devices. Should this setting restrict which interface it listens on?

**Comment by bwssytems** [comment]
https://github.com/bwssytems/ha-bridge/blob/master/README.md#web-server-ip-address

**Comment by sgruby-reformation** [comment]
Thanks. I do have the web server IP set and it is listening on the correct IP.
`tcp4       0      0  10.0.1.100.9001        *.*                    LISTEN`

The UPnP listener is listening on all interfaces/IP addresses. I wonder if it is the way the UDP multicast listener works. I'm not a Java developer, so I'm no help in diagnosing why it is listening on all interfaces despite setting the upnpconfigaddress.

Thanks for your time looking at this.

**Comment by bwssytems** [comment]
Yeah, that is how the bridge is built, it listens on all ifaces

**Comment by sgruby-reformation** [comment]
OK, thanks. I have some IP cameras that for some reason are doing UPnP discovery and found the bridge and trying to connect to the bridge. I may just move the bridge to a VM and the problem will go away.

**Comment by bwssytems** [comment]
Maybe something to think about for a future enhancement.
