### ISSUE TITLE
Show error message if serverport is already used

### ISSUE THREAD

**Issue by mfraiss** [bwssytems/ha-bridge#592]
Hy guys,

You do a great job! I just had to fiddle around, to find out that another application has blocked my serverport, when trying to start up ha-bridge. Ha-bridge just crashed and the java process terminated.

It would be great if the JAR shows an error in command line or writes a error.log to the directory if this happens.

What do you guys think?

**Comment by bwssytems** [comment]
It does, it prints out it's error sharing port is already in use, then it prints the stack Trace. This is in the log messages, which are on the command line....
