### ISSUE TITLE
Buttons on Hue Devices page do not work

### ISSUE THREAD

**Issue by Monki77** [bwssytems/ha-bridge#594]
Unfortunately after pressing the link button and getting all my hue lights to show up in the Hue Device List, I cannot add them to the bridge devices.
Clicking Build Item does nothing, and neither does Bulk Add.

Tested with IE and Firefox.

I also tried deleting the hue link and repairing it but the buttons still do not work.

Edit: Ticking a single light and clicking Add/Edit will allow the devices to be added one by one.
Edit: It's 50/50 whether ticking a light and clicking Add/Edit will actually fill in the info so I can add the device... Strange.

Thanks

**Comment by emigrating** [comment]
Similar thing happens for me (on v4.5.0) using Microsoft Edge as the browser.

Basically, going to the root of ha-bridge will bring up the Bridge Devices as expected, but there are obviously some HTML and/or CSS errors on the page as it doesn't fully populate data (version for example).

![snip_20170411141833](https://cloud.githubusercontent.com/assets/18260264/24908824/f17d3010-1ec1-11e7-9d80-0dae3566f035.png)

Clicking on Bridge Control, Logs or Add/Edit simply reloads the devices page with the same errors. Thinking this was a config file issue, I also tried starting a fresh install, but same issue there.

Then tried Chrome, and it works as intended. Not ideal having to have Chrome installed, but it'll do for now.

**Comment by emigrating** [comment]
Similar thing happens for me (on v4.5.0) using Microsoft Edge as the browser.

Basically, going to the root of ha-bridge will bring up the Bridge Devices as expected, but there are obviously some HTML and/or CSS errors on the page as it doesn't fully populate data (version for example).

![snip_20170411142439](https://cloud.githubusercontent.com/assets/18260264/24909047/b4a2c4a6-1ec2-11e7-9ae6-34140af46985.png)

Clicking on Bridge Control, Logs or Add/Edit simply reloads the devices page with the same errors.
Thinking this was a config file issue, I also tried starting a fresh install, but same issue there.

Then tried Chrome, and it works as intended. Not ideal having to have Chrome installed, but it'll do for now.

**Comment by bwssytems** [comment]
Will take a look

**Comment by Sharky84** [comment]
Hi,

I have the same problem. But I can't get it working in any browser, whether on Chrome, Internet-Explorer or Edge. 

I have 4.5.0 installed on a raspberry pi. Manually, added devices (not hue) are working very good!

I have got a list of my hue devices on the Hue Devices tab (Hue Devices List Page) but when I push the "Build Item" button on any device nothing happens.

Got this error in the Web-Console in Firefox:

**Error: buildonly is not defined**
$scope.buildDeviceUrls@http://192.168.1.29/scripts/app.js:2082:7
fn@http://192.168.1.29/js/angular.min.js line 237 > Function:2:256
e@http://192.168.1.29/js/angular.min.js:282:195
$eval@http://192.168.1.29/js/angular.min.js:147:309
$apply@http://192.168.1.29/js/angular.min.js:148:12
compile/</<@http://192.168.1.29/js/angular.min.js:282:245
dispatch@http://192.168.1.29/js/jquery-1.11.3.min.js:4:8497
add/r.handle@http://192.168.1.29/js/jquery-1.11.3.min.js:4:5235

I would really appreciate your help. The HaBridge is a very good software and I like it very much!
Thank you in advance.

**Comment by bwssytems** [comment]
Still working on this

**Comment by hyperbolic2346** [comment]
The problem appears to be on line 2088 of app.js:
`if (!buildonly) {`
buildonly is undefined here. If I use dev console on chrome and just define buildonly in the console to be false everything works fine except it dumps to the edit page even when I bulk add.

**Comment by bwssytems** [comment]
Totally blew past this one on the last release. Confirmed, buildonly needs to be an argument to the function.
