### ISSUE TITLE
Harmony Press Button http commands

### ISSUE THREAD

**Issue by Radiohead23** [bwssytems/ha-bridge#595]
Is it possible to send http commands to ha-bridge to send a "press button" command to harmony like with restful-harmony, or is it necessary to install both parallel?

**Comment by bwssytems** [comment]
Yes, that is the harmony device tab

**Comment by bwssytems** [comment]
So, did you put in your harmony hub address in the Bridge Control tab? And do you see the devices now?

**Comment by Radiohead23** [comment]
Thank you for asking, my harmony is integrated into the ha-bridge and i can send command via echo, etc. to my harmony. 
My actual question was, if it is possible to send "push button" commands via http like the restful Put-command "PUT http://host:8081/harmony/press" to ha-bridge.
The "/api/devices/harmony/devices" command to ha-bridge gives me the same list like the ":8081/harmony/list/devices" to restful-hamony. So i thought that maybe a command like "/api/devices/harmony/press{..." could work so i don't need to run ha-bridge and restful-hamony.
I hope i explained my question properly.

**Comment by bwssytems** [comment]
Sorry, the ha-bridge does not expose the restful-harmony api. You could make button press in the ha-bridge and then call it's api for that device using the emulated hue api.

**Comment by Radiohead23** [comment]
Then i'll stay with the 2 apps with different ports. Thank you for the reply, the support and the good apps. Donationtime.
