### ISSUE TITLE
Now that Alexa does colors natively...

### ISSUE THREAD

**Issue by emigrating** [bwssytems/ha-bridge#596]
So, Alexa rolled out an update a few days ago so you can now control the color of your bulbs natively. Just say "Alexa turn the [devicename] [color]" and it'll do so. It accepts over a hundred color variants.

Obviously this doesn't work thru HA-bridge but could it? At the moment you get a reply like "That command doesn't work on device [devicename]" which indicates this could work if the bulb type was changed within HA-bridge.

If it is as easy as changing the bulb type and including another command type (on, dim, off) to get the commands accepted then we would just need some sort of color name to rgb value type table (user definable) and this could work on all supported HA devices.

Any ideas?

**Comment by Matt8119** [comment]
https://github.com/bwssytems/ha-bridge/issues/327

**Comment by Matt8119** [comment]
already answered

**Comment by emigrating** [comment]
It's not really answered though.

Yes, I realize I asked for "any ideas" in the original post, but I already knew one could edit the source to do this, what I really meant to say was more akin to;

Are there any plans on integrating this in the config section of HA-bridge? Perhaps by changing the "type" value.

Forking projects is all good and fine if you're going to do a lot of customization, but forking a project simply to edit a couple lines of code isn't really a viable solution.

**Comment by Matt8119** [comment]
i definitely agree on the fact that having to edit a few lines of code isn't a viable option/solution.. the Ha-bridge has matured incredibly in the last few updates, so i can see this feature appearing sooner than later. id also like to see this ability of changing colors added.

**Comment by bwssytems** [comment]
So, #327 is the request to add color functionality. The issue I am having is converting the CIE color space that the hue api uses to RGB to make it useful. It is not as simple as getting "green" and sending "green", these are encoded color sequences.

**Comment by emigrating** [comment]
@bwssytems This I understand, hence me mentioning a user definable CIE - RGB lookup table. If you already have something working in terms of acting on "turn [device] [color]" and expose the CIE value somewhere let me at it and I'll see if I can work out the conversion.
