### ISSUE TITLE
SomfyDevice not responding

### ISSUE THREAD

**Issue by c0zm0** [bwssytems/ha-bridge#599]
Hi,

I have two Somfy IO roller shutters and one awning. These devices are controlled by the TaHoma Service using the TaHome Box. In ha-bridge I get the correct device-listing after setting up the account-credentials. 
After setting up the devices and testing I get the "green success layer" but nothing happens.

In the logfile I get "HTTP response code was not an expected successful response of between 200 - 299, the code was: HTTP/1.1 400 Bad Request" from com.bwssystems.HABridge.plugins.http.HTTPHandler.

Any advice for me?

**Comment by bwssytems** [comment]
I don't have a Somfy so I will put this out there for others.

**Comment by c0zm0** [comment]
Maybe this helps, here are the headers of a request to close a roller shutters (some IDs are manually obfuscated):

`Request URL:https://www.tahomalink.com/enduser-mobile-web/enduserAPI//exec/current/6cf26ea3-ac10-0c01-58eb-97XXXXXXXXX?_=XxXx90887967
Request Method:GET
Status Code:200 OK
Remote Address:178.32.15.131:443
Referrer Policy:no-referrer-when-downgrade
Response Headers
view source
Cache-Control:no-store, must-revalidate, no-cache, max-age=0
Connection:Keep-Alive
Content-Type:application/json;charset=UTF-8
Date:Fri, 14 Apr 2017 14:51:19 GMT
Expires:Mon, 01 Jan 1990 00:00:00 GMT
Keep-Alive:timeout=5, max=4
Server:Apache
Strict-Transport-Security:max-age=31536000; includeSubDomains
Transfer-Encoding:chunked
Request Headers
view parsed
GET /enduser-mobile-web/enduserAPI//exec/current/6cf26ea3-ac10-xXxXxXxXx-97ea3a5e4314?_=1491990887967 HTTP/1.1
Host: www.tahomalink.com
Connection: keep-alive
Accept: */*
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36
DNT: 1
Referer: https://www.tahomalink.com/enduser-mobile-web/steer-html5-client/tahoma/
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
Cookie: JSESSIONID=E9548C6C31B84342AXxXxXXxXxEAB5D92C
Query String Parameters
 (1)
Name
`

**Request:**

`{startTime: 1492181479077, owner: "fu@bar.com",…}
actionGroup
:
{label: "Fenster WZ - Schließen - TaHoma PC", shortcut: false, notificationTypeMask: 0,…}
actions
:
[{deviceURL: "io://0203-xXxXx-8060/32xXx38", commands: [{type: 1, name: "close", parameters: []}]}]
0
:
{deviceURL: "io://0203-xXxX-8060/325xXx8", commands: [{type: 1, name: "close", parameters: []}]}
label
:
"Fenster WZ - Schließen - TaHoma PC"
notificationCondition
:
"NEVER"
notificationTypeMask
:
0
shortcut
:
false
executionSubType
:
"MANUAL_CONTROL"
executionType
:
"Immediate execution"
id
:
"6cf26ea3-ac10-0c01-xXxX-97exXxXxe4314"
owner
:
"fu@bar.com"
startTime
:
1492181479077
state
:
"TRANSMITTED"`


**Response:**

{"startTime":1492181479077,"owner":"fu@bar.com","actionGroup":{"label":"Fenster WZ - Schließen - TaHoma PC","shortcut":false,"notificationTypeMask":0,"notificationCondition":"NEVER","actions":[{"deviceURL":"io://0203-xXxXx-8060/325xXxXx8","commands":[{"type":1,"name":"close","parameters":[]}]}]},"id":"6cf26ea3-xXxXx-0c01-xXxXx-97ea3a5e4314","state":"TRANSMITTED","executionType":"Immediate execution","executionSubType":"MANUAL_CONTROL"}

**Comment by CaptMauser** [comment]
Did you get it to work? So can you control your roller shutter with ha-bridge?

I am also trying to get it worked, but it seems I'm still missing some information. Ha bridge has connected with TaHoma and gathered information, but I don't know what to configure to be Abe to control e.g. shutters

Some guideline would be highly appreciated :-)

**Comment by c0zm0** [comment]
Sadly not... but i'm not a developer, it may be an easy taks but unfortunately the somfy system seems not to be very popular.

**Comment by CaptMauser** [comment]
Hey c0zm0,
A friend of mine (using Somfy io devices like you) tested ha-bridge yesterday and he did not change anything, only connected to tahoma, then added bridge device. He can control his roller shutters.
I have rts shutters and using the same version etc, but it is not working for me....
I thought maybe there is some port not configured or so...
Really strange...

**Comment by CaptMauser** [comment]
Hi,
meanwhile it is running on my RTS shutters. The "trick" was to hold the test button 1sec longer, then the shutter moved finally.

**Comment by blazon72** [comment]
Hi,

is there any update in this thread - any help would be very much appreciated.
I am facing the same issue - having 3 Somfy motors (with external shades), which have been successfully recognized by HA Bridge (with right aliases, device IDs, etc.). The problem seems to be the JSON API compatibility ... when tracing the log, the first API call, which is login, is successful, but the next one (either ON or OFF command) returns the wrong response with 'wrong API call'.
It would be extremely helpful, if anyone who has it working, could share the parameters used/tweaks within the HA Bridge for Tahoma device (the default one, generated during the device add process seems to be incomplete).
Thanks a lot for any support.
