### ISSUE TITLE
UDP packet?

### ISSUE THREAD

**Issue by farhanito** [bwssytems/ha-bridge#6]
Is it possible to send UDP packet instead of TCP?

Thanks

**Comment by bwssytems** [comment]
So, where do you want the UDP calls to be? The UPNP listener is UDP for multicast and so is it's reply.

**Comment by farhanito** [comment]
I have LEDs from www.limitlessled.com/dev that use 3bytes UDP commands, like
OnUrl = udp://<ip address>:<port>/0x450055
OffUrl = udp://<ip address>:<port>/0x460055
...etc

**Comment by bwssytems** [comment]
I'll put that on the list, should be doable. Thanks for the clarification.
