### ISSUE TITLE
Server not responding/blank screen

### ISSUE THREAD

**Issue by Dilepa** [bwssytems/ha-bridge#600]
Hi,

I have installed the latest 4.5.0 habridge, i can access the server but nothing works. I also do not get the update security setting dialog. Nothing happens when i click HAbridge or login/logout.
![server](https://cloud.githubusercontent.com/assets/18387012/24985400/2a6b3edc-2037-11e7-9153-9c6c2587a4b1.png)

The server version is also not shown which tells something is wrong in the compiled java files.
![server version](https://cloud.githubusercontent.com/assets/18387012/24985417/59ea01d4-2037-11e7-89a0-ed223527fb89.png)

The previous version 4.3.1 works.

Could not locate http://xxxxxxxxxxx/js/angular.js specified in source map http://xxxxxxxxxxxx/js/angular.min.js.map.

Error pops up when developer tools enabled in IE and chrome

**Comment by Dilepa** [comment]
Could not locate http://xxxxxxxxxxx/js/angular.js specified in source map http://xxxxxxxxxxxx/js/angular.min.js.map.

Error pops up when developer tools enabled in IE and chrome

**Comment by declanhadley** [comment]
I get the same problem  - works fine in Chrome

**Comment by Dilepa** [comment]
I get the error in ie and chrome as well.


On Apr 14, 2017 10:07 PM, "declanhadley" <notifications@github.com> wrote:

I get the same problem - works fine in Chrome

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bwssytems/ha-bridge/issues/600#issuecomment-294143232>,
or mute the thread

**Comment by tuicemen** [comment]
Never could get the bridge to Load completely in IE
Chrome did work  but now doesn't with the new 4.5.0 version.
As well Windows Edge use to work but now doesn't
I use Avast SafeZone browser for all bridge views on my PC it worked fine prior to 4.5.0 and still works.
The issue with  angular.jar and IE is a well documented issue however never seen anything with it and Chrome or Edge

**Comment by bwssytems** [comment]
That is an unusual error. Will need to see why the javascript map file is pointing that way.

**Comment by declan2511** [comment]
Hi I've just updated to windows creator version (latest w10) and can now see the bridge fine in Edge

**Comment by tuicemen** [comment]
I noticed there was another update for Windows 10 however this still didn't fix the issue with the Edge
opening the developer tools I get 4 file not found errors.
Name	Protocol	Method	Result	Content type	Received	Time	Initiator
http://localhost/js/angular-resource.js	HTTP	GET	404	text/html	337 B	13.97 ms	
http://localhost/js/angular.js	HTTP	GET	404	text/html	328 B	1.25 ms	
http://localhost/js/angular-route.js	HTTP	GET	404	text/html	334 B	3.08 ms	
http://localhost/js/angular-sanitize.js	HTTP	GET	404	text/html	337 B	3.99 ms

**Comment by tuicemen** [comment]
Windows Creator edition of 10  fixes the issues with the edge browser as declan2511 stated.
However it doesn't fix the issue with IE

**Comment by kmdm** [comment]
I think this is due to the use of "async function"[1] in app.js which requires a very modern browser[2]:

[1] https://github.com/bwssytems/ha-bridge/blob/master/src/main/resources/public/scripts/app.js#L80
[2] http://caniuse.com/#feat=async-functions

**Comment by gblachstein** [comment]
I am having the same issue on Ubuntu using Firefox using 4.5.0.  It still works fine with 4.3.1.

**Comment by OzzieJacks** [comment]
Same problem here. Older versions of Firefox and IE that work with 4.3.1 show only the top bar with 4.5.0.  Latest version of Firefox Nightly works fine.

**Comment by bwssytems** [comment]
So, it seems it is the async functionality that is used for authentication check.
