### ISSUE TITLE
Having trouble executing programs

### ISSUE THREAD

**Issue by timfis** [bwssytems/ha-bridge#602]
Hey guys,

I'm trying to execute a shell script that would do a bit of clean-up, then open a chromium browser window on the local raspberry pi.  I'm able to get it to kill processes and do other non-display based operations.  However, as soon as I try to set the display an open a chromium window, it just does nothing.

Here's what I'm trying to execute:
#!/bin/bash
ps aux | grep chromium-browser | grep -v grep | awk '{print $2}' > tmp.txt
kill -9 $(cat tmp.txt)
export DISPLAY=:0
chromium-browser --noerrdialogs --incognito --kiosk http://www.google.com &

I've also tried 
#!/bin/bash
ps aux | grep chromium-browser | grep -v grep | awk '{print $2}' > tmp.txt
kill -9 $(cat tmp.txt)
DISPLAY=:0 chromium-browser --noerrdialogs --incognito --kiosk http://www.google.com &

To be clear, I have my Bridge Device setup to execute script/program with "/home/pi/wallboard/scripts/openbrowser.sh" in the "Target It" box.  openbrowser.sh has the above code in it.

I'm sure that there's a better way to be accomplishing this, but I'm dusting off the linux rust, so bear with me.

The script runs, any running  processes are killed and the tmp.txt file is populated.  The process is running as the pi user.

I see no errors in the syslog, nor in the HA Bridge logs.

I'm guessing I'm just doing the display wrong. 

If I ssh into the system and run the script, it works fine.

Any thoughts?

Thanks!

**Comment by audiofreak9** [comment]
Have you tried adding "bash" to the exec?

bash /home/pi/wallboard/scripts/openbrowser.sh

**Comment by timfis** [comment]
I haven't. I'll give that a shot. I didn't think that would be the issue since the script is running, but I'll try it.

**Comment by audiofreak9** [comment]
I couldn't get my bash scripts to run properly without it.

**Comment by timfis** [comment]
Ok. Thank you!

**Comment by bwssytems** [comment]
Also, did you give access to the display with xhost +?

**Comment by timfis** [comment]
Ok - I tried adding bash before the script, but the behavior didn't change.

@bwssytems - So I'm not 100% sure what you mean by this.  I did some research and found a post with a similar question, though no real answer.  I ultimately tried:  xhost +SI:localuser:pi  though that did not seem to work at all.   Could you provide a bit more info on what you're taking about?

**Comment by bwssytems** [comment]
i don't think bash is the problem as it is int script itself. The first script you show with the display export is correct. The 'xhost +', without an id, needs to be executed on a console in the pi window display and not in the script.

**Comment by timfis** [comment]
I ran this separate from the script, though via ssh. I'm assuming i need to do this in the actual pi, though. 

I'll try that later today. I'm confused why the script would work when running this via ssh, though... It seems odd, but I'll give it a go.

**Comment by timfis** [comment]
Ok... So, when writing my last reply, I decided to try something out and I believe this all makes sense now.

So, because I don't rm the tmp.txt file, the first time I ran this script, it created the tmp.txt file as the pi user...  I thought I had deleted the file, run the command via HA Bridge and noted that it created the file as the pi user still - which is why I assumed everything was working as the pi user.

I re-tested this and discovered that I was wrong.  It's running as root...  So, this makes sense.  the pi user has permissions to do this, the root user doesn't.  So, now I need to figure out how to get this all to run as pi and I think it will all be fine...

I'll update later - if anyone has any tips for me as to how to get this to run as root, I would be grateful.

**Comment by bwssytems** [comment]
If you use the systemctl or rc.local to run the habridge, it will use root by default. You can always modify the startups to have it run under a target user as well.

**Comment by bwssytems** [comment]
Anything new on this?

**Comment by timfis** [comment]
It's running as root so, but that's fine for now. Thank you for the help.
