### ISSUE TITLE
Alexa now supports color changing

### ISSUE THREAD

**Issue by durzo** [bwssytems/ha-bridge#603]
I just received an email from Amazon announcing Alexa now change colors on "brands like Philips, LIFX, and TP-Link". When I asked my echo to "set kitchen lights to blue" I got the reponse "That command doesn't work on device kitchen" - Is this something that ha-bridge needs updating to support?

**Comment by durzo** [comment]
Here is the Alexa development docs for the new color options: https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/smart-home-skill-api-reference#tunable-lighting-control-messages

**Comment by bwssytems** [comment]
Duplicate of #596 and #327
