### ISSUE TITLE
Ha-Brigde Hangs

### ISSUE THREAD

**Issue by darnold64** [bwssytems/ha-bridge#604]
When I try to run ha-bridge on my Windows 7 PC it hangs.  I use the command line java -jar ha-bridge-4.5.0.jar, it loads until UPNP Discovery Listener running and ready.... it hangs at this point.

I have just started trying to use the package...it worked fine last night but for some reason it now hangs (nothing has changed??)

**Comment by bwssytems** [comment]
Could you post the symptoms of how it hangs, please

**Comment by tuicemen** [comment]
Have you opened a browser and attempted to access the HA-Bridge?
If not the Command Prompt will display what your seeing.
The bridge still works even thought the command prompt doesn't display any new info unless I physically open it in a browser.
(at least it doesn't in my case)
I'm not sure why your starting it from the command prompt  you can just click on it in Windows to start it, however doing this doesn't display a command prompt.

**Comment by darnold64** [comment]
Managed to get things working.  Plan to migrate it from my PC to either a Rasberry Pi or to a Synology NAS.  I have one minor issue with the browser interface which I will post separately.
