### ISSUE TITLE
Having to repeat command

### ISSUE THREAD

**Issue by lemrock** [bwssytems/ha-bridge#605]
Ever since release 4.1.1 (and releases thereafter) I find myself having to repeat a command.  It's not that Echo doesn't hear clearly...the device answers with the affirmative "OK".  But nothing gets executed.  When I repeat the command a second time everything works as expected.   It doesn't happen on every command and I can't tell you how often.  I've experimented with the different releases and found that with  3.5.1 the issue seems to not be there at all.

**Comment by wookienow** [comment]
I have seen similar behavior and thought it was just me or that the devices ha-bridge was talking to were not reacting to the commands.

**Comment by bwssytems** [comment]
what is your target system that is having this issue?

**Comment by lemrock** [comment]
The target system is Vera 3:UI5.

**Comment by bwssytems** [comment]
let's turn on debug for the huemulator and httpdevice so we can see what is happening.

**Comment by lemrock** [comment]
I  turned on the proper debugger for the huemulator but not sure for httpdevice.  Anyway, I got the issue to happen and I have attached a log.
[Log.docx](https://github.com/bwssytems/ha-bridge/files/946002/Log.docx)

**Comment by bwssytems** [comment]
It looks like it is getting double requests to change the light state within milliseconds of each other. One set of items is going out with intensity levels and the other ones are going out saying turn off. Is there something else that can control you ha-bridge?

**Comment by lemrock** [comment]
The only thing I can think of is I have multiple Echos. They are located far away enough to not be able to hear when I'm in different rooms. Each has its own wake word too.  Nothing else I can think of.

**Comment by bwssytems** [comment]
Well my thought is incorrect on that as it is coming from the same IP Address and user id. Does the echo have duplicate devices from multiple discoveries?

**Comment by bwssytems** [comment]
Looking at the code is that the ha-bridge is being called twice from the same device, your echo. I would do a forget all devices and discover again. Also, could you post your device.db file. Thanks

**Comment by lemrock** [comment]
I realized that I have a second HA bridge initialized on another port but with no devices attached.  This was from the days when there was a device limit per bridge.  Could this be the reason for my issue?

**Comment by bwssytems** [comment]
Yes, This is the issue. The other echo is sending the response through the original echo. They have hive minds and share configurations.

**Comment by bwssytems** [comment]
Also, they use each other to execute commands. i.e.  echo2 hears command and when it comes back from amazon it goes to echo1.
