### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by Neuroplant** [bwssytems/ha-bridge#606]
Hello,
as Amazon provides Alexa funktions in FireTV it would be nice to make it clear that FireTV is no Echo/ FireTV does not work with local Smarthome devices, when there is no real Echo[Dot] is present.
Best Regards and thanks for the good work,

Neuroplant

**Comment by bwssytems** [comment]
Will put this in the wiki

**Comment by bwssytems** [comment]
FAQ updated
