### ISSUE TITLE
Display problem when changing "Use Link Button"

### ISSUE THREAD

**Issue by mprangenberg** [bwssytems/ha-bridge#607]
I recently upgraded to 4.5.0. When i wanted to enable the link button feature i updated the security settings and got a short message in the background that everything went fine. When i re-opened the security-dialog later the checkbox was unchecked again. I tried it again and reinitialized the bridge with the same effect. I haven't checked if the link button was displayed on the devices page, though. After restarting the service via systemctl the button was finally checked. The same goes for turning the feature off.

**Comment by bwssytems** [comment]
Did you select the update button after checling the box?

**Comment by mprangenberg** [comment]
Yes, several times and i also saw a little box in the background notifying me about success every time.

**Comment by mprangenberg** [comment]
Strange, i tried it again today after restarting the RPi and it worked as it should. Maybe it had something to do with upgrading?
