### ISSUE TITLE
Link-Button-Feature and Hue App

### ISSUE THREAD

**Issue by mprangenberg** [bwssytems/ha-bridge#608]
I recently upgraded to 4.5.0 and tried out the Link-Button-Feature. My findings were somewhat strange. The Amazon Echo didn't need to be (re-)authorized, probably due to it's Whitelist entry already existing. The Hue-App though had problems connecting, always asking to authorize via the link-button. When i used the button on the devices-page it worked for exactly 30 seconds. As soon as the stop-message for the link-button pops up, the Hue App needs to be re-authorized. While the link-button is pressed or the feature is disabled completely the app works without a glitch. Is this a known bug? I've disabled the link-button for now, as i use the app quite a lot when i'm in a different room than the echo.

**Comment by slowbolio** [comment]
ive got kind of the same problem. Ive managed to get it working on a windows computer somewhat but now when i installed it on my raspberry pi i cannot "link" to "ha bridge". I use the logitech harmony app and it finds the bridge but it doesnt matter if i press link or remove the button altogether. I cannot add the bridge.

i can easily add the original hue bridge too my harmony app but it doesnt seem to recognize ha-bridge.
this is a comment from the log file 
"raspberrypi rsyslogd-2007: action 'action 17' suspended, next retry is Wed Apr 26 00:57:41 2017 [try http://www.rsyslog.com/e/2007 ]"

any ideas? 
i have to say: this is one of the most creative and cool softwares written. Keep up the good work!

**Comment by slowbolio** [comment]
I have to ask: does anyone have problems running domoticz and ha bridge on same device? Other apps who scans the network can find both habridge hue and my original hue but the "buttonpress" for connecting with it doesnt seem to work.

**Comment by bwssytems** [comment]
I am seeing the same issue. Just not sure why the HUE App does not keep the username from the link button negotiation. Still looking.

**Comment by bwssytems** [comment]
Found it! fixed for next release.
