### ISSUE TITLE
Bridge not found

### ISSUE THREAD

**Issue by scargill** [bwssytems/ha-bridge#609]
I have HA-Bridge running back home in the UK - no problem in a Raspberry Pi.

I have a new installation here in Spain - I have two Alexa units here working perfectly (well, other than they won't report the weather here!)

I've set up Ha-Bridge as normal on port 82.  It works. I've given it two devices (exe - running mosquitto_publish) and I've tested them in Ha-Bridge with the on-off controls - all works perfectly.

However - when I tell Alexa to find devices - it finds one device (a customised SONOFF device) - but will NOT find these devices.

In my router, UPNP is ticked - and in the Bridge on the Pi, it refers to the correct IP address and port.

Help.

**Comment by bwssytems** [comment]
Are all your Echo units on one account?

**Comment by bwssytems** [comment]
Anything here?

**Comment by scargill** [comment]
I do hope so I’m getting no-where with the new HA-Bridge – my alexa is just not seeing it.

**Comment by bwssytems** [comment]
So, I assume you are running a second bridge in the Spain location?

**Comment by scargill** [comment]
In the UK location I had 2… and it seemed to pick everything up just fine…

 

In Spain… let me see….Right, with one device attached – I told Alexa to find devices and it found the one device I’ve created…. (2 devices as there is also an ESP8266 device which works with Alexa).  Yup – sure enough I can turn the Pi device on and off.

 

So I turned on the second Pi with Habridge on that… told Alexa to find devices and… it is still working – HOW ON EARTH is that – it wasn’t working before.

 

Dooooohhhh….

**Comment by bwssytems** [comment]
Sometimes, it happens.... glad you got it solved.
