### ISSUE TITLE
Webhook for Harmony not being saved

### ISSUE THREAD

**Issue by DanfieldNet** [bwssytems/ha-bridge#610]
I'm able to define a Harmony hub with IP via web interface, but it will not save the an entered webhook URL.

**Comment by NovaGL** [comment]
Same here, it just puts blank there

**Comment by SlingMaxwell** [comment]
I'm encountering this same defect.  I enter a webhook URL, but it just shows a blank and does not store it in the config file.

**Comment by bwssytems** [comment]
I assumee this in 4.5.0?

**Comment by DanfieldNet** [comment]
Yes, 4.5.0, at least for me.

**Comment by NovaGL** [comment]
Me too

**Comment by audiofreak9** [comment]
Add me to that list v4.5.0

**Comment by bwssytems** [comment]
I should really finish my implementations......

**Comment by DanfieldNet** [comment]
Is there a work-around by directly editing the .ini file and, if so, what is the format?

Thanks!

**Comment by bwssytems** [comment]
Yes, in the habridge.config file after the  name and ip of the harmony, add this ',"webhook":"http://192.168.0.1/activity/${activity.id}/${activity.label} OR http://hook?a=${activity.label}"'

**Comment by NovaGL** [comment]
Thanks. Is there anyway to decrypt config for direct manipulation

**Comment by bwssytems** [comment]
Th only part of the config that is encrypted are the security settings and passwords. If you want to write a lot of code to decrypt with the key you give, have at it, but it is encrypted for a reason.....

**Comment by NovaGL** [comment]
I just want to batch update the IP of devices but can't see a way
