### ISSUE TITLE
Error creating URI http request

### ISSUE THREAD

**Issue by Parkash067** [bwssytems/ha-bridge#611]
I add Envisalink in device list but when I hit request failed to get response

Error log:
Error creating URI http request: [{"item":"http://192.168.0.xxx:xxxx/api/alarm/armwithcode?alarmcode=xxxxx"}] with message: Illegal character in scheme name at index 0: [{"item":"http://192.168.0.xxx:xxxx/api/alarm/armwithcode?alarmcode=xxxx"}]

![2017-04-26-145243_1440x900_scrot](https://cloud.githubusercontent.com/assets/12471633/25428750/1dd07800-2a90-11e7-8190-a727d8a28bc9.png)

**Comment by bwssytems** [comment]
Just put the http call into that field. Target item is item in json

**Comment by Parkash067** [comment]
I already tried but it didn't work too
{"item":"http://192.168.0.xxx:8111/api/alarm/armwithcode?alarmcode=xxxx","httpVerb":"GET","type":"httpDevice"}

Then I made a simple script named script.sh for testing purpose 
{"item":"/home/pi/Downloads/script.sh","type":"cmdDevice"}
again same thing happened. I am using HA Bridge verison 4.1.4 , is this issue of version??

**Comment by Parkash067** [comment]
Resolved , I changed version of HA Bridge
