### ISSUE TITLE
(Issue) using math for dimming

### ISSUE THREAD

**Issue by ich777** [bwssytems/ha-bridge#612]
Hello,

i've try to get a value from 0.0 to 1 (0.0 = 0% and 1 = 100%) already i've tried differt methodes to solve my problem but none of them worked actually the way it should be.
Now i am using 0.${intensity.percent} but that's not the best option in my opinion, if i change the percentage to 100 it will gave me 0.1 not 1.

Is there any way to convert from integer to decimal with the math option in ha-bridge? The option ${intensity.math(X/255)} will give me the right value but only if i get a decimal value, or can this added as a request in a future release?

Regards, ich777

**Comment by audiofreak9** [comment]
Try ${intensity.decimal_percent}

**Comment by ich777** [comment]
Already tried but doesn't work.

**Comment by bwssytems** [comment]
What version of the ha-bridge are you running. As @audiofreak9 pointed out, that is the syntax to get what you want but is a recent addition.

**Comment by ich777** [comment]
I'm running (hopefully the latest) version 4.5.0
I've installed it yesterday.

**Comment by bwssytems** [comment]
I'll need to check and see if anything is broke.

**Comment by ich777** [comment]
Thank you very much, in the meantime i will test the docker if there is the same behavior.

**Comment by ich777** [comment]
I've tested all versions down to 4.3.0 and non of them worked for me.

**Comment by bwssytems** [comment]
So, could you post your device config as I have tested this and it sends 0.xx as the value.

**Comment by ich777** [comment]
This is my config for the dimmer:

http://x.x.x.x/config/xmlapi/statechange.cgi?ise_id=xxxxx&new_value=${intensity.decimal_percent}

**Comment by gitpaddex** [comment]
Hello,

i have the same Problem.
I have increased the loglevel and found the following

http://192.168.X.X/config/xmlapi/statechange.cgi?ise_id=4641&new_value=0,31

There ist 0,31 and not 0.31

Is it possible to change this to an dot?

Greating

Maik

**Comment by bwssytems** [comment]
@ich777 and @gitpaddex I am going to assume internationalization is happening on the string format in Java. If your local formatting uses a comma for decimal number separation, that will be the issue. I will need to look at forcing the dot in the number.

**Comment by gitpaddex** [comment]
Thank you

**Comment by ich777** [comment]
Thank you!
