### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by benburkhart1** [bwssytems/ha-bridge#613]
I recently migrated from a much older version of ha-bridge. In doing so I nuked my data directory to start over. While following the instructions to POST to /api/devices I noticed that your application expects
onUrl and offUrl to be a string. It actually takes a JSON string of an array, not an array:

So in your basic example:

```
{
"name" : "bedroom light",
"deviceType" : "switch",
  "onUrl" : [{"item":"http://192.168.1.201:3480/data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:SwitchPower1&action=SetTarget&newTargetValue=1&DeviceNum=41","type":"veraDevice"}],
  "offUrl" : [{"item":"http://192.168.1.201:3480/data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:SwitchPower1&action=SetTarget&newTargetValue=0&DeviceNum=41","type":"veraDevice"}]
}

```

It should actually be:

```
{
"name" : "bedroom light",
"deviceType" : "switch",
  "onUrl" : "[{\"item\":\"http://192.168.1.201:3480/data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:SwitchPower1&action=SetTarget&newTargetValue=1&DeviceNum=41\",\"type\":\"veraDevice\"}]",
  "offUrl" : "[{\"item\":\"http://192.168.1.201:3480/data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:SwitchPower1&action=SetTarget&newTargetValue=0&DeviceNum=41\",\"type\":\"veraDevice\"}]"
}
```

This can be demonstrated also by using your basic example and using curl to post against my /api/devices

curl -X POST -d '{"name" : "bedroom light","deviceType" : "switch",  "onUrl" : [{"item":"http://192.168.1.201:3480/data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:SwitchPower1&action=SetTarget&newTargetValue=1&DeviceNum=41","type":"veraDevice"}],  "offUrl" : [{"item":"http://192.168.1.201:3480/data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:SwitchPower1&action=SetTarget&newTargetValue=0&DeviceNum=41","type":"veraDevice"}]}' http://192.168.0.2/api/devices
<html><body><h2>500 Internal Error</h2></body></html>root@bedroom-htpc:/home/bedroom/smarthomesoft#

When I have onUrl/offUrl as a quoted JSON string, it works fine:

curl -X POST -d '{"name" : "bedroom light","deviceType" : "switch",  "onUrl" : "[{\"item\":\"http://192.168.1.201:3480/data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:SwitchPower1&action=SetTarget&newTargetValue=1&DeviceNum=41\",\"type\":\"veraDevice\"}]",  "offUrl" : "[{\"item\":\"http://192.168.1.201:3480/data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:SwitchPower1&action=SetTarget&newTargetValue=0&DeviceNum=41\",\"type\":\"veraDevice\"}]"}' http://192.168.0.2/api/devices

**Comment by bwssytems** [comment]
Yes, This was due to backwards compatibility when I put the json array in. I should add some more logic to test the element before converting.
