### ISSUE TITLE
Echo Dot isn't discovering my device

### ISSUE THREAD

**Issue by Parkash067** [bwssytems/ha-bridge#614]
I configured device on HA Bridge it is working properly but my Echo Dot is not discovering this device, need help ....

**Comment by bwssytems** [comment]
So, pretty thin info here. Search the issue list in the closed issues as this has been discussed so many times. And also look at the wiki https://github.com/bwssytems/ha-bridge/wiki.

I have to say your pretty pretentious for someone who is an IT person.... just saying... search is your friend
