### ISSUE TITLE
Milights not controllable via TCP in 4.5.0 or 4.3.1, but is okay in 4.1.4

### ISSUE THREAD

**Issue by Jinsterrrr** [bwssytems/ha-bridge#615]
I have been loading HA-bridge using a batch file in windows with the command line
java -jar -Dserver.port=80 "c:\ha-bridge-4.1.4.jar" -Dconfig.file=c:\data\habridge.config
and it has been working well.

I have recently downloaded ha-bridge 4.5.0
Changing the command to suit, the script loads properly, with no errors. The Milight devices still show up, but cannot be triggered for some reason. It's still using the same tcp command obviously since it's loading the same config file. And it says executed successfully, but the lights don't come on.

Loading back 4.1.4 everything still works fine, just not if I load 4.5.0 or 4.3.1 instead...

**Comment by bwssytems** [comment]
Pleaes post the milight device configuration. Thanks

**Comment by Jinsterrrr** [comment]
I am not sure if I am doing this right. I am using Milight wifi box hardware version 4. It's set to TCP-server mode, at static IP address 10.0.0.201

HA-bridge is simply setup to (what I think) execute a http address which turns on the Milights and a separate http address which turns off the lights.

So, they are configured as:
for on
Type: TCP device
Target Item: http://10.0.0.201:8899/0x380055

for off
Type: TCP device
Target Item: http://10.0.0.201:8899/0x3B0055

What I have found just now is that if I execute the exact same http address in a browser, I get the same inconsistent weird light behaviour (some lights change colour, others turn on or off, and completely unpredictable which light group does what each time).

But if I execute the same addresses using the Test On or Test Off buttons in HA-bridge interface, it works fine.

Am I doing the configuration wrong?

**Comment by bwssytems** [comment]
Ahh yes, the target itme needs to use tcp:// not http://

**Comment by bwssytems** [comment]
Or, it is the other way around and should be an HTTP device

**Comment by bwssytems** [comment]
Any update on this?

**Comment by Jinsterrrr** [comment]
Been away on holiday. Will test it when I get back on Monday. It seems to make sense. I don't know why in the old version the http address worked. A bug in my favour perhaps. Haha.

**Comment by Jinsterrrr** [comment]
Ok. Tested and working. It was my error to use http prefix for the tcp command. Even though it worked in the earlier versions of ha-bridge, it no longer did in the latest. So I changed the http to tcp and everything is fine. Thanks, Dev.
