### ISSUE TITLE
Execute bat files

### ISSUE THREAD

**Issue by herbiems89** [bwssytems/ha-bridge#616]
Im trying to run a bat file via the HABridge but even after reading trough https://github.com/bwssytems/ha-bridge/issues/197 i still cant get it to work :/

I tried it like this:

![image](https://cloud.githubusercontent.com/assets/19638125/25552311/71b8fb10-2c96-11e7-9c2d-340bfbc5ff38.png)

and i get this error:

![image](https://cloud.githubusercontent.com/assets/19638125/25552315/832e523c-2c96-11e7-8c91-6039a9107844.png)

I also tried it like this:

![image](https://cloud.githubusercontent.com/assets/19638125/25552323/a7bff722-2c96-11e7-957f-32a90e55b1df.png)

And i actually got a success confirmation:

![image](https://cloud.githubusercontent.com/assets/19638125/25552327/b92c5078-2c96-11e7-854e-160c09cc45b5.png)

However it doesnt actually work. If i run the bat manually it works. 
Im running HABridge on  Windows Server 2012R2.
Any advice? :)

**Comment by tuicemen** [comment]
Try just typing in the path **_C:\pstools\shutdown_desktop.bat_**

**Comment by herbiems89** [comment]
Doesnt help either :( It shows the same success confirmation as my try with cmd.exe in front of it, but it doesnt do anything either. I´d like to have a look in the logs, can you tell me where i can find them under windows?

**Comment by tuicemen** [comment]
bridge logs are under logs scroll down to logging configuration to set the views you wish.
 Have you set the device type (informational) to **_Execute Script/program_** ?

**Comment by herbiems89** [comment]
Yes i have, this is what the whole page looks like.

![image](https://cloud.githubusercontent.com/assets/19638125/25558154/ccc37942-2d20-11e7-9c64-3704ad030417.png)

**Comment by tuicemen** [comment]
Have you set your windows firewall inbound rules to allow java?
I run a very simular batch fie to turn on/off my PC display.
When you say it works manually, is that clicking on the bat file or running the command from CMD?

**Comment by herbiems89** [comment]
Sorry for not responding sooner. I figured it out. It seems that if you call a bat via HA-Bridge the bat doesnt start in the folder where you saved it, like it normally does. Instead you have to navigate to said folder via the cd command, then it works.

But thanks for your help anyway :)
