### ISSUE TITLE
Long Press for Harmony

### ISSUE THREAD

**Issue by narcosi** [bwssytems/ha-bridge#618]
Hi, my TV requires a long press for ON

When i setup a harmony activity then this works fine, but the problem with that is that if the harmony thinks the TV is on when it is off then it WONT run the harmony on activity. so i have to ask alexa to turn off the tv then turn it on. even if its off

what i really want is just to program a device button press with a long press command is this possible?

[{"device":"24408818","button":"PowerOn"}] is what i have now but this is instant press - i even tried adding lots of these but that didnt work.

also is it possible to chain commands in the harmony?

thanks

Jon

**Comment by narcosi** [comment]
i solved the long press andmultiples with this:

[{"device":"24408818","button":"PowerOn"},{"device":"24408818","button":"PowerOn"},{"device":"24408818","button":"PowerOn"},{"device":"24408818","button":"PowerOn"},{"device":"24408818","button":"PowerOn"}]

**Comment by audiofreak9** [comment]
Alternatively you could have listed the `[{"device":"24408818","button":"PowerOn"}]` once and added 5 to the count column.

**Comment by narcosi** [comment]
I dont have a count column - does this mean i have an old version?

also the above fix is not quite a fix - it works when the TV is recently turned off but when it is coming on from a long period of off it doesnt work, an press and hold is needed

any ideas how i could try to achieve this?

**Comment by audiofreak9** [comment]
To find out what version you are running click About in the ha-bridge navigation, current is 4.5.0.

Does the Harmony offer a long press PowerOn button command from the listed commands on the Harmony Devices page?

**Comment by narcosi** [comment]
No it doesn't but when I set up an action in harmony it knows it's a long press - I hate Harmony - why can't u just program a macro as you want grrr

______________________________

On 15 May 2017, at 23:22, audiofreak9 <notifications@github.com<mailto:notifications@github.com>> wrote:


To find out what version you are running click About in the ha-bridge navigation, current is 4.5.0.

Does the Harmony offer a long press PowerOn button command from the listed commands on the Harmony Devices page?

**Comment by audiofreak9** [comment]
Have you read this: https://support.myharmony.com/en-us/adjusting-a-devices-command-repeats#harmonyapp

**Comment by digiltd** [comment]
Are you turning the TV on and off with two separate activities?

>  but the problem with that is that if the harmony thinks the TV is on when it is off 

This might be the problem, Harmony should know if the TV is on or off. Are you using other remotes to turn the TV off?

**Comment by bwssytems** [comment]
There will now be a pressTime value for milliseconds on a button
