### ISSUE TITLE
Should I be able to connect to the HA-Bridge from android?

### ISSUE THREAD

**Issue by diecastgit** [bwssytems/ha-bridge#62]
I am setting up HA-Bridge and Domoticz while my Echo is still in the post to me. I have set up bwssytems/ha-bridge on windows, and am trying to connect to test it with the Hue app on Android. The app finds the 'hub' but displays an error "The connection with the bridge has been lost" when trying to set it up, should this work?

Update; The windows WinHue app gives the error "An error occurred while getting the basic bridge configuration" and the other android app I tried, 'all 4 hue', gives me the error "Selected Philips Hue Bridge with IP address 192.168.1.20 is not responding"

**Comment by bwssytems** [comment]
It has worked in the past but I have not tested the app in a while though.

**Comment by bwssytems** [comment]
Tested the Philips HUE android app and I have no issues with connecting and showing devices. Is this still an issue with your system? Also, what version of the ha-bridge are you using?

**Comment by bwssytems** [comment]
Any new comments?

**Comment by farhanito** [comment]
Using v1.4.2, tried Phillips HUE android app, seems like it sees the bridge but refused to connect.

p.s Running on port 8081

**Comment by diecastgit** [comment]
I'm using v1.4.1. I have got the Amazon Echo, and it finds the devices fine, as I was only trying to use the android apps to test before the Echo came, it doesn't really matter to me, but no both the Philips HUE android app and the All 4 Hue app see the bridge, but do not connect / loose connection to it before they can do anything useful as they did in the OP.

**Comment by bwssytems** [comment]
Ahh, yes, any port other than 80 does not work well with those apps. Forgot about this as someone else had the same issue. The Apps only work if your bridge is on port 80.

**Comment by diecastgit** [comment]
If so, why does the default HA-Bridge install run on port 8080?

**Comment by bwssytems** [comment]
Due to the fact that most computer systems already have some thing running on port 80 and if you run it as a user and not root on linux, you cannot use port 80 as it is considered restricted. You can just set the port in the config and save it if you prefer.

**Comment by bwssytems** [comment]
Since this is answered. Closing.
