### ISSUE TITLE
FireTV isn't able to discover devices

### ISSUE THREAD

**Issue by Manawyrm** [bwssytems/ha-bridge#620]
Hello,

I have tried to install ha-bridge and configure my FireTV's Alexa to work with it. 
Unfortunatly, Alexa will not find any devices.

This is what I have tested: 
FireTV via WiFi and Ethernet
ha-bridge on Laptop, ha-bridge on Virtual Machine on my Homeserver-Setup,
Laptop directly connected to the FireTV via a straight-thru LAN cable,
IGMP multicast snooping is disabled everywhere, the multicast listener reports and packets get thru the network, 
Discovery of devices via Webinterface and via Voice command instantly gives a negative response. 

My IPv4 network is located at 10.4.0.0/16, 
the FireTV (via Ethernet) is 10.4.0.33, 
my Laptop (running ha-bridge) is 10.4.0.77.

The bridge is configured as follows: 
https://screenshot.tbspace.de/wqkmjytgfzn.png

My 1 device is configured like this: 
https://screenshot.tbspace.de/afowbsiunrv.png

/api/devices returns this: 
https://screenshot.tbspace.de/cgjdqekvoiu.png

/description.xml (pulled by the FireTV) contains this: 
https://screenshot.tbspace.de/lxrhuwqzgkm.png

and this is what the (filtered) communication between my laptop and the FireTV looks like: 
https://screenshot.tbspace.de/jbcdvogwfqt.png

UPnP trace debugging is enabled in ha-bridge, and I am not seeing any response in the terminal to my Discovery request to Alexa. Only the periodic upnp announces. 

I do not see M-SEARCH *-packets from the FireTV as I would like to see. That's probably also the problem. 
iptables rules are not set on any of the devices, the software runs as root, and ip maddr show also shows that the kernel is subscribed to the multicast IPv4 address. 

Do you have any ideas on how I could debug this problem? 
Thank you very much,
Tobias

**Comment by audiofreak9** [comment]
For discovery, you need a physical Echo, Dot or Tap.

**Comment by Manawyrm** [comment]
Amazons FireTV has gotten full Alexa-functionality from it's last update, and I am seeing the HTTP requests asking for the description.xml. Also: I can configure extra skills on the amazon.alexa.com page.
Are you sure that the FireTV will not work?

**Comment by bwssytems** [comment]
Interesting, it shows in your trace that the document was sent back, that is the TCP trans for 1505 bytes. The trace upnp should show that a certain IP requested the description.xml, so did it?

**Comment by Manawyrm** [comment]
I borrowed an Echo Dot today, and unfortunatly it works at first try. 
So altough the FireTV seems to be detecting the ha-bridge, it seems to be arbitrarily limited to not talk to it. 
When the Echo Dot is on, ha-bridge works wonderfully on both the Echo Dot and the FireTV. 

I'll go and ask Amazon about standalone Philips Hue support, but as long as that isn't coming up, I'm thinking about putting an Echo with (hardware side) disconnected microphone in my server rack... 

Thank you for your time, 
Tobias

**Comment by chross** [comment]
Issue is closed however I can confirm this exact behavior that Manawyrm described.
