### ISSUE TITLE
shutdown script issue

### ISSUE THREAD

**Issue by kai27** [bwssytems/ha-bridge#621]
Hello! 

I created a script for "on items" to start my NAS with WOL. This script works perfectly. So I decided to use a script to shutdown my NAS as well. This Script works without the ha-bridge. When I define at "off items" Type "Execute Command / Script" with target item the path of the script, nothing happens. 
When I click on "test off" i get a positive feedback in green with the information it was executed. 

The script do a ssh-login to the NAS and do the shutdown command. Whats wrong here?
Thanks in Advance

**Comment by bwssytems** [comment]
How are you running your bridge? And also, is there a path to your script?

**Comment by kai27** [comment]
I am running the bridge 4.5.0 on a zero pi w on port 80. yes, my first script for wake on lan with path "/home/pi/wol/nas.sh" works perfectly. I installed etherwake and my NAS is starting with Echo-Command.
Shutdown don't work with Path "/home/pi/wol/nasoff.sh". The Pi connect via SSH to my NAS and make a shutdown-command (ssh -o StrictHostKeyChecking=no USER@IP-ADDRESS /sbin/shutdown -h now). When I execute the script via command line on the pi, my nas is shuting down. With the HA-Bridge nothing happens. I don't know whats wrong :(

**Comment by bwssytems** [comment]
What user is running the ha-bridge? (ps aux on the command line should tell you)

**Comment by kai27** [comment]
Do you mean the java process? Then it is as root but I'm logged in with "pi" user. 
![screen shot 2017-05-08 at 17 27 27](https://cloud.githubusercontent.com/assets/28395187/25811595/14b75972-3414-11e7-81e3-3ad6e3e281e9.png)

**Comment by kai27** [comment]
hi,
I solved my problem myself. I just copied the public key for ssh connect in the pi/.ssh folder and not for the root-user. so the root-user could not connect to my nas via ssh. my log on my nas told me. I am an idiot. Thanks for the help anyway!

**Comment by bwssytems** [comment]
Glad it is solved!
