### ISSUE TITLE
Support for Logitech Pop

### ISSUE THREAD

**Issue by ahertz** [bwssytems/ha-bridge#623]
I'm trying to get the <a href="https://www.logitech.com/en-us/product/pop-smart-button">Logitech Pop</a> to work with ha-bridge, with little success.  The Pop's bridge sees the ha-bridge, and lists the devices I have configured.  But, it's not able to actually turn on and off a light.

Looking at packet captures, it appears that it's trying to use the scene API rather than directly manipulate individual lights.  I see that trying to recall a scene is unimplemented, returning a 404 which throws an error in the Pop app.  So far, so reasonable.

The really weird thing is that the Pop doesn't seem to ever create the scene before it invokes it!  I assume that it must have some logic to try invoking the scene, and, if that fails, create it.  I don't have a real Hue hub, and the Philips documentation on what the error messages are are pretty vague.  To test my theory, can anyone with a real hub tell me what the error message for an invocation of an invalid scene is?  That is, do a PUT to

`/api/<userid>/groups/0/action`

with a body of

`{"scene": "dAgckOe5XTPOgqV8"}`

(or some other non-existant scene identifier).

I guessed that it should look something like:

`{"error":{"address": "/groups/0/action/scene", "type":"3"}}`

but that was just enough to confuse the Pop into throwing an error at the app, but not to get it it to actually create the scene.

Thanks in advance for any help!

**Comment by bwssytems** [comment]
Without a deep look at the api for the pop, we will all be lost. I would keep doing a trace to see what commands are sent, maybe some sort of security binding. Otherwise, the ha-bridge should have all the facilities to work with it.

**Comment by ahertz** [comment]
Thanks.  I'll keep poking, and will put in a pull request if I get it working.

**Comment by bwssytems** [comment]
I don't think you will need any special code unless there is a security login

**Comment by ahertz** [comment]
It did turn out to need a little code (pull request submitted).  Here's how it works:  the Pop authenticates to the bridge using the normal user creation process.  To turn on or off a light, it first tries to call a scene.  If that call fails with a normal Hue bridge error message that the scene doesn't exist, it then manipulates the individual lights, then defines the scene for the next time that action is needed.

If it gets a 404 when it calls the scene, it gives up and throws an error in the app.  That's what was happening with the current version of ha-bridge.  I defined a handler for /api/<userid>/groups/<groupid>/action,  which is used to call scenes, and faked out the error message based on a friend's real bridge.  That seems to be sufficient to get it to work.  It still gets a 404 when it tries to create the scene, but that doesn't seem to bother it. 

Of course, the /groups/<groupid>/action call can do a lot of different things, and this error message doesn't make sense for all of them.  But I can't see any way it would break anything that's currently working.

**Comment by bwssytems** [comment]
I totally missed the idea of what you were trying to do. Big brain fart.... lol Yes, the actions portion is not implemented and I see you have pull request that added that. I will include it in the next release. Thanks!

**Comment by BassTeQ** [comment]
Hi I'm experiencing this same issue, the logitec pop software can see the HA Hue Hub but is asking to press the button on the hue hub?
Using HA version 5.1.0.
![screenshot_20180109-095038](https://user-images.githubusercontent.com/32693997/34696397-c1cd2770-f522-11e7-9d43-65db2ab11c85.png)

**Comment by bwssytems** [comment]
Do you use security linking in the security settings on the ha-bridge? If so, hit the link button. Otherwise, the  ha-bridge should be in always link mode.

**Comment by BassTeQ** [comment]
Hello, I'm just using the default settings mostly, this is the first time using it.

Security settings below, I've pressed update and reinitialised the bridge.

![image](https://user-images.githubusercontent.com/32693997/34744800-88516dec-f5e2-11e7-85e2-cbd2989cea82.png)

**Comment by bwssytems** [comment]
select the use link button, then use the 'link' button on the config page.

**Comment by BassTeQ** [comment]
I've selected it and pressed update, although I can't find the "link" button on the config page.

![image](https://user-images.githubusercontent.com/32693997/34746892-fcec20dc-f5e9-11e7-93f8-9d64bafccbab.png)

**Comment by bwssytems** [comment]
So, you will need to turn on trace upnp in the bridge control tab and then post the log here. Also, this is not the same issue as the OP as that was to include support to call a logitech POP.

**Comment by BassTeQ** [comment]
Ahh ok, my mistake, I'm trying to use my POP device to find a HA Bridge (as a Philips Hue).
Here's the log.
[ha.log](https://github.com/bwssytems/ha-bridge/files/1621018/ha.log)

**Comment by ahertz** [comment]
Looking at your system and mine, the major difference I see is that you're running on port 83 instead of 80.  I'd suggest changing that to port 80 and trying again.  Real Hue bridges listen on port 80, and the Pop hub may have that assumption hardcoded.

If that doesn't do the trick, let me know and I'll see if I can reproduce the issue.

**Comment by BassTeQ** [comment]
Thanks that did the trick! The POP can now see the device configured in HA Bridge, however it doesn't look like its controlling the configured device in HA Bridge. Is there any debugging I can enable to see if the POP is attempting to turn ON the HA device?

Cheers

**Comment by ahertz** [comment]
If you set logging for com.bwssystems.HABridge.hue.HueMulator to DEBUG, you should see the requests hitting the Hue API.

**Comment by BassTeQ** [comment]
Done, and restarted the bridge, I'm not seeing any requests in the log when pressing the pop buttons.
The pop buttons are working fine with other devices.

**Comment by BassTeQ** [comment]
I've done more testing using a generic hue app, it found the hub and can control the device. When looking at the log using the generic app I see this.

01-11-2018 15:44:24.323 | DEBUG | hue state change requested: 4aea436b491d468fac56b09a41260acf from 192.168.100.38 body: {"on":true} | com.bwssystems.HABridge.hue.HueMulator
-- | -- | -- | --
01-11-2018 15:44:24.325 | DEBUG | Decode Json for url items: [{"item":"http://192.168.100.100:82/JSON?request=controldevicebyvalue&ref=577&value=100"}]

With the POP switches, they are unaware of the ON/OFF state of the light, its a dumb switch that sends an ON/OFF command. I wonder if this is could be causing my problems?

**Comment by bwssytems** [comment]
@BassTeQ What version are you using? IT looks like the Release Candidate. That error message is not correct. You have no error.

**Comment by bwssytems** [comment]
@BassTeQ Also, your controller is calling a scene in the ha-bridge and that is why you may not be seeing the results.

**Comment by BassTeQ** [comment]
Hi, I'm using v 5.1.0. So whats the best way to troubleshoot this issue?

**Comment by ahertz** [comment]
I'd suggest firing up Wireshark on the same box you're running ha-bridge, and see what the traffic between the Pop and ha-bridge actually looks like when you trigger it.
