### ISSUE TITLE
issue running ha-bridge and real Hue bridge at the same time on google home

### ISSUE THREAD

**Issue by Matt8119** [bwssytems/ha-bridge#624]
i was able to successfully sync the the HA with the current 4.5.0 file to my google home, but i was forced to remove my real HUE hub before it would give me ability to connect.  now that the HA is up and running with the google home, it only shows "one" hue icon in the home controls section.  how do i also add/re-sync my original HUE hub to the google home so i can have the emulated HUE and my real HUE running at the same time?

**Comment by volcan96** [comment]
If I'm understanding your question, I think you can only have 1 'hue' device.

Habridge would be the main hue device paired with Google Home.
'Real Hue' links to habridge
you control the 'real hue' devices via Google Home & HA Bridge

kind of like this:

Voice Command -> Google Home ->HaBridge -> real hue

**Comment by Matt8119** [comment]
That makes sense. I have few items already connected to my ha-bridge, but where I'm really stuck on is how to proxy my real HUE bridge to the Ha-bridge. I see it's possible, but I can't find any write ups or directions on how I go about doing it..  Thanks!

**Comment by bwssytems** [comment]
So is this answered based on your other post?

**Comment by Matt8119** [comment]
Yes. Thanks!
