### ISSUE TITLE
Open/close?!

### ISSUE THREAD

**Issue by oktane83** [bwssytems/ha-bridge#627]
Is there any way to be able to say "Alexa, open the blinds. Or close? Instead of " Alexa turn off/on the blinds"?

**Comment by tuicemen** [comment]
I believe here are a few words you can use instead of on/off and Alexa will send the command to the bridge.
Unfortunately open/close won't work presumably it associate them with web searches.
When I first got my dot I experimented with different activation phrases however I find I use on/off most often so I've forgotten all that worked for me.
activate/deactivate  run/stop I seem to remember worked for me.

**Comment by bwssytems** [comment]
I believe open and close have now been reserved and not for use with the hue

**Comment by autofrank** [comment]
Hi,
Firstly, thanks for creating this. I have a fibaro HC2 and have started using this and it's great, It a much faster response time that the native skill. I mainly use the generic http on/off/dim

do the commands activate/deactivate and run/stop work for the generic http commands?
Would it be possible to add open and close for the http as it would be great to use for gates and garage doors ?

**Comment by bwssytems** [comment]
That would not make sense as the http commands are specific to your target system. As mentioned, the echo does not let you use those words with the Hue.

**Comment by tuicemen** [comment]
The few alternate words I had success with were only tested with Exec commands.

**Comment by autofrank** [comment]
Hi bwssystems,
I am not using Hue and was wondering if that makes a difference. but perhaps options need to apply to all options in the "type" drop down
I was looking for open/close for just the http device

If open / close are not possible, would raise/lower (blinds and garage doors) or run (for scenes) 

Thanks
_f

**Comment by autofrank** [comment]
Hi tuiceman
Could you expand on your comment
What other words did you have success with and what do you mean by exec commands ?

thanks
_f

**Comment by tuicemen** [comment]
EXEC commands is the execute command/script/program option.
The exact words I had success with I don't remember as I played with a number of variations. 
I ultimately didn't find activation/deactivation combo words that felt natural for my name device so I renamed the device but I do remember finding alternative words.

To see what works for you first  make a list of on activation words like start, activate, run ....
Then make a list of off  trigger words like deactivate, stop, end....
Then try to turn on your device with deferent words, if it turns on try your off variations to see what will turn it off.

**Comment by audiofreak9** [comment]
@autofrank What must be understood is that the ha-bridge **emulates** a Philips Hue bridge.  This means the Echo sees the ha-bridge as if it were a real Hue bridge.  Effectively the devices you create in the ha-bridge are seen as Hue devices by the Echo.  Therefore you are limited to the commands that work between the Echo and a real Hue bridge.  These commands can not be changed through programming within the ha-bridge.

**Comment by autofrank** [comment]
@audiofreak9 
Thanks, I didn't realise it was actually emulating the Hue bridge and now it makes sense :-)
Do you know if there are other words that work beside Turn on, turn off and Set level

Thanks

**Comment by autofrank** [comment]
@tuicemen 
Thanks - is there any documentation on how to setup a Exec command or is it reasonable intuitive to do what you suggest to try other words

Thanks

**Comment by tuicemen** [comment]
The call is basically the path to the executable file. testing other words is straight forward you just say "Alexa, (alternate word) call name."

I haven't tested this but you may try setting up a group in the Alexa app (there is no min of devices that can be in a group) once the device is in the group and it has a name you would say "Alexa, (alternate word) group name"
You may have better success with this method but I don't think open/close will work with that either.

**Comment by autofrank** [comment]
@tuicemen 

Thanks, I'll give that a go...
