### ISSUE TITLE
Virtual devices with fibaro commands through ha-bridge 

### ISSUE THREAD

**Issue by Matt8119** [bwssytems/ha-bridge#628]
I am interested to know if anyone has had any luck with controlling LUA virtual devices through their echo/google home via Fibaro HC2 yet? I have a few LUA virtual devices and i cant seem to find an ID for the http command to type into the HA...

**Comment by bwssytems** [comment]
Could you post this on the Fibaro Support request that is already open. Then close this issue. Thanks
