### ISSUE TITLE
Nest Thermo - Temperature in Celcius ?

### ISSUE THREAD

**Issue by winware2000** [bwssytems/ha-bridge#63]
I am located in Europe so my Nest thermos are set to display the temperature in degrees Celsius.
I assumed I could just use degrees Celsius when setting the temperature value in the HA Bridge.
However, I found out that the HA Bridge temperature setting MUST ALWAYS be in Fahrenheit - then and only then, the correct, Celsius-converted temp appears on the Nest itself. 

For example:
- If bridge temp value = 68 (F) then Nest displays 20 C (OK assuming the entry value is in F)
- If bridge temp value = 20 (C) then I get an error: -6.66 (C) value out of range (10 C - 33 C)

Is there a way or modification to have the HA-bridge accept Celsius range (10-33) temp values and send them to Nest in Fahrenheit as expected?

Thanks in advance

**Comment by bwssytems** [comment]
Yeah, I was going to get to this. I'll need to add a setting to control if you want it in F or C. The math is done in the bridge so it is easy.
