### ISSUE TITLE
Is it possible to run this on Android running debian?

### ISSUE THREAD

**Issue by crsnwby** [bwssytems/ha-bridge#631]
Got a HTC M7 with Linux on it and would like to use it as a bridge. Is it possible?

**Comment by bwssytems** [comment]
this is a java program, so theoretically it should work

**Comment by crsnwby** [comment]
Yes you can, took me 2 days to learn android and linux but i have it working now. So my old phone is now a amazon echo hub and I can control my denon amp etc via voice commands.

**Comment by bwssytems** [comment]
We'll put this into the wiki

**Comment by bwssytems** [comment]
Added to wiki
