### ISSUE TITLE
Update readme - incorrect path

### ISSUE THREAD

**Issue by Lorccan** [bwssytems/ha-bridge#632]
$ wget https://github.com/bwssytems/ha-bridge/releases/download/{VERSION}/ha-bridge-{VERSION}.jar

should read

$ wget https://github.com/bwssytems/ha-bridge/releases/download/v{VERSION}/ha-bridge-{VERSION}.jar

**Comment by ibenrodriguez** [comment]
I can add this to my README fix pull request.

**Comment by ibenrodriguez** [comment]
@Lorccan - i looked through the README.MD file and only found 2 lines (74 and 80) with **wget** commands. Here they are - and they both already have the "v" before the version.  Can you pull the latest code and check again? Please update this issue with your test results.

I did notice the instructions were there twice so I'm going to submit a patch to remove the duplicate lines.

Create the directory and make sure that ha-bridge-4.5.0.jar is in your /home/pi/habridge directory.
```
pi@raspberrypi:~ $ mkdir habridge
pi@raspberrypi:~ $ cd habridge

pi@raspberrypi:~/habridge $ wget https://github.com/bwssytems/ha-bridge/releases/download/v4.5.0/ha-bridge-4.5.0.jar
```
Create the directory and make sure that ha-bridge-4.5.0.jar is in your /home/pi/habridge directory.
```
pi@raspberrypi:~ $ mkdir habridge
pi@raspberrypi:~ $ cd habridge
pi@raspberrypi:~/habridge $ wget https://github.com/bwssytems/ha-bridge/releases/download/v4.5.0/ha-bridge-4.5.0.jar

**Comment by Lorccan** [comment]
Sorry, I am pointing you in the wrong place.  It's here: https://github.com/bwssytems/ha-bridge/wiki/HA-Bridge-FAQs under the heading 'How do I update the ha-bridge jar file?'

**Comment by ibenrodriguez** [comment]
That's an easy one - it's just a wiki page so anyone with a github account can edit it.  This is resolved.  Thanks for the suggestion and feedback.

**Comment by Lorccan** [comment]
DIdn't realise I could edit.  I'll do so in future.  Thanks.
