### ISSUE TITLE
Ha-Bridge and Firewall? Which Ports to open for source and destination?

### ISSUE THREAD

**Issue by monukoshy** [bwssytems/ha-bridge#634]
I am trying to setup the ha-bridge on a dedicated ubuntu box.
Following all the steps, and each time i try to start the ha-bridge service, it looks it never starts, upon checking the status, i get this error message.

> root@automation:/etc/systemd/system# systemctl status habridge.service -l
> ● habridge.service - HA Bridge
>    Loaded: loaded (/etc/systemd/system/habridge.service; enabled; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Tue 2017-05-16 14:05:54 CDT; 13s ago
>   Process: 8119 ExecStart=/usr/bin/java -jar -Dconfig.file=/home/automation/habridge/data/habridge.config /home/automation/habridge/ha-bridge-4.5.0.jar (code=exited, status=100)
>  Main PID: 8119 (code=exited, status=100)
> 
> May 16 14:05:54 automation java[8119]:         at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:244)
> May 16 14:05:54 automation java[8119]:         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
> May 16 14:05:54 automation java[8119]:         at org.eclipse.jetty.server.Server.doStart(Server.java:384)
> May 16 14:05:54 automation java[8119]:         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
> May 16 14:05:54 automation java[8119]:         at spark.webserver.JettySparkServer.ignite(JettySparkServer.java:131)
> May 16 14:05:54 automation java[8119]:         at spark.SparkInstance.lambda$init$0(SparkInstance.java:341)
> May 16 14:05:54 automation java[8119]:         at java.lang.Thread.run(Thread.java:748)
> May 16 14:05:54 automation systemd[1]: habridge.service: Main process exited, code=exited, status=100/n/a
> May 16 14:05:54 automation systemd[1]: habridge.service: Unit entered failed state.
> May 16 14:05:54 automation systemd[1]: habridge.service: Failed with result 'exit-code'.
> 

Is this because of a Firewall I have in my home network? Do i need to port forward? My dedicated server box's internal IP is 192.168.1.102
Do i need to open the port 80 for this ip address above for outside world?
Or what else is causing could be causing this issue?

**Comment by bwssytems** [comment]
Well, we need to see the log of the ha-bridge and not the os startup log

**Comment by monukoshy** [comment]
Thanks for your replies.
Uploading the logs here.
https://www.dropbox.com/s/xyth6akqjhu4axx/habridge-log.txt?dl=0

Let me know if you'd like me to upload these logs in a different host, or in a private pastebin session.

**Comment by monukoshy** [comment]
Any help with this, greatly appreciated. I still havent been able to get to work on this.

**Comment by bwssytems** [comment]
You are having a permissions issue on trying to open port 80 as you get the error 'Permission denied'. You can either give permission to use the port to your user or run this as root.

**Comment by bwssytems** [comment]
Did you resolve your issue?
