### ISSUE TITLE
Control of the echo device itself

### ISSUE THREAD

**Issue by autofrank** [bwssytems/ha-bridge#638]
Hi 
Is it already possible or would it be possible to offer some control the echo device itself. 
Specifically I'm looking to control volume and mute so I can either mute the device or lower it depending on location of echo device (bedroom etc) and time of day.

I looked at the AVS API and it's possible through the api

`{
    "directive": {
        "header": {
            "namespace": "Speaker",
            "name": "SetVolume",
            "messageId": "{{STRING}}",
            "dialogRequestId": "{{STRING}}"
        },
        "payload": {
            "volume": {{LONG}}
    }
}`

[https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/reference/speaker](url)

Thanks

**Comment by bwssytems** [comment]
You can use any http output command to any ip you want so, that may work. Go ahead and give it a try!

**Comment by digiltd** [comment]
AVS is what amazon call the service they allow to be run on other devices (pi, fridges, cars etc). It unfortunately isn't an api into an echo device. 

I am not sure of a way but the Alexa app allows volume control and that is basically a packaged website. But I expect it's pretty locked down.

**Comment by bwssytems** [comment]
You could create your own Echo Skill and have it fired by a web call since they are lambda calls.

**Comment by digiltd** [comment]
@autofrank do you want to adjust the volume level of his Echo device remotely and independently of the Alexa? i.e. have a cron job (or ifttt or similar schedule/rule/based service) to fire at 6pm to turn the volume level down to 3 and then at 9am turn it up to 10? 

A workaround would be to use Dots and an external audio device with its own speakers. Then use cron (or whatever) to set the volume level of the external speakers at specific times.

... I spotted a "do not disturb" option in the Alexa app today, it can't set volume but it can mute it at certain times.

**Comment by autofrank** [comment]
@digiltd , @bwssytems 
Thanks 
I have a fibaro HC2 controller and I'm looking for a way to control the volume and mute status from scenes on my controller (via lua)
The AVS API looks like it has a web method (even though I can't see yet how to identify different echo devices) I think I can register an application with AWS and get a token for the API to provide access but I though that the HA bridge must already have this capability but I reckon now,.
I'll take another look at the AWS and see if I can solve it from there

Thanks again
_f

**Comment by digiltd** [comment]
@autofrank Using the AVS API is only going to work if you have built your own Alexa device out of a Pi or similar. 

To clarify, AVS is not a way to connect to an official Amazon Echo product. It is a way to connect an unofficial/homemade device to the Alexa service.

https://github.com/alexa/alexa-avs-sample-app

Hopefully that will save you some hassle :)

**Comment by bwssytems** [comment]
Closing as not an ha-bridge issue
