### ISSUE TITLE
connecting hue hub to ha bridge question

### ISSUE THREAD

**Issue by Matt8119** [bwssytems/ha-bridge#639]
ive read the readme file and i wasn't sure if read it correctly because wasn't too clear on how to connect my real HUE bridge to the HA... 

is it as simple as using a port scanner to find the IP address of the real HUE bridge and entering its IP address in the localhost page next to the "Hue Names and IP Addresses," followed by pressing the button on the real HUE to put it into discovery mode?

thanks!

**Comment by bwssytems** [comment]
That would be correct!

**Comment by Matt8119** [comment]
a big thanks for the fast response!
