### ISSUE TITLE
Manual Device Add - HTTP REST POST Syntax Help

### ISSUE THREAD

**Issue by muglar** [bwssytems/ha-bridge#64]
HELP - I've been at this for three days!

This REST POST will control my garage door 

**http://192.168.3.131:8000/GPIO/3/sequence/400,101**

I've test successfully in POSTMAN

![postman](https://cloud.githubusercontent.com/assets/17802517/13724785/f896690c-e85d-11e5-9a00-a8c39e91e468.png)

However, no matter how I add to the ha-bridge I can't seem to actually get it too work.  Can someone please point me in the right direction on howto correctly add to the HA-BRIDGE.

![image](https://cloud.githubusercontent.com/assets/17802517/13724805/8f615770-e85e-11e5-87ab-1a1f8328ac2e.png)

![image](https://cloud.githubusercontent.com/assets/17802517/13724800/6e7dd740-e85e-11e5-8b1f-fd875cb03ec3.png)

**Comment by audiofreak9** [comment]
Try changing the comma in the URL to %2C this is the urlencoded value of a comma.

**Comment by muglar** [comment]
Thanks for the help.

I tried changing to %2C, however this didn't seem to help.  I've added the output of the test on button and the console of the server.....

![image](https://cloud.githubusercontent.com/assets/17802517/13726283/aca858ee-e88e-11e5-8fd6-f7e0722c883e.png)

**Comment by audiofreak9** [comment]
Have you read the Logs tab of the ha-bridge for the details?  Also, what version of the bridge are you running?

**Comment by muglar** [comment]
I did and believe they have the same output as the console of the server.  My version is 1.4.1.

![image](https://cloud.githubusercontent.com/assets/17802517/13726494/67a6fd8c-e897-11e5-8314-6cf89f16f8cf.png)

**Comment by audiofreak9** [comment]
I keep coming back to blaming the comma as the culprit.  Are you using webiopi?

**Comment by muglar** [comment]
I am!  I've checked the console logs of WEBIOPI and when the bridge doesn't work, it hasn't even sent a post over to the webiopi server.  When I use postman (on the same computer as the ha bridge) you can see the post make it's way to the webiopi server and the garage door open.

I've tried the simpler request of http://192.168.3.131:8000/GPIO/3/value/1  (that doesn't work either)

I've tried every possible combination of input into HA-Bridge I can think off.....so confused.

When I use postman it worked first try.

**Comment by audiofreak9** [comment]
Well we can't blame the comma when it's not there when using the Set GPIO value method.  You did have it set as POST for this as well correct?

**Comment by audiofreak9** [comment]
[This Post](https://www.raspberrypi.org/forums/viewtopic.php?f=44&t=15257&start=50#p207760) may hold the key to the problem.  I see you had 'Headers 0' selected in postman, you may need to send some `headers={'Content-Length':'0'})` in the ha-bridge, however I can't figure out how to set that.  @bwssytems may be able to shed some light on your problem.

**Comment by muglar** [comment]
Actually, I just tried again for the ON URL using the simpler call as well as the OFF URL call with the %2C.....the error log is actually different...this mean anything to you?

03-12-2016 22:08:28.127	ERROR		spark.webserver.MatcherFilter

I noticed that I get the above error message if I leave the optional "content type" default.  If I change it to something different say HTML or * then I get the previous WARN message.

If this makes any sense to you - hope I haven't confused things.

![image](https://cloud.githubusercontent.com/assets/17802517/13726636/748acb7a-e89f-11e5-81b6-a19867d64113.png)

![image](https://cloud.githubusercontent.com/assets/17802517/13726639/8d953916-e89f-11e5-9b7a-6deb874b5152.png)

**Comment by audiofreak9** [comment]
Since I don't think the ha-bridge is sending a 'Content-Length':'0' header, which may be required by webiopi when there is no Body Content set, how about try setting some 'fake' Body content?  
In the Content Body On enter {"fooBar":"baz_on"} 

In the Content Body Off enter {"fooBar":"baz_off"}

**Comment by muglar** [comment]
Thanks for all the advice and tips. Unfortunately this didn't work. @bwssystems any ideas?

**Comment by muglar** [comment]
Any other ideas of how to achieve functionality...so close.

**Comment by muglar** [comment]
I was able to work around this issue by using NODE RED to pass the request from the HABRIDGE.

**(Alexa, Turn ON Garage Door 1) --> ECHO --> HABRIDGE -(get)-> NODE RED -(post)-> WEBIOPI --> GARAGE DOOR**

Alexa, responds with a beep rather than "OK"...not sure how to get her to say **OK**.  Would prefer she said **OK**

![image](https://cloud.githubusercontent.com/assets/17802517/13762169/65a27d68-ea13-11e5-8b29-65732f8daea8.png)

**Comment by emiliosic** [comment]
I noticed the beeps too. I think it's a change from Amazon. It no longer says OK. There is a different beep for On and Off

**Comment by bwssytems** [comment]
I need to take a look at the WEBIOPI and see what it expects. It should be able to handle it.

**Comment by audiofreak9** [comment]
It requires POST and I believe it needs the `headers={'Content-Length':'0'})` sent.

**Comment by bwssytems** [comment]
After looking at the WebIOPi API and handling, it looks like you need to authenticate with the http rest api to have it work. I see you have that in your node-red config. The ha-bridge does not support credential authentication for a http call.

**Comment by muglar** [comment]
Thanks!  Still love the HABRIDGE

**Comment by bwssytems** [comment]
Just want to confirm, you have to authentication with the WebIOPi interface for it to work?

**Comment by muglar** [comment]
I don't believe that you do. I renabled authentication later.

On the first tries with POSTMAN. See first picture on thread I had no
username or password.

In WEBIOPI you can disable authentication by deleting the password and
restarting the web server.

**Comment by bwssytems** [comment]
Then, if you are not using a username/password to make the call, we still have some investigation todo.

**Comment by bwssytems** [comment]
So, I thought I would install this and test it myself.... wrong.... WebIOPi has issues with the RPi2 and I don't feel like patching it.

Could you turn on DEBUG in your version for WebIOPi and post the issue that occurs from the WebIOPi log.

Thanks

**Comment by bwssytems** [comment]
Any new comments?

**Comment by bwssytems** [comment]
No comments received, closing
