### ISSUE TITLE
Is it possible without a physical bridge to control a light?

### ISSUE THREAD

**Issue by crsnwby** [bwssytems/ha-bridge#642]
I have a inur GU10 and would like to voice control it, but I dont know if its possible using only the ha-bridge and an echo. As I cant see a way of adding the bulb to the bridge devices.

**Comment by bwssytems** [comment]
Does it have a protocol that can be send via http/tcp/udp? If so, most likely.

**Comment by crsnwby** [comment]
Its this one, cant seem to see a way of adding it for pairing without a brigde.

https://www.amazon.co.uk/dimmable-retrofit-enabled-Android-compatible/dp/B01LT9UK7I

**Comment by digiltd** [comment]
No, you need to pair it with a bridge. 

Innr bulbs are controlled using a "wireless signal" called Zigbee, this is what Hue (and others, soon to include Ikea bulbs) also use. It is a different technology to the wifi that is used by your home router, phones, computers etc.

The bridge has the hardware inside it to transmit and receive these signals, and the bridge connects to your home network. That is why it is called a bridge, it "bridges" the two things together :) 

If you want a bulb that uses the same wifi signal as your router, have a look at **lifx**. Though they are quite expensive and if you are going to have more than one Innr bulb you would be better off getting a Hue starter kit and then adding more Innr bulbs to that.

**Comment by crsnwby** [comment]
Thanks that was the info I needed, I was racking my brain and google without success trying to figure out why a bridge was needed but if its a different network it makes sense. I got a osram hub in the end as it was cheap so my bulb works, now I need either another 2, or an inline switch thats controllable as its a bathroom light with a fan connected. But again searching for switches in google just brings back remote switches rather than controllable in line switches.

**Comment by digiltd** [comment]
Glad you got it sorted. I am not sure there is that much of a price difference between the Hue Bridge and Osram for the standard white bulbs. Amazon sell a Hue starter kit (bridge and 2 x white dimmable bulbs) for £59, and the Osram starter kit (hub and 1 x dimmable warm to cool bulb) for £60. Inline switches are a bit of a minefield. I have been looking myself and there is a difference in the way that UK and US wire their lights, so you need to make sure which is which. There are also issues if you have a 2 way switch (two separate light switches that turn the same set of lights on and off).

This site has wiring info

http://www.vesternet.com/resources/application-notes/wirings

And you will be thrilled to learned that I am pretty sure there is not a zigbee/hue controllable inline switch. You will need another hub that sends out a z-wave or lightwaverf signal. 

That site is a good resource with lots of guides http://www.vesternet.com/help

**Comment by nldroid** [comment]
I recently found out that Home Assistant supports Hue lights without a bridge:

https://home-assistant.io/blog/2017/05/06/zigbee-opencv-dlib/

So if you already run ha-bridge on a raspberry pi, just add a Zigbee stick and Home Assistant and you can control them without a bridge.
