### ISSUE TITLE
script don' start at pi

### ISSUE THREAD

**Issue by Moing33** [bwssytems/ha-bridge#645]
I won't to run a script on my pi, on which the ha-bridge also is running. 

whan i push the button "test on" on the ha-bridge it, it bring me the green succassge message

the sricpt is only for testing, it should restart the pi:

```
#!/bin/bash

echo "Test"
sudo shutdown -r now
```
on the ha-bridge i add the device following
![ha-bridge](https://cloud.githubusercontent.com/assets/28889102/26348206/4e8a208c-3fac-11e7-8974-77636d506916.PNG)

Then i run the bash on the pi it works fine.
Did i make any mistake?

**Comment by bwssytems** [comment]
Let's take some things out of the picture here to help. remove the 'bash' in front of the script name as it already says it is a bash script internally.

**Comment by Moing33** [comment]
this i have already tested, what was not the solution

but a friend seen it. i have forgot the / for home


so the problem is solved an can be closed
