### ISSUE TITLE
google home now thinks my Bridge is a second light

### ISSUE THREAD

**Issue by Matt8119** [bwssytems/ha-bridge#649]
currently i have one HUE bulb connected through my HA-bridge.  when i tell google to dim or turn off/on "the living room light," it used to respond normally, now it always responds "ok, dimming/off/on two lights." i think its acting like the HUE bridge is the "second" light.  How do i correct this so it responds to each light??

**Comment by bwssytems** [comment]
If you have multiple lights with the word living room in it as the first to phrases, Google Home does not differentiate... You need to have uniquely named bulbs.... This is a Google Home  quirk as naming by room makes it a psuedo group
