### ISSUE TITLE
Bridge Found, but no devices

### ISSUE THREAD

**Issue by flintory5** [bwssytems/ha-bridge#65]
I have HA Bridge set up with 16 lights on an ISY hub. The echo finds the bridge and seems to get the device list, but it doesn't show any discovered. Any thoughts? Here the end of the log after running discover on the echo:

03-13-2016 17:31:05.449	INFO	Traceupnp: SSDP packet from 192.168.1.137:50000, body: M-SEARCH * HTTP/1.1
 HOST: 239.255.255.250:1900
 MAN: "ssdp:discover"
 MX: 15
 ST: urn:schemas-upnp-org:device:basic:1
 
03-13-2016 17:31:05.449	INFO	Traceupnp: sendUpnpResponse discovery template with address: 192.168.1.150 and port: 8080	com.bwssystems.HABridge.upnp.UpnpListener
03-13-2016 17:31:06.011	INFO	Traceupnp: upnp device settings requested: null from 192.168.1.137:8080	com.bwssystems.HABridge.upnp.UpnpSettingsResource
03-13-2016 17:31:06.011	INFO	Traceupnp: upnp device settings template filled with address: 192.168.1.150 and port: 8080	com.bwssystems.HABridge.upnp.UpnpSettingsResource
03-13-2016 17:31:06.389	INFO	Traceupnp: upnp device settings requested: null from 192.168.1.137:8080	com.bwssystems.HABridge.upnp.UpnpSettingsResource
03-13-2016 17:31:06.390	INFO	Traceupnp: upnp device settings template filled with address: 192.168.1.150 and port: 8080	com.bwssystems.HABridge.upnp.UpnpSettingsResource
03-13-2016 17:31:06.706	INFO	Traceupnp: hue lights list requested: hm3JnxYjJAKVDx8OkGQZwk1UKTwslVGKn0or5N29 from 192.168.1.137	com.bwssystems.HABridge.hue.HueMulator
03-13-2016 17:31:06.800	INFO	Traceupnp: hue lights list requested: hm3JnxYjJAKVDx8OkGQZwk1UKTwslVGKn0or5N29 from 192.168.1.137	com.bwssystems.HABridge.hue.HueMulator

**Comment by bwssytems** [comment]
So, it looks like you did not add devices. On the first page of the UI are there any devices listed? You need to create devices from the helper screens. The system does not automatically add them.

**Comment by flintory5** [comment]
Thanks for the response! Yeah, based on the logs, that's what I would think to, but there are 16 individual devices I added manually. Here is the /api/devices response:

[{"id":"777911934","name":"Front Porch","deviceType":"custom","targetDevice":"Encapsulated","offUrl":"http://XXXXXX:XXXXXX@192.168.1.144/rest/nodes/3C%2028%20DF%201/cmd/DOF","onUrl":"http://XXXXXX:XXXXXX@192.168.1.144/rest/nodes/3C%2028%20DF%201/cmd/DON","httpVerb":"GET"},{"id":"2045380197","name":"Master Light","deviceType":"custom","targetDevice":"Encapsulated","offUrl":"http://XXXXXX:XXXXXX@192.168.1.144/rest/nodes/31%204F%2044%201/cmd/DOF","onUrl":"http://XXXXXX:XXXXXX@192.168.1.144/rest/nodes/31%204F%2044%201/cmd/DON","httpVerb":"GET"},{"id":"1803125825","name":"Master Fan","deviceType":"custom","targetDevice":"Encapsulated","offUrl":"http://XXXXXX:XXXXXX@192.168.1.144/rest/nodes/31%2053%205B%201/cmd/DOF","onUrl":"http://XXXXXX:XXXXXX@192.168.1.144/rest/nodes/31%2053%205B%201/cmd/DON","httpVerb":"GET"},{"id":"1757500035","name":"Kitchen Fan","deviceType":"custom","targetDevice":"Encapsulated","offUrl":"http://XXXXXX:XXXXXX@192.168.1.144/rest/nodes/2F%20EA%2068%201/cmd/DOF","onUrl":"http://XXXXXX:XXXXXX@192.168.1.144/rest/nodes/2F%20EA%2068%201/cmd/DON","httpVerb":"GET"},{"id":"2094985729","name":"Basement Movie Light","deviceType":"custom","targetDevice":"Encapsulated","offUrl":"http://XXXXXX:XXXXXX@192.168.1.144/rest/nodes/31%2058%2078%201/cmd/DOF","onUrl":"http://XXXXXX:XXXXXX@192.168.1.144/rest/nodes/31%2058%2078%201/cmd/DON","httpVerb":"GET"},{"id":"502064345","name":"Kitchen Sink","deviceType":"custom","targetDevice":"Encapsulated","offUrl":"http://XXXXXX:XXXXXX@192.168.1.144/rest/nodes/ZW012_1/cmd/DOF","onUrl":"http://XXXXXX:XXXXXX@192.168.1.144/rest/nodes/ZW012_1/cmd/DON","httpVerb":"GET"},{"id":"1887722991","name":"Living Room","deviceType":"custom","targetDevice":"Encapsulated","offUrl":"http://XXXXXX:XXXXXX@192.168.1.144/rest/nodes/ZW011_1/cmd/DOF","onUrl":"http://XXXXXX:XXXXXX@192.168.1.144/rest/nodes/ZW011_1/cmd/DON","httpVerb":"GET"},{"id":"1784270411","name":"Dining Table","deviceType":"custom","targetDevice":"Encapsulated","offUrl":"http://XXXXXX:XXXXXX@192.168.1.144/rest/nodes/ZW013_1/cmd/DOF","onUrl":"http://XXXXXX:XXXXXX@192.168.1.144/rest/nodes/ZW013_1/cmd/DON","httpVerb":"GET"},{"id":"458866122","name":"Basement Light","deviceType":"custom","targetDevice":"Encapsulated","offUrl":"http://XXXXXX:XXXXXX@192.168.1.144/rest/nodes/ZW014_1/cmd/DOF","onUrl":"http://XXXXXX:XXXXXX@192.168.1.144/rest/nodes/ZW014_1/cmd/DON","httpVerb":"GET"},{"id":"1736518086","name":"First Floor Hallway","deviceType":"custom","targetDevice":"Encapsulated","offUrl":"http://XXXXXX:XXXXXX@192.168.1.144/rest/nodes/ZW015_1/cmd/DOF","onUrl":"http://XXXXXX:XXXXXX@192.168.1.144/rest/nodes/ZW015_1/cmd/DON","httpVerb":"GET"},{"id":"90898063","name":"Fire Place","deviceType":"custom","targetDevice":"Encapsulated","offUrl":"http://XXXXXX:XXXXXX@192.168.1.144/rest/nodes/ZW016_1/cmd/DOF","onUrl":"http://XXXXXX:XXXXXX@192.168.1.144/rest/nodes/ZW016_1/cmd/DON","httpVerb":"GET"},{"id":"778744766","name":"Office","deviceType":"custom","targetDevice":"Encapsulated","offUrl":"http://XXXXXX:XXXXXX@192.168.1.144/rest/nodes/30%208%203E%201/cmd/DOF","onUrl":"http://XXXXXX:XXXXXX@192.168.1.144/rest/nodes/30%208%203E%201/cmd/DON","httpVerb":"GET"},{"id":"1831946181","name":"Entryway","deviceType":"custom","targetDevice":"Encapsulated","offUrl":"http://XXXXXX:XXXXXX@192.168.1.144/rest/nodes/30%206%20D7%201/cmd/DOF","onUrl":"http://XXXXXX:XXXXXX@192.168.1.144/rest/nodes/30%206%20D7%201/cmd/DON","httpVerb":"GET"},{"id":"2029334298","name":"Second Floor Hallway","deviceType":"custom","targetDevice":"Encapsulated","offUrl":"http://XXXXXX:XXXXXX@192.168.1.144/rest/nodes/33%2059%205D%201/cmd/DOF","onUrl":"http://XXXXXX:XXXXXX@192.168.1.144/rest/nodes/33%2059%205D%201/cmd/DON","httpVerb":"GET"},{"id":"1827605687","name":"Storage Room","deviceType":"custom","targetDevice":"Encapsulated","offUrl":"http://XXXXXX:XXXXXX@192.168.1.144/rest/nodes/2F%20E7%207D%201/cmd/DOF","onUrl":"http://XXXXXX:XXXXXX@192.168.1.144/rest/nodes/2F%20E7%207D%201/cmd/DON","httpVerb":"GET"},{"id":"322778532","name":"Boys Room","deviceType":"custom","targetDevice":"Encapsulated","offUrl":"http://XXXXXX:XXXXXX@192.168.1.144/rest/nodes/2F%20E3%206C%201/cmd/DOF","onUrl":"http://XXXXXX:XXXXXX@192.168.1.144/rest/nodes/2F%20E3%206C%201/cmd/DON","httpVerb":"GET"}]

**Comment by bwssytems** [comment]
That should be fine. And I will assume that 192.168.1.137 is your Echo?

**Comment by flintory5** [comment]
Yes

**Comment by flintory5** [comment]
Update - I discovered the issue and it was in my environment. On my router (Linksys EA6100), UPNP was enabled - I'm not entirely sure I understand why, but as soon as I turned it off, the echo discovered all devices and they worked as expected. Thank you for the great work on the app and thanks for the help.

**Comment by lamiastella** [comment]
@flintory5 thank you so much. After I disabled the upnp in the linksys and ran the amazon echo HA bridge again, I was able to discover devices! 
<img width="522" alt="screen shot 2016-03-25 at 8 42 32 pm" src="https://cloud.githubusercontent.com/assets/1892917/14057335/87374908-f2ca-11e5-932b-1532d6beebe8.png">
