### ISSUE TITLE
Lights: only on/off/dimming?

### ISSUE THREAD

**Issue by kevinvanryck** [bwssytems/ha-bridge#650]
Is it somehow possible also to add colour changes to the API? That would be so useful! Also, milights can also change the white balance, is this possible? I guess it might not since I'm not sure whether this is possible with the hue lights.

I now have my MiLight bulbs connected to the bridge, and made a small API from the node-milight-promise that allows to set colours/disco microphone lights/light alarms and so on (I'm thinking of publishing it opensource once it is more refined and easy to setup).

The ha-bridge then makes http requests to my API which controls the lights, and it works very well!

**Comment by bwssytems** [comment]
This is already referenced in #327
