### ISSUE TITLE
Creating and inserting a basic script into ha-bridge to overcome echo's 5 second timeout?? Help!

### ISSUE THREAD

**Issue by Matttribal** [bwssytems/ha-bridge#653]
Hi.

Im really hoping somebody can help. 
When adding multiple item lines to a Bridge device I sometimes need to add multiple delays in order for equipment to finish turning on before the next line starts. Doing this works great, but Amazon Echo freaks out when it doesn't receive a "close connection" with in 5 seconds and then verbally tells you the command failed (even though it still executes it, sometimes twice).

I found the issue here: https://github.com/bwssytems/ha-bridge/issues/341
At the bottom of that issue it explains how somebody got around this.
It looks like a script was made that sent the "close connection" command to the Echo so that the rest of the items in the list can then continue to run with all their delays. This script needs to run early in the list of items that run.

**My questions are...**
(I'm working on a windows machine)
Can I create a .txt file and insert the following commands into it (and then rename the file with the correct extension)?? then insert the file into /data folder??

ignore_user_abort(true);
header("Location: ".$redirectUrl, true);
header("Connection: close", true);
header("Content-Length: 0", true);
ob_end_flush();
flush();
fastcgi_finish_request(); // important when using php-fpm!

What would the correct file extension be?? .sh ? .jar?

From the ha-bridge edit/copy device page, how would I then run this script file? Is it a command in the "Target Item" that i need to add?

Thanks

**Comment by bwssytems** [comment]
Please post this on #341 as the people who got that working in the script listen to that thread. Close this when you have done so. Thanks
