### ISSUE TITLE
Curl -k equivalent

### ISSUE THREAD

**Issue by BigfootDel** [bwssytems/ha-bridge#655]
Is there any way to do a curl -k equivalent with the bridge devices to provide an insecure SSL connection?  I am trying to run commands on a Vizio TV which work using the command line and curl -k from this API: https://github.com/exiva/Vizio_SmartCast_API

If I don't use the -k I get: "Error on calling url to change device state: https://192.168..."

**Comment by bwssytems** [comment]
So looking into this a bit more. Could you post the error from the program output log that occurs from the https call?

**Comment by bwssytems** [comment]
Also, an alternative is to use the command type for ha-bridge and call curl itself.

**Comment by bwssytems** [comment]
included in the community information https://github.com/bwssytems/ha-bridge/wiki/Informational-Items-Collected-from-the-Community#q-curl--k-equivalent
