### ISSUE TITLE
Raspberry PI Runtime Error

### ISSUE THREAD

**Issue by javaftper** [bwssytems/ha-bridge#656]
Raspbian OS-
Linux raspberrypi 4.4.48-v7+ #964 SMP Mon Feb 13 16:57:51 GMT 2017 armv7l GNU/Linux

Installed ha-bridge as advised and running successfully.

I'm trying to exec a python script to power on and off my orvibo s20.

My ON entry for execute command is-
"exec:///home/pi/habridge/s20control.py poweroff 192.168.1.2 ac:cf:23:99:a6:b4"

When I test this on ha-bridge I receive-
`2017-06-05 17:40:07,624 [qtp23387733-22] WARN  com.bwssystems.HABridge.plugins.exec.CommandHome - Could not execute request: /home/pi/habridge/s20control.py poweroff 192.168.1.2 ac:cf:23:99:a6:b4" with message: Cannot run program "/home/pi/habridge/s20control.py": error=2, No such file or directory`

Is there a problem with my file location reference or do I need to adjust config?

**Comment by masterchop** [comment]
did you try python /path/script.py? its working for me.

**Comment by javaftper** [comment]
I've updated my habridge on as follows-
[{"item":"python /home/pi/Downloads/OrviboS20-master/S20control/S20control.py poweron 192.168.1.4 ac:cf:23:99:a6:b4","type":"cmdDevice"}]

Running python /home/pi/Downloads/OrviboS20-master/S20control/S20control.py poweron 192.168.1.4 ac:cf:23:99:a6:b4 in shell works.

But via ha-bridge log returns-
`2017-06-05 19:22:17,543 [qtp23387733-20] WARN  com.bwssystems.HABridge.plugins.exec.CommandHome - Could not execute request: [{"item":"python /home/pi/Downloads/OrviboS20-master/S20control/S20control.py poweron 192.168.1.4 ac:cf:23:99:a6:b4","type":"cmdDevice"}] with message: Cannot run program "[{"item":"python": error=2, No such file or directory`

**Comment by masterchop** [comment]
are you running the ha-bridge as root?

**Comment by javaftper** [comment]
Yes.

**Comment by bwssytems** [comment]
Since you are running within the environment of the java program, you need to specify the full path to the python executable itself.

**Comment by javaftper** [comment]
I've copied the pyton package to habridge.  Still causing exception.

When you say "full path" isn't that what I've got (/home/pi...) or do you mean something webserver related? I'm running apache on port 81.

[{"item":"python /home/pi/habridge/OrviboS20-master/S20control/S20control.py poweron 192.168.1.4 ac:cf:23:99:a6:b4","type":"cmdDevice"}]

`ec.CommandHome - Could not execute request: [{"item":"python /home/pi/habridge/OrviboS20-master/S20control/S20control.py poweron 192.168.1.4 ac:cf:23:99:a6:b4","type":"cmdDevice"}] with message: Cannot run program "[{"item":"python": error=2, No such file or directory`

**Comment by bwssytems** [comment]
It is the path to python itself. Do 'which python' on the command line to find it. Then use that path in your call. Also, you could make a script and or for call in that.

**Comment by bwssytems** [comment]
any update on this?

**Comment by javaftper** [comment]
I understood what you meant about python location and updated script ref as follows-
`[{"item":"/usr/bin/python2.7 /home/pi/Downloads/OrviboS20-master/S20control/S20control.py poweron 192.168.1.4 ac:cf:23:99:a6:b4","type":"cmdDevice"}]`

But I still get-

`2017-06-12 15:42:06,439 [qtp7406352-13] WARN  com.bwssystems.HABridge.plugins.exec.CommandHome - Could not execute request: [{"item":"/usr/bin/python2.7 /home/pi/Downloads/OrviboS20-master/S20control/S20control.py poweron 192.168.1.4 ac:cf:23:99:a6:b4","type":"cmdDevice"}] with message: Cannot run program "[{"item":"/usr/bin/python2.7": error=2, No such file or directory
`

**Comment by bwssytems** [comment]
Maybe it would be best to encapsulate your python call in a shell script that is constructed with the bash environment. Then you just call the script. There is something that is not being pulled into the environment when you run it through the ha-bridge.

**Comment by bwssytems** [comment]
@javaftper Did you find a solution to your issue?

**Comment by javaftper** [comment]
No.  I tried using a shell script-no joy.
But I'm sure it's something specific to my python setup/env but I don't want to mess with it because I've got other services running.
I will at some point setup a new PI and try again.
I bought a couple of the new orvibo (B25)- they are plug and play with Alexa (no bridge required).
And I've setup https://github.com/fernadosilva/orvfms on my PI for my S20's which is a PHP implementation enabling automation, schedules etc but you have to control using a standard web browser connected to the network- no Alexa integration.
I'll close this as an environment related issue.
