### ISSUE TITLE
Problems with Alexa finding HA Bridge devices

### ISSUE THREAD

**Issue by jonohunt** [bwssytems/ha-bridge#657]
I'm having problems with Alexa connecting to HA Bridge.

I've read Help & the FAQ, and tried lots of things with 2 different Raspberry Pis to try and get it working consistently, and it's very hit and miss for me. Most of the time when I run Discovery in Alexa it doesn't find any devices/activities from HA Bridge, but it does find them on the odd occasion.

I ended up wiping the disk of one of the Pis, installing Jesse Lite from fresh, and then installing and setting up HA Bridge again from fresh (without installing any other apps).

I've tried removing the Hue skill from Alexa's settings and running discovery with and without pressing the button on my (physical) Hue Bridge 2.0.

Re-enabling the Hue skill from Alexa's settings and running discovery with and without pressing the button on my (physical) Hue Bridge 2.0, but can't get it to find the devices reliably every time.

I set the 'UPNP IP Address' to the IP address of my Pi, and left 'Web Server Port' as the default port (80).

In the logs I see lots of (the same) error messages saying 'spark.webserver.MatcherFilter'.

Also seeing these warnings:
'registerWithHue needs link button pressed on HUE bridge: Hue Bridge 2.0'
'Error on calling hue device to get state: Upstairs Lights Could not register with hue: Hue Bridge 2.0'
(As I've said, I've tried running Discovery in Alexa's settings after pressing the button on the Hue, as well trying Discovery without pressing the button.)

Any clues as to what the error message means?
Or is there anything else anyone can suggest in trying to get it running properly?

**Comment by bwssytems** [comment]
So, do you have a real Philips hue bridge on your network as well?

**Comment by jonohunt** [comment]
Yes, should I not?

I've tried turning the Hue Bridge off when discovering devices, as well as leaving it on. It doesn't seem to make any difference either way.

**Comment by bwssytems** [comment]
You will have better luck with the echo when you unplug it.

**Comment by jonohunt** [comment]
Thanks, I've done some more tests.

Each time I unplug the Hue Bridge then run discovery in Alexa it doesn't find anything.

If I plug the Hue Bridge back in then run discovery Alexa sees all the devices in HA Bridge. But after a while it says they're all offline, so Alexa's stops seeing them after a certain length of time.

**Comment by rafale77** [comment]
This is strange. I am running a very similar setup with a real 2nd gen hue and a bridge I have been running for months. I have never had to disconnect the real hue bridge and Alexa detects everything consistently and has been doing so for several months. I suspect something to do with your router UPNP setup or port settings on your pie.

**Comment by bwssytems** [comment]
any update on this?
