### ISSUE TITLE
Ability to make Harmony Activity Appear as a Switch

### ISSUE THREAD

**Issue by iSmigit** [bwssytems/ha-bridge#658]
Hi. I'm using HA-Bridge successfully with a number of Logitech Harmony accessories. The HA-Bridge is being accessed via HomeBridge (using Homebridge-Hue plugin) so that I can do voice commands on my iPhone to turn my home theatre on and off. So far this works a treat.

One option I would however love is for the Harmony Activities to appear as Switches instead of lights to external processes. The reason for this is due to me using voice commands, it'd be nice to be able to issue a command to all lights in a room without impacting Home Theatre equipment. Something like "turn off the lights in the living room" is a pretty common command for us to use but as far as HomeKit is concerned all the HT equipment is also a light.

There's ways around this such as defining a scene that only commands the lights or by configuring home theatre equipment in HomeKit to be in a seperate room, but I'd prefer to have the devices grouped just as different device types.

Does the ability exist already to do something like this, and if so where should I be looking. If not can I flag it as a potential feature request. It may also apply to other device types other than Harmony, I'm unsure.

**Comment by bwssytems** [comment]
Is there a switch type for hue? I have not found that yet.

**Comment by iSmigit** [comment]
My bad, new to it and haven't really looked at the API itself. Just checked and switches would fall under 'Sensor' type as opposed to being a type of their own. They are covered at https://www.developers.meethue.com/documentation/supported-sensors

The ones I thought *may* make sense would be ZGP Switch (Hue Tap) or ZLL Switch (Dimmer). Both have an on/off state that look like they could be set via an update to the sensor config -  https://www.developers.meethue.com/documentation/sensors-api#58_change_sensor_config

Of the sensors the CLIP OpenClose might be a good binary switch too or the 'CLIP Generic Status Sensor' given both seem to only maintain an on/off state.

Unsure how worthwhile that all would be though, was a thought but to distinguish some devices from lights.

**Comment by bwssytems** [comment]
It's just a means to an end currently. So, I am not going to change this at this time.

Thanks for the input
