### ISSUE TITLE
Configuration is gone after re-start

### ISSUE THREAD

**Issue by mcwieger** [bwssytems/ha-bridge#659]
I'm running ha-bridge on Synology using the following script on startup:

`/volume1/@appstore/Java8/j2sdk-image/bin/java -jar -Dserver.port=8085 /volume1/@appstore/HA_bridge/ha-bridge-4.1.1.jar`

This works well, but every time I reboot my server (e.g. on updates), the whole configuration is gone. I have backed up the configuration in ha-bridge, but that can't be found. The log file shows the following after startup:

`Error reading the file: data/device.db - Does not exist or is not readable. continuing...`

And after logging in to ha-bridge it shows:

`Issue getting directory listing for backups in directory: data`

To resolve any of the issues I set permissions to everything under ha-bridge to 777. No results.

What's going on?

**Comment by bwssytems** [comment]
I know there is a synology install thread somewhere in the closed items. Does Synology use virtual storage for a process and then removes it when the process ends? Google synology ha-bridge....

**Comment by mcwieger** [comment]
Most topics out there are on running ha-bridge in Docker, which is not available on my model (DS414). However, I did add another parameter to the startupscript (-Dconfig.file), which solves the issue that the configuration of Domoticz and Harmony were gone too. They are now available on startup.

So question: is there a parameter for device.db as well? That should solve it.

**Comment by bwssytems** [comment]
Read this as it fixes that issue:
https://github.com/bwssytems/ha-bridge#-dconfigfilefilepath

**Comment by mcwieger** [comment]
Issue resolved. Apparently the configuration on Synology requires an absolute path to the configuration file and the device database file.

Default configuration is:

`data/habridge.config` and `data/device.db`

Issue resolved with:

`volume1/@appstore/ha_bridge/data/habridge.config` and `volume1/@appstore/ha_bridge/data/device.db`
