### ISSUE TITLE
Lamp states not handled

### ISSUE THREAD

**Issue by quenthal** [bwssytems/ha-bridge#66]
I have succesfully configured few of my lights (some of them are simple on/off, few dimmable).

I'm using HA Bridge with Logitech Harmony, and I can succesfully control them. However, after 10-20 seconds or so lamps lose their state in Harmony remote or app...Useability gets quite low with this.

For example I turn them on, state is correctlyON in Harmony. After a while (whatever is the update cycle between bridge and harmony) Harmony indicates mistakenly that it is turned off. If I now really want to turn the lamp off, I need to "turn it on" in Harmony, and then off.

It seems that correct dimming value is saved anyway and correctly displayed in Harmony as well even after on / off - in both real and "fake" status changes.

**Comment by bwssytems** [comment]
I thought this issue came up before but I can't find it in the history. What type of lights do you use? Also, the habridge does not keep state. I have a hunch that the hub is querying the bridge and seeing what the state of the light is and it defaults to off as I do not track state. Could you turn on DEBUG for com.bwssystems.HABridge.hue.HueMulator and then post the log. Thanks

**Comment by audiofreak9** [comment]
I have all my ha-bridge devices discovered by my Harmony Hub as well, I'll check to see if my hub 'looses' their On state as well.  I can't recall I so infrequently use the hub to control the bridge, way easier to use the Echo.

**Comment by quenthal** [comment]
Will do, however Harmony makea the queries quite often, that is visible even without debug.

Missing state tracking easily explains this. Some of the lights do not have that capability at all, and some of them are real Hue lights - I have mapped even them to ha-bridge, since Harmony can handle only one Hue Bridge.

Tracking states, wven though it always possible they get out of sync, would be a nice feature :)

Br,

Eero

**Comment by emiliosic** [comment]
I would like to see this also. I'm currently using both a Vera Plus and a Harmony. Perhaps another REST URL for querying Vera?

**Comment by bwssytems** [comment]
Another question....

What kind of lights are controlling through the Harmony Hub? As audiofreak9 points out, it's easier for the ha-bridge to control them directly... and it is ok to also control them with the harmony hub, but not as a loop through the ha-bridge...

**Comment by emiliosic** [comment]
All the lights are controlled by Vera. Harmony can control lights via ha-bridge, just like Echo. What I,m thinking is that when ha-bridge gets a status query, it in turn queries Vera

**Comment by quenthal** [comment]
Could one also get simple workaround by adding one boolean (status, on/off), that would get changed whenever ha bridge gets for that object either discrete on or off? And value of this boolean would be returned, whenever something queries about devices/lamps from ha bridge? Harmony makes these queries quite often.

If all devices I have behind ha-bridge had their own status handling, I'd naturally would like to have the same thing as emiliosic asks, but it wouldn't help with every device.

**Comment by audiofreak9** [comment]
I tested my Harmony Hub to turn on an ha-bridge controlled light, about 10 seconds later the state returned to off on the Harmony Hub, so it's polling for state.  Like I said, easier to tell Alexa to turn them on/off.

We also should realize what it would require to have the ha-bridge communicate a device state to the Harmony Hub.  The "last commanded" state would need to be captured by the ha-bridge in some manner as @quenthal suggests, but that "last commanded" state would also need to be broadcast by the ha-bridge in the HUE API method.

**Comment by audiofreak9** [comment]
Forgot to add, we should all request Harmony support multiple Hue Bridges.

**Comment by bwssytems** [comment]
So, I can put the state changes that the ha-bridge knows about and return that on the api. I won't track what the Vera or other systems have been set too. So when the ha-bridge comes up, it will default to 'off'.

**Comment by audiofreak9** [comment]
Will this also include the level variable for the On state?

**Comment by bwssytems** [comment]
Yes, but only when the ha-bridge is told to set it.

**Comment by cornholio1234** [comment]
what would be additionally awesome - if you could put an api command to set the device state - therefore if I turn on my lights using some 3rd party tool I can notifiy the ha-bridge about the new state (without switching it)

**Comment by bwssytems** [comment]
@cornholio1234 I'll look into that.

**Comment by bwssytems** [comment]
Ok, have a version that has the fixes included. http://www.bwssystems.com/files/ha-bridge-1.4.1d.jar

Also, to change the state and level, just call the hue api to change the state, no need to add another call.

**Comment by audiofreak9** [comment]
Brilliant!

**Comment by cornholio1234** [comment]
Works great - many many thanks! - Could you give me a hint how to use the HUE API to change the state without raising a device trigger?
My setup is following

logitech hub ----> HA bridge ------> domoticz ----> (zwave)

therefore if I change a switch state using logitech remote, the hub will trigger HA which triggers domoticz switching my light via zwave. In this direction everyone is informed and up to date. But if I trigger a device directly from domoticz the zwave device will change the state but HA bridge is not aware of the change.

domoticz -----> (zwave)
domoticz -----> ha bridge -----> domoticz ----> ....

If I call the HA bridge API from domoticz it will start looping between HA bridge and domoticz (or is there something like a internal tie-breaker in the ha bridge killing responses for a repeated call?

**Comment by audiofreak9** [comment]
@cornholio1234 README has what you are asking for [here](https://github.com/bwssytems/ha-bridge/blob/master/README.md#set-light-state).  Short answer a PUT to http://host:port/api/<username>/lights/<id>/state

**Comment by cornholio1234** [comment]
@audiofreak9 - thanks for the info, but it is not what I am looking for. I'd like to update the data value for the lamp state without actually switching the light (in ha bridge), because it already has been switched using the central management tool (or a motion detector, or a wall switch, ... ;-)) just want to notify HA about such changes.

**Comment by audiofreak9** [comment]
@cornholio1234 gotcha, that would be a nice option to have, simply change the stored state without actually operating.

**Comment by audiofreak9** [comment]
@bwssytems, Thinking about this, could you code a third body argument like 'op' into the PUT that when set to false doesn't actually operate the device, but only changes the state?

**Comment by bwssytems** [comment]
I will just add another call. It will be easier and cleaner. Also, if any additions to the real call override the 'op' from the Hue API, that wouldn't work well.
