### ISSUE TITLE
Fire TV stick compatible?

### ISSUE THREAD

**Issue by ertlflorian1** [bwssytems/ha-bridge#660]
Hello,

I am trying to install the ha bridge on my Raspberry Pi B+.
I created the virtual devices in the Webinterface but Alexa doesn't find any devices.

Is it compatible with an new Fire Tv stick? I think so or not?
Another embarrassing question, I don't need an real HUE Bridge to emulated the habride or I am there wrong?

I also tryed to install it on my other RPI 3 but the same problem there.
The HaBridge is running on Port 8080 because on 80 Apache is running.

I tryed to change the Port to 80 then in the Hue App i found the bridge and i could control the virtual devices. But Alexa doesn't found anything. So i changed back the port to 8080

Sorry for the bad englisch.
Thanks, Flo

**Comment by bwssytems** [comment]
The Fire TV line (stick or box) does not support internally any connection to home automation items. It requires that you have an Echo or Echo DOT physically.

You do not need a real HUE bridge for using the ha-bridge.... BUT if you have HUE bulbs you will need the HUE Bridge.

The HUE App only talks to bridges on port 80. If you want to use the HUE app you will need to shutdown your apache server and run the ha-bridge on port 80. There are some instructions for advanced proxy in the readme that will let you do this, but it requires under standing the network proxy setup.

**Comment by ertlflorian1** [comment]
Okay thanks a lot for your very quick answer.

That means I must buy an Echo Dot, then I can use ha bridge for virtual devices?
But when I have the echo then I can controll with the Fire TV Stick Remote too or?
The habridge must not run on Port 80 that Alexa would find it?

**Comment by bwssytems** [comment]
You can run on any port for the Alexa, it would be if you wanted to use the Philips HUE Phone App that requires it to be on port 80.

When you have an Echo the Fire TV stick will then work.

**Comment by ertlflorian1** [comment]
Thanks man.

I bought now the Echo ;)
