### ISSUE TITLE
Yeelight problem

### ISSUE THREAD

**Issue by danmed** [bwssytems/ha-bridge#667]
I'm having a problem with some yeelight bulbs which you've already discussed but i'm still having the issue..

set the device type to "tcp",
the target : tcp://192.168.2.211:55443/{"id": 1, "method":"set_power", "params":["on"]}\r\n
the content type to "application/json"

When trying to use the on / off commands nothing happens.. the interface doesn't return an error at all..

the debug log shows 

06-09-2017 22:50:56.605	DEBUG	Decode Json for url items: [{"item":"tcp://192.168.2.211:55443/{\"id\": 1, \"method\":\"set_power\", \"params\":[\"off\"]}\\r\\n","type":"tcpDevice","contentType":"application/json"}]	com.bwssystems.HABridge.hue.HueMulator

06-09-2017 22:50:56.605	DEBUG	executing HUE api request to TCP: tcp://192.168.2.211:55443/{"id": 1, "method":"set_power", "params":["off"]}\r\n	com.bwssystems.HABridge.plugins.tcp.TCPHome

06-09-2017 22:50:56.605	ERROR		spark.webserver.MatcherFilter

any help? am i just setting something wrong?

I've ha d alook in the db and this is the entry : 

[{"id":"11","uniqueid":"00:17:88:5E:D3:0B-0B","name":"Dan Lamp","deviceType":"TCP","offUrl":"[{\"item\":\"tcp://192.168.2.211:55443/{\\\"id\\\": 1, \\\"method\\\":\\\"set_power\\\", \\\"params\\\":[\\\"off\\\"]}\\\\r\\\\n\",\"type\":\"tcpDevice\",\"contentType\":\"application/json\"}]","onUrl":"[{\"item\":\"tcp://192.168.2.211:55443/{\\\"id\\\": 1, \\\"method\\\":\\\"set_power\\\", \\\"params\\\":[\\\"on\\\"]}\\\\r\\\\n\",\"type\":\"tcpDevice\",\"contentType\":\"application/json\"}]","inactive":false,"noState":false,"offState":false}

Note : Developer mode is on and i can manually turn the bulb on and off via telnet..

**Comment by bwssytems** [comment]
will take a look

**Comment by bwssytems** [comment]
You need to escape the quotes inside the item like so:
tcp://192.168.2.211:55443/{\"id\": 1, \"method\":\"set_power\", \"params\":[\"on\"]}\r\n

**Comment by danmed** [comment]
i think your email stripped out the escapes.. but i have done that and it
didn't work either.

**Comment by bwssytems** [comment]
The escapes show up on the web view of this issue. I tried it and it works for me without issue if the escapes are there. Make sure you get all of them.

**Comment by danmed** [comment]
Thank you.. i don't know what i did wrong last time but it's working now..

can you confirm if the below is correct for brightness?

tcp://192.168.2.211:55443/{\"id\": 1, \"method\":\"brightness\", \"params\":[\"${intensity.percent}\"]}\r\n

**Comment by bwssytems** [comment]
This is correct for using ${intensity.percent}
