### ISSUE TITLE
No devices found on bridge

### ISSUE THREAD

**Issue by mtitus83** [bwssytems/ha-bridge#67]
Having a similar issue to #65 that I can't seem to figure out.  I have added devices to my bridge and have confirmed they work manually and from the test functions but when I tell Alexa to discover my devices it returns that she found no devices.  Looking at the logs nothing sticks out to me but I get the impression it does in fact get to the device but cannot return the deice list.

Just to understand the pieces in this scenario I have OpenHAB+ha-bridge running on a raspberry pi 1 model b which is connected via ethernet with a ddwrt router serving the home network.  I have tried a mix of wired/wireless settings to no avail and for what its worth I have a firetv2 that I initially tested with prior to owning an echo and had identical results to this then as well.  Any assistance would be greatly appreciated.  I have attached a [debug log](http://pastebin.com/pnAKvb3B), [habridge.conf](http://pastebin.com/5rZ1GNFh) and [device.db](http://pastebin.com/H2D34Tpp) in case they can offer any window into what I may be doing wrong.

Any further insight would be very appreciated

**Comment by bwssytems** [comment]
If your echo is on ip 10.220.29.211 it sure looks like it found the bridge and asked for the devices. I'll need to dig a bit more with the issue on #65 to see what can be done to figure this out.

**Comment by mtitus83** [comment]
Thats correct, .211 is my Echo.  I'll keep my eyes peeled on #65. If there is anything I can do to help test or attempt I'd be glad to - in the interim I am going to update my routers firmware to make sure that I am not having any issues on that side of the house.  No need to chase something that is not related to the project.

**Comment by mtitus83** [comment]
It looks like tonight my device is allowing itself to be added .. how nice of it.  I have yet to change anything on my network however I did just power cycle the router prior to me asking it to discover the devices.  I'll continue to test to see if this behavior continues and if so close this as soon as I confirm.

**Comment by bwssytems** [comment]
It seems there have been many instances where the router has gotten in the way of upnp handling. #65 is now closed due to a router setting.

**Comment by bwssytems** [comment]
Is this working?

**Comment by bwssytems** [comment]
Any new comments?

**Comment by bwssytems** [comment]
Closing as it is working for user.
