### ISSUE TITLE
Execute select Device when bridge loads [Enhancement Request]

### ISSUE THREAD

**Issue by audiofreak9** [bwssytems/ha-bridge#670]
I have dozens of X10 modules that I control with the ha-bridge / Alexa.  I use an X10 CM11A controller that I communicate to/from the RPi using HEYU.  HEYU has a state engine that keeps the X10 device states.  I wrote a python script that updates the X10 device states on the ha-bridge, using HEYU's state engine, which I run on cron every 30 minutes.  However, when the ha-bridge is restarted, it's device states are cleared.  I either have to execute a configured device on the ha-bridge that executes my python script or wait until the cron runs to update my X10 device states on the ha-bridge.  It would be nice to have the option to execute the ON, OFF or DIM Items of a select configured device on the ha-bridge when it loads.

**Comment by tuicemen** [comment]
I too use X10 and wrote a Windows based app to utilize the bridge.
It will work with the cm11,cm19, and cm15 as well as some third party controllers
The program will keep HA-Bridge alive (restart it if it stops) and reports what the bridge sees as On/Off/Dimmed (not just x10 devices)
I can see a need for this option

**Comment by bwssytems** [comment]
So, the question is do you want just the states updates or the states updated and the commands called?

**Comment by tuicemen** [comment]
For me just to have the bridge turn on or off a selected device on starting would be fine.
My app could update the rest on seeing that or do something else.

**Comment by audiofreak9** [comment]
Just execute a device on start up for me, my script takes care of the rest as well.

**Comment by bwssytems** [comment]
@audiofreak9 I am finally implementing your request! Ha!

**Comment by audiofreak9** [comment]
Patience is a virtue.

**Comment by audiofreak9** [comment]
I can't for the life of me find the Execute select Device on startup?  I looked at the Bridge Control, and the devices themselves.  Where do I find it?

**Comment by bwssytems** [comment]
haha, the column on the bridge devices tab called startup, then click on that cell for the device you want to startup

**Comment by audiofreak9** [comment]
Works like a charm!  This is awesome, thanks.

**Comment by tuicemen** [comment]
Just tested this as well with no issues.
Awesome! @bwssytems  A big thanks for this from me too!
