### ISSUE TITLE
I have to keep running nssm every so often

### ISSUE THREAD

**Issue by michaelhinchey** [bwssytems/ha-bridge#672]
3.5 habridge, Vera, Alexa , running nssm, windows 10
I don't know why this is happening but I keep my computer on 24-7, the bridge seems to go offline and I have to rerun the script again to get it back up and running.   
Can I tell if nssm is set to automatically run somehow?  Where can I check this?  Thx

**Comment by bwssytems** [comment]
I would gogole this as I am not familiar with nssm, If someone else has knows something that would be great.

**Comment by tuicemen** [comment]
Update HA-Bridge  and maybe you won't need  the Non-Sucking Service Manager of Windows 10 to be running.
no developer should be expected to debug outdated software.
If the issue remains with the latest version of HA-Bridge then I would expect bwssystems will look into it.
I run 4.5 and windows 10 and have no issues with HA-Bridge stopping.
It may however be that my app (x10alex) restarts the bridge if it ever stops.

**Comment by tuicemen** [comment]
Also since NSSM is a service manager you need to load the bridge as a service in Windows otherwise it won't restart it.

**Comment by michaelhinchey** [comment]
I'm sorry. I replied to your answer a week ago or a but it didn't take.  Sorry.  I was wondering what are the steps to get the bridge to work without the need for nssm?  I would love to update the bridge and not need excess stuff running on my pc. Thx

**Comment by tuicemen** [comment]
Try loading the bridge as a service to see if Windows will keep it active without needing NSSM.

**Comment by tuicemen** [comment]
Out of curiosity what antivirus are you running?
You may need to set a rule for the bridge in your antivirus program.

**Comment by michaelhinchey** [comment]
I'm running avast antivirus.  I had it turned off and still didn't run.  How do I make it a service?

**Comment by tuicemen** [comment]
Turning off the antivirus won't auto restart the bridge if it is stopped.
However if that is what is stopping the bridge turning it off then starting the bridge should allow the bridge to keep running.
To set the bridge to run as a service use google to get a step by step how to.

**Comment by michaelhinchey** [comment]
I honestly would like to update the bridge and do without the nssm.  I just always thought you needed it no matter what.  I do have it running on windows 10.

**Comment by tuicemen** [comment]
I've never used NSSM and run HA-Bridge on Windows 10 since version 3.5.0
I don't know why you would think NSSM was or is required.
Your missing out on many new options and fixes by staying with 3.5

**Comment by michaelhinchey** [comment]
OK. What I am asking is a little help with this.  
    If I upgrade to habridge 4.5 or above could you explain how it runs?   I'm unsure how exactly windows would know how to run it.  Hope that helps.  
Maybe a short walk through would help. Thank you in advance.

**Comment by tuicemen** [comment]
4.5 runs basically the same as 3.5 just click on the jar file to run it.
However the web UI  has changed a bit (in the add/edit device page mostly) there are other options now available.
As a suggestion why not down load the newest version to a temp folder stop your current version then start the new version.
Once started open your browser to the web UI address and look around.

**Comment by michaelhinchey** [comment]
I did do that with 4.5 when it firat came out but I ran it with nssm so I thought.  So will I be able to run that as a service or do I always have to run the jar file at reboot. 
    I didn't have a lot of time to see what the fuss was about bit I did notice it was completely overhauled.  I got scared when I couldn't add a device as easy and then went back to 3.5. Lol. 
   I have more time as of now so I can poke around some more.

**Comment by tuicemen** [comment]
You can set any jar to run as a service I suspect.
I just placed a shortcut to the jar file in my startup folder so each time windows starts it loads the HA-Bridge.
I don't run it as a service however the front end (Alex10) I created to allow X10 control watches the HA-Bridge and if it stops auto restarts it.

**Comment by michaelhinchey** [comment]
Thx I will give it a whirl again.

**Comment by michaelhinchey** [comment]
Thank you all that helped me get away from having to run a program unnecessarily.  I have migrated from 3.5 to 4.5.6 with no apparent issues.  I have to catch up now on all the new stuff it can do.  I'll have to read up on the login stuff as well as security is an awesome feature to have.
