### ISSUE TITLE
ha-bridge not working after restart

### ISSUE THREAD

**Issue by akurz42** [bwssytems/ha-bridge#673]
Hi,

I don't know which version this started with, but I noticed an issue a few days ago.

I'm using ha-bridge together with Alexa and up to now this worked flawlessly. It still does work, but there's some new and strange behavior: after ha-bridge is started, none of my devices can be addressed from Alexa anymore. It always comes back saying "<device name> isn't available right now" (this is translated from german, so the english message may be slightly different). To make it work I need to press the "Link" button and do a "Find Devices" on Alexa. After that everything will work fine until the next restart.

Cheers,
Alex

**Comment by akurz42** [comment]
Did some more testing... This started with 4.5.1. Version 4.5.0 works just fine.

Alex

**Comment by bwssytems** [comment]
Yep, there is an issue with the ha-bridge app saving the linked username it creates for devices. This is fixed in the next release.

**Comment by akurz42** [comment]
Cool. Thanks!

Alex

**Comment by akurz42** [comment]
Sorry, accidentally closed the issue :)
