### ISSUE TITLE
ha bridge + isy + harmony elite rocker switch?

### ISSUE THREAD

**Issue by rebirth24** [bwssytems/ha-bridge#674]
Is anyone successfully using the ha bridge + isy + harmony elite rocker switch buttons tied to their device? I currently have (for example) living room tied to one of the "light" buttons.  You are then supposed to be able to Increase/Decrease brightness of that light button using the rocker switch.  Does anyone know how the devices needs to be set up in ha bridge in order to accomplish this? On/Off works just fine.
![cap](https://user-images.githubusercontent.com/16981943/27385319-0bd1a588-5647-11e7-924e-4dc7040eba4b.JPG)

**Comment by NovaGL** [comment]
To rocker uses the dim command. If dim is not setup it won't work.

I am using dim with my lights via C-Bus

**Comment by bwssytems** [comment]
Is this issue answered? Dim is the only item that is called by harmony hub.
