### ISSUE TITLE
FHEM home automation integration

### ISSUE THREAD

**Issue by sashsc** [bwssytems/ha-bridge#675]
Hello everyone.

You have already integrated into the bridge domoticz.
Is it possible to make an integration for FHEM (like DOMOTICZ)?

Or will it be possible to retrieve a status from a device or a reading?

Thanx
Sascha

**Comment by bwssytems** [comment]
That would be an enhancement we can put on the list for FHEM integration.

You can already get device state by https://github.com/bwssytems/ha-bridge#get-light-attributes-and-state

**Comment by bwssytems** [comment]
Also, how many would like FHEM integration? Would like to know how many use this as other systems I have not yet done are more popular.

**Comment by sashsc** [comment]
Thanx for answering. 

I think, most of the users are in germany. And how much of them using the ha bridge, i don't know.
But i think that there are enough users. The makers of ESPEASY have integrated a connection for FHEM Tool.

**Comment by bwssytems** [comment]
Updated the title for the enhancement. This currently will be after a few other items.

**Comment by essera** [comment]
Hi,

HABridge ist e very cool Tool in Connection with Fhem and alexa. If there will be a Integration with Fhem that will be great. i know many peole using habridge instead of connect Fhem to Amazon directly.

**Comment by heikoh81** [comment]
I'm using HABridge to control FHEM, too.

**Comment by RaiderXXL** [comment]
That would be great

**Comment by docb7** [comment]
Yes, definetly. Fhem has a huge and extremely active community and I am sure we all would love to have it implemented!

**Comment by nihebe** [comment]
+1 for native FHEM support, but not a big 1...

At the moment I'm controlling it via HTTP requests of the form:
`http://usr:pwd@FHEM-IP:FHEMWEB-Port/fhem?cmd=set%20Device%20on`
`http://usr:pwd@FHEM-IP:FHEMWEB-Port/fhem?cmd=set%20Device%20dim%20${intensity.percent}`
`http://usr:pwd@FHEM-IP:FHEMWEB-Port/fhem?cmd=set%20Device%20RGB%20${color.rgbx}`

Actually, this works like a charm and maintaining is acceptable. The only condition is, that you don't control hardware directly from habridge. Otherwise the states in FHEM won't be up-to-date.

**Comment by bwssytems** [comment]
Do you know what the query for devices and or scenes call is? If I have that, it pretty much is easy from there.

**Comment by nihebe** [comment]
I think it would make sense to define a own room `habridge` for habridge in FHEM where the user has to add all FHEM-devices, that should be exposed to habridge. Then you could retrieve them by:
`http://usr:pwd@FHEM-IP:PORT/fhem?cmd=jsonlist2%20room=habridge`

What you're going to receive is a full HTML document. But inside the div with the id `content` you'll have a nice JSON, that lists all devices as single entities. There are going to be lots of parameters, but actually you don't need more than `Name` to build the controller URLs provided an hour ago.

Additionally you could use `PossibleSets`, which tells if there is e.g. `on` and `off` only or also `dim` (-> habridge `${intensity.percent}`) and `RGB` (-> habridge `${color.rgbx}`). Depending on `PossibleSets` you could either allow on/off only, or also dimming and coloring.

In `Readings` you could also read current status of devices in FHEM and refresh them in habridge, but at least in my setup this isn't important, as FHEM remains the `leading` smart home engine, that has logic depending on the device states.

[Here's](https://gist.github.com/nihebe/510df7cf79dcbb0edc30990845e4befc) an example for a sample habridge room with two devices `DeckenlameLinks` (coloring + dimming supported) and `Arbeitslicht` (on off only). The JSON begins in line 152.

**Comment by bwssytems** [comment]
Could you give me an example output of this call. That would go along way in getting this integrated as I do not have a FHEM

**Comment by gvzdus** [comment]
Just want to say "Thank you". habridge now let Alexa open my shutters (via FHEM & Homematic) and set the thermostats (via FHEM & CUL & eq3 MAX). Installation worked very charming, the 2 traps I got caught were the CSRF token and HA bridge promoting rather the dynamic IP of the Wifi LAN than the fixed IP of the Ethernet connection. Webinterface is straight forward. "I am happy". I hope, if Philips should extend the protocol e.g. for fetching values, you will be close behind...

**Comment by bwssytems** [comment]
Please go test RC version in #863

**Comment by bwssytems** [comment]
Would really like someone to test the 5.2.0RC to see if it is working. I do not have a FHEM.

**Comment by gvzdus** [comment]
Hi,

I asked my wife for some time :-)

When will you have RC2 ready you announced some minutes ago? 
I guess I should await this…

BR,


Georg

**Comment by bwssytems** [comment]
@gvzdus I just put RC2 up and it is available

**Comment by gvzdus** [comment]
Hi,

RC2 does not break anything for me, that’s the good news…

Bad news: I don’t know how to enable DEBUG for a certain class.

I would also trust you to login to my raspberry, if you send me your public SSH key.

But please via direct mail (gvz@garnix.de)…

Best regards,


Georg

**Comment by bwssytems** [comment]
DEBUG is turned on in the logs tab at the bottom. Hit the "+" and then select 'show all loggers' That will expand the list of classes. for FHEM select DEBUG for com.bwssystems.HABridge.plugins.fhem and com.bwssystems.HABridge.plugins.http. That should output to your syslog or log file depending on startup and you can post a link to the file. Ue pastebin.org for that.

**Comment by bwssytems** [comment]
New Jar is out in thread #863
