### ISSUE TITLE
Server doesn't listen on IPv4 on Raspberry Pi

### ISSUE THREAD

**Issue by sgruby** [bwssytems/ha-bridge#676]
I installed HA Bridge on a Raspberry Pi 2 today (latest Raspbian Jessie Lite) and installed the java 8 SDK. In troubleshooting the startup, I realized that while it was listening on all interfaces, it was only listening on IPv6. I found a reference on the Vera forums that I need to add:

`-Djava.net.preferIPv4Stack=true`

On the line that starts the bridge for Raspberry Pi. It might be useful to add this in the documentation.

`ExecStart=/usr/bin/java -jar -Dconfig.file=/home/pi/habridge/data/habridge.config -Djava.net.preferIPv4Stack=true /home/pi/habridge/ha-bridge.jar`

**Comment by bwssytems** [comment]
Yes, I see that now as well. Will need to see what sparkjava is doing as of some version around 2, this code is called:
```
        String ipV6Stack = System.getProperty("ipV6Stack");
        if(ipV6Stack == null || !ipV6Stack.equalsIgnoreCase("true")) {
        	System.setProperty("java.net.preferIPv4Stack" , "true");
```

**Comment by bwssytems** [comment]
Well, looking into the internal set and it is not valid after the vm starts, it must be passed on the command line. Thanks, will update the documentation.
