### ISSUE TITLE
google home detected same device 3 times

### ISSUE THREAD

**Issue by Khengsoon** [bwssytems/ha-bridge#677]
Dear all, 

I'm not sure if any of you having the same problem as I had. Echo can discover number of device correctly. but Google Home discover same device appear 3 times on my philips hue device. 

Need help 
Regards, 
Kheng Soon

**Comment by bwssytems** [comment]
I believe this is an issue with discovery and a bug in the ha-bridge not saving the unique id that is given to the calling application.

**Comment by bwssytems** [comment]
related to #669

**Comment by bwssytems** [comment]
This should be resolved with V4.5.6
