### ISSUE TITLE
calling api url: unauthorized user

### ISSUE THREAD

**Issue by 99ttz** [bwssytems/ha-bridge#678]
Hi, after upgrading to 4.5.x (4.5.5.) i cannot invoke any commands via api, e.g.:

curl -H 'Content-Type: application/json' -X PUT -d {"on":true} http://habridge_ip/api/B827EBFFFE2DDD09/lights/2/state

Would result into [{"error":{"type":"1","address":"B827EBFFFE2DDD09","description":"unauthorized user"}}]

Also if i create a user within habridge, activate use username & password for the api and specify username and password to the curl via the "-u" switch, the error message is the same.

Any pointers to what i could do to fix the issue?

Best,
T

**Comment by 99ttz** [comment]
One more thing: is it possible to whitelist for the api call some IPs?

Thanks,
T

**Comment by 99ttz** [comment]
Figured it out :)

**Comment by ramsnerm** [comment]
In case anyone is running into the same edge I note here what I did to solve the issue (using Version 4.5.6):

In the GUI under "Bridge Control" -> "Update Security Settings" I had to deactivate "Use Link Button" (false). Then it worked!
