### ISSUE TITLE
Integrate Tempurpedic bed base

### ISSUE THREAD

**Issue by tymanthius** [bwssytems/ha-bridge#679]
This is likely an edge case, but I would love to see the tempurpedic bed base included here.

Some work has been done to make this an alexa skill at https://github.com/docwho2/java-alexa-tempurpedic-skill

I'm willing to help, but I'm not a programmer.

**Comment by bwssytems** [comment]
Will take a look and see what it takes. IT will be after some other requests though

**Comment by bwssytems** [comment]
Only one person interested in this.....
