### ISSUE TITLE
Linking to hue account online

### ISSUE THREAD

**Issue by javijuan** [bwssytems/ha-bridge#680]
Hi, I was able to program everything and have it working. I want to add some IFTTT applets to my google home connected to a Vera Plus thru HA-Bridge... I am able to "find" a Hue HUB with the latest ha-bridge and hue app... My issue now is when I want to log in to meethue.com and link the hub, it does not find it.

Im running the server on a windows 10 PC, Ha-Bridge 4.5.6, hue app version 2.13.0... only the meethue.com account cannot be linked as it request to "press" the button again on the hub. Not sure if I'm explaining my self clear.. but thats my question... how to link the virtual Hub to meethue.com account so I can give permission to access IFTTT applets.

Thanks

**Comment by bwssytems** [comment]
Since the ha-bridge is not a valid hue product, it just emulates the local api, the linking the ha-bridge to meethue.com never occur. It is to be used only locally.
