### ISSUE TITLE
Ha Bridge 4.5.6 not detected by Alexa App, Show or on http://alexa.amazon.com

### ISSUE THREAD

**Issue by umarally** [bwssytems/ha-bridge#681]
HI,

I have been trying to detect the Ha bridge (Which is detected by Hue App on my IOS) using Alexa but it doesn't discover the devices. I have tried it on multiple ports like 80,8080 etc. I have tried reinstalling raspbian on RPI3 multiple times and doing the setup again. I am able to access Ha bridge and control through <Host>:<port> from any other device on my network but Alexa always gives me the same result, No device found

**Comment by masterchop** [comment]
i had the same problem, i had to rollback to 3.5.x after that everything worked fine again.

**Comment by umarally** [comment]
I have already tried 3.5.1 and still didn't work for me

**Comment by bwssytems** [comment]
You will need to turn some debug on, please review this trouble shooting item and post your log afterwords https://github.com/bwssytems/ha-bridge/wiki/Trouble-Shooting#q-echo-or-google-home-does-not-discover-my-ha-bridge

**Comment by audiofreak9** [comment]
Just want to make sure you have a physical Echo, Dot or Tap, not just the app?

**Comment by audiofreak9** [comment]
Just want to make sure you have a physical Echo, Dot or Tap not just the Alexa App?

**Comment by umarally** [comment]
I have the Echo Show - the new echo with a screen which I am using to discover the device. I will get the logs soon.

**Comment by bwssytems** [comment]
I'll need to you to turn in that Trace up listed in the link above. They may have changed something in the show.

**Comment by umarally** [comment]
Here, Also is there a basic requirement that detection has to be through a physical device? I have tried all three Echo Show, Alexa app and Web
[UPNP logs.docx](https://github.com/bwssytems/ha-bridge/files/1116729/UPNP.logs.docx)

**Comment by rafale77** [comment]
Maybe this could help someone here. I just tried migrating from 3.5.1 to 4.5.6 and wanted to start from scratch as somehow Alexa has been very slow to respond to any hue command as I have been accumulating a lot of redundant devices (double discovered after an upgrade). I also tried moving my bridge from one VM to another and encountered this:

On the new VM, neither 3.5.1 nor 4.5.6 would discover the devices properly. When discovering from the Echo, it would sound like the devices were discovered as the number of devices in the response is correct (ie 59) but when I go into the echo app I see only 12 (all my non bridge devices). I went back to my old VM and did the same thing but all devices discovered properly. The only difference I can see between the 2 VMs is the network setup was missing the Broadcast address under /etc/network/interfaces (I am on ubuntu)

**Comment by shannonmcmurtrey** [comment]
I'm following this issue now also.  I've attached my logs.  
[logs.txt](https://github.com/bwssytems/ha-bridge/files/1126664/logs.txt)

**Comment by bwssytems** [comment]
@umarally What devices did you add to your system? The logs show there are no devices configured. That is not the same as having systems configured in the bridge control tab.

**Comment by bwssytems** [comment]
@shannonmcmurtrey What is your specific issue? Your log shows something communicating with the ha-bridge.

**Comment by umarally** [comment]
i added some rf switches like Eteckcity ones. I can control those from the ha-bridge page.

**Comment by shannonmcmurtrey** [comment]
None of the devices are being discovered by Alexa.

**Comment by shannonmcmurtrey** [comment]
I can control the devices from the habridge web page, and the "test api" seems fine; but when I "discover devices" from Alexa (after forgetting all) none are picked up.

**Comment by bwssytems** [comment]
@umarally What is the IP address of your Amazon Show?

**Comment by bwssytems** [comment]
@shannonmcmurtrey Which Alexa device do you have? And what is it's IP address?

**Comment by umarally** [comment]
192.168.1.20

**Comment by bwssytems** [comment]
@umarally Bad news for you, it looks like they did not implement the local hue api search for the Show. There are never any upnp requests in your log for that IP. You may have to buy an echo dot to get that functionality.

**Comment by shannonmcmurtrey** [comment]
I have a couple of the original Alexa’s and one dot.  I tried discovery from both, also from the web link provided by habridge, and from my alexa app on my iPhone.  Not sure about the IP address.  I’m away from the house.

**Comment by bwssytems** [comment]
@shannonmcmurtrey You'll need to investigate the bridge control tab settings for upnp config address and that your network is allowing the upnp requests to flow from the wifi devices.

**Comment by shannonmcmurtrey** [comment]
It has worked in the past (before upgrading to 4.5.6); but I will double check that when I get home.

**Comment by shannonmcmurtrey** [comment]
UPNP IP Address |  Set to IP address of my raspberry pi
Use UPNP Address Interface Only | I changed this to be true

**Comment by shannonmcmurtrey** [comment]
...and my Alexa IP address is 192.168.1.194

**Comment by shannonmcmurtrey** [comment]
...You'll need to investigate the bridge control tab settings for upnp config address and that your network is allowing the upnp requests to flow from the wifi devices.

Did that, still no luck.  UPNP is definitely enabled; but the bridge isn't logging the IP address of my alexa at all.  I can control devices from the habridge web page; but Alexa isn't finding them.

**Comment by umarally** [comment]
HI @bwssytems on the description page for Echo Show it says "Ask Alexa to show you the front door or monitor the baby's room with compatible cameras from Ring and Arlo. Turn on lights, control thermostats and more with WeMo, Philips Hue, ecobee, and other compatible smart home devices."


Since Philips Hue is mentioned and I thought the Ha Bridge mimicks a hue Bridge so it should be discovered. Just trying all the options that could resolve this.

**Comment by bwssytems** [comment]
@umarally Then there must be something preventing your show from sending upnp broadcasts as the request does not show up in your log for that ip.

**Comment by umarally** [comment]
yes, I noticed that as well. I have unblocked UNPN request on my router. Any other ideas where I can look to unblock this ?

**Comment by bwssytems** [comment]
I have no other ideas without seeing your whole network setup. Any news on this

**Comment by umarally** [comment]
so I bought a Echo Dot and it worked perfectly with that. Thanks I am closing this.

**Comment by bwssytems** [comment]
That is unfortunate then. The Show must not do the discovery....

**Comment by masterchop** [comment]
3.5.1 works fine for me but 4,5.6 is not been detected this is so weird.

**Comment by willypowwow** [comment]
I had an issue with devices not being discovered.  In my case, changing the Upnp address from localhost to the specific IP resolved the issue.

**Comment by heffneil** [comment]
I have upgraded to 5.0 and I can't find devices.  I removed all my devices and added just one for this test.  I know uPNP works because all my ip cameras are detectable.  I am trying with the website and a show.  I will try with an dot next.  Its very odd.  The upnp address is the IP of the machine so that is confirmed as well.  Any other ideas?

**Comment by bwssytems** [comment]
Are you also using web port 80, it is default unless overridden.

**Comment by heffneil** [comment]
Yes I am using port 80.  I believe I was using port 80 prior but I could be wrong.  Is there a way to change ports for the UPNP?  I noticed the response port is set to 5000. Thanks!

**Comment by umarally** [comment]
try with a echo dot. Echo show was not detecting my devices over UNPN

**Comment by heffneil** [comment]
How does one override the UPNP port?

**Comment by heffneil** [comment]
I changed the port on Apache to 80 and it doesn't work - this is with an echo show.  I will try when I go upstairs on a dot.  Seems odd that one would work vs another?!

**Comment by heffneil** [comment]
I tried with an echo dot, didn't work.  I tried with two different Shows.  I was concerned about being in different subnets although my subnet is set to 255.255.0.0 in DHCP.  I setup a reservation in the DHCP server so I confirmed that this Echo Show and my server are all in the same class C of 192.168.1.x

**Comment by michaelhinchey** [comment]
What ports have you tried?









    Every dream is a goal with a date on it; if you can conceive it believe
it, you can achieve it. Don't let anyone steal your dream. Make the
decision to take a positive attitude, take pride in yourself and what you
do, work hard and stay with it. A mind is a terrible thing to waste.


"I felt bad because I couldn't wheelie; until I met a man with no bicycle"

"You are young at any age... if you are planning on tomorrow"

**Comment by heffneil** [comment]
What ports? I didn’t change them just moved the service (Apache) blocking it. 

Thanks,
Neil H.

**Comment by heffneil** [comment]
So today I tried it again just now.  I did the search from the Alexa website and it found them! BTW i do run apache and have always run apache on port 80 and it has never been a problem.  I have NO idea why it works today because the other day I had tried from the website and it didn't find them.  Very very strange but for today its working!

**Comment by sheriffdude** [comment]
hi guy how do you run ha bridge on port 80 mine is se to run or start with a batch file 
ie java -jar -Dserver.port=8081 ha-bridge.jar this starts my ha bridge ..then i use http://localhost:8081/#!/ to show bridge ..i can turn my easy bulbs of and on but can not get my echo dot to find the ha bridge if i change web server port to 80 and save it just goes back to 8081

**Comment by mikep809** [comment]
Everything was working fine until i migrated to 5.2? Now none of my x10 devices are found with my dots. Any ideas?

**Comment by echery** [comment]
Make sure ha-bridge is using the same UPNP address as the one used to access it from the browser. My setup didn't originally because the UPNP auto discovered a random IP that was not the IP for ha-bridge.
![image](https://user-images.githubusercontent.com/10801762/43360182-c058d46c-927e-11e8-8cbd-b6725621a770.png)
