### ISSUE TITLE
HTTP Request - JSON in the URL string - Illegal character in query

### ISSUE THREAD

**Issue by robste11159** [bwssytems/ha-bridge#682]
Hi,
I'm using ha-bridge with this project: https://github.com/mdhiggins/ESP8266-HTTP-IR-Blaster
For some IR codes, I need to use a URL like:

http://myhost.asuscomm.com:8080/json?pass=mypass&plain=[{"type":"raw","data":[3500,1700, 450,450, 450,1300, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,1300, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,1300, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,1300, 450,1300, 450,1300, 450,1300, 450,1300, 450,1300, 450,450, 450,450, 450,1300, 450,1300, 450,1300, 450,1300, 450,1300, 450,1300, 450,450, 450,1300, 450],"khz":"38","repeat":1,"rdelay":80}]

The above works in my browser and IFTTT, but HA-Bridge doesn't like this as the "target item", any ideas on how to make it happy?

The logs spat this out, but after trying for an hour or so I'm not making any progress:

Error creating URI http request: http://myhost.asuscomm.com:8080/json?pass=mypass&plain=[{"type":"raw","data":[3500,1700, 450,450, 450,1300, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,1300, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,1300, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,1300, 450,1300, 450,1300, 450,1300, 450,1300, 450,1300, 450,450, 450,450, 450,1300, 450,1300, 450,1300, 450,1300, 450,1300, 450,1300, 450,450, 450,1300, 450],"khz":"38","repeat":1,"rdelay":80}] with message: Illegal character in query at index 72: http://myhost.asuscomm.com:8080/json?pass=mypass&plain=[{"type":"raw","data":[3500,1700, 450,450, 450,1300, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,1300, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,1300, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,450, 450,1300, 450,1300, 450,1300, 450,1300, 450,1300, 450,1300, 450,450, 450,450, 450,1300, 450,1300, 450,1300, 450,1300, 450,1300, 450,1300, 450,450, 450,1300, 450],"khz":"38","repeat":1,"rdelay":80}]

Thanks!

**Comment by bwssytems** [comment]
I'll need to look into the URI formatter that is being used. It seems it does not like the '['

**Comment by bwssytems** [comment]
It is a few characters since I use the generic URI formatter. Your request should look like this:
```
http://http://myhost.asuscomm.com:8080/json?pass=mypass&plain=%5B%7B%22type%22:%22raw%22,%22data%22:%5B3500,1700/json?pass=mypass&plain=%5B%7B%22type%22:%22raw%22,%22data%22:%5B3500,1700,450,450,450,1300,450,450,450,450,450,450,450,450,450,450,450,450,450,450,450,450,450,450,450,450,450,450,450,1300,450,450,450,450,450,450,450,450,450,450,450,450,450,450,450,450,450,450,450,1300,450,450,450,450,450,450,450,450,450,450,450,450,450,450,450,450,450,1300,450,1300,450,1300,450,1300,450,1300,450,1300,450,450,450,450,450,1300,450,1300,450,1300,450,1300,450,1300,450,1300,450,450,450,1300,450%5D,%22khz%22:%2238%22,%22repeat%22:1,%22rdelay%22:80%7D%5D
```

**Comment by bwssytems** [comment]
Did this solve your issue?
