### ISSUE TITLE
Cannot reuse a former device.db ?

### ISSUE THREAD

**Issue by Xavier38330** [bwssytems/ha-bridge#683]
Hi

I had to reinstall ha-bridge on a new installation (RPi3) and I saved my old device.db

I stopped the new ha-bridge service and copied device.db in the data directory.

I thought that restarting the service would take into account my old device.db but it still empty on the web portal.

How can I import my old database to avoid recreating all the emulated devices ?

**Comment by bwssytems** [comment]
Which versions were going from and to?

**Comment by Xavier38330** [comment]
To 4.5.6 but can't find the old one. Is there a way to convert it ?

**Comment by bwssytems** [comment]
Which version did you start with?

**Comment by bwssytems** [comment]
After v3.x there was a change in the way on and off items were handled and that code may be removed. You can add '"[{\"item\":\"<your http url here>\",\"type\":\"httpDevice\"}]"' and that would help

**Comment by Xavier38330** [comment]
I should add this where ? I just checked my old device.db file and there are already such markers.

**Comment by bwssytems** [comment]
Then you should be fine running that file, can you post the file so I can take a look?

**Comment by Xavier38330** [comment]
Thanks but I decided to rebuilt from scratch.
