### ISSUE TITLE
Newbie how do you setup dimmer %

### ISSUE THREAD

**Issue by Tsportcar** [bwssytems/ha-bridge#684]
I have tried and tried to figure out the correct format to pass through the percentage lamp intensity from Google Home but with no luck.

{"clientId":"HAbridge","topic":"MainLightDimmer","message":"$"{intensity.percent}

Please can someone point me in the right direction?

**Comment by audiofreak9** [comment]
You have **"$"{intensity.percent}** above, the percentage variable is **${intensity.percent}**.  The string symbol (dollar sign) needs to be next to the open brace.  I'm going to guess you should use **"${intensity.percent}"** instead.

**Comment by Tsportcar** [comment]
Yes now working a treat thank you.
