### ISSUE TITLE
state not updating

### ISSUE THREAD

**Issue by 99ttz** [bwssytems/ha-bridge#686]
Hi bwssytems,

Since version 4.5.x nor state not bridgeupdate commands updates the state (no matter true or false):

e.g.: 

curl -H 'Content-Type: application/json' -X PUT -d {"on":true} http://192.168.1.2/api/homebridge/lights/9/state

curl -H 'Content-Type: application/json' -X PUT -d {"on":true} http://192.168.1.2/api/homebridge/lights/9/bridgeupdatestate

Results in the same state (assuming the initially was false):
	"9": {
		"state": {
			"on": false,
			"bri": 0,
			"hue": 0,
			"sat": 0,
			"effect": "none",
			"ct": 0,
			"alert": "none",
			"reachable": true
		},

The action is performed correctly, but by not having the state updated, the information in homekit is not displayed correctly. This behavior started with 4.x series of ha bridge. The 3.x series worked flawlessly.

Is there something that needs to be done differently?

Best
T

**Comment by bwssytems** [comment]
Will take a look.

**Comment by bwssytems** [comment]
Under 4.5.6 I am getting the state back correctly. What method are you using to get the state?

**Comment by 99ttz** [comment]
Hi bwssytems,

I'm using: curl -X GET http://192.168.1.2/api/homebridge/lights

Also tested using 4.5.6. The issue is that the status in homebridge (which connects to habridge) no longer gets updated, and it was updating when on 3.5.x. The culprit seems to be the commands issued with curl as any actions in homebridge, gets habridge executing some scripts containg curl commands to habridge.

Any ideas?

Best,
T

**Comment by bwssytems** [comment]
I cannot get it to fail. Using Curl or Postman.

**Comment by 99ttz** [comment]
So for you state updates correctly? :(

The curl executes ok for me, action is performed, but status is not
updated...

-- 
Theodor Carp

From: BWS Systems <notifications@github.com> <notifications@github.com>
Reply: bwssytems/ha-bridge
<reply@reply.github.com>
<reply@reply.github.com>
Date: 7 July 2017 at 22:17:32
To: bwssytems/ha-bridge <ha-bridge@noreply.github.com>
<ha-bridge@noreply.github.com>
CC: 99ttz <theodor.carp@gmail.com> <theodor.carp@gmail.com>, Author
<author@noreply.github.com> <author@noreply.github.com>
Subject:  Re: [bwssytems/ha-bridge] state not updating (#686)

I cannot get it to fail. Using Curl or Postman.

**Comment by bwssytems** [comment]
Have you tried it on a command line outside of a script or using postman to verify? Also, is the state call immediately after the state call? If so, each call is independent and the first call may not be completed yet.

**Comment by 99ttz** [comment]
Yes. All the troubleshooting i'm doing outside the scripts by using the command line. I also waited for 30 secs before checking the state.

The interesting part is that if i use the web interface, which calls the exact same scripts, it updates the state correctly...

**Comment by bwssytems** [comment]
I am at a loss here as I would need to see your complete setup. How you start the ha-bridge, how it is stopped. Is  there another process taking over your port, etc.
