### ISSUE TITLE
Web Service rejected

### ISSUE THREAD

**Issue by lemrock** [bwssytems/ha-bridge#687]
This is probably not a problem with the HA Bridge but I experienced a power outage last night and now I can't get the HA Bridge web service thru my Raspberry Pi 2.  Apparently everything is still working because all of my voice commands are working.   I can't get the service thru any browser on my iMac and Windows 10 machine. The error says "connection refused".  I checked all the files and they are correct also checked my router and things appear as they always have been.  I'm just asking is there anything else I can check.  I'm using version 4.5.1 and it was working for months prior to my issue.

**Comment by bwssytems** [comment]
So, you will need to check your network settings. The hue api runs on the same port as the web pages....

**Comment by lemrock** [comment]
I believe I understand what's going on with my HA Bridge.  I've checked the 8080 port and the only thing using it on my system is the HA Bridge on the RPi 2.  Again, everything was running beautifully until 2 days ago.  I changed or added nothing.  

I decided to just run the HA Bridge from a command line:
/usr/bin/java -jar -Dserver.port=8080 -Dconfig.file=/home/pi/habridge/data/habridge.config -Dupnp.device.db=/home/pi/habridge/data/device.db /home/pi/habridge/ha-bridge-4.5.6.jar

And everything worked!!!!

So I suspected the services I installed on the RPi had stopped. I'm using the systemd method for creating the service:

Unit]
Description=HA Bridge 
Wants=network.target
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/java -jar -Dserver.port=8080 -Dconfig.file=/home/pi/habridge/data/habridge.config -Dupnp.device.db=/home/pi/habridge/data/device.db /home/pi/habridge/ha-bridge-4.5.6.jar
Restart=always
Restart=3

[Install]
WantedBy=multi-user.target

I checked the status of the service:
pi@raspberrypi:~ $ systemctl status habridge1.service
habridge.service - HA Bridge
Loaded: loaded (/usr/lib/systemd/system/habridge.service; enabled)
Active: active (running) since Fri 2017-07-07 00:56:03 UTC; 621ms ago
Main PID: 1626 (java)
   CGroup: /system.slice/habridge.service
           └─1626 /usr/bin/java -jar -Dserver.port=8080 -Dconfig.file=/home/p...

And I checked to see if the service failed:
pi@raspberrypi:~ $ systemctl is-failed habridge.service
active

So the service is enabled and active and I assume is running correctly but I get the "connection refused" error when I try to use the UI thru a browser.  I don't get the error when I execute the commands from a command line prompt.   I'm stumped and looking for advice.

**Comment by kmdm** [comment]
Pi2:
```
# iptables-save
# netstat -lntp | grep 8080
```

**Comment by bwssytems** [comment]
Also to check if it is running after 'systemctl start habridge1.service' si to run 'ps aux | grep bridge'

**Comment by dghh** [comment]
I have the same issue at the moment with ha-bridge-4.5.6.jar. Often, after starting with systemd, the service 
 is shortly active and then exits with error port 1900 already used..... Something was changed with the handling of port 1900, i think.

**Comment by bwssytems** [comment]
@dghh You either have another instance of the ha-bridge running or you have some other process utilizing upnp and not allowing the port to share.

**Comment by bwssytems** [comment]
any update on this?

**Comment by lemrock** [comment]
Oh yes, it worked very well.
