### ISSUE TITLE
HTTP Device - Echo - "[device] isn't respondig"

### ISSUE THREAD

**Issue by tohu2000** [bwssytems/ha-bridge#690]
Bridge is setup, Echo discovers all HTTP devices on RASP PI.

Actioning the HTTP devices through browser like:  http://rasp:8888/group_3_down works just fine. The HTTP server request closes with an HTTP 200 OK.  All fine too when I hit the button in the HA-Bridge console app (!)

Now if i user the bridge using the Echo - the call is being made twice, and Echo responds  "[device] isn't respondig".

That is weird, help?

[{"id":"1","uniqueid":"00:17:88:5E:D3:01-01","name":"Master Bedroom Shade","mapType":"httpDevice","deviceType":"custom","offUrl":"[{\"item\":\"http://localhost:8888/group_3_down\",\"type\":\"httpDevice\",\"httpVerb\":\"GET\",\"contentType\":\"*/*\",\"delay\":\"0\",\"count\":\"0\"}]","onUrl":"[{\"item\":\"http://localhost:8888/group_3_up\",\"type\":\"httpDevice\",\"httpVerb\":\"GET\",\"contentType\":\"*/*\",\"delay\":\"0\",\"count\":\"0\"}]","inactive":false,"noState":false,"offState":false,"deviceState":{"on":false,"bri":0,"hue":0,"sat":0,"effect":"none","ct":0,"alert":"none","reachable":true}}

**Comment by bwssytems** [comment]
The configuration looks fine. Would need you to turn on debugging and post log to help find the cause. https://github.com/bwssytems/ha-bridge#the-logs-tab

**Comment by jeffrego** [comment]
It looks like HTTPHome.deviceHandler expects a non-null response from the API. The API I was calling from HA Bridge returns a 204 (no content) with a null entity on success, so while the action was successful the Echo thinks it's failed based on the response from HA Bridge. I just modified my API to return the String "SUCCESS" on success, and now it plays well together.

I think most of the smart home APIs return some kind of status when you change something, so I could see an argument that a null response means something has gone wrong. It doesn't look like HA Bridge actually needs to do anything with the response though, so if HTTPHandler threw an exception if it got too many non-200 responses and ran out of retries then HTTPHome could look for that, and return success if it doesn't get one. If this seems reasonable I can submit a pull request.

Here's a section of my logs that covers the problem:
```
09-17-2017 20:59:25.005 | DEBUG | executing HUE api request to Http PUT: http://192.168.1.2:9089/api/lights/10/state | com.bwssystems.HABridge.plugins.http.HTTPHome
-- | -- | -- | --
09-17-2017 20:59:25.005 | DEBUG | doHttpRequest with url: http://192.168.1.2:9089/api/lights/10/state with http command: PUT with body: {"on":false} | com.bwssystems.HABridge.plugins.http.HTTPHandler
09-17-2017 20:59:25.005 | DEBUG | Making outbound call in doHttpRequest: <<<PUT http://192.168.1.2:9089/api/lights/10/state HTTP/1.1>>> | com.bwssystems.HABridge.plugins.http.HTTPHandler
09-17-2017 20:59:25.029 | DEBUG | PUT execute (0) on URL responded: 204 | com.bwssystems.HABridge.plugins.http.HTTPHandler
09-17-2017 20:59:25.029 | DEBUG | Successfull response - The http response is <<<null>>> | com.bwssystems.HABridge.plugins.http.HTTPHandler
09-17-2017 20:59:25.029 | WARN | Error on calling url to change device state: http://192.168.1.2:9089/api/lights/10/state | com.bwssystems.HABridge.plugins.http.HTTPHome
```

**Comment by bwssytems** [comment]
any update on this?
