### ISSUE TITLE
cannot execute python command

### ISSUE THREAD

**Issue by dony71** [bwssytems/ha-bridge#692]
I have latest ha-bridge 4.5.6 
I want to control MyQ Chamberlain Garage Door via python script
I get the script from https://github.com/Einstein42/myq-garage
The script is working OK if I execute in terminal, for ex. 
/usr/bin/python  /root/myQ/myq-garage.py  open  Garage Door
this will open door.
However when I put this command line in HA-Bridge, it doesn't work
Log file show below 
Decode Json for url items: [{"item":"/usr/bin/python /root/myQ-Garage/myq-garage.py open Garage Door","type":"cmdDevice"}]
Exec Request called with url: /usr/bin/python /root/myQ-Garage/myq-garage.py open Garage Door and exec Garden: not given
Executing request: /usr/bin/python /root/myQ-Garage/myq-garage.py open Garage Door
Process running: true

**Comment by Rob78** [comment]
Hi, have you found a solution to your issue? I am having a similar problem. I am trying to execute an sh script. I gave read and execute access to www-data. One will work but the other two do not work.

Device1 (executes sshpass to run a command in another linux system. It changes the voicemail on my asterisk PBX system)
exec:///etc/sh-scripts/voicemail1.sh

Device2 (executes sshpass to run a command in another linux system. It change the voicemail on my asterisk PBX system)
exec:///etc/sh-scripts/voicemail2.sh

Device3 (executes winexe to make the PC open a fireplace video and displays it on the TV
exec:///etc/sh-scripts/fireplace.sh

all scripts work fine from terminal but only one works from HA-Bridge. I came to the conclusion it has to do with privileges. The one without needing privileges executes just fine however the one requiring privilages will not execute from ha-bridge. Please note I do not have to type for any command when running from terminal they work fine from terminal. Maybe the ha-bridge is not running as www-data?

**Comment by bwssytems** [comment]
So, you need to encapsulate the running of python itself inside a script that is executed as a non shell command. You will need to google this please.
