### ISSUE TITLE
Multiple Questions

### ISSUE THREAD

**Issue by lemrock** [bwssytems/ha-bridge#694]
As you can see from my username I've been asking a lot of questions lately.  Something happened to my perfectly stable HA Bridge and I'm at the point where I have reimaged the RPi and starting all over again.  I would like to ask a few questions in this single post:

1.  The configuration and device.db path names I thought would be able to configure from the UI but after I hit save and the bridge re initializes I'm still in the old locations,  am I doing something wrong?

**Comment by bwssytems** [comment]
When starting from the system scripts, they become relative to root and not the pi user. That is why there are command line arguments to tell where to find the config file for startup.
