### ISSUE TITLE
Wand doesn't discover devices

### ISSUE THREAD

**Issue by mwm** [bwssytems/ha-bridge#697]
Alexa fails to discover the HA-bridge from a Dash Wand. This isn't one of the "prototype devices" that are known not to work, but it's also not on the list of "physical devices" that are known to work.

Should I expect this to work? If not, the docs ought to be updated.

Update: grabbed a fire stick and tried that as well. Still no go.

**Comment by audiofreak9** [comment]
I have one, and can report it will NOT discover without one of the listed physical devices.  However once your devices are discovered, it will control them.
