### ISSUE TITLE
Alexa unable to discover devices when running on FreeBSD because multicast join failed

### ISSUE THREAD

**Issue by HarryWeppner** [bwssytems/ha-bridge#698]
I am reporting this issue along with a solution to make this easier to fix for other FreeBSD users.

On my Raspberry Pi B+, Alexa did not discover any devices. My environment was:

```
root@rpi-b:~ # uname -a                                                                                                
FreeBSD rpi-b 11.1-PRERELEASE FreeBSD 11.1-PRERELEASE #0 r319452: Fri Jun  2 13:00:54 UTC 2017     root@releng2.nyi.freebsd.org:/usr/obj/arm.armv6/usr/src/sys/RPI-B  arm                                              
root@rpi-b:~ # java -version                                                                                           
openjdk version "1.8.0_92"                                                                                             
OpenJDK Runtime Environment (build 1.8.0_92-b14)                                                                       
OpenJDK Zero VM (build 25.92-b14, interpreted mode)
```

Looking at the log I stumbled across the following error:

```
Multicast join failed for: 239.255.255.250 to interface: ue0 with message: Invalid argument
```

Indeed, `ifmcstat -f inet -v` confirmed that the interface `ue0` had in fact not joined the multicast group `239.255.255.250`. That led me to an [old FreeBSD list posting](https://lists.freebsd.org/pipermail/freebsd-net/2014-February/037958.html) that suggested to force IPv4 by setting `java.net.preferIPv4Stack=true`.

After modifying the startup script by adding `-Djava.net.preferIPv4Stack=true` joining the multicast group worked, which then allowed all devices to be discovered.

I would suggest to add this to the doc or even enforce that in code, i.e. `System.setProperty("java.net.preferIPv4Stack", "true")`.

**Comment by bwssytems** [comment]
Glad you found a solution. This is already in the doc https://github.com/bwssytems/ha-bridge#-djavanetpreferipv4stacktrue

But the Java internal to set the property is not valid as when it is set inside the program, it is way past the point where it is used in the VM. That is why it is now documented to pass on the command line.

**Comment by HarryWeppner** [comment]
I missed that in the docs - probably because it isn't mentioned in relationship to failing to join the multicast group. Anyway, people who are having the same problem will now find this issue ;-)
