### ISSUE TITLE
Send commands to ha-bridge

### ISSUE THREAD

**Issue by DavidFBakker** [bwssytems/ha-bridge#699]
Hopefully i didnt miss something obvious but can i send commands (curl/command line...) to ha-bridge to execute bridged devices? For instance send a http post command to turn my nest to X temperature.

**Comment by audiofreak9** [comment]
Yes, you can both control and update stored state for ha-bridge configured devices:
https://github.com/bwssytems/ha-bridge#set-light-state
https://github.com/bwssytems/ha-bridge#update-bridge-internal-light-state

**Comment by DavidFBakker** [comment]
Perfect! Thanks for an awesome piece of software!
