### ISSUE TITLE
Virtually support multiple HUE bridges

### ISSUE THREAD

**Issue by bwssytems** [bwssytems/ha-bridge#7]
Since there seems to be a limitation between the echo and the bridge for the number of devices, it may be prudent to emulate multiple HUE bridges virtually inside one bridge to overcome this limitation.

**Comment by rafale77** [comment]
Have you actually observed the limitation? I have now 60 devices and have not seen any yet.

**Comment by bwssytems** [comment]
Personally, I have not. Others that I have communicated have found this before. So a big question would be is what version of software is your echo on. As this was a limitation found with the echo itself, not the bridge. A recent Echo update may have changed it.

**Comment by bwssytems** [comment]
I'm going to put this issue into the category of closed as it doesn't make sense. If there is an issue, running multiple instances of the ha-bridge with different ports does the trick.

**Comment by quenthal** [comment]
I'd like to open this again - I'm using ha-bridge for some lamps with Logitech Harmony, as they are not natively supported by Logitech. However I also have real Philips Hue, and Harmony supports only one Hue Hub. Currently for Logitech usage I'm commanding real Hub with ha-bridge, which works expect for keeping track of lamp states.
