### ISSUE TITLE
'About' menu not working at al

### ISSUE THREAD

**Issue by Ltek** [bwssytems/ha-bridge#70]
For the last few versions, when I click on 'About' - nothing happens. All other menus work perfectly. The The 'About' menu link is to... http://192.168.2.XX:8099  ... Is this right?

**Comment by bwssytems** [comment]
I will test again. That happened a few version ago due to a bug.

**Comment by bwssytems** [comment]
This has been fixed in v1.4.1.

**Comment by bwssytems** [comment]
Any new comments?

**Comment by bwssytems** [comment]
Closing due to lack of interest.
