### ISSUE TITLE
Access /api/devices when username/password security is set?

### ISSUE THREAD

**Issue by audiofreak9** [bwssytems/ha-bridge#700]
Is there a way to access /api/devices when username/password security is set?

My [PHP Control page code](https://github.com/audiofreak9/HA-Bridge_Control) parses the JSON response from /api/devices, but can't access when a username and password is set on the HA-Bridge.

**Comment by tuicemen** [comment]
Are you sending username and password with the request?
I'm not using PHP but I get a responce

**Comment by audiofreak9** [comment]
Using `file_get_contents()`, I'll try to use the Authorization Header.

**Comment by audiofreak9** [comment]
@tuicemen Yeah, that worked, thanks for the nudge!

**Comment by tuicemen** [comment]
Glad it wasn't a bug.
I initially also forgot to use authorization in my requests, I guess I figured initial login would not require it.
