### ISSUE TITLE
Alexa does not find HA Bridge devices - I only have 2

### ISSUE THREAD

**Issue by Ltek** [bwssytems/ha-bridge#702]
Just yesterday I updated HA-Bridge to the latest version (it was a few versions back). I removed all Vera & Harmony Hub devices from it.

Now I only have the Harmony Hub (Vera is retired) connected to HA-B with 2 Activities added

Alexa discovers 48 Homeseer devices just fine but no longer finds anything on HA-Bridge?

ideas?

thx

**Comment by FloFoer** [comment]
The latest version works fine for me.  
I would start by looking at the response for GET <ha_bridge_ip>/api/<user>/lights 
If everything is ok there, turn on the debug log in the logs tab under logging configuration. Start a discovery on your echo and look at the log. Maybe use "tail -f /var/log/syslog" on your shell for that, than start the discovery, CTRL+C after discovery is finished and then check the console output. (I think that is an easy way to access the log for a specific test)
Look for anything unusual in the discovery phase.

**Comment by bwssytems** [comment]
any update on this?
