### ISSUE TITLE
iconnect hue - ha bridge - fhem

### ISSUE THREAD

**Issue by DaJansenGit** [bwssytems/ha-bridge#703]
Hey i use fhem to control some 433 mhz plugs. Now i integrated them into ha bridge as http devices and the on and off function is working fine. My next step would be to control the ha bridge devices by my iconnect hue app. I can discover the ha bridge and also my devices are shown but if i want to put them on or off nothing happens. Actually it works with the original philips hue app but not with iConnect hue. Does anybody have an idea what the problem could be?
I want to use iconnect hue because they have multi bridge support and i have also an original hue bridge in my home.
Thank you in advance.

**Comment by FloFoer** [comment]
I guess when it's working with the official hue app it could be that it's not a problem in ha-bridge.  
I would turn on the debug log in the logs tab under logging configuration to look for what's going on. If debug log is on issue "tail -f /var/log/syslog" on your shell, then try to turn on your plug via iconnect , afterwards stop the log monitoring with CTRL+C and then check the console output.   
Look for anything unusual. It could be a good idea to do the same with the official hue app and compare the result to look if they behave differently.

**Comment by DaJansenGit** [comment]
hey thank you for your help.
i watched the logs and did a copy:
iConnectHue:
`Jul 20 12:15:55 localhost java[2846]: 2017-07-20 12:15:55,061 [qtp23426297-16] DEBUG spark.Request - get params
Jul 20 12:15:55 localhost java[2846]: 2017-07-20 12:15:55,062 [qtp23426297-16] DEBUG spark.Request - matchedPart: :userid = Qn99zAModJzV-zOjfwtw9JrhP7TOWiI82Uf5ASg0
Jul 20 12:15:55 localhost java[2846]: 2017-07-20 12:15:55,062 [qtp23426297-16] DEBUG spark.Request - get splat
**Jul 20 12:15:55 localhost java[2846]: 2017-07-20 12:15:55,063 [qtp23426297-16] DEBUG com.bwssystems.HABridge.hue.HueMulator - hue api full state requested: Qn99zAModJzV-zOjfwtw9JrhP7TOWiI82Uf5ASg0 from 127.0.0.1**
Jul 20 12:15:55 localhost java[2846]: 2017-07-20 12:15:55,064 [qtp23426297-16] DEBUG com.bwssystems.HABridge.BridgeSecurity - validateWhitelistUser: found a user <Qn99zAModJzV-zOjfwtw9JrhP7TOWiI82Uf5ASg0>
Jul 20 12:15:55 localhost java[2846]: 2017-07-20 12:15:55,088 [qtp23426297-16] DEBUG com.bwssystems.HABridge.hue.HueMulator - hue lights list requested: Qn99zAModJzV-zOjfwtw9JrhP7TOWiI82Uf5ASg0 from 127.0.0.1
Jul 20 12:15:55 localhost java[2846]: 2017-07-20 12:15:55,089 [qtp23426297-16] DEBUG com.bwssystems.HABridge.BridgeSecurity - validateWhitelistUser: found a user <Qn99zAModJzV-zOjfwtw9JrhP7TOWiI82Uf5ASg0>
Jul 20 12:15:55 localhost java[2846]: 2017-07-20 12:15:55,090 [qtp23426297-16] DEBUG com.bwssystems.HABridge.hue.HueMulator - hue group list requested: Qn99zAModJzV-zOjfwtw9JrhP7TOWiI82Uf5ASg0 from 127.0.0.1
Jul 20 12:15:55 localhost java[2846]: 2017-07-20 12:15:55,090 [qtp23426297-16] DEBUG com.bwssystems.HABridge.BridgeSecurity - validateWhitelistUser: found a user <Qn99zAModJzV-zOjfwtw9JrhP7TOWiI82Uf5ASg0>
Jul 20 12:15:55 localhost java[2846]: 2017-07-20 12:15:55,091 [qtp23426297-16] DEBUG com.bwssystems.HABridge.hue.HueMulator - hue group id: <1> requested: Qn99zAModJzV-zOjfwtw9JrhP7TOWiI82Uf5ASg0 from 127.0.0.1
Jul 20 12:15:55 localhost java[2846]: 2017-07-20 12:15:55,091 [qtp23426297-16] DEBUG com.bwssystems.HABridge.BridgeSecurity - validateWhitelistUser: found a user <Qn99zAModJzV-zOjfwtw9JrhP7TOWiI82Uf5ASg0>
Jul 20 12:16:00 localhost java[2846]: 2017-07-20 12:16:00,083 [qtp23426297-9] DEBUG spark.webserver.MatcherFilter - httpMethod:get, uri: /api/Qn99zAModJzV-zOjfwtw9JrhP7TOWiI82Uf5ASg0/
`

Official Hue App:
`Jul 20 12:18:10 localhost java[2846]: 2017-07-20 12:18:10,752 [qtp23426297-13] DEBUG spark.Request - get params
Jul 20 12:18:10 localhost java[2846]: 2017-07-20 12:18:10,752 [qtp23426297-13] DEBUG spark.Request - get splat
Jul 20 12:18:10 localhost java[2846]: 2017-07-20 12:18:10,754 [qtp23426297-13] DEBUG com.bwssystems.HABridge.hue.HueMulator - HueMulator PUT called on api/* with request <<</api/7548a43c607c4445b8bbe24d4456e0df/lights/1/state>>>, and body <<<{"on":false}>>>
Jul 20 12:18:10 localhost java[2846]: 2017-07-20 12:18:10,755 [qtp23426297-13] DEBUG spark.Request - get params
Jul 20 12:18:10 localhost java[2846]: 2017-07-20 12:18:10,757 [qtp23426297-13] DEBUG spark.Request - matchedPart: :userid = 7548a43c607c4445b8bbe24d4456e0df
Jul 20 12:18:10 localhost java[2846]: 2017-07-20 12:18:10,757 [qtp23426297-13] DEBUG spark.Request - matchedPart: :id = 1
Jul 20 12:18:10 localhost java[2846]: 2017-07-20 12:18:10,757 [qtp23426297-13] DEBUG spark.Request - get splat
**Jul 20 12:18:10 localhost java[2846]: 2017-07-20 12:18:10,757 [qtp23426297-13] DEBUG com.bwssystems.HABridge.hue.HueMulator - hue state change requested: 7548a43c607c4445b8bbe24d4456e0df from 127.0.0.1 body: {"on":false}**
Jul 20 12:18:10 localhost java[2846]: 2017-07-20 12:18:10,758 [qtp23426297-13] DEBUG com.bwssystems.HABridge.BridgeSecurity - validateWhitelistUser: found a user <7548a43c607c4445b8bbe24d4456e0df>
Jul 20 12:18:10 localhost java[2846]: 2017-07-20 12:18:10,759 [qtp23426297-13] DEBUG com.bwssystems.HABridge.hue.HueMulator - Decode Json for url items: [{"item":"http://192.168.178.51:8083/fhem?cmd.Test=set%20wz_BestaLampe%20off","type":"httpDevice","httpVerb":"GET"}]
Jul 20 12:18:10 localhost java[2846]: 2017-07-20 12:18:10,762 [qtp23426297-13] DEBUG com.bwssystems.HABridge.plugins.http.HTTPHome - executing HUE api request to Http GET: http://192.168.178.51:8083/fhem?cmd.Test=set%20wz_BestaLampe%20off
Jul 20 12:18:10 localhost java[2846]: 2017-07-20 12:18:10,763 [qtp23426297-13] DEBUG com.bwssystems.HABridge.hue.DeviceDataDecode - Request <<http://192.168.178.51:8083/fhem?cmd.Test=set%20wz_BestaLampe%20off>>, not done: false
Jul 20 12:18:10 localhost java[2846]: 2017-07-20 12:18:10,764 [qtp23426297-13] DEBUG com.bwssystems.HABridge.plugins.http.HTTPHandler - doHttpRequest with url: http://192.168.178.51:8083/fhem?cmd.Test=set%20wz_BestaLampe%20off with http command: GET with body: null
Jul 20 12:18:10 localhost java[2846]: 2017-07-20 12:18:10,766 [qtp23426297-13] DEBUG com.bwssystems.HABridge.plugins.http.HTTPHandler - Making outbound call in doHttpRequest: <<<GET http://192.168.178.51:8083/fhem?cmd.Test=set%20wz_BestaLampe%20off HTTP/1.1>>>
Jul 20 12:18:10 localhost java[2846]: 2017-07-20 12:18:10,840 [qtp23426297-13] DEBUG com.bwssystems.HABridge.plugins.http.HTTPHandler - GET execute (0) on URL responded: 200
Jul 20 12:18:10 localhost java[2846]: 2017-07-20 12:18:10,841 [qtp23426297-13] DEBUG com.bwssystems.HABridge.plugins.http.HTTPHandler - Successfull response - The http response is <<<null>>>`

It seems like the iconnect hue app only makes a full state request while the official hue app makes a change request. I marked the two loglines bold 
Sadly i don't have an idea what i should change...
