### ISSUE TITLE
Item Delete Button deletes multiple items

### ISSUE THREAD

**Issue by FloFoer** [bwssytems/ha-bridge#705]
If i use the the item delete button on the editdevice screen it deletes multiple items instead of the one i pressed delete on if there are multiple items with the same item and type in the items list.   
This happens even if they are not consecutive in the list.  
Is this intentional?  

Maybe in the removeItemxxx methods in app.js it should better be:
`$scope.onDevices[i] === anItem`
instead of
`$scope.onDevices[i].item === anItem.item && $scope.onDevices[i].type === anItem.type`
in the loop over xxDevices to determine which one to delete?

**Comment by bwssytems** [comment]
Will take a look

**Comment by FloFoer** [comment]
I actually changed that in my code so it's included in my pull request regarding rooms/color.

**Comment by bwssytems** [comment]
Thanks!
