### ISSUE TITLE
doesn't work on first startup, always requires a re-start

### ISSUE THREAD

**Issue by Jinsterrrr** [bwssytems/ha-bridge#706]
I thought it's time to report this. I have been loading HA-bridge using a batch file with the command line

java -jar -Dserver.port=80 "c:\ha-bridge-4.5.6.jar" -Dconfig.file=c:\data\habridge.config

It appears to load but Echo isn't able to find any of the pre-defined devices. I will then close the cmd prompt and rerun the exact same batch file. And then everything would be fine.

This has been the case for at least the last 4 versions.

**Comment by bwssytems** [comment]
All "-D" arguments have to be before the jar file. It is ignoring your config file. It should be like this:

java -jar -Dserver.port=80 -Dconfig.file=c:\data\habridge.config "c:\ha-bridge-4.5.6.jar"

**Comment by Jinsterrrr** [comment]
You are a lifesaver! Keep up the good work. Issue resolved. My bad.
