### ISSUE TITLE
Google home suddenly not working any more with ha-bridge

### ISSUE THREAD

**Issue by wanaka1975** [bwssytems/ha-bridge#707]
It was working until yesterday suddenly google home has no control over ha-bridge device any more.  I have reset my google home and relink the ha-bridge but it doesn't seem to help.

i just want to confirm whether i am the only one facing this issue.

Google home still can control lifx and wemo but not ha-bridge any more.   I have tried my ha-bridge is working and I can perform test on and off.

Now if I ask google home to turn on and off my fibaro device, it will simply reply "i don't understand" or "power control is not available"

I

**Comment by wanaka1975** [comment]
the bridge version is 4.5.5 and my Hub is Fibaro HC2

**Comment by jratliff681** [comment]
I wondered if anyone else had that problem. But I assumed it was Google screwing something up because my tp-link smart plug connected directly to Google doesn't work either now.

**Comment by wanaka1975** [comment]
someone has complaint this issue in the following link.  
https://productforums.google.com/forum/?utm_medium=email&utm_source=footer#!msg/googlehome/uPKJ0PH36kI/OErsgABYBAAJ

**Comment by klingon888** [comment]
just tried and its working for me on 4.5.6.

**Comment by wanaka1975** [comment]
i have upgraded to 4.5.6 the result is the same.  In fact I notice all my wemo and lifx are not working at all if I have the philips hue linked.   I have to unlink then Wemo and lifx are working again.  It doesnt help either using google home 1.2.9 and perform are link of the hue

**Comment by danwooller** [comment]
I had a loss of functionality a couple of days ago. Fixed it by updating to the latest jar, deleting and re-adding all my entries.

HTH someone

**Comment by wanaka1975** [comment]
yesterday I have tried to relink and link couple of time.  i managed to be able to control the link but only a while (less than 4 sec) then i lost all control.   I will try reset tonight

**Comment by robertw** [comment]
I find out that by deleting the data folder and allowing it to create new files seems to resolve the issue but you're still unable to add an additional user once one link is established

**Comment by wanaka1975** [comment]
I seriously don't think this is a ha-bridge issue.   it is the communication between google home and habridge seem to be gone.   From the ha-bridge using the test on/off I was able to turn off and on my device without any issue.

**Comment by wanaka1975** [comment]
my problem resolved.  I delete the entire PI folder and setup from scratch.   No idea what is going on but everything work now.

**Comment by wanaka1975** [comment]
my happiness is only a short while again google home stop working with habridge

**Comment by bwssytems** [comment]
Hmm, maybe I'll need to have a reset whitelist as that controls the id's that are given to the items that link.

**Comment by jratliff681** [comment]
This spontaneously resolved for me, I figured Google changed something. I didn't change anything and it started working again a couple days ago. As was mentioned before though Google Home app won't add/discover devices from a second gmail account linked to the same Google home.

**Comment by wanaka1975** [comment]
yes for me i also noticed it must be some screw up by google because it was ok again

**Comment by SurajPadmasali** [comment]
I'm also facing the issue with my Google Home Mini When I tell my mini to "turn off", it replies with "sorry, power control is not supported". I've to turn off it manually. But [this solution](https://www.megebyte.com/google-home-mini-not-responding/) fixes this annoying problem.
