### ISSUE TITLE
Room Name with Domoticz

### ISSUE THREAD

**Issue by g1r1** [bwssytems/ha-bridge#709]
Is there a way to have or setup HA-Bridge to be used with and without Room Names in Domoticz with in a room context? For example:

When I am in Bedroom, I just want to be able to say "Light On"  instead of   "Bedroom Light On", which would also work.

Is this possible?

**Comment by tuicemen** [comment]
This would be a Domoticz Add/Request.
How would HA-Bridge know what room your  in?
If Domoticz knows where you are then a simple condition could be added to the Domoticz code so if your in that room then a command to turn on light was received it would turn on the light in that room.

**Comment by g1r1** [comment]
I was thinking something like 'Filter Address' option. As I understand that restricts the commands from specific Echo devices with IP addresses,  so, HA-Bridge can figure out the room. is the IP address of Echo device passed to Domoticz? then maybe that could be used as well. 

Just thinking aloud.

**Comment by tuicemen** [comment]
I haven't used or played with the Filter IPs option (yet)
https://github.com/bwssytems/ha-bridge/wiki/HA-Bridge-FAQs#q-how-does-the-new-filterips-work
Nor do I use Domoticz.
Perhaps someone Using the filter IP option can expand on this. 
The Filter IP option would only work if your other Alexa devices couldn't hear you. In my case most times that isn't possible.

**Comment by bwssytems** [comment]
The filter IP's do not work with Alexa Echo as they are hive minds. IF you use something else to call the ha-bridge that can be filtered that will work. I wish they would change this as it doesn't make ti very natural....
