### ISSUE TITLE
Update device change using bridgeupdatestate

### ISSUE THREAD

**Issue by cornholio1234** [bwssytems/ha-bridge#71]
Hi bwssystems,

many many thanks for the last update - works moreless perfect. Only little thing I cannot get working is changing the bool value for the on state. Am I too stupid or is there a little bug? Changing the bri parameter works:

curl -H "Content-Type: application/json" -X PUT -d "{ \"on\": false, \"bri\": 55 }" http://192.168.1.10:8088/api/user/lights/1272799582/bridgeupdatestate
[{"success":{"/lights/1272799582/state/on":true}},{"success":{"/lights/1272799582/state/bri":55}}]

curl -H "Content-Type: application/json" -X PUT -d "{ \"on\": false, \"bri\": 155 }" http://192.168.1.10:8088/api/user/lights/1272799582/bridgeupdatestate
[{"success":{"/lights/1272799582/state/on":true}},{"success":{"/lights/1272799582/state/bri":155}}]

As you see both commands return a success, but the on state stays true.

**Comment by bwssytems** [comment]
Ahh yes, if you are setting the bri value, my code assumed you were turning it on. Off, does not make sense with a bri value.

**Comment by cornholio1234** [comment]
makes sense, I'll update my scripts accordingly :-)

**Comment by bwssytems** [comment]
Glad it's working for you. Closing.
