### ISSUE TITLE
Moving hardware | Bridge control path wrong

### ISSUE THREAD

**Issue by xbmcnut** [bwssytems/ha-bridge#710]
Hi there,

Just tried moving 4.5.0 from my Pi3 to LibreELEC inside docker on a Odroid C2. Did _Bridge Device DB Backup_ and _Bridge Settings Backup_ and popped these into /storage/downloads/habridge/data on my Odroid. From there they could be restored and I have all of my _Bridge Settings_ and _Bridge Devices_ however; the information for _Configuration Path and File_, _Device DB Path_ and the _UPNP IP Address_ are all stuck from the previous hardware and do not want to update. Is there a workaround for that? Docker version is 4.5.6

**Comment by xbmcnut** [comment]
FYI, I manually edited those lines in the backup file, blew out the database and restored the modded backup file and the settings are now correct. Is there a better way?

**Comment by bwssytems** [comment]
Unfortunately, there is not. It is all about how the ha-bridge is started and the paths that are used for the data directory. Something has to tell the ha-bridge where they are if they are not relative to the start location of the ha-bridge.
