### ISSUE TITLE
[Switch PB]HA-Bridge + Domoticz + Logitech Harmony Elite

### ISSUE THREAD

**Issue by Xenderblade** [bwssytems/ha-bridge#716]
Hello !

I'm using HA-Bridge + Domoticz + Logitech Harmony Elite.

I've configured an ON/OFF wall switch for my bass speaker whose working great with domoticz
this switch show up correctly in my Ha-bridge but I have difficulty to make it turned OFF when I start an Harmony Activity.
ON is working on an another Harmony activity.

Domoticz Device :
![priseampli](https://user-images.githubusercontent.com/15358191/28869574-793e7a22-777d-11e7-8924-09e07ece71a2.PNG)

I have configured my switch to turn Off in the HA-bridge device in "On Items" but it's not working :
Name : Show TV
Device Type (Informational) : Activty
Map Type (Legacy) : Harmony Activity
ON Action:
Type : Hamony Activity
Target Item : {"name":"27464463","hub":"Harmony Elite"}
Type : Domoticz device
Target Item : http://192.168.1.27:8084/json.htm?type=command&param=switchlight&idx=163&switchcmd=Off
![regardertv](https://user-images.githubusercontent.com/15358191/28869573-793cb138-777d-11e7-8a22-a95c027adf89.PNG)

The one working have this configuration :
Name : Show TV + Amplifier
ON Action :
Type : Hamony Activity
Target Item : {"name":"27467760","hub":"Harmony Elite"}
Type : Domoticz device
Target Item : http://192.168.1.27:8084/json.htm?type=command&param=switchlight&idx=163&switchcmd=On
![regardertv ampli](https://user-images.githubusercontent.com/15358191/28869575-79402728-777d-11e7-8864-4ffb490c5491.PNG)

Please can you help me finding what I'm doing wrong?
Thanks

**Comment by bwssytems** [comment]
Did you use the domoticz helper to create this item?
