### ISSUE TITLE
Having to often repeat command

### ISSUE THREAD

**Issue by lemrock** [bwssytems/ha-bridge#717]
I think I've seen this issue before in the past.  I have to repeat a command before it actually gets executed.  I will say Alexa, Turn on TV..it'll say OK but then nothing happens.  If I say it again then it works.  This happens more often than not.  When I had this issue before I was running two HABridges and was told to kill one and that would solve my problem.  That didn't work.  Any ideas?

**Comment by tuicemen** [comment]
Since you were running two bridges did you go into your Alexa app and check for and  remove the extra TV and other devices  it maybe seeing?

**Comment by pickeld** [comment]
seems like this issue got forgotten #671

**Comment by lemrock** [comment]
@tuicemen ...I did go through and made sure Alexa "forgot" all the devices that were attached to the removed HABridge.  Those devices were marked in the Alexa app as "Offline".  I am running only single instances of my devices.

**Comment by bwssytems** [comment]
@pickeld The #671 is very specific to Home Assistant and the way it handles http requests. Currently, it is an issue on the HA side.

**Comment by bwssytems** [comment]
@lemrock So, you had devices show offline before you did a forget and discover?

**Comment by lemrock** [comment]
@bwssytems... Alexa app showed devices offline **after** I removed the second HABridge.  That made sense to me because they were removed with the HABridge.  Then I forgot all the offine devices and then discovered.  

Maybe this can help in troubleshooting.  The repeat of commands when it happens is with any device that "On-Dims-Off".  It doesn't seem to happen on "On-Off" devices.  Also If I say Alexa "Turn on Lights 100 percent" it works everytime,  but if I say Alexa "Turn on Lights"  it will most likely say OK but nothing happens until I say it again.

**Comment by bwssytems** [comment]
could you send me your device.db please

**Comment by tuicemen** [comment]
Try forget all then rediscover.
It is possible everything wasn't wiped on the amazon side of things or something got corrupt.

**Comment by lemrock** [comment]
@tuicemen ..I did forget everything and rediscovered and the problem was still there.

@bwssytems ...my device.db file is attached.
[device.db.txt](https://github.com/bwssytems/ha-bridge/files/1199017/device.db.txt)

**Comment by bwssytems** [comment]
So I assume you are trying to turn on "Living Room TV" and it is a harmony device. Does this happen with all Harmony devices? Does this happen with your Vera?

**Comment by lemrock** [comment]
None of my Harmony devices are affected by the issue I described.  I control Harmony through the Vera via Scenes and the Harmony Hub via the Alexa HArmony Skill. Devices that are affected are anything that has Dim control.  That is obviously lights and I have Vents that have position (Dim) control.  My shade shave a position (Dim) control but that function has never worked.

**Comment by bwssytems** [comment]
Well, that is more specific.

**Comment by bwssytems** [comment]
@lemrock What version are you running? Also, I see that your device.db has not been updated recently. Hit the renumber devices button on the config page and then have alexa forget and discover your devices.

**Comment by JJAZ** [comment]
I have a similar issue.
I use Homseer and with the bridge I notice if I have to reinitialize the bridge, it then takes 2 subsequent commands to turn on a light that has a dim capability. A way around this I have found is if I go to the bridge webpage and manually turn on the light, then click the dim setting button, the next command from alexa will then turn the light on and off appropriately. Something about the dim setting pop up window seems to hold up the process. Any of my harmony activities or lights that cannot dim work fine first try.

**Comment by lemrock** [comment]
@bwssytems ...I am running your version 4.5.6.  I also did what you suggested (renumber, forget, discover) and the issue is still there.  I see that JJAZ reported a similar issue (DIM devices).

**Comment by bwssytems** [comment]
You'll need to turn on debug for me https://github.com/bwssytems/ha-bridge#the-logs-tab and post your log.

**Comment by lemrock** [comment]
Turned on Debug for the Huemulator.  In this log you should see the issue I described for 2 devices Ceiling Lights 2 and Entryway Lights. Ask to turn on but doesn't, ask a second time and it does.  Problem only appears for devices that DIm.
[BridgeLog.docx](https://github.com/bwssytems/ha-bridge/files/1253688/BridgeLog.docx)

**Comment by bwssytems** [comment]
Well, ha-bridge is calling your vera without error for the 2 calls to each device that you are requesting. My only concern is that in the startup of your bridge, there is a network error for multicast upnp. That may be an issue of network setup with your machine you run the ha-bridge on.

**Comment by lemrock** [comment]
I'm running the habridge on a Raspberry Pi 2 and over wifi. Any suggestions about what I could look at and is there another DEBUG parameter I could turn on.

**Comment by bwssytems** [comment]
Unfortunately, it is not ha-bridge debug related. It is your Pi 2 network config. The issue is from an error when trying to reply to the multicast request. That may or may not have any effect on your issue.

**Comment by bwssytems** [comment]
Any update on this?

**Comment by lemrock** [comment]
No update.  I’ve done everything recommended but I still have to ask Alexa twice before any command is executed.  I’ve just decided to live with it. The clue i think to solve this is it only happens on devices with dim control.

**Comment by bwssytems** [comment]
Hopefully the new http handling in 5.0.0 will make this a non issue.
