### ISSUE TITLE
Duplicate devices, second set offline?

### ISSUE THREAD

**Issue by jswim788** [bwssytems/ha-bridge#719]
Running 4.5.6.  habridge works well for a period of time, then I get a second set of devices that are all marked (offline).  Only for the habridge - other items that Echo discovers don't have duplicates.  Problem is that Echo says "You have 2 devices with the same name, rename and re-discover".  If I have Echo forget all the devices and re-discover, only one set is there.  But after some period of time, the duplicates appear again.

Any thoughts?

**Comment by audiofreak9** [comment]
Try this, from the Bridge Devices tab click the Renumber Devices button, then forget your devices on the Alexa app, then rediscover your devices.

**Comment by jswim788** [comment]
No luck.  The second set were gone for a while, but today they are back again.  One set marked "(offline)" and the other are normal.  But Echo doesn't seem to mind right now.  If it follows past behavior, in a day or two, she will then say I have 2 devices with the same name again.

**Comment by tuicemen** [comment]
The device running the bridge is it set for a static IP?
It should be.

**Comment by jswim788** [comment]
Yes, static IP - set in the router.

**Comment by bwssytems** [comment]
@jswim788 Have you ever started the bridge on another port or computer and left it running by chance?

**Comment by bwssytems** [comment]
So, could you post your device.db to debug.

Thanks

**Comment by notoriousbdg** [comment]
I had a similar issue with Home Assistant.  What happened was Home Assistant was discovering HA Bridge devices and automatically adding them to Home Assistant, which ended up creating duplicate devices.  I had to disable Hue discovery in Home Assistant to get rid of the duplicates.

**Comment by pickeld** [comment]
does home assistant externalizes hue devices to google home? or just habridge does that?

**Comment by jswim788** [comment]
device.db is below.  These were originally created in the older 3.x version.  It would not be that hard to delete the whole database and recreate these if you think that might help.

[device.db.txt](https://github.com/bwssytems/ha-bridge/files/1219449/device.db.txt)

**Comment by bwssytems** [comment]
@jswim788 Your device.db is clean. It should not matter when the devices were created, I think. You can try to see if that helps and if so, I will have some digging to do.

**Comment by ahielg** [comment]
same here. I think it happens after I restart my PI...

**Comment by CrEaK** [comment]
Same here aswell

**Comment by bwssytems** [comment]
Ok, will need to see your habridge.conf files as this does not happen to my install. I will need to se more info.

**Comment by jswim788** [comment]
It's not 100% clear to me that duplicate devices the root cause of the problem although it may be contributing.  Alexa can say there is a duplicate device and not work, and then 10 minutes later, she works without a problem yet the duplicate devices are still there.  No reboot or anything else changed.  And stranger still, I've had Alexa start telling me that there is a duplicate device, then interrupt herself and say "Okay" and turn on the requested light.  Very strange.

**Comment by bwssytems** [comment]
@donmike73 Nothing out of the ordinary in your config when I reviewed it.

So, just to make sure that everyone is using static IPs for the host running the bridge. Also to test this theory, if you run discover on the echo multiple times without doing a forget do you get duplicates. And the last item is what version of the ha-bridge are you running

**Comment by wendy2702** [comment]
@bwssytems: Hi, i setup ha-bridge 2 days ago and created some activities today. Some of the new created activites were not working and i just deleted them from ha-bridge but if i remove them from Echo and did a discover all of them are visible twice.

Config files and how it looks at Echo attached.

Can somebody please help how to remove devices and double devices?
[device.zip](https://github.com/bwssytems/ha-bridge/files/1446551/device.zip)
[habridge.zip](https://github.com/bwssytems/ha-bridge/files/1446552/habridge.zip)
![echo devices](https://user-images.githubusercontent.com/33424168/32446524-736bb04c-c309-11e7-87da-339fcafef62b.jpg)

**Comment by CrEaK** [comment]
try to use the "Alle verwerfen" (no idea what the englisch text is) and after that rerun the discovery. Now the devices should only visible once.

**Comment by wendy2702** [comment]
Hi,
this i tried several times but after new discovery all devices are visible again.
Can it be that the problem is related to Amazon Echo service itself because i stopped ha-bridge, removed all devices via "verwerfen" and did a new discover... surprise all device came back again.

**Comment by wendy2702** [comment]
Yesterday evening i contacted Amazon about this issue that i'm not able to delete devices. Last night a answer from service was provided and if i tried it again today it 's working.

Maybe Amazon has done something.

**Comment by michaelhinchey** [comment]
Please keep us upto date









    Every dream is a goal with a date on it; if you can conceive it believe
it, you can achieve it. Don't let anyone steal your dream. Make the
decision to take a positive attitude, take pride in yourself and what you
do, work hard and stay with it. A mind is a terrible thing to waste.


"I felt bad because I couldn't wheelie; until I met a man with no bicycle"

"You are young at any age... if you are planning on tomorrow"

**Comment by bwssytems** [comment]
So, those that are still having an issue, we need to see the networking setup of the machine that runs the ha-bridge. If there are multiple paths that are configured on the machine, Alexa will think it is 2 different devices.

**Comment by jswim788** [comment]
I run habridge on a Raspberry Pi 3.  I have the eth0 set with a static IP.  I had Wifi enabled but not connected to anything (wlan0).  I've disabled wlan0 completely through /boot/config.txt and made sure that it is not seen by ifconfig.  I had Alexa forget all devices and then had her rediscover.  Currently I have no duplicates, but it often takes a day or so for the duplicates to appear.  I'll report back on what I see.

**Comment by jswim788** [comment]
After completely disabling the wlan0, the duplicate devices came back within a few hours and Alexa complained about multiple devices with the same name.  So I had Alexa forget all devices, powered off the Echo and the Dots (good name for a band!), rebooted the RPi, then powered them up and did the discovery.  It's been 24 hours and no duplicates, but it's not unusual to see it go this long without duplicates.  Need to wait a few more days to see if this really helps or not.

**Comment by jswim788** [comment]
FYI - the issue still persists.  It just takes some time to recur.  I may try to go back to a 3.5 version as I don't recall it happening there or just live with periodically removing all devices and re-discovering.  Irritating, but it limps along.

**Comment by cmptrblder** [comment]
Same issue here with the dupes, disabling emulated hue in the config file causes HA to not see any of the devices  or to be able to control them from HA but Alexa can without dupes.  Turning on emulated hue in the config makes the devices show & control in HA but doing this causes dupes in Alexa.

**Comment by bwssytems** [comment]
What I am hearing is you are having your alexa find the ha-bridge that is using pass through to your hue devices and you have alexa linked to the physical hue as well?

**Comment by cmptrblder** [comment]
No, I have no physical hue hub.  I have a Pi3 with a static IP running Home Assistant & HA Bridge. 

1.)  If I insert "ignore hue" into the config file of Home Assistant, the Items never show up in Home Assistant BUT Alexa can see them just fine and NEVER get duplicates in Alexa marked "offline".  Alexa at this point also sees a few things from Home Assistant as well,

2.) If I remove "ignore hue" from the config file, all items show up in Home Assistant but then the "offline" duplicates show up on Alexa.

**Comment by bwssytems** [comment]
Ok, got you. It is that you have 2 items representing to the Alexa as a Hue with the same names for the devices. You would have to pick one, HomeAssitant or the ha-bridge.

**Comment by cmptrblder** [comment]
I figured that was probably the issue (2 representations) I need HA Bridge to represent the devices to Home Assistant but is there a setting in HA Bridge to "check" or "select" so that Alexa wasn't hearing them but Home Assistant is?

**Comment by cmptrblder** [comment]
I'm also wondering if there is a setting in Home Assistant to keep Assistant from broadcasting devices.

**Comment by bwssytems** [comment]
Yes, there is, you can user the filter by ip address on each device. On the device when you edit it, use the "Filter Address (comma separated list)" to set the ip addresses that this device will respond to.

**Comment by cmptrblder** [comment]
So what I'm thinking your saying is I could enter the IP address of the Pi3 running Home Assistant and Alexa would not see the devices from HA Bridge unless I entered Alexas IP address as well?

**Comment by cmptrblder** [comment]
THANK YOU!  :)

**Comment by heikoh81** [comment]
Still an issue here with 5.2.0, no Home Assistant.
Alexa - after a random time - discoeres exactly double the number of devices.
The name is the same, one is declared as "Royal Philips Electronics intelligent device", the other as "dimmable light".

**Comment by cmptrblder** [comment]
I had this issue but what BWSSYSTEMS told me above, once I did that I have NEVER had the duplicate device issue in Alexa again.  In HA Bridge, go into each device and insert the IP of the Home Assistant device.  The duplicate is because Home Assistant AND Alexa BOTH are detecting the devices (creating duplicates), putting the IP in HA Bridge allows ONLY Home Assistant see them BUT will pass them on to Alexa.

**Comment by tuicemen** [comment]
@heikoh81 what other software or bridge are you using?
The answer doesn't just apply to Home Assistant.

**Comment by cmptrblder** [comment]
Besides HA Bridge, do you have any other hardware / emulated bridges on your network?  I'm using HA Bridge, Home Assistant, Emulated Hue and X10 Commander

**Comment by heikoh81** [comment]
No, there are no other Hue emulators whatsoever in my LAN.
I have a FHEM Master, but without any emulation. I use HABridge to perform HTTP-requests to my FHEM master.

**Comment by tuicemen** [comment]
Interestingly under supported protocols it lists Alexa. From this I would suspect Alexa is reading your devices in configured in Fhem as well as HA-Bridge if so the fix mentioned here will help

**Comment by heikoh81** [comment]
No, I can exclude this!
FHEM has complicated Alexa supported (with custom skill and port forwarding), but I have not activated it. That is why I use HABridge.
So FHEM cannot be the reason for double entries.

By the way, the double device names are exactly as named in my one and only HA Bridge installation. The names do not occur in FHEM. If I change the name in HABridge, it will change in Alexa.

**Comment by pankratz** [comment]
Hi,
exact same problem here. On my Pi3 only mosquitto and ha-bridge are running. No Wifi connection. Fixed LAN IP. No further Hue device (emulation) in my network.
I have 4 Echos and 2 Echo dots.
HA-Bridge devices are recognized well and everything is fine as "dimmable light".
But after some time (hours/days) all devices appear duplicated as "Royal Philips Electronics intelligent device" and Alexa responds about duplicated names...
