### ISSUE TITLE
Question: In addition to bri, could xy (maybe ct as well) be added as well?

### ISSUE THREAD

**Issue by quenthal** [bwssytems/ha-bridge#72]
I would like to control color changing lamps as well using ha-bridge.

One thing this would also give to users as a side effect is handling multiple Hue Hubs (real or emulated) as one with all capabilities. For example Harmony can handle only one Hue Hub. 

Also, as a additional question: can scenes somehow be handled?

**Comment by bwssytems** [comment]
Let me look into that. We could put that into a different variable. Didn't know people were using the bridge to pass through to a real HUE Bridge, does that work well?

**Comment by quenthal** [comment]
For Harmony usage, relatively well. Have just started to fiddle with other Hue -apps with this passthru -idea.

**Comment by bwssytems** [comment]
So, how do you get a real HUE bridge to recognize the ha-bridge? It needs to do user send, which the ha-bridge does not do to the real HUE bridge for it to work based on the API doc.

**Comment by quenthal** [comment]
I just HTTP PUT commands to real hub. What would be great if I could catch xy, ct, hue and sat as well, so I could pass them thru to real hub as well :)

**Comment by quenthal** [comment]
Naturally if I could get the body data, and simply redirect it to to real hub (i.e. just changing some headers ha-bridge receives to real hub's same information, it could be even more efficient). Then I could configure some of my lights simply to be redirected, and for the rest of my non-hue lights and devices use the current capability of ha-bridge

**Comment by bwssytems** [comment]
This sounds like a good request. Now it will be an enhancement.

**Comment by bwssytems** [comment]
So, more questions. Currently I have the bulb type returned as a Lux which is not color. When reading the API docs, there are many bulbs that have crossections of the different attributes and how many settings need to be passed. Also, is state needed for color on the Harmony Hub?

**Comment by quenthal** [comment]
I assume Hue (not Lux) support ct. xy. hue and sat. They are partially overlapping, for example one can set the same color to Hue using xy as well as using hue/sat.

When setting color, Harmony seems to be forwarding only ct (when changing warm/cool -setting) or xy (when changing color). I also tried some apps on my phone, they usually don't touch ct or xy, and change the color using hue and/or sat -parameters.

State for color is not needed for Harmony, but for complete support for apps this might be needed. I have tried this out with modifying hue-upnp (python), but bridge emulation and other options are lacking a lot compared to your ha-bridge.

**Comment by quenthal** [comment]
What would be intresting, more than passing parameters, atleast for Hue usage, would be passing thru the complete body -parts to real hue hub. One would configure real hue hub, and when (known or even unknown command) is given from any controller/app etc., it would send it to there.

**Comment by bwssytems** [comment]
So, I think what I will be implementing is a subsytem, like the harmony, where it will find your hue systems and allow you to select the bulbs to be handled by the bridge and it will pass on the full state vars in a set state call.

**Comment by dmoos777** [comment]
Can you ask the Amazon echo to change hue and sat and stuff, if so, what are the actual voice commands.

**Comment by bwssytems** [comment]
I am not sure if you can. For now I am implementing a passthru to real hue lights with this enhancement
