### ISSUE TITLE
Long time no operation causes failure of the first operation of home assistant devices

### ISSUE THREAD

**Issue by shuaiger** [bwssytems/ha-bridge#722]
After quite a while without any operation, when clicking the TEST_ON or TEST_OFF button on the devices page, the first click would not succeed, also not controllable by smart speaker.

Maybe habridge should send keep alive packages to HomeAssistant API to maintain connection.

HaBridge version 4.5.6, running on ubuntu 16.10, with java version 1.8.0_131.

Hope to fix it soon. Thanks.

**Comment by tryingwebguy** [comment]
I'm a new ha-bridge user.

This issue seems to be the same as `https://github.com/bwssytems/ha-bridge/issues/671`

Which user @kmdm has posted a "fix" i am yet to try. (Last comment contain his fix download link)

**Comment by shuaiger** [comment]
thanks to @tryingwebguy and @kmdm, it seems that the problem was solved by using the `fixed jar`. let me try after a long time to see if it still works.

**Comment by tryingwebguy** [comment]
Solved it for me initially but it seams I'm now back at square 1

**Comment by shuaiger** [comment]
I've tested several times and it worked like a charm.

**Comment by tryingwebguy** [comment]
Which version of Home Assistant are you using? I'm now on 0.51.1 maybe this is causing it..

**Comment by kmdm** [comment]
@tryingwebguy I have 0.51.1 - working fine for me.

**Comment by tryingwebguy** [comment]
Looks like restarting my docker container after replacing the jar file was resorting it back to the original. Just replaced the file and re-initialised within ha-bridge and I'm so far so good. Thanks for the fix @kmdm

**Comment by shuaiger** [comment]
@tryingwebguy I ran habridge on ubuntu, just placed the fix file there and enabled auto starting, no renaming needed. btw i saw you have solved this. cong.

**Comment by bwssytems** [comment]
Fixing with #671
