### ISSUE TITLE
Lock/Unlock, open/close feature?

### ISSUE THREAD

**Issue by dannieboiz** [bwssytems/ha-bridge#723]
Does HA Bridge support lock/unlock and open/close for garage and doors?

**Comment by tuicemen** [comment]
I guess it would depend on the manufacture and the protocol used to communicate to the door.

**Comment by bwssytems** [comment]
If you are referring to what Alexa can tell the ha-bridge, it is only on and off. Those words are reserved and not used with the Philips Hue interface from amazon.
