### ISSUE TITLE
Is it possible to support the HUE sensor API to get things like temperature?

### ISSUE THREAD

**Issue by srchacker** [bwssytems/ha-bridge#724]
Looking at the HUE API, it looks like it should be possible to do a ZLL Temperature -> vera request so that alexa's "what's the temperature in here?" command would work.      Is there some fundamental problem with this?  I'm not too familiar of how alexa interfaces with the hue interface so not sure if  if trying this is worthwhile.  Any advice?  Thanks in advance.

**Comment by Rob78** [comment]
I believe this question has been asked before. Unfortunately I don't think it is possible
#721  read temperature

**Comment by bwssytems** [comment]
Only if amazon will support that call on the local Hue API call. If it does not, then it will not work.

**Comment by bwssytems** [comment]
Closing since this is not an available feature from Amazon.
