### ISSUE TITLE
Repeated Error

### ISSUE THREAD

**Issue by JJAZ** [bwssytems/ha-bridge#725]
Hello,
I keep getting this error over and over:

2017-08-18 18:42:01,313 [main] WARN  com.bwssystems.HABridge.upnp.UpnpListener - UpnpListener encountered an error sending upnp notify packet. IP: 239.255.255.250 with message: No route to host: Datagram send failed

Any ideas? My router has upnp open.

HA bridge 4.5.6 running on Win10 Pro 64
All of my other IoT devices have no issues connecting outside my router/ISP.
Thanks

**Comment by Rob78** [comment]
Hi,
is this for an on fiction or off and also what you trying to control

**Comment by JJAZ** [comment]
Neither. As the bridge sits there waiting for a command, the error repeats over and over. 

As I issue a command, it will eventually fire as normal. However, I use Alexa and sometimes it takes a bit of time to get through, and sometimes Alexa says "I don't know what went wrong" but still issues the command correctly. 

I have renumberd the devices and re-discovered them, but it still happens randomly. It seems unrelated to the above error, unless the repetitive firing is what is the cause of the delay in response.

My setup is using the bridge to control lights through Homeseer and AV activities through a Harmony Hub.

**Comment by Rob78** [comment]
can you post a debug log

**Comment by JJAZ** [comment]
See if this looks ok.
[DEBUG 8-20.pdf](https://github.com/bwssytems/ha-bridge/files/1237320/DEBUG.8-20.pdf)

**Comment by Rob78** [comment]
mmm interesting.   What is this IP address for? 239.255.255.250 is outside of your local subnet 192.168.1.0

**Comment by Rob78** [comment]
what the warning says is that it is unable to find a route to 239.255.255.250. It seems to be some sort of multicast IP address. Is there a multicast option in your router

**Comment by JJAZ** [comment]
That was my thought too. I went into the router and shut down any site filtering and threat blocking ticks other than the general firewall. I will watch this evening to see if the error calms down.

**Comment by JJAZ** [comment]
Ok to update this error. 
It seems that in fact it was the router that was blocking the upnp update process.

For those in the future, here was the problem:

I have an ASUS RT-AC1900 Router.
Under the AIProtection tab, click on Network Protection and make sure Malicious Sites Blocking is turned off. 

Thanks for the input. Will close now.
