### ISSUE TITLE
What user does it run as?

### ISSUE THREAD

**Issue by Rob78** [bwssytems/ha-bridge#726]
I am trying to run a script when I call the on funtion. Alexa Turn on Kimberly's Voicemail.  or Alexa turn on Sam's Voicemail.

Our phone system is asterisk. I have a script in the asterisk phone system to change who the voicemail goes to for the weekend. voicemail.kim.sh and voicemail.sam.sh
An ubuntu system has the ha-bridge. I created a script that uses sshpass to ssh into asterisk and launch the script to change voicemail.

The script works well from ubuntu but not from ha-bridge. I think the problem is the user ha-bridge is running as. Maybe I am being asked for sudo privileges but I dont know under what user is ha-bridge running. Other scripts are running fine "Alexa turn on the office" which is a script that uses wakeonlan to turn on the computers. I'm guessing wakeonlan does not require sudo but sshpass does.

**Comment by bwssytems** [comment]
It depends on how you start your ha-bridge. If you use one of the automatic startup configurations, it would be as root. IF you start from the command line yourself, it is the user you are logged in as.

**Comment by Rob78** [comment]
Ok. It is running on automatic startup configuration. So if it is running as root any ideas why my script wont execute from ha-bridge.  I can execute other scripts but the script using sshpass to login to my phone system does not work =( Any ideas?

**Comment by bwssytems** [comment]
Do you qualify the entire path to your shell script? Also, the script may not be running in a shell environment and needs to have 'sh' or 'bash' in front of the statement. These too will need to be fully qualified paths.

**Comment by bwssytems** [comment]
Any issues with this still?
