### ISSUE TITLE
Illegal Character in HTTP Body Arguments

### ISSUE THREAD

**Issue by VsmileV** [bwssytems/ha-bridge#73]
I am able to have Echo find the Device. (BTW - Great job on the HA-Bridge)

I am having a problem with the HTTP Body Arguments for onUrl and offUrl.  I have tried adding the device using the GUI and with I'm Only Resting and get the same issue <See Log>

 at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.URISyntaxException: Illegal character in path at index 44: http://localhost:33335/api/VC.TellVox&&Power on
        at java.net.URI$Parser.fail(URI.java:2848)
        at java.net.URI$Parser.checkChars(URI.java:3021)
        at java.net.URI$Parser.parseHierarchical(URI.java:3105)
        at java.net.URI$Parser.parse(URI.java:3053)
        at java.net.URI.<init>(URI.java:588)
        at java.net.URI.create(URI.java:850)

The Device is

[{"id":"317998676","name":"Box","deviceType":"switch","offUrl":"http://localhost:33335/api/VC.TellVox\u0026\u0026Power off","onUrl":"http://localhost:33335/api/VC.TellVox\u0026\u0026Power on","deviceState":false,"deviceSetValue":0},

I am guessing the problem is the && in the onUrl and offUrl arguments.("http://localhost:33335/api/VC.TellVox&&Power off")

Manually testing HTTP strings does indeed control the target device (both on and off) correctly so I know the syntax is correct.

Any suggestions how to deal with '&&' in the argument?

**Comment by audiofreak9** [comment]
@VsmileV I don't know if the double ampersand is causing the issues, they were both successfully converted to java source code value "\u0026".  I wonder of the space in both "Power off" and "Power on" is the problem?  The space was not converted, space is: "\u0020"

**Comment by bwssytems** [comment]
@VsmileV Did audiofreak9's suggestion solve your issues? I concur that should be the solution.

**Comment by VsmileV** [comment]
The space is indeed the problem. 

Interesting the GUI or the I'M at Rest app would not convert the space in the HTTP syntax. I tried entering the 'space' code manually  using a modified text editor but that didn't work.

I had some flexibility to adjust the syntax on the target device. Once I changed it to a single word,  everything worked perfectly.  Thanks for the tip audiofreak9

**Comment by bwssytems** [comment]
Something I may need to consider is assuming that anything typed in is what the user wants to send even thought it is not in a http url spec. This will be an enhancement.

**Comment by audiofreak9** [comment]
Yeah, that's a tough one, funny how other applications will allow incorrect http syntax.

**Comment by VsmileV** [comment]
Thanks for the help. I will be testing more over the summer.

**Comment by bwssytems** [comment]
So the best we will get is the checks when the http request gets created. The space is not valid at anytime.
