### ISSUE TITLE
Echo can't discover HA bridge

### ISSUE THREAD

**Issue by ckhyatt** [bwssytems/ha-bridge#730]
My bridge has been working great for a couple of years. I am on the current version--4.5.6. I have attached the log with UPNP trace enabled. There are no errors in the log. I noticed in the Alexa app that several devices were listed as offline, even though they appeared to be working. Just SOP I forgot the devices and ran discovery again. The Echo will not discover the the bridge now! I have gone through all the web searches I can find. I have enabled UPNP on my router. I am using a UPNP analyzer and I can see both my Echo and Echo dot send an 

M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover" 
MX: 15
ST: urn: Belkin: device: **

I can see the bridge announce NOTIFY * HTTP/1.1
HOST: 239.255.255.250:1900
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.2.136:8080/description.xml
SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.19.0
NTS: ssdp:alive
hue-bridgeid: B827EBFFFEA5A70B
NT: uuid:2f402f80-da50-11e1-9b23-b827eba5a70b
USN: uuid:2f402f80-da50-11e1-9b23-b827eba5a70b.

The attached log does not appear to show the bridge responding to the Echo/Dot's M-SEARCH.

Both the Echo devices and the bridge are on the same subnet and the same subnet as the UPNP analyzer. 

The bridge controls the Vera devices and scenes with no issue. It is only discovery that is failing.

I have spent several hours troubleshooting this and reached a dead end. Any help would be greatly appreciated.

Just to be clear, I was able to control the Vera devices through Echo/Dot prior to forgetting them and attempting discovery. I am stumped why discovery is failing.

Thanks!
[habridge.log.zip](https://github.com/bwssytems/ha-bridge/files/1242494/habridge.log.zip)

**Comment by bwssytems** [comment]
From your log, the device, 192.168.2.159, is the only one requesting information. What is this device?

**Comment by ckhyatt** [comment]
It is a NVR.

**Comment by ckhyatt** [comment]
I FINALLY figured it out. There is a switch in the middle with IGMP
Snooping enabled by default. I disabled it and everything works correctly!
Amazingly, the clue to the solution was an brief note in the Wiki entry for
UPNP. Please close issue.

Thanks!

**Comment by ckhyatt** [comment]
From the Wiki:

IGMP snooping and reliability[edit
<https://en.wikipedia.org/w/index.php?title=Universal_Plug_and_Play&action=edit&section=17>
]

UPnP is often the only significant multicast application in use in digital
home networks; therefore, multicast network misconfiguration or other
deficiencies can appear as UPnP issues rather than underlying network
issues.

If IGMP snooping is enabled on a switch, or more commonly a wireless
router/switch, it will interfere with UPnP/DLNA device discovery (SSDP) if
incorrectly or incompletely configured (e.g. without an active querier or
IGMP proxy), making UPnP appear unreliable.

**Comment by bwssytems** [comment]
Thanks! That is a treasure of a piece of information. Will put it in the wiki.

**Comment by ckhyatt** [comment]
Hopefully that will help someone else :)

Thanks!

Craig
