### ISSUE TITLE
HTTP command Error on calling url to change device state

### ISSUE THREAD

**Issue by Gutfarah** [bwssytems/ha-bridge#732]
Hi, 
Thanks for the great work. I have been trying to integrate my Air con system with this HA-Bridge with no luck as yet. the HTTP command to set the temp is : 

http://192.168.0.32:2025/setAircon?json={"ac1":{"info":{"order":0},"zones":{"z08":{"number":8,"setTemp":18}}}}

This sets the temp to 18 degrees and works from the browser, but does not work in the HA-Bridge Device. 

Any suggestions would be much appreciated . 

Cheers

![2017-08-24](https://user-images.githubusercontent.com/31308187/29665764-f29ea9bc-8918-11e7-8d3a-7816cccdc7ac.png)

**Comment by bwssytems** [comment]
Yes, I do have a suggestion. You will need to escape the json string with quotes using ```\"```

**Comment by Gutfarah** [comment]
Hi, 

Many thanks for the fast reply, I did that with no luck , I also escaped them as below with no luck :

http://192.168.0.32:2025/setAircon?json={%22ac1%22:{%22info%22:{%22order%22:0},%22zones%22:{%22z08%22:{%22number%22:8,%22setTemp%22:18}}}}

**Comment by Twit123** [comment]
Have you tried \\" - I thought you needed this to escape a double quote mark. I'm just guessing though.

http://192.168.0.32:2025/setAircon?json={\\"ac1\\":{\\"info\\":{\\"order\\":0},\\"zones\\":{\\"z08\\":{\\"number\\":8,\\"setTemp\\":18}}}}

**Comment by Gutfarah** [comment]
thanks, yes an still the same error message : 

Error on calling url to change device state: http://192.168.0.32:2025/setAircon?json={\\"ac1\\":{\\"info\\":{\\"order\\":0},\\"zones\\":{\\"z08\\":{\\"number\\":8,\\"setTemp\\":18}}}}

**Comment by Gutfarah** [comment]
I have a vera and all these work in its http command, just cant find a away to fix it here :(

**Comment by bwssytems** [comment]
Turn on debug as described here https://github.com/bwssytems/ha-bridge#the-logs-tab

It has a decoder output that will show what may be the problem in escaping

**Comment by Gutfarah** [comment]
Thanks bwssytems, problem solved, the issue was { and } , I changed them to %7B and %7D , now everything works beautifully. 

the working url is : 

http://192.168.0.32:2025/setAircon?json=%7B%22ac1%22:%7B%22info%22:%7B%22order%22:0%7D,%22zones%22:%7B%22z08%22:%7B%22number%22:8,%22setTemp%22:${intensity.percent}%7D%7D%7D%7D

I use the dimmer to set the temp.
