### ISSUE TITLE
Status of devices

### ISSUE THREAD

**Issue by orctrial** [bwssytems/ha-bridge#733]
Hi,

is there a way to get status of a device? I have several light switches and sensors and would like to see if i can ask Alexa fr status of the device. I am using http and the On and off is working great. for example

"on_url": "http://192.168.1.30:8688/controller/rest/control/877/ON" ---- > working OK
"off_url": "http://192.168.1.30:8688/controller/rest/control/877/OFF",---- > working - OK
"status_url": "http://192.168.1.30:8688/controller/rest/status/408982"-----> This is the URL for getting current status of the device. Is there any way i can use this with ha-bridge and Alexa?

**Comment by NovaGL** [comment]
Doesn't work for me. I use Node-Red and that can do what you want. There is an Alexa plugin for it which works really well

**Comment by orctrial** [comment]
Thanks I started looking in to node red. By any chance if you have implemented this scenario would be provide more details on your flow/logic?

**Comment by NovaGL** [comment]
You can't actually ask for a light level but if you do plus +1 it will use the direct api so t should work.

Looks like you are using OpenRemote. You can do the commands direct in Node-Red without using OpenRemote.

Here is the simplest one
https://alexa-node-red.bm.hardill.me.uk/#

If you look at my DIY repos they are the ones that deal with Alexa and Google Home

**Comment by orctrial** [comment]
Thanks for the hints. I have homebridge with the Openremote plugin (for Siri) and ha-bridge( for Alexa) both setup and running. As I see it, the constraint with homebridge is it only supports on / off. So if I am using it with a door sensor that returns open / closed it does not recognize it. Even if I use on /off for door sensors as retired values, what I have noticed is it these is a significant delay between the communication from the HomeKit support app like Home or Devices and the homebridge. So on the homebridge terminal console I see the status update message come in immediately but it does not get updated on Home till I restart the app after which it immediately shows the correct status. Lights and switches seem to work just fine with immediate status updates but door sensors don't. 

With ha-bridge , I can't get status updates- if I ask "what is the status of table lamp" it says this function is not supported. 

Hence I was looking for some other alternate platform. Node-red with Alexa plugin still does not seem to have support for status- I created account etc but after adding the device it only seems to give option for on /off and some temperature values ( I am assuming it is for thermostat). I will poke around a little more on node-red plugin to see if there is a way.

Let me know your thoughts.

**Comment by NovaGL** [comment]
I would go one step forward. You can either nodered homebridge flow or you can store everything in MQTT and use the homebridge plugin MQTT to Homebridge.

You can do much more than just on and off. I made my own motion sensors for Homebridge.

Will try tonight asking the status of a light, but mine are currently setup in Habridge.

You can also make a custom skill and then it does whatever you want but then you have to do Ask ...

**Comment by bwssytems** [comment]
@orctrial For the Alexa and Hue integration, status is not supported by Amazon. You would need to use another avenue that @NovaGL has specified.
