### ISSUE TITLE
Echo limit with HA Bridge: 70-75 devices?

### ISSUE THREAD

**Issue by heikoh81** [bwssytems/ha-bridge#736]
Hi,

my HABridge 4.5.6 installaton grew to 84 devices (not physical devices, but commands issued to FHEM).
I noticed a huge decrease of voice recognition by Echo when hitting 70-75 devices.
A lot of commands were not recognized anymore
On "Alexa, find my devices", the answer was "no devices found", although the Alexa App shows all devices including the new ones.

I found a solution by running 2 instances of HABridge on the same raspi (Web-Port 81/82, UPnP-Port 50001/50002. Instance 1 now has 44 devices, instance 2 has 40 devices.

Anyone else experiences this problem?

Greetings, Heiko

**Comment by rafale77** [comment]
I am running 74 devices and all are published correctly to the Echo. I am also not observing commands not being recognized although I have indeed seen the "no new device found" on the Alexa app in spite of having new devices reported and added correctly. If I was to run 2 instances, I would run them on different IP addresses using a VM.
