### ISSUE TITLE
2 HA-Bridge instances: UpnpListener encountered an error sending upnp notify packet. IP: 239.255.255.250 with message: Operation not permitted

### ISSUE THREAD

**Issue by heikoh81** [bwssytems/ha-bridge#737]
Hi,

as stated in issue #736, I need to run 2 HA-Bridge instances on the same Raspi2.
However, upon doing so, I now get my log flooded with this message that I didn't have before:

`UpnpListener encountered an error sending upnp notify packet. IP: 239.255.255.250 with message: Operation not permitted`

I use 2 different home-dirs, thus running 2 different config files, 1 for each instance.
My further settings are:

- Raspi2, Raspian Jessie, HA-Bridge 4.5.6
- Use UPNP Address Interface Only = FALSE
- UPNP Strict Handling = FALSE
- Port for Webinterface, instance 1: 81
- UPNP-Port, instance 1: 50001
- Port for Webinterface, instance 2: 82
- UPNP-Port, instance 2: 50002
- local IP adress of my Raspi: 192.168.178.220

Thanks for your help.
Heiko

**Comment by bwssytems** [comment]
Will take a look as that should not happen.

**Comment by heikoh81** [comment]
Thanks! I really hope you can fix this!

I tried some other things today - not successful though.

- I bound a 2nd IP-Address to my Raspi, assigning the new IP to the 2nd instance. Error still occurs.
- I added 2 iptables rules. Error still occurs
`iptables -I INPUT -p ALL -s 239.255.255.250/24 -j ACCEPT
iptables -I OUTPUT -p ALL -d 239.255.255.250/24 -j ACCEPT`

As soon as I stop one of the two instances, the error message stops!

**Comment by heikoh81** [comment]
Despite the error messages in the log, I now have 3 instances running (24/32/31 devices).
If I put all of these devides into 1 habridge, Alexa completely messes up recognizing any voice commands.
Just right now  I tried adding a 4th instance, however, now Alexa also messes completely up.
A random small number of devices of any of the 4 virtual bridges is now not found by device discovery.
Any idea why that is happening?

**Comment by bwssytems** [comment]
I have updated the upnp socket implementation to be on only one socket for the multicast responses.
