### ISSUE TITLE
Edit configuration or a backup file as script 

### ISSUE THREAD

**Issue by DeetAus** [bwssytems/ha-bridge#739]
I am using the HA bridge to send a TCP command into a control device.
 basically its the same string for every command except one integer changes

Is there a way to use a text editor to create the HA-Bridge configuration, It would be so much faster to copy/paste a bunch of lines and then simply change that one integer 

BTW that integer could simply be the device number. 

All I am trying to do is map a command word (Living Light) to an integer

**Comment by bwssytems** [comment]
Yes, the device.db is just text file with json strings in it. The only thing that is encrypted is the security items.

**Comment by DeetAus** [comment]
Thanks

dumb question, what folder is it in on a RaspPi install?

**Comment by bwssytems** [comment]
Depending on how you start your ha-bridge, if you use a specific location in your config it will be there, other wise it is relative to the starting user and directory under data/.
