### ISSUE TITLE
Discovery issues

### ISSUE THREAD

**Issue by mph070770** [bwssytems/ha-bridge#74]
Hi. I'm having the same issue as mtitus83 and #67. I've attached my log:

[results.log.txt](https://github.com/bwssytems/ha-bridge/files/189392/results.log.txt)

Discovery did work when I first installed the SW but the next day it had stopped working and I can't determine why. I'm using default bridge settings and only have 1 device set up. 

Any ideas? (my echo is on 192.168.0.80 and the bridge is 192.168.0.4).

**Comment by bwssytems** [comment]
So, is 192.168.0.80 your echo? Also, do you have upnp enabled on your router. If you turn that off there will be less interference from the router. Other wise, forget all the devices on the echo. Unplug it, wait the requisite 10 seconds , power it on again and then do a re-discover.

**Comment by mph070770** [comment]
Yes, 80 is my echo. I've managed to get discovery to work by closing the bridge using the webpage button and then restarting from the command line. Perhaps killing at the command line (which I had done previously when debugging) is closing down the bridge in an unclean way?

**Comment by bwssytems** [comment]
Restarting in anyway would be ok. It doesn't matter if which way you do that. Maybe on restart, a new setting was picked up?

**Comment by bwssytems** [comment]
Since this is working, closing issue.
