### ISSUE TITLE
Adding Hue device to multi-command breaks Alexa discovery

### ISSUE THREAD

**Issue by leyton01** [bwssytems/ha-bridge#740]
Had some issues with  alexa discovering devices on a new setup and after resetting everything I have managed to identify and recreate the issue.

When adding a hue device to a multi-comment in anything but FIRST place I get errors "ERROR |   | spark.webserver.MatcherFilter" and Alexa cannot see ANY devices (discovery fails for everything, not just the new multi-command).

eg Add Harmony activity then add hue device to multi-command and the errors occur and no discovery
Adding hue device first and then same harmony activity and the multi-command can be discovered in alexa

**Comment by leyton01** [comment]
I think this is not the correct use of the multi-command (see issue #738 ) and it is trying to set up both a passthru device and a normal device in the multi-command and that is what is breaking.  Although I am not using it correctly I think it could probably error more gracefully than killing discovery or stop noobs like myself breaking stuff?

**Comment by bwssytems** [comment]
Will look into that

**Comment by bwssytems** [comment]
I believe I know the issue that occurred for you. You need to sync your hue passthru first with a command (add a hue passthru device and test it) before using any device in a command

**Comment by bwssytems** [comment]
Any update on this?
