### ISSUE TITLE
Athom Homey doesnt see HA Bridge

### ISSUE THREAD

**Issue by xAPPO** [bwssytems/ha-bridge#742]
The Athom Homey controller does not discover the HA Bridge.
They are not using the cloud API,  they discover and use local bridges (and that works fine).  They are using the Node.js HueJay v1.7 library in their driver - and their complete driver code is available here.

https://github.com/athombv/nl.philips.hue
https://github.com/athombv/nl.philips.hue/tree/master/node_modules/huejay
They try both nupnp and upnp in their implementation and watching the debug output it doesn't find the bridge. 

Any ideas ?

**Comment by xAPPO** [comment]
Just a couple of extra log snippets that might help ?
----------------------------------------------------------------------------
Discovered 1 nupnp bridges
[log] Found bridge 001788fffe239521 @ 192.168.1.226
[log] [Bridge][001788fffe239521] init
[log] [Bridge][001788fffe239521] No keys found
[error] [Bridge][001788fffe239521] Error: no_token
    at _client.bridge.get.then (/lib/Bridge.js:80:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
----------------------------------------------------------------------------
[log] [DriverBulb] Skipping bridge due to undefined modelId Bridge {
  domain: null,
  _events:
   { log: [Function: bound log],
     error: [Function: bound error],
     bridge_available: [Function] },
  _eventsCount: 3,
  _maxListeners: 0,
  _debug: true,
  id: '001788fffe239521',
  address: '192.168.1.226',
  name: undefined,
  modelId: undefined,
  modelName: undefined,
  icon: undefined,
  _lights: {},
  _client:
   Client {
     config:
      { host: '192.168.1.226',
        port: 80,
        username: undefined,
        timeout: 15000 },
     accessors: { Bridge: [Object] },
     transport: Transport { client: [Circular] } },
  _token: undefined }
[log] Discovered 1 nupnp bridges
----------------------------------------------------------------------------

**Comment by bwssytems** [comment]
So, nupnp is Philips Hue cloud connect system. The ha-bridge is not part of that and is only available through the local network upnp.

**Comment by xAPPO** [comment]
It's trying upnp too though. It finds the Philips hub with no WAN access and works OK

**Comment by bwssytems** [comment]
Disable your philips hue hub and try it....
