### ISSUE TITLE
HA-Brigde is dicovered but no connection is established

### ISSUE THREAD

**Issue by Wolbolar** [bwssytems/ha-bridge#744]
I'm trying to use HA-Bridge (4.5.6), the app iConnectHue can find the HA-Bridge when the option add another base in the app is pressed, but then the status is hanging with the message connecting and then nothing more is happening. The devices in the HA-Bridge are working, when tested via the test buttons. The only problem is, that is is not possible to establish a connection to the HA-Bridge. I have tried also UPNP Strict Handling disabled but that makes no difference.

**Comment by bwssytems** [comment]
Turn on trace upnp in the settings and post the log file.

**Comment by Wolbolar** [comment]
Time | Level | Message | Component
-- | -- | -- | --
09-12-2017 21:08:21.650 | INFO | Traceupnp: isSSDPDiscovery found message to be valid under loose rules - strict: false | com.bwssystems.HABridge.upnp.UpnpListener
09-12-2017 21:08:21.650 | INFO | Traceupnp: SSDP packet from 192.168.55.10:61985, body: M-SEARCH * HTTP/1.1  MX: 1  ST: upnp:rootdevice  MAN: "ssdp:discover"  User-Agent: UPnP/1.0 DLNADOC/1.50 Platinum/1.0.5.13  Host: 239.255.255.250:1900  Connection: close | com.bwssystems.HABridge.upnp.UpnpListener
09-12-2017 21:08:21.651 | INFO | Traceupnp: sendUpnpResponse discovery responseTemplate1 is <<<HTTP/1.1 200 OK  HOST: 239.255.255.250:1900  CACHE-CONTROL: max-age=100  EXT:  LOCATION: http://192.168.55.71:81/description.xml  SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.19.0  hue-bridgeid: B827EBFFFED11E18  ST: upnp:rootdevice  USN: uuid:2f402f80-da50-11e1-9b23-b827ebd11e18::upnp:rootdevice    >>> | com.bwssystems.HABridge.upnp.UpnpListener
09-12-2017 21:08:21.651 | INFO | Traceupnp: sendUpnpResponse discovery responseTemplate2 is <<<HTTP/1.1 200 OK  HOST: 239.255.255.250:1900  CACHE-CONTROL: max-age=100  EXT:  LOCATION: http://192.168.55.71:81/description.xml  SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.19.0  hue-bridgeid: B827EBFFFED11E18  ST: uuid:2f402f80-da50-11e1-9b23-b827ebd11e18  USN: uuid:2f402f80-da50-11e1-9b23-b827ebd11e18    >>> | com.bwssystems.HABridge.upnp.UpnpListener
09-12-2017 21:08:21.652 | INFO | Traceupnp: sendUpnpResponse discovery responseTemplate3 is <<<HTTP/1.1 200 OK  HOST: 239.255.255.250:1900  CACHE-CONTROL: max-age=100  EXT:  LOCATION: http://192.168.55.71:81/description.xml  SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.19.0  hue-bridgeid: B827EBFFFED11E18  ST: urn:schemas-upnp-org:device:basic:1  USN: uuid:2f402f80-da50-11e1-9b23-b827ebd11e18    >>> | com.bwssystems.HABridge.upnp.UpnpListener
09-12-2017 21:08:21.943 | INFO | Traceupnp: isSSDPDiscovery found message to be an M-SEARCH message. | com.bwssystems.HABridge.upnp.UpnpListener
09-12-2017 21:08:21.943 | INFO | Traceupnp: isSSDPDiscovery found message to be valid under loose rules - strict: false | com.bwssystems.HABridge.upnp.UpnpListener
09-12-2017 21:08:21.943 | INFO | Traceupnp: SSDP packet from 192.168.55.10:61980, body: M-SEARCH * HTTP/1.1  Host: 239.255.255.250:1900  Man: "ssdp:discover"  ST: ssdp:all  MX: 5 | com.bwssystems.HABridge.upnp.UpnpListener
09-12-2017 21:08:21.944 | INFO | Traceupnp: sendUpnpResponse discovery responseTemplate1 is <<<HTTP/1.1 200 OK  HOST: 239.255.255.250:1900  CACHE-CONTROL: max-age=100  EXT:  LOCATION: http://192.168.55.71:81/description.xml  SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.19.0  hue-bridgeid: B827EBFFFED11E18  ST: upnp:rootdevice  USN: uuid:2f402f80-da50-11e1-9b23-b827ebd11e18::upnp:rootdevice    >>> | com.bwssystems.HABridge.upnp.UpnpListener
09-12-2017 21:08:21.944 | INFO | Traceupnp: sendUpnpResponse discovery responseTemplate2 is <<<HTTP/1.1 200 OK  HOST: 239.255.255.250:1900  CACHE-CONTROL: max-age=100  EXT:  LOCATION: http://192.168.55.71:81/description.xml  SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.19.0  hue-bridgeid: B827EBFFFED11E18  ST: uuid:2f402f80-da50-11e1-9b23-b827ebd11e18  USN: uuid:2f402f80-da50-11e1-9b23-b827ebd11e18    >>> | com.bwssystems.HABridge.upnp.UpnpListener
09-12-2017 21:08:21.944 | INFO | Traceupnp: sendUpnpResponse discovery responseTemplate3 is <<<HTTP/1.1 200 OK  HOST: 239.255.255.250:1900  CACHE-CONTROL: max-age=100  EXT:  LOCATION: http://192.168.55.71:81/description.xml  SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.19.0  hue-bridgeid: B827EBFFFED11E18  ST: urn:schemas-upnp-org:device:basic:1  USN: uuid:2f402f80-da50-11e1-9b23-b827ebd11e18    >>> | com.bwssystems.HABridge.upnp.UpnpListener
09-12-2017 21:08:22.209 | INFO | Traceupnp: upnp device settings requested: from 192.168.55.10:81 | com.bwssystems.HABridge.upnp.UpnpSettingsResource
09-12-2017 21:08:22.211 | INFO | Traceupnp: upnp device settings template filled with address: 192.168.55.71 and port: 81 | com.bwssystems.HABridge.upnp.UpnpSettingsResource
09-12-2017 21:08:24.623 | INFO | Traceupnp: hue lights list requested: (null) from 192.168.55.42 | com.bwssystems.HABridge.hue.HueMulator
09-12-2017 21:08:26.272 | INFO | Traceupnp: isSSDPDiscovery found message to be an M-SEARCH message. | com.bwssystems.HABridge.upnp.UpnpListener
09-12-2017 21:08:26.272 | INFO | Traceupnp: isSSDPDiscovery found message to be valid under loose rules - strict: false | com.bwssystems.HABridge.upnp.UpnpListener
09-12-2017 21:08:26.272 | INFO | Traceupnp: SSDP packet from 192.168.55.95:38977, body: M-SEARCH * HTTP/1.1  HOST: 239.255.255.250:1900  MAN: "ssdp:discover"  MX: 2  ST: ssdp:all | com.bwssystems.HABridge.upnp.UpnpListener
09-12-2017 21:08:26.273 | INFO | Traceupnp: sendUpnpResponse discovery responseTemplate1 is <<<HTTP/1.1 200 OK  HOST: 239.255.255.250:1900  CACHE-CONTROL: max-age=100  EXT:  LOCATION: http://192.168.55.71:81/description.xml  SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.19.0  hue-bridgeid: B827EBFFFED11E18  ST: upnp:rootdevice  USN: uuid:2f402f80-da50-11e1-9b23-b827ebd11e18::upnp:rootdevice    >>> | com.bwssystems.HABridge.upnp.UpnpListener
09-12-2017 21:08:26.275 | INFO | Traceupnp: sendUpnpResponse discovery responseTemplate2 is <<<HTTP/1.1 200 OK  HOST: 239.255.255.250:1900  CACHE-CONTROL: max-age=100  EXT:  LOCATION: http://192.168.55.71:81/description.xml  SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.19.0  hue-bridgeid: B827EBFFFED11E18  ST: uuid:2f402f80-da50-11e1-9b23-b827ebd11e18  USN: uuid:2f402f80-da50-11e1-9b23-b827ebd11e18    >>> | com.bwssystems.HABridge.upnp.UpnpListener
09-12-2017 21:08:26.276 | INFO | Traceupnp: sendUpnpResponse discovery responseTemplate3 is <<<HTTP/1.1 200 OK  HOST: 239.255.255.250:1900  CACHE-CONTROL: max-age=100  EXT:  LOCATION: http://192.168.55.71:81/description.xml  SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.19.0  hue-bridgeid: B827EBFFFED11E18  ST: urn:schemas-upnp-org:device:basic:1  USN: uuid:2f402f80-da50-11e1-9b23-b827ebd11e18    >>> | com.bwssystems.HABridge.upnp.UpnpListener
09-12-2017 21:08:27.553 | INFO | Traceupnp: isSSDPDiscovery found message to be an M-SEARCH message. | com.bwssystems.HABridge.upnp.UpnpL

**Comment by Wolbolar** [comment]
Another strange thing is, I tried the Hue App, there a bridge is found, but no connection can be established. I tried also iConnectHue were the Bridge is found and a connection could be established. But after discovery of the HA Bridge, I can see all the Hue bulbs from the other real HUE Bridges and the status is changing also in the HA Bridge devices, when I send a command to the real Hue Bridge. If I try to send a command via iConnectHUE to the HA Bridge nothing happens. If I press the Test ON / Test OFF button for a bulb inside the HA Bridge the bulb is responding and turns on/off.

**Comment by bwssytems** [comment]
Ahhh, you will need to run the ha-bridge on port 80. Most apps seem to hard code the port for philips hue instead of following the upnp protocol.

**Comment by bwssytems** [comment]
Any update on this?

**Comment by Wolbolar** [comment]
I changed the Port to 80 now it works fine.
