### ISSUE TITLE
Logitech POP redux, and Hue

### ISSUE THREAD

**Issue by spud** [bwssytems/ha-bridge#745]
User ahertz mentioned a while ago that s/he was able to link the Logitech POP bridge with the HA Bridge.

Can anyone give any information on how this works? I've enabled the Link Button in HA Bridge (with no username/password), and I've clicked the "Link" button on HA Bridge while having the Logitech app "Scan for devices" as when as attempting to add "Philips Hue" and clicking "Link" when it prompts me to push the Hue bridge button.

The POP app never seems to recognize the HA bridge.

I do have a physical Hue bridge, but I have been unable to add it to HA bridge. I give it a name, and the proper local IP address, and hit "Save." 

I can navigated away from the page (say, to "Bridge devices") and return to "Bridge control," and _sometimes_ the Hue address is still there, and sometimes it has disappeared. In any case, after various clicking, it always disappears. 

My Philips Hue app can always get to the Hue bridge, and my Harmony Hub can reach it as well.

I'm hoping to get the Logitech POP to be able to control Vera devices, ultimately, and the HA bridge seems to be the only way to do it.

Any suggestions?

PS: Running HA Bridge 4.5.6.

**Comment by bwssytems** [comment]
Maybe turn off your hue bridge to let the POP see the ha-bridge....
