### ISSUE TITLE
Startup issue? 

### ISSUE THREAD

**Issue by pnutp0wer** [bwssytems/ha-bridge#746]
Hi all,

I am using since 2 weeks the ha-bridge through my RPi. But since today the bridge isn't working properly. If I check on the http://192.168.188.35 I get a blank page... Debugging isn't my thing, I just dont understand anything of it. I checked the the habridge.service file and everything is still here: 

> [Unit]
> Description=HA  Bridge
> Wants=network.target
> After=network.target
> 
> [Service]
> Type=simple
> WorkingDirectory=/home/pi/habridge
> ExecStart=/usr/bin/java -jar    -Dconfig.file=/home/pi/habridge/data/habridge.c$
> 
> [Install]
> WantedBy=multi-user.target
> 

Also I taked a look at the system log

> pi@raspberrypi:~ $ tail -f /var/log/syslog
> Sep 13 20:27:30 raspberrypi java[8338]: Error: A fatal exception has occurred. Program will exit.
> Sep 13 20:27:30 raspberrypi systemd[1]: habridge.service: Main process exited, code=exited, status=1/FAILURE
> Sep 13 20:27:30 raspberrypi systemd[1]: habridge.service: Unit entered failed state.
> Sep 13 20:27:30 raspberrypi systemd[1]: habridge.service: Failed with result 'exit-code'.
> Sep 13 20:27:30 raspberrypi systemd[1]: habridge.service: Service hold-off time over, scheduling restart.
> Sep 13 20:27:30 raspberrypi systemd[1]: Stopped HA#011Bridge.
> Sep 13 20:27:30 raspberrypi systemd[1]: habridge.service: Start request repeated too quickly.
> Sep 13 20:27:30 raspberrypi systemd[1]: Failed to start HA#011Bridge.
> Sep 13 20:27:30 raspberrypi systemd[1]: habridge.service: Unit entered failed state.
> Sep 13 20:27:30 raspberrypi systemd[1]: habridge.service: Failed with result 'exit-code'.

If I do the following commando described out of the tutorial I get no feedback?

> pi@raspberrypi:~ $ sudo systemctl daemon-reload
> pi@raspberrypi:~ $ 
> 

If I check on the logs I get the following response multiple times:

> ● habridge.service - HA Bridge
>    Loaded: loaded (/etc/systemd/system/habridge.service; enabled; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Wed 2017-09-13 00:38:35 CEST; 15s ago
>   Process: 1110 ExecStart=/usr/bin/java -jar -Dconfig.file=/home/pi/habridge/data/habridge.config /home/pi/habridge/h
>  Main PID: 1110 (code=exited, status=1/FAILURE)
> 
> sep 13 00:38:34 raspberrypi systemd[1]: Started HA        Bridge.
> sep 13 00:38:35 raspberrypi java[1110]: 2017-09-13 00:38:35,312 [main] INFO  com.bwssystems.HABridge.HABridge - HA Br
> sep 13 00:38:35 raspberrypi java[1110]: 2017-09-13 00:38:35,366 [main] INFO  com.bwssystems.HABridge.BridgeSettings -
> sep 13 00:38:35 raspberrypi java[1110]: Exception in thread "main" java.lang.NullPointerException
> sep 13 00:38:35 raspberrypi java[1110]:         at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSetting
> sep 13 00:38:35 raspberrypi java[1110]:         at com.bwssystems.HABridge.HABridge.main(HABridge.java:51)
> sep 13 00:38:35 raspberrypi systemd[1]: habridge.service: Main process exited, code=exited, status=1/FAILURE
> sep 13 00:38:35 raspberrypi systemd[1]: habridge.service: Unit entered failed state.
> sep 13 00:38:35 raspberrypi systemd[1]: habridge.service: Failed with result 'exit-code'.
> ~
> ~
> ~
> ~
> ~
> ~
> ~
> ~
> lines 1-15/15 (END)

Does somebody know how to fix this issue? FYI I got also the Sonos API from Jishi running on http://192.168.188.35:5005/. Both worked together always great until today ..

**Comment by audiofreak9** [comment]
The line 
`ExecStart=/usr/bin/java -jar -Dconfig.file=/home/pi/habridge/data/habridge.c$` 
does it actually end with a string $, or is that a copy from a line overrun?

It should be (all on one line) the following:
`ExecStart=/usr/bin/java -jar -Dconfig.file=/home/pi/habridge/data/habridge.config /home/pi/habridge/ha-bridge.jar`

**Comment by pnutp0wer** [comment]
Sorry, didn't copy the string correctly. It does end the way you describe it..

**Comment by pnutp0wer** [comment]
Haha believe it or not, but when I wanted to start sonos it didn't work this morning, while it worked yesterday. strange thing, it wasn;t the memory this time.. Just rebooted my pi and it's working again.

**Comment by pnutp0wer** [comment]
Crashed again this morning, unless I reboot the pi the ha-bridge isn't working. If i check the logs i get this: 

pi@raspberrypi:~ $ tail -f /var/log/syslog
Oct 22 08:17:01 raspberrypi CRON[24758]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Oct 22 09:17:01 raspberrypi CRON[24781]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Oct 22 10:17:01 raspberrypi CRON[24799]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Oct 22 11:17:01 raspberrypi CRON[24823]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Oct 22 12:17:01 raspberrypi CRON[24847]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Oct 22 12:35:52 raspberrypi systemd[1]: Starting Cleanup of Temporary Directories...
Oct 22 12:35:52 raspberrypi systemd[1]: Started Cleanup of Temporary Directories.
Oct 22 13:17:01 raspberrypi CRON[24871]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Oct 22 13:26:03 raspberrypi systemd[1]: Started Session c4 of user pi.
Oct 22 13:27:42 raspberrypi systemd[1]: Started Session c5 of user pi.

**Comment by pnutp0wer** [comment]
Hi @bwssytems unfortanetly it stopped working again. If I check the logs I get the following back:
Oct 24 19:31:32 raspberrypi java[1369]: 2017-10-24 19:31:32,425 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: /home/pi/habridge1/data/habridge.config
Oct 24 19:31:32 raspberrypi java[1369]: Exception in thread "main" java.lang.NullPointerException
Oct 24 19:31:32 raspberrypi java[1369]: #011at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:150)
Oct 24 19:31:32 raspberrypi java[1369]: #011at com.bwssystems.HABridge.HABridge.main(HABridge.java:51)
Oct 24 19:31:32 raspberrypi systemd[1]: habridge.service: Main process exited, code=exited, status=1/FAILURE
Oct 24 19:31:32 raspberrypi systemd[1]: habridge.service: Unit entered failed state.
Oct 24 19:31:32 raspberrypi systemd[1]: habridge.service: Failed with result 'exit-code'.

**Comment by bwssytems** [comment]
Well, it looks as the error in your log says it cannot build the settings from the config file. Since your cut and paste does not fully show the error, I can only suggest that you validate your config file, or start fresh with an empty config.

**Comment by pnutp0wer** [comment]
Thank you for your info! I overwrited the new created habridge.config file (see: https://imgur.com/a/TQLFu) by the old one. Everything is working now. Want to share this so other people will also know it.

**Comment by jayjupdhig** [comment]
How to import ha-bridge correctly in Eclipse? I always get package src.main.com ... 

I tried tons og different methods - no noe works really well.

Maybe it's much more simple to create the project manually, which means to create an empty project, then package, then download source classes to package folder, then resolve depenceeies, etc. pp..
