### ISSUE TITLE
Hue Bridge not recognized by Alexa device with v4.5.6

### ISSUE THREAD

**Issue by rkanton** [bwssytems/ha-bridge#748]
I have a iLive Platinum Alexa device, that says it supports Home Automation (but I'm beginning to doubt that).

Here is my trace:

2017-09-19 12:41:14,899 [main] INFO com.bwssystems.HABridge.upnp.UpnpListener - Traceupnp: sendUpnpNotify notifyTemplate is <<<NOTIFY * HTTP/1.1
HOST: 239.255.255.250:1900
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.0.68:8080/description.xml
SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.19.0
NTS: ssdp:alive
hue-bridgeid: B827EBFFFE7B2EF9
NT: uuid:2f402f80-da50-11e1-9b23-b827eb7b2ef9
USN: uuid:2f402f80-da50-11e1-9b23-b827eb7b2ef9

Here is the output of a upnp discovery app in Linux:
USN: uuid:2f402f80-da50-11e1-9b23-b827eb7b2ef9::upnp:rootdevice
Location: http://192.168.0.68:8080/description.xml
resource available
USN: uuid:2f402f80-da50-11e1-9b23-b827eb7b2ef9
Location: http://192.168.0.68:8080/description.xml
resource available

Here is the description.xml
10http://192.168.0.68:8080/urn:schemas-upnp-org:device:Basic:1Philips hue (192.168.0.68)Royal Philips Electronicshttp://www.philips.comPhilips hue Personal Wireless LightingPhilips hue bridge 2015BSB002http://www.meethue.comb827eb7b2ef9uuid:2f402f80-da50-11e1-9b23-b827eb7b2ef9(null)(null)(null)(null)(null)index.htmlimage/png484824hue_logo_0.pngimage/png12012024hue_logo_3.png

**Comment by bwssytems** [comment]
The iLive may be hard coded to find the ha-bridge/hue on port 80 not port 8080.

**Comment by rkanton** [comment]
Sorry for the late response.  I tried changing the ha_bridge/hue port to 80 and the iLive still could not discover any devices.

**Comment by bwssytems** [comment]
So, is there any more info from the trace? Did the iLive request the description.xml?
