### ISSUE TITLE
No Login Feedback - No Password reset

### ISSUE THREAD

**Issue by denizkoekden** [bwssytems/ha-bridge#749]
Hello,
once setup I did not touch the bridge for a while. Now I want to login and there is no feedback on the login. I dont get an error like "wrong password" or something like this. And I dont see an option to reset the password. Is there an hidden option?

**Comment by bwssytems** [comment]
Will need to add the feedback then. To reset, you will need to go in to the habridge.conf file and delete the security json string and reset the items you need.

Something to add in the future.

**Comment by bwssytems** [comment]
Adding the feedback portion. As far as reset, the file editing is the only way if you forget the password.

**Comment by cool-lox** [comment]
Have same problem, password was stored in Browser. Now I made new installation of PC, passwort is gone. What happens when deleting the part "securityData":.......  ?   Do I have to install after that all items new ? For example I have setup 15 items which I can start with Alexa.

**Comment by bwssytems** [comment]
as th post above mentions, delete the ```"security":xxxxx''' json string in the habridge.conf and you will be ok.
