### ISSUE TITLE
Custom request works but reports error

### ISSUE THREAD

**Issue by amerton** [bwssytems/ha-bridge#75]
Dear all

I've setup a device to command a roller blind via a Fibaro HCL.
When I test the command, the blind opens/closes but the ha-bridge reports an error 
	Error on calling url to change device state

The command is
http://usr:pwd@192.168.1.6/api/callAction?deviceID=118&name=setValue&arg1=0

When I try it from safari by entering it directly in the adress bar it returns
{"id":0,"jsonrpc":"2.0","result":{"result":0}}

I've set GET, no content in the manual add interface

Ideas?

Thanks for your help
Anthony

**Comment by audiofreak9** [comment]
@bwssytems I had a user report on my how-to blog post the same problem, 

> "...when I try to use the Test On or Test Off buttons, I get this error message: Error on calling url to change device state..."

It was for a custom url, I've asked for their devices json, I'll post when I get it.

**Comment by osenbruggen** [comment]
I have the same problem. I'm using: http://user:password@192.168.x.x/api/callAction?deviceID=149&name=turnOn with GET. It does work by the way, I can switch this light on and off, but Alexa (and the test buttons) return an error message.

**Comment by bwssytems** [comment]
This should work, I'll look at the url handling.

**Comment by osenbruggen** [comment]
I found the problem. Fibaro is sending a back 202 not a 200

**Comment by bwssytems** [comment]
Ahh, I see. And that is a valid code. I'll update the handling to be more cognizant of the other success codes.

**Comment by bwssytems** [comment]
Ahh, I see. And that is a valid code. I'll update the handling to be more cognizant of the other success codes.

**Comment by TrevorNewsome** [comment]
I had this working on an old server, I have re-installed a new server a few weeks later and my old settings no longer working. the difference being there has been a recent Home Center 2 update and not sure if this maybe part of the issue. I am getting the issue that you have described above whereby even though I specify the username and password in the http content. On my browser it still askes me to login using my username and password and then works there after. I am running a Ubuntu server with command prompt only so I have no way of authorizing the output message like I do in the browser any ideas? Any help would be appreciated.

**Comment by TrevorNewsome** [comment]
curl -v http://UserName:Password@192.168.xxx.xxx/api/callAction?deviceID=21&name=turnOn
[6] 6057
[5]   Done                    curl -v http://Username:Password@192.168.xxx.xxx/api/callAction?deviceID=21
usr@HomeServer:/usr/bin/habridge/data$ *   Trying 192.168.xxx.xxx...
* Connected to 192.168.x.xx (192.168.xxx.xxx) port 80 (#0)
* Server auth using Basic with user 'Username'
> GET /api/callAction?deviceID=21 HTTP/1.1
> Host: 192.168.xxx.xxx
> Authorization: Basic BBJlem3yOlRvc3Nlcjcc
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Date: Sat, 24 Dec 2016 14:28:24 GMT
< Server: 0.9
< Cache-Control: no-cache, no-store, must-revalidate, max-age=0, max-age:0
< Content-Type: application/json;charset=UTF-8
< Pragma: no-cache
< Expires: Fri, 01 Jan 2010 00:00:00 GMT
< Connection: close
< Transfer-Encoding: chunked
<
* Closing connection 0
{"type":"ERROR","reason":"MISSING_PARAMETER","message":"name: missing required parameter"}^C
[6]+  Done                    curl -v http://Username:Password@192.168.xxx.xxx/api/callAction?deviceID=21
usr@HomeServer:/usr/bin/habridge/data$

**Comment by bwssytems** [comment]
Not an ha-bridge issue as I can see. You will need to work out the http call with curl and then get that into the ha-bridge.
