### ISSUE TITLE
ha-bridge doesnt see harmony activity 

### ISSUE THREAD

**Issue by andynchou** [bwssytems/ha-bridge#752]
Hi 
i have ha-bridge-4.5.6 running on pi 
all my Vera and harmony was working properly with Google home 
not sure when the Google home cant control the TV so i check the ha-bridge all the harmony activity is blank but my Vera still there and everything working fine with Vera 

tried delete data on ha-bridge and reinitialize the bridge no luck 
tried change ip on harmony and rest harmony still wont work 
do i need enter the user name and pass for harmony on ha-bridge ?(i don't see anywhere i can put those info)

this is the error message from ha-bridge log
ERROR	Cannot get harmony client (Harmony) setup, Exiting with message: Failed communicating with Harmony Hub	com.bwssystems.HABridge.plugins.harmony.HarmonyHome

if someone can give some advice will be much appreciate 
thanks

**Comment by rafale77** [comment]
Reboot the bridge. I observed this a few days ago and got it fixed that way. I am suspecting that it was due to some firmware upgrade from the cloud on the harmony units.

**Comment by andynchou** [comment]
thanks for reply 
i rebooted pi and reinitialized the bridge again 
on the harmony activity still showing nothing

**Comment by rafale77** [comment]
This is odd. I have not seen this. What version of hub firmware are you running?

**Comment by andynchou** [comment]
ha-bridge-4.5.6
harmony is latest

**Comment by rafale77** [comment]
the latest harmony might be your problem. You know for sure your Harmony addresses did not change? I have just checked my harmony hub and I also am on the latest.

**Comment by andynchou** [comment]
yes i set the address in my router make sure they always have same IP 
and after this issue i did try change different IP address as well 
still same problem

**Comment by audiofreak9** [comment]
@andynchou I had a similar problem when I updated to 4.5.6.  I deleted the harmony entry in the bridge, then clicked Save, then added a new, but exact harmony entry, then clicked Save.  After that my harmony hub was discovered and my configured activities and devices appeared on the Harmony Tabs.

**Comment by andynchou** [comment]
just tried delete on bridge control then save 
add the harmony bridge ip back then save again 
still blank in harmony activity

**Comment by andynchou** [comment]
finally i got it work after reinstall pi and habridge

**Comment by tholle26** [comment]
Hi,

i have the same issue. No harmony activities or harmony devices found.
I've tried a new installation of ha bridge, but still now activities or devices.

I am using the latest version of habridge (v.4.5.6).

I hope, i can find any help here.

kind regards,
tholle

**Comment by gpion** [comment]
Exact same problem for me on a totally fresh newly installation
My java version seem fine:
```
# java -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode)
```
