### ISSUE TITLE
living room light isn't responding

### ISSUE THREAD

**Issue by trped** [bwssytems/ha-bridge#754]
Every 10 times i get this reply from alexa "xxx device isn't responding"

Why is this?? 

HTTP response code was not an expected successful response of between 200 - 299, the code was: HTTP/1.1 502 Proxy Error

This is from my log

please help

**Comment by bwssytems** [comment]
That is interesting, but it is the end point giving you the message of the proxy error. Do you have something in between you and your device and what type of device is this?
