### ISSUE TITLE
Hue Bridge IP address doesn't stick

### ISSUE THREAD

**Issue by spud** [bwssytems/ha-bridge#755]
I have a Vera Plus, a Harmony Hub, and a Philips Hue Bridge (v1). The HA Bridge recognizes and keeps track of my Vera and Harmony hubs, but if I enter the IP address of my Hue bridge and give it a name ("My Hue"), upon saving the configuration, I end up on the "Login" screen, and when I return to Bridge Control, the information I entered for the Hue Bridge is gone.

How can I troubleshoot this? I assume this shouldn't be happening...

**Comment by bwssytems** [comment]
Will take a look

**Comment by bwssytems** [comment]
Hmm, did you hit the green 'Add' button before you hit save on the Hue IP address?

**Comment by bwssytems** [comment]
Is this still an issue?
