### ISSUE TITLE
Setup to control my clo system tv mount

### ISSUE THREAD

**Issue by michaelhinchey** [bwssytems/ha-bridge#757]
I was wondering if I needed to create scenes with the mount through harmony or could I create them in habridge?  
  I only saw on/off buttons in the build a button menu in 4.5.6 habridge. 
Thx for your help

**Comment by bwssytems** [comment]
You should see your clo mount in the devices section of the harmony tabs.

**Comment by michaelhinchey** [comment]
Yes I see them.  I asked do I have to make certain scenes like pre set position 1, pre set position 2 etc?
  Or can I just make them in ha bridge?

**Comment by bwssytems** [comment]
You can just name them in the bridge.

**Comment by michaelhinchey** [comment]
I was wondering how to set them up. I'm asking If I can set the settings in
the bridge or do I have to go through harmony ?









    Every dream is a goal with a date on it; if you can conceive it believe
it, you can achieve it. Don't let anyone steal your dream. Make the
decision to take a positive attitude, take pride in yourself and what you
do, work hard and stay with it. A mind is a terrible thing to waste.


"I felt bad because I couldn't wheelie; until I met a man with no bicycle"

"You are young at any age... if you are planning on tomorrow"

**Comment by bwssytems** [comment]
Not sure what the system really can do, so you'll need to experiment. Try it  in the Harmony, can't hurt.
