### ISSUE TITLE
Webserver Port Changing 81-->80 does not work

### ISSUE THREAD

**Issue by ChRos41** [bwssytems/ha-bridge#760]
Hi, I am running an raspberry RPI with HA-Bridge. Its running well and I can control devices by Alexa,
However, I want change the Webserver Port by which is running at 81 to 80. This does not work!
Neither through the WEB-GUI of the HA Bridge nor in the Command lines using the terminal.

Can anyone help me?

**Comment by jlekhter** [comment]
You probably have something running that is already using port 80. Do a netstat -a to see what it is and determine if you need to run that thing.

**Comment by ChRos41** [comment]
Dear all, my problem is solved, I wasn´t aware  of that the Vi-editor requires specific shortcuts to edit something. Now i am  changed it to 80 and it is also in the WebGUi changed.
