### ISSUE TITLE
Philips Hue app update - bridge update required

### ISSUE THREAD

**Issue by balk77** [bwssytems/ha-bridge#761]
My Android phone pulled in a new version of the Philips Hue app, v 2.16.0. The result is that this app does not work work HA Bridge anymore. "App functionality is limited until Hue bridge is updated" (freely translated from Dutch). Obviously the update function does not work as I do not have a physical Hue bridge. Alternative Hue apps still work. Is this easy to fix?

**Comment by FloFoer** [comment]
Yes, go to your HA-Bridge web ui and there to the bridge control tab. Change the setting "Emulate Hue Hub version" to 1709131301.  Afterwards the update note disappears, because it thinks you gut the update.

**Comment by balk77** [comment]
Cool it works, thanks! For a next time, where do I find these numbers and can this be automated?

**Comment by audiofreak9** [comment]
Wiki FAQ here https://github.com/bwssytems/ha-bridge/wiki/HA-Bridge-FAQs#HUEReleaseVersion

Currently not automated.

**Comment by ChRos41** [comment]
Dear all,  I am running the HA-Bridge on Port 80. it  is recognized by the hue app after manually entering the IP adress, within th iOS-Hue App. I also updated  the latest Hue firmware within the Bridge Control and saved it. However the connection of the App to the HA Bridge seems to be completely instable. It switches constantly between "Connected" and "Not Connected." Same with the Android app. Have I overseen some settings?
Thanks

**Comment by FloFoer** [comment]
@balk77 
One possibility to try to "automate" it is to simply set the "Emulate Hue Hub Version" to a very large number that is much larger than the current version number (for example to 9999999999). I have tried that and the app **seems** to go with it. I assume the app simply checks the version number to be greater than or equal to the minimum "required" to work.

**Comment by bwssytems** [comment]
@FloFoer I'll put that in this release. Of course I will leave the setting in the control tab if it doesn't.
