### ISSUE TITLE
Google Home changed to account.meethue.com with logins

### ISSUE THREAD

**Issue by tonlof** [bwssytems/ha-bridge#764]
Today all my devices was gone in Google home app so I had to connect to Philips Hue but now I'm directed to account.meethue.com to login. This page does only recognize the orignial hardware and not ha-bridge. 
Also tried to change Emulate Hue Hub Version to 1709131301
Anybody else experience same?

**Comment by Twistedmist** [comment]
I experienced the same.

check out issue 765. 

Detailed description

**Comment by tonaldo85** [comment]
Hello,
have the same Problem. Also trying to connect the original Hue Bridge to Google Home and this is also not working. So the problem is that google direct you to account.meethue.com and not to the old site. Does anybody have a workaround for this problem? I need this function for my master thesis. 
Thanks

**Comment by boudicca99** [comment]
@tonaldo85 you are a bit borked. This is probably the end for Google Home to hue api local controlled devices on the Google Assistant platform. They are very much moved entirely to cloud based mostly big vendors with silo'ed/walled off product lines supporting their "Actions" with auth api.  Its going to mean that unless your product is certified to work with Google Home via this Actions method, you are left out in the cold.

**Comment by 1980georgeg** [comment]
Has anyone tried spinning up bind and nginx on a pi or even the hass box and doing a permanent redirect with some crafty local DNS from https://account.meethue.com to https://hue-adapter.appsot.com ?

I might give this a try over the coming days as I now have a Google junkhome.

**Comment by 1980georgeg** [comment]
I should add that my habridge / hass setup was still working - I just wanted to try out emulated hue in hass and removed the Google home app to reinstall the older one for the purpose of adding the bridge.

**Comment by boudicca99** [comment]
sadly that won't work. as Assistant.google.com redirects to account.meethue.com, any redirect of meethue.com has already got the full url from assistant.google.com with Auth / Token etc. resulting 404 against a aliased account.meethue.com to hue-adapter.appspot.com, aliasing assistant.google.com breaks the google home app so you can't even select hue. 

In short the api codes gone anyway.  Previously when you opened "hue-adapter.appspot.com" there was a "Link" button, now replaced with a message , Please use Google Home app to connect Hue bridge to Google

**Comment by 1980georgeg** [comment]
Yup you're right. Had a closer look tonight and definitely agree that this indeed this extends as far as Google changes to our detriment.

I guess it's ifttt and security concerns and lag until something comes up, or a move to Alexa/Bing for me.

I feel for the love and time that's gone into the habridge development and hope that the big G come to their senses and start behaving in the way that made them what they are now, again. From what I understand anyone with a genuine v1 bridge is also affected? Can anyone confirm?

George

**Comment by robertw** [comment]
I don't think that will happen as it is looking more like Smarthome v3 will also be moving in that direction....

**Comment by bardoup** [comment]
Is there any hope to integrate HAbridge with the philips cloud ?
Or is google home + habridge definitively dead ?

**Comment by bwssytems** [comment]
@bardoup We are not associated with Philips as that is their own system so there would not be any way to be part of that private cloud.

**Comment by bardoup** [comment]
@bwssytems Thank you for your reply. 
This is very sad, cause HA bridge was a very convenient way to interface google home with domoticz. I'll have to use the hard way, IFTTT, node-red and MQTT.

**Comment by tonaldo85** [comment]
@bardoup. You Can also use the way IFTTT and Openhab2. This is my workaround for The time until The habridge works again.

**Comment by bardoup** [comment]
@tonaldo85  The major interest of HAbridge for me was to avoid IFTTT, because for security reasons I didn't want my home automation center to be opened to the Internet.
If I understood well, HAbridge will **never** integrate in the Philips cloud, and therefore will **never** work again with google home.

**Comment by jeckyllhavok** [comment]
I wouldn't say that it will never work again, this seems promising:
https://developers.google.com/actions/smarthome/

**Comment by LuckyMallari** [comment]
@jeckyllhavok yep. When that comes into fruition, there actually wont be any need for HABridge.

**Comment by dannieboiz** [comment]
Just so I'm not missing anything. I had issue with my HA bridge then one thing lead to another I deleted all of my devices from GH thinking I can start over then I came to this same issue... Are we done here.... for now? No more ok google turn on my lights?

**Comment by 1980georgeg** [comment]
Guys, in case you're using homeassitant the Google actions / assistant integration is working since several releases ago. In fact I use it with no issues (apart from a slight delay vs habridge). The hass site has a complete guide on setting it up too.

Cheers

**Comment by wallylee99** [comment]
I've switched to node-red + IFTTT as an interim solution, by creating applet in IFTTT which translates google home's calls to MQTT, I am able to control my lights the same way as before.  The down side is that I have to expose my rpi to the internet and the response of IFTTT is a little bit slow.  Hopefully this issue can be resolved soon.

**Comment by bwssytems** [comment]
Unfortunately, until Google changes the app api to not use cloud type services only, this will not be possible. They have taken away the ability to use local control from the Home.

**Comment by bwssytems** [comment]
@wallylee99 Also, I would not use the ha-bridge exposed externally. This is a use at your own risk software as it is open source.

**Comment by wallylee99** [comment]
@bwssytems, as I have switched over to another solution, I am not using ha-bridge now and have disabled it.  I do understand the risk of exposing my rpi to the internet, and I have hardened it and hope it would be only temporary.

**Comment by mrv777** [comment]
So we can no longer use our Google Homes with ha-bridge and thus the Vera?

**Comment by bwssytems** [comment]
@mrv777 that is correct.

**Comment by Eric2XU** [comment]
@bwssytems first I want to thank you, your code has run my home smoothly for as long as you have created it. I see the tide turning however on not just Google but Amazon too given 2nd Gen cant discover HABrdge. Can you recommend a way forward when the day comes where HA Bridge is not longer able to be used with Amazon and Google? Not asking you to build anything persay just give me a general direction if I wanted to write my own code. I have the resources to host cloud services and connect vpns from my home to those clouds to get communications back on prem, what I am missing is how I can get Amazon or Google APIs that would even call such web services. Since HA Bridge has worked so well for so long I have never really put much thought into it.

**Comment by bwssytems** [comment]
Actually, the 2nd gen Echo's are working. They need to use the link feature that is turned on in security and it may take a couple of tries. Most issues now with people and 2nd gen are network issues on their end.

As far as the way the companies are going with connectivity? You are on track with what probably will happen. So the only way I though on how to do this is with a Amazon Alexa Skill that can be configured to talk the ha-bridge through a encrypted connection and with google a home app that would do the same concept. I know that the Google home app structure is using secure login based services from the provider to utilize the registered system.

To build you would register for the Amazon Developer and start looking at the skills tutorials and the same for Google and Home App development.

**Comment by cookemmm** [comment]
I have been working on a solution using a combination of ifttt with pushbullet python client listener and domoticz lua script to interpret and execute the command. So I do not have have my pi sitting on the internet with ports open and use ifttt with google assistant to push any note I want and have the lua script in domoticz perform the action from the pushbullet note. hope this helps.

**Comment by robertw** [comment]
fyi been trying all sort of things and the only real solution was to migrate to home assistant and using the google home tools have to say they work fine and yes being on the net is a concern but at the end of the day it has opened many doors and working very well

**Comment by audiofreak9** [comment]
@Eric2XU 

Based on your available resources you get a simple answer from me, same as @bwssytems,  Alexa Skill.  

I created an Alexa Skill that can tell me the state of my HA-Bridge devices: on, dim level or off.  My skill can also tell me my pool temperature, hot tub temperature, a to the point weather report, family phone numbers, birthdays, etc.  It was super simple, and Amazon hosts the whole thing, including images for my Show and Spot response cards.  I have my HA Bridge on an RPi that is port forwarded from my router to query the device states, and another port forwarded RPi that also provides the pool and hot tub temperatures.  **CAUTION! Exposing your HA Bridge to the internet is not recommended!**

**Comment by Eric2XU** [comment]
Just updating... I ended up setting up NGINX reverse proxy server in a home DMZ that takes in random high port SSL encrypted with letsEncrypt which is allowed http access to my internal Home Assistant instance. Google Home works great with it. Downsides are that I can only control things Home Assistant supports (which is most of my stuff) and the fact I have to use XAML (which I hate more than anything). But it is working well. The only thing left is I want to write a Home Assistant plugin that can call random webservice things for the remaining small bits it doesnt support to call HA Bridge

**Comment by Lee1135** [comment]
I notice that I could use a harmony hub as intermediate to make google home work again with HABridge: HA bridge can be added to harmony as Hue light, and harmony can be linked to google home.   

This involves lots of set up, but I do believe this all happens locally, google home should talk to harmony hub via wifi to execute the command ( "tell harmony to do something"), so a safer approach?

**Comment by bwssytems** [comment]
@Lee1135 will have to give that a try

**Comment by bwssytems** [comment]
Included in community information https://github.com/bwssytems/ha-bridge/wiki/Informational-Items-Collected-from-the-Community#q-google-home-changed-to-accountmeethuecom-with-logins
