### ISSUE TITLE
Google Home stopped responding to habridge

### ISSUE THREAD

**Issue by Twistedmist** [bwssytems/ha-bridge#765]
Hi all :)

first of, heres my setup:

Vera - Habridge - Google Home
Habridge Version 4.5.6

Yesterday I was trying to fix Dimming since it wasent working, so i deleted all my devices from habridge, when i added them again google home could not detect my devices.

So i started wandering around. Stoped bridge, reloaded, etc etc, still nothing.
Checked the status on system control. and everything was looking fine, but still nothing.

So i reinstalled my RPI. followed the instructions carefully, still nothing, Checked status and found one WARN. Could not find devices.db.
So i sudo nano device.db from habridge/data corrected the path, reloaded, start (stopped of course) then status and everything looked fine, But still nothing.

Have restarted my router but that didnt help either, so i reinstalled my RPI again (raspian). 
But still nothing.

So i wounder what might have happened and what to do, from here im clueless.

I have readed Habridge.config and everything looks fine.

Have google made some changes? Any one elsen have this problem.

All suggestions would be greatly appreciated.

Richard

**Comment by FloFoer** [comment]
Pretty sure that this is the same problem as the 2 hour old [issue #764](https://github.com/bwssytems/ha-bridge/issues/764)

**Comment by donaldtse118** [comment]
same issue here, it was working before...but suddenly all function gone...

**Comment by bwssytems** [comment]
If Google has changed to only use the meethue.com auth pi, then ha-bridge will not work with it any more .

**Comment by ozett** [comment]
if anybody finds a way around - could it may posted here?

**Comment by bwssytems** [comment]
Closing in reference to #764

**Comment by donaldtse118** [comment]
should have solution soon
https://community.home-assistant.io/t/setting-up-google-actions-for-assistant/29889

**Comment by bwssytems** [comment]
post this in #764 please
