### ISSUE TITLE
issuing "off command" to scenes

### ISSUE THREAD

**Issue by dannieboiz** [bwssytems/ha-bridge#766]
I have 2 scenes in Vera

1- All yard lights off
2 - All yard lights on

How do I merge this into one device or instead of saying "turn on all yard lights of" I can say turn off all yard lights. 

I can do this with a normal device switch obviously but not sure how to build this scene into an on/off device.

**Comment by bwssytems** [comment]
So, it is abit tricky. Use build item for your new device selecting the on scene. Then without saving go back to vera scenes and select the off scene. You will need to delete the off call in the multi command for the on command and in the of multi command delete the on command and then save your new device.

**Comment by dannieboiz** [comment]
Thanks that did the trick. It sounded confusing at first but once it's done, it's stupidly simple. 

For a moment, I thought it was like the old version where you had to copy and paste the command. I was looking for the commands but didn't see any. Re-read your post a few times then followed it.  You actually don't have to do this. 

Had to put on my logic thinking cap, just have to remember, if you click on the "scene on" build button first, then the first item would be the On command in the multi command in both on and off. So in the on, delete the 2nd scene and in the off, delete the first scene....easy peasy.
