### ISSUE TITLE
Cheap amazon wifi smart plugs Ha-Bridge Support

### ISSUE THREAD

**Issue by kentletor** [bwssytems/ha-bridge#769]
I purchased these two cheapo wifi smart plugs on amazon
https://www.amazon.com/Outlet-Amazon-Control-Anywhere-Anytime/dp/B072WSSTD4/ref=sr_1_3?ie=UTF8&qid=1508828396&sr=8-3&keywords=smart+outlet

Any way to get them to work with Ha-Bridge? I've been having issues with them not automatically reconnecting to Alexa and the app they recommend using.

**Comment by michaelhinchey** [comment]
Did you give them a static ip address?  I have this and Alexa and they work great.  However, I would like more control over them so it would be nice to integrate them into my bridge.

**Comment by bwssytems** [comment]
Anybody have a link to the protocol?

**Comment by kentletor** [comment]
@michaelhinchey I did give them a static ip, my router is one of those technicolor time warner router/modem combos; usually full of issues, I bought a new router to to see if that resolves the issues. Ha-bridge works perfect with my ir shield setup though.
