### ISSUE TITLE
Whitelabel Error Page  This application has no explicit mapping for /error, so you are seeing this as a fallback.

### ISSUE THREAD

**Issue by lamiastella** [bwssytems/ha-bridge#77]
So I am not sure why the configurator cannot control the Hue light. Also I am not sure if I should name it Toggle_1. Toggle_1 is the name I have used in OpenHAB items.

<img width="867" alt="screen shot 2016-03-25 at 8 54 35 pm" src="https://cloud.githubusercontent.com/assets/1892917/14057391/fcf2c82e-f2cb-11e5-8a17-7e6fe63adb5c.png">
<img width="1096" alt="screen shot 2016-03-25 at 8 54 54 pm" src="https://cloud.githubusercontent.com/assets/1892917/14057392/fcf546da-f2cb-11e5-8904-03de66787231.png">

This is what I have in the iotpi.items
```
Switch Toggle_1   "IoT Lab Light Bulb"   (Switching) {hue="3"}
Color Color_1     "IoT Lab Light Bulb"   (Colorize)  {hue="3"; colorTemperature; 30"}
Switch Toggle_2   "IoT Lab Light Bulb"   (Switching) {hue="1;brightness;30"}
Color Color_2     "IoT Lab Light Bulb"   (Colorize)  {hue="1;colorTemperature;30"}
```
and here's the error I get when I click on the test ON:
```
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Sat Mar 26 01:57:26 UTC 2016
There was an unexpected error (type=Not Found, status=404).
No message available
```

<img width="574" alt="screen shot 2016-03-25 at 8 57 44 pm" src="https://cloud.githubusercontent.com/assets/1892917/14057400/4d2d27c6-f2cc-11e5-8bbe-a3e9a05ada39.png">

In http://192.168.1.102:8080/, 192.168.1.102 is my Raspberry Pi 2 Model B IP, and 8080 is the port Amazon Echo HA bridge is running on. I have upnp disabled on my router configuration and openhab daemon is running on port 8082.

<img width="522" alt="screen shot 2016-03-25 at 8 42 32 pm" src="https://cloud.githubusercontent.com/assets/1892917/14057405/7b1eb06e-f2cc-11e5-9379-6666907e3f7f.png">

Can you help me please to troubleshoot this problem?

**Comment by audiofreak9** [comment]
You need to change your port in the on/off URLs to your OpenHab port 8082.

**Comment by audiofreak9** [comment]
BTW, what version of the bridge are you running?  The screen shots you provided look a lot like the armzilla version, not the bwssystem's forked version here.

**Comment by bwssytems** [comment]
That is the armzilla version which is not this one. Go to the releases page here and download the V1.4.2 and use the readme to set it up.

**Comment by bwssytems** [comment]
Di you try the latest version from this github page?

**Comment by bwssytems** [comment]
Assume this is closed as the correct release is being used.
