### ISSUE TITLE
Harmony Commands suddenly stopped working

### ISSUE THREAD

**Issue by vaderag** [bwssytems/ha-bridge#770]
I am using Echo to control Harmony commands via HA Bridge.

All other commands are working, but when I request the Harmony related ones I get "[Activity] is not responding"

Looking at the logs I'm seeing a lot of failing heartbeats and many many Errors on spark.webserver.MatcherFilter

Log pasted below.

This has been working for sometime tho I have just changed my router and needed to update the IP of the hub (it's static), and after that is was working a couple of days ago, but came back from work and now getting the errors.

Any help appreciated!
Thanks

--------------

10-24-2017 09:39:58.852 | INFO | activity changed: [27852048] Xbox | com.bwssystems.HABridge.plugins.harmony.HarmonyServer
-- | -- | -- | --
10-24-2017 09:41:13.987 | INFO | activity changed: [-1] PowerOff | com.bwssystems.HABridge.plugins.harmony.HarmonyServer
10-24-2017 10:42:47.564 | WARN | Send heartbeat failed | net.whistlingfish.harmony.HarmonyClient
10-24-2017 12:12:13.284 | INFO | activity changed: [27852048] Xbox | com.bwssystems.HABridge.plugins.harmony.HarmonyServer
10-24-2017 13:19:41.569 | INFO | activity changed: [-1] PowerOff | com.bwssystems.HABridge.plugins.harmony.HarmonyServer
10-24-2017 17:40:04.688 | INFO | activity changed: [27852048] Xbox | com.bwssystems.HABridge.plugins.harmony.HarmonyServer
10-24-2017 22:26:49.920 | ERROR |   | spark.webserver.MatcherFilter
10-24-2017 22:27:19.497 | ERROR |   | spark.webserver.MatcherFilter
10-24-2017 22:27:19.567 | WARN | Send heartbeat failed | net.whistlingfish.harmony.HarmonyClient
10-25-2017 18:16:31.274 | ERROR |   | spark.webserver.MatcherFilter
10-25-2017 18:16:31.474 | ERROR |   | spark.webserver.MatcherFilter
10-25-2017 18:16:43.517 | ERROR |   | spark.webserver.MatcherFilter
10-25-2017 18:16:43.570 | ERROR |   | spark.webserver.MatcherFilter
10-25-2017 18:16:49.870 | ERROR |   | spark.webserver.MatcherFilter
10-25-2017 18:16:49.934 | ERROR |   | spark.webserver.MatcherFilter
10-25-2017 18:16:59.569 | ERROR |   | spark.webserver.MatcherFilter
10-25-2017 18:16:59.901 | ERROR |   | spark.webserver.MatcherFilter
10-25-2017 18:30:43.343 | ERROR |   | spark.webserver.MatcherFilter
10-25-2017 18:30:43.443 | ERROR |   | spark.webserver.MatcherFilter
10-25-2017 19:34:40.612 | ERROR |   | spark.webserver.MatcherFilter
10-25-2017 19:34:40.728 | ERROR |   | spark.webserver.MatcherFilter
10-25-2017 20:12:14.538 | ERROR |   | spark.webserver.MatcherFilter
10-25-2017 20:12:14.590 | ERROR |   | spark.webserver.MatcherFilter

**Comment by bwssytems** [comment]
I will need to see the log file output itself. The display does not show all details.

**Comment by vaderag** [comment]
Ah. Well, the good news is that this seems fixed now. I did a complete reboot of my hub and reconnect to the network which seemed to fix it. It didn't seem to have any issues in actually working previously tho (i.e. i could still command via Alexa skill) but either way, seemed to fix the issue :)
