### ISSUE TITLE
Domoticz server settings not saved

### ISSUE THREAD

**Issue by rmhopper** [bwssytems/ha-bridge#772]
Bridge control settings page--domoticz server entries are not saved.  Note, I do have a Vera configured as well, and those settings are saved.
Version 4.5.6 on RPi 3

**Comment by bwssytems** [comment]
Just to make sure, you hit the green add button to the right of the settings row?

**Comment by rmhopper** [comment]
Yes, I do hit the green save button, and the Bridge restarts, but the entry
disappears.  Other factors that may be at play--my HA-bridge controller is
on a different subnet than the Domoticz server (but so is my Vera), and I
don't currently have Hue-controllable devices on the Domoticz.

  --Rob

**Comment by bwssytems** [comment]
I cannot get this to occur.

**Comment by rmhopper** [comment]
OK.  It must be something unique to my environment.  When I get some time,
I will spin up another server and see if I can replicate it or hunt down
the root cause.  Thank you for checking!

 --Rob
