### ISSUE TITLE
Sonos ONE speaker (built in Alexa) doesn't find HA Bridge 4.5.6

### ISSUE THREAD

**Issue by boogiedownberlin** [bwssytems/ha-bridge#773]
I just bought a Sonos ONE speaker that has built in Alexa. I set up ha-bridge to control a Loxone smart home. All device tests are successful, however Alexa can't find HA Bridge. Meanwhile, I have the guess that this is a bug on the brand new Sonos implementation of Alexa. (The speaker is about a week on the marked). Here my data:

Bridge Control settings:
  Configuration Path and File: /home/pi/habridge/data/habridge.config
  Device DB Path and File: data/device.db
  UPNP IP Address: 192.168.1.114
  Use UPNP Address Interface Only: FALSE
  Web Server IP Address: 192.168.1.114
  Web Server Port: 80
  UPNP Response Port: 50000
  Emulate Hue Hub Version: 1705121051
  Button Press/Call Item Loop Sleep Interval (ms): 100
  Log Messages to Buffer: 512
  UPNP Strict Handling: TRUE
  Trace UPNP Calls: TRUE

Host:
  Raspberry PI 3, exclusively been used for HAB2
  OS: Raspbian Stretch Lite 4.9 (September 2017)

Router data (TPLink ARCHER VR200v):
  IGMP-Snooping: Enabled
  UPnP: Enabled
  UPnP Services (found by the router): NONE

Traceupnp: sendUpnpNotify notifyTemplate is <<<NOTIFY * HTTP/1.1
  HOST: 239.255.255.250:1900
  CACHE-CONTROL: max-age=100
  LOCATION: http://192.168.1.114:80/description.xml
  SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.19.0
  NTS: ssdp:alive
  hue-bridgeid: B827EBFFFE4759C2
  NT: uuid:2f402f80-da50-11e1-9b23-b827eb4759c2
  USN: uuid:2f402f80-da50-11e1-9b23-b827eb4759c2

**Comment by bwssytems** [comment]
Most Software Alexa's do not support the local upnp find of a Philips hue. And since the ha-bridge only mimics the local hue, this most likely will not work. Turn on trace upnp to verify.

**Comment by boogiedownberlin** [comment]
Trace upnp is on. Please check my first post!

**Comment by bwssytems** [comment]
That does not show anything but one notify and it sends 3, need more upnp log messages to verify. You should see the interaction between your devices by looking at the ip addresses.

**Comment by boogiedownberlin** [comment]
Even if I want, I cannot change the log level to trace in order to get a better knowledge of what's going on. It doesn't take (save) any change in the log level. How else can I find out?

**Comment by boogiedownberlin** [comment]
Physical Hue works with Sonos ONE/Alexa. I tried it myself. No problems at all!

**Comment by bwssytems** [comment]
For the first item, there should be more info in your log when you turn on upnp trace, it is not just one message, paste the whole log.

For the second item, The real Philips hue is found as you probably entered your account.meethue.com information which is the Philips secondary method of finding a hue device, which the ha-bridge cannot do.

**Comment by smartermyhome** [comment]
Hi,
having the same problem. Sonos one, Alexa not finding devices.
Tried already every update, but no connection to Alexa.
HA-Bridge is working so far, Test on and off is working.

Here is the log (with tracing UPNP):

11-02-2017 22:41:26.431 | INFO | Traceupnp: upnp device settings requested:  from 192.168.0.118:8080 | com.bwssystems.HABridge.upnp.UpnpSettingsResource
-- | -- | -- | --
11-02-2017 22:41:26.434 | INFO | Traceupnp: upnp device settings template filled with address: 192.168.0.114 and port: 8080 | com.bwssystems.HABridge.upnp.UpnpSettingsResource
11-02-2017 22:41:51.430 | INFO | Traceupnp: sendUpnpNotify notifyTemplate is <<<NOTIFY * HTTP/1.1  HOST: 239.255.255.250:1900  CACHE-CONTROL: max-age=100  LOCATION: http://192.168.0.114:8080/description.xml  SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0  NTS: ssdp:alive  hue-bridgeid: B827EBFFFE8AE52A  NT: uuid:2f402f80-da50-11e1-9b23-b827eb8ae52a  USN: uuid:2f402f80-da50-11e1-9b23-b827eb8ae52a    >>> | com.bwssystems.HABridge.upnp.UpnpListener
11-02-2017 22:41:51.432 | INFO | Traceupnp: sendUpnpNotify notifyTemplate is <<<NOTIFY * HTTP/1.1  HOST: 239.255.255.250:1900  CACHE-CONTROL: max-age=100  LOCATION: http://192.168.0.114:8080/description.xml  SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.15.0  NTS: ssdp:alive  hue-bridgeid: B827EBFFFE8AE52A  NT: uuid:2f402f80-da50-11e1-9b23-b827eb8ae52a  USN: uuid:2f402f80-da50-11e1-9b23-b827eb8ae52a    >>>

192.168.0.118 is my panasonic TV
192.168.0.114 is my pi3
192.168.0.120 is my Sonos one (not listet above).

Can you see anything in the log?

Thanks forwarding.
Greetings

**Comment by audiofreak9** [comment]
Please refer to the FAQs page for a list of known devices that discover the HA-Bridge devices here: https://github.com/bwssytems/ha-bridge/wiki/HA-Bridge-FAQs#device

As @bwssytems stated, "Most Software Alexa's do not support the local upnp find of a Philips hue", I believe the SONOS to have the same limitation.
