### ISSUE TITLE
Call the HA Bridge HTTP API

### ISSUE THREAD

**Issue by rhalbheer** [bwssytems/ha-bridge#774]
Hi All,
I really tried to figure it out but failed: I use HA bridge successfully to overcome Alexa's limitation with Fibaro. Great work!
I have another problem I would like to solve as well and to get there I would simply like to send an HTTP call to HA bridge to turn on a device but I did not find the respective command.
So, I would like to do something like http://HA_Bridge_IP/api/device/15/turnOn - is this possible and if yes where is the api documented?
Thank you
Roger

**Comment by bwssytems** [comment]
It's in the read me here https://github.com/bwssytems/ha-bridge#hue-rest-api-usage

**Comment by rhalbheer** [comment]
Darn, I did not get this (and I read the whole Read Me, believe me). Just as a hint: I guess it would help if you put "status" in barckets as well like http://host:port/api/<username>/lights/<id>/<state>
definitely my bad, sorry

**Comment by bwssytems** [comment]
The master document is actually available on the Philips Dev site here https://developers.meethue.com/philips-hue-api

Just register for it and you will have access, no cost.

**Comment by rhalbheer** [comment]
Me again. I now tried to make it work. The sending app is a fairly "dumb" remote. The reason why I want to take the detour with HA brdige is their inability to handle HTTP authentication (and a lot of other things). Now, the only thing I can do there is sending a simple http request (without body, just the URL). Current understanding of the http interface of HA Bridge is that I need to trigger something like http://ip/api/user/lights/123/status and in the body send the request. 
Unfortunately, my remote app does not allow this. I can just send an HTTP-request (the URL). Can I leverage the bridge for that?

**Comment by rhalbheer** [comment]
Should this work? http://ip/api/test/lights/123/state?on=true I get a 404 with anything which starts with http://ip/api/test/lights/123/state
I am on 4.5.6 - where is the mistake in my thinking? BTW, http://ip/api/test/lights/123 works 
{"state":{"on":false,"bri":0,"hue":0,"sat":0,"effect":"none","ct":0,"alert":"none","reachable":true},"type":"Dimmable light","name":"Buero","modelid":"LWB004","manufacturername":"Philips","uniqueid":"00:17:88:5E:D3:14-14","swversion":"66012040"}

**Comment by audiofreak9** [comment]
No this will not work through just a HTTP call.  The [ha-bridge follows Phillip Hue's REST API](https://github.com/bwssytems/ha-bridge#set-light-state) for turning devices on/off.

**Comment by rhalbheer** [comment]
Just FYI: What I actually wanted to do (and do know) is to extend AIO NEO Remote with more functionality from Fibaro as actually delivered by the plugin (e.g. call scenes). I now extended NEO with the Pihilips Hue Plugin and let this plugin connect to the bridge. So far works like a charm. Actually the last comment helped me to get there.
