### ISSUE TITLE
HaBridge boutton Link ne fonctionne pas lors de l'appairage Philips Hue 

### ISSUE THREAD

**Issue by teubize** [bwssytems/ha-bridge#775]
Bonjour,

je n'arrive pas a appairer le téléphone au travers Philips Hue.
j'ai tenté avec plusieurs version de HaBridge 3.5.1, 4.5.1 et 4.5.6
il ne se passe rien lorsque je clic sur Link pendant les 60 seconds du décompte pour l’appairage.

si quelqu'un as une info.

Merci

**Comment by bwssytems** [comment]
Anglais: What application for the phone are you using?

Quelle application pour le téléphone utilisez-vous?

**Comment by rafale77** [comment]
Je ne comprends pas ce que vous essayez de faire.
Le bridge est écrit pour appairer un amazon echo a un autre system en émulant un hub Philips hue. Si vous essayer d'appairer un telephone avec une appli qui s'enregistre au compte cloud de Philips, et pas en local, ca ne marchera effectivement pas.

**Comment by bwssytems** [comment]
Is there any progress on this?
