### ISSUE TITLE
Question: Running HA and Alexa on one slice of pi

### ISSUE THREAD

**Issue by itzmrdavis2u** [bwssytems/ha-bridge#78]
I have Amazon echo up and running on my Pi3 as detailed at [https://github.com/amzn/alexa-avs-raspberry-pi](url) I have also installed the ha-bridge.
Ha-bridge seems to be running fine to the point that I have added my "Mi-Lights" manually and can turn them on/off via the bridge ui. I briefly changed the port from 8080 to 80 just to connect the hue app and that connected fine.
My problem is Alexa will not find the bridge on my network when I do a search. It finds my nest thermostat fine just not the bridge.
I have tried it with upnp enabled and disabled on my router, I have removed all my devices from alexa and searched again, rebooted etc
I am beggining to wonder if it is unable to find it because both alexa and ha-bridge are on the same Pi.
is there anything you could suggest I do to try and resolve this? I would try setting up bridge on a second Pi but I only have one.
Mark

**Comment by bwssytems** [comment]
If you could turn on trace upnp and then post the log output along with the IP of your echo. That would help.

Thanks

**Comment by itzmrdavis2u** [comment]
Thanks for your response. I turned on trace upnp and the ran a search for devices from the alexa app. the ip for the echo is the same as the bridge 192.168.1.122

`03-31-2016 15:36:20.487	INFO	HA Bridge (v1.4.3) starting....	com.bwssystems.HABridge.HABridge
03-31-2016 15:36:20.524	INFO	reading from config file: data/habridge.config	com.bwssystems.HABridge.BridgeSettings
03-31-2016 15:36:20.697	INFO	HA Bridge (v1.4.3) initializing....	com.bwssystems.HABridge.HABridge
03-31-2016 15:36:20.735	INFO	System control service started....	com.bwssystems.HABridge.SystemControl
03-31-2016 15:36:21.052	INFO	HABridge device management service started....	com.bwssystems.HABridge.devicemanagmeent.DeviceResource
03-31-2016 15:36:21.281	INFO	== Spark has ignited ...	spark.webserver.JettySparkServer
03-31-2016 15:36:21.286	INFO	>> Listening on 0.0.0.0:8080	spark.webserver.JettySparkServer
03-31-2016 15:36:22.377	INFO	Hue emulator service started....	com.bwssystems.HABridge.hue.HueMulator
03-31-2016 15:36:22.397	INFO	Hue description service started....	com.bwssystems.HABridge.upnp.UpnpSettingsResource
03-31-2016 15:36:22.403	INFO	UPNP Discovery Listener starting....	com.bwssystems.HABridge.upnp.UpnpListener
03-31-2016 15:36:22.412	INFO	Traceupnp: eth0 ... has addr /fe80:0:0:0:9724:171:e14d:fd70%eth0	com.bwssystems.HABridge.upnp.UpnpListener
03-31-2016 15:36:22.418	INFO	Traceupnp: wlan0 ... has addr /fd00:0:0:1:246e:7d62:6ecf:eaf9%wlan0	com.bwssystems.HABridge.upnp.UpnpListener
03-31-2016 15:36:22.418	INFO	Traceupnp: wlan0 ... has addr /fe80:0:0:0:ba27:ebff:feb9:c344%wlan0	com.bwssystems.HABridge.upnp.UpnpListener
03-31-2016 15:36:22.419	INFO	Traceupnp: wlan0 ... has addr /192.168.1.122	com.bwssystems.HABridge.upnp.UpnpListener
03-31-2016 15:36:22.420	INFO	Traceupnp: Adding wlan0 to our interface set	com.bwssystems.HABridge.upnp.UpnpListener
03-31-2016 15:36:22.420	INFO	Traceupnp: lo ... has addr /0:0:0:0:0:0:0:1%lo	com.bwssystems.HABridge.upnp.UpnpListener
03-31-2016 15:36:22.421	INFO	Traceupnp: lo ... has addr /127.0.0.1	com.bwssystems.HABridge.upnp.UpnpListener
03-31-2016 15:36:22.421	INFO	Traceupnp: Adding lo to our interface set	com.bwssystems.HABridge.upnp.UpnpListener
03-31-2016 15:36:22.421	INFO	UPNP Discovery Listener running and ready....	com.bwssystems.HABridge.upnp.UpnpListener
03-31-2016 15:36:40.559	INFO	Traceupnp: isSSDPDiscovery found message to be an M-SEARCH message.	com.bwssystems.HABridge.upnp.UpnpListener
03-31-2016 15:36:40.560	INFO	Traceupnp: isSSDPDiscovery found message to be valid under strict rules - strict: true	com.bwssystems.HABridge.upnp.UpnpListener
03-31-2016 15:36:40.560	INFO	Traceupnp: SSDP packet from 192.168.1.101:50243, body: M-SEARCH * HTTP/1.1
 Host: 239.255.255.250:1900
 Man: "ssdp:discover"
 ST: ssdp:all
 MX: 5
 
	com.bwssystems.HABridge.upnp.UpnpListener
03-31-2016 15:36:40.561	INFO	Traceupnp: sendUpnpResponse discovery template with address: 127.0.0.1 and port: 8080	com.bwssystems.HABridge.upnp.UpnpListener
03-31-2016 15:37:10.662	INFO	Traceupnp: isSSDPDiscovery found message to be an M-SEARCH message.	com.bwssystems.HABridge.upnp.UpnpListener
03-31-2016 15:37:10.663	INFO	Traceupnp: isSSDPDiscovery found message to be valid under strict rules - strict: true	com.bwssystems.HABridge.upnp.UpnpListener
03-31-2016 15:37:10.664	INFO	Traceupnp: SSDP packet from 192.168.1.101:50243, body: M-SEARCH * HTTP/1.1
 Host: 239.255.255.250:1900
 Man: "ssdp:discover"
 ST: ssdp:all
 MX: 5
 
	com.bwssystems.HABridge.upnp.UpnpListener
03-31-2016 15:37:10.665	INFO	Traceupnp: sendUpnpResponse discovery template with address: 127.0.0.1 and port: 8080	com.bwssystems.HABridge.upnp.UpnpListener
03-31-2016 15:37:40.770	INFO	Traceupnp: isSSDPDiscovery found message to be an M-SEARCH message.	com.bwssystems.HABridge.upnp.UpnpListener
03-31-2016 15:37:40.771	INFO	Traceupnp: isSSDPDiscovery found message to be valid under strict rules - strict: true	com.bwssystems.HABridge.upnp.UpnpListener
03-31-2016 15:37:40.772	INFO	Traceupnp: SSDP packet from 192.168.1.101:50243, body: M-SEARCH * HTTP/1.1
 Host: 239.255.255.250:1900
 Man: "ssdp:discover"
 ST: ssdp:all
 MX: 5
 
	com.bwssystems.HABridge.upnp.UpnpListener
03-31-2016 15:37:40.776	INFO	Traceupnp: sendUpnpResponse discovery template with address: 127.0.0.1 and port: 8080	com.bwssystems.HABridge.upnp.UpnpListener`

**Comment by bwssytems** [comment]
So, since it is an app on the same pi, you'll need to get routing setup for local multicast as the alexa app is not getting out on multicast.

**Comment by itzmrdavis2u** [comment]
local multicast? sounds complicated looks like I have I have some googling to do then! lol. Thank you for taking a look and your quick response!!!

**Comment by kevinsickles** [comment]
I also have an Amazon Echo running on a pi using the same github project.     The ha-bridge is running on a separate pi.   my logs look similar,  UPNP starting etc but the Echo does not find the bridge.

**Comment by bwssytems** [comment]
So, the echo dev setup is not sending out a request on discover. So maybe they disabled the local discovery and only the linked home auto stuff is the only thing that works?

**Comment by itzmrdavis2u** [comment]
When I first got the echo setup and searched for devices it found my nest thermostat before I had linked any accounts so I assume the echo must have found it.

**Comment by bwssytems** [comment]
That is what I'm assuming and the local network discovery has been disabled, so no finding the Hue or bridge for that matter. Looks like you'll need a real echo.

**Comment by bwssytems** [comment]
Closing as the Alexa development does not have discovery.
