### ISSUE TITLE
getting server error 500 out of nowhere

### ISSUE THREAD

**Issue by dannieboiz** [bwssytems/ha-bridge#782]
Been working fine then all of a sudden I'm getting error 500. The devices that has been add still works but when I click on vera devices it's empty but the already configure devices populate when I click on it. please help troubleshoot this.

**Comment by bwssytems** [comment]
Will need to see the output file from the program that will have an exception in it.

**Comment by bwssytems** [comment]
What version of the ha-bridge are you using?

**Comment by michaelhinchey** [comment]
I did get the error as well.  I added my user and password and the error went away.  Worth a try

**Comment by dannieboiz** [comment]
Michael... what username/pw are you referring to?

I'm using the latest version 4.5.6 I tried to run 4.5.0 yesterday by modifying my startup script with same result. :(

**Comment by dannieboiz** [comment]
btw: Here's the log, not showing any errors unless there's another log?

`

11-14-2017 19:55:38.530 | INFO | HA Bridge (v4.5.6) starting.... | com.bwssystems.HABridge.HABridge
-- | -- | -- | --
11-14-2017 19:55:38.654 | INFO | reading from config file: data/habridge.config | com.bwssystems.HABridge.BridgeSettings
11-14-2017 19:55:40.210 | INFO | HA Bridge initializing.... | com.bwssystems.HABridge.HABridge
11-14-2017 19:55:40.222 | INFO | System control service started.... | com.bwssystems.HABridge.SystemControl
11-14-2017 19:55:40.236 | INFO | Initializing UDP response Socket... | com.bwssystems.HABridge.util.UDPDatagramSender
11-14-2017 19:55:40.252 | INFO | UDP response Seocket initialized to: 50000 | com.bwssystems.HABridge.util.UDPDatagramSender
11-14-2017 19:55:40.254 | INFO | Harmony Home created. | com.bwssystems.HABridge.plugins.harmony.HarmonyHome
11-14-2017 19:55:40.322 | INFO | == Spark has ignited ... | spark.webserver.JettySparkServer
11-14-2017 19:55:40.324 | INFO | >> Listening on 0.0.0.0:80 | spark.webserver.JettySparkServer
11-14-2017 19:55:40.608 | INFO | setup initiated .... | com.bwssystems.HABridge.plugins.harmony.HarmonyServer
11-14-2017 19:55:42.934 | INFO | activity changed: [29386065] Watch Fire TV | com.bwssystems.HABridge.plugins.harmony.HarmonyServer
11-14-2017 19:55:42.936 | INFO | Nest Home created. No Nest configured. | com.bwssystems.HABridge.plugins.NestBridge.NestHome
11-14-2017 19:55:42.936 | INFO | Hue passthru Home created. No Hue passtrhu systems configured. | com.bwssystems.HABridge.plugins.hue.HueHome
11-14-2017 19:55:42.938 | INFO | HAL Home created. No HAL devices configured. | com.bwssystems.HABridge.plugins.hal.HalHome
11-14-2017 19:55:42.938 | INFO | MQTT Home created. No MQTT Clients configured. | com.bwssystems.HABridge.plugins.mqtt.MQTTHome
11-14-2017 19:55:42.940 | INFO | HomeAssistant Home created. No HomeAssistants configured. | com.bwssystems.HABridge.plugins.hass.HassHome
11-14-2017 19:55:42.940 | INFO | Command Home for system program execution created. | com.bwssystems.HABridge.plugins.exec.CommandHome
11-14-2017 19:55:42.944 | INFO | Http Home created. | com.bwssystems.HABridge.plugins.http.HTTPHome
11-14-2017 19:55:42.946 | INFO | TCP Home created. | com.bwssystems.HABridge.plugins.tcp.TCPHome
11-14-2017 19:55:42.946 | INFO | UDP Home created. | com.bwssystems.HABridge.plugins.udp.UDPHome
11-14-2017 19:55:42.946 | INFO | Vera Home created. | com.bwssystems.HABridge.plugins.vera.VeraHome
11-14-2017 19:55:42.966 | INFO | Domoticz Home created. No Domoticz devices configured. | com.bwssystems.HABridge.plugins.domoticz.DomoticzHome
11-14-2017 19:55:42.970 | INFO | Somfy Home created. No Somfys configured. | com.bwssystems.HABridge.plugins.somfy.SomfyHome
11-14-2017 19:55:42.972 | INFO | LifxDevice Home created. No LifxDevices configured. | com.bwssystems.HABridge.plugins.lifx.LifxHome
11-14-2017 19:55:42.992 | INFO | HABridge device management service started.... | com.bwssystems.HABridge.devicemanagmeent.DeviceResource
11-14-2017 19:55:43.000 | INFO | Hue description service started.... | com.bwssystems.HABridge.upnp.UpnpSettingsResource
11-14-2017 19:55:43.006 | INFO | Hue emulator service started.... | com.bwssystems.HABridge.hue.HueMulator
11-14-2017 19:55:43.072 | INFO | UPNP Discovery Listener starting.... | com.bwssystems.HABridge.upnp.UpnpListener
11-14-2017 19:55:43.124 | INFO | UPNP Discovery Listener running and ready.... | com.bwssystems.HABridge.upnp.UpnpListener
11-14-2017 20:00:21.122 | INFO | Link button pressed.... | com.bwssystems.HABridge.SystemControl
11-14-2017 20:00:51.124 | INFO | Link button time ended.... | com.bwssystems.HABridge.LinkButtonPressed
11-14-2017 21:13:18.072 | INFO | activity changed: [-1] PowerOff | com.bwssystems.HABridge.plugins.harmony.HarmonyServer
11-14-2017 22:31:42.814 | INFO | Link button pressed.... | com.bwssystems.HABridge.SystemControl
11-14-2017 22:32:00.110 | WARN | Error calling out to HA gateway: IOException in log | com.bwssystems.HABridge.plugins.http.HTTPHandler
11-14-2017 22:32:00.110 | WARN | Error calling out to HA gateway: IOException in log | com.bwssystems.HABridge.plugins.http.HTTPHandler
11-14-2017 22:32:01.233 | ERROR |   | spark.webserver.MatcherFilter
11-14-2017 22:32:01.233 | ERROR |   | spark.webserver.MatcherFilter

`

**Comment by bwssytems** [comment]
I believe there are some issues in the http handler. These will be corrected in 5.0.0

**Comment by dannieboiz** [comment]
thanks, when can we expect to see v5 release? If u need a beta tester, I'll volunteer. It's already broken, it's not like it can be any worse. LOL

**Comment by dannieboiz** [comment]
Little update: 

Installed HA Bridge on another computer, copied the devices file over and reinitialize and it seems to be working fine over there. After I added the Vera device IP back in I can control it right out of the box. But I think my GH needs to be reconfigure to see the new Hue Device. At least this will get me going for now.

**Comment by bwssytems** [comment]
Great!
