### ISSUE TITLE
Overwrite Hue passtrough device state

### ISSUE THREAD

**Issue by ph4x0** [bwssytems/ha-bridge#784]
Hi all together,

since using Alexa to controll my Hue devices I have an anoying issue which I want to discuss now. I have an old Hue v1 bridge and I'm using only Osram bulbs, no original Philips bulbs. Please note that in Europe the Osram bulbs are using LightLink protocoll which is compatible with Hue bridge so the bulbs are working quite well. But there is one small problem when using the Osram bulbs, very often the state of the bulb is not recognized by the bridge. This is definitely no issue with ha-bridge but with Osram and Hue bridge and is well known when you google it. Most time when you completely power off the bulbs it is working some days but reoccurs every time. I know that in passthrough mode, the state of the bulb is not saved in ha-bridge but I would be happy to see such an overwrite device state feature.

Cheers

**Comment by bwssytems** [comment]
If you use the ha-bridge to control one of the bulbs through the pass thru, it will then save that state.

**Comment by ph4x0** [comment]
I don't know in which thread you wrote it but there you mentioned that the state is completely handled by the hue bridge and will just be called by ha-bridge. Whatever, I have added ha-bridge as an hue bridge in fhem and I can see all devices and the osram bulbs have no state, most time but some times it works. For the hue bridge the bulbs seams to be disconnected and this is what alexa tells me by triggering the light over ha-bridge to the hue bridge. Like I said, this is a known bug between hue bridge and osram bulbs. Just to mention it, this bug was suddenly existing and both companies don't care about it. It worked without any problems for month.

**Comment by bwssytems** [comment]
Sorry, misconstrued your intention. Your understanding is correct, when the ha-bridge returns status and it is a hue passthrough device, it queries the hue bridge for the state. Otherwise it will pass the ha-bridge known state.

**Comment by bwssytems** [comment]
@ph4x0 Is your question answered?
