### ISSUE TITLE
Cant link with echo dot - cant activate skill

### ISSUE THREAD

**Issue by dtr55** [bwssytems/ha-bridge#786]
Hi all,

I have my echo dot and when I try to activate the alexa 'Hue Skill' it link me to the 'account.meethue' website - same as when I tried this with a google home last week and then found out the configuration has been changed. 

BR - Dtr

**Comment by bwssytems** [comment]
Sorry if there is confusion, but you do not need the Hue Skill, the echo has that capability by default.. Delete that from your echo configuration and then just ask Alexa to discover devices.

**Comment by dtr55** [comment]
Hi,
Thanks for the such quick response..... TL_DR it works :)

It is slightly confusing ref the skills but I see now that the Hue skill is not needed - 
I also went into the security settings and enabled the link button,
I also had to update my webserver IP address which I set to 0.0.0.0,
I also made sure the codes worked my pressing the manual button via my browser.

My one light is now turning on and off via UDP codes - This is a great start so time to do some more testing.

Thanks - Dtr
