### ISSUE TITLE
HTTP help

### ISSUE THREAD

**Issue by holdestmade** [bwssytems/ha-bridge#789]
Hi, I have this command that works fine in chrome but not in HA, any ideas  why ?

`http://192.168.1.50:8080/jsonrpc?request={"jsonrpc":"2.0","method":"GUI.ActivateWindow","id":1,"params":{"window":"videos","parameters":["\"LIBRARY://VIDEO/EMBY/C8CA023CDBB96C78E4DE5FCB477DF512/ALL.XML\",RETURN"]}}`

This one works fine:
`http://192.168.1.100:50701/?macro=30`

Using a HTTP device with no options selected

Thanks

**Comment by bwssytems** [comment]
Well, this is a bit tricky. You will need to quote and escape quote the quotes. Json interprets those specifically. Turn on debug for the HueMulator class as it will dump out what it is interpreting.

**Comment by holdestmade** [comment]
Tried it in an online "escape tool" and got this warning in the logs:

**Comment by holdestmade** [comment]
Tried it in an online "escape tool" and got this warning in the logs:

`Error creating URI http request: http://192.168.1.50:8080/jsonrpc?request={\"jsonrpc\":\"2.0\",\"method\":\"GUI.ActivateWindow\",\"id\":1,\"params\":{\"window\":\"videos\",\"parameters\":[\"\\\"LIBRARY:\/\/VIDEO\/EMBY\/C8CA023CDBB96C78E4DE5FCB477DF512\/ALL.XML\\\",RETURN\"]}} with message: Illegal character in query at index 41: http://192.168.1.50:8080/jsonrpc?request={\"jsonrpc\":\"2.0\",\"method\":\"GUI.ActivateWindow\",\"id\":1,\"params\":{\"window\":\"videos\",\"parameters\":[\"\\\"LIBRARY:\/\/VIDEO\/EMBY\/C8CA023CDBB96C78E4DE5FCB477DF512\/ALL.XML\\\",RETURN\"]}}`

**Comment by holdestmade** [comment]
Solved it, used HTML formatter online:

http://192.168.1.50:8080/jsonrpc?request=%7B%22jsonrpc%22%3A%222.0%22%2C%22method%22%3A%22GUI.ActivateWindow%22%2C%22id%22%3A1%2C%22params%22%3A%7B%22window%22%3A%22videos%22%2C%22parameters%22%3A%5B%22%5C%22LIBRARY%3A%2F%2FVIDEO%2FEMBY%2FC8CA023CDBB96C78E4DE5FCB477DF512%2FALL.XML%5C%22%2CRETURN%22%5D%7D%7D

**Comment by bwssytems** [comment]
perfect
