### ISSUE TITLE
Question: Talking to a serial port over the bridge

### ISSUE THREAD

**Issue by N8XS** [bwssytems/ha-bridge#79]
I have an older Denon receiver (AVR-3805) that I can control via serial port. It takes simple ASCII commands like:

MV35<CR> - Set main volume to 35dB
SIDVD<CR> - Set input source to DVD
TP02<CR> - Switch to tuner preset 02

I have a USB serial adapter giving me a serial port at /dev/ttyUSB1

What would be a clever way to send a short series of pre-configured ASCII commands to this receiver using the ha-bridge? 

I'm thinking:
Alexa, tell serial VOLUME UP (increase volume)
Alexa, tell serial VOLUME 35(set volume to 35)
Alexa, tell serial PLAY DVD (switch to DVD and change volume)

**Comment by bwssytems** [comment]
I'll take a look. I believe in Java, an external library is needed for serial ports.

**Comment by N8XS** [comment]
Found a possible solution:

http://chilipeppr.com/serialport#com-chilipeppr-widget-serialport-connect

I have been able to see the receiver's status update over the serial port after installing the server. So far, I cannot send commands to the receiver, but that might be a simple permissions issue.

**Comment by bwssytems** [comment]
That is an interesting system, You could do this without any coding on the ha-bridge as you would just call the webserver port on the SPJS and send the command.

**Comment by bwssytems** [comment]
I am assuming this is working with something like SPJS.

**Comment by bwssytems** [comment]
No response, assuming this subsystem works.
