### ISSUE TITLE
Previously working - will not connect to Hue bridge

### ISSUE THREAD

**Issue by Lorccan** [bwssytems/ha-bridge#790]
I've got a real (square) Hue bridge that was previously working fine with HA Bridge, but now I can't get it to connect.

I've tried rebooting (the bridge and the RPi), pressing the link button, but all I get is this in the logs:

```
Nov 15 19:32:06 milos java[5353]: 2017-11-15 19:32:06,283 [qtp547206-16] INFO  com.bwssystems.HABridge.SystemControl - Link button pressed....
Nov 15 19:32:08 milos java[5353]: 2017-11-15 19:32:08,463 [qtp547206-21] WARN  com.bwssystems.HABridge.plugins.hue.HueInfo - registerWithHue needs link button pressed on HUE bridge: Hue Bridge
```

Any suggestions what I can try please?

**Comment by bwssytems** [comment]
You need to press the real hue link button, then hit the hue devices tab on the ha-bridge.

**Comment by Lorccan** [comment]
That did it.  Thank you.  I don't remember doing it before.
