### ISSUE TITLE
service masked after install

### ISSUE THREAD

**Issue by carcamerarig** [bwssytems/ha-bridge#792]
Hi Ive run into an issue where the service is masked and failed to start, could you help me fix the issue please?
root@raspberrypi:~# sudo su
root@raspberrypi:~# touch /etc/systemd/system/habridge.service
root@raspberrypi:~# chmod 664 /etc/systemd/system/habridge.service
root@raspberrypi:~# cd /etc/systemd/system/
root@raspberrypi:/etc/systemd/system# nano habridge.service
root@raspberrypi:/etc/systemd/system# systemctl start habridge.service
Failed to start habridge.service: Unit habridge.service is masked.
root@raspberrypi:/etc/systemd/system# systemctl enable habridge
Failed to enable unit: Unit file /etc/systemd/system/habridge.service is masked.
root@raspberrypi:/etc/systemd/system# systemctl status habridge.service -l
● habridge.service
   Loaded: masked (/etc/systemd/system/habridge.service; masked; vendor preset: 
   Active: inactive (dead)
lines 1-3/3 (END)

**Comment by bwssytems** [comment]
You need to do a 'systemctl daemon-reload'

**Comment by carcamerarig** [comment]
Could you explain to me how to do that please?

**Comment by carcamerarig** [comment]
Could do with a little guidance if you could please, im actually stuck in the directory i think but dont know how to get back out and carry on. Could you help me? 
![screen shot 2017-11-17 at 14 49 21](https://user-images.githubusercontent.com/33754742/32953050-ea1d7fae-cba6-11e7-869d-4898d70c927a.png)

**Comment by carcamerarig** [comment]
root@raspberrypi:/etc/systemd/system# systemctl daemon-reload
root@raspberrypi:/etc/systemd/system# systemctl start habridge.service
Failed to start habridge.service: Unit habridge.service is masked.
root@raspberrypi:/etc/systemd/system# systemctl enable habridge
Failed to enable unit: Unit file /etc/systemd/system/habridge.service is masked.
root@raspberrypi:/etc/systemd/system#

**Comment by bwssytems** [comment]
you will need to do 'systemctl unmask habridge.service'. you can google systemctl on how to do this. Also you can google how to change to a directory in linux....

**Comment by carcamerarig** [comment]
Thanks for the advice, i have the bridge running and the test buttons turn
lights on and off. The echo discovered the bridge / lights and the echo
accepts the commands on or off but they dont change the state of the
lights?? I have the echo app on the iphone and that does change the state
of the lights when on or off button is pressed. Any idea what the issue
will be or what i have failed to configure?
Thanks J

Many Thanks

Justin Edgington.
Visit us: Car camera Rig <http://www.carcamerarig.com>
Email us: justin@carcamerarig.com
Follow us at: Facebook <http://www.facebook.com/carcamerarig>
<https://t.yesware.com/tl/dad779841ffb3b81069864ab6998c13136d2450e/dcc8913a0f61ad65d65ebdfcba0ea0cc/6500a1c8ee38c6efce36ee12187ff131?ytl=http%3A%2F%2Fwww.facebook.com%2Fcarcamerarig>
Call us: +44 (0) 7973 746192

**Comment by carcamerarig** [comment]
I followed Corey's write up and all seems well, the Echo discovered the
bridge for the lights and accepts commands but doesent actually change the
state of the X10 module. When the X10 module is in the off state the Echo
cant respond.
here is the bridge server log.

[{"id":"1","uniqueid":"00:17:88:5E:D3:01-01","name":"drive_lights","mapType":"cmdDevice","deviceType":"exec","offUrl":"[{\"item\":\"heyu
off A14\",\"type\":\"cmdDevice\"}]","dimUrl":"[{\"item\":\"heyu dimb A14
${intensity.percent}\",\"type\":\"cmdDevice\"}]","onUrl":"[{\"item\":\"heyu
on
A14\",\"type\":\"cmdDevice\"}]","inactive":false,"noState":false,"offState":false,"description":"drive
lights","deviceState":{"on":true,"bri":254,"hue":0,"sat":0,"effect":"none","ct":0,"alert":"none","reachable":true}}]

does this look right or have i not configured it correctly?

**Comment by audiofreak9** [comment]
Corey, aka audiofreak9 here: 

This entry as an X10 device looks good.  Would you happen to be "Justin", who [posted nearly the same issue in the comments on my blog](http://coreyswrite.com/electronics/home-automation/amazon-echo-x10-home-control-updated/comment-page-11/#comment-1448)?  If so we can continue this over on my blog, and I posted a reply question.

**Comment by carcamerarig** [comment]
Hey Corey indeed, 
That would be great.

**Comment by carcamerarig** [comment]
Left another reply on your blog Corey ;)

**Comment by bwssytems** [comment]
Closing as this is now onto a different topic. You can still use this to post when closed

**Comment by audiofreak9** [comment]
Thanks, I should have closed it, I moved this discussion to my blog.
