### ISSUE TITLE
habridge cannot see my Nest install

### ISSUE THREAD

**Issue by jouster1974** [bwssytems/ha-bridge#794]
HA bridge has been set up and is allowing me to control Servers via WOL calls and also.  Im also able to see my Logitech Harmony Hub and its relevant services/activities/devices.

I am however having issues seeing/gaining access to any Nest devices.  I am using the nest username/password section where the input takes the format of   xxxxxxxxx@gmail.com and password but when I go to the nest Tab on HAB, the values never and nothing is input

Everything else so far is working well

**Comment by bwssytems** [comment]
Will take a look

**Comment by jouster1974** [comment]
fantastic...

**Comment by bwssytems** [comment]
Testing this and it seems to work properly. I had a bad setup for my credentials, but after that, it is working properly.

**Comment by bwssytems** [comment]
@jouster1974 Any update on this?

**Comment by jouster1974** [comment]
hi there.  they weren't showing when I logged in last (a day or so ago) and retested my credentials...but logging in now, I can now see my Nest Thermostats (but not Protects)...so this is great.

Now I am wondering if there is any ability to call the hot water heating functions via the bridge (I have both a V2 and a V3)

This is NOT available via Alexa at all yet and to my knowledge has to be done via the app...but that would make my Nest setup complete.  Neither Nest nor Amazon seem to making any attempt to sort this out which is a shame

**Comment by bwssytems** [comment]
Protects will not show up in the ha-bridge only Thermostats and the home/away function.
