### ISSUE TITLE
Harmony Hub - access to created sequences

### ISSUE THREAD

**Issue by jouster1974** [bwssytems/ha-bridge#795]
With a Harmony remote, you are able to create sequences on the soft touch buttons on the Harmony remote itself.  

I think this is a moot point as its not ON the hub itself, but Im wondering if there is any way to access these sequences to attach to the HABRIDGE?

**Comment by bwssytems** [comment]
I have not looked if there is any update on the api, but the last time I checked it was not there.

**Comment by jouster1974** [comment]
Many thanks.
