### ISSUE TITLE
discovered but pairing failed

### ISSUE THREAD

**Issue by bance** [bwssytems/ha-bridge#798]
[habridge_log.txt](https://github.com/bwssytems/ha-bridge/files/1498945/habridge_log.txt)

running 5.0.0 on RPi 3 with a third-party speaker device. the HA Bridge setup was discovered as a Hue Hub. during the pairing process, user was asked to press the link button, which I enabled and clicked in HA Bridge, but pairing still got failed after timing-out. logs are attached. any suggestion would be greatly appreciated.

**Comment by bwssytems** [comment]
Interesting, logs like an Ali call is not being hacked properly. Dis this work fine in 4.5.6?

**Comment by bwssytems** [comment]
Any update on this?
