### ISSUE TITLE
Alexa Not Finding Raspberry Pi

### ISSUE THREAD

**Issue by lessphiling** [bwssytems/ha-bridge#80]
I was able to get ha-bridge installed, my two harmony hubs discovered, and setup to start on boot. However my echo can't find the devices. Below are my logs.

`04-02-2016 17:13:16.564	INFO	HA Bridge (v1.4.3) starting.... com.bwssystems.HABridge.HABridge

04-02-2016 17:13:16.729	INFO	reading from config file: data/habridge.config	com.bwssystems.HABridge.BridgeSettings

04-02-2016 17:13:17.123	INFO	HA Bridge (v1.4.3) initializing....	com.bwssystems.HABridge.HABridge

04-02-2016 17:13:17.249	INFO	System control service started....	com.bwssystems.HABridge.SystemControl

04-02-2016 17:13:36.981	INFO	== Spark has ignited ...	spark.webserver.JettySparkServer

04-02-2016 17:13:36.990	INFO	>> Listening on 0.0.0.0:8080	spark.webserver.JettySparkServer

04-02-2016 17:13:37.757	INFO	setup initiated ....	com.bwssystems.harmony.HarmonyServer

04-02-2016 17:13:42.102	INFO	activity changed: [-1] PowerOff	com.bwssystems.harmony.HarmonyServer

04-02-2016 17:13:42.109	INFO	setup initiated ....	com.bwssystems.harmony.HarmonyServer

04-02-2016 17:13:44.245	INFO	activity changed: [19384030] Watch TV	com.bwssystems.harmony.HarmonyServer

04-02-2016 17:13:44.309	INFO	HABridge device management service started....	com.bwssystems.HABridge.devicemanagmeent.DeviceResource

04-02-2016 17:13:44.732	INFO	Hue emulator service started....	com.bwssystems.HABridge.hue.HueMulator

04-02-2016 17:13:44.751	INFO	Hue description service started....	com.bwssystems.HABridge.upnp.UpnpSettingsResource

04-02-2016 17:13:44.756	INFO	UPNP Discovery Listener starting....	com.bwssystems.HABridge.upnp.UpnpListener

04-02-2016 17:13:44.791	INFO	UPNP Discovery Listener running and ready....	com.bwssystems.HABridge.upnp.UpnpListener
`

**Comment by bwssytems** [comment]
I will need you to turn on trace upnp in the settings as that will log what is happening when you try to do a discover from the echo. Also, sometimes the router upnp config has issues if the router upnp is turned on.

**Comment by lessphiling** [comment]
I have an airport extreme, I can't find a trace upnp option. After waiting about 24 hours the echo found the bridge and found my harmony activities but it won't turn them on/off

**Comment by emiliosic** [comment]
@lessphiling Apple routers do not have UPnP. They use a different method: NAT-PNP. https://en.wikipedia.org/wiki/NAT_Port_Mapping_Protocol
I'm running Echo, Fire TV, Logitech Harmony hub and ha-bridge running on a Linux VM with no issues; with a network with two Apple routers (one is a Router and another is an access point).
Note that on the Linux VM running ha-brigde, disabled the firewall, SELinux and enabled Avahi.
Avahi is the UPnP service for Linux. I'm running CentOS 7.2
Never had any noticeable delay detecting or responding to commands with ha-bridge.

**Comment by bwssytems** [comment]
So, you have the discovery done, but no contact to the bridge from the echo.... I got an email from another who is experiencing this issue but it only started 2 days ago. Turn on DEBUG for com.bwssystems.HABridge.hue.HueMulator in the Logs page and post any output from an on/off call from the echo...if there is any.

**Comment by lessphiling** [comment]
So the echo was able to control my living room harmony hub but not the bedroom. I did test on/off with the bedroom from the bridge webpage but saying "Alexa, turn on the bedroom TV" didn't work. Here's how the device is setup in the bridge and i've attached the logs for asking from the echo and the test from the bridge page.

Row ID 			Name 		Type 	Target Actions
1	639834684	Bedroom TV	activity	Bedroom

[habridgelog.txt](https://github.com/bwssytems/ha-bridge/files/205063/habridgelog.txt)

**Comment by bwssytems** [comment]
So, for turning on debug, do not use ROOT, lick the show all loggers and set only this one com.bwssystems.HABridge.hue.HueMulator to DEBUG, make sure anything else is set to INFO.

**Comment by shadygrady** [comment]
I am the guy the had the similar issue. My "device" was found on my alexa app after discover but wasnt communicating. I was able to test that the device was working from the ha bridge configuration page, but  I'd get a "no device" sound from the echo whenever I issued a verbal command. After 3 days of scratching my head I figured out how to fix it on my end. I set up a "dummy" device as recommended, reinitialized the bridge, and re-discovered on the echo. Afterwards, I gave it some verbal commands and realized that it was communicating to the new device. So, I deleted all of my devices from the ha bridge and from the echo (discovered devices), added them again on ha bridge, and re-ran discovery on the echo. It now works. Somehow the echo must have been getting confused. Hope this helps anyone that comes across this issue. Thank you bwssystems for the help and quick responses to emails!!

**Comment by lessphiling** [comment]
I haven't tried deleting everything and starting over again but I did change the log settings and when I tried triggering the bridge from my echo I didn't get anything new in the logs.

**Comment by shadygrady** [comment]
I would try deleting all, adding devices, reinitialize, and rediscover on the echo. Also make sure to use a simple recognizable name as your device name. I previously had mine as "my highlander" but now only "car or truck" seem to work.

**Comment by shadygrady** [comment]
Make sure to delete the old discovered devices in your alexa app too

**Comment by lessphiling** [comment]
Now we're back to square one where the echo doesn't see the bridge. Here are the logs

hue lights list requested: hm3JnxYjJAKVDx8OkGQZwk1UKTwslVGKn0or5N29 from 10.0.1.179	com.bwssystems.HABridge.hue.HueMulator
04-07-2016 14:28:23.832	DEBUG	hue lights list requested: hm3JnxYjJAKVDx8OkGQZwk1UKTwslVGKn0or5N29 from 10.0.1.179

**Comment by shadygrady** [comment]
If you change any device parameters (ie..name), make sure you re-initialize the bridge?

**Comment by lessphiling** [comment]
Yup, did that

**Comment by bwssytems** [comment]
If the echo doesn't see the bridge, we need to use the trace upnp setting to see those log messages

**Comment by bwssytems** [comment]
For issues with calling devices, I just went into my amazon developer account and looked at all the updates to the Amazon Skill Set and they have updated it with new capabilities last week and specifically to the SmartHome area. So, now it will be a new thing to figure out how to name your devices so that the Echo responds properly. IT is nothing that I can change on the bridge as this is all Amazon services in the Cloud.
Modify message

**Comment by lessphiling** [comment]
An update, I tried getting the echo to recognize the bridge today and it found it. I'm not sure if the commands are working with the hub that was having a problem before I need to troubleshoot some more. But at least it found it, not sure why it took a couple days to be found.

**Comment by bwssytems** [comment]
So, I am going to close this. Amazon Echo software update is the issue it seems.
