### ISSUE TITLE
5.0.0 no longer connects to the vera

### ISSUE THREAD

**Issue by rafale77** [bwssytems/ha-bridge#800]
Upgraded to 5.0.0 using my 4.5.6 database and none of my existing devices work when I test them from the bridge.

I get this error"
`Request Error, Please look in your habridge log: error {"type":"3","address":"/groups/1488527247","description":"resource, /groups/1488527247, not available"}`

Downgraded back to 4.5.6 and it works again. Not sure what I am missing here.

**Comment by bwssytems** [comment]
Could you put your config here and a step by step on how you create this issue? Thanks.

**Comment by bwssytems** [comment]
So, do you have device ids that are greater than 10000? If so, do a renumber devices and have echo forget and rediscover.

**Comment by rafale77** [comment]
Oops sorry, forgot to reply. Do you mean device Ids on the Vera? Then no. On the bridge? I have never had an ID below 10000.

The step by step? From my working 4.5.6 configuration, I downloaded the 5.0.0 jar file. Stopped the 4.5.6 instance and started the 5.0.0. Open the web UI for the bridge and test on and off various Vera devices which were previously setup. None works.

**Comment by bwssytems** [comment]
Since many versions ago, if you hit the "Renumber Devices" button in the Bridge Devices Tab, it will renumber them starting at 1. To get this to work, you need to do this as a feature for groups which you don;t use is interferring due to the numbers being above 10000. You will have to have your alexa forget all devices and rediscover for it to find the devices after renumbering.

**Comment by rafale77** [comment]
ok, It is a tedious task for me to renumber and reconfigure Alexa. I have too many groups. I will stick with 4.5.6 for now until I have a need to move to 5.x.x

**Comment by bwssytems** [comment]
@rafale77 How many devices do you have in Alexa for the ha-bridge? If it is a small enough number, you can forget each of them individually and keep all of your other settings and the rediscover will only find the newly renumbered ha-bridge devices.

**Comment by rafale77** [comment]
I have over a hundred with ~groups...

**Comment by bwssytems** [comment]
Ahh, it's the groups created in Alexa using those devices. Well, we may consider the group feature optional in the ha-bridge so this does not happen.

**Comment by rafale77** [comment]
Well only partially. I am grouping from the Alexa interface because I also have some mixed groups: Vera devices through the bridge and other devices through other skills. Adding grouping in the bridge would only help partially and one could even create scenes in the vera to group the vera devices. I think it is a bit redundant though the value would come in play if several interfaces were being controlled by the bridge itself which I am sure some people have. I am trying to keep as simple as possible so I keep the grouping at the highest level instead of having multiple levels of grouping.

**Comment by bwssytems** [comment]
Sorry for the confusion, what I meant was that a switch would have to be used to turn on the new feature in the ha-bridge which is giving you problems so that it would not affect your system.
