### ISSUE TITLE
Fibaro scenes are not created

### ISSUE THREAD

**Issue by inwaar** [bwssytems/ha-bridge#801]
When "Build item" button is clicked on a fibaro scene an error in console appears and fields on "Add/edit" are not filled.

![image](https://user-images.githubusercontent.com/3331076/33187281-6e6b9966-d099-11e7-9b4e-a15c7c4dcc38.png)

Looks like an invalid json that can not be parsed.
![image](https://user-images.githubusercontent.com/3331076/33187298-89c53726-d099-11e7-99c9-ba918d2bb1b6.png)

**Comment by bwssytems** [comment]
We will take a look.

**Comment by bwssytems** [comment]
Bug that occurred with merge of color enhancement
