### ISSUE TITLE
Echo 2. Generation wont find HA Bridge

### ISSUE THREAD

**Issue by einmalacht** [bwssytems/ha-bridge#802]
Hello together,
i updated my echo dot second generation to a new Echo device.
But the echo wont find my HA Bridge devices.
When i connect the dot then all devices were found and they are controllable from both Echo devices.
But when i disconnect the dot ... the HA Bridge devices are gone on the Echo.
I resetet the Echo many times but im not able to find the HA Bridge :-(

**Comment by michbeck100** [comment]
the port must be 80

**Comment by matchy2** [comment]
me too

**Comment by bwssytems** [comment]
Pleas turn on trace upnp in the bridge control panel and send me your log.

**Comment by bwssytems** [comment]
This is a duplicate of #810, Put any other info in that issue.
