### ISSUE TITLE
Error with Groups

### ISSUE THREAD

**Issue by darrenmcuk** [bwssytems/ha-bridge#804]
I am getting the following error:

Error reading the file: data\group.db - Does not exist or is not readable. continuing...

Does this mean anything? and how do I fix it.

**Comment by rems02** [comment]
Hi,
I'm a same error

**Comment by bwssytems** [comment]
No issue, it is just saying that config file is not there.

**Comment by ozett** [comment]
sorry for bringing this up again, 
but the answer ist not really fully satisfying.

i have still this error with v5.2.1, but how to solve it?

does habridge creates the group.db by itself?
is it needed? do i have to create group.db?
do is ==need== group.db?

**Comment by audiofreak9** [comment]
No the HA-Bridge currently does not create this file.  This is not an error/issue, the `[WARN]  Error reading the file: /home/pi/habridge/data/group.db - Does not exist or is not readable. continuing...` is just letting you know the group.db was not present and is being skipped.

**Comment by ozett** [comment]
thanks for explanation. 👍 

someone must have put this warning in, maybe for some reason.

and now log-reading puzzles me with this waring: so should i create the file?
or should the coder make an option in the gui, to ommit such irritation for some people, who look into the log from time to time 😵 ?

but now i now know: ignore warnings.. 
anyway: ha-bridge: 👍 
and thanx for answer on an old topic

**Comment by audiofreak9** [comment]
@ozett 
The group.db file was coded and merged into this project.  You can search closed issues for the discussion of use of group.db.  With the Alexa app allowing the creation of groups it's a null for most.

**Comment by ozett** [comment]
thanks audiofreak9 for clearing this up.

i searched closed issues and found the explanation here: 
https://github.com/bwssytems/ha-bridge/pull/712

i put the link in for further reference, as i like solutions a the end of threads. 😃 
thankx again.
for me this issue here can be considered closed again. 😸
