### ISSUE TITLE
Fibaro HomeCenter2: Devices "Build Item" broken

### ISSUE THREAD

**Issue by mol7os** [bwssytems/ha-bridge#805]
Devices of Fibaro Homecenter are collected well and Listed including parameters in HA-Bridge.
When I try to "Build Item" nothing happens.

After a while clicking and many luck I get into the "edit form" but its completly empty.
Saving ends in no result. Bridge Item will not be saved.

Bridge Version 5.0.0

LOG Message: The requested route [/(null)] has not been mapped in Spark for Accept: [null]
LOG Component: spark.http.matching.MatcherFilter

LOG Message: The requested route [/description.xml] has not been mapped in Spark for Accept: [application/json, text/plain, */*]
LOG Message:  Error reading the file: /home/pi/.habridge/data/group.db - Does not exist or is not readable. continuing...

**Comment by inwaar** [comment]
I can confirm the same behavior but for scenes in #801, perhaps the same bug.

**Comment by bwssytems** [comment]
Similar to #801

**Comment by bwssytems** [comment]
See #801
