### ISSUE TITLE
Duplicate devices in Alexa since 5.0.0

### ISSUE THREAD

**Issue by mol7os** [bwssytems/ha-bridge#806]
Hi,

in Alexa I can find now duplicates of devices.

Every Device will also listed as "Royal Phillips Electronics intelligent device" and as "dimmable light".

If I activate the flag "inactive" to hide actions/scenes (devices) in HA-Bridge the "dimmable light" device will be marked as offline in Alexa (or not discovered in scan). The Royal Phillips doesnt care.

Didn´t find any option to stop this behavior.

**Comment by mniebel** [comment]
.... however .... my homebridge caused this issue.

**Comment by mniebel** [comment]
Getting carzy ... the Royal Phillips devices must come from HA-Brigde.
I renamed some devices to be sure. And they will be listed in Alexa.

It doesnt matter:
- ... if i switch back to 4.5.6 Version
- ... set inactive to devices
- ... shut down HA-Bridge

Alexa discover this devices also when HA-Bridge is stopped ... (FYI: Alexa Echo2 is new to my installation)

**Comment by bwssytems** [comment]
You will need to forget the devices that are from the U.S.-bridge and then rediscover them.

**Comment by mol7os** [comment]
Thanks for your quick response.

It sounds like "Royal Phillips Electronics intelligent device" are the U.S.-bridge devices (rights).
How should I "forget this devices" when discovered again and again. 
Is there any special option I need to enable, or do i need to ignore the doubled devices?

**Comment by bwssytems** [comment]
Sorry, some how the U.S.-bridge was supposed to mean you r ha-bridge.

So, go into the echo control panel for your smart devices and forget them all and do a rediscover.

**Comment by bwssytems** [comment]
Any other info on this?

**Comment by mol7os** [comment]
Not really.

The old Echo and Echo Dot discovers the expected and configured devices from HABridge.
The new Echo2 discovers every device (it does not matter if flagged as inactive) as "Royal Phillips Electronics intelligent device".

Option "Forget All", or "Forget item" doesn´t help.

Everything is working - but with many devices in HABridge you have a mass in Alexa which is confusing.

**Comment by bwssytems** [comment]
Unfortunate;y, there is some configuration in your environment that is causing this. Multiple interfaces exposing the api or muleiple ha-bridges running.

**Comment by mol7os** [comment]
Running on Raspberry PI 3 Debian stretch. Only one interface.
For me it looks like something with UPNP ...
But i didn´t had this bahavior with Version 4 and no ECHO 2.

**Comment by bwssytems** [comment]
This may be an issue with some redirect code that was in the ha-bridge. The next version changes that and that it may help with this issue....

**Comment by bwssytems** [comment]
Please try the new release 5.1.0 https://github.com/bwssytems/ha-bridge/releases/tag/v5.1.0

**Comment by bwssytems** [comment]
Any update on this after trying 5.1.0?

**Comment by mol7os** [comment]
No chance to check before weekend. But I will try 5.1.0 soon as possible and provide a feedback.

**Comment by mol7os** [comment]
Looks ok for me now. Every Bridge Device listed only one times.

**Comment by mol7os** [comment]
Sorry to fast,
in first scan ist seems to be ok. 
But no i checked again in Alexa Web and its still the same behavoir.

![image](https://user-images.githubusercontent.com/26004218/34297119-8448f100-e716-11e7-8ba5-a6e60c79c6a4.png)

![image](https://user-images.githubusercontent.com/26004218/34297132-95d4ff72-e716-11e7-8772-6ecdc991a668.png)

Additonal i have some devices listed which are not up to date and in my opinion already removed past weeks. I cannot find this device in my HABridge. But its discovered by Alexa.

Example: 
![image](https://user-images.githubusercontent.com/26004218/34297171-dd594d1c-e716-11e7-9af9-fc0e0b2fcc0b.png)

Absolutly no idea. I have only one HA-Bridge running now on Vers. 5.1.0

**Comment by bwssytems** [comment]
@mol7os Do you have a real hue hub as well?

**Comment by mol7os** [comment]
Yes i have a hue bridge 2.0.

**Comment by bwssytems** [comment]
So you are exposing your Philips lights with the ha-bridge, you need to use one of the other for those devices, I would leave the bus lights on the bus hub only.

**Comment by Nomar383** [comment]
I'm having the same issue on 5.1 and 4.5.6. In the docker container or in a Ubuntu VM. Duplicate Royal devices all of the sudden.

I do not have a physical hue bridge and I have only one instance of habridge running.

**Comment by bwssytems** [comment]
@Nomar383 Then it will be network setup with docker.

**Comment by mol7os** [comment]
I dont think so.
Everything was fine till i added a "new Echo" into my environment.

With old Dot & Echo the devices were listed as expected. If i switch back to a special port (ex. 8081) everything is fine. In this case only the old Echo Dot is able to discover.

There is something wrong/changed in the discovery with new Echo Devices.
For me it feels like the HA.Bridge provides some old cached data. There must be an issue in exchanging device information with the new 2017 Alexa devices.

**Comment by Nomar383** [comment]
I added an echo spot recently. Not sure if that has anything to do with it.

I have killed the docker altogether and I'm now strictly using an Ubuntu
16.04 VM with only HA Bridge 4.5.6 installed. I changed the port to 8081. I
still had the extra Royal devices showing up. I manually forgot each Royal
device and they haven't come back. I suspect if I do a "Discover All" I
will see them again though...

**Comment by bwssytems** [comment]
@mol7os Are you using docker?

**Comment by mol7os** [comment]
No, my current setup runs on a debian stretch.

But I had a installation running well in docker under 4.5.6 without new Echo devices. (port 8081)
I switched to a dedicated Raspberry before adding Echo 2 in my environment.

Echo2, Echo Spot, Echo Plus does something different discover devices as the old once ....

**Comment by audiofreak9** [comment]
@bwssytems 

FWIW, I too am experiencing the duplicate devices, since adding an Echo Spot.  I have:  an Echo Gen 1, 3 Dots (mixed gens), an Echo Show and an Echo Spot.  However here is what I am noticing, all Echos but the Spot discover and configure the ha-bridge devices as **"Dimmable Light"**, the Spot discovers and configures the devices as **"Royal Philips Electronics smart device"** all else being the same.

**Comment by bwssytems** [comment]
Interesting, so Amazon has different characteristics for different device firmware. So, that will not be fixable by the ha-bridge. But, since there are 2 devices looking for the ha-bridge, you could use the ip address filter for the devices and then it would only respond to one of them.

**Comment by audiofreak9** [comment]
Just after posting above, I went to the Alexa Webpage and Forgot all the "Dimmable Light" devices.  I did discovery with all my Echos, the app and the webpage one at a time.  The duplicates have not returned.  At this point all devices are listed as "Royal Philips Electronics smart device".  I know there was a software update for the Alexa app and webpage yesterday.  Maybe there was a device software update too?  i don't track the software version numbers for date of change to know.

**Comment by dpullen-fml** [comment]
I have seen the same problem. My duplicates started when I added Echo Dots (2nd Gen). The Echo Show and Echo (2nd Gen) appeared to produce devices listed as "Royal Philips Electronics smart device". The Echo Dots introduced the "Dimmable Light". I have tried forgetting the devices (each type) and forgetting "all" but they all return. The Dots have sw 597465220. The Echo is 595530420 and the Show is 597464020.

**Comment by kandlg** [comment]
I was having this issue consistently and noticed the earlier posts about different Amazon devices.  I have a  Show, Tap, Original Echo, 2nd gen Echo, original Dot, 2nd gen Dots.  I removed the original dot from service about a week ago and haven't had the issue since.

**Comment by bwssytems** [comment]
So, has this still been happening?

**Comment by kandlg** [comment]
It happened once during the last echo firmware update, but other than that no.

**Comment by heikoh81** [comment]
Still happening here with 1x Echo Show, 2x Echo 2017 and 2x Echo dot 2017.
1 HA Bridge running on port 80 on Raspi 2, Lan, static IP.
No original Philips Hue in the House.

**Comment by heikoh81** [comment]
Shouldn't the different Echos cooperate?
They are all in the same prime account, in the same LAN...

**Comment by kandlg** [comment]
Have you identified which Alexa systems report different source names?  It would be helpful if you could post that in an FAQ since it is a recurring issue.  I have a Show, Tap, Original Echo, 2nd gen Echo, original Dot, 2nd gen Dots (~2016 when they first came out).  Taking the original Dot offline seems to have fixed my duplication issues, so that one would seem to be different.  I find it interesting that current mix of devices are all consistent, despite being mixed generations.  Heikoh81's experience suggests maybe a 2017 dot is different?

Further info, I have a hue bridge on a rasp version 3 and a real hue.

**Comment by mol7os** [comment]
I can confirm that the problem is still there and it's annoying.
Among other things I already have:

IPtables excured my HUE Bridge
IPtabels 2 Echo Dot 1st generation UDP prohibited (should prevent discovery)
On the PI all interfaces deactivated and only eth0 with fixed IP

and so on, finally nothing solved the issue.... its really annoying.

**Comment by mol7os** [comment]
Removed all Skills from Alexa and unplug HA-Bridge, Hue-Bridg ... everything ....

Alexa discovers everything including doubled devices .... from where .... a bad joke!

**Comment by mol7os** [comment]
Hi,

/etc/iptables/rules.v4

:INPUT ACCEPT [392:47811]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [290:56603]
-A INPUT -m iprange --src-range 10.0.0.243-10.0.0.250 -p udp -j DROP /
-A INPUT -m iprange --src-range 10.0.0.243-10.0.0.250 -p tcp --dport 80 -j ACCEPT 
-A INPUT -m iprange --src-range 10.0.0.243-10.0.0.250 -p tcp -j DROP
-A INPUT -s 10.0.0.24/32 -j DROP
COMMIT

All Echo and UPNP devices will have fix IPs to limit communication to HA-Bridge.
I have some more rules as shown in example. Many devices cache UPNP information and it feels like some of them have bad TTLs. (I excluded for example every FireTV, QNAP, HueBridge .... in communication to HAB).

My Echo Dot1 devices discover HA-Bridge (IPs 10.0.0.240-242), Echo2 cannot discover (10.0.0.243-250 cause of iptables), in Example you find additional .24 which is my HueBridge.

This fixed my communication with Alexa Service and prevent stupid doubled discovery for me.

**Comment by mol7os** [comment]
There is already a file on your HA-Bridge Rasperry (or docker, whatever).
Only add your lines. (-A INPUT  ....)
The commit line stands at the end. The order (lines) presents the priority .
First hit wins:
Example:
-A INPUT -m iprange --src-range 10.0.0.243-10.0.0.250 -p tcp --dport 80 -j ACCEPT
-A INPUT -m iprange --src-range 10.0.0.243-10.0.0.250 -p tcp -j DROP

ALL TCP is not allowed after Port 80 TCP is allowed. If you change the order of this lines you never get access to port 80 TCP. Place the rules based on hit priority top down.

**Comment by heikoh81** [comment]
So, for my two echos with IPs .240 and .245, is the follow correct?

-A INPUT -m iprange --src-range 192.168.178.2**4**0 -p tcp --dport 80 -j ACCEPT
-A INPUT -m iprange --src-range 192.168.178.2**4**0 -p tcp -j DROP
-A INPUT -m iprange --src-range 192.168.178.2**5**0 -p tcp --dport 80 -j ACCEPT
-A INPUT -m iprange --src-range 192.168.178.2**5**0 -p tcp -j DROP

**Comment by popy2k14** [comment]
Hey guys, i also have this issue with the duplicate devices.

I have the following echo devices:
3x Echo 1st Generation (192.168.0.230 and up)
2x echo dot 2nd Generation  (192.168.0.240 and up)
2x echo show 5  (192.168.0.240 and up)

Which one of those should ill let the discovery do and which to block?

I am running ha-bridge on raspbian buster and sadly there is no iptables.
There is the replacement nftables.

Any guide how to set it up?
(already googled, but hell the nftables is complicated for a noob like me :-)

Hope you can help me.
thx

**Comment by popy2k14** [comment]
I think i have solved it in raspbian buster 👍 

I am using ufw because its easier than fiddling around with iptables.
First install it:

`sudo apt install ufw`

Now allow all incomming traffic (default is deny!!!!)
`sudo nano /etc/default/ufw`

Change the DEFAULT_INPUT_POLICY to ACCEPT:
`    DEFAULT_INPUT_POLICY="ACCEPT"`

Save the file with CTRL-X and y + ENter
Reopen and ensure that ACCEPT was saved!
Otherwise you could lock yourself out of the RPI (ssh)!

Enable the ufw:

`sudo ufw enable`

Status should look like:

```
pi@rfhem-pi:/etc/ufw $ sudo ufw status verbose
Status: active
Logging: on (low)
Default: allow (incoming), allow (outgoing), disabled (routed)
New profiles: skip

```

Add Rules to block upnp discover of the echos!

```
sudo ufw deny proto udp from 192.168.0.240 to any
sudo ufw deny proto udp from 192.168.0.241 to any
sudo ufw deny proto udp from 192.168.0.242 to any
sudo ufw deny proto udp from 192.168.0.243 to any
sudo ufw deny proto udp from 192.168.0.244 to any
sudo ufw deny proto udp from 192.168.0.245 to any
sudo ufw deny proto udp from 192.168.0.246 to any
sudo ufw deny proto udp from 192.168.0.247 to any
sudo ufw deny proto udp from 192.168.0.248 to any
sudo ufw deny proto udp from 192.168.0.249 to any
sudo ufw reload

```

Check Rules:

```
pi@rfhem-pi:~ $ sudo ufw status verbose
Status: active
Logging: on (low)
Default: allow (incoming), allow (outgoing), disabled (routed)
New profiles: skip

To                         Action      From
--                         ------      ----
Anywhere                   DENY IN     192.168.0.240/udp
Anywhere                   DENY IN     192.168.0.241/udp
Anywhere                   DENY IN     192.168.0.242/udp
Anywhere                   DENY IN     192.168.0.243/udp
Anywhere                   DENY IN     192.168.0.244/udp
Anywhere                   DENY IN     192.168.0.245/udp
Anywhere                   DENY IN     192.168.0.246/udp
Anywhere                   DENY IN     192.168.0.247/udp
Anywhere                   DENY IN     192.168.0.248/udp
Anywhere                   DENY IN     192.168.0.249/udp

```

To delete a rule use:

`sudo ufw delete 3`

In my case its working, have hit forget all and search a few times.
Also from android app and until now -> now double entries :-)

**Comment by popy2k14** [comment]
Sadly the duplicates are back :-( any hints...
