### ISSUE TITLE
Update Home Assistant State

### ISSUE THREAD

**Issue by TheCellMC** [bwssytems/ha-bridge#807]
Would it be possible to have the state of my Home Assistant lights update in the HA Bridge?

**Comment by FloFoer** [comment]
This has been discussed before [here](https://github.com/bwssytems/ha-bridge/issues/762)  

To sum it up: HA-Bridge doesn't keep track of your Home Assistant device states, it does so only for hue passthrough devices. For everything else the state gets only updated if you control the device through HA-Bridge.  
However, if you can edit you HASSIO devices to execute an additional HTTP command you could notify HA-Bridge that the state has changed like [described here](https://github.com/bwssytems/ha-bridge#update-bridge-internal-light-state)
