### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by drhill** [bwssytems/ha-bridge#81]
Trying to setup for the first time on my ubuntu server to control my Harmony via the echo.  I downloaded the jar because I couldn't build because I didn't have java 1.8, but then I had to update to 1.8 anyway.  I also tried building from source.  How do I specify the port to use?  There is no default config file to change and I have other things running on the server.

**Comment by drhill** [comment]
I modified the server port in Configuration.java and rebuilt from scratch.  All good now.

**Comment by bwssytems** [comment]
This is a good reason to put a command line override for the port.
