### ISSUE TITLE
Echo Second Edition not discoverying  HA bridge 5.0.0(synology) 

### ISSUE THREAD

**Issue by haymaan** [bwssytems/ha-bridge#810]
hallo,
i was enjoying the Habridge(4-5-6) synology ver in combi with Alexa DOT 2,and every thing works fine,,,,
after update to Echo Second Gen it's not detecting the HA bridge,i've update the bridge to 5-0-0,and still not working ,HA bridge working fine throught compuer/mobile.....

i have Synology and use poort 8088 for the bridge,that was not a probleem with Dot 2...please help

**Comment by michaelhinchey** [comment]
Try port 80









    Every dream is a goal with a date on it; if you can conceive it believe
it, you can achieve it. Don't let anyone steal your dream. Make the
decision to take a positive attitude, take pride in yourself and what you
do, work hard and stay with it. A mind is a terrible thing to waste.


"I felt bad because I couldn't wheelie; until I met a man with no bicycle"

"You are young at any age... if you are planning on tomorrow"

**Comment by haymaan** [comment]
thanks will try that ...

**Comment by bwssytems** [comment]
Did port 80 solve your issue?

**Comment by haymaan** [comment]
No still the same problem ,are there any other with this problem??

**Comment by varguello** [comment]
Exact same issue with my brand new Echo 2nd gen. Echo Dot works fine. Once Echo Dot has sent a successful request to the device my Echo 2nd gen seems to find it for a while but "forgets" it again. Habridge is running on Synology DS214play on port 81.

**Comment by bwssytems** [comment]
So, I will need you to turn on trace upnp and do a discover with the 2nd gen Echo and post the entire log.

Thanks

**Comment by varguello** [comment]
Here it goes:
[traceupnp.txt](https://github.com/bwssytems/ha-bridge/files/1515781/traceupnp.txt)

**Comment by bwssytems** [comment]
I assume  the 2nd gen echo is IP 192.168.5.171. It looks like it asks for the description.xml but does not use that information to go get the lights list. For fun, does the 2nd gen echo work with 4.5.6?

**Comment by haymaan** [comment]
No it's even not working with 4.5.6....
thanks

**Comment by varguello** [comment]
I can confirm it too. It doesn't work on 4.5.6. The trace is basically the same (aside from different formatting). The echo 2nd gen does not query the hue lights.
[traceupnp-4.5.6.txt](https://github.com/bwssytems/ha-bridge/files/1519792/traceupnp-4.5.6.txt)

**Comment by bwssytems** [comment]
Well, this is not good. So they changed some interpretation on querying info from the description.xml.

**Comment by haymaan** [comment]
thanks for the reply ,is there any way that can fixed ..?

**Comment by bwssytems** [comment]
It will take some research as this would be a reverse engineering endeavor.

**Comment by bwssytems** [comment]
Anyone with a 2nd gen Echo and a real philips hue that could do a trace on messages used during discover on the philips hue? There must be something in the update hue description.xml that is needed.

**Comment by NorthernMan54** [comment]
@bwssytems I just started playing with this in my setup, and it appears to only respond to Hue devices on port 80.  Have you tried that?

I'm dealing with a similar V2 issue, with the hue emulator I built into homebridge.  https://github.com/NorthernMan54/homebridge-alexa/issues/32

**Comment by cw-kid** [comment]
I have been using an Echo DOT OK with HA-Bridge for sometime, recently I also added a gen 2 Echo. 
I then later decided to buy several Google Home speakers instead (Also not working with HA-Bridge either) .

So I unregistered and removed the gen 2 Echo. However seems since then, that the original Echo Dot which I plan to keep, now no longer detects any devices from the HA-Bridge. 

I was running HA-Bridge on port 8087 on my Windows server, I have just tried running it on port 80 instead but the Echo Dot is still not detecting devices. 

I dare not press the Forget All devices button in case none of them come back. 

Tried HA-Bridge 4.5.6 and just updated it to 5.0.0.

So has temporarily adding a gen 2 Echo device to my setup, now broken the original Echo Dot from being able to add devices from the HA-Bridge ? 

Thanks

**Comment by cw-kid** [comment]
I have managed to get my Echo Dot to discover devices from HA-Bridge now. But seems I have to do things a bit differently than before though. 

Previously I was using a gen 1 Hue bridge. Two days ago I migrated to a new gen 2 Hue bridge. It now seems I have to power off the real Hue bridge before discovering devices in the Alexa app.

Also now it seems you have to set the HA-Bridge to port 80 as well. As when the bridge is set to my regular port number it does not work and Alexa will not find any new devices. 

Once Alexa had discovered the new devices off the HA-Bridge I then changed the port number back from 80 to my regular port number I use and then nothing works, I wasn't able to turn on or off any devices from the Alexa app. 

So seems HA-Bridge now needs to be on port 80 all the time. I cannot do this on my Windows server as I have another service on port 80. 

So time to run HA-Bridge on a Raspberry Pi or use something else instead of HA-Bridge. 

Also since updating to HA-Bridge 5.0.0 I am seeing loads of these messages constantly. 

"The requested route [/(null)] has not been mapped in Spark for Accept: [null]"

**Comment by cw-kid** [comment]
Can you specify which IP address HA-Bridge should run on ? 

Thinking maybe I could add a second IP address to my Windows server and have HA-Bridge run on port 80 on that secondary IP address. 

Thus allowing port 80 on the primary IP address to still be used for the webserver.

**Comment by bwssytems** [comment]
@cw-kid Make sure you didn't use the web server address feature in the ha-bridge, that would prevent it from binding to the correct interface. Also, it seems that Amazon has now updated the echo software across the board to only go to port 80 from what you have shown.

**Comment by cw-kid** [comment]
I kinda messed up my WHS 2011 server a bit today trying to get this working. 

I added a secondary IP address and I changed the HA-Bridge to start up with this new IP and also that it should use Port 80.

In IIS for the Default Website aka the WHS 2011 remote access page, Port 80 was binded to All unassigned IP addresses. I changed this to only use the first IP address of the server. 

I was then able to access HA-Bridge, on the new secondary IP address and on port 80.

However I was then unable to also access the WHS 2011 RWA page via the servers first IP address on port 80 / 443. The page wouldn't load. 

So I couldn't seem to get both running on different IPs but both using port 80 etc. 

I have currently set everything back to how it was before I started and rebooted the server. This has fixed the WHS 2011 RWA page but HA-Bridge still isn't working. 

In fact now for some reason whatever port I specify for HA-Bridge it now never seems to stay running, it goes through the motions of starting up but then just vanishes and isn't running. So think I have really broken HA-Bridge now.

**Comment by cw-kid** [comment]
If I rename the data folder to data.old and create a new blank data folder HA bridge starts again now, so must have messed up my original data folder ? 

I've managed to use one of the backup config files and it looks like I did have the "Web Server IP Address" and "Web Server Port" populated. 

I should leave these blank I guess and just specify the IP and Port in my startup batch file.

**Comment by cw-kid** [comment]
I give up I cannot get HA bridge to run on port 80 on the WHS 2011 server and also have the server run its stuff on port 80 also, even with two IP addresses and messing about with bindings in IIS. 

Now switching to Vera's native skill for Alexa instead as that wasn't available when I first setup HA-Bridge. 

Thanks

**Comment by haymaan** [comment]
why closed there is no way to get it works ... ?

**Comment by happyhammers** [comment]
Any closer to finding a fix, I've tried port 80 still no luck. I can not get my gen 2 echo to see bridge. Cheers Dave

**Comment by cw-kid** [comment]
Power off your real Hue bridge as well, I had to do that also before my Echo Dot / Alexa web app would discover devices from the HA-Bridge.

Can't comment on actual gen 2 Echo devices as haven't got one now.

**Comment by bwssytems** [comment]
@haymaan It's not closed, it is a reference to an other issue that was a duplicate that is closed

**Comment by NorthernMan54** [comment]
@bwssytems I have a Echo 2nd generation and the Hue V1 hub ( round ) and am still looking at this.  So far I have found that my code gets stuck on the /api/username/light/# response.  I'm sending the response, which is copied from my V1, but it m my echo just repeats the request.  Tomorrow I'm going to confirm if my echo 2nd generation does  work with my Hue V1.  If that doesn't work then it may be a Amazon defect.

**Comment by avenantsoftware** [comment]
I just bought an echo dot version 2, and noticed that alexa doesn't discover the ha bridge, but when you ask alex: discover devices, and then under 'bridge control" => "bridge reinitilize", if you do this when alexa is trying to discover your devices, then alexa finds it...

**Comment by haymaan** [comment]
i'll try it tonight thanks

**Comment by bwssytems** [comment]
Please try the new release 5.1.0 https://github.com/bwssytems/ha-bridge/releases/tag/v5.1.0

**Comment by smorks** [comment]
5.1.0 worked right away for me with my echo dot 2nd gen. thanks for the quick fix!

**Comment by Ordep** [comment]
Are you using a specific port? How are finding new devices? (Voice, app, web)
I have the echo 2nd gen, but didn't work. I'm might be doing something wrong though.

**Comment by cw-kid** [comment]
So do you still need to use port 80 with version 5.1.0 of HA bridge?

**Comment by cw-kid** [comment]
Appears to be working again now on ports other than 80. My HA Bridge is on port 8087 and I have updated the Bridge to version 5.1.0. In the Alexa web app I forgot all devices and re-discovered them. It has now added back in devices from the HA-Bridge !

**Comment by Ordep** [comment]
I'll try to use the webapp instead of the app and forget all devices before re-discover them.

Wasn't working for me this morning in any port, but probably was because I haven't removed all existent devices (non ha-bridge)

**Comment by Andi1927** [comment]
I tried it also with the Web app and port 8080 on a synology but doesn´t work with my 2.end Edition of Echo. Maybe I make something wrong.

**Comment by cw-kid** [comment]
I only have an Echo Dot not a gen 2 Echo. You might need to still use port 80 for that to work.

**Comment by michbeck100** [comment]
@cw-kid echo dot always worked. just test with the new Echo (2nd gen)

**Comment by cw-kid** [comment]
It wasnt working the other day unless Ha bridge was on port 80 and also the real hue bridge powered off.

**Comment by haymaan** [comment]
still not working even with 5.1.0 ,,
hope will it fix soon

**Comment by Andi1927** [comment]
For me it is working Echo and echo dot both 2nd gen. It works since 5.1.0.
Port 8080
So thanks for the good job

**Comment by haymaan** [comment]
Which device you use for HAbridge??

**Comment by Andi1927** [comment]
I use a Synology with Docker.

**Comment by Ordep** [comment]
I'm nearly throwing the towel in.

Could someone take a look at my log file and see if something odd?
[output.log](https://github.com/bwssytems/ha-bridge/files/1564963/output.log)

**Comment by firecube** [comment]
My new echo show doesn't detect either but, as I read on another thread, if I plug my version 1 dot in too then the devices are detected and the show can control them.

**Comment by bwssytems** [comment]
@Ordep What is the ip address of your echo?

**Comment by Ordep** [comment]
> @Ordep What is the ip address of your echo?

@bwssytems 192.168.1.134

**Comment by bwssytems** [comment]
So, the echo goes through the whole upnp process correctly, asks for the list of lights and then asks for light 1 (which is patio in your case). Then it seems to go through searching for the bridge again..... I am at a loss here too. Maybe it is not liking what is in the return of the light request. Will take a look and see if there was a change in the Philips API.

**Comment by NorthernMan54** [comment]
I was looking at this in detail as well, and found that it did go thru all my devices and stopped.  What I did see that was odd, was that the echo had 2 threads talking to my code.   One went thru the devices, and the other just asked for the description.xml and closed 13 seconds later.

My thinking is that the echo is calling one of the hue cloud API’s to check or validate something during the 13 seconds and that fails.  Causing the discovery to fail.   I did go so far as to use the exact response from my V1 hub as the response in my code, to downplay any API issues.

I also have a V1 round hue hub, and it works with the echo.

**Comment by bwssytems** [comment]
@NorthernMan54 Just to make sure I understand, in your Homebridge plugin for Alexa, it stops after it gets the device list and the fist device as well?

**Comment by NorthernMan54** [comment]
No, it goes thru all the lights and stops.  ( the full device list ). 

When I compared it to my Dot, it goes thru the lights, then the groups.

**Comment by bwssytems** [comment]
@NorthernMan54 Interesting. Maybe a little network snooping will need to be in order.

**Comment by NorthernMan54** [comment]
Where are you thinking of snooping between?  Echo and my code or echo and the internet?   I was thinking about that, and trying to see if what else the echo is talking to during device discovery.  And looked at the Philips API, which is https transport. And realized the most i might see is a ssl handshake.

It would prove my theory, but not get us any farther ahead.

I was actual thinking about going the skill based approach.

**Comment by bwssytems** [comment]
@NorthernMan54 I do not have a 2nd gen echo so I am out for testing. And yes, snooping the echo IP and probably just the http packets would be the way to go.

**Comment by NorthernMan54** [comment]
Okay, I can do that but am away for a week.

**Comment by bwssytems** [comment]
@NorthernMan54 No problem, we all do what we can when we can..... Thanks!

**Comment by roberteinhaus** [comment]
In a probably related case I had problems after throwing in a second echo. Everything was working well with my existing configuration with the two echos both able to use ha bridge devices until I added a new device to my configuration and started a new device discovery. It said it was not able to find any new devices. From then on, even the older, previously working devices were not working anymore.
Even after removing the new device and restarting the bridge several times I could not search for devices or use the old ones.
However I was able to fix it by disconnecting the second echo. Then I was able to find new devices and use them. Afterwards I reconnected the second echo and now I am able to use all the previously found devices.

**Comment by bwssytems** [comment]
@roberteinhaus That would be due to one of the echo's being a second gen.

**Comment by bwssytems** [comment]
Please go test RC version in #863

**Comment by NorthernMan54** [comment]
@bwssytems I spent a few hours trying to figure out how to sniff this.  I was able to easily look at what was going thru my router from my echo gen 2, and didn't see anything except calls to the amazon cloud servers while running discovery.  I'm still trying to get a sniff going on my wifi network to see if I can see anything else interesting.

**Comment by bwssytems** [comment]
@NorthernMan54 another reported issue in another thread gets the 2nd gne echo to the point of requesting the lights list, but then does not do anything after that. Another mention here was the discovering of scenes from the echo app then doing a discover devices.

**Comment by chrismillsuk** [comment]
Hi I have ha-bridge 5.1.0 installed on raspberry pi and after a few initial issues is working fine with echo plus , echo (2nd Gen) and 2 x echo dot(2nd gen) all in the same network.

When I started out with ha-bridge I only had the echo plus and I couldn’t get it to discover devices but I found if I did discover scenes, followed by discover devices from the app it worked. Since then if I delete all my devices in the app and ask any of the echos to discover my devices it finds all 6 ha-bridge devices.

**Comment by chrismillsuk** [comment]
I made a mistake the home bridge version is 5.0.0

**Comment by NorthernMan54** [comment]
@bwssytems Well I know a lot more about about sniffing WiFi networks then I did 2 weeks ago, but am no further ahead.  ( Pro tip for sniffing a 2.4 and 5ghz network, your devices may hop networks so shut down one prior to sniffing. ).   I see it getting the lights list, then the individuals lights then nothing.  I think this is stuck until someone can discover what we are missing.

I did see some odd things with my hue v1 hub.  First it is using http 1.0, and second my echo 2nd generation has stopped talking to it.  It was working previously, but something changed to stop it.  My dot still works with it okay.

**Comment by Pontihog67** [comment]
Hi,

I have been trying for 4 days to get the Echo to find the bridge. I am on port 80. I have purchased an Echo 2 dot that was just delivered today in hopes that could find the bridge, but no luck.

Can anyone assist with getting this to work for me? I am trying to use Alex10 on Windows with the bridge and the creator of Alex10 has tried to help me and referred me here.

I am just using X10 modules and a Bond ceiling fan interface. Alexa finds the Bond ceiling fans but not the bridge.r

I saw the messages in the closed thread about adding a scene, but I am unfamiliar with how to do that.

Any help will be greatly appreciated.

Thanks
Ponti

**Comment by bwssytems** [comment]
So far, there have been mixed reports on Echo 2nd Gen working. It seems you may have to wait until a software update comes to your 2nd Gen Echo and unfortunately, there is no control over when that occurs.

**Comment by Pontihog67** [comment]
Thank you,

I tried again this morning and for the first time I got a screen about pairing my lights (can't remember everything it said) but it still said no devices found) Never had that screen before.

I guess I have to wait for an update as I'm not sure how to add a scene (even if I can with just X10).

Thanks for the help

**Comment by bwssytems** [comment]
So V5.2.0 is out there and it has an update for upnp sending. Please try and see if your echo 2nd gen is working now.

**Comment by Pontihog67** [comment]
No luck with V5.2.0 on my end.  Both my Echo 2nd gen and Dot 2nd gen cannot find any new devices with this update.

**Comment by bwssytems** [comment]
@Pontihog67 Please check in the bridge control tab what the upnp send delay is set to?

**Comment by Pontihog67** [comment]
@bwssytems  upnp send is set to 650

**Comment by bwssytems** [comment]
Try 500 and if that is not working go up to 1000 and see what happens.

**Comment by Pontihog67** [comment]
@bwssytems  Tried 500 and 1000 and Alexa did not discover my bridge.  Tried from the app also.

**Comment by Pontihog67** [comment]
@bwssytems  Tried 500 and 1000 and Alexa did not discover my bridge.  Tried from the app also.

**Comment by bwssytems** [comment]
Just finished testing my Echo 2nd Gen and it finds the ha-bridge. One caveat for all of you out there. If you have 'Use Link Button' turned on in your security settings, you still need to hit the link button to get it to pair.

**Comment by Pontihog67** [comment]
Still no luck here.  Must be something I'm doing wrong.  I can click on the bridge on and off and my my units will cycle on and off.   My firewall is open for java, but my echo 2nd gen will not find them.

Thanks for all of your help

**Comment by bwssytems** [comment]
No skills needed. It seems the 2nd gen is just a bit trickier on the discovery.

My scenario that seems to work:

** Make sure you have enabled the  'Use Link Button' in the ha-bridge security settings!

1) start discover on Alexa
2) press the link button on the ha-bridge 'Bridge Devices' tab
3) most likely this discover will not find anything
4) start discover on Alexa again
5) press the link button on the ha-bridge 'Bridge Devices' tab
6) after Alexa finishes, you should see your devices or new devices added

**Comment by Pontihog67** [comment]
@bwssytems  Still no luck,  I guess it just won't work with my version.  
Thanks for all your help anyway.

**Comment by bwssytems** [comment]
@Pontihog67 One last thing to try is going down to 100 for the upnp send delay

**Comment by Pontihog67** [comment]
@bwssytems  Oh well, no luck with that either.  Has anyone else reported any success over the last couple of days?

Thanks again

**Comment by bwssytems** [comment]
@Pontihog67 There have been successes all along. I have a 2nd gen and it is working fine. Others have had success when I added the send delay. You may have other issues. Turn on traceupnp and try it and send the log and the ip address of your echo

**Comment by Jenjis486** [comment]
It happens the same to me.
I have HA-Bridge installed in a Docker container in a Synology
The configuration of HA-Bridge is 192.168.1.10 and port 8080.
The echo dot 2 has the ip 192.168.1.35

[ha-bridge.log](https://github.com/bwssytems/ha-bridge/files/1807633/ha-bridge.log)

**Comment by Pontihog67** [comment]
@bwssytems   Do I turn on Trace UPNP Calls by clicking the false box?  

I'm really not sure where to find the log file other than the log tab, but it doesn't look like the ha-bridge.log that is in the message above.

**Comment by bwssytems** [comment]
@Jenjis486 Port 8080 is not the suggested port to use. Please change it to 80. 

@Pontihog67 The logs in the log tab will be fine. Jut cut and past it into a text file, then post.

**Comment by bwssytems** [comment]
@Jenjis486 You have an issue with your setup where it is using the 10.8.0.0 network.

**Comment by Pontihog67** [comment]
@bwssytems   The bridge is running on 192.168.1.236  The echo is 192.168.1.122  The echo dot 192.168.1.171.

[habridgelog.txt](https://github.com/bwssytems/ha-bridge/files/1808667/habridgelog.txt)

**Comment by Jenjis486** [comment]
I can not use port 80 because Synology uses it, so I want to use port 8080
The 10.8.0.0 network is my vpn access to the computer, but the local network is 192.168.1.0

**Comment by bwssytems** [comment]
@Jenjis486 Well the first problem is your ha-bridge is picking up your VPN address, this needs to be configured in the settings to be your local ip address. https://github.com/bwssytems/ha-bridge/wiki/Trouble-Shooting#q-echo-does-not-discover-my-ha-bridge

**Comment by bwssytems** [comment]
@Pontihog67 You still need to turn on trace upnp in the Bridge Control Tab first. Then do a discover after so it generates the trace messages.

**Comment by Pontihog67** [comment]
@bwssytems. I guess you missed my question before.  Not sure how to turn it on, I just see a clickbox for "false" for Upnp trace.  Do I tick that?

Thanks

**Comment by bwssytems** [comment]
Yes

**Comment by Pontihog67** [comment]
@bwssytems 

I'll try again

[habridgelogmarch14.txt](https://github.com/bwssytems/ha-bridge/files/1813184/habridgelogmarch14.txt)

**Comment by bwssytems** [comment]
@Pontihog67 you have this error:
```
03-14-2018 17:26:52.188 	WARN 	The upnp config address, localhost, does not match any known IP's on this host. 	com.bwssystems.HABridge.BridgeSettings

```
So you did not follow the troubleshooting faq. You still need to set your upnp config address to the ip of your host, 192.168.1.236.

**Comment by Pontihog67** [comment]
Missed that!   That was it, Thanks for all the help

**Comment by bwssytems** [comment]
@haymaan Is your issue resolved?

**Comment by haymaan** [comment]
Still can't discover any thing....change my HAbridge from Synology to raspberry no success

**Comment by bwssytems** [comment]
@haymaan please read the trouble shooting faq referenced above and install version 5.2.0

**Comment by haymaan** [comment]
Okey I'll reinstall and read it again..
Thanks will keep you updated

**Comment by Jenjis486** [comment]
He realizado una instalación limpia en una Raspberry (192.168.1.11), donde he instalado Domoticz y HaBridge, este en el puerto 80.
Sigo teniendo el mismo problema. Te adjunto el fichero de logs.
Puede ser que tenga un problema en mi Echo Dot 2. Lo compre en UK, pero lo tengo funcionando en España?
[habridge-log.txt](https://github.com/bwssytems/ha-bridge/files/1814600/habridge-log.txt)

**Comment by Jenjis486** [comment]
Sorry,

I have done a clean installation on a Raspberry (192.168.1.11), where I installed Domoticz and HaBridge, this on port 80.
I'm still having the same problem. I attached the log file.
Maybe I have a problem with my Echo Dot 2. I buy it in the UK, but I have it working in Spain?

[habridge-log.txt](https://github.com/bwssytems/ha-bridge/files/1814601/habridge-log.txt)

**Comment by bwssytems** [comment]
@Jenjis486 I will assume the echo dot you have is on IP address 192.168.1.10. So you will need to try the steps in the Trouble Shooting faq for using the link button. It is the 5th bullet point in https://github.com/bwssytems/ha-bridge/wiki/Trouble-Shooting#q-echo-does-not-discover-my-ha-bridge

**Comment by Jenjis486** [comment]
No. The ip 192.168.1.10 in the NAS Synology, the IP of Echo Dot 2 is in the IP 192.168.1.35 and the HaBridge server in the IP 192.168.1.11.
When reviewing the log file, I have not seen this IP ask.
I do not know if it's configuration of my Echo Dot 2

**Comment by bwssytems** [comment]
@Jenjis486 Interesting, the echo dot is not even asking. This should happen. Is there some network settings to check on your router such as allowing upnp traffic?

**Comment by bwssytems** [comment]
@Jenjis486 This also needs to be considered if on a synology https://github.com/aptalca/docker-ha-bridge/issues/13

**Comment by originaltacos** [comment]
Hi everybody,
 
  I have the same problem. HA-Bridge running on a Synology NAS on port 8081 (Port 80 is already used) without docker. Try everything from the trouble shooting guide except the Port 80 because I can't. My Echo dot (second gen) can't find the bridge. I'm running version 5.2.1. 

Here the logs
[Log.txt](https://github.com/bwssytems/ha-bridge/files/1821875/Log.txt)

**Comment by butsify** [comment]
Hi,

I run HA-Bridge 5.2.1 on a raspberry on port 80. I also tried the troubleshooting guide (IGMP off, UPNP on, 2x search,...), changed the UPNP delay, enabled the link button, recreated the device (currently, I just have one for testing) and still can't find the device in the Alexa app.

Under Manage Links, there is a Echo entry: 

Echo#192.168.188.67 | 2018-03-18T20:28:20

I already removed it again, retried to find devices and the entry was there again.

Echo IP: 192.168.188.67 PI IP: 192.168.188.62

The device works in the web UI. 

Logs (tried to find devices 3x this time):
[habridge-log.txt](https://github.com/bwssytems/ha-bridge/files/1823060/habridge-log.txt)

Thank you!

**Comment by Jenjis486** [comment]
I have several Philips Hue that has detected the Echo Dot 2 without any problem.

The only thing I have not managed to do is add Ha-Bridge, neither the Synology with Docker (port 8080), nor in the Raspberry (port 80).

I'm going to install a network analyzer and review the IP frames.

But reviewing the comments, I see that this problem we have enough users. In my case the Echo Dot buy it in the UK, although I use it in Spain, but configured with UK address

**Comment by bwssytems** [comment]
@Jenjis486 It seems your issue is about networking. Currently, all 2nd gen device issues are resolved. One question for you, are you trying to control a device on a remote network?

**Comment by bgeneto** [comment]
Just to let you know guys... my problem with ha-bridge v5.2.1 and echo dot 2nd gen not working was the firewall (iptables, in my case). Even after running on port 80, upnp delay set to 100, "Use link button" turned on, allowed tcp/udp ports 80 and 50000 etc... the discovery from Alexa app didn't work. I had to allow all traffic in my subnet in order to getting the devices recognized by echo dot 2. As this imposes a (small) security risk, I still would like to know the exact rules/ports needed to ha-bridge in order to communicate successfully with Amazon echo devices... Great job anyway.

**Comment by Jenjis486** [comment]
Good morning, I continue with my tests.
I installed Ha-Bridge on a raspberry (192.168.1.11) on port 80 and I have the Echo Dot 2 (192.168.1.35). When analyzing traffic on the raspberry using tcpdump, I do not see Upnp UDP discovery frames sent by the Echo (port 1900).
Other discovery frames of other computers are seen on the network, so the network is not cutting off that traffic.
All security is disabled.
I have set the Echo factory, so I do not know what else I can do.
I have the Echo configured in the UK, with my Amazon account in the UK.
If it occurs to you that can happen to me, I would appreciate it.
Regards,

**Comment by Jenjis486** [comment]
The only thing I do is set up the computer remotely, through a tunnel from my office, but I do the same from home and it does not work either.
The Echo Dot 2 discovered a Philips Hue gateway without problem.

**Comment by bwssytems** [comment]
@Jenjis486 So, Still confused here. IS your echo in a physical location at a home in the UK while your raspberry Pi is in a location in Spain over a bridged network?

**Comment by Jenjis486** [comment]
No. Alexa has not arrived in Spain. I bought the Echo DOt 2 in the UK; but I have it installed in Spain, in the same physical location as the raspberry.
The Echo is connected by Wifi and the raspberry by cable to a router Aus RT-AC1200G +.
I have registered the Echo in the Amazon account of UK to be able to use it and in that account I have the UK address. Yesterday I was resetting factory, but I could not finish the configuration.

**Comment by bwssytems** [comment]
@Jenjis486 Please post your ha-bridge.conf

**Comment by haranewbie** [comment]
Hi guys, so I tried using the latest version of habridge with my Echo gen 2 bought in India and it did not discover devices. However, when I reverted to the older version (v3.5.1) I was able to discover devices. I haven't run any debugging but the biggest difference in terms of settings is with respect to the server.ip. In v3.5.1 I am using the following command at startup to run: 

> nohup /storage/java/bin/java -jar -Dconfig.file=/storage/data/habridge.config -Dserver.ip=192.168.1.7 /storage/ha-bridge-fibaro.jar

and in the latest I had to use this to run habridge

> nohup /storage/java/bin/java -jar -Dconfig.file=/storage/data/habridge.config -Dserver.ip=192.168.0.69 -Dserver.port=80 /storage/ha-bridge-fibaro-latest.jar

Not sure if this is helpful in anyway but I thought I should share this here..

**Comment by haranewbie** [comment]
Hi guys, I have faced similar problems in getting Echo Gen 2 (India) to work with ha-bridge. However, I recently stumbled onto a solution. When I reverted my ha-bridge version to v3.5.1 (which was originally installed on my pi) from v.5.2.0 my Gen 2 Echo was able to discover devices immediately. I changed the installed version a couple of times more and the behaviour has been consistent - discovery works on v3.5.1 and fails on the latest.

**Comment by bwssytems** [comment]
@Jenjis486 You synology habridge is running on port 8080. Try port 80. Does your Pi habridge work properly?

**Comment by Jenjis486** [comment]
No. I have the same problem as Synology. I have Ha Bridge configured on the Raspberry, connected to Dmoticz, and I can not get my Echo Dot 2 to recognize any signal

**Comment by bwssytems** [comment]
@Jenjis486 If you would please, turn on tracupnp on your Pi and post the logs.

**Comment by bwssytems** [comment]
@Jenjis486 Also, don't forget the discovery while traceupnp is on....

**Comment by sarge31** [comment]
Is it possible to get a copy of a successful log showing a successful discovery.  I don't get an devices listed in Alexa however it does allow me to control the devices added in haBridge with voice (dot 2).  I'm assuming that it has discovered the devices but I just cant see them listed in Alexa.  New to all this btw so apologies if I'm missing something.

**Comment by bwssytems** [comment]
@sarge31 So you do not see them in the alexa app or the alexa web page under smart home devices?

**Comment by sarge31** [comment]
@bwssytems  Correct.  They do not appear in the devices under smart home (app or web page) but are definitely recognised when I tell alexa to turn them on or off.  I originally thought this was how it was meant to be since there was no skill associated but from reading this thread it seems I might have an issue.

**Comment by sarge31** [comment]
Disregard.  Re-registered the dot and it now displays the devices under smart home.

**Comment by bwssytems** [comment]
I am closing this as the synology issue has been resolved. All discovery issues have been discussed as well and they all have solutions.
