### ISSUE TITLE
Error on sending http commands

### ISSUE THREAD

**Issue by Spiral1401** [bwssytems/ha-bridge#811]
I'm getting an odd error after switching routers - I can't say for sure it specifically had to do with the new router (having a hard time seeing how) but I didn't see it happen beforehand. (see below in red at top-right)

![image](https://user-images.githubusercontent.com/30994127/33243093-4c576a6a-d2ad-11e7-8170-4dfea08ffaad.png)

The logs are full of this message:

The requested route [/(null)] has not been mapped in Spark for Accept: [null]

That seems to be happening every 1-20 seconds or so.

I have ha-bridge running in docker as detailed here: https://github.com/aptalca/docker-ha-bridge

My new router is configured the same in every way I could think (same subnet, devices sending/receiving commands are at the same IPs as before)

Any idea whats going on here? Perhaps I should wipe everything out and start over with ha-bridge & docker-ha-bridge?

edit: Also wanted to mention - the http commands work fine if I just enter them straight into the browser.

**Comment by bwssytems** [comment]
Please post your log file from the command line with this error.

**Comment by Spiral1401** [comment]
[ha-bridge.log](https://github.com/bwssytems/ha-bridge/files/1508105/ha-bridge.log)

Is this the right log? Was expecting to see that popup error in here...

**Comment by bwssytems** [comment]
That is the correct log. Can you get to the web page?

**Comment by Spiral1401** [comment]
Yeah, everything web UI wise appears to work. The error from the first screenshot happens when I do Test ON / Test OFF.

This is the what the "Fan" device is set up as, for instance:

![image](https://user-images.githubusercontent.com/30994127/33296993-a2663972-d3ac-11e7-80ad-2fc5813cd0b6.png)

**Comment by bwssytems** [comment]
Hmm, wonder if you got assigned a new ip address by the router....

**Comment by Spiral1401** [comment]
My public IP did change, which I wasn't expecting (and I had to adjust some other unrelated things to account for that), but I made an attempt to keep all local IPs the same (for the devices that matter, anyway), either through static ip or DHCP reservations on the new router.

The 192.168.2.238 is a sort of network power outlet switch, and it controls 4 outlets, so thats what the /2 is (to denote the outlet) and then the command to set it on/off. 192.168.2.231 is where the ha-bridge is running, an ubuntu 16.04 machine.

Like I mentioned before, it still works if I just drop the http command there into the chrome address bar and hit enter.

I understand that this one is probably just a weird one, and maybe something on my machine just went haywire somehow. I can give configuring ha-bridge fresh a try probably sometime this weekend, and/or maybe update to ubuntu 17.10 while I'm at it.

**Comment by bwssytems** [comment]
Turn on debug for the HueMulator class and let's see if there is any issues.

**Comment by Spiral1401** [comment]
Here's a cut of the end of the log after setting the debug level and hitting Test ON:


11-28-2017 15:03:30.904 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter
-- | -- | -- | --
11-28-2017 15:03:33.248 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter
11-28-2017 15:03:40.389 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter
11-28-2017 15:03:42.452 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter
11-28-2017 15:03:51.224 | DEBUG | HueMulator GET called on api/* with request <<</api/devices>>>, and body <<<>>> | com.bwssystems.HABridge.hue.HueMulator
11-28-2017 15:03:51.226 | DEBUG | HueMulator GET called on api/* with request <<</api/devices/backup/available>>>, and body <<<>>> | com.bwssystems.HABridge.hue.HueMulator
11-28-2017 15:03:51.427 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter
11-28-2017 15:03:52.486 | DEBUG | HueMulator PUT called on api/* with request <<</api/2a362844dfdc4879964e7b5ed4c20073/lights/842179921/state>>>, and body <<<{"on":true}>>> | com.bwssystems.HABridge.hue.HueMulator
11-28-2017 15:03:52.486 | DEBUG | PUT action to group 842169921 from 192.168.2.231 user 2a362844dfdc4879964e7b5ed4c20073 with body {"on":true} | com.bwssystems.HABridge.hue.HueMulator

**Comment by bwssytems** [comment]
Were you expecting to go to a group? Otherwise There is a new feature that if the device id us greater than 10000 it is a group.

**Comment by Spiral1401** [comment]
I wasn't. Isn't that automatically assigned? The only ID that seems to be editable that I can see is the map ID.

**Comment by niwmik** [comment]
Had same error.  Fixed it by hitting the renumber devices button on the config page and then have alexa forget and discover devices

**Comment by bwssytems** [comment]
@Spiral1401 Did you try the renumber as that should fix it.

**Comment by Spiral1401** [comment]
That did fix it indeed. Thank you both for your help.
