### ISSUE TITLE
Can't add devices to the bridge using Post

### ISSUE THREAD

**Issue by tuicemen** [bwssytems/ha-bridge#812]
With version 5 I can no longer Post a new device to the Bridge
I think the expected string has changed.
I was using {"name":"(DeviceName)","deviceType":"exec","offUrl":"[{\"item\":\" (exe Off command\"}]","onUrl":"[{\"item\":\"(exe On command)\"}]","inactive":false,"noState":false,"offState":" true "}

I'll admit it has been a few versions since adding devices so I expect maybe something else is required now.

**Comment by bwssytems** [comment]
Please post your log file with errors please.

**Comment by tuicemen** [comment]
OK, looks like the issue is in my code.
Using postman and original Post everything works.
