### ISSUE TITLE
Echo 2nd gen no devices seen but see bridge

### ISSUE THREAD

**Issue by happyhammers** [bwssytems/ha-bridge#814]
Hi I have similar to other mentioned. Initially Echo did see the bridge and the devices, deleting devices and now does not see devices but i'm sure its seeing bridge. 

I've done a log with debug. It appears to get the request for the device named Front lounge but does not add it. The Hue app on android finds and device and can control it, echo just does not seem to add it.

Any ideas what i'm doing wrong ?

Many thanks

11-27-2017 21:47:17.330 | DEBUG | sendUpnpNotify notifyTemplate is <<<NOTIFY * HTTP/1.1 HOST:   239.255.255.250:1900 CACHE-CONTROL: max-age=100 LOCATION:   http://192.168.0.21:80/description.xml SERVER: Linux/3.14.0 UPnP/1.0   IpBridge/1.19.0 NTS: ssdp:alive hue-bridgeid: C03FD5FFFE63F45A NT:   uuid:2f402f80-da50-11e1-9b23-c03fd563f45a USN:   uuid:2f402f80-da50-11e1-9b23-c03fd563f45a >>> | com.bwssystems.HABridge.upnp.UpnpListener
-- | -- | -- | --
11-27-2017 21:47:37.334 | DEBUG | sendUpnpNotify notifyTemplate is <<<NOTIFY * HTTP/1.1 HOST:   239.255.255.250:1900 CACHE-CONTROL: max-age=100 LOCATION:   http://192.168.0.21:80/description.xml SERVER: Linux/3.14.0 UPnP/1.0   IpBridge/1.19.0 NTS: ssdp:alive hue-bridgeid: C03FD5FFFE63F45A NT:   uuid:2f402f80-da50-11e1-9b23-c03fd563f45a USN: uuid:2f402f80-da50-11e1-9b23-c03fd563f45a   >>> | com.bwssystems.HABridge.upnp.UpnpListener
11-27-2017 21:47:37.391 | INFO | Traceupnp: request of description.xml from: 192.168.0.12:80 filled in   with address: 192.168.0.21:80 | com.bwssystems.HABridge.upnp.UpnpSettingsResource
11-27-2017 21:47:37.448 | INFO | Traceupnp: request of description.xml from: 192.168.0.12:80 filled in   with address: 192.168.0.21:80 | com.bwssystems.HABridge.upnp.UpnpSettingsResource
11-27-2017 21:47:37.455 | DEBUG | HueMulator GET called on api/* with request   <<</api/73e2f2b2d41c4aeda6e4420d36b9e32f/lights>>>, and   body <<<>>> | com.bwssystems.HABridge.hue.HueMulator
11-27-2017 21:47:37.456 | DEBUG | matchedPart: :userid = 73e2f2b2d41c4aeda6e4420d36b9e32f | spark.Request
11-27-2017 21:47:37.456 | INFO | Traceupnp: hue lights list requested by user:   73e2f2b2d41c4aeda6e4420d36b9e32f from address: 192.168.0.12 | com.bwssystems.HABridge.hue.HueMulator
11-27-2017 21:47:37.456 | DEBUG | hue lights list requested: 73e2f2b2d41c4aeda6e4420d36b9e32f from   192.168.0.12 | com.bwssystems.HABridge.hue.HueMulator
11-27-2017 21:47:37.456 | DEBUG | validateWhitelistUser: found a user   <73e2f2b2d41c4aeda6e4420d36b9e32f> | com.bwssystems.HABridge.BridgeSecurity
11-27-2017 21:47:37.456 | DEBUG | Save HA Bridge settings. | com.bwssystems.HABridge.BridgeSettings
11-27-2017 21:47:37.543 | DEBUG | HueMulator GET called on api/* with request   <<</api/73e2f2b2d41c4aeda6e4420d36b9e32f/lights/1>>>, and   body <<<>>> | com.bwssystems.HABridge.hue.HueMulator
11-27-2017 21:47:37.544 | DEBUG | matchedPart: :userid = 73e2f2b2d41c4aeda6e4420d36b9e32f | spark.Request
11-27-2017 21:47:37.544 | DEBUG | matchedPart: :id = 1 | spark.Request
11-27-2017 21:47:37.544 | DEBUG | hue light requested: 1 for user: 73e2f2b2d41c4aeda6e4420d36b9e32f from   192.168.0.12 | com.bwssystems.HABridge.hue.HueMulator
11-27-2017 21:47:37.544 | DEBUG | validateWhitelistUser: found a user   <73e2f2b2d41c4aeda6e4420d36b9e32f> | com.bwssystems.HABridge.BridgeSecurity
11-27-2017 21:47:37.544 | DEBUG | found device named: Front Lounge | com.bwssystems.HABridge.hue.HueMulator
11-27-2017 21:47:39.652 | DEBUG | HueMulator GET called on api/* with request   <<</api/73e2f2b2d41c4aeda6e4420d36b9e32f/lights/1>>>, and   body <<<>>> | com.bwssystems.HABridge.hue.HueMulator
11-27-2017 21:47:39.653 | DEBUG | matchedPart: :userid = 73e2f2b2d41c4aeda6e4420d36b9e32f | spark.Request
11-27-2017 21:47:39.654 | DEBUG | matchedPart: :id = 1 | spark.Request
11-27-2017 21:47:39.654 | DEBUG | hue light requested: 1 for user: 73e2f2b2d41c4aeda6e4420d36b9e32f from   192.168.0.12 | com.bwssystems.HABridge.hue.HueMulator
11-27-2017 21:47:39.654 | DEBUG | validateWhitelistUser: found a user   <73e2f2b2d41c4aeda6e4420d36b9e32f> | com.bwssystems.HABridge.BridgeSecurity
11-27-2017 21:47:39.655 | DEBUG | found device named: Front Lounge | com.bwssystems.HABridge.hue.HueMulator
11-27-2017 21:47:39.694 | DEBUG | HueMulator GET called on api/* with request   <<</api/73e2f2b2d41c4aeda6e4420d36b9e32f/lights/1>>>, and   body <<<>>> | com.bwssystems.HABridge.hue.HueMulator
11-27-2017 21:47:39.694 | DEBUG | matchedPart: :userid = 73e2f2b2d41c4aeda6e4420d36b9e32f | spark.Request
11-27-2017 21:47:39.694 | DEBUG | matchedPart: :id = 1 | spark.Request
11-27-2017 21:47:39.694 | DEBUG | hue light requested: 1 for user: 73e2f2b2d41c4aeda6e4420d36b9e32f from   192.168.0.12 | com.bwssystems.HABridge.hue.HueMulator
11-27-2017 21:47:39.694 | DEBUG | validateWhitelistUser: found a user   <73e2f2b2d41c4aeda6e4420d36b9e32f> | com.bwssystems.HABridge.BridgeSecurity
11-27-2017 21:47:39.694 | DEBUG | found device named: Front Lounge | com.bwssystems.HABridge.hue.HueMulator
11-27-2017 21:47:48.843 | DEBUG | Get logmsgs. | com.bwssystems.HABridge.SystemControl
11-27-2017 21:47:55.309 | DEBUG | Get logmsgs. |

**Comment by bwssytems** [comment]
Can you verify that this IP, 192.168.0.12, is the one from your 2nd gen echo?

**Comment by happyhammers** [comment]
Hi Yes that is the ip for my echo.

**Comment by bwssytems** [comment]
Well, it looks as it is finding the bridge and the light.

**Comment by happyhammers** [comment]
That's what i thought, do you think they have recently changed something on the echo ? When i first set it up a week ago it worked ok. I've tried different routers, different wifi's, tried the echo forum and still not sure what the problem is, thanks Dave

**Comment by bwssytems** [comment]
When you change routers, do you get a new ip address? If so, you need to change the upnp config address in the bridge control page.

**Comment by happyhammers** [comment]
Habridge is running on linux with static ip rather than DHCP so with either router is stays the same.

**Comment by varguello** [comment]
Hello,
I'm having the same issue with my Echo 2nd generation. This might be of interest: I have an Echo Dot 2nd gen running on the same network and signed in to the same account and it finds the device in habridge every time. Once the Echo Dot has sent a successful request to the device the Echo 2nd seems to be able to find the device for a while. After a few minutes though the Echo 2nd fails again to find the device. The Echo Dot can still carry out successful requests.

**Comment by Blacksus90** [comment]
This is a thing. Thank god I found this, I thought I was going crazy.
Exactly the same problem. My Echo 2nd Gen cannot find the habridge devices. However, my old echo dot (that I plan on giving away) can find them. Once they are found, the Echo 2nd Gen can use them. But if you delete one from the alexa app and try to find it again via the Echo 2ng gen...nothing. Only the dot can discord them.

Begging for a fix for this. It's like I'm living in 2014 again. Who wants that?


Cheers!

**Comment by bwssytems** [comment]
Same as #810

**Comment by bwssytems** [comment]
What  are the environments that you are running the ha-bridge in? RaspberryPI, Docker on linux or windows, Mac or other setup?

**Comment by bwssytems** [comment]
So V5.2.0 is out there and it has an update for upnp sending. Please try and see if your echo 2nd gen is working now.

**Comment by bwssytems** [comment]
Any updates

**Comment by bwssytems** [comment]
This has been resolved for 2nd Gen Echo devices. The 5.2.0 and on releases work with them now.
