### ISSUE TITLE
5.0.0 Harmony pairing not working because of HTTP302 issue

### ISSUE THREAD

**Issue by vinch1218** [bwssytems/ha-bridge#816]
Hello,

I recently updated switched from a windows ha-bridge to a docker version in 5.0.0 and discovered that the Pairing process from my Harmony Hub could not complete.
To better understand if it was related to my docker, I did all the test using the official relaeses on my windows machine and found the following 

While doing a quick network analysis on a working version (4.5.6), we see the request from my Harmony hub (.119) :
`192.168.1.119:38225	192.168.1.115:3080	HTTP	235	POST /api/ HTTP/1.1  (application/json)`
and then the reply 
`192.168.1.115:3080	192.168.1.119:38225	HTTP	66	HTTP/1.1 200 OK  (application/json)`
and then the pairing process starts and complete correctly.

Doing the same process in 5.0.0 shows that it's now using an HTTP 302 redirect : 
`192.168.1.115:3080	192.168.1.119:38225	HTTP	211	HTTP/1.1 302 Found 	Location : http://192.168.1.115/api`

However the target (location) does not include the port, which is certainly one good reason for the pairing failure.

Best regards

[pcap files.zip](https://github.com/bwssytems/ha-bridge/files/1509364/pcap.files.zip)

**Comment by bwssytems** [comment]
Which direction are you pairing the harmony hub? To the ha-bridge or from the ha-bridge...

**Comment by vinch1218** [comment]
To the HA-Bridge, I use the MyHarmony configuration software to scan the devices available on my network, when discoevered I select the fake Hue bridge and when I click Next it asks me to push on the Sync Button on my Hue Bridge (which I manually do through the HABridge WebUI)

**Comment by M-Schoeler** [comment]
Hi, same problem here:

When pairing Harmony Hub to ha-bridge i experience the same problem. Hub is sending "POST /api/ HTTP/1.1", ha-bridge replies with 
        HTTP/1.1 302 Found
        Connection: close
        [...]
        Server: Jetty(9.4.z-SNAPSHOT)

Any ideas?

**Comment by bwssytems** [comment]
This is a duplicate of #797, Please update that thread with any info and close this.

**Comment by vinch1218** [comment]
Thanks
