### ISSUE TITLE
Log full of error: The requested route [/(null)] has not been mapped in Spark 

### ISSUE THREAD

**Issue by Zwickor** [bwssytems/ha-bridge#817]
Hello guys :)

I recently upgraded to v5.0. I just watched the log and its full with tons of these entries. I already tried to use google but wasnt successful. Any ideas?:

`

11-29-2017 19:06:21.605 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter
-- | -- | -- | --
11-29-2017 19:06:47.046 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter
11-29-2017 19:06:55.369 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter
11-29-2017 19:07:15.196 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter
11-29-2017 19:07:45.027 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter
11-29-2017 19:07:49.630 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter
11-29-2017 19:08:12.038 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter
11-29-2017 19:08:32.128 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter
11-29-2017 19:08:43.708 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter
11-29-2017 19:09:03.409 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter
11-29-2017 19:09:23.399 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter
11-29-2017 19:09:37.530 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter
11-29-2017 19:09:57.380 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter
11-29-2017 19:10:18.068 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter
11-29-2017 19:10:32.108 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter
11-29-2017 19:10:38.102 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter
11-29-2017 19:11:03.132 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter
11-29-2017 19:11:23.163 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter

`

**Comment by bwssytems** [comment]
It looks like something is trying to HTTP POST to your bridge machine. As for the Google Home, That has issues that are already identified due to Google using the cloud lookup for Philips Hue. See #764

**Comment by audiofreak9** [comment]
@bwssytems 

With v5.0.0 I am also getting the INFO log: 

> "The requested route [/(null)] has not been mapped in Spark for Accept: [null]"

about every 4 seconds.  I have a fairly simple setup, only Echos (Gen 1, Dots & Show) and a Harmony Hub.  When I try to change the log level for spark.http.matching.MatcherFilter, I get the success message, but it doesn't seem to change any actual logs.  Advice?

**Comment by audiofreak9** [comment]
Was the Webserver on my Synology NAS making the request.

**Comment by Cypher87** [comment]
I have the same issue here. The logging doesn't show where the request is coming from. Would be nice to know what is causing this. As my house is full of devices, it's hard to tell what is causing this.

**Comment by bwssytems** [comment]
This is a by product of using the Spark framework. The message is harmless and is not affecting anything. If you want to find out what it is, turn on debug fro the com.spark framework items.

**Comment by essera** [comment]
I have the same issue with a log full of unwanted / unknown messages of 

12-10-2017 13:39:33.244 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter
-- | -- | -- | --
This started with the installation of ha-bridge 5.0.
It is ok thats these message are harmless but they spam my log und use CPU Power. How can i stop them ?
I don´t know anything about the com.spark.framework....

**Comment by bwssytems** [comment]
It is harmless

**Comment by essera** [comment]
OK - i understood from the Posts before....
But how can i stop it.....
It wasn´t there before the update to 5.0 and my system has nothing to do than writing log entries....

**Comment by bwssytems** [comment]
I'll see if I can get it to filter those out.

**Comment by bwssytems** [comment]
For other reasons, it looks like the new Spark has an issue with certain paths. Reverting back to 2.3 from 2.7.1

**Comment by bwssytems** [comment]
@essera Found a piece of code that got pulled in from a merge for adding the color and it had an incorrect path redirect for Spark.

**Comment by audiofreak9** [comment]
The `The requested route [/(null)] has not been mapped in Spark for Accept: [null]` INFO log error is back for me with V5.1.0 about every 20 seconds.  I'll try to figure out which of my home's devices is causing the error.

**Comment by audiofreak9** [comment]
Reset logging and error stopped...closing.

**Comment by sigma415** [comment]
> 

Reset logging and error stopped...closing.
--

How can I "Reset logging" ?

**Comment by bikeymouse** [comment]
I'm also wondering how to "Reset the logging", because still on V5.1.0 my log is flooded with these messages about every 15 seconds:
"The requested route [/(null)] has not been mapped in Spark for Accept: [null]"

**Comment by bwssytems** [comment]
With the next version the /(null) will go away. The reply for upnp has a null service defined and shouldn't be so something finds that and calls it.

**Comment by l0uka0s** [comment]
I have also these Problem: 
762 [qtp500879282-63] INFO  spark.http.matching.MatcherFilter - The requested route [/api/4bd09ecf0a5a40d984bc54522391f7e4/capabilities] has not been mapped in Spark for Accept: [*/*]

I always get these errors when I want to save a room at Philips Hue app. I can connect to the Philips Hue Hub (HA-Bridge), but in the app I can´t save a room or something other. The Controlling from every Bulb is also not possible.
I can turn on just every Bulb and turn off I´m possible to turn off everything or just a single Bulb.

**Comment by bwssytems** [comment]
@l0uka0s The ha-bridge does not support saving rooms.

**Comment by michel130** [comment]
Hello,

How can I use the I Philips Hue app ? 
If the ha-bridge does not support saving rooms.

I startup the app and the first thing it ask me to configure rooms but I cannot skip that part in the app.

**Comment by l0uka0s** [comment]
Well, could can try save a room and after a time of trying to save the room you see "these room is already saved" than you have to be fast and klick after Arrow top left and than directly the arrow top right. If you are fast enough you will come tho the next screen where you normally see all your saved rooms, than you're finished

**Comment by michel130** [comment]
@bwssytems when will the next release will be released?

@l0uka0s Unfortunately I don't get anything on my IPhone the software start I see that I have a couple of lamps connect on the HA-Bridge but when I click on it wants first that I connect these lamps to an room and that does not work, I also not see the arrow on right top.

**Comment by l0uka0s** [comment]
Okay, Well I have a Androide Phone so I can't tell you how it's work on Iphone :/

**Comment by ifuchs** [comment]
As reported (much) earlier, this message
`spark.http.matching.MatcherFilter - The requested route [/eventstream/clip/v2] has not been mapped in Spark for Accept: [text/event-stream]`

is written to the log every few seconds. Is there a way to stop it?
