### ISSUE TITLE
Word "light" enables all devices on Google Home

### ISSUE THREAD

**Issue by rjtrigo** [bwssytems/ha-bridge#819]
Every time I say "OK Google, turn on light" all the devices setup on habridge switch on and also goole reports that is switching on all the 7 devices despite I have no device called "light".

**Comment by bwssytems** [comment]
Yes, known feature with Google Home. It automatically considers light a group of all devices it knows about. This is not an ha-bridge issue.

**Comment by rjtrigo** [comment]
Can it be stopped? Thanks

**Comment by audiofreak9** [comment]
No, this is a "feature" of the Google Home devices.  Google has added logic to their devices.  As @bwssytems stated this is not an ha-bridge issue.
