### ISSUE TITLE
Sending custom headers?

### ISSUE THREAD

**Issue by RocThrower** [bwssytems/ha-bridge#82]
Is there any way to specify a custom header when manually adding a device? For example, I'm trying to control Sonos and need to send the header:
`SOAPACTION: "urn:schemas-upnp-org:service:RenderingControl:1#SetMute"`
Thanks for all the work you've put in to this by the way!

**Comment by fearoffish** [comment]
I need to authenticate with headers against a device, so being able to add them would be great

**Comment by chapeter** [comment]
Just ran into this as well.  Other than that running into no problems.  Great Project

**Comment by bwssytems** [comment]
Not at t his time. I'll add it as an enhancement.
