### ISSUE TITLE
upgrading to 5.0.0 all Script/Program Devices now Fail

### ISSUE THREAD

**Issue by merlin051** [bwssytems/ha-bridge#820]
As above, when running with the 5.0.0 Jar all my devices which are using Script blocks to (mostly) execute Python scripts.

everything was fine on the last version.

I can see this in the logs which looks suspect:

WARN | Error reading the file: data\group.db - Does not exist or is not readable. continuing... | com.bwssystems.HABridge.dao.GroupRepository
-- | -- | --

**Comment by bwssytems** [comment]
That is just a warning telling you there is no group file as you haven't set them up.

As far as the script issues, I assume you are using the exec function to call a local script. Turn on debug for com.bwssystems.HABRidge.plugins.exec and post your log.

**Comment by bwssytems** [comment]
Any update?

**Comment by tuicemen** [comment]
Check your antivirus. You may need to add an exclusion for the Ha-bridge folder

**Comment by merlin051** [comment]
Sorry, been on vacation.

I did not change any anti virus settings, however after putting 5.1.0 on, everything is working again.

Not sure what it was in 5.0.0 that broke it.
