### ISSUE TITLE
Support HEX-Formatted RGB Values for color

### ISSUE THREAD

**Issue by nihebe** [bwssytems/ha-bridge#821]
Hey guys,

is there someone around who can give me a hint regarding the color-feature? I'm using a FHEM-server behind my ha-bridge, which controls my Milights. That server expects HEX encoded values for RGB.

Are there any chances to not only have
`${color.r} ${color.g} ${color.b}` (0-255 format)
but also
`${color.rgb}` (HEX format)?

I'm looking forward your answers.

Best
Nils

**Comment by peos3** [comment]
I dont' know your exact setup, but can't you just calculate the Hex Value, given the RGB values?

Best regards,
Pascal

**Comment by bwssytems** [comment]
@nihebe Could you give an example on how that format would be described?

**Comment by nihebe** [comment]
@peos3 Well you're right, using a bash-script which calculates the HEX representation and executes the Rest-Call would be a solution, but quite unpleasant to maintain.

@bwssytems Of course RGB: `66, 134, 244` (light blue) would be HEX: `4286f4`
I think this could be easily mapped by something like `String.format("%02x%02x%02x", r, g, b);`

**Comment by bwssytems** [comment]
Added ${color.rx} ${color.gx} ${color.bx} ${color.rgbx}
