### ISSUE TITLE
connect ha-bridge to homebridge

### ISSUE THREAD

**Issue by krobipd** [bwssytems/ha-bridge#822]
I wonder if its possible to connect ha-bridge to homebridge.

I would like to control homebridge devices with ha-bridge without manually re-adding them into ha-bridge.

so I would be great if there is a solution to directly connect this two programs.

**Comment by bwssytems** [comment]
This is a topic that has been touched upon. I have been looking into how this could work as the ha-bridge would have to talk to homebridge using the Apple HAP protocol. So, is there something that homebridge talks to that ha-bridge cannot?

**Comment by krobipd** [comment]
the main reason I would like to connect this two is quite simple,

its way easier for me to connect my devices with homebridge - for example I have wlan leds, with homebridge I install the plugin type the ip into the config file and thats it. I don't know who to do that in ha-bridge.

second example, Homematic. on homebridge I install the plugin type the ip address into the config and thats it. every Homematic device is now working on homebridge.

in ha-bridge I have to manual add every function through http requests - as fas I know, maybe there is a easier, more automatic way.

i also want to use the homebridge function for apples HomeKit system - something ha-bridge doesn't offer (as far as I know) but I also want to control some devices through my Logitech harmony (something homebridge can't do).

for example I would like to enable or disable my Homematic light switch with my harmony but also want to have full control with apples HomeKit system.

i also don't want to have duplicated entries, the same in homebridge as in ha-bridge. the perfect way would be that theses two program could talk to each other for maximum connectivity.

I hope i made my point, ansonsten kann ich das gerne in deutsch ausführen ;-)

**Comment by bwssytems** [comment]
Those are all good reasons. I have been looking into this and it may come about.

**Comment by bwssytems** [comment]
This is also mentioned in #366

**Comment by bwssytems** [comment]
With the implementation of Mozilla IOT, Which has homebridge connectivity, I will suggest that is the path to implement this.

See https://iot.mozilla.org/
