### ISSUE TITLE
Routines wont see virtual devices

### ISSUE THREAD

**Issue by MOST2K2** [bwssytems/ha-bridge#824]
Hello i want to use a habridge device in a routine in the alexa app (android, latest version), but the device wont show under routines.  Under devices it will be listed and it works. Only the real hue devices are shown under routines. With openhab2 i saw the virtual devices under routines.

Any hints how to solve the problem?

**Comment by bwssytems** [comment]
Maybe a misunderstanding here, in the english version there are Groups, Devices and Scenes. Do you mean Scenes?

**Comment by bwssytems** [comment]
Any update?

**Comment by gdeboos** [comment]
Routines are different to Devices, Groups or Scenes. For me, in the main slide out menu/navigation above Smart Home there is a nav item called Routines. This allows you to set a custom command (Alexa, xxxx xxxx) and do multiple things. E,g tell me the weather and turn bedroom light on.

I can see my HABridge devices but when added to a routine they don't do anything.

**Comment by bwssytems** [comment]
One of the things I see for smarthome devices is that it sets hue devices by percentage. It may be calling the dim url from the routine. I will check later on my system.

**Comment by gdeboos** [comment]
I managed to check, it is calling the dim url.

**Comment by bwssytems** [comment]
Thanks for checking on that, now we now how that will work. So, using the dim URL can only do one thing though.

**Comment by gdeboos** [comment]
I worked around it by creating a device specifically for a routine. Then used ha Bridge to do multiple things. No perfect but works well.
