### ISSUE TITLE
New devices in v5.0.0 do not have deviceState parameters?

### ISSUE THREAD

**Issue by audiofreak9** [bwssytems/ha-bridge#827]
When I create new devices in v5.0.0 the deviceState information in the devices db is not present.  I created a test item, compare with existing:

**New Test device:**
`{"id":"30","uniqueid":"00:17:88:5E:D3:1E-1E","name":"test","mapType":"cmdDevice","deviceType":"exec","targetDevice":"Encapsulated","offUrl":"[{\"item\":\"heyu off M12\",\"type\":\"cmdDevice\"}]","dimUrl":"[{\"item\":\"heyu dimb M12 ${intensity.math(((X*-22)/255)+22)}\",\"type\":\"cmdDevice\"}]","onUrl":"[{\"item\":\"heyu on M12\",\"type\":\"cmdDevice\"}]","inactive":false,"noState":false,"offState":false,"description":"M12 China Cabinet","comments":"cabinet seems to work also"}`

**Existing device:**
`{"id":"19","uniqueid":"00:17:88:5E:D3:13-13","name":"china cabinet","mapType":"cmdDevice","deviceType":"exec","targetDevice":"Encapsulated","offUrl":"[{\"item\":\"heyu off M12\",\"type\":\"cmdDevice\"}]","dimUrl":"[{\"item\":\"heyu dimb M12 ${intensity.math(((X*-22)/255)+22)}\",\"type\":\"cmdDevice\"}]","onUrl":"[{\"item\":\"heyu on M12\",\"type\":\"cmdDevice\"}]","inactive":false,"noState":false,"offState":false,"description":"M12 China Cabinet","comments":"cabinet seems to work also","deviceState":{"on":false,"bri":0,"alert":"none","reachable":true}}`

**Comment by audiofreak9** [comment]
If I operate the device from the ha-bridge, it then includes the deviceState parameter.  So it seems the ha-bridge does not set the deviceState parameter for any one device until it knows the controlled state.  Is this a change from previous versions?  Since I use the devices xml in a control program I wrote, I'd prefer it to set the deviceState parameter with null entries, is this possible?

**Comment by bwssytems** [comment]
That is correct. The null entries would be confusing as what needs to be returned is definitive as in ON or OFF. There is no unknown state.

**Comment by audiofreak9** [comment]
Ok, thanks for confirming, I’ll write my script accordinly.
