### ISSUE TITLE
QUESTION - UDP Command Orvibi S20 Smart Plug

### ISSUE THREAD

**Issue by merlin051** [bwssytems/ha-bridge#828]
Has anyone got the UDP command working for the Orvibo S20 switches?

and can you share your configuration?

**Comment by bwssytems** [comment]
Orvibo has it's own discovery and transmission protocols. This is similar to the way broadlink works but not quite the same messages.

**Comment by jj-0** [comment]
The Orvibo S20 protocol can be found [here](https://web.archive.org/web/20170705074530/https://stikonas.eu/wordpress/2015/02/24/reverse-engineering-orvibo-s20-socket/). You have to add an UDP subscribe before each and an UDP on or off command:

My 'on' command:
[{"item":"udp://**S20 IP**:10000/0x6864001e636c**S20 MAC**202020202020**REVERSE S20 MAC**202020202020","type":"udpDevice","delay":"100","count":"2"},
{"item":"udp://**S20 IP**:10000/0x686400176463**S20 MAC**2020202020200000000001","type":"udpDevice","delay":"100","count":"2"}]

My 'off' command:
[{"item":"udp://**S20 IP**:10000/0x6864001e636c**S20 MAC**202020202020**REVERSE S20 MAC**202020202020","type":"udpDevice","delay":"100","count":"2"},
{"item":"udp://**S20 IP**:10000/0x686400176463**S20 MAC**2020202020200000000000","type":"udpDevice","delay":"100","count":"2"}]

Replace **S20 MAC** with the mac address of your S20 in hex and the same in revers order for **REVERSE S20 MAC**.

**Comment by bwssytems** [comment]
included in community information https://github.com/bwssytems/ha-bridge/wiki/Informational-Items-Collected-from-the-Community#q-udp-command-orvibi-s20-smart-plug
