### ISSUE TITLE
HUE Device Color & possible bugs with Build Item

### ISSUE THREAD

**Issue by docb7** [bwssytems/ha-bridge#829]
Hi, as I understand the release notes, now hue device pass-through of colors should work. I freshly installed you really unbelievable great ha-bridge and added the hue bridge. All devices were found and I used Build Item. 
So when I did this with my Hue Bloom, there were no entries at Dim Items and Color Items. I just copied and pasted that from on / off items (were all the same) and dim works, but color does not. My echo dot say "light does not support this".
When I  press Build Item at another lamp, there are several entries in On Items and Off Items,  in each the first line ist with a wrong deviceId, the second and third line with the right one, eacht with same content. And this behavior gets even worse when trying to press Build Item again, then the two beforementioned lamps will be there in on and of items as well. It seems that build item just adds it to an existing Device (the first one I've created).

Thank you so much for all you effort!

**Comment by FloFoer** [comment]
Unfortunately color with Alexa doesn't work. The color feature is only usable via other methods, for example via apps. You can read why [here in this issue](https://github.com/bwssytems/ha-bridge/issues/813)  
For the Hue passthru devices it doen't matter that dim/color is empty, it still works.
