### ISSUE TITLE
Wink app not seeing HA-Bridge (but Hue app does)

### ISSUE THREAD

**Issue by KeithLaepple** [bwssytems/ha-bridge#833]
I have HA Bridge running successfully on Windows 10, evidenced by web UI working at http://localhost:80, and from other PCs and smartphones on the LAN. HA Bridge discovers my Logitech Harmony activities and devices. 

On that LAN, Philips Hue Android app sees and connects to HA Bridge, but only with manually specified LAN IP address and "Link button" configured in the app. It will then discover HA Bridge as a Hue hub, and automatically adds emulated Harmony buttons configured in HA Bridge.

But, I'm unable to get the Wink Android app to discover HA Bridge, running on the same Android device and LAN as the Hue app that does see HA Bridge. Wink appears to be connecting to meethue.com, displays exact same UI as meethue.com attempting to discover Hue hubs in the browser. Does this imply Wink isn't looking for Hue hubs locally, but instead connecting via the Hue cloud service, like Google Home now does?

If Wink isn't going to be able to connect to HA Bridge, I'll need another route to connect my Google Home. I was hoping to utilize Wink similarly to how I've read others have Smartthings working.

Is IFTTT another option, e.g. using remote JSON commands via Webhooks? 

I should also mention, my end game to control Mi Light v6, but need to first confirm HA-Bridge can interface to Wink. Path I envision:  Google Home > Wink > HA-Bridge > Node-MiLight-Promise.js > Mi Light v6 WiFi hub > Mi Light LED chandelier.

If anyone knows an easier way now possible for HA-Bridge to control Mi Light v6, please advise!

**Comment by rafale77** [comment]
The purpose of this bridge is to connect to broadcast the devices from a home automation system (originally a vera then a harmony hub or a hue hub) to the echo for voice control. It does not fully emulate a hue hub. Most devices are now moving to a cloud based control of the hue hub. For devices like the wink, google home or ST, it makes sense since it would be a local > cloud > cloud > home link. The echo works differently, it uses cloud for voice processing only and then controls everything locally. Using this bridge enables local> local without cloud.

**Comment by bwssytems** [comment]
Unfortunately, this topic has been discussed many times. If the connecting system uses meethue.com, it will not work with the ha-bridge as it is using Philips cloud service for discovery. The ha-bridge is not a Philips product so it is not part of meethue.com. The ha-bridge only can be found by the local LAN with it's IP address or the local LAN UPNP discovery.

**Comment by KeithLaepple** [comment]
Thank you for these replies. Yes, I'd seen the posts about the cloud vs. local limitation, but thought I'd still ask if anyone knew for sure how Wink was implemented.

Just out of technical curiosity, can you explain why meethue.com won't discover ha-bridge, even though the Philips Hue app does? My guess is meethue does some type of authentication for security purposes. 

Instead of using ha-bridge as a Hue emulator, might it work to command ha-bridge via its Hue API functions, directly? If so, I'm wondering if another solution pathway for my situation could be:  Google Home > IFTTT > Webhooks > ha-bridge > Node-MiLight-Promise > Mi Light v6 hub.

Between this situation (Mi Link/Limitless LED v6) and another proprietary protocol device (Broadlink RM Mini Wifi IR blaster) I figured out an integration solution for previously, it seems like there's need for some form of generalized software bridge that could proxy/translate basic HTTP commands into customized HTTP/UDP calls to proprietary WiFi based device hubs. That might at least facilitate Google Home integration by using IFTTT's Maker Webhooks, for example.

**Comment by bwssytems** [comment]
Glad you have an idea on how to handle this. Closing as the original issue is answered.

**Comment by KeithLaepple** [comment]
Can you point me in the right direction for docs on how to control ha-bridge via HTTP? Would that just be the Hue API published by Philips?

**Comment by audiofreak9** [comment]
HA_Bridge uses the HUE API, as detailed here: https://github.com/bwssytems/ha-bridge#set-light-state
