### ISSUE TITLE
Backup configuration to external file

### ISSUE THREAD

**Issue by sanderlv** [bwssytems/ha-bridge#834]
Hi, would it be possible to build in a backup configuration option to save externally? To a file?

**Comment by bwssytems** [comment]
So, the ha-bridge allows you to backup your devices data and config data already. Is this more of a question to set where the backup directory location is?

**Comment by sanderlv** [comment]
Yes I can make backups "inside" my docker container. But which to "download" via the GUI my config in a file.

**Comment by bwssytems** [comment]
Since I am nto the maintainer of docker, it would be best to post your question here  https://github.com/aptalca/docker-ha-bridge

**Comment by sanderlv** [comment]
Ok, will do thanks
