### ISSUE TITLE
Harmony activities are no longer started

### ISSUE THREAD

**Issue by aptalca** [bwssytems/ha-bridge#835]
I have been using ha-bridge since the first version. I had created devices from harmony activities since the beginning.

Recently they stopped working (with ver 5.0?). When I click on the "test on" and "test off" buttons in the gui, I get the error popup message: `Request Error, Please look in your habridge log: error {"type":"3","address":"/groups/6429XXXXX","description":"resource, /groups/6429XXXXX, not available"}` (I'm redacting some of the ids, not sure if they are unique to me)

When I check the debug logs, this is what I see:
```
12-07-2017 21:13:25.070	DEBUG	HueMulator PUT called on api/* with request <<</api/e8103d12XXXXXXXXXXXXXXX/lights/6429XXXXXXstate>>>, and body <<<{"on":true}>>>	com.bwssystems.HABridge.hue.HueMulator
12-07-2017 21:13:25.070	DEBUG	matchedPart: :userid = e8103d12XXXXXXXXXXX	spark.Request
12-07-2017 21:13:25.070	DEBUG	matchedPart: :id = 6429XXXXX	spark.Request
12-07-2017 21:13:25.070	DEBUG	PUT action to group 6429XXXXX from 192.168.13.60 user e8103d12XXXXXXXXXXXXXXXXX with body {"on":true}	com.bwssystems.HABridge.hue.HueMulator
12-07-2017 21:13:25.070	DEBUG	validateWhitelistUser: found a user <e8103d12XXXXXXXXXXXXXXXXX>	com.bwssystems.HABridge.BridgeSecurity
```

I'm not using groups and don't have the groups.db file (I get the errors in the log about that too). Not sure why the log refers to id `6429XXXXX` as group, it is actually the device id

Thanks

**Comment by aptalca** [comment]
Just realized that the device id numbers in there are actually one digit off. Here's one where you can see the different ids, I'm only redacting the user id.

```
12-07-2017 21:48:09.700	DEBUG	HueMulator PUT called on api/* with request <<</api/04eb6a1XXXXXXXX/lights/996009963/state>>>, and body <<<{"on":true}>>>	com.bwssystems.HABridge.hue.HueMulator
12-07-2017 21:48:09.700	DEBUG	matchedPart: :userid = 04eb6a1XXXXXXXXXXX	spark.Request
12-07-2017 21:48:09.700	DEBUG	matchedPart: :id = 996009963	spark.Request
12-07-2017 21:48:09.700	DEBUG	PUT action to group 995999963 from 192.168.13.60 user 04eb6a1XXXXXXXXX with body {"on":true}	com.bwssystems.HABridge.hue.HueMulator
12-07-2017 21:48:09.700	DEBUG	validateWhitelistUser: found a user <04eb6a1XXXXXXXX>	com.bwssystems.HABridge.BridgeSecurity
```

**Comment by bwssytems** [comment]
Ahh, yes, you have encountered the new feature for groups..... Any ID above 10000 is now routed to as special room/group call in the ha-bridge. So, if you would like to have it work now, you will need to use the renumber devices feature OR wait till I put in a new switch to make this feature an option. Same behavior as in #800

**Comment by aptalca** [comment]
Ah, sorry, didn't see that thread. I'll close this so the issue can be tracked through the other. In the meantime, I'll renumber.

Thanks
