### ISSUE TITLE
error using REST api

### ISSUE THREAD

**Issue by edd--** [bwssytems/ha-bridge#839]
Hi,

ha bridge 5.0.0 on linux (jre1.8.0_152)
I'm trying to debug why a connecter for my domotica system is not pulling the states from HA Bridge. I tried to simulate the REST api process (with postman) according to the wiki:

I first do a http POST to http://snas.local:8888/api with body:
{"devicetype": "my_hue_app#iphone_peter","username":"my_test_username"}

I receive:
[{"success":{"username":"my_test_username"}}]

Then I do:

GET http://snas.local:8888/api/my_test_username/lights

and receive:

<html><body><h2>500 Internal Server Error</h2></body></html>

anyone got an idea what I'm doing wrong here ? I'm kinda out of ideas here...

thx a lot for anyone that can help me out !

**Comment by edd--** [comment]
some logs:


12-10-2017 21:07:11.430 | DEBUG | hue lights list requested: my_test_username from 192.168.77.200 | com.bwssystems.HABridge.hue.HueMulator
12-10-2017 21:07:11.430 | DEBUG | validateWhitelistUser: found a user <my_test_username> | com.bwssystems.HABridge.BridgeSecurity
12-10-2017 21:07:11.430 | ERROR |   | spark.http.matching.GeneralError
12-10-2017 21:07:15.254 | DEBUG | Stats: [leased: 0; pending: 0; available: 0; max: 200] | com.bwssystems.HABridge.plugins.http.HttpClientPool

**Comment by bwssytems** [comment]
interesting as that should work. I'll take a look

**Comment by bwssytems** [comment]
This might be related again to the new version of Spark I am using. I am reverting back to a previous version.

**Comment by bwssytems** [comment]
Please try the new release 5.1.0 https://github.com/bwssytems/ha-bridge/releases/tag/v5.1.0

**Comment by edd--** [comment]
Thanks for looking into this !

just upgraded to the 5.1 version, but I get the same error.

Logs:

`

12-14-2017 11:02:11.015 | DEBUG | HueMulator GET called on api/* with request <<</api/my_test_username/lights>>>, and body <<<>>> | com.bwssystems.HABridge.hue.HueMulator
-- | -- | -- | --
12-14-2017 11:02:11.016 | DEBUG | matchedPart: :userid = my_test_username | spark.Request
12-14-2017 11:02:11.017 | DEBUG | hue lights list requested: my_test_username from 0:0:0:0:0:0:0:1 | com.bwssystems.HABridge.hue.HueMulator
12-14-2017 11:02:11.017 | DEBUG | validateWhitelistUser: found a user <my_test_username> | com.bwssystems.HABridge.BridgeSecurity
12-14-2017 11:02:11.019 | ERROR |   | spark.http.matching.GeneralError
12-14-2017 11:02:13.997 | DEBUG | Get logmsgs. | com.bwssystems.HABridge.SystemControl

`

**Comment by bwssytems** [comment]
So, there must be an exception that is occurring. The output of the exception will be in a log that is the output of the ha-bridge window or file.

**Comment by edd--** [comment]
hmmmm ... I can't find a logfile other then the logentries in the webinterface. 
I use following startup file:

`[Unit]
Description=HA Bridge
Wants=network.target
After=network.target

[Service]
Type=simple
WorkingDirectory=/root/habridge
ExecStart=/root/habridge/jre1.8.0_152/bin/java -jar -Dserver.port=8888 /root/habridge/ha-bridge-5.1.0.jar

[Install]
WantedBy=multi-user.target`

but I can't find anything in my /root/habridge folder or in the sdk folders ...

**Comment by bwssytems** [comment]
Ahh, it is in /var/log/syslog

**Comment by edd--** [comment]
OK, here goes:

`Dec 15 09:22:35 snas java[10045]: 2017-12-15 09:22:35,613 [qtp17964016-44] DEBUG com.bwssystems.HABridge.hue.HueMulator - HueMulator GET called on api/* with request <<</api/test/lights>>>, and body <<<>>>
Dec 15 09:22:35 snas java[10045]: 2017-12-15 09:22:35,613 [qtp17964016-44] DEBUG spark.Request - matchedPart: :userid = test
Dec 15 09:22:35 snas java[10045]: 2017-12-15 09:22:35,614 [qtp17964016-44] DEBUG com.bwssystems.HABridge.hue.HueMulator - hue lights list requested: test from 192.168.77.63
Dec 15 09:22:35 snas java[10045]: 2017-12-15 09:22:35,614 [qtp17964016-44] DEBUG com.bwssystems.HABridge.BridgeSecurity - validateWhitelistUser: found a user <test>
Dec 15 09:22:35 snas java[10045]: 2017-12-15 09:22:35,615 [qtp17964016-44] ERROR spark.http.matching.GeneralError -
Dec 15 09:22:35 snas java[10045]: java.lang.NullPointerException: null
Dec 15 09:22:35 snas java[10045]: #011at com.bwssystems.HABridge.plugins.hue.HueHome.getHueDeviceInfo(HueHome.java:88)
Dec 15 09:22:35 snas java[10045]: #011at com.bwssystems.HABridge.hue.HueMulator.lightsListHandler(HueMulator.java:883)
Dec 15 09:22:35 snas java[10045]: #011at com.bwssystems.HABridge.hue.HueMulator.lambda$23(HueMulator.java:293)
Dec 15 09:22:35 snas java[10045]: #011at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
Dec 15 09:22:35 snas java[10045]: #011at spark.http.matching.Routes.execute(Routes.java:61)
Dec 15 09:22:35 snas java[10045]: #011at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
Dec 15 09:22:35 snas java[10045]: #011at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
Dec 15 09:22:35 snas java[10045]: #011at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
Dec 15 09:22:35 snas java[10045]: #011at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
Dec 15 09:22:35 snas java[10045]: #011at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
Dec 15 09:22:35 snas java[10045]: #011at org.eclipse.jetty.server.Server.handle(Server.java:564)
Dec 15 09:22:35 snas java[10045]: #011at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
Dec 15 09:22:35 snas java[10045]: #011at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
Dec 15 09:22:35 snas java[10045]: #011at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
Dec 15 09:22:35 snas java[10045]: #011at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
Dec 15 09:22:35 snas java[10045]: #011at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
Dec 15 09:22:35 snas java[10045]: #011at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
Dec 15 09:22:35 snas java[10045]: #011at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
Dec 15 09:22:35 snas java[10045]: #011at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
Dec 15 09:22:35 snas java[10045]: #011at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
Dec 15 09:22:35 snas java[10045]: #011at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
Dec 15 09:22:35 snas java[10045]: #011at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
Dec 15 09:22:35 snas java[10045]: #011at java.lang.Thread.run(Thread.java:748)`

**Comment by bwssytems** [comment]
So, my best guess is your device.db got corrupted. I would delete your hue pass through devices and re add them.

**Comment by edd--** [comment]
Ha ! We're on to the right track here. I removed the hue device from the bridge config and now it works. unfortunately I'm unable to add it without having the same issue ... I'm trying to add a sonoff device that also emulates hue

**Comment by edd--** [comment]
I worked around this using MQTT to control the sonoff device, which is even a nicer solution. maybe off-topic question: but is it possible to control ha-bridge itself using MQTT ?

**Comment by bwssytems** [comment]
Was not planning on controlling ha-bridge with mqtt as there are systems like OpenHAB that already implement that.
