### ISSUE TITLE
Alexa doesn't support colors for "Color Light"-devices

### ISSUE THREAD

**Issue by nihebe** [bwssytems/ha-bridge#845]
While trying to test the new HEX-formatted colors from #821 I encountered following problem:

After I added HTTP-calls for some devices in habridge and rediscovered devices in Alexa, the Alexa web frontend shows the type `Color Light` instead of `Dimmable Light`. Even though this looks correct, I still get a "device doesn't support this"-answer when prompting Alexa to turn a lamp red.

Is this an issue connected to the new release or am I doing something wrong? The HTTP-call for the Color item is:
`http://usr:pwd@10.2.1.10:8723/fhem?cmd=set%20Ecklampe%20RGB%20${color.rgbx}`

**Comment by bwssytems** [comment]
Alexa does not support color changes yet.

**Comment by nihebe** [comment]
Okay, do you already know what's to do for this support?
Otherwise I could try do some Wireshark investigations.

**Comment by bwssytems** [comment]
IT is the Alexa software itself does not do it. Talk to Amazon.....

**Comment by nihebe** [comment]
Great.. that means even if one is using the "original" setup (Amazon Echo + Philips Hue Bridge) he won't be able to change colors without installing the cloud based skill.

Thank you Amazon 🙈

**Comment by bwssytems** [comment]
That is correct. closing

**Comment by spid3r** [comment]
hi all. is this still the case as of today? you need to install the alexa skill in order to change colors?
