### ISSUE TITLE
[5.1.0] Harmony commands not being split into on/dim

### ISSUE THREAD

**Issue by gohamstergo** [bwssytems/ha-bridge#846]
First, Thanks for fixing pairing issue in 5.1.0. Working pretty well now! But with the following oddity:

The "On Items" field is being completely ignored. Only "dim items" and "off items" are being used.

So, for example, I have the "on items" field empty and the necessary JSON in the "dim items" field and when pressing the Harmony button, the scene turns on perfectly. Off works as well.

However, my ideal functioning would be to have the Harmony button activate the "on items" field and then in the "dim items" field I could have a Hue passthru command so the brightness rocker on the Harmony Remote would function.

Additional info: When entering the passthru command into "dim items" Harmony does turn on the light and the rocker works as well. But of course, can't set a scene this way.

Hopefully this makes sense. If you want me to paste my exact config for all the fields, let me know!

**Comment by bwssytems** [comment]
You can turn on debug for the HueMulator class and see what is being called. Make sure you hit the 'UpdateLogLevels' button.

As a guess here, this may be like another app that we saw that only calls dim url as ti is always sending that call. You can always use that as your on if that is the case.

**Comment by gohamstergo** [comment]
Ya, have tried changing debug level, but wont change for some reason. Always shows info, even the green box appears saying the log level was changed, but it doesn't :\

**Comment by audiofreak9** [comment]
@bwssytems 
I have the same log level chagne issue, I can't get the log level to change for anything, but get the green confirmation that they did.

**Comment by bwssytems** [comment]
What browser are you all using? I use Chrome and have no issues.

**Comment by bwssytems** [comment]
Also, if using Chrome, you will need to Shift F5 to replace your cache as it is super aggressive on caching older pages.

**Comment by gohamstergo** [comment]
Oh, Just Trace isn't working for anything Im testing. All other levels work.

**Comment by audiofreak9** [comment]
Always Chrome, even tried the CTRL + F5 to clear the cache.  Can confirm it's just TRACE that I can't seem to get to work too.

**Comment by bwssytems** [comment]
Ahh, glad that the debugging is not an issue. Not all classes implement TRACE. Some of the packages that I pull in from others do, but all of mine only implement DEBUG.

**Comment by audiofreak9** [comment]
Good info, thanks!

**Comment by gohamstergo** [comment]
Any idea on that picture I posted. Sort of off topic for this ticket, but have those spark null reponses every 20 seconds or so and cant figure out where theyre coming from with just 'info' level showing.

**Comment by gohamstergo** [comment]
I've thought of a potential way to get harmony's on, dim, and off functions to work properly, but it would likely need to be coded on your end.

When turning a device on or using the rocker switch, harmony always sends an empty color command, on command, and a specific brightness level.

Examples:
On Pressed: "{"xy":[0,0],"on":true,"bri":50}"
Rocker switch up pressed: "{"xy":[0,0],"on":true,"bri":75}"
Off Pressed: {"on":false}

So, "on" and "dim" are currently the same, hence why only "Dim Items" is used in habridge. What we need to do is use some variables to tell habridge how to interpret what harmony is trying to do, so we can get "On Items" separated from "Dim Items."

Each habridge device could have a variable "isON" that is set to "false" by default and then when harmony sends its first PUT, the "xy" and "bri" could be ignored and only "on" would be acknowledged and could activate the call in "On Items" field in habridge. Also, the variable would change to "isON"=true.

Now, when harmony sends its next PUT, the "bri" value would be accepted and would apply to the "Dim Items field."

When harmony sends {"on":false} the variable for that device would change back to "isON"=false.

This would enable what I was hoping to do: Activate a Scene in "On Items" and use hue passthru for "Dim Items."

My knowledge is limited, so I'm just guessing at how this could work. :)

**Comment by bwssytems** [comment]
Thanks dor doing the leg work. We could put that in there as an enhancement.

**Comment by gohamstergo** [comment]
Sweeeet! Look forward to it. :)

**Comment by bwssytems** [comment]
I will call the switch in the device as Send On with first Dim.

**Comment by gohamstergo** [comment]
sweeeet. That will be an optional toggle, right? Just in case it alters the behavior of stuff people already have setup.

**Comment by bwssytems** [comment]
it is, you can try it right now in th release candidate

**Comment by gohamstergo** [comment]
where can the toggle be found? i installed rc3 but dont see it in the Edit device area. Also, version number still shows 2.1.0 in "about." unless i really am still on 2.1.0 and somehow jacked something up XD

**Comment by gohamstergo** [comment]
where is the toggle located? running rc3, but dont see it in the Edit area anywhere.

**Comment by bwssytems** [comment]
You have two versions running

**Comment by gohamstergo** [comment]
weird that the proc didnt show. either way, another reboot fix it right up. will report findings in 5.2 ticket.
