### ISSUE TITLE
Athom Homey

### ISSUE THREAD

**Issue by Deojuvente** [bwssytems/ha-bridge#847]
Hello BWSsystems

i like to reqest if you are willing to at Homey support to the HABridge?
here you can see how Homey is working: https://developer.athom.com/docs/apps

http://IPadres/api/manager/devices/device

 The target should be http://yourhomeyip/api/manager/devices/device/${device.targetDevice}/state
- HTTP type should be set to PUT
- HTTP Body should be set as {"onoff": true} for ON, {"onoff": false} for OFF and {"dim": ${intensity.decimal_percent}} for DIM
- HTTP Header should be set as [{"name":"Authorization","value":"bearer YOURBEARERTOKENHERE"}]
- Set the content type to Aplication/JSON
- Now add the device and test it on the dashboard (there is an on, off and dim button there)
- If it works, you can let Alexa or any other service that connects to Hue scan for devices again and it should pop-up.
- You can copy devices and just change the device id, by adding multiple rows to the ON, OFF and DIM fields you can add more devices to one virtual Hue light.

To find the right device id you have 2 options:
1. Go to the devices page on homey from a chrome browser, right click the device card and chose inspect, there you should find a parameter called "data-id", this is the device id.
2. Go to http://yourhomeyip/api/manager/devices/device , this outputs all your devices. To make it read-able you can copy and past it in json lint for example. http://jsonlint.com/

Thanks for you help and time
Edwin

**Comment by razorfish79** [comment]
It would be much better if someone would create a HA-Bridge -  Homey App which directly recognize the devices of the HA-Bridge in Homey. 

The things you mentioned you can realize yourself easily with the Homey App "HTTP request flow cards" and the http on, off, dim in HA-Bridge. Currently I am doing so and it works great. 

Or did I miss something?

**Comment by Deojuvente** [comment]
i have it working. its just more easy to add devices if you can add them whit one press in the ha bridge. for the vera and the fibaro it already works like that. its more for noobs how dont know how to set this up.. I like to ha bridge a lot, its so fast in response and i dont like alexa ask homey or fibaro to turn on bla bla whit the ha bridge you can just tell alexa kitchen light on and hopa it turns on.

**Comment by bwssytems** [comment]
So, I do not have a Homey device to test with this, is this still something really needed? And there seems to be only 2 persons that are requesting this.

**Comment by Deojuvente** [comment]
not for me i am useing a google home whit homey inerg. thnx
