### ISSUE TITLE
Echo stopped working (devices offline) after update no progress.

### ISSUE THREAD

**Issue by KruisR** [bwssytems/ha-bridge#848]
Hi There. I am using HA Bridge and Domoticz for a while and it has always worked flawless. Since yesterday the Echo stopped communicating with HA Bridge and i am trying to solve this. 
After updating the whole thing to 5.1.0 it still didn't find any device with the Echo. I thought that it might have to do something with the RPI 3 so i took a Zero and did a fresh install. After installing 5.1.0 at the Zero still no cure :(

Anyone having an idea or is there currently a known issue? The echo is a V1 echo and not a V2.

**Comment by bwssytems** [comment]
Make sure your ip address and ports are correctly setup in the ha-bridge for your device.

**Comment by mdescher** [comment]
Same problem here. All of a sudden Alexa won't recognize any HA Bridge devices anymore. The test buttons in HA Bridge work fine (i.e. the actual devices are configured correctly) and the IP address in HA Bridge config is the correct one.

**Comment by mdescher** [comment]
Searching for new devices in Echo did not yield any results. Removing the existing HA Bridge devices using the Alexa app and then searching again did the trick. The devices are back and working.

**Comment by Omen12345** [comment]
I have quite the same issue now. Yesterday I have received a new Echo 2. Gen which can't find any of the devices configured in the HA Bridge (Version 5.1.0) nor can control the existing devices I already had in the Smart Home section of the Amazon Alexa app. Whereas my Echo Dot 2. Gen is still able to find and control all the devices setup in HA Bridge. When both Echos are connected I can still control the lights with both Echos, but when I disconnect the Echo Dot 2. Gen the new Echo 2. Gen again is not able to control/find them. Device discovery is not possible with Echo 2. Gen (FW version 595530420)
Firmware version of Echo Dot 2. Gen: 597464620
Emulate Hue Hub Version: 1705121051

**Comment by bwssytems** [comment]
@mdescher @KruisR When changing systems, this would be the procedure to update the echo.

@Omen12345 You are experiencing an issue we have found with second generation Echos. Currently, they are not finding the bridge.

**Comment by mdescher** [comment]
I have three 2nd gen Echoes. They stopped working yesterday and are working again now after removing all devices and discovering them again. I am not sure if there still are issues. At least the whole system seems to be less reliable than before (Alexa sometimes claims that devices did not respond although they in fact reacted). But this might as well be a different issue with my WLAN or whatever else. ;-)

**Comment by bwssytems** [comment]
@mdescher So you can validate that the latest Gen 2 is working after this process of remoavel. I hope that this is true for others.

**Comment by KruisR** [comment]
I i do a Wireshark trace on my network  i am able to see that my NAS responds to port 50000 but the HA Bridge doesn't respond at all. 

Is see that the Echo does a ssdp request at port 50000 and only the NAS comes in with an ACK.

There is no need for me to remove any devices because UPNP is not working :(

**Comment by bwssytems** [comment]
@KruisR can you turn on debug for the upnp classes and post the output please.

**Comment by KruisR** [comment]
@bwssytems i got back from vacation doing the things you are asking for and everything seems to be working. After looking what might have changed:The app got an update. 

After that i added two echo's to the network and everything it working like a charme :)

**Comment by sheriffdude** [comment]
have the same problem was all working great now all light showing off line have not changed anything apart for did try to add dim light ..but that did not seem to work deleted it ..so it should all be just the same all light turn off and on from ha bridge ..just alexa cant now find the lights ..if i tell alexa to forget light it does not find it again ...just when it was working so well ...can only think UPNP IP Address may have changed ..but if i put i 0.0.0.0 it defaults to 192.168.1.14  so i am assuming thats correct
