### ISSUE TITLE
HB[5.1.0] Fibaro HomeCenter2: Devices "Build Item" not working

### ISSUE THREAD

**Issue by rems02** [bwssytems/ha-bridge#850]
HB[5.1.0] Fibaro HomeCenter2: Devices "Build Item" not working

logs:
```
habridge.service - HA Bridge
   Loaded: loaded (/home/pi/habridge/habridge.service; enabled)
   Active: active (running) since lun. 2017-12-18 19:40:34 CET; 57min ago
 Main PID: 584 (java)
   CGroup: /system.slice/habridge.service
           └─584 /usr/bin/java -jar -Dconfig.file=/home/pi/habridge/data/habridg                                             e.config /home/pi/habridge/ha-bridge-5.1.0.jar

déc. 18 20:35:48 raspberrypi java[584]: at org.eclipse.jetty.util.thread.Invocab                                             le$InvocableExecutor.invoke(Invocable.java:222)
déc. 18 20:35:48 raspberrypi java[584]: at org.eclipse.jetty.util.thread.strateg                                             y.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
déc. 18 20:35:48 raspberrypi java[584]: at org.eclipse.jetty.util.thread.strateg                                             y.EatWhatYouKill.run(EatWhatYouKill.java:199)
déc. 18 20:35:48 raspberrypi java[584]: at org.eclipse.jetty.util.thread.QueuedT                                             hreadPool.runJob(QueuedThreadPool.java:673)
déc. 18 20:35:48 raspberrypi java[584]: at org.eclipse.jetty.util.thread.QueuedT                                             hreadPool$2.run(QueuedThreadPool.java:591)
déc. 18 20:35:48 raspberrypi java[584]: at java.lang.Thread.run(Thread.java:745)
déc. 18 20:35:48 raspberrypi java[584]: 2017-12-18 20:35:48,948 [qtp5891383-33]                                              INFO  com.bwssystems.HABridge.plugins.fibaro.FibaroInfo - Found: 0 scenes
déc. 18 20:37:16 raspberrypi java[584]: 2017-12-18 20:37:16,958 [qtp5891383-40]                                              INFO  com.bwssystems.HABridge.plugins.fibaro.FibaroInfo - Found: 19 rooms
déc. 18 20:37:16 raspberrypi java[584]: 2017-12-18 20:37:16,985 [qtp5891383-40]                                              INFO  com.bwssystems.HABridge.plugins.fibaro.FibaroInfo - Found: 1 devices
déc. 18 20:37:17 raspberrypi java[584]: 2017-12-18 20:37:17,000 [qtp5891383-47]                                              INFO  com.bwssystems.HABridge.plugins.fibaro.FibaroInfo - Found: 0 scenes
```

**Comment by bwssytems** [comment]
What is the issue you see when you got build item?

**Comment by rems02** [comment]
the "Build Item" button does not work.

**Comment by bwssytems** [comment]
So, what browser are you using? I cannot see any reason that this should not work and no others seem to have this issue.

**Comment by darrenmcuk** [comment]
Same happens for me...the build button is not doing anything.

**Comment by bwssytems** [comment]
HAve you all refreshed your browser cache? As the change in 5.1.0 was to the javascript.

**Comment by rems02** [comment]
It's OK Thanks
Refreshed browser cache and it's work

**Comment by bwssytems** [comment]
Yep, thought thats what it was....

@darrenmcuk Please do the same.

**Comment by mol7os** [comment]
Doesn´t work for me in Version 5.1.0.

After click on "Build item" nothing happens.
Browser tested: Chrome, Mozilla, Edge

**Comment by bwssytems** [comment]
@mol7os Refresh your browser cache. In Chrome that is Ctrl-F5 for the tab you are in.

**Comment by mol7os** [comment]
Doesnt work for me with follwing Browsers (nothing changed after deleting Browser cache): 

1. Intenet Explorer 11.125.16299.0
2. Microsoft Edge 41.16299.15.0
3. Chrome x64 Version 63.0.3239.84 
4. Mozilla Firefox 57.0.2 (64-Bit)

**Comment by bwssytems** [comment]
@mol7os my advice is to delete your setup and try again

**Comment by bwssytems** [comment]
@mol7os Any update? No one else is reporting this issue now.

**Comment by mol7os** [comment]
Problem still exist and I expect others have this too but dont care.
Friends have same behavior since added a new Echo 2 in their environment.

The good: Commands still working
The bad: doubled, old outdated bridge devices listed in Alexa Smarthome devices.

Tried nearly everything, but no chance .... switched back to port 8081 in the first discovery everything looks fine. But after some ... same .... and Royal Phillips Devices are back in Alexa.

Maybe a combination of Echo Dot1, Echo 1 and Echo 2.

My installation includes 8 Echo devices and ~50 HABridge devices pointing to ~250 Fibaro actors on HC2.

Current Solution: Ignoring (the roller shutter working as expected), Harmony removed from HABridge cause this doesn´t work well (felt like doubled devices has impact there).

**Comment by bwssytems** [comment]
@mol7os Does the build button work at all for you?

**Comment by mol7os** [comment]
Oh my mistake. Mixed up different issues. Sorry.

No the button is not working for me. Nothing happends in all listed browsers above.
Tested Safari on MacBook too, nothing happens.

**Comment by bwssytems** [comment]
@mol7os So, the next time you try a build, open the developer console and see if there is an error in the browser. Everyone else is fixed for this but you.

**Comment by mol7os** [comment]
## Log Chrome
angular.min.js:122 ReferenceError: dimpayload is not defined
    at b.$scope.buildDeviceUrls (app.js:2148)
    at fn (eval at compile (angular.min.js:237), <anonymous>:4:387)
    at e (angular.min.js:282)
    at b.$eval (angular.min.js:147)
    at b.$apply (angular.min.js:148)
    at HTMLButtonElement.<anonymous> (angular.min.js:282)
    at HTMLButtonElement.dispatch (jquery-1.11.3.min.js:4)
    at HTMLButtonElement.r.handle (jquery-1.11.3.min.js:4)
(anonymous) @ angular.min.js:122
6angular.min.js:122 ReferenceError: dimpayload is not defined
    at b.$scope.buildDeviceUrls (app.js:2148)
    at fn (eval at compile (angular.min.js:237), <anonymous>:4:387)
    at e (angular.min.js:282)
    at b.$eval (angular.min.js:147)
    at b.$apply (angular.min.js:148)
    at HTMLButtonElement.<anonymous> (angular.min.js:282)
    at HTMLButtonElement.dispatch (jquery-1.11.3.min.js:4)
    at HTMLButtonElement.r.handle (jquery-1.11.3.min.js:4)

## Log Firfox
Source-Map-Fehler: request failed with status 404
Ressourcen-Adresse: http://rpi-smh:8081/js/angular-resource.min.js
Source-Map-Adresse: angular-resource.min.js.map

Error: dimpayload is not defined
$scope.buildDeviceUrls@http://rpi-smh:8081/scripts/app.js:2148:3
fn@http://rpi-smh:8081/js/angular.min.js line 237 > Function:4:384
e@http://rpi-smh:8081/js/angular.min.js:282:195
$eval@http://rpi-smh:8081/js/angular.min.js:147:309
$apply@http://rpi-smh:8081/js/angular.min.js:148:12
compile/</<@http://rpi-smh:8081/js/angular.min.js:282:245
dispatch@http://rpi-smh:8081/js/jquery-1.11.3.min.js:4:8497
add/r.handle@http://rpi-smh:8081/js/jquery-1.11.3.min.js:4:5235


## Log HABridge
01-04-2018 08:42:45.676 | DEBUG | Stats: [leased: 0; pending: 0; available: 0; max: 200] | com.bwssystems.HABridge.plugins.http.HttpClientPool
-- | -- | -- | --
01-04-2018 08:42:50.676 | DEBUG | Stats: [leased: 0; pending: 0; available: 0; max: 200] | com.bwssystems.HABridge.plugins.http.HttpClientPool

**Comment by bwssytems** [comment]
@mol7os Thanks, that is a huge help!

**Comment by bwssytems** [comment]
Found the issue. Thanks for the debug.

**Comment by mariefischer** [comment]
Had the same issue on 5.1.0. Works on 5.2.0RC3.

As a workaround on 5.1.0, it worked for me if the "select menu for which type of dim control" selection was something else except "none".
