### ISSUE TITLE
non-dimmable device

### ISSUE THREAD

**Issue by mill7008** [bwssytems/ha-bridge#851]
I am using ha bridge to control some non-dimmable lights. Is there any way to make ha bridge show them as only having an on/off state. OPENHAB only discovers a dimer control for ha  bridge devices which these lights don't like (It makes them flash). Can ha bridge emulate a non-dimmable device?

**Comment by bwssytems** [comment]
Unfortunately, the Hue protocol does not describe lights as binary. In OpenHAB you should be able to set the item as a switch after it is discovered.

**Comment by FloFoer** [comment]
Actually there is a light type called "On/Off plug-in unit" (for example used by the osram lightify plugs which can be integrated in the Hue system). I have such a plug in use with my real hue bridge and alexa says it's a switch, not color and not dimmable. 
As i implemented color and automatic light type depending on the situation i decided to not use this light type for 2 reasons:  

1. The Hue app doesn't care about it. It's handled like normal dimmable lights.
2. Alexa does discover the On/Off plug-in units only via the skill, so it will never work with HA-Bridge.

**Comment by bwssytems** [comment]
ing OpenHAB to call haI believe the OP was using OpenHAB to call the ha-bridge using the hue plugin. I have done that and you can change the type of item in OpenHAB to be a switch.

If we put the selection of the device type in the device config, that may help.

**Comment by mill7008** [comment]
Thanks for the help and for the great application. I've been using ha-bridge since some of the early versions. I use it as.an interface from alexa to a bunch of legacy devices in my home. I just started using openHAB so I'm not great with it yet. Having the config option in ha-bridge will help a lot.

**Comment by bwssytems** [comment]
@mill7008 This still should not be an issue as the ha-bridge interface will be fine for on/off. IF you do not want an OpenHAB item to be dimmable, you can edit the item to be a switch.
