### ISSUE TITLE
Smarththings locating ha-bridge not found

### ISSUE THREAD

**Issue by Kpocius1** [bwssytems/ha-bridge#852]
I have it installed on a windows machine and it appears to be running fine on default part 80.  I opened up the smartthings app and tried to add a thing.  The Hue Bridge showed up momentarily, and I accidentally pressed the button to rename.  It froze, so I shut down the app.

On many subsequent tries, ha-bridge is not found.  It's running, I can access via the web GUI, and I reinitialized it several times.  I even stopped it and restarted from the command line.  I even rebotted the hub, and also tried disconnecting the power and removing the batteries, and then powering back up.  No joy.  It's the most recent version, I installed December 18, 2017.

Any suggestions?

**Comment by Kpocius1** [comment]
For what it's worth, I downloaded the Hue App and it discovered the bridge.

**Comment by bwssytems** [comment]
So, it seems your ha-bridge is configured properly. Must be something with the way Smartthings is finding the bridge. Turn on traceupnp in the Bridge Control tab and then post the log here after you try to discover the ha-bridge with Smartthings again.

**Comment by Kpocius1** [comment]
I turned on traceupnp  - is this the log?:


12-20-2017 10:19:26.698 | INFO | Description xml service started.... | com.bwssystems.HABridge.upnp.UpnpSettingsResource
-- | -- | -- | --
12-20-2017 10:19:26.830 | INFO | UPNP Discovery Listener starting.... | com.bwssystems.HABridge.upnp.UpnpListener
12-20-2017 10:19:26.915 | INFO | UPNP Discovery Listener running and ready.... | com.bwssystems.HABridge.upnp.UpnpListener

**Comment by Kpocius1** [comment]
I'm not sure why, but after I enabled trace it worked.  I'm now connected.  Thanks.

**Comment by bwssytems** [comment]
I see you restarted your ha-bridge after saving some info I believe.
