### ISSUE TITLE
Turn Logging off

### ISSUE THREAD

**Issue by einmalacht** [bwssytems/ha-bridge#853]
Hello i will prevent my SD card from damage and will turn complete loggin off in HA-Bridge.
But i dont know how i can turn all logging off ....
Some message from java runns in my syslog ..

**Comment by sigma415** [comment]
Same question here.
Also it's not clear for me, how the log level can be controlled.
I changed it to WARN, but this setting seems not to be persistent.
I still get a flooded log with:
" INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] "

habridge 5.1.0

Thank you

**Comment by bikeymouse** [comment]
I agree with this suggestion/question, for the same reasons, both having an SD-card as having the The "requested route [/(null)] has not been mapped in Spark for Accept: [null]" flooding my log on ha-brdige 5.1.0.

**Comment by bwssytems** [comment]
The /(null) will go away in the next release, so this won't be an issue.

**Comment by heikoh81** [comment]
Yes, but I also would prefer to be able to turn off logging completey.
If  my system is stable, I don't need logs. As I'm on a raspberry with SD card, I like to minimize all writes that I don't need!

**Comment by bwssytems** [comment]
Will take a look

**Comment by bwssytems** [comment]
So, if you want to not write to your logs, start your ha-bridge command line with the redirect to null... i.e. java -jar ha-bridge-5.1.0.jar > /dev/null in your start up script. The output will not be logged anywhere. You still will be able to see log entries on the ha-bridge UI as that is kept in memory.

**Comment by heikoh81** [comment]
Thanks, will give that a try.

**Comment by bwssytems** [comment]
Did that trick work?

**Comment by heikoh81** [comment]
No, unfortunately it does NOT work.

I have this in /etc/systemd/system/habridge.service
(the code tag seems not to work here on Github like in other forums)

> Description=HA Bridge
> Wants=network.target
> After=network.target
>  
> [Service]
> Type=simple
>  
> ExecStart=/usr/bin/java -jar -Dserver.port=81 -Dconfig.file=/home/pi/habridge/data/habridge.config /home/pi/habridge/ha-bridge.jar > /dev/null
>  
> [Install]
> WantedBy=multi-user.target

Still getting this in syslog:
Any more suggestions on how to disable logging completely?

> 
> Jan 19 18:13:22 raspcam6 java[22232]: 2018-01-19 18:13:22,872 [qtp1130427-15] INFO  spark.http.matching.MatcherFilter - The requested route [/(null)] has not been mapped in Spark for Accept: [null]
> Jan 19 18:13:32 raspcam6 java[22232]: 2018-01-19 18:13:32,908 [qtp1130427-8] INFO  spark.http.matching.MatcherFilter - The requested route [/(null)] has not been mapped in Spark for Accept: [null]
> Jan 19 18:13:53 raspcam6 java[22232]: 2018-01-19 18:13:53,405 [qtp1130427-14] INFO  spark.http.matching.MatcherFilter - The requested route [/(null)] has not been mapped in Spark for Accept: [null]
> Jan 19 18:14:17 raspcam6 java[22232]: 2018-01-19 18:14:17,962 [qtp1130427-8] INFO  spark.http.matching.MatcherFilter - The requested route [/(null)] has not been mapped in Spark for Accept: [null]
> Jan 19 18:14:39 raspcam6 java[22232]: 2018-01-19 18:14:39,762 [qtp1130427-13] INFO  spark.http.matching.MatcherFilter - The requested route [/(null)] has not been mapped in Spark for Accept: [null]
> Jan 19 18:15:05 raspcam6 java[22232]: 2018-01-19 18:15:05,378 [qtp1130427-8] INFO  spark.http.matching.MatcherFilter - The requested route [/(null)] has not been mapped in Spark for Accept: [null]
> Jan 19 18:15:12 raspcam6 java[22232]: 2018-01-19 18:15:12,471 [qtp1130427-14] INFO  spark.http.matching.MatcherFilter - The requested route [/(null)] has not been mapped in Spark for Accept: [null]
> Jan 19 18:15:45 raspcam6 java[22232]: 2018-01-19 18:15:45,463 [qtp1130427-13] INFO  spark.http.matching.MatcherFilter - The requested route [/(null)] has not been mapped in Spark for Accept: [null]
> Jan 19 18:16:07 raspcam6 java[22232]: 2018-01-19 18:16:07,226 [qtp1130427-11] INFO  spark.http.matching.MatcherFilter - The requested route [/(null)] has not been mapped in Spark for Accept: [null]
> Jan 19 18:16:25 raspcam6 java[22232]: 2018-01-19 18:16:25,570 [qtp1130427-9] INFO  spark.http.matching.MatcherFilter - The requested route [/(null)] has not been mapped in Spark for Accept: [null]
> Jan 19 18:17:02 raspcam6 java[22232]: 2018-01-19 18:17:02,048 [qtp1130427-12] INFO  spark.http.matching.MatcherFilter - The requested route [/(null)] has not been mapped in Spark for Accept: [null]
> Jan 19 18:17:05 raspcam6 java[22232]: 2018-01-19 18:17:05,682 [qtp1130427-11] INFO  spark.http.matching.MatcherFilter - The requested route [/(null)] has not been mapped in Spark for Accept: [null]
> Jan 19 18:17:25 raspcam6 java[22232]: 2018-01-19 18:17:25,640 [qtp1130427-8] INFO  spark.http.matching.MatcherFilter - The requested route [/(null)] has not been mapped in Spark for Accept: [null]
> Jan 19 18:17:47 raspcam6 java[22232]: 2018-01-19 18:17:47,751 [qtp1130427-13] INFO  spark.http.matching.MatcherFilter - The requested route [/(null)] has not been mapped in Spark for Accept: [null]
> Jan 19 18:17:56 raspcam6 java[22232]: 2018-01-19 18:17:56,539 [qtp1130427-11] INFO  spark.http.matching.MatcherFilter - The requested route [/(null)] has not been mapped in Spark for Accept: [null]
> Jan 19 18:18:09 raspcam6 java[22232]: 2018-01-19 18:18:09,237 [qtp1130427-13] INFO  spark.http.matching.MatcherFilter - The requested route [/(null)] has not been mapped in Spark for Accept: [null]

**Comment by bwssytems** [comment]
You will need to add '2> /dev/null' as well since that must be going out the error side

**Comment by bwssytems** [comment]
Also, the release candidate will not have the /null issue.

**Comment by heikoh81** [comment]
No luck either.

I know that RC4 doesn't produce the /null issue, however, I tried RC4 a few days ago and had "no devices issues" again...

However, it would be great to have a way to disable logging completely if needed.
As I said, if my System is running, I don't Need the logs.

Jan 19 22:02:15 raspcam6 java[23210]: 2018-01-19 22:02:15,620 [qtp13607222-10] INFO  spark.http.matching.MatcherFilter - The requested route [/(null)] has not been mapped in Spark for Accept: [null]
Jan 19 22:02:19 raspcam6 java[23210]: 2018-01-19 22:02:19,641 [qtp13607222-9] INFO  spark.http.matching.MatcherFilter - The requested route [/(null)] has not been mapped in Spark for Accept: [null]
Jan 19 22:02:19 raspcam6 java[23210]: 2018-01-19 22:02:19,652 [qtp13607222-13] INFO  spark.http.matching.MatcherFilter - The requested route [/(null)] has not been mapped in Spark for Accept: [null]

**Comment by bwssytems** [comment]
Ahh my instructions may not be correct, just user '&> /dev/null'

ExecStart=/usr/bin/java -jar -Dserver.port=81 -Dconfig.file=/home/pi/habridge/data/habridge.config /home/pi/habridge/ha-bridge.jar &> /dev/null

**Comment by heikoh81** [comment]
Again, no luck:

Jan 19 23:54:11 raspcam6 java[23692]: 2018-01-19 23:54:11,261 [qtp32109218-9] INFO  spark.http.matching.MatcherFilter - The requested route [/(null)] has not been mapped in Spark for Accept: [null]
Jan 19 23:54:25 raspcam6 java[23692]: 2018-01-19 23:54:25,019 [qtp32109218-11] INFO  spark.http.matching.MatcherFilter - The requested route [/(null)] has not been mapped in Spark for Accept: [null]
Jan 19 23:54:25 raspcam6 java[23692]: 2018-01-19 23:54:25,029 [qtp32109218-8] INFO  spark.http.matching.MatcherFilter - The requested route [/(null)] has not been mapped in Spark for Accept: [null]

**Comment by bwssytems** [comment]
So, there is more options on linux command line redirect. I would suggest you google for those and find the one that works.

**Comment by heikoh81** [comment]
I totally understand that Java logging Options are not to be solved within this project.
However, to my understanding, there should be the possibility to set a log Level within your program code (Info / Error / All / None / etc).
Maybe you find time in the future to implement this.

**Comment by bwssytems** [comment]
So, I can do this for my code, but the other packages I pull in from other repositories don't, such as spark errors you are seeing. When the new version comes out and u use the redirect, you won't get that many error messages and unless you are using an sdcard in the MB range, there really are no worries writing to a modern high speed sdcard. Also, you could set your syslog control to limit the file size and only rotate one log. Do a little digging on Linux syslog. This would work for any application you run on your pi. Please look at this solution as it would benefit what you are trying to accomplish across your system.

**Comment by ikuria** [comment]
how do you disable the log now?

**Comment by bwssytems** [comment]
Read the previous post on setting the program output on the command line with /dev/null
