### ISSUE TITLE
running habridge with openjdk-9-jre requires --add-modules java.xml.bind

### ISSUE THREAD

**Issue by thomasgresch** [bwssytems/ha-bridge#854]
Hi 

After some debugging and getting strange 500 errors while trying a new device to habridge I realized that I have to add `--add-modules java.xml.bind` to invike habridge. 

So my habridge.service now looks like:

`[Unit]
Description=HA Bridge
Wants=network.target
After=network.target

[Service]
Type=simple
WorkingDirectory=/home/habridge/habridge
ExecStart=/usr/bin/java -jar -Dconfig.file=/home/habridge/habridge/data/habridge.config --add-modules java.xml.bind /home/habridge/habridge/ha-bridge-5.1.0.jar

[Install]
WantedBy=multi-user.target`

-> could you please update the readme for other not to stumble over it too?

**Comment by bwssytems** [comment]
Ahh, haven't tested this with java 9 so that would be at your own risk.

**Comment by bwssytems** [comment]
Closing as added this ti the wiki https://github.com/bwssytems/ha-bridge/wiki/HA-Bridge-FAQs#q-ha-bridge-errors-when-running-with-java9

**Comment by sanderlv** [comment]
Sorry to ask a new question. 

But "where" do I do this:
Q: Ha-bridge errors when running with Java9?
A: You have to add `—add-modules java.xml.bind` to invoke the ha-bridge using Java9.

**Comment by ESF-nl** [comment]
> Sorry to ask a new question.
> 
> But "where" do I do this:
> Q: Ha-bridge errors when running with Java9?
> A: You have to add `—add-modules java.xml.bind` to invoke the ha-bridge using Java9.

A few years later: I still have the same error 500. More apps require java 11. Does somebody know how do I add modules as suggested?

**Comment by bwssytems** [comment]
In the newer versions, this is a moot point as we do not use the libraries anymore. Use newer version of habridge.
