### ISSUE TITLE
Echo Show cant find devices

### ISSUE THREAD

**Issue by du6jip** [bwssytems/ha-bridge#855]
I have an Echo Dot (2nd Gen) working nicely with HA, I bought an Echo Show recently and it cant find the devices. I added new devices and let Echo Show search for it but no luck. "No devices found", then I tried the Echo Dot and it found the new device. Can they share same HA-Bridge?

**Comment by henits** [comment]
Are they logged in with the same amazon account?

**Comment by du6jip** [comment]
I tried Logging in the same acct and seperate acct. Still Cant find it

**Comment by henits** [comment]
But there is only one ha-bridge running?

**Comment by bwssytems** [comment]
Echo show is already known not to find local hue type devices such as the ha-bridge.

**Comment by TomHenderson4** [comment]
"Echo show is already known not to find local hue type devices such as the ha-bridge."

Is this known issue possible to fix, or am I just out of luck?

**Comment by bwssytems** [comment]
Out of luck, but if you buy an Amazon dot, it will share what it finds wit the show.

**Comment by TomHenderson4** [comment]
That's useful info about the dot! I was already considering getting one for another room.

**Comment by AnayaDic** [comment]
Some solutions if your echo show  can't find device and unable to set error  then read here
1. Sometimes echo will not power on, so check power adapter is plugged in.
2. Restart your device.
3.  You can also check that echo show is not snooze mode and able to connect the local network.
4. If your echo show device is nearby any other device such as computer or printer then move echo away from these devices and reboot your device by holding the power button for 30 seconds.
Getting more solutions to troubleshoot echo show issues by [echo show support team](https://echoalexasupport.com/echo-show-support/).

**Comment by TomHenderson4** [comment]
Thanks, but it turns out the show simply doesn't have that capability. 
No amount of rebooting or relocating will change the outcome. In my case 
I solved it by following advice shared here. I bought a spot that I 
needed anyway for another room and let it do the discovering. It worked 
on the first try. Now the discovered devices are know to both the show 
and the dot.

Tom Henderson

**Comment by bwssytems** [comment]
So, in th thread #890 There is some success with the show. Also the n v5.2.0 has some changes for upnp response timings that may help.

**Comment by bwssytems** [comment]
Any updates?

**Comment by bwssytems** [comment]
Will close this in reference to #890
