### ISSUE TITLE
Anyway to add a socket to HABridge

### ISSUE THREAD

**Issue by jouster1974** [bwssytems/ha-bridge#856]
I've got a new Alexa enabled bulb that works fine..but as Alexa sees it as a socket style device rather than a bulb, I cant add it to a group so I can say "Alexa lights off".  instead, I currently need to specify the light bulb name.

Is there a way via HAbridge to make Alexa think this is a bulb so this cant be accomplished.

TIA   Merry Christmas

**Comment by bwssytems** [comment]
What brand device is it?

**Comment by jouster1974** [comment]
It's a generic Chinese brand...works on the efamily plus apps...It has a
mac address and IP address but I cant tell you any more than that
really...very vague I know but thought I would enquire all the same

Happy Christmas

**Comment by bwssytems** [comment]
You probably can as there is tcp device in the ha-bridge. You just need to find out what to send it.

**Comment by bwssytems** [comment]
Any update on this?
