### ISSUE TITLE
Echo doesn't find devices of one ha-bridge, ha-bridge devices of another Raspberry Pi are found

### ISSUE THREAD

**Issue by henits** [bwssytems/ha-bridge#857]
I know it is not a very new problem Echo doesn't find ha-birdge devices. I had the same issue and although I read every issue concerning the problem, I couldn't solve it. So I decided to run ha-bridge on another Raspberry Pi: And it worked fine. My Echo Dot discovered every device without any problems.

Some information:

Raspberry Pi who is **not** working:

- Raspberry Pi 3 Model B
- connected with an ethernet cable
- ha-bridge was running on port 80 and port 81: none of that worked
- it worked until I had to delete the devices in the Alexa app
- apache2 is running on the same RPi but on another port
- raspberry-remote is running too on this one

Raspberry Pi who is working:

- Raspberry Pi Zero W
- connected via WLAN
- ha-bridge is running on the normal port (80)
- no webserver is running on that one#

I installed the newest version (v5.1.0) of ha-bridge on both of them.

**Comment by henits** [comment]
I just re-installed everything on the RPi 3. Now everything is working almost fine but Echo says that my devices are offline.

**Comment by bwssytems** [comment]
Did you run traceupnp on the ha-bridge on the first pi setup? Most times it is a network setup.

**Comment by bwssytems** [comment]
Any update on this?

**Comment by henits** [comment]
I am sorry I could answer for quiet a long time, but now I am back working on this problem!
I turned on trace upnp and it showed me this output. `

07-02-2018 23:42:57.358 | INFO | >> Listening on 0.0.0.0:81 | spark.embeddedserver.jetty.EmbeddedJettyServer
-- | -- | -- | --
07-02-2018 23:42:57.427 | INFO | Hue emulator service started.... | com.bwssystems.HABridge.hue.HueMulator
07-02-2018 23:42:57.531 | INFO | Description xml service started.... | com.bwssystems.HABridge.upnp.UpnpSettingsResource
07-02-2018 23:42:57.549 | INFO | UPNP Discovery Listener starting.... | com.bwssystems.HABridge.upnp.UpnpListener
07-02-2018 23:42:57.551 | INFO | UPNP Discovery Listener running and ready....

`
I notice that it is listening on 0.0.0.0:81 although this is not my IP Adress. Where can you change this?

**Comment by bwssytems** [comment]
The 0.0.0.0 means it is listening on all ip addresses on your machine. Your issue is you need to have the bridge listen on port 80 not 81.

**Comment by henits** [comment]
A few versions ago I could even discover devices on port 81 so I thought that should not be a problem. But I changed it anyways. It is still not working. Apparently there are just no UPNP calls received by my pi.

**Comment by bwssytems** [comment]
Did you turn on traceupnp in the settings page and look at the upnp chatter?

**Comment by henits** [comment]
I turned on trace upnp. Where can I find the upnp chatter?

**Comment by bwssytems** [comment]
It is in the log of the ha-bridge. You can view it on the logs tab. Or you can look at your log facility.
