### ISSUE TITLE
Something wrong maybe with java when i started the ha-bridge

### ISSUE THREAD

**Issue by rainble** [bwssytems/ha-bridge#858]
I downloaded the jar from github and follow the steps in readme. When i used the command `sudo systemctl start habridge.service` , nothing happened and localhost:80 is disconnected. Then i saw the log, it showed me as follow:
```
Dec 25 19:59:32 sun-ThinkPad-X270 systemd[1]: Started HA Bridge.
Dec 25 19:59:32 sun-ThinkPad-X270 systemd[19689]: habridge.service: Failed at step CHDIR spawning /usr/bin/java: No such file or directory
Dec 25 19:59:32 sun-ThinkPad-X270 systemd[1]: habridge.service: Main process exited, code=exited, status=200/CHDIR
Dec 25 19:59:32 sun-ThinkPad-X270 systemd[1]: habridge.service: Unit entered failed state.
Dec 25 19:59:32 sun-ThinkPad-X270 systemd[1]: habridge.service: Failed with result 'exit-code'.

```
So i reinstalled my java environment by apt-get and try again. This error appeared again.
So i have no idea about this. Anyone help?

**Comment by bwssytems** [comment]
The error shows it cannot find java. Install java 8.

**Comment by bwssytems** [comment]
Any update on this?

**Comment by rainble** [comment]
Sorry so much for replaying late (from last week till now my internet speed
was too slow to visited github. It`s a very common problem in China). I
reinstalled the OS and reinstalled java8, then it did work. Thanks a lot
for your timely help.



2018-01-05 5:20 GMT+08:00 BWS Systems <notifications@github.com>:

**Comment by flo1985august** [comment]
Hi, 
i have the same issue. Java is installed. I've also switched the versions from 11 to 8, but could not resolve the problem.
Any further suggestions?
BR
Florian
