### ISSUE TITLE
How to properly add automation script to HA Bridge?

### ISSUE THREAD

**Issue by ferbulous** [bwssytems/ha-bridge#859]
Hi, I'm having some problem adding automation script with HA bridge. So far it works fine with switch
Using similar setup to this

https://community.home-assistant.io/t/simple-tv-channel-command-sequencing-broadlink-rf-ir-blaster/14056/9?u=ferbulous

The automation script is listed in homeassistant devices

![bbce606aed97fc4663ff448ec5b2d3a2bad4dcaf_1_690x357](https://user-images.githubusercontent.com/24526737/34383632-72a7ef0c-eb51-11e7-9aae-83b78b954136.png)
![ece7dcd1fe2e6ed8d7c7365c8ca28eff1ee4fe97_1_690x249](https://user-images.githubusercontent.com/24526737/34383633-72e32932-eb51-11e7-84a1-bbe5401e5776.png)
![ee034b0acabb34d6c706623891d6ce8fff34e711](https://user-images.githubusercontent.com/24526737/34383646-8fb2c2c0-eb51-11e7-9c9b-c713f554ccdd.png)

However, nothing happens when I tried turning it on in ha bridge and broadlink device was not blasting ir signal at the same time. 
The configuration is working fine as I can still use ifttt to trigger the channel automation or from the front end

![04b64f725fa602f8a7bdb7a29be276c7193ee7b2](https://user-images.githubusercontent.com/24526737/34383682-d8b50528-eb51-11e7-8e7e-d130d5df7ffd.png)

Is there any anything else I need to configure properly with automation script?

**Comment by bwssytems** [comment]
Please check your log for errors. Post the log here if there are questions.

**Comment by ferbulous** [comment]
Hi, this is the log output

> Dec 27 23:35:07 bpi-iot-ros-ai hass[1384]: #033[32m2017-12-27 23:35:07 INFO (MainThread) [homeassistant.components.http] Serving /api/services/switch/turn_on to 192.168.2.74 (auth: True)#033[0m
**Dec 27 23:35:07 bpi-iot-ros-ai hass[1384]: #033[32m2017-12-27 23:35:07 INFO (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: service=turn_on, service_call_id=3047619536-74, service_data=entity_id=switch.fan_speed_2, domain=switch>#033[0m**
Dec 27 23:35:07 bpi-iot-ros-ai hass[1384]: #033[32m2017-12-27 23:35:07 INFO (MainThread) [homeassistant.core] Bus:Handling <Event service_executed[L]: service_call_id=3047619536-74>#033[0m
Dec 27 23:35:08 bpi-iot-ros-ai avahi-daemon[367]: Invalid response packet from host 192.168.2.83.
Dec 27 23:35:08 bpi-iot-ros-ai avahi-daemon[367]: Invalid response packet from host 192.168.2.83.
Dec 27 23:35:09 bpi-iot-ros-ai avahi-daemon[367]: Invalid response packet from host 192.168.2.83.
Dec 27 23:35:09 bpi-iot-ros-ai avahi-daemon[367]: Invalid response packet from host 192.168.2.83.
Dec 27 23:35:09 bpi-iot-ros-ai avahi-daemon[367]: Invalid response packet from host 192.168.2.83.
Dec 27 23:35:09 bpi-iot-ros-ai avahi-daemon[367]: Invalid response packet from host 192.168.2.83.
Dec 27 23:35:09 bpi-iot-ros-ai avahi-daemon[367]: Invalid response packet from host 192.168.2.83.
Dec 27 23:36:32 bpi-iot-ros-ai avahi-daemon[367]: Invalid response packet from host 192.168.2.83.
Dec 27 23:36:33 bpi-iot-ros-ai hass[1384]: #033[32m2017-12-27 23:36:33 INFO (MainThread) [homeassistant.components.http] Serving /api/services/automation/turn_on to 192.168.2.74 (auth: True)#033[0m
**Dec 27 23:36:33 bpi-iot-ros-ai hass[1384]: #033[32m2017-12-27 23:36:33 INFO (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: service=turn_on, service_call_id=3047619536-77, service_data=entity_id=automation.maya_hd, domain=automation>#033[0m
Dec 27 23:36:33 bpi-iot-ros-ai hass[1384]: #033[32m2017-12-27 23:36:33 INFO (MainThread) [homeassistant.core] Bus:Handling <Event service_executed[L]: service_call_id=3047619536-77>#033[0m**
Dec 27 23:36:33 bpi-iot-ros-ai avahi-daemon[367]: Invalid response packet from host 192.168.2.83.
Dec 27 23:36:33 bpi-iot-ros-ai avahi-daemon[367]: Invalid response packet from host 192.168.2.83.
Dec 27 23:36:34 bpi-iot-ros-ai avahi-daemon[367]: Invalid response packet from host 192.168.2.83.
Dec 27 23:36:34 bpi-iot-ros-ai avahi-daemon[367]: Invalid response packet from host 192.168.2.83.
Dec 27 23:36:34 bpi-iot-ros-ai avahi-daemon[367]: Invalid response packet from host 192.168.2.83.
Dec 27 23:36:35 bpi-iot-ros-ai avahi-daemon[367]: Invalid response packet from host 192.168.2.83.

The first action is for my fan speed which works, second is for tuning channel where nothing happens

**Comment by bwssytems** [comment]
Is there any error in the ha-bridge log? Not sure what to say about issues within HomeAssistant.

**Comment by bwssytems** [comment]
Any update on this?

**Comment by ferbulous** [comment]
Sorry, i won't be back home until this weekend.
I'll provides more updates on it later
