### ISSUE TITLE
Can you link IFTTT to the HueMulator

### ISSUE THREAD

**Issue by dmoos777** [bwssytems/ha-bridge#86]
Love this software BTW it has allowed me to tie my X10 System and IR control into the amazon echo using a raspberry pi, with the built in IR stuff in the Raspberry and mochad/heyu.  Here in one example of what I am currently doing.

Alexa turn on Channel 7.  I have a bridge device called channelseven which in turn runs am http  command on the raspberry pi which then sends the correct IR commands to change to channel 7.  However the echo is a little touchy with some names like ESPN and BBC, so some commands like "Alexa turn on BBC" don't work. 

Here is where I am going with this.
Would be nice to use IFTTT and have a single device called Channel.  So I could say "Alexa Trigger Channel 7 or trigger Channel BBC and then have the bridge pass the third word as a variable. 

I guess the possibilities could be endless.  Anyway, not sure it's possible, just a thought.  Thanks again for all of your hard work on this project.

**Comment by bwssytems** [comment]
I have not looked into being an IFTTT channel and as every bridge is in someones network, I don't know if that would work.

**Comment by bwssytems** [comment]
So, if you want to be very unsecured, you could use this https://ifttt.com/maker. I would not take any responsibility in anyone exposing the bridge to the internet. Just a Bad, Bad, Bad idea....

**Comment by dmoos777** [comment]
I think I agree with you, but will look into it.  Thanks for the info.
