### ISSUE TITLE
Echo Plus: No discovery after factory reset

### ISSUE THREAD

**Issue by sigma415** [bwssytems/ha-bridge#861]
Hello,

until yesterday I had a working ha-bridge system with my new Echo Plus but then I took the wrong decision:  I did a factory reset on the Echo Plus.  :(

Since then Echo Plus does not discover the ha-bridge server anymore. It looks like Echo+ never calls the IP address of the server: I could not find any reference to the IP of Echo Plus when tracing the UPNP calls in log.

Any help or hints what I can do the solve the problem ? Thanks a lot

**Comment by bwssytems** [comment]
Well that seems odd.  Even the gen 2s call the bridge but just do not pair. Will have to see if others have seen this.

**Comment by Malarcy** [comment]
Echo plus isn’t working for me. Simply won’t discover. 

I have also seen this with other hue emulators. (The node red one ) 

Planning on some testing over the next few days to see if I get anywhere.

**Comment by bwssytems** [comment]
See #860

**Comment by bwssytems** [comment]
Please go test RC version in #863

**Comment by bwssytems** [comment]
In the Amazon Echo App on your phone, do a add scene as it will go and discover again but it seems it may be different.

**Comment by bwssytems** [comment]
So V5.2.0 is out there and it has an update for upnp sending. Please try and see if your echo 2nd gen is working now.
