### ISSUE TITLE
Echo will not detect devices on HA Bridge

### ISSUE THREAD

**Issue by pbrisebois** [bwssytems/ha-bridge#862]
I am currently trying to get my new Echo Plus (Canadian Version) to run my Vera lights and scenes. What I am using is a Windows PC, running HA-Bridge 5.1.0, I also updated to the newest version of Java and the inbound firewall is configured to allow Java through. I also created a batch file with the following line: java -jar -Dserver.port=8081 ha-bridge.jar.

When I start the batch file, then open Google Chrome, I type in my windows pc IP address (192.168.2.159:8081) and HA Bridge starts fine. I am also able to go into the Bridge Control tab and configure my vera. When I save (or Bridge Reinitialize) I do get the Vera Devices and Vera Scenes at the top. As well, I am able to pick one of my lights (in Vera Devices), build item and the light now shows in the Bridge Devices tab. I am also able to test by turning the light on and off.....works great up to this point. However, when I ask Alexa to discover devices (or try manually via the web browser or my android app), Alexa does not find the device?

I did try other ports that were not used (I tried 8080 and 8085), I also tried an older version HA Bridge jar file (3.5.1)........and still nothing seems to work. I also checked if uPnP was enabled on my router, it is enabled.

Is there something that I am missing here or doing wrong?

I have enabled Trace UPNP Calls and have attached a text file to show the script. The IP's are as follows, CPU IP: 192.168.2.159, Echo Plus IP: 192.168.2.126. My version Java is SE JDK 8 update 151.
[HA Bridge bat text.txt](https://github.com/bwssytems/ha-bridge/files/1594589/HA.Bridge.bat.text.txt)

**Comment by Malarcy** [comment]
I have an echo plus and I can’t get it to discover habridge. 

I have had some success with doing the discovery from other devices. ( the ap on iPhone and a ten 2 echo dot but that is unreliable for me - I have a separate issue running for that )

So no help except to say I don’t think it’s just you 

I am planning on spending some time trying to get the echo plus to play nice will post what I find.

**Comment by bwssytems** [comment]
The next version works better with the upnp timing which seems to fix it for gen 2 echos as well.

**Comment by bwssytems** [comment]
Also see #860

**Comment by bwssytems** [comment]
Please go test RC version in #863

**Comment by bwssytems** [comment]
In the Amazon Echo App on your phone, do a add scene as it will go and discover again but it seems it may be different.

**Comment by mcclaur** [comment]
I have been trying for over a month to get Alexa to discover my RPi running HABridge to control my X10 lights.  I have scoured this forum and the Web and tried everything but nothing worked.  I started with release 5.0 and upgraded to 5.1, 5.2, 5.2RC1, 5.2RC3 and then this morning 5.2RC4.  I am not sure what was different in RC4 that would have addressed discovery but without any other changes my devices were discovered and are working perfectly.  I wanted to mention this in case someone else was experiencing a similar issue.  Thank you bwssystems!

**Comment by mcclaur** [comment]
While doing some additional testing I discovered something odd.  I have one gen 2 Echo Dot tied to my Amazon account and I am in a Household with my son who has a Prime account.  At the time I did the successful discovery mentioned in my previous post I was unknowingly logged into his account.  The discovery works consistently when logged into his account but does not work from mine.  I can find no differences between the accounts in the settings and I can't imagine his Prime account has any impact on discovery.  I am at a bit of a loss but plan to do some additional testing.

**Comment by Malarcy** [comment]
When you are logged in to his account when doing discovery where / how are you stating the discovery ?

It’s not a scenario I am familiar with but maybe only the person who holds the account can do things like that. 

Not sure how that would work but maybe ethereal are features that get unlocked when you have a different account setup. 

I always do discovery by a voice command “Alexa discover devices “

**Comment by mcclaur** [comment]
I typically start the discovery from HABridge by selecting MyEcho, log in and in the Alexa app select Smart Home, Devices, Discover.  I did try the voice command before but had no luck.  Your post made me think more about the accounts so I asked Alexa "What account is this?"  She responded with my son's account.  I asked Alexa to switch accounts to mine and re-ran discovery.  The discovery worked so I feel a bit silly not realizing discovery was tied to the specific Household account being used.  Oh well, at least it is now working and I understand why.

**Comment by kevvv31** [comment]
It's a great input, as I have also been trying for a month to make it works and no success...
But your solution cannot be adapted to my situation as I am the only account holder and cannot switch to another account..
But I hope it will helps other people. Thanks

**Comment by Riddlr** [comment]
Is there any fix to this issue?  My Echo 2 can't find my HA-Bridge 5.1.0

**Comment by hefat** [comment]
HABridge must be on port 80, I use it on a PI 3 with Homegenie.  HG is on port 81. Before HaBridge was on 81 en HG on 80 and my echo 2gen found no devices at all. Also the must be on the same network.
After changing ports and rebooting Homegenie, HABridge and my PI 3  I went to HABridge tab Bridge Devices and push "test on" en than "test of" of every device, then i went to my echo plus  and "suprise", the were all there. ( in the pi for changing the port use "sudo nano /etc/systemd/system)/habridge.service"

**Comment by Riddlr** [comment]
Thanks @hefat that was it - I installed it on an  pogoplug that wasn't using port 80 and it worked after a few attempts to discover devices.  The original box I had it on has nginx on port 80, so I couldn't use it.  So my Echo 2 is working just fine again.  Interestingly the commands were all working, but Alexa was stating that device x isn't responding.  I un/re/plugged and that problem went away.

**Comment by bwssytems** [comment]
So V5.2.0 is out there and it has an update for upnp sending. Please try and see if your echo 2nd gen is working now.

**Comment by vador98** [comment]
I'm on V5.2.0 and my Echo Dot still is not finding my devices.

**Comment by bwssytems** [comment]
My scenario that seems to work:

** Make sure you have enabled the 'Use Link Button' in the ha-bridge security settings!

start discover on Alexa
press the link button on the ha-bridge 'Bridge Devices' tab
most likely this discover will not find anything
start discover on Alexa again
press the link button on the ha-bridge 'Bridge Devices' tab
after Alexa finishes, you should see your devices or new devices added

**Comment by vador98** [comment]
I was very hopeful that enabling link in the security settings would fix the problem, but sadly, no. I will try again in the morning, but as of right now, Alexa still can’t see the bridge.

**Comment by bwssytems** [comment]
Have you done all the items in the Trouble shooting faq? https://github.com/bwssytems/ha-bridge/wiki/Trouble-Shooting#q-echo-does-not-discover-my-ha-bridge

**Comment by vador98** [comment]
I really appreciate the help!  I hadn't seen that troubleshooting section yet, but I've now gone through it to no avail.  Steps taken:

- Set the upnp IP to the machine IP
- Verified the web server port is set to 80
- Verified upnp is enabled on my router
- Turned on upnp tracing.  I've attached the findings.
- Tried the touchy 2nd gen Echo steps
[HA Bridge.log](https://github.com/bwssytems/ha-bridge/files/1811380/HA.Bridge.log)

**Comment by michaelhinchey** [comment]
I used version 2 echo I'm almost sure and had no issues with finding the bridge. I now use the echo smart hub though.  I've never had an issue since version 3 of habridge.

**Comment by bwssytems** [comment]
@vador98 So let's start here:

```
03-14-2018 13:45:35.549	WARN	The upnp config address, 192.168.1.74, does not match any known IP's on this host.	com.bwssystems.HABridge.BridgeSettings
```
You are not getting the correct ip for your host. What type of system is this?

**Comment by vador98** [comment]
This is running inside a container on a QNAP NAS. I have port 80 forwarded to the container.  I will look into what sort of IP changes may need to happen.

**Comment by bwssytems** [comment]
I believe this has been discussed before. Search all issues (even closed) for QNAP and you may find some hints.

**Comment by vador98** [comment]
I found 5 questions that were in regards to QNAP devices, but none of them really addressed this same sort of issue.  I had originally tried to run this outside of the container, but ran into issues with port 80 being taken.  After I installed this in the container, I decided to move the other web server to a different port to allow this to have control, but it obviously didn't work.  

I decided to try running this outside of the container again and voila!  Alexa was finally able to see my devices.  I now need to figure out how to get this to start automatically since QNAP doesn't use systemd, but I think I'm on the right track.  Thanks again for your help!

**Comment by bwssytems** [comment]
@Malarcy @pbrisebois Do you have any updates?

**Comment by Malarcy** [comment]
Every version since the 1st RC with the modified timing has improved things for me.

I have had successful discovery with echo plus and eco dot v2. 

I have seen some inconsistencies in the echo response and the Alexa app. Both have run discovery, said they found nothing new (or never actually spoken the dreaded phrase ) but a refresh of the app or the web view shows the devices. 

For my setup, for my issues discovery has gone from doesn’t work find new solution to works most of the time, occasional glitch, but workable. 

My environment is complicated because I have 5 Alexa devices  and for best results I need to run discovery on all of them even though they all think they know everything anyway.

**Comment by bwssytems** [comment]
@Malarcy Good to hear. With the 2nd gen Echo that I am testing, it seems more sensitive and need to do multiple discoveries to have it add devices. But working as well. I think I will close this as it was related to 2nd gen devices which are now working.

**Comment by vador98** [comment]
To close the loop on my issue...  When this is installed on the main system, all configuration is lost when the system is restarted.  I decided to try the container one more time and found a solution.  If you set the network settings to bridge mode for the container, give the container a static IP via a virtual switch.  This will allow all traffic to be forwarded to your container, and it will appear as its own system on the network.  After doing this and clicking the "Link" link on the HA bridge web server, Alexa was finally able to successfully locate my devices.  

Thanks so much for such an awesome product and thanks so much for your support beyond your software!

**Comment by pbrisebois** [comment]
What finally worked for me was to use HA Bridge V5.2.0, making sure .bat file and Web Server Port are using port 80. Once I can update bridge with each Vera device, I had to do Alexa discover 3 times....would always only recognize on the 3rd discovery. So far, so good.

**Comment by DrJJC** [comment]
I found enabling the LINK button in the advanced area of the HA Bridge and clicking that when discovering with Alexa Android app, then running Discovery a 2nd time and clicking the Link button again works... Not sure why but another user said the same and it works for me too.
