### ISSUE TITLE
Debugging Color with exectuted commands

### ISSUE THREAD

**Issue by MisterC925** [bwssytems/ha-bridge#864]
With both 5.1.0 and 5.2.0RC1 I can see my color bulbs as color in the smartthings app (the hue app in android can't seem to find the bulbs so this is my only way of testing outside of alexa).

Since they are the new milight/limitless bulbs I use the great node scripts I found online (sorry can't remember where)  to control them instead of trying to do udp/tcp stuff since the protocol has gotten much more complicated with the V6 bridge and newer bulbs.

Since version 4, the on/off has worked just fine through script execution has worked just fine, but the color doesn't seem to want to work.

I have the following condigured: 
node /volume1/.@root/node/fullcolor.js 1 color $(color.r) $(color.g) $(color.b)

I've tried it with both parenthesis and braces for the color varlables.

When run in the terminal, "node /volume1/.@root/node/fullcolor.js 1 color 100 0 100" will result in purple so I think it's working properly.  Other terminal tests work as well.

However when called from smartthings, I see it in the habridge logs but nothing happens so I'm wondering if the variable syntax is wrong?

2018-01-04 17:46:40,197 [qtp23541116-21] DEBUG com.bwssystems.HABridge.hue.HueM
ulator - HueMulator PUT called on api/* with request <<</api/ea77fb8b0fc64b07ad
d6a82ee79cddbf/lights/696172047/state>>>, and body <<<{"hue":4602,"sat":196,"tr
ansitiontime":4,"on":true}>>>
2018-01-04 17:46:40,198 [qtp23541116-21] DEBUG spark.Request - matchedPart: :us
erid = ea77fb8b0fc64b07add6a82ee79cddbf
2018-01-04 17:46:40,198 [qtp23541116-21] DEBUG spark.Request - matchedPart: :id
 = 696172047
2018-01-04 17:46:40,198 [qtp23541116-21] DEBUG com.bwssystems.HABridge.hue.HueM
ulator - hue state change requested: ea77fb8b0fc64b07add6a82ee79cddbf from 172.
20.20.116 body: {"hue":4602,"sat":196,"transitiontime":4,"on":true}
2018-01-04 17:46:40,198 [qtp23541116-21] DEBUG com.bwssystems.HABridge.BridgeSe
curity - validateWhitelistUser: found a user <ea77fb8b0fc64b07add6a82ee79cddbf>
2018-01-04 17:46:40,199 [qtp23541116-21] DEBUG com.bwssystems.HABridge.hue.HueM
ulator - Decode Json for url items: [{"item":"node /volume1/.@root/node/fullcol
or.js 1 color $(color.r) $(color.g) $(color.b)","type":"cmdDevice"}]
2018-01-04 17:46:40,199 [qtp23541116-21] DEBUG com.bwssystems.HABridge.hue.HueM
ulator - Calling Home device handler for type : cmdDevice
2018-01-04 17:46:40,199 [qtp23541116-21] DEBUG com.bwssystems.HABridge.plugins.
exec.CommandHome - Exec Request called with url: node /volume1/.@root/node/full
color.js 1 color $(color.r) $(color.g) $(color.b) and exec Garden: not given
2018-01-04 17:46:40,199 [qtp23541116-21] DEBUG com.bwssystems.HABridge.hue.Devi
ceDataDecode - Request <<node /volume1/.@root/node/fullcolor.js 1 color $(color
.r) $(color.g) $(color.b)>>, not done: false
2018-01-04 17:46:40,200 [qtp23541116-21] DEBUG com.bwssystems.HABridge.plugins.
exec.CommandHome - Executing request: node /volume1/.@root/node/fullcolor.js 1
color $(color.r) $(color.g) $(color.b)
2018-01-04 17:46:40,201 [qtp23541116-21] DEBUG com.bwssystems.HABridge.plugins.
exec.CommandHome - Process running: true
2018-01-04 17:46:40,202 [qtp23541116-21] DEBUG com.bwssystems.HABridge.hue.HueM
ulator - Response is in error: null
2018-01-04 17:46:40,253 [qtp23541116-18] DEBUG com.bwssystems.HABridge.hue.HueM
ulator - HueMulator GET called on api/* with request <<</api/ea77fb8b0fc64b07ad
d6a82ee79cddbf/lights>>>, and body <<<>>>

Should I see the variable translations in the debug output?

Thanks!

**Comment by FloFoer** [comment]
Your command is using hue/sat to change colors: `{"hue":4602,"sat":196,"transitiontime":4,"on":true}`  
This is the only conversion that is currently not yet implemented. It should work with CT or XY values, but in the current version not with hue/sat.

**Comment by MisterC925** [comment]
Okay thanks.  I wonder why it's doing that.  I'm assuming Alexa is doing the same since it's using smartthings to talk to the bulbs (there are weird issues with alexa seeing 2 of everything if it sees the ha-bridge and smarthings together so I removed the Alexa hue bulbs from it's config)
