### ISSUE TITLE
Original Philips Hue App won't find habridge

### ISSUE THREAD

**Issue by pappaq** [bwssytems/ha-bridge#865]
Hey there,

I can't get my habridge to show up in my Hue App (Android). The Version of habridge is 5.1.0.

It's running on port: 81

I've got one physical Hue Bridge in the App and want to add the habridge to it. Is that possible?

**Comment by bwssytems** [comment]
This has been discussed before. The app requires the ha-bridge run on port 80.

**Comment by pappaq** [comment]
When I change the port to 80 the webfrontend won't start.

**Comment by bwssytems** [comment]
Yep, that is because your system either has a webserver running there already or that you need privileges to open that port.

**Comment by pappaq** [comment]
Ok, how can I find out, that a webserver already is running? And how do I get the privileges to open that port?

**Comment by bwssytems** [comment]
That question is specific to your system and you should google that info for your particular OS.

**Comment by pappaq** [comment]
Got it running now! Next problem is, that habridge won't start the scripts I told it to. Thanks for your answers though!

**Comment by bwssytems** [comment]
Search for "exec" in the closed issues. It's probably a quotation issue.

**Comment by bwssytems** [comment]
Also, Debug is your friend. Turn it on for the com.bwssystems.HABridge.plugins.exec

**Comment by pappaq** [comment]
I've got some scripts in my /home/pi/hyperion folder and they all work in my shell. But when I try to execute them, habridge gives back "Request Executed: success [{"success":{"/lights/1/state/on":true}}]". But nothing happends.

When I start the same script with the "sh /home/pi/hyperion/on.sh" command, that is placed under "Target Item" in the device I created, in the terminal, it works.
