### ISSUE TITLE
Scripts won't work in habridge but in raspbian terminal

### ISSUE THREAD

**Issue by pappaq** [bwssytems/ha-bridge#866]
I've got some scripts in my /home/pi/hyperion folder and they all work in my shell. But when I try to execute them, habridge gives back "Request Executed: success [{"success":{"/lights/1/state/on":true}}]". But nothing happends.

When I start the same script with the "sh /home/pi/hyperion/on.sh" command, that is placed under "Target Item" in the device I created, in the terminal, it works.

**Comment by bwssytems** [comment]
As mentioned before, this issue has been discussed in the issues (open and closed). You don't mention the setup of your target item.

**Comment by pappaq** [comment]
Ok, now with a little bit more information:

I try to control my hyperion which runs on a libreelec on a raspberry pi 3.

I've got several scripts on the raspberry, that runs habridge. For example these two, to turn the Ambilight ON and OFF:

on.sh
`#!/bin/bash`
`ssh root@192.168.1.206 "/storage/.config/autostart.sh > /dev/null 2>&1 &"`

off.sh
`#!/bin/bash`
`ssh root@192.168.1.206 "killall hyperiond 2>/dev/null"`

They both work when I execute them via terminal like this: sh /home/pi/hyperion/on.sh OR sh /home/pi/hyperion/off.sh

Here are screenshots of the device and the success popup I get.
![device_troubleshoot_1](https://user-images.githubusercontent.com/18289940/34629160-82c30e04-f267-11e7-99ea-78445659fc6a.PNG)
![device_troubleshoot_2](https://user-images.githubusercontent.com/18289940/34629161-82e0a5e0-f267-11e7-82e8-b6cb38d6a63a.PNG)

**Comment by bwssytems** [comment]
remove the sh from your command as it already as the bash command line inside.

**Comment by pappaq** [comment]
On another installation of habridge, which I had running before but on port 81 it worked like this. But I got the error "Could not execute request: /home/pi/hyperion/on.sh with message: Cannot run program "/home/pi/hyperion/on.sh": error=13, Permission denied", so I added "sh" and it worked. The same problem occurs now.

**Comment by pappaq** [comment]
I think root is the user that started ha-bridge, so I tried to run `sh /home/pi/hyperion/on.sh` after changing to root via `sudo su -`. But I get `sh: 0: Can't open /home/hyperion/on.sh` back. Should I change the ownership or move the files to another place?

**Comment by pappaq** [comment]
Got it running. First off, I got the path wrong `/home/hyperion/on.sh` instead of `/home/pi/hyperion/on.sh`. After fixing that it was a authentication issue. Solved that by creating a RSA key and copying that over to the raspi on which the ambilight is running.

Thanks for your help@bwssystems over the evening! Have a nice weekend!

**Comment by Xairoo** [comment]
For me it looks like the ssh command is just ignored. Can't log anything to a file. My script works fine, but it just ignores ssh. Worked well before an upgrade of ha-bridge, but I don't know the version because I haven't use that script for a while.
