### ISSUE TITLE
Strange issue with Fibaro Scenes

### ISSUE THREAD

**Issue by darrenmcuk** [bwssytems/ha-bridge#869]
I am getting the following error when I go to the Fibaro Scenes tab...

Get Fibaro Scenes Error: undefined with status: Server Error - 500

but the devices tab is all populated correctly? Anyone any ideas?

Thanks

**Comment by bwssytems** [comment]
Which version

**Comment by mariefischer** [comment]
I am seeing the same problem. ha-bridge 5.1.0, Fibaro HC2 4.150.

**Comment by bwssytems** [comment]
Rules for Testing: I need DEBUG turned on for your particular system com.bwssystems.HABridge.plugins. (fibaro, FHEM, etc) and com.bwssystems.HABridge.plugins.http so that you can post your command line log output.

**Comment by bwssytems** [comment]
So, use the release candidate 5.2.0RC5 in the other thread and turn on debug for fibaro.

**Comment by bwssytems** [comment]
The Fibaro has an issue in 5.1.0. Did you try the Release Candidate?

**Comment by bwssytems** [comment]
New Jar is out in thread #863

**Comment by bwssytems** [comment]
So V5.2.0 is out there and it has an update for fibaro.
