### ISSUE TITLE
5.2.0rc3 - Alexa not allowing control of colour - MiLight

### ISSUE THREAD

**Issue by vwillcox** [bwssytems/ha-bridge#870]
![screenshot_20180106-162519](https://user-images.githubusercontent.com/3775843/34641604-7e7f1b5c-f2fe-11e7-8e06-176a5c27b0a3.png)
![habridge](https://user-images.githubusercontent.com/3775843/34641614-9de61afe-f2fe-11e7-9ea5-083b11ebd031.PNG)
Alexa does not allow me to control the colour still :(

**Comment by bwssytems** [comment]
Nope, talk to Amazon, sorry
