### ISSUE TITLE
Custom Dim Commands 

### ISSUE THREAD

**Issue by xundre** [bwssytems/ha-bridge#872]
I am trying to set up a Vera non dimmer light  that has the following on/off/dim functions but having trouble with the dim portion .

1. ON - Turn on light 
2 DIM 
    100% - Run vera scene to turn on lights and deactivate light motion sensor 
      0% - Run vera scene to turn off motion sensor
3. OFF - Turn off light 

Essentially , the dim functions are controlling the motion sensors .Is this possible?

**Comment by bwssytems** [comment]
That is an enhancement request. Will put it in the queue.

**Comment by xundre** [comment]
I see, I was hopping it could be done with the multiple dim options or execute command/script like if 100% (run scene1 ) if 0% run scene 2. 

Thanks for all the work!

**Comment by bwssytems** [comment]
Currently there is no logic that says if dim value is this do that.

**Comment by FloFoer** [comment]
@xundre of course you always could write your own script and call it with the brightness level as argument within the dim url (as execute command/script item)

**Comment by xundre** [comment]
@FloFoer Do you have an example of this ?

**Comment by bwssytems** [comment]
This will be to unique and is best implemented by using a script.
