### ISSUE TITLE
Different interpretations of Harmony commands

### ISSUE THREAD

**Issue by CarnivoreD** [bwssytems/ha-bridge#873]
First thank you for the ha-bridge!

I have set up device with an OnItem and an OffItem like this:

Type: HTTP Device
Target Item: http:// 192.168.[Device-URL]...new_value=1
HTTP Verb: GET

**If I trigger the OFFItem from the Harmony App or with the long press (= off) on the left smart home button of my Harmony Companion everything works fine.

If I trigger the ONItem from the Harmony App it also works fine. The log shows:**

01-16-2018   17:14:10.680 | DEBUG | hue state change requested:   xyz from 192.168.[IPad-URL] body:   {"on":true} | com.bwssystems.HABridge.hue.HueMulator
-- | -- | -- | --
01-16-2018   17:14:10.680 | DEBUG | validateWhitelistUser: found a   user <xyz> | com.bwssystems.HABridge.BridgeSecurity
01-16-2018   17:14:10.680 | DEBUG | Decode Json for url items:   [{"item":"http:// 192.168.[Device-URL]...new_value=1","type":"httpDevice","httpVerb":"GET"}] | com.bwssystems.HABridge.hue.HueMulator
01-16-2018   17:14:10.680 | DEBUG | Calling Home device handler for   type : httpDevice | com.bwssystems.HABridge.hue.HueMulator
01-16-2018   17:14:10.680 | DEBUG | executing HUE api request to   Http GET:   http:// 192.168.[Device-URL]...new_value=1 | com.bwssystems.HABridge.plugins.http.HTTPHome
01-16-2018   17:14:10.680 | DEBUG | Request   <<http:// 192.168.[Device-URL]...new_value=1>>,   not done: false | com.bwssystems.HABridge.hue.DeviceDataDecode
01-16-2018   17:14:10.681 | DEBUG | doHttpRequest with url:   http:// 192.168.[Device-URL]...new_value=1   with http command: GET with body: null | com.bwssystems.HABridge.plugins.http.HTTPHandler
01-16-2018   17:14:10.681 | DEBUG | Making outbound call in   doHttpRequest: <<<GET   http:// 192.168.[Device-URL]...new_value=1   HTTP/1.1>>> | com.bwssystems.HABridge.plugins.http.HTTPHandler
01-16-2018   17:14:10.936 | DEBUG | GET execute (0) on URL   responded: 200 | com.bwssystems.HABridge.plugins.http.HTTPHandler
01-16-2018   17:14:10.939 | DEBUG | Successfull response - The http   response is <<<<?xml version="1.0"   encoding="ISO-8859-1" ?><result><changed   id="1775" new_value="1" /></result>>>> | com.bwssystems.HABridge.plugins.http.HTTPHandler
01-16-2018   17:14:10.939 | DEBUG | Response is in error: null | com.bwssystems.HABridge.hue.HueMulator

**If I trigger the ONItem with the short press (= on) on the left smart home button of my Harmony Companion it doesn't work at all. The log shows:**

01-16-2018   17:21:19.203 | DEBUG | HueMulator PUT called on api/*   with request   <<</api/abc/lights/1/state>>>,   and body   <<<{"xy":[0,0],"on":true,"bri":254}>>> | com.bwssystems.HABridge.hue.HueMulator
-- | -- | -- | --
01-16-2018   17:21:19.204 | DEBUG | matchedPart: :userid =   abc | spark.Request
01-16-2018   17:21:19.204 | DEBUG | matchedPart: :id = 1 | spark.Request
01-16-2018   17:21:19.204 | DEBUG | hue state change requested:   abc from [...Harmony-URL...] body:   {"xy":[0,0],"on":true,"bri":254} | com.bwssystems.HABridge.hue.HueMulator
01-16-2018   17:21:19.204 | DEBUG | validateWhitelistUser: found a   user <abc> | com.bwssystems.HABridge.BridgeSecurity
01-16-2018   17:21:19.205 | DEBUG | Decode Json for url items:   [{"item":"[]"}] | com.bwssystems.HABridge.hue.HueMulator
01-16-2018   17:21:19.205 | DEBUG | Calling Home device handler for   type : custom | com.bwssystems.HABridge.hue.HueMulator
01-16-2018   17:21:19.205 | WARN | HTTP Call to be presented as   http(s)://<ip_address>(:<port>)/payload, format of request   unknown: [] | com.bwssystems.HABridge.plugins.http.HTTPHome
01-16-2018   17:21:19.357 | DEBUG | Stats: [leased: 0; pending: 0;   available: 0; max: 200] | com.bwssystems.HABridge.plugins.http.HttpClientPool

Why does it not work with the Companion button when pressing short (= on)??? 

Thank you for your help...

**Comment by bwssytems** [comment]
It is trying to execute the dim command as the "bri" value is populated. This will change in V5.2.0 and will work properly.

**Comment by CarnivoreD** [comment]
Great, thank you!

Is it already foreseeable when V5.2.0 will be released?

**Comment by CarnivoreD** [comment]
The url I trigger with a **short** press on the Companion button (=**on**) is an url which toggles a non-dimable light and I want to trigger another url with a **long** press on the Companion button (=**off**) that is an url which toggles another non-dimable light:

Therefore on should toggls light 1 and off should toggle light 2.

If I understand you right this will be possible in V5.2.0?!?

**Comment by bwssytems** [comment]
@CarnivoreD You can test this now with the 5.2.0RC5 in the Release candidate thread.

**Comment by CarnivoreD** [comment]
I tested it with 5.2.0RC5

With a **short press (=on)** the light is turned on then off then on. Therefore the url is triggered 3 times. Log:

01-19-2018 14:26:17.021 | WARN | HTTP Call to be presented as http(s)://<ip_address>(:<port>)/payload, format of request unknown: [] | com.bwssystems.HABridge.plugins.http.HTTPHome
-- | -- | -- | --
01-19-2018 14:26:17.025 | INFO | Color url not available for state change,  lightId: 1, userId: ..., from IP:  192.168.[IP Harmony Hub], body: {"xy":[0,0],"on":true,"bri":254} | com.bwssystems.HABridge.hue.HueMulator
01-19-2018 14:26:17.654 | WARN | HTTP Call to be presented as http(s)://<ip_address>(:<port>)/payload, format of request unknown: [] | com.bwssystems.HABridge.plugins.http.HTTPHome
01-19-2018 14:26:17.658 | INFO | Color url not available for state change,  lightId: 1, userId: ..., from IP:  192.168.[IP Harmony Hub], body: {"xy":[0,0],"on":true,"bri":254} | com.bwssystems.HABridge.hue.HueMulator
01-19-2018 14:26:18.286 | WARN | HTTP Call to be presented as http(s)://<ip_address>(:<port>)/payload, format of request unknown: [] | com.bwssystems.HABridge.plugins.http.HTTPHome
01-19-2018 14:26:18.289 | INFO | Color url not available for state change,  lightId: 1, userId: ..., from IP:  192.168.[IP Harmony Hub], body: {"xy":[0,0],"on":true,"bri":254} | com.bwssystems.HABridge.hue.HueMulator

With a **long press (=off)** it still works fine.

**Comment by bwssytems** [comment]
Did you set the device type to be onFirstDim in the device edit screen?

**Comment by CarnivoreD** [comment]
My mistake - now it works. Thank you so much...!
