### ISSUE TITLE
Error on calling URL - Nanoleaf Aurora

### ISSUE THREAD

**Issue by Nicras** [bwssytems/ha-bridge#874]
Hi,

I receive the following error, when trying to ON, OFF, DIM my Nanoleaf Aurora from within HA-Bridge:

Request Error, Please look in your habridge log: error {"type":"6","address":"/lights/11","description":"Error on calling url to change device state","method_name":"/lights/11state"}

The device is configured as shown

![image](https://user-images.githubusercontent.com/35510003/35017969-b78eb78a-fb1f-11e7-9fdf-c37d8bf9ee35.png)

The light turns ON and OFF and DIM works too but the error still occurs

I want to use this to control my Aurora from my Harmony Remote. I can turn ON and OFF but DIM doesn't work from Harmony.

Debug Log attached, Thanks in advance!

Nicras

01-17-2018 00:37:44.692 | DEBUG | hue lights list requested: fc2e80189f134f2d9504b14d2d11712f from 10.22.3.46 | com.bwssystems.HABridge.hue.HueMulator
-- | -- | -- | --
01-17-2018 00:37:44.691 | DEBUG | HueMulator GET called on api/* with request <<</api/fc2e80189f134f2d9504b14d2d11712f/lights>>>, and body <<<>>> | com.bwssystems.HABridge.hue.HueMulator
01-17-2018 00:37:37.370 | WARN | Error on calling url to change device state: http://10.22.3.48:16021/api/v1/luqXb3v56WrmOrcEugLKraqZ6G7SE0ex/state | com.bwssystems.HABridge.plugins.http.HTTPHome
01-17-2018 00:37:37.265 | DEBUG | executing HUE api request to Http PUT: http://10.22.3.48:16021/api/v1/luqXb3v56WrmOrcEugLKraqZ6G7SE0ex/state | com.bwssystems.HABridge.plugins.http.HTTPHome
01-17-2018 00:37:37.265 | DEBUG | Calling Home device handler for type : httpDevice | com.bwssystems.HABridge.hue.HueMulator
01-17-2018 00:37:37.265 | DEBUG | Decode Json for url items: [{"item":"http://10.22.3.48:16021/api/v1/luqXb3v56WrmOrcEugLKraqZ6G7SE0ex/state","httpBody":"{\"on\" : {\"value\":true}}","httpVerb":"PUT","type":"httpDevice","contentType":"text/html"}] | com.bwssystems.HABridge.hue.HueMulator
01-17-2018 00:37:37.264 | DEBUG | hue state change requested: 3dfcd29e232c4a9ba2c8560173396b81 from 10.22.3.28 body: {"on":true} | com.bwssystems.HABridge.hue.HueMulator
01-17-2018 00:37:37.263 | DEBUG | HueMulator PUT called on api/* with request <<</api/3dfcd29e232c4a9ba2c8560173396b81/lights/11/state>>>, and body <<<{"on":true}>>> | com.bwssystems.HABridge.hue.HueMulator

**Comment by bwssytems** [comment]
First off, which version? And please attach the command line log file.

**Comment by Nicras** [comment]
Version is 5.1.0

How do i get the command line logfile?

**Comment by Nicras** [comment]
[habridge.log](https://github.com/bwssytems/ha-bridge/files/1640152/habridge.log)
 
This?

**Comment by Nicras** [comment]
I just started HA-Bridge and executed OFF, ON and DIM.

**Comment by bwssytems** [comment]
That was the log file I wanted. Very interesting, when you try this request in a REST client such as postman, do you get a null return value? It seems that is the response and the ha-bridge code does not expect a successful request with a null return value. Also, you could try the new RC candidate and turn on debug for the http plugin and post the logs.

**Comment by Nicras** [comment]
[habridge.log](https://github.com/bwssytems/ha-bridge/files/1643869/habridge.log)
 Here's the log from 5.2.0RC5 with debug logging for the HTTP plugin.

And this is what the request in Postman looks like:

![image](https://user-images.githubusercontent.com/35510003/35112726-321f5d8c-fc7f-11e7-93f1-2cad36fd45ff.png)

**Comment by Nicras** [comment]
And because I didn't mention it already, Thanks for your great solution. Because of HA-Bridge my dreams came true, managing all my stuff via my Harmony remote.
And your support is amazing ;-)

**Comment by bwssytems** [comment]
Unfortunately, the debug was not set. Did you hit Update Log Levels after selecting DEBUG for the http plugin? Also, the postman screen does not show the response window.

**Comment by Nicras** [comment]
[habridge (1).log](https://github.com/bwssytems/ha-bridge/files/1644097/habridge.1.log)
I thought I did the update log levels, but here you are
![image](https://user-images.githubusercontent.com/35510003/35116171-bb3fd8c0-fc8a-11e7-96eb-8a1eaeb53f56.png)
I marked the response part of the Window and in the upper right corner is the HTTP Status with "204 No Content"
Is it that what you mean?

**Comment by Nicras** [comment]
sounds pretty good, thanks in advantage

**Comment by tuicemen** [comment]
Was this fixed yet in the RC builds?
Running 5.2.0.rc22
I just tested a Http call and get the same issue thought the device does turn on/off
Maybe because I'm making a call to the same device the Bridge is on though different port?
