### ISSUE TITLE
SmartThings intergation the Google Cure?

### ISSUE THREAD

**Issue by tuicemen** [bwssytems/ha-bridge#876]
I've been playing with the Samsung SmartThings developers console and there are lots of samples for different devices.
http://developer.smartthings.com/
It would be cool if HA-Bridge could utilize this cloud based tool! Devices created in it show up in its app as well as its Alexa and Google skills.
This would allow HA-Bridge to again work with Google home.
Since I picked up a google mini prior to Christmas I managed to get control of my X10 devices with it using this cloud based tool and response time is very quick.
It allows things from GitHub to be pulled in so creating and publishing a device handler may be all that is needed.
Just a thought

**Comment by bwssytems** [comment]
Will check that out. As mentioned before, cloud authorization is the only way that Google Home is working.

**Comment by dony71** [comment]
hope this will be work-around to make HA-bridge working on Google Home device

**Comment by tuicemen** [comment]
I created a little windows app which allows Google home control of X10 devices.
It is a very simple bridge so HA-Bridge should be able to do something simular.
I attempted to do something with the bridge but the device ID # changing in HA-Bridge made it impossible to setup currently.

**Comment by tuicemen** [comment]
I've been looking at several Smart app code examples for SmartThings posted in the developers pages.
I know nothing about Groovy coding but loading one or more of these samples then opening the SmartThings app it appears you could discover devices in the Bridge and auto add them from the app.
no need to create each device in the SmartThings developer screen.
If this isn't possible then a Device Handler would need to be created and each device added manually to the developers console before SmartThings would see them.
 As stated before I've managed to create a Device Handler for my app using pieces of code samples.
I'm a bit stumped for making the calls to the bridge directly as I've not found a sample displaying how to send authorization and such one would want with the bridge exposed.

**Comment by tuicemen** [comment]
I've modified my device handler so it should work for on/off/dimming of bridge devices.
all that needs to be done now is to add the correct call to make to the bridge.
Since I'm not a Java or groovy coder I'm stumped here.
I'll post my device handler in hopes someone can finish it or provide some help in finishing it.
[HA-Bridge(device handler).txt](https://github.com/bwssytems/ha-bridge/files/1817584/HA-Bridge.device.handler.txt)

**Comment by bwssytems** [comment]
I believe the answer here is that using another Home Automation system that is Google Home capable and also can detect Philips Hue bridges (which would detect an ha-bridge) is the solution.

**Comment by bwssytems** [comment]
included in community information https://github.com/bwssytems/ha-bridge/wiki/Informational-Items-Collected-from-the-Community#q-smartthings-intergation-the-google-cure
