### ISSUE TITLE
Color in Hue/Sat

### ISSUE THREAD

**Issue by Nicras** [bwssytems/ha-bridge#877]
As the Nanoleaf Aurora API only accepts Hue and Saturation besides Brightness for color would it be nice to have the option to pass the values for color as HS.

Or am I missing, that it's already possible?

**Comment by bwssytems** [comment]
Not currently, but we could put that in as a replaceable parameter like the dim controls.

**Comment by Nicras** [comment]
That is what I wanted to read ;-)

**Comment by bwssytems** [comment]
When version 5.3.0 comes out, you can use ${color.hsl} to pass this.
