### ISSUE TITLE
use different profiles and/or amazon accounts

### ISSUE THREAD

**Issue by joergbeyer** [bwssytems/ha-bridge#878]
Hi,

Alexa and the habridge work fine for my amazon account. My wife has a seperate amazon account and seperate profile on the same alexa. That is useful, e.g. for her seperate spotify account.

I can access the devices behind the habridge - my wife can't, when she is using her account/profile.

Its even more complicated for my kids: they have their own alexa (and spotify identity). Amazon does not support asociated accounts for kids ("Teen and Child household profiles are not available with Alexa." -->https://www.amazon.com/gp/help/customer/display.html?nodeId=201628040 ).

It would be great to better understand how the habridge and an amazon account are tied together. Any ideas? I am even willing to setup several habridges, one for each account. But it's not that trivial: for example, I don't know how to forward the http calls to /api to the different instances of the habridge.

thanks in advance
Joerg

**Comment by bwssytems** [comment]
First off, It seems your one alexa where you and your wife have accounts that it would not respond to her for smart home calls. As far as the kids alexas, they have to discover devices as well and it will find the ha-bridge. In this scenario, you can separate actions between your alexa and the kids as they are on separate accounts by using the ip address filter capability.

**Comment by joergbeyer** [comment]
How do I connect the same habridge that works fine with my alexa and my amazon account to my kids alexa (with their amazon account)?

I tried this: I start a fresh browser, login to amazon as my son. Then I browse to the habridge, go to the  "My Echo" tab on the habridge.  It uses then my sons amazon account. If I search for devices on the "smart home" tab, it does not show any of the devices that is sees under my account and it does not find any devices.

I assume - right or wrong - that the amazon account and the habridge have a link, so the alexa knows what to, when it get a command ("alexa, swtich studio light on"). 

I also assume that the habridge can only handle a single amazon account, tight to one ore more alexas per house. Is that right?

**Comment by bwssytems** [comment]
'Alexa, discover devices'

**Comment by joergbeyer** [comment]
I tried this with my sons Alexa. I also does not find the devices that are configured in the ha bridge.

my alexa sees the devices and also (re-)finds them if I keep them in hte habridge config, but delete them (for testing purposes) in the alexa app.

**Comment by bwssytems** [comment]
Is your kids echos a gen 2? Those have issues finding the ha-bridge.

**Comment by joergbeyer** [comment]
yes. mine is a dot, his is a amazon echo, 2nd generation like this https://images-na.ssl-images-amazon.com/images/I/61Kkci2qM1L._SL1000_.jpg . Both are from december 2017

**Comment by bwssytems** [comment]
That is the issue. No resolution on why 2nd gen echos do not complete searching for the bridge.

**Comment by joergbeyer** [comment]
Is my issue then similar/same as this https://github.com/bwssytems/ha-bridge/issues/810 ?

**Comment by bwssytems** [comment]
That is correct for the 2nd gen echos.

**Comment by joergbeyer** [comment]
got it, thx

**Comment by joergbeyer** [comment]
I updated to http://bwssystems.com/files/ha-bridge-5.2.0RC6.jar , but the problem still exists.

**Comment by bwssytems** [comment]
Yes, the issue with the 2nd gen is on the amazon side.

**Comment by joergbeyer** [comment]
I logged myself out on my echo dot. Then I registered that echo to as my sons device. Discovery then worked immediately with the echo dot.

The devices all showed up in my sons app. all worked well. unfortunately the devices disappeared, when I unregistered the dot for him (to re-register the echo dot for me). So, it's also not a workaround to temporarily use a non-2nd gen device for discovery.

**Comment by joergbeyer** [comment]
is there any chance to emulate an echo device in software and let take the devices from a configuration? this device does not need to do all the speech recognition - only the discovery part...

**Comment by bwssytems** [comment]
Unfortunately, no.

**Comment by mcclaur** [comment]
I had a similar issues with discovery and was unaware the Echo was using my son's account when I was doing the discovery logged into my account.  You can ask her which account she is using and you can tell her to change accounts if the accounts are in a Household.  Maybe the posts in #862 will be of some help.

**Comment by NovaGL** [comment]
I have an Echo Dot V2 and it works fine. I changed the port it uses maybe that fixes it?

**Comment by bwssytems** [comment]
Closing as this is an out of date request now.
