### ISSUE TITLE
Intensity.math(x).hex does not deliver hex values

### ISSUE THREAD

**Issue by Mingarer** [bwssytems/ha-bridge#879]
Hi folks,

I need to calculate a string in hex format depending on the brightness.

My url looks like:

http://192.168.178.5/control?cmd=on,typ,tcp,192.168.178.50%3A5577,dta,31${intensity.byte.hex}${intensity.math(X+64).hex}

Brightness of 50% (=128 in abs numbers) delivers these log file entries:

_HueMulator PUT called on api/* with request ...  and body <<<{"on":true,"bri":**128**}>>>

executing HUE api request to Http GET: http://192.168.178.5/control?cmd=on,typ,tcp,192.168.178.50%3A5577,dta,31${intensity.byte.hex}${intensity.math(X+64).hex}

Request <<http://192.168.178.5/control?cmd=on,typ,tcp,192.168.178.50%3A5577,dta,3180192>>, not done: false_

As you can see the 50% (128) is converted in Hex value 80, i.e. intensity.byte.hex works

intensity.math(x+64).hex is supposed to return hex value C0 but delivers the integer 192. Conversion into hex not done.

Any idea how to fix? I guess the string is correct. I'm on V5.1.0

Thanks in advance!

**Comment by bwssytems** [comment]
Found it. Will be fixed in the next release.

**Comment by Mingarer** [comment]
You made my day:) 

Thanks!
