### ISSUE TITLE
Can't send MQTT - Error: Not Found - 404

### ISSUE THREAD

**Issue by veitk** [bwssytems/ha-bridge#880]
Hi,

i'm trying to send MQTT messages. It didn't work with my 4.5.6 Version so i updated to 5.1.0. 

Now if i hit Test-On or Test-Off a message pops up:

"Request Error, Pleae look in your habridge.log: undefined with status: Not Found - 404"  (and yes the "please" is spelled wrong ;-) )

log says:
The requested route [/(null)] has not been mapped in Spark for Accept: [null]

**Comment by bwssytems** [comment]
Will take a look

**Comment by veitk** [comment]
yes i thought so, because there are plenty of entries like that. 

would be really cool to send mqtt messages through alexa :)

**Comment by bwssytems** [comment]
So it may be a config issue with your mqtt device. Please post your habridge.conf

**Comment by veitk** [comment]
this is my habridge.conf:


{
	"upnpconfigaddress": "192.168.0.80",
	"useupnpiface": false,
	"userooms": false,
	"serverport": 80,
	"upnpresponseport": 50000,
	"upnpdevicedb": "data/device.db",
	"upnpgroupdb": "data/group.db",
	"buttonsleep": 100,
	"traceupnp": false,
	"farenheit": true,
	"configfile": "/home/pi/habridge/data/habridge.config",
	"numberoflogmessages": 512,
	"myechourl": "alexa.amazon.com/spa/index.html#cards",
	"webaddress": "0.0.0.0",
	"mqttaddress": {
		"devices": [{
			"name": "habridgemqtt",
			"ip": "192.168.0.80:1883"
		}]
	},
	"hubversion": "9999999999",
	"securityData": "Qd29J...... ",
	"settingsChanged": false,
	"veraconfigured": false,
	"fibaroconfigured": false,
	"harmonyconfigured": false,
	"hueconfigured": false,
	"nestconfigured": false,
	"halconfigured": false,
	"mqttconfigured": true,
	"hassconfigured": false,
	"domoticzconfigured": false,
	"somfyconfigured": false,
	"lifxconfigured": false,
	"homewizardconfigured": false,
	"upnpstrict": true
}

**Comment by bwssytems** [comment]
@veitk Also if you could post your device.db file as well.

**Comment by bwssytems** [comment]
Any update on this?
