### ISSUE TITLE
Ha-bridge issues heyu command but heyu does not issue command

### ISSUE THREAD

**Issue by tsgtxs1** [bwssytems/ha-bridge#881]
Ha-bridge (release 4.5.6) issues the heyu command (heyu on c1) and responds that the light is on. However heyu never issues the command. The install was done following instructions in Corey Writes guide. the x10 is hooked up through a CM11A and will accept the on command when I issue it to heyu directly. After trying different approaches by granting rwx and using sudo to execute, I am at an impass as where to go to next. The only part of this that I don't have a handle on is the ttyUSB0 permissions.
Any suggestions? I am running on an RPI3 with raspbian.

Thanks in advance

**Comment by audiofreak9** [comment]
@tsgtxs1 
Hey it's Corey, let's trouble shoot this on my blog in the comments, this is not an ha-bridge issue, but rather a permissions issue.

**Comment by tsgtxs1** [comment]
Leave a comment

**Comment by tsgtxs1** [comment]
Sorry, but being a new guy to this, please let me know how to get to your blog and comments. I clicked on your picture but did not see where to leave a message.

**Comment by audiofreak9** [comment]
Scroll to the bottom of [the blog post page](http://coreyswrite.com/electronics/home-automation/amazon-echo-x10-home-control-updated/), there is a comment box for the post.
