### ISSUE TITLE
Can't control WEMO Insight Switch

### ISSUE THREAD

**Issue by Nicras** [bwssytems/ha-bridge#882]
Hi, 

with the following call from postman I can control my Belkin WEMO Insight Switch:

![image](https://user-images.githubusercontent.com/35510003/35250437-e1d31a2a-ffd6-11e7-83b7-2dc77634e245.png)
![image](https://user-images.githubusercontent.com/35510003/35250451-f89682ec-ffd6-11e7-9419-86d171d42982.png)

I tried to implement this in HA-Bridge like this:

![image](https://user-images.githubusercontent.com/35510003/35250523-4b41cefc-ffd7-11e7-9ba3-7384984824e3.png)

But it's not working. 

Here's the log with http plugins set to DEBUG:

[habridge.log](https://github.com/bwssytems/ha-bridge/files/1653992/habridge.log)

I don't see the header name and value pairs in the log. Am I missing something?

Cheers Nicras

**Comment by Nicras** [comment]
BTW: Since using RC7, my Aurora works fine but I don't get any error messages at all ;-)

**Comment by bwssytems** [comment]
@Nicras The headers don't get dumped on debug. I should add that. But I do see you now have duplicate content type statements as you selected that from the drop down and then put it in the header as well. Take out the content type on your header and try it.

**Comment by Nicras** [comment]
I did but it doesn't work

**Comment by Nicras** [comment]
Tried to do it again with RC13 but still no luck.
![image](https://user-images.githubusercontent.com/35510003/35767313-6afc3856-08ea-11e8-9f44-26ba4b948a2b.png)
This is how I configured the device and in the screenshots above you can see how it works with postman.

[habridge.log](https://github.com/bwssytems/ha-bridge/files/1691777/habridge.log)

**Comment by bwssytems** [comment]
@Nicras The only thing I can see from Wemo examples on the web, is that you have slash after BasicEvent1. Remove that slash, sometimes it makes a difference, sometimes not.

**Comment by Nicras** [comment]
It does! Removing the slash in the URL did the trick. Thank you very much!
