### ISSUE TITLE
So is HA-bridge obsolete now?

### ISSUE THREAD

**Issue by ro8in** [bwssytems/ha-bridge#885]
Since Philips hue decided to do their new API cloud based and more and more things seem to switch to their new Web based login system, is ha-bridge becoming useless or are there any plans to have ha-bridge be recognized by Hue cloud as an actual bridge??

Yesterday I re added the Alexa Hue skill and suddenly i was presented with a login screen from Hue. That way Alexa could only connect to my actual Hue bridge and not HA-Bridge. I tried adding HA-bridge to my Hue account but it doesn't work it only detects my actual bridges. Luckily I also have a domoticz server and I could still use the controlicz skill to control everything (not my preferred way since i'm depended on the controlicz servers to be live now) 

Currently i still run HA-Bridge for my Logitech Harmony to connect to my domoticz, since they still use the old style Hue api with actually connecting to the bridge itself, but it probably won't be long until they do switch to the new Hue cloud based API and I probably won't be able to use my Harmony for controlling domoticz anymore. 

Do you developers see a way of having ha-bridge be detected by the Hue cloud or will this just be a dead project eventually? Really hope its fixable!

**Comment by NovaGL** [comment]
HA-Bridge is supported natively by Alexa, you do not need to use the Hue Skill.

**Comment by ro8in** [comment]
How? If I just do search devices without adding the skill I don't see any result..

**Comment by ro8in** [comment]
BTW Im using Sonos One players

**Comment by digiltd** [comment]
The Sonos One is your main Alexa device, as in you don't have a Dot or Echo?

Did it find your Hue bridge without the Hue Skill?

It looks like the Sonos uses the Alexa Voice Service which is what Amazon let third parties to use so they can use Alexa in their devices.

The Dot/Echo can control Hue bulbs natively by talking directly to the Bridge within your local network, you don't even need the Skill for basic on/off/dim commands. When you use the Skill you are using the cloud based API to talk to your bridge.

**Comment by bwssytems** [comment]
Most implementations outside of the Echo ecosystem use the Alexa Voice Service which only connects to cloud based systems. the Amazon Echo and Dot, but not the Show, look for Hue systems on the local network.

**Comment by bwssytems** [comment]
Also, the ha-bridge will never be part of the hue cloud as it is not associated with Philips as this is a third party project.

**Comment by NovaGL** [comment]
As mentioned above devices other than Echos use AVS which is not the full feature set. I use an Echo Dot v2 so I have all the options available to me.

**Comment by bwssytems** [comment]
Closing and referencing #890
