### ISSUE TITLE
Exception every minute after linking harmony hub

### ISSUE THREAD

**Issue by delgurth** [bwssytems/ha-bridge#886]
I recently started using ha-bridge to get my FRITZ!Dect 200 to work with my Harmony Hub remote. I've seen the pull request for the FRITZ!Box support, but haven't had time yet to really look at the current state and on how to get that working nicely, so I now just shell commands to switch it on/off. And that works just fine.

But, after I added my Harmony Hub to ha-bridge I'm getting a warning every minute:

```
Jan 30 10:08:56 raspberrypi java[12841]: Jan 30, 2018 10:08:56 AM org.jivesoftware.smack.XMPPConnection callConnectionClosedOnErrorListener
Jan 30 10:08:56 raspberrypi java[12841]: WARNING: Connection closed with error
Jan 30 10:08:56 raspberrypi java[12841]: java.io.EOFException: no more data available - expected end tag </stream:stream> to close start tag <stream:stream> from line 1, parser stopped on END_TAG seen ...</mechanisms></stream:features>... @1:307
Jan 30 10:08:56 raspberrypi java[12841]: #011at org.xmlpull.mxp1.MXParser.fillBuf(MXParser.java:3035)
Jan 30 10:08:56 raspberrypi java[12841]: #011at org.xmlpull.mxp1.MXParser.more(MXParser.java:3046)
Jan 30 10:08:56 raspberrypi java[12841]: #011at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1144)
Jan 30 10:08:56 raspberrypi java[12841]: #011at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
Jan 30 10:08:56 raspberrypi java[12841]: #011at org.jivesoftware.smack.tcp.PacketReader.parsePackets(PacketReader.java:279)
Jan 30 10:08:56 raspberrypi java[12841]: #011at org.jivesoftware.smack.tcp.PacketReader.access$000(PacketReader.java:47)
Jan 30 10:08:56 raspberrypi java[12841]: #011at org.jivesoftware.smack.tcp.PacketReader$1.run(PacketReader.java:81)
```

I've seen that the tuck182/harmony-java-client has been updated to smack 4.2.0 from people using it in [openhab2 after they got some problems](https://github.com/openhab/openhab2-addons/issues/1222). It seems that your merge missed at least a part of [that pull](https://github.com/tuck182/harmony-java-client/pull/16) since you are using smack-core 4.0.7.

Is there a reason you are maintaining your own version of harmony-java-client?

**Comment by bwssytems** [comment]
Hmm, will take a look at updating that.

**Comment by bwssytems** [comment]
Upgraded to the latest library. Take a look at the 5.2.0 RC11 in #863

**Comment by delgurth** [comment]
RC11 works perfectly for me. Thanks for the quick fix.

**Comment by bwssytems** [comment]
keeping open until 5.2.0 is released
