### ISSUE TITLE
Not an issue but FYI for Wiki potentially

### ISSUE THREAD

**Issue by crsnwby** [bwssytems/ha-bridge#887]
I gave you the info about getting this working on Android using Lunix on a mobile phone. I recently put it on a Synology NAS and got it working also, this info might be of help for some people as it wasn't clear for me as being new to NAS.

1. Install Java on NAS from package centre app
2. Put jar file onto NAS in a folder of your choice
3. Run JAR file from terminal using command line: nohup java -jar ha-bridge.jar &
Make sure your in the folder with the ha-bridge.jar file when running the command as you may think you are but type dir to check as you may be in a folder with the same name that is virtual.

**Comment by bwssytems** [comment]
Thanks, much appreciated!

**Comment by hphde** [comment]
My Syno start/stop script
```
#!/bin/sh
PATH=$PATH:/var/packages/Java8/target/j2sdk-image/bin:/var/packages/Java8/target/j2sdk-image/jre/bin
BASEPATH=$(dirname $0)
mkdir -p $BASEPATH/data
JARFILE="ha-bridge.jar"
LOGFILE="$BASEPATH/${JARFILE}.log"
#CFGFILE="$BASEPATH/data/habridge.config"
JAVA="ava8"
PIDFILE="/var/run/ha-bridge.pid"
cd $BASEPATH

start(){
	if [ "$JAVA" != "$(which java|grep -oP $JAVA)" ]; then
		echo "Java8 not found - please install first"
		exit 1
	fi
	if [ -f $JARFILE ]; then
		java -jar $JARFILE &> $LOGFILE &
		echo $! > $PIDFILE
	else
		echo "HA Bridge JAR file not found. Download from https://github.com/bwssytems/ha-bridge/releases"
		echo "Rename or link it to '$JARFILE'"
		exit 1
	fi
}
stop(){
	kill $(cat $PIDFILE)
}

case $1 in
	start)
		start
		;;
	stop)
		stop
		;;
	*)
		echo "usage: $0 {start|stop}"
		;;
esac
```

**Comment by bwssytems** [comment]
Added to the wiki https://github.com/bwssytems/ha-bridge/wiki/Run-on-Synology-NAS
