### ISSUE TITLE
Added TCP/IP support

### ISSUE THREAD

**Issue by mscappini** [bwssytems/ha-bridge#89]
Can we just have the ability to send raw TCP bytes to an IP/port?

**Comment by hollanas** [comment]
Would love to see this added as well.  This would be extremely useful so I can control my Hunter Douglas Shades with my Amazon Echo.

**Comment by mvau** [comment]
If shell script support is added (as per issue https://github.com/bwssytems/ha-bridge/issues/85) could you use sendip to achieve this from the command line?  To send UDP packet sequences I use the following via php exec and have ha-bridge call the script on a loopback webserver:

`/usr/bin/sendip -p ipv4 -is 10.106.16.152 -p udp -ud 8899 -d "0x4EC555" -v 10.106.16.152`

sendip has a tcp module and if this can be called directly from ha-bridge (as of v1.5.0) you should have a fairly clean solution.

**Comment by greg12579** [comment]
@bwssytems How would I execute a shell script? Which field does the command go in?

**Comment by matena** [comment]
@bwssytems same question as greg12579 - pls could you link corresponding documentation?
I highly appreciate your work so far

**Comment by bwssytems** [comment]
In versions after V4, you addthis in the manual add area by selecting the type of `Execute Command/Script/Program` on a n item and in the `Target Item` field you put your command in that
