### ISSUE TITLE
Color replacement control in MQTT

### ISSUE THREAD

**Issue by semicuda** [bwssytems/ha-bridge#891]
Hi!

I'm trying to use ${color.r}/${color.g}/${color.b} in a MQTT message for setting the color of an ESP8266 based device. But it seems that those tokens are only replaced for UDP devices? If so, can this be extended to MQTT as well?

Thanks, and great work :)

**Comment by bwssytems** [comment]
You are correct! That did not get into the tcp plugin. Next release.

**Comment by semicuda** [comment]
Just curious... Doesn't that need to go into MQTTHome?

**Comment by bwssytems** [comment]
Yes, you are correct, it needs to go there as well.
