### ISSUE TITLE
HABridge issues

### ISSUE THREAD

**Issue by jouster1974** [bwssytems/ha-bridge#892]
Tried to trigger some of my activities set up on HAB this morning and was told they were not responding....tried to SSH into my PI and couldn't so tried to look at the webpage assigned to it and get  this

<img width="893" alt="screen shot 2018-02-06 at 09 22 40" src="https://user-images.githubusercontent.com/15368005/35851278-73bb7db2-0b1f-11e8-8b6c-eb9f88492cc4.png">

No passwords are working so I cant SSH in....nothing has changed...is there anything I can try before I wipe the card and rebuild again from scratch (really wish Id backed up the image, which I will be doing this time

**Comment by bwssytems** [comment]
Well, looks like you have a system issue with your pi. Most likely from an auto update. This is not the place to get that resolved.

**Comment by jouster1974** [comment]
I have checked my PI and all is well with normal use...it boots into the desktop when connected with an HDMI and I am able to connect to it via WinSCP, however, the HABridge service is no longer running and if I try to execute it I get the following error

Command '"./habridge.service"'
failed with return code 126 and error message
-bash: line 7: ./habridge.service: Permission denied.

So Pi is working without issue but there still seems to be a problem with HAB in particular....does my error code shed any light?

TIA

**Comment by jouster1974** [comment]
to see if there was an issue with my existing card for some reason, I have created a new card build and installed a fresh version of HABridge but I am instantly getting the same issue and going back to the page above

**Comment by jouster1974** [comment]
I have also tried a completely different pi and get identical results

**Comment by jouster1974** [comment]
Appeared to be a browser issue.  I have always accessed via Firefox before but may have updated to Firefox Quantum since first installing HABridge....no longer works this way but then works fine from all other browsers....thanks for insight anyway
