### ISSUE TITLE
Repeating message in log

### ISSUE THREAD

**Issue by lemrock** [bwssytems/ha-bridge#894]
All of a sudden my HABridge is slowing down and I'm getting this message over and over "The requested route [/(null)] has not been mapped in Spark for Accept: [null]".  Hundreds of these messages are listed in the log.  Any idea what's going on here? I'm using ver 5.1.0.  Here is a sample so you can see how often this message logs:

02-12-2018 03:19:06.502 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter
-- | -- | -- | --
02-12-2018 03:19:06.508 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter
02-12-2018 03:19:26.928 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter
02-12-2018 03:19:26.928 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter
02-12-2018 03:19:47.000 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter
02-12-2018 03:19:47.000 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter
02-12-2018 03:20:08.004 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter
02-12-2018 03:20:08.010 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter

**Comment by audiofreak9** [comment]
@lemrock This is a known issue
https://github.com/bwssytems/ha-bridge/issues/817
