### ISSUE TITLE
Incorrect examples in documentation for color.

### ISSUE THREAD

**Issue by danielb7390** [bwssytems/ha-bridge#896]
In the docs we can read this:

> Color has been added as a replacement control and the available values are $(color.r), $(color.g), $(color.b) which are representations of each color as 0 - 255. There are hex equivalents as well as $(color.rx), $(color.gx), $(color.bx) and $(color.rgbx) as 2 place hex representations except for rgbx which is a six place hex representation.

I was copying this example and getting errors, and actually took me a while to notice that the examples are incorrect. Where it's () it should be {}.
There's another typo in the paragraph prior to this one.

**Comment by bwssytems** [comment]
Thanks!
