### ISSUE TITLE
Exclusion from "Lights" - Rooms for Alexa / Special Group

### ISSUE THREAD

**Issue by andocromn** [bwssytems/ha-bridge#897]
I have an old X10 system and interface HA-Bridge with Heyu on a raspberry pi.  Right now I only have the "Lights" in HA-Bridge but I would like to be able to turn on other things with Alexa such as a Lava Lamp and a Black light.  However since these are not "Lights" in the strictest sense of the word, I do not want these to come on when I ask Alexa to "turn the lights on"

I've looked for more information on what the "Rooms for Alexa" feature does.  The readme says devices above 10000 are treated as a special group, I'm hoping there is a way I can use this.  Is there any way to use these special groups to exclude certain devices from the "Lights" group?  Can I create a "Room" where my "Lights" and my Echos live in but still control the devices in the "Non-Lights Room" ?

My thought was if there is a way to create a group for all lights.  X10 has native 'All Lights on' and 'All Units off' commands that would actually work better.  has anyone tried this anything like this?  I'm hesitant about how Alexa will react to a light named "All" 

any advice appreciated
thanks in advance

**Comment by bwssytems** [comment]
Yes, Alexa thinks they are all lights do to the interface the bridge is using. It does not matter what is behind the name. You can name your device 'Fred' and then say 'Alexa, Turn on Fred' and then it will do so. You do not have to have the word light in the field.

**Comment by bwssytems** [comment]
Ahh, and now that I re-read the real question.  You can create a device that is called 'lights' and put what ever many commands you want. So when you say 'Alexa, turn on lights' it will only call that device named lights. I use this currently to control a scene.
