### ISSUE TITLE
Why must Disable UPnP Mode on router for Echo Discovery Device ?

### ISSUE THREAD

**Issue by guntp** [bwssytems/ha-bridge#898]
My Echo cannot discovery device when UPnP on router is Enable. I wanna to know that why ?

Thank so much.

**Comment by michaelhinchey** [comment]
I'm not sure if this will answer your questions but since some breaches were made to routers enabled with upnp the settings add some rules when enabled. Check to see if any rules are blocking discovery.

**Comment by bwssytems** [comment]
@guntp Cannot say why that would matter as most routers have enablement for UPnP control of the router itself, not traffic. Have you googled your router and upnp settings?

**Comment by guntp** [comment]
@bwssytems now i fix by disable upnp mode in router, echo can discovery device.
thx.
