### ISSUE TITLE
DMX Lighting Control From Alexa is possible [question] [help wanted]

### ISSUE THREAD

**Issue by Harry-Fabb** [bwssytems/ha-bridge#899]
HI, I am new in the word of coding but im having a go at it.

My interests lie with DMX lighting.

I have an idea that I would appreciate some help with.

Chromateq is a DMX device that will accept UDP communication with predefined JSON commands.

This means i can create a scene or programme and run it from Alexa however the lights have to be DMX (Milight has a DMX emitter so this brings MiLight into easy setup, DMX RGBW drivers are cheap and readily available for LED Tape, there is also a whole host of other DMX controlled devices that can make a smart home a huge amount better)

My question is can anybody help me work out how to configure this system, I have data from the developer of the commands and data e.g below will trigger a scene but I have no idea how to make this work with HA Bridge, i'm surprised i've even been able to run the Jar file
 
{
"typ" : 8,
"content" :
{"id" : 1, "a" : 0, "s" : true}
}

If anybody can help i would greatly appreciate it and more than happily help with programming the DMX side if you wish to use this system, i have developers permission to play with the software Chromateq TM.

thanks in advanced, 

Harry.

**Comment by bwssytems** [comment]
The ha-bridge supports udp command. Take a look at the readme and you can package your json command to be sent.

**Comment by Harry-Fabb** [comment]
I wish i understood what all that meant, could you narrow it down the the section that will help me the most?

**Comment by bwssytems** [comment]
Here is the link to the Add/Edit tab to create a custom device. There are examples on how to format a UDP request.

https://github.com/bwssytems/ha-bridge#the-addedit-tab

**Comment by bwssytems** [comment]
Any update on this

**Comment by Harry-Fabb** [comment]
i got it working and can now control DMX from Alexa thanks for your help!
