### ISSUE TITLE
Test ON/OFF buttons not working

### ISSUE THREAD

**Issue by nkgilley** [bwssytems/ha-bridge#9]
My Test On and Test Off buttons aren't working properly when I do a POST with a content-body.  The POST does work properly when I fire the command via Alexa.

![image](https://cloud.githubusercontent.com/assets/1507498/11182775/67d75bd4-8c3b-11e5-84a7-8045451a0a10.png)

**Comment by bwssytems** [comment]
Let me take a look. Your setup looks pretty straightforward and should be fine.

**Comment by bwssytems** [comment]
Also, the browser is sending this request as a test and not the bridge itself. Some systems use CORS to protect it's application from malicious attacks from a browser. You may be getting that return error itself. I may change the utility to test only through the bridge and not as a helper function.

**Comment by nkgilley** [comment]
In the Chrome developer console I see this in the network tab:

Remote Address:192.168.1.100:8123
Request URL:http://192.168.1.100:8123/api/services/homeassistant/turn_off?api_password=xxxx
Request Method:OPTIONS
Status Code:501 Unsupported method ('OPTIONS')

**Comment by bwssytems** [comment]
Ahh, congratulations, you have hit the CORS security error on your HomeAssistant. I am removing the calls from the javascript for testing and it will be a call to the bridge to execute the test. You just won't be able to test as you build the URL, you'll have to add it to the bridge first then test.

**Comment by nkgilley** [comment]
Thanks!

**Comment by bwssytems** [comment]
Updated code to handle Test On and Off only through the HUE API calls. Removed test buttons on URL creation screens so that it tests through the bridge system.
