### ISSUE TITLE
(Echo Gen1) All devices detected as "Dimmable Light"

### ISSUE THREAD

**Issue by Lyve1981** [bwssytems/ha-bridge#901]
It seems that there is currently not way to modify the device type that the Echo detects. Although you can chose a device type to configure what type of call is made (like, http, HAL etc), the result in Alexa is always a "Dimmable Light".

I would like to be able to configure the device type independently, so that a http call that I configure could be something else. The reason for this is, that I could control rollershutters, wallplugs, TVs, garage doos etc by initiating http calls, but of course these devices should not be controlled if I say something like "Alexa, turn off all lights".

**Comment by andocromn** [comment]
@Lyve1981 take a look at the issue i recently opened #897 I'm basically looking to do the same thing.  What I found is that the "Dimmable Light" was not changeable.  My next thought was to use rooms, but i have figured how or if this would work... the idea being that you'd have a "Lights" room and a "not lights" room, all of the Alexas would be in the Lights room therefore in theory when you say "turn on the lights" she would only turn on the lights in the lights room but hopefully still be able to control the lights in the "not lights" room if called specifically by name

Please update the issue if you do get this working, i'd be very interested in doing this on my system i just have not had the time

**Comment by bwssytems** [comment]
There have been comments that the echo only knows about dimmable lights and color lights for the echo. The ha-bridge returns either of these appropriately.

**Comment by bwssytems** [comment]
Any update on this?
