### ISSUE TITLE
ha-bridge and 2nd gen echo

### ISSUE THREAD

**Issue by Pontihog67** [bwssytems/ha-bridge#904]
Hi,
I am being trying to use Alexa10 to control my X10 items.  I am having trouble getting a gen 2 Echo to recognize the bridge.  The bridge works fine in controlling the X10's but the Echo doesn't see the bridge.

Has anyone successfully been able to add devices via the bridge with a 2nd gen Echo?  Any suggestions?
I have ordered a 2nd gen dot to see if it will see the bridge also.
Thank you

**Comment by bwssytems** [comment]
dup of #810
