### ISSUE TITLE
Help needed with recognizing Ha-bridge with Echo 2nd gen. Please

### ISSUE THREAD

**Issue by Pontihog67** [bwssytems/ha-bridge#905]
Hi,

Please don't close this subject as I have been trying to get some help with connecting ha-bridge to my 2nd gen Echo.  I tried to ask for help 2 days ago and the thread was closed and I was directed to another closed thread, where I could not ask questions.

I have been trying for 4 days to get the Echo to find the bridge.  I am on port 80.  I have purchased an Echo 2 dot that was just delivered today in hopes that could find the bridge, but no luck.

Can anyone assist with getting this to work for me?  I am trying to use Alex10 on Windows with the bridge and the creator of Alex10 has tried to help me and referred me here. 

I am just using X10 modules and a Bond ceiling fan interface.  Alexa finds the Bond ceiling fans but not the bridge.r

I saw the messages in the closed thread about adding a scene, but I am unfamiliar on how to do that.

Any help will be greatly appreciated.

Thanks
Ponti

**Comment by bwssytems** [comment]
Please post your question here #810  That is why I closed your new issue. We don't need duplicate topics.
