### ISSUE TITLE
Can HA-bridge reflect status of harmony activity when using remote

### ISSUE THREAD

**Issue by glsf91** [bwssytems/ha-bridge#906]
I have a Logitech harmony hub with matching remote.
I have made a device in HA-bridge of a harmony activity. With this I can turn the activity on and off. The device state is also reflecting the right state (on or off).

But should it be also possible ((and how) to reflect the right state when starting and stopping the activity from the harmony remote (or app)?
Now the state in HA-bridge stays off when starting the activity from the remote or app.

**Comment by bwssytems** [comment]
Yes it could. There is even tricky way to do it in the current version using webhook. This fires an event based on the activity monitor.

**Comment by glsf91** [comment]
Is then de hub it self calling the url which is in the webhook field?
If yes, which url do I have to use to change the status of the corresponding activity in HA-bridge?

**Comment by bwssytems** [comment]
No, it is the ha-bridge calls the url with the webhook string. Actually it would have to be another server to decode what you send it an then send another command back to update the state. It would be pretty ugly and I wouldn't recommend it.

**Comment by bwssytems** [comment]
ha-bridge was not built to watch it's end points for status changes. It is still not an easy task to find the devices associated with the activity as they are disconnected.
