### ISSUE TITLE
Exception during Backup of fresh started HA-Bridge database

### ISSUE THREAD

**Issue by escalate** [bwssytems/ha-bridge#907]
I would like to create an empty backup from a fresh started HA-Bridge service.
But i receive the following Stack Trace inside the HA-Bridge logs.
```                                
2018-03-04 13:23:06,987 [qtp14634715-14] ERROR com.bwssystems.HABridge.util.BackupHandler - Could not backup to file: test.bk message: data/device.db
 java.nio.file.NoSuchFileException: data/device.db
 #011at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
...
```
After the start of the HA-Bridge service there is no device.db file created.
HA-Bridge itself complains the missing file, too.
```
2018-03-04 13:18:14,656 [main] WARN  com.bwssystems.HABridge.dao.DeviceRepository - Error reading the file: data/device.db - Does not exist or is not readable. continuing...
```

My workaround for the moment is to click the Button "Renumber Devices" after a fresh start of HA-Bridge.
This forces the write of an device.db file with no elements, which is now able to backup.

But it feels like a bug.

A good solution would be to create an device.db file with no elements at startup of HA-Bridge. 
This would fix the warning of HA-Bridge itself and my wish to backup an empty database.

**Comment by audiofreak9** [comment]
Not a bug, without a first device save there is no file written.  It’s saved as JSON and without a device there is nothing to write well formed JSON.

**Comment by escalate** [comment]
Thats not true. With the mentioned workaround you get an empty list.
```
[]
```
An empty list is valid JSON syntax. So a first device is not necessary for initializing the device.db file.
It is not a bug but it is also not a good implementation.

**Comment by bwssytems** [comment]
I have decided based on review that the backup code is generic and deals file handling only. Too much work for something that would rarely be used.
