### ISSUE TITLE
Alternate action verbs for different device types.

### ISSUE THREAD

**Issue by seanford** [bwssytems/ha-bridge#91]
Use additional verbs to control specific devices....

Example:

Right now, to control my office blinds, I have to say Turn off Office Blinds to close them, and Turn On Office Blinds to Open them.  Would be more intuitive to be able to associate "Close" or "Lower" with Off, and "Open" or "Raise" with On.

Same goes for Locks.  Unlock = Off, Lock = On

etc.

**Comment by bwssytems** [comment]
Unfortunately, this is all in the Amazon Echo and cannot be changed by a user or the bridge.

**Comment by seanford** [comment]
I see.  are you guys currently using the Smart Home Skill API?

If so, there's probably an opportunity to have them add this to it down the line.  Reading their pages, they already plan on this, although it looks to be possible to add additional supported utterances now.  I'll have to see if I can get more info on this.

**Comment by dale3h** [comment]
seanford, this is actually already available on Alexa. Please check here for more details: https://www.reddit.com/r/amazonecho/comments/4gaf05/discovery_a_lot_more_smart_home_action_phrases/

**Comment by seanford** [comment]
@dale3h, thanks for the tip.  I see that my natural language requests can be tweaked a bit to make this work....e.g. I was saying lower, when close would work.  (Using a Somfy ZRTSI through a VeraPlus).

Now, just a few more days for my Haiku fan to have native support.  :)

**Comment by bwssytems** [comment]
The HA Bridge is emulating a Phillips Hue, so any utterances that the Smart Home Skill applies to the Hue will work. Unfortunately, the Smart Home Skill has now reserved more words for itself and some may not work.

**Comment by bwssytems** [comment]
@dale3h - I'm going to put your list of commands into the documentation for the ha bridge as that will help others. Great Work!

**Comment by bwssytems** [comment]
I believe this is now answered.
