### ISSUE TITLE
IP Filter not working

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [bwssytems/ha-bridge#911]
I have two Echo Dots at my home.
Echo1 with the IP 192.168.1.22 and Echo2 with the IP 192.168.1.23

I've setup device with two on actions and an ip filter for each action, but no matter which Echo Dot turns the device off, it always runs Action1.

The log says 
`WARN  com.bwssystems.HABridge.hue.HueMulator - filter for requester address not present in: (device)null OR then (item)192.168.1.23 with request ip of: 192.168.1.22`

**Comment by bwssytems** [comment]
This is a dup of #386 

The echo is a hive mind and sends from any given device on your account.
