### ISSUE TITLE
Without any changes: Alexa suddenly doesn't control HABridge anymore

### ISSUE THREAD

**Issue by heikoh81** [bwssytems/ha-bridge#912]
Hi,

I have 124 devices setup in HA Bridge.
Everything worked fine.

I changed NOTHING with my local setup.
Suddenly, Alexa does not execute any voice commands any more.
All devices are discovered correctly and are shown either in the Alexa app and the Alexa website, though.
Manual control in the Alexa is not possible anymore.
Manual control "Test on/off" in HA Bridge is working.

Every command Alexa reponds with: "I don't know what has gone wrong" (Ich weiß nicht, was schiefgelaufen ist).

Anyone else with this problem?
Seems like Amazon has changed s.th. within AVS (Germany)?

Heiko

**Comment by LCristoPT** [comment]
I have Echo Plus Gen 2 and everything find with HA Bridge 5.2.0RC20 till yesterday.

It happens the same with me as heikoh81.

The alexa turn on / turn off the HA device correctly but can't get the status and because of that gave the "I don't know what has gone wrong" message.

**Comment by LCristoPT** [comment]
Updated to RC25 and still the same message.

**Comment by tuicemen** [comment]
The "I don't know what has gone wrong" message seems to be an Amazon thing.
It appears to be related to other strange blurts from Alexa Like the Creepy laugh blurts.
Although I've not experienced it (yet) other Alexa users here in Canada have reported it.

**Comment by masterchop** [comment]
This solution no longer works for me. i have tried multiple versions with the same problem. i guess i have to  use the sdk again :(

**Comment by heikoh81** [comment]
I was most likely a AWS problem I think. After 1-2 days, it started working again.

I just want to add that I installaled a completely fresh Raspian Stretch Lite on a Pi Zero as the single application on this Raspberry and now Alexa with HA Bridge is much more reliable.

**Comment by masterchop** [comment]
mine just doesnt find it if i look for devices i just go and find my lifx bulbs :(

**Comment by bwssytems** [comment]
@masterchop Run on trace upnp in the bridge control and post your log and tell us the ip address of your echo.

**Comment by bwssytems** [comment]
Any update here

**Comment by heikoh81** [comment]
I think that it was a Timing Setting.
Since I set UPNP Response Time to 650ms, discovery is working reliably even from my Echo Show.
