### ISSUE TITLE
Vera closing down port 3480

### ISSUE THREAD

**Issue by dreamcryer** [bwssytems/ha-bridge#913]
I just saw an announcement on Vera forum notifying developers about closing a bunch of ports for security enhancement. [http://forum.micasaverde.com/index.php/topic,56959.0.html](http://forum.micasaverde.com/index.php/topic,56959.0.html)

I just tried calling http://{veraip}/port_3480/{command}. It returns a job id. And HA-Bridge thinks the request failed as the response was not expected. Any plan to fix this preemptively or cross our fingers hoping Vera will allow an option to turn on the port?

**Comment by michaelhinchey** [comment]
Hmm this is interesting. I'll keep up on this one.

**Comment by bwssytems** [comment]
Don't upgrade to 7.27. I still use UI5 because it just works.

**Comment by bwssytems** [comment]
So this will not disallow the usage of the commands, it will be just the format of the command and it will go to the standard http port (80). The commands will need to change in your ha-bridge config when you upgrade to the new version. Also more info in #924

**Comment by bwssytems** [comment]
included in community information https://github.com/bwssytems/ha-bridge/wiki/Informational-Items-Collected-from-the-Community#q-vera-closing-down-port-3480
