### ISSUE TITLE
Problems selecting FHEM Devices

### ISSUE THREAD

**Issue by hvorragend** [bwssytems/ha-bridge#915]
It looks like that it is not possible to just import one or some FHEM devices.
The checkbox is always marking all devices in the FHEM Device List.

`<input type="checkbox" name="bulk.devices[]" value="" ng-checked="bulk.devices.indexOf(fhemdevice.item.name) > -1" ng-click="toggleSelection(fhemdevice.item.name)" checked="checked">`

**Comment by bwssytems** [comment]
Will take a look

**Comment by bwssytems** [comment]
So, for either of these issues, you can still build individually with the button to the right. This will be in a bug fix release that will come shortly

**Comment by bwssytems** [comment]
Fixed in 5.2.1

**Comment by hvorragend** [comment]
Oh sorry, I didn't see the button at the right, because the columns are full of text.

By the way: The bulk add-button still imports all devices. It doesn't matter how many are checked.
