### ISSUE TITLE
All added FHEM devices are having the same name

### ISSUE THREAD

**Issue by hvorragend** [bwssytems/ha-bridge#916]
I already mentioned in #915 that I can just import (bulk add) all FHEM devices.
After that the new imported bridge devices are having the same name.
It is the name of the last row in the "FHEM devices"-tab.

**Comment by bwssytems** [comment]
will take a look

**Comment by bwssytems** [comment]
So, for either of these issues, you can still build individually with the button to the right. This will be in a bug fix release that will come shortly

**Comment by bwssytems** [comment]
Fixed in 5.2.1
