### ISSUE TITLE
lock device ID #s

### ISSUE THREAD

**Issue by tuicemen** [bwssytems/ha-bridge#917]
Is it possible to lock the device ID numbers for devices so that they don't change?
Renumbering the device list changes the device ID.
I believe removing a device and adding may also do this though it has been a while since I examined that part.
If the option to lock IDs was available it would be possible to get Google control back as well as add Cortana control using something like SmartThings very easy.
Of course that would mean opening HA-Bridge for web access on your machine running HA-Bridge.

**Comment by bwssytems** [comment]
So one thing would be is, don't use renumber, that feature was for legacy numbering.

**Comment by tuicemen** [comment]
So if that feature was for legacy numbering, is it still needed?

The simplest solution is not to touch that renumber button for sure.
Adding a warning to a readme about that helps, but how many actually read those?
It also doesn't prevent an accidental renumber.

**Comment by bwssytems** [comment]
You can go into the device.db file and change these manually. Maybe a note on the google home faq.

**Comment by tuicemen** [comment]
Manually changing these manually would be time consuming, especially in a large setup.

As a suggestion, place a simple check box on the bridge control page to allow legacy numbering. 
If that was true renumbering would work, if false renumbering fails to work.
By default it could be false.

**Comment by bwssytems** [comment]
Will incorporate the checkbox.

**Comment by tuicemen** [comment]
Thanks, that will help not just me I hope.

**Comment by heikoh81** [comment]
I also would appreciate that feature very much, too!!!

With my HA Bridge, IDs sometimes seem to get confused without any user interaction.
Sometimes, in my Alexa webinterface, the number of devices mutliplies.

One morning, I executed a voice command, and a different device on my house reacted!
I checked the Alexa Website to see that my devices had doubled over night.
I had to manually hit renumber, delete all devices from the Alexa website and finde devices again to get it back to working.

**Comment by tuicemen** [comment]
@bwssytems 
Just getting around to testing things now.
Where is the check box? or is it locked by default and only checking renumbering changes them now?

**Comment by bwssytems** [comment]
@tuicmen You can also just click the ID number in the devices page. It will toggle it back and forth.

**Comment by tuicemen** [comment]
Awesome, nice tip!
