### ISSUE TITLE
Issue with initiating Fibaro scenes

### ISSUE THREAD

**Issue by donL666** [bwssytems/ha-bridge#918]
I have a problem with initiating Fibaro (v4.160) scenes with HA-Bridge (v5.2.0).

The HTTP request that I use in the HA-Bridge parameters works well when launched in Safari web browser but does not work with HA Bridge.

I have created a new device with the following parameters:
- On Items
  - Type: _HTTP Device_
  - Target Item: _http://username:password@ipaddress:80/api/sceneControl?id=id&action=start_

If I click the test on button I receive the following note but the Fibaro scene is not triggered:
_Request Executed: success [{"success":{"/lights/6/state/on":true}}]_

The log says:
_WARN | HTTP response code was not an expected successful response of between 200 - 299, the code was: HTTP/1.1 301 Moved Permanently with the content of <<<>>> | com.bwssystems.HABridge.plugins.http.HTTPHandler
-- | -- | --_

**Comment by bwssytems** [comment]
You'll need to turn on debug for the http handler and then post the output
