### ISSUE TITLE
Google Home keeps telling to update software?

### ISSUE THREAD

**Issue by ygalanter** [bwssytems/ha-bridge#919]
Google Home still controls my MI-Light bulbs fine via ha-bridge, but now after every command and response it says "_by the way, software for this device needs upgrading, visit home control to start the upgrade_" it's kinda annoying, any idea how to get rid of it? Thanks!

**Comment by bwssytems** [comment]
Nope, there is no way. And if you upgrade, it will tale away the ability to contrrol the ha-bridge.

**Comment by ygalanter** [comment]
I haven't done anything and all it says now I have to re-link devices and there's nothing to re-link. Does it mean it auto-updated and all control is gone now?

**Comment by micropet** [comment]
Hello,

I also did the software update today.
When setting up again, I am always directed to the Hue side.

does that mean that we can never use the ha-bridge again with Google Home?

**Comment by bwssytems** [comment]
That is correct. See #764

**Comment by domier** [comment]
Sadly, today google has started to refuse to operate ha-bridge unless it is updated.  Seems that those of us who were grandfathered in are now out of luck.

It's been a good run!  I'll miss ha-bridge T_T

**Comment by ygalanter** [comment]
Well, Alexa/Echo still works fine, so there's that.

**Comment by micropet** [comment]
Thank you. I will switch to the Echo.

**Comment by bwssytems** [comment]
Closing to #764
