### ISSUE TITLE
Can't add Wifi Smart Plug as network device 

### ISSUE THREAD

**Issue by Noirad** [bwssytems/ha-bridge#920]
I'm trying to add [this](https://www.insigniaproducts.com/pdp/NS-SP1XM8/5845000) Smart Plug as a UDP device but can't seem to get it up. Any ideas why?

**Comment by bwssytems** [comment]
For fun, enable the broadlink support in the ha-bridge and see if it finds this device. I have a hunch that this maybe a re-branded broadlink SP1 or SP2 device.

**Comment by Noirad** [comment]
Hey @bwssytems, I tried to use it via broadlink but no luck. 

I gave up on the Insignia, I'll be switching to [this device](https://www.amazon.com/KMC-Monitoring-Required-Control-Protector/dp/B0786B1LGM),

Ultimately, I'm trying to emulate the device in HA as a light bulb, I've been able to do so successfully with  a TP-Link switch.

Another reference point: https://community.home-assistant.io/t/kmc-smart-plug/19610/2

**Comment by bwssytems** [comment]
It seems these plugs do not have any published api and have not found anyone to reverse engineer the api. But, there are people who have flashed the firmware on the chip, but that is way deep to do as you have to have a specialized chip flashing setup.
