### ISSUE TITLE
Link for 5.2.1 not working --> 404

### ISSUE THREAD

**Issue by heikoh81** [bwssytems/ha-bridge#921]
The Link
wget https://github.com/bwssytems/ha-bridge/releases/download/v5.2.1/ha-bridge-5.2.1.jar
on description page
gives me 404!

Please fix.

**Comment by bwssytems** [comment]
Sorry, checked in info on the next small fixes and the readme shows 5.2.1 which does not exist yet. Also, where is that link you show?

**Comment by heikoh81** [comment]
It was in the text in the section "Manual installation of ha-bridge and setup of systemd service".
Maybe you updated the info before putting the file online?
Now the link is working.

**Comment by bwssytems** [comment]
Yes, I as I said above, I checked in the update readme before I released the jar.
