### ISSUE TITLE
Upcoming Vera api changes

### ISSUE THREAD

**Issue by cw-kid** [bwssytems/ha-bridge#924]
Hello

Are you aware of up coming Vera api changes ? 

http://forum.micasaverde.com/index.php/topic,56959.0.html

They are closing some port numbers and changing the way the URLs should be formatted.

Solution
This issue can't be fully fixed by the plugin developers, however, it's necessary that all the data_requests are made on port_3480, and NOT directly on port 3480, or on port 49451, or on port_49451.

So, any request that looks like this:
http://VERA_IP:3480/data_request?id=SOME_VALUE
http://VERA_IP:49451/data_request?id=SOME_VALUE
http://VERA_IP/port_49451/data_request?id=SOME_VALUE

Must be rewritten to look like this:
http://VERA_IP/port_3480/data_request?id=SOME_VALUE

**Comment by bwssytems** [comment]
Someone did put out a notice here for the vera port in #913 

But this looks as if is just changing how to format the url and it will go to the normal port 80 destination.

**Comment by bwssytems** [comment]
included in community information https://github.com/bwssytems/ha-bridge/wiki/Informational-Items-Collected-from-the-Community#q-upcoming-vera-api-changes
