### ISSUE TITLE
Issue pairing with Harmony Hub

### ISSUE THREAD

**Issue by Chrille2k** [bwssytems/ha-bridge#925]
After updating the firmware on my Harmony hub I have not been able to pair with my HA Bridge instance (running in docker) and I get stuck on "_Press the center button in the bridge to pair it with Harmony Hub_"

I use the following steps:

1. Enable Link button in security settings
2. Add the hub in bridge control tab with name and IP.
3. After saving I can see my activities and devices in the Harmony tabs (communications works)
4. In "Manage links" there is one item: _test_ha_bridge#172.17.0.1_
5. Click "Link" button and start pairing with the app.
6. The app finds the hue but requires me to press the "center" button.

I enabled debug loggin and all I got was:

03-15-2018 20:58:34.468 | WARN | Send heartbeat failed | net.whistlingfish.harmony.HarmonyClient
-- | -- | -- | --
03-15-2018 21:00:13.235 | INFO | Link button pressed.... | com.bwssystems.HABridge.SystemControl
03-15-2018 21:00:43.241 | INFO | Link button time ended.... | com.bwssystems.HABridge.LinkButtonPressed

Any ideas?

**Comment by bwssytems** [comment]
What system are you running on with docker? If it is a synology, look at this https://github.com/aptalca/docker-ha-bridge/issues/13

**Comment by Chrille2k** [comment]
I'm running Docker for Windows

**Comment by bwssytems** [comment]
And have you looked at all the other wiki guides to make sure you have your upnp config address set properly?

**Comment by Chrille2k** [comment]
Yes, upnp setup is correct. After some research I found out that Docker for Windows doesn't support "net=host" argument which is needed to forward all ports from the host to the container.

Instead I have to manually forward all ports to the container both the web ui port (8181 in my case) and the upnp ports. Would that be port 50000 according to the documentation?

**Comment by bwssytems** [comment]
That port is for responses directed to habridge by udp sends from the other end when upnp is being negotiated.

**Comment by Chrille2k** [comment]
Opening port 50000/udp makes no difference, I guess there are communications on other ports after the negotiation. Will try with Wireshark.

**Comment by Chrille2k** [comment]
Reverted back to a windows runtime with java which I had before. Docker for Windows simply doesn't support the net=host which is required.

**Comment by bwssytems** [comment]
That is unfortunate. Glad you are up and running though.
