### ISSUE TITLE
Dim commands do not work and other small issues

### ISSUE THREAD

**Issue by pbrisebois** [bwssytems/ha-bridge#926]
Hi Everyone, I just manage to get my Echo 2nd Gen working with my Vera 3 system. However, I do have a couple issues that I am trying to figure out.
1. is it possible to control Door locks? What I am trying to do is to issue a Lock all Doors group in Alexa.
2. on all my Dimable Lights, the Dim function does not work. No matter what percentage I put (either by voice command or within HA Bridge web browser, the light always goes to 100% brightness. Here is the On Command in Edit in one of my lights (http://192.168.#.###:3480/data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:SwitchPower1&action=SetTarget&newTargetValue=1&DeviceNum=80)

Here is the Dim Command (http://192.168.#.##:3480/data_request?id=action&output_format=json&serviceId=urn:upnp-org:serviceId:SwitchPower1&action=SetTarget&newTargetValue=1&DeviceNum=80)

Notice that they are both the same? shouldn't Dim have a different command line?

Anyone know how to fix this?

**Comment by bwssytems** [comment]
@pbrisebois Before you build a device, you need to select the type of Dim that is at the top of the page. The default is no dim as we don't know if this is just a switch or not.

**Comment by pbrisebois** [comment]
I actually figured it out, as well, I got the locks to work. Just forgot to post my findings.

thanks
