### ISSUE TITLE
homekit "sync" issue with 5.2.0 and up

### ISSUE THREAD

**Issue by pponce** [bwssytems/ha-bridge#928]
I'm not 100% sure how to troubleshoot this issue to help you with reproducing this.
Here is my setup.
Homebridge --> Homebridge-hue ---> ha-bridge
Here is what i'm seeing:
On version 5.2.0 and above when my activity states get out of sync with homekit because someone in my family chooses to use the actual harmony remote or the apple remote (which turns tv and receiver on via hdmi cec), I am unable to "gracefully" get things back in sync.   Instead my homekit "watch apple tv activity" get stuck in an unreachable state.  Only way to fix the issue that i've found is to restore my harmony activities db in HA-bridge settings.

On version 5.1.0 when my activity states get out sync. I can get things back in sync by just turning on and off the activity in homekit. No unreachable error is returned.  No need to do a settings restore in ha-bridge.  Everything just gets back in sync by hitting the homekit buttons a couple of times.

Let me know what i can do to provide more useful info.

**Comment by bwssytems** [comment]
Interesting, will take a look

**Comment by pponce** [comment]
Thanks. Let me know if there is some testing i can do.
I'm running just fine on 5.1.0 though.

**Comment by bwssytems** [comment]
Turn on debug for the HueMulator class and post your log. This seems related to #938

**Comment by pponce** [comment]
Updated back to 5.2.1 last night and turned on debug.
Tried to recreate my issue but was not able to. Scratching my head a little here as I was able to create the issue pretty consistently before i reverted back to 5.1.0.

I'll keep the debug setting on for some time in case i'm able to recreate the issue again.

**Comment by pponce** [comment]
I just tried to turn on my "watch apple tv scene" and got the failed error in the home app.
Can't turn on the harmony activity. the harmony activity that corresponds to "watch apple tv" shows in the home app as "no response".  And i can't change that.
I did not notice anything strange in the debug log.
[debug.txt](https://github.com/bwssytems/ha-bridge/files/1864689/debug.txt)
Restoring device db backup and restarting the home app fixes it until it happens again.

**Comment by bwssytems** [comment]
So, does your Harmony get turned off or change IP addresses? This seems as if ha-bridge has lost connectivity to the harmony after it is turned off and back on. This is in #945

**Comment by pponce** [comment]
No my harmony is always plugged in, directly into an old fashioned dumb socket.  :)
IP does not change.
5.1.0 works flawlessly for me though.  When my wife uses the harmony direct to turn on my apple tv activity all i need to do is hit the watch apple tv scene to get back in sync.  Works 100% of the time in 5.1.0.

In 5.2.0 and above i end up having these out of sync issues that can only get rectified with restoring device db backup and restarting the home app.
