### ISSUE TITLE
Running HA-Bridge as a service in Linux?

### ISSUE THREAD

**Issue by tuicemen** [bwssytems/ha-bridge#929]
I'm not a Linux guy so doing this has been a issue and I'm not sure I still have everything set right.
This may be the reason it doesn't see the Broadlink RM
I'm running the latest stable Debian release and seeing as each flavor of Linux uses a different method to get a service working that may be part of the issue as well.
After several days playing with scripts I finally got the bridge to load on boot up running as a service seemed to be the trick to that.
However initial run I lost all settings and devices which I managed to reconfigure  and they all now load on each boot.
The issue still remains with the Broadlink RM discovery. If I disable the broadlink support then re-enable Ha-Bridge finds the Broadlink also if after boot I go and just reinitialize it also finds the Broadlink.
This leads me to think the Bridge is getting loaded prior to my Wi-Fi on boot.
Is it possible to add a delay to the Broadlink discovery?
May be user selectable?
I'm not sure if debug settings will stay on a reboot in Linux as they don't in Windows.so submitting a log may not be helpful.

**Comment by bwssytems** [comment]
You should use the instructions here https://github.com/bwssytems/ha-bridge/blob/master/README.md#manual-installation-of-ha-bridge-and-setup-of-systemd-service

**Comment by tuicemen** [comment]
That is essentially what I tried initially but it never worked.
The problem isn't that the bridge isn't starting, it is.
It just doesn't see the Broadlink RM until I do a refresh.
I doubt following the outlined instructions will help but will disable the service I created and try again using the instructions for a PI.
I may have better luck this time around.

**Comment by audiofreak9** [comment]
You can add a sleep command before your `ExecStart` with `ExecStartPre`

`ExecStartPre=/bin/sleep 30`

**Comment by tuicemen** [comment]
@audiofreak9 thanks that may work I'll try that as well.

**Comment by tuicemen** [comment]
Well no difference.
Broadlink RM still doesn't get seen on bridge service loading on boot.
I'll try a longer sleep then 30 tomorrow.
Every thing works if I just manually start the service this is why I feel the need for the delay

**Comment by tuicemen** [comment]
I figured the issue may be the speed at which my Wi-Fi connects so I switched to using an Ethernet connection, but that doesn't help.
I also thought it maybe the default browser (firefox) so I installed another still with no difference.
Well actually a re-initialization even fails to find the Broadlink using Ethernet and a different browser.

Does anyone have HA-Bridge successfully running as a server with a Broadlink being discovered on boot up?

**Comment by bwssytems** [comment]
@tuicemen So a couple of things. As @audiofreak9 suggested it may not be waiting for the network to be up, even though the unit files says it should. Does the discovery work if you hit the broadlink refresh button, then leavr that tab and then come back to it? If disvoery is not working, turn on debug for broadlink plugin and the com.mob41.blapi. Also, if you have broadlinks already in your device list, they will autocreate themselves when they are used.

**Comment by tuicemen** [comment]
I'm beginning to think the issue is the PC
I stopped the service I created using the Help file directions and restarted the service I had created earlier as what worked yesterday doesn't today.
With my previous service a refresh did display the broadlink when I returned to the tab.

**Comment by tuicemen** [comment]
bridge has been running for a few days now as service.
I ended up using the Ethernet connection and the Broadlink RM was found each boot up.
