### ISSUE TITLE
Run two commands with one HA Bridge Device (Yamaha AV)

### ISSUE THREAD

**Issue by 1liminal1** [bwssytems/ha-bridge#930]
Hey all, 

Ive seen a post asking how people can use HA Bridge to turn on there Yamaha Amps, heres some info I have dug up. 

http://www.hifi-forum.de/viewthread-276-7262.html

https://www.heimkino-praxis.com/yamaha-netzwerk-steuerung/

https://www.andreas-edler.de/blog/2017/01/yamaha-av-receiver-mit-amazon-echo-steuern/

Just in case anyone needs it :)

**Comment by npaisnel** [comment]
Commenting to follow

**Comment by bwssytems** [comment]
included in the community information https://github.com/bwssytems/ha-bridge/wiki/Informational-Items-Collected-from-the-Community#q-run-two-commands-with-one-ha-bridge-device-yamaha-av
