### ISSUE TITLE
Alexa continues to see old devices

### ISSUE THREAD

**Issue by jonny9998** [bwssytems/ha-bridge#932]
I probably made a mistake here, but I decided to redo my devices on ha-bridge.  Now Alexa is seeing two of everything after discovery.  Is this an Alexa issue or an ha-bridge issue?  If a bridge, issue, how do I remove the old devices from reporting to Alexa

**Comment by bwssytems** [comment]
You will need to forget all devices on Alexa and then do the discovery.

**Comment by jonny9998** [comment]
Thanks.  I did get it to work but the only way I could make it work is to forget each device individually.  Attempting to use the option to forget all devices did not work.  I suspect this is an Alexa issue.
