### ISSUE TITLE
Help with running a PHP module via HAB

### ISSUE THREAD

**Issue by jouster1974** [bwssytems/ha-bridge#933]
HABridge is running well for me so far and I'd like to add a Nest component to my controls.

A very helpful chap has created a PHP module that can trigger the Hot Water boost that many users want but NEST refuse to supply.

His write up about it can be found here

(http://www.aimlesswandering.uk/web/2017/11/nest-thermostat-hot-water-controlled-by-alexa/)

I've created the relevant PHP file and now wondering how I can call that module from within HABridge

Im sure many people here might find this useful so was wondering if you are able to shed any light on it

**Comment by bwssytems** [comment]
You could do what the article suggests as one tool does not fit everything. Or you could create a script to call the PHP code on your ha-bridge host. FYI - I am not the one to do the script....

**Comment by jouster1974** [comment]
I've got a script but it was HOW I call a PHO script that I was asking about as this wasn't immediately obvious to me

**Comment by bwssytems** [comment]
Here is the construct of calling a script. https://github.com/bwssytems/ha-bridge#script-or-command-execution
