### ISSUE TITLE
Changing Alexa app device status that is activated by outside source

### ISSUE THREAD

**Issue by mikelhall** [bwssytems/ha-bridge#938]
I can activate thru the HA Bridge by IFTTT the command to turn on/off lights. This process,however, will not indicate this in the Alexa app for my devices. This is the command I am using:
WinHTTP := ComObjCreate("WinHTTP.WinHttpRequest.5.1")
;~ WinHTTP.SetProxy(0)
WinHTTP.Open("PUT", "http://xx.x.x.xxx:8080/api/user/lights/26/state")
WinHTTP.SetRequestHeader("Content-Type", "application/json")
Body := "{'on':true}"
WinHTTP.Send(Body)
This will turn on/off lights thru the bridge but not change the status in the Alexa app. The same goes when using this in IFTTT. If I use the Test Buttons in the HA Bridge, The status does change. What am I missing?

**Comment by bwssytems** [comment]
That is interesting as the test button calls the ha-bridge the same way as any external device would. Turn on debug for the HueMulator class and pay your log.

**Comment by mikelhall** [comment]
This is the information sent to the Bridge by the IFTTT. The funny thing is, if I change the state to bridgeupdatestate and the body to {"on":false}, the Alexa app will change status but the light will not turn off.
03-28-2018 20:29:14.812 	DEBUG 	HueMulator PUT called on api/* with request <<</api/user/lights/26/state>>>, and body <<<{'on':true}>>> 	com.bwssystems.HABridge.hue.HueMulator
03-28-2018 20:29:14.813 	DEBUG 	matchedPart: :userid = user 	spark.Request
03-28-2018 20:29:14.814 	DEBUG 	matchedPart: :id = 26 	spark.Request
03-28-2018 20:29:14.815 	DEBUG 	hue state change requested: user from 54.88.172.133 body: {'on':true} 	com.bwssystems.HABridge.hue.HueMulator
03-28-2018 20:29:14.815 	DEBUG 	validateWhitelistUser: found a user <user> 	com.bwssystems.HABridge.BridgeSecurity
03-28-2018 20:29:14.816 	DEBUG 	Decode Json for url items: [{"item":"C:\\ALEX10/ALEX10.EXE SENDRF_A11_ON"},{"item":"C:\\ALEX10/ALEX10.EXE SENDPLC_A11_On"}] 	com.bwssystems.HABridge.hue.HueMulator
03-28-2018 20:29:14.817 	DEBUG 	Calling Home device handler for type : exec 	com.bwssystems.HABridge.hue.HueMulator
03-28-2018 20:29:14.817 	DEBUG 	Exec Request called with url: C:\ALEX10/ALEX10.EXE SENDRF_A11_ON and exec Garden: not given 	com.bwssystems.HABridge.plugins.exec.CommandHome
03-28-2018 20:29:14.817 	DEBUG 	Request <<C:\ALEX10/ALEX10.EXE SENDRF_A11_ON>>, not done: false 	com.bwssystems.HABridge.hue.DeviceDataDecode
03-28-2018 20:29:14.818 	DEBUG 	Executing request: C:\ALEX10/ALEX10.EXE SENDRF_A11_ON 	com.bwssystems.HABridge.plugins.exec.CommandHome
03-28-2018 20:29:14.829 	DEBUG 	Process running: true 	com.bwssystems.HABridge.plugins.exec.CommandHome
03-28-2018 20:29:14.934 	DEBUG 	Calling Home device handler for type : exec 	com.bwssystems.HABridge.hue.HueMulator
03-28-2018 20:29:14.934 	DEBUG 	Exec Request called with url: C:\ALEX10/ALEX10.EXE SENDPLC_A11_On and exec Garden: not given 	com.bwssystems.HABridge.plugins.exec.CommandHome
03-28-2018 20:29:14.934 	DEBUG 	Request <<C:\ALEX10/ALEX10.EXE SENDPLC_A11_On>>, not done: false 	com.bwssystems.HABridge.hue.DeviceDataDecode
03-28-2018 20:29:14.934 	DEBUG 	Executing request: C:\ALEX10/ALEX10.EXE SENDPLC_A11_On 	com.bwssystems.HABridge.plugins.exec.CommandHome
03-28-2018 20:29:14.944 	DEBUG 	Process running: true 	com.bwssystems.HABridge.plugins.exec.CommandHome
03-28-2018 20:29:14.944 	DEBUG 	Response is in error: null 	com.bwssystems.HABridge.hue.HueMulator

**Comment by tuicemen** [comment]
have you tried `PUT	http://host:port/api/<username>/lights/<id>/bridgeupdatestate` 
https://github.com/bwssytems/ha-bridge#update-bridge-internal-light-state

**Comment by mikelhall** [comment]
Hi Tuicemen. I was hoping to delete some of the running programs on the computer by IFTTT. Alex10 has been my best option and i will stick with it. IFTTT is a secondary Alexa command that works instantly when Alexa has a delay with HA Bridge working.

**Comment by tuicemen** [comment]
You may also wish to look at SmartThings I mentioned here:
https://github.com/bwssytems/ha-bridge/issues/876
Though I use it for Google it works with Alexa and Cortana as well.
Once setup you merely enable the SmartThings skill.
