### ISSUE TITLE
Bridge requires user name and password if default port is changed (5.2.1)

### ISSUE THREAD

**Issue by tuicemen** [bwssytems/ha-bridge#939]
I remember this being brought up in 5.2.0 RC testing.
Since several of us already had usernames and passwords added many never noticed.
and reverting to a previous build and adding a user fixed the issue.

However while attempting to debug a friends HA bridge I noticed this.
Using the default port of 80 the bridges loads fine, if you change the port when it restarts it goes to the login page.
Since no login was created you can't access the bridge.

I deleted the habridge.config file and restarted the bridge which loads the defaults. I created a login then changed the port and saved I was able to login  and access the bridge so I figured I would remove the user and that would allow access to the bridge without the log-in.  Nope! Still throws the login page up so I figured maybe the user never got deleted, but typing in the info I get user doesn't exist.

**Comment by bwssytems** [comment]
That is interesting. I saw that comment too and thought the user added  security at some point. But remembering that post, he did not add a user. Let me take a look.

**Comment by bwssytems** [comment]
I do not get the login page when changing the web server port.
