### ISSUE TITLE
Emulate Hue Hub Version# stops Alexa seeing HA-Bridge devices

### ISSUE THREAD

**Issue by tuicemen** [bwssytems/ha-bridge#941]
While attempting to get the HA-Bridge running on Linux I noticed Alexa wasn't seeing my HA-Bridge configured devices.
I have no issue with my older setup on a Windows 10 PC.
However this was a new setup with no old settings so I began to compare settings. My Windows machine is running default values for things from 3.5.0 the Linux machine has default values from 5.2.1 so there are a few different ones. After going through all settings I noticed the Emulate Hue Hub Version# was now 99999999 the version on my old setup is 01036659.
changing to the old version # allowed Alexa to see my devices. There were other settings which were different but that's the only one that made a difference.
Is the  Emulate Hue Hub Version# of 99999999 right?
Could this be why others are having issues with Alexa seeing HA-Bridge devices?

**Comment by audiofreak9** [comment]
I find this interesting, I wonder who else can try this that is having discovery issues.  What mix of Echos do you have?  This is the firmware version from Nov 28, 2016 Firmware **01036659** (bridge V1 & V2) per [meethue.com](https://www2.meethue.com/en-us/support/release-notes/bridge).  I wonder what would happen if you enter the current V2 Firmware **1802201122** from Mar 19, 2018?

BTW, you can always [reference the FAQ WIKI](https://github.com/bwssytems/ha-bridge/wiki/HA-Bridge-FAQs#HUEReleaseVersion) to find the link to update your emulation version.

**Comment by tuicemen** [comment]
I have several second gen dots but no other Alexa devices.
Looking over another new HA-Bridge setup on a windows PC that had discovery issues I also noticed the Emulate Hue Hub Version entry of 99999999
Interesting using the  current V2 firmware 1802201122 works and Alexa discovers the devices.
I'll play around a bit more with this as there may be something else at play.
The fact that I have more then one bridge operating may also be a factor here.

**Comment by tuicemen** [comment]
interestingly after playing with different hub version numbers and discovery working for them I re-entered
99999999 and added a new device and discovery worked.
Now I'm really stumped!
I'm not sure why Alexa didn't discover before it wasn't a internet thingy as devices on my other bridge were still seen as connected.

**Comment by m0urs** [comment]
Have the same issue here. However, none of the firmware versions mentioned did improve something. Alexa is no longer seeing my devices. All old ones are offline and new ones are not recognized.

**Comment by wennes** [comment]
New Device not working...
Update to 5.2.1 ...
Version change....
Alexa still does not find my devices anymore...
Smells like the same problem

**Comment by m0urs** [comment]
Now everything is working again without a change here. Seems that it was a issue with Amazon.

**Comment by dougdalton** [comment]
I went back to 4.5.6

and I am running on a qnap with:
UPNP set to my server ip
Use UPNP Address Interface Only not set to false 
web server address set to 0.0.0.0
web server port to 8065
UPNP response port 50000
Emulate hue hub version to 1802201122
and Strict UPNP to off

and it still isnt working,  I am happy to try 5.3.1rc1 with recommended settings again and send more log file
