### ISSUE TITLE
HABridge no longer picked up by Alexa

### ISSUE THREAD

**Issue by jouster1974** [bwssytems/ha-bridge#942]
Everything has been working well with my basic setup for quite some time now but I've noticed a slight issue today.

I noticed that one element on my HABridge wasn't responding to voice activation today so I removed it from Alexa and tried to discover it again but it wasn't able to do so...I know from experience that sometimes Alexa needs to have ALL devices removed in order to redetect existing ones so I removed them all hoping it would solve the issue

Unfortunately, this has not worked.  None of my three existing and fully working HABridge devices are now detectable at all.  I've rebooted the Pi they are running on but still no joy.

I can still activate them via the test button on the HABRidge UI but they simply won't be activated via Alexa.  I don't have any true Hue devices so it's not directly Hue related.

I am running HAB version 5.1.0,  I've looked at my phone and can't see any updates to the app that may have changed anything at my end.  One of the Dots I usually use for this has device software version 601481020 on it 

I've looked at the logs and there are a lot of repetitions of the following line, all at different times 

03-29-2018 14:58:00.404 | INFO | The requested route [/(null)] has not been mapped in Spark for Accept: [null] | spark.http.matching.MatcherFilter
-- | -- | -- | --

I've changed nothing on Alexa prior to this and it was working just this morning without issue.

I assume Alexa itself may have had some updates which have thrown a spanner in the works but thought I would report this anyway in the hope I am not the first to discover it and that there is some form of fix in the works that I haven't tried yet.

If you require any other information that I haven't included above please let me know.

TIA

UPDATE

I have just updated to HABridge version 5.2.1 and still have exactly the same issue, the devices are controllable from within HABridge UI itself but I cannot discover them in Alexa and therfore they arent working from that..

**Comment by m0urs** [comment]
I see the same issue here after it has been working for a while. Updating to the newest version also did not solve the issue.

**Comment by vantino** [comment]
#metoo - running 5.2.1 since weeks w/o any issues, but today Alexa can not find the HUE Bridge.
GUess it´s on the Amazon side ...

/V

**Comment by martinbulinski** [comment]
The same problem to me: I can access my devices via the "test"-buttons in ha-bridge, but Alexa does not recognize. All went good for months. Using 5.0.0. 
Asking for Dimming Alexa answers "not supported" asking for "switch on or off" answers "not found".

**Comment by stnkl** [comment]
I only tried using ha-bridge today and was wondering why I couldn't get Alexa to find my ha-bridge with my Echo Dot 2nd Gen. I tried discovering my ESP8266 based device ([arduino-esp8266-alexa-multiple-wemo-switch](https://github.com/kakopappa/arduino-esp8266-alexa-multiple-wemo-switch)) which emulates the Belkin Wemo switch and couldn't find it either. The same device could be detected two days ago, so I also suspect some changes by Amazon. I hope this is not the end of device emulation.

**Comment by jag77** [comment]
Same problem for me too. Test buttons work, but Alex just isn't able to discover any devices after I have removed all devices.

All my 3 echo and dots are Gen1 units.

**Comment by stbluesrul** [comment]
I had the same issue earlier today as described in this thread but I just did a discovery and every is showing up again.

**Comment by torinnguyen** [comment]
I had problem discovering devices about 12h hours earlier, even with Echo 1st gen. Now it's working again. I didn't change anything.

**Comment by jag77** [comment]
Strangely, all systems normal now. Earlier reported issue went away.

**Comment by m0urs** [comment]
Yes, it seems it was an issue with Amazon. Works here again also without any changes.

**Comment by jouster1974** [comment]
Also working fine here again now.  

Thanks for the coments all.
