### ISSUE TITLE
Binding to all IP addresses

### ISSUE THREAD

**Issue by martinpeg26** [bwssytems/ha-bridge#944]
Hi, firstly thank you for an amazing bit of software, it's brilliant.
I've been trying to get ha-bridge v5.0.0, 5.1.0 and 5.2.1 to bind to just my Pi3's IP address for the UPnP port 1900 but none of them will, starting them all I can see that 1900 udp is bound to all interfaces (0.0.0.0).

The setting in my config for Use UPNP Address Interface Only is ticked and the UPnP IP address is set to the host's IP.

I also tried to set this by passing in -Dserver.ip on the command line but it was still the same and I see that command line arguments are deprecated anyways.

Any help anyone can give would be very much appreciated.
Kind regards
Martin

**Comment by bwssytems** [comment]
Will take a look

**Comment by martinpeg26** [comment]
Ok. C is my language of choice and I'd b a bit lost with Java.
Good luck with it but please realise it's not as important as the other tasks you have, it's just that I'd like to have minidlna running on the same RPi 3 as ha-bridge and domoticz.
Thank you again.
Martin

**Comment by bwssytems** [comment]
Already have it worked out.

**Comment by martinpeg26** [comment]
That's brilliant, thank you.

**Comment by martinpeg26** [comment]
Hi, I'd forgotten about this and just remembered about it now.
Is there any update/fix please?
Thanks
Martin

**Comment by bwssytems** [comment]
Yes, the development branch has the fix, but i am not liking the way I did it. Thinking through a better solution.

**Comment by martinpeg26** [comment]
No problem, I'm fine without this at the minute but would be good to get a fix.
