### ISSUE TITLE
Homekit client implementation for local control of cloud-only devices

### ISSUE THREAD

**Issue by fm5150** [bwssytems/ha-bridge#946]
Would there be any way to implement a Homekit client in ha-bridge to control Homekit devices locally that would otherwise be controlled via cloud? I ran into a project called mqtt2homekit that seems to do this. It would be great, however, if ha-bridge could talk directly with a Homekit device. I am looking for the inverse of Homebridge, so I thought I would ask here since ha-bridge is already doing a fantastic job of tying other systems together.

**Comment by bwssytems** [comment]
Something to look at. I have been playing around with the java homekit library that is out there, but it is only emulation side, not client side.

**Comment by bwssytems** [comment]
This is a dup of #822  as well

**Comment by bwssytems** [comment]
With the implementation of Mozilla IOT, Which has homebridge connectivity, I will suggest that is the path to implement this.

See https://iot.mozilla.org/
