### ISSUE TITLE
Fibaro HC2 Error while get getJson Ha-Bridge version 5.2.1

### ISSUE THREAD

**Issue by Scarac01** [bwssytems/ha-bridge#948]
Hello,

we are trying to set up ha-bridge for Fibaro Homecenter 2 to get Alexa support.
At bridge control under: Fibaro Names and IP Addresses we put in:

Name: we used the Homecenter 2 Fibaro serial number HC2-012345
IP : we used the IP in our windows network for the homecenter
Port: Standard 80 (no webserver is running on rasbperry pi)

**Identification:**
1st: Username: we tried the local Homecenter admin (not as E-Mail address) with the local Pasword
2nd: Username: we tried the fibaro ID for entering the homecenter from everywhere (admin@xxx.de) and the fibaro id password
3rd: Username: we tried local  admin@xxx.de  for entering the homecenter in the local network and the local Pasword

Filters: 
Save Logs X  
User Desc X 
Lili Cmd
Trash Chars  X

The result was always after pushing the Fibaro button in habridge:

INFO | Fibaro Home created. | com.bwssystems.HABridge.plugins.fibaro.FibaroHome

WARN | Error while get getJson: /api/rooms | com.bwssystems.HABridge.plugins.fibaro.FibaroInfo
WARN | Error while get getJson: /api/scenes?enabled=true&visible=true | com.bwssystems.HABridge.plugins.fibaro.FibaroInfo

WARN | Error reading the file: data/group.db - Does not exist or is not readable. continuing... | com.bwssystems.HABridge.dao.GroupRepository
(we have not created any groups by now)

WARN | The upnp config address, 10.xxx.xxx.xxx, does not match any known IP's on this host. | com.bwssystems.HABridge.BridgeSettings
(10.xxx.xxx.xxx is the local IP of the rasbperry in the network)

Is it right that normaly the fibaro plugin should call all apis from the homecenter? So you do not have to put in all devices and scenes manually.

**To find out whats happening with fibaro we tried the following in the browser:**

http://admin%40xxx.de:Passwd@10.xxx.xxx.yyy/api/rooms
http://admin%40xxx.de:Passwd@10.xxx.xxx.yyy/api/devices?enabled=true&visible=true
(10.xxx.xxx.yyy is the local IP of the Fibar HC2 in the network)

We are not able to get to the adress /api/rooms directtly. We have to log in manually the User  and the Passwd in the browser. The result is the list of rooms and devices.

If you need more information to solve the issue pleas do not hesitate to ask.

Thank you very much for your help
best regards

**Comment by Chickenparmie** [comment]
If you have all the right info it should drag all devices and scenes out of the home centre.
Name is what you want to call it, IP adress of Home Centre, port 80, FibaroID email and password.
If you are on the latest firmware of Fibaro 4.17 you should not have admin as the login and password.
it adds the Fibaro ID as the login in the setup after update.
If that does not work, I just build my own devices in the bridge, name it what you want to and add the http calls.
for example:    http://FIBAROID%40PROVIDER.COM:PASSWORD@HOMECENTREIP/api/callAction?deviceID=IDNUMBER&name=turnOn
You enter your FIBARO ID email and PASSWORD and HOMECENTREIP and IDNUMBER of device
for dimming call     http://FIBAROID%40PROVIDER.COM:PASSWORD@HOMECENTREIP/api/callAction?deviceID=IDNUMBER&name=setValue&arg1=${intensity.percent}
and for off call   http://FIBAROID%40PROVIDER.COM:PASSWORD@HOMECENTREIP/api/callAction?deviceID=IDNUMBER&name=turnOff
for a scene   http://	FIBAROID%40PROVIDER.COM:PASSWORD@HOMECENTREIP/api/sceneControl?id=SCENEIDNUMBER&action=start

once you have one created you can just change the device name and the id numbers in the calls and add as a new device.
upnp should be IP of Pi
