### ISSUE TITLE
FHEM Names and IP Addresses will not be saved

### ISSUE THREAD

**Issue by darkretailer** [bwssytems/ha-bridge#949]
Today i update my habridge to 5.2.1.
Now there is an option to save FHEM Names and IP Addresses.
I add these, save and the bridge will reinitialize.
The settings are written to habridge.config but if i login again the settings will not be shown, as if I had made no changes.

habridge.config:
```
...
"fhemaddress":{"devices":[{"name":"FHEM","ip":"127.0.0.1","port":"8089"},{"port":"8080"}]},
...
```

**Comment by bwssytems** [comment]
So this looks as if the habridge.config device is being saved to a location that is not found in the start up path for the habridge. It is best to use the command line location to define the full path to your habridge.conf.
