### ISSUE TITLE
FHEM devices after import not working

### ISSUE THREAD

**Issue by Thomas-8-Bit** [bwssytems/ha-bridge#950]
After successfull installation of ha-bridge i've configured my FHEM-server within the config of ha-bridge. I can see all devices under the "FHEM Devices" tab. When i import a device, it's not working. No test ist positive and it seems that ha-bridge doesn't contact the FHEM-server to set any value.

Defined HTTP-Devices work well with the FHEM server and ha-bridge. 

How have i to import FHEM devices to not use HTTP devices?

**Comment by bwssytems** [comment]
Are there any errors in your log?

**Comment by Thomas-8-Bit** [comment]
There were no errors. Don't know why, but after 24 hours now it works without restart or reboot? Thank you for your investigation.
