### ISSUE TITLE
Vera Connection Problem

### ISSUE THREAD

**Issue by jsin44** [bwssytems/ha-bridge#952]
Ha-bridge can't find my Vera devices/scenes. It stopped working about a month ago.

I get this WARN:
Error calling out to HA gateway: IOException in log: Connect to 193.168.1.24:3480 [/193.168.1.24] failed: Connection timed out: connect

Vera version is 1.7.1017

Let me know what other info you need, please.

**Comment by jsin44** [comment]
Yes.  The ip of the vera changed from .24 to .25. I noticed this, changed the vera ip in ha-bridge, and the vera devices/scenes list repopulated right away and it worked for about a day. Then the vera ip changed back to .24 and when I changed it back in ha-bridge it didn't work (empty devices/scenes lists).

**Comment by bwssytems** [comment]
Please set your vera to a static IP address. The ha-bridge is not a mind reader when the ip changes.

**Comment by jsin44** [comment]
Thanks for your help.
