### ISSUE TITLE
Alexa discovers all devices, but returns 'device not responding'

### ISSUE THREAD

**Issue by ROL-HA** [bwssytems/ha-bridge#953]
Setup ha-bridge-5.2.1, successfully added and tested 15 bridge devices linked to my Domoticz setup.

Alexa discovers all devices, but when using the command 'Alexa Turn On [device name], Alexa responds with '[device name] not responding'. This is the same for all 15 Devices.

ha-bridge is on port 8081 and Domoticz is on port 8080.

Can anyone assist, please?

**Comment by tuicemen** [comment]
Does the device actually turn on/off with Alexa but you get the "not responding" voice response?
I've had this happen to me on occasion.
I've fixed this with either unplugging my amazon device then plugging it back in after 5 mins, and or rebooting my PC.
