### ISSUE TITLE
ha bridge with easy bulbs 

### ISSUE THREAD

**Issue by sheriffdude** [bwssytems/ha-bridge#954]
hi guys could some one help here been trying this for ages with no luck ok i have have bridge up and running using 5.2.1 dont see any manual add i am using a batch file to start it with 
java -jar -Dserver.port=8081 ha-bridge.jar so it opens up after i put 
http://localhost:8081/#!/ in the browser page ..ok so now i have the bridge up can some one help with where i put what i no ip bridge is https://192.168.1.3:8899/0x420055    is 192.168.1.3 and port number is 8899 but where do i put this info as have tried loads of thing with no luck ..
i can get the app LimitlessLED MiLight Remote v2.1.11  to work and that works with 192.168.13 port number 8899  so i no this works ..so if you guys can just help me with the rest have also tried getting alexa to find ha bride no luck i have a dot 2..  
![bridge](https://user-images.githubusercontent.com/34724820/39097581-1fe1ec54-4656-11e8-92a8-bef96f9ab1c7.png)
![bridgezzxxxxx](https://user-images.githubusercontent.com/34724820/39097584-2381bd8a-4656-11e8-8237-1af3565ef07c.png)
![bridgezzxx](https://user-images.githubusercontent.com/34724820/39097587-33bdc112-4656-11e8-8d6b-f1eb4d9d277a.png)

so i need to know what do i put in where it says bridge url ..is that ./api/devices or is it https://192.168.1.3:8899 
sorry guys not done any proper coding so if some one could help ..some one did say you could also put the code into a browser to work but not again sure what to put in 
i would like to get this working with easy bulbs then use alexa with it by at some point puting it on a raspberry  pie running ha bridge i understand the concept just not why it not all working 
also using in the call box 
udp://192.168.1.3:8899/0x420055
to turn light on but again nothing is working 

up date i can now control all light   ..but alexa still can't find ha bridge so if anyone out there can think of something help would be great thank you using windows 10 and ha bridge 5.2.1

**Comment by bwssytems** [comment]
Please review the FAQ for Alexa to find your bridge. https://github.com/bwssytems/ha-bridge/wiki/Trouble-Shooting#q-echo-does-not-discover-my-ha-bridge
