### ISSUE TITLE
nest 2FA support?

### ISSUE THREAD

**Issue by dJOS1475** [bwssytems/ha-bridge#957]
Howdy, loving HA-Bridge for tying my Echo's to my Vera Plus HAC however I'd like to try the nest integration but there's no option to put in the 2FA code nest text's me when I enter my credentials?

I assume 2FA isnt supported yet?

**Comment by dJOS1475** [comment]
PS, im running 5.2.1

**Comment by bwssytems** [comment]
Unfortunately, the api I use is an old one and does not support 2FA. Probably will not happen.

**Comment by dJOS1475** [comment]
Cheers, I thought that might be the case.
