### ISSUE TITLE
Http request with authentication

### ISSUE THREAD

**Issue by peadard** [bwssytems/ha-bridge#96]
HI there i am trying to get the ha bridge to control an ElkM1 with Elve via http calls such as this:
http://user:password@172.16.0.22:33900/RunScript/false/elkm1.TurnOnLight(5)
If I type it into a browser it works fine and I can turn on the lights.
However when I add it to the ha bridge I get an error " Change device state, Could not send data for network request"
I read in one of the other closed issues that the bridge does not support URL authentication.
Is this so? is there any way around this without disabling authentication?
Thanks guys?

**Comment by bwssytems** [comment]
I'll take a look at the URL parsing to see if that messes with this

**Comment by peadard** [comment]
Thanks mate, appreciate it
