### ISSUE TITLE
Device DB not saving

### ISSUE THREAD

**Issue by wookienow** [bwssytems/ha-bridge#960]
I can't get the device.db to update. If I delete the device.db file Homebridge will recreate and put the current config in the GUI in it.
If I change the config then stop and start it Homebridge it doe snot update the device.db file.

Any ideas?

**Comment by bwssytems** [comment]
make sure that the file is in the place you expect it and the user running the ha-bridge has write access.

**Comment by wookienow** [comment]
As HA-bridge is able to recreate the file if I delete it. I would have thought write permission should be correct. I have chmod 777 the device.db file and it didn't make a difference as well.

**Comment by bwssytems** [comment]
So, what is your command line to star the ha-bridge and also the directory where you are at the time of the start. Also post the habridge.conf file

**Comment by bwssytems** [comment]
Any update on this?
