### ISSUE TITLE
new router. cannot open webpage after running java jar file.

### ISSUE THREAD

**Issue by michaelhinchey** [bwssytems/ha-bridge#961]
was wondering if I needed to open ports on my new router//?   This was setup on my old router so long ago and worked great.  Now it wont open the initial page.  I tried changing the port and ipaddress of the config file and nothing happened.  i also tried to delete it and then run the jar file again.  i didn't see a config file made so maybe its stored elsewhere.  My ip address now has a / so lloks like this 192.168.1.16/24.
i never really noticed this before. Does the slash and number after it matter//?Any help would be appreciated.  Thx in advance

**Comment by bwssytems** [comment]
The ip address is always a 4 byte number representation, 192.168.1.16. The ```/24``` is just a reference to the net mask of 255.255.255.0. So don't put the ```/24``` in any ip address field.
