### ISSUE TITLE
How to Create Vera Scenes?

### ISSUE THREAD

**Issue by dJOS1475** [bwssytems/ha-bridge#962]
I might be dense but is there a guide on making Vera Scenes available to Alexa? I thought i'd successfully created a couple only to find that Alexa sees them as devices, not scenes.

**Comment by dJOS1475** [comment]
So the reason this is a problem is, Alexa thinks my "scenes" act like an on/off toggle switch when in fact scenes are more like a momentary switch merely trigger other actions.

**Comment by dJOS1475** [comment]
So the reason this is a problem is, Alexa thinks my "scenes" act like an on/off toggle switch when in fact scenes are more like a momentary switch merely trigger other actions.

I want to use my Vera Scenes inside Alexa Routines to enhance WAF, but if the routine only knows to turn on a "vera scene" it'll only work once.

eg I have a Routine called "Bedtime" = Turn off lounge lights, rumpus room lights, set Downstairs nest to 16c, turn on Main bedroom Lamps.

**Comment by dJOS1475** [comment]
So the reason this is a problem is, Alexa thinks my "scenes" act like an on/off toggle switch when in fact scenes are more like a momentary switch merely trigger other actions.

I want to use my Vera Scenes inside Alexa Routines to enhance WAF, but if the routine only knows to turn on a "vera scene" it'll only work once.

eg I have a Routine called "Bedtime" which equals this Vera Scene = Turn off lounge lights, rumpus room lights, set Downstairs nest to 16c, turn on Main bedroom Lamps.

**Comment by dJOS1475** [comment]
Ok I was just poking around my HA-Bridge "scene devices" and found "No State (Do not update state for device)" will turning this on cause the device to act like a stateless "momentary switch" and merely trigger other actions?

**Comment by dJOS1475** [comment]
Update: setting "No State (Do not update state for device)" to "true" does indeed solve the problem and cause Scene's to work properly when the "device" is included in an Alexa Routine. 

Can I suggest that when converting HA Scenes to "devices" that "No State (Do not update state for device)" = "true" be the default setting or at least this info is included in the FAQ please?

Anyhoo, I love HA-bridge, it's great - keep up the awesome work.

**Comment by bwssytems** [comment]
I can add some more info into the FAQ on how No State works and where it makes sense.

**Comment by bwssytems** [comment]
include in the community information https://github.com/bwssytems/ha-bridge/wiki/Informational-Items-Collected-from-the-Community#q-how-to-create-vera-scenes
