### ISSUE TITLE
Any Alternative when Google/Alexa go to Philips login?

### ISSUE THREAD

**Issue by kmand** [bwssytems/ha-bridge#963]
I actually just want to run commands to my X10 firecracker. I think I have the ha-bridge set up properly but setup for either my Google Home Mini  or my Alexa Dot end up at the Philips login. I know this is an issue from the README.

Is there any workaround, or an alternate way to use the bridge.

I do have a Harmony Hub, but I don't see how that would help me.

**Comment by bwssytems** [comment]
Please refer to #764
