### ISSUE TITLE
Broadlink RM different after power outage.

### ISSUE THREAD

**Issue by tuicemen** [bwssytems/ha-bridge#964]
After a power outage my broadlink configured devices failed to work.
opening HA-Bridge to the broadlink page I noticed the router had assigned a new IP to the broadlink RM.
inorder to get my devices to work again I had to edit all devices with the new IP.
Can HA-Bridge be coded to assign the new IP to existing devices when the broadlink gets a new IP?
if one has more then 1 broadlink RM configured this could get confusing.

**Comment by bwssytems** [comment]
Please make sure when you add new devices to your network that you assign them a static IP from the router. Coding around is not the solution for this.

**Comment by tuicemen** [comment]
Some things you can't asign static IPs to.
The Broadlink RM is just one I have a couple cloud type cameras and Amazon Dots. If they grab the Broadlinks IP used with the bridge then I have to reconfigure.Every thing else hasa static IP

**Comment by tuicemen** [comment]
I managed to find the Mac address of the Broadlink which had eluded me for setting up a static IP for it.
Using the Econtrol app displays the mac address for each device.
Also you can use a tool like advanced port scanner which will display that as well as ports being used.

**Comment by bwssytems** [comment]
All modern routers have a dhcp reserve for a given mac address once one has been assigned. Should be just hitting a button next to the device that should say reserve or assign.

**Comment by tuicemen** [comment]
Mine here doesn't have that however once I was able to find my mac address of the broadlink I was able to manually add.
The router I have at my city place does display Wi-Fi devices connected but even that is hit and miss and rarely if ever shows all devices connected.
