### ISSUE TITLE
ISY 994i support?

### ISSUE THREAD

**Issue by bluemantwo** [bwssytems/ha-bridge#965]
I have been using your great software for over 2 years and made a small donation a year ago.  I really appreciate the work you have done!  The one item missing for me is support for the ISY 994i Insteon/Zwave automation hub.  There was a  piece of software by Barry Gordon for the ISY, but that no longer works for HA Bridge.    

I would be happy to be an alpha/beta tester for ISY support if that can be put into your roadmap.  

Thanks,
Blueman2

**Comment by bwssytems** [comment]
ISY is supported by OpenHAB, Please use that system and ha-bridge to connect.
