### ISSUE TITLE
Map HAbridge actions to Harmony remote buttons

### ISSUE THREAD

**Issue by coricidin12** [bwssytems/ha-bridge#969]
Thanks for this great software. Is there any way to get a Harmony hub to recognize HA bridge as an AV device rather than a home control device (Hue)? 

I have working HTTP commands setup in the HA bridge, but since the hub sees HA as a Hue, the only remote buttons I can map them to are the home control buttons. I want to be able map my HA actions to any button on the remote.

**Comment by bwssytems** [comment]
No, since ha-bridge emulates a Philips Hue it will be an HA device.

**Comment by bwssytems** [comment]
this is inlcuded in the community information https://github.com/bwssytems/ha-bridge/wiki/Informational-Items-Collected-from-the-Community#q-map-habridge-actions-to-harmony-remote-buttons
