### ISSUE TITLE
HTTPS self-signed certificate not working

### ISSUE THREAD

**Issue by dale3h** [bwssytems/ha-bridge#97]
I am having an issue trying to get the bridge to post commands to Home Assistant using HTTPS. I am using a self-signed certificate.

> Request Error, Pleae look in your habridge log: error {"type":6,"address":"/lights/1162386581","description":"Error on calling url to change device state","parameter":"/lights/1162386581state"}

**Comment by bwssytems** [comment]
Fearoffish may need to update his tutorial as there were some things he did to get certs working, take a look at one of the closed issues he commented on

**Comment by bwssytems** [comment]
Can you provide a debug log of what is happneing?

**Comment by dale3h** [comment]
I apologize for the delay in getting back to you, it's been a busy weeked. As per your request, here is the log file: http://pastebin.com/muUb8rii

**Comment by bwssytems** [comment]
I assume you are importing the cert into the Java Keystore?

**Comment by dale3h** [comment]
I honestly have no idea how to do that, but I'll research and try it. I'll keep you updated.

**Comment by bwssytems** [comment]
read through closed issue #93 and then you may want to contact the use "fearoffish" as he has done this.

**Comment by dale3h** [comment]
So I got it to work using a self-signed certificate, but doing so broke the Harmony authentication. I went back and figured out which cacerts that it was using by default and added my key to that.

All is good now!

I'll post instructions on how to do this shortly, in case others run into the same problem.

**Comment by dale3h** [comment]
To add your certificate to the default Java truststore on Windows, run this command in the command prompt:

Replace <Certificate> with the path to your SSL certificate (common extensions: `.pem`, `.crt`)
Replace <JavaHome> with the path to the Java installation directory (common install path (x64): `C:\Program Files\Java\jreW.X.Y_Z`)

`"<JavaHome>\bin\keytool.exe" -import -v -trustcacerts -alias selfsigned -file "<Certificate>" -keystore "<JavaHome>\lib\security\cacerts" -storepass changeit -keypass changeit -noprompt`

* **changeit** is the default password for the default truststore, so do not change this unless required
* **selfsigned** can be anything, it is just an alias for the certificate

@bwssytems It should be pretty simple to provide an embedded option for importing self-signed keys, if that is ever something you wanted to add. I believe the current truststore can be retrieved by calling `System.getProperty("javax.net.ssl.trustStore")`

**Comment by ih8gates** [comment]
Thanks. I'm not 100% sure how to apply this on my RaspberryPi. I can find the java keytool, but the machine I'm connecting to is a different machine, so I wouldn't have it's pem or crt, right?

Aside - LetsEncrypt certs have to be updated every 90 days, so an option that imports keys would be great.
