### ISSUE TITLE
device.db not updating

### ISSUE THREAD

**Issue by sdi2000** [bwssytems/ha-bridge#975]
Hi.

Not sure if it is helpful, but I have been chasing an issue for a couple of days where I couldn't add devices or update existing ones.

I have just spotted in syslog that there was an issue with a device.db.old file which was preventing the updates (I guess when it makes the update it may be momentarily making a temporary device.db.old file).

I renamed the file and it now seems to be fine. 

```
Jul  9 13:17:29 localhost java[10919]: 2018-07-09 13:17:29,367 [qtp9088149-93] ERROR com.bwssystems.HABridge.dao.DeviceRepository - Error writing the file: /home/pi/habridge/data/device.db message: /home/pi/habridge/data/device.db.old
Jul  9 13:17:29 localhost java[10919]: java.nio.file.FileAlreadyExistsException: /home/pi/habridge/data/device.db.old
```

**Comment by bwssytems** [comment]
It seems that there was an errant file left behind. Delete the .old file and you are good to go
