### ISSUE TITLE
Failed communicating with Harmony Hub

### ISSUE THREAD

**Issue by steveh2001** [bwssytems/ha-bridge#976]
Edit:
I’ve figured out to configure the harmony hub address (as found in the app, about, versions) in the bridge controls section and give it a name. I see nothing in the helper tabs and the logs show - Failed communicating with Harmony Hub.  The IP is dhcp and obviously I will set a reservation long term but I can’t see why it is failing now?

Hi

I am trying to achieve the following but really struggling to see how/if this is possible via ha-bridge.  I have read the readme and faq.

I have Alexa and harmony hub with an elite remote.  I can control harmony activities fine via Alexa but not devices.  The scenario is I want to be able to control my IR fan which is a device in harmony and I can control via the remote just fine but Alexa can only integrate with harmony activities natively.  I want to be able to say ‘Alexa, turn fan on’ with out impacting the activity ‘watch tv’ for example.

I have ha-bridge installed on docker and it is working fine but I just dont understand what I need to configure.  I have put the harmony IP address in but it doesn’t discover any Devices.  I can discover Philips hue now in my harmony app (I have no real Philips hue).  

Am I right in saying I need to form a HTTP POST command for the harmony to control the device buttons and make this a device in ha-bridge? If so I can’t find any examples on this.

Could anyone please help?

Thank you
Steve

**Comment by steveh2001** [comment]
Is there supposed to be a web hook in the harmony config under bridge control?

**Comment by bwssytems** [comment]
this is a dup of #945 

Restart your ha-bridge to connect to the harmony hub. Reinitialize does not accomplish this.

**Comment by steveh2001** [comment]
I have tried restarting the docker container - it still doesn’t work
