### ISSUE TITLE
Echo (2017) slow or do not respond, Dot & Show normal

### ISSUE THREAD

**Issue by heikoh81** [bwssytems/ha-bridge#977]
Hi,

although this is not directly HA Bridge related, I open this thread as there are many experienced Echo users on this Issue page.

For several weeks I have the Problem that my 2 Echos are very slow in responding, do not say Okay, forget timers or do not respond at all. Dots and Show are working normally.
In the meantime, I received replacement Echos from Amazon, however, after several minutes, they Show the same symtoms.

Does anyone else experience this, as well?

Heiko

**Comment by bwssytems** [comment]
What are your running the ha-bridge software on? Also, what types of calls from the ha-bridge are being made to what devices as if those are slow, the response is slow.

**Comment by heikoh81** [comment]
It seems that it had nothing to do with HA Bridge.
Those Echoes (2017) have died, got replacement (refurbished, look new though) during warranty.
Very strange, as all my Echos have died within first year. No problems with Echo Dots or Echo Show in the same WiFi.
