### ISSUE TITLE
ha-bridge will not discover on certain networks, even though the origional ha-bridge will

### ISSUE THREAD

**Issue by jimkernsjr** [bwssytems/ha-bridge#978]
Hi...
I hope you can help me out.  For clarity, I will refer to the BWS bride as the BWS bridge, and the HA bridge as the first HA-Bridge that this was based off of by Armzilla:  
https://github.com/armzilla/amazon-echo-ha-bridge

I have 2 locations I used HA-Bridge at.  
Location A has a full size origional Echo, and a dot v2.
Location B has a Echo dot v2.  It runs HA-Bridge on port 8081 because of a web server on port 80.  It runs version 0.2.1 of this old software .jar file because there is a bug in .4 where you cant discover devices if you change the port number.  I opened a case, but the author of this is MIA.

I've been wanting to switch to the BWS systems bridge for some time now, since it's maintained and has a whole lot of nice new features.  The other day, the HA-Bridge at location 2 threw a tantrum and refused to start, I don't remember why.  No problem, I wanted to switch to BWS bridge and this was my oppurtunity!  So I made a directory, started it up, followed the directions for configuring it, added 1 item, and did a discovery.  No joy with either the dot nor the web app from the computer.  (both worked fine with the old HA-bridge).  I decided ok, I'll set it up on a PI zero by itself and come back (it's not my primary residence).  I went home, set up a new PI zero at location A, installed BWS bridge + a test item, starts right up!  Happyness, so I configure the rest of the items, print me a nice case for the PI and take off for location B.  This is where my happyness ends.

I cannot get it to work.  In the meantime, the HA bridge started working again so at least I'm back in business there (go figure).  I cleaned out alexa, stopped the HA bridge, ran discovery and still nothing.  Here is what I tried:
-Changed the webserver port to 8081.  This makes the dot lock up half way through discovery, and also the web app fail.  So I went back to 80, because on this SBC, there is nothing else running.
-tried UPNP delay at 100,500,650,1000 as suggested in another post
-I made sure UPNP is not disabled on the router, but I'm not sure this is a point because HA bridge works fine.
-I dont have "use link button" turned on, but I did try your suggestion from the other post about using that.
-I tried the suggestion from the other post with discover, press reinitialize while it's discovering
-Changed webserver from all addresses (0.0.0.0) to specific address of the wifi interface(192.168.2.16)
-Wiped out the data directory, and started over.

At any time, I can start the HA-bridge service for the old one on the origional SBC and it rediscovers fine.  Leads me to believe it's not a problem with the dot nor the router.  But at the same time, the BWS bridge worked at location A???
[bridge logs-both.txt](https://github.com/bwssytems/ha-bridge/files/2216743/bridge.logs-both.txt)

I put the startup and discovery logs from HA bridge, and the logs and discovery request from both bridges, marked with banners.  

I've also copied the whole thing to my Ubuntu laptop, changed the IP's in the config file, started it and nothing.  removed the config file, restart, reconfigure, still nothing.

I've ran out of troubleshooting ideas.  Any help is appreciated.

**Comment by jimkernsjr** [comment]
Ok, I don't know if this means anything, but I made location A EXACTLY as location B, with just one Gen 2 Echo Dot.  It discovers fine.  This comes with a bit of a note as follows:

I took the time to see what bridge discovers what, and the results are interesting.  See table below:

_____________HA BRIDGE_________BWS BRIDGE
ECHO GEN 1______YES_______________YES *2
DOT GEN 2_______YES________________YES *2
SPOT____________NO________________YES *1
FIRE TV CUBE_____NO________________NO
FIRE TABLET 7____NO________________NO

*1 - SPOT discovers with BWS bridge, but only with 2 repeat attempts, one right after another
*2 - HA Bridge discovers this ALWAYS as a "Hue Light",  BWS bridge discovers it as a "Dimmable Light" if only 1 Echo is present on the network.  If 2 Echo's are present, it discovers as "Royal Phillips Electronics Smart Device".  Go Figure.

I was actually going to bet on DOT giving problems, but you see there is still differences.

All discovery was done with the web app.  With no Echo plugged in, of course nothing was detected because it's obvious it proxys out the discovery request to the local Echo to find devices.

My conclusion:
-The echo device still matters, but maybe not as much as we might think
-The BWS and HA bridge obviously have different discovery mechanisms.
-UPNP is not enabled on the router, and this should not matter nor is it a good practice to keep this protocol enabled.  The Echo requests are stateful.

I think my next step is WireShark. I will also take the Gen 2 Dot to location B over the weekend to see if there is discovery success, as multiple Echo's seem to make a difference with this bridge!  Maybe even Echo HW or FW levels within the device it'self...

I'd really like to see this BWS bridge working properly - it's such a slick piece of software and one heck of an upgrade.  But as it stands, I'm having trouble trusting it.  If I can provide anything else that may lead to a resolution, please feel free to ask.

**Comment by bwssytems** [comment]
So, I need some logfiles with upnp trace turned on so I can see what ip addresses are talking to each other.

**Comment by jimkernsjr** [comment]
Ok..Sorry I forgot to check back.  I'll give that a shot and let you know.
Best regards,

**Comment by pvint** [comment]
Not sure if it is related, but I have had trouble like this when the device running ha-bridge has more than one IP address in use. See https://github.com/bwssytems/ha-bridge/issues/980

**Comment by bwssytems** [comment]
Yes, that is in issue and will be resolved with the next release.

**Comment by bwssytems** [comment]
This will be fixed with #980
