### ISSUE TITLE
Alexa Discovers Duplicate Devices

### ISSUE THREAD

**Issue by Lorccan** [bwssytems/ha-bridge#979]
(Issue #806 refers to this. Although that's closed I am getting this with 5.2.1.)

I have 12 devices exposed to Alexa via ha-bridge. Using the Alexa web interface 'Forget All' seems to clear the list, but if I wait for a while the list starts to repopulate with a strange mix of duplicates. These are the variations I've got at the moment:

2 x 'Royal Philips Electronics smart device' + 1 x 'Dimmable light' (7 instances = 21 devices)
1 x 'Royal Philips Electronics smart device' + 1 x 'Dimmable light' (5 instances = 10 devices)

Stopping ha-bridge, forgetting all, then discover finds 0 devices (however many times I try), so I am pretty sure that the duplicates are coming from ha-bridge. I can't see any relationship between the device types and the type of duplicates I get.

In case it's relevant, the devices are a mix of LightwaveRF sockets (some on|off, others dimmable) exposed to ha-bridge via domoticz.

**Comment by Lorccan** [comment]
I am going to close this as it appears that the duplicates are coming from Amazon's side. (Shortly after I posted the above, devices started to come back - even when ha-bridge was down.)

Amazon's front line support was laughably bad - actually making stuff up on the fly - but I deleted the iPhone and iPad Alexa apps after deleting each device individually on the iPhone app (rather than using the 'Forget All' option) and this seems, finally, to have purged the cached data.

**Comment by Lorccan** [comment]
Now I am not sure if the problem is with Alexa or ha-bridge:

I removed all Bridge Devices from ha-bridge and restarted it. Alexa's list stayed empty. So far, so good.

I then added a single switch back into the Bridge Devices.

Initial discovery on Alexa finds the correct device as (type) 'Dimmable light'.  However, when I do a further discovery I get a duplicate as 'Royal Philips Electronics smart device'.

In case this was an issue with a previously discovered device and a cache of some kind, I created a new (dummy) switch in Domoticz and added this to habridge. As before, initial discovery got 'Dimmable Light' and a second one got the duplicate name as 'Royal Philips Electronics smart device'.

This makes me suspect that the problem is with ha-bridge after all.

Let me know what I can provide in the way of logs to help resolve this.  Thanks.

**Comment by bwssytems** [comment]
please turn on traceupnp and post your log. Thanks

**Comment by greendog99** [comment]
@Lorccan I've run into the same thing many times. I've found that using "Forget All" doesn't work right... the devices all re-appear. But if I forget each one individually (which is a pain, obviously) they stay forgotten. Not sure if that helps narrow it down as an Alexa vs. habridge problem, but it's something you can try.
