### ISSUE TITLE
Help! My echo won't detect the HA-Bridge

### ISSUE THREAD

**Issue by SA1656tw** [bwssytems/ha-bridge#982]
Hi! This is my first ever attempt at even using raspberry pi (3 B+)and ha-bridge so bear with me. I followed the tutorial and everything seemed to have worked out. (Localhost:80) However, I can't get my echo to detect. I tried forcing it to prefer ipv4, pressing link in the home page, and messing with the UPNP send delay. 

I'm still unsure about one thing. I do understand this is a bridge and the goal is to create "fake" bulbs to execute certain tasks. Am I supposed to connect the HA-Bridge to the echo or create fake bulbs for the echo to detect. As far as I know my philips bridge, which is currently off, allows echo to only see the individual bulbs.

Here are my logs:

`
08-02-2018 22:43:58.018 | INFO | HA Bridge startup sequence... | com.bwssystems.HABridge.HABridge
-- | -- | -- | --
08-02-2018 22:43:58.143 | INFO | reading from config file: /home/pi/ha-bridge/data/habridge.config | com.bwssystems.HABridge.BridgeSettings
08-02-2018 22:44:03.346 | INFO | HA Bridge (v5.2.1) initializing.... | com.bwssystems.HABridge.HABridge
08-02-2018 22:44:03.455 | INFO | StaticResourceHandler configured with folder = /public | spark.staticfiles.StaticFilesConfiguration
08-02-2018 22:44:03.562 | INFO | System control service started.... | com.bwssystems.HABridge.SystemControl
08-02-2018 22:44:03.853 | INFO | Initializing UDP response Socket... | com.bwssystems.HABridge.util.UDPDatagramSender
08-02-2018 22:44:03.895 | INFO | UDP response Socket initialized to: 50000 | com.bwssystems.HABridge.util.UDPDatagramSender
08-02-2018 22:44:03.912 | INFO | HTTP Home created. | com.bwssystems.HABridge.plugins.http.HTTPHome
08-02-2018 22:44:03.934 | INFO | Harmony Home created. No Harmony devices configured. | com.bwssystems.HABridge.plugins.harmony.HarmonyHome
08-02-2018 22:44:03.947 | INFO | Nest Home created. No Nest configured. | com.bwssystems.HABridge.plugins.NestBridge.NestHome
08-02-2018 22:44:03.953 | INFO | Hue passthru Home created. No Hue passtrhu systems configured. | com.bwssystems.HABridge.plugins.hue.HueHome
08-02-2018 22:44:03.962 | INFO | HAL Home created. No HAL devices configured. | com.bwssystems.HABridge.plugins.hal.HalHome
08-02-2018 22:44:03.968 | INFO | MQTT Home created. No MQTT Clients configured. | com.bwssystems.HABridge.plugins.mqtt.MQTTHome
08-02-2018 22:44:03.974 | INFO | HomeAssistant Home created. No HomeAssistants configured. | com.bwssystems.HABridge.plugins.hass.HassHome
08-02-2018 22:44:03.980 | INFO | HomeWizard Home created. No HomeWizard gateways configured. | com.bwssystems.HABridge.plugins.homewizard.HomeWizardHome
08-02-2018 22:44:03.985 | INFO | Command Home for system program execution created. | com.bwssystems.HABridge.plugins.exec.CommandHome
08-02-2018 22:44:03.995 | INFO | TCP Home created. | com.bwssystems.HABridge.plugins.tcp.TCPHome
08-02-2018 22:44:04.004 | INFO | UDP Home created. | com.bwssystems.HABridge.plugins.udp.UDPHome
08-02-2018 22:44:04.009 | INFO | Vera Home created. No Veras configured. | com.bwssystems.HABridge.plugins.vera.VeraHome
08-02-2018 22:44:04.014 | INFO | Fibaro Home created. No Fibaros configured. | com.bwssystems.HABridge.plugins.fibaro.FibaroHome
08-02-2018 22:44:04.023 | INFO | Domoticz Home created. No Domoticz devices configured. | com.bwssystems.HABridge.plugins.domoticz.DomoticzHome
08-02-2018 22:44:04.030 | INFO | Somfy Home created. No Somfys configured. | com.bwssystems.HABridge.plugins.somfy.SomfyHome
08-02-2018 22:44:04.053 | INFO | LifxDevice Home created. No LifxDevices configured. | com.bwssystems.HABridge.plugins.lifx.LifxHome
08-02-2018 22:44:04.063 | INFO | OpenHAB Home created. No OpenHABs configured. | com.bwssystems.HABridge.plugins.openhab.OpenHABHome
08-02-2018 22:44:04.071 | INFO | FHEM Home created. No FHEMs configured. | com.bwssystems.HABridge.plugins.fhem.FHEMHome
08-02-2018 22:44:04.111 | INFO | Broadlink Home created. No Broadlinks configured. | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
08-02-2018 22:44:04.135 | WARN | Error reading the file: data/device.db - Does not exist or is not readable. continuing... | com.bwssystems.HABridge.dao.DeviceRepository
08-02-2018 22:44:04.143 | WARN | Error reading the file: data/group.db - Does not exist or is not readable. continuing... | com.bwssystems.HABridge.dao.GroupRepository
08-02-2018 22:44:04.144 | INFO | HABridge device management service started.... | com.bwssystems.HABridge.devicemanagmeent.DeviceResource
08-02-2018 22:44:04.207 | INFO | == Spark has ignited ... | spark.embeddedserver.jetty.EmbeddedJettyServer
08-02-2018 22:44:04.217 | INFO | >> Listening on 0.0.0.0:80 | spark.embeddedserver.jetty.EmbeddedJettyServer
08-02-2018 22:44:04.301 | INFO | Hue emulator service started.... | com.bwssystems.HABridge.hue.HueMulator
08-02-2018 22:44:04.595 | INFO | Traceupnp: upnp config address: 192.168.1.11-useIface:false on web server: 0.0.0.0:80 | com.bwssystems.HABridge.HABridge
08-02-2018 22:44:04.599 | INFO | Description xml service started.... | com.bwssystems.HABridge.upnp.UpnpSettingsResource
08-02-2018 22:44:04.640 | INFO | UPNP Discovery Listener starting.... | com.bwssystems.HABridge.upnp.UpnpListener
08-02-2018 22:44:04.642 | INFO | Traceupnp: Interface: docker0 valid usable IP address: /172.17.0.1 | com.bwssystems.HABridge.upnp.UpnpListener
08-02-2018 22:44:04.644 | INFO | Traceupnp: Adding docker0 to our upnp join interface set. | com.bwssystems.HABridge.upnp.UpnpListener
08-02-2018 22:44:04.645 | INFO | Traceupnp: Interface: wlan0 valid usable IP address: /192.168.1.11 | com.bwssystems.HABridge.upnp.UpnpListener
08-02-2018 22:44:04.646 | INFO | Traceupnp: Adding wlan0 to our upnp join interface set. | com.bwssystems.HABridge.upnp.UpnpListener
08-02-2018 22:44:04.647 | INFO | Traceupnp: Interface: lo valid usable IP address: /127.0.0.1 | com.bwssystems.HABridge.upnp.UpnpListener
08-02-2018 22:44:04.647 | INFO | Traceupnp: Adding lo to our upnp join interface set. | com.bwssystems.HABridge.upnp.UpnpListener
08-02-2018 22:44:04.648 | INFO | UPNP Discovery Listener running and ready.... | com.bwssystems.HABridge.upnp.UpnpListener
08-02-2018 22:44:35.604 | INFO | Traceupnp: request of description.xml from: 192.168.1.11:80 filled in with address: 192.168.1.11:80 | com.bwssystems.HABridge.upnp.UpnpSettingsResource
08-02-2018 22:44:54.151 | INFO | Traceupnp: hue api user create requested for device type: test_ha_bridge#127.0.0.1 and username: 38efeb8985c041a0a77e8bf177cad65a | com.bwssystems.HABridge.hue.HueMulator
08-02-2018 22:45:02.080 | INFO | Traceupnp: SSDP M-SEARCH packet from 192.168.1.7:50000 | com.bwssystems.HABridge.upnp.UpnpListener
08-02-2018 22:45:04.083 | INFO | Traceupnp: send upnp discovery template 1 with response address: 192.168.1.11:80 to address: /192.168.1.7:50000 | com.bwssystems.HABridge.upnp.UpnpListener
08-02-2018 22:45:06.086 | INFO | Traceupnp: send upnp discovery template 2 with response address: 192.168.1.11:80 to address: /192.168.1.7:50000 | com.bwssystems.HABridge.upnp.UpnpListener
08-02-2018 22:45:08.088 | INFO | Traceupnp: send upnp discovery template 3 with response address: 192.168.1.11:80 to address: /192.168.1.7:50000 | com.bwssystems.HABridge.upnp.UpnpListener
08-02-2018 22:45:08.090 | INFO | Traceupnp: SSDP M-SEARCH packet from 192.168.1.7:50000 | com.bwssystems.HABridge.upnp.UpnpListener
08-02-2018 22:45:08.137 | INFO | Traceupnp: request of description.xml from: 192.168.1.7:80 filled in with address: 192.168.1.11:80 | com.bwssystems.HABridge.upnp.UpnpSettingsResource
08-02-2018 22:45:08.651 | INFO | Traceupnp: hue lights list requested by user: YP2oenn0PUaXNC5TerN4b77iCPfpyICph9QyiadB from address: 192.168.1.7 | com.bwssystems.HABridge.hue.HueMulator
08-02-2018 22:45:10.091 | INFO | Traceupnp: send upnp discovery template 1 with response address: 192.168.1.11:80 to address: /192.168.1.7:50000 | com.bwssystems.HABridge.upnp.UpnpListener
08-02-2018 22:45:12.094 | INFO | Traceupnp: send upnp discovery template 2 with response address: 192.168.1.11:80 to address: /192.168.1.7:50000 | com.bwssystems.HABridge.upnp.UpnpListener
08-02-2018 22:45:14.098 | INFO | Traceupnp: send upnp discovery template 3 with response address: 192.168.1.11:80 to address: /192.168.1.7:50000 | com.bwssystems.HABridge.upnp.UpnpListener
08-02-2018 22:45:14.131 | INFO | Traceupnp: request of description.xml from: 192.168.1.7:80 filled in with address: 192.168.1.11:80 | com.bwssystems.HABridge.upnp.UpnpSettingsResource
08-02-2018 22:45:14.472 | INFO | Traceupnp: hue lights list requested by user: YP2oenn0PUaXNC5TerN4b77iCPfpyICph9QyiadB from address: 192.168.1.7

`

**Comment by bwssytems** [comment]
So, there is a device in your log that seems to ask for the lights eventually and that is IP 192.168.1.7, is this your echo's IP?

**Comment by SA1656tw** [comment]
Yes.

**Comment by bwssytems** [comment]
The interesting thing is it has discovered the ha-bridge according to this log. What type of Echo are you using?

**Comment by SA1656tw** [comment]
It's a first generation echo
I also tried it with the dot, but to no avail.

**Comment by SA1656tw** [comment]
It just says "no devices found" after discovering via voice or the Alexa app.

**Comment by bwssytems** [comment]
Ohhh, I see you are running in a docker container.... you need to follow the docker instructions for forwarding the networks between your machine and docker look at these:

https://github.com/aptalca/docker-ha-bridge/issues/7

https://github.com/bwssytems/ha-bridge/issues/134

If there are any issues, post  a question here https://github.com/aptalca/docker-ha-bridge/issues

**Comment by SA1656tw** [comment]
Well I figured it out. I simply had no "fake bulbs" so echo was successfully requesting hue bulb data, but there weren't simply any bulbs to find. I didn't realize this until I started to look at other ha-bridge configurations. Sorry for wasting your time. I have added some bulbs and looks like Alexa is detecting them fine. Please close.

**Comment by SA1656tw** [comment]
Well I figured it out. I simply had no "fake bulbs" so echo was successfully requesting hue bulb data, but there weren't simply any bulbs to find. I didn't realize this until I started to look at other ha-bridge configurations. Sorry for wasting your time. I have added some bulbs and looks like Alexa is detecting them fine. Please close.
