### ISSUE TITLE
xbox-smartglass-core-python commands dont execute

### ISSUE THREAD

**Issue by Andee78** [bwssytems/ha-bridge#983]
Hi! First of all, great work!
I have problem executing commands to control my Xbox One. I have plenty of other devices running commands but the xbox-smartglass-core-python doesnt fire off. The commands works in the terminal.

Example: xbox-poweroff --all
This will turn off all connected devices, works great in terminal, but not in HA Bridge. No error message, just a message that everthing went well....but nothing happens. 

Anything you guys have been running into?

I have also tried putting those commands into python scripts and shell scripts, without any luck...

Cheers!

Running on Pi3 Raspbian Stretch lite

**Comment by bwssytems** [comment]
try putting cmd.exe before that so it will execute in a windows shell

**Comment by Andee78** [comment]
Tried that but without success... HA says its running, but its not.

**Comment by bwssytems** [comment]
So, does the script uses specific paths to what it is executing? Since ha-bridge kicks off a process, it is not in a shell with environment variables loaded.

**Comment by Andee78** [comment]
It uses load_entry_point to execute the commands...maybe thats why it wont work...? No specific paths... But I cant really see why it shouldnt work. I have also tried putting the command in both .sh and .py files and executed them from those script-files, but without any luck. I also rewritten them so I dont need any parameters any more, but no luck. Those scripts working from terminal but not in the HA.

**Comment by bwssytems** [comment]
You need to run this within a shell script with all of your environment variables set to run python.

**Comment by Andee78** [comment]
bwssystems, you rock! Just had to set the env var to my python sites-packages in a shell-script and call the original command from there!

**Comment by bwssytems** [comment]
There ya go, I should put a FAQ in for this as java execution environment spins off a clean thread...not like you have when you login to your machine...
