### ISSUE TITLE
Ha-bridge does not recognize Broadlink RM Pro

### ISSUE THREAD

**Issue by noberholtz** [bwssytems/ha-bridge#984]
I have been using the BWS successfully for a couple of years. I recently added some motorized shades. The use a RF remote so I invested in a Broadlink RM Pro and learned all of the buttons. I was successful in using their Echo Skills, but my ha-bridge running on a RPi3 does not recognize the RM Pro. I successfully initiated the Broadlink tab, but Refresh does not find the device. Any hints on how to troubleshoot. The logs just say discovering with the Refresh, but nothing is found. What port are in play in this interface?

**Comment by tuicemen** [comment]
I use a RPi3 B+ with one Broadlink RM Pro. If the pi doesn't have wi-fi configured and on, HA-Bridge doesn't see the Broadlink.
Also I found you need to setup IP reservations in your router for the Broadink as a reboot of the router usually will assign it a new IP which makes all Broadlink devices already configured in the Bridge stop responding.

**Comment by noberholtz** [comment]
Thank you for the info. My Rpi3 B is using wi-fi. Both the Pi and Broadlink have static IP addresses in the router. I will continue experimenting. I have turned on additional debug logging for com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome in the ha-bridge, but it simply reports that no broadlink is discovered. If anyone else has any idea's I am open to testing them.

**Comment by ahhanafy** [comment]
Hi everyone, I am having the same issue here, I have configured the HA Bridge 5.2.1 on Raspberry Pi3 B running on RASPBIAN STRETCH WITH DESKTOP Kernel version:4.14.
The setup went smooth, I have tried to add the broadlink devices but no luck so far, I have connected the Pi and the Broadlink on the same network, and the Broadlink is configured and remotes added, and when I checked the mark in the bridge control in front of Broadlink Support (now showing True) I got this new tab broadlink devices, but sadly it is empty as the ha bridge didn't discover any of the devices installed, anyone could support in this case pleas?

**Comment by ahhanafy** [comment]
DrMichael, thank you very much for your prompt response, however i guess this is not the case for me as I have doubled checked and found Broadlink and the Pi are on the same wifi network.

Below is the log inside Ha Bridge in case it could clarify the issue, I could see that there is some kind of a warring is repeating "Could not discover Broadlinks, Port in use, increasing by 11" but i don't know how to fix it or even is it the reason why it is not discovering the devices


Time | Level | Message | Component
-- | -- | -- | --
11-08-2018 15:16:39.576 | INFO | HA Bridge startup sequence... | com.bwssystems.HABridge.HABridge
11-08-2018 15:16:39.670 | INFO | reading from config file: /home/pi/habridge/data/habridge.config | com.bwssystems.HABridge.BridgeSettings
11-08-2018 15:16:40.376 | WARN | The upnp config address, 10.70.2.189, does not match any known IP's on this host. | com.bwssystems.HABridge.BridgeSettings
11-08-2018 15:16:45.353 | INFO | HA Bridge (v5.2.1) initializing.... | com.bwssystems.HABridge.HABridge
11-08-2018 15:16:45.407 | INFO | StaticResourceHandler configured with folder = /public | spark.staticfiles.StaticFilesConfiguration
11-08-2018 15:16:45.456 | INFO | System control service started.... | com.bwssystems.HABridge.SystemControl
11-08-2018 15:16:45.653 | INFO | Initializing UDP response Socket... | com.bwssystems.HABridge.util.UDPDatagramSender
11-08-2018 15:16:45.679 | INFO | UDP response Socket initialized to: 50000 | com.bwssystems.HABridge.util.UDPDatagramSender
11-08-2018 15:16:45.691 | INFO | HTTP Home created. | com.bwssystems.HABridge.plugins.http.HTTPHome
11-08-2018 15:16:45.712 | INFO | Harmony Home created. No Harmony devices configured. | com.bwssystems.HABridge.plugins.harmony.HarmonyHome
11-08-2018 15:16:45.721 | INFO | Nest Home created. No Nest configured. | com.bwssystems.HABridge.plugins.NestBridge.NestHome
11-08-2018 15:16:45.724 | INFO | Hue passthru Home created. No Hue passtrhu systems configured. | com.bwssystems.HABridge.plugins.hue.HueHome
11-08-2018 15:16:45.729 | INFO | HAL Home created. No HAL devices configured. | com.bwssystems.HABridge.plugins.hal.HalHome
11-08-2018 15:16:45.733 | INFO | MQTT Home created. No MQTT Clients configured. | com.bwssystems.HABridge.plugins.mqtt.MQTTHome
11-08-2018 15:16:45.737 | INFO | HomeAssistant Home created. No HomeAssistants configured. | com.bwssystems.HABridge.plugins.hass.HassHome
11-08-2018 15:16:45.740 | INFO | HomeWizard Home created. No HomeWizard gateways configured. | com.bwssystems.HABridge.plugins.homewizard.HomeWizardHome
11-08-2018 15:16:45.746 | INFO | Command Home for system program execution created. | com.bwssystems.HABridge.plugins.exec.CommandHome
11-08-2018 15:16:45.750 | INFO | TCP Home created. | com.bwssystems.HABridge.plugins.tcp.TCPHome
11-08-2018 15:16:45.757 | INFO | UDP Home created. | com.bwssystems.HABridge.plugins.udp.UDPHome
11-08-2018 15:16:45.780 | INFO | Vera Home created. No Veras configured. | com.bwssystems.HABridge.plugins.vera.VeraHome
11-08-2018 15:16:45.783 | INFO | Fibaro Home created. No Fibaros configured. | com.bwssystems.HABridge.plugins.fibaro.FibaroHome
11-08-2018 15:16:45.788 | INFO | Domoticz Home created. No Domoticz devices configured. | com.bwssystems.HABridge.plugins.domoticz.DomoticzHome
11-08-2018 15:16:45.791 | INFO | Somfy Home created. No Somfys configured. | com.bwssystems.HABridge.plugins.somfy.SomfyHome
11-08-2018 15:16:45.806 | INFO | LifxDevice Home created. No LifxDevices configured. | com.bwssystems.HABridge.plugins.lifx.LifxHome
11-08-2018 15:16:45.810 | INFO | OpenHAB Home created. No OpenHABs configured. | com.bwssystems.HABridge.plugins.openhab.OpenHABHome
11-08-2018 15:16:45.815 | INFO | FHEM Home created. No FHEMs configured. | com.bwssystems.HABridge.plugins.fhem.FHEMHome
11-08-2018 15:16:45.829 | INFO | Broadlink discover.... | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:16:45.854 | INFO | == Spark has ignited ... | spark.embeddedserver.jetty.EmbeddedJettyServer
11-08-2018 15:16:45.861 | INFO | >> Listening on 0.0.0.0:80 | spark.embeddedserver.jetty.EmbeddedJettyServer
11-08-2018 15:16:45.917 | WARN | Could not discover Broadlinks, Port in use, increasing by 11 | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:16:45.918 | INFO | Broadlink discover.... | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:16:45.949 | WARN | Could not discover Broadlinks, Port in use, increasing by 11 | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:16:45.949 | INFO | Broadlink discover.... | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:16:45.980 | WARN | Could not discover Broadlinks, Port in use, increasing by 11 | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:16:45.980 | INFO | Broadlink discover.... | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:16:46.009 | WARN | Could not discover Broadlinks, Port in use, increasing by 11 | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:16:46.010 | INFO | Broadlink discover.... | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:16:46.040 | WARN | Could not discover Broadlinks, Port in use, increasing by 11 | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:16:46.041 | INFO | Broadlink discover.... | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:16:46.070 | WARN | Could not discover Broadlinks, Port in use, increasing by 11 | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:16:46.071 | INFO | Broadlink discover.... | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:16:46.101 | WARN | Could not discover Broadlinks, Port in use, increasing by 11 | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:16:46.102 | INFO | Broadlink discover.... | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:16:46.136 | WARN | Could not discover Broadlinks, Port in use, increasing by 11 | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:16:46.136 | INFO | Broadlink discover.... | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:16:46.164 | WARN | Could not discover Broadlinks, Port in use, increasing by 11 | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:16:46.165 | INFO | Broadlink discover.... | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:16:46.194 | WARN | Could not discover Broadlinks, Port in use, increasing by 11 | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:16:46.195 | INFO | Broadlink discover.... | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:16:46.225 | WARN | Could not discover Broadlinks, Port in use, increasing by 11 | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:16:46.226 | WARN | Did not discover any Broadlinks. | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:16:46.226 | INFO | Broadlink Home created. | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:16:46.269 | WARN | Error reading the file: data/group.db - Does not exist or is not readable. continuing... | com.bwssystems.HABridge.dao.GroupRepository
11-08-2018 15:16:46.270 | INFO | HABridge device management service started.... | com.bwssystems.HABridge.devicemanagmeent.DeviceResource
11-08-2018 15:16:46.344 | INFO | Hue emulator service started.... | com.bwssystems.HABridge.hue.HueMulator
11-08-2018 15:16:46.406 | INFO | Description xml service started.... | com.bwssystems.HABridge.upnp.UpnpSettingsResource
11-08-2018 15:16:46.423 | INFO | UPNP Discovery Listener starting.... | com.bwssystems.HABridge.upnp.UpnpListener
11-08-2018 15:16:46.425 | INFO | UPNP Discovery Listener running and ready.... | com.bwssystems.HABridge.upnp.UpnpListener
11-08-2018 15:31:31.288 | INFO | Broadlink discover.... | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:31:31.347 | WARN | Could not discover Broadlinks, Port in use, increasing by 11 | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:31:31.347 | INFO | Broadlink discover.... | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:31:31.382 | WARN | Could not discover Broadlinks, Port in use, increasing by 11 | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:31:31.382 | INFO | Broadlink discover.... | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:31:31.412 | WARN | Could not discover Broadlinks, Port in use, increasing by 11 | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:31:31.412 | INFO | Broadlink discover.... | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:31:31.441 | WARN | Could not discover Broadlinks, Port in use, increasing by 11 | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:31:31.441 | INFO | Broadlink discover.... | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:31:31.471 | WARN | Could not discover Broadlinks, Port in use, increasing by 11 | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:31:31.472 | INFO | Broadlink discover.... | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:31:31.507 | WARN | Could not discover Broadlinks, Port in use, increasing by 11 | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:31:31.508 | INFO | Broadlink discover.... | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:31:31.540 | WARN | Could not discover Broadlinks, Port in use, increasing by 11 | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:31:31.541 | INFO | Broadlink discover.... | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:31:31.611 | WARN | Could not discover Broadlinks, Port in use, increasing by 11 | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:31:31.611 | INFO | Broadlink discover.... | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:31:31.643 | WARN | Could not discover Broadlinks, Port in use, increasing by 11 | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:31:31.643 | INFO | Broadlink discover.... | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:31:31.676 | WARN | Could not discover Broadlinks, Port in use, increasing by 11 | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:31:31.676 | INFO | Broadlink discover.... | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:31:31.709 | WARN | Could not discover Broadlinks, Port in use, increasing by 11 | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-08-2018 15:31:31.710 | WARN | Did not discover any Broadlinks. | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome

**Comment by Nachtfalke49** [comment]
Hello,

I have the same issue.


11-25-2018 00:34:49.416 | INFO | Broadlink discover.... | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
-- | -- | -- | --
11-25-2018 00:34:54.445 | WARN | Did not discover any Broadlinks. | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
11-25-2018 00:34:54.446 | INFO | Broadlink Home created. | com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome
