### ISSUE TITLE
Ha Bridge discovered by Alexa, devices not found

### ISSUE THREAD

**Issue by bamajo** [bwssytems/ha-bridge#987]
Hello.

My Ha Bridge server runs on my computer (192.168.0.177) and the Alexa is on 192.168.0.162.

I activated Trace uPnP calls in settings which shows that Alexa communicates with the bridge, however always returns with no devices found. I have an Alexa Dot V2.

I have added a HTTP device on the main page - I specified the name, device type, on/off itema (type, target item) - is this enough to be discovered?

I cannot understand why the device is not recognised by Alexa eventhough the Ha Bridge is definitely being communicated with.

Attached is the log.
[habridgelog.txt](https://github.com/bwssytems/ha-bridge/files/2321862/habridgelog.txt)

**Comment by bwssytems** [comment]
Sure does look like everything is good. Could you post your data/device.db please.

Thanks

**Comment by bamajo** [comment]
Thanks for your response. 

Attached is the device.db file, its in a zip folder because the .db filetype upload is not supported.
[device db.zip](https://github.com/bwssytems/ha-bridge/files/2324531/device.db.zip)

As far as I am aware this should contain one device called Bedside Light or similar.

**Comment by bamajo** [comment]
Hi bwssytems,

Thank you for your help with this. After several hours of messing with the ha bridge it just started to work - not sure why! But my devices have now been found by Alexa.

I appreciate you looking into this for me.

Not sure if it is just me, but Alexa can only find the ha bridge on my laptop when plugged into the LAN via ethernet as opposed to WiFi? This may just be my network conditions though.

**Comment by bwssytems** [comment]
Glad it's working now!
