### ISSUE TITLE
com.google.gson.JsonSyntaxException with custom Device.db

### ISSUE THREAD

**Issue by hpposch** [bwssytems/ha-bridge#988]
Hi, i have s script that generates my device.db
It worked now for many months, but suddenly it started to throw an exception when i restart ha-bridge.
I get the following error:
`
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
        at com.google.gson.Gson.fromJson(Gson.java:891)
        at com.google.gson.Gson.fromJson(Gson.java:844)
        at com.google.gson.Gson.fromJson(Gson.java:793)
        at com.google.gson.Gson.fromJson(Gson.java:765)
        at com.bwssystems.HABridge.dao.DeviceRepository._loadRepository(DeviceRepository.java:70)
        at com.bwssystems.HABridge.dao.DeviceRepository.<init>(DeviceRepository.java:57)
        at com.bwssystems.HABridge.devicemanagmeent.DeviceResource.<init>(DeviceResource.java:50)
        at com.bwssystems.HABridge.HABridge.main(HABridge.java:81)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:351)
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:70)
        at com.google.gson.Gson.fromJson(Gson.java:879)
        ... 7 more
`

My Device.db looks like this:
`
[{"id":"1","uniqueid":"b1158168-bcd4-4a22-b9e7-3ede133408e1","name":"Esszimmer Kochen","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/0AD260B1-02EC-3567-FFFFEEE000D81BB1/1\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"2","uniqueid":"778a4be1-a67e-4b44-950c-06e840e7b91f","name":"Esszimmer Essen","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/0AD260B1-02EC-3567-FFFFEEE000D81BB1/2\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"3","uniqueid":"58caaa41-93c3-43d3-8b40-2d2aa8c1e48a","name":"Esszimmer Fernsehen","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/0AD260B1-02EC-3567-FFFFEEE000D81BB1/3\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"4","uniqueid":"32d8d7c8-4e45-4930-b1a3-0dd599b75e14","name":"Esszimmer Chillen","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/0AD260B1-02EC-3567-FFFFEEE000D81BB1/4\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"5","uniqueid":"72e5eb73-3609-4838-a277-570352b95380","name":"Esszimmer Romantik","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/0AD260B1-02EC-3567-FFFFEEE000D81BB1/5\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"6","uniqueid":"809b4fd6-1245-4971-b572-418d12917fe6","name":"Esszimmer Reinigen","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/0AD260B1-02EC-3567-FFFFEEE000D81BB1/6\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"7","uniqueid":"7423cc9a-1127-45a3-a2cf-8511cfb615ee","name":"Esszimmer Nachtlicht","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/0AD260B1-02EC-3567-FFFFEEE000D81BB1/7\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"8","uniqueid":"a1c51b3e-60d1-465d-96d6-38ac51aac743","name":"Esszimmer Bewegen","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/0AD260B1-02EC-3567-FFFFEEE000D81BB1/8\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"9","uniqueid":"8556ab4e-988d-4108-922e-1aa37a448712","name":"Esszimmer Alles","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/0AD260B1-02EC-3567-FFFFEEE000D81BB1/9\",\"type\":\"httpDevice\"}","offUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/0AD260B1-02EC-3567-FFFFEEE000D81BB1/0\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"10","uniqueid":"d8fa4006-a68c-44cc-bd2f-9e2238461255","name":"Esszimmer nächste Szene","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/0AD260B1-02EC-3567-FFFFEEE000D81BB1/plus\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"11","uniqueid":"f2d4eb65-a6a1-4f01-a652-ed8458165c70","name":"Esszimmer vorherige Szene","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/0AD260B1-02EC-3567-FFFFEEE000D81BB1/minus\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"12","uniqueid":"2d493029-f071-4f6e-b58f-9cab4956775e","name":"Esszimmer nächste Stimmung","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/0AD260B1-02EC-3567-FFFFEEE000D81BB1/plus\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"13","uniqueid":"341f6332-8a32-4954-aff0-32a1b444387d","name":"Esszimmer vorherige Stimmung","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/0AD260B1-02EC-3567-FFFFEEE000D81BB1/minus\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"14","uniqueid":"33e4ccb9-4bce-4ed3-b1eb-0dd3c5a7367f","name":"Vorraum EG Anziehen","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/35109B1A-3FBF-11E3-91A9DB74549C0715/1\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"15","uniqueid":"24cc5b43-2aa6-4476-92af-bc694dd5b8d7","name":"Vorraum EG Nachtlicht","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/35109B1A-3FBF-11E3-91A9DB74549C0715/7\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"16","uniqueid":"15fdbcab-3903-4f92-9c83-725584c90497","name":"Vorraum EG Bewegen","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/35109B1A-3FBF-11E3-91A9DB74549C0715/8\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"17","uniqueid":"02a5e0d8-cf61-4c10-bbc3-1dcd10146e3a","name":"Vorraum EG Alles","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/35109B1A-3FBF-11E3-91A9DB74549C0715/9\",\"type\":\"httpDevice\"}","offUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/35109B1A-3FBF-11E3-91A9DB74549C0715/0\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"18","uniqueid":"f4563889-2abb-4724-82fe-93bd7ee7315e","name":"Vorraum EG nächste Szene","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/35109B1A-3FBF-11E3-91A9DB74549C0715/plus\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"19","uniqueid":"a1c8f4eb-e916-48eb-9e08-acdd03465510","name":"Vorraum EG vorherige Szene","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/35109B1A-3FBF-11E3-91A9DB74549C0715/minus\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"20","uniqueid":"39059bb8-606c-4bb6-937e-f1ed92c10dad","name":"Vorraum EG nächste Stimmung","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/35109B1A-3FBF-11E3-91A9DB74549C0715/plus\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"21","uniqueid":"4862074f-e731-4828-9921-c138386fc64a","name":"Vorraum EG vorherige Stimmung","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/35109B1A-3FBF-11E3-91A9DB74549C0715/minus\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"22","uniqueid":"f8e5cad9-2e04-4e9c-bd46-8fbb680150bc","name":"Büro Arbeiten MW und/oder HP","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/0A835D4C-0098-1331-FFFFEEE000D81BB1/1\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"23","uniqueid":"3648ee49-8cb5-4614-8578-94060ac6d218","name":"Büro Arbeiten Alle","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/0A835D4C-0098-1331-FFFFEEE000D81BB1/2\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"24","uniqueid":"687778e0-e43d-4476-aea0-a2e31a70dfef","name":"Büro Nachtlicht","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/0A835D4C-0098-1331-FFFFEEE000D81BB1/7\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"25","uniqueid":"336903d8-3b39-4a86-9e76-74c2a0c8815a","name":"Büro Bewegen","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/0A835D4C-0098-1331-FFFFEEE000D81BB1/8\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"26","uniqueid":"ffb4aa82-b66b-4675-b3c3-cdd1d39cf49c","name":"Büro Alles","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/0A835D4C-0098-1331-FFFFEEE000D81BB1/9\",\"type\":\"httpDevice\"}","offUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/0A835D4C-0098-1331-FFFFEEE000D81BB1/0\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"27","uniqueid":"5ac926e1-791e-4399-b53e-861748eb9ad4","name":"Büro nächste Szene","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/0A835D4C-0098-1331-FFFFEEE000D81BB1/plus\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"28","uniqueid":"67426526-6512-4913-a213-d8e7ab891f14","name":"Büro vorherige Szene","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/0A835D4C-0098-1331-FFFFEEE000D81BB1/minus\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"29","uniqueid":"b03f7dbc-1809-4fc1-85d4-3df098a9aa88","name":"Büro nächste Stimmung","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/0A835D4C-0098-1331-FFFFEEE000D81BB1/plus\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"30","uniqueid":"4a856e20-daf1-4267-994e-c70d0fdf9dc6","name":"Büro vorherige Stimmung","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/0A835D4C-0098-1331-FFFFEEE000D81BB1/minus\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"31","uniqueid":"bc454ea0-122a-40b1-b715-594e8244cb20","name":"Küche Kochen","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/F3531C38-3FC7-11E3-BFA3DB74549C0715/1\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"32","uniqueid":"b2df1b32-9c88-41a5-ab55-92f70ad5f70a","name":"Küche Essen","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/F3531C38-3FC7-11E3-BFA3DB74549C0715/2\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"33","uniqueid":"622b6c25-9714-4059-8132-5807658a1f28","name":"Küche Fernsehen","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/F3531C38-3FC7-11E3-BFA3DB74549C0715/3\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"34","uniqueid":"08e20687-8b7e-4cdf-901d-23ce325b756b","name":"Küche Chillen","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/F3531C38-3FC7-11E3-BFA3DB74549C0715/4\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"35","uniqueid":"b8fc2aac-a802-4efa-bd2b-cd98db940166","name":"Küche Romantik","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/F3531C38-3FC7-11E3-BFA3DB74549C0715/5\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"36","uniqueid":"de68a7ef-d37f-4754-88d4-0e2422e7b411","name":"Küche Reinigen","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/F3531C38-3FC7-11E3-BFA3DB74549C0715/6\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"37","uniqueid":"3d2753d5-1a91-40d2-82b1-bb660b535030","name":"Küche Nachtlicht","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/F3531C38-3FC7-11E3-BFA3DB74549C0715/7\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"38","uniqueid":"51bca947-4bda-48ac-bc8b-978ba4dca911","name":"Küche Bewegen","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/F3531C38-3FC7-11E3-BFA3DB74549C0715/8\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"39","uniqueid":"7d8985e6-646d-49b8-b23c-104ca31addce","name":"Küche Alles","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/F3531C38-3FC7-11E3-BFA3DB74549C0715/9\",\"type\":\"httpDevice\"}","offUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/F3531C38-3FC7-11E3-BFA3DB74549C0715/0\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"40","uniqueid":"1a0d8045-4f21-4841-ba32-ebb41ec51b66","name":"Küche nächste Szene","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/F3531C38-3FC7-11E3-BFA3DB74549C0715/plus\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"41","uniqueid":"0f21dcd4-0e03-4575-ad39-659259643aff","name":"Küche vorherige Szene","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/F3531C38-3FC7-11E3-BFA3DB74549C0715/minus\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"42","uniqueid":"1301d506-4e69-4c7a-ac9c-cb51a9185bc8","name":"Küche nächste Stimmung","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/F3531C38-3FC7-11E3-BFA3DB74549C0715/plus\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"43","uniqueid":"39234e80-0ae0-464d-92c5-dc84983e0bd5","name":"Küche vorherige Stimmung","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/F3531C38-3FC7-11E3-BFA3DB74549C0715/minus\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"44","uniqueid":"d86105b2-eb0f-4c3f-bbd2-ebe66aa1ee10","name":"Zentral Bewegung","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/11F61273-01AA-8ADC-FFFFFBC11EB205D5/1\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"45","uniqueid":"28fe87a6-a7b6-4af4-adf4-6ea3f0ef7d72","name":"Zentral Alles","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/11F61273-01AA-8ADC-FFFFFBC11EB205D5/9\",\"type\":\"httpDevice\"}","offUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/11F61273-01AA-8ADC-FFFFFBC11EB205D5/0\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"46","uniqueid":"514cae1e-b6e1-4a95-abb1-a631556ea733","name":"Zentral nächste Szene","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/11F61273-01AA-8ADC-FFFFFBC11EB205D5/plus\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"47","uniqueid":"62400709-c1e4-45f3-9220-cf5b3c327529","name":"Zentral vorherige Szene","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/11F61273-01AA-8ADC-FFFFFBC11EB205D5/minus\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"48","uniqueid":"b5fe7ace-cb87-4e6e-a13c-f2bc4f53a15f","name":"Zentral nächste Stimmung","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/11F61273-01AA-8ADC-FFFFFBC11EB205D5/plus\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"49","uniqueid":"c93ea9fa-52a0-4804-a3d9-2342a6b745a2","name":"Zentral vorherige Stimmung","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/11F61273-01AA-8ADC-FFFFFBC11EB205D5/minus\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"50","uniqueid":"416e7ccc-2842-41ec-8db6-65b3d98a9d01","name":"Wohnzimmer Kochen","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/DB0661A9-3FC6-11E3-821ADB74549C0715/1\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"51","uniqueid":"6b7d7cef-f8d6-46c2-b824-8e72ae26dbde","name":"Wohnzimmer Essen","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/DB0661A9-3FC6-11E3-821ADB74549C0715/2\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"52","uniqueid":"3c33273c-c366-4bda-9514-635e24218522","name":"Wohnzimmer Fernsehen","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/DB0661A9-3FC6-11E3-821ADB74549C0715/3\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"53","uniqueid":"76e063c8-dc35-46c6-aff6-4dede2207b30","name":"Wohnzimmer Chillen","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/DB0661A9-3FC6-11E3-821ADB74549C0715/4\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"54","uniqueid":"cef209b1-dc4b-4b7b-82ea-bf5c168738f9","name":"Wohnzimmer Romantik","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/DB0661A9-3FC6-11E3-821ADB74549C0715/5\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"55","uniqueid":"4ca472de-7b66-44e4-92d6-2479aaeeee83","name":"Wohnzimmer Reinigen","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/DB0661A9-3FC6-11E3-821ADB74549C0715/6\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"56","uniqueid":"d374329a-d52f-406d-8ebd-eaabbf854a26","name":"Wohnzimmer Nachtlicht","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/DB0661A9-3FC6-11E3-821ADB74549C0715/7\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"57","uniqueid":"3f0fdfd2-4869-4cc2-bbe1-6dc5af79d6ac","name":"Wohnzimmer Bewegen","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/DB0661A9-3FC6-11E3-821ADB74549C0715/8\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"58","uniqueid":"85c48cc4-6a25-4aa1-a320-053d6a6c565f","name":"Wohnzimmer Alles","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/DB0661A9-3FC6-11E3-821ADB74549C0715/9\",\"type\":\"httpDevice\"}","offUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/DB0661A9-3FC6-11E3-821ADB74549C0715/0\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"59","uniqueid":"393f7d28-73fd-4cd3-9b91-67bdf4af4003","name":"Wohnzimmer nächste Szene","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/DB0661A9-3FC6-11E3-821ADB74549C0715/plus\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"60","uniqueid":"eaef2219-0988-47ba-8218-3e18767e0e59","name":"Wohnzimmer vorherige Szene","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/DB0661A9-3FC6-11E3-821ADB74549C0715/minus\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"61","uniqueid":"9c2f6fb6-a80c-4375-93e6-39f53a2bb623","name":"Wohnzimmer nächste Stimmung","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/DB0661A9-3FC6-11E3-821ADB74549C0715/plus\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}},{"id":"62","uniqueid":"06cba5d6-777a-4bbe-8d6c-032bc8c4d2e3","name":"Wohnzimmer vorherige Stimmung","mapType":"httpDevice","deviceType":"switch","targetDevice":"Encapsulated","onUrl":"{\"item\":\"http://admin:admin@192.168.1.77:80/dev/sps/io/DB0661A9-3FC6-11E3-821ADB74549C0715/minus\",\"type\":\"httpDevice\"}","inactive":false,"noState":false,"offState":false,"deviceState":{}}]
`

**Comment by bwssytems** [comment]
Cursory look and everything seems to be in place with a review of the code. I just loaded your file in with 5.2.1 and it works just fine.
