### ISSUE TITLE
Alexa Room Support

### ISSUE THREAD

**Issue by skavan** [bwssytems/ha-bridge#989]
I have searched and searched, and still can't understand how to (or if its even possible to) leverage Alexa's Room support.

Use case:
Echo Dot in Living Room: 
Alexa, Turn on the Table Lamps --> Turns on the Living Room Table Lamps.
Alexa, Turn on the Main Lights ---> Turns on the Living Room Main Lights
Alexa, Turn on the Lights ---> Turns on All Living Room Lights.
Bonus Points:
Alexa, Movie Time ---> Turns off the Living Room Main Lights. Dims Living Room Table Lamps to 50%.
Alexa, Goodnight ---> Turns off everything in the Living Room.

Echo Dot in Kitchen:
As above, but replace Living Room with Kitchen.

I can handle all the downstream macros, if I can at the very least, identify the calling Alexa.

Is there any way to do this - or approximate it with ha-bridge?

s.

**Comment by bwssytems** [comment]
The ha-bridge does not support the hue scenes which would work for the rooms. Alexa does have a grouping function to group devices it knows about and map it to a name. The other item is to create an ha-bridge device that turns on the groups of lights using the multi command feature.

**Comment by skavan** [comment]
Don't really need the Hue Scenes. as you note, I can handle the groups of lights in ha-bridge or even further downstream using, in my case, node-red.
The real trick is getting an ID/IP Address from Amazon that let's us know WHICH alexa made the call.
Unless there's another approach...

**Comment by bwssytems** [comment]
Ahh, that is the dig and that is in issue #386 whcih is an issue with the Amazon implementation. Basically, any one for the echos may make the request, not the one that is the closest... The ha-bridge does have the ability to fire a device based on an IP, but since that may not  happen from an echo, it does not work.

**Comment by bwssytems** [comment]
included in community information https://github.com/bwssytems/ha-bridge/wiki/Informational-Items-Collected-from-the-Community#q-alexa-room-support
