### ISSUE TITLE
Domoticz discovery fails when using https without any credentials

### ISSUE THREAD

**Issue by necoras** [bwssytems/ha-bridge#992]
When trying to setup Domoticz devices I put in my ip address (in my instance its the same as the ha-bridge server) and port 443. However, no devices populate on the Domoticz tab. Checking the logs it becomes clear that the generated url is "http://[ipaddress]:443/[Restofurl]. 

The problem is that the url should be "https://" if the specified port is 443. 

I'm digging through the code to figure out how to convince ha-bridge to use https, but it seems that it should be smart enough to detect that port and switch to "secure" mode.

**Comment by bwssytems** [comment]
Yep, that is the issue. I will need to add the Use SSL checkbox and implementation to make it use https
