### ISSUE TITLE
state does not get updated and action not performed

### ISSUE THREAD

**Issue by 99ttz** [bwssytems/ha-bridge#995]
hi,

i'm trying to control the devices configured in habridge via api calls from within a bash script. Unfortunately, even if the command appears to execute successful, the state within habridge does not get updated and the action does not get performed.

below the curl commands to check current status of device and curl command to update it's state.

can you please take a look? i'm running the latest version 5.20.

best
T

curl -X GET http://192.168.1.28/api/I29e75ef174e54e55a29c887b80ce96d8/lights

{"1":{"state":{"on":false,"bri":0,"alert":"none","reachable":true},"type":"Dimmable light","name":"cooling","modelid":"LWB007","manufacturername":"Philips","uniqueid":"00:17:88:5E:D3:01-01","swversion":"66012040"}}

curl -X POST -d "{"on": true}" http://192.168.1.28/api/I29e75ef174e54e55a29c887b80ce96d8/lights/1/state

[{"success":{"username":"29e75ef174e54e55a29c887b80ce96d8"}}]

curl -X GET http://192.168.1.28/api/I29e75ef174e54e55a29c887b80ce96d8/lights

{"1":{"state":{"on":false,"bri":0,"alert":"none","reachable":true},"type":"Dimmable light","name":"cooling","modelid":"LWB007","manufacturername":"Philips","uniqueid":"00:17:88:5E:D3:01-01","swversion":"66012040"}}

**Comment by bwssytems** [comment]
If you could turn on debug for com.bwssystems.habridge.HueMulator and  post your log that would help.

**Comment by thmang82** [comment]
I have the same issue in the latest version.
Somehow API commands are not executed any more.
Response contains only "success" with "username" in it, instead the confirmation about the execution
