### ISSUE TITLE
Too slow for Echo

### ISSUE THREAD

**Issue by cnissmo** [bwssytems/ha-bridge#997]
I am using ha-bridge to control my Yamaha Receiver via Echo voice commands. It works great, but Echo answers with „The device is not responding....“ if I use several commands in a row. It still works, but the response is annoying :-/

**Comment by bwssytems** [comment]
Yep, the echo likes to have immediate responses. If the system that is being called from ha-bridge does not respond in the time the echo has, this will happen.

**Comment by cnissmo** [comment]
Is there any possibility to send a response to Echo proactively? I guess it would make the response pointless, but it would circumvent the annoying response by Echo.

**Comment by bwssytems** [comment]
The fire and forget method has been talked about before here. It would be a little overhaul on the communication side to implement the threading and a queue.

**Comment by cnissmo** [comment]
Okay, thanks. You have my vote for the change ;-)

PS: If placed in a group (within Alexa) with a device that responds in time, Echo replies with OK.
