### ISSUE TITLE
habridge sends "on" on dim event when device.isOnFirstDim() is false

### ISSUE THREAD

**Issue by pvint** [bwssytems/ha-bridge#998]
When I send a dim event and the device in question is off, it seems that regardless of the settings from the web interface it sends an "on" event before it sends the dim event.

In my use case I am sending on/off/dim to an external script, and everything works perfectly, except that when habridge believes that the device is off it sends an "on" before the "dim". 

Here is the current settings for an example device:

```
{"id":"1","uniqueid":"00:17:88:5E:D3:01-01","name":"Red Table light","offUrl":"[{\"item\":\"/root/hawrap.sh -c 7 -l 0\",\"type\":\"cmdDevice\"}]","dimUrl":"[{\"item\":\"/root/hawrap.sh -c 7 -l ${intensity.percent}\",\"type\":\"cmdDevice\"}]","onUrl":"[{\"item\":\"/root/hawrap.sh -c 7 -l 50\",\"type\":\"cmdDevice\"}]","inactive":false,"noState":true,"offState":true,"onFirstDim":false}
```

I've been looking at the code and have found a workaround for my case (NOTE: This is not a fix, just a workaround for my use case!)

```
root@foxtrot:/usr/local/src/ha-bridge # git diff src/main/java/com/bwssystems/HABridge/hue/HueMulator.java
diff --git a/src/main/java/com/bwssystems/HABridge/hue/HueMulator.java b/src/main/java/com/bwssystems/HABridge/hue/HueMulator.java
index c106b2f..a1d69fe 100644
--- a/src/main/java/com/bwssystems/HABridge/hue/HueMulator.java
+++ b/src/main/java/com/bwssystems/HABridge/hue/HueMulator.java
@@ -1202,7 +1202,7 @@ public class HueMulator {
                        }
                }
                
-               if(isOnRequest) {
+               if(isOnRequest && !isDimRequest) {
                        log.debug("Calling on-off as requested.");
                        if (theStateChanges.isOn()) {
                                url = device.getOnUrl();
```

I know that it should be handled using `device.isOnFirstDim()`, but I tried for a bit and I'm out of time... I need it to work and will be sailing out of internet range shortly. :)

I verified my issue on commits from approximately June until the latest, and I don't believe that this issue was present in the spring (say, around March). I would test more to confirm, but I simply do not have time at the moment.

I can likely look into this more in a week or two, but I wanted to document what I know about this.

Again - my little code change up there makes it work for me, but I know it's not the real fix!

**Comment by bwssytems** [comment]
The behaviour is send on always when dim is present when the device was previously off. If the flag is on, it will send on only the first time it detects the off.

This may not be what you need and I would have to add another flag.

**Comment by bwssytems** [comment]
I believe this is an issue identified in #923. I will be adding an enhancement for a flag to not do the on when dim is present.

Closing to #923
